### ISSUE TITLE
SSECustomerKey using AES-265 bit only support ASCII characters

### ISSUE THREAD

**Issue by pat-humphreys** [aws/aws-sdk-java#1000]
It appears that SSECustomerKey only supports ASCII characters in the Base64 encoded string. I cant find a reference to this limitation in the docs. Is this expected behaviour ?

The Base64 encoded key (with non ASCII chars) 
`jyx4Yz51nFRDLB4TrhdEKKw+PTHybUlrKgAVQeniV6o=`
Throws the following error in aws-java-sdk-core:**1.11.11**

```
Input is expected to be encoded in multiple of 4 bytes but found: 43: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Input is expected to be encoded in multiple of 4 bytes but found: 43
at com.amazonaws.util.Base64Codec.decode(Base64Codec.java:198)
at com.amazonaws.util.Base64.decode(Base64.java:67)
at com.amazonaws.services.s3.AmazonS3Client.populateSSE_C(AmazonS3Client.java:3447)
at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1137)
```

**Comment by kiiadi** [comment]
Using your example, I can call `Base64.decode("jyx4Yz51nFRDLB4TrhdEKKw+PTHybUlrKgAVQeniV6o=")` Can you provide a full example? I used 1.11.11

**Comment by pat-humphreys** [comment]
I wrote a sample app to verify it in Lambda. It turn out it was my code.

**Comment by kiiadi** [comment]
no problem
