### ISSUE TITLE
Latest AWS JAVA SDK 1.11.86 throws NoSuchMethodError on Jackson Databind AnnotatedMethod.getParameterType(int)

### ISSUE THREAD

**Issue by sgatade** [aws/aws-sdk-java#1002]
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-bom</artifactId>
    <version>1.11.86</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

The above Maven dependency still imports Jackson Databind 2.6.6 (which does not have the getParameterType(I) method. 

If I look at the AWS JAVA SDK 1.11.86 POM, line # 137 states Property <jackson.version>2.6.6</jackson.version>, while the getParameterType(int) was added in or after Jackson 2.7.0.

Can someone fix this Jackson dependency please?

Regards,

SG

**Comment by shorea** [comment]
Is the NoSuchMethod errror thrown from within the SDK or from your application code? 2.6.6 is our minimum, consumers are free to override the version in their own POM if they need newer features of Jackson.

**Comment by kiiadi** [comment]
Haven't had a response in a while, not clear if this is still a problem - please re-open if this is still a problem.
