### ISSUE TITLE
Decorating classes whose constructors were deprecated in 1.11.84

### ISSUE THREAD

**Issue by evnm** [aws/aws-sdk-java#1003]
In my company's codebase, I maintain a few subclasses of client classes for AWS services that decorate the base client class with additional functionality. For instance, I have a `ManagedTransferManager` which ensures graceful shutdown of my application by tying a `TransferManager`'s lifecycle to that of a Jetty server.

Since 1.11.84, my classes that extend AWS clients like `TransferManager` rely on deprecated constructors. There isn't an easy way to decorate such classes when using the builder pattern.

Has this kind of use case been thought of as supported? How would you advise me to proceed?

**Comment by kiiadi** [comment]
Thank you for raising this, apologies that the deprecation warnings have cause an issue. We're trying to move away from mutability and trying to ensure that both clients and high-level features like `TransferManager` are correctly configured (hence the motivation behind the deprecation).

We could potentially open  up a `protected` constructor to `TransferManager` that takes an instance of a `TransferManagerBuilder` which is used to pass the configuration that `TransferManager` requires. Would that solve your use-case?

**Comment by evnm** [comment]
Thanks for the quick reply!

I'm fully onboard with the move towards immutability. Your `protected` construction idea sounds great. That would solve my immediate use case with `TransferManager` and could be used for other client classes.

**Comment by kiiadi** [comment]
Sorry about the delay coming back on this - the protected constructor was added several releases ago - https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L332

**Comment by evnm** [comment]
Thank you!
