### ISSUE TITLE
S3 - Tagging S3 Objects using the TransferManager uploadDirectory is not possible with the current SDK.

### ISSUE THREAD

**Issue by erbrito** [aws/aws-sdk-java#1005]
Tagging S3 Objects using the TransferManager uploadDirectory is not possible with the current SDK. It would very nice and simple to implement a TransferManager with Tagging functionality with a ObjectTaggingProvider. In the same way it is implemented the ObjectMetadataProvider.

https://aws.amazon.com/blogs/developer/amazon-s3-transfermanager-batched-file-uploads/

http://docs.aws.amazon.com/AmazonS3/latest/dev/tagging-manage-javasdk.html

Please let me know how can I contribute to add this functionality and add a pull request with this solution.

**Comment by dagnir** [comment]
Hi @erbrito, yep you're right, it's not currently possible. Your suggestion of using providing a callback similar to `ObjectMetadataProvider` is probably the right way to go. We love pull requests so if you're interested in implementing this functionality and submitting one for it, i'd be happy to take a look. Here's the bit of code where the `TransferManager` makes a call back to the `ObjectMetadataProvider`: https://github.com/aws/aws-sdk-java/blob/1c7134c77edd2f71e5cdc9f5774d4534bcb07365/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L1451-L1479. We would probably just want to do the same thing with a similar call back for tags.

**Comment by erbrito** [comment]
I created the pull request #1011 Please let me know if there are some procedures or guidelines to follow.

**Comment by erbrito** [comment]
Thanks @dagnir to add this feature.  I just verified that is merged the pull request on the master branch. 
Do you know in which release will be integrated 1.11.90? 
and when it will released?

**Comment by dagnir** [comment]
Hey @erbrito I believe we have a release today.

**Comment by dagnir** [comment]
Looks like we're not having a release today after all. I'll update when I get another date, but it hopefully by the end of the week!
