### ISSUE TITLE
TransferManager.copy() performs GetObjectMetadata request without passing sourceVersionId

### ISSUE THREAD

**Issue by ejono** [aws/aws-sdk-java#1009]
When TransferManager.copy() performs a GetObjectMetadata request, it always requests the metadata for the latest object version (i.e., it doesn't pass in a versionId), even though it's possible for the CopyObjectRequest to specify a sourceVersionId. When constructing the GetObjectMetadataRequest, it should also pass in copyObjectRequest.getSourceVersionId().

There are several bugs that could be caused by not doing this if a non-current version of an object is being copied:
- If you try to copy an object version when the object's current version has been deleted (i.e., the latest version is a delete marker), the copy will fail when it shouldn't.
- If the size of the object version being copied differs from that of the current version, the transfer progress will be wrong because it will be using the wrong total size.
- If the size of the object version being copied is greater than the multipart copy threshold size but the size of the current version is less than the threshold, multipart copy will not be used when it should be (or vice versa).
- When performing a multipart copy, and the CopyObjectRequest didn't include any "newObjectMetadata" (or the newObjectMetadata contentType wasn't set), the contentType of the new object will be set to the content type of the current object version rather than the version being copied.

**Comment by dagnir** [comment]
Thank you for reporting this. I will look into it and get a fix out. We also love pull requests if you'd like to contribute one!

**Comment by ejono** [comment]
Thanks for the response! I could certainly fix this myself because it's such a simple change, but I couldn't help but notice that the s3 module is one of the very few that doesn't even seem to have any tests. Are there really no tests for the S3 Java SDK? Should I just submit a PR for the fix itself (just a one-liner)?

**Comment by dagnir** [comment]
Yes I apologize about the lack of tests. We have a large number of them internally but we don't currently publish them publicly, but we're working on it. Feel free to just submit the change to the `TransferManager` code and I can take care writing the tests and making sure everything is good.

**Comment by dagnir** [comment]
I have a fix for this upstream. It should be available in our Monday release next week (2/6).

**Comment by ejono** [comment]
Thank you!

**Comment by dagnir** [comment]
Hi @ejono, the fix was pushed as part of [1.11.87](https://github.com/aws/aws-sdk-java/blob/1.11.87/CHANGELOG.md).
