### ISSUE TITLE
finalize in AmazonHttpClient

### ISSUE THREAD

**Issue by abharti79** [aws/aws-sdk-java#1013]
Code review: 
finalize method in AmazonHttpClient calls shutdown method. shutdown method in turns call shutdown for various class members like clientExecutionTimer and httpRequestTimer. The Java programming language imposes no ordering on finalize method calls. Finalizers may be called in any order, or even concurrently. As of now, there is no finalize method in ClientExecutionTimer and HttpRequestTimer class, hence there will be no issue but there is no comment in ClientExecutionTimer and HttpRequestTimer class to suppress the temptation of adding finalize method in these classes. I believe adding a comment in these class can save from bugs in future.

**Comment by shorea** [comment]
+1

**Comment by dagnir** [comment]
Thanks for reporting this @abharti79. We've added comments in `HttpRequestTimer` and `ClientExecutionTimer` to dissuade developers from overriding `finalize()`. They will appear in this repository after our next public release.

**Comment by dagnir** [comment]
The classes mentioned above now contain the warnings ([1.11.87 release notes](https://github.com/aws/aws-sdk-java/blob/1.11.87/CHANGELOG.md). Resolving this issue.
