### ISSUE TITLE
CONTRIBUTING.md is not found in aws-sdk-java

### ISSUE THREAD

**Issue by t2y** [aws/aws-sdk-java#1017]
I want to contribute aws-sdk-java, but I could not find _CONTRIBUTING.md_. Other sdks have it, like below.

* https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md
* https://github.com/aws/aws-sdk-js/blob/master/CONTRIBUTING.md

I think it's better to put _CONTRIBUTING.md_ explicitly in this repository.

## reference

* https://github.com/aws/aws-sdk-java/issues/569

**Comment by spfink** [comment]
This is definitely something that we can add. I'll get together a draft this week and hope to have an approved version out early next week.

**Comment by t2y** [comment]
@spfink What's the progress?

**Comment by t2y** [comment]
@spfink ping?

**Comment by spfink** [comment]
Still working on getting this out. Hope to have it out with a release this week.

**Comment by t2y** [comment]
Thanks! I hope, too.

**Comment by t2y** [comment]
@spfink still working?

**Comment by t2y** [comment]
@spfink @kiiadi ping?

**Comment by millems** [comment]
Sorry about the delay on this. We've added a contributing.md to our V2 repository that you can reference for now. Contributing to V1 is fairly similar to V2: https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md

We still hope to add one for V1 that covers any differences.

**Comment by t2y** [comment]
Thank you for sharing. It's better putting contributing.md into v1 repository.
