### ISSUE TITLE
Garbled text being delivered when using special characters for SMS messages with AmazonSNSClient

### ISSUE THREAD

**Issue by dcominottim** [aws/aws-sdk-java#1027]
Using aws-java-sdk-bom version 1.11.93 with all source files and Maven source encoding set to UTF-8, when trying to publish an SMS message using SNS, a message that has special characteres (such as 'ç', 'ã', etc.) results in garbled text when it is received (for instance, 'Recomendação' becomes 'Recomenda?').

#692 seemed to describe the issue in detail.

**Comment by zhangzhx** [comment]
Can you enable the [wirelog](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) for more information that we could test? I've testing this sending Unicode to SNS but not seeing the issue. Could you provide a test case to reproduce this issue? Some sample code would be appreciated.

**Comment by zhangzhx** [comment]
Closing this issue due to lack of response. Feel free to reopen one if you still have further questions.
