### ISSUE TITLE
None of the SDK objects override equals or hashcode

### ISSUE THREAD

**Issue by HunterSherms** [aws/aws-sdk-java#1029]
This makes it nearly impossible to build useful unit tests for methods that call SDK methods since you can't verify the objects passed to them.

For a random example (though this applies everywhere) say my code wants to list objects in an S3 bucket:

```
        return s3Client.listObjectsV2(new ListObjectsV2Request()
                .withBucketName(MY_BUCKET_NAME)
                .withDelimiter("/")
                .withPrefix(MY_PREFIX);
```

It is effectively impossible for me to verify in a unit test that listObjectsV2 was called with a ListObjectsV2Request object that contains MY_BUCKET_NAME and MY_PREFIX without extending every SDK object you use.

This could be solved by adding an equals and hashcode method to each object in this SDK.

**Comment by zhangzhx** [comment]
Thanks for reaching out to us. Not like other clients, the S3 client is handwritten and we don't have equal, hashCode methods for the Request objects.

This is a nice feature request and feel free to send us a pull request and we are glad to take a look.

**Comment by HunterSherms** [comment]
Ok, will do.

**Comment by debora-ito** [comment]
Fixed with an internal change as mentioned in https://github.com/aws/aws-sdk-java/pull/1133#issuecomment-395896362.
