### ISSUE TITLE
No warnings when attempting to overwrite immutable SWF activity registration parameters (e.g. defaultTaskList)

### ISSUE THREAD

**Issue by neil-rubens** [aws/aws-sdk-java#103]
No warnings when attempting to overwrite immutable SWF activity registration parameters (e.g. defaultTaskList)

An example of problem that this may cause is as following.  If taskList configurations are changed in code, but the version is not changed; the code will deploy just fine; yet the changes to the settings will not be propagated, and no warnings will be given.  This is a frequently occurring case; and is quite difficult to discover/debug.

This issue is briefly discussed in this AWS Developer forum [post](https://forums.aws.amazon.com/message.jspa?messageID=474975#474975).

**Comment by breedloj** [comment]
Hey Neil,

I noticed that this issue has been open for nearly 3 years and I apologize for the lack of response.  Is this still an issue for you?

**Comment by neil-rubens** [comment]
Thanks for the reply.  Currently I am not using SWF so am not sure if it is
still an issue.

**Comment by breedloj** [comment]
Gotcha.  SWF has seen a lot of changes over the past couple of years so I am going to close this for now.  Feel free to re-open or open a new issue if you start using SWF again and run into issues.  Thanks, and sorry again for the super delayed response.
