### ISSUE TITLE
How to perform a synchronous Upload using the AWS S3 sdk

### ISSUE THREAD

**Issue by jplazcano87** [aws/aws-sdk-java#1033]
i need to perform a synchronous upload with the AWS S3 sdk, this upload lives in another thread so there's no problem with UI block, there's any way to achieve this?

greetings

**Comment by squiddle** [comment]
In the Getting Started guide you can find some examples for using the aws-sdk-s3 API https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3.html

The full example for uploading a file to S3 can be found in the awsdocs/aws-doc-sdk-examples repository.
https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/aws/example/s3/PutObject.java

**Comment by varunnvs92** [comment]
Did you try the code samples in the links provided by @squiddle.

You can also try transfer manager.
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3-transfermanager.html

**Comment by varunnvs92** [comment]
Feel free to re-open if the above links didn't answer your question.
