### ISSUE TITLE
Create conditions on permissions with com.amazonaws.services.sqs.model.AddPermissionRequest

### ISSUE THREAD

**Issue by dgoetsch** [aws/aws-sdk-java#1037]
I recently tried to create permissions for an sns topic to publish to sqs queues, unfortunately I couldn't figure out how to do this with the provided API. The AddPermissionRequest class doesn't appear to support the same level of granular configuration as the UI or raw rest api, or even manual request configuration. I also couldn't find any examples on the web.

```
val permissionRequest = new AddPermissionRequest()
permissionRequest.setQueueUrl(queueUrl)
permissionRequest.setActions(Seq("sqs:SendMessage"))
permissionRequest.setLabel(s"$queueName-SendMessage")
permissionRequest.setAWSAccountIds(Seq(accountId))
//No methods for configuring conditions
val permissionResult = sqsClient.addPermission(permissionRequest)
```

I was able to do this on the UI, as shown here: http://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html

Am I missing something? Is this a new feature request?

**Comment by varunnvs92** [comment]
I think you are looking for this.
https://aws.amazon.com/blogs/developer/subscribing-queues-to-topics/
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sns/util/Topics.html

To get quicker response on service functionality, it is better to ask the question on stack-overflow and tag it with aws-java-sdk.
See https://github.com/aws/aws-sdk-java#getting-help
