### ISSUE TITLE
AWS Lambda: LambdaInvokerFactory does not permit RequestStreamHandler implementation

### ISSUE THREAD

**Issue by rostskadat** [aws/aws-sdk-java#1038]
Hi,

Here is the scenario:
1- a Lambda function that implement the com.amazonaws.services.lambda.runtime.RequestStreamHandler interface
```java
public class MyRequestStreamHandler implements RequestStreamHandler {
    public void handleRequest(InputStream is, OutputStream os, Context context) throws IOException {
        int letter;
        while((letter = inputStream.read()) != -1)
        {
            outputStream.write(Character.toUpperCase(letter));
        }
    }
}
```
2- a java class that tries to call that Lambda function:

```java
public class MyLambdaConsumer {

    public interface MyLambdaFunction {
       @LambdaFunction(functionName = "MyRequestStreamHandler")
       void handleRequest(InputStream is, OutputStream os);
    } 

    public void consume(AWSLambdaClient lambdaClient, InputStream is, OutputStream os) {
        LambdaInvokerFactory.Builder builder = LambdaInvokerFactory.builder();
        MyLambdaFunction lambdaFunction = builder.lambdaClient(lambdaClient).build(MyLambdaFunction.class);
        lambdaFunction.handleRequest(is, os);
   }
}
```

=> This will fail with a 

```
Caused by: com.amazonaws.services.lambda.invoke.LambdaSerializationException: LambdaFunctions take either 0 or 1 arguments
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.validateInterfaceMethod(LambdaInvokerFactory.java:235)
```

=> I would expect that the Builder would allow to create a LambdaFunction stub from a function that implements the RequestStreamHandler. I believe that the check in LambdaInvocationHandler.validateInterfaceMethod(LambdaInvokerFactory.java:235) is incorrect:

```java
    if (args != null && args.length > 1) {
        throw new LambdaSerializationException("LambdaFunctions take either 0 or 1 arguments");
    }
```

**Comment by shorea** [comment]
With streaming though it wouldn't make sense to have an OutputStream as the second parameter. You'd want the input stream of the data coming back from the function.

**Comment by rostskadat** [comment]
Hum, I understand. However, how does AWS knows that the second parameter of the LambdaFunction implementing the ``RequestStreamHandler`` should be streamed to the InputStream return by the local interface's method?

**Comment by shorea** [comment]
Anything you write to the OutputStream provided will be written to the socket as the response (I'm not actually sure if they truly stream it or buffer it and send it all at once). At the end of the day though it is buffered in a Java ByteBuffer client side. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-lambda/src/main/java/com/amazonaws/services/lambda/model/InvokeResult.java#L66

**Comment by rostskadat** [comment]
Ok, I'll try the change to the local interface you're proposing, and see if it fixes the problem.
If it does then, you should probably reject the pull request, as this is probably more a documentation problem than a API problem.

**Comment by shorea** [comment]
I'm pretty sure it won't work. We assume it's a POJO and use jackson-databind to deserialize the data. You can give it a try but if it doesn't work I don't that it will be too hard to add support for.

**Comment by debora-ito** [comment]
Hi @rostskadat 

The SDK team are concentrating efforts on V2 new features so they decided not to implement this one in V1. It's still being considered for V2.

I'll go ahead and close this, please feel free to reach out if you have further questions.
