### ISSUE TITLE
Presigning non-S3 requests with latest SDK

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-sdk-java#1039]
Up until 1.11.90 we used the following code to pre-sign CloudWatch Logs requests:

```
FilterLogEventsRequest filterLogEventsRequest = new FilterLogEventsRequest()
                .withInterleaved(true)
                .withLogGroupName(logGroupName)
                .withStartTime(startTime)
                .withEndTime(endTime)
                .withLimit(limit)
                .withNextToken(nextToken)
                .withFilterPattern(filterPattern);

if (logStreamNames != null) {
    filterLogEventsRequest.setLogStreamNames(logStreamNames);
}

SdkJsonProtocolFactory protocolFactory = new SdkJsonProtocolFactory(
                new JsonClientMetadata()
                        .withProtocolVersion("1.1")
                        .withSupportsCbor(false)
                        .withSupportsIon(false)
                        .withBaseServiceExceptionClass(
                                com.amazonaws.services.logs.model.AWSLogsException.class));

URI endpoint = createEndpoint(awsRegion.getName(), AWSLogs.ENDPOINT_PREFIX);

Request<FilterLogEventsRequest> requestForPresigning =
                new FilterLogEventsRequestMarshaller(protocolFactory).marshall(filterLogEventsRequest);
```

however this doesn't work anymore with the latest version of the SDK due to the change in signature of the `marshall` method. What is the correct way to pre-sign this now?

**Comment by shorea** [comment]
This isn't something we officially support but you can use https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-logs/src/main/java/com/amazonaws/services/logs/model/transform/FilterLogEventsRequestProtocolMarshaller.java#L32 pretty much the same way. Note that this APIs are Protected or Internal meaning we may make breaking changes to them from time to time.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/annotation/SdkInternalApi.java
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/annotation/SdkProtectedApi.java

**Comment by axelfontaine** [comment]
That worked great! Thanks for the fast help!
