### ISSUE TITLE
Attributes in extended class not saved to DynamoDB

### ISSUE THREAD

**Issue by xquarel** [aws/aws-sdk-java#1040]
I have a base class containing some common attribute such as createdBy, createdAt, updatedBy, updatedAt, then I have POJOs extends this base class. But these common attributes are not saved to DynamoDB. Did I miss anything?

(Sorry, not sure why the formatting doesn't work correctly.)

public class BaseEntity {
    @DynamoDBAttribute(attributeName = "createdBy")
    private String createdBy;

    @DynamoDBAttribute(attributeName = "createdAt")
    private Date createdAt;

    @DynamoDBAttribute(attributeName = "updatedBy")
    private String updatedBy;

    @DynamoDBAttribute(attributeName = "updatedAt")
    private Date updatedAt;

	public BaseDomain() {
		super();
	}
	/* getters and setters */
}

@DynamoDBTable(tableName = "mft-data-pipeline")
public class SomeObject extends BaseEntity {
	
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    /* getters and setters */
}

**Comment by kiiadi** [comment]
How are you saving/loading these items?

**Comment by xquarel** [comment]
I use spring-data-dynamodb. I think it is looking for getter/setter in the class that extends the base class.

**Comment by kiiadi** [comment]
Just did a play locally to re-create this, if you annotate you base class with `@DynamoDBDocument` that will indicate to the mapper that it's properties also need to be serialized.

**Comment by xquarel** [comment]
I tried annotating the base class with @DynamoDBDocument, but it still didn't add the properties. Could you share your sample code please? Thank you so much.

**Comment by kiiadi** [comment]
This is my base class:

```java
@DynamoDBDocument
public class BaseEntity {
    @DynamoDBAttribute(attributeName = "baseName")
    private String baseName;

    public String getBaseName() { return baseName; }

    public void setBaseName(String baseName) { this.baseName = baseName; }
}
```

Here's the extension object:

```java
@DynamoDBTable(tableName = "test-table")
public class SomeObject extends BaseEntity {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    public String getId() { return id; }

    public void setId(String id) { this.id = id; }

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }
}
```

Here's the test:
```java
AmazonDynamoDB dynamoDb = AmazonDynamoDBClientBuilder.standard().withRegion("us-west-2").build();
DynamoDBMapper mapper = new DynamoDBMapper(dynamoDb);

SomeObject obj = new SomeObject();
obj.setId("object");
obj.setBaseName("the base name");
obj.setName("actual");

mapper.save(obj);

SomeObject loaded = mapper.load(SomeObject.class, "object");

System.out.println(new ObjectMapper().writeValueAsString(loaded));
```

This prints:

```json
{"baseName":"the base name","id":"object","name":"actual"}
```

**Comment by xquarel** [comment]
Hi kiiadi, based on your example, I got it to work. Thank you so much. I really appreciate your help!
