### ISSUE TITLE
Unable to find aws-java-sdk-organizations in Maven

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1041]
Is there another repository I should be looking for this dependency? I'm looking for the module version 1.11.98.
```
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-core</artifactId>
      <version>1.11.98</version>
    </dependency>
```

**Comment by shorea** [comment]
Seems like it's there. How recently have you tried referencing it? Maven was having issues yesterday due to the S3 outage.

https://search.maven.org/#artifactdetails|com.amazonaws|aws-java-sdk-organizations|1.11.98|jar

**Comment by rdifalco** [comment]
Wasn't there two hours ago, it's there now. Hmph. I'll close this issue.
