### ISSUE TITLE
Several fns described as deprecated in their documentation, but not in the model

### ISSUE THREAD

**Issue by lvh** [aws/aws-sdk-java#1043]
http://docs.aws.amazon.com/cli/latest/reference/directconnect/describe-connection-loa.html
http://docs.aws.amazon.com/cli/latest/reference/directconnect/describe-interconnect-loa.html

The matching result classes in the model are not marked as deprecated. The matching operations are similarly also not marked as deprecated.

~~I don't know if the "deprecated" part of the model is ever used at all, but this seems inconsistent.~~ Looks like the codegen uses deprecated pretty sanely: adding at least an annotation.

**Comment by lvh** [comment]
You can see this e.g. here: https://github.com/aws/aws-sdk-java/blob/a90a49d088b5afadba048efe52f7d57652cb11ed/aws-java-sdk-models/src/main/resources/models/directconnect-2012-10-25-model.json#L798

**Comment by lvh** [comment]
Some more fns:

- SES' list-verified-email-addresses operation is [deprecated since 2012](http://docs.aws.amazon.com/ses/latest/APIReference/API_ListVerifiedEmailAddresses.html) but not marked as such in the [model](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-models/src/main/resources/models/email-2010-12-01-model.json#L942) or the SDK

- StorageGateway's DescribeWorkingStorage operation is [deprecated since 2012](http://docs.aws.amazon.com/storagegateway/latest/APIReference/API_DescribeWorkingStorage.html) but not marked as such in the [model](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-models/src/main/resources/models/storagegateway-2013-06-30-model.json#L1365) or the SDK

**Comment by lvh** [comment]
Some more:

DirectConnect's AllocateConnectionOnInterconnect: https://github.com/aws/aws-sdk-java/blame/a90a49d088b5afadba048efe52f7d57652cb11ed/aws-java-sdk-models/src/main/resources/models/directconnect-2012-10-25-model.json#L21

**Comment by varunnvs92** [comment]
@lvh 
Thanks for finding this issue. Internally, the SDK team uses a model provided by service team and converts it to a Json model (the models in our repo). I checked the service team models and found that they are not tagging these operations as deprecated. This is why our models are picking them as "deprecated=false". 

I will raise a ticket to DirectConnect team (as this is a recent change) to notify this issue. I update you when I hear back from them. Thank you.

**Comment by lvh** [comment]
@varunnvs92 Yep, I'm aware :) I've asked about similar issues in the past, but since I can't file tickets against that team directly, the aws-java-sdk is all I got :D

I have added a test to my internal test suite for things that are inconsistently marked as deprecated, and found the following things:

```
#{#'amazonica.aws.directconnect/allocate-connection-on-interconnect
  #'amazonica.aws.directconnect/describe-connection-loa
  #'amazonica.aws.directconnect/describe-connections-on-interconnect
  #'amazonica.aws.directconnect/describe-interconnect-loa
  #'amazonica.aws.simpleemail/delete-verified-email-address
  #'amazonica.aws.simpleemail/list-verified-email-addresses
  #'amazonica.aws.simpleemail/verify-email-address
  #'amazonica.aws.storagegateway/add-working-storage
  #'amazonica.aws.storagegateway/describe-working-storage}
```

That might not be a complete list, because not every service marks deprecation in the documentation consistently, and some operations have `deprecate` in the name themselves. OTOH deprecations are fairly rare, so... Here's hoping. Could you please also file tickets with the SES and StorageGateway teams?

**Comment by kiiadi** [comment]
@lvh you can actually file support cases via the [AWS console](https://console.aws.amazon.com/support/home) that will find their way to the correct service team. I appreciate your interaction is with the SDK and thus raising it via this means seems like the only option - but it probably makes more sense to cut us out as the middle-man in the future and go directly to the source 😃

**Comment by lvh** [comment]
Apologies, I was previously instructed to do it via the SDK.

**Comment by kiiadi** [comment]
@lvh yep, sorry about the churn; we're trying to make sure that we're not the bottle-neck!

**Comment by varunnvs92** [comment]
Closing this issue as per @kiiadi comment. I didn't get any response yet and I pinged them again. There might be better response if you engage the service team directly. Thank you.

**Comment by varunnvs92** [comment]
The direct connect team fixed the issue on their end. I am making changes to SDK's internal models. The deprecations for direct connect will be including in 03/21 or 03/22 release. 

For other services, please contact support through console or forums. Thanks.
