### ISSUE TITLE
Wrong Exception in TransferManager#download

### ISSUE THREAD

**Issue by smigfu** [aws/aws-sdk-java#1046]
When using the TransferManager's download method to download an object in a parallelised way and something fails the client will be presented with an AmazonClientException instead of the expected AmazonS3Exception.

Steps to repro (sorry I can't provide a JUnit test for that due to the parallelism):

* upload an object which can be downloaded with a parallel request
* set a breakpoint DownloadCallable#downloadInParallel (line 188)
* initiate the request to download the object
* if you hit the breakpoint, delete the object manually from S3 (this emulates another client which deletes the object)
* resume the breakpoint
* DownloadCallable#combineFiles will throw an ExecutionException with the wrapped AmazonS3Exception.
* this is caught in DownloadCallable#call and afterwards is rethrown.
* Since DownloadCallable is also executed in a ExecutorService it will be wrapped again in an ExecutionException. We now have (ExecutionException -> ExecutionException -> AmazonS3Exception)
* The Exception is then caught in AbstractTransfer#unwrapExecutionException which will unwrap only the top most exception and the does a check if it is an AmazonClientException (which it is not and thus wrap everything in AmazonClientException which leads to AmazonClientException -> ExecutionException -> AmazonS3Exception)
* Next exception handling has to be done by the client (i.e. transferManager.download(xyz).waitForCompletion(). The exception presented to the client is an AmazonClientException where the expected exception should be only the AmazonS3Exception

We do expect the Exception to be the AmazonS3Exception b/c we have some special handling for that case. In the single download case this works as expected but fails in the parallel download. I guess the right fix would either be to implement AbstractTransfer#unwrapExecutionException to unwrap until all ExecutionExceptions are gone or in the exception handling of DownloadCallable to unrwrap the ExecutionException already there.

**Comment by kiiadi** [comment]
@smigfu definitely sounds like odd behaviour and I think either of your two solutions could work - probably the "unwrap until all ExecutionExceptions are gone" would be slightly better because it may prevent other similar cases in the future. Since `AmazonS3Exception` ultimately extends `AmazonClientException` I think we're good from a backwards compatibility point of view. We do accept pull-requests if you wanted to submit one for this I'd be happy to take a look.

**Comment by dagnir** [comment]
This is fixed in [1.11.106](https://github.com/aws/aws-sdk-java/blob/799319f670344153d588e7e42095653fabf01673/CHANGELOG.md#amazon-s3)
