### ISSUE TITLE
JsonMappingException: Conflicting setter definitions for property \"protocol\": com.amazonaws.services.ecs.model.PortMapping#setProtocol

### ISSUE THREAD

**Issue by abirdatta** [aws/aws-sdk-java#1053]
Hi,

I am trying to create a AWS Lambda JAVA function to update my ECS service with new task definition. The Lambda function is taking in a JSON input which is serializing to com.amazonaws.services.ecs.model.ContainerDefinition and com.amazonaws.services.ecs.model.PortMapping objects.
Since the PortMapping class has two setter setProtocol methods its giving the error mentioned below-

Can we please put JsonIgnore in 
public void setProtocol(TransportProtocol protocol) {
        this.protocol = protocol.toString();
    }

or suggest me a workaround for this, other than creating my own objects.

{"errorMessage":"An` error occurred during JSON parsing","errorType":"java.lang.RuntimeException","stackTrace":[],"cause":{"errorMessage":"com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property \"protocol\": com.amazonaws.services.ecs.model.PortMapping#setProtocol(1 params) vs com.amazonaws.services.ecs.model.PortMapping#setProtocol(1 params)","errorType":"java.io.UncheckedIOException","stackTrace":[],"cause":{"errorMessage":"Conflicting setter definitions for property \"protocol\": com.amazonaws.services.ecs.model.PortMapping#setProtocol(1 params) vs com.amazonaws.services.ecs.model.PortMapping#setProtocol(1 params)","errorType":"com.fasterxml.jackson.databind.JsonMappingException","stackTrace":["com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)","com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)","com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)","com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)","com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)","com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)","com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)","com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)","com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)","com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)","com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)","com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:1749)","com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1506)","com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)"],"cause":{"errorMessage":"Conflicting setter definitions for property \"protocol\": com.amazonaws.services.ecs.model.PortMapping#setProtocol(1 params) vs com.amazonaws.services.ecs.model.PortMapping#setProtocol(1 params)","errorType":"java.lang.IllegalArgumentException","stackTrace":["com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:300)","com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:592)","com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:488)","com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:229)","com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:142)","com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)","com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)","com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)","com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)","com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)","com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)","com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)","com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)","com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669)","com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430)","com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947)","com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)","com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)","com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)","com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)","com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:1749)","com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1506)","com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)"]}}}}

**Comment by kiiadi** [comment]
@abirdatta should be able to get this out in todays release

**Comment by kiiadi** [comment]
@abirdatta adding this attribute caused some odd serialization issues in some of integration tests (specifically around waiters) so I've reverted it for now. I'm not *overly* comfortable introducing Jackson specific annotations to our models. Yes, we use Jackson internally as a serialization mechanism but we use our own marshaller implementations to correctly output the JSON structure; adding these annotations that customers may rely on is dangerous if we ever choose to switch serialization libraries (and it could open the door to customers asking us to add other attributes to support their specific serialization library eg GSON).

All of that said, I wanted to understand a bit more about your use-case. You have a Lambda function that takes a JSON-serialized AWS request object is that right? Could you form your own structure that then is unpacked to the request object in the lambda?

**Comment by abirdatta** [comment]
@kiiadi , I understand your concern. Yes, I have a Lambda function, which takes a JSON serialized AWS request object. At the moment I am using POJOs which are exactly similar to AWS ECS model ContainerDefinition and PortMapping, which I didn't want to do and wanted to use the AWS classes. Please have a look at the [project](https://github.com/abirdatta/AWSLambdaProjectToWorkWithAmazonECS).

**Comment by millems** [comment]
Sorry for the delay on this. Some versions of Jackson do well in disambiguating conflicting setters by looking at the return type of the getter. If upgrading your Jackson version doesn't fix this problem, you can mix-in the `@JsonIgnore` annotations yourself on problematic methods: https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations

Unfortunately we won't be able to add jackson-specific annotations to our objects to fix your problem in this case. We're wary of externally implying our customers should use jackson over other libraries.

Let me know if this doesn't work to fix the problem!
