### ISSUE TITLE
JVM exit blocked by AmazonCloudFormationWaiters

### ISSUE THREAD

**Issue by harschware** [aws/aws-sdk-java#1056]
I have code that calls cloudformation create stack and subsequently calls: `acfClient.waiters().stackCreateComplete().runAsync();`

When the stack creation is complete my `WaiterHandler<DescribeStacksRequest>` is notified as expected.

Later, when the main method completes. The JVM is unable to exit.

I've tracked the source of the problem down to the executor service in AmazonCloudFormationWaiters.  It should be creating daemon threads using a ThreadFactory for doing so.
see:  https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/waiters/AmazonCloudFormationWaiters.java#L33

**Comment by kiiadi** [comment]
@harschware can you provide a brief test-case that reproduces this? I'm trying to determine if a fix that I've made for this resolves the issue.

**Comment by harschware** [comment]
I will try, it might be a day or two though.

**Comment by kiiadi** [comment]
@harschware don't worry - I was able to reproduce this. I've added a `shutdown()` method to the waiters which in turn gets called by the client's `shutdown()` method. It should be out in the 1.11.106 release next week.

**Comment by dagnir** [comment]
This is fixed in [1.11.106](https://github.com/aws/aws-sdk-java/blob/799319f670344153d588e7e42095653fabf01673/CHANGELOG.md#core) Resolving this.
