### ISSUE TITLE
How to get the unencrypted length of an S3 object?

### ISSUE THREAD

**Issue by nezihyigitbasi** [aws/aws-sdk-java#1057]
As part of the Presto project we have some open issues that boil down to determining the unencrypted length of an encrypted S3 object (please see prestodb/presto#7103 and prestodb/presto#7186). 

Previously we were using `UNENCRYPTED_CONTENT_LENGTH` header in the metadata, but the docs say that this header is optional. In case this header isn't set, what's the proper way to determine the unencrypted length (hopefully without reading the entire object)?

**Comment by kiiadi** [comment]
Where are you doing your encryption? Is it on the client-side using the AmazonS3EncryptionClient or is it using the S3 Server Side Encryption (SSE)?

For the client-side, looking at the crypto-code we set this header before we make the request so it *should* be there for objects that you've set through the client - https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/crypto/S3CryptoModuleBase.java#L625

**Comment by nezihyigitbasi** [comment]
@kiiadi if you look at [this](https://github.com/prestodb/presto/issues/7103#issuecomment-285169896) comment in prestodb/presto#7103, it's possible that this header may not be set when using client side encryption. In cases like this (whether due to a bug or sth else) where we don't have this header, what's the best practice to get the unencrypted length information?

**Comment by kiiadi** [comment]
@nezihyigitbasi since it's encrypted on the client side, I don't think there's going to be any service-side mechanism to determine the length of the original content. Only the client knows the content prior to encryption (the whole point of client-side encryption).

I'm interested to dig more into why this header isn't being set, that seems like the underlying issue here. Do you have code the repros this?

Also out of interest what's your use-case for getting the content-length without actually reading the data?

**Comment by nezihyigitbasi** [comment]
@kiiadi I think @RothA can provide you more info about how to reproduce this issue using Spark and EMRFS.

To answer your last question, we have readers to decode different file formats (such as Parquet) and these readers read the bytes from S3 using a Hadoop filesystem implementation that we have. Before even starting to read the file, one of these readers use the file length to determine where to seek to read the file footer (to read metadata) and this file length should be unencrypted to seek to the right point in file.

**Comment by RothA** [comment]
@kiiadi Some background into our use case:

* We use Spark running on EMR clusters with data encryption on S3 using KMS client-side. (https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-emr-now-supports-data-encryption-for-apache-spark-tez-and-hadoop-mapreduce/)
* The process reads data from a database into a Spark DataFrame which is then saved to S3 in a parquet format.  This write is done by the EMRFS not an S3Client directly.    https://spark.apache.org/docs/1.6.0/sql-programming-guide.html#parquet-files

Quick example:

```
// sqlContext from the previous example is used in this example.
// This is used to implicitly convert an RDD to a DataFrame.
import sqlContext.implicits._

val people: RDD[Person] = ... // An RDD of case class objects, from the previous example.

// The RDD is implicitly converted to a DataFrame by implicits, allowing it to be stored using Parquet.
people.write.format("parquet")("s3://testbucket/people")
```

**Comment by kiiadi** [comment]
@nezihyigitbasi @RothA what I'm really trying to understand is why that header is not being set on the request when you PUT the object. Can you give me a snippet of code that reproduces the problem where the `x-amz-unencrypted-content-length` is not set?

**Comment by nezihyigitbasi** [comment]
Unfortunately, I don't have any snippets other than the one @RothA commented above.

**Comment by RothA** [comment]
@kiiadi yes the code snippet above is what can reproduce it.  Obviously if we were using a S3 client directly we could set headers, etc but this is all handled on EMR by the underlying EMRFS.  http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-fs.html

**Comment by kiiadi** [comment]
@nezihyigitbasi @RothA unfortunately I'm not overly familiar with EMR - I've had a bit of a read up on it and it sounds like the EMRFS has its own interface to S3 (separate from the aws-java-sdk) - it's presumably at this point that the header needs to be provided. I can try to reach out to the EMR service team internally and get more information. In the meantime it's probably a good idea to raise this as a request on stack-overflow using EMR's tag: http://stackoverflow.com/questions/tagged/amazon-emr

**Comment by nezihyigitbasi** [comment]
@kiiadi were you able to get more info about this one?

**Comment by nezihyigitbasi** [comment]
@kiiadi any updates on this one?

**Comment by kiiadi** [comment]
@nezihyigitbasi I'm following up with the EMR team - waiting to hear back. Did you have any luck raising this on stack-overflow? As I said above, this doesn't seem like an issue with the SDK itself.

**Comment by RothA** [comment]
@kiiadi I was able to confirm with the EMR team that they use the S3EncryptionClient for handling the KMS encryption in EMRFS.  It is seeming like there is a difference between how EMRFS handles this and PrestoS3FileSystem does.  I have yet to explain why I can handle these same parquet files perfectly fine when using Spark and Hive on EMRFS but am unable to read them with Presto.

**Comment by kiiadi** [comment]
@nezihyigitbasi believe you had a conversation with EMR and agreed that there's nothing to be done here - I'm going to resolve this for now - feel free to re-open if you think this is an issue with the SDK.
