### ISSUE TITLE
Huge JSON schema files

### ISSUE THREAD

**Issue by tadaskay** [aws/aws-sdk-java#1058]
Would it be possible to avoid bundling huge JSON schema into the SDK JARs?
For example, 18.5MB `ec2-2016-11-15-intermediate.json` in aws-sdk-java-ec2. That's about 1/4th of my application's fat jar size.
There is a closed feature request #831, but the big files are still there ;)

**Comment by dagnir** [comment]
Hi @tadaskay, we have a fix for this upstream that should be available in the next release.

**Comment by lvh** [comment]
I think I've reported that independently on another ticket too, so happy to see that addressed (as long as the models jar doesn't change :D)

**Comment by kiiadi** [comment]
@tadaskay @lvh these were removed in last nights build the models should now only appear in the models module directly.
