### ISSUE TITLE
revokeSecurityGroupIngress will always throw an exception

### ISSUE THREAD

**Issue by harschware** [aws/aws-sdk-java#1059]
The method AmazonEC2Client#revokeSecurityGroupIngress()   (see: https://github.com/aws/aws-sdk-java/blob/1.11.93/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/AmazonEC2Client.java#L11608)

will ALWAYS throw the exception.   "com.amazonaws.services.ec2.model.AmazonEC2Exception: The request must contain the parameter groupName or groupId"

**Comment by kiiadi** [comment]
@harschware good catch, we won't be able to remove this since customers could be compile-time dependent on it (even if it's in a dead-branch of code and not cause any actual problems) - seems very unlikely I know but it is possible. I will mark it as deprecated and we'll remove it in our next major-version bump

**Comment by harschware** [comment]
Thanks, seems reasonable to me.   I thought the method might actually revoke all Ingress rules in a group (no noticing that it doesn't get anything passed to it).  It would be nice to have such a method.  As it stands, I had to create code to query out all Ingress rules and pass them in to a revoke request.

**Comment by kiiadi** [comment]
@harschware without a supported operation on the service-side that does that the SDK would be stuck doing the same thing you're doing anyway - so performance wise there'd be no gain.

If you want to suggest the feature to the service team you can do it either via a support-ticket in the AWS Console or by asking a question on StackOverflow using ecs's tag : http://stackoverflow.com/questions/tagged/amazon-ecs

**Comment by dagnir** [comment]
This is fixed in [1.11.106](https://github.com/aws/aws-sdk-java/blob/799319f670344153d588e7e42095653fabf01673/CHANGELOG.md#amazon-ec2)
