### ISSUE TITLE
DynamoDBMapper throws NullPointerException when querying for count

### ISSUE THREAD

**Issue by shaddyz** [aws/aws-sdk-java#1063]
When attempting to count the number of items in a table of items with both a hash and sort key, a NullPointerException is thrown. See the code sample below:
```
public int getCount(String hashKey) {
	MyDbItem dbItem = new MyDbItem();
	dbItem.setHashKey(hashKey);
	DynamoDBQueryExpression<MyDbItem> queryExpression = new DynamoDBQueryExpression<MyDbItem>()
		.withHashKeyValues(dbItem)
		.withSelect(Select.COUNT);
	QueryResultPage<SubscriptionDbItem> result = dbMapper.queryPage(MyDbItem.class, queryExpression);
	return result.getCount();
}
```

```
java.lang.NullPointerException
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.toParameters(DynamoDBMapper.java:1976)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.queryPage(DynamoDBMapper.java:1520)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.queryPage(AbstractDynamoDBMapper.java:277)
     // at dbMapper.queryPage call
```

**Comment by shaddyz** [comment]
I found there is a count method for doing this operation, however, I still believe a NullPointerException is an issue. It should either be a validation exception informing the consumer that is not a valid use, the types should not permit a count, or it should just work regardless of if there's a dedicated method to count.

**Comment by millems** [comment]
Thanks for the detailed bug report! A fix has been made internally and will go out with our next release.
