### ISSUE TITLE
MD5DigestCalculatingInputStream.getMd5Digest() doesn't consider including the bytes from input stream

### ISSUE THREAD

**Issue by pravsingh** [aws/aws-sdk-java#1064]
The digest member field of MD5DigestCalculatingInputStream class doesn't have reference to InputStream and hence its not obvious on how it includes the inputs file bytes for calculating the MD5 hash.

**Comment by kiiadi** [comment]
The digest is updated as the stream is read - https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/MD5DigestCalculatingInputStream.java#L88 

I'm not sure what your question is exactly, what are you trying to do?

**Comment by pravsingh** [comment]
thanks for the clarification. I was trying to use the same md5 calculation for my other code base.
