### ISSUE TITLE
AwsClientBuilder should have a toBuilder copy constructor

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1067]
Feature Request

Because `AwsClientBuilder` does not have a  copy constructor method, I need to synchronized the builder to create a regional client manager. We use (for example) an EC2 client in multiple regions throughout our code. So we have a class that just maps regions to clients so we can re-use the same client for a given region everywhere. It's impossible to create this class without synchronization because builders do not have a copy ctor. Consider the following snippet.

```
public final class AwsClientContext<T> {

    private final Map<String, T> clientByRegion = new ConcurrentHashMap<>();
    private final AwsClientBuilder<? extends AwsClientBuilder, T> builder;

    public AwsClientContext(AwsClientBuilder<? extends AwsClientBuilder, T> builder) {
        this.builder = builder;
    }

    public T getClient(String region) {
        return clientByRegion.computeIfAbsent(region, this::createClient);
    }

    private T createClient(String region) {
        // NOTE: Synchronization is required since we are reusing the same builder
        // concurrently for multiple regions
        synchronized (builder) {
            builder.withRegion(region);
            builder.withCredentials(INVALID_PROVIDER);
            return builder.build();
        }
    }
```

FWIW, I can solve this by using a `Supplier<AwsClientBuilder<? extends AwsClientBuilder>>`, so this enhancement request isn't that big of a deal.

**Comment by kiiadi** [comment]
@rdifalco this is something that we're going to address in the next major version bump of the SDK - we'll have exactly what you suggest a copy() method on the builder instance which will create a shallow copy of the object. 

I like your implementation of a regional client too - that's something we've been discussing internally.

If this isn't causing major pain, I'd rather leave it as it is in 1.11.x right now, as I say we'll address in the next MV of the SDK.

**Comment by rdifalco** [comment]
@kiiadi, no major pain at all, I worked around it by creating a Supplier<> for the builder to act as a Builder Factory.

**Comment by kiiadi** [comment]
Cool - I'm going to resolve this for now.
