### ISSUE TITLE
null check for long partSize in MultiPartUpload can never fail

### ISSUE THREAD

**Issue by kayvonr** [aws/aws-sdk-java#1069]
In https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java:3103 there is a `rejectNull()` check on the `UploadPartRequest.partSize`. However, that is a `long`, not a `Long`, and if omitted from the `UploadPartRequest` object will be 0, not null. This will cause the part to seem to go through (but not actually get uploaded), and the whole upload will fail only once attempting to complete it (with error `com.amazonaws.services.s3.model.AmazonS3Exception: Your proposed upload is smaller than the minimum allowed size`).

**Comment by dagnir** [comment]
Thanks for reporting this, will get a fix out soon!

**Comment by kiiadi** [comment]
See related issue : https://github.com/aws/aws-sdk-java/issues/995

**Comment by dagnir** [comment]
Thanks. I agree, we should leave it. I'll remove the check.

**Comment by kayvonr** [comment]
Ah ok, tried to search before opening this but didn't find that somehow. I'll comment on that

**Comment by dagnir** [comment]
Null checks removed upstream. This will be fixed in our next release (scheduled for tomorrow). Thanks!
