### ISSUE TITLE
API Gateway - AmazonApiGatewayClient.getExport ignores "Accept" parameter

### ISSUE THREAD

**Issue by shuttj** [aws/aws-sdk-java#1072]
I also posted this as a question on the forum [here](https://forums.aws.amazon.com/thread.jspa?threadID=251583&tstart=0).

I am trying to export the yaml version of my api deployed to the api gateway using the aws sdk for java, but it is ignoring my accepts value where I am specifying "application/yaml". In fact, it doesn't matter if I provide a valid value for accepts or not, it always returns "application/json". 

**SDK version:** `"com.amazonaws" % "aws-java-sdk-api-gateway" % "1.11.104"`

**Code snippet in Scala**
```scala
val creds: BasicAWSCredentials = ...
val apiId: String = ...
val stageName: String = ...

val client = AmazonApiGatewayClientBuilder
  .standard()
  .withCredentials(new AWSStaticCredentialsProvider(creds))
  .withRegion(Regions.US_WEST_2)
  .build()

val getExportRequest = new GetExportRequest()
  .withRestApiId(apiId)
  .withStageName(stageName)
  .withAccepts("application/yaml")
  .withExportType("swagger")
val getExportResponse = client.getExport(getExportRequest)
```

**Debug output of actual request**
```
[debug] o.a.h.headers - http-outgoing-1 >> GET /restapis/.../stages/.../exports/swagger HTTP/1.1
[debug] o.a.h.headers - http-outgoing-1 >> Host: apigateway.us-west-2.amazonaws.com
[debug] o.a.h.headers - http-outgoing-1 >> Authorization: AWS4-HMAC-SHA256 Credential=.../20170315/us-west-2/apigateway/aws4_request, SignedHeaders=accept;amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-date, Signature=...
[debug] o.a.h.headers - http-outgoing-1 >> X-Amz-Date: 20170315T214638Z
[debug] o.a.h.headers - http-outgoing-1 >> Accept: application/json
[debug] o.a.h.headers - http-outgoing-1 >> User-Agent: aws-sdk-java/1.11.104 Linux/4.8.0-41-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.111-b14/1.8.0_111 scala/2.11.8
```
You can see that the actual request fires off with the Accept header set as "application/json".

I have traced through the code and found that the problem lies in the [`com.amazonaws.services.apigateway.internal.AcceptJsonRequestHandler`](https://github.com/aws/aws-sdk-java/blob/1.11.104/aws-java-sdk-api-gateway/src/main/java/com/amazonaws/services/apigateway/internal/AcceptJsonRequestHandler.java#L26) class. This is called before each request goes out, and it is overriding the value set in the `GetExportRequest` object.

It's not a huge blocker as most tools support reading either the yaml or json format, but it would be nice if it worked [as advertised](https://github.com/aws/aws-sdk-java/blob/1.11.104/aws-java-sdk-api-gateway/src/main/java/com/amazonaws/services/apigateway/model/GetExportRequest.java#L59).

**Comment by dagnir** [comment]
Thanks for reporting this! Will work on getting a fix out.

**Comment by dagnir** [comment]
Hi @shuttj, this will be fixed in our next release (some time early next week). Thanks again for reporting.

**Comment by shuttj** [comment]
Thank you!
