### ISSUE TITLE
Add a pagination interface so that you can generically handle paginated responses

### ISSUE THREAD

**Issue by gorzell** [aws/aws-sdk-java#1074]
I am re-opening #121 since the alternate solution seems like it was never completed and is not maintained.

It would be really help to have interfaces around the pagination of results. This would give you the ability to write generic logic for loading the full data set.

I propose declaring interfaces which would probably only need to have the getNextToken and setNextToken methods respectively and then changing the Request/Result model classes that have these methods already to implement the interfaces.

I am happy to do the code change if people think this would be useful and is the correct approach.

**Comment by shorea** [comment]
We are working on V2 of the SDK and one of the goals is to provide a consistent pagination experience and make automatic pagination a first class citizen of the SDK. If you are interested in participating in the developer preview we can reach out to you later this year.

**Comment by gorzell** [comment]
Any updates on this?  Is it in the new version?

**Comment by millems** [comment]
Yes! This is currently available in V2 for our sync clients (https://github.com/aws/aws-sdk-java-v2/issues/26). If you add `Iterable` to the end of the method name on a client, you get to the automated-depaginating result type:

```Java
ListObjectsV2Paginator result = s3Client.listObjectsIterable(request);

Iterable<ListObjectsV2Response> resultPages = result;
Stream<ListObjectsV2Response> resultPagesStream = result.stream();

Iterable<S3Object> results = result.contents();
Stream<S3Object> resultsStream = result.contents().stream();
```

Please let us know what you think!

**Comment by debora-ito** [comment]
Hi @gorzell, since the SDK team is concentrating efforts on V2 new features and pagination is already available in V2, they decided to not implement this one in V1. I'll go ahead and close this one.

Please feel free to reach out if you have further questions.
