### ISSUE TITLE
Deserializing PrimaryKey (DynamoDB) with Jackson

### ISSUE THREAD

**Issue by cyberjoac** [aws/aws-sdk-java#1078]
An error is thrown when I'm trying to deserialize PrimaryKey (serialization goes well with Jackson).

I'm trying the following:

```
Myobject myObject =(Myobject) mapper.convertValue(obj.get("myObject"), MyObject.class);
```
with object:
```
public class MyObject {

    private PrimaryKey primaryKey;
    private String attributeName;
    private String metaDataFieldName;
    private long numRepeated;
```
And getting the error:

`java.lang.IllegalArgumentException: (was java.lang.UnsupportedOperationException) (through reference chain: com.scanner.dynamodb.DynamoDBDataLink["primaryKey"]->com.amazonaws.services.dynamodbv2.document.PrimaryKey["componentNameSet"]->java.util.LinkedKeySet[0])`

Thanks for your help

**Comment by kiiadi** [comment]
@cyberjoac what is `mapper.convertObject` I don't believe that's a method on the `DynamoDBMapper` - can you provide a full code sample that reproduces this?

**Comment by kiiadi** [comment]
Closing due to lack of response, please re-open if you feel this is an issue with the Java SDK.
