### ISSUE TITLE
Client Builds for Global Services

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1081]
Hi
I moved to the newer SDK version
and started using the new client Build pattern
at this style I'm forced to provide a Region before build() of the Service Client. fine.
but what bout the global services, e.g. Identity Management? (e.g. AmazonIdentityManagementAsyncClient)
for those types Region is irrelevant!
same goes for Rout53

Am I missing something? Please help

**Comment by shorea** [comment]
Global services are kind of a deprecated concept in the SDK. For these existing services though you can supply any region and all calls will be directed to the global endpoint.

Generally we recommend sourcing the region from your environment. In that case no explicit region is needed. See http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html

**Comment by bmagic39** [comment]
you recommended "supply any region and all calls will be directed to the global endpoint"
not working!! 
working with AmazonRoute53DomainsAsyncClientBuilder and assigning any region produces the error 
com.amazonaws.SdkClientException: Unable to execute HTTP request: route53domains.eu-west-1.amazonaws.com

**Comment by shorea** [comment]
Not sure why but route53 domains is not marked as the partition endpoint so correct that won't work. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1072

For that you'll have to explicitly configure us-east-1
