### ISSUE TITLE
Error to create FIFO Queues

### ISSUE THREAD

**Issue by cunhazera** [aws/aws-sdk-java#1084]
I'm following this tutorial: http://docs.aws.amazon.com/pt_br/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-create-queue.html

But the class `SendMessageRequest` does not contais the `messageGroupId` attribute anymore, so I can not create my FIFO Queue.

I'm using the 1.11.109 SDK version at maven.

**Comment by spfink** [comment]
Are you sure that you are using 1.11.109 of SQS?

Looks like messageGroupId is still available:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/SendMessageRequest.java#L232

**Comment by cunhazera** [comment]
I was using this maven dependency:

```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk</artifactId>
    <version>1.11.109</version>
</dependency>
```

**Comment by kiiadi** [comment]
It's possible that another dependency is pulling in a different version of the SQS client. Can you run `mvn dependency:tree` from your project and paste the output? That should help debug which version of the SQS client is actually being resolved.

The other thing that might be interesting to do is to see where the `SendMessageRequest` object is actually being loaded - to determine this can you do:

```java
System.out.println(SendMessageRequest.class.getProtectionDomain().getCodeSource().getLocation())
```

**Comment by kiiadi** [comment]
@cunhazera were you able to get to the bottom of this?

**Comment by cunhazera** [comment]
@kiiadi I'm sorry for the delay. I just changed the project setup, so it's not a problem anymore.
