### ISSUE TITLE
working with AmazonRoute53DomainsAsyncClientBuilder

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1085]
at the new version while working with AmazonRoute53DomainsAsyncClientBuilder
and as recommended at issue#1081 by setting any region (while Rout53 is global service and not related to region)
I get the error:
com.amazonaws.SdkClientException: Unable to execute HTTP request: route53domains.eu-west-1.amazonaws.com

what shall I do!!!

**Comment by spfink** [comment]
You need to set a region or endpoint with all services based on the regions available for that service. For Route 53 refer to our regions and endpoints page:

http://docs.aws.amazon.com/general/latest/gr/rande.html#r53_region

us-east-1 is the only supported region. Set that region and see if it works.

**Comment by spfink** [comment]
Closing out due to inactivity. Feel free to reopen if the above does not work for you.
