### ISSUE TITLE
Feature Request: Consider a new approach for AmazonS3#getObject

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1088]
The `S3Object` is unnecessarily tough to work with because it has a close method and it's #getObjectContent result also has a close method. Closing one will close the other since they use the same connection.

While I do appreciate being saved a round trip to S3, it comes at the expense of a simple way to manage resources. Also, of course, you can only call #getObjectContent once which makes retries complex. What might have been nicer is an `S3Object` that is itself an `InputStream`. This would be similar to how `FileInputStream` has a `getFD` method. `S3ObjectInputStream` could have a #getMetaData method. Maybe even a reset that can make a new request. 

I think many first time AWS SDK users don't think of S3Object as an open connection given it's name and it's #getObjectContent method. 

Low priority but I've seen it bite a few people, especially when deciding to pass around an `S3Object` vs an `S3ObjectInputStream`.

**Comment by CWindatt** [comment]
Documentation on the S3Object itself would be helpful in understanding its use.  The s3Client.getObject() method explains that the returned object contains an open connection, but the object does not.  There is a note on the getObjectContent(), but in our case we were only looking at the object's metadata.

**Comment by debora-ito** [comment]
@rdifalco @CWindatt 

The SDK team has reviewed the feature request list for V1 and decided to not implement this since they're concentrating efforts on V2 new features. 

The `getObject` operation was completely  redesigned in V2 so please check it out and send us any feedback you might have.
