### ISSUE TITLE
Add Version and other information to the MANIFEST.MF file

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-sdk-java#1093]
In response to https://github.com/aws/aws-sdk-java/pull/1091

Would be good include additional metadata about the SDK in each Jar's MANIFEST.MF file such as

```
Implementation-Version:  
Implementation-Title: 
Implementation-Vendor-Id:  
Specification-Title: 
Specification-Version: 
```

**Comment by frekele** [comment]
Default headers in a manifest:
https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html

Example:

| Header                                      | Value                                                        |
| --------------------------------- | -------------------------------------------- |
| Manifest-Version:                     |  1.0                                                            |
| Specification-Title:                   |  AWS Java SDK for Amazon S3                  |
| Specification-Version:              |  1.11.113                                                    |
| Implementation-Title:              |  AWS Java SDK for Amazon S3                  |
| Implementation-URL:               | https://aws.amazon.com/sdkforjava         |
| Implementation-Vendor-Id:     |  com.amazonaws.s3                                   |
| Implementation-Version:         |  1.11.113                                                    |

It would also be interesting to add build information:

| Header                                | Value                                                                                                |
| ----------------------------- | ----------------------------------------------------------------------- |
| Build-Jdk:                            |  1.8.0_121                                                                                         |
| Built-By:                              |  frekele                                                                                             |
| Created-By:                         |  Apache Maven 3.3.9                                                                       |
| Java-Vendor:                       |  Oracle Corporation                                                                         |
| Java-Version:                       |  1.8.0_121                                                                                         |
| Os-Arch:                              |  amd64                                                                                             |
| Os-Name:                            |  Linux                                                                                                |
| Os-Version:                          |  3.16.0-4-amd64                                                                               |
| Scm-Connection:                 |  scm:git:git@github.com:aws/aws-sdk-java.git/aws-java-sdk-s3     |
| Scm-Url:                               |  https://github.com/aws/aws-sdk-java.git/aws-java-sdk-s3            |
| Scm-Revision:                      |  2e3d75087c97a3d1e86df6b2c6a7c83aa0416c36                            |

**Comment by debora-ito** [comment]
Hi @frekele, the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. 

It's still being considered for V2. I'll go ahead and close this.

Please feel free to reach out if you have further questions.
