### ISSUE TITLE
AWS Lambda: Support for region ap-south-1 not reflected in SDK

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#1095]
Similar to #767: The recently added availability of [AWS Lambda in Asia Pacific (Mumbai)](https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-available-in-asia-pacific-mumbai-region/) is not reflected in the SDK's [`endpoints.json`](https://github.com/aws/aws-sdk-java/blob/1.11.113/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L851) yet.

This affects UX in terms of e.g. the added region not being returned by `RegionUtils.getRegionsForService()` (actual usage of the region by setting it explicitly to the result of `RegionUtils.getRegion("ap-south-1")` does work as expected)

**Comment by kiiadi** [comment]
@sopel unfortunately there is often a delay in getting the region/service data into the SDK. I'll follow-up with the service team to see when we're planning to get this data populated. In the meantime please refer to this tracking issue to make the data available more dynamically : https://github.com/aws/aws-sdk-java/issues/948

Please feel free to +1 it to register your interest in this feature.

**Comment by sopel** [comment]
Thanks @kiiadi, I've already registered my interest there :)

While that would also be useful, this is really just about the SDK itself:

Usually newly supported regions for a service show up in pretty much the next SDK release. However, we've encountered a couple of times that a resp. service update had not ended up in the SDK at all until someone reported it (see e.g. #767, #677, #621, #403), suggesting that there are manual steps involved. So given there have already been two SDK releases since, I figured I'd best file an issue indeed (from that angle I'll mention that this also affects Amazon API Gateway).

Are you implying that the endpoints exposed via the SDK are meanwhile generated automatically from upstream metadata so that the information will always be up to date in a timely fashion? In case, I'll happily refrain from filing such a 'reminder' issue next time around ;)

**Comment by kiiadi** [comment]
@sopel no please do file these - that's absolutely fine. There are some manual steps involves when a service launches in a new region as you can imagine - hence why sometimes there's a delay in getting the details into the SDK.

The pointer to #948 was really more to say that hopefully in future there'll be a better way 😄 rather than having to upgrade SDK versions to get the new info.

**Comment by kiiadi** [comment]
@sopel should be there now as of 1.11.114
