### ISSUE TITLE
AWS S3 Download  SdkClientException help

### ISSUE THREAD

**Issue by studioam** [aws/aws-sdk-java#1098]
Hi, I'm usig the s3 Java SDK for a Multiple File downloads tool it works fine with files under 10GB, but when I try with a 150GB folder where I have some 30GB each files I have the following error:

        PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
      AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection.          This  is likely an error and may result in sub-optimal behavior. Request only the bytes     you need via a ranged GET or drain the input stream after use.

      PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
            AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection.              This is likely an error and may result in sub-optimal behavior. Request only the bytes            you need via a ranged GET or drain the input stream after use.
           apr 03, 2017 8:49:57 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
              AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP            connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
           apr 03, 2017 8:53:09 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
                         AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
            apr 03, 2017 8:53:09 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
                 AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
           apr 03, 2017 8:53:22 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
             AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
          apr 03, 2017 8:53:22 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
              AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
            apr 03, 2017 8:54:03 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
         AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
          apr 03, 2017 8:54:03 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
           AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
          apr 03, 2017 8:57:34 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
            AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
        apr 03, 2017 8:57:34 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
        AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
         apr 03, 2017 9:01:06 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
           AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
          apr 03, 2017 9:01:06 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
         AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
      apr 03, 2017 9:32:57 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
    AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
     apr 03, 2017 9:32:57 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
            AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
        apr 03, 2017 9:33:38 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
           AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
          apr 03, 2017 9:33:38 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
            AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
          apr 03, 2017 9:33:43 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
             AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
         apr 03, 2017 9:33:43 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
           AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
        apr 03, 2017 9:34:12 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
            AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
           apr 03, 2017 9:34:12 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
         AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
        apr 03, 2017 9:34:16 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
         AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
     apr 03, 2017 9:34:16 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
       AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
         apr 03, 2017 9:56:26 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
         AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
            apr 03, 2017 9:56:26 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
             AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
         apr 03, 2017 9:56:26 PM com.amazonaws.services.s3.internal.S3AbortableInputStream close
       AVVERTENZA: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
         apr 03, 2017 9:56:26 PM com.amazonaws.services.s3.internal.ServiceUtils retryableDownloadS3ObjectToFile
          INFORMAZIONI: Retry the download of object Moonlight_FTR-1_S_EN-IT_51_2K_LR_20170127_AM/Moonlight_FTR-1_S_EN-IT_51_2K_LR_20170127_AM_01.mxf (bucket moonlightenit)
     com.amazonaws.SdkClientException: Unable to store object contents to disk: Read timed out
	at com.amazonaws.services.s3.internal.ServiceUtils.downloadToFile(ServiceUtils.java:315)
	at com.amazonaws.services.s3.internal.ServiceUtils.downloadObjectToFile(ServiceUtils.java:272)
	at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:404)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1458)
	at com.amazonaws.services.s3.transfer.internal.DownloadPartCallable.call(DownloadPartCallable.java:59)
	at com.amazonaws.services.s3.transfer.internal.DownloadPartCallable.call(DownloadPartCallable.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
         Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:200)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:115)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.amazonaws.services.s3.internal.ServiceUtils.downloadToFile(ServiceUtils.java:309)

can anyone help to find the source of error?

**Comment by millems** [comment]
Hi, what major and minor version of the SDK are you using?

**Comment by kiiadi** [comment]
Closing due to lack of response, please feel free to re-open if you feel this is a bug with the SDK.
