### ISSUE TITLE
API Gateway generated clients do not support date time types

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java#1099]
Customers currently have to use Strings to represent date times for their API gateway services if they are generating a Java SDK. The API gateway code generator should be updated to support date types.

**Comment by tasneem93** [comment]
I am facing the same issue where I need to generate SDK with date-time format. We are using mapstruct in our code base to map the properties and it is working fine in EBS. But cannot generate SDK in API Gateway for client to use. 

Will really appreciate if we can find out an ETA on this. Thanks in advance.

**Comment by tasneem93** [comment]
Is there any update on this millems? This is blocking us in developing. Please let me know. Thanks in advance.

**Comment by ben-benson** [comment]
This is a significant blocker to our development teams as well.  We are using swagger OpenAPI spec to generate code and support for date-time format is critical or we cannot handle dates.

**Comment by tasneem93** [comment]
@shorea any update on this? We really are waiting on this before we can go to Production. Please let us know. Thanks.

**Comment by shorea** [comment]
Just a quick update. I've implemented support for this in the SDK. It does require a deployment to the API Gateway service so it might be next week before it's live. I'll update this issue when I know more.

**Comment by tasneem93** [comment]
That's great @shorea ...Please let us know when it goes live.

**Comment by shorea** [comment]
Checked us-west-2 this morning and it's out there. Not sure if it's made it to every region yet but it should be deployed worldwide soon if not. Closing this issue.

**Comment by cartick** [comment]
Looks like right now it only supports java.util.Date api.
Is this change also supposed to support java 8 DateTime api ?
If not when can we expect this feature ?

**Comment by shorea** [comment]
We'll be supporting the DateTime natively in [SDK v2](https://github.com/aws/aws-sdk-java-v2), for now it should be a pretty easy conversion from the legacy date to the new DateTime API.
