### ISSUE TITLE
Hang in SDK with parallel uploads under load

### ISSUE THREAD

**Issue by ajfabbri** [aws/aws-sdk-java#1102]
We have reproduced a hang in the aws-sdk-java version 1.11.86.  It takes some time to reproduce but is pretty reliable.

Support case ID 2115933851.

The original reproduction was using Hadoop, but we've created an SDK-only test that reproduces the bug here:

https://github.com/ajfabbri/awstest

**Comment by ajfabbri** [comment]
Run the included test for awhile.. At some point it should hang.  Using jstack or a debugger you'll see a thread stuck in com.amazonaws.services.s3.transfer.internal.CopyImpl.waitForCopyResult() and never getting woke up.

**Comment by ajfabbri** [comment]
Filed a Hadoop bug [here](https://issues.apache.org/jira/browse/HADOOP-14283), since that project depends on this.

**Comment by dagnir** [comment]
Good news, we've found the root cause to be a subtle scheduling issue with the way `CopyMonitor#setFuture` works. We are considering possible solutions now.

**Comment by dagnir** [comment]
This is fixed upstream. It should be available in our next release which will probably happen later today.

**Comment by dagnir** [comment]
Hi @ajfabbri this is fixed in [1.11.119](https://github.com/aws/aws-sdk-java/blob/1.11.119/CHANGELOG.md#bugfixes). Closing this issue.
