### ISSUE TITLE
Feature Request: Bandwidth Throttling for S3 Transfer Manager

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java#1103]
The S3 transfer manager should be able to limit (in some way) the bandwidth used when uploading multiple files to prevent saturating the network on a host. This is similar to the feature discussed in this blog post: https://www.instaclustr.com/blog/2016/04/20/cassandra-backups-using-aws-transfermanager/

**Comment by arunagrawal84** [comment]
+1
I am making some changes to Netflix/Priam for backups and was bummed to find that this is not a standard feature yet. It makes sense as S3 is used for backups and while doing a backup you don't want to throttle the bandwidth of the instance.

**Comment by johnbonds** [comment]
+1
Using Amazon S3 to do database backups. When transferring the backup to S3, it uses up all available bandwidth. I also use Galera so the combination of the 2 causes actual SQL errors on my other nodes.

**Comment by millems** [comment]
We do not currently intend to implement this in V1 of the Java SDK. Keep an eye out on https://github.com/aws/aws-sdk-java-v2/issues/37 for this functionality.
