### ISSUE TITLE
Executor services use default ThreadFactory, resulting in unhelpful thread names in dumps

### ISSUE THREAD

**Issue by spatula75** [aws/aws-sdk-java#1104]
When debugging thread leaks and thread-pool leaks, it is very valuable to have thread names which are meaningful and provide some indication as to their origin and purpose.

A variety of classes in the SDK call Executors.new.*executor, which returns a java.util.concurrent.ThreadPoolExecutor (or subclass) using the DefaultThreadFactory.  The DefaultThreadFactory in turn names threads using the naming scheme pool-{pool number}-thread-{thread number}.

In the event of SDK classes containing these executors getting garbage collected, the executors get orphaned (but are still alive and uncollectable), making it difficult/impossible to detect from a heap dump where the executors came from.

A substantial improvement would be to provide a CustomThreadFactory, which takes as an argument a naming prefix, then using that CustomThreadFactory everywhere an Executor is created (using the static methods that accept a ThreadFactory as the last argument); in this way, from a thread dump of the JVM, it will be possible to tell the origin and purpose of each thread allocated by the SDK.

One very good example of this in action is the org.springframework.scheduling.concurrent.CustomizableThreadFactory in Spring.

This would really help in cases where it might not be immediately obvious to a casual user of the SDK that a class is going to create a thread pool; for example, in the InstanceProfileCredentialsProvider.  In the event of a leak, getting a thread dump would give the user an immediate idea of where to look for the problem.

**Comment by millems** [comment]
We've made this change in V2, but don't intend to make it in V1. Sorry for the inconvenience.
