### ISSUE TITLE
EC2MetadataUtils#getItems may yield `null`, causing NPEs

### ISSUE THREAD

**Issue by Stephan202** [aws/aws-sdk-java#1110]
The method `EC2MetadataUtils#getItems(String, int, boolean)` returns a `List<String>` but [may yield `null`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L388). Some callers [handle](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L297) this case, while others [don't](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L337). We hit this issue while running some integration tests using [Travis CI's Trusty build environment](https://docs.travis-ci.com/user/trusty-ci-environment/):
```
        ...
Caused by: java.lang.NullPointerException: null
        at com.amazonaws.util.EC2MetadataUtils.getNetworkInterfaces(EC2MetadataUtils.java:337)
        ...
```

(Personal opinion: I think the `AmazonClientException` should either be bubbled up (but I guess that's a backwards-incompatible change), or the `null` should be replaced with an empty list. Nullable collections should be avoided.)

**Comment by shorea** [comment]
Should be able to change this. I don't think anyone should be relying on an NPE to be thrown for correct behavior of their application.

**Comment by Stephan202** [comment]
@shorea, any update on this ticket? If you sketch a preferred solution I'm willing to try and provide a PR for this.

**Comment by Stephan202** [comment]
(Note that Travis CI will make Trusty their default distribution [next Tuesday](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming). On that distribution, the NPE is triggered both with containerized and "sudo enabled" environments. So it might be quite a few more people will hit this issue soon.)

**Comment by shorea** [comment]
Apologies for the delay @Stephan202 , finally got around to doing this. The team was uncomfortable making this change in getItems so instead I've updated all SDK consumers of the getItems method to handle potential nulls. This will be available in the next release of the SDK, version 1.11.205.

**Comment by Stephan202** [comment]
@shorea just tested 1.11.205 using our Travis CI build. Confirmed fixed :white_check_mark: .

**Comment by shorea** [comment]
Great! :)
