### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by carloslimasis** [aws/aws-sdk-java#1113]
When I tried to import the aws-sdk-java projects into to Eclipse I had the following problem in the aws-sdk-java-osgi module:

> Plugin execution not covered by lifecycle configuration: com.ruleoftech:markdown-page-generator-plugin:0.8:generate (execution: default, phase: process-sources)

I think that markdown-page-generator-plugin should be declared in the pluginManagement.

**Comment by zhangzhx** [comment]
Thanks for reporting this problem. I'm closing this issue in favor of the PR.
