### ISSUE TITLE
AwsProfileRegionProvider don't take Default profile

### ISSUE THREAD

**Issue by piclemx** [aws/aws-sdk-java#1115]
I have a default profile, when I try to use S3Client he fail on the `getRegion()` because we take a look at my `$AWS_HOME/config` and don't take the default when is there? This is normal?

**Comment by zhangzhx** [comment]
Hey @piclemx ,

Are you using the default constructor to instantiate the S3 client? In that case, it doesn't respect the default profile for the region.

We recommend you use the [AmazonS3ClientBuilder](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3ClientBuilder.java) to create new S3 client

`AmazonS3 s3Client = AmazonS3ClientBuilder.defaultClient();`

The client builder respects the default profile in the config file for seeking the region.

**Comment by piclemx** [comment]
Hi @zhangzhx, I'm using the `AmazonS3ClientBuilder.defaultClient();` and he don't find my default profile, but this is not the current `AWS_PROFILE` i'm using.

**Comment by zhangzhx** [comment]
Can you double check whether the environment your application is running in has `AWS_PROFILE` set? The Builder is respecting the `AWS_PROFILE` environment variable for the preferred profile to look for region.

And I just want to double check that you are using the latest SDK version, right ?

**Comment by piclemx** [comment]
My `AWS_PROFILE` env is not `default` and my SDK version is `1.11.86`

**Comment by zhangzhx** [comment]
Little confusion here:

So your `AWS_PROFILE` env is not set to `default`, but another one? If so, the S3 client would be using the profile `AWS_PROFILE` env specified.

[Here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/AwsProfileNameLoader.java#L53-L65) is the source code how the profile is retrieved.

To be short:
environment variable > system property > default profile name

So in your case, the env variable is prioritized for retrieving the profile name.

**Comment by piclemx** [comment]
thanks @zhangzhx
