### ISSUE TITLE
AWS Java SDK for J2ME (Micro Edition)

### ISSUE THREAD

**Issue by rlcomte** [aws/aws-sdk-java#1117]
We need the AWS Java SDK for Kinesis to work on J2M, as the eWON modems support this Java VM. Currently the SDK does not compile because java.lang.Enum is not available. Other classes may not be available as well.

**Comment by shorea** [comment]
It is very unlikely we will be able to support this, especially if not even enum is available. It may be possible to extract out the SigV4 signer or fork it to use only ME available classes and use just a normal HTTP client instead of the SDK.
