### ISSUE TITLE
Cross region S3 copy using TransferManager fails on getObjectMetadata

### ISSUE THREAD

**Issue by BartXZX** [aws/aws-sdk-java#1118]
I am trying to copy an Object from an S3 bucket located in eu-west-1 to a bucket located in eu-central-1.

Support told me to point the S3 client to the source region, but..
When using the S3 client in the source region I get: **The bucket is in this region: null** when copying.
When using the S3 client in the target region I get: The bucket is in this region: eu-west-1.
But the second one does not occur on the copy action but actually on the getObjectMetadata action.

The REST API actually specifies using the target region as endpoint so I went from there

> PUT /destinationObject HTTP/1.1
> Host: destinationBucket.s3.amazonaws.com
> x-amz-copy-source: /source_bucket/sourceObject
> ...

Now, I extended the TransferManager to be able to accept a second S3 client pointing at the source region and passing it to **TransferManager.copy(CopyObjectRequest, AmazonS3, TransferStateChangeListener)** to use when executing the getObjectMetadata and it works.

Support was not able to help me on this one, but this way does not seem to be the correct or 'intended' way. Am I missing something or is this action simply not yet properly supported in the Java SDK?

**Comment by BartXZX** [comment]
Note:
This problem seems to only occur when copying using the TransferManager.
When using the S3 client **AmazonS3.copyObject(String, String, String, String)** in the **target** region it does work.

**Comment by zhangzhx** [comment]
Thanks for reaching out to us for this issue. I can reproduce this problem. One workaround is to use the global S3 endpoint

`AmazonS3 client = new AmazonS3Client();`

But we are not encouraging this way to instantiate an S3 client. We'll fix this bug in our next release. Thank you for reporting this.

**Comment by zhangzhx** [comment]
I've taken a deeper look at this problem and find out that there is no a clean way to work around this right now. It's more like a feature request than a bug. We'll add this to our backlog and let you know once we release this feature for cross region copying in Transfer Manager.

**Comment by BartXZX** [comment]
Ok, thank you for your reply!

**Comment by varunnvs92** [comment]
@BartXZX 
As you mentioned when specifying region on the s3 client, you need to use the **TransferManager.copy(CopyObjectRequest, AmazonS3, TransferStateChangeListener)** method to copy objects across buckets in different regions. I agree its not clear right away. I can update the documentation to be more clear. But we don't have a clean solution to fix this issue in this version.

We will be releasing a v2 version of the SDK late this year in which we are looking at re-writing TransferManager. I will add a backlog item to have a better solution for this issue in v2. Thank you.

**Comment by varunnvs92** [comment]
One more thing, you mentioned in the first comment that "Support told me to point the S3 client to the source region".
I tested the operation with both low level s3 client and TransferManager, you need to point the S3 client to **destination region** and not source region.

**Comment by ruchika007** [comment]
I am struggling using the aws java sdk for copying s3 objects across different accounts, present in different regions. I am using `InitiateMultipartUploadRequest ` API and it seems working fine when both source & destination buckets are in same account & region.
Does anyone has faced the similar issue, or knows the solution for the same.
