### ISSUE TITLE
Add support for native marshal / unmarshal of Java 8 Time Constructs

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-java#1119]
Java 8's new LocalDateTime, LocalDate, LocalTime, and ZonedDateTime are slowly replacing instances of Joda time and the older java.util.Date.

Dynamo already supports automagic mapping of java.util.Date to and from string to support seamless marshaling and unmarshaling for storing instances of the class which is awesome but further support for the new java 8 standards would be welcome. 

For now there is a workaround to create a converter and annotate the field appropriately 

`@DynamoDBTypeConverted(converter = ZonedDateTimeConverter.class)` 

and implement the class as such:

    public class ZonedDateTimeConverter implements DynamoDBTypeConverter<String, ZonedDateTime> {
    
        @Override
        public String convert(final ZonedDateTime time) {
            return time.toString();
        }
    
        @Override
        public ZonedDateTime unconvert(final String stringValue) {
            return ZonedDateTime.parse(stringValue);
        }
    }

However there are two downsides to this. The code will need to be copy/pasted into each subsequent project that utilizes these new time constructs in lieu of java.util.Date and furthermore, when support for these classes is eventually added to Dynamo, each occurrence of a converter in each project for usages of the time constructs will need to be cleaned up and removed. 

Thus, the longer these classes go unsupported the more cruft code will be created as a result of their eventual implementation.

**Comment by kiiadi** [comment]
@tricksterbrewingdev unlikely we'll be able to do this in the current version of the SDK because we need to remain backwards compatible with Java 1.6 - we'll consider this for inclusion into our next major version.

**Comment by debora-ito** [comment]
Closing this as the team is concentrating efforts in V2 new features. As mentioned by @kiiadi, this will be considered for SDK for Java V2.
