### ISSUE TITLE
Invalid Request Parameters

### ISSUE THREAD

**Issue by nikthakkar** [aws/aws-sdk-java#1123]
I'm also facing the same issue referred here #971. Some of the requests are failing saying InvalidParameter Exception.
I still couldn't figure out as to why they are failing. I'm using a local folder to supply the images for comparing them against the first image in the folder.
Any directions in what causes/reasons result in failing of a request would be very helpful.
P.S: All the images are under the limitations listed [here](http://docs.aws.amazon.com/rekognition/latest/dg/limits.html).

**Comment by kiiadi** [comment]
@nikthakkar this is most likely not an SDK issue, like #971 this sounds like service-side logic - so you might be better off following our advice for getting help from service teams (i.e. posting on http://stackoverflow.com/ with the service tag [[amazon-rekognition](http://stackoverflow.com/questions/tagged/amazon-rekognition)] and/or opening a [support](https://console.aws.amazon.com/support/) ticket through the AWS Console).

That said, let's see if we can help - can you provide the following additional information:
* a code sample that reproduces the error
* the full stack-trace
* wire logs (see [here](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html) for enabling wire logs).

**Comment by kiiadi** [comment]
Closing due to lack of response, please re-open if you feel this is an SDK issue.
