### ISSUE TITLE
Where is RdsIamAuthTokenGenerator?

### ISSUE THREAD

**Issue by marcy-terui** [aws/aws-sdk-java#1126]
Hi SDK team,

I want to know about the implemetation of IAM Database Authentication for MySQL.
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

However, I could not find `RdsIamAuthTokenGenerator` in this repository.

Please tell me the location of the code.
Or, Does it have any mistakes in the document?

**Comment by stevesloka** [comment]
I was just trying the same, I think it's not available yet until 4/26: 

> The version of the AWS SDK for Java described below is not yet available. The updated SDK will be available on 26 April 2017.

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Getting

**Comment by kiiadi** [comment]
@marcy-terui @stevesloka plan is to release this today - still waiting on final confirmation from the service team.

**Comment by marcy-terui** [comment]
@stevesloka @kiiadi Oh, I see. I'm looking forward to the release. Thanks!!
