### ISSUE TITLE
Simplify ChangePasswordRequest exceptions

### ISSUE THREAD

**Issue by markwoon** [aws/aws-sdk-java#1130]
`AWSCognitoIdentityProvider..changePassword()` has a check to make sure that `previousPassword` and `proposedPassword` have length greater than 6.  When this happens, it throws an `InvalidParameterException`. 

Please throw `InvalidPasswordException` when there's a problem with the `proposedPassword`.  This would match what would happen if the password is too short according to the user pool's password strength requirements.

Please throw `NotAuthorizedException` when there's a problem with `previousPassword`. 

This would simplify the error conditions that needs to be checked.

**Comment by kiiadi** [comment]
@markwoon these exceptions are thrown by the Cognito IDP service as part of their public facing [API](http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ChangePassword.html); the SDK simply unmarshalls the service response into Java POJOs (or Exceptions). You can request the change to the API to the service team directly (by raising a Support Case through the AWS Console and/or asking them directly on stack-overflow [amazon-cognito](http://stackoverflow.com/questions/tagged/amazon-cognito)), however given the change in behaviour it may not be possible to do this in a way that is backwards compatible.
