### ISSUE TITLE
SDK and cli mismatch on EC2 describe-instances with parameters empty

### ISSUE THREAD

**Issue by hgontijo** [aws/aws-sdk-java#1131]
Hello,

We have a case where DescribeInstancesRequest#withInstanceIds() is filled with an empty list, then call AmazonEC2#describeInstances(request) and that's causing the result to return all EC2 instances from our account. I noticed the AWS EC2 cli has a different behavior which requires setting a valid value whenever using the instance-ids parameter:

```shell
$ aws ec2 describe-instances --instance-ids ''
An error occurred (MissingParameter) when calling the DescribeInstances operation: The request must contain the parameter InstanceId
```

What's the expected behavior of this SDK whenever the AmazonEC2#describeInstances is called with an empty list defined on DescribeInstancesRequest#instanceIds?

**Comment by kiiadi** [comment]
Looking at the EC2 [API](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) reference, InstanceId.N is an optional field. If you look at the CLI debug logs, you'll see it actually tries to send an "InstanceId.1": "" when you set the instance as above.

```
aws ec2 describe-instances --instance-ids '' --debug
```

Tries to make this request:

```js
{'body': {'Action': u'DescribeInstances', 'Version': u'2016-11-15', u'InstanceId.1': u''}
```

The Java SDK iterates the list that's passed to add Instance.1, Instance.2 etc - if the list is empty then no Instances and the parameter is not passed.

**Comment by hgontijo** [comment]
That makes sense to me. Thanks!
