### ISSUE TITLE
WaiterHandler methods are never called when cloud formation stack succeeds

### ISSUE THREAD

**Issue by harschware** [aws/aws-sdk-java#1134]
I have created an example to demonstrate the issue here:
https://github.com/harschware/aws-delete-stack

To demonstrate:
```
export VPC_ID=<your VPC>
./create-stack.sh
# verify you have a new stack called 'AwsDeleteStackS1'
mvn clean install
java -jar target/aws-delete-stack-1.0.0.one-jar.jar App
```

After running code you will see 'Check status of delete operation' appear repeatedly, even after stack is gone.  Note that the log messages in the WaiterHandler will never appear.

**Comment by kiiadi** [comment]
@harschware looks like you aren't passing the stack-name to the `DescribeStacksRequest` object in your waiter here: https://github.com/harschware/aws-delete-stack/blob/master/src/main/java/App.java#L55

If the stack-name is not passed then no stack information is returned from the describe request.

Added `withStackName(STACK_NAME)` to your sample code and it works.

**Comment by harschware** [comment]
sometimes it just takes a second set of eyes...  thanks for the help!

**Comment by harschware** [comment]
I thought I saw other Describe methods throw exception when the name wasn't found (maybe security groups)..   should it throw an exception if no stack name is given?

**Comment by kiiadi** [comment]
@harschware potentially - but that would be a change in the service API rather than the SDK specifically. I agree the behaviour is a little unexpected.
