### ISSUE TITLE
Libraries not found to update samples code

### ISSUE THREAD

**Issue by anandhs** [aws/aws-sdk-java#1136]
Hi, 
I would like to submit a patch to upgrade Samples code for AmazonKinesis to include examples from Kinesis V2 API.  The samples code seems to be looking for a `../../lib` and `../../thirdparty/` folders for other jars.  These directories don't exist on the forked repos.   
How can i ensure to submit a patch on samples w/o these directories.  ?

**Comment by dagnir** [comment]
Hi @anandhs, these libraries are only present when you download the SDK through the [ZIP distribution](https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip).
