### ISSUE TITLE
aws-kms signature version?

### ISSUE THREAD

**Issue by sixcorners** [aws/aws-sdk-java#1138]
The javadoc says
> If you are uploading AWS KMS-encrypted objects, you need to specify the correct region of the bucket on your client and configure AWS Signature Version 4 for added security. For more information on how to do this, see http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version

and that website says  
> For all AWS regions, AWS SDKs use Signature Version 4 by default to authenticate requests. When using AWS SDKs that were released before May 2016, you may be required to request Signature Version 4 as shown in the following table:

So which is it? Does the SDK know about the signature thing or not? If it is default on then can't the call to action in the javadoc be removed?

**Comment by dagnir** [comment]
Actually, looking at this again, I think it's fine to leave this in here. It's possible users on 1.11.x are still using Signature Version 2, in which case this documentation would still be helpful to have.

**Comment by sixcorners** [comment]
Could something be added to say that the version of the SDK we are currently looking at defaults to version 4? Or maybe that versions after x default to 4? Or maybe change your versions to be based on dates (like docker and ubuntu releases)?

**Comment by shorea** [comment]
This has been updated to 

>For all AWS Regions, AWS SDKs use Signature Version 4 by default to authenticate requests. When using AWS SDKs that were released before May 2016, you may be required to request Signature Version 4 as shown in the following table:

which is more clear that SDKs now default to SigV4
