### ISSUE TITLE
Default retry count of S3SimpleCopy

### ISSUE THREAD

**Issue by bgayathri** [aws/aws-sdk-java#1141]
Hi -

We have an application that does both simplecopy and multipartcopy based on the file size.

Recently we are seeing the below error pop up when the simplecopy operation was called,

Error:File Copy Failed. We encountered an internal error. Please try again. (Service: Amazon S3; Status Code:
 200; Error Code: InternalError; Request ID: 1973604A192BFEF2) ]

We haven't introduced any retry count within the application.

Could we please know what the default retry count is for both performS3SimpleCopy & performS3MultiPartCopy?

What do you recommend us to do in this kind of situations?

**Comment by dagnir** [comment]
Hi, are you using a custom wrapper around the S3 client? I'm not familiar with `performS3SimpleCopy` and `a performS3MultiPartCopy`as they do not appear in our codebase.

**Comment by bgayathri** [comment]
`    public String performS3SimpleCopy(AmazonS3 s3client, String srcBucket, String srcobjKey, String desBucket, String destKeyName)
            throws AmazonServiceException, AmazonClientException {
        try {
            LOG.info("Calling PERFORM-S3-SIMPLE-COPY with input params srcBucket:{}, srcobjKey:{}, desBucket:{}, destKeyName:{}", srcBucket, srcobjKey, desBucket, destKeyName);
            CopyObjectRequest copyObjRequest = new CopyObjectRequest(srcBucket, srcobjKey, desBucket, destKeyName);
            ObjectMetadata objectMetadata = new ObjectMetadata();
            objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
            copyObjRequest.withNewObjectMetadata(objectMetadata);
            LOG.info("Copying object from srcBucket- {} ; srcobjKey- {} ; desBucket- {} ; destKeyName - {}", srcBucket, srcobjKey, desBucket, destKeyName);
            s3client.copyObject(copyObjRequest);
            LOG.info("Copying complete.");
            return "SUCCESS";
        } catch (Exception e) {

            LOG.error("Exception occured in performS3RegularCopy. Exception Message:{}." , e.getMessage() );
            e.printStackTrace();
            return e.getMessage();`

This is the sample code we are trying to use.

**Comment by dagnir** [comment]
Okay I see. Unfortunately, the SDK does not retry on 200 responses from the service so tweaking retry counts would not help in this case; so at the moment, if S3 sends back a 200 response for COPY but it's actually an error (like you're seeing) you would need to handle the retry yourself. Are you seeing this error for every COPY operation or just occasionally?

**Comment by bgayathri** [comment]
Yes, I'm seeing this occasionally. But  this cannot happen in our application as all files that come through has to be copied to the destination.

What is the root cause for these errors?

**Comment by dagnir** [comment]
Unfortunately, I don't have a good answer as to why S3 would send an error response back as a 200. This is clearly a bad design, but it's most likely that they need to keep this behavior in order to not break customers relying on it.

It's looks like we do automatic retrying for [`CompleteMultipartUpload`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L2927-L2928) so it's possible we can do something similar for COPY.

**Comment by bgayathri** [comment]
Thank you.

Is there an ETA of when this feature could be added? Thanks!!

**Comment by fernomac** [comment]
S3 does this for potentially-long-running operations, to avoid timeouts. They send a 200 immediately after receiving the request, then send an occasional space character (at the start of the response body) to keep the connection alive while they do the actual work, then send the actual XML payload when the operation completes/fails.

Yeah, it's a little funky. But it works. *shrug*

**Comment by bgayathri** [comment]
@fernomac @dagnir 

Until the automatic retry option is enabled for SIMPLECOPY, I'm planning to introduce  retry count within my code.

Please let me know if you have other recommendations.

**Comment by dagnir** [comment]
@fernomac Thanks for the context!

@bgayathri Yes catching the exception and executing a retry yourself will the the best path forward until this feature lands. I have not ETA yet since we need to prioritize this along with other feature requests and necessary development work.

**Comment by steveloughran** [comment]
This is a really silly question but is this still open? Asking as its been a while.

*do applications using this operation which which to be resilient to (transient) servers need to recognise and retry on 200 + InternalServerError*

This is through the the `TransferManager` I'm thinking of here

**Comment by steveloughran** [comment]
Note, causes: https://issues.apache.org/jira/browse/HADOOP-16188

I'm going to suggest you just close this as a WONTFIX. That way people's expectations will be correctly set. Thanks
