### ISSUE TITLE
.equals on Projection compares NonKeyAttributes lists (but they're unordered behind the scenes)

### ISSUE THREAD

**Issue by wryun** [aws/aws-sdk-java#1145]
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/model/Projection.java#L457

does a comparison of NonKeyAttributes lists. Unfortunately, if you use this method to check that the local definition of a dynamo table is the same as a remote one, it's likely to fail, since the 'NonKeyAttributes' ordering is not preserved.

i.e. I can create with NonKeyAttributes=[b, a], but a following describe will give me NonKeyAttributes=[a, b].

**Comment by dagnir** [comment]
Unfortunately this not something that we can change in the SDK as this would be behavior change; we use the same model generation scheme for all services, so for another service the order of members in the list could have significance. One solution for you if you need to support unordered comparison is a helper class to ensure ordered is ignored here.
