### ISSUE TITLE
Deprecated versisons

### ISSUE THREAD

**Issue by vedarad** [aws/aws-sdk-java#1149]
Isn't this deprecated already?
AmazonSQS sqs = new **AmazonSQSClient(credentials)**;

**Comment by dagnir** [comment]
Hi @vedarad yes the constructors for service clients are deprecated and use of the builders (e.g. [`AmazonSQSClientBuilder`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClientBuilder.html)) is preferred.

Why do you ask?

**Comment by vedarad** [comment]
Still I see this being used in aws-sdk-java examples!

**Comment by dagnir** [comment]
Okay got it. Sorry for the confusion. We'll work on getting those updated.

**Comment by shorea** [comment]
Samples are using the builder now
