### ISSUE TITLE
[StepFunctions] Can't make nullable paths in StateMachine

### ISSUE THREAD

**Issue by dstainer** [aws/aws-sdk-java#1150]
Contextually there is a huge difference with Paths with null and being omitted. By not allowing null paths to be deserialized into JSON the StateMachine does not comply with the users intent. 

**Is there, or can there be a way to make this behavior configurable?**

### Details

To give some additional clarity, hopefully, the documentation states the following regarding ResultPath:

> * If the ResultPath has the default value of $, it matches the entire input. In this case, the results of the state execution overwrite the input entirely and the input becomes available to pass along.
> * If the ResultPath is null, the results of executing the state are discarded and the input is untouched.

If I explicitly set result path to null, via the API, the resultant JSON has it completely omitted. Thus my state machine goes from ignoring the results completely to overwriting the input with the results.

The code causing this behavior is here (I think): [https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-stepfunctions/src/main/java/com/amazonaws/services/stepfunctions/builder/StateMachine.java#L39](url)

Here's some example code:

<pre>
    .state("my-state-name", taskState()
        .resource("my-lambda-function-arn")
        .inputPath("$.metadata")
        .resultPath(null)
        .outputPath("$")
        .transition(next("my-next-state")))
</pre>

Results in the following JSON:

<pre>
    "my-state-name" : {
      "Next" : "my-next-state",
      "Resource" : "my-lambda-function-arn",
      "InputPath" : "$.metadata",
      "OutputPath" : "$",
      "Type" : "Task"
    }
</pre>

Where what I would actually want here is the following JSON:

<pre>
    "my-state-name" : {
      "Next" : "my-next-state",
      "Resource" : "my-lambda-function-arn",
      "InputPath" : "$.metadata",
      "ResultPath" : null,
      "OutputPath" : "$",
      "Type" : "Task"
    }
</pre>

**Comment by shorea** [comment]
+1, sounds reasonable. I'll see what we can do to add this in a backwards compatible way.

**Comment by shorea** [comment]
We've got this in CR. Should be released this week.

**Comment by shorea** [comment]
This has been fixed in 1.11.130. Thanks for reporting! Let us know if you have any other comments or feedback on the fluent API.
