### ISSUE TITLE
Adding support for canada region to V1.9

### ISSUE THREAD

**Issue by stonefury** [aws/aws-sdk-java#1156]
Is it possible to tweak V1.9 to allow support for the new canada region ca-central-1? We are forced to stay at 1.9 for awhile and can't upgrade.  

Thanks

**Comment by spfink** [comment]
Is there anything we can do to help your migration to 1.11.x? We typically do not make updates to older versions of the SDK anymore.

**Comment by stonefury** [comment]
@spfink That's ok, one of our engineers was able to add support for the canada region to 1.9 to temporarily work around the problem. Thank you for your quick reply!
