### ISSUE TITLE
Can't specify custom AwsRegionProvider 

### ISSUE THREAD

**Issue by ejain** [aws/aws-sdk-java#1157]
When creating an AmazonS3Client via an AmazonS3ClientBuilder, there is no way to specify a custom AwsRegionProvider, i.e. there is no `AmazonS3ClientBuilder::withRegion(AwsRegionProvider)` method (analogous to `AmazonS3ClientBuilder::withCredentials(AWSCredentialsProvider)`).

**Comment by millems** [comment]
Other than for consistency, what would you want the region provider used for?

Credentials often need to be updated during the lifecycle of a single client, but that's not usually seen as a case for region.

**Comment by ejain** [comment]
I have a custom AwsRegionProviderChain that obtains the region from a system property if the region is not set in an environment variable (and before checking the profile or instance metadata). But there probably isn't much benefit in being able to do `s3ClientBuilder.withRegion(customRegionProvider)` rather than `s3ClientBuilder.withRegion(customRegionProvider.getRegion())`.
