### ISSUE TITLE
Request to update jackson version to avoid Jackson Deserializer security vulnerability

### ISSUE THREAD

**Issue by DaichiUeura** [aws/aws-sdk-java#1159]
Please look at https://github.com/FasterXML/jackson-databind/issues/1599 and the fix has been e.g. included in 2.7.9.1 release. Not sure if security issue happen with the functionalities AWS SDK provides. But AWS SDK client apps that depend on Jackson could want to use the new version(they might use version 2.6.6 come from AWS SDK).

**Comment by spfink** [comment]
We have to maintain backwards compatibility with Java 6 and thus we can't upgrade to Jackson 2.7+. Customers running on JDK 7+ can safely switch out to use Jackson 2.7+.

**Comment by skrzyneckik** [comment]
FYI in [the original issue's thread](https://github.com/FasterXML/jackson-databind/issues/1599) @cowtowncoder mentioned that jackson-databind v2.6.7.1 has been released to target it for Jackson's  v2.6.* users

**Comment by spfink** [comment]
@skrzyneckik, not sure if that was a request or just a statement, but we do already depend on 2.6.7.1
