### ISSUE TITLE
How do I read a file from AWS s3 using its presigned URL?

### ISSUE THREAD

**Issue by rtndp** [aws/aws-sdk-java#1161]
[Question] How do I read the contents of a file using its pre-signed Url. 

I am trying to do something similar to this - 

```
public void readFromS3(String bucketName, String key) throws IOException {
    S3Object s3object = s3.getObject(new GetObjectRequest(
            bucketName, key));
    System.out.println(s3object.getObjectMetadata().getContentType());
    System.out.println(s3object.getObjectMetadata().getContentLength());

    BufferedReader reader = new BufferedReader(new InputStreamReader(s3object.getObjectContent()));
    String line;
    while((line = reader.readLine()) != null) {
      // can copy the content locally as well
      // using a buffered writer
      System.out.println(line);
    }
  }
```

What are my options here?

Thanks for the help in advance!

**Comment by shorea** [comment]
You should just be able to use HttpsUrlConnection to download the file. Alternatively you can use an HTTP client like Apache.

https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/HttpsURLConnection.html
http://www.codejava.net/java-se/networking/use-httpurlconnection-to-download-file-from-an-http-url
