### ISSUE TITLE
EC2 DescribeVpcsRequest which does not return name of the vpc

### ISSUE THREAD

**Issue by somnath-infiverve** [aws/aws-sdk-java#1166]
Hi,
I am trying to fetch the details of the vpc using the vpc-id using aws-ec2-java sdk (1.11.99) but not getting name of the  vpc in response but able to get other details. 
**Code:**
```java
 vpcId=is my vpc id
amazonEC2Client =this is my amazon client.
  DescribeVpcsRequest describeVpcsRequest = new DescribeVpcsRequest();
 describeVpcsRequest.withVpcIds(vpcId);
       AsyncHandler<DescribeVpcsRequest, DescribeVpcsResult> asyncHandler = new AsyncHandler<DescribeVpcsRequest, DescribeVpcsResult>() {
            @Override
                public void onError(Exception exception) {
         
            }
                @Override
                public void onSuccess(DescribeVpcsRequest describeVpcsRequest,
                        DescribeVpcsResult describeVpcsResult) {
                    JsonArray vpcList= new JsonArray();
                    List<Vpc> vpcs = describeVpcsResult.getVpcs();
                    if(vpcs !=null && vpcs.size()!=0){
                    for (Vpc vpc : vpcs)
                    {
                     vpc.getCidrBlock();
                     vpc.getDhcpOptionsId();
                    }
                }
            } 
};
amazonEC2AsyncClient.describeVpcsAsync(describeVpcsRequest , asyncHandler );
```
So I could not find method for fetching name of the vpc  for DescribeVpcsRequest but i am able to get all the other details.

Thanks a lot in advance.

**Comment by millems** [comment]
To clarify, do you mean the name tag that is available through the AWS console? If so, are you able to find this data in one of the elements of [`vpc.getTags()`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/Vpc.html#getTags--)?

**Comment by somnath-infiverve** [comment]
@millems thank you for your valuable time and reply .Now I am able to find the required field using the vpc.getTags().

Thanks!
