### ISSUE TITLE
EC-2 : Unable to revoke security group rule

### ISSUE THREAD

**Issue by varun-kulkarni24** [aws/aws-sdk-java#1169]
Hi,
I am trying to revoke a rule by its security group name asynchronously. The onSuccess callback is getting called but the rule still appears on the aws ec2 console.

**MY CODE :** 
```java
RevokeSecurityGroupIngressRequest revokeSecurityGroupIngressRequest = new RevokeSecurityGroupIngressRequest();
//security group whose rules are to be revoked
revokeSecurityGroupIngressRequest.setGroupName("<my-group-name>");
//my-ip-permissions ->  [{IpProtocol: -1,UserIdGroupPairs: [],Ipv6Ranges: [],PrefixListIds: [],Ipv4Ranges: [{CidrIp: 219.91.160.90/32}]}]
revokeSecurityGroupIngressRequest
 .setIpPermissions(<ArrayList<IpPermission>>);
AsyncHandler < RevokeSecurityGroupIngressRequest, RevokeSecurityGroupIngressResult > asyncHandler = new AsyncHandler < RevokeSecurityGroupIngressRequest, RevokeSecurityGroupIngressResult > () {

 @Override
 public void onError(Exception exception) {
 //do something here
 }

 @Override
 public void onSuccess(
  RevokeSecurityGroupIngressRequest revokeSecurityGroupIngressRequest,
  RevokeSecurityGroupIngressResult result) {
 //do something here
 }
};
amazonEC2AsyncClient.revokeSecurityGroupIngressAsync(
 revokeSecurityGroupIngressRequest, asyncHandler);
```
Have also tried using security group name along with its id. But it did not work.
Alternative is to use security group id only. But I need by name too.

**Comment by varunnvs92** [comment]
Please enable wire log and post it here (DO NOT include Sensitive data).The SDK takes the information you provide and sends it to the service (EC2) in wire format. If wirelog shows SDK is properly sending the data, then the issue is with your application code or on service side. For non-SDK questions, we suggest using AWS forums or StackOverflow as you will get quick response from a broad community.

**Comment by varunnvs92** [comment]
Feel free to reopen if you still have the issue. Please provide wire log.
