### ISSUE TITLE
Urgency/Relevance of access key ID length extension from 32 to 128?

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#1171]
Hi Team,

Release [1.11.135](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111135-2017-05-24) reflects a possibly far reaching change regarding the extension of the IAM [AccessKey](http://docs.aws.amazon.com/IAM/latest/APIReference/API_AccessKey.html) datatype's  `AccessKeyId` field length that has seemingly also been applied to most/all other SDKs already, yet doesn't seem to be announced/documented  elsewhere so far:

> The unique ID and access key lengths were extended from 32 to 128

Can you already comment on when/how respectively longer access key IDs might be encountered at runtime?

* Of course, I'd hope that this will be a controlled and step wise rollout similar to how [longer EC2 resource IDs](https://aws.amazon.com/blogs/aws/heads-up-longer-ec2-ebs-resource-ids-coming-in-2016/) have been faded into production over the course of 2016, but given the sudden appearance as an 'API fact', I thought I'd better ask right away before our mutual customers run into it ;)

Many thanks,
Steffen

**Comment by varunnvs92** [comment]
This change is on service (AWS IAM) side. Based on the service side changes, we auto-update SDKs. The SDK team is not the right team to answer the affect of longer access ID lengths. Please reach out to AWS IAM team through AWS forums or console support. Thank you.
https://forums.aws.amazon.com/forum.jspa?forumID=76

Feel free to reopen if you think this is an SDK issue.
