### ISSUE TITLE
Can't fetch athena from maven central but all other jars fetch fine

### ISSUE THREAD

**Issue by sshorkey** [aws/aws-sdk-java#1178]
For the past few hours, whenever I attempt to fetch athena using maven, I end up with the following error:

[ERROR] Failed to execute goal on project <redacted>: Could not resolve dependencies for project com.<redacted>.<redacted>:<redacted>:war:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.amazonaws:aws-java-sdk-athena:jar:1.11.136: Could not transfer artifact com.amazonaws:aws-java-sdk-athena:jar:1.11.136 from/to central (http://repo.maven.apache.org/maven2): GET request of: com/amazonaws/aws-java-sdk-athena/1.11.136/aws-java-sdk-athena-1.11.136.jar from central failed: Connection reset -> [Help 1]

However, dozens of other artifacts from maven repo fetch fine. It's just this one that fails. So I assume there's something up with this project specifically.

I opened the link in my web browser (http://repo.maven.apache.org/maven2/com/amazonaws/aws-java-sdk-athena/1.11.136/), and attempted to download aws-java-sdk-athena-1.11.136.jar, and a strange thing happened: it started to download but once it was about half done the download speed dropped to zero and stayed there for quite a while, and then Chrome labelled the download "Failed - Network error".

**Comment by varunnvs92** [comment]
I tried it now and I am able to successfully import it into my maven project and also download the jar from maven central (used Chrome browser). I tried for both 1.11.136 and 1.11.138 versions.

It is possible you might have networking issues on your end or maybe maven central had issues at that time. Can you try again?

**Comment by varunnvs92** [comment]
Closing as this doesn't seem to be an issue. Feel free to re-open if you still have the issue.
