### ISSUE TITLE
InvalidOriginAccessIdentityException : Typo in the Documentation (Origin-Access-Identity)

### ISSUE THREAD

**Issue by cartick** [aws/aws-sdk-java#1179]
The [documentation](http://docs.aws.amazon.com/cloudfront/latest/APIReference/API_S3OriginConfig.html#cloudfront-Type-S3OriginConfig-OriginAccessIdentity) and [javaDoc](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/model/S3OriginConfig.html#withOriginAccessIdentity-java.lang.String-) for origin-access-identity states that, there needs to be a prefix for setting the origin access identity; "**origin-access-identity/CloudFront/**". 

SO, the above prefix needs to be added to the _**ID-of-origin-access-identity**_  

So, this "**_origin-access-identity/CloudFront/ID-of-origin-access-identity_** " needs to be passed to the [S3OriginConfig](docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/model/S3OriginConfig.html)-> [OriginAccessIdentity](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/model/S3OriginConfig.html#withOriginAccessIdentity-java.lang.String-) field.
`S3OriginConfig().withOriginAccessIdentity("origin-access-identity/CloudFront/" + "123456789")`

But the above configuration is causing this error:
`Exception in thread "main" com.amazonaws.services.cloudfront.model.InvalidOriginAccessIdentityException: The specified origin access identity does not exist or is not valid. (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidOriginAccessIdentity)`

When i changed "**origin-access-identity/CloudFront/**" to "**origin-access-identity/cloudfront/**" it worked fine. So, in the prefix, the "CloudFront" should be lowerCase ("cloudfront").
`S3OriginConfig().withOriginAccessIdentity("origin-access-identity/cloudfront/" + "123456789")`

**REF** : 
- https://forums.aws.amazon.com/message.jspa?messageID=749598
- http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/model/S3OriginConfig.html#withOriginAccessIdentity-java.lang.String-
- http://docs.aws.amazon.com/cloudfront/latest/APIReference/API_S3OriginConfig.html#cloudfront-Type-S3OriginConfig-OriginAccessIdentity

**Comment by varunnvs92** [comment]
Hi,
Thanks for reporting this issue. The docs are maintained by CloudFront team and I raised an internal ticket to them. I will get back you when I get a reply. You can also try reaching to service team directly on AWS Forums.
https://forums.aws.amazon.com/forum.jspa?forumID=46

**Comment by varunnvs92** [comment]
Service team has fixed the issue and updated their docs. 
http://docs.aws.amazon.com/cloudfront/latest/APIReference/API_S3OriginConfig.html#cloudfront-Type-S3OriginConfig-OriginAccessIdentity

Updating API docs i is a little tricky due to our internal process. Our Javadoc will be updated next week.

**Comment by cartick** [comment]
Ohh thats good to hear. 
Thanks for the quick reply.

**Comment by varunnvs92** [comment]
Javadocs are fixed too in recent release (1.11.42)
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/model/S3OriginConfig.html#withOriginAccessIdentity-java.lang.String-
