### ISSUE TITLE
This is why .withPathStyleAccess(true); is needed

### ISSUE THREAD

**Issue by garygriswold** [aws/aws-sdk-java#1182]
It appears that S3ClientOptions().withPathStyleAccess(true); has been deprecated.

From looking at stackoverflow there appear to be a number of people needing this feature.  My purpose in writing this is to emphasize the importance of this feature for some applications.

KEY THOUGHT: Path style URLs are a security feature, because the path becomes an entry in the header and is fully encrypted by SSL/TLS. While a virtual style URL is sent out to DNS unencrypted. I will use the example of an encrypted letter as a simile. 1. Sending a message to a personal domain is like sending a letter to a public address. 2. Sending a message to a virtual address is like sending a letter to a PO box. It is somewhat hidden, but with a little investigation the identity of the recipient is revealed. 3. Sending a message with a path address is like sending a letter to a general mail drop, which will distribute the letter, leaving no public way to identify the recipient.

**Comment by shorea** [comment]
+1, the feature isn't deprecated. Just that style of configuring it. We suggest to use the client builders instead, https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3ClientBuilder.java

I'll update the documentation to be more clear on why it's deprecated.

**Comment by garygriswold** [comment]
Got it.  Thanks!
