### ISSUE TITLE
Appears AWSSecurityTokenService Does Caching that I don't Understand

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1183]
I have some code to ensure that a Role Trust Policy has an external id. It looks like this:
```
    boolean isExternalIdPresent(String roleArn) {

        // Ensure it won't work unless we specify the external id
        AssumeRoleRequest request = new AssumeRoleRequest()
            .withDurationSeconds(900)
            .withRoleArn(roleArn)
            // make session name unique
            .withRoleSessionName("VerifyExternalIdPresent-" + UUID.randomUUID());

        try {
            // try to assume the role without an external id
            stsClient.assumeRole(request);
            return false; // should not have been able to assume the role.
        } catch (AWSSecurityTokenServiceException e) {
            if (e.getStatusCode() == 403) {
                return true;
            }

            throw e;
        }
    }

```
If I use a long lived STS client for this I get the same result before and after I remove the ExternalID Condition from the Role in the IAM Console. However, if I build a new client each time this method is called I get a timely result. i.e. after removing the ExternalID condition it turns false, if I put the ExternalID condition back in then it returns true.  When I use a long lived client, it will eventually work but it takes >5 minutes for the client to recognize the external id change to the Role. 

I've hunted around in the code but I can't figure out where a session might be cached. Even so, I'm setting a unique session name each time.  So I cannot figure out why creating a client each time gives me more timely results (i.e. recognizes the external id condition change sooner).

**Comment by rdifalco** [comment]
Steps to reproduce. Create a role with an external id. Run `isExternalIdPresent`. Remove the ExternalID condition from your Role and run `isExternalIdPresent` again. Make sure not to restart the Java process, maybe put it in main with a while System.in.read() loop.  Note that after you make the ExternaId change in the IAM Role that the fresh client returns one result while the long lived client returns a different result.
```
    private static final AWSSecurityTokenService stsClient = newClient();
    
    boolean isExternalIdPresent(String roleArn) {
        System.out.println("LONG LIVED  : " + isExternalIdPresent(roleArn, stsClient));
        System.out.println("FRESH CLIENT: " + isExternalIdPresent(roleArn, newStsClient()));

        return isExternalIdPresent(roleArn, stsClient);
    }

    boolean isExternalIdPresent(String roleArn, AWSSecurityTokenService client) {

        // Ensure it won't work unless we specify the external id
        AssumeRoleRequest request = new AssumeRoleRequest()
            .withDurationSeconds(900)
            .withRoleArn(roleArn)
            .withRoleSessionName("VerifyExternalId-" + UUID.randomUUID());

        try {
            client.assumeRole(request);
            return false; // should not have been able to assume the role.
        } catch (AWSSecurityTokenServiceException e) {
            if (e.getStatusCode() == 403) {
                return true;
            }

            throw e;
        }
    }
```

**Comment by shorea** [comment]
Apologies for the delay Robert, the SDK does not do any caching of service responses in the low level clients. We do some caching in the STS credential providers but that's a separate utility. My best guess is that the service is doing some caching for performance reasons, using the long lived client will just reuse the existing connection you have with the service which will land on the same host where the cache is populated. A fresh client will require a new connection to the service which will probably hit a different host which doesn't have the cached data. I suggest reaching out to the service team to get their SLAs around consistency for this API so that you may code appropriately around it. I know service like IAM are very eventually consistent (on the order of minutes sometimes) so perhaps STS is in a similar boat.

**Comment by dagnir** [comment]
Going to go ahead and close this since it looks @shorea answered the the question as far as SDK behavior.
