### ISSUE TITLE
Empty attribute values cannot be added to a DynamoDB table

### ISSUE THREAD

**Issue by arun-gupta** [aws/aws-sdk-java#1189]
Adding the following document to a DynamoDB table:

```
{
  "id_str": "1",
  "foo": ""
}
```

gives the following error:

```
One or more parameter values were invalid: An AttributeValue may not contain an empty string (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: HPH1B0TUMQKHF0Q7SOMEOR5CKJVV4KQNSO5AEMVJF66Q9ASUAAJG)
```

This is a common use case and already fixed for https://github.com/aws/aws-sdk-js/pull/1283#issuecomment-306954767[JavaScript SDK]. It has caused enough frustration among customers. This is evident at https://forums.aws.amazon.com/thread.jspa?threadID=90137&start=0&tstart=0 and https://news.ycombinator.com/item?id=13170746 and should be fixed.

**Comment by shorea** [comment]
How did they fix this in Javascript? This is a service side limitation, attribute values cannot be created with an empty string value (not sure the exact reasoning for this). What is the expected behavior in the SDK?

**Comment by arun-gupta** [comment]
Discussion at https://github.com/aws/aws-sdk-js/issues/833

**Comment by shorea** [comment]
Ah I see, I am not crazy about the idea of adding a flag to ignore empty strings and treat them as null. We did something similar for the DDB mapper and it's surprising, possibly dangerous behavior since null and empty string do not have the same semantics and we are subtly hiding a service side limitation. That said an opt in approach seems reasonable. I've reached out to the service team to see if it's possible to relax the constraint on empty string as I think that would be the best solution, I'll let you know what I hear and we can go from there.

**Comment by lamon** [comment]
+1

**Comment by shorea** [comment]
I've heard back from the DynamoDB team. They plan on supporting empty string sometime in 2018, no specific dates at the moment though. I'll update this issue if I get more information.

**Comment by jobetdelima** [comment]
Hello @shorea, Any update on when this would be supported?

**Comment by paulupendo** [comment]
@shorea Any update on this? What I experienced is that if I have optional values on my request payload, DynamoDB populates a digit into the values on retrieval. This lead to the inability to retrieve all the values from DynamoDB on my GET requests due to parsing errors originating from the values DynamoDB was populating the optional fields with. So I resolved to provide a default value whenever a field value is not supplied when saving data to DynamoDB. However, a solution to enable storing of empty strings, especially when the field is optional will be awesome.

**Comment by niraj-bpsoftware** [comment]
Any update on this?

**Comment by hounded** [comment]
any update?

**Comment by jhulfikarali** [comment]
We just started with DynamoDB and there you go, SURPRISE! I agree that empty doesn't make great sense in NoSQL but it would really help customers and would love to know if this has come to any fix after a year and a half wait time.

**Comment by portinos** [comment]
any update? still waiting :(

**Comment by mikechambers610** [comment]
This should be a quick and easy thing to fix on the DynamoDB side. Where are the AWS pros at!?

This makes it so that you can not have any optional fields... any work arounds or answers?

**Comment by VladMasarik** [comment]
I have still not found a solution. Just another entry into my "Why I never want to use AWS" list.
So I created this:
```
def removeEmptyString(dic):
    for e in dic:
        if isinstance(dic[e], dict):
            dic[e] = removeEmptyString(dic[e])
        if (isinstance(dic[e], str) and dic[e] == ""):
            dic[e] = None
        if isinstance(dic[e], list):
            for entry in dic[e]:
                removeEmptyString(entry)
    return dic

dictionaryWithEmptyValuesReplacedWithNone = removeEmptyString(dicrionaryWithEmptyValues)
```

It is far from perfect but it works.

**Comment by hounded** [comment]
@VladMasarik Yeah still waiting 
I use the same for my appsync resolver in VTL land
```apacheVTL
    #if ( $context.arguments.input.vid == "" )
    "update" : {
        "expression" : "REMOVE vid",
    },
    #else
        "update" : {
        "expression" : "SET vid = :vid",
        "expressionValues": {
            ":vid" : { "S": "${context.arguments.input.vid}" },
        }
    },
   #end
```
Still a crappy work around as in the front end I need to find if null and then equate it to "" to make my tables work correctly

**Comment by PVautour** [comment]
I used an option when initialising the document client. Works as expected except for null displaying as true. This is, however, expected behaviour in dynamodb. Here is the example from my javascript code:

const documentClient = new AWS.DynamoDB.DocumentClient({convertEmptyValues: true});

**Comment by japadgett2** [comment]
Same here.  const documentClient = new AWS.DynamoDB.DocumentClient({convertEmptyValues: true}) works for me.

**Comment by hugepanda** [comment]
It is already 2020 and I cannot believe aws still does not support empty string. Is this function in the plan or you guys just don't care? Please give us an answer here. Thank you.

**Comment by millems** [comment]
I've reached out to the DynamoDB organization again regarding this issue. 

DynamoDB is aware of the requirement and is still considering a fix for the issue. We know this response isn’t particularly satisfying, since the issue has been open for such a long time.

**Comment by mrajancsr** [comment]
i can believe after all these years this db can't support empty strings.

**Comment by fmontada** [comment]
My Solution 

```
const convertEmptyValues = Item => {
	return JSON.parse(
		JSON.stringify(Item, (key, value) => {
			if (value === "" || value === null || value === undefined) {
				return undefined;
			}
			return value;
		})
	);
};
```

**Comment by portcoding** [comment]
use update list to update the empty array
