### ISSUE TITLE
japicmp-maven-plugin plugin dependency is invalid in github

### ISSUE THREAD

**Issue by manyixu** [aws/aws-sdk-java#1191]
When i git clone the aws-sdk-java all the dependence is valid except the japicmp-maven-plugin. I can't find what‘s wrong.Maybe the japicmp-maven-plugin in github is invalid.

 <plugins>
          <plugin>
            <groupId>com.github.siom79.japicmp</groupId>
            <artifactId>japicmp-maven-plugin</artifactId>
            <version>0.5.0</version>
            <executions>
              <execution>
                <phase>verify</phase>
                <goals>
                  <goal>cmp</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <oldVersion>
                <dependency>
                  <groupId>com.amazonaws</groupId>
                  <artifactId>aws-java-sdk-snowball</artifactId>
                  <version>RELEASE</version>
                </dependency>
              </oldVersion>
              <newVersion>
                <file>
                  <path>${project.build.directory}/${project.artifactId}-${project.version}.jar</path>
                </file>
              </newVersion>
              <parameter>
                <onlyModified>true</onlyModified>
                <accessModifier>public</accessModifier>
                <breakBuildOnModifications>false</breakBuildOnModifications>
                <breakBuildOnBinaryIncompatibleModifications>false</breakBuildOnBinaryIncompatibleModifications>
                <onlyBinaryIncompatible>false</onlyBinaryIncompatible>
              </parameter>
            </configuration>
          </plugin>
        </plugins>

**Comment by shorea** [comment]
Seems to be in maven central, what problem are you seeing? Can you paste/attach the full maven build output?

https://search.maven.org/#artifactdetails|com.github.siom79.japicmp|japicmp-maven-plugin|0.5.0|maven-plugin

**Comment by shorea** [comment]
Closing this issue.
