### ISSUE TITLE
DescribeInstances not working for Canada Region

### ISSUE THREAD

**Issue by Halderian** [aws/aws-sdk-java#1194]
I update a small program yesterday the the current sdk version (1.11.146).
It collects some data from all instances worldwide. As we are using new regions i planned to code it future proof so i iterate over all regions and fire a "DescribeInstances" to the regions one by one. 
Of cause i get an error querying us-gov-1, but cn-central-1 throws an AmazonEC2Exception: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Request ID: ...)

All other regions are working well.

**Comment by dagnir** [comment]
Hi @Halderian `cn-central-1` is not a valid region. Did you mean `ca-central-1`? Can you please post [wire logs](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) of when you're seeing the error (be careful not to post sensitive information)?

**Comment by Halderian** [comment]
Hi @dagnir thanks for your answer. 

It seems like Canada Region was a missinterpretation on my side (for me cn => Canada). Actualy the error accur while sending requests to "cn-north-1" which seems to be the upcoming China Region. Thus I fully understand why the error is been thrown.

It would be great just to integrate Regions which are online and "usable" as it is for exampe for the upcoming Paris Region (not yet listed in Regions.java). 

Thanks a lot!

**Comment by dagnir** [comment]
Cool glad it was a quick fix.

**Comment by fernomac** [comment]
cn-north-1 has been live for quite a while now, but it has a separate account pool because ${reasons}. :( Trying to access it with credentials for a "normal" AWS region will fail, same as us-gov-*. Have a look at http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/RegionImpl.html#getPartition-- to future-proof against similar "special" regions.
