### ISSUE TITLE
AttributeValue.isBool() returns false if bOOL is set to false.

### ISSUE THREAD

**Issue by ahornbeck** [aws/aws-sdk-java#1197]
AttributeValue.isBool() returns false if bOOL is set to false.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/model/AttributeValue.java#L995

Is:
```
 public Boolean isBOOL() {
        return this.bOOL;
    }
```

Should be:
```
 public Boolean isBOOL() {
        return (this.bOOL == null);
    }
```

**Comment by dagnir** [comment]
Hi @ahornbeck, this is actually a quirk of our [code generator](https://github.com/aws/aws-sdk-java/blob/1.11.147/aws-java-sdk-code-generator/src/main/resources/macros/common/MethodDefinitionMacro.ftl#L206). It creates a `is[PropertyName]` method whenever it sees a member of a boolean type; it doesn't really have any knowledge of the semantics.

In this particular instance we really should have not have generated this, but it's too late to remove.

**Comment by ahornbeck** [comment]
comment and deprecate the method.

**Comment by dagnir** [comment]
As the code is auto generated with every release, we'd need to put the fix into the generator itself. We could certainly fix it there but we currently don't have support for deprecating individual generated methods, only members, which would deprecate all the getters/setters for the member. I'll go ahead and re-open this so we can investigate the best way to do this (probably an enhancement to `customization.config`.

**Comment by ahornbeck** [comment]
👍

**Comment by shorea** [comment]
This isn't something we will likely change for V1. For V2 our naming is more consistent as we don't have is/get/with/set prefixes so it's just bool().
