### ISSUE TITLE
How to add data in bulk to AWS managed ElasticSearch using java

### ISSUE THREAD

**Issue by kathulasandeep** [aws/aws-sdk-java#1200]
I wanted to bulk upload data in JSON format to AWS managed ElasticSearch using java. I cannot find any refernece for doing that in Github. Could someone help me?

**Comment by dagnir** [comment]
Hi @kathulasandeep the Amazon ElasticSearch SDK only deals with the creation and management of  your ElasticSearch clusters in AWS. You will need a client that works with the ElasticSearch REST API for interacting with ElasticSearch itself.

Here is some information on uploading data to ES using the `bulk` API: http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-upload-data.html

**Comment by dagnir** [comment]
Going to go ahead and close this. If you have further questions about bulk uploads to Amazon ElasticSearch, please open a question over at [StackOverflow](http://stackoverflow.com/questions/tagged/aws-java-sdk) and tag it with `aws-java-sdk`.
