### ISSUE TITLE
TransferManager - Support of CannedAccessControlList in uploadFileList method

### ISSUE THREAD

**Issue by se7en007** [aws/aws-sdk-java#1207]
Hi,
 I am currently working on multiple file upload method using TransferManager. I have looked into all overloaded methods for this:-

```
com.amazonaws.services.s3.transfer.TransferManager#uploadFileList(java.lang.String, java.lang.String, java.io.File, java.util.List<java.io.File>)  
com.amazonaws.services.s3.transfer.TransferManager#uploadFileList(java.lang.String, java.lang.String, java.io.File, java.util.List<java.io.File>, com.amazonaws.services.s3.transfer.ObjectMetadataProvider)  
com.amazonaws.services.s3.transfer.TransferManager#uploadFileList(java.lang.String, java.lang.String, java.io.File, java.util.List<java.io.File>, com.amazonaws.services.s3.transfer.ObjectMetadataProvider, com.amazonaws.services.s3.transfer.ObjectTaggingProvider)  
```

As per my understanding, neither ObjectMetadataProvider nor ObjectTaggingProvider can be used to set CannedAccessControlList. Is it possible to circumvent this situation?

P.S. :- In hope that I am not way off the mark, will it be good to have a overloaded method that accepts a list of PutObjectRequest? This would prevent multiple overloaded methods for every different configuration. Multiple PutObjectRequest can point to different buckets, which may hinder any S3-backend optimization if available(an assumption I made, since all existing methods needs all files to point to same bucket and same s3Prefix), but such checks can be taken care of in S3 Client JDK while hidden from user.

Thank you in advance.

**Comment by varunnvs92** [comment]
As per my understanding, neither ObjectMetadataProvider nor ObjectTaggingProvider can be used to set CannedAccessControlList. Is it possible to circumvent this situation?
>> No, you cannot set ACL using uploadFileList operations. Only tags ands metadata are supported as they are most used. You need to use the [upload](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#upload-com.amazonaws.services.s3.model.PutObjectRequest-) operation.

>> will it be good to have a overloaded method that accepts a list of PutObjectRequest? 
We are not planning to add any new methods to TransferManager unless there is a lot of customer ask for that feature. But if you can provide a PR, we will be happy to take a look

**Comment by se7en007** [comment]
This use case reduces wait time for users and I will be happy to add PR by next week.

**Comment by debora-ito** [comment]
This is just a quick update letting you know that the SDK team has reviewed the feature request list for V1 and this one looks like a great candidate for a community PR, which we’ll help merge in and support.

**Comment by debora-ito** [comment]
We don't have plans to support this before going into Maintenance Mode, so I'll go ahead and close this feature request. 

If this issue is still relevant when the v2 S3TransferManager is used (v2 S3TransferManager doesn't have a uploadFileList API though), please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.


#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
