### ISSUE TITLE
Multipart uploads failing with no error message

### ISSUE THREAD

**Issue by bgayathri** [aws/aws-sdk-java#1208]
We are using the aws java sdk to copy files from one location to another.

We have seen that for the past couple of weeks, all the multipart uploads are failing with no error messages printed out.

` new InitiateMultipartUploadRequest(targetBucketName, targetObjectKey)
amazonS3Client.initiateMultipartUpload(initiateRequest)
Exception occured in copyS3Object. Exception Message:null`

The same code has worked for us before and we have not made any recent code changes.

Issue occurs in m4.large/m4.2xlarge/m4.4xlarge instances.

Could you please help here in understanding what could be the root cause for this issue?

Thanks.

**Comment by varunnvs92** [comment]
I tried the following code and it worked fine with the latest SDK version.
```
InitiateMultipartUploadRequest req = new InitiateMultipartUploadRequest(bucket, key);
s3Client.initiateMultipartUpload(req);
```

Please provide a complete example which throws this error. Its is suspicious that error is showing "copyS3Object" when you are doing a initiateMultipartUpload operation. I suspect there might something going on in your code. 
Btw is it a multithreaded application?

**Comment by bgayathri** [comment]
No, this is not a multithreaded application. 

The copyS3Object is just from the log.

`public String copyS3Object(AmazonS3 s3client, AmazonS3Client amazonS3Client, String srcBucket, String srcobjKey, String desBucket, String destKeyName, Integer partFileSize)
            throws AmazonServiceException, AmazonClientException {
Long fileSizeLimit = 5L;
        try {
            LOG.info("Calling copyS3Object with input params srcBucket:{}, srcobjKey:{}, desBucket:{}, destKeyName:{}", srcBucket, srcobjKey, desBucket, destKeyName);
            Long fileSize = getObjectSize(s3client, srcBucket, srcobjKey);
            LOG.info("File size: Bytes:{}  or {}GB", Long.toString(fileSize), Long.toString(fileSize / (1024 * 1024 * 1024)));
            LOG.info("Comparing FileSize:{} with fileSizeLimit:{}", Long.toString(fileSize / (1024 * 1024 * 1024)), Long.toString(fileSizeLimit));
            if (fileSize / (1024 * 1024 * 1024) < fileSizeLimit) {
                return performS3SimpleCopy(s3client, srcBucket, srcobjKey, desBucket, destKeyName);
            } else {
                return performS3MultiPartCopy(amazonS3Client, srcBucket, srcobjKey, desBucket, destKeyName, partFileSize);
            }

        } catch (Exception ex) {
            LOG.error("Exception occured in copyS3Object. Exception Message:" + ex.getMessage());
            ex.printStackTrace();
            return ex.getMessage();
        }
    }
    public String performS3SimpleCopy(AmazonS3 s3client, String srcBucket, String srcobjKey, String desBucket, String destKeyName)
            throws AmazonServiceException, AmazonClientException {
        int count = 0;
        int maxTries = 10;
        while (true) {
            try {
                LOG.info("Calling PERFORM-S3-SIMPLE-COPY with input params srcBucket:{}, srcobjKey:{}, desBucket:{}, destKeyName:{}", srcBucket, srcobjKey, desBucket, destKeyName);
                CopyObjectRequest copyObjRequest = new CopyObjectRequest(srcBucket, srcobjKey, desBucket, destKeyName);
                ObjectMetadata objectMetadata = new ObjectMetadata();
                objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
                copyObjRequest.withNewObjectMetadata(objectMetadata);
                LOG.info("Copying object from srcBucket- {} ; srcobjKey- {} ; desBucket- {} ; destKeyName - {}", srcBucket, srcobjKey, desBucket, destKeyName);
                s3client.copyObject(copyObjRequest);
                LOG.info("Copying complete.");
                return "SUCCESS";
            } catch (Exception e) {
                LOG.error("Exception occured in performS3RegularCopy. Exception Message:{}.", e.getMessage());
                e.printStackTrace();
                if (++count == maxTries)
                    LOG.info("Value of count"+count);
                    return e.getMessage();
            }
        }
    }

    public String performS3MultiPartCopy(AmazonS3Client amazonS3Client, String sourceBucketName, String sourceObjectKey, String targetBucketName, String targetObjectKey, Integer partFileSize)
            throws AmazonServiceException, AmazonClientException {

        LOG.info("Calling PERFORM-S3-MULTI-PART-COPY with input parameters srcBucket:{}, srcobjKey:{}, desBucket:{}, destKeyName:{}", sourceBucketName, sourceObjectKey, targetBucketName, targetObjectKey);

        // List to store copy part responses.

        List<CopyPartResult> copyResponses =
                new ArrayList<CopyPartResult>();

        ObjectMetadata objectMetadata = new ObjectMetadata();
        objectMetadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);

        LOG.info("new InitiateMultipartUploadRequest(targetBucketName, targetObjectKey)");
        InitiateMultipartUploadRequest initiateRequest =
                new InitiateMultipartUploadRequest(targetBucketName, targetObjectKey, objectMetadata);

        LOG.info("amazonS3Client.initiateMultipartUpload(initiateRequest)");
        InitiateMultipartUploadResult initResult =
                amazonS3Client.initiateMultipartUpload(initiateRequest);

        try {
            // Get object size.
            LOG.info("Executing... new GetObjectMetadataRequest(sourceBucketName, sourceObjectKey)");

            GetObjectMetadataRequest metadataRequest =
                    new GetObjectMetadataRequest(sourceBucketName, sourceObjectKey);

            LOG.info("Executing... amazonS3Client.getObjectMetadata(metadataRequest)");

            ObjectMetadata metadataResult = amazonS3Client.getObjectMetadata(metadataRequest);
            LOG.info("Executing... metadataResult.getContentLength()");

            long objectSize = metadataResult.getContentLength(); // in bytes

            LOG.info("Executing... 4 * 1024 * (long) Math.pow(2.0, 20.0);");

            // Copy parts.
            long partSize = partFileSize * (long) Math.pow(2.0, 20.0); // partFileSize is an Integer. Part Size is calculated in MB.

            LOG.info("Executing... calculated partSize:{} objectSize:{}", Long.toString(partSize), Long.toString(objectSize));

            long bytePosition = 0;
            for (int i = 1; bytePosition < objectSize; i++) {
                LOG.info("Creating copyRequest with PartNumber:{}, bytePosition:{}, objectSize:{}, LastByte:{}", Integer.toString(i), Long.toString(bytePosition), Long.toString(objectSize), Long.toString(bytePosition + partSize - 1 >= objectSize ? objectSize - 1 : bytePosition + partSize - 1));
                CopyPartRequest copyRequest = new CopyPartRequest()
                        .withDestinationBucketName(targetBucketName)
                        .withDestinationKey(targetObjectKey)
                        .withSourceBucketName(sourceBucketName)
                        .withSourceKey(sourceObjectKey)
                        .withUploadId(initResult.getUploadId())
                        .withFirstByte(bytePosition)
                        .withLastByte(bytePosition + partSize - 1 >= objectSize ? objectSize - 1 : bytePosition + partSize - 1)
                        .withPartNumber(i);
                LOG.info("Executing... copyResponses.add(amazonS3Client.copyPart(copyRequest));");

                copyResponses.add(amazonS3Client.copyPart(copyRequest));
                bytePosition += partSize;
                LOG.info("Executing... End of loop bytePosition:{}", Long.toString(bytePosition));
            }
            LOG.info("Executing... creating CompleteMultipartUploadRequest");
            CompleteMultipartUploadRequest completeRequest = new
                    CompleteMultipartUploadRequest(
                    targetBucketName,
                    targetObjectKey,
                    initResult.getUploadId(),
                    GetETags(copyResponses));

            LOG.info("Executing... Calling amazonS3Client.completeMultipartUpload");

            CompleteMultipartUploadResult completeUploadResponse =
                    amazonS3Client.completeMultipartUpload(completeRequest);
            LOG.info("MultipartUpload complete. Returning Success");

            return "SUCCESS";
        } catch (Exception e) {
            LOG.error("Exception occured in putS3Object. Exception Message:" + e.getMessage());
            e.printStackTrace();
            return e.getMessage();
        }

    }`

**Comment by varunnvs92** [comment]
For copying objects, why are you using multipart upload operations? You can use [AmazonS3Client#CopyObject](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#copyObject-java.lang.String-java.lang.String-java.lang.String-java.lang.String-) or [TransferManager#copy](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#copy-com.amazonaws.services.s3.model.CopyObjectRequest-) operations to copy objects between buckets.

**Comment by bgayathri** [comment]
We use simple copy for files less than 5gb and multi part upload for files greater than 5gb

**Comment by varunnvs92** [comment]
Sorry for the silence on the ticket. There was no recent changes to TransferManager#copy or upload code from few months. So I am not sure whats going on in this case. Did you upgrade your sdk recently? If so, what is old and new versions?

Fyi, TransferManger copy supports copying object in multiple parts.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CopyCallable.java#L168-L183

**Comment by bgayathri** [comment]
Hello Varun - No problem.

I found that the issue got resolved by changing the code,

initResult = s3client.initiateMultipartUpload(initiateRequest); (code that works)

initResult = amazonS3Client.initiateMultipartUpload(initiateRequest); (code that does not work)

The constructor amazonS3Client was throwing us off. I found that it has been deprecated.

Thanks!!

**Comment by varunnvs92** [comment]
Glad the issue is resolved.
