### ISSUE TITLE
can't use AWS Java SDK to sendCommand to a windows platform

### ISSUE THREAD

**Issue by enventor** [aws/aws-sdk-java#1209]
if I try to use the AWS Java SDK to send a command to a windows instance, I get the following error:

> Exception in thread "Thread-3" com.amazonaws.services.simplesystemsmanagement.model.UnsupportedPlatformTypeException: Cannot perform operation for instance id i-01d5373d148f269d2 of platform type Windows (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: UnsupportedPlatformType; Request ID: 8a35d591-5691-11e7-8769-e7ce70e6bb47)

Here is the complete code:
	```

> private void stopAndDeleteE360Listener(String instanceId) {
> 		List<String> commands = new ArrayList<String>();
> 		commands.add("dir");
> 		SendCommandRequest request = new SendCommandRequest()
> 			.withInstanceIds(instanceId)
> 			.withDocumentName("AWS-RunShellScript")
> 			.addParametersEntry("commands", commands);
> 		
> 		AWSSimpleSystemsManagementClient client = new AWSSimpleSystemsManagementClient(new BasicAWSCredentials("my access key", "my secret access key"));
> 		client.setEndpoint("https://ssm.us-west-2.amazonaws.com");
> 		SendCommandResult result = client.sendCommand(request);
> 		
> 		System.out.println("----Result ----"+result.toString());	
> 	}
> 

```
Please note that I am able to remote desktop into the instance (i-01d5373d148f269d2) so can connect to it ok.

**Comment by varunnvs92** [comment]
The response returned from the aws service contains this exception and the SDK is unmarshalling and throwing it (not generating the exception). Its possible that the operation you are trying to do does not apply to that platform. (Search for UnsupportedPlatformType [here](http://docs.aws.amazon.com/systems-manager/latest/APIReference/API_SendCommand.html)).

You should reach out to the service team either through [forums](https://forums.aws.amazon.com/tags/ssm) or through AWS support. This channel is only for bugs and feature-requests for AWS Java SDK.

**Comment by enventor** [comment]
The DocumentName needs to be AWS-RunPowerShellScript for Windows commands.  No documentation on that anywhere I could find.  A tech support agent told me.

**Comment by varunnvs92** [comment]
Please enable wire logs and look at what the service response is. If service is returning the response, then SDK is working as expected. If its not, you need to contact the service team. If you can post the wire log here, I can take a look (DO NOT include SENSITIVE data).
