### ISSUE TITLE
Performance Bottleneck: TransferManager downloadDirectory 

### ISSUE THREAD

**Issue by bawejakunal** [aws/aws-sdk-java#1215]
In the `TransferManager.downloadDirectory` a [depth-first-search has been implemented](https://github.com/aws/aws-sdk-java/blob/d65733f87550d74a042e30f630c4b9033b6e3372/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L1210) where the list objects request is formed as below:

```
ListObjectsRequest listObjectsRequest = new ListObjectsRequest().withBucketName(bucketName)
                            .withDelimiter(DEFAULT_DELIMITER).withPrefix(prefix);
```
Well when we want to download all of the files of a directory based on a `KeyFilter` then why do we need a `ListObjectsRequest.withDelimiter`. Instead we could just have had:

```
ListObjectsRequest listObjectsRequest = new ListObjectsRequest().withBucketName(bucketName)
                            .withPrefix(prefix);
```

I have more than 13000 files which I can list easily in 14 API calls with the latter method. But the `downloadDirectory()` call makes 27000 API calls for the same because at each API call it goes down just 1 level of virtual directory.

Is there a particular justification for such implementation using `withDelimiter(DEFAULT_DELIMITER)` because as far as I see all possible filtering can be achieved through `KeyFilter` and `keyPrefix`.

**Comment by longi5rui** [comment]
Hey guys, any update on this issue? I always got `java.lang.OutOfMemoryError` when using TransferManager `downloadDirectory` API to download a directory with 3 million files.

This is a issue also for TransferManager `uploadDirectory` API but I use the approach @millems suggested which is I use `DirecotryStream` + Multi-threading my own to upload directory with large number files.

**Comment by millems** [comment]
Sorry that this was ignored for so long. We're nervous about making non-trivial changes for 1.11.x at this time, because we've found that even seemingly-safe changes can affect a handful of users and pull us away from development on 2.x of the SDK.

We'll incorporate this feedback while building the SDK 2.x.

**Comment by zoewangg** [comment]
Hi all, just a quick update, this feature has been implemented in the transfer manager in Java SDK v2. Note that it's in Developer Preview. You can check out sample code here https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/s3-transfer-manager. 

As always, we welcome feedback, bug reports and feature requests on the https://github.com/aws/aws-sdk-java-v2 repo!:)
