### ISSUE TITLE
cognitoidp listUsers() finds user with removed attribute

### ISSUE THREAD

**Issue by clintfoster** [aws/aws-sdk-java#1218]
If I remove a searchable attribute such as `name` by saving it with an empty string, it still shows up if I call `listUsers` with a filter for the old attribute value, even though the attribute is no longer returned.

I assume Cognito is using Dynamo under the covers. Since Dynamo doesn't allow saving empty attributes my guess is that Cognito is making things easier by automatically removing the attribute instead of throwing an exception. However, it apparently isn't removing the index for the attribute.

### Java snippet to reproduce

```
final String username = "Test";
final String name = "Fred";

// Create user with "name" attr
congnitoIdp.adminCreateUser(new AdminCreateUserRequest()
        .withUserPoolId(userPoolId)
        .withUsername(username)
        .withUserAttributes(new AttributeType()
                .withName("name")
                .withValue(name)));

// List user by name attr. Output:
// {Users: [{Username: Test, Attributes: [{Name: sub, Value: xxx}, {Name: name, Value: Fred}]
System.out.println(
        congnitoIdp.listUsers(new ListUsersRequest()
                .withUserPoolId(userPoolId)
                .withFilter(
                        String.format("%s = \"%s\"", "name", name))));

// Set name attr to empty string
congnitoIdp.adminUpdateUserAttributes(new AdminUpdateUserAttributesRequest()
        .withUserPoolId(userPoolId)
        .withUsername(username)
        .withUserAttributes(new AttributeType()
                .withName("name")
                .withValue("")));

// List by name still works even tho user no longer has name attr:
// {Users: [{Username: Test, Attributes: [{Name: sub, Value: xxx}]
System.out.println(
        congnitoIdp.listUsers(new ListUsersRequest()
                .withUserPoolId(userPoolId)
                .withFilter(
                        String.format("%s = \"%s\"", "name", name))));
```

**Comment by millems** [comment]
Great bug report! I'm not sure how long that search result will stick around, but it definitely sticks for 4 hours or so after I used your code to reproduce it. I'll forward this on to the cognito service team.

**Comment by kushwahavinay** [comment]
We have fixed this bug in one of our recent releases. Thanks for reporting this!

**Comment by clintfoster** [comment]
Confirmed, thanks. We're a little behind on the cognitoidp version (`1.11.251`), but it no longer reproduces even in that version. Perhaps that's not surprising since presumably the fix was on the cloud side.
