### ISSUE TITLE
Copying S3 data having special characters in the name from one bucket to another with use of client SSE key

### ISSUE THREAD

**Issue by susmitbansod** [aws/aws-sdk-java#1220]
We are using AWS Java SDK.
We want to copy a document from one bucket to another and while copying we want to encrypt it using SSE with client provided Key. We are facing an issue while copying when we try to copy we get error "Bad request" as our object name contains few special characters like space, (, ), -, _, :, " . etc.

**Exception:
com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 54AEFFEE96F01BB3), S3 Extended Request ID: sHAEmjrlRxgW6bosTkPuOkiqjw08L5+fy9183sznMuBI6BJrW8KTBJn0RTgqC0w2wZkluaED/Cg=**

We have tried copying object with SSE(using client key) that does not contain any special characters in the object name, it got successfully copied.
We also tried to copy object whose name contains special characters without SSE(using client key), it also got successfully copied.
But when we tried to copy the object having special characters in the name with SSE(using client key), was throwing above exception.

We cannot remove this special characters as this files are added by the third party. So we cannot just rename before uploading it to S3. 

Please provide a solution to solve this issue.

**Comment by millems** [comment]
I'm having some issues reproducing this issue in the latest version of the 1.11.x SDK. Could you provide code to reproduce it and the version of the SDK you are using?

Here's what I have:
```Java
String key = "key ()-_:\".";
s3.putObject(new PutObjectRequest(bucketName, key, file)
                     .withSSECustomerKey(sse_c));
s3.copyObject(new CopyObjectRequest(bucketName, key, bucketName, key + "-copy")
                      .withSourceSSECustomerKey(sse_c)
                      .withDestinationSSECustomerKey(sse_c));
System.out.println(s3.getObjectMetadata(new GetObjectMetadataRequest(bucketName, key + "-copy")
                                                .withSSECustomerKey(sse_c)).getRawMetadata());
```

**Comment by susmitbansod** [comment]
Hi Millems,

Sorry for late reply. We are using AWS Java SDK 1.11.149. Please find the code snippet that we are using:

```
public void copyExistingFile(String sourcePartitionName, String sourcePath, String destinationPartitionName, String destinationPath,
            SSECustomerKey destinationSSECustomerKey, AWSCredentials awsCredentials) {
			
		AmazonS3 amazonS3 = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
						.withRegion("AWS-BUCKET-REGION").build();
		CopyObjectRequest copyObjectRequest = new CopyObjectRequest(sourcePartitionName, sourcePath, destinationPartitionName, destinationPath)
							.withDestinationSSECustomerKey("SSE-CUSTOMER-KEY");
		amazonS3.copyObject(copyObjectRequest);
}
```

**Comment by millems** [comment]
Can you provide an example bucket and object name you're having trouble with?

**Comment by susmitbansod** [comment]
Hi Millems,

We are using bucket "qworem-filestack" and object key that is having trouble is "1/filestack-documents/00SanC6cS9mEpWZTIHSS_Agenda Topic  (1) - Copy (1) (1) (1).pdf". We are trying t copy this object from "qworem-filestack" bucket to let say XYZ bucket but using Customer key for SSE.

**Comment by millems** [comment]
Hmm.. I'm sorry, but I'm still having trouble reproducing it on the latest 1.11.x SDK version (see my working code below). I've tried using both an encrypted source object and an encrypted destination object. The error I get if that's mismatched mentions the objects being encrypted, so that's probably not your problem based on the error you're getting.

```Java
SSECustomerKey sse_c = new SSECustomerKey(CryptoTestUtils.getTestSecretKey());

String srcBucket = "qworem-filestack-2lk4jl23k423";
String srcKey = "1/filestack-documents/00SanC6cS9mEpWZTIHSS_Agenda Topic (1) - Copy (1) (1) (1).pdf";
String dstBucket = "xyz-l23k4n23lk4n2lk3n4";
String dstKey = srcKey;

try {
    s3.createBucket(srcBucket);
    s3.createBucket(dstBucket);
    s3.putObject(new PutObjectRequest(srcBucket, srcKey, file).withSourceSSECustomerKey(sse_c));
    s3.copyObject(new CopyObjectRequest(srcBucket, srcKey, dstBucket, dstKey).withDestinationSSECustomerKey(sse_c));
    System.out.println(s3.getObjectMetadata(new GetObjectMetadataRequest(dstBucket, dstKey)).getRawMetadata());
} finally {
    try { CryptoTestUtils.deleteBucketAndAllContents(s3, srcBucket); } catch (Exception e) {}
    try { CryptoTestUtils.deleteBucketAndAllContents(s3, dstBucket); } catch (Exception e) {}
}
```

**Comment by millems** [comment]
Closing for now. Let me know if you're still encountering this problem.
