### ISSUE TITLE
How to set region name that isn't available in Regions API

### ISSUE THREAD

**Issue by Omnipresent** [aws/aws-sdk-java#1224]
How do I set the region name for a region that is not in endpoints.json?

**Comment by spfink** [comment]
You can use RegionUtils.getRegion("region-string").

**Comment by Omnipresent** [comment]
@spfink I am trying to set a region that is only available in C2S. I tried this by doing below:

```
            AmazonS3 s3 = AmazonS3ClientBuilder.standard()
             .withRegion(regionName) //regionName is a string of region available only in C2S
             .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(aKeyUpload, sKeyUpload)))
             .build()
```

However, I get an error `No Region Provided`. If I do `RegionUtils.getRegion("region-string")` as you suggested, would it work for a region that is only available in C2S? Or is there a completely different SDK for C2S?

Additionally, I'm using version `1.11.30` of `aws-java-sdk-core` and when my project is packaged as a WAR file, I can't find the `endpoints.json`.
