### ISSUE TITLE
Fix commons-logging convergence: update aws-java-sdk-core to depend on commons-logging 1.2

### ISSUE THREAD

**Issue by amcp** [aws/aws-sdk-java#1230]
From the maven enforcer plugin dependency convergence rule, I get the following exception

```
Dependency convergence error for commons-logging:commons-logging:1.1.3 paths to dependency are:
+-com.amazonaws:dynamodb-lock-client:1.0.0
  +-com.amazonaws:aws-java-sdk-dynamodb:1.11.160
    +-com.amazonaws:aws-java-sdk-core:1.11.160
      +-commons-logging:commons-logging:1.1.3
and
+-com.amazonaws:dynamodb-lock-client:1.0.0
  +-com.amazonaws:aws-java-sdk-dynamodb:1.11.160
    +-com.amazonaws:aws-java-sdk-core:1.11.160
      +-org.apache.httpcomponents:httpclient:4.5.2
        +-commons-logging:commons-logging:1.2
```

**Comment by millems** [comment]
I'm not entirely sure how safe the change would be. Customers using nearest-first resolution of dependencies may currently be pulling in 1.1.3 and would be bumped up a minor version if we made that 1.2. Though, I think they only bumped to 1.2 because they dropped support for JDK 1.1 in that version: https://commons.apache.org/proper/commons-logging/changes-report.html

What's the impact of leaving this in on your use-case?

**Comment by shorea** [comment]
Closing due to no response. Feel free to reopen if you'd like to see this changed and we can discuss further.

**Comment by whilp** [comment]
Hi! This issue is preventing our dependencies from converging:

```
$ mvn dependency:tree; mvn enforcer:enforce
...
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [               
Require upper bound dependencies error for commons-logging:commons-logging:1.1.3 paths to dependency are:                         
+-internal:internal-dependencies:1.0                                                                                          
  +-com.amazonaws:aws-java-sdk-dynamodb:1.11.273
    +-com.amazonaws:aws-java-sdk-core:1.11.273                                     
      +-commons-logging:commons-logging:1.1.3                         
and    
+-internal:internal-dependencies:1.0                                                                             
  +-com.amazonaws:aws-java-sdk-dynamodb:1.11.273                                        
    +-com.amazonaws:aws-java-sdk-core:1.11.273
      +-org.apache.httpcomponents:httpclient:4.5.2
        +-commons-logging:commons-logging:1.2
]
```

While this conflict remains, our automated build machinery cannot easily detect a new dependency that cannot converge.

**Comment by imtdeepak** [comment]
We have to add commons-logging 1.2 to resolve. But why aws-sdk-core has two different version of commons-logging dependencies ?


+-com.amazonaws:aws-java-sdk-s3:1.11.745 
+-com.amazonaws:aws-java-sdk-core:1.11.745 
+-commons-logging:commons-logging:1.1.3 

and 
 +-com.amazonaws:aws-java-sdk-s3:1.11.745 
+-com.amazonaws:aws-java-sdk-core:1.11.745 
+-org.apache.httpcomponents:httpclient:4.5.9 
+-commons-logging:commons-logging:1.2 ]
