### ISSUE TITLE
Current latest version on Bintray

### ISSUE THREAD

**Issue by ahamana** [aws/aws-sdk-java#1231]
When I get the maven metadata file from Bintray(*), the latest version is 1.11.160.
Could you please update the version to 1.11.162?
* https://jcenter.bintray.com/com/amazonaws/aws-java-sdk-core/maven-metadata.xml

Thank you in advance.

**Comment by shorea** [comment]
@ahamana , we don't control what version is in Bintray. We only publish to MavenCentral. Presumably BinTray is syncing from that periodically so you'll need to get in touch with their support.
