### ISSUE TITLE
Feature Request: More details in SdkClientException (or subclasses)

### ISSUE THREAD

**Issue by C-Otto** [aws/aws-sdk-java#1232]
Currently the implementation of `AmazonS3` throws the rather generic `SdkClientException`. In my code I would like to see a difference between server errors, and input errors. Up to now I identified MD5 mismatches and content-length differences as errors that I would prefer to treat differently.

If the `SdkClientException` offered more information about the error, possibly using subclasses, this would help making the code below less brittle.

 ```
private URL throwCorrectException(SdkClientException exception) throws IOException {
        String message = exception.getMessage();
        if (message.contains("BadDigest")) {
            throw new IllegalArgumentException(MD5_CHECKSUM_MISMATCH);
        }
        if (message.contains("Data read has a different length than the expected")) {
            throw new IllegalArgumentException(WRONG_CONTENT_LENGTH);
        }
        throw new IOException(exception);
    }
```

**Comment by C-Otto** [comment]
The information in `AmazonS3Exception` (especially `errorCode` and `errorType`) are helpful, but I don't consider this enough for all use cases. For example, the content length mismatch is not communicated this way.

**Comment by spfink** [comment]
We would have to use subclasses for backwards compatibility which would make this hard for any service but S3. All client but S3 are generated from a model and thus we only generate exceptions that they have modeled. This is really a problem the service team should address to provide better error documentation. If you have specific use cases where you'd like to see better exceptions (beyond the ones you've already listed) we can take those to the service team. However, as we don't support polymorphism in our code generator currently, it would be difficult to introduce new exceptions in a backwards compatible manner.

We can take a look at the S3 examples you mentioned. There we might be able to introduce new subclassed exceptions as the client is not generated from a model.

**Comment by s-spindler** [comment]
We are facing the same issue trying to differentiate the SdkClientException thrown in LengthCheckInputStream from other occurrences.

If subclassing proves to be too difficult maybe it would be possible to add some kind of error code field (maybe an enum)?

**Comment by debora-ito** [comment]
@C-Otto, @s-spindler 

The team has reviewed the feature request list for V1 and decided to not implement this one since they are actively working on V2 new features. So I'll go ahead and close this.

Please feel free to reach out if you have further questions.
