### ISSUE TITLE
Add scala api

### ISSUE THREAD

**Issue by MatteCarra** [aws/aws-sdk-java#1233]
I think that it would be a good idea to add a scala api to allow developers to handle better asynchronous actions.

**Comment by laughedelic** [comment]
You may be interested in this list of the available AWS Scala libraries:
https://docs.google.com/spreadsheets/d/1tPX1YVQhE1RXpnZNrTPhm0o0FJOPXsauYC9zVKy4ikg/edit?usp=sharing

**Comment by spfink** [comment]
Thanks @laughedelic for the list of AWS Scala libraries. Quick once over shows that it has all of the libraries we usually recommend.

@MatteCarra beyond those libraries listed in the link, we don't have a fully supported Scala SDK. We have our new v2 developer preview out which has better java support for asynchronous actions: https://github.com/aws/aws-sdk-java-v2

It'd be great if you could provide any additional feedback on what you are looking for as far as asynchronous programming goes.

**Comment by kiiadi** [comment]
The v2 version of the SDK returns `CompletableFutures` instead of classic Java `Futures` - these are much closer to the Scala `Future`. There's even a handy library out there that allows simple conversion between them : https://github.com/scala/scala-java8-compat

**Comment by MatteCarra** [comment]
@laughedelic Thank you very much for the list.

@spfink I'm looking for a stable aws sdk which allows to perform async operations.
Aws sdk v2 would be perfect but as I've understood it's still in an early development stage and it's not recommended to use it in production scenarios.

I've suggested to create a scala api because it's easier for developers to deal with async operations, but as @kiiadi pointed out `CompletableFutures` are enough

**Comment by kiiadi** [comment]
@MatteCarra you're right, v2 is still in developer preview right now. The closest we have to a Scala SDK is a custom generator that sits on-top of the existing SDK : https://github.com/awslabs/aws-scala-sdk

By invoking a maven goal you can generate a Scala client for any service that wraps the Async calls and returns a Scala `Future` that is completed when the async call completes.

**Comment by dsilvasc** [comment]
@MatteCarra @kiiadi looks like aws-sdk-java-v2 is out of preview.

There's also a project (maybe in early stages) https://github.com/matsluni/aws-spi-akka-http trying to replace the Netty client in aws-sdk-java-v2 with akka-http so you could have the aws IO in your application managed by the same actor system as your application, if you're already using akka, akka-streams, and/or akka-http.

**Comment by debora-ito** [comment]
Hey everyone, as we are concentrating efforts on V2 new features, the team has reviewed this and decided not to implement it in V1. 

As pointed out in the previous comments, V2 has a better support for asynchronous actions, so feel free to reach out to us in the V2 repo with any specific needs and use cases.
