### ISSUE TITLE
EC2Actions is missing DescribeReservedInstancesModifications

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1237]
Not sure the logic for what actions go in this enum but `DescribeReservedInstancesModifications` is missing.

**Comment by kiiadi** [comment]
Which attribute on the `DescribeReservedInstancesModificationsRequest` / `DescribeReservedInstancesModificationsResponse` objects should have an enum? The enum's are generated from the service model.

**Comment by rdifalco** [comment]
Sorry, I'm not sure I understand. I mean as a peer to `EC2Actions.DescribeInstances`, `EC2Actions.DescribeReservicedInstances`, etc.  How is it done for those two?

**Comment by rdifalco** [comment]
Ah, okay, if you are not going to support these enums going forward (for IAM Actions by service) then feel free to close this. Having a public `NamedActions` that can be compared with what is in the `Statement#getActions` would be better anyway.

**Comment by kiiadi** [comment]
Oh I see, it's missing as part of the actions enum. You actually found one that is manually curated - hence why `DescribeReservedInstancesModifications` isn't in there. I can add it if you like?

**Comment by rdifalco** [comment]
I wouldn't bother if you don't plan on adding to them going forward (I didn't know that before I created the issue). Since I can't match them up to the `Policy#Statement#getActions` it doesn't matter that much anymore. I already have to parse the PolicyDocument into something other than your `Policy` class since I need actions that can be compared with these enums. I'll just move to strings.

**Comment by kiiadi** [comment]
Cool - sorry about that.
