### ISSUE TITLE
NamedAction in PolicyReader Does not define equals and hashcode. 

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1238]
A bit of a clumsy design around the `Action` interface where Enums are created upfront for service but cannot interact with `Statement` actions in `Policy`.  So you cannot compare these with each other. Furthermore `NamedAction` in the policy reader does not implement equals or hashCode making these even more impossible to compare. For example, this is impossible:

```
   statement.getActions().contains(EC2Actions.DescribeInstances);
```
I'd suggest either not having these enums at all in a future version or implementing hashCode and equals somehow in `NamedAction` so it can be compared. Either that or just don't have `Statement` return `Action` implementations so that you don't give the false impression that a statement action is the same thing as a service action enum. 

I bet you wish you had made these predefined `Action`s be Immutable object instances so that you could read a policy without pulling in every dep but still have an `Action` be an `Action`. :)

**Comment by kiiadi** [comment]
The generated `Action` enums for each service are often incorrect anyway - we attempt to generate these from the operation names of the service API and in many cases they actually differ from the action defined in the service itself.

By default we no longer generate the policy actions per service for new services (for example [Rekognition](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-rekognition/src) doesn't have them generated), in [v2](https://github.com/aws/aws-sdk-java-v2) we'll remove the enums for all services until we have a more reliable mechanism to generate them.
