### ISSUE TITLE
Feature Request: Consider Consumer based List/Describe

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1239]
I can't count the amount of code I have that has to deal with the different ways the different services handle Paged results, isTruncated, getMarker == null, getNextToken, etc. 

While it would be nice to standardize these I would prefer if you just did the while loops for me. For example, I would like every Describe and List action to have the following variant.

```
   ec2.describeInstancesForAll(DescribeInstancesRequest, Consumer<DescribeInstancesResult>);
```
This may be a v2 request, which is fine by me. But given that 99% of the time I iterate through *all* these `List` and `Describe` services calls, having an internal iteration variant for each that takes a consumer would be really friggin awesome.

**Comment by kiiadi** [comment]
We are looking at adding better pagination for our v2 version of the SDK. I've linked the related issue here and would prefer to track it in a single place - please feel free to 👍  the issue to help us prioritise it!
