### ISSUE TITLE
when i use putObject method,i find large number file handle leak 

### ISSUE THREAD

**Issue by laojiang99** [aws/aws-sdk-java#1242]
when i use putObject method,i find large number file handle leak
i dump jvm memory ,i fiind file handle hold by PutObjectRequest object ,don't release by S3DataSource.cleanupDataSource ; many files tag deleted(lsof),but not deleted

**Comment by laojiang99** [comment]
when i use putObject method,i find large number file handle leak 
i dump jvm memory ,i fiind file handle hold by PutObjectRequest object ,don't release by S3DataSource.cleanupDataSource ; many files tag deleted(lsof),but not deleted

**Comment by kiiadi** [comment]
Can you post a code-sample that re-produces this?

**Comment by laojiang99** [comment]
i'm sorry,i mistake。it's cos sdk，not s3 sdk；s3 sdk don't has this problem，it's cos sdk has

**Comment by kiiadi** [comment]
@laojiang99 are you uploading via a file or an input stream? Looking at `S3DataSource` it only releases if the original source was *not* a file. A code sample of how you're invoking the `putObject` request might make it easier to track down.
