### ISSUE TITLE
does ForceGlobalBucketAccess enable the client to upload to a bucket with any acceleration mode?

### ISSUE THREAD

**Issue by EdwardHong** [aws/aws-sdk-java#1250]
Hello all, 

If I build a AmazonS3client and set the options as below,
`client.setS3ClientOptions( S3ClientOptions.builder().setAccelerateModeEnabled( acceleration ).build() );
`

When I try to write to a s3 bucket that doesn't have the acceleration mode enabled, it will throw 

> Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: S3 Transfer Acceleration is not configured on this bucket (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; 

However, if I enable the force global bucket access as below,
`        client.setS3ClientOptions( S3ClientOptions.builder().setAccelerateModeEnabled( acceleration ).enableForceGlobalBucketAccess().build() );
`

I am able to write to a bucket that doesn't have acceleration mode enabled. Does this mean that, with the use of ForceGlobalBucketAccess, I can always have the acceleration mode enabled on the client and based on the configuration of the bucket, the upload will know whether to use acceleration mode or not?

**Comment by shorea** [comment]
I'm pretty sure we don't support that, this sounds more like a bug by allowing two incompatible options. Investigating.

**Comment by EdwardHong** [comment]
Okay, thanks for doing that.

The reason I had to set ForceGlobalBucketAccess with AccelerationMode is because after I set S3ClientOptions on my client, I was experiencing some unexpected behaviors. Basically, when I tried to upload to a bucket that are in other regions than US-East 1, it gave me 

> com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; ...

Before I set any S3ClientOptions, I didn't specify any region for my client but it was able to upload to buckets in different regions. I suspected that explicitly setting S3ClientOptions somehow overrides the default behavior of the client that could write to buckets in different regions. 

That's why I had to force enable global bucket access to be able to write to buckets in different regions with a client. If these are two incompatible options, how would I proceed to set the acceleration option on my client while ensuring it can still upload to buckets in different regions? More importantly, if my theory that when you're setting S3ClientOptions you're overriding the default behavior of the client's ability to write to multi-region buckets, could you please guide me to the part where this is happening?

**Comment by shorea** [comment]
Do you know where the buckets are located or do they come from an external source?

**Comment by EdwardHong** [comment]
The buckets that I failed to upload were basically in any region other than US-EAST-1. What do you mean an external source? I might've misinterpreted your question.

**Comment by shorea** [comment]
I guess what I'm asking is, do you have the need to interact with buckets in multiple regions in the same JVM/process.

**Comment by EdwardHong** [comment]
Oh okay. To answer your question, yes, I need to be able to interact with buckets in multiple regions in the same JVM process. This wasn't hard to do when I didn't set any region on my client but now after setting the acceleration mode on my client, I'm having trouble supporting both accelerationMode/writing to buckets in multiple regions without having to create multiple s3 clients.

**Comment by shorea** [comment]
@EdwardHong apologies for the silence. Looked into this a bit and it looks like this is an unsupported feature at the moment and I would probably consider it a bug. When accelerate and global mode are both enabled, we will make a HEAD bucket request to the configured endpoint (the global accelerate endpoint in this case) to get the bucket region to cache for later use. When we then resolve that region into an endpoint we don't take into account accelerate mode again (although we do consider dualstack for whatever reason) thus we will hit the non-accelerate s3.amazonaws.com endpoint. At a minimum I think we need to prevent these options from being used together if we don't want to support bucket discovery for accelerate mode. Alternatively we could support the same discovery mechanisms when using accelerate.
