### ISSUE TITLE
TransferManager downloadDirectory seems to be unstable for downloading large number of files

### ISSUE THREAD

**Issue by josephkurian** [aws/aws-sdk-java#1251]
We have an application that downloads files from an S3 bucket in an EC2 machine using TransferManager.downloadDirectory . When the number of objects stored in the bucket  are very high (about 200k - 300k) , we are noticing that this api call is unstable- either it silently fails(downloads only a subset of the files without warnings ) or goes on for a long time without really doing anything (no network out/in or disk writes) before our app times out(in about 48 hours or so). The EC2 machine is r4.8x large and the aws s3 version is 1.11.166
Following code snippet outlines what we are doing:

`val transferManager: TransferManager =   TransferManagerBuilder.standard().withS3Client(AmazonS3ClientBuilder.defaultClient())
   .withExecutorFactory(() => Executors.newFixedThreadPool(30)).build()
  var download :MultipleFileDownload =  transferManager.downloadDirectory("bucket-name", "level1/level2", new File("/tmp/test"))

  if (!download.isDone) {
    Thread.sleep(60000)
    System.out.println("Transfer: " + download.getDescription)
    System.out.println("State: " + download.getState)
    System.out.println("Progress: " + download.getProgress.getBytesTransferred)
  }`

**Comment by josephkurian** [comment]
Update : 
Occasionally I get the following during execution: 
**Jul 25, 2017 12:17:40 AM com.amazonaws.services.s3.internal.S3AbortableInputStream close
WARNING: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
Jul 25, 2017 12:17:42 AM com.amazonaws.services.s3.internal.S3AbortableInputStream close
WARNING: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
Jul 25, 2017 3:09:40 AM com.amazonaws.services.s3.internal.S3AbortableInputStream close
WARNING: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.**

**Comment by josephkurian** [comment]
Update :  
Noticing that the  process failed with OutOfMemoryException after a few hours and the FileSystem was left with a partial list of files:
**Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)**

**Comment by shorea** [comment]
How large are these files?

**Comment by josephkurian** [comment]
They are mostly pretty small. A few Kbs to a few 100 Kbs. Occasionally though there are ones that can go up to a few 100 Mbs . But probably around 99% of them are small objects.

**Comment by josephkurian** [comment]
Update : 
I bumped up the JVM heap space max to about 5 GB as advised by enterprise AWS support  and also added the transferManager.shutDownNow() method at the end . Now it seems to be pretty stable. So the above code snippet works fine(I used download.waitForCompletion() instead of the if (!download.isDone) condition ). 
I am yet to put a fix in our pipeline code that actually utilizes this , but the real scenario is hard to test and I will try to explain it. 
The pipeline works in a series of sequential steps where the output of one(the set of files in S3) feeds in as input to the next. Since there is a large amount of overlapping files between the different stages, at each stage we only rewrite the files that have changed , leaving the others untouched. So we are doing an overwrite PUT on a set of files(rather than a new put) , leaving a majority of the files unchanged . And almost immediately, we read the files in to EC2 as input for the new step. So , I wonder if we might run in to READ-AFTER-WRITE consistency problems(which probably was the real problem too) ?

**Comment by josephkurian** [comment]
For anyone who might be encountering issues dealing with this api call (transferManager.downloadDirectory) especially when there is a very high number of files in S3 , the following set of steps seems to have worked(In the order of what I think is the most important to the least) : 
a.) Increasing the JVM heap size to an appropriately high value(5 GB worked for us)
b.) Ensuring TransferManger is shutdown after every usage. 
c.) Using the non deprecated constructors for TransferManager and AWSS3Client (Don't know if it is as important as the above 2)

**Comment by shorea** [comment]
Thanks for the analysis @josephkurian! This is great for helping future customers who have the same problem. I'll add to b) that we generally recommend the TransferManager be long lived where possible. In V2 of the SDK we are making things like clients AutoCloseable so it's much more obvious it needs to be cleaned up, as it stands today it's somewhat hidden and requires tribal knowledge.
