### ISSUE TITLE
Java + Gradle SDK generated from API gateway uses wrong version of aws-java-sdk-opensdk

### ISSUE THREAD

**Issue by wjbuys** [aws/aws-sdk-java#1252]
When generating a Java + Gradle SDK for a deployed API Gateway API:

```sh
aws apigateway get-sdk --rest-api-id 1234 --stage-name Beta --sdk-type java \
  --parameters service.name=Foo,java.package-name=com.example,java.build-system=gradle \
  /tmp/sdk.zip
```

the generated SDK does not build out of the box:

```
> Task :compileJava
/code/generated-code/src/main/java/com/example/FooClient.java:251: error: cannot find symbol
        request = beforeClientExecution(request);
                  ^
  symbol:   method beforeClientExecution(DescribeEnvironmentRequest)
  location: class FooClient
```

It looks like the generated client's operations all call `beforeClientExecution(request)` on AmazonWebServiceClient:

```java
    public DoSomethingResult doSomething(DoSomethingRequest request) {
        request = beforeClientExecution(request);
        return executeDoSomething(request);
    }
```

but the generated `build.gradle` declares a dependency on `com.amazonaws:aws-java-sdk-opensdk:1.11.94`. That version does not yet have `beforeClientExecution` defined on `AmazonWebServiceClient`, it was only [added in 1.11.106](https://github.com/aws/aws-sdk-java/commit/799319f670344153d588e7e42095653fabf01673).

**Comment by shorea** [comment]
This should be fixed now.
