### ISSUE TITLE
Xray recorder source JARs missing in Maven Repos 

### ISSUE THREAD

**Issue by tfeak** [aws/aws-sdk-java#1257]
I'm looking into integration of Xray with our server (Dropwizard) and usually learn a lot about how the system functions by perusing source code. With all of your other SDK libraries, I've been able to get the source JARs from the Maven library. However, with the following libraries (all version 1.1.2) I cannot.

aws-xray-recorder-sdk-core
aws-xray-recorder-sdk-aws-sdk
aws-xray-recorder-sdk-apache

I assume the handful of other libraries prefixed with aws-xray-recorder-* may also be missing source JARs. Furthermore, I can't even find the Github source for this, so I can't look at source that way.

It's looking like the Xray integration other than the base client classes is a separate project?

**Comment by shorea** [comment]
I'll forward this to the Xray team to see where they are at in terms of open sourcing the recorders.

**Comment by tfeak** [comment]
Thank you.

As a follow up on this, I understand if they don't want to open up the source. But at least some Javadoc would be nice. As is, I don't even get parameter names on Interfaces that I may want to implement as extension points.

**Comment by jamesdbowman** [comment]
Hi tfeak,

We're still in the process of open sourcing the X-Ray SDKs.

In the meantime, Javadoc is available both as `javadoc.jar` related artifacts in Maven Central, and  [hosted here](http://docs-aws.amazon.com/xray-sdk-for-java/latest/javadoc/).

James

**Comment by tfeak** [comment]
Ah, thanks for the pointer!
