### ISSUE TITLE
Elasticsearch parameters included in uri unsupported

### ISSUE THREAD

**Issue by Josca** [aws/aws-sdk-java#1258]
Hi,
 I'm writing Java client for Elasticsearch using `com.amazonaws.http.AmazonHttpClient`. I found that including parameters into uri when requesting AWS Elasticsearch instance is not supported. Here are my examples:

```java
// That works. Parameters are included using method.
request.setEndpoint(URI.create("https://...es.amazon/myindex/mytype/_search"));
request.addParameter("q", "car");
request.addParameter("size", "1");
```

```java
// That fails. Parameters are included in uri.
request.setEndpoint(URI.create("https://...es.amazon/myindex/mytype/_search?q=car&size=1"));
```

So, it's not fully compatible with Elasticsearch documentation. Additionally, how can I use [pretty](https://www.elastic.co/guide/en/elasticsearch/guide/current/get-doc.html) "flag" parameter?

Note: full example code can be found in [this similar issue](https://github.com/aws/aws-sdk-java/issues/1254).

**Comment by shorea** [comment]
Are you getting a signing error?

**Comment by shorea** [comment]
Closing per lack of response, feel free to reopen if problem persists.
