### ISSUE TITLE
BeanstalkEnvironment EnvironmentHealthStatus missing status

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1261]
Hi
the EnvironmentHealthStatus is missing the Suspended status
from the com.amazonaws.services.elasticbeanstalk.model.EnvironmentDescription.getHealthStatus() I get the Suspended status but it is missing from the Enum

**Comment by spfink** [comment]
I'll pass this on to the service team for clarification. Doesn't look like suspended is supposed to be a health status:

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced-status.html

**Comment by spfink** [comment]
@bmagic39 can you provide a quick code snippet that you are using to get this status?

**Comment by bmagic39** [comment]
the code below fails at fromValue

DescribeEnvironmentsRequest request = new DescribeEnvironmentsRequest();
DescribeEnvironmentsResult describeEnvironmentsResult = awsClient.describeEnvironments(request.withEnvironmentIds(envid));

int retSize = describeEnvironmentsResult.getEnvironments().size();
if (retSize == 0) return null;
com.amazonaws.services.elasticbeanstalk.model.EnvironmentDescription env = describeEnvironmentsResult.getEnvironments().get(0);

EnvironmentHealthStatus estatus = EnvironmentHealthStatus.fromValue(env.getHealthStatus());

so I added the following as workaround
		if (env.getHealthStatus().equals("Suspended"))
			return EnvironmentHealthStatus.Unknown;

**Comment by spfink** [comment]
Thanks @bmagic39! I will follow up with the service team now.

**Comment by bmagic39** [comment]
Hi
any news on this?

**Comment by millems** [comment]
I'm sorry, we don't have any update to provide at this time. Sorry about the delay.

**Comment by millems** [comment]
Sorry, still no update on this.

**Comment by millems** [comment]
Beanstalk is still working to fix the problem, but does not have any public ETA at this time.

**Comment by spfink** [comment]
This has been released:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-elasticbeanstalk/src/main/java/com/amazonaws/services/elasticbeanstalk/model/EnvironmentHealthStatus.java#L31
