### ISSUE TITLE
S3 Client incompatible with GovCloud Region? HEAD request always goes to standard region

### ISSUE THREAD

**Issue by bennnjamin** [aws/aws-sdk-java#1266]
It appears that the S3Client cannot access buckets in GovCloud (specifically for put operations) because the initial HEAD request is sent to s3.amazonaws.com no matter what. This results in odd behavior. I have inadvertently put data in public buckets because my correspond GovCloud S3 names duplicate names in the East-West cloud. See example code of how I'm configuring the client below.

`s3 = (AmazonS3Client) AmazonS3ClientBuilder.standard()
                    .withCredentials(new AWSStaticCredentialsProvider(govCloudCredentials))
                    .withRegion(Regions.GovCloud)
                    .build();`

Even if I set the endpoint explicitly it still sends a HEAD request to s3.amazonaws.com and attempts to PUT there.

`	s3 = (AmazonS3Client) AmazonS3ClientBuilder.standard()
           .withEndpointConfiguration(new EndpointConfiguration("s3-us-gov-west-1.amazonaws.com", "us-gov-west-1"))
                    .build();`

`017-08-07 16:08:36,680 [s3-transfer-manager-worker-1] DEBUG com.amazonaws.request -  Sending Request: HEAD https://mybucket.s3.amazonaws.com / Headers: (User-Agent: aws-sdk-java/1.11.172 Mac_OS_X/10.12.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.51-b03/1.8.0_51, amz-sdk-invocation-id: 2f070b40-4212-8a37-62a1-880375444890, Content-Type: application/octet-stream, )
2017-08-07 16:08:37,456 [s3-transfer-manager-worker-1] DEBUG com.amazonaws.request -  Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 926535E192279471; S3 Extended Request ID: /pkKHq/UXtzJ7V5MfHyx0z3FWwOyyzeuoLyHoDYyde4L1fcTjOkx+ro4oMp85ZGpShblFQk9Yis=), S3 Extended Request ID: /pkKHq/UXtzJ7V5MfHyx0z3FWwOyyzeuoLyHoDYyde4L1fcTjOkx+ro4oMp85ZGpShblFQk9Yis=`

**Comment by abprasan** [comment]
Responding to this thread based on an offline conversation with bennnjamin.

The initial HEAD request was being sent to s3.amazonaws.com as Transfer Manager was being used. Default Transfer Manager settings are set to point to s3.amazonaws.com. If TransferManagerBuilder is built using the settings from the S3ClientBuilder which has the GovCloud destination specified, the requests will hit the correct endpoint (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManagerBuilder.html#withS3Client-com.amazonaws.services.s3.AmazonS3-)

**Comment by millems** [comment]
Thanks for the report. It sounds like you got things working? Is there something we could do to make this more intuitive?

**Comment by abprasan** [comment]
Yes; we got it working. Maybe an alert about this might help - can't think of anything else that could make it intuitive. 

An alert saying that the default settings will point to the regular S3 endpoint and if the plan is to use TransferManagerBuilder, then to hit a specific endpoint (especially GovCloud), the settings from the S3ClientBuilder will need to be imported (unless there is another way to achieve this which I do not know).

**Comment by bennnjamin** [comment]
IMO, the best thing to do is just update the documentation because that is where I first looked. This would be a good place to mention a default vs explicit S3Client for the TransferManagerBuilder (side note: documentation still mentions the deprecated TransferManager). Since the behavior is not intuitive it would be nice if it was explicitly documented.

**Comment by spfink** [comment]
We've updated our documentation on TransferManagerBuilder and it's method setS3Client and withS3Client to also state:

If no client is specified, a default client will be created using {@link DefaultAwsRegionProviderChain} and {@link DefaultAWSCredentialsProviderChain}.

Closing this issue. Documentation will go out with today's release.
