### ISSUE TITLE
[S3 upload] API to upload outputstream

### ISSUE THREAD

**Issue by 16srana** [aws/aws-sdk-java#1268]
Current API in sdk accepts either file or inputStream  object to upload content, which is more sort of a pull mechanism from s3 to upload content.
Can we have a API more sort of a push mechanism, like an API which accepts outputStream object to upload any content.

Actually we are using s3 to upload large files in GBs to be distributed to our users, which we generate based on our users request, currently we save the file locally and then upload it, in ideal case we would like to generate/write the zip file directly to s3.

**Comment by millems** [comment]
Can you describe your use-case in a little bit more depth? You'd like us to return an `OutputStream` to which you can push content?

Something like this? (Ignore syntax for now, just trying to understand)

```Java
SdkOutputStream<PutObjectResponse> contentStream = s3.initiatePutObject(request);
contentStream.write("My Data".getBytes());
PutObjectResponse response = contentStream.complete();
```

**Comment by millems** [comment]
See also: https://github.com/aws/aws-sdk-java/issues/1139#issuecomment-321752006

**Comment by 16srana** [comment]
Sorry for Late reply...
@millems Yeah the sudo code above is what expected, also the issue #1139 mentioned also has similar ask.
Can we Expect this API?
If yes then when ?
Actually in my service I have to generate huge zip files ranging from  2~12 GB in size, which I have to first write to filesystem and than upload it to s3, I would really love to merge these steps.
`SdkOutputStream<PutObjectResponse> contentStream = s3.initiatePutObject(request);
ZipOutputStream os = new ZipOutputStream(contentStream.getOutputStream()); 
os.write("My Data".getBytes());
PutObjectResponse response = contentStream.complete();`
Actually I will be wrapping the contentStream into my zip output stream object
I am expecting following two benefits:
1. Less memory use.
2. Less time taken to make the file available to my users.
3. Less IO operations.

**Comment by shorea** [comment]
Would a [PipedInputStream](https://docs.oracle.com/javase/7/docs/api/java/io/PipedInputStream.html) and output stream work for you? You'd still need to know the content length in this case and set in on the PutObjectRequest otherwise the SDK will buffer it into memory.

If you don't know the content length then I think your best option is to do a multipart upload and buffer each part into memory. The minimum for part size is 5MB so memory consumption is manageable. I don't believe S3 supports chunked encoding which would allow for dynamic content, if that's desired than you'll have to make a feature request to the S3 service team.

**Comment by 16srana** [comment]
@shorea I have tried the Piped Input/Output Stream, it involves making a reader thread and a writer thread and synchronizing them and messaging between them, that wasn't quite effective and had few performance hits as well, also there is lot of boiler plate code, I am already considering this as my backup option.

I was hoping an option from the sdk itself, but since you have mentioned that the support is not from the s3 itself than I think I will have to rely on workarounds.
I was reading the s3 upload documentations and it does mention that, If the length of the content is unknown than the upload would happen in a single thread, which would take forever to upload large files.

**Comment by shorea** [comment]
Yeah if we don't know the content length we have to buffer contents into memory which is obviously not ideal. Doing the multipart upload makes the buffering less of a problem but adds complexity to the upload.

**Comment by shorea** [comment]
Going to close this and open a feature request in our V2 repo. I think there are a couple of things we can do to make streaming easier via TransferManager

**Comment by shorea** [comment]
https://github.com/aws/aws-sdk-java-v2/issues/139

**Comment by badmitrii** [comment]
@shorea 
I have sort of similar issue with uploading a file. I have a large plain-text files (~65GB) which I want to be able to gzip on the fly while uploading to S3. It would be perfect if I just do something like
```
OutputStream ous = //get sdk OutputStream
OutputStream gzous = new GZIPOutputStream(ous)
//pushing to gzous
```
Is something like this possible in the current sdk (1.9.6) or 2.x?
