### ISSUE TITLE
What is the correct value of targetType for @DynamoDBTypeConvertedJson when working with a Map type?

### ISSUE THREAD

**Issue by seantcanavan** [aws/aws-sdk-java#1269]
I have a Class:

    @DynamoDBTable(tableName = "A")
    public class A {

        // What annotation should go here?
        private Map<EnumType, Class> values;
    }

Annotating with `@DynamoDBTypeConvertedJson` does not work for the map

Annotating the class `EnumType` with `@DynamoDBTypeConvertedEnum` does not work either.

Annotating with `@DynamoDBTypeConvertedJson(targetType = new TypeReference<Map<EnumType, Class>>(){})` does not compile unfortunately.

But the above syntax is the correct way to unmarshal as my custom converter works fine with it:

    @Override
    public String convert(Map<EnumType, Class> object) {
        try {
            return objectMapper.writeValueAsString(object);
        } catch (JsonProcessingException e) {
            throw new IllegalArgumentException("Failed to marshal instance of Map<EnumType, Class> to String.");
        }
    }

    @Override
    public Map<EnumType, Class> unconvert(String object) {
        try {
            return objectMapper.readValue(object, new TypeReference<Map<EnumType, Class>>(){});
        } catch (IOException e) {
            throw new IllegalArgumentException("Failed to unmarshal instance of String to Map<EnumType, Class>.");
        }
    }

So what then is the correct value of targetType when marshaling a Map of non-standard java objects? Because I don't want to have to make a simple converter that just calls Jackson each time when my converter code is nearly identical to the code found in [DynamoDBTypeConvertedJson.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBTypeConvertedJson.java).

**Comment by shorea** [comment]
@seantcanavan apologies for the lack of response. I think you have a couple of options here. If you are dead set on using `DynamoDBTypeConvertedJson` (which stores data as a Dynamo String serialized as JSON) then you can wrap that Map in an extra structure and annotate that structure with `DynamoDBTypeConvertedJson`. Here's an example of what that would look like

```java
@DynamoDBTable(tableName = "TestTable")
public class MyPojo {

    @DynamoDBHashKey
    private String hashKey;

    @DynamoDBTypeConvertedJson
    private StructWithMap structWithMap;

    public String getHashKey() {
        return hashKey;
    }

    public void setHashKey(String hashKey) {
        this.hashKey = hashKey;
    }

    public StructWithMap getStructWithMap() {
        return structWithMap;
    }

    public void setStructWithMap(StructWithMap structWithMap) {
        this.structWithMap = structWithMap;
    }
}

public class StructWithMap {

    private Map<String, SimplePojo> mapValue;

    public Map<String, SimplePojo> getMapValue() {
        return mapValue;
    }

    public void setMapValue(Map<String, SimplePojo> mapValue) {
        this.mapValue = mapValue;
    }

    public StructWithMap withMapValue(Map<String, SimplePojo> mapValue) {
        this.mapValue = mapValue;
        return this;
    }
}

public class SimplePojo {

    private String valueOne;
    private String valueTwo;

    public String getValueOne() {
        return valueOne;
    }

    public void setValueOne(String valueOne) {
        this.valueOne = valueOne;
    }

    public SimplePojo withValueOne(String valueOne) {
        this.valueOne = valueOne;
        return this;
    }

    public String getValueTwo() {
        return valueTwo;
    }

    public void setValueTwo(String valueTwo) {
        this.valueTwo = valueTwo;
    }

    public SimplePojo withValueTwo(String valueTwo) {
        this.valueTwo = valueTwo;
        return this;
    }
}
```

The other option, which does not require extra wrapping would be to use the `DynamoDBTyped` annotation along with `DynamoDBDocument` on the map value class. This stores data using the Dynamo native Map/Document type rather than a JSON string.
```java
@DynamoDBTable(tableName = "TestTable")
public class MyPojo {

    @DynamoDBHashKey
    private String hashKey;

    @DynamoDBTypeConvertedJson
    private StructWithMap structWithMap;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.M)
    private Map<String, SimplePojo> mapValue;

    public String getHashKey() {
        return hashKey;
    }

    public void setHashKey(String hashKey) {
        this.hashKey = hashKey;
    }

    public StructWithMap getStructWithMap() {
        return structWithMap;
    }

    public void setStructWithMap(StructWithMap structWithMap) {
        this.structWithMap = structWithMap;
    }

    public Map<String, SimplePojo> getMapValue() {
        return mapValue;
    }

    public void setMapValue(Map<String, SimplePojo> mapValue) {
        this.mapValue = mapValue;
    }

    public MyPojo withMapValue(Map<String, SimplePojo> mapValue) {
        this.mapValue = mapValue;
        return this;
    }
}

@DynamoDBDocument
public class SimplePojo {

    private String valueOne;
    private String valueTwo;

    public String getValueOne() {
        return valueOne;
    }

    public void setValueOne(String valueOne) {
        this.valueOne = valueOne;
    }

    public SimplePojo withValueOne(String valueOne) {
        this.valueOne = valueOne;
        return this;
    }

    public String getValueTwo() {
        return valueTwo;
    }

    public void setValueTwo(String valueTwo) {
        this.valueTwo = valueTwo;
    }

    public SimplePojo withValueTwo(String valueTwo) {
        this.valueTwo = valueTwo;
        return this;
    }
}
```

**Comment by shorea** [comment]
Apologies I missed the enum key part of your question. The second option does not appear to be compatible with `DynamoDBTypeConvertedEnum`. Seeing if that's fixable, but option one does work with enums using standard Jackson serialization of enums.

**Comment by seantcanavan** [comment]
Thanks for the reply @shorea. Is there a specific reason why `@DynamoDBTypeConvertedJSON` works better for a Map nested within a class rather than on the Map type itself?

I'll have to give your first suggestion a whirl later today. I'm very pleased with custom DynamoDB type converters - I use at least 2-3 per project. But it would be awesome if the out-of-the-box support was a bit stronger seeing as I mentioned in my original post that sometimes my custom converter code is just a call to Jackson which is essentially what you guys are doing with the `@DynamoDBTypeConvertedJSON` implementation.

**Comment by shorea** [comment]
It seems to be a limitation of the library that for document/map types we assume the key is always an actual Java string rather than something that can be converted to a string (via custom annotations or type converters, etc). Investigating to see if it's possible to overcome this limitation.

**Comment by shorea** [comment]
@seantcanavan unfortunately I wasn't able to get the second option to work with non-string keys. It should be possible to recursively map the key type like we do for the value type but the way our code is structured that would require some major changes. Does the first option work for you?

**Comment by seantcanavan** [comment]
Sure that's a decent-enough workaround for the time being. Thanks again for investigating. Are you going to file a potential feature request?

**Comment by shorea** [comment]
@seantcanavan sure thing, I'll move this over to our V2 feature request backlog as it's unlikely we will invest the effort to add this to V1.
