### ISSUE TITLE
Specify AMI Name when creating image by ImportImage.

### ISSUE THREAD

**Issue by MaxTakahashi** [aws/aws-sdk-java#1270]
Is it possible to specify AMI Name when creating image using ImportImage API?
It is generated automatically like "import-ami-abcd1234". But I would like to give more reasonable name.

ImportImageRequest does not have "Name" parameter while CreateImageRequest have it.
```
CreateImageRequest createImageRequest = new CreateImageRequest();
createImageRequest.withInstanceId("i-xxxxxxxxxxxxxxxxx")
    .withName("myaminame")
    .withDescription("this is my ami");
```

Or is it possible to rename it later?

Thanks.

**Comment by millems** [comment]
Howdy! Would you be able to ask this question on StackOverflow ([See: Getting Help](https://github.com/aws/aws-sdk-java#getting-help)) ? Unfortunately we're only arbiters of the SDK itself. We're not so familiar with the details of each service.

**Comment by MaxTakahashi** [comment]
Hello millems! thanks for your advice.
I opened [a question on StackOverflow](https://stackoverflow.com/questions/45788383/how-to-specify-ami-name-when-creating-image-using-importimage). Now I close this one.

Thanks.
