### ISSUE TITLE
SimpleWorkflowService ListActivityTypes does not respect maximumPageSize > 100

### ISSUE THREAD

**Issue by strmer15** [aws/aws-sdk-java#1275]
```
   ListActivityTypesRequest request = new ListActivityTypesRequest()
                    .withDomain("my_domain")
                    .withMaximumPageSize(1000)
                    .withRegistrationStatus(RegistrationStatus.REGISTERED);
```

If you actually execute this request when you have more than 100 activities registered, only the first 100 are returned.  From the javadoc:

```
    /**
     * <p>
     * The maximum number of results that are returned per call. <code>nextPageToken</code> can be used to obtain futher
     * pages of results. The default is 1000, which is the maximum allowed page size. You can, however, specify a page
     * size <i>smaller</i> than the maximum.
     * </p>
     * <p>
     * This is an upper limit only; the actual number of results returned per call may be fewer than the specified
     * maximum.
     * </p>
     */
    private Integer maximumPageSize;
```

In practice, setting the maximumPageSize to anything >= 100 doesn't actually work.  Seems like the server has an actual max of 100 that it enforces.  Not setting a maximumPageSize has the same result, only the first 100 are returned.  I've also tried this from the CLI and the same thing happens; either the documentation should change or the bug should be fixed.

**Comment by kiiadi** [comment]
@strmer15 tested this myself and you're right, definitely odd behaviour. I'm not sure if it's a documentation issue or a bug with the service - but I agree what you're seeing is inconsistent.

I've raised this with the SWF service team to see if they can provide any insights. As you point out this is in the CLI as well so it's not a specific issue with the Java SDK - I'm going to close this issue. 

I'll come back when I hear from the service team.

**Comment by kiiadi** [comment]
@strmer15 just an update, the service team is looking to get the documentation corrected.
