### ISSUE TITLE
headBucket operation throwing wrong exception when bucket does not exist

### ISSUE THREAD

**Issue by gpj1** [aws/aws-sdk-java#1279]
Hi,
I'm using aws s3 java sdk 2.0.0-preview-2 and I'm invoking headBucket method on s3Client.
In the HeadBucketRequest, when I give non existing bucket name, as per documentation I was expecting it to throw "NoSuchBucketException" but, it is throwing S3Exception with error code 404 inside it.
Below is my code snippet. 

```
S3Client s3Client = S3Client.builder().credentialsProvider(new StaticCredentialsProvider(new AwsCredentials("xxxaccesskey", "yyyysecretkey"))).region("us-east-1").build();
try {
s3Client.headBucket(HeadBucketRequest.builder().bucket("non-existing-bucket-name").build());	
} catch(NoSuchBucketException noSuchBucketException) {
System.out.println("Nosuchbucket exception");
} catch(S3Exception s3Exception) {
System.out.println("s3Exception");
}

```

**Comment by shorea** [comment]
@gpj1 do you mind opening this issue here, https://github.com/aws/aws-sdk-java-v2/issues

Looks like we missed support for modeled exceptions when generating the s3 client. I'll add this to our backlog.

**Comment by gpj1** [comment]
submitted. Thanks @shorea
