### ISSUE TITLE
flow framework: ability to add control data when creating a timer

### ISSUE THREAD

**Issue by ogrodnek** [aws/aws-sdk-java#128]
It would be nice if there was a WorkflowTimer.createTimer method that allowed one to pass in control data for the timer creation.

I know the control data is meant for use in the decider to handle workflow, but for my app it would be nice to be able to stash some additional info in the Timer as part of the HistoryEvent that gets created, for displaying historical logs.

**Comment by breedloj** [comment]
Resolving this since the SWF code has changed considerably since this issue was created.  Feel free to re-open or create a new issue if it is still a pain point.
