### ISSUE TITLE
Is there Service Model/Intermediate model for S3 api?

### ISSUE THREAD

**Issue by brsanthu** [aws/aws-sdk-java#1280]
This [location](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-models/src/main/resources/models) has service and intermediate models for most of the services. Couldn't find one for S3 service.

Any idea if it is version controlled somewhere else?

**Comment by shorea** [comment]
S3 is handwritten in V1 of the Java SDK. You can find the service model in some of the other language SDKs that do generate S3, https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/s3/2006-03-01/api-2.json. There is no corresponding intermediate model since that is a Java specific code gen construct.

**Comment by brsanthu** [comment]
Thanks @shorea. I will refer to that.

I would like to understand more about aws-sdk-java code generation process. It is documented anywhere? or talked about?

If not, is it possible to create some high-level documentation for that?

**Comment by shorea** [comment]
The code generator is a bit cryptic, it uses freemarker as a templating engine. We don't really have documentation on it outside like javadocs on the classes themselves. Is there something specific you are looking to do with it?

**Comment by brsanthu** [comment]
Just curious to understand how it is done and to learn from it to see if we can adopt similar process to our own product sdks.

**Comment by varunnvs92** [comment]
As shorea@ mentioned, we don't have documentation for it. The codegen is a bit complex and we might change internally how it works, so it would be lot of effort to maintain the documentation.

[This](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-code-generator/src/main/java/com/amazonaws/codegen) is the module if you are interested in learning through source code.
You need start with [CodeGenerator class](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-code-generator/src/main/java/com/amazonaws/codegen/CodeGenerator.java) and execute() method in it.

If we decide to add documentation in future, we will update you. Thank you for your interest.

**Comment by brsanthu** [comment]
I'd understand. Thank you.

**Comment by shorea** [comment]
For what it's worth we are moving away from Freemarker and towards Java Poet for V2 of the SDK (https://github.com/aws/aws-sdk-java-v2). We've found this leads to much more maintainable code that's easier to debug and step through. It does hurt readability somewhat for larger static code blocks but overall it's been much better for us. It also helps with imports and generating a consistent layout. As a general rule of thumb it's best to keep the code that you do generate minimal and as simple as possible, do all the heavy lifting and actual logic in core/runtime classes that are handmaintained. Handwritten code is much cheaper to write and much easier to unit test, code generation is best for things like POJO objects and minimal wiring of components.  A good example of this is our JSON marshallers, the code to marshall is quite complicated but it's hidden behind a simple interface and the code is easy to generate, https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/model/transform/PutItemRequestMarshaller.java. In V2 we've also gotten great value out of functional tests for the code generation that just asserts the output matches that of a given resource, this is essentially an acknowledged diff that gives you quick feedback on changes to the code generator (https://github.com/aws/aws-sdk-java-v2/blob/master/codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/PoetClientFunctionalTests.java). If you have any specific questions feel free to hit me up on gitter.
