### ISSUE TITLE
code samples for Amazon PinPoint

### ISSUE THREAD

**Issue by madhugilla** [aws/aws-sdk-java#1281]
Hi,

Can you please add amazon java sdk pinpoint samples please it will be easy to get started without setting up a project..etc

**Comment by shorea** [comment]
I'll forward this feedback to the Pinpoint team. Closing this issue.

**Comment by jsolman** [comment]
Have you tried using AWS Mobile Hub to get a sample project that uses Pinpoint?
https://console.aws.amazon.com/mobilehub
