### ISSUE TITLE
Copying S3 object loses metadata when SSEAlgorithm is set

### ISSUE THREAD

**Issue by rideliner** [aws/aws-sdk-java#1283]
Per the documentation of [x-amz-metadata-directive](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html), the "server-side-encryption" metadata is not copied from the source, but if specified explicitly in the copy request, S3 adds it to the resulting object.

When setting metadata for a copy request that only contains the server side encryption algorithm set to AES256, the resulting object has the encryption set, but none of its original metadata copied with it.

The issue is that unlike the storage class and redirect location (the other blacklisted metadata items), the server side encryption cannot be set outside of the metadata. Because the metadata passed to the request is not null, it sets the "x-amz-metadata-directive" header to "REPLACE" instead of "COPY".

Example of SDK
```java
ObjectMetadata metadata = new ObjectMetadata();
metadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
CopyObjectRequest req = new CopyObjectRequest()
        .withNewObjectMetadata(metadata);
client.copyObject(req);
```

Example of CLI
```bash
aws s3api copy-object --bucket example-bucket --key image.png --copy-source source-bucket/image.png --server-side-encryption AES256
```

The CLI copies the existing metadata (minus the blacklisted metadata) to the new object, but the SDK does not.

**Comment by shorea** [comment]
@rideliner unfortunately I don't believe we can change the current behavior without risking breaking other customers. We could however expose a way to specify the metadata directive on the CopyObjectRequest explicitly so you could do something like the below

```java
ObjectMetadata metadata = new ObjectMetadata();
metadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
CopyObjectRequest req = new CopyObjectRequest()
        .withNewObjectMetadata(metadata)
       .withMetadataDirective(MetadataDirective.COPY);
client.copyObject(req);
```

Would this meet your needs?

**Comment by rideliner** [comment]
Yes. That would be great!

**Comment by shorea** [comment]
Got this out in CR. Hopefully should be available this week. If you need a workaround until then you can set a custom request header.

```java
CopyObjectRequest copyObjectRequest = new CopyObjectRequest("source-bucket", "source-key", "dest-bucket", "dest-key");
copyObjectRequest.putCustomRequestHeader("x-amz-metadata-directive", "COPY");
```

**Comment by shorea** [comment]
This has been pushed and will be available in our next scheduled release, in version 1.11.191. That should hopefully happen sometime this week, otherwise early next week. Preemptively closing this issue, feel free to reopen if the new version does not meet your needs.
