### ISSUE TITLE
s3 client throwing exception when not providing region 

### ISSUE THREAD

**Issue by sar009** [aws/aws-sdk-java#1284]
my code looks as follows
```
BasicAWSCredentials credentials = new BasicAWSCredentials("key", "secret");
AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
    .withCredentials(new AWSStaticCredentialsProvider(credentials))
    .build();
```
it throws `SdkClientException` when ever i am not passing region(`.withRegion()`). 
the error I get is
```
Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
```

why is region mandatory in s3. 

stack trace for reference
```
! com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
! at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:371)
! at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
! at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
```

**Comment by shorea** [comment]
Are you trying to use buckets in multiple regions?

**Comment by sar009** [comment]
no

**Comment by shorea** [comment]
Gotcha, region is mandatory for all client builders including S3. It's best practice to specify the region your buckets are located in but if you do have a need for a global s3 client you can use the [withForceGlobalBucketAccessEnabled](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#withForceGlobalBucketAccessEnabled-java.lang.Boolean-) option to interact with buckets in multiple regions. 

Some more info on setting a region in the builders is available [here](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html).
