### ISSUE TITLE
InterruptedException in TransferManager and ProgressListener

### ISSUE THREAD

**Issue by AadithyaU** [aws/aws-sdk-java#1285]
I am using Transfer Manager to upload file to S3. I am attaching progress listener to get all the event updates.
My use case depends on the progress listener and hence I want high reliability that the progress listener will be called in case of all events.
I was going through the code to find out how the progress listener is used and when are they fired.
I have a question regarding that.
 
1. TransferManager takes ExecutorService as input
2. When upload is called, it setups the request and calls UploadMonitor to put manage the upload.
3. After this all the events are being handled by the Upload Monitor or the underlying S3Client
 
I couldn’t find the place where, what would happen if the thread that is executing the request gets interrupted?
My question here is, will the progress listener get the FAILED event in this case?
If not, isn’t that the expectation as this reduces the reliability or use-case of progress listeners?
Then relying on the resultant upload.waitForCompletion(), the only option to get the update regarding Interrupted event?

**Comment by shorea** [comment]
Not sure I understood all your questions but I'll do my best to answer them. You ask if events are being handled by the UploadMonitor or the S3Client. To my knowledge most events are handled by the S3 client and the core runtime. We wrap input streams so that we report bytes as they are streamed to the listeners. 

In terms of interrupted exception we handle that via a custom input stream that throws AbortedException on interrupt. This will propagate to the listeners as a FAILED event. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/internal/SdkFilterInputStream.java#L50

**Comment by AadithyaU** [comment]
@shorea, Yes, most of the events are handled by the underlying S3Client.

Let me tell a use-case and the issue/problem.
I am using TransferManager to upload a file. Assume multi-part uploads are disabled.
So it will upload the given object in one whole junk. Now in this case, all the events are handled by S3Client and TransferManager does not add any additional events to it.

Now my question is, [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadMonitor.java#L117) the upload task is getting added to the executor. What if the thread that is executing the task fails?
InterruptedException will be thrown in general (which we will get if we do future.get()). But Will we get TRANSFER_FAILED_EVENT in ProgressListener? Is that case handled?

**Comment by shorea** [comment]
Yes you should get a TRANSFER_FAILED_EVENT, if the upload is done in a single chunk we internally call AmazonS3#putObject which will send this event on any failure, including interrupt related failures.

https://github.com/aws/aws-sdk-java/blob/08207c0d96cd2e532d544a98c984545c77a2256f/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1724
