### ISSUE TITLE
Running out of connections

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1289]
I'm sure it's my code and not yours, I've updated the AWS SDK recently and at the same time changes the way I am using S3 and TransferManager under very high load. 

Recently something is causing my server to freeze, everything gets stuck waiting lease a connection from the pool. 

What would really help me is some sort of tracing option that would periodically print out every "in-use" connection along with the stack trace of when it was leased (so I could see what part of my code is somehow missing an SObject#close or maybe misusing TransferManager.  Is there anything like that? 

I have an unbounded fixed size (64) queue for TransferManager and a max client pool size of 128 for S3. This has always worked well before, the service is very concurrent and so it shares these instances. But as I said, it appears the connection pool is getting exhausted even though I generally only have about 20 requests going on a time.

**Comment by rdifalco** [comment]
@dagnir: I believe this is my issue but it sure would help me find it if you have some tracing call I could make to print out all the currently leased connection and where they were allocated from (i.e. their stack trace).

**Comment by dagnir** [comment]
Gotcha. We currently don't have anything like what you describe. The closest thing currently would be client side metrics, which would log various stats after each request, like the connection pool size and active leases, among other things: https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/. I'll go ahead and mark this as a feature request.

**Comment by rdifalco** [comment]
Might be a better feature request for the new Java SDK. Would be great to have configuration options like "TrackConnectionStackTraces" that would just on lease annotate it with a Throwable. Then when returning to the pool it clear the stack trace. Then you could have a util method like "ConnectionStats.printLeasedConnections()` that would go through every open connection and print its thread name and stack trace. This is similar to what Hikari DB Connection Pool does for detecting leaks. It makes it super easier to see who (for example) got an S3Object but never closed it. It might also help with your own internal debugging. If TrackOpenConnections isn't enabled then you would call `new Throwable()` on each lease.

**Comment by dagnir** [comment]
I've gone ahead and opened up https://github.com/aws/aws-sdk-java-v2/issues/143. Better introspection of the SDK is definitely something we've discussed in the past and would be great to have.
