### ISSUE TITLE
AWS SNS Cloudwatch metric - SMSMonthToDateSpentUSD

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#1291]
I'm using AWS SNS service and monitoring the metrics using cloudwatch.

Could I know why the value of metric '**SMSMonthToDateSpentUSD**' is keep on increasing even I stop publishing new messages for few hours?

Regards,
Gowtham

**Comment by shorea** [comment]
@gowthamsankar312 This is a better question for AWS support. http://docs.aws.amazon.com/awssupport/latest/user/getting-started.html

**Comment by gowthamsankar312** [comment]
Thank you.
@shorea
