### ISSUE TITLE
AWS Java SDK does not respect custom JDK TrustStore

### ISSUE THREAD

**Issue by rcha** [aws/aws-sdk-java#1294]
The SDK uses a custom HttpClientBuilder that does not respect the majority of system properties.

**Comment by spfink** [comment]
Which system properties are you trying to use?

**Comment by shorea** [comment]
This is a feature request to honor more system properties like javax.net.ssl.trustStore.

http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html

**Comment by shorea** [comment]
@apfritts  I believe you can do that via a custom socket factory. https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ApacheHttpClientConfig.html#withSslSocketFactory-org.apache.http.conn.socket.ConnectionSocketFactory-

```java
ClientConfiguration config = new ClientConfiguration();
config.getApacheHttpClientConfig().setSslSocketFactory(....);
```

**Comment by aghag10** [comment]
@apfritts Were you able to set up a trust store in aws java sdk client? 
@shorea I'm looking at the code in ApacheHttpClientConfig code in the sdk - 

 public void setSslSocketFactory(ConnectionSocketFactory sslSocketFactory) {
        this.sslSocketFactory = sslSocketFactory;
    }

But I don't see any method to set keystore path in ConnectionSocketFactory. Any pointers?

**Comment by toroc** [comment]
@shorea are there any plans to support this feature to override the JDK truststore location? We are trying to use the Redshift JDBC driver with the AWS Java SDK in a containerized environment. We maintain a truststore in a persistent volume and need to have the driver pick up certificates from that truststore.

**Comment by shorea** [comment]
Hey no longer with the SDK team but I'm pretty sure the SDK now respects the Java system properties for custom trust stores. Can you give that a try and report your results?

-Djavax.net.ssl.trustStore
-Djavax.net.ssl.trustStorePassword

**Comment by apfritts** [comment]
> @apfritts I believe you can do that via a custom socket factory. https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ApacheHttpClientConfig.html#withSslSocketFactory-org.apache.http.conn.socket.ConnectionSocketFactory-
> 
> ```java
> ClientConfiguration config = new ClientConfiguration();
> config.getApacheHttpClientConfig().setSslSocketFactory(....);
> ```

@shorea yes! Sorry I didn't respond earlier but this works fabulously. Thanks!

**Comment by chandrabipin** [comment]
> > @apfritts I believe you can do that via a custom socket factory. https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ApacheHttpClientConfig.html#withSslSocketFactory-org.apache.http.conn.socket.ConnectionSocketFactory-
> > ```java
> > ClientConfiguration config = new ClientConfiguration();
> > config.getApacheHttpClientConfig().setSslSocketFactory(....);
> > ```
> 
> @shorea yes! Sorry I didn't respond earlier but this works fabulously. Thanks!

Can you provide more details as how can we set the truststore here...

**Comment by salviof** [comment]
Thats NOT working form me:
    ClientConfiguration awsHttpsClientConfig = new ClientConfiguration();
            awsHttpsClientConfig.setProtocol(Protocol.HTTPS);

            SSLContext contextTrustAllssl = SSLContexts.custom()
                    .loadTrustMaterial(new TrustAllStrategy())
                    .build();
            awsHttpsClientConfig.getApacheHttpClientConfig()
                    .withSslSocketFactory(new SSLConnectionSocketFactory(contextTrustAllssl));

            VerifyDomainIdentityResult verifyDomain = AmazonSimpleEmailServiceClientBuilder.standard()
                    .withCredentials(new AWSStaticCredentialsProvider(awsCreds))
                    .withClientConfiguration(awsHttpsClientConfig)
                    .withRegion(Regions.AP_EAST_1)
                    .build().verifyDomainIdentity(verifyProperties);
Fuck!
This could be simpler... Whats wrong?

**Comment by wojtasskorcz** [comment]
Joining @chandrabipin question to @apfritts. Also, question to the repo maintainers -- could you confirm if what @shorea said above is true?

> Hey no longer with the SDK team but I'm pretty sure the SDK now respects the Java system properties for custom trust stores. Can you give that a try and report your results?
> 
> -Djavax.net.ssl.trustStore 
> -Djavax.net.ssl.trustStorePassword

**Comment by apfritts** [comment]
@wojtasskorcz @chandrabipin

I’m no longer with Box so I can look up what I did and I don’t play in the Java world any more. Sorry!

**Comment by debora-ito** [comment]
Yes, Java SDK v1 honors the system properties javax.net.ssl.trustStore and javax.net.ssl.trustStorePassword.
