### ISSUE TITLE
"WEB-INF" as root level folder name can't be accessed via SDK?

### ISSUE THREAD

**Issue by starry-chan** [aws/aws-sdk-java#1295]
We are able to manually create folder with name "WEB-INF" at the root level of bucket. However any action towards the folder via SDK would return 404 not found.

![image](https://user-images.githubusercontent.com/31837165/30257676-46803d68-96e6-11e7-9aa9-24b8b011e2f3.png)

```
ObjectListing ol = s3Client.listObjects(new ListObjectsRequest().withBucketName(bucketName));
for (S3ObjectSummary summary : ol.getObjectSummaries()) {
    if (!s3Client.doesObjectExist(bucketName, summary.getKey())) {
	System.out.println(summary.getKey() + " doesn't exist");
    }
}
```

> WEB-INF/ doesn't exist
> WEB-INF/conf/ doesn't exist
> WEB-INF/conf/xxxxxxxxx.html doesn't exist

It always works with folder name containing hyphens, only fails when it is exactly "web-inf". I'm working around to avoid this name at the same time wishing it to be resolved.

**Comment by dagnir** [comment]
Hi @starry-chan, it's possible S3 is treating paths starting with "WEB-INF" specially. You can get around this by [enable path style addressing](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#withPathStyleAccessEnabled-java.lang.Boolean-)

**Comment by spfink** [comment]
Bucket names that contain uppercase characters are not DNS compliant and can only be created in the us-east-1 region currently. You must enable path-style addressing for this use case to work but it is recommended that you use a DNS compatible bucket name.

http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by starry-chan** [comment]
https://bucket.region.amazonaws.com/WEB-INF/file.txt doesn't work
https://region.amazonaws.com/bucket/WEB-INF/file.txt works

> https://stackoverflow.com/questions/43109359/how-to-change-amazon-s3-file-url-like-s3-amazonaws-com-bucket-key-from-bucket-s3
> By default pathstyleaccess is false so your uploaded file should be bucket.s3.amazonaws.com/key but when you explicitly add clientOptions -- pathStyleAccess to true then it will generate URL like s3.amazonaws.com/bucket/key.

The option WORKS! Thanks everyone!

**Comment by shorea** [comment]
Got a response from the S3 service team. This is a known bug and no fix is currently planned. The suggested workaround is to use path style addressing as mentioned above.

**Comment by missedone** [comment]
I encountered the same issue, and it turns out that the object key can't start with "WEB-INF", the workaround is adding prefix before "WEB-INF", e.g. "www/WEB-INF/"
