### ISSUE TITLE
Allow a user to add a JVM shutdown hook to drain metrics queue

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java#1296]
Metrics published asynchronously are sometimes lost when the JVM shuts down, which can happen relatively often in serverless environments. This usually is not a problem, because there is usually little impact from the loss of a few metrics, but in some cases the user would want to make sure the metrics are fully released before the JVM shutdown finishes. A shutdown hook (or similar mechanism) should be introduced to allow this.

**Comment by debora-ito** [comment]
Closing this, will be considered for SDK for Java V2.
