### ISSUE TITLE
Unable to connect to AWS through CLI

### ISSUE THREAD

**Issue by kusharora02** [aws/aws-sdk-java#1297]
Hi,

In our office network we use a proxy so I am not able to connect to aws at office network.

I tried to setup HTTP_PROXY and HTTPS_PROXY as mentioned in aws documentation. 

http://docs.aws.amazon.com/cli/latest/userguide/cli-http-proxy.html

Still I am getting connect timed out (443) error. 
can any one help on this?

Thanks

**Comment by shorea** [comment]
Are you using the CLI or the Java SDK?

**Comment by kusharora02** [comment]
Hi MY requirement is I have already jar file which is using java sdk internally, I need to run it in an proxy environment, If run in open network it works fine but in proxy environment it gives connection time out.

I know one way in which set proxy at code level using client configuration. though I already have jar file I cannot provide proxy through client configuration.  so is there any other way to set proxy? I already tried environment variable for http and https but it did not help.

**Comment by shorea** [comment]
It looks like we may only respect the JVM system properties. Can you try setting that? Looks like host and port would be specified separately.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L593

**Comment by spfink** [comment]
@kusharora02 have you been able to test using the JVM system properties as suggested by @shorea above?

**Comment by kusharora02** [comment]
Hi @spfink  and @shorea  I am still not able access connect to s3 i have verified that credentials are setup correctly. Is there any way to set proxy out side the code in envrionment variable or cntlm as i have jar file i cannot add proxy configuration at code level.

**Comment by shorea** [comment]
Can you share how you are starting the application? We should be honoring the JVM system properties.

**Comment by shorea** [comment]
Closing issue, feel free to reopen if problem persists.
