### ISSUE TITLE
S3 SDK: CopyObjectRequest does not allow setting SSE-S3 to destination object

### ISSUE THREAD

**Issue by MastaP** [aws/aws-sdk-java#1301]
Hello.

According to the documentation during the copy operation,
> Amazon S3 resets the system controlled metadata. 
http://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjectsExamples.html

which means that if a source object had S3-managed encryption (SSE-S3) set, the copied object becomes unencrypted.
For some unknown reason, CopyObjectRequest class only supports SSE-C and SSE-KMS (and CLI, for instance, supports all three kinds on encryption).

In my project I was able to resolve this issue by extending SSEAwsKeyManagementParams allowing `getEncryption()` in my class to return SSEAlgorithm.AES256 instead of a hard-coded SSEAlgorithm.KMS.
Would you like me to create a PR with the fix? I've created this issue just to make sure there was no particular reason not to support SSE-S3.

Thanks

**Comment by shorea** [comment]
Can you set it on the NewObjectMetadata?

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/CopyObjectRequest.java#L669

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/ObjectMetadata.java#L710

**Comment by MastaP** [comment]
Not an option, this will erase existing user metadata.
In the code which makes copying I cannot afford to make another request to fetch source object's metadata in order to set it via NewObjectMetadata. In other words, for the copy operation I only know src and target paths and if a source object is encrypted or not.

In fact, resetting the encryption by AWS has been pretty big surprise. Quoting the documentation:
> When you copy an object, user-controlled system metadata and user-defined metadata are also copied. Amazon S3 resets the system controlled metadata. For example, when you copy an object, Amazon S3 resets creation date of copied object. You don't need to set any of these values in your copy request.

Is encryption user-controlled or system controlled? If former, it should not be reset. If latter, first, the paragraph might explicitly say it and second, how can it be system-controlled if **user** sets the encryption header to enable SSE-S3?
Next:
>When copying objects you can **request Amazon S3 to save the target object encrypted using** an AWS Key Management Service (KMS) encryption key, an **Amazon S3-managed encryption key**, or a customer-provided encryption key. Accordingly you must specify encryption information in your request. 

So, according to the documentation, it _should_ be possible, but in Java S3 SDK it's not implemented.
CopyObjectRequest should be consistent with SSE support, if it enables to set -C and -KMS, it should also allow setting -S3 encryption.

**Comment by shorea** [comment]
@MastaP would the new field added per https://github.com/aws/aws-sdk-java/issues/1283 be helpful for your use case?

**Comment by MastaP** [comment]
Yes, thanks for pointing out, but it rather looks like a workaround, not a proper solution (in terms of API consistency).
Currently it contains:
CopyObjectRequest.setSourceSSECustomerKey(SSECustomerKey sseKey)
CopyObjectRequest.setSSEAwsKeyManagementParams(SSEAwsKeyManagementParams params)

Could also include something like this:
CopyObjectRequest.setSSEAwsS3Managed(boolean enable)

**Comment by shorea** [comment]
@MastaP I totally agree it's not consistent with the API and can be confusing. The current S3 client is handwritten and thus takes a lot more liberties and deviates from the actual S3 API quite a bit which can be quite confusing when coming from another tool/SDK like the CLI that does follow the API exactly. For V2 of the Java SDK we are moving to code generating the S3 client to remain 100% compatible with their API and consistent. For V1 however I'm hesitant to add an additional parameter to the CopyObjectRequest because there will now be two places it can be set which may cause further confusion and brings up precedence questions.

**Comment by MastaP** [comment]
okay, thanks for the explanation. any rough estimates for V2?

**Comment by shorea** [comment]
@MastaP we don't have an estimate yet. We are still defining the scope of V2 but we will get back to you as soon as we have a rough idea. Closing this issue for now. V2 is currently in developer preview, we'd love to get your feedback, particularly the generated S3 client.

https://github.com/aws/aws-sdk-java-v2
https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/

**Comment by eboto** [comment]
@MastaP just had to deal with this myself. The following scala worked for me:

```scala
val copyReq = new CopyObjectRequest(fromContainer, fromName, toContainer, toName)
copyReq.putCustomRequestHeader("x-amz-server-side-encryption", "AES256")
this._s3Client.copyObject(copyReq)
```

**Comment by adrianwong81** [comment]
> @MastaP just had to deal with this myself. The following scala worked for me:
> 
> ```scala
> val copyReq = new CopyObjectRequest(fromContainer, fromName, toContainer, toName)
> copyReq.putCustomRequestHeader("x-amz-server-side-encryption", "AES256")
> this._s3Client.copyObject(copyReq)
> ```
@eboto thanks for the tip, worked like a charm.
