### ISSUE TITLE
Error in listAccessKeys call: Must specify userName when calling with non-User credentials

### ISSUE THREAD

**Issue by dy10** [aws/aws-sdk-java#1304]
In following code the first API call to iamClient (i.e. iamClient.getAccountAuthorizationDetails()) is working fine, but the 2nd API call ( iamClient.listAccessKeys() ) gives error. The error-msg and stack-trace is after the code.

The code is as follows:

```
private static void work() throws Exception {
	ClientConfiguration config = new ClientConfiguration();

	BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(accessKey, secretKey);
	AWSCredentialsProvider provider = new AWSStaticCredentialsProvider(basicAWSCredentials);

	AWSSecurityTokenService stsClient = AWSSecurityTokenServiceClientBuilder.standard().withCredentials(provider)
				.withRegion("us-west-2").withClientConfiguration(config).build();
	STSAssumeRoleSessionCredentialsProvider assumeRoleProvider = new STSAssumeRoleSessionCredentialsProvider.Builder(
				roleArn, sessionName).withStsClient(stsClient).withExternalId(externalId).build();

	AmazonIdentityManagement iamClient = AmazonIdentityManagementClientBuilder.standard().withRegion("us-west-2")
				.withCredentials(assumeRoleProvider).build();

	List<UserDetail> awsUsers = iamClient.getAccountAuthorizationDetails().getUserDetailList();
	for (UserDetail userDetail : awsUsers) {
		log(userDetail.getUserName());
	}
	List<AccessKeyMetadata> accessKeyMetadata = iamClient.listAccessKeys().getAccessKeyMetadata();
	for (AccessKeyMetadata key : accessKeyMetadata) {
		log(key.getAccessKeyId());
	}
}
```

The error msg and stack-trace is as follows:

> com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: Must specify userName when calling with non-User credentials (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: xxxxxxx)
> Time Taken: 11505
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
>         at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
>         at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.doInvoke(AmazonIdentityManagementClient.java:8275)
>         at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:8251)
>         at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.executeListAccessKeys(AmazonIdentityManagementClient.java:4845)
>         at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.listAccessKeys(AmazonIdentityManagementClient.java:4821)
>         at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.listAccessKeys(AmazonIdentityManagementClient.java:4857)
>         at com.dy.aws.iam.GetAccessKeyTest.work(GetAccessKeyTest.java:45)
>         at com.dy.aws.iam.GetAccessKeyTest.main(GetAccessKeyTest.java:56)

**Comment by shorea** [comment]
Seems like you might be using temporary or assume role credentials. When calling with IAM user credentials (that is static access key and secret access key) looks like IAM can infer from the credentials which user you want to list access keys for. When you call with non user credentials you must specify the user explicitly in the request.
