### ISSUE TITLE
Documentation for multipart download APIs

### ISSUE THREAD

**Issue by fernomac** [aws/aws-sdk-java#1308]
Hi friends!

It's super cool to see the new (ish? since the last time I checked at least) support for parallelized downloads of multipart objects in the Java SDK. I'm not seeing the parameters used to do it documented on S3's side though (looks like number of parts is returned as object metadata and part number is an optional parameter to GET object?). If this is an officially-supported API from S3, any chance you could get them to document it? We're a little wary of using something that isn't officially supported and documented by the service team, even if it is in the official SDK.

Thanks!

**Comment by shorea** [comment]
Hey @fernomac, I'll reach out to S3 to see if it's something they want to document. Also related, we've been asked to replace the implementation with a more traditional Content-Range approach which is documented and would give the customer a bit more flexibility in choosing the partition size.

https://github.com/aws/aws-sdk-java/issues/1303

**Comment by fernomac** [comment]
Thanks for the pointer and sorry for not searching the issue history!
