### ISSUE TITLE
Cloud Trail multi region dilemma

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1309]
Hi
I created a multi-region CloudTrail… meaning I marked “Apply trail to all regions” and as a result I see the same Cloud Trail name at all regions
Now, when I use the AWSCloudTrailClient sdk to inquiry this trail object at specific region (e.g. eu-central-1) which is not the original region I create the region at (e.g. eu-west-1), I get the trail object but with arn of the original region (e.g. arn:aws:cloudtrail:eu-west-1:XXXXXX:trail/YYYYYY)
More, this arn can’t be used at another SDK APIs for the other region (eu-central-1). It throws exception “com.amazonaws.services.cloudtrail.model.CloudTrailARNInvalidException: Region in ARN is wrong, you can only access resources in region eu-central-1.”
I’m stuck!
Is it a bug?? Or there is another way to inquiry the trail object not at the origin region (which I don’t know by the way)?

For now I added code that checks if the HomeRegion and my current region are the same, if not I open another connection to the original region and inquiry the object there! is this the only way?

**Comment by shorea** [comment]
@bmagic39 I can't say I know much about Cloudtrail but I am seeing the behavior you describe. It seems that when you create a multi region trail it only exists as a true resource in one region (the one you create it in) but it seems to pseudo exist in other regions via some kind of pointer (i.e. it will be returned in describe calls as you mention). Any attempts to manipulate the trail outside the region it was created in results in an exception. It looks like you can use read-only or describe like calls on a multi region trail in another region using the ARN.

I found [this documentation](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-concepts.html#cloudtrail-concepts-regional-and-global-services) which explains the multi region use case a little bit. If you have further questions I suggest reaching out to the service team via StackOverflow using the tag `amazon-cloudtrail`.
