### ISSUE TITLE
AmazonS3EncryptionClient issue on EMR cluster

### ISSUE THREAD

**Issue by gupdurga** [aws/aws-sdk-java#1310]
Hi Team,

I am trying to read S3 object from EMR cluster. I need to  use both AmazonS3Client and AmazonS3EncryptionClient
First i tried to use AwsS3JavaClient = external_release_1.9 package 
1. new AmazonS3Client(); 
=> Able to read data without any issue on local machine and EMR cluster
2. new AmazonS3EncryptionClient(encryptionMaterials);
=> Able to read on local machine, but when i am trying to read read on EMR getting below exception:
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 253452DED3650048), S3 Extended Request ID: XAjBGUFJvoL4Li0qu5B1uRUMuh1geLgkYIUvXxiIS42TxFcGu6OLsfeailU8vbbZxtDFRz6T62I= at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389) at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902) at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826) at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1143) at com.amazonaws.services.s3.AmazonS3EncryptionClient.access$201(AmazonS3EncryptionClient.java:79) at 

upgraded to AWSS3JavaClient = 1.11.x;
=> Able to run from Local machine for both the case, but getting error in EMR 
 java.lang.IllegalAccessError: tried to access class com.amazonaws.services.s3.AmazonS3ClientConfigurationFactory from class com.amazonaws.services.s3.AmazonS3Builder	at com.amazonaws.services.s3.AmazonS3Builder.<clinit>(AmazonS3Builder.java:30)	at com.amazon.forage.s3.AmazonS3ObjectProvider.getAmazonS3(AmazonS3ObjectProvider.java:27)	at com.amazon.forage.s3.S3Test.main(S3Test.java:27)	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.lang.reflect.Method.invoke(Method.java:498)	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

Can you some face/aware  how to fix the issue?

**Comment by shorea** [comment]
Can you try wiring up the InstanceProfileCredentialsProvider directly? S3 will fallback to anonymous access if credentials can't be found. If you use the Instance Profile provider directly it will throw an exception saying why it can't get credentials.

**Comment by shorea** [comment]
Problem was fixed by upgrading to EMR 5.8.0. Related to https://github.com/aws/aws-sdk-java/issues/1094
