### ISSUE TITLE
lambda.Policy deserialization bug on overloaded Statement.setPrincipals methods

### ISSUE THREAD

**Issue by SeanRoy** [aws/aws-sdk-java#1314]
com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "principals": com.amazonaws.auth.policy.Statement#setPrincipals(1 params) vs com.amazonaws.auth.policy.Statement#setPrincipals(1 params)

I'm getting the Exception above when I try to deserialize the lambda Policy:

GetPolicyRequest getPolicyRequest = new GetPolicyRequest()
                    .withFunctionName(lambdaFunction.getFunctionName());
            GetPolicyResult GetPolicyResult = lambdaClient.getPolicy(getPolicyRequest);
            Policy policy = Policy.fromJson(GetPolicyResult.getPolicy()

**Comment by shorea** [comment]
Wasn't able to reproduce this issue. The stack trace indicates that ObjectMapper is being used but we don't use ObjectMapper in our fromJson/toJson methods. Can you provide a complete code example?

**Comment by SeanRoy** [comment]
Thanks @shorea, I'm sorry, after seeing your hint above, I looked closer and realized that I was setting the Policy retrieved the function on a class which goes through some custom jackson parsing, using ObjectMapper.  My fault, but thank you for your quick attention to this.

**Comment by shorea** [comment]
Glad you were able to work it out :)
