### ISSUE TITLE
@DynamoDBDocument not working for a Map<Object, Object>

### ISSUE THREAD

**Issue by namral** [aws/aws-sdk-java#1315]
I tried to use @DynamoDBDocument to serialize a POJO that looks like this : 

`
@DynamoDBDocument
    public class Metadata {
        Map<Object, Object> metadata;
    
        public Metadata() {
        }
    
        public Metadata(Map<Object, Object> metadata) {
            this.metadata = metadata;
        }
    
        @DynamoDBAttribute
        public Map<Object, Object> getMetadata() {
            return stateMetadata;
        }
    
        public void setMetadata(Map<Object, Object> metadata) {
            this.metadata = metadata;
        }
    }

   @DynamoDBTable(tableName = "REPLACED_BY_CONFIG")
   public class ProductItem {
          private Metadata metadata;

         @DynamoDBAttribute
         public Metadata getMetadata() {
               return metadata;
         }
   }
`

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.Annotations.html#DynamoDBMapper.Annotations.DynamoDBDocument

It throws the following exception : 
Caused by: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: not supported; requires @DynamoDBTyped or @DynamoDBTypeConverted

I was able to get this to work by adding the following annotation to the getter method in ProductItem
`    @DynamoDBTypeConverted(converter = MetadataTypeConverter.class)`

I was wondering why I see this behavior ?

**Comment by millems** [comment]
At this time, maps can only be converted automatically without an annotation when the key type is a string. I've passed along the request to support more types (or at least a better error message) here: https://github.com/aws/aws-sdk-java-v2/issues/35

**Comment by dimPhotobox** [comment]
I still confirm, on the 18th of december 2017, aws-sdk.version=1.11.246, key as Integer are still unsupported...

**Comment by deevant07** [comment]
> At this time, maps can only be converted automatically without an annotation when the key type is a string. I've passed along the request to support more types (or at least a better error message) here: [aws/aws-sdk-java-v2#35](https://github.com/aws/aws-sdk-java-v2/issues/35)

--> Map<String,CustomObject> is also not working in the latest version 1.11.140... any changes again

**Comment by biniama** [comment]
Adding `@DynamoDBDocument` to the Custom Class made it work for me.
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBDocument.html

A dynamoDB table will not be created for this object.
This way, you don't need to implement a Converter class which `implements DynamoDBTypeConverter`
