### ISSUE TITLE
AWS JAVA SDK - Large json files under models folder.

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#1318]
Hi,

We had been using aws java sdk jar v1.3.26 to connect to aws services. Now we are upgrading to v1.11.171. The issue we face here is the jar file size as the new jar size is 64MB. After extracting the model folder alone consist of 273MB. 

We eager to know what's the real purpose of these json files because we have not seen one inside the old jar that we had been using for long time.

Can I know what will be the impact we face if we remove those large json files [entire model folder] ?

Regards,
Gowtham

**Comment by millems** [comment]
Hey Gowtham,

How are you taking a dependency on the SDK? We recommend just adding a dependency on the services that you require to minimize the code you pull in.

In this case it sounds like you might be pulling in the aws-java-sdk-models module, which has all of the model files in it. This dependency can be safely removed - it isn't needed for the SDK to function correctly.

**Comment by varunnvs92** [comment]
Were you able to try the suggestion by millems@?

**Comment by varunnvs92** [comment]
Feel free to reopen if you still face the issue.

**Comment by gowthamsankar312** [comment]
Thank you for your help. We decided to use the entire jar instead of modifing it.
@millems
