### ISSUE TITLE
Support for custom ClientConfiguration in AwsSdkMetrics

### ISSUE THREAD

**Issue by reecefenwick** [aws/aws-sdk-java#1319]
I'm trying to enable aws sdk metrics behind a corporate proxy, and want to avoid setting proxy settings for the JVM.

I can configure my own credentials provider like below:

```java
AwsSdkMetrics.setCredentialProvider(customCredentialsProvider);
```

I would also like to provide my own instance of ClientConfiguration, is there any reason it is not supported or has no one asked?

**Comment by millems** [comment]
I don't think anyone has asked! You could control the proxy settings JVM-wide using the system properties documented here: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html, but that's not ideal if you needed them to be localized to just the metrics client.

Do the system properties unblock you for now or are you blocked from using the metrics feature until this can be localized to just the metrics system?

**Comment by reecefenwick** [comment]
I am a hesitant to set those properties JVM wide, it will help me debug my current problem, but for me to use this feature across my platform in production I will definitely need to isolate these settings to the client.

**Comment by reecefenwick** [comment]
Any chance of this getting added? I don't see JVM properties being suitable at all given we use VPC endpoints for S3/Dynamo (therefore no proxy for those clients)

We have been having issues the past couple weeks and this would have been extremely useful, I had to modify sqs messaging library to find that we are getting very bad response times from SQS.
