### ISSUE TITLE
Expose a method in client builder that returns a default ClientConfiguration for a service. 

### ISSUE THREAD

**Issue by manikandanrs** [aws/aws-sdk-java#1325]
I have a use case where I need to change a few time out settings on the client and at the same time I would like to retain service specific default ClientConfiguration for other settings.

The service specific ClientConfiguration defaults are exposed today but they are marked as internal APIs. It would be nice if these classes are exposed for customers to consume and a method on builder that returns the service specific ClientConfiguration

**Comment by kiiadi** [comment]
@manikandanrs in [2.0](https://github.com/aws/aws-sdk-java-v2) we do much more sophisticated configuration merging ([DefaultClientBuilder](https://github.com/aws/aws-sdk-java-v2/blob/master/core/src/main/java/software/amazon/awssdk/client/builder/DefaultClientBuilder.java#L170) / [ClientConfigurationDefaults](https://github.com/aws/aws-sdk-java-v2/blob/master/core/src/main/java/software/amazon/awssdk/config/defaults/ClientConfigurationDefaults.java#L50)), making it possible to override only some settings and retain the original service defaults. I'd be interested to get your opinion on this to see if it would suit your use-case.

Which service are you trying to use? I don't see it as a massive risk to remove the `@SdkInternalApi` annotation from the `[AmazonDynamoDBClientConfigurationFactory](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClientConfigurationFactory.java)` as I think it's unlikely to change in this major version.

**Comment by debora-ito** [comment]
Hi @manikandanrs, as mentioned by @kiiadi this is supported in the V2 version of the SDK, so we decided not to implement this feature in V1. I'll go ahed and close this.

Please feel free to reach out if you have further questions.

**Comment by jxtps** [comment]
Please reopen this. It is trivial to open the scoping on the clientConfigFactory or on an accessor method to enable this. 

Instead you force me to either misconfigure my client, use reflection, or do an upgrade to v2 (which according to https://docs.aws.amazon.com/sdk-for-java/v2/migration-guide/whats-different.html doesn't support S3 transfer manager which I use, so no dice there as it's s3 I'm trying to configure).

**Comment by jxtps** [comment]
Adding a 
```
public ClientConfigurationFactory getClientConfigFactory() {
   return clientConfigFactory;
}
```
to AwsClientBuilder would do the trick, and since that class only exposes a single final method with which to get the populated ClientConfig, it would seem to be quite safe to provide an accessor for it.
