### ISSUE TITLE
Unable to load OSGi bundle from 1.11.205; 1.11.202 is OK

### ISSUE THREAD

**Issue by MushyMiddle** [aws/aws-sdk-java#1326]
Hi.  There appears to be a problem loading the OSGi version of the SDK on Oracle Java 8 (1.8.0_141).  It appears that a referenced package was added in 1.11.203 that is no longer available in Java 8.

INFO   | jvm 1    | 2017/10/02 17:25:33 | Starting bundle: com.amazonaws.aws-java-sdk-osgi
INFO   | jvm 1    | 2017/10/02 17:25:33 | org.osgi.framework.BundleException: The bundle could not be resolved. Reason: Missing Constraint: Import-Package: com.sun.org.apache.bcel.internal.util; version="0.0.0"
INFO   | jvm 1    | 2017/10/02 17:25:33 | 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1313)
INFO   | jvm 1    | 2017/10/02 17:25:33 | 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1297)
INFO   | jvm 1    | 2017/10/02 17:25:33 | 	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:309)
INFO   | jvm 1    | 2017/10/02 17:25:33 | 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:280)
INFO   | jvm 1    | 2017/10/02 17:25:33 | 	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:272)

**Comment by varunnvs92** [comment]
Thanks for reporting the issue. The import has been removed and will be released in tomorrow's release. I will update the ticket after the release.

**Comment by MushyMiddle** [comment]
Thanks for the quick work.

**Comment by varunnvs92** [comment]
Thanks for reporting this bug. It is fixed in v1.11.209. Please try it out and let us know if you still have the issue. Resolving.

**Comment by varunnvs92** [comment]
@MushyMiddle 
I believe you use our SDK in OSGI environment. We are working on a [SDK V2](https://github.com/aws/aws-sdk-java-v2). We are trying to make the v2 OSGI compatible. In V2, we use [ServiceLoader](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html) to load the http client implementations. However OSGI requires special configuration to work properly with ServiceLoader. See https://github.com/aws/aws-sdk-java-v2/issues/607
We are looking for an external customer to test the fix pushed to `varunkn/OsgiCompatibility` in v2. Is it possible for you to install the v2 sdk in OSGI, create a service client and make few API calls? Let me know if you have questions. Thank you.
