### ISSUE TITLE
Moving file atomic way with in s3? 

### ISSUE THREAD

**Issue by gowtham-sai** [aws/aws-sdk-java#1332]
I'm using s3fs and fastparquet to write parquet files to s3. I've configured presto to read from s3 using hive external table. 

Problem here is, presto will read from the file where fast parquet is writing, so it is failing saying invalid parquet file. To outcome this problem, I'll be writing to a temporary path, lets say, i'm supposed to write to 

```python
filename = 'bucket_name/account_type/yr=2017/mn=10/dt=8/19/de86d8ed-7447-420f-9f25-799412e377adparquet.json'
# let's write to temp file
tmp_file = filename.replace('account_type', 'tmp-account_type')
fastparquet.write(filename, df, open_with=opener)
fs.mv(tmp_file, fllename)
```
But even in this case, it looks like sometimes, rarely presto is reading incomplete file. How's this possible? How can we make this atomic/isolated with s3fs?
Referencing s3fs (issue)[https://github.com/dask/s3fs/issues/new]

**Comment by gabrielgrant** [comment]
Was this solved? We're wondering about atomic moves of S3 objects too
