### ISSUE TITLE
Need request Id support

### ISSUE THREAD

**Issue by sharadholani** [aws/aws-sdk-java#1333]
Every dynamoDb response contains a header (x-amzn-RequestId).
I need to access this header value using the sdk.

Right now, I think its accessible only via exception objects.

I need it for all the requests I make using the sdk.

**Comment by kiiadi** [comment]
@sharadholani you should be able to get at this via the response meta-data on every "result" object:

```java
ListTablesResult result = db.listTables();
System.out.println(result.getSdkResponseMetadata().getRequestId());
```

**Comment by sharadholani** [comment]
In com.amazonaws.services.dynamodbv2.document.DynamoDB class, the listTables() call returns a TableCollection<ListTablesResult> object and not a ListTableResult object.

db is an object of DynamoDB class right ?

**Comment by kiiadi** [comment]
Aaah you're using the document API. If you want to get the request Id you'll need to either use the low-level client `AmazonDynamoDB` or get it from the low-level request like so:

```java
DynamoDB db = new DynamoDB(AmazonDynamoDBClient.builder().withRegion("us-west-2").build());
db.listTables().getLastLowLevelResult().getSdkResponseMetadata().getRequestId();
```

Be aware though that through the document API (`DynamoDB`) results are automatically paginated, so the `listTables()` operation may actually make multiple calls if there are many pages of tables. Hence the 'last' in the `getLastLowLevelResult()` method - you'll get the most recent result/page.

If you want the requestId for each individual page you can do so like so:
```java
for(Page<Table, ListTablesResult> page: db.listTables().pages()) {
    System.out.println(page.getLowLevelResult().getSdkResponseMetadata().getRequestId());
}
```
