### ISSUE TITLE
Use of x-amz-id-2

### ISSUE THREAD

**Issue by sharadholani** [aws/aws-sdk-java#1336]
Why are there 2 different headers for a request id in the response headers ?

Why this could not be done in only 1 request id ?

What exactly is x-amz-id-2 used for ?

Is it necessary to provide both the request ids for troubleshooting?
Will extended request id suffice ?

**Comment by kiiadi** [comment]
@sharadholani that's really more of a question for service teams than the SDK - but typically the `x-amz-request-id` is sufficient for troubleshooting. This forum post might shed some more light on the differences between them : https://forums.aws.amazon.com/thread.jspa?threadID=32250
