### ISSUE TITLE
Missing @DynamoDBKeyed in DynamoDBIndexHashKey and DynamoDBIndexRangeKey 

### ISSUE THREAD

**Issue by MartianCitizen** [aws/aws-sdk-java#1337]
Package: com.amazonaws.services.dynamodbv2.datamodeling

DynamoDBIndexHashKey and DynamoDBIndexRangeKey are missing the @DynamoDBKeyed annotations that are present in DynamoDHashKey and DynamoDBRangeKey. This causes the usage described in http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.Methods.html#DynamoDBMapper.Methods.query to throw "DynamoDBMappingException: no mapping for HASH key". The workaround is to explicit add @DynamoDBKeyed to your mapper model.

**Comment by shorea** [comment]
@MartianCitizen Can you provide sample code and POJOs. Want to make sure I understand the problem before proceeding.

**Comment by shorea** [comment]
Closing issue for now. Feel free to reopen when you are able to provide sample code.
