### ISSUE TITLE
Update the outdated Java SDK samples

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-sdk-java#1341]
The Java SDK samples in the [**samples**](https://github.com/aws/aws-sdk-java/tree/master/src/samples) folder are outdated. The most up-to-date way for instantiating an AWS service client should be using builders, while they are still using the deprecated constructors. 

The AWS Toolkit for Eclipse are using these samples for beginners to learn AWS Java SDK. They will mislead beginners in the wrong way of using AWS Java SDK.

**Comment by dagnir** [comment]
The samples have been updated upstream to use the new builders. They will be included in the next release.
