### ISSUE TITLE
'x-amz-grant-full-control' header is passed incorrectly

### ISSUE THREAD

**Issue by yohei1126** [aws/aws-sdk-java#1346]
When I put an object to S3 with FullControl permission for a canonical id using Java SDK, The SDK adds escape double quotes around the ID. So, the request is as follows and it is rejected. 

```
"s3:x-amz-grant-full-control": "id=\"qwertyuiop\""
```

Request from CLI or Python SDK does not have escape double quotes around the ID, then request is accepted.

```
"s3:x-amz-grant-full-control": "id="qwertyuiop"
``` 

This might cause the issue.
https://github.com/aws/aws-sdk-java/blob/51428ab65a35a309c7853e91401f40f456d5b159/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1614-L1615

**Comment by dagnir** [comment]
Thanks for reporting the issue!

**Comment by dagnir** [comment]
Relabeling this as "Investigating" while I wait for a response from S3 to see if quotes in the grantee ID is valid, since it seems to both ways. The only time it doesn't is if you specify that a request must have a specific grantee value like in the following:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "statement1",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::AccountB-ID:user/Dave"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::examplebucket/*",
      "Condition": {
        "StringEquals": {
          "s3:x-amz-grant-full-control": "id=AccountA-CanonicalUserID"
        }
      }
    }
  ]
}
```

**Comment by dagnir** [comment]
As as workaround, you can change you `Condition` to the following:

```json
"Condition": {
    "StringLike": {
            "s3:x-amz-grant-full-control": [
                "id=\"qwertyuiop\"",
                "id=qwertyuiop"
            ]
    }
}
```

So it matches the quoted and unquoted versions.

**Comment by yohei1126** [comment]
I have the following statement in my bucket policy. CLI and Python SDK works fine but Java SDK does not.

```
        {
            "Sid": "DenyPutObjectWithoutGrantFullControl",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::mybucket/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-grant-full-control": "id=myid"
                }
            }
        },
```

There is an inconsistency between Python SDK and Java SDK. Python SDK does not add quotes on the header but Java SDK does. This is causing a confusion in my project. So, I want you to fix Java SDK.

**Comment by yohei1126** [comment]
Thank you for offering temporary workaround! It would work fine in my case where we use both of CLI (Python) and Java SDK. Although, I do not want to add the quoted and unquoted versions every time. So I expect that my fix get merged and both Python SDK and Java SDK support unquoted version.

**Comment by dagnir** [comment]
Sorry, I realize it's confusing to have inconsistent behavior across the SDKs. I'd like to do a survey of the other SDKs besides Java and Python to see what they do so we can all be consistent wrt to this behavior

**Comment by yohei1126** [comment]
My collegue also said putObject request from C# SDK was also rejected because of Access Denied Error. I did not check it but C# SDK might have the same issue.

**Comment by yohei1126** [comment]
Any updates?

**Comment by yohei1126** [comment]
Did you get any update?

**Comment by shorea** [comment]
@yohei1126 we are waiting on a response from the service team to figure out the best, safest way to proceed. Apologies for the delay, I'll let you know as soon as we get a response.

**Comment by yohei1126** [comment]
Thank you!

**Comment by yohei1126** [comment]
1 month already has passed since I opened this issue. Still no answer from S3 team?
I need this fix when I develop with Java SDK.

**Comment by varunnvs92** [comment]
S3 team responded that they accept both quoted and non-quoted values. I will submit a fix soon.

**Comment by varunnvs92** [comment]
@yohei1126 
After deeper discussion with the team, we decided not to change the current behavior as it breaks existing customers who have uploaded objects using quotes. S3 accepts both quoted and non-quoted values and there is no official guidance on which one to use, so this is essentially not a bug. 

The best path forward for you is to use the workaround suggested by dagnir@.
```
"Condition": {
    "StringEquals": {
        "s3:x-amz-grant-full-control": [
            "id=\"qwertyuiop\"",
            "id=qwertyuiop"
        ]
    }
}
```

Apologies for the delay in response as the ticket to service team got overlooked. Thank you for your patience. Let us know if you have any other questions.

**Comment by yohei1126** [comment]
I feel this is apparently a bug but thank you for your deep consideration.
