### ISSUE TITLE
Add module-info.java

### ISSUE THREAD

**Issue by hrchu** [aws/aws-sdk-java#1350]
So that projects depend on this can be published to a public artifact repository.
Note that this is not breaking backward compatibility. All codes except this file can be still compiled in Java 6.

**Comment by polle** [comment]
Using automatic modules only works in some cases because there are spit packages. For example, the package com.amazonaws.auth exists in both aws-java-sdk-s3 and aws-java-sdk-core giving the following error:

`error: module demo reads package com.amazonaws.auth from both aws.java.sdk.core and aws.java.sdk.s3`

**Comment by hookla** [comment]
so whats the solution for now ?

**Comment by rferreira** [comment]
The real issue here is split packages, effectively rendering the SDK unusable in a JPMS (jdk9 or later) runtime.

**Comment by damnhandy** [comment]
A relatively low-effort way of addressing this is to add an `Automatic-Module-Name` value to the `MANIFEST.MF` in each JAR file. This could be done in maven by adding something like:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <configuration>
    <archive>
      <manifestEntries>
        <Automatic-Module-Name>com.amazonaws.aws.java.sdk.iam</Automatic-Module-Name>
      </manifestEntries>
    </archive>
  </configuration>
</plugin>
``` 

This doesn't get around the modules dependencies, but it helps ensure that we don't get module naming collusions, etc..

**Comment by jhg023** [comment]
Any update(s) on this? I have some code being used from v1 (as it doesn't exist yet in v2), and I'm encountering a split package on `com.amazonaws.auth`.

**Comment by akud** [comment]
This is still a problem as of `1.11.480`, the latest version on maven central

**Comment by edusasse** [comment]
Any update on this issue?

**Comment by rosanas88** [comment]
Hey I'm migrating to jdk 11, is there any update about this ?

**Comment by akud** [comment]
I think your best bet is to use the v2 sdk if you want to do modules. I doubt they will be fixing the split packages any time soon.

**Comment by rosanas88** [comment]
Thank you @akud! Worked fine.

**Comment by debora-ito** [comment]
We don't have plans to support this in v1 before going into Maintenance Mode, so I'll go ahead and close this issue.

Java SDK v2 uses Automatic-Module-Name and doesn't have split packages, please check it out and send us any feedback or issue reports by creating a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
