### ISSUE TITLE
Resuming download with TransferManager not working after JVM restart

### ISSUE THREAD

**Issue by valdiblondal** [aws/aws-sdk-java#1351]
For demonstration purposes I've made a short program using aws java sdk 1.11.118: https://drive.google.com/file/d/0B5I97wOzbG7MdDBDVkVjZVVWejA/view?usp=sharing

On the first run it starts downloading a +300MB file but exits when it's half done. It uses every chance to save the download state. 

On second run it reads the state file to resume the download. But it always starts from the beginning and takes twice as long as the first run.

Unfortunately it looks like the download state is only saved in the beginning and when the last parts are being downloaded and concatenated.

I've tried adding a shutdown hook to call download.pause() and save that state without success.

I see that com.amazonaws.services.s3.transfer.internal.DownloadPartCallable.java deletes all the parts on JVM exit which was a little surprising since com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload only joins them in the end. So I'm not sure how this is supposed to have any chance of working if the chunks are not stored locally after exit.

And here's the output from these 2 runs:
--- FIRST RUN ----

12:28:54: Jar comes from: file:/D:/jdk_supp/amazon/aws-java-sdk-1.11.118/lib/aws-java-sdk-1.11.118.jar
12:28:54: Starting from scratch
12:28:55: Saving download state
12:28:55: Total bytes to transfer: 354101561
12:28:55: Bytes transferred: 0
12:28:55: downloaded: 0
12:28:55: downloaded: 10.240
12:28:57: downloaded: 10.507.340
12:28:59: downloaded: 21.004.364
12:29:00: downloaded: 31.501.388
12:29:01: downloaded: 41.998.412
12:29:02: downloaded: 52.495.436
12:29:04: downloaded: 62.992.460
12:29:05: downloaded: 73.495.626
12:29:06: downloaded: 83.987.896
12:29:08: downloaded: 94.477.799
12:29:09: downloaded: 104.972.856
12:29:11: downloaded: 115.467.494
12:29:12: downloaded: 125.960.927
12:29:13: downloaded: 136.455.012
12:29:14: downloaded: 146.952.036
12:29:15: downloaded: 157.449.060
12:29:16: downloaded: 167.946.084
12:29:17: Exiting

--- SECOND RUN ---

12:29:40: Jar comes from: file:/D:/jdk_supp/amazon/aws-java-sdk-1.11.118/lib/aws-java-sdk-1.11.118.jar
12:29:40: Starting again
12:29:41: Total bytes to transfer: 354101561
12:29:41: Bytes transferred: 0
12:29:41: downloaded: 0
12:29:41: downloaded: 10.240
12:29:43: downloaded: 10.507.340
12:29:44: downloaded: 21.004.364
12:29:45: downloaded: 31.501.388
12:29:47: downloaded: 41.998.412
12:29:48: downloaded: 52.495.436
12:29:49: downloaded: 62.992.460
12:29:50: downloaded: 73.482.362
12:29:51: downloaded: 83.985.528
12:29:53: downloaded: 94.478.351
12:29:54: downloaded: 104.979.865
12:29:55: downloaded: 115.476.889
12:29:56: downloaded: 125.975.913
12:29:57: downloaded: 136.476.584
12:29:59: downloaded: 146.973.608
12:30:00: downloaded: 157.463.510
12:30:01: downloaded: 167.962.719
12:30:03: downloaded: 178.456.212
12:30:04: downloaded: 188.955.236
12:30:06: downloaded: 199.453.770
12:30:07: downloaded: 209.956.818
12:30:08: downloaded: 220.458.154
12:30:09: downloaded: 230.948.114
12:30:10: downloaded: 241.445.138
12:30:12: downloaded: 251.948.306
12:30:13: downloaded: 262.447.210
12:30:14: downloaded: 272.946.176
12:30:15: downloaded: 283.445.138
12:30:17: downloaded: 293.944.181
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: Saving download state
12:30:18: downloaded: 304.436.990
12:30:20: downloaded: 314.934.689
12:30:22: downloaded: 325.423.980
12:30:23: downloaded: 335.921.004
12:30:25: downloaded: 346.422.016
12:30:25: Saving download state
12:30:25: Saving download state
12:30:25: Saving download state
12:30:25: Saving download state
12:30:25: Saving download state
12:30:25: Saving download state
12:30:25: Saving download state
12:30:27: Saving download state
12:30:27: Saving download state
12:30:27: Saving download state
12:30:27: This is over

**Comment by shorea** [comment]
@valdiblondal are you using parallel or serial downloads? Can you paste your sample code in the github issue as well?

**Comment by valdiblondal** [comment]
@shorea I'm using parallel.

```
package awstest;

import com.amazonaws.auth.*;
import com.amazonaws.event.ProgressEvent;
import com.amazonaws.services.s3.model.GetObjectRequest;
import com.amazonaws.services.s3.transfer.*;
import com.amazonaws.services.s3.transfer.internal.S3ProgressListener;
import com.amazonaws.services.s3.transfer.internal.S3SyncProgressListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.net.URL;
import java.security.CodeSource;
import java.security.ProtectionDomain;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Date;

public class AwsResumeTest 
{
   private static final File LOCAL_RESUME_INFO = new File(System.getProperty("user.home"), "amazondownloadtest.resumeinfo");
   private static final boolean DOWNLOAD_HALF_AND_KILL = !LOCAL_RESUME_INFO.exists();
   private static final File LOCAL_BIG_FILE = new File(System.getProperty("user.home"), "amazondownloadtest.bigfile");
   
   private static Download DOWNLOAD;
   
   public static void main(String[] args) throws Exception
   {
      AWSCredentialsProvider creds = OtherClass.getCredentialsProvider();
      String bucket = OtherClass.getTestBucket();
      String key = OtherClass.getTestKey();
      
      TransferManager tm = new TransferManager(creds);
      log("Jar comes from: " + getClassJar(tm.getClass()));
      
      if (DOWNLOAD_HALF_AND_KILL)
      {
         GetObjectRequest gor = new GetObjectRequest(bucket, key);
         log("Starting from scratch");
         DOWNLOAD = tm.download(gor, LOCAL_BIG_FILE, LISTENER);         
      }
      else
      {
         log("Starting again");
         DOWNLOAD = tm.resumeDownload(PersistableDownload.deserializeFrom(new FileInputStream(LOCAL_RESUME_INFO)));
         DOWNLOAD.addProgressListener(LISTENER);
      }

      log("Total bytes to transfer: " + DOWNLOAD.getProgress().getTotalBytesToTransfer());
      log("Bytes transferred: " + DOWNLOAD.getProgress().getBytesTransferred());

      DOWNLOAD.waitForCompletion();
      log("This is over");
      
      tm.shutdownNow();
      if (DOWNLOAD.isDone())
         LOCAL_RESUME_INFO.delete();
      
      System.exit(0);
   }
   
   private static void log(String msg)
   {
      System.out.println(DateFormat.getTimeInstance().format(new Date()) + ": " + msg);
   }
   
   private static long LAST_LOGGED_BYTES;
   private static final S3ProgressListener LISTENER = new S3SyncProgressListener()
   {
      @Override
      public void progressChanged(ProgressEvent pe)
      {
         long bytes = DOWNLOAD.getProgress().getBytesTransferred();
         
         if (pe.getEventType().isByteCountEvent())
         {
            if (LAST_LOGGED_BYTES == 0 || bytes - LAST_LOGGED_BYTES > 10*1024*1024)
            {
               LAST_LOGGED_BYTES = bytes;
               log("downloaded: " + NumberFormat.getNumberInstance().format(bytes));
            }
         }
         
         if (bytes > DOWNLOAD.getProgress().getTotalBytesToTransfer()/2 && DOWNLOAD_HALF_AND_KILL)
         {
            log("Exiting");
            System.exit(0);
         }
      }

      @Override
      public void onPersistableTransfer(final PersistableTransfer pt)
      {
         // TODO should not be blocked
         try
         {
            log("Saving download state");
            pt.serialize(new FileOutputStream(LOCAL_RESUME_INFO));
         }
         catch (Exception e)
         {
            e.printStackTrace();
         }
      }           
   };      

   private static String getClassJar(Class cls) throws Exception
   {
      ProtectionDomain pDomain = cls.getProtectionDomain();
      CodeSource cSource = pDomain.getCodeSource();
      URL loc = cSource.getLocation();   
      return loc.toString();
   }
}
```

**Comment by shorea** [comment]
@valdiblondal  was able to confirm this bug. Looks like we update the lastFullyDownloadedPartNumber in CompleteMultipartDownload task but that's only executed once all the parts have been downloaded and the file is being assembled.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/DownloadCallable.java#L195

Looking into a solution for this now.

**Comment by valdiblondal** [comment]
@shorea good to hear, thanks.

**Comment by valdiblondal** [comment]
@shorea any news or plans about fixing this?

**Comment by debora-ito** [comment]
@valdiblondal the multipart download has received a couple of updates starting from version `1.11.472`. Try the newer versions of the SDK and please reopen if you are still seeing this.

**Comment by rmleme** [comment]
Hi @debora-ito. I've just tested with the exact same source code of @valdiblondal, using the latest version (`1.12.180`), and the issue still remains. Would you like me to open a new issue, or would you prefer to reopen this?
