### ISSUE TITLE
S3 Multipart upload fails on ByteArrayInputStream passed as part content body.

### ISSUE THREAD

**Issue by mentegy** [aws/aws-sdk-java#1360]
I'm trying to run multipart upload and pass `byte[]` as part body by wrapping it with `ByteArrayInputStream`. Simple example:
```java
String bucket = "test-bucket";
String key = "test1";
AmazonS3 s3 = //...
Random rand = new Random();
Function<Integer, byte[]> randomBytes = (size) -> {
    byte[] bb = new byte[size];
    rand.nextBytes(bb);
    return bb;
};

String uploadId = s3
    .initiateMultipartUpload(new InitiateMultipartUploadRequest(bucket, key))
    .getUploadId();
int partSize = 5 * 1024 * 1024;
List<PartETag> list = new ArrayList<>(3);

for (int i = 1; i <= 3; i++) {
    UploadPartRequest req = new UploadPartRequest()
        .withInputStream(new ByteArrayInputStream(randomBytes.apply(partSize)))
        .withBucketName(bucket)
        .withUploadId(uploadId)
        .withKey(key)
        .withPartNumber(i);
    list.add(s3.uploadPart(req).getPartETag());
}

s3.completeMultipartUpload(new CompleteMultipartUploadRequest(bucket, key, uploadId, list));
```

However on the completion I'm getting `AmazonS3Exception: Your proposed upload is smaller than the minimum allowed object size. (Service: Amazon S3; Status Code: 400; Error Code: EntityTooSmall)`.

Here's part of logs:
```
-  http-outgoing-0 >> PUT /test-bucket/test1?uploadId=9cf8c626-6cbc-4973-a2c1-6d65f188fdf3&partNumber=2 HTTP/1.1
-  http-outgoing-0 >> x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
-  http-outgoing-0 >> X-Amz-Date: 20171024T142139Z
-  http-outgoing-0 >> User-Agent: aws-sdk-java/1.11.213 Linux/4.10.0-37-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.144-b01 java/1.8.0_144
-  http-outgoing-0 >> x-amz-decoded-content-length: 0
-  http-outgoing-0 >> amz-sdk-retry: 0/0/500
-  http-outgoing-0 >> Content-Type: application/octet-stream
-  http-outgoing-0 >> Content-Length: 86
-  http-outgoing-0 >> Connection: Keep-Alive
-  http-outgoing-0 >> Expect: 100-continue
-  http-outgoing-0 << HTTP/1.1 200 OK
-  http-outgoing-0 << Accept-Ranges: bytes
-  http-outgoing-0 << Etag: "d41d8cd98f00b204e9800998ecf8427e"
```

As you can see `Content-Length` is 86 but not 5MB.

Is there a way to upload dynamic data from memory instead of writing it to file and passing it to request ?

**Comment by spfink** [comment]
Have you tried using TransferManager?

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html

Takes care of doing multi-part uploads / downloads for you.

**Comment by mentegy** [comment]
@spfink Yes, it does its job perfect, moreover low level api works great with file streams. But the point is using dynamic data generated in RAM as with ByteArrayInputStream, or another custom implementation of InputStream since sdk does not provide support of ByteBuffer.

**Comment by mentegy** [comment]
PartRequest builder was missing `withPartSize` parameter but java primitive was making it 0 hence no actual data was sent
