### ISSUE TITLE
Uploads < MultipartUploadThreshold do not publish events to ProgressListener 

### ISSUE THREAD

**Issue by philipbalinov** [aws/aws-sdk-java#1363]
[Uploads via UploadResult.call()  only conditionally publish events to ProgressListener](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadCallable.java#L125)

Uploads smaller than MultipartUploadThreshold call uploadInOneChunk() and do not trigger the TRANSFER_STARTED_EVENT and also do not trigger the TRANSFER_FAILED_EVENT [as opposed to the uploadInParts() function](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadCallable.java#L193) 

 As a result, non-blocking calls to TransferManager.upload , as illustrated [in the example here](http://docs.aws.amazon.com/AmazonS3/latest/dev/HLuploadFileJava.html), will hang indefinitely unless  the Upload is explicitly polled via Upload.getState() or the thread is blocked via Upload.waitForCompletion() . This contradicts the documentation, where these calls are marked as optional.

**Comment by shorea** [comment]
@philipbalinov this seems like intended (although perhaps confusing) behavior. From what I can glean from looking at the code, TRANSFER_STARTED_EVENT is used when the transfer manager will make multiple calls under the hood, either by doing a multipart upload or uploading multiple files. This seems to be a common pattern we do across the TransferManager, see https://github.com/aws/aws-sdk-java/blob/8ceca7113bafe6fe0bc1e947e82abed172f0593c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CopyCallable.java#L130. There should be other indications that the request completed via other event types. Would those meet your needs?

**Comment by philipbalinov** [comment]
The problem is not when the transfer completes, its when the transfer doesn't complete. 

Currently, UploadResult will or will not emit an event to the ProgressListener depending on the size of MultipartUploadThreshold,  which is unequivocally a bug in the control flow.
Ergo, if you do not have a blocking transfer via polling or Upload.waitForCompletion(), Uploads smaller than MultipartUploadThreshold will hang indefinitely.

**Comment by shorea** [comment]
Do you get no indication that the request completed? CLIENT_REQUEST_FAILED_EVENT for example.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/event/ProgressEventType.java#L117

**Comment by philipbalinov** [comment]
No, 
looking at: [UploadCallable.java#L121](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadCallable.java#L121)

`UploadCallable.uploadInParts()` performs the upload in a `try..catch` block and updates the progress on failure,

whereas `UploadCallable.uploadInOneChunk()` does not handle exceptions, neither does `UploadCallable.call()`

This way the exception gets thrown up all the way to the thread running `TransferManager.doUpload()`
and is eventually swallowed by the framework.

**Comment by bisoldi** [comment]
I got here because looking at the S3 Transfer Manager, I had the same concern.  This might be OBE by now, but the `uploadInOneChunk()` method calls `s3.putObject(origReq);` which then handles all of the ProgressEvents.  In 1.11.336, the AmazonS3Client calls:

`publishProgress(listener, ProgressEventType.TRANSFER_STARTED_EVENT);`

`listener, ProgressEventType.TRANSFER_FAILED_EVENT);`

`publishProgress(listener, ProgressEventType.TRANSFER_COMPLETED_EVENT);`

**Comment by millems** [comment]
Unfortunately (based on customer feedback) we're devoting our development resources toward 2.x of the SDK, and aren't planning to implement many changes in the 1.11.x transfer manager at this time.
