### ISSUE TITLE
BUG: AmazonSQSBufferedAsyncClient with AmazonSQSExtendedClient

### ISSUE THREAD

**Issue by DavidRHoffman** [aws/aws-sdk-java#1364]
Combining the AmazonSQSExtendedClient and the AmazonSQSBufferedAsyncClient using default values exposes a bug where it is impossible to send message with size 262,144 or 262,143 bytes.

The SQS Max Message size is 256 KB (1024 bytes * 256 = 262,144 bytes)

In the package com.amazonaws.services.sqs.buffered.

The class QueueBufferConfig has the default values:

`public static final long SERVICE_MAX_BATCH_SIZE_BYTES = 256 * 1024 - 1;  /* 262,143 bytes */`
`public static final long MAX_BATCH_SIZE_BYTES_DEFAULT = SERVICE_MAX_BATCH_SIZE_BYTES;`

The class SendQueueBuffer$SendMessageBatchTask extends OutboundBatchTask has the method:

`protected boolean isOkToAdd(SendMessageRequest request) {`
`    return (requests.size() < config.getMaxBatchSize())`
`            && ((request.getMessageBody().getBytes().length + batchSizeBytes) < config.getMaxBatchSizeBytes());`
`}`

It gets called from the SendQueueBuffer$OutboundBatchTask method which returns false if isOkToAdd() returns false:

`boolean addIfAllowed(...)`

This is in turn called by the SendQueueBuffer$OutboundBatchTask  method which returns null if addIfAllowed() returns false:

`QueueBufferFuture addRequest(...)`

Which is called from the SendQueueBuffer method:

`<OBT extends OutboundBatchTask<R, Result>, R extends AmazonWebServiceRequest, Result> QueueBufferFuture<R, Result> submitOutboundRequest(...)`

In this method is the following code:

`theFuture = openOutboundBatchTask[0].addRequest(request, callback);`
`if (null == theFuture) {`
`    throw new AmazonClientException("Failed to schedule request " + request + " for execution");`
`}`

Now the AmazonSQSExtendedClient by default with large message support sends messages which are greater than 262,144 bytes to S3 buckets and the actual SQS messages are small in size with pointers to the S3 bucket SQS message objects.  Messages with byte size 1 to 262,142 will work, but messages with byte size exactly 262,143 or 262,144 will always fail with the AmazonClientException when backed by the AmazonSQSBufferedAsyncClient using default settings.

A workaround is to use ExtendedClientConfiguration.withMessageSizeThreshold(262142) with the AmazonSQSExtendedClient, but this doesn't get around the fact that there is a bug in the AmazonSQSBufferedAsyncClient because it should but does not support messages up to 256 KB inclusive (or even exclusive for that matter with messages 1 byte less).

The real fix is to change QueueBufferConfig `SERVICE_MAX_BATCH_SIZE_BYTES` to:

`public static final long SERVICE_MAX_BATCH_SIZE_BYTES = 256 * 1024;`  

And to change isOkToAdd() to: 

` ((request.getMessageBody().getBytes().length + batchSizeBytes) <= config.getMaxBatchSizeBytes())`

**Comment by millems** [comment]
Good bug report! Working on a quick fix for this...

**Comment by millems** [comment]
A fix has been made and will go out over the next few days. Thanks!

**Comment by DavidRHoffman** [comment]
Thanks, I trust this will also be addressed in aws-sdk-java-v2 which shares the bug.

**Comment by millems** [comment]
The buffered client has been temporarily removed from V2 until it can be updated, so in a sense the bug doesn't exist there anymore.
