### ISSUE TITLE
DynamoDB client configuration setConnectionMaxIdleMillis with more than 60s does not work.

### ISSUE THREAD

**Issue by forhappy** [aws/aws-sdk-java#1365]
Hey AWS Team,

I tried to set the DynamoDB client configuration ConnectionMaxIdleMillis with an idle duration for more than 60s, e.g. 2 minutes, 5 minutes, or even 10 minutes, but it appears the DynamoDB service will not respect any longer idle during time for more than 60s.

But when I set the duration to 30s, the DynamoDB connection will be discarded after it idles for 30s.

So my question is, is 60s the maximum idle duration setting for a DynamoDB connection?

**Comment by shorea** [comment]
Max idle is a client side setting and has no bearing on how the service will handle connections. I'm not sure what Dynamo's max idle setting is for their VIPs but 60 seconds sounds reasonable if that's the behavior your seeing. In general though I don't think that's something you can rely on not changing. If you need to keep the connection alive for longer you can try enabling TCP keep alives, not 100% this would work so you'd have to test it out. http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#withTcpKeepAlive-boolean-

**Comment by artpdr** [comment]
Hi guys, I just saw this post after spending an afternoon trying to understand why changing ConnectionMaxIdleMillis to values > 60000 wasn't doing anything. I always see idle connections going to CLOSE_WAIT state after 60 seconds.

I also tried changing TCPKeepAlive config to true and even increasing the socketTimeout config to 120000 but nothing works as it seems that you have timeouts on the server-side (as expected). Do you have any place where you document these timeouts and can you enhance DynamoDB documentation for users to keep in mind the timeouts that are used on server-side? 

Thanks

**Comment by abhayaps** [comment]
Hey Guys, Is there any way to keep up the idle connections for more than 1 minute?
 ConnectionMaxIdleMillis > 60000 and TCPKeepAlive config to true is not working.

**Comment by birbirsbirbirs** [comment]
I saw this issue closed. any update? This issue is till relevant? thank you very much.
