### ISSUE TITLE
GeneratePresignedUrlRequest seems to generate wrong URL

### ISSUE THREAD

**Issue by leolux** [aws/aws-sdk-java#1368]
When using the following code:
```
String bucketName = "test.bucket.eu";
String objectKey="path/to/my/file.pdf";
 GeneratePresignedUrlRequest generatePresignedUrlRequest =
          new GeneratePresignedUrlRequest(bucketName, objectKey);
```
the sdk returns the following URL:
https://test.bucket.eu.s3.eu-central-1.amazonaws.com/path/to/my/file.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=...

This URL leads to the following exception
` java.security.cert.CertificateException: No subject alternative DNS name matching test.bucket.eu.s3.eu-central-1.amazonaws.com found`

I would have expected the generated URL to lool like 
https://s3.eu-central-1.amazonaws.com/test.bucket.eu/path/to/my/file.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=...

**Comment by shorea** [comment]
I'm almost positive we will respect path style if you configure it in your client which would generate the URL you're expecting. http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#enablePathStyleAccess--

Alternatively the computed URL should work if your HTTP client supports wildcard hostname verification.

**Comment by leolux** [comment]
Alright, thanks!
