### ISSUE TITLE
UnknownHostException elasticloadbalancing.us-wes-2.amazonaws.com

### ISSUE THREAD

**Issue by Haribou** [aws/aws-sdk-java#1369]
We set up an EC2 instance in US_WEST_2 (Oregon) an run Java applications on it that use the AWS Java SDK 1.11.146. Some of these applications use AWS Elastic Load Balancing, others use AWS SQS queues. The elastic load balancer and the SQS queues are also located in US_WEST_2. A request from the AWS Java SDK to either the ELB or SQS service results in a java.net.UnknownHostException. In the case of an ELB request, we see the following stack trace (note the "us-wes-2" substring in the DNS name instead of "us-west-2"):
java.net.UnknownHostException: elasticloadbalancing.us-wes-2.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)

Here is how we set up the AWS ELB client in our Java application:
AmazonElasticLoadBalancingClient elbClient = (AmazonElasticLoadBalancingClient) AmazonElasticLoadBalancingClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("<our accessKey>", "<our accessKeySecret>"))).withRegion("US_WEST_2").build();

DescribeLoadBalancersResult loadBalancersDescription = elbClient.describeLoadBalancers(); // Throws java.netUnknownHostException 

We run the same code in a different EC2 instance in US_WEST_2 without any problems!

Any idea why the DNS name for the ELB service is misspelled?

Thanks!

**Comment by shorea** [comment]
Can you try the following? If you pass in a string you must pass in the region name as `us-west-2`. Using the enum is preferred though if you are using a known fixed region.

```java 
AmazonElasticLoadBalancingClient elbClient = (AmazonElasticLoadBalancingClient) AmazonElasticLoadBalancingClientBuilder.standard()
        .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("", "")))
        .withRegion(Regions.US_WEST_2)
        .build();
```

**Comment by Haribou** [comment]
Hi and thank you for your response. I tried your suggestion and it worked. Do you know why a Region name string such as US_WEST_2 works on most instances but not on some others?

Thanks again.

**Comment by shorea** [comment]
Hmm I am surprised it works anywhere. Unless perhaps for some clients you don't set a region explicitly and it gets the region from the provider chain as described in http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html
