### ISSUE TITLE
Unable to upload multipart to SnowballEdge with Java SDK

### ISSUE THREAD

**Issue by nkunkee** [aws/aws-sdk-java#1372]
Using the TransferManager gives this error almost immediately:
```
[run-main-0] INFO TransferManager$ - Uploading to XXXXXXXX/testing2/YYYYYYYY.tar.gz
[run-main-0] ERROR TransferManager$ - Upload failed because Unable to execute HTTP request: The target server failed to respond
```
The file YYYYYYY.tar.gz is 115MB in size, which is over the threshold set when constructing the TransferManager.
Using the simpler PutObject request and an input YYYYYYYY.tar.gz of 6GB:
```
[run-main-0] INFO PushObject$ - Uploading to XXXXXXXX/testing/YYYYYYYY.tar.gz
[run-main-0] ERROR PushObject$ - Upload failed because Unable to execute HTTP request: Connection reset
```
at the end of uploading.
I can upload to AWS or a Minio instance just fine with the same code. The Python AWS CLI client uploads to the SnowballEdge just fine (and has been my work around).

I've attached my code, being the simplest case I have.

**Comment by nkunkee** [comment]
[snowball-test.tar.gz](https://github.com/aws/aws-sdk-java/files/1447837/snowball-test.tar.gz)

**Comment by nkunkee** [comment]
The SnowballEdge devices have been returned, so I'm no longer able to test this.

**Comment by varunnvs92** [comment]
Found the following issues for error "The target server failed to respond"
https://github.com/aws/aws-sdk-java/issues/1328 [Issue with signing]
https://github.com/aws/aws-sdk-java/issues/1212 [Buggy http client]

Can you check you don't have the problems mentioned in the above issue?
As you don't have logs, it is difficult for us to debug the issue?
Is this seen only when uploading to SnowballEdge devices or Is this reproducible when uploading files to S3?

**Comment by nkunkee** [comment]
#1328 talks about a different signing algorithm and a longer timeout. Since there was no perceptible delay (meaning less than half a minute wall clock), I didn't try a longer timeout. There was nothing I could see in the Snowball docs saying to use a different signing algorithm. The python CLI worked fine--does it use V4 signatures?
#1212 talked about conflicting dependencies. If Apache HttpClient is included in my app, then it is because of the AWS SDK; my only other dependencies do not include it.

I'm sorry, I didn't manage to get a wire log.

This was only seen uploading to the SnowballEdge. The same code works as expected to Minio and AWS otherwise.

**Comment by varunnvs92** [comment]
Its tricky to debug as this issue is seen only when uploading to SnowballEdge. We don't have access to SnowballEdge for testing and you currently don't have any logs. I don't see a way to proceed further. You mentioned that your SnowballEdge devices have been returned, Do you expect to get access to SnowballEdge devices soon for logs? If not, then this is not a blocker for you. In that case, I would suggest resolving the issue and re-open it when you can reproduce the issue again.

**Comment by nkunkee** [comment]
I'll agree and close the issue. It's logged, so it may still help if someone else finds the same issue.
