### ISSUE TITLE
 randomSeed dataRearrangement documentation contains invalid json

### ISSUE THREAD

**Issue by malduarte** [aws/aws-sdk-java#1378]
Instead of 
`"randomSeed"="s3://my_s3_path/bucket/file.csv"`

It should be 
 `"strategyParams": {"randomSeed":"s3://my_s3_path/bucket/file.csv"}`

**Comment by malduarte** [comment]
Submited https://github.com/aws/aws-sdk-java/pull/1377 with a fix

**Comment by millems** [comment]
These are auto-generated from models internally, so we can't accept this pull request without it being overridden later on, but I'll forward this onto the service team to have their doc guys fix. Thanks!

**Comment by malduarte** [comment]
@millems Thanks!

**Comment by millems** [comment]
The service team has acknowledged that they're aware of the issue and are working on updating it at the source.

**Comment by millems** [comment]
To provide an update, the service team is still working to fix this issue on our end.

**Comment by millems** [comment]
To provide an update, the service team is still working to fix this issue on our end.

**Comment by debora-ito** [comment]
@malduarte It looks like the service team won't update the docs after all, the docs are still unaltered. I'll go ahead and close this as there's nothing pending from the Java SDK team.
