### ISSUE TITLE
AWS China region

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#1382]
Hi,

We are currently using aws services like EC2, RDS, S3, SNS, DynamoDB in almost all the supported regions. And we are collecting metrics through CLOUDWATCH by using aws-java-sdk-1.11.171.jar.

We have initiated the process to create a new account in China Beijing region. 

Our doubt is whether we need separate aws java sdk to monitor and collect metrics from china region via cloudwatch Or we can use the same java-sdk that we are using it currently to collect metrics in all other 14 regions ?

How to collect metrics via cloudwatch from china beijing region? 

Thanks,
Gowtham

**Comment by varunnvs92** [comment]
You can use the same SDK for China Beijing region. When you create the clients, you need to set the valid china region on the client.

>How to collect metrics via cloudwatch from china beijing region?

The process should be same as with other regions. 
https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/AwsSdkMetrics.html

**Comment by gowthamsankar312** [comment]
Thank you for your information.
