### ISSUE TITLE
Datetime ISO8601 not respected by doParseISO8601Date

### ISSUE THREAD

**Issue by glynd** [aws/aws-sdk-java#1383]
The current com.amazonaws.util.DateUtils method 'doParseISO8601Date' does not correctly parse ISO 8601 date-time strings without a millisecond field but with a timezone offset

Fails with: 2017-11-13T15:09:59+03:00
Succeeds with: 2017-11-13T15:09:59.0+03:00

It will only cope with date-time strings that have a 'Z' timezone designation without milliseconds 

It has a special case for some spot instance servers?  Where '+0000' is mapped directly to a 'Z' timezone designator

**Comment by varunnvs92** [comment]
I am able to reproduce the issue. I need to confirm with the team if this is a known issue and the right path forward. We are currently overwhelmed due to [AWS ReInvent](https://reinvent.awsevents.com/). I will get back to you when I have more updates. Thank you.
