### ISSUE TITLE
Add authorizer to APIGatewayProxyRequestEvent.ProxyRequestContext

### ISSUE THREAD

**Issue by tomwetjens** [aws/aws-sdk-java#1387]
When using the provided APIGatewayProxyRequestEvent as the input type for a RequestHandler, it is currently not possible using the provided Java POJOs to access "$context.authorizer.principalId" when using a custom authorizer.

By temporarily changing the RequestHandler input type to Map, I was able to access it, but of course I'd rather use standard Java POJOs to access it in a safe way.

Please add "authorizer" property with structure according to http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference to ProxyRequestContext.

**Comment by varunnvs92** [comment]
I don't see ProxyRequestContext class in Java SDK. Can you give me more details?

**Comment by tomwetjens** [comment]
To clarify: it would need to be added to the com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent.ProxyRequestContext class.

**Comment by varunnvs92** [comment]
This class is part of Lambda Runtime which is not owned by SDK team. This is owned by service team (AWS Lambda). Please reach out directly to Lambda team through AWS Forums or customer support. Thank you.
