### ISSUE TITLE
[AWSLogsClient] Unable to parse HTTP response content

### ISSUE THREAD

**Issue by mixcloud-downloader** [aws/aws-sdk-java#1389]
I see this here once every few days:

    Nov 16 12:20:31 us downloader.jar[40770]: 2017-11-16 12:20:31.970  INFO 40790 --- [GS Async Worker] com.amazonaws.protocol.json.JsonContent  : Unable to parse HTTP response content
    Nov 16 12:20:31 us downloader.jar[40770]: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
    Nov 16 12:20:31 us downloader.jar[40770]:  at [Source: [B@6d0ccbf0; line: 1, column: 0]
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3854)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2420)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1511)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:1685)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:1661)
    Nov 16 12:20:31 us downloader.jar[40770]: #011at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:1402)

Today I saw it many time from many different servers within the same period of time, 30 times within 2 hours. Unfortunately that's all I have. So there's probably a non JSON answer coming from AWS. Maybe as a first step, it might help to include more hints of the response in that error message (e.g. status code and body).

**Comment by varunnvs92** [comment]
My guess is same as yours (non JSON answer coming from AWS or part of content is dropped to network issues). Can you enable wire logging and capture the request ids for the failed requests? Service team needs request ids to look up their logs.

**Comment by varunnvs92** [comment]
Do you have a test case that can consistently reproduce the issue?
Do you mind sharing your code where the client is configured? (Do Not put any sensitive data)

**Comment by mixcloud-downloader** [comment]
> Do you have a test case that can consistently reproduce the issue?

Unfortunately no, I don't. I just see it consistently once every few days in production.

> Do you mind sharing your code where the client is configured?

I'm using it over a [third party library](https://github.com/pierredavidbelanger/logback-awslogs-appender/blob/1.0.0/src/main/java/ca/pjer/logback/AWSLogsStub.java#L32-L36). I don't configure any region.

>  Can you enable wire logging and capture the request ids for the failed requests?

I will and come back with the results. This will take a few days.

**Comment by dagnir** [comment]
@mixcloud-downloader Were you able to capture any failed request ID's?

**Comment by mixcloud-downloader** [comment]
Unfortunately not yet.

**Comment by mixcloud-downloader** [comment]
Ok, now I got more context:

    Dez 05 23:52:03 vn downloader.jar[667]: 2017-12-06 06:52:03.295 DEBUG 688 --- [GS Async Worker] com.amazonaws.request                    : Sending Request: POST https://logs.us-east-1.amazonaws.com / Headers: (Accept: application/json, User-Agent: aws-sdk-java/1.11.55 Linux/4.4.0-101-generic OpenJDK_64-Bit_Server_VM/25.151-b12/1.8.0_151, amz-sdk-invocation-id:
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.185 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "POST / HTTP/1.1[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.187 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "Host: logs.us-east-1.amazonaws.com[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.187 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "Authorization: AWS4-HMAC-SHA256 Credential=***, SignedHeaders=accept;amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-age
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "X-Amz-Date: 20171205T235203Z[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "Accept: application/json[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "User-Agent: aws-sdk-java/1.11.55 Linux/4.4.0-101-generic OpenJDK_64-Bit_Server_VM/25.151-b12/1.8.0_151[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "amz-sdk-invocation-id: 9b6c9c23-eb8a-2ca4-2bff-6472a8e0df46[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "amz-sdk-retry: 0/0/500[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "X-Amz-Target: Logs_20140328.PutLogEvents[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.188 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "Content-Type: application/x-amz-json-1.1[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.189 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "Content-Length: 18847[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.189 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "Connection: Keep-Alive[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.189 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "[\r][\n]"
    Dez 05 23:52:05 vn downloader.jar[667]: 2017-12-06 06:52:05.189 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 >> "{"logGroupName":"downloader","logStreamName":"20171205T044413-vn","logEvents":***
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.045 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.046 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "Transfer-Encoding: chunked[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.046 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "Date: Tue, 05 Dec 2017 23:52:10 GMT[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.047 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "Connection: close[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.047 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.049 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "0[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.050 DEBUG 688 --- [GS Async Worker] org.apache.http.wire                     : http-outgoing-3922 << "[\r][\n]"
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.058  INFO 688 --- [GS Async Worker] com.amazonaws.protocol.json.JsonContent  : Unable to parse HTTP response content
    Dez 05 23:52:11 vn downloader.jar[667]: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
    Dez 05 23:52:11 vn downloader.jar[667]:  at [Source: [B@914e637; line: 1, column: 0]
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3854)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2420)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1511)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:1685)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:1661)
    Dez 05 23:52:11 vn downloader.jar[667]:         at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:1402)
    Dez 05 23:52:11 vn downloader.jar[667]:         at ca.pjer.logback.AWSLogsStub.logPreparedEvents(AWSLogsStub.java:83)
    Dez 05 23:52:11 vn downloader.jar[667]:         at ca.pjer.logback.AWSLogsStub.logEvents(AWSLogsStub.java:73)
    Dez 05 23:52:11 vn downloader.jar[667]:         at ca.pjer.logback.AsyncWorker.flush(AsyncWorker.java:142)
    Dez 05 23:52:11 vn downloader.jar[667]:         at ca.pjer.logback.AsyncWorker.run(AsyncWorker.java:119)
    Dez 05 23:52:11 vn downloader.jar[667]:         at java.lang.Thread.run(Thread.java:748)
    Dez 05 23:52:11 vn downloader.jar[667]: 2017-12-06 06:52:11.087 DEBUG 688 --- [GS Async Worker] com.amazonaws.request                    : Received error response: com.amazonaws.services.logs.model.AWSLogsException: null (Service: AWSLogs; Status Code: 500; Error Code: null; Request ID: null)

So it's a server error (HTTP 500) from Cloudwatch Logs. After that there's a successful retry. I think the error message in my log is just confusing. It would be nice if that message would tell me just that there was a 500 from Cloudwatch and that I don't have to worry as this request will be retried. "Unable to parse HTTP response content" causes confusion.

**Comment by dagnir** [comment]
I see, thanks for providing the extra information. We'll look into making the log message more informative.

**Comment by shorea** [comment]
We've made this a DEBUG level log statement, it will be available in our next release.
