### ISSUE TITLE
Add a verify credentials method to AmazonWebServiceClient

### ISSUE THREAD

**Issue by oscerd** [aws/aws-sdk-java#1390]
It would be useful to have a method to verify the credentials provided to the client before doing any operations.

**Comment by kiiadi** [comment]
@oscerd can you explain a bit more about the use-case and the expected behaviour?

**Comment by oscerd** [comment]
Hello @kiiadi, thanks for the answer first.

In Apache Camel we are using the AWS SDK client in our camel-aws component https://github.com/apache/camel/tree/master/components/camel-aws

We are working on some new features about Components' Verify, we look at the configuration our component and trying to do a connectivity test first, like here https://github.com/apache/camel/blob/master/components/camel-aws/src/test/java/org/apache/camel/component/aws/s3/S3ComponentVerifierExtensionTest.java

We check for SdkClientException to verify if something is wrong or if it's ok. To raise an exception we need to do some kind of operation in our code, for example we do a listBucket for the S3 component.

IMO, it would be helpful to have a method in AmazonWebServiceClient to verify the credentials ahead of time, to check if everything is fine in terms of connectivity. Otherwise, we will use different operations for each different client we will use.

**Comment by oscerd** [comment]
Any feedback on this?

**Comment by shorea** [comment]
This isn't really something we can add. I suggest making just a service call that you should have permissions to and assert that the call succeeds.

**Comment by oscerd** [comment]
This is what we are already doing. I believe make a service call just to check if I have permission is a bit overkilling. Also the service call may be expensive. By the way thanks for your attention and for considering this. Cheers.
