### ISSUE TITLE
ObjectTagging suggestion

### ISSUE THREAD

**Issue by rmundkowsky** [aws/aws-sdk-java#1391]
ObjectTagging should use Java Set rather than List. This would reduce problems with duplicate tags.

**Comment by varunnvs92** [comment]
Is this for S3 client? Can you provide the link for the operation?

**Comment by rmundkowsky** [comment]
OK:

org.ets.speechrater.aws.s3.S3.putObject(String, String, List<Tag>, InputStream, String, long, int, boolean, boolean, boolean)

Better:

org.ets.speechrater.aws.s3.S3.putObject(String, String, Set<Tag>, InputStream, String, long, int, boolean, boolean, boolean)

**Comment by varunnvs92** [comment]
Got it. I agree it would have been better experience to represent it as Set instead of List. We can't change it now due to backwards compatibility reason. We will consider this for [v2 SDK](https://github.com/aws/aws-sdk-java-v2).
