### ISSUE TITLE
ObjectTaggingProvider can not be implemented

### ISSUE THREAD

**Issue by nec-mas** [aws/aws-sdk-java#1393]
When i tried to implement the ObjectTaggingProvider this way,
        ObjectTaggingProvider tagProvider = new ObjectTaggingProvider() {
            
            @Override
            public ObjectTagging provideObjectTags(UploadContext uploadContext) {
                // TODO Auto-generated method stub
                return null;
            }
        };
a compile error occurs because of the UploadContext class is invisible.
I am wondering that it's a bug?

**Comment by shorea** [comment]
Yes this is a bug, we meant to make the constructor package private but the class public. I'll fix.

**Comment by shorea** [comment]
We have fixed this and it will be available in the next release 1.11.235.

**Comment by shorea** [comment]
This is now available.
