### ISSUE TITLE
Cognito birthdate field requires 10 characters?

### ISSUE THREAD

**Issue by djar** [aws/aws-sdk-java#1396]
I get this error when setting a birth date. However I'm not sure what the 10 characters should represent. Should the error message be updated to give more detail on what is incorrect?

"Invalid user attributes: birthdate: String must be no shorter than 10 characters"

**Comment by varunnvs92** [comment]
http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html
http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
Copied from above link - "End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format." 
The above format is 10 characters. I guess you are not following it. Please try with the above format.

Note: This is a service specific question. We manage the Java SDK library but we might not know about APIs in all services. For service how-to-use questions, you would be able to get better support through popular sites like stackoverflow or AWS forums.
