### ISSUE TITLE
security issue reporting?

### ISSUE THREAD

**Issue by jtnord** [aws/aws-sdk-java#1397]
I did not see in the readme where to report potential security issues.  Can you please let me know?

**Comment by spfink** [comment]
@jtnord Please email us at github-awsforjava@amazon.com

**Comment by spfink** [comment]
@jtnord did you get a chance to send us an email?

**Comment by jtnord** [comment]
@spfink not yet

**Comment by varunnvs92** [comment]
@jtnord 
Did you report the issue to the above email? If there is a valid security issue, we would like to know about it as soon as possible. Thank you.

**Comment by jtnord** [comment]
sent.
