### ISSUE TITLE
STS: Add account alias to GetCallIdentity response

### ISSUE THREAD

**Issue by testphreak** [aws/aws-sdk-java#1399]
`
AWS Java SDK: 1.11.210
`

Currently when I make a call to to STS `GetCallerIdentity`, I don't see the account alias if one is set on the account in the response. To get that information, I have to make a separate call to IAM `ListAccountAliases`. This results in one additional call which I think should be avoided if possible.

Also, I am a little unclear why is it a list of account aliases. From my understanding there can only be a single account alias. In the [user guide](http://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html) it says, 
```
Your AWS account can have only one alias. If you create a new alias for your AWS account, the new alias overwrites the old alias, and the URL containing the old alias stops working.
```

**Comment by varunnvs92** [comment]
Our team owns the Java SDK. We auto-generate the service clients from the models that service team provides us. This feature request seems more appropriate for the service team (STS) rather than us. Please reach out to them directly either through console or AWS forums.
