### ISSUE TITLE
Add async client for S3

### ISSUE THREAD

**Issue by karol-gwaj** [aws/aws-sdk-java#140]
Will be useful to have async client for S3 (similar like for other services).

**Comment by xdlai** [comment]
Will other operations (e.g.: AmazonS3Client.getObject) have async version in the future?

**Comment by manikandanrs** [comment]
@xdlai Did you get a chance to look at TransferManager ?

**Comment by xdlai** [comment]
Yes,I tried it. It can allow me to download s3 object to the local file asynchronously. My question is if I want to get metadata of an object only(without downloading it's content) asynchronously, how do I do that?

**Comment by rocketraman** [comment]
> so there's definitely still a need for an Async client like the other clients in the SDK

Yes, created issue #725 to track this. Thanks!

**Comment by shorea** [comment]
We just launched a Developer Preview of AWS SDK for Java 2.0 that adds support for this feature request. Try it out and let us know what you think!

https://github.com/aws/aws-sdk-java-v2
http://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html
https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/
