### ISSUE TITLE
Unable to upload file to S3

### ISSUE THREAD

**Issue by kusharora02** [aws/aws-sdk-java#1404]
Hi,

I am trying to upload the list of files to s3 using TransferManager by following code:

MultipleFileUpload upload = transferMgr.uploadFileList(s3Bucket, "", baseDir, Lists.newArrayList(dataFiles),
            metadataProvider);

once the code runs it does not give any error and I am not able to see any file uploaded to s3.

if I see in upload variable I am able to see Transfer State as failed. does any one has idea when transfer state can be failed?

**Comment by dagnir** [comment]
Hi @kusharora02 can you share a bit more about about how you're calling `uploadFileList`? Are you calling `waitForCompletion`? Is it throwing an exception?

**Comment by kusharora02** [comment]
No I am not seeing any exception, but I am checking as 
 while (!upload.isDone()) {
        }
and then the further code.

and this how I am creating metadataProvider

 ObjectMetadataProvider metadataProvider = new ObjectMetadataProvider() {

          @Override
          public void provideObjectMetadata(File file, ObjectMetadata metadata) {

            metadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
            metadata.setContentLength(file.length());
          }

        };

**Comment by dagnir** [comment]
Okay I see. `isDone` will return `true` once the operation is finished running, regardless of whether if succeeded or failed.

You can either switching to calling [`upload.waitForCompletion()`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/Transfer.html#waitForCompletion--) which will throw an `AmazonS3Exception` if the operation failed, or attach a progress listener to upload using [`upload.addProgressListener`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/Transfer.html#addProgressListener-com.amazonaws.event.ProgressListener-)

**Comment by kusharora02** [comment]
okay Thanks.. I am able to see following error

com.amazonaws.AmazonClientException: Unable to complete transfer: Thread failed to begin a subsegment: segment not found. Verify that a segment is in progress, and that the SegmentContextResolverChain is configured correctly in order to discover the segment.

will look in to and ask if I have some issue

**Comment by shorea** [comment]
@kusharora02 this looks like an issue with Xray. If you disable Xray does the error go away?

If it does turn out to be an X-ray specific issue you can open an issue here, https://github.com/aws/aws-xray-sdk-java

**Comment by dagnir** [comment]
Closing due to no response. As @shorea observed this looks like an X-Ray issue so it might be more helpful to report the issue to them.
