### ISSUE TITLE
Possible OSGi related issue with jackson in 1.11.240

### ISSUE THREAD

**Issue by clintoncampbell** [aws/aws-sdk-java#1407]
Yesterday, we began to experience a build failure in our development environment that was quickly linked to the 1.11.240 version of the SDK. After a fair amount of diagnosis, I believe that the issue is related to dependency bundling and OSGi. 

The issue is presenting itself in a Lucee 5.2 based application running on top of Tomcat 8.0.47. Building the same container with aws-java-sdk-1.11.233.jar works well, though we begin to see ClientConfiguration instantiation issues linked with Jackson as soon as we update the jar to 1.11.240. Lucee Server provides a decent picture of what is happening in terms of OSGi, and in both cases I can see that the proper dependencies are being loaded. 

<img width="862" alt="screen shot 2017-12-01 at 2 46 16 pm" src="https://user-images.githubusercontent.com/7392492/33507036-542f8cba-d6a7-11e7-86a2-55086dadbf27.png">

The following image depicts a portion of the stack trace indicating an issue with loading the correct classes from jackson.

<img width="734" alt="screen shot 2017-12-01 at 2 50 01 pm" src="https://user-images.githubusercontent.com/7392492/33507032-4e1a54cc-d6a7-11e7-9ffc-bf64d8f23989.png">

Note that I ran both scenarios (1.11.233 and 1.11.240) with the jars packaged with the 1.11.240 sdk, so I do not believe the issue is with the dependencies themselves, but how 1.11.240 consumes them.

**Comment by varunnvs92** [comment]
There were no changes specific to Jackson or OSGi in that version. I am not sure whats going on. Can you try latest version (1.11.243) and see if you can reproduce the issue?

**Comment by shorea** [comment]
Have you been able to reproduce the issue with the latest version of the SDK?

**Comment by clintoncampbell** [comment]
Haven't had a chance to try yet, but I think I can make it happen today.
Sorry about that.

**Comment by clintoncampbell** [comment]
Apologies for the delay. Yes, we are still encountering the errors on the latest version.

**Comment by clintoncampbell** [comment]
Seems to be a dependency conflict with another part of the framework. Issue resolved using the new bundled version of the jar.
