### ISSUE TITLE
US-East-1 Missing from S3 Regions (was hard to find reference that US_Standard should be used)

### ISSUE THREAD

**Issue by timcharper** [aws/aws-sdk-java#1411]
http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html indicates that S3 does run in us-east-1, but you won't find an enum value here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/Region.java#L69

This page indicates that us-east-1 is US_Standard: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Might be nice to mention this in the docs somehow.

**Comment by shorea** [comment]
We have updated the documentation to be more clear that US Standard is synonymous with us-east-1. This will be included in our next release.
