### ISSUE TITLE
Unable to add T2 Unlimited when launching T2s using AutoScalingGroup

### ISSUE THREAD

**Issue by bjornbak** [aws/aws-sdk-java#1413]
According to http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html#t2-auto-scaling-grp I need to add a LaunchTemplateSpecification to AutoScalingGroup to add T2 Unlimited.

I use a LaunchConfiguration and not LaunchTemplate as the later is linked to only one subnet and I need the autoscalinggroup to create new instances in several AZs.

Please add the CreditSpecification feature to LaunchConfigurations too some thing like:

        CreateLaunchConfigurationRequest vCreateLaunchConfigurationRequest =
                new CreateLaunchConfigurationRequest()
                        .withLaunchConfigurationName(pClusterName + LAUNCH_CONFIGURATION_POSTFIX)
                        .withInstanceType(pInstanceType)
                        .withImageId(pImageId)
                        .withUserData(UserDataUtil.readUserData(pLog, pUserData, pClusterName))
                        .withKeyName("myKey")
                        .withIamInstanceProfile(pInstanceProfileArn)
            -->       .withCreditSpecification(CpuCredits.Unlimited)   <--
                        .withSecurityGroups(pSecurityGroup);

        AMAZON_AUTO_SCALING.createLaunchConfiguration(
                vCreateLaunchConfigurationRequest
        );

        AMAZON_AUTO_SCALING.createAutoScalingGroup(
                new CreateAutoScalingGroupRequest()
                        .withLaunchConfigurationName(pClusterName + LAUNCH_CONFIGURATION_POSTFIX)
                        .withAutoScalingGroupName(pClusterName + AUTO_SCALING_POSTFIX)
                        .withMinSize(pMinSize)
                        .withMaxSize(pMaxSize)
                        .withVPCZoneIdentifier(pVpcZoneIdentifier)
                        .withLaunchTemplate(vLaunchTemplateSpecification)
                        .withTags(
                                new Tag()
                                        .withResourceType("auto-scaling-group")
                                        .withResourceId(pClusterName + AUTO_SCALING_POSTFIX)
                                        .withKey("Name")
                                        .withValue(pClusterName))
                        .withDefaultCooldown(90)
                        .withTerminationPolicies("OldestInstance","OldestLaunchConfiguration","ClosestToNextInstanceHour")
        );

**Comment by bjornbak** [comment]
Rereading the aws-cli documentation I realize that I should either use a LaunchConfiguration or a LaunchTemplate not both.

But dropping the LaunchConfiguration from my example there is still no way to add LaunchTemplateData to the LaunchTemplateSpecification.

**Comment by bjornbak** [comment]
Usage error.

I should have used new CreateLaunchTemplateRequest() instead of new LaunchTemplateSpecification()

**Comment by varunnvs92** [comment]
This seems like a request to the EC2 team. We generate the Java SDK based on the models provided by service team. The feature you are asking should be added on the service end. Please directly reach out to service team either through [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) or console support.
