### ISSUE TITLE
AWS Credentials could not be loaded when using AWS lambda using ProfileCredentialProvider

### ISSUE THREAD

**Issue by vamsiampolu** [aws/aws-sdk-java#1416]
AWS lambda function does not work when attempting to work with credentials provided using the DefaultCredentialProvider.

I need to pass the credentials to S3 for it to run.

**Code**

    def initializeAwsCredentials():AWSCredentials = {
        var credentials: AWSCredentials  = null
        try {
          credentials = new ProfileCredentialsProvider().getCredentials
        } catch {
          case e: Exception => {
            throw new AmazonClientException(
              "Cannot load the credentials from the credential profiles file. " +
                "Please make sure that your credentials file is at the correct " +
                "location (~/.aws/credentials), and is in valid format.",
              e);
          }
    
        }
        return credentials
      }

     def buildS3API(credentials: AWSCredentials): AmazonS3 = {
      new AmazonS3Client(credentials)
    }

    // inside handle request
    val credentials = initializeAwsCredentials()
    println("Credetials have been retrieved successfully")

    println("Build S3 API using the constructor provided")
    val s3 = buildS3API(credentials)
    s3.setRegion(region)
    println("S3 API is now available")

**Error**

    {
      "errorMessage": "Cannot load the credentials from the credential profiles file. Please make sure that your credentials file is at the correct location (~/.aws/credentials), and is in valid format.",
      "errorType": "com.amazonaws.AmazonClientException",
      "stackTrace": [
        "example.Main$.initializeAwsCredentials(Hello.scala:52)",
        "example.Main$.handleRequest(Hello.scala:125)",
        "example.Main.handleRequest(Hello.scala)",
        "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
        "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "java.lang.reflect.Method.invoke(Method.java:498)"
      ],
      "cause": {
        "errorMessage": "java.lang.NullPointerException",
        "errorType": "java.lang.NullPointerException",
        "stackTrace": [
          "com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:143)",
          "com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:132)",
          "com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:99)",
          "com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:135)",
          "example.Main$.initializeAwsCredentials(Hello.scala:45)",
          "example.Main$.handleRequest(Hello.scala:125)",
          "example.Main.handleRequest(Hello.scala)",
          "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
          "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
          "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
          "java.lang.reflect.Method.invoke(Method.java:498)"
        ]
      }
    }

Stackoverflow Question: https://stackoverflow.com/questions/47763573/aws-credentials-for-lambda-when-working-with-scala-not-working

**Comment by shorea** [comment]
Profile files aren't relevant for Lambda. If you create a client without credentials or region set it will automatically pick it up from the environment.

AmazonS3Client.builder().build() will create a default client which should just work in Lambda.

**Comment by vishalsatam** [comment]
How can we assume a role in another account to access the other account's resources using Lambda? What AWSCredentialsProvider can be passed to the STSClient?

**Comment by ashish023** [comment]
> How can we assume a role in another account to access the other account's resources using Lambda? What AWSCredentialsProvider can be passed to the STSClient?

I think you don't need to pass AWSCredentialsProvider to the sts client while working in lambda.
Which means you can directly create STSClient: AWSSecurityTokenServiceClientBuilder.standard().build()
and then pass this client to STSAssumeRoleSessionCredentialsProvider() to assume role to other account's resources:

new STSAssumeRoleSessionCredentialsProvider.Builder("roleArn", "roleSessionName")
                .withStsClient(<Pass in the client created above>)
                .withRoleSessionDurationSeconds(DURATION_IN_SECONDS)
                .build();
