### ISSUE TITLE
New regions China (Ningxia) / cn-northwest-1 and EU (Paris) / eu-west-3 not yet fully reflected in SDK

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#1417]
While `cn-northwest-1` and `eu-west-3` seem already properly reflected for individual services like [CloudFormation](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1693), the partition's `regions` lists still lack resp. entries . This affects UX in terms of automatic display name resolution (easily worked around of course).

Thanks!

### Workaround

By chance of requiring a solution right away, we have successfully used the [PartitionsLoader](https://github.com/aws/aws-sdk-java/blob/39ebf439b8e4050684cbfca1811c84b3ac5f2468/aws-java-sdk-core/src/main/java/com/amazonaws/partitions/PartitionsLoader.java#L45) capability to load an override `com/amazonaws/partitions/override/endpoints.json` from the class path , very helpful feature!

**Comment by shorea** [comment]
Thanks for reporting, we are investigating an issue with our source of region metadata.

**Comment by sopel** [comment]
Thanks for the confirmation @shorea - this obviously also affects for `eu-west-3` now, I've updated the issue accordingly.

**Comment by dagnir** [comment]
Looks like this was resolved in [1.11.252](https://github.com/aws/aws-sdk-java/blob/4cd41a6ca7e0e6cf0670cd125741fd958d06084c/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1716). Closing this issue.
