### ISSUE TITLE
premature end of file

### ISSUE THREAD

**Issue by Kumar-Patil** [aws/aws-sdk-java#1418]
Hi ,

All of sudden i am getting below error from aws sdk. please help me to handle this error.

com.amazonaws.http.DefaultErrorResponseHandler: Unable to parse HTTP response (Invocation Id:31fe4b5d-02b3-b44e-f8e6-031b2c75ba85) content to XML document ''
! org.xml.sax.SAXParseException: Premature end of file.
! at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
! at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
! at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
! at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
! at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
! at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
! at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
! at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
! at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
! at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
! at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
! at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
! at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
! at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
! at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:162)
! at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:169)
! at com.amazonaws.http.DefaultErrorResponseHandler.parseXml(DefaultErrorResponseHandler.java:124)
! at com.amazonaws.http.DefaultErrorResponseHandler.documentFromContent(DefaultErrorResponseHandler.java:105)
! at com.amazonaws.http.DefaultErrorResponseHandler.createAse(DefaultErrorResponseHandler.java:84)
! at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:71)
! at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:47)
! at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
! at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
! at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1561)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1249)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
! at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:969)
! at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:945)
! at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.getMetricStatistics(AmazonCloudWatchClient.java:634)
! at

**Comment by shorea** [comment]
Did you recently upgrade the SDK? What version are you using? Can you provide wire logs of a sample request/response that has this issue?

**Comment by Kumar-Patil** [comment]
Hi thanks for replaying.

I am using this  aws java sdk V1.11.87.
I am requesting like this to get statistiucs.
 GetMetricStatisticsRequest request = new GetMetricStatisticsRequest()
                    .withNamespace(m.getService())
                    .withMetricName(m.getMetricName())
                    .withDimensions(d)
                    .withPeriod(AWS_STATISTICS_PERIOD)
                    .withStartTime(startTime.toDate())
                    .withEndTime(currentDate.toDate())
                    .withStatistics(DatapointUtils.aggregateToStatistic(definition.getAggregate()));

Here i am getting the response  GetMetricStatisticsResult result = cloudWatchClient.getMetricStatistics(page);

it will through suddenly above error.

Please suggest why it is comming ?

**Comment by dagnir** [comment]
@Kumar-Patil were you always on version `1.11.87` or did you upgrade from an earlier version? Also please provide wire logs so we can see if what the service is responding with: http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose

**Comment by Kumar-Patil** [comment]
Most of the services(EC2 , lambada etc ) i am getting above error and it is not constant

**Comment by dagnir** [comment]
@Kumar-Patil were you able to capture any wire logs per @shorea's comment? If you're only see these intermittently it could be connection issues to the service resulting in incomplete responses being received from the client.

**Comment by dagnir** [comment]
Closing due to no response. Please feel free to reopen if you're continuing to see this error.
