### ISSUE TITLE
Amazon ECS: Support for regions ap-south-1, sa-east-1, and eu-west-3 not reflected in SDK

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#1419]
Similar to #1205 (and possibly related to #1417): The recently added availability of [Amazon ECS and Amazon ECR in São Paulo (sa-east-1) and Mumbai (ap-south-1)](https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ecs-and-amazon-ecr-now-available-in-sao-paulo-and-mumbai-regions/) is not **fully** reflected in the SDK's [`endpoints.json`](https://github.com/aws/aws-sdk-java/blob/1.11.251/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1350) yet, and the same issue also applies to ECS in the new [EU (Paris) Region (eu-west-3)](https://aws.amazon.com/about-aws/whats-new/2017/12/announcing-the-aws-eu-paris-region/).

Please not the following **peculiarities**:
* This only affects [ECS](https://github.com/aws/aws-sdk-java/blob/1.11.251/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L634), while [ECR](https://github.com/aws/aws-sdk-java/blob/1.11.251/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L615) is properly reflected already.
* This may simply be related to https://github.com/aws/aws-sdk-java/issues/1417#issuecomment-352112942, but given that one is about the partition region list and other regional service updates seem to be reflected properly, I'd rather report it separately.

This affects UX in terms of e.g. the added region not being returned by `RegionUtils.getRegionsForService()` (actual usage of the region by setting it explicitly to the result of e.g. `RegionUtils.getRegion("ap-south-1")` does work as expected).

### Workaround

By chance of requiring a solution for #1417 right away, we have successfully used the [PartitionsLoader](https://github.com/aws/aws-sdk-java/blob/39ebf439b8e4050684cbfca1811c84b3ac5f2468/aws-java-sdk-core/src/main/java/com/amazonaws/partitions/PartitionsLoader.java#L45) capability to load an override `com/amazonaws/partitions/override/endpoints.json` from the class path , very helpful feature!

**Comment by dagnir** [comment]
Looks like the region information is now properly reflected for ECS as of [1.11.252](https://github.com/aws/aws-sdk-java/blob/c5f04d7bd539005c68036dfe4e1b78241a7811c1/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L637). Closing this issue.
