### ISSUE TITLE
Latest API documentation?

### ISSUE THREAD

**Issue by jhult** [aws/aws-sdk-java#1420]
This seems out of date: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html

It references "AWS SDK for Java API Reference - 1.11.247".

Also, the [WorkMail API reference](https://docs.aws.amazon.com/workmail/latest/APIReference/API_ListGroups.html) links to [this page](http://docs.aws.amazon.com/goto/SdkForJava/workmail-2017-10-01/ListGroups) (which appears to go nowhere).

**Comment by dagnir** [comment]
Thanks for letting us know. The update is in progress now and should fix both issue. It should be available within an hour.

**Comment by dagnir** [comment]
Tested both links and they are now linking to the correct pages. Closing this issue.
