### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by swch125** [aws/aws-sdk-java#1421]
![image](https://user-images.githubusercontent.com/24468307/34187588-31277b0e-e56d-11e7-8a68-dc779082cec2.png)

i use ams-sdk-java-s3 in java,  and use method  s3.putObject(bucketName, amazonKey, is, metadata) to upload picture to my s3, but it also is used 10 minutes .And i try to use .setExpirationTime(),but it is unuseful. how can i do to set ?

**Comment by dagnir** [comment]
Hi, sorry I'm not sure what the question is. Are you trying to download the object using a presigned URL?

**Comment by dagnir** [comment]
Closing this due to lack of response. Please feel free to reopen if you continue to experience this issue.

**Comment by Daniela9696** [comment]
![Screenshot_2024-07-28-02-36-04-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/d1bafc6e-e291-4f67-82a3-57bb73d0071f)


Esto me aparece y no puedo conectar
