### ISSUE TITLE
Upload Lambda from eclipse

### ISSUE THREAD

**Issue by xlmeng** [aws/aws-sdk-java#1427]
I always got the following error when uploading a Lambda function:
Failed to load iam role in US West (Oregon): com.amazonaws.services.identitymanagement.model.AmazonIdent

**Comment by dagnir** [comment]
Hi @xlmeng are you trying to use the Eclipse Toolkit? If so, there's a separate repository for it here: https://github.com/aws/aws-toolkit-eclipse. Going to go ahead and close this. Feel free to reopen if it's not for the toolkit/you have other issues relating to the SDK.
