### ISSUE TITLE
Feature Request: EC2 Resource Serialization for Cloud Formation Template

### ISSUE THREAD

**Issue by flound1129** [aws/aws-sdk-java#1433]
Maybe I'm missing something, but there doesn't seem to be an easy way to add an EC2 resource (Instance, Volume, etc.) directly to a CloudFormation template.

Could a method be added to EC2 objects that returns and ObjectNode in the correct format for adding to the CF template?

**Comment by shorea** [comment]
Can you give me an example of how that would look?

**Comment by flound1129** [comment]
What I envisioned was a method similar to toString() that would spit out the JSONNode or ObjectNode needed to include the resource in a CloudFormation template.

**Comment by flound1129** [comment]
Alternately, there could be a CloudFormationTemplate class that has a .addResource() method that accepts any object under com.amazonaws.services.ec2.model.

Anything that lets me more easily add a resource to a template without requiring me to know exactly which fields need to be populated would be very welcome.

**Comment by debora-ito** [comment]
@flound1129 the SDK team has reviewed the feature request list for V1 and decided not to implement this one, as they are concentrating efforts on V2 new features. I'll go ahead and close this one.

Feel free to open a new feature request in the V2 repo if you are still interested in seeing this, and reach out if you have further questions.
