### ISSUE TITLE
getReplacement() should return boolean, not String

### ISSUE THREAD

**Issue by flound1129** [aws/aws-sdk-java#1434]
com.aws.services.cloudformation.model.getResourceChange().getReplacement() currently returns a string, "True" or "False".  Wouldn't it be more proper to return the native boolean value?

**Comment by kiiadi** [comment]
@flound1129 looking at the [API documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ResourceChange.html) this value can be "True", "False" or "Conditional" - therefore a boolean will not work.
