### ISSUE TITLE
Lambda: Provide access to ObjectMapper in LambdaInvokerFactory

### ISSUE THREAD

**Issue by gerrit-hntschl** [aws/aws-sdk-java#1436]
Hi,

I need to set the date format for the `ObjectMapper` and now have to resort to reflection.
Please make the static `MAPPER` accessible or allow to set your own instance.

Best regards,
Gerrit

**Comment by kiiadi** [comment]
Can you provide an example of where you need this? I'm not sure I fully understand the context.

**Comment by gerrit-hntschl** [comment]
Thanks for the response. 

What I am doing is this:
```
class RequestParams{
 private Date startDate;

 public Date getStartDate(){
   return startDate;
 }
}
```
The lambda function expects dates to be formatted as a string according to ISO8601.

To invoke the lambda I use this:

```
public interface SomeLambda {
    @LambdaFunction
    Response doSomething(RequestParams request);
}

LambdaInvokerFactory.builder()
                .lambdaClient(lambda)
                .build(SomeLambda.class).doSomething(new RequestParams(someStartDate));

```
Under the hood the LambdaInvokerFactory uses the static field `ObjectMapper MAPPER` to turn my `RequestParams` into JSON.

The problem is I cannot access that mapper to tell it how to serialize the date. Currently I have to hack my way around that like this:
```
            Field mapperField = LambdaInvokerFactory.class.getDeclaredField("MAPPER");
            mapperField.setAccessible(true);

            Object mapperVal = mapperField.get(null);
            if (!(mapperVal instanceof ObjectMapper)) {
                throw new IllegalStateException("Mapper not an objectmapper: " + mapperVal.getClass());
            }
            ObjectMapper objectMapper = (ObjectMapper) mapperVal;

            objectMapper.setDateFormat(new ISO8601DateFormat());
```

For my use-case having `.objectMapper(...`-method on the `LambdaInvokerFactory.Builder` would be fine.

**Comment by shorea** [comment]
Would the JsonFormat annotation work?

http://www.baeldung.com/jackson-jsonformat

**Comment by shorea** [comment]
Closing this issue, if the mentioned annotation doesn't work out feel free to reopen and we can explore other options.

**Comment by etwillbefine** [comment]
In our use case the `@JsonFormat` annotation is not very suitable. We have defined one object mapper for all our applications und dtos. I dont want to go through each `Date` property and add an annotation just because there is no easy way to override the static mapper which in any case should be configureable.

**Comment by avirtuos** [comment]
Looks like you can now provide your own ObjectMapper when creating an Invoker via LambdaInvokerFactory. Does this solve your issue?

`       metadataService = LambdaInvokerFactory.builder()
                .lambdaClient(AWSLambdaClientBuilder.standard()
                        .withCredentials(new AWSStaticCredentialsProvider(awsCreds))
                        .build())
                .objectMapper(ObjectMapperFactory.create())
                .build(MetadataService.class);
`

**Comment by etwillbefine** [comment]
Yes
