### ISSUE TITLE
Reported region list for data.iot seems to be wrong

### ISSUE THREAD

**Issue by fpolzer** [aws/aws-sdk-java#1438]
Looking into the SDK docs at https://docs.aws.amazon.com/general/latest/gr/rande.html#iot_region tells that the things-shadow service (data.iot) should be enabled for the us-east-2 region.

But when using the API it tells that it isn't supported.

Looking into the SDK code it seems that the json list for the supported regions for the data.iot endpoint seems to miss some region entries that should be supported due to the SDK docs:

"data.iot" : {
	"defaults" : {
		"credentialScope" : {
			"service" : "iotdata"
		},
		"protocols" : [ "https" ]
	},
	"endpoints" : {
		"ap-northeast-1" : { },
		"ap-northeast-2" : { },
		"ap-southeast-1" : { },
		"ap-southeast-2" : { },
		"eu-central-1" : { },
		"eu-west-1" : { },
		"us-east-1" : { },
		"us-west-2" : { }
	}
}

**Comment by spfink** [comment]
We are working on getting our region data updated and should have an update next week. You should still be able use IoT data in us-east-1 just fine though.

**Comment by varunnvs92** [comment]
As spfink@ mentioned, you can still use iot in us-east-2 even if endpoints.json is not updated. We get this information from a different team where they don't have current data for Iot. I have raised an internal issue for that team. 

Closing the issue. Feel free to re-open if you are having trouble with using iot in us-east-2.
