### ISSUE TITLE
Provide target region on Request object for xray-sdk 

### ISSUE THREAD

**Issue by glicht** [aws/aws-sdk-java#1439]
Hi,

Currently the xray-sdk for Java is unable to report the target region for outgoing aws service calls.  

A reply from the xray team (@jamesdbowman) has indicated that this is actually a limitation in the aws-sdk-java, that it doesn't provide this information as part of the Request object.

I am opening this feature request to add the target region information to the Request so we can have this information as part of the xray traces.

See following issue and reply at aws-xray-sdk-java: https://github.com/aws/aws-xray-sdk-java/issues/7

thanks,

Guy

**Comment by shorea** [comment]
Support for this was added in the sdk. You can follow xrays integration via the issue in the other repo.
