### ISSUE TITLE
Protocol changes from version 226 -> 277

### ISSUE THREAD

**Issue by ardias** [aws/aws-sdk-java#1442]
Hi All,
I have a question regarding version after 226 that is making my "integration" tests fail.
I'm using Hoverfly (http proxy) to capture the requests and responses made using the SDK and with version 200 (1.11.200) everything was working fine. 
Now i needed support for Global Tables and so updated my sdk version to the latest release, 257. With this version I'm having problems with S3 and DynamoDb. Something changed that is making Hoverfly either not return data (for example DynamoDb `listTables`) or return different data (S3).
I've tested with various versions and it seems this started to happen when going from version 226 to 227.

My question is, did something change in the core protocol that may be making Hoverfly fail?

**Comment by shorea** [comment]
I don't see anything that could possibly affect Dynamo but there were some endpoint changes to S3 that might be affecting you.

https://github.com/aws/aws-sdk-java/commit/ef57ea8238f5ce7a3d321434b41381cf3a497f93#diff-7fdbe9b566d0c5a3c98deef8c920bbd0

**Comment by ardias** [comment]
Thanks @shorea . I had to do some other stuff, but then i finally found the problem. By default Hoverfly was not storing all headers in the request and so when it "played back" it couldn't distinguish the requests properly and would respond with whatever response it would find first. The fix was configuring Hoverfly to save the **x-amz-target** header so that it can correctly return the proper response to the request.
