### ISSUE TITLE
Is the documentation correct re: md5 vs ETag?

### ISSUE THREAD

**Issue by daisieh** [aws/aws-sdk-java#1444]
If I understand the situation correctly, an object's ETag is equivalent to its md5 checksum if it was uploaded in a single part and less than 5GB in size, but is calculated differently otherwise. However, the [getETag javadoc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getETag--) says that the ETag *is* the same as the md5 checksum, and the [getContentMD5 doc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getContentMD5--) says that this will be the same as the ETag. Is this documentation out of date?

**Comment by dagnir** [comment]
Yes the javadoc is out of date. We will fix this.

**Comment by shorea** [comment]
This documentation has been improved and will be available in our next release.
