### ISSUE TITLE
ProgessEvents continue to arrive after TransferManager.shutdownNow()

### ISSUE THREAD

**Issue by apara** [aws/aws-sdk-java#1445]
We create a TransferManager, register a ProgressListener, and then waitForCompletion().  After the transfer is done we invoke shutDownNow(false).  However, the invocations to ProgressListener.progressChanged still continue to happen even after shutdownNow() returns.  I suspect this is due to the fact that notifications have been queued up for asynchronous delivery already and continue to be delivered.  

Are the notifications somehow related to a specific TranscodeManager?  is there a way to purge any remaining notifications?  I actually think that TranscodeManager.shutdown() should probably purge any unprocessed notifications.

Is this a bug or intended operation?  

```
        TransferManager aws = new TransferManager(client);

        try {
            Transfer upload = aws.upload(req);
            if (listener != null) {
                upload.addProgressListener(new ProgressListener() {
                    long totalBytesTransferred;

                    //THIS METHOD CONTINUES TO BE INVOKED even AFTER upload.waitForCompletion() returns.
                    public void progressChanged(ProgressEvent progressEvent) {
                        this.totalBytesTransferred += progressEvent.getBytesTransferred();
                        ...
                    }
                });
            }

             //HERE we wait for upload to complete
            upload.waitForCompletion();
        } 
        finally {
            //HERE we shutdown the TransferManager, but ProgressListener.progressChanged continue to be invoked
            aws.shutdownNow(false);
        }

```

**Comment by dagnir** [comment]
This appears to be expected behavior as progress publishing can be handled asynchronously within a different non `TransferManager` owned thread pool: https://github.com/aws/aws-sdk-java/blob/60196261032eb91e615478ba78c085cc57e72621/aws-java-sdk-core/src/main/java/com/amazonaws/event/SDKProgressPublisher.java#L51

**Comment by dagnir** [comment]
If you need to ignore any pending progress event deliveries after the transfer has completed, then you could probably do something like

```java
public void progressChanged(ProgressEvent progressEvent) {
    if (!upload.isDone()) {
        ...
    }
}
```

**Comment by shorea** [comment]
Closing issue due to no response. If the workaround suggested by @dagnir does not work, feel free to reopen.

**Comment by apara** [comment]
That work around worked, but is there a way to reduce the frequency of ProgressEvents?  If many large transfers are in progress is there a chance of consuming a lot of memory as progress events stack up in the queue?
