### ISSUE TITLE
Allow monitoring of Connection pool 

### ISSUE THREAD

**Issue by maczikasz** [aws/aws-sdk-java#1447]
Our Application keeps running into :

 `Unable to execute HTTP request: Timeout waiting for connection from pool
com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool`

We are suspecting that our pool settings is too low, but it seems to be impossible to create monitoring on the current status of the connection pool.

The connection manager or the connection manager factory is not injectable, there are no JMX beans available, and the MetricsCollector is only called after the request is executed.

Am i missing something that would allow me to monitor in order to fix the problem, or is it really not possible?

**Comment by dagnir** [comment]
What service client are you running into this issue with? This is a common error in S3 during multiple parallel uploads for example where an `PutObject` operation can get blocked for a long time while all the connections are used for other uploads.

This can also occur when leaving open streams that are returned from a streaming service operation. Again using S3 as an example, this can happen if the object InputStream from S3's `GetObject` is never closed.

**Comment by maczikasz** [comment]
Ahh sorry yes it's the S3 client.

I know that these root causes are possible, my main problem is not really the fix of the issue.

My problem is that there is two possibilities as you mentioned it, either we are just having a connection pool that's set to a too low number of connection so  in a period of high usage it simply runs out.

Or we are leaking the streams and not closing them somewhere.

This is exactly the reason I would like to monitor the state of the pool because that would help us in identifying which of the two case we are running into. If the pool size keeps growing even after hot period is over we are leaking them probably , on the other hand it would also help us to identify the zone where our connection pool size need to be to be able to serve our clients

**Comment by dagnir** [comment]
@maczikasz I see. Do the metrics gathered by the client help solve your use case? You can refer to the following links to get an idea of what you can monitor with it:

- https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/
- https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/
- https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/util/AWSRequestMetrics.java#L41

**Comment by shorea** [comment]
@maczikasz do you need anything from us or can I close this issue?

**Comment by maczikasz** [comment]
Sorry I forgot to answer I have just deployed the application with the monitoring for the pool and i see that we the leased connection keep growing, so I am probably leaking the connections somewhere.

Maybe you know if there is any kindof leak detection we can use for the connection manager or any way to inject a wrapper around it that would allow us to find leaks

**Comment by shorea** [comment]
Are you using any kind of streaming APIs? I.E. an API that returns an InputStream as part of the response object? Failure to read from this input stream is the most likely cause for leaked connections.

**Comment by maczikasz** [comment]
We use the s3Client.getObject and we return this IS to the client, but even if it's not read I think spring should take care of it, but I will investigate in this direction

**Comment by shorea** [comment]
Since the input stream has a direct reference to the connection, if it's not read fully the connection will be unable to be returned to the pool.

**Comment by maczikasz** [comment]
Thanks for the help, I managed to track down the leak after enabling DEBUG logging on the PoolingHttpClientConnectionManager and looking for mismatch between the number of 
"Connection leased" and "Connection released", it was due to an exception thrown before we give the stream to Spring for handling

**Comment by chsi13** [comment]
@maczikasz I'm facing with the same problem... did you finally found interesting stuff  ?

My first idea was to change the socketTimeout value.. Default is very big (50 secs)..

**Comment by maczikasz** [comment]
@chsi13 sorry man, but in our case the bug was on our side, I don't exactly remember what but the point was that the stream was not read fully because of some exception
