### ISSUE TITLE
XMLInputFactory Lock Contention

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java#1449]
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/StaxResponseHandler.java#L91-L98

```Java
        XMLEventReader eventReader;
        synchronized (xmlInputFactory) {
            try {
                eventReader = xmlInputFactory.createXMLEventReader(content);
            } catch (XMLStreamException e) {
                throw handleXmlStreamException(e);
            }
        }
```

XML response processing is serialized around creating a XML reader, and at least one customer has reported contention acquiring an XML reader in the code above at ~2k TPS.

The SDK should consider pooling `XMLInputFactory` instances or storing them thread-locally. Note: this synchronized pattern is used for `XMLInputFactory` instances elsewhere. We should also consider fixing this globally for the SDK.

**Comment by shorea** [comment]
Staged for next release.
