### ISSUE TITLE
AWS Pricing API missing certain instance types

### ISSUE THREAD

**Issue by paksv** [aws/aws-sdk-java#1450]
I'm trying to use Pricing API, but it looks like certain instance types are missing (с5.large for eu-west-3). For example:
```
        Filter parisFilter = new Filter().withType(FilterType.TERM_MATCH).withField("location").withValue("EU (Paris)");
        Filter c5Filter = new Filter().withType(FilterType.TERM_MATCH).withField("instanceType").withValue("c5.large");
        AWSPricing pricing = AWSPricingClientBuilder.standard().withCredentials(creds).withRegion("us-east-1").build();
        pricing.getProducts(
                new GetProductsRequest()
                        .withServiceCode("AmazonEC2")
                        .withFilters(parisFilter, c5Filter)
        )
                .getPriceList()
                .forEach(System.out::println);
```
The code above returns nothing, despite c5.large is actually available for eu-west-3.
c5.18xlarge is also missing.

If I change instance type filter to c5.xlarge, the code will return 4 lines:
```
{"product":{"productFamily":"Compute Instance","attributes":{"enhancedNetworkingSupported":"Yes","memory":"8 GiB","dedicatedEbsThroughput":"Upto 2250 Mbps","vcpu":"4","locationType":"AWS Region","storage":"EBS only","instanceFamily":"Compute optimized","operatingSystem":"Windows","physicalProcessor":"Intel Xeon Platinum 8124M","clockSpeed":"3.0 Ghz","ecu":"16","networkPerformance":"Up to 10 Gigabit","servicename":"Amazon Elastic Compute Cloud","instanceType":"c5.xlarge",....}
....
```

Another inconvenient thing is that I cannot filter by region code (like eu-west-3), only by Human Readable name, which is not available anywhere else.

**Comment by paksv** [comment]
It would be fair to say that https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/eu-west-3/index.json misses those entries too, but it's not possible to submit a bug against Pricing API.

**Comment by paksv** [comment]
![2018-01-16_14-55-30](https://user-images.githubusercontent.com/4375974/34992404-6cd45b5c-facd-11e7-96dd-2ad7d2642e3c.png)

**Comment by spfink** [comment]
I've opened an issue with the service team behind the pricing API. Will let you know what we hear back.

**Comment by spfink** [comment]
An update to the available data has been pushed out. However, still working on getting c5.18xlarge available through the API.

**Comment by paksv** [comment]
Thanks a lot. What should I do next time I see the mismatch?

**Comment by spfink** [comment]
@paksv, doesn't look like Pricing has a forum on the AWS forums so you can come back here and we can forward the request to the Pricing team.

**Comment by shorea** [comment]
Looks like c5.18xlarge is also available so closing issue.

**Comment by mobrien** [comment]
c5.large is missing in us-east-1
