### ISSUE TITLE
Password reset for any user in Cognito only needs email/userid

### ISSUE THREAD

**Issue by alok13** [aws/aws-sdk-java#1452]
Password reset for any user in Cognito only needs email/userid and status of user changes to "FORCE_RESET_PASSWORD" and *then user cannot login until he changes the password*.

Question 1 : Why such behaviour
Question 2:  Someone else can enter other's email ID and that user is now blocked until he change his password.  Not user friendly at all.
Question 3: Any way we can change the status of user from Admin API's?
Question 4 : Anyway to do it without confirmation code(name and password are enough )

**Comment by spfink** [comment]
Please create a post in the Amazon Cognito forum: https://forums.aws.amazon.com/forum.jspa?forumID=173

That forum is monitored by members of the Amazon Cognito team.
