### ISSUE TITLE
CloudSearch API model doesn't define a uid in its metadata 

### ISSUE THREAD

**Issue by lvh** [aws/aws-sdk-java#1453]
Unlike every other API, which does. The correct uid is presumably `cloudsearch-2013-01-01`.

**Comment by spfink** [comment]
Can you give me some details on how this is effecting you?

**Comment by lvh** [comment]
As far as I know, the API UID is the only unique way to refer to an API and operations within it. I log the UID of an API as part of some instrumentation.

**Comment by shorea** [comment]
We have fixed this internally and it will be included in our next release.

**Comment by lvh** [comment]
Cool, thanks :)
