### ISSUE TITLE
Add amazon-sqs-java-messaging-lib to bom

### ISSUE THREAD

**Issue by candrews** [aws/aws-sdk-java#1455]
It would be nice if [amazon-sqs-java-messaging-lib](https://github.com/awslabs/amazon-sqs-java-messaging-lib) were added to the [bom](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-bom/pom.xml).

**Comment by shorea** [comment]
Unfortunately this is a maintained by a separate team and outside of our normal release process. It's transitive SDK dependencies should be influenced by the BOM module though.
