### ISSUE TITLE
API Gateway generated clients do not support payloads for DELETEs

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java#1456]
Unfortunately DELETEs with a body are a weird situation, since they're not technically prohibited by any RFCs, but aren't widely supported.

That said, other SDKs with generated clients could potentially support this, so Java should as well. This applies to all SDKs with API-gateway generated clients, not just Java.

**Comment by debora-ito** [comment]
Closing this. Support in V2 is being discussed.
