### ISSUE TITLE
TransferManager copy using multipart HighLevel API - No byteCount ProgressEvent generated

### ISSUE THREAD

**Issue by amarkin** [aws/aws-sdk-java#1461]
With the MultiPart Copy implementation we are unable to receive the transfer progress data like bytesTransferred or percentTransferred. 

I see the TRANSFER_COMPLETED_EVENT event generated but don't get the bytesTransferred or percentTransferred.

```
TransferManager tx = TransferManagerBuilder.standard()
        	        .withMultipartCopyPartSize(5 * (long)Math.pow(2.0, 20.0)) // 5MB Part Size
        	        .withMultipartCopyThreshold(5 * (long)Math.pow(2.0, 20.0))
        	        .withS3Client(s3ClientRemote)
        	        .build();

Copy copy = transferManager.copy(sourceBucketName, sourceObjectKey, targetBucketName, targetObjectKey);

copy.addProgressListener(new ProgressListener(){
			
	public void progressChanged(ProgressEvent event) {
		System.out.println("getEventCode.name--->"+event.getEventType().name());
		System.out.println("isTransferEvent()--->"+event.getEventType().isTransferEvent());
		System.out.println("isByteCountEvent()--->"+event.getEventType().isByteCountEvent());
		System.out.println("getBytesTransferred--->"+event.getBytesTransferred());
		System.out.println("getBytes--->"+event.getBytes());
	}});
```

Please see the similar issue reported in the forum.
https://forums.aws.amazon.com/thread.jspa?threadID=255379&tstart=0

Thanks
Amar.

**Comment by amarkin** [comment]
@kiiadi ,

Any help on this issue would be appreciated.

Thanks
Amar.

**Comment by amarkin** [comment]
Here is the aws-java-sdk version I am using.

<dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk</artifactId>
      <version>1.11.197</version>
      <scope>compile</scope>
</dependency>

**Comment by amarkin** [comment]
@millems ,

I have noticed you have addressed similar issue on #1076. Can you please check this ticket and let me know if I am missing anything ? 

Thanks
Amar.

**Comment by varunnvs92** [comment]
@amarkin As millems@ mentioned in [this comment](https://github.com/aws/aws-sdk-java/pull/1076#issuecomment-343627884), currently copy operation doesn't support the transfer events. We will not be changing the behavior in 1.11.x. We are actively working on SDK 2.0 which has a [open feature request](https://github.com/aws/aws-sdk-java-v2/issues/25) for progress listeners. This issue will be addressed in 2.0. Feel free to add your requests/suggestions there.

**Comment by amarkin** [comment]
@varunnvs92 ,

Thanks for the response. Just to be clear we are using copy parts(MultiPart Copy). 

I understand with version v1,  copy with **NO** parts will not generate the transfer events. 

How about the copy parts ? are we supposed to get transfer events with copy parts in version v1 ?

Thanks
Amar.

**Comment by varunnvs92** [comment]
Ideal behavior would be to generate transfer events when using parts. But we are hesitant to change the behavior now as there can be cases which might break existing customers. We are also not adding any new features for high level utilities like TransferManager, DynamoDb Mapper in 1.11.x as we are focusing on SDK 2.0
