### ISSUE TITLE
SetQueueAttribute performance vis REST vs SDK

### ISSUE THREAD

**Issue by noviceamateur** [aws/aws-sdk-java#1462]
I tried the SetQueueAttribute using the sqs java sdk call. And the changes made by that call were effective almost immediately on the queue. 
I tried the same call by using the REST call directly . Gave the same version as in the SDK call also. But , here I had to wait for around 30 seconds before the changes got effective.

I know in the documentation,it is mentioned that it can take upto 1 minute for the changes to propagate. But, how come it is happening almost instantaneously via SQS SDK?
What can I add to my REST Call apart to get the same result ?

**Comment by varunnvs92** [comment]
I don't think the SDK does anything special to make the call. We just marshall the request into wire format and send it to service. See [SetQueueAttributesRequestMarshaller](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/transform/SetQueueAttributesRequestMarshaller.java). Any difference you observe is happening on service end. You should reach out to service team (Amazon SQS) either through forums or console support.

I am closing the issue as this is not an issue in Java SDK. For general questions, please post in public forums to get better support. See the [Getting Help](https://github.com/aws/aws-sdk-java#getting-help) section.
