### ISSUE TITLE
ProfilesConfigFile returns results from Credentials file (not Config file)

### ISSUE THREAD

**Issue by godzsa** [aws/aws-sdk-java#1464]
When I call `ProfileConfigFile().getAllBasicProfiles()` I expect it to load properties for the profiles defined in `.aws/config` based on the class' name. However it returns the properties from the `.aws/credentials` file.

**Comment by godzsa** [comment]
What is a genuine way to get data form the config fle? What I found so far is
`ProfilesConfigFile(AwsProfileFileLocationProvider.DEFAULT_CONFIG_LOCATION_PROVIDER.location).allBasicProfiles` (Kotlin)

**Comment by shorea** [comment]
@godzsa this is the best we have for now. We've refactored the profile stuff a bit in https://github.com/aws/aws-sdk-java-v2. We'd certainly welcome your feedback on the new interfaces.

**Comment by varunnvs92** [comment]
We will not be changing the behavior in 1.11.x. As shorea@ suggested, please try v2 and provide your feedback. Thank you.
