### ISSUE TITLE
How to get Profile data from config and credentials?

### ISSUE THREAD

**Issue by godzsa** [aws/aws-sdk-java#1465]
I am looking for a way to get an array (or list) of `BasicProfile` filled with data collected from .aws/credentials and .aws/config files merged: 

Something like this: 

.aws/credentials :
```
[default]
aws_access_key_id = example_key1
aws_secret_access_key = example_secret1
[profile1]
aws_access_key_id = example_key2
aws_secret_access_key = example_secret2
```

.aws/config
```
[default]
region = ap-southeast-1
output = json
[profile2]
source_profile = default
role_arn = example_arn
```

calling `ProfileProvider().getProfiles()` (the function I am looking for) returns a list of `BasicProfile`s
```
[
  {
    "profileName": "default",
    "properties": {
       "aws_access_key_id": "example_key1"
       "aws_secret_access_key": "example_secret1"
       "region": "ap-southeast-1"
       "output": "json"
     }
  },
  {
    "profileName": "profile1",
    "properties": {
       "aws_access_key_id": "example_key2"
       "aws_secret_access_key": "example_secret2"
     }
  },
  {
    "profileName": "profile2",
    "properties": {
       "role_arn": "example_arn"
       "source_profile": "default"
     }
  }
]
```
There should also be a `getProfile(String profileName)` method, which returns the profile by its name, and

**Comment by shorea** [comment]
What's your use case?

**Comment by godzsa** [comment]
In general it would be useful if you want to get all the data regarding an aws profile in an app, orif you want to make adjustments to it via code.

In my case it is for choosing between defined aws profiles in a GUI so later that profile is used in my app (I am creating an IntelliJ IDEA plugin ([AWS Tail](https://plugins.jetbrains.com/plugin/10342-aws-tail)) and in the settings you could specify your aws credentials+configurations). By default I want it to load all the profile names to a list and let the user choose one, and output the data corresponding to a profile into textfields, so the user can update them, review them etc..

**Comment by godzsa** [comment]
I could create a merge request for this, if you find it useful

**Comment by millems** [comment]
Hey, see [ProfileFile](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/profiles/ProfileFile.html) in 2.x for this functionality.
