### ISSUE TITLE
Option to retrieve region display names ('description') via SDK

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#1467]
The region display names (e.g. 'US West (Oregon)' for 'us-west-2') are defined as 'description' entries in the SDK's  [endpoints.json](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json) resource.

We would like to retrieve those at runtime via SDK calls, but can't find a decent way to do so.

They seem to be available via [com.amazonaws.partitions.model.Region#getDescription](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/partitions/model/Region.java#L34), but that class is not usually exposed and has no obvious retrieval path (at least I have not found one yet).

The obvious place where I'd expect the display name/description to be available would be the more often used [com.amazonaws.regions.Region](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Region.java) class, which gives us access to e.g. the region's partition, but alas, not to the display name.

:grey_question: Is there an 'official' way to retrieve a region's display name via the SDK?

:grey_question: If not, would it be possible to add this option to the com.amazonaws.regions.Region class?

**Comment by teeohhem** [comment]
Done in https://github.com/aws/aws-sdk-java/pull/1595

**Comment by BigChief45** [comment]
@dagnir As @teeohhem mentioned, I think this can be closed.

**Comment by dagnir** [comment]
Nice! Thanks for the contribution @BigChief45!
