### ISSUE TITLE
Route53 Domains: Add API to retrieve supported TLD's with pricing and ExtraParams

### ISSUE THREAD

**Issue by tuzzmaniandevil** [aws/aws-sdk-java#1468]
At the moment we have to manually parse the JSON file: https://s3.amazonaws.com/ris-public/TldCatalog/v1/latest.json

Which works to a degree, but doesn't include the ExtraParams that some domains require like .ca

Would be better if this could be part of the official SDK with all the required information and objects needed to purchase domains via Route53 Domains. For example all the ExtraParams

**Comment by dagnir** [comment]
Hi, just so it's clear, are you asking for an API that returns data similar to the linked JSON document?

Can you explain your use case some more, maybe with a few quick examples?

**Comment by tuzzmaniandevil** [comment]
Kademi is a CX platform that allows users to send emails, host websites, stores, loyalty programs and a bunch of other stuff, One of the features we offer is allowing users to manage their domain within Kademi, For that we have integrated with Route53, We also have a feature to allow users to buy domains from Kademi, We are using Route53 Domains for that feature.

At the moment to provide a user-friendly UI to our users we parse the JSON file above and use the information from that to provide available domains, costings and also what fields are required when filling out the details part of the process. The JSON file is incomplete, It doesn't have all the details for extraParams required by some domains as listed here: https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_ExtraParam.html

Here are some screenshots of our screens:
![image](https://user-images.githubusercontent.com/3378330/36286691-abf71896-1315-11e8-823f-ca6d5c119f1a.png)

![image](https://user-images.githubusercontent.com/3378330/36286721-cae27070-1315-11e8-87a5-33ced458752c.png)

![image](https://user-images.githubusercontent.com/3378330/36286742-df101944-1315-11e8-82b8-1fd0991e7c84.png)

**Comment by tuzzmaniandevil** [comment]
@dagnir Any news on this? :-)

**Comment by dagnir** [comment]
Hey @tuzzmaniandevil sorry for the delay. I've gone ahead and forwarded the feature request to the Route 53 Domains team. Since there is no more action on the SDK side here, I'm going to go ahead and close this issue.
