### ISSUE TITLE
SQS Thread safety - Long polling blocks other threads

### ISSUE THREAD

**Issue by Selikoff** [aws/aws-sdk-java#1469]
After enabling long polling in SQS, I noticed my number of in-flight messages consistently spike.  After a lot of debugging, I've isolated it to a bug in the AmazonSQS SDK that shows it is not thread safe, despite being advertised as such.  

I've written a bug report here:  [https://www.selikoff.net/2018/02/14/the-amazon-aws-java-sqs-client-not-thread-safe/]

**Comment by fernomac** [comment]
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setMaxConnections-int-

**Comment by dagnir** [comment]
Hi @Selikoff, as @fernomac said, this is a result of API calls getting blocked on waiting for the next available connection from the HTTP client's connection pool. This can be solved by ensuring that the number of threads you intend to do long polling with is less than or equal to the number of max connections set in your client.

**Comment by millems** [comment]
Please let us know if this hasn't resolved your problem.
