### ISSUE TITLE
CompleteMultipartCopy does not abort multipart upload if one of the parts failed

### ISSUE THREAD

**Issue by artamonovkirill** [aws/aws-sdk-java#1471]
[collectPartETags](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CompleteMultipartCopy.java#L116-L117) method throws an SdkClientException if one of the part futures has failed.
No attempt is made to abort multipart upload in [CompleteMultipartUpload.call()](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CompleteMultipartCopy.java#L86-L87).
This causes multipart uploads to remain incomplete and never be closed.

**Comment by dagnir** [comment]
Thanks for pointing this out. The same thing could happen if even the complete call fails as well. As a fix to do this, would setting a bucket life cycle policy to automatically abort incomplete multipart uploads work for you?

https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html#mpu-abort-incomplete-mpu-lifecycle-config

**Comment by artamonovkirill** [comment]
Hi, @dagnir.

We currently having two use cases:
1) Persisting artifacts on an s3 bucket by request from our service consumers.
2) Delivering artifacts from our s3 bucket to our service consumers' bucket upon request.

While it can work for the 1st case, it might be a bit trickier for the 2nd case (as we don't own the buckets with pending multipart uploads).
