### ISSUE TITLE
CompleteMultipartCopy does not emit an event to TransferStateChangeListener when one of the parts fails

### ISSUE THREAD

**Issue by artamonovkirill** [aws/aws-sdk-java#1472]
CompleteMultipartCopy only takes [ProgressListenerChain as a constructor argument](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CompleteMultipartCopy.java#L61-L63).
If one of the part futures fails to complete, an event is [sent to the ProgressListenerChain](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CompleteMultipartCopy.java#L86).

Yet, if only [TransferChangeChangeListener is provided to the copy request](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L1906-L1907), without [adding a ProgressListener](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/Transfer.java#L118) to a Copy object returned by TransferManager.copy, we never receive a TransferState.Failed or TransferState.Cancelled event in the TransferStateChangeListener.

Thus, we have to use two listeners to have the complete state of the transfer.

**Comment by millems** [comment]
Your first paragraph/title mentions `upload` requests, and your second paragraph mentions `copy` requests. Are you having this issue with copies as well as uploads?

**Comment by artamonovkirill** [comment]
Hi, @millems.
We only experienced this problem while copying files from one bucket to another.
We haven't experimented with uploading files to/from an s3 bucket to check if it also occurs there.

**Comment by artamonovkirill** [comment]
@millems, I've also corrected class name in the issue to the correct one.

**Comment by millems** [comment]
Sorry this issue sat so long without comment. We're currently focused primarily on 2.x of the SDK and won't be implementing this in 1.11.x.
