### ISSUE TITLE
Comprehend Service nowhere supported?

### ISSUE THREAD

**Issue by guntherstuer** [aws/aws-sdk-java#1474]
When using the Java SDK, it is not possible to use the Comprehend Service as it does not seem to be supported by any region.

For example, 
- RegionUtils.getRegionsForService(AmazonComprehend.ENDPOINT_PREFIX), return an empty array
- Region.getRegion(Regions.EU_WEST_1).isServiceSupported(AmazonComprehend.ENDPOINT_PREFIX), returns false

While via the CLI, it works just fine

**Comment by dagnir** [comment]
Those classes use the data in our [endpoints.json](https://github.com/aws/aws-sdk-java/blob/7b4854b5e03729e831d1e43d5e20c5098fdb8d90/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L1), and Comprehend is missing at the moment. We're investigating this issue with the source that we pull this information from.

For now, if Comprehend is listed as available in a following region here: https://docs.aws.amazon.com/general/latest/gr/rande.html#comprehend_region you should be able to configure the client to use that region.

**Comment by dagnir** [comment]
This should now be fixed as of 1.11.290:

https://github.com/aws/aws-sdk-java/blob/a7d4956bb055e3b15198590d0cbdf99b2755f80e/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L497
