### ISSUE TITLE
kms account id

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/aws-sdk-java#1479]
We have a  KMS key and s3 bucket on a different account from the one running a java app
following https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/SSEAwsKeyManagementParams.html#getAwsKmsKeyId--
it asks for KMS key, instead of ARN
this means that when running the app, it will fill in the account id and region with the one from the app account and not the right one.

is it possible to fill in the accountid as a parameter in the constructor ?

**Comment by spfink** [comment]
No that is not possible. 

You can try creating a feature request for this in the Amazon S3 forum:

https://forums.aws.amazon.com/forum.jspa?forumID=24

But it's unlikely that you will be able to use AWS account id as an input without also having credentials attached to that account.

**Comment by FernandoMiguel** [comment]
@spfink you mean like assuming a role?
