### ISSUE TITLE
 com.amazonaws.SdkClientException: Unable to execute HTTP request

### ISSUE THREAD

**Issue by mydata** [aws/aws-sdk-java#1481]
I am trying to execute the sample code given here : https://docs.aws.amazon.com/rekognition/latest/dg/images-bytes.html

I am getting  com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to rekognition.us-east-1.amazonaws.com:443 [rekognition.us-east-1.amazonaws.com/35.153.137.23, rekognition.us-east-1.amazonaws.com/52.22.179.95, rekognition.us-east-1.amazonaws.com/54.165.54.72] failed: connect timed out

Development environment:
OS : MacOS

Is there any additional access/network connectivity need to be open to access the rekognition sdk operations from local desktop and/or aws ecs container instances?

**Comment by spfink** [comment]
There shouldn't need to be any additional configuration needed from a local desktop or container. Are you using a proxy? Running in a VPC?

**Comment by dagnir** [comment]
Closing since there has been no response. Please feel free to reopen if you're still experiencing this issue.

**Comment by jyrai** [comment]
@spfink I have same Issue,
My lambda function is stored on the s3 bucket and trying to publish message on a sns topic by triggering lambda function. It is running on a VPC.

Here is my error
 Unable to execute HTTP request: Connect to sns.eu-central-1.amazonaws.com:443 [sns.eu-central-1.amazonaws.com/54.239.55.119] failed: connect timed out: com.amazonaws.SdkClientException

Thank you.

**Comment by murugesan70** [comment]
My lambda is having the same issue accessing to S3. I am accessing some resources in VPC which is working fine, but wanted to delete the S3 resource (IAM role has DeleteObject permission).

Here is my error:
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to <bucket>.s3.us-west-2.amazonaws.com:443 [<bucket>.s3.us-west-2.amazonaws.com/54.231.168.212] failed: connect timed out

**Comment by codewinkel** [comment]
I have the same problem due connecting from lambda to s3 - there are some internal issues related to that @aws ???? The same functionality with the same lambda role in the same vpc is working fine so far. Hm, confusing ... Some ideas???

Unable to execute HTTP request: Connect to ...s3.eu-central-1.amazonaws.com:443 [....s3.eu-central-1.amazonaws.com/IP.ADDRESS.XX.YY] failed: connect timed out

**Comment by contacttapan** [comment]
any update on this issue, even I am facing the issue.

**Comment by gavinromberger** [comment]
Im getting the same issue

com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to dynamodb.us-west-2.amazonaws.com:443 [dynamodb.us-west-2.amazonaws.com/xx.xx.xx.xxx] failed: connect timed out

**Comment by contacttapan** [comment]
Hi,
My issue got resolved, it was related to VPC which lamda containers are configured, it was always using private VPC, hence no internet gateway for that ..so no S3 connection.

**Comment by vbijjam1** [comment]
I am trying to execute the sample code given here : https://docs.aws.amazon.com/rekognition/latest/dg/images-bytes.html

I am getting com.amazonaws.SdkClientException: Unable to execute HTTP request: rekognition.us-east-1.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
Caused by: java.net.UnknownHostException: rekognition.us-east-1.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy218.connect(Unknown Source)

Development environment:
OS : Window

Is there any additional access/network connectivity need to be open to access the rekognition sdk operations from local desktop and/or aws ecs container instances?

**Comment by mudasir111** [comment]
Does it have to do anything NAT Gateway for internet access??

**Comment by vbijjam1** [comment]
If my laptop is connected to my work network then its not working. When i tried it at home its working. What can i do to get it working with my work network. Please suggest

**Comment by nathanshurte** [comment]
Adding a +1, looks like a potential issue across different VPCs. Using the same creds from my local workstation or from inside the cluster with aws-cli works. Using them from the application in the cluster fails. Same errors using an entirely different SDK interface to accomplish the same thing, so it really suggests an environmental (or cluster-level) issue

**Comment by FrankKirin** [comment]
> Hi,
> My issue got resolved, it was related to VPC which lamda containers are configured, it was always using private VPC, hence no internet gateway for that ..so no S3 connection.

How do you fix the issue, can you tell me the process with more detail?

**Comment by cd-ujangiti** [comment]
Hi, I have same issue while connecting from kinesis data analytics to RDS MYSQL through secrets manager.  i have provided secrets manager full access, still failing with same below error. 

Flink Application Start Failed. Reason Unable to execute HTTP request: Connect to secretsmanager.us-east-1.amazonaws.com:443 [secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/18.214.158.206, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY] failed: connect timed out

**Comment by lucazin** [comment]
Unable to execute HTTP request: failed to connect to sqs.sa-east-1.amazonaws.com/52.46.172.189 (port 443) from /192.168.1.178 (port 42438) after 15000ms

i have this problem using sdk client  ( SQS )  in Android application. 

Using 4G network.

Some help please

    implementation 'com.amazonaws:aws-android-sdk-core:2.16.0'
    implementation 'com.amazonaws:aws-android-sdk-sqs:2.16.0'

**Comment by cd-ujangiti** [comment]
> Hi, I have same issue while connecting from kinesis data analytics to RDS MYSQL through secrets manager. i have provided secrets manager full access, still failing with same below error.
> 
> Flink Application Start Failed. Reason Unable to execute HTTP request: Connect to secretsmanager.us-east-1.amazonaws.com:443 [secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY, secretsmanager.us-east-1.amazonaws.com/IP.ADDRESS.XX.YY] failed: connect timed out

Resolution: 
This is resolved after creating the AWS Secrets Manager VPC endpoint with public subnets.

Using an AWS Secrets Manager VPC endpoint
https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html
https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html
