### ISSUE TITLE
Q - How to detect Shadow State change without subscribe to a topic

### ISSUE THREAD

**Issue by BorjaHazas** [aws/aws-sdk-java#1482]
Hello,

Is there any way to detect a Shadow State change without been subscribed to a topic?

I mean, is there a handler like _public void onMessage(AWSIotMessage message) {..........}_ but regarding the shadow update?

Your help is to much appreciated

Thanks in advance.

Kind regards,

**Comment by spfink** [comment]
There is not such a method today unfortunately. Subscribing to the topic and getting updates that way is the best method currently. 

We are always looking for new feature requests in our v2 repo:

https://github.com/aws/aws-sdk-java-v2

If you wouldn't mind creating an ask for this there. It's not something we are going to be able to pull into v1 at the moment.
