### ISSUE TITLE
S3 TagSet should maintain the insertion ordering of tags

### ISSUE THREAD

**Issue by daveagill** [aws/aws-sdk-java#1483]
The current implementation of TagSet (and associated parsing code) uses a HashMap to store tag pairs. This means the ordering is undefined and not stable across restarts of the JVM.

However, S3 tags do in fact appear to have a stable insertion ordering when viewed and managed from the AWS Console, this ordering should be maintained by the SDK. Perhaps by using a LinkedHashMap instead?

The consequence of the SDK not maintaining this ordering means that an attempt to append a single tag to an S3 bucket will also cause all pre-existing tags to re-order themselves randomly when viewed from the AWS Console.

The effect can be demonstrated with this code snippet:

```
// 1. retrieve existing tags
BucketTaggingConfiguration existingConf = s3Client.getBucketTaggingConfiguration(bucketName);
TagSet allTags = existingConf.getTagSet();
if (allTags == null) {
    allTags = new TagSet();
}

// 2. append our new tag
allTags.setTag(key, value);

// 3. push the new state back up
s3Client.setBucketTaggingConfiguration(bucketName, new BucketTaggingConfiguration().withTagSets(allTags));
```

**Comment by shorea** [comment]
+1 seems reasonable, I'll work on a fix.

**Comment by millems** [comment]
Sorry about the delay on this. A fix for this issue will go out in the next S3 service release, and we will  consider doing this for all services in the future.
