### ISSUE TITLE
javax.jms.JMSException: AmazonClientException: getQueueUrl.

### ISSUE THREAD

**Issue by Kiran-N** [aws/aws-sdk-java#1486]
I am getting the below exception, I fixed this once by setting the region. But It again started to give the same exception after a day. Thanks in advance.

{"@timestamp":"2018-02-22T16:14:07.905-06:00","@version":1,"log":"Servlet.service() for servlet [dispatcherServlet] in context with path [/api/v1/message] threw exception [Request processing failed; nested exception is org.springframework.jms.UncategorizedJmsException: Uncategorized exception occurred during JMS processing; nested exception is javax.jms.JMSException: AmazonClientException: getQueueUrl.] with root cause","logger_name":"org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/api/v1/message].[dispatcherServlet]","thread_name":"https-jsse-nio-443-exec-2","log_level":"ERROR","level_value":40000,"stack_trace":"s.s.p.c.SunCertPathBuilderException:
unable to find valid certification path to requested target\n\tat s.s.p.c.SunCertPathBuilder.build(SunCertPathBuilder.java:141)\n\tat s.s.p.c.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)\n\tat j.s.c.CertPathBuilder.build(CertPathBuilder.java:280)\n\tat s.s.v.PKIXValidator.doBuild(PKIXValidator.java:382)\n\tat s.s.v.PKIXValidator.engineValidate(PKIXValidator.java:292)\n\tat s.s.v.Validator.validate(Validator.java:260)\n\tat s.s.s.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)\n\tat s.s.s.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)\n\tat s.s.s.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)\n\tat s.s.s.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)\n\tat s.s.s.ClientHandshaker.processMessage(ClientHandshaker.java:216)\n\tat s.s.ssl.Handshaker.processLoop(Handshaker.java:1026)\n\tat s.s.ssl.Handshaker.process_record(Handshaker.java:961)\n\tat s.s.s.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)\n\tat s.s.s.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)\n\tat s.s.s.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)\n\tat s.s.s.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)\n\tat o.a.h.c.s.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)\n\tat o.a.h.c.s.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)\n\tat c.a.h.c.s.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132)\n\t... 118 frames truncated\n","appName”:”messaging”,”env":"int"}

**Comment by Kiran-N** [comment]
unable to find valid certification path to requested target\n\tat s.s.v.PKIXValidator.doBuild(PKIXValidator.java:387)\n\tat s.s.v.PKIXValidator.engineValidate(PKIXValidator.java:292)\n\tat s.s.v.Validator.validate(Validator.java:260)\n\tat s.s.s.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)\n\tat s.s.s.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)\n\tat s.s.s.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)\n\tat s.s.s.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)\n\t... 128 common frames omitted\nWrapped by: j.n.s.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat s.s.ssl.Alerts.getSSLException(Alerts.java:192)\n\tat s.s.s.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)\n\tat s.s.ssl.Handshaker.fatalSE(Handshaker.java:302)\n\tat s.s.ssl.Handshaker.fatalSE(Handshaker.java:296)\n\tat s.s.s.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)\n\tat s.s.s.ClientHandshaker.processMessage(ClientHandshaker.java:216)\n\tat s.s.ssl.Handshaker.processLoop(Handshaker.java:1026)\n\tat s.s.ssl.Handshaker.process_record(Handshaker.java:961)\n\tat s.s.s.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)\n\tat s.s.s.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)\n\tat s.s.s.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)\n\tat s.s.s.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)\n\tat o.a.h.c.s.SSLCon..."

**Comment by spfink** [comment]
Are you using a custom truststore? Is your truststore not in the default java install location?

**Comment by Kiran-N** [comment]
Yes We are using a custom trust store which includes the SSL certificate to connect to RDS.

**Comment by Kiran-N** [comment]
We fixed this by explicitly setting the credentials. Passing credentials though java args is not picked up by the SQS configuration.

**Comment by Kiran-N** [comment]
Yes we are using the custom trust store which has the cert for RDS

**Comment by spfink** [comment]
Have you pointed your JVM to the truststore?

**Comment by Kiran-N** [comment]
Yes we do

**Comment by Kiran-N** [comment]
It finally worked after adding the symantic certificate.
https://symwisedownload.symantec.com//resources/sites/SYMWISE/content/live/GENERAL_INFORMATION/2000/INFO2550/en_US/Symc_Cross_Root.txt?__gda__=1519572790_704e4d88e061ab9ef4785310453d25f4 

It would have been better if it was documented in AWS.
