### ISSUE TITLE
List Shards Kinesis: Getting Error code 500

### ISSUE THREAD

**Issue by kailashhd** [aws/aws-sdk-java#1490]
My setup:
Created a kinesis stream <stream-name> with 2 shards.
user-agent:aws-sdk-java/1.11.272 Java_HotSpot(TM)_64-Bit_Server_VM/25.152-b16 java/1.8.0_152 scala/2.11.11
Calling the endpoint ListShards x-amz-target:Kinesis_20131202.ListShards

Issue:
When I create my request with just the stream name I get the following result: 
{
    "Shards": [
        {
            "ShardId": "shardId-000000000000", 
            "HashKeyRange": {
                "EndingHashKey": <>, 
                "StartingHashKey": <>
            }, 
            "SequenceNumberRange": {
                "StartingSequenceNumber": <>
            }
        }, 
        {
            "ShardId": "shardId-000000000001", 
            "HashKeyRange": {
                "EndingHashKey": <>, 
                "StartingHashKey": <>
            }, 
            "SequenceNumberRange": {
                "StartingSequenceNumber": <>
            }
        }
    ]
}

But when the ListShardRequest is set with stream-name="stream-name" and exclusive-start-shard-id="shardid-000000000001", the request failed with the server returning 500 error. I tried this on the awscli too and was able to reproduce this issue. I don't know if this is the right place to report this bug as it looks like a problem with API behavior rather than SDK behavior.

**Comment by shorea** [comment]
What's the behavior you expect? Seems like it should be returning some type of validation error stating that stream name is required. Is this in line with your expectations?

**Comment by kailashhd** [comment]
Since ListShards is to replace the describeStream behavior, I would expect the result to be null and a valid 200 response. Note I am setting both the stream-name and also exclusive-start-shard-id. 

To give you an example, when I use the following command: aws kinesis describe-stream --stream-name <stream-name> --starting-token shardId-000000000001, I get an empty list of shards:  
"StreamDescription": {
        "KeyId": null, 
        "EncryptionType": "NONE", 
        "StreamStatus": "ACTIVE", 
        "StreamName": "stream-name", 
        "Shards": [], 
         ... <other fields>
}

**Comment by shorea** [comment]
@kailashhd I can't comment on the service behavior, I suggest reaching out to the Kinesis team for clarification on the 500 behavior. I did have better luck with using NextToken which I believe is the intended mechanism for paging shards. Note that the API does not allow setting both NextToken and StreamName for some reason so you'd have to only set NextToken for subsequent pages. Sample code below.

```java
        AmazonKinesis kinesis = AmazonKinesisClient.builder()
                                                   .withCredentials(new ProfileCredentialsProvider("personal"))
                                                   .withRegion(Regions.US_WEST_2)
                                                   .build();
        ListShardsResult result = kinesis.listShards(new ListShardsRequest()
                                                         .withStreamName("github-stream")
                                                         .withMaxResults(1));

        System.out.println(result);
        System.out.println(result.getNextToken());
        ListShardsResult nextResult = kinesis.listShards(new ListShardsRequest()
                                                             .withMaxResults(1)
                                                             .withNextToken(result.getNextToken()));
        System.out.println(nextResult);
        System.out.println(nextResult.getNextToken());
```

**Comment by kailashhd** [comment]
Thanks for verifying this. I am currently talking to the Kinesis service team and a likely solution for this is expected soon(FYI: For others who are experiencing this).

**Comment by pfifer** [comment]
From the Kinesis side thanks again for reporting this.  Kinesis has identified the issue, and we are currently working on a fix.  For others running into this, please ensure that you don't use the exclusive start shard id equal to the last shard of the stream.

When using ListShards you do want to use the next token for pagination, as that ensures the results will remain consistent with your initial call to ListShards.
