### ISSUE TITLE
S3 Upload issue, com.amazonaws.AmazonClientException: More data read (4567265) than expected (4561427)

### ISSUE THREAD

**Issue by prabha303** [aws/aws-sdk-java#1491]
We are observing something similar to #749 .

We upload a file to S3, wait until it's done. Then we open an URLConnection to this file via CloudFront, and upload it somewhere again, using it's InputStream.

In some cases, this fails with:

SdkClientException: More data read than expected: dataLength=457963; expectedLength=454759;

**Comment by varunnvs92** [comment]
What is the version of the SDK?
Can you share sample code?

**Comment by prabha303** [comment]
TransferUtility transferUtility = new TransferUtility(s3, context);
        if(!file.exists()) {
            Toast.makeText(context, "File Not Found!", Toast.LENGTH_SHORT).show();
            return;
        }
        ObjectMetadata metadata = new ObjectMetadata();
        try {
            FileInputStream sampleStream = new FileInputStream(file);
            byte[] byteArray = new byte[0];
            try {
                byteArray = IOUtils.toByteArray( sampleStream );
            } catch (IOException e) {
                e.printStackTrace();
            }
            Long contentLength = Long.valueOf(byteArray.length);
            metadata.setContentLength(contentLength + contentLength);
            metadata.setContentType("file/txt");
            try {
                sampleStream.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        s3.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());
        // 1. Enable bucket for Amazon S3 Transfer Acceleration.
        s3.setBucketAccelerateConfiguration(new SetBucketAccelerateConfigurationRequest(bucket,new BucketAccelerateConfiguration(BucketAccelerateStatus.Enabled)));
        // 2. Get the acceleration status of the bucket.
        String accelerateStatus = s3.getBucketAccelerateConfiguration(new GetBucketAccelerateConfigurationRequest(bucket)).getStatus();
        System.out.println("Acceleration status = " + accelerateStatus);
        //PutObjectRequest putObjectRequest = new PutObjectRequest(bucket, accessKey, inputStream, metadata);
        try {
            metadata.setContentType("file/txt");
        } catch (Exception e) {
            e.printStackTrace();
        }

        final TransferObserver observer = transferUtility.upload(bucket,ErrorFileName,file,metadata);
        observer.cleanTransferListener();
        observer.setTransferListener(new TransferListener()
        {
            @Override
            public void onStateChanged(int id, TransferState state)
            {
                if (state.COMPLETED.equals(observer.getState()))
                {
                    Toast.makeText(context, "File Upload Complete", Toast.LENGTH_SHORT).show();
                }
            }
            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal)
            {
                try
                {
                    long _bytesCurrent = bytesCurrent;
                    long _bytesTotal = bytesTotal;
                    float percentage =  ((float)_bytesCurrent /(float)_bytesTotal * 100);
                    Log.d("percentage","" +percentage);
                    String drvrid = SharedPref.getStringValue(LynkApplication.getAppContext(), DriverID);
                    Google_Analytics.onSetGAEventAction("FileUpload_"+drvrid,""+percentage,"-");
                    Utility.getInstance().DumpError("File_Dpwnload-- "+percentage);
                    //pb.setProgress((int) percentage);
                    //_status.setText(percentage + "%");
                }catch (Exception e)
                {
                    Utility.getInstance().DumpError("File_Dpwnload-Exception- "+e.getMessage());
                    e.printStackTrace();
                }
            }
            @Override
            public void onError(int id, Exception ex)
            {
                Log.d("percentage","" +ex.getMessage());
                String drvrid = SharedPref.getStringValue(LynkApplication.getAppContext(), DriverID);
                Google_Analytics.onSetGAEventAction(AppConstants.AnalyticsName.Errors +"_Fileupload_"+drvrid,""+ex.getMessage(),"");
                Utility.getInstance().DumpError("File_Dpwnload-Exception- "+id + "-"+ex.getMessage());
                Toast.makeText(context, "" + ex.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });

**Comment by prabha303** [comment]
compile 'com.amazonaws:aws-android-sdk-core:2.6.16'
    compile 'com.amazonaws:aws-android-sdk-s3:2.6.16'

**Comment by sanjaygadhiya** [comment]
I have already face smiler issue today.

**Comment by shorea** [comment]
@prabha303 we don't support the android SDK. Can you open an issue at https://github.com/aws/aws-sdk-android

**Comment by ppamorim** [comment]
I am getting this error on version 2.7.1.

**Comment by varunnvs92** [comment]
Our team doesn't own the mobile sdk. Please open a ticket in this [repo](https://github.com/aws/aws-sdk-android). Thank you.
