### ISSUE TITLE
Add CognitoCachingCredentialsProvider!

### ISSUE THREAD

**Issue by camhart** [aws/aws-sdk-java#1494]
Would really appreciate a CognitoCachingCredentialsProvider in this SDK.

**Comment by debora-ito** [comment]
Hi @camhart I believe you are referring to the `CognitoCachingCredentialsProvider` of the [Mobile SDK for Android](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/auth/CognitoCachingCredentialsProvider.html), right? 

Can you give us more details of your use case, and why this is needed?

**Comment by camhart** [comment]
For a desktop app.

**Comment by debora-ito** [comment]
@camhart the SDK team has reviewed the feature request list for V1 and decided not to implement this one, as they're concentrating efforts on V2 new features. It'll be considered for V2. 

I'll go ahead and close this one, feel free to reach out if you have further questions.
