### ISSUE TITLE
AmazonDynamoDBClient references inexistent constant

### ISSUE THREAD

**Issue by a-henning** [aws/aws-sdk-java#1495]
The changes made in this [commit](https://github.com/aws/aws-sdk-java/commit/54eea30a78ba3fdf4115968ca1f0c69a2cdb3943#diff-46b55b93b9714fec43410770e9c11035) result in the `AmazonDynamoDBClient` referencing `HandlerContextKey.SIGNING_REGION` (for example on line 282), but the `HandlerContextKey` class does not contain that value.
The result is the following error: `java.lang.NoSuchFieldError: SIGNING_REGION`.
This has been introduces since version `1.11.272`. The previous version is working.

**Comment by shorea** [comment]
Looks like you are using a new version of the dynamodb module and an older version of core. Make sure you have consistent versions on your classpath. See the BOM for an easier way to manage SDK dependencies.

https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/
