### ISSUE TITLE
S3 Transfer Manager bytesTransferred not being updated

### ISSUE THREAD

**Issue by stevorobs3** [aws/aws-sdk-java#1502]
I am using the S3 Transfer Manager within a Scala project. It seems like the bytesTransferred is not being updated. Please see below sample code:

 val amazonTransferManager : TransferManager = ???
 val copy = amazonTransferManager.copy(sourceBucket, sourceKey, destinationBucket, destinationKey)
 while (!copy.isDone) {
   Thread.sleep(100)
   println(s"Transfer progress ${copy.getProgress.getBytesTransferred} / ${copy.getProgress.getTotalBytesToTransfer}")
 }

The `getTotalBytesToTransfer` always returns the correct value but the `getBytesTransferred` always returns 0 even when the `TransferState` is Completed.

Is this expected behaviour or is there something I can do differently to ensure the `getBytesTransferred` method returns the expected result?

Thanks,

Steve

**Comment by millems** [comment]
It's unfortunate, but for `copy` calls, S3 doesn't return any progress indicator that can be used to supply you with the bytes transferred. This is because the copy is entirely service-side. We get the `totalBytesToTransfer` from the object metadata.

The `byteTransferred` only works for uploads and downloads.

**Comment by stevorobs3** [comment]
Ok thanks very much for clarifying this. Would a pr be welcome that documents this in code? Also, could we set the bytes transferred = totalbytestotransfer when the progress state changes to complete?

**Comment by millems** [comment]
A PR is always welcome, but we're willing to fix it ourselves. Let me know which you prefer.

I agree the documentation isn't clear and updating byte transferred once we finish the transfer makes sense.

**Comment by stevorobs3** [comment]
Great I will have a look at making that change now. Do you have any developer guidelines that I can read? I can't find any contributor guidelines.

**Comment by stevorobs3** [comment]
I have added PR #1510 in order to close this

**Comment by millems** [comment]
Merged the PR! It should be released to maven today or Monday.

**Comment by JoseMFranco** [comment]
Hi guys, so I'm wondering if the fix is working in the Java SDK. I used it with maven v1.11.340
According to the dates that fix should be there, right?
But I'm still getting 0 when I used the copy call and the bytesTransferred() method.

I would really appreciate your help. Thanks.
