### ISSUE TITLE
Throws error clientName must contain a scheme

### ISSUE THREAD

**Issue by cenxui** [aws/aws-sdk-java#1505]
The [document](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#CognitoUserPools-CreateUserPoolClient-request-ClientName) shows that we can use custom name. However, it will throw the error "clientName must contain a scheme".

 ```
        String userPoolId = "ap-northeast-1_XXXXXXXX"; //cens user
        String clientName = "clientName";

        AWSCognitoIdentityProvider provider = AWSCognitoIdentityProviderClientBuilder.defaultClient();

        CreateUserPoolClientRequest update = new CreateUserPoolClientRequest()
                .withUserPoolId(userPoolId)
                .withClientName(clientName)
                .withAllowedOAuthFlows(OAuthFlowType.Implicit)
                .withAllowedOAuthScopes("phone", "email", "openid");

        provider.createUserPoolClient(update);
```

**Comment by millems** [comment]
I agree the documentation doesn't give good detail on how the specify the `clientName`. I can forward on this feedback to the documentation writers, but the SDK issue queue isn't really one that can give you an answer on what the correct value would be.

Could you raise this question on the AWS forums for cognito, and cross-link the thread here so people can find it?

**Comment by cenxui** [comment]
The  AWS forums for cognito for this issue.  I hope that it could be helpful.
[AWS forums for cognito](https://forums.aws.amazon.com/thread.jspa?threadID=275922)

**Comment by millems** [comment]
Closing to keep this issue queue focused on the SDK.
