### ISSUE TITLE
S3Encryption: Unable to load credentials from service endpoint

### ISSUE THREAD

**Issue by amiivas** [aws/aws-sdk-java#1506]
Hi All,

There is a similar issue already listed over here for the same problem but no solution was provided as it was automatically resolved. But I am trying to get some encrypted connection parameter from s3 bucket in my sample Spring application. Here is the method I am using to run inside a container:
`public void encryptionOnly_KmsManagedKey() throws NoSuchAlgorithmException {
		 
		 //BasicAWSCredentials awsCreds = new BasicAWSCredentials("xxxxxxxxxx", "xxxxxxxx");
		 AmazonS3Encryption s3Encryption = AmazonS3EncryptionClientBuilder
	                .standard()
	                .withRegion(Regions.US_EAST_1)
	                //.withCredentials(new AWSStaticCredentialsProvider(awsCreds))
	                .withCredentials(new InstanceProfileCredentialsProvider(false))
	                .withCryptoConfiguration(new CryptoConfiguration(CryptoMode.AuthenticatedEncryption))
	                // Can either be Key ID or alias (prefixed with 'alias/')
	                .withEncryptionMaterials(new KMSEncryptionMaterialsProvider("alias/db-connstring"))
	                .build();

		 	//System.out.println(amazonS3.getObjectAsString(BUCKET_NAME, PROPERTIES_FILE_NON_ENC));
	        System.out.println(s3Encryption.getObjectAsString(BUCKET_NAME, PROPERTIES_FILE_ENC));
	        
	}'

I have created an IAM role and assigned to my ECS task [using Fargate] :
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject"
            ],
            "Sid": "Stmt1",
            "Resource": [
                "arn:aws:s3:::dev-web-s3/dev-webapp.properties"
            ],
            "Effect": "Allow"
        }
    ]
}`

But I am still getting unable to load credentials from service endpoint. The above method is in a spring controller and the applicationcontext is also initializing below
`<aws-context:context-credentials>
		<aws-context:instance-profile-credentials />
		<aws-context:simple-credentials
			access-key="xxxxxx" secret-key="xxxxxxxx" />
	</aws-context:context-credentials>`
You can see some redundancy in the approach but all I am  trying it to work. Thanks in advance for your help.

Thanks.
Amit

**Comment by millems** [comment]
What is the exception or error you're seeing?

**Comment by amiivas** [comment]
Please find attached the error trace:
[error_trace.txt](https://github.com/aws/aws-sdk-java/files/1811671/error_trace.txt)
Few noteworthy lines:
`4:59:30,870 WARN  [com.amazonaws.http.AmazonHttpClient] (http-/0.0.0.0:8080-1) SSL Certificate checking for endpoints has been explicitly disabled.
14:59:30,874 WARN  [com.amazonaws.http.AmazonHttpClient] (http-/0.0.0.0:8080-1) SSL Certificate checking for endpoints has been explicitly disabled.
14:59:30,876 ERROR [stderr] (http-/0.0.0.0:8080-1) com.amazonaws.SdkClientException: Unable to load credentials from service endpoint
14:59:30,876 ERROR [stderr] (http-/0.0.0.0:8080-1) 	at com.amazonaws.auth.EC2CredentialsFetcher.handleError(EC2CredentialsFetcher.java:180)
14:59:30,877 ERROR [stderr] (http-/0.0.0.0:8080-1) 	at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:159`

Thanks,
Amit

**Comment by millems** [comment]
For ECS, the [`ContainerCredentialsProvider`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/ContainerCredentialsProvider.html) is more appropriate.

Have you tried using the default credential chain (not specifying the credentials), which makes the application a bit more portable between ECS and other run-times? It checks all of the standard credentials providers, including ECS.

**Comment by amiivas** [comment]
I removed .withCredentials forcing to use default credentials chain, but I am getting Access denied. Please find the error_trace_without_cred.txt for the same. I will try with ContainerCredentialsProvider.
[error_trace_without_cred.txt](https://github.com/aws/aws-sdk-java/files/1816027/error_trace_without_cred.txt)

Thanks.

**Comment by millems** [comment]
It sounds like we're actually getting credentials loaded this time, which is an improvement. 

You could either test those credentials you got from CURL to see if your role is configured correctly, or you could enable debug-level logging and look for "Loading credentials". The default credentials chain will log the different credential providers it attempts and specifies "Unable to load credentials" if a particular method failed.

**Comment by amiivas** [comment]
I tried to use the credentials from the CURL command using BasicAWSCredentials options and got below error:
`com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 81CC7254BCA83D53), S3 Extended Request ID: of46B2ujyTG`

I am trying to get debug-level logging information but meanwhile any other issues which can be pointed out or alternative solution provided is much appreciated.

Thanks.

**Comment by amiivas** [comment]
Somehow debug level logging is not working for log4j2 configuration. Let me know if I can provide any other information.

**Comment by amiivas** [comment]
I found the solution. I need to add role in the encryption keys which I was using to decrypt the s3 file.
