### ISSUE TITLE
could AmazonS3EncryptionClient have a method to call putObject unencrypted?

### ISSUE THREAD

**Issue by c0b** [aws/aws-sdk-java#1507]
this is especially needed when need to crate a really empty object, sample code in hadoop-aws s3a filesystem driver's `createFakeDirectory` `createEmptyObject` which is doing so by create an empty object naming like `s3://bucket/path/dir/` this needs ensure it's really 0 bytes.

https://github.com/apache/hadoop/blob/trunk/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AFileSystem.java#L2738-L2768

this question is also:  how to create an really empty object (0 byte) when the s3client is an AmazonS3EncryptionClient instance?

```java
  private void createEmptyObject(final String objectName)
      throws IOException {
    final InputStream im = new InputStream() {
      @Override
      public int read() throws IOException {
        return -1;
      }
    };

    PutObjectRequest putObjectRequest = newPutObjectRequest(objectName,
        newObjectMetadata(0L),
        im);
    invoker.retry("PUT 0-byte object ", objectName,
         true,
        () -> putObjectDirect(putObjectRequest));
    incrementPutProgressStatistics(objectName, 0);
    instrumentation.directoryCreated();
  }
```

background is I am trying to continue this ticket make s3a driver's client side encryption working, am doing so by create s3client as an AmazonS3EncryptionClient instance (instead of regular AmazonS3Client) when given client side encryption command line switches, in most cases an AmazonS3EncryptionClient instance is working same way as a regular non-encrypted AmazonS3Client instance;
so far my code is almost done, just without the deep directory recursively distcp, in the case, above `createFakeDirectory` is trying to create a 0 byte file naming ends with a `/` but the AmazonS3EncryptionClient would create such a fake directory with 16 bytes instead, it's because of PKCS5Padding, making the directory named file has a real length, then all following files to be created under this directory would fail
https://issues.apache.org/jira/browse/HADOOP-13887

A workaround might be to comment out `createFakeDirectory` to not doing anything at all, I understand under a s3 bucket there is no need to create such a fake directory,  but I am not sure why the original hadoop-aws started this approach

**Comment by dagnir** [comment]
I can't comment on why `createFakeDirectory` was needed in the implementation but S3 itself doesn't really distinguish between directories and files/objects, only buckets and objects.

If you need to create empty objects, is having a second (non-encryption) s3 client around to do this an option?

**Comment by fernomac** [comment]
While S3 itself has no official concept of directories, plenty of tools (including the AWS console) treat it as though it does using the prefix and delimiter parameters on ListObjects.

This works fine as long as every directory eventually has a file in it, as S3 is only storing the files, not the directory structure. A zero-byte “file” whose name is the empty string (so “/some/directory/path/“) is the way these tools generally represent an empty directory, which I guess is maybe what’s going on here?

Yeah, two clients is likely the way to go. Or you could extend AmazonS3EncryptionClient and override putObject if the key ends in / and the content-length is zero, maybe?

**Comment by c0b** [comment]
> Yeah, two clients is likely the way to go. Or you could extend AmazonS3EncryptionClient and override putObject if the key ends in / and the content-length is zero, maybe?

this seems not possible because in Java the overridden method may call parent method by keyword `super` but direct parent only, from the CustomizedAmazonS3EncryptionClient it's unable to call grand-parent's putObject

```
AmazonS3Client

AmazonS3EncryptionClient

CustomizedAmazonS3EncryptionClient
```

> Use the keyword super within the overridden method in the child class to use the parent class method. You can only use the keyword within the overridden method though.

**Comment by debora-ito** [comment]
Hi @c0b,  the team has reviewed the feature requests list for V1 and decided to not implement this one since they are actively working on V2 new features. I'll go ahead and close this.

Please feel free to reach out if you have further questions.
