### ISSUE TITLE
NullPointerException on save in DynamoDB

### ISSUE THREAD

**Issue by vihung** [aws/aws-sdk-java#1512]
I have a `User` entity with an `id`

    @DynamoDBTable(tableName = "User")
    public class User {
      ...
      @DynamoDBHashKey(attributeName = "id")
      @DynamoDBAutoGeneratedKey
      public String getId() {
        ...
      }
      // other attributes, getters and setters omitted for simplicity
      ...
    }

and a `User` Table with key name `id` of type `S`

        final ArrayList<KeySchemaElement> keySchema = new ArrayList<KeySchemaElement>();
        keySchema.add(new KeySchemaElement().withAttributeName(pKeyName).withKeyType(KeyType.HASH));
        final ArrayList<AttributeDefinition> attributeDefinitions = new ArrayList<AttributeDefinition>();
        attributeDefinitions.add(new AttributeDefinition().withAttributeName(pKeyName).withAttributeType(pKeyType));
        final CreateTableRequest request = new CreateTableRequest().withTableName(pTableName).withKeySchema(keySchema)
                .withProvisionedThroughput(new ProvisionedThroughput().withReadCapacityUnits(10L).withWriteCapacityUnits(5L));
        request.setAttributeDefinitions(attributeDefinitions);

on doing a 'save' operation

    public <S extends User> S save(final S pUser) {
        mapper.save(pUser);
        return pUser;
    }

I get a NullPointerException from within the DBMapper code

    java.lang.NullPointerException: null
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doPutItem(DynamoDBMapper.java:883) ~[aws-java-sdk-dynamodb-1.11.295.jar!/:na]
    ...
    at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123) ~[aws-java-sdk-dynamodb-1.11.295.jar!/:na]
	at hello.user.repository.UserRepository.save(UserRepository.java:85) ~[classes!/:0.1.0]

My user object is not `null`, nor are any of its attributes other than the `id` which is autogenerated. Any idea what's going on?

Is the null id causing the exception? Is this not how I should expect `@DynamoDBAutoGeneratedKey` to work? According to the documentation and example at
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.Annotations.html#DynamoDBMapper.Annotations.DynamoDBAutoGeneratedKey
this should be how it works

**Comment by zoewangg** [comment]
DynamoDBAutoGeneratedKey is not likely to be the issue. I tried the example on the link you provided and it works for me. Below is the snippet I used.

```
@DynamoDBTable(tableName = "TestTable")
public class TestItem {

    private String id;
    private String payload;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "payload")
    public String getPayload() {
        return this.payload;
    }

    public void setPayload(String payload) {
        this.payload = payload;
    }
}
...
public void test() {
        CreateTableRequest request = new CreateTableRequest()
            .withTableName("TestTable")
            .withKeySchema(new KeySchemaElement("id", KeyType.HASH))
            .withAttributeDefinitions(new AttributeDefinition("id", ScalarAttributeType.S))
            .withProvisionedThroughput(new ProvisionedThroughput()
                                           .withReadCapacityUnits(1L)
                                           .withWriteCapacityUnits(1L));

        CreateTableResult table = client.createTable(request);
        System.out.println(table.getTableDescription());
        
        TestItem obj = new TestItem();
        obj.setPayload("hello world");

        mapper.save(obj);
        
        System.out.println("Object was saved with id " + obj.getId());
    }

```
From the stack trace you provided, it throw exception on [DynamoDBMapper.java:883](https://github.com/aws/aws-sdk-java/blob/1.11.295/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.java#L883), indicating `db` could be null. Can you check when you create `DynamoDBMapper`, are you passing `null` AmazonDynamoDB to it?

**Comment by vihung** [comment]
It is not because of a `null` attribute value.

The issue is one of timing, or rather, of sequencing. The NullPointerException occurs in `doPutItem(DynamoDBMapper.java:883)`. Looking at the source code, the line is

    883    return db.putItem(applyUserAgent(req));

this implies that `db` is null. 

`db` is a member variable

    191    private final AmazonDynamoDB db;

and it is initialised in the constructor

    public DynamoDBMapper(
            final AmazonDynamoDB dynamoDB,
            final DynamoDBMapperConfig config,
            final AttributeTransformer transformer,
            final AWSCredentialsProvider s3CredentialsProvider) {
        super(config);
        ...
        this.db = dynamoDB;
        ...
    }

So, `db` is the instance of `AmazonDynamoDB` client that _you_ pass when creating the mapper.

In a spring context, if the mapper is being constructed before the client has been provided an (`@Autowired`) value, then it will be null.

Ensure the right sequencing of creation of the `AmazonDynamoDB` client and the `DynamoDBMapper` and everything will be fine
