### ISSUE TITLE
When enabling metrics collection the latency logging is quite verbose by default.

### ISSUE THREAD

**Issue by nathanburrell** [aws/aws-sdk-java#1514]
When metrics collection are enabled, the latencyLogger in [AWSRequestMetricsFullSupport](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/AWSRequestMetricsFullSupport.java) logging to INFO level logs, verbose information about the request.

As this is purely trace information, should this be logged to a level lower than INFO, say DEBUG/TRACE?As to avoid polluting application logs.

**Comment by preflightsiren** [comment]
👍

**Comment by zoewangg** [comment]
Thanks for reporting! Code changes have been pushed and will go out in the next release.

**Comment by zoewangg** [comment]
Changes are out in [1.11.298](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#aws-sdk-for-java)
