### ISSUE TITLE
CompletableFuture support

### ISSUE THREAD

**Issue by noviceamateur** [aws/aws-sdk-java#1515]
Are completableFutures supported by async clients ? 
Right now the clients (I am using async SQS Client) sends a future and not completableFutures which makes chaining them difficult.

And are the async clients truly asnyc ? Do the clients actually make async http calls or they just wrap the response in futures ?

**Comment by millems** [comment]
Unfortunately returning `CompletableFuture` requires raising the minimum Java version from our current 1.6. The upcoming version of the SDK (currently in preview) requires Java 8 and uses `CompletableFuture` along with non-blocking IO: https://github.com/aws/aws-sdk-java-v2

The best we can suggest for now is to [adapt to a Guava `ListenableFuture`](https://stackoverflow.com/questions/30159229/how-to-convert-java-futurev-to-guava-listenablefuturev) if latency and extra threads aren't a concern, or use the [AsyncHandler](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/handlers/AsyncHandler.html) callbacks in our async methods to complete a `CompletableFuture` yourself.
