### ISSUE TITLE
Unable to list all loadbalancers other than classic one

### ISSUE THREAD

**Issue by ameerthehacker** [aws/aws-sdk-java#1516]
I have one elastic load balancer which is a network load balancer. When I do a describeLoadBalancers it shows only the classic load balancers and not network or HTTP load balancers.

**Comment by millems** [comment]
Unfortunately we're not the experts on ELB that would be able to answer your question. I'd suggest asking this question on the AWS forums for ELB or on stackoverflow where someone more knowledgeable can help.
