### ISSUE TITLE
Glue API very different from what the web page shows

### ISSUE THREAD

**Issue by Lempiraholio** [aws/aws-sdk-java#1517]
I've taken a look to the Glue API that the [web page](https://docs.aws.amazon.com/glue/latest/dg/glue-etl-scala-apis.html), and it looks very different from what this SDK has. For example, there is no GlueContext anywhere under the glue source code. Most of the example files use the "web page" SDK version so it's confusing whenever I try to write some code that the API's don't match

**Comment by zoewangg** [comment]
They are actually two different set of APIs. aws-sdk-java uses this [Glue web api](https://docs.aws.amazon.com/glue/latest/webapi/WebAPI_Welcome.html) and the web page you provided is for AWS Glue Scala Library and we don't own that library.

**Comment by zoewangg** [comment]
Closing the issue. Feel free to reopen if you have any questions.
