### ISSUE TITLE
Consumer pauses processing messages in between suddenly for some sometime

### ISSUE THREAD

**Issue by vikrantch-hk** [aws/aws-sdk-java#1522]
Hi team,
We are facing a weird issue where consumer did not pick messages for sometime although in getrecords is getting hit continuously and there are messages in stream , this happens for sometime after few restarts again system behaves properly not sure where is the problem, there is no exception in the logs. messages were put in stream around 11 am, they were processed around 11:30 am although getrecords method was getting called continuously.
Below are the logs for kinesis getRecords

amz-sdk-invocation-id:ae00d212-858a-0ec0-a0b1-e9d409cc79ba
amz-sdk-retry:0/0/500
content-length:251
content-type:application/x-amz-cbor-1.1
host:kinesis.ap-south-1.amazonaws.com
user-agent:aws-sdk-java/1.11.125 Linux/2.6.32-696.10.1.el6.x86_64 OpenJDK_64-Bit_Server_VM/25.161-b14/1.8.0_161
x-amz-date:20180323T054355Z
x-amz-target:Kinesis_20131202.GetRecords

amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target
73351c9a04a09b20456711d1e59173255c1e2898b2078615ea3892be9ddbe567"
2018-03-23 11:13:55.929 DEBUG 13601 --- [esis-consumer-1] com.amazonaws.auth.AWS4Signer            : AWS4 String to Sign: '"AWS4-HMAC-SHA256
20180323T054355Z
20180323/ap-south-1/kinesis/aws4_request
f9fd57041d5ef4d46dfb95eda89a16af855fdfac9f0e9e1a79de43da4b0ad795"
2018-03-23 11:13:55.972 DEBUG 13601 --- [esis-consumer-1] com.amazonaws.request                    : Received successful response: 200, AWS Request ID: db967db4-a143-4842-88b8-eb5c70051b80
2018-03-23 11:13:55.972 DEBUG 13601 --- [esis-consumer-1] com.amazonaws.requestId                  : x-amzn-RequestId: db967db4-a143-4842-88b8-eb5c70051b80
![get records](https://user-images.githubusercontent.com/34442831/37922208-9af70568-3149-11e8-989f-5df549ad2f0f.JPG)
![get records2](https://user-images.githubusercontent.com/34442831/37922210-9b32812e-3149-11e8-86b0-7cadd45b9a47.JPG)
![put records](https://user-images.githubusercontent.com/34442831/37922211-9b6cb74a-3149-11e8-93a4-e1df1b902b84.JPG)

**Comment by dagnir** [comment]
Hi I'm having trouble understanding what the issue is. Can you please explain your use case in more detail?

**Comment by vikrantch-hk** [comment]
@dagnir the issue is that although there are records in kinesis stream which you can see in putrrecords screenshot, but getrecords is not getting these messages for processing for quite some time please have a look on screen shots. After some time again these messages are getting processed perfectly without any lag. Is there any configuration becuase of which this lag is happening

**Comment by dagnir** [comment]
@vikrantch-hk Thanks for the explanation. Is the call to `getRecords` hanging or returning an empty list of records?

**Comment by vikrantch-hk** [comment]
@dagnir it's not hanging but returning empty list

**Comment by dagnir** [comment]
@vikrantch-hk From reading the [documentation](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html) for `GetRecords` it looks like this is expected behavior and the service could return multiple empty lists until it the iterator gets to a point in the shard that returns data.

> If there are no records available in the portion of the shard that the iterator points to, GetRecords returns an empty list. It might take multiple calls to get to a portion of the shard that contains records.

**Comment by shorea** [comment]
Per @dagnir comments this is expected behavior for all paginated APIs. The rationale being that the service index might hit a large area of tombstoned or deleted records and cannot deliver a single record within a timely manner. If the service provides a pagination token in the response you must assume there are more records and keep making requests until that pagination token is null and there are no more records.
