### ISSUE TITLE
Feature Request: Modify Aurora DB Engine Version

### ISSUE THREAD

**Issue by c1phr** [aws/aws-sdk-java#1523]
The API appears to allow modifying the DB Engine Version of an Aurora cluster (https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html), but this functionality is missing from the SDK.

For non-Aurora engines, the capability is there to modify the engine version as part of the `ModifyDBInstance` call, so it seems like it should be there for DB Cluster as well.

Proposed addition: `EngineVersion` is added as a field on the `ModifyDBClusterRequest` object to be passed to `ModifyDBCluster`.

**Comment by dagnir** [comment]
Hi @c1phr thanks for reporting this. We are currently investigating this with the service and hope to get an update out soon!

**Comment by c1phr** [comment]
Thanks @dagnir, please let me know if there's any other info or use-case examples that I can provide to help out.

**Comment by dagnir** [comment]
Quick update to say that we'll be fixing this upstream and the member should get added in a release soon.

**Comment by zoewangg** [comment]
EngineVersion parameter is now available in the latest release [1.11.314](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111314-2018-04-19).
