### ISSUE TITLE
kinesis sample in AWS-JAVA-SDK v1.11.306

### ISSUE THREAD

**Issue by hysmky** [aws/aws-sdk-java#1532]
Dear SDK Developer,
I just started to use AWS SDK and saw sample code for Kinesis (although this sample is not mentioned in the developer guide).
I set up the credentials and other details however the code simply does not work because
com.amazonaws.services.kinesis.clientlibrary... does not exist! The IDE (IntelliJ in my case) does not recognize the symbol clientlibrary and in fact such a node does not exits. More specifically, the code tries to import the following and none of them exist in the released API:
import com.amazonaws.services.kinesis.clientlibrary.interfaces.IRecordProcessorFactory;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitialPositionInStream;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibConfiguration;
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker;

Is there a workaround to make the sample code work or shall I wait a bug fix in the SDK?

Thanks and the best,

**Comment by dagnir** [comment]
Hi @hysmky, the Kinesis Client Library is not included with the AWS SDK for Java, it is a separate project hosted here: https://github.com/awslabs/amazon-kinesis-client 

Depending on how your project is setup, you need to add it to your project's classpath, e.g. by adding a Maven dependency.

If you're looking at the samples in `src/samples/AmazonKinesis`, using `ant` to run the samples will automatically fetch the JAR for you: https://github.com/aws/aws-sdk-java/blob/c2332d7a34c9e678391ae1e41fa05165c5233354/src/samples/AmazonKinesis/build.xml#L54

**Comment by hysmky** [comment]
Thanks for the fast response and directions. I see that build.xml is not working by default under my IDE!
