### ISSUE TITLE
Unable to execute HTTP request: connect timed out

### ISSUE THREAD

**Issue by sudhir05** [aws/aws-sdk-java#1534]
Hi All,
I am going through strange error, i am running spring boot locally and connecting to AWS Dynamodb, it returns below exception:
EVENT>{"@timestamp":"2018-04-03T17:57:33.173+10:00","@version":1,"message":"Error while creating connection with DynamoDB","logger_name":"com.DynamoDBRepository","thread_name":"http-nio-8080-exec-1","level":"ERROR","level_value":40000,"name":"xyz","apiVersion":"1","application":"xyz","version":"1.6.37","type":"ERROR"}
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to dynamodb.ap-southeast-2.amazonaws.com:443 [dynamodb.ap-southeast-2.amazonaws.com/52.94.13.132] failed: connect timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)

However, this error do not appear when i run my code through public internet.

**Comment by spfink** [comment]
What do you mean by "when i run my code through public internet."?

**Comment by sudhir05** [comment]
I am behind client proxy and connecting Internet by bypassing through cntlm http://localhost:3128, however i do not have such proxy when i connect dynamoDB through public internet.

**Comment by spfink** [comment]
Have you configured your proxy through the SDK ClientConfiguration class?

**Comment by sudhir05** [comment]
No, i haven't. In the ~.aws/credentialsi do have aws key and secret key. What and how i can configure.

**Comment by spfink** [comment]
You can configure the proxy through ClientConfiguration:

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html

You can set the proxy host, password, port, domain, authentication scheme and workstation.

**Comment by Aruun** [comment]
Getting the same issue when accessing dynamodb from the Glue job.  Any solution for this issue?  Thanks in advance :)
