### ISSUE TITLE
Need a suggestion on upgrading to the latest version of AWS SDK

### ISSUE THREAD

**Issue by bhaskar20001** [aws/aws-sdk-java#1536]
We are using AWS SDK 1.11.44 in our project. And we use most of the services provided by AWS cloud.

I want an opinion about upgrading my project to use latest version of AWS SDK available for Java.

What are the benefits towards my project I can expect by upgrading to the latest/recent SDK?
The benefits can be in any manner which should improve overall performance, stability and cost reduction for my project.

Thanks,
Bhaskar

**Comment by spfink** [comment]
What do you mean by latest version? 1.11.307 or the new v2 SDK:

https://github.com/aws/aws-sdk-java-v2

If it's just the latest version within 1.11.x then it would come down to the features and bug fixes from our changelog:

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md

If none of the features or bug fixes from later versions are needed for you, then you don't need to upgrade.

If you are talking about moving to 2.0 then there are many reasons to upgrade but not until we go GA. Much better performance, non-blocking IO, Java 8 as a base, pagination, etc.

**Comment by bhaskar20001** [comment]
@spfink Thanks for the response.
Sorry for the confusion, I am referring to 1.11.307. Will go through the change log.

And about 2.0, I see that as an interesting one. We can wait for that as we are already on Java8. May I ask you about tentative timelines for GA of v2.

**Comment by spfink** [comment]
We don't yet have a date for a timeline for GA of v2 but we should be able to provide more updates soon!
