### ISSUE TITLE
Does AmazonS3Client.generatePresignedUrl support to create a signed url for CompleteMultipartUploadResult

### ISSUE THREAD

**Issue by zsxwing** [aws/aws-sdk-java#1537]
I used `AmazonS3Client.generatePresignedUrl` to create a signed url for `CompleteMultipartUploadResult`, but when I used this url, it failed. Here is a part of the error message:

```xml
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
```

I saw the doc here doesn't include the `POST` method: https://github.com/aws/aws-sdk-java/blob/1.11.308/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.java#L42

Is the above error because `CompleteMultipartUploadResult` must be a `POST` request?

**Comment by spfink** [comment]
Are you specifying post when generating the presigned url? Can you provide a code sample?

**Comment by shorea** [comment]
A note to Java SDK team, see TT0146774011.

**Comment by varunnvs92** [comment]
This is not currently supported in the SDK. After discussion with S3 team, it seems there are complexities to support this feature. We don't have plans to support this feature in v1 unless requested by many customers. You can certainly open a feature request in [2.0 SDK](https://github.com/aws/aws-sdk-java-v2). We can prioritize it when implementing TransferManager, S3 high level utility.

**Comment by ade90036** [comment]
@varunnvs92 could you elaborate on why this cannot be achieved?

@shorea, is that a cryptic: "I told you so" :D:D

Apart from technical limitations or won't fix it, what is the underline problem?

I guess the POST request validation routine (AWS server-side) is looking for additional data which is not provided by `AmazonS3Client.generatePresignedUrl`

My application has the requirement to allow file upload for ~= 10GB files and using strong security in mind and leaving AWS credentials present on the client machine it simply won't do it.

FYI, other AWS S3 SKDs provide this functionality, like PHP and JS.

This feature is not even on the roadmap of aws-java-sdk 2.0, so i suspect that it will be a while before this is provided. 

Therefore i would prefer get informed of the issue and code a workaround. 

Regards

Andrea
