### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: SIGNING_REGION

### ISSUE THREAD

**Issue by roygeorgeP** [aws/aws-sdk-java#1540]
All of the clientbuilder classes seem to be erroring out with the error
Exception in thread "main" java.lang.NoSuchFieldError: SIGNING_REGION

in the following version 
<version>1.11.307</version>

**Comment by spfink** [comment]
Are you using Maven? Can you print out your dependency tree? Sounds like you are using mixed versions of the SDK.

**Comment by roygeorgeP** [comment]
In my pom if I have just this...
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-bom</artifactId>
    <version>1.11.308</version>
    <type>pom</type>
</dependency>

Then none of these imports resolve

import com.amazonaws.services.rekognition.AmazonRekognition;
import com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder;
import com.amazonaws.services.rekognition.model.AmazonRekognitionException;
import com.amazonaws.services.rekognition.model.DetectLabelsRequest;
import com.amazonaws.services.rekognition.model.DetectLabelsResult;
import com.amazonaws.services.rekognition.model.DetectTextRequest;
import com.amazonaws.services.rekognition.model.DetectTextResult;
import com.amazonaws.services.rekognition.model.Image;
import com.amazonaws.services.rekognition.model.Label;
import com.amazonaws.services.rekognition.model.S3Object;
import com.amazonaws.services.rekognition.model.TextDetection;

Then I add this in to make it compile...
 <dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-rekognition</artifactId>
	<version>1.11.307</version>
</dependency>
because version 308 does not compile.
And then it compiles.
But now when I run my code I get the same error...

Exception in thread "main" java.lang.NoSuchFieldError: SIGNING_REGION
	at com.amazonaws.services.rekognition.AmazonRekognitionClient.executeDetectLabels(AmazonRekognitionClient.java:1022)
	at com.amazonaws.services.rekognition.AmazonRekognitionClient.detectLabels(AmazonRekognitionClient.java:1004)
	at com.tfs.aws.image.DetectImage.detectLabel(DetectImage.java:60)
	at com.tfs.aws.image.DetectImage.main(DetectImage.java:41)

**Comment by spfink** [comment]
Can you provide your actual pom? Or at least the actual dependencies section?

**Comment by roygeorgeP** [comment]
`	<dependencyManagement>
	    <dependencies>
		<dependency>
		    <groupId>com.amazonaws</groupId>
		    <artifactId>aws-java-sdk-bom</artifactId>
		    <version>1.11.308</version>
		    <type>pom</type>
		</dependency>
	    </dependencies>
	  </dependencyManagement>
	<dependencies>
	    <dependency>
	      <groupId>com.google.apis</groupId>
	      <artifactId>google-api-services-vision</artifactId>
	      <version>v1-rev374-1.23.0</version>
	    </dependency>
		<dependency>
	    <groupId>com.fasterxml.jackson.core</groupId>
	    <artifactId>jackson-core</artifactId>
	    <version>2.8.6</version>
	</dependency>
	
		
	<dependency>
	    <groupId>com.fasterxml.jackson.core</groupId>
	    <artifactId>jackson-annotations</artifactId>
	    <version>2.8.6</version>
	</dependency>
	<dependency>
	<groupId>com.fasterxml.jackson.core</groupId>
	        <artifactId>jackson-databind</artifactId>
	        <version>2.8.6</version>
	</dependency>
		<dependency>
    		<groupId>com.amazonaws</groupId>
    		<artifactId>aws-java-sdk-rekognition</artifactId>
    		<version>1.11.307</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-utils</artifactId>
			<version>3.0.8</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
`

**Comment by roygeorgeP** [comment]
[pom.txt](https://github.com/aws/aws-sdk-java/files/1881508/pom.txt)

**Comment by spfink** [comment]
Can you add the import scope for the bom?

**Comment by roygeorgeP** [comment]
Added this `<scope>import</scope>`  Still same error

**Comment by spfink** [comment]
Hmm, still not sure why you are getting this issue. I have the following pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.finks</groupId>
    <artifactId>test-project</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.11.308</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.google.apis</groupId>
            <artifactId>google-api-services-vision</artifactId>
            <version>v1-rev374-1.23.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.8.6</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.8.6</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.8.6</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-rekognition</artifactId>
        </dependency>
        <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-utils</artifactId>
            <version>3.0.8</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.8.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

And then the following code:

```
public class Test {

    public static void main(String[] args) {
        AmazonRekognition client = AmazonRekognitionClientBuilder.standard().withRegion("us-east-1").build();

        client.detectLabels(new DetectLabelsRequest().withImage(new Image().withS3Object(new S3Object().withBucket("sam.fink").withName("image.png")))).getLabels().forEach(r -> System.out.println(r.getName()));
    }
}
```

And it works just fine...

**Comment by spfink** [comment]
What's your output if you run

```
mvn dependency:tree
```

**Comment by roygeorgeP** [comment]
`
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AwsRekognition 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ AwsRekognition ---
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.pom
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.pom
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.pom
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/maven-artifact/2.2.0/maven-artifact-2.2.0.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-artifact/2.2.0/maven-artifact-2.2.0.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-artifact/2.2.0/maven-artifact-2.2.0.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.jar
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.jar
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.jar
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.jar
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.jar
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.jar
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.jar
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.jar
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar (0 B at 0.0 KB/sec)
[INFO] com.tfs.aws:AwsRekognition:jar:1.0-SNAPSHOT
[INFO] +- com.google.apis:google-api-services-vision:jar:v1-rev374-1.23.0:compile
[INFO] |  \- com.google.api-client:google-api-client:jar:1.23.0:compile
[INFO] |     +- com.google.oauth-client:google-oauth-client:jar:1.23.0:compile
[INFO] |     |  +- com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO] |     |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |     +- com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile
[INFO] |     \- com.google.guava:guava-jdk5:jar:17.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.8.6:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.6:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.6:compile
[INFO] +- com.amazonaws:aws-java-sdk-rekognition:jar:1.11.308:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.308:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.308:compile
[INFO] +- org.codehaus.plexus:plexus-utils:jar:3.0.8:compile
[INFO] \- junit:junit:jar:4.8.2:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.456 s
[INFO] Finished at: 2018-04-05T17:29:09-04:00
[INFO] Final Memory: 18M/375M
[INFO] ------------------------------------------------------------------------
`

**Comment by roygeorgeP** [comment]
> [INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AwsRekognition 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ AwsRekognition ---
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.pom
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.pom
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.pom
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-settings/2.2.0/maven-settings-2.2.0.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/maven-artifact/2.2.0/maven-artifact-2.2.0.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-artifact/2.2.0/maven-artifact-2.2.0.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/maven-artifact/2.2.0/maven-artifact-2.2.0.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.pom
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.pom
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.pom (0 B at 0.0 KB/sec)
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.jar
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.jar
Downloading: https://maven.oracle.com/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.jar
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
Downloading: https://maven.oracle.com/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.jar
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.jar
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.jar
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.jar
Downloading: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.jar
Downloading: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-archiver/2.3/plexus-archiver-2.3.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-utils/3.0.9/plexus-utils-3.0.9.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-dependency-analyzer/1.4/maven-dependency-analyzer-1.4.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/codehaus/plexus/plexus-io/2.0.6/plexus-io-2.0.6.jar (0 B at 0.0 KB/sec)
Downloaded: http://repo.spring.io/libs-snapshot/org/apache/maven/shared/maven-invoker/2.0.11/maven-invoker-2.0.11.jar (0 B at 0.0 KB/sec)
[INFO] com.tfs.aws:AwsRekognition:jar:1.0-SNAPSHOT
[INFO] +- com.google.apis:google-api-services-vision:jar:v1-rev374-1.23.0:compile
[INFO] |  \- com.google.api-client:google-api-client:jar:1.23.0:compile
[INFO] |     +- com.google.oauth-client:google-oauth-client:jar:1.23.0:compile
[INFO] |     |  +- com.google.http-client:google-http-client:jar:1.23.0:compile
[INFO] |     |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |     +- com.google.http-client:google-http-client-jackson2:jar:1.23.0:compile
[INFO] |     \- com.google.guava:guava-jdk5:jar:17.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.8.6:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.6:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.6:compile
[INFO] +- com.amazonaws:aws-java-sdk-rekognition:jar:1.11.308:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.308:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.308:compile
[INFO] +- org.codehaus.plexus:plexus-utils:jar:3.0.8:compile
[INFO] \- junit:junit:jar:4.8.2:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.456 s
[INFO] Finished at: 2018-04-05T17:29:09-04:00
[INFO] Final Memory: 18M/375M
[INFO] ------------------------------------------------------------------------

**Comment by spfink** [comment]
Hmm, that looks 100% correct and should work. You're bringing in 308 of Rekognition and the core module. 

Let me try and bring in someone else from my side on this cause I'm not sure what to look into next.

**Comment by spfink** [comment]
Are you running this locally? Is that dependency tree output from the same host that is running the code?

**Comment by roygeorgeP** [comment]
same host

**Comment by roygeorgeP** [comment]
Yes locally on a windows box.

**Comment by spfink** [comment]
Can you add this to your code and provide the output:

```
System.out.println(HandlerContextKey.class.getProtectionDomain().getCodeSource().getLocation().getPath());
```

**Comment by roygeorgeP** [comment]
aha - there is the error
/C:/Users/p00rg/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-java-sdk-core/1.11.128/1c508333875e5015942840861f6aca77bcfe8b0d/aws-java-sdk-core-1.11.128.jar

**Comment by spfink** [comment]
Nice, makes sense now why this was happening.

So presumably clearing your dependency cache will prevent the issue from occurring unless you have something else that keeps pulling that version in.

**Comment by spfink** [comment]
Glad we were able to help!

**Comment by sushant-wadhone-mpf** [comment]
I am also facing the same issue, but this didn't worked for me

**Comment by umangs9** [comment]
When i run following code :
`System.out.println(HandlerContextKey.class.getProtectionDomain().getCodeSource().getLocation().getPath());`

It shows this output:
`/C:/Users/admin/.m2/repository/com/amazonaws/aws-java-sdk-core/1.11.251/aws-java-sdk-core-1.11.251.jar`

What does that mean.?
