### ISSUE TITLE
support for custom collections of transfers in TransferManager

### ISSUE THREAD

**Issue by timotheev** [aws/aws-sdk-java#1541]
Hi,

I want to use the AWS java SDK to programmatically transfer files back and forth files from local machines, EC2 machines and S3.

On one hand, ``TransferManager`` seems the dedicated and "ready to use" tool do so, on the other hand the  usage cases it currently supports for multiple transfers are, to my understanding, quite restrictive and hard to customize to my needs:

In my case the **local file system and the S3 cloud storage keys do not mirror each-other**. So I need local file path/names to be different from S3 keys. I am also looking for **non blocking method to upload or download of multiple files in a batch and to follow the global progress and state change** (a very useful feature, exactly like what ``MultipleFileUpload`` / ``MultipleFileDownload`` interfaces currently offer, but not restricted to a given directory and without enforcing keys/paths to be identical)!

Is this possible in the current state of the sdk (might have missed it...*) ?

If not, I suggest to **expose a method for uploading  custom collection of files with a custom collection of keys and the other way round**. This might be achieved by supporting two additional methods:
1/ takes a ``List<PutObjectRequest>`` as argument and returns a ``UploadCollection`` instance (that simply extends from ``MultipleFileTransfer<Upload>``),
2/ takes a ``List<GetObjectRequest>`` and target files ``List<File>``  as arguments and returns a ``DownloadCollection`` instance (that simply extends from ``MultipleFileTransfer<Download>``)
(all other arguments can be similar to what existing methods offer for multiple files transfer, such as ``ObjectTaggingProvider`` etc...)

I think it would be much appreciated by developers and users !
bests.

(* I have looked at the currently available public interfaces and classes: I tried to obtain the desired feature from a collection ``List<Download>`` or ``List<Upload>`` could not find a tool meant for developer to create and pass a listener for changes of the global state of the multiple transfer (``TransferStateChangeListener`` interface comment specify "Not intended to be consumed externally.")... Also looking at ``TransferManager`` code to see whether it gives the possibility to extend existing interfaces/classes for such feature, it does not look like there is a clean path to hook up something from there... )

**Comment by timotheev** [comment]
Working further on this, I  realized that callback events passed to `ProgressListener` are sufficients for what I need -progress basically event includes the state changes info- so indeed `TransferStateChangeListener` is not needed by the user.
So indeed, the following is a good starting point to do the job:
```
for (int i = 0; i < paths.size(); i++) {
File f = new File(paths.get(i));
if (f.isFile()) {
	transferSize += f.length();
	String key = keys.get(i);
	uploads.add((Upload) transferManager.upload(
	new PutObjectRequest(bucketName, key, f), s3ProgressListenerChain));
}
```
However, returning time per example for this loop seems gets slower and slower as the string array `paths` size grows and this slow return is annoying for an asynchronous method... MultipleFileUpload seems to use `CountDownLatch` to control thread launch/execution, I guess this affect how fast `TransferManager` returns...

**Comment by debora-ito** [comment]
Hey @timotheev the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the TransferManager refactor in V2, see the referenced issue above. I'll go ahead and close this.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
