### ISSUE TITLE
Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed

### ISSUE THREAD

**Issue by nashid** [aws/aws-sdk-java#1542]
I am getting this error once I am making a `putObject` request. 

It's not clear to me what is causing this issue. What is the root cause for this error and what would be the strategy to avoid this?

Secondly, how to make this a retryable so that `aws-sdk` retries while having this error. I am already setting the error retry which does not seem to have any effect.

```
com.amazonaws.services.s3.model.AmazonS3Exception: Your socket connection to the 
server was not read from or written to within the timeout period. Idle connections 
will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout
```

Code:
```
  val s3ClientConfig = new ClientConfiguration().withMaxErrorRetry(3)
    .withConnectionTimeout(60 * 1000)
    .withSocketTimeout(60 * 1000)
```

In a similar issue (https://github.com/aws/aws-sdk-js/issues/281), it was mentioned this happens when the provided Content-Length is larger than the number of bytes sent, causing S3 to wait for you to send a specified number of bytes then timeout while waiting. 

However, for my case, I am not specifying any content length and I am simply invoking with:

`PutObjectRequest(String bucketName, String key, File file)`

**Comment by spfink** [comment]
Are you seeing this consistently or intermittently? Can you provide a code sample for where you are calling PutObjectRequest?

**Comment by nashid** [comment]
This is an intermittent error which we are observing recently and its making our `aws batch jobs` error-prone and not reliable. 

```
 val s3ClientConfig = new ClientConfiguration().withMaxErrorRetry(3)
    .withConnectionTimeout(60 * 1000)
    .withSocketTimeout(60 * 1000)

 val amazonS3Client: AmazonS3 = AmazonS3ClientBuilder
    .standard()
    .withRegion("us-east-1")
    .withCredentials(new AWSStaticCredentialsProvider(credentials))
    .withClientConfiguration(s3ClientConfig).build

val objectRequest = new PutObjectRequest(s3config.s3Bucket, destination.path, file)

amazonS3Client.putObject(objectRequest)
```

**Comment by nashid** [comment]
@spfink do you need anything else from me on this?

**Comment by shorea** [comment]
Are these files being modified or appended to while you upload? What's the rate at which you upload files?

**Comment by nashid** [comment]
@shorea we prepare the files locally before uploading - so these files are not modified/appended while we are uploading.

The rate at which we upload is actually very low - at best ~10 upload per hour.

**Comment by shorea** [comment]
Closing issue, feel free to reopen if you need further assistance from the SDK team.

**Comment by ngbalk** [comment]
The OP's questions `Secondly, how to make this a retryable so that aws-sdk retries while having this error. I am already setting the error retry which does not seem to have any effect.` I think is still a good one that was not answered - how can we make this socket timeout `400` error code retry-able?
