### ISSUE TITLE
Couchbase to Dynamodb migration using javasdk

### ISSUE THREAD

**Issue by sudhir05** [aws/aws-sdk-java#1543]
We are maintaining our database using NoSQL couchbase and migrating to DynamoDB.

 - Currently everything is stored in one JSON file.
 - As of now there are more than 15 attributes based on which json is scanned.
 - Below is sample of JSON we have, i kept it small for better understanding
 - 

    {
          "createdAt": "2018-02-15T07:19:44.731Z",
          "id": "345",
          "myDetailsLog": [
            {
              "e": "TRUE",
              "status": "CCCC",
              "updatedAt": "2018-02-15T07:23:55.989Z"
            }
          ],
          "logiID": "123",
          "vnumber": "3",
          "attr": {
            "pdetails": [
              {
                "iId": "98",
                "pCode": "1",
                "quantity": "1",
                "pCodeType": "1-TC"
              }
            ],
            "rDetails": {
              "cId": "Frank",
              "ctUUID": "abc-efg",
              "rTpye": "New",
              "oId": "0099",
              "cName": "Frede Smith",
              "correlationId": "2930-23u-2397-230",
              "cNumber": "28320923",
              "email": "test@test.com",
              "addressId": "fdlkas"
            },
            "sDetails": {
              "aLeave": "N",
              "dTime": "2017-09-11T17:00:00.000Z",
              "pType": "Mon-Fri Business Hours",
              "ddTime": "2017-09-11T08:00:00.000Z",
              "dis": "TBD"
            }
          },
          "type": "Close",
          "subStatus": "Clear",
          "status": "Notclear",
          "updatedAt": "2018-02-15T07:19:44.731Z"
        }
        

 - If we use DynamodDB and put everything into one Table, i can use maximum of 5 secondary index, however we have almost 15 attributes on which we query the JSON. For example we query json/table on cId, rType, oId, rId, logiID.

 - Is it possible to break the JSON into different block and store into different table of dynamodb, but complexity is to again join the tables for generating the response. Not sure, how joining will happen here.

**Comment by spfink** [comment]
Can you clarify exactly what you are asking?

**Comment by sudhir05** [comment]
My question was how the above mentioned json will migrate to DynamoDB where we should be be able to search/query on all the attributes present on json file.

**Comment by spfink** [comment]
The AWS DynamoDB forum may be a better place for this question then:

https://forums.aws.amazon.com/forum.jspa?forumID=131

That forum may allow you to discuss with experts in DynamoDB. Be aware though that for questions like this that are more system design related, providing an answer may not be easy without knowing more on your system requirements.
