### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connect to s3.amazonaws.com:443 [s3.amazonaws.com/52.216.101.53] failed: connect timed out

### ISSUE THREAD

**Issue by vipulshivnani** [aws/aws-sdk-java#1546]
<img width="1099" alt="screen shot 2018-04-09 at 3 01 15 am" src="https://user-images.githubusercontent.com/220078/38493272-7324449e-3ba6-11e8-8154-4fc821a9cbc1.png">
i am usinf aws java sdk to get instance metadata info. The API is failing with this error in screenshot.

com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connect to s3.amazonaws.com:443 [s3.amazonaws.com/52.216.101.53] failed: connect timed out

**Comment by spfink** [comment]
Are you using a proxy? Is it correctly configured? Have you tried increasing your connection timeout?

**Comment by shorea** [comment]
Any update? Are you still experiencing this problem?

**Comment by vipulshivnani** [comment]
@shorea  looks like there is a proxy being used at the location we are running the aws sdk calls. We are using instancecredentialsprovider to get temporary credentials for IAM role. I am following this https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/section-client-configuration.html ,
 
@spfink  thanks for the suggestion.  If there is a good sample of how to add proxy information to instancecredentialsprovider I can add that.

**Comment by shorea** [comment]
@vipulshivnani you should be able to use system properties, https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html

**Comment by varunnvs92** [comment]
Feel free to reopen if you still have the issue.

**Comment by Prathameshshewale07** [comment]
same error I got in Linux ??what to do??How to solve it???
