### ISSUE TITLE
cannot retrieve a URL with s3-accelerate endpoint using s3Client.getResourceUrl

### ISSUE THREAD

**Issue by thunderdoor** [aws/aws-sdk-java#1550]
I use s3Client.getResourceUrl to get the URL of an object in a S3 bucket with transfer acceleration enabled.

I expect to derive a result like the following:
https://bucket.s3-accelerate.amazonaws.com/file

However, I derives a result using the standard endpoint rather than s3-accelerate endpoint:
https://bucket.s3.ap-northeast-1.amazonaws.com/file

Could you add a function like getAccelerateResourceUrl so that I can derive the URL with s3-accelerate endpoint?

**Comment by debora-ito** [comment]
The SDK team has reviewed the feature request list for V1 and this one looks like a great candidate for a community PR, which we’ll help merge in and support.
