### ISSUE TITLE
Secrets Manager not allowing both String and Binary Secret

### ISSUE THREAD

**Issue by castortech** [aws/aws-sdk-java#1556]
Trying to create a secret via the Java SDK and got this error:

> The request had invalid params: You can’t specify both a binary secret value and a string secret value in the same secret. (Service: AWSSecretsManager; Status Code: 400; Error Code: InvalidParameterException; 

The documentation states that:

> Either SecretString , SecretBinary , or both must have a value. They cannot both be empty.
> This SecretBinary value is stored separately from the SecretString , but the two parameters jointly share a maximum size limit.

As per the documentation it is clearly allowed to have both a string and a binary secret as long as you don't exceed the maximum size.

**Comment by zoewangg** [comment]
Thanks for reporting! Looks like it's a documentation issue and I'll reach out to the service team to correct it.

**Comment by bisdavid** [comment]
This is correct - I missed this in my docs. I'll correct it and resubmit to the SDK teams.

**Comment by zoewangg** [comment]
Documentations have been updated.
