### ISSUE TITLE
Error with DynamoDB QuerySpec and FilterExpressions

### ISSUE THREAD

**Issue by angrychewie** [aws/aws-sdk-java#1557]
Hi,

I have a DynamoDB Table consisting of a @DynamoDBHashKey(attributeName="YearAndWeek"), an associated @DynamoDBRangeKey(attributeName="PostedDateTime"), and 2 global secondary indexes @DynamoDBIndexHashKey(globalSecondaryIndexName = "Origin", attributeName = "Origin") and @DynamoDBIndexHashKey(globalSecondaryIndexName = "Operation", attributeName = "Operation").

Within the DynamoDB website console, I can make a query where I set the partition key string to equal a certain value, the sort key string to be between 2 dates, and 2 additional filters that correspond to the 2 global secondary indexes. Performing this query gives me the desired expected results. However, when I attempt to perform the same query through a lambda function written in java, I get the following error: "Error: Value provided in ExpressionAttributeValues unused in expressions: keys: {:v_origin} (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: #####)".

Here is the code snippet I have for the query:

QuerySpec spec = new QuerySpec()
							.withKeyConditionExpression("YearAndWeek = :v_yw and PostedDateTime between :v_start_dt and :v_end_dt")
							.withFilterExpression("Origin = :v_origin")
							.withFilterExpression("Operation = :v_operation")
							.withValueMap(new ValueMap()
									.withString(":v_yw", yearAndWeek)
									.withString(":v_start_dt", changingDateConv)
									.withString(":v_end_dt", endDateConv)
									.withString(":v_origin", Origin.TIMESHEET.toString())
									.withString(":v_operation", Operation.CLOCK_OUT.toString()))
							.withConsistentRead(true);
					ItemCollection<QueryOutcome> items = table.query(spec);

What is interesting is that when I make a different query, where either the Origin or Operation is the only filter, it works.

Is there something incorrect with my QuerySpec statement? I don't understand how the DynamoDB web console can perform the query correctly, but utilizing the DynamoDB Java API gives a different result.

The only similar case to mine that I could find is from here: https://github.com/awspilot/dynamodb-oop/issues/29 but this person was not using the Java API.

**Comment by angrychewie** [comment]
@zoewangg Hi Zoe, would you be able to elaborate on whether this is a bug in the Java sdk or if there is something incorrect with my QuerySpec statement? I'm confused as to why the same query parameters work in the web console, but not here...

**Comment by zoewangg** [comment]
Hi @angrychewie, two `withFilterExpression` were provided and that could cause the error. Have you tried `.withFilterExpression("Operation = :v_operation and Origin = : v_origin")`?

**Comment by angrychewie** [comment]
That worked! Thank you! However, I'm not sure why it should throw an error when using multiple separate withFilterExpression() calls. It seems like it would be useful to be able to chain separate calls especially if someone were to build complex/arbitrary queue logic

**Comment by varunnvs92** [comment]
Looks like the original issue is solved. Resolving the issue. Let us know if you have any other questions.
