### ISSUE TITLE
S3 CopyObjectRequest no-arg constructor for builder-style methods

### ISSUE THREAD

**Issue by rdbatch02** [aws/aws-sdk-java#1558]
It seems that nearly all of the SDK Request objects have a no-argument constructor so that the various builder-style methods can be called on them. For example:

`ListObjectsRequest().withBucketName(sourceBucket)`

It seems that `CopyObjectRequest()` does not have a no-argument constructor, though it does appear to have the various .with*() and .set*() methods that would seem to imply that it should follow the same pattern. [CopyObjectRequest Docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/CopyObjectRequest.html)

Could a no-argument constructor be added for `CopyObjectRequest()` so that it can have its fields passed in with the more readable builder syntax?

Expected result:

```
CopyObjectRequest()
    .withSourceBucketName("sourceBucket")
    .withSourceKey("sourceKey")
    .withDestinationBucketName("destinationBucket")
    .withDestinationKey("destKey")
```

**Comment by debora-ito** [comment]
Closing via #2173.
