### ISSUE TITLE
httpclient jar conflicts when submitting job via oozie

### ISSUE THREAD

**Issue by Goleo8** [aws/aws-sdk-java#1560]
Hi,

Currently I deployed an emr with latest version 5.13.0, with both oozie and spark. However the oozie share lib load /user/oozie/share/lib/***/spark/httpclient-4.3.6.jar. The old version of httpclient. When submitting a spark job with oozie, there will an error thrown. 

Caused by: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.

I found the aws-sdk-java 1.11 uses httpclient-4.5.3. I guess this is the root cause. Is there anyway to avoid this error? Thanks in advance.

**Comment by varunnvs92** [comment]
See related issue #1356 
I hope this helps.
