### ISSUE TITLE
AWS Java SDK For AWS Direct Connect for Java 1.7 support

### ISSUE THREAD

**Issue by vahith** [aws/aws-sdk-java#1561]
Hi Team
G'DAY currently we are using Java version 1.7  in our projects but when we trying to use AWS Java SDK For AWS Direct Connect it's compitable with our ve

**Comment by vahith** [comment]
Hi Team
G'DAY currently we are using Java version 1.7 in our projects but when we trying to use AWS Java SDK For AWS Direct Connect it's not compatible with our version  because Aws compatible with 1.8..could you suggest how to use..

**Comment by shorea** [comment]
We support Java6 and higher. What problems are you having?

**Comment by varunnvs92** [comment]
Doesn't seem to be an issue as SDK 1.11.x supports JDK 6 and above. Resolving the ticket. Fell free to reopen if you have more questions.
