### ISSUE TITLE
Respecting Java Proxy Environment Variables Should Be Optional

### ISSUE THREAD

**Issue by mschappel-r7** [aws/aws-sdk-java#1563]
Parts of our application can be configured to use a proxy separately from each other. Some of those rely on the Java environment variables being set, but our AWS interfacing code configures proxy use through the `ClientConfiguration` class. PR https://github.com/aws/aws-sdk-java/pull/596 forces us to use a proxy when the environment variables are set even if we've intentionally excluded proxy configuration from our `ClientConfiguration`s. Can use of the environment variables be made optional?

**Comment by varunnvs92** [comment]
You need some option to ignore all proxy configurations. Is that right? Not sure if I can get to it this week. If you can send us a PR, we would be happy to merge it in.
