### ISSUE TITLE
aws-sdk-core, aws-sdk-lambda and jackson dependencies

### ISSUE THREAD

**Issue by karthikpromontory** [aws/aws-sdk-java#1564]
Hi,
The latest version of aws-sdk-core(1.11.315) and aws-sdk-lambda (1.11.316) are said to have the latest version of jackson-databind and jackson-core. However, our dependency report after upgrade still show 
[AWS-jackson.txt](https://github.com/aws/aws-sdk-java/files/1943655/AWS-jackson.txt)
2.6.7 for jackson. Is there something else I should be upgrading to get the jackson dependencies to their latest build?
I have attached the dependency tree (removed dependencies not directly related to jackson)
Thx
Karthik

**Comment by varunnvs92** [comment]
> The latest version of ... are said to have the latest version of jackson-databind and jackson-core.

Where is it mentioned that latest version are being used? If it is in the official docs, we want to fix it.

Current version of the SDK supports JDK 6 and above. But Jackson 2.7+ requires minimum JDK 7. So we are limited to using max 2.6.x version of Jackson to not break customers running on JDK 6.

**Comment by karthikpromontory** [comment]
HI,
I see that in https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core/1.11.315 it provide two columns for version and updates. I assumed the first column is for the version used prior to the 315 update, and the updates column is for the version being used by the updated sdk-core. If that understanding is wrong, and it just means that there are updates to the existing version of the library used, then please close this thread, and sorry for the confusion.

**Comment by varunnvs92** [comment]
"version" column indicates the version used by SDK. "Updates" column indicates the latest version available in maven for that dependency.
For jackson-databind, version is 2.6.7.1 (used by SDK) and latest available is (2.9.5). As mentioned earlier, its not possible for us to upgrade to 2.7+ as SDK still supports JDK 6.
