### ISSUE TITLE
Externalized functionaName value for LambdaFunction

### ISSUE THREAD

**Issue by mengjiann** [aws/aws-sdk-java#1568]
May I know if it is possible to load the functionName value for com.amazonaws.services.lambda.invoke.LambdaFunction from external source like properties file?

**application.properties**
```
...
lambda.function.name=anotherLambdaFunction
...
```

**LambdaApi.class**
```

    @LambdaFunction(functionName = "${lambda.function.name}")
    Void triggerAnotherLambdaFunction(Void empty);

```

**Comment by varunnvs92** [comment]
The values in annotations should be compile time constants. So I don't think its possible to load the value at runtime.

**Comment by mengjiann** [comment]
But, the @Value annotation from Spring allows injecting values into field from the properties file. So maybe an enhancement to the @LambdaFunction implementation?

**Comment by mengjiann** [comment]
@varunnvs92 , I was checking on the source code for lambda sdk. I discovered that we are allowed to customise our own lambdaFunctionNameResolver and supply to the LambdaInvokerFactory builder when building the LambdaFunctionAPI. This should solve my concern.
