### ISSUE TITLE
Regions should have proper, easily understandable 'Region Names'

### ISSUE THREAD

**Issue by zenfenan** [aws/aws-sdk-java#1570]
The Enum `Regions` right now have just the code. It would be better to also include a proper, easy to understand name. For ex: `us-west-1` should also have the proper name `US West (N. California)`. This may sound trivial but I think this might come in handy in many situations for third party softwares and/or even AWS SDKs.

**Comment by varunnvs92** [comment]
Region codes are preferred as they follow specific pattern and are used in the endpoint which customers can easily related to. It would be tough to standardize enum constants based on names. Do you think its useful if we add the names in the comments in the class? 
What is your use case for preferring names over standard codes?

**Comment by zenfenan** [comment]
I dint mean to replace code with the name. What I actually meant was, *along with* the code, it needs to have a corresponding proper readable name as well so that how the code gets read using `getName`, the proper region name can be read from something like `getReadableName` or a function with a better name. Ideally `getName` should return `us-west-1` and `getReadableName` should return `US West (N. California)`

**Comment by millems** [comment]
This should be straight-forward to implement, since the data is included in the [endpoints.json file](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json).
