### ISSUE TITLE
Missing credentials in config in local dev environment

### ISSUE THREAD

**Issue by warmjaijai** [aws/aws-sdk-java#1571]
My colleague successfully perform the following code showing the table without setting the credentials in local environment, but when i conduct it it shows such error on my local machine. Please help.

Please find my codes below:

Controller:
```
        AWS.config.update({
            region: 'localhost',
            endpoint: new AWS.Endpoint('http://localhost:8008'),
        })
        var params = {
            TableName: 'history',
            KeySchema: [{
                AttributeName: 'b_id',
                KeyType: 'HASH'
            },{
                AttributeName: 'e_id',
                KeyType: 'RANGE'
            }],
            AttributeDefinitions: [{
                AttributeName: 'b_id',
                AttributeType: 'S',
            },{
                AttributeName: 'e_id',
                AttributeType: 'N',
            }],
            ProvisionedThroughput: { // required provisioned throughput for the table
                ReadCapacityUnits: 1, 
                WriteCapacityUnits: 1, 
            },
        }
        response.implicitEnd = false
        AWS.query('history',params, function(err, data){
            if(err) console.log(err)
            else  response.json(data)
        })
```

Error Message:
> { Error: connect EHOSTUNREACH 169.254.169.254:80 - Local ()
>     at Object._errnoException (util.js:1022:11)
>     at _exceptionWithHostPort (util.js:1044:20)
>     at internalConnect (net.js:971:16)
>     at net.js:1065:9
>     at _combinedTickCallback (internal/process/next_tick.js:131:7)
>     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
>   message: 'Missing credentials in config',
>   code: 'CredentialsError',
>   errno: 'EHOSTUNREACH',
>   syscall: 'connect',
>   address: '169.254.169.254',
>   port: 80,
>   time: 2018-04-30T04:34:53.218Z,
>   originalError: 
>    { message: 'Could not load credentials from any providers',
>      code: 'CredentialsError',
>      errno: 'EHOSTUNREACH',
>      syscall: 'connect',
>      address: '169.254.169.254',
>      port: 80,
>      time: 2018-04-30T04:34:53.218Z,
>      originalError: 
>       { code: 'EHOSTUNREACH',
>         errno: 'EHOSTUNREACH',
>         syscall: 'connect',
>         address: '169.254.169.254',
>         port: 80,
>         message: 'connect EHOSTUNREACH 169.254.169.254:80 - Local ()' } } }

**Comment by varunnvs92** [comment]
> message: 'Could not load credentials from any providers'

This indicates SDK could not load credentials from any of the [default credential providers](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html).

You should set the credentials in atleast one of the methods provided in the above link. I suspect your colleague has credentials in his local machine. You can verify it by having a simple test to load each of the credential providers and printing the access keys. This is just for your local testing and do not post any of the sensitive data here.

**Comment by millems** [comment]
Feel free to reopen if this hasn't resolved your question.
