### ISSUE TITLE
unable to import com.amazonaws.services.s3.AmazonS3ClientBuilder on android

### ISSUE THREAD

**Issue by Boukhechba** [aws/aws-sdk-java#1573]
I am unable to import com.amazonaws.services.s3.AmazonS3ClientBuilder on android studio. Current Java version is 1.8 and current android API version is: 26 .
I have also checked for potential conflict between dependencies, but it doesn't seem to have a link with this issue. Here are my dependencies : 

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.0.0-alpha1'
    compile 'com.google.android.gms:play-services-wearable:11.0.4'
    compile 'com.google.android.gms:play-services-maps:11.0.4'
    compile 'com.google.android.gms:play-services:11.0.4'

    compile ('com.amazonaws:aws-android-sdk-mobile-client:2.6.7@aar'){ transitive = true; }
    compile 'com.amazonaws:aws-android-sdk-core:2.6.+'
    compile 'com.amazonaws:aws-android-sdk-s3:2.6.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.6.+';
   
} 
```

**Comment by millems** [comment]
They would be able to help you more over at https://github.com/aws/aws-sdk-android/issues . This is the non-android Java SDK repository.
