### ISSUE TITLE
Question about generated endpoint when creating a signer

### ISSUE THREAD

**Issue by jihoonson** [aws/aws-sdk-java#1575]
When AmazonS3Client creates a signer, it checks that the given bucket should be cached. If it is and the bucket is already cached, [it generates an endpoint instead of using the one specified in the request](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3610-L3613). Here is the code snippet.

```
                String region = bucketRegionCache.get(bucketName);
                if (region != null) {
                     // If cache contains the region for the bucket, create an endpoint for the region and
                     // update the request with that endpoint.
                     request.addHandlerContext(HandlerContextKey.SIGNING_REGION, region);
                     resolveRequestEndpoint(request, bucketName, key, RuntimeHttpUtils.toUri(RegionUtils.getRegion(region).getServiceEndpoint(S3_SERVICE_NAME), clientConfiguration));
                     return updateSigV4SignerWithRegion((AWSS3V4Signer) signer, region);
                }
```

I wonder why it generates a new endpoint rather than using the specified one and why it does only when the cache hits. Would anyone please elaborate more on this?

**Comment by jihoonson** [comment]
Thanks @varunnvs92. I have a follow-up question.

The above code was executed when I enabled `forceGlobalBucketAccessEnabled` (because [bucketRegionShouldBeCached() returns true](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L4426)) even though I set both an endpoint and a signing region. Would you please let me know why the configured signing region is ignored in this case?

**Comment by varunnvs92** [comment]
Enabling globalBucketAccess allows the client to interact with any region. This is a complicated case and **we don't recommend customers enable this option unless necessary.** With this option enabled, even though a single client can talk to multiple regions, SDK still needs to sign the request with the correct bucket region. 

For example, you create a S3 client with "us-west-2" endpoint and "us-west-2" signing region, then you decide to talk to a bucket in "eu-central-1" with this option enabled. Now SDK needs a way to find the correct region for signing each request as the client can be interacting with any region. **From SDK perspective, this is similar to noExplicitRegionProvided case as we can't just rely on the region/endpoint provided on the client.** So we use the bucket cache (first) or extra head bucket (if cache has no info) to find the signing region. In addition, there will be performance effect with globalBucketAccess as we do extra HeadBucket calls each time a new bucket is encountered.

**Comment by jihoonson** [comment]
@varunnvs92 thank you for the detailed explanation. Now I understand this behavior better!
