### ISSUE TITLE
S3 Common Prefixes Incorrectly Returns Empty List

### ISSUE THREAD

**Issue by rbuck** [aws/aws-sdk-java#1576]
The Java code is below. But when I try to list the top-level "folders" in an S3 bucket, I get an empty list. Using the Ruby client I've confirmed there are indeed files, and that similarly I can list "folders". It's only for the Java client that this operation fails.

Incidentally, this code works for every other customer who's buckets are scanned, and even for this customer who other buckets, those other buckets may be scanned. It's the case that only this one bucket cannot be scanned.

Again, I thought it would be a permissions issue, but when I bring up a Ruby IRB, it can indeed read the bucket folders without issue.

Has anyone ever run into an issue where the listing is empty when factually the bucket has (lots of) content? Any hints as how to diagnose and work around the issue?

For the code below, entry is simply a hash-like object in Java.

```
            CredentialsProvider provider = new CredentialsProvider();
            AWSCredentials awsCredentials = provider.getCredentials(entry.getValue().getCustomerId(), entry.getValue().getAccountId());

            s3 = AmazonS3ClientBuilder.standard()
                    .withRegion(entry.getValue().getRegion())
                    .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                    .build();

            final ListObjectsRequest listObjectRequest = new ListObjectsRequest()
                    .withPrefix(prefix)
                    .withDelimiter("/")
                    .withBucketName(entry.getValue().getBucket());
            ObjectListing objectListing = s3.listObjects(listObjectRequest);
            for (final S3ObjectSummary objectSummary : objectListing.getObjectSummaries()) {
                final String key = objectSummary.getKey();
                System.out.println(key);
            }
```

**Comment by millems** [comment]
Can you enable debug-level wire logging for this request? It'll show what S3 is actually reporting.

**Comment by dagnir** [comment]
Closing this due to no response. Please feel free to reopen if you continue to experience this issue.
