### ISSUE TITLE
S3 'the specified key does not exist' error should report the key

### ISSUE THREAD

**Issue by mmroden** [aws/aws-sdk-java#1578]
Hi all,

I keep getting errors like the following using the java SDK:

    Invocation of init method failed; nested exception is     
    com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. 
    (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: <ID>), 
    S3 Extended Request ID: <longer ID>

That error message should contain the key that was used in the request, especially since I can use the same key to download the file using the aws cli.

**Comment by millems** [comment]
Unfortunately this message is controlled by the S3 service. Could you reach out to the S3 team via the AWS forums or AWS support to request this feature?
