### ISSUE TITLE
Working of S3 file download

### ISSUE THREAD

**Issue by noviceamateur** [aws/aws-sdk-java#1581]
To download a file from S3 using java SDK, we need to do the following -> Note- Multipart download is off.

S3Object s3Object = s3.getObject(getObjectRequest);
S3ObjectInputStream s3ObjectInputStream = s3Object.getObjectContent();
//Write to a file from this stream
When we make a getObject call, the SDK does a GET call on that object. This call returns just the headers of the response.

When we actually start reading from the s3ObjectInputStream, we get the response body. But this all is one REST call.

So, I was confused why the call returned only the headers first. And how did S3 know when to start sending in the response body?

We are making only one call, so how are we notifying S3 that we have now started reading from the s3ObjectInputStream. Where is the actual file stored till we read it from the stream ?

**Comment by dagnir** [comment]
Gonna go ahead and close this since it looks like the original questions were answered by @millems. Please feel free to reopen if you have further questions.
