### ISSUE TITLE
Amazon S3 internal Retry policy

### ISSUE THREAD

**Issue by shakeelashaik05** [aws/aws-sdk-java#1582]
Hi,

I want to know what kind of retry policy Amazon S3 will use for retry on internal errors. In my use-case, I used S3 and below is the behaviour on retry.

I haven't used any retry mechanism on S3.

But I observed that for "connect timed out" and for "Read timed out", internally S3 retried for 11 times.

In S3 connector config, no details about max retry.

Is there any information/Documentation on retry for internal errors of S3??

**Comment by dagnir** [comment]
Sorry one correction, DDB has different default settings from other services: https://github.com/aws/aws-sdk-java/blob/b51f416a5d2c68dd150d17031a39121a96cf416a/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L118-L122

**Comment by shakeelashaik05** [comment]
Thanks for reply.
The observed retries - 11 are only for a single request.
I am using S3 connector in Mulesoft Integration, and it internally uses Rest API.
I don't see any details about thr retries in S3 connector of Mule.
Is there any way to find the behaviour of S3 on retry for 11 times??

**Comment by dagnir** [comment]
Gotcha. I'm not familiar with the MuleSoft or their products, but I found this from the [release notes for their S3 connector](https://docs.mulesoft.com/release-notes/amazon-s3-connector-release-notes):

> 

    Support for Retry Policy - The connector will perform a maximum of 10 retries when a request fails due to server-side throttling or dropped connection.

10 retries plus the original request sounds consistent with the 11 requests you're observing.

It sounds like MuleSoft is using a custom retry policy for their S3 client.

**Comment by dagnir** [comment]
Gonna go ahead and close this since there's no issue with the SDK. Please feel free to reopen if you have further questions.
