### ISSUE TITLE
Questions about AmazonS3Client#putObject

### ISSUE THREAD

**Issue by AlexITC** [aws/aws-sdk-java#1592]
When calling the `AmazonS3Client#putObject` method, we can get back an exception or a `PutObjectResult`.

I wonder if there is a possibility that we get a `PutObjectResult` even if the object wasn't uploaded successfully, I haven't been able to find that in the documentation or in the source.

Also, while looking to this piece [AmazonS3Client.java#L1764](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1764), I see that the `contentMd5` might be discarded, I wonder if the conditional should be `if (contentMd5 == null)` instead:

```java
...
        String contentMd5 = metadata.getContentMD5();
        if (md5DigestStream != null) {
            contentMd5 = Base64.encodeAsString(md5DigestStream.getMd5Digest());
        }
...
```

Thanks!

**Comment by AlexITC** [comment]
The scenario that I have is that I get back a `PutObjectResult` that I'm discarding but after that, I have tried to retrieve the object and it isn't there. That's why I ask if there is something I need to validate in the  `PutObjectResult` to ensure the object was created successfully.

As the method throws exceptions in certain scenarios, I was expecting it to throw an exception when the object wasn't created.

**Comment by spfink** [comment]
Ah, that clarifies things. I'm not aware of any case where a PutObjectResult is returned and the object was not uploaded. Can you provide a code sample of how you are uploading? If it's easy to replicate can you provide debug logs of a successful put object request that resulted in the object not being available.

**Comment by AlexITC** [comment]
Sadly I haven't been able to replicate it, it is something that has occurred just one time in around a year.

The code was basically taken from the Java SDK examples, the `PutObjectResult` is being discarded.

One thing that I read somewhere was that it might be useful to check the `ETag` from the result against a MD5 to verify the content wasn't corrupted.

Thanks.

**Comment by spfink** [comment]
Are you using encryption? If not, and assuming you didn't disable MD5 checking, the SDK will automatically check the ETag on uploads so you don't need to do it yourself.

**Comment by AlexITC** [comment]
Interesting, no, I'm not using encryption, is kind of weird.

The other possibility would be that the file was uploaded and deleted just after that, because the application checked in less than 5 seconds after it was uploaded and we have no automatic deletion.

**Comment by spfink** [comment]
Hmm, not sure what could be the issue here then. If you are getting back a PutObjectResult then the file should be there. You could look into CloudTrail to see if any other API calls are being made that would mess with the object. Additionally, verify that you have permission to access the uploaded object. Are you using the same credentials to put and then get?

**Comment by AlexITC** [comment]
I'll check about CloudTrail, on the credentials, they should be ok because from all the actions, just this one failed, other actions did the same operations and we checked the bucket for the object existence with the same credentials.

I'll investigate to see if someone else did the mess.

Thanks.

**Comment by AlexITC** [comment]
Sadly, we don't have enough information to know if the file was uploaded and removed or it wasn't uploaded at all.

At last,, while looking to this piece AmazonS3Client.java#L1764, I see that the contentMd5 might be discarded, I wonder if the conditional should be if (contentMd5 == null) instead:

...
        String contentMd5 = metadata.getContentMD5();
        if (md5DigestStream != null) {
            contentMd5 = Base64.encodeAsString(md5DigestStream.getMd5Digest());
        }
...

**Comment by shorea** [comment]
@AlexITC  while the code may be somewhat confusing, I believe it is correct. md5DigestStream will only be non-null when content-md5 is null (i.e. not provided by customer). 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1739

Do you need anything further from the SDK team?

**Comment by AlexITC** [comment]
That's all, thanks!
