### ISSUE TITLE
Update CreateReplicationJobRequest

### ISSUE THREAD

**Issue by ovkhasch** [aws/aws-sdk-java#1593]
CreateReplicationJobRequest doesn't include the fields notificationEmails and numberOfRecentAmisToKeep used by the AWS console. Please, make these fields available for API users as well.

**Comment by spfink** [comment]
I've submitted a feature request to the service team about this. Will let you know when we hear back.

**Comment by shorea** [comment]
Closing this issue. If we receive any updates we will communicate that here but we'd like to keep our issues SDK specific as much as possible.
