### ISSUE TITLE
Methods and parameters in Java SDK should be annotated for nullability

### ISSUE THREAD

**Issue by xenomachina** [aws/aws-sdk-java#1598]
Methods and parameters in Java SDK should be annotated for nullability (ie: either `@Nullable` or `@NotNull`). This would help Java programmers who use static analysis tools, and would be a huge help to Kotlin programmers using the Java SDK.

Nullability annotations in Java unfortunately suffer from a bit of a [too many standards](https://xkcd.com/927/) problem, but JetBrains has [a list of nullability annotations supported by the Kotlin compiler as well as other advice that should help with migrating to using nullability annotations](https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations).

**Comment by shorea** [comment]
This would be a good addition. At this point I'm not sure if it's worth the effort for V1 but we will consider it for V2 (https://github.com/aws/aws-sdk-java-v2)

**Comment by xenomachina** [comment]
Ok, I filed [issue 505](https://github.com/aws/aws-sdk-java-v2/issues/505) with V2.

**Comment by debora-ito** [comment]
Hi @xenomachina, the team has reviewed the feature request list for V1 and decided to not implement this one because they are concentrating their efforts on V2 new features. So I'll go ahead and close this in V1. 

Please feel free to reach out if you have further questions or comments.
