### ISSUE TITLE
Cloudfront Signed URL from Salesforce APEX

### ISSUE THREAD

**Issue by vamsigkrishna** [aws/aws-sdk-java#1601]
We are getting 403 Access Denied error from Cloudfront when accessing an S3 resource via cloudfront using signed url. We raised a case with AWS 5080768621 and they suggested I log a ticket here. All the additional details with the issue is detailed in the case.

I've used PKCS1, PKCS8 and DER formats and all of the formats are giving the same error.

These are 2 approaches we have tried and both of them are giving the same error with all 3 formats of the private key.
1. https://salesforce.stackexchange.com/questions/131159/how-to-generate-aws-cloudfront-signed-url-in-apex
2. https://developer.salesforce.com/forums/?id=906F0000000kHKFIA2

The Actual code snippet we used is in this discussion thread
https://salesforce.stackexchange.com/questions/219252/aws-cloudfront-signed-url-from-apex

any help in getting this resolved will be useful for us to go live with our project which is being blocked now due to this issue.

**Comment by zoewangg** [comment]
Just to be clear, the presigned url generated from AWS Java SDK worked but not the code snippets in the link your provided, correct?

Are you able to compare the generated URLs from both approaches to see which parts are different?

**Comment by zoewangg** [comment]
I see. Not sure how much we can help in this case since this is more like an Apex question.

Here are some links of how we calculate signatures:
- https://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html
- https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L425

**Comment by zoewangg** [comment]
This might also be helpful:

https://github.com/aws/aws-sdk-java/blob/6927b2eda56da6b0737aff14d1d02775011c4547/aws-java-sdk-cloudfront/src/main/java/com/amazonaws/services/cloudfront/CloudFrontUrlSigner.java#L93-L102

**Comment by zoewangg** [comment]
Closing the issue. Feel free to reopen if you have any other questions.
