### ISSUE TITLE
 TransferManagerUtils.isDownloadParallelizable returning false for Downloads

### ISSUE THREAD

**Issue by patricksculley** [aws/aws-sdk-java#1605]
Parallel downloads are not working because x-amz-mp-parts-count not being set in ObjectMetadata during GetObjectMetadataRequest. 

Use the following sample code to verify:

```
        GetObjectMetadataRequest getObjectMetadataRequest =
        RequestCopyUtils.createGetObjectMetadataRequestFrom(getObjectRequest).withPartNumber(1);
      ObjectMetadata meta = s3.getObjectMetadata(getObjectMetadataRequest);
      System.out.println(meta.getPartCount());
```

You can notice that CPU cores are underutilized when running top. This results in poor download speed for Java clients since downloads are being defaulted to single threaded.

**Comment by zoewangg** [comment]
- What Java SDK version are you using?
- When you uploaded the object, did you use single `putObject` or multipart upload API? 

`getPartCount` will only return part count if the object has more than 1 part. So it will not work for any objects uploaded using `putObject` api.

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#getPartCount--

**Comment by patricksculley** [comment]
I am using Java version 1.7.80 but you are correct, the parallelization/missing header issue is related to files that were not uploaded as a multipart upload originally.

I guess it wasn't clear the way the file was uploaded was a dependency. Is there any workaround to do parallel downloads otherwise?

**Comment by zoewangg** [comment]
Unfortunately no. Parallelizable downloading is not supported if any of the following condition is true
- if the client is an instance of AmazonS3EncryptionClient
- if the download request is a ranged request
- if the object was originally uploaded to Amazon S3 as a single object.

https://github.com/aws/aws-sdk-java/blob/92b557495323ca35719ba7a95e0283267275c9e2/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/TransferManagerUtils.java#L202-L212

**Comment by zoewangg** [comment]
Closing the issue. Feel free to reopen it if you have any other questions.
