### ISSUE TITLE
How to get EC2 instance type?

### ISSUE THREAD

**Issue by flyingl** [aws/aws-sdk-java#1606]
I want get all EC2 instance type using aws-java-sdk-ec2, but not found this action.Which action is get instance type and flavors? Thanks!

**Comment by zoewangg** [comment]
similar issue with https://github.com/aws/aws-sdk-java/issues/1607 

Does `DescribeInstances` work for you? 

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2.html#describeInstances--

**Comment by zoewangg** [comment]
Replied to you on gitter as well.

Unfortunately there’s no API available to retrieve all EC2 instance types. But if you want to get instance type information of all your instances, you can use `DescribeInstances` API.

**Comment by lshmouse** [comment]
+1 for this problem.
The aws cli provided a command to get all instance-types offerings by:
```
 aws ec2 describe-instance-type-offerings --location-type "availability-zone" --filters "Name=location,Values=ap-southeast-1b"
```
See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-discovery.html

**Comment by debora-ito** [comment]
@lshmouse the DescribeInstanceTypeOfferings operation is also available in the SDK:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2.html#describeInstanceTypeOfferings-com.amazonaws.services.ec2.model.DescribeInstanceTypeOfferingsRequest-
