### ISSUE TITLE
How to get the instance type?

### ISSUE THREAD

**Issue by accumulatepig** [aws/aws-sdk-java#1607]
I wanna get the instance type by aws-java-sdk-ec2 , but not find the sdk .Does any sdk to support the method or any other way to get the instance type? thanks

**Comment by zoewangg** [comment]
Does `DescribeInstances` work for you? 

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2.html#describeInstances--

**Comment by zoewangg** [comment]
Closing due to duplication of #1606 Feel free to reopen if you have any other questions.
