### ISSUE TITLE
Support sessionToken method to AWSCredentials

### ISSUE THREAD

**Issue by azihsoyn** [aws/aws-sdk-java#1608]
Hi, I'm using S3 as private maven repository.

For authentication, I need to pass sessionToken to gradle [AwsCredentials](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/credentials/AwsCredentials.java).

Currently, [AWSCredentails](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSCredentials.java) is not supported getSessionToken.

I want to use sessionToken like this.

like this
```
maven {
        url 's3://<private maven bucket>'
        credentials(AwsCredentials) {
            def credentials = new AWSCredentialsProviderChain(
                    // for local
                    new ProfileCredentialsProvider(rootProject.getProperties().get('aws.profileName', 'default')),
                    // for circleci
                    new EnvironmentVariableCredentialsProvider()
            ).getCredentials()
            accessKey credentials.getAWSAccessKeyId()
            secretKey credentials.getAWSSecretKey()
            sessionToken credentials.getAWSSecretKey() // does not work now
        }
    }
```

Thanks.

**Comment by shorea** [comment]
Can you try to see if its an instance of BasicSessionCredentials?

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/EnvironmentVariableCredentialsProvider.java#L59

**Comment by azihsoyn** [comment]
Great! I'll try it next Monday!

**Comment by azihsoyn** [comment]
Hi, I found my intent was wrong.

EnvironmentVariableCredentialsProvider works fine.
But I want to use sessionToken from config file for local.

https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html
`aws_session_token`

Like this [PR](https://github.com/aws/aws-sdk-java/pull/1137).

**Comment by millems** [comment]
To clarify, you want to set the access key and secret key from environment variables, but the session token from the configuration file? Or using all of it from the configuration file is fine (`ProfileCredentialsProvider`)?

**Comment by millems** [comment]
Let us know if the `ProfileCredentialsProvider` doesn't suit your needs or whether you have any questions about using it!

**Comment by azihsoyn** [comment]
In my company, developers are using https://github.com/physera/onelogin-aws-cli for security.
onelogin-aws-cli saves `aws_access_key_id`, `aws_secret_access_key` and `aws_session_token` to config file (`~/.aws/credentials` ).

For local Android app build, ProfileCredentialsProvider is used to access private s3 maven repository.

But cannot retrieve sessionToken from ProfileCredentialsProvider.

**Comment by millems** [comment]
A few questions:
1. Are you having this issue with the mobile android SDK or the Java SDK? The android SDK is not maintained in this repository.
2. Can you provide an isolated code sample that can reproduce this issue?

**Comment by azihsoyn** [comment]
1. for android build.gradle, but using java SDK.
2. here.
```
import com.amazonaws.auth.AWSCredentialsProviderChain
import com.amazonaws.auth.EnvironmentVariableCredentialsProvider
import com.amazonaws.auth.profile.ProfileCredentialsProvider

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.amazonaws:aws-java-sdk-core:1.11.341'
    }
}

allprojects {
    repositories {
        maven { url "http://dl.bintray.com/populov/maven" }
        jcenter()
        mavenCentral()
        google()
        maven {
            url 's3://my-company-private-maven-repository'
            credentials(AwsCredentials) {
                def credentials = new AWSCredentialsProviderChain(
                        // for local
                        new ProfileCredentialsProvider(rootProject.getProperties().get('aws.profileName', 'default'))
                ).getCredentials()
                accessKey credentials.getAWSAccessKeyId()
                secretKey credentials.getAWSSecretKey()
                if (credentials instanceof AWSSessionCredentials) { 
                    sessionToken credentials.sessionToken
                }
            }
        }
    }
}
```

**Comment by millems** [comment]
Hmm.. We definitely check for the file to contain session credentials: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/ProfileStaticCredentialsProvider.java#L53-L79

Can you provide a sample (with fake keys) credentials file and what profile `rootProject.getProperties().get('aws.profileName', 'default')` is resolving to? That will help me reproduce it on my end.

**Comment by azihsoyn** [comment]
I'm really sorry... ProfileCredentialsProvider works perfectly. 

Thank you for helping!
