### ISSUE TITLE
Error in AWS Glue ETL JOB if it is created with lambda

### ISSUE THREAD

**Issue by rathodsantosh** [aws/aws-sdk-java#1612]
Hi,

I have this error in my glue job when is created with lambda:

<pre>JobName:AutoJob and JobRunId:jr_72dcafecdc9d824d0b11aa7811041c6cb52068b98d151973898e32e4872d1e89 failed to execute with exception Could not find command for the given criteria</pre>

I am not able to find the cloudwatch logs as well. Not able to understand where I am doing wrong.

Any suggestions are welcome.

**Comment by zoewangg** [comment]
Since this is a service specific question rather than a SDK question, I'd suggest posting it to AWS forums, https://forums.aws.amazon.com/forum.jspa?forumID=262 to get better support from AWS Glue team.
