### ISSUE TITLE
The XML you provided was not well-formed or did not validate against our published schema - using java SDK while creating Analytics configuration

### ISSUE THREAD

**Issue by ramd123** [aws/aws-sdk-java#1613]
getting the below error  while creating analytics configuration using java sdk. 

The observation, getting the error if there is no filter set to the analytics configuration (new AnalyticsFilter().withPredicate(new AnalyticsPrefixPredicate("123456"))). you may find the code snippet below. The filter is optional in the UI.

private void manageAnalytics(String name, AmazonS3 s3) {

	SetBucketAnalyticsConfigurationRequest req = new SetBucketAnalyticsConfigurationRequest();
		req.setBucketName(name);
		AnalyticsS3BucketDestination s3destination = new AnalyticsS3BucketDestination()
				.withBucketAccountId("12345").withBucketArn("arn:aws:s3:::test-lifecycle")
				.withFormat(AnalyticsS3ExportFileFormat.CSV);
		AnalyticsExportDestination destination = new AnalyticsExportDestination()
				.withS3BucketDestination(s3destination);
		StorageClassAnalysisDataExport dataExport = new StorageClassAnalysisDataExport()
				.withDestination(destination).withOutputSchemaVersion("V_1");
		AnalyticsConfiguration analyticsConfiguration = new AnalyticsConfiguration()
				.withId(name + "-analytics-conf-2")
				.withStorageClassAnalysis(new StorageClassAnalysis().withDataExport(dataExport))
				.withFilter(new AnalyticsFilter().withPredicate(new AnalyticsPrefixPredicate("123456")));
		req.setAnalyticsConfiguration(analyticsConfiguration);
		
		s3.setBucketAnalyticsConfiguration(req);
	}

**Comment by millems** [comment]
Can you share the logs from the failing example with debug-level logging enabled and also share the failing code? (I assume it's the same as the above without the `.withFilter(new AnalyticsFilter().withPredicate(new AnalyticsPrefixPredicate("123456")));` line, but couldn't hurt to ask).

**Comment by ramd123** [comment]
following is the piece of code is throwing exception.. without setting filter it is throwing the exception, the same issue occurs though i try with blank value. will send you the logs shortly

SetBucketAnalyticsConfigurationRequest req = new SetBucketAnalyticsConfigurationRequest();
			req.setBucketName(name);
			AnalyticsS3BucketDestination s3destination = new AnalyticsS3BucketDestination()
					.withBucketAccountId(String.valueOf(credentialdetails.getProperty("account.id")))
					.withBucketArn((String) credentialdetails.getProperty("account.destination.bucket"))
					.withFormat(AnalyticsS3ExportFileFormat.CSV);
			AnalyticsExportDestination destination = new AnalyticsExportDestination()
					.withS3BucketDestination(s3destination);
			StorageClassAnalysisDataExport dataExport = new StorageClassAnalysisDataExport()
					.withDestination(destination).withOutputSchemaVersion("V_1");
			AnalyticsConfiguration analyticsConfiguration = new AnalyticsConfiguration()
					.withId(name + "-analytics-conf-3")
					.withStorageClassAnalysis(new StorageClassAnalysis().withDataExport(dataExport));
			req.setAnalyticsConfiguration(analyticsConfiguration);
			s3.setBucketAnalyticsConfiguration(req);

**Comment by ramd123** [comment]
Thanks Matthew, I wonder it is working now without Filter. Not sure what happened.. Is there any change happen at your end? i see it works now.. you may close this ticket.

**Comment by millems** [comment]
I'm not sure whether S3 made a change, but I'm glad it's working! Let us know if anything changes.
