### ISSUE TITLE
NoSuch Method Error - Before Execution

### ISSUE THREAD

**Issue by jclima27** [aws/aws-sdk-java#1617]
java.lang.NoSuchMethodError: com.amazonaws.services.s3.AmazonS3Client.beforeClientExecution(Lcom/amazonaws/AmazonWebServiceRequest;)Lcom/amazonaws/AmazonWebServiceRequest;

at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1623)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1610)

<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-s3</artifactId>
	<version>1.9.30</version>
</dependency>
<dependency>
	<groupId>com.itextpdf</groupId>
	<artifactId>itextpdf</artifactId>
	<version>5.5.6</version>
</dependency>
<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpclient</artifactId>
	<version>4.5.3</version>
	<scope>compile</scope>
</dependency>

**Comment by jclima27** [comment]
<code>
My Pom
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-s3</artifactId>
	<version>1.9.30</version>
</dependency>
<dependency>
	<groupId>com.itextpdf</groupId>
	<artifactId>itextpdf</artifactId>
	<version>5.5.6</version>
</dependency>
<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpclient</artifactId>
	<version>4.5.3</version>
	<scope>compile</scope>
</dependency>
</code>

**Comment by millems** [comment]
Make sure to use a version of the core runtime that is equal to or higher than your S3 version. This exception indicates your core version is out of date.

**Comment by jclima27** [comment]
My Pom
<pre><code>
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-s3</artifactId>
	<version>1.9.30</version>
</dependency>
<dependency>
	<groupId>com.itextpdf</groupId>
	<artifactId>itextpdf</artifactId>
	<version>5.5.6</version>
</dependency>
<dependency>
	<groupId>org.apache.httpcomponents</groupId>
	<artifactId>httpclient</artifactId>
	<version>4.5.3</version>
	<scope>compile</scope>
</dependency>
</code></pre>

**Comment by varunnvs92** [comment]
Do you still have the issue?

**Comment by millems** [comment]
Resolving. Let us know if we can help in any other way.
