### ISSUE TITLE
Feature Request: Lambda Get Function Execution Permission

### ISSUE THREAD

**Issue by c1phr** [aws/aws-sdk-java#1618]
The current Lambda SDK exposes methods for adding and removing function permissions, but there's no way to inspect the permissions that are currently implemented on a function. This can make using the RemovePermission method difficult since it requires advance knowledge of the SID to be deleted (and this SID cannot be looked up programmatically).

I would like to propose that a method be added similar to [GetPolicy](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/AWSLambdaClient.html#getPolicy-com.amazonaws.services.lambda.model.GetPolicyRequest-) which returns the execution permissions that are set on the lambda function. The request could take the same parameters as GetPolicy: Function Name and optionally a qualifier (see [GetPolicyRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/model/GetPolicyRequest.html)).

**Comment by binaryblake** [comment]
+1

**Comment by millems** [comment]
Unfortunately we just expose functionality that the lambda team supports. Could you try asking on the AWS forums or to AWS support for this functionality to be added? We could forward on this feedback to the lambda team, but wouldn't be able to feed you back any status updates.

**Comment by c1phr** [comment]
I opened a support ticket on this and it does look like it's there in the API and SDK under the name "GetPolicy" rather than referencing "permission", which is where the confusion came from. I'll close this issue here, but [this is the SDK docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/AWSLambda.html#getPolicy-com.amazonaws.services.lambda.model.GetPolicyRequest-) for the method in question in case anyone else stumbles on this.
