### ISSUE TITLE
AmazonS3URI doesn't provide a method to get an unencoded s3 path

### ISSUE THREAD

**Issue by pbartoszek** [aws/aws-sdk-java#1619]
AmazonS3URI uses internally `java.net.URI` class to parse passed path via constructor. The problem is that it's very hard to get unencoded version of the path from the class afterwards.

```
AmazonS3URI amazonS3URI = new AmazonS3URI("s3://my-bucket/yyyy=2018/file.txt");
System.out.println(amazonS3URI.getURI().toString()); // it prints s3://my-bucket/yyyy%3D2018/file.txt
```

Currently to be able to get unencoded path I need to manually build the path from s3 protocol, bucket and key. I am thinking about cases where s3 path should be stored in DynamoDB unencoded.

**Comment by millems** [comment]
Is passing `false` as the second constructor parameter to skip encoding sufficient to fix your problem, or do you want to be able to have the class encode it, but still be able to access the string you originally passed in?

**Comment by pbartoszek** [comment]
Thanks @millems. Passing `false` as second parameter fixes the problem. However semantics of the flag is a bit misleading as javadoc suggests that I should ensure that path is encoded beforehand. I don't encode `=` character and it still works...

**Comment by millems** [comment]
Sorry this issue sat so long without comment. We're currently focused primarily on 2.x of the SDK and won't be making any changes of this nature in 1.11.x.
