### ISSUE TITLE
AWS::DynamoDB metrics :: aggregation granularity

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#1621]
Hi,

we have been using AWS DynamoDB for some time. It clearly mentioned in the help document that for the metrics 'ProvisionedRead/Write Capacity Units', the aggregation granularity is 5 minutes. But in cloudwatch console, there is some lagging in the datapoints as its taking more than 5 minutes which is expected. 

Maximum it takes 7 minutes and most of the time it took 6 minutes to populate.

Thank you in advance.

Regards,
Garry.

**Comment by varunnvs92** [comment]
These metrics are not maintained by the SDK. Please reach out to DynamoDB and Cloudwatch team either through console support or [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=138).
