### ISSUE TITLE
Useless error message when attempting to delete too many S3 objects

### ISSUE THREAD

**Issue by sithmein** [aws/aws-sdk-java#1626]
Using the following code snippet

```
DeleteObjectsRequest deleteRequest = new DeleteObjectsRequest("root");
deleteRequest.setKeys(toDelete);
s3client.deleteObjects(deleteRequest);
```

results in an error message "The XML you provided was not well-formed or did not validate against our published schema" if the list of keys is too large (>>100 items). It took me about an hour to find out and after I deleted the items in chunks it worked. The message is clearly totally useless in this case - it's even wrong in my opinion because the sent XML is correct. It's likely a server issue but the S3 client could check the size of the request beforehand and either issue a better message or perform chunked requests on its own.

**Comment by varunnvs92** [comment]
This is a known issue. See https://github.com/aws/aws-sdk-java/issues/1293
Amazon S3 team has added it to their backlog but has not prioritized it yet. You can +1 the other ticket and follow updates there. Resolving this ticket as duplicate.

Feel free to reopen if you think this is a different issue or have other questions.
