### ISSUE TITLE
Performance issue while listing buckets in a specific region

### ISSUE THREAD

**Issue by ankitachdhr** [aws/aws-sdk-java#1627]
**Requirement:**
To list buckets in a specified region
**Problem statement:**
After adding the check "to get buckets in a specific location" and then fetching the final result set is taking ~5 seconds whereas without get bucket location check it will hardly take 1 second but will get all the buckets globally defined.
**Insight:**
Using AWS SDK for Java, we are trying to fetch list of buckets in a specific region with method
-s3.getBucketLocation(String bucket). But when we add this constraint to fetch bucket in the specified region then we get the list of buckets in ~5 seconds.
Without location/region check it hardly take 1 second to get the result from AWS S3. 

Is there any other way where the performance is not compromised and we can easily get list buckets for a specific location? I have tried with HeadBucketRequest.withBucketRegion(String bucket) too. It is again not useful.

**Comment by varunnvs92** [comment]
Please provide sample test code to repo the issue?
What is the SDK version?

**Comment by ankitachdhr** [comment]
**Sample code:**
listBucket.removeIf((e) -> !s3.getBucketLocation(e.getName()).equals(region));
where region is "eu-central-1"

**SDK Version:** 
1.11.29

**Comment by varunnvs92** [comment]
```getBucketLocation``` makes a "GET" call to Amazon S3. For each bucket, we have to request S3 and wait for response which introduces small latency. So when you have high number of buckets, there are high number of network calls and the latency adds up. This is expected.

You can use HeadBucket which is "HEAD" call, so the latency is small. See this [code](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L5119-L5140) for reference. The catch clause is for cases when you make a request to one region but sign the request with another region. In these cases, please be aware that its not guaranteed that region info is present all the times.

**Comment by varunnvs92** [comment]
Aren't the permissions requirements same for GET call?

>> Is there any other alternative to get bucket location??
I don't think so. AFAIK these are the 2 APIs that can give the region info.

**Comment by ankitachdhr** [comment]
Unfortunately, it does not goes with the same permission level because when it tries to fetch region for any bucket in some other location it throws a forbidden error.
-client.headBucket(new HeadBucketRequest(bucket)).getBucketRegion(). it requires s3:ListBucket permission, see https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html for more info.

I have tried this piece of code in my application.

**Comment by varunnvs92** [comment]
Maybe its the reason we have catch the exception and retrieve the bucket region from exception.getAdditionalDetails().

**Comment by ankitachdhr** [comment]
This is how am trying to get bucket region with **HeadBucketRequest**
> listBucket.removeIf((e) -> !(s3.headBucket(new HeadBucketRequest(e.getName())).getBucketRegion()).equals(region));

But it throws an exception with the following message because I have access to eu-central-1 buckets only and stops the execution to fetch region for rest of the buckets.
"message": "The bucket is in this region: us-east-1. Please use this region to retry the request "

Can you please give a sample code or an example if am wrong somewhere while fetching bucket region?

**Comment by varunnvs92** [comment]
The following code should work on getting the region via HEAD call. I am just printing the bucket name and region. You can modify the code to delete buckets based on your criteria.

It worked for all buckets in my account. As I mentioned, there might be edge cases where the bucket name can be null. Please modify the code to handle null case.

```
    @Test
    public void testBucketRegion() {
        AmazonS3 s3 = AmazonS3ClientBuilder.defaultClient();

        s3.listBuckets().stream().map(b -> b.getName())
          .forEach(bucket -> System.out.println(String.format("%s -- %s", bucket,
                                                              getBucketRegionViaHeadRequest(s3, bucket)))
          );
    }


    private String getBucketRegionViaHeadRequest(AmazonS3 s3, String bucketName) {
        String bucketRegion = null;

        try {
            HeadBucketResult result = s3.headBucket(new HeadBucketRequest(bucketName));
            bucketRegion = result.getBucketRegion();
        } catch (AmazonS3Exception exception) {
            if (exception.getAdditionalDetails() != null) {
                bucketRegion = exception.getAdditionalDetails().get(Headers.S3_BUCKET_REGION);
            }
        }

        if (bucketRegion == null) {
            System.out.println("Not able to derive region of the " + bucketName + " from the HEAD Bucket requests.");
        }

        return bucketRegion;
    }
```
Let us know if you have more questions.

**Comment by ankitachdhr** [comment]
Thanku varun. This is working now.  Cheers !!
