### ISSUE TITLE
InputStreams are confusing EOF states with timeouts

### ISSUE THREAD

**Issue by mackrorysd** [aws/aws-sdk-java#1630]
I've also written up this bug and a possible work-around for Hadoop (https://issues.apache.org/jira/browse/HADOOP-15541), but I think there may be some flawed logic in the SDK regardless that we might want to fix. In a nutshell, when recovering from a read timeout, Hadoop tries to drain the stream (I'm trying to figure out what benefit we gain from doing that), but it gets an SdkClientException for an unexpected reason. Upon reading the stream, we check the lengths are what we expect. Having timed out, the stream reports -1, which is interpreted by the SDK to mean we've hit EOF. Since it think we've hit EOF, the SDK expects bytes read to match expected bytes. Since we haven't actually hit EOF, they don't match. The relevant code is here:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/LengthCheckInputStream.java#L90-L93
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/LengthCheckInputStream.java#L148

I suspect our attempt at "draining the stream" when recovering from a failure would have to fail eventually anyway, so I don't know how big of a deal it is to simply abort after this particular failure. But regardless, the SDK seems to be assuming we've hit EOF when we haven't, and that feels wrong regardless.

**Comment by varunnvs92** [comment]
Can you point me to the resources where the stream returns -1 in case of timeout. Why does it return -1 instead of throwing an exception? Maybe I am missing some context here.

>> Hadoop tries to drain the stream (I'm trying to figure out what benefit we gain from doing that)

Its possible that aborting the stream will close the underlying connection instead of releasing it to the pool. We have similar logic where we try to drain the stream instead of aborting to release the underlying connection to pool.

**Comment by mackrorysd** [comment]
When it times out, it does throw a SocketTimeoutException. The concern is just that later, retrieving the bytes read returns -1 at the lines I linked to above, and that is equated with EOF.

**Comment by steveloughran** [comment]
oh, so after the ex, any read() returns -1, not 'failed'?

**Comment by steveloughran** [comment]
...we should force an abort() here to stop the connection going back to the pool. Socket timeouts don't suddenly heal themselves, do they?

**Comment by dagnir** [comment]
Maybe I'm misunderstanding, but if an`IOException`s occurs when reading from the connection, it should not be getting released back into the pool. Are you observing something different?

**Comment by steveloughran** [comment]
It sounds a bit like that; we can just abort() in our client to make sure that this is guaranteed to happen.

**Comment by shorea** [comment]
Is there anything further pending from the SDK team on this issue?

**Comment by steveloughran** [comment]
@shorea I don't think there is. We're treating any input stream IOE raised as a non-closing-stream failure; socket timeouts = break the input stream  before retrying. And as I regression test the update to [1.11.374](https://issues.apache.org/jira/browse/HADOOP-15642); I'm not seeing any new problems here. That said, it's not something our fault-injection layer simulates failures with.

**Comment by dagnir** [comment]
Cool, in that case I'm going to go ahead and close this. Feel free to reopen if any further questions come up.
