### ISSUE TITLE
Allow usage of BouncyCastle FIPS library

### ISSUE THREAD

**Issue by presto9292** [aws/aws-sdk-java#1632]
Using client-side encryption with CryptoMode.AuthenticatedEncryption fails with UnsupportedOperationException when the BouncyCastle library being used is the FIPS version
 
`org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider`

Is solving this just a matter of relaxing the BouncyCastle check in CryptoRuntime to allow for the FIPS provider as well ?

```
AmazonS3EncryptionClientBuilder.standard()
.withCryptoConfiguration(newCryptoConfiguration(CryptoMode.AuthenticatedEncryption)
.withCryptoProvider(new BouncyCastleFipsProvider()))

java.lang.UnsupportedOperationException: The Bouncy castle library jar is required on the classpath to enable authenticated encryption
	at com.amazonaws.services.s3.model.CryptoConfiguration.check(CryptoConfiguration.java:241)
```

**Comment by varunnvs92** [comment]
What is the difference between normal bouncy castle vs Fips version? Is it recommended to use FIPS?

**Comment by varunnvs92** [comment]
This code might be relavant to your use case
https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/crypto/S3CryptoModuleBase.java#L529-L530
https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/crypto/ContentCryptoMaterial.java#L900-L915


**I would say set this key-value pair using [EncryptionMaterials#addDescription](https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/EncryptionMaterials.java#L103-L106). Let us know if it worked.**

**Comment by presto9292** [comment]
FIPS-140 is a US federal standard that specifies requirements for cryptography.
BouncyCastle is providing an alternative JCE implementation jar file that has been certified by a testing lab. Software for the US government is required to use the FIPS JCE version rather then the plain one. The two JCE providers can not co-exist on the classpath.
So it's either 
org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
or
org.bouncycastle.jce.provider.BouncyCastleProvider

Further details in this link (choose option 3 and proceed)
https://www.bouncycastle.org/fips-java/

**Comment by presto9292** [comment]
Please also note the distinction between approved and non-approved modes of the FIPS JCE as explained in sections 1.1 and 1.2 of BC-FJA-SecurityPolicy-1.0.1.pdf on the BC FIPS page.

In approved mode only a subset of the encryption algorithms are available.
The JCE goes into approved mode by setting system property org.bouncycastle.fips.approved_only to true
In our case the software is shipped with the FIPS JCE to our many customers in non-approved mode, and approved mode is turned on only in few select cases as required.
So for our purposes it would be enough if the SDK supports the non-approved mode, although supporting approved-mode would be brilliant

**Comment by zoewangg** [comment]
Closing via #1633
