### ISSUE TITLE
List Objects inside a bucket

### ISSUE THREAD

**Issue by ankitachdhr** [aws/aws-sdk-java#1635]
**Requirement:**
We have this requirement where we want to fetch result inside a folder(key) and we can have huge number of records  and each file can be of more than 1GB(Image files).
**Problem statement:**
In case we fetch all the results at a time then we have obvious performance issues. So in order to optimize am using listObjectsV2 method provided where in the request am passing maximum keys value and truncating the result. Now, we want to add pagination too because even with maximum keys we cant optimize it.
**We want to do pagination before we hit the listObjectsV2 method as post processing the result set is not a solution for performance optimization.**

Like if we say we want to show the user with the first set of records from UI. Then we will fetch 0-1000 records. Fetching 0-1000 records is not an issue (when starting index is 0) but when we try to fetch from 1000-2000, we cant attain so before hitting **listObjectsV2** method as we dont have any starting index as 1000 in S3 from where we can fetch next 1k results inside a folder(key)

**Sample code:**
ListObjectsV2Request req = new ListObjectsV2Request().withBucketName(bucket).withMaxKeys(500);
		// When we want to fetch records under a path only.
		if (!StringUtils.isNullOrEmpty(key) && s3.doesObjectExist(bucket, key)) {
			req.setPrefix(key);
		} else {
			throw new ObjectNotFoundException("File/Folder does not exist.");
		}
          	do {
			result = s3.listObjectsV2(req);
			for (S3ObjectSummary objectSummary : result.getObjectSummaries()) {
				objectList.add(objectSummary);
			}
			String token = result.getNextContinuationToken();
			// In case we have more than 500 records then passing the next token
			// from where it has to start again.
			req.setContinuationToken(token);
		} while (result.isTruncated());

**Comment by varunnvs92** [comment]
I am not fully clear on the question. From what I understand you want the pagination feature which is already present in the SDK.

When you specify ```MaxKeys``` as 500 and make a ```listObjectsV2``` call, then you will get a maximum of 500 values. Then you can retrieve the next set of results using the ```NextContinuationToken```. If your request is to paginate again in the first 500 (ie, show only 250 to user), then you have to implement custom code in you application to show first 250, then next 250. When you are out of results locally, make the next ```listObjectsV2``` call to get more results.

**Comment by ankitachdhr** [comment]
Lets say from UI we want to fetch result set from 0-1000 in one request. Then in another API request we want to fetch from 1000-2000. 
First API request to fetch 0-1000 results. Starting index: 0
Another API request to fetch 1000-2000 records, Starting index: 1000
Now, the starting index is 1000 and I cant resume from 1000 in a separate request as I dont have the value stored for nextContinuationToken in the second request. I want 1k records in separate requests not in a single request. 

**Question:** In another request how can I fetch result set from 1000-2000 without fetching 0-2000 records.

**Comment by dagnir** [comment]
@ankitachdhr if I understand correctly, you want to do something like this in your application?

```
myApp.showObjectsInFolder(0, 1000);

....

myApp.showObjectsInFolder(1000, 2000);
```
?

If so, I don't think believe there's a way to do it with just the `ListObjectsV2` API; the closest thing is the `startAfter` parameter, which allows you to start the listing after the given key: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ListObjectsV2Request.html#withStartAfter-java.lang.String-.

One solution might be to maintain some sort of index and query that instead.

**Comment by dagnir** [comment]
Going to go ahead and close this as we reserve GitHub issues for bugs and feature requests within the SDK. For usage questions, we recommend moving them over to [StackOverflow](http://stackoverflow.com/questions/tagged/aws-java-sdk) and tagging it with `aws-java-sdk`, so that our community of users can help you out! This seems like a use case that might be pretty common so it's possible some users over at SO can give some pointers.

Please feel free if to reopen if you have any further questions.
