### ISSUE TITLE
Desperate on logging verbosity

### ISSUE THREAD

**Issue by mariano-calandra-xp** [aws/aws-sdk-java#1637]
We have a 100 Lambda application. This Lambda print a huge amount of logging and we need to reduce it. I read some docs (Logging AWS SDK for Java Calls [v1](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html) and [v2](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-logging.html)). So I installed it in pom, like doc said:

	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
		<artifactId>log4j-core</artifactId>
		<version>2.11.0</version>
	</dependency>
	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
		<artifactId>log4j-api</artifactId>
		<version>2.11.0</version>
	</dependency>
	<dependency>
		<groupId>org.apache.logging.log4j</groupId>
		<artifactId>log4j-slf4j-impl</artifactId>
		<version>2.11.0</version>
	</dependency>

I issued a `mvn clean` and a `mvn package shade:shade`, inside the _target_ directory, I unzip the jar with unzip command and put the resulting files in a directory called jar. Then I executed at the root of my project a `sam local` command like this: 

    > sam local invoke MyFunction -e evenfile.json -t template.yml -v target/jar
    10:52:16.810 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
    10:52:16.948 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics

And here it is the DEBUG line. What I would is to reduce the verbosity to WARN, and I create a file log4j2.xml (following the doc):

```
<Configuration status="WARN">
  <Appenders>
    <Console name="ConsoleAppender" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{YYYY-MM-dd HH:mm:ss} [%t] %-5p %c:%L - %m%n" />
    </Console>
  </Appenders>

  <Loggers>
    <Root level="WARN">
      <AppenderRef ref="ConsoleAppender"/>
    </Root>
  </Loggers>
</Configuration>
```

I tried to copy this file into class path but that DEBUG line are printed as usual. So to speed up the clock I said, I copy this file in each folder and subfolder of the target/jar recursively. So I used:

    find target/jar -type d -exec cp log4j2.xml {} \;

but the DEBUG is still there. I don't know what to do anymore, but I need to put reduce it.

**Comment by dagnir** [comment]
Hi @mariano-calandra-xp, it looks like you may have followed the instructions for logging in V2, which using a different logging framework than V1.

To enable and configure logging in V1, please refer to https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

Basically, you will need to do the following:

Add `logj4j` 1.x to your POM:

```xml
    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.17</version>
    </dependency>
```

in your `src/main/resources` of your project, create a `log4j.properties` file to store your logging configuration.

Here's a simple one that sets the root logging level to `WARN`:

```
log4j.rootLogger=WARN, A1
log4j.appender.A1=org.apache.log4j.ConsoleAppender
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%d [%t] %-5p %c -  %m%n
```

You can find more examples from the link above.

**Comment by mariano-calandra-xp** [comment]
Thank @dagnir 
Some updates: I created a parallel project, it start prints that log as soon I use, soemthing like:
```
AmazonDynamoDB client= AmazonDynamoDBClientBuilder.standard().withRegion(Regions.EU_WEST_1).build();
```
Your tip do the job on this parallel job but is unusefull on the real project. I suppose that some package's dependencies starts a logger war and log4j.properties is ignored.

**Comment by dagnir** [comment]
Gotcha; yes it sounds as if one of the other dependencies in your real application is interfering. Since this doesn't look like an issue with the SDK--log4j is being configured by one of the other dependencies--would you please move this question over to [StackOverflow](http://stackoverflow.com/questions/tagged/aws-java-sdk) and tag it with `aws-java-sdk`? Our community of users should be able to help you out.

We have limited bandwidth to look at issues here on GitHub so we try to keep them only related to bugs and feature requests for the SDK itself.

**Comment by mariano-calandra-xp** [comment]
surely @dagnir :)
I resolved the issue excluding log related subdependencies from pom.xml and installing log4j and common-logging.

**Comment by jackmead515** [comment]
Just for future clarification, a very similar thing happened while I was doing work on an application. To "exclude" dependencies from packages in Maven, add the follow:
```
<dependency>
            <groupId>com.company.stuff</groupId>
            <artifactId>MyUtils</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.company</groupId>
                    <artifactId>ProblemPackage</artifactId>
                </exclusion>
                <!-- add more if needed -->
            <exclusions>
           ...
```
