### ISSUE TITLE
java.lang.NoSuchMethodError: com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient

### ISSUE THREAD

**Issue by yogesh-0586** [aws/aws-sdk-java#1640]
Hi, I  run following  code in aws-emr cluster as below 
`spark-shell --jars aws-java-sdk-1.11.350.jar, jackson-core-2.6.7.jar, RedshiftJDBC42-1.2.15.1025.jar`

```
import com.amazonaws.services.redshift.AmazonRedshiftClient
import com.amazonaws.auth.{AWSSessionCredentials, InstanceProfileCredentialsProvider}
import com.amazonaws.services.redshift.model._
import com.amazonaws.services.securitytoken.AWSSecurityTokenService
import com.amazonaws.services.securitytoken.model.AssumeRoleRequest
import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder
import com.amazonaws.auth.profile.ProfileCredentialsProvider

val roleARN = "roleARN"
val roleSessionName = "roleName"
val clientRegion = "us-east-1"

val stsClient : AWSSecurityTokenService = AWSSecurityTokenServiceClientBuilder.standard().withCredentials(new ProfileCredentialsProvider()).withRegion(clientRegion).build()
```

but it show following error 

> java.lang.NoSuchMethodError: com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(Lcom/amazonaws/client/AwsSyncClientParams;)V
  at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:60)
  at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:26)
  at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
  ... 50 elided

**Comment by dagnir** [comment]
Hi, I'm not familiar with EMR or `spark-shell` but I assume the option `--jars aws-java-sdk-1.11.350.jar, jackson-core-2.6.7.jar, RedshiftJDBC42-1.2.15.1025.jar` puts these JARs on your classpath.

Where is `aws-java-sdk-1.11.350.jar`? How was it obtained?

**Comment by yogesh-0586** [comment]
Using [This link](https://aws.amazon.com/sdk-for-java/) I downloaded aws-java-sdk and extract that zip in that `lib` folder having this `aws-java-sdk-1.11.350.jar` I copied this jar in EMR home path `/home/hadoop` and used this jar path in spark-shell if that spark-shell not loaded jar properly then it show's error at the import time but in import it work fine  but when I execute this statement 

`val stsClient : AWSSecurityTokenService = AWSSecurityTokenServiceClientBuilder.standard().withCredentials(new ProfileCredentialsProvider()).withRegion(clientRegion).build()`

then it show error

**Comment by dagnir** [comment]
Thanks for the details! I'll look into it.

**Comment by dagnir** [comment]
Okay I see where the issue is. The inclusion of `RedshiftJDBC42-1.2.15.1025.jar` is causing the issue because it packages (older) parts of the Java SDK with it, including STS 1.11.118.

Per the documentation here, if you're bringing your own version of the SDK, they recommend using the `no-awssdk` variants instead:

https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html

**Comment by dagnir** [comment]
BTW if you're using `aws-java-sdk-1.11.350.jar` from the the linked URL, you may need to include some or all of the libraries in `third-party/lib` as well as that JAR only contains the SDK classes and not any of the dependencies.

**Comment by yogesh-0586** [comment]
I tried following a way 

`spark-shell --jars aws-java-sdk-1.11.350.jar, aws-java-sdk-1.11.350/third-party/lib/*` 

and remove `RedshiftJDBC42-1.2.15.1025.jar` but it still shows same errors

**Comment by dagnir** [comment]
Hmm the same error?

```
java.lang.NoSuchMethodError: com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.(Lcom/amazonaws/client/AwsSyncClientParams;)V
at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:60)
at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:26)
at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
... 50 elided
```
?

**Comment by yogesh-0586** [comment]
yes it show the same error 
```
java.lang.NoSuchMethodError: com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.(Lcom/amazonaws/client/AwsSyncClientParams;)V
at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:60)
at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:26)
at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
... 50 elided
```

**Comment by dagnir** [comment]
Hmm then there must be something else on the classpath that's also bringing an older version of the STS client. Is there a way for `spark-shell` to show you what all the loaded JARs are? I would then check if any of them include an outdated STS client.

**Comment by yogesh-0586** [comment]
Hey @dagnir Thanks for your support I found that issues and resolved. It related to spark-configuration and version, I used EMR 5.2.2 cluster and it's default contains this `aws-java-sdk-1.10.75.1.jar` aws-sdk . 

For this I started spark shell as below 

`spark-shell --conf "spark.driver.extraClassPath=/home/hadoop/aws-java-sdk-1.11.353/lib/*"` and it's resolved all issues 

Thanks
