### ISSUE TITLE
AWSCostExplorerException: Expression has zero or more than one roots

### ISSUE THREAD

**Issue by EUGinsane** [aws/aws-sdk-java#1645]
Hi, I am using GetCostAndUsageRequest to get the VMs usage data on AWS, it works fine if I specify only either dimensions or tags in filter, but I want to use both to get the right data then it causes this exception:

> Exception in thread "main" com.amazonaws.services.costexplorer.model.AWSCostExplorerException: Expression has zero or more than one roots. Only one root operator is allowed for each expression: "and", "or", "not", "tag" or "dimensionValue" (Service: AWSCostExplorer; Status Code: 400; Error Code: ValidationException; Request ID: 47ac847b-75ec-11e8-ae1d-074631c62224)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
> 	at com.amazonaws.services.costexplorer.AWSCostExplorerClient.doInvoke(AWSCostExplorerClient.java:636)
> 	at com.amazonaws.services.costexplorer.AWSCostExplorerClient.invoke(AWSCostExplorerClient.java:612)
> 	at com.amazonaws.services.costexplorer.AWSCostExplorerClient.executeGetCostAndUsage(AWSCostExplorerClient.java:196)
> 	at com.amazonaws.services.costexplorer.AWSCostExplorerClient.getCostAndUsage(AWSCostExplorerClient.java:171)
> 	at com.aws.app.GetBillingInfo.main(GetBillingInfo.java:47)

Here is my code:

```
filter.setDimensions(dimensionValues
				.withKey(Dimension.USAGE_TYPE_GROUP)
				.withValues("EC2: Running Hours"));
        
        filter.setTags(tagValues
				.withKey("Name")
				.withValues("Foreman_NghiaNguyen"));
        
        GetCostAndUsageRequest request = new GetCostAndUsageRequest()
        		.withTimePeriod(dateInterval)
        		.withGranularity(Granularity.MONTHLY)
        		.withMetrics("UsageQuantity", "UnblendedCost")
        		.withFilter(filter);
```

Like I said before, if I use only setDimensions or setTags, it works, but I need to use both to get the right data. Any solutions ? Thanks

Extra Question: How can I filter to get the exact VM ? Maybe filter by its instanceID, does AWS sdk support this ? Thanks again,

**Comment by dagnir** [comment]
Hi @EUGinsane, looking at the [docs for Expression](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Expression.html) it looks you need to combine your two filters using `And` (there's also `Or` and `Not`). So something like this should work:

```java
        Expression dimensions = new Expression()
                .withDimensions(new DimensionValues().withKey("someKey").withValues("foo", "bar"));

        Expression tags = new Expression()
                .withTags(new TagValues().withKey("someKey").withValues("baz"));

        Expression expr = new Expression().withAnd(dimensions, tags);
```

and use `expr` in your filter.

Since this doesn't look like an issue with the SDK itself, would you please post the question over at [StackOverflow](http://stackoverflow.com/questions/tagged/aws-java-sdk) and tag it with `aws-java-sdk`? Our community of users should be able to help you out with any usage questions.

We have limited bandwidth to respond to issues on our GitHub page so we reserve it for issues and feature request related to the SDK itself.

**Comment by EUGinsane** [comment]
@dagnir thanks, will keep that in mind, I posted on StackOverflow but for days nobody answer so I have to post here, sry for this inconvenience

**Comment by dagnir** [comment]
Okay I see. As far as your second question, looking at the docs for the operation  (https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html#API_GetCostAndUsage_RequestParameters) I don't see any builtin way to do this unfortunately.

**Comment by dagnir** [comment]
@EUGinsane I've gone ahead and closed this as there's no issue with the SDK that I can see. Please feel free to reopen or open a new issue if you experience any issues!
