### ISSUE TITLE
Add waiter for the Athena Client?

### ISSUE THREAD

**Issue by danielcompton** [aws/aws-sdk-java#1646]
It looks like many of the [Clients](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/overview-summary.html) have a [waiter](https://aws.amazon.com/blogs/developer/waiters-in-the-aws-sdk-for-java/), but not Amazon Athena. Would it be possible to add one for Athena too?

**Comment by tomkoshy999** [comment]
Please add this. Without this it is really hard to figure out when it completes

**Comment by kmbotts** [comment]
This seems like a fun little project, but how would one begin something like this? Looking at the AmazonCloudFormationWaiters as an example, the code seems pretty uniform, however it also appears to be completely code generated. I found the templates, but oblivious to how it's run or where things are stored to be replicated by someone. Not to mention that the Athena project is entirely sans unit tests, so it would need to be built from scratch. But again, comparing it to Cloudformation, there doesn't seem to be much unit testing going on in general.

**Comment by drissamri** [comment]
This would be very useful feature. Reimplementing the same waitForQueryToComplete is a bit silly. 
Hooks to execute on query status (succeed/running/queued/failed/cancelled) would also be very helpful

**Comment by debora-ito** [comment]
We are tracking this in the cross-sdk repository `aws-sdk`: https://github.com/aws/aws-sdk/issues/80.
