### ISSUE TITLE
How to set timeout for api connector from Assert in Mule crowd release 

### ISSUE THREAD

**Issue by shakeelashaik05** [aws/aws-sdk-java#1647]
Hi,

We have created API connectors within our organization to use in different applications to call the specific resource.
I downloaded the specific connector from Exchange and used in my application to call a specific resource from other API. 
 in the connector configuration, there is no option to set timeout.

Please let me know how to configure this.

**Comment by dagnir** [comment]
Hi can you elaborate on the question? I'm not sure exactly what the question is from reading the issue unfortunately.

**Comment by shakeelashaik05** [comment]
Hi ,
Thanks for your reply 
we are following API led connectivity approach.

After Mule crowd release, We have published each API to Exchange as Connector within our organization These connectors can be used to invoke resource in another API, instead of using HTTP requester.

I downloaded the connector and successfully invoked the other API. I need to set response timeout for some specific API in API connector. But no option is available to set this connector.

`  <xxx-sl-app:update-api config-ref="xxx_SL_app__Configuration" entity="#[message.payload]" doc:name="xxx_SL_app" />
`
![image](https://user-images.githubusercontent.com/19384183/41872441-317a3cac-78c2-11e8-9627-42582b990386.png)

**Comment by spfink** [comment]
Sorry, I'm not sure if this is the right repo for this request. This repo is for the AWS Java SDK used to communicate with all of our AWS services. I'm not familiar with this "Connector" interface that you are talking about. We don't have a UI either. Are you using a third-party tool with the SDK? If so, going through their support channels will likely get you the answer you need.
