### ISSUE TITLE
Multipart file upload content type

### ISSUE THREAD

**Issue by pacey** [aws/aws-sdk-java#1648]
It looks like the normal `putObject` method on the S3 client will add a content-type header for you if one is missing. This is super helpful and I couldn't see this behaviour in the `initiateMultipartUpload` method. All the files I've uploaded end up having the content-type set to `application/octet-stream`

I'm currently using the AmazonS3 interface via the https://github.com/spring-cloud/spring-cloud-aws project and it's not possible to set the ObjectMetadata there.

Would it be possible to add this functionality to the `initiateMultipartUpload` method, as I can see the rest api supports that header?

**Comment by rafael-adcp** [comment]
Hey i found some work arounds for this, you can either call the s3 rest api directly which will work properly, or you can provide the content type when you initiate the multipart upload

eg:
```java
//setting object metadata to have your file content type
ObjectMetadata objectMetadata = new ObjectMetadata();
objectMetadata.setContentType("video/mp4");

// Initiate the multipart upload.
InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest(
    bucket,
    key,
    objectMetadata
);
```

code to uploadPart and also to complete remains the same

**Comment by debora-ito** [comment]
@pacey @rafael-adcp 

Just a quick update letting you know that the SDK team has reviewed the feature request list for V1 and this looks like a great candidate for a community PR, which we’ll help merge in and support.

**Comment by pacey** [comment]
I can have a stab at it @debora-ito

**Comment by debora-ito** [comment]
@pacey @JasonVoss 

We did a bad job reviewing PRs for v1 requested features in a timely manner. And now v1 is moving to [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so we are closing stale issues like this. 

The recommendation is to migrate to Java SDK v2. The v2 S3 client is auto-generated (not manually written like in v1) so the behavior is more consistent across APIs, but if you see any problem please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.


#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
