### ISSUE TITLE
Cannot specify GuardDuty time-based Conditions to ListFindings because it requires integers larger than 32 bit.

### ISSUE THREAD

**Issue by walkerk1980** [aws/aws-sdk-java#1650]
If you test the below code with the variable i set to unix time in seconds the api call will work, but your results will not be accurate. For this API call to work properly you must provide an Integer argument to condition.withGte() with the date in milliseconds. The problem is that a date in milliseconds (example 1556233254000) is larger than a 32 bit integer can hold. [1][2][3]

[1] https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/guardduty/model/Condition.html#withGt-java.lang.Integer-
[2] https://docs.oracle.com/javase/6/docs/api/java/lang/Integer.html#MAX_VALUE 
[3] ListFindings - Request Parameters - https://docs.aws.amazon.com/guardduty/latest/ug/list-findings.html#list-findings-request-parameters

If you run the code below with the required integer milliseconds value you will get the java error "integer number too large: 1556233254000".

public class ListFindingsWithFindingCriteria {
    public static void main(String[] args) {

        AmazonGuardDuty guardduty =
            AmazonGuardDutyClientBuilder.defaultClient();

        String detectorId = "ceb03b04f96520a8884c959f3e95c25a";
        FindingCriteria criteria = new FindingCriteria();
        Condition condition = new Condition();
        Integer i = 1556233254000;
        condition.withGte(i);

        criteria.addCriterionEntry("updatedAt", condition);

        try {
            ListFindingsRequest request = new ListFindingsRequest()
                        .withDetectorId(detectorId)
                        .withFindingCriteria(criteria);

            ListFindingsResult response = guardduty.listFindings(request);

            for (String finding : response.getFindingIds()) {
                System.out.println("FindingId: " + finding);
            }
        } catch (AmazonServiceException ase) {
                System.out.println("Caught Exception: " + ase.getMessage());
                System.out.println("Reponse Status Code: " + ase.getStatusCode());
                System.out.println("Error Code: " + ase.getErrorCode());
                System.out.println("Request ID: " + ase.getRequestId());
        }

    }
}

You can further test this with the AWS CLI:

Correct results will be returned when specifying Unix Epoch Time in milliseconds:

aws guardduty list-findings --detector-id ceb03b04f96520a8884c959f3e95c25a --finding-criteria '{ "Criterion": { "updatedAt": { "Gte": 1524697254000}}}'

Incorrect results will be returned when specifying Unix Epoch Time in seconds:

aws guardduty list-findings --detector-id ceb03b04f96520a8884c959f3e95c25a --finding-criteria '{ "Criterion": { "updatedAt": { "Gte": 1524697254}}}'

**Comment by spfink** [comment]
We have a request open with the service team on this. Will update when we hear back.

**Comment by shorea** [comment]
The service team is aware of the issue and we are discussing potential fixes.

For SDK team, TT0154767053.

**Comment by debora-ito** [comment]
Hi @walkerk1980, GuardDuty released a change on their [Condition](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/guardduty/model/Condition.html) fields and they now support Long types with new names like equals, notEquals, lessThan, greaterThan etc. Also, the old field names were deprecated. Please check the javadoc for more info.

The change is available from version `1.11.567` of the SDK. I'll go ahead and close this, please feel free to reopen if you have any other questions.
