### ISSUE TITLE
AppStream 2.0 SDK with Region Support

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1652]
Hi
according to what I get, the AppStream 2.0 is not configured to be supported for region eu-central-1 (Frankfurt) at the SDK, while this service is supported for this region
calling region.isServiceSupported on region eu-central-1 return false, and I see that the configuration is not containing this region

**Comment by spfink** [comment]
Our endpoints.json file has not yet been updated to include eu-central-1 for AppStream 2.0. I've cut a request to one of our internal teams to get this data flowing into our SDK.

The service is available in-region and you can configure the SDK with that region with AppStream 2.0 and it will work.
