### ISSUE TITLE
Support returning updated item after save operation of DynamoDBMapper

### ISSUE THREAD

**Issue by jungseoklee** [aws/aws-sdk-java#1654]
There is a case where an item appearing after save operation is needed. In other words, a result of `updateItem` request setting `ReturnValue.ALL_NEW` is required in some context.

Since DynamoDBMapper does not support the above, we should load an item again for further save operations (please correct me if I am wrong here). A low-level client would be preferred unless the additional load operation is negligible.

Thus, I am wondering if DynamoDBMapper supports the following:

```
public <T> T save(T object);
```

I tried to search the same request or similar ones in [Refactor: Dynamo DB Mapper](https://github.com/aws/aws-sdk-java-v2/issues/35), but I could not find any.

Thanks in advance!

**Comment by ankurgupta4891** [comment]
Is there any plan to implement this feature?

**Comment by ajak6** [comment]
This should be implemented soon as the underlying API already supports it.

**Comment by debora-ito** [comment]
@jungseoklee @ankurgupta4891 @ajak6 

The SDK team has reviewed the feature request list for V1 and decided not to implement this one, as they're concentrating efforts on V2 new features. It's still being considered for the DynamoDB Mapper refactor in V2, I added it to the refactor tracking issue. I'll go ahead and close this.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.

**Comment by imjuoy** [comment]
Do we have any timeline on this? This would really help.
