### ISSUE TITLE
Pass "priority" field to SNS PublishRequest

### ISSUE THREAD

**Issue by kiteflo** [aws/aws-sdk-java#1655]
Currently we are facing the issue that our notifications sometimes are not displayed on certain 
 Android devices. It turns out that there is idle mode for these devices but according to the FCM documentation (https://firebase.google.com/docs/cloud-messaging/http-server-ref) it should be possible to pass a "priority" flag indicating that messages with data payload are displayed even the device is in idle mode.

Our issue: even we pass the priority flag to the PublishRequest, the priority flag never arrives at the Android client. For simplification I pasted what we "put IN" and what we "get OUT":

put IN (Server):

String msg = "{"GCM":"{\"collapse_key\":\"e153eb1e-b404-4b31-8199-6bc2b1e9626b\",\"priority\":\"high\",\"data\":{\"alert\":{\"body\":\"Our body\",\"title\":\"Our title\"},\"data\":\"{\\\"type\\\":\\\"QUIZ\\\",\\\"id\\\":\\\"2d151424-871b-477e-8ea8-d0b72e9f89fb\\\",\\\"url\\\":\\\"https://ourapi/api/stream/123456\\\"}\",\"badge\":1,\"sound\":\"default\"},\"delay_while_idle\":false,\"time_to_live\":172800,\"dry_run\":false}"}"
       
 PublishRequest request = new PublishRequest(
                msg,
                'json',
                'ourEndpointArn'
 )

get OUT (Android):

Bundle[{google.sent_time=1530165644083, google.ttl=172800, data={"type":"QUIZ","id":"12c77bf1-0fed-4c13-b7b4-270a0ddc29eb","url":"https://ourapi/api/stream/12c77bf1-0fed-4c13-b7b4-270a0ddc29eb"}, from=591603510782, alert={"body":"Our body","title":"Our title"}, badge=1, sound=default, google.message_id=0:1530165644086695%f709319f78ca69cc, collapse_key=1afbf896-3fd9-4b8a-97fa-ea1b45eea053}]

So where is the priority flag being "lost"? The same applies to the "delay_whil_idle" flag, we pass it to the PublishRequest but somehow the property is "eaten" and never arrives at the client.

Or do we totally misundertsand something and these properties are used by FCM "internally" and are never passed to the client?

Any help is highly appreciated. The whole issue here which is chalked out (Pushes not delivered to certain Android devices) is a really big issuse as it looks like there are a lot of messages lost due to this idle stuff and I am pretty sure we are not the only startup facing these issues...thanx a lot for your help!

Cheers,
Florian

**Comment by spfink** [comment]
Can you open a thread for this in the SNS forum:

https://forums.aws.amazon.com/forum.jspa?forumID=72

They would be the experts in SNS. This may be more specific to Android though but they should be able to better help narrow it down.
