### ISSUE TITLE
AmazonServiceException in Lambda

### ISSUE THREAD

**Issue by jianfangbhbbc** [aws/aws-sdk-java#1656]
Hello everyone here,

Can someone please answer my question, if Icatch an AmazonServiceException (so we can log it in our way), do I need to throw a RuntimeException after I catch it? Will it make difference on Lambda retrying  to run the function, with or without throwing a RuntimeException?

Thanks.

**Comment by spfink** [comment]
An AmazonServiceException is a RuntimeException so from that perspective, I would not think so.

However, do you have more details on the setup of your function? Lambda doesn't retry by default in most cases.

**Comment by zoewangg** [comment]
Closing due to no response. Feel free to reopen if you have any questions.

**Comment by jianfangbhbbc** [comment]
so actually, I decided not to catch the exception and let aws log and retry by default.
