### ISSUE TITLE
variable:"S3_HOSTNAME"

### ISSUE THREAD

**Issue by ererermao** [aws/aws-sdk-java#1660]
Can this variable "S3_HOSTNAME" be set to a variable on line 32 of [class](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/Constants.java) . 
Because we can't access s3.amazonaws.com, we can only visit s3.cn-north-1.amazonaws.com.cn

**Comment by shorea** [comment]
You can configure the client with the BJS region like so

```java
AmazonS3ClientBuilder.standard()
.withRegion(Region.CN_NORTH_1)
.build()
```
