### ISSUE TITLE
The specified bucket does not exist while using virtual-hosted–style URL as endpoint configuration

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java#1663]
s3Client = AmazonS3ClientBuilder.standard()
						.withEndpointConfiguration(new EndpointConfiguration(getServer(), s3Region))
						.withCredentials(loadCredentials()).build();

getServer() is of the form : bucket.s3-aws-region.amazonaws.com

when i use path styled url (s3-aws-region.amazonaws.com), it works fine.

**Comment by shorea** [comment]
The SDK will append the bucket to the endpoint for you, you should just set the s3 endpoint without the bucket in EndpointConfiguration. If you don't want virtual addressing for some reason you can enable path style via the builder.
