### ISSUE TITLE
Cognito JSON Web Token (JWT) Verification

### ISSUE THREAD

**Issue by EthanLozano** [aws/aws-sdk-java#1664]
The [Verifying a JSON Web Token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html) docs describe several steps for verifying id and access JWT's. The security of a developer's app depends on implementing these instructions correctly and without any vulnerabilities. It's easy to miss one of these steps. Missing a step negates most of the security that Cognito brings to an external application. There are a [handful](https://forums.aws.amazon.com/thread.jspa?messageID=787330&#787330) of instances online where someone incorrectly implements java JWT verification. It's a little unrealistic to expect every developer to implement this verification correctly.

Google has officially supported JWT verification for Google Sign-In within their ["Using a Google API Client Library"](https://developers.google.com/identity/sign-in/web/backend-auth).

Please provide an officially supported implementation of JWT verification!

**Comment by shorea** [comment]
Closing per comments in the PR.
