### ISSUE TITLE
DynamoDBMappingException on mapping Map<String, Object>attribute.

### ISSUE THREAD

**Issue by arammkrtchyan** [aws/aws-sdk-java#1668]
Hello guys,
I am trying to save the instance of this class into dynamdb but getting 
`DynamoDBMappingException: not supported; requires @DynamoDBTyped or @DynamoDBTypeConverted` exception.

@DynamoDBTable(tableName = "FulfillmentOrders")
public class FulfillmentOrder {

    @DynamoDBHashKey
    private String orderId;

    @DynamoDBAttribute
    @DynamoDBTyped(value = DynamoDBMapperFieldModel.DynamoDBAttributeType.M)
    private Map<String, Object> order;
    
    ....... 

}

could someone help, there is the problem here or maybe SDK doesn't support such kind of conversion ?

Thanks!

**Comment by zoewangg** [comment]
I think you need to provide a `DynamoDBTypeConverter` because dynamodb mapper doesn't know how to marshal and unmarshal `Object` in `Map<String, Object>`

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.ArbitraryDataMapping.html
