### ISSUE TITLE
AccessControlListHandler (parse XML) should have less strict about String case

### ISSUE THREAD

**Issue by philipzhaoTS** [aws/aws-sdk-java#1669]
Use JAXBContext and Marshaller, it will create something like:
`<Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="canonicalUser">
</Grantee>`

But this won't pass S3Client since it is case sensitive. I suggest when do the comparison, ignore the case. Changing the xsi:type="canonicalUser" to xsi:type="CanonicalUser" is very hard. Unless we do String.replace method.

https://github.com/aws/aws-sdk-java/blob/f2c2eb3abc5e58e50d1a3e0a03e1d2edfdbe339b/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/transform/XmlResponsesSaxParser.java#L1024

**Comment by zoewangg** [comment]
I guess there's something missing after your first sentence.
Could you clarify what you are trying to do?

**Comment by philipzhaoTS** [comment]
I guess the github does not render "<>" well. Updated.

**Comment by philipzhaoTS** [comment]
If my endpoint return this XML. Notice that "canonicalUser" is lowercase on "c". S3Client won't parse it correctly simple due to the case issue in the code.

**Comment by zoewangg** [comment]
Thanks for the update. If I understand it correctly, you are using the java sdk S3 xml unmarshaller to unmarshall the xml from your own service and then send the request to S3 through S3 client?

**Comment by philipzhaoTS** [comment]
Yes. I am using the JAXB xml marshaller to xml format. Example:
StringWriter stringWriter = new StringWriter();
JAXBContext context =JAXBContext.newInstance(GetAclResult.class, GetAclResult.CanonicalUser.class, GetAclResult.Group.class);
Marshaller marshaller = context.createMarshaller();
marshaller.setProperty(Marshaller.​JAXB_FORMATTED_OUTPUT, true);
marshaller.marshal(aclResult, stringWriter);

System.out.println(stringWriter.toString());

Note: I create the GetAclResult, GetAclResult.CanonicalUser, GetAclResult.Group class.

**Comment by shorea** [comment]
@philipzhaoTS can you provide more details about your use case? I'm not sure if this is something that we would want to support.

**Comment by philipzhaoTS** [comment]
I want to construct the XML response for S3 client to parse. One of challenging thing of constructing the XML in Java is that xsi:type="canonicalUser" while the S3 client parser would only accept xsi:type="CanonicalUser". I have not found a good way to work with JAXBContext/Marshaller to do upper case (unless you have some good pointer). 

Any reason that this is a challenge to support??

**Comment by shorea** [comment]
@philipzhaoTS this is not a use case we support. The unmarshallers are for unmarshalling the service response as S3 defines it. At a high level what problem are you trying to solve?

**Comment by shorea** [comment]
Closing this issue, it doesn't appear to be a use case we would want to support.
