### ISSUE TITLE
Missing aws-java-sdk-core-1.11.365 in both snapshots and release version.

### ISSUE THREAD

**Issue by omverma22** [aws/aws-sdk-java#1670]
Today morning we start getting issues related to version 1.11.365. Jar missing. We tried the following locations.

https://repo.spring.io/libs-release/com/amazonaws/aws-java-sdk-core/1.11.365/aws-java-sdk-core-1.11.365.jar

https://repo.spring.io/libs-snapshots/com/amazonaws/aws-java-sdk-core/1.11.365/aws-java-sdk-core-1.11.365.jar

Please help !

Thanks,
Op

**Comment by zoewangg** [comment]
The first link works for me.

You can also download from:
https://aws.amazon.com/sdk-for-java/

**Comment by omverma22** [comment]
Thanks for your reply. We have downloaded the jar and used it with our repo. But how come, version has been increased and jar still missing. I can see the metadata entries in local maven configuration, vesion 1.11.365 has been added. But when it try to download the jar from snapshots, it throws error 404 jar missing.

I never get such issues before.

Thanks,
Op

**Comment by zoewangg** [comment]
I think the correct link for the snapshot is:

https://repo.spring.io/libs-snapshot/com/amazonaws/aws-java-sdk-core/1.11.365/aws-java-sdk-core-1.11.365.jar

Note, `libs-snapshot` rather than `libs-snapshots`

**Comment by omverma22** [comment]
OK Thanks. I tried the with snapshots too, but it was not working. Now it seems jars are there.

Thanks,
Op

**Comment by omverma22** [comment]
Again getting the issue. See the below urls. Not sure why such issues are coming very frequently. Now new version is 1.11.367. But jars are not there.

https://repo.spring.io/libs-snapshot/com/amazonaws/aws-java-sdk-core/1.11.367/aws-java-sdk-core-1.11.367.jar

https://repo.spring.io/libs-snapshots/com/amazonaws/aws-java-sdk-core/1.11.367/aws-java-sdk-core-1.11.367.jar

Thanks,
Op

**Comment by zoewangg** [comment]
Hmm, https://repo.spring.io/libs-snapshot/com/amazonaws/aws-java-sdk-core/1.11.367/aws-java-sdk-core-1.11.367.jar works for me now.

My guess is that it takes some time for the jar to be downloadable in repo.spring.io site. If you want the latest released jar right away, you can download from this link: https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip

**Comment by omverma22** [comment]
Thanks.
