### ISSUE TITLE
Glue api for Scala not available

### ISSUE THREAD

**Issue by alexandredantas** [aws/aws-sdk-java#1671]
I'm trying to write a glue script outside AWS script editor but dependencies for Scala API are missing.
Where can I find the dependency providing classes like com.amazonaws.services.glue.GlueContext, com.amazonaws.services.glue.MappingSpec and com.amazonaws.services.glue.ResolveSpec?

PS 1: Looks like issue #1517 is related
PS 2: For python I can find the library under  https://github.com/awslabs/aws-glue-libs

**Comment by zoewangg** [comment]
Since this is a glue question, could you post this question on https://github.com/awslabs/aws-glue-libs or AWS forum https://forums.aws.amazon.com/forum.jspa?forumID=262&start=0? The service team might have better knowledge than us.
