### ISSUE TITLE
SQS Message Attributes enum or constant?

### ISSUE THREAD

**Issue by dotCipher** [aws/aws-sdk-java#1672]
I noticed that you guys modeled the [QueueAttributeName](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/QueueAttributeName.java) as an enum, but there is no enum for the standard 'known' `MessageAttributeName`s that can be returned from a `ReceiveMessageRequest`.

I realize this might be due to the nature of custom MessageAttributes being returned, but it would be nice to at least have an enum construct containing all the known values (ie the ones documented in the internal [Message.attributes](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/Message.java#L62) variable.

Are there any plans to include an enum with said values? or provide said values to the consumer of this SDK is some way?  I find myself rewriting code a bunch to work around this (ie. providing a subset of `All` / `.*` containing only known `MessageAttributeName`s, like: [`SenderId`,`SentTimestamp`])

**Comment by zoewangg** [comment]
All the models are generated based on the service model files. Unfortunately, it would be backward incompatible if we change the type to an enum at this point.

**Comment by dotCipher** [comment]
Ah ok, that generally makes sense.  Fair enough!  Closing for now.
