### ISSUE TITLE
Missing classes used for authoring Glue jobs with Scala/Java

### ISSUE THREAD

**Issue by rgduncan** [aws/aws-sdk-java#1675]
I need the below classes to write glue jobs but I can't find them anywhere. What is going on? Why aren't these in this project?

```
import com.amazonaws.services.glue.util.JsonOptions
import com.amazonaws.services.glue.{DynamicRecord, GlueContext}
```

**Comment by varunnvs92** [comment]
We don't own these classes. It looks like these are maintained by the service team itself. I could not find the source for these classes. Please open issues in the following repos (these are the closest match i could find):
https://github.com/aws-samples/aws-glue-samples
https://github.com/awslabs/aws-glue-libs
