### ISSUE TITLE
TransferManager Copy across different regions issue.

### ISSUE THREAD

**Issue by ernakulgoyal** [aws/aws-sdk-java#1676]
I am trying to copy objects between two buckets (being in different region) using TransferManager SDK, I am not getting any exception but also object does not gets copied on target location.

Can you guys please share a snippet, link to do the same. Any leads will be highly appreciable.

Thanks in advance.

**Comment by shorea** [comment]
@ernakulgoyal the code below worked for me.

```java
    public static void main(String[] args) throws InterruptedException {
        AmazonS3 sourceS3 = AmazonS3ClientBuilder.standard()
                                                 .withRegion(SOURCE_REGION)
                                                 .build();
        AmazonS3 destintationS3 = AmazonS3ClientBuilder.standard()
                                                       .withRegion(DESTINATION_REGION)
                                                       .build();

        TransferManager transferManager = TransferManagerBuilder.standard()
                                                                .withS3Client(destintationS3)
                                                                .build();

        Copy copy = transferManager.copy(new CopyObjectRequest(SOURCE_BUCKET_NAME, SOURCE_KEY,
                                                               DESTINATION_BUCKET_NAME, DESTINATION_KEY),
                                         sourceS3, null);


        copy.waitForCopyResult();
        transferManager.shutdownNow();
        sourceS3.shutdown();
        destintationS3.shutdown();
    }
```

**Comment by ernakulgoyal** [comment]
@shorea Thanks for your reply, it helped me, a bit I want to understand if this works without bucket permissions or with permissions (buckets across different accounts i.e. account A->B and vice-versa) as I don't find any precise documentation which one should follow (since this a very common use case). It would be really great if you could share more on this, Thanks anyways, appreciate it.

**Comment by shorea** [comment]
Copying across accounts is possible with the right permissions. This guide has some good details on that, https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example2.html

As far as permissions, we call getObjectMetadata (or HEAD Object) on the source s3 client. And on the destintation s3 client (the one you create Transfer Manager with) we either call just copyObject (PUT Object - COPY) if we are copying in one chunk or initiateMultipartUpload then copyObjectPart (Upload Part - Copy) then completeMultipartUpload.

**Comment by shorea** [comment]
@ernakulgoyal does this answer your question?

**Comment by ernakulgoyal** [comment]
Suppose, I have two AWS accounts A & B,

A have ACL: -  
List objects | Write objects | Read bucket permissions | Write bucket permissions
on a bucket created in account B.

B have ACL Write objects | Write bucket permissions  on a bucket created in account A.
(ACLs have been granted from java code)
I can see it on AWS console.

Still I am unable to transfer data from bucket in B to bucket in A account.

It would be great if you can help on this.

**Comment by ernakulgoyal** [comment]
I am getting com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID.

I am able to transfer files from account A to B (buckets are in different region), but not able to transfer files from B to A.

I tried attaching bucket policy to the bucket in account A, but its throwing exception when buckets are in different region.

**Comment by ernakulgoyal** [comment]
@shorea Could you please update on this. It will really appreciate. Thanks in advance.

**Comment by zoewangg** [comment]
@ernakulgoyal  Can you share the sample code of how you attach the bucket policy?

**Comment by ernakulgoyal** [comment]
A sample snippet to set ACL.
With above snippet I am able to transfer data from source bucket to destination bucket but not able to achieve reverse of it.
Also I tried giving bucket policy from console, but it didn't worked (was giving access denied).

@zoewangg @shorea It would really be great if you guys could share a possible solution to it. 

After reading some issues on GIT regarding Transfer Manager, would you please also share the tentative next release date of Transfer Manager Java API?

**Comment by ernakulgoyal** [comment]
@zoewangg @shorea It would be really great if you could suggest a way out of it?

**Comment by spfink** [comment]
Have you verified via the AWS Console that the applied ACLs to each bucket are referencing the correct buckets and AWS account Ids?

**Comment by shorea** [comment]
@ernakulgoyal are you still having issues?

**Comment by ernakulgoyal** [comment]
@shorea I found a way out of it, I suggest this should be documented as its a very common use case one would try with AWS SDK.

**Comment by varunnvs92** [comment]
@ernakulgoyal 
Please post your findings and how you fixed the issue. We would look into updating our examples to add this. Thank you.

**Comment by zoewangg** [comment]
Closing the issue, feel free to reopen if you have further questions/issues.
