### ISSUE TITLE
Limit Issue

### ISSUE THREAD

**Issue by wal31** [aws/aws-sdk-java#1679]
Hey I'm using the Java AWS SDK to loop through a bucket that has almost 500,000 files and performs some operations on them. For some reason the program stops at a certain file and never goes beyond that file. Is that because there's a limit to the amount of files the java sdk can access?

**Comment by shorea** [comment]
Can you provide sample code that reproduces the problem?

**Comment by wal31** [comment]
thank you for responding but nvm I just found out that there was a limit of 1000 keys on objectlisting objects.

**Comment by shorea** [comment]
Glad you figured it out! Thanks for closing :)
