### ISSUE TITLE
Need DynamoDB.marshallIntoObject() or alternative

### ISSUE THREAD

**Issue by kenklin** [aws/aws-sdk-java#168]
My DynamoDB has a heterogenous mix of items mapped from _different_ Java classes.  The classes all implement a common base interface that contains a "type" data member containing the object's simple class name.  The Java "type" data member is mapped into a DynamoDB attribute, "type", which I use for instanceof marshalling.

I use the deprecated DynamoDBMapper.**marshallIntoObject(Class, Map)** to nicely map db items into a collection of Java objects using a fragment something like this ,,,

```
QueryResult result = dynamo.query(queryRequest);

Iterator<Map<String, AttributeValue>> items = result.getItems().iterator();
while (items.hasNext()) {
    Map<String, AttributeValue> itemAttributes = items.next();
    String type = itemAttributes.get("type").getS();

    // See implementation of DynamoDBMapper.load()
    if (type.equals("User")) {
        collection.add(mapper.marshallIntoObject(User.class, itemAttributes));
    } else if (type.equals("Contact")) {
        collection.add(mapper.marshallIntoObject(Contact.class, itemAttributes));
    }
}
```

Can you provide me a non-deprecated means to access this lower level marshalling functionality, presumably by either ...
1) Un-deprecating the signature above, or
2) Making toParameters(itemAttributes, clazz, this.config) public, or
3) Some other means?

Thanks in advance,
Ken

**Comment by dimPhotobox** [comment]
Hello, 

what is the official strategy/policy to fetch/load/query :

- A list of entities which are polymorphic (1 root class with common properties whose a dedicated "type" one (declaring a discriminant value for subtypes) + n subclasses with additional specifics properties)
- a root entity owning a list of polymorphic entities (previous line)

sorry (to post here) but it is a little bit confusing, and quite difficult to find the appropriate information...

Sincerely

i42

**Comment by manikandanrs** [comment]
@dimPhotobox 

Can you please open a new issue in this repository ? Also please provide a description of the use case that you are trying to do and any code if applicable. This would help us in responding better.
