### ISSUE TITLE
S3 presigned upload url <HeadersNotSigned> error

### ISSUE THREAD

**Issue by wildthing81** [aws/aws-sdk-java#1680]
I am trying to perform a document upload using an S3 pre-signed POST url. I generated the url via AWS SDK for java (**GeneratePresignedUrlRequest.java**). This url generation code sits in a lambda function behind AWS API gateway.

However I am getting the following error when I copy the generated url in Postman & try to perform an upload.

`<Error>
<Code>AccessDenied</Code>
<Message>
There were headers present in the request which were not signed
</Message>
<HeadersNotSigned>host</HeadersNotSigned>
<RequestId>6E624EC66091A099</RequestId>
<HostId>
9HnUUZpa9zUWfyzuNrZtRkoN2CYxH8V6rqx5QgsMFC6foTZKuG5qmZL5ThnUXooYPk2reFzKKUg=
</HostId>
</Error>`

The generated url is "https://<**_bucket_**>.s3.amazonaws.com/<**_key_**>?X-Amz-Security-Token=<**_value_**>&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20180718T013339Z&X-Amz-SignedHeaders=content-type%253Bhost&X-Amz-Expires=1799&X-Amz-Credential=<**_value_**>&X-Amz-Signature=<**_value_**>

**Comment by shorea** [comment]
Can you try with PUT? The documentation doesn't explicitly state that POST is supported

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.java#L234

**Comment by shorea** [comment]
Did PUT work for you?

**Comment by shorea** [comment]
Closing issue, feel free to reopen if suggestion above does not meet your needs.
