### ISSUE TITLE
Question: How to use dynamic DynamoDB table name when using scan?

### ISSUE THREAD

**Issue by BigChief45** [aws/aws-sdk-java#1681]
I currently have a domain class that is annotated so that objects can be instantiated when running a scan on the DynamoDB table:

```java
@DynamoDBTable(tableName = "my-table")
public class MyObject {
    // ...
}
```
```java
DynamoDBMapper mapper = new DynamoDBMapper(dynamoClient);
List<MyObject> itemList = mapper.scan(MyObject.class, new DynamoDBScanExpression());
```

That works great as expected. However, I am trying to introduce multiple AWS environment configurations in my application using **enums**, so I would like the DynamoDB table name to be a dynamic value. However this seems to be not possible when using the `@DynamoDBTable` annotation.

What is the way around this issue?

**Comment by shorea** [comment]
See https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.java#L233
