### ISSUE TITLE
aws s3 ls --recursive in S3 SDK.

### ISSUE THREAD

**Issue by sushilkumarchaudhary** [aws/aws-sdk-java#1686]
folks, 
is there recursive way to listObjects using Amazon SDK.

**Comment by shorea** [comment]
Is this what you are looking for?

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/iterable/S3Objects.java

**Comment by sushilkumarchaudhary** [comment]
Probably. Is the public Iterator<S3ObjectSummary> iterator() I can use to iterate through all the folder/file inside a given s3 path?

**Comment by sushilkumarchaudhary** [comment]
Probably. Is the Iterator iterator() I can use to iterate through all the folder/file inside a given s3 path? Does it do recursive iteration in each and every directory.

**Comment by sushilkumarchaudhary** [comment]
Also, I do not the iterator to iterate. Instead get the list of everything under a folder.

**Comment by shorea** [comment]
@sushilkumarchaudhary S3 doesn't really have the concept of a folder, it's a key/object store. That said certain tools interpret slashes in key names as folders or directories. You can limit the iteration to a specific prefix which is like limiting to a certain folder.

**Comment by sushilkumarchaudhary** [comment]
Since aws CLI has option to pass —reclusive to get the Recursive listing, I was just thinking if SDK has some function on same line. 

Thanks for the clarifying.

**Comment by shorea** [comment]
Sure thing!
