### ISSUE TITLE
AmazonS3ClientBuilder.standard() returns null

### ISSUE THREAD

**Issue by egurinGH** [aws/aws-sdk-java#1687]
Hello there. 
After updating aws-java-sdk-s3 from 1.11.104 to 1.11.137 (or even 1.11.372) I started to get NullPointer calling **AmazonS3ClientBuilder.standard().withRegion(rName).build();**  
AmazonS3ClientBuilder.standard() return **null** in  1.11.137 (or 1.11.372)

Is there any precondition that should be met to prevent this NPE?

Regards,
Eugene.

**Comment by shorea** [comment]
Can you provide the stack trace? I'd say the most likely cause is mismatched versions of aws-java-sdk-s3 and aws-java-sdk-core.

**Comment by egurinGH** [comment]
I found an issue and it was related to invalid config (version missmatch). Thank for you help!

**Comment by Luharkk** [comment]
Hi **egurinGH** can you please specify what changes you have made?. I am also facing the same issue.Please help me on this.
