### ISSUE TITLE
SQS Message request must contain non-empty message attribute type

### ISSUE THREAD

**Issue by houseofdouglas** [aws/aws-sdk-java#1692]
Am I using the chain building in the wrong way?

/Library/Java/JavaVirtualMachines/jdk1.8.0_131
<aws.sdk.version>1.11.372</aws.sdk.version>

`com.amazonaws.services.sqs.model.AmazonSQSException: The message attribute 'HTTPStatus' must contain non-empty message attribute type.`

```
SendMessageRequest request = new SendMessageRequest()
                        .withQueueUrl(SQS_DEADLETTER_QUEUE)
                        .withMessageBody(new String(dataEvent))
                        .addMessageAttributesEntry("HTTPStatus",
                                new MessageAttributeValue().withStringValue(String.valueOf(sfmcDataEvents.getResponseCode())));
getSQSClient().sendMessage(request);
```

<img width="542" alt="screen shot 2018-07-24 at 10 30 18 am" src="https://user-images.githubusercontent.com/270671/43152755-a0513812-8f2c-11e8-9f5d-c371e2041043.png">

**Comment by zoewangg** [comment]
Looks like you need to set the datatype of the MessageAttributeValue. https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_MessageAttributeValue.html 

```java
 .addMessageAttributesEntry("HTTPStatus",
           new MessageAttributeValue()
                    .withDataType("String")
                    .withStringValue("200")));
```

**Comment by houseofdouglas** [comment]
Thanks @zoewangg, I had assumed that the datatype would be set to 'String' with that call as well. Thanks for the quick response!
