### ISSUE TITLE
Documentation: AWS IoT metric description and metric values on Cloudwatch mismatches

### ISSUE THREAD

**Issue by gangadharaswamy** [aws/aws-sdk-java#1693]
In [AWS IoT Metrics and Dimensions](https://docs.aws.amazon.com/iot/latest/developerguide/metrics_dimensions.html) page, all metrics description says count. But on Cloudwatch graphs all metrics values are in status (1 or 0).
Why is this difference? Is it possible to get actual count values instead of status while invoking metric values through APIs?

**Comment by zoewangg** [comment]
Since this is more like a service specific question, could you post it on AWS forum, https://forums.aws.amazon.com/forum.jspa?forumID=210 or Stackoverflow? The service team might have better knowledge than us.
