### ISSUE TITLE
S3 Complete Multipart Upload Request

### ISSUE THREAD

**Issue by visualpaper** [aws/aws-sdk-java#1694]
The documentation of aws sdk has the following description

https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/API/mpUploadComplete.html#mpUploadComplete-responses

Processing of a Complete Multipart Upload request could take several minutes to complete. After
Amazon S3 begins processing the request, it sends an HTTP response header that specifies a 200 OK
response. While processing is in progress, Amazon S3 periodically sends whitespace characters to keep
the connection from timing out. Because a request could fail after the initial 200 OK response has
been sent, it is important that you check the response body to determine whether the request
succeeded.

Is this specification hidden within AmazonS3.completeMultipartUpload?

If you want to control whitespace capture, do you need to implement it from your own HTTP request without using aws - sdk?

**Comment by zoewangg** [comment]
Not sure if I understand the question. Could you clarify what you are trying to achieve?

**Comment by visualpaper** [comment]
I solved the problem and I will close it.
