### ISSUE TITLE
S3 ContinuationToken is not send to backend

### ISSUE THREAD

**Issue by philipzhaoTS** [aws/aws-sdk-java#1695]
When I use the following code:

        ListObjectsRequest request = new ListObjectsRequest();
        request.setBucketName("test-bucket-17");
        request.setMaxKeys(2);
        request.setPrefix("/my/lame/");
        
        ObjectListing listResult = s3client.listObjects(request);
        request.setMarker(listResult.getNextMarker());
        
        listResult = s3client.listObjects(request);

When I inspect the outgoing Query parameters, I observe this:

http://localhost:42823/test-bucket-17/?prefix=%2Fmy%2Flame%2F&marker=%2Fmy%2Flame%2Fkey%2Fb&max-keys=2

Notice that marker in the query parameter is not "continuation-token" as described in the document here:
https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

Is this the expected behavior? Should the SDK to send query parameter as marker= or continuation-token=

**Comment by zoewangg** [comment]
The code you provided above is actually calling `ListObjects V1` API and it is `marker` according to the docs
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html

If you want to use `ListObject V2` api, you need to call `s3.listObjectsV2(...)`

**Comment by philipzhaoTS** [comment]
Yep, thanks for the help.
