### ISSUE TITLE
AWS Glue Service APIs not available. GlueContext Missing!

### ISSUE THREAD

**Issue by swapnonil** [aws/aws-sdk-java#1698]
Hi,

None of the classes inside com.amazonaws.services.glue.* are available inside this SDK, which prevents developers from using the local IDE for development. For example, this https://github.com/aws-samples/aws-glue-samples/blob/master/examples/ResolveChoice.scala cannot be written or compiled in your IDE. The workaround is to download  s3://aws-glue-jes-prod-us-east-1-assets/etl/jars/glue-assembly.jar and add it as a provided jar to SBT or Maven.

For SBT use this for example to add a local jar.
libraryDependencies += "com.amazonaws.services.glue" % "glue-services" % "1.0" from "file:///C:/Users/myusername/Downloads/glue-assembly.jar"

However this jar file is 368 MB in size. Surely Amazon must release these Scala classes as a Maven dependency.

**Comment by millems** [comment]
Similar issue: https://github.com/aws/aws-sdk-java/issues/1675

I've found this issue on the glue repo that complains about it not being available in Maven: https://github.com/aws-samples/aws-glue-samples/issues/21#issuecomment-405041473

Let me follow up with the glue developers to see if they have any news on getting this out to maven.

**Comment by millems** [comment]
I've passed the feedback onto glue that it should be released to maven.

**Comment by mbragg02** [comment]
Hi, is there any update on this? Id like to supply my own library the uses the Glue service APIs and downloading the assembly jar and including it is not really an option.

**Comment by Lempiraholio** [comment]
@mbragg02 you can download the Glue jar and add it as a local dependency of your project.

`aws s3 cp s3://aws-glue-jes-prod-us-east-1-assets/etl/jars/glue-assembly.jar glue-assembly.jar`

**Comment by VikasGite** [comment]
We still do not have maven release for GlueContext.

**Comment by CallMeBW** [comment]
Check this out:
https://aws.amazon.com/about-aws/whats-new/2019/08/aws-glue-releases-binaries-of-glue-etl-libraries-for-glue-jobs/

It is available now.

**Comment by nemo83** [comment]
Does anyone manage to get it working with version 2.0.0. I am using sbt/scala and it fails to download ti artifact:

[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.amazonaws:AWSGlueETL:2.0.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/gio/.ivy2/local/com.amazonaws/AWSGlueETL/2.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom
[error]   not found: https://aws-glue-etl-artifacts.s3.amazonaws.com/release/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom
