### ISSUE TITLE
java.lang.NoSuchFieldError: SIGNING_REGION Exception from AmazonElasticLoadBalancingClient

### ISSUE THREAD

**Issue by sidswnt** [aws/aws-sdk-java#1700]
**Exception thrown** :  java.lang.NoSuchFieldError: SIGNING_REGION
**Code Snippet** :

```
com.amazonaws.services.elasticloadbalancingv2.AmazonElasticLoadBalancing client = com.amazonaws.services.elasticloadbalancingv2.AmazonElasticLoadBalancingClientBuilder.standard().build();
DescribeTargetGroupAttributesRequest describeTargetGroupAttributesRequest = new DescribeTargetGroupAttributesRequest();
describeTargetGroupAttributesRequest.setTargetGroupArn(getTargetGroupARN());
DescribeTargetGroupAttributesResult describeTargetGroupAttributesResult = client.describeTargetGroupAttributes(describeTargetGroupAttributesRequest); 
```

**SDK Dependency**: aws-java-sdk-elasticloadbalancingv2-1.11.285

**Comment by millems** [comment]
This indicates a mismatched core / client combination. The version of core must be the same or newer than the client version. Can you see if the debugging steps followed here help identify the issue? https://github.com/aws/aws-sdk-java/issues/1540

Let me know if you have any questions or need help!

**Comment by dagnir** [comment]
Hi @sidswnt per @millems's response, this appears to be a version mismatch between the client and core. Ensure that they're the same (`1.11.285` in this case) should fix this. Please feel free to reopen if this does not fix your issue.
