### ISSUE TITLE
Why not InstanceProfileCredentialsProvider use daemon thread to refresh?

### ISSUE THREAD

**Issue by markbooch** [aws/aws-sdk-java#1702]
When using InstanceProfileCredentialsProvider, application come into endless. All other daemon thread cannot terminate normally.

I saw in the constructor of InstanceProfileCredentialsProvider, you have init a scheduledThreadPool, but didn't give the threadFactory to change threads to daemon.
`executor = Executors.newScheduledThreadPool(1);
`
Is there any consideration for this implementation? Is there anyway to avoid using sys.exit to terminate all threads?

**Comment by dagnir** [comment]
@markbooch Can you provide example code of how you're using the credentials provider? The provider implementation has a `close()` method that will shut down the executor service.

https://github.com/aws/aws-sdk-java/blob/46c00efdd9240d2d20d734f806dcc71506af6e0f/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceProfileCredentialsProvider.java#L177-L182

**Comment by shorea** [comment]
@markbooch I don't see a problem with making it a daemon thread. We do the same for the STS provider which does a similar async refresh (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/RefreshableTask.java#L63). If you want to submit a PR I'd be happy to merge it.
