### ISSUE TITLE
Remove ThreadLocal use

### ISSUE THREAD

**Issue by davidmoten** [aws/aws-sdk-java#1704]
Following on from #934.

When the aws-sdk-java (any component) is used in a container like Glassfish or Tomcat a SEVERE/ERROR entry is written to the log whenever a webapp is bounced/redeployed or the container shutdown. Here's the error (glassfish):

```java
[2016-12-06T12:07:12.369-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=113 _ThreadName=admin-listener(6)] [timeMillis: 1481044032369] [levelValue: 1000] [[
  The web application [/XYZ] created a ThreadLocal with key of type [com.amazonaws.auth.AbstractAWSSigner$1] (value [com.amazonaws.auth.AbstractAWSSigner$1@39054dd0]) and a value of type [java.security.MessageDigest.Delegate] (value [SHA-256 Message Digest from SUN, <initialized>
]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]

[2016-12-06T12:07:12.371-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=113 _ThreadName=admin-listener(6)] [timeMillis: 1481044032371] [levelValue: 1000] [[
  The web application [/XYZ] created a ThreadLocal with key of type [com.amazonaws.auth.SigningAlgorithm$1] (value [com.amazonaws.auth.SigningAlgorithm$1@396e15e3]) and a value of type [javax.crypto.Mac] (value [javax.crypto.Mac@411308ff]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]
```
The ThreadLocals above are not actually memory leaks according to discussion in #918 and I am happy with the reasoning. 

However, we monitor for the existence of SEVERE log lines and raise on-call alerts when seen so I'd like to remove this red-herring so that I can monitor normally and so that we don't waste peoples time when they see the error report in their container logs.

The ThreadLocal use is in the classes [`AbstractAWSSigner.java`](https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AbstractAWSSigner.java) (SHA-256 `MessageDigest`) and [`SigningAlgorithm.java`](https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/auth/SigningAlgorithm.java) (SHA-1 and SHA-256 Mac instances).

Ideally we remove the use of ThreadLocals. I've investigated this and benchmarked the effect of removing them.

For the AbstractAWSSigner case I ran JMH benchmarks that created and applied a MessageDigest instance to an 8 byte array in these variants:
* create a new MessageDigest instance and apply it to bytes
* clone an existing MessageDigest instance an apply it to bytes
* get a ThreadLocal MessageDigest, reset it and apply it to bytes

Here are the results:
```
Benchmark                                     Mode  Cnt        Score       Error  Units
DigestBenchmarks.createNewDigestAndUse       thrpt   10  1368554.701 ± 17528.805  ops/s
DigestBenchmarks.cloneMessageDigestAndUse    thrpt   10  1529761.626 ±  3525.232  ops/s
DigestBenchmarks.getThreadLocalDigestAndUse  thrpt   10  1648388.630 ±  9248.017  ops/s
```

For starters, creating a new MessageDigest every time is still very fast (1.4 million a second) and is 83% as fast as using the ThreadLocal version. Note that I was using a very small byte array as input and the margin between the methods would very likely reduce as the array size increases.

We should also bear in mind that we are applying the MessageDigest in an I/O context (network calls) and the overhead of creating one MessageDigest to service a network call is ridiculously small in comparison to the network overhead.

I included the clone case out of interest but I shy away from that one as implementing clone is not mandatory and different JVMs may differ.

**Would the team be open to a PR from me where we create a new MessageDigest instance every time?** I'd be happy to benchmark the Mac cases as well.

Here's the benchmarking code:
```java
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import org.openjdk.jmh.annotations.Benchmark;

public class DigestBenchmarks {

    private static final byte[] input = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 };
    private static final ThreadLocal<MessageDigest> messageDigestThreadLocal = new ThreadLocal<MessageDigest>() {
        @Override
        public MessageDigest initialValue() {
            return createMessageDigest();
        }
    };
    private static final MessageDigest messageDigest = createMessageDigest();
 
    @Benchmark
    public byte[] createNewDigestAndUse() throws NoSuchAlgorithmException {
        MessageDigest d = MessageDigest.getInstance("SHA-256");
        return d.digest(input);
    }

    @Benchmark
    public byte[] getThreadLocalDigestAndUse() throws NoSuchAlgorithmException {
        MessageDigest d = messageDigestThreadLocal.get();
        d.reset();
        return d.digest(input);
    }
    
    @Benchmark
    public byte[] cloneMessageDigestAndUse() throws NoSuchAlgorithmException {
        MessageDigest d;
        try {
            d = (MessageDigest) messageDigest.clone();
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
        return d.digest(input);
    }

    private static MessageDigest createMessageDigest() {
        try {
            return MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by davidmoten** [comment]
Ran a benchmark for creation of `Mac` object and can create 3.5m objects a second using either SHA1 or SHA-256 algorithms. Did not bother applying Mac object, just created new one.

Benchmark code:
```java
    @Benchmark
    public Mac createNewMacSHA1AndUse() throws NoSuchAlgorithmException {
        return createMac("HmacSHA1");
    }
    
    @Benchmark
    public Mac createNewMacSHA256AndUse() throws NoSuchAlgorithmException {
        return createMac("HmacSHA256");
    }
    private static Mac createMac(String algorithm) {
        try {
            return Mac.getInstance(algorithm);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
```

Result:
```
Benchmark                                   Mode  Cnt        Score       Error  Units
DigestBenchmarks.createNewMacSHA1AndUse    thrpt   10  3559850.884 ± 25016.474  ops/s
DigestBenchmarks.createNewMacSHA256AndUse  thrpt   10  3619130.052 ±  8778.732  ops/s
```
Looks like no significant performance advantage (in our context) to using ThreadLocal for Hmac either.

**Comment by dagnir** [comment]
Thanks for the detailed report! I definitely think it would be nice to remove as many uses of `ThreadLocal`s as possible. Can you share some more information on your testing setup? E.g. JVM version, OS, etc?

I think we'll want to do some multithreaded testing and with varying/randomized inputs as well.

**Comment by davidmoten** [comment]
>Can you share some more information on your testing setup? E.g. JVM version, OS, etc?
JMH header:
```
# JMH version: 1.21
# VM version: JDK 1.8.0_171, Java HotSpot(TM) 64-Bit Server VM, 25.171-b11
# VM invoker: /usr/lib/jvm/java-8-oracle/jre/bin/java
# VM options: -Xmx512m
# Warmup: 4 iterations, 10 s each
# Measurement: 10 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time
```
OS: Ubuntu 14.04.5 LTS

>I think we'll want to do some multithreaded testing and with varying/randomized inputs as well.

Multithreaded testing should not be necessary given that every call will get a new instance. If we had retained the ThreadLocal approach there were some untested paths (like a cached MessageDigest needs to be reset before reuse) but now the approach is simpler and actually needs less testing for full coverage. See #1706 for details of the changes. 

I'd also add the testing with varying/randomized inputs may not be necessary either because this small investigation makes it clear we are talking about object creation and any possible lazy initialization taking order of microseconds. If we were calling this hundreds of thousands of times in a loop this might be relevant but our context is applying this once per network call. Happy to test more inputs but not sure that it tells us anything useful.

**Comment by dagnir** [comment]
@davidmoten Ah yeah I agree. Now that I think about it more, I don't think those additional testing scenarios will help either.

I'll take a look at this and the PR tomorrow when I get back in the office 👍

**Comment by dagnir** [comment]
Hi @davidmoten it appears there are at least a few situations where this might be a performance regression for customers; at least [this SO post](https://stackoverflow.com/questions/25321187/java-mac-getinstance-for-hmacsha1-slow) (and linked posts within) suggest that in some configurations (e.g. Oracle vs Open JDK, `/etc/hosts` configuration, number of files in `java.io.tmpdir`) this could be a performance regression. 

I think we may need to do more digging and verification for this.

**Comment by davidmoten** [comment]
Complications, drat! I'll have a look around as well.

**Comment by davidmoten** [comment]
@dagnir if there is doubt we could continue to use `ThreadLocal` by default but support configuration to turn caching off (e.g. via system properties). I can adjust PR to reflect this. I'd probably have separate props for each `ThreadLocal` case.

**Comment by davidmoten** [comment]
>Do you mean one property to control caching for each of AbstractAWSSigner and SigningAlgorithm, or for Mac and MessageDigest caching?

Ideally for Mac and MessageDigest caching in general. Is that practical?

**Comment by davidmoten** [comment]
I assume [SDKJavaGlobalConfiguration.java](https://github.com/aws/aws-sdk-java/blob/e377144ed99b69515c6b481802b2c1e03b2575a5/aws-java-sdk-core/src/main/java/com/amazonaws/SDKGlobalConfiguration.java) might be relevant if we go ahead.

**Comment by davidmoten** [comment]
@dagnir How are we going on this one? I could update the PR with System property enablement if it helps consideration of the issue.

**Comment by dagnir** [comment]
Hi @davidmoten I discussed your proposal with the team and a couple concerns were brought up.

Since `ThreadLocal`s are used to cache other things in the SDK (e.g. `XMLInputFactory`), if these other components get brought into yours or other customers' applications over time, these will cause the false alarm log lines to get appear again.

For the rest of those classes that we use `ThreadLocal`s for, as well as any new ones in the future, they would need to be checked/tested to see if it would also make sense (i.e. cheap enough to create on each invocation) to give them these "disable" properties. If we had one for each type then it would mean a lot of additional system properties.

There are some ideas being discussed that we think could provide a more robust solution to this. One is to give customers the ability to provide a "registry" for `ThreadLocal`s that would ultimately allow them to call the `remove` method on them. This would allow you to avoid the warnings for both expensive and inexpensive classes.

For now, is it possible for you to suppress these `ThreadLocal` warnings from being emitted in your logs?

**Comment by davidmoten** [comment]
Thanks for discussing it @dagnir.

I agree that the system properties idea is not ideal for the reasons you mentioned.

The registry idea has legs I think but should be under the covers. I'd suggest that internally the SDK tracks its ThreadLocal usage on the current thread and a call to one static method like 'AwsSdk.clearThreadLocals()` or `AwsSdk.resetCaches()` or whatever, could be optionally made by the client after a chunk of single threaded AWS interaction. 

>For now, is it possible for you to suppress these ThreadLocal warnings from being emitted in your logs?

Yes that is possible but  is not ideal longer term because some ThreadLocal warnings can really represent a memory leak and they each should be assessed individually. My preference is that I can optionally force the SDK to clean up its own ThreadLocals.

Happy to knock up a PR if desired.

**Comment by davidmoten** [comment]
Another ThreadLocal that could cause a memory leak is this one (from `com.amazonaws.util.XmlUtils`):

```java
[2018-08-16T03:29:50.514+0000] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=998 _ThreadName=RunLevelControllerThread-1534390188803] [timeMillis: 1534390190514] [levelValue: 1000] The web application [/cobham-receiver] created a ThreadLocal with key of type [com.amazonaws.util.XmlUtils$1] (value [com.amazonaws.util.XmlUtils$1@53d8d34f]) and a value of type [com.ctc.wstx.stax.WstxInputFactory] (value [com.ctc.wstx.stax.WstxInputFactory@7929bb03]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```
In particular the ThreadLocal value is from the webapp classloader (being of type `com.ctc.wstx.stax.WstxInputFactory`) so I assume the webapp classloader cannot be garbage collected unless this thread is garbage collected (thread renewal may help eventually).

**Comment by millems** [comment]
We just talked about the `SdkThreadLocals.removeThreadLocals()` solution, and we were keen on it. If you could take the first stab at a PR we'd love to take a look!

**Comment by davidmoten** [comment]
>We just talked about the SdkThreadLocals.removeThreadLocals() solution, and we were keen on it. If you could take the first stab at a PR we'd love to take a look!

Will do. Naming wise, `SdkThreadLocals.removeThreadLocals()` is a bit repetitive. What about `SdkThreadLocals.remove()`?

**Comment by zoewangg** [comment]
`SdkThreadLocals.clear()`? `remove()` seems it's removing itself.

**Comment by davidmoten** [comment]
>SdkThreadLocals.clear()?

Fine by me.

**Comment by millems** [comment]
I actually like `remove()` since it matches `ThreadLocal.remove()`. We can argue about it in the PR :)
