### ISSUE TITLE
Generating Different checksum 

### ISSUE THREAD

**Issue by JJigar** [aws/aws-sdk-java#1711]
Mismatch of checksum as per the file size changed.

Eg: File size 767 KB creates correct checksum both at the s3 and my local machine by busing the 2 and 3 point which i have mentioned below and when we upload file with size 2.05 GB it creates different checksum.

1. Using TransferManager without multipart to upload objects in s3 bucket.

2. Received s3 Bucket Object checksum using  "s3client.getObjectMetadata(bucket_name,key_name).getETag()".

3. Local MD5 checksum generated using "BinaryUtils.toHex(Md5Utils.computeMD5Hash(new File(filepath)));"

Sharing code snippet:
 TransferManager tm = TransferManagerBuilder.standard()
                            .withS3Client(s3client)
                            .build();
 Upload upload = tm.upload(bucket_name, key_name, new File(file_path));

s3checksum = s3client.getObjectMetadata(bucket_name,key_name).getETag();
 localmachineChecksum =  BinaryUtils.toHex(Md5Utils.computeMD5Hash(new File(filepath)));

**Comment by dagnir** [comment]
Hi @JJigar by default, the `TransferManager` will split your object into a multipart upload once it exceeds a threshold; the default threshold is 16MB:

https://github.com/aws/aws-sdk-java/blob/fd9cf3192ae0782064bcd915dc1fa34ffd78c8d7/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManagerConfiguration.java#L57-L69

so for your 2.05 GB file, the `TransferManager` will upload it using the MultipartUpload API.

When doing multipart uploads, the ETag is no longer the MD5 sum of the object: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

If you don't need to better performance of the multipart upload, you can effectively disable it by setting a very high upload threshold (e.g. `Long.MAX_VALUE`) here: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManagerConfiguration.html#setMultipartUploadThreshold-long-

However, if you are already calculating the MD5 of the file at the time of upload, you could set it on the `ObjectMetadata` before doing the upload:

```java
        ObjectMetadata md = new ObjectMetadata();
        md.setContentMD5("foobar");
        PutObjectRequest req = new PutObjectRequest(BUCKET, KEY, new File("/path/to/file")).withMetadata(md);
        tm.upload(req).waitForUploadResult();
```

And then access it through `getContentMD5`:

```java
        ObjectMetadata md2 = s3Client.getObjectMetadata(BUCKET, KEY);
        System.out.println(md.getContentMD5());
```

**Comment by shorea** [comment]
Looks like @dagnir answered your question. Closing issue, feel free to reopen if you have further questions.

**Comment by kirtimeena** [comment]
Hi @dagnir, I am also facing the similar issue. I have tried the solution provided by you.
I am doing the multipart transfer of the larger file.

TransferManager manager = TransferManagerBuilder.standard().withS3Client(s3).withMultipartUploadThreshold(transferManagerConfiguration.getMultipartUploadThreshold()).withMinimumUploadPartSize(transferManagerConfiguration.getMinimumUploadPartSize()).build();
ObjectMetadata objectMetadata = new ObjectMetadata();
objectMetadata.setContentMD5(sourceFileChecksum);
PutObjectRequest request = new PutObjectRequest(bucketName,key,srcFile).withMetadata(objectMetadata);
Upload upload = manager.upload(request);
upload.waitForCompletion();
ObjectMetadata uploadedObjectMetadata = s3.getObjectMetadata(bucketName, key);
String uploadedCheckusm = uploadedObjectMetadata.getContentMD5();

The uploadedChecksum is null.
Can you please help me if I am missing anything here.
