### ISSUE TITLE
can't set objectSummaries in ListObjectsV2Result

### ISSUE THREAD

**Issue by alexanderkjeldaas** [aws/aws-sdk-java#1714]
There's a missing `setObjectSummaries` in ListObjectsV2Result it seems..?  Can't properly test APIs using this class.

**Comment by spfink** [comment]
Any particular reason you are looking to change the object summaries on a result object?

**Comment by shorea** [comment]
@alexanderkjeldaas are you trying to mock the result for testing? If so I'll go ahead and add that.

**Comment by shorea** [comment]
Ping

**Comment by varunnvs92** [comment]
Closing the issue due to inactivity. Feel free to reopen if you still have the issue.

**Comment by alexanderkjeldaas** [comment]
Yes, this is for mocking.

**Comment by assafgov** [comment]
> @alexanderkjeldaas are you trying to mock the result for testing? If so I'll go ahead and add that.

I'm also trying to test my project without connecting to S3 but at local directory.
Is there any solution?

**Comment by flavio-henrique** [comment]
I'm trying to mock as well, any other solution?

**Comment by JonNorman** [comment]
@varunnvs92 can we reopen this issue please? Similar to the others above, I am wishing to mock a response for a `ListObjectsV2Result` and am unable to set the `objectSummaries` (and whilst we are here `commonPrefixes`).
