### ISSUE TITLE
CloudFront Invalidation Request can be error prone with current Paths class implementation

### ISSUE THREAD

**Issue by Leoat12** [aws/aws-sdk-java#1715]
While I was doing some code using S3 and CloudFront it was necessary to invalidate objects on a distribution. I did exactly what is show in the snippet. 
```java
AmazonCloudFront amazonCloudFront = AmazonCloudFrontClientBuilder.standard().build();
Paths paths = new Paths().withItems("/path/*");
InvalidationBatch invalidationBatch = new InvalidationBatch(paths, Long.toString(Calendar.getInstance().getTimeInMillis()));
CreateInvalidationRequest request = new CreateInvalidationRequest("<DISTRIBUTION_ID>", invalidationBatch);
amazonCloudFront.createInvalidation(request);
```

I didn't notice at first that the attribute "quantity" was mandatory since there is nowhere clearly stating that. An error was given saying that "quantity" cannot be null when I made the request. 
When I set "quantity" another doubt came to mind due to what was written on the Javadoc and on the [API Reference for Paths](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Paths.html?shortFooter=true):

> Items: A complex type that contains a list of the paths that you want to invalidate.
> Quantity: The number of objects that you want to invalidate.

Is it paths the same as objects? Looks like it was, but it is a valid confusion since at least in S3 objects is very close to files. I gave 1 a try since it was one path and it solved the problem, but after that I thought that it would be good to report these apparent inconsistencies. 

Also, one of the errors described on API Reference is:

> InconsistentQuantities
> The value of Quantity and the size of Items don't match.
> HTTP Status Code: 400 

Since "quantity" and the size of "items" must always be equal, it wouldn't be better to change the implementation of the class Paths a little bit to make these two attributes more closely related and, therefore, less error prone?  

I was thinking about implementing it myself, but I thought it would be better to post an issue to see if it is plausible and if there is anything I am missing on my reasons for this change. 

Thanks in advance for the answer!

**Comment by spfink** [comment]
Can you create a thread on this in the CloudFront forum:

https://forums.aws.amazon.com/forum.jspa?forumID=46

I'll leave this open here until they respond but we'd rather the CloudFront team make an update to their API if possible rather than introduce a helper in the SDK for this (since we'd want to do it in all AWS SDKs if we decide to do it)

**Comment by Leoat12** [comment]
Thank you for the answer. As I thought, it can really lead to changes in all SDKs, that makes sense. 
I just posted on the forum the issue: https://forums.aws.amazon.com/thread.jspa?threadID=287770

**Comment by shorea** [comment]
Closing this issue as the ball is in Cloudfronts court.
