### ISSUE TITLE
Need a way to write tags without rewriting existing tags of resources created using CFT

### ISSUE THREAD

**Issue by rajeshbshinde** [aws/aws-sdk-java#1718]
This is a request for a way to update a bucket's tagging configuration without overwriting the existing configuration.

I need to add a tag to S3 buckets while keeping the existing configuration. I tried getting the current configuration, adding the new tag, and then setting the BucketTaggingConfiguration with this updated configuration. However, some of these buckets are created by CloudFormation, and they have 'aws' prefixed tags, which a user is prohibited from writing to any resource. Because of this, I cannot reset the entire configuration as it was plus the extra tag.

**Comment by rajeshbshinde** [comment]
I am using Java SDK version 1.11.372.

**Comment by spfink** [comment]
Can you post a thread on this in the S3 forum:

https://forums.aws.amazon.com/forum.jspa?forumID=24

My suggestion would have been what you did in getting the current tags and setting them back. Restrictions on the aws prefixed tags is not something that the SDK can get around. The members of the S3 forum of the CloudFormation forum would be able to advise of any possible workarounds.
