### ISSUE TITLE
JAVA: AWS S3 File upload error by some other method

### ISSUE THREAD

**Issue by timusiiit123** [aws/aws-sdk-java#1719]
**Here is my code to upload an object to the AWS S3 bucket folder.**

import java.io.File;
import java.util.Calendar;
import java.util.Date;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.PutObjectRequest;

public class AmazonWebService {

	private final static String AWS_ACCESS_KEY_ID = "";
	private final static String AWS_SECRET_KEY = "";
	
	public static void S3UploadFile(String keyName){

		String path = "mybucket/bucketFolder";	// e.g. bucket>folder>folder 
		String key = "";		// e.g. "sample.csv" in bucket>folder>folder>sample.csv
		
		String local_file_path = "";
		
		if(keyName.equals("positions")){
			key = "lesser-than-2018-07-27 00-00-00.csv";
			local_file_path = "C:\\\\demo_sqls\\\\positions\\\\"+key;
		}

		try{
			System.out.println("Uploading the file to AWS S3 ");
			File file = new File(local_file_path);
			AWSCredentials credentials = new BasicAWSCredentials(AWS_ACCESS_KEY_ID, AWS_SECRET_KEY);
			AmazonS3 s3Client = new AmazonS3Client(credentials);
			s3Client.putObject(new PutObjectRequest(path, key, file));
			System.out.println("file uploaded");
		} catch (AmazonServiceException ase) {
            System.out.println("Caught an AmazonServiceException, which means your request made it "
                    + "to Amazon S3, but was rejected with an error response for some reason.");
            System.out.println("Error Message:    " + ase.getMessage());
            System.out.println("HTTP Status Code: " + ase.getStatusCode());
            System.out.println("AWS Error Code:   " + ase.getErrorCode());
            System.out.println("Error Type:       " + ase.getErrorType());
            System.out.println("Request ID:       " + ase.getRequestId());
        } catch (AmazonClientException ace) {
            System.out.println("Caught an AmazonClientException, which means the client encountered "
                    + "a serious internal problem while trying to communicate with S3, "
                    + "such as not being able to access the network.");
            System.out.println("Error Message: " + ace.getMessage());
        }
		
	}
	
	public static void main(String args[]){
		S3UploadFile("positions");
	}

}

So my issue is when I run the code from main method it uploads the object without any error but when I do this in some other class like this: **AmazonWebService.S3UploadFile("positions");**

Then it gives me this:
**Caught an AmazonServiceException, which means your request made it to Amazon S3, but was rejected with an error response for some reason.
Error Message:    The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 3EDF54A4B8301CF2)
HTTP Status Code: 301
AWS Error Code:   PermanentRedirect
Error Type:       Client
Request ID:       3EDF54A4B8301CF2
Finished**

How can I solve this?

**Comment by spfink** [comment]
Can you provide wire logs? How recently did you create the bucket you are uploading to?

**Comment by timusiiit123** [comment]
I created the bucket August 08, 2018 04:33:35 PM GMT+0530.
And which wire logs do you need _AWS S3 or Java_?

**Comment by timusiiit123** [comment]
If you need logs from JAVA side, I get this when I remove the exception:

```
Aug 14, 2018 12:27:48 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [Jersey RESTful Application] in context with path [/Ryoking] threw exception [com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: B4C137EC7408CE6D), S3 Extended Request ID: yQlizl2sHpL2YC4Dtb3jruu6mcYgvUBGdV4aJUUKn/tEwPBdrHFVfE1keUF9Na4NprpYW6ooXas=] with root cause
com.amazonaws.services.s3.model.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: B4C137EC7408CE6D), S3 Extended Request ID: yQlizl2sHpL2YC4Dtb3jruu6mcYgvUBGdV4aJUUKn/tEwPBdrHFVfE1keUF9Na4NprpYW6ooXas=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3790)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1404)
	at com.zedacross.ryoking_server.utilities.AmazonWebService.S3UploadFile(AmazonWebService.java:59)
```

**Comment by timusiiit123** [comment]
Hey,
I solved it by importing new library of aws-java-sdk, 1.11.327 version and in the code I add **region** with the **credentials**.

**Comment by timusiiit123** [comment]
Please see this:
https://github.com/aws/aws-sdk-java/issues/1719


Thanks,
Sumit Kumar Sagar
