### ISSUE TITLE
S3 data encryption and decryption

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java#1721]
I have few questions on , how to use sdk in order to implement server side/client side encryption.

1. I assume any body having access key and secret key can easily download the s3 object (uploaded earlier using server side encryption) ? So in a nutshell, server side encryption just encrypt data on s3 data center disk. Is this assumption right?

2. I have the requirement like, even if somehow access key and secret key is known to someone, he can't download and decrypt the content uploaded by someone else using encryption.

If the second point is feasible only through client side encryption?

whether yes or no, what is most appropriate code sample/configurations required to achieve that while using transfer manager.

**Comment by shorea** [comment]
1) Yes that's correct, decryption happens service side so anyone with access to the object can get the decrypted contents.

2) Yes this is the purpose of client side encryption. You need both access to the object and the correct encryption key to be able to decrypt it. Otherwise with only access to the object can just get the encrypted data but won't be able to view the plaintext.

Here's an example of using KMS client side encryption with the transfer manager.

```java
        AmazonS3Encryption s3 =
            AmazonS3EncryptionClientBuilder.standard()
                                           .withKmsClient(AWSKMSClientBuilder.defaultClient())
                                           .withEncryptionMaterials(new KMSEncryptionMaterialsProvider("alias/your-key"))
                                           .build();

        TransferManager tf = TransferManagerBuilder.standard().withS3Client(s3).build();

        tf.upload("your-bucket", "some-object", new File("toUpload.txt"))
          .waitForCompletion();

        tf.download("your-bucket", "some-object", new File("download.txt"))
          .waitForCompletion();

        tf.shutdownNow();
```

**Comment by MkJha** [comment]
Thanks @shorea , it woked as you mentioned. Just one thing , is there any way so that whatever region and endPoint ,client configuration  and credentials we use to build the AmazonS3Encryption  , same can be used by the attached KMS client. I mean instead of passing all stuffs for client and KMS client separately.

As you can see below 

s3Client = AmazonS3EncryptionClientBuilder.standard()
						.withEndpointConfiguration(new EndpointConfiguration(getServer(), getRegion()))
						.withCredentials(loadCredentials()).withClientConfiguration(getClientConfiguration())
						.withEncryptionMaterials(
								new KMSEncryptionMaterialsProvider("XXXXXXXXXXXXXXXXXXX"))
						.withKmsClient(AWSKMSClientBuilder.standard().withRegion(getRegion())
								.withCredentials(loadCredentials()).build())
						.build();

**Comment by shorea** [comment]
We don't have support for that in a first class way but you can always have a common configuration method that takes the builder super class and configures the common properties. Also we support configuring credentials and region from the environment which is a good option to keep code portable (see links below).

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html

**Comment by zoewangg** [comment]
Closing the issue, feel free to reopen if you have further questions/issues.
