### ISSUE TITLE
No SuchFieldError: SIGNING_REGION while using Dynamodb getItem on EC2

### ISSUE THREAD

**Issue by chengchengmu** [aws/aws-sdk-java#1724]
# Description of the problem
## Error on EC2
The following error appears : 
```
java.lang.NoSuchFieldError: SIGNING_REGION
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeGetItem(AmazonDynamoDBClient.java:1780) 
```
while running on *EC2* with `aws-java-sdk-dynamodb 1.11.382` and same version of aws-java-sdk-core.
`AmazonDynamoDBClientBuilder.defaultClient()` is used to build the client.
Tried with several other versions of the library (1.11.386 : latest, 1.11.300), all have the same error.
**However it works with 1.11.256 of aws-java-sdk-dynamodb ( a randomly chosen older version).**
Java jdk version: 
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

## On local machine with another build of the same version of JDK : 
The latest versions (1.11.382, 1.11.386) of aws java sdk work locally.
Java jdk version :
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

There are other ticket with the same error.
For eg. https://github.com/aws/aws-sdk-java/issues/1700 where the suspicion is a mismatch of version between the client and core. It is not the case here.
https://github.com/aws/aws-sdk-java/issues/1611  seems to be a similar issue, and it worked with a particular version of core.

Is there any compatibility grid to help people find what should work ?
The current solution is to try randomly multiple versions until one works ...

**Comment by shorea** [comment]
Looks like a mismatch between client and core. Can you add some logging to see where the following class is being loaded from?

```java
 System.out.println(HandlerContextKey.class.getProtectionDomain().getCodeSource());
```

> Is there any compatibility grid to help people find what should work ?

As long as you have a newer version of core than your clients then you should be fine. When you use an newer version of the client with an older version of core then you may run into runtime issues. The BOM is a good option for keeping versions in sync.

https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/

**Comment by varunnvs92** [comment]
@chengchengmu 
were you able to try the above suggestion?

**Comment by chengchengmu** [comment]
@shorea @varunnvs92
Thanks for the reply.
I will try the above when I have time.


As I mentioned, I tried with the same version of core and client and it resulted in the error.

@shorea core version had to be strictly newer than client's ?

**Comment by shorea** [comment]
Newer than or equal to.

**Comment by chengchengmu** [comment]
@shorea after checking this jar, it's actually different from the one I specified ...
We can close this ticket. Thanks for your help !
