### ISSUE TITLE
Java 11 Compatibility check: aws-java-sdk

### ISSUE THREAD

**Issue by KryniuPL** [aws/aws-sdk-java#1725]
Hi,
We are reaching out to you to check Java 11 compatibility of the library aws-java-sdk.

Could you help us by answering the following questions:

1. Library Name: <library name.="" e.g:="" activation="">
2. Latest version: <latest 1.1.1="" eg:="" version.="">
3. Latest version Is the library compatible with Java 11 Compatible? (Y/N)
4. Is the library supported with Java 11? (Y/N)
5. (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
6. Date of support availability?</latest></library>

Appreciate your response by 19.08.2018.

Thanks,
Krzysztof Dragan,
PTC Inc. Contractor

**Comment by varunnvs92** [comment]
**Library Name:** AWS SDK for Java
**Latest version:** 1.11.391
**Latest version Is the library compatible with Java 11 Compatible?** 
We don't have JDK 9 modular support in 1.11. Assuming thats your question, I would say No. But customers can use automatic modules to make it work.
**Is the library supported with Java 11?** 
No, 1.11.x still supports Java 6. 
**What is the versions that would be compatible and Supported?**
We are working on v2 version of the SDK. It is compatible with java 9. As Java 11 GA is sep 2018, v2 might be made compatible with Java 11.
https://github.com/aws/aws-sdk-java-v2
**Date of support availability?**
No concrete date yet. Tentative data is end of this year or early next year.
