### ISSUE TITLE
Can we also do a null or empty check in ConnectionsList class

### ISSUE THREAD

**Issue by gauravbrills** [aws/aws-sdk-java#1726]
Can we also do a null or empty check in connection list , as if the user supplies an empty list it gives an error as it expects values in the list . 

https://github.com/aws/aws-sdk-java/blob/60196261032eb91e615478ba78c085cc57e72621/aws-java-sdk-glue/src/main/java/com/amazonaws/services/glue/model/ConnectionsList.java#L60

**Comment by shorea** [comment]
This is probably not something we'd be able to do. We try to limit the amount of client side validation we do as it can hinder services from relaxing constraints in the future.
