### ISSUE TITLE
App is crashing when user is trying to upload the image in s3 

### ISSUE THREAD

**Issue by aravindvogo** [aws/aws-sdk-java#1727]
io.reactivex.plugins.RxJavaPlugins.initComputationScheduler (Unknown Source) io.reactivex.subjects.PublishSubject.onError (Unknown Source) com.example.util.S3Uploader$1.onStateChanged (Unknown Source) com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$1.run (Unknown Source)

**Comment by shorea** [comment]
Will need a full stack trace to troubleshoot further.

**Comment by aravindvogo** [comment]
> io.reactivex.plugins.RxJavaPlugins.initComputationScheduler (Unknown Source)
io.reactivex.subjects.PublishSubject.onError (Unknown Source)
com.VoDrive.util.S3Uploader$1.onStateChanged (Unknown Source)
com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$1.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6946)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

**Comment by aravindvogo** [comment]
`com.example.util.S3Uploader$1.onStateChanged (Unknown Source)
com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$1.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6946)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)`

**Comment by aravindvogo** [comment]
This is the reason which crashltyics shows

`Fatal Exception: io.b.c.f
java.lang.Exception: S3 Upload failed
io.reactivex.plugins.RxJavaPlugins.initComputationScheduler`

**Comment by shorea** [comment]
Sorry it's still not clear what the SDK error is.

**Comment by zoewangg** [comment]
Closing the issue due to no response. Feel free to reopen if you have further questions/issues.
