### ISSUE TITLE
Add ListMetricAlarmRequest option for cloudwatch alarms

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [aws/aws-sdk-java#1728]
### Option: ListMetricAlarmRequest 
As of now if we want to check alarms have to do describe alarm for particular alarm. But if we want to list all the alarms available there is not option. Like we do have ListBucketsRequest option to check all the buckets.
### Expected Result: 
It would be nice if you can add ListMetricAlarmRequest option through SDK so that we can check whether all the alarms we planned to create are created for a particular instance or not and also to check whether the alarm exists before trying to create it.

**Comment by debora-ito** [comment]
Hi @SrikarshVardhanreddyKolanu, I opened an internal ticket to the Cloudwatch service team requesting this feature, and will update here when they respond.

I'd suggest you also post your feature request in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=138), where you can get a reply from the service team.

I'll go ahead and close this, but will let you know when we hear back.

**Comment by debora-ito** [comment]
@SrikarshVardhanreddyKolanu the service team said it's possible to retrieve the list of alarms with these APIs

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarms.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarmsForMetric.html

Let us know if you have any other question.
