### ISSUE TITLE
Enable Point In Time Recovery for DynamoDB via the Java SDK

### ISSUE THREAD

**Issue by davidgoate** [aws/aws-sdk-java#1735]
It'd be useful to be able to create a table via the Java SDK with point in time recovery enabled.

I imagined it might be an option added to `com.amazonaws.services.dynamodbv2.model.CreateTableRequest` e.g.

```java
 final CreateTableRequest schema = new CreateTableRequest()
            .withTableName(tableName)
            .withPointInTimeRecovery(true);
```

Is there any plan to support in the near future?

**Comment by varunnvs92** [comment]
This would be a feature request to Amazon DynamoDB team as we generate the SDK based on the service models. There is a feature to backup the table and restore from that back up. I don't think there is automatic PointInTimeRecovery. See if this is the feature you are looking for.
https://aws.amazon.com/dynamodb/backup-restore/
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateBackup.html
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_RestoreTableFromBackup.html

If you are asking for a different feature, You can reach out to service team via [AWS forums](https://forums.aws.amazon.com/forum.jspa?forumID=131).

**Comment by Andrew-Webb** [comment]
You can use https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateContinuousBackups.html to enable it after creation... like you have to tag the table after creation.
