### ISSUE TITLE
Add ability to set S3ClientOptions to AmazonS3ClientBuilder

### ISSUE THREAD

**Issue by yuppie-flu** [aws/aws-sdk-java#1736]
The recommended way to create `AmazonS3` is using `AmazonS3ClientBuilder`.
The builder has a set of configuration methods to configure all properties, which are inside `S3ClientOptions` object. However there is no method to set the whole `S3ClientOptions` to this builder.

Let's consider a case of some service, which utilize `aws-sdk-java` library underneath.  The service should provide a way to configure a creation of amazon s3 client. With the current `AmazonS3ClientBuilder` design, the service should either expose all options inside `S3ClientOptions` to an end-user for configuration of should accept the whole `AmazonS3ClientBuilder`. The first solution obviously requires changes, when new options are added to `S3ClientOptions`. The second solution looks ugly, because the builder is huge.
That's the motivation, why adding the new method is useful.

**Comment by varunnvs92** [comment]
The builders are new and added in 1.11. We moved all client settings onto the builder. Adding S3ClientOptions to the builder adds confusion on which would take precedence when an option is set in both places. I am not sure if we will prioritize this feature as we are working on v2. You can send us a PR and we are happy to take a look.

**Comment by debora-ito** [comment]
Hi @yuppie-flu, the team has reviewed the feature requests list for V1 and decided to not implement this one because they are actively working on V2 new features. So I'll go ahead and close this.

Please feel free to reach out if you have further questions.
