### ISSUE TITLE
Subscribing to an AWS IoT topic in a Java backend 

### ISSUE THREAD

**Issue by wjans** [aws/aws-sdk-java#1739]
When using `aws-sdk-java-iot`, it is possible to publish messages to an AWS IoT topic from a backend system, but it doesn't seem possible to subscribe to a topic?  What is the reasoning behind this?

We are looking for a way to have our Java backend (deployed on AWS) take part in our IoT solution and being able to publish and subscribe to topics.  If using the sdk is not the way to go, what would be a good design to achieve this?

**Comment by zoewangg** [comment]
This seems more like a service specific question, could you post it on AWS forums https://forums.aws.amazon.com/forum.jspa?forumID=210 or statckoverflow? The service team might have better knowledge than us.
