### ISSUE TITLE
could not resolve "com.amazonaws.services.kinesis.clientlibrary.types.ShutdownReason" with amazon-kinesis-client(1.9.1)

### ISSUE THREAD

**Issue by nikesh-dev** [aws/aws-sdk-java#1742]
https://github.com/aws/aws-sdk-java/blob/7b291bfc93ff1e8f4eb9c2af11985cc5108a2f19/src/samples/AmazonKinesis/AmazonKinesisApplicationSampleRecordProcessor.java#L29

**Comment by zoewangg** [comment]
As mentioned in #1741, it is recommended to keep all sdk modules the same version. Side note: 1.11.x is the recommended version.

**Comment by Nxtra** [comment]
You should change the import to: 
`import com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownReason;`
And it will find the enum there.
