### ISSUE TITLE
Support for multiple availability zones in a spot fleet request

### ISSUE THREAD

**Issue by jacool** [aws/aws-sdk-java#1744]
Despite the following declaration being almost 3 years old it seems to be still unsupported by com.amazonaws.services.ec2.model.LaunchSpecification.

https://aws.amazon.com/about-aws/whats-new/2015/11/specify-multiple-availability-zones-in-a-single-ec2-spot-fleet-request/

**Comment by zoewangg** [comment]
You can specify availability zone via `SpotFleetLaunchSpecification.SpotPlacement.availabilityZone`.

For example:

```java
ec2.requestSpotFleet(new RequestSpotFleetRequest()
            .withSpotFleetRequestConfig(new SpotFleetRequestConfigData()
                .withLaunchSpecifications(new SpotFleetLaunchSpecification()
                    .withInstanceType(InstanceType.T1Micro)
                    .withPlacement(new SpotPlacement().withAvailabilityZone("us-west-2a, us-west-2b"));
```

**Comment by jacool** [comment]
A method named withAvailabilityZone accepting a coma-separated string to designate multiple inputs in a public Java API would be called a bug where I work. The corresponding setSubnetId is not even documented to accept multiple inputs. I would classify this report as an API improvement request not as a question.

**Comment by millems** [comment]
I agree it could be modeled better in the Java API, but it's a little tricky to fix now. It looks like the same `SpotPlacement` shape is used for spot fleets and individual instances, so the value is only _contextually_ allowed to be a list. 

Our only real option here is to also generate a `List` setter that would only sometimes work (which might be even more confusing). It probably should have been modeled differently in the past, but it's not something we can fix without a major version bump of the service API, which I don't think that EC2 is planning to do soon.

It looks like the same comma-based list pattern exists in `SpotPlacement.SubnetId`, as well.

**Comment by varunnvs92** [comment]
Closing the issue as we can't fix the issue to due backward compatibility reasons.
