### ISSUE TITLE
error on default client for CloudWatch

### ISSUE THREAD

**Issue by thaeness** [aws/aws-sdk-java#1751]
I'm getting a `java.lang.NoSuchFieldError: SIGNING_REGION` error when I made a request to put a custom metric using `AmazonCloudWatchClientBuilder.defaultClient()` 
I have tried several versions of the client, including the latest, but the error persists.

version: 1.11.401 

stracktrace:
```
java.lang.NoSuchFieldError: SIGNING_REGION
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:1217)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:1199)
```
simplified code:
```
AmazonCloudWatch cw = AmazonCloudWatchClientBuilder.defaultClient();
PutMetricDataRequest request = new PutMetricDataRequest()
                .withNamespace(namespace)
                .withMetricData(metrics);
PutMetricDataResult response = cw.putMetricData(request);
```

**Comment by debora-ito** [comment]
This looks like a mismatch between client and core. The version of core must be the same or newer than the client version. 

Can you add some logging to your code and see if it helps identifying the issue?
```java
System.out.println(HandlerContextKey.class.getProtectionDomain().getCodeSource());
```

**Comment by thaeness** [comment]
yep, you are right, my mistake, thanks a lot!
