### ISSUE TITLE
Incomplete endpoints in endpoints.json

### ISSUE THREAD

**Issue by smanikim** [aws/aws-sdk-java#1753]
I was thinking to use https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json for getting FIPS endpoint using code. but looks like
1) List is incomplete as it doesnt contain all endpoints e.g. config
2) Method parsing this is private

Could you suggest if this is bug or intentional
In latter case, how do you suggest to get endpoints in code instead of hardcoding in application code

**Comment by varunnvs92** [comment]
We don't suggest relying on the endpoints.json for the complete endpoint data. We get this data from service team and sometimes there are delays or missing endpoints. SDK uses this data to find the endpoint, if not we compute using specific patterns.

For special endpoints like fips, you need to set the endpoint in the application code as there is no other configuration in the SDK to indicate you want to use fips endpoint.

**Comment by smanikim** [comment]
I am thinking to get this information from code instead of hardcoding it per region and keep a tap on AWS site for updates if any.  I believe adding to endpoints.json make it easier to pull this information (though I can always write customer code for this). 
I can create PR to update FIPS endpoints or use custom file as current SDK support. 
Do you think it will make sense to make com.amazonaws.partitions.PartitionsLoader#loadPartitionFromStream public so that I can override endpoints.json and reuse code

**Comment by smanikim** [comment]
should I file PR for this

**Comment by debora-ito** [comment]
As @varunnvs92 mentioned before, the endpoints.json file is auto-generated, so any changes will get overwritten when there's a new update from the service team later on. So unfortunately we won't be able to receive a PR on this.
Please follow @varunnvs92 guidance on how to set FIPS endpoints in your application.

**Comment by smanikim** [comment]
code provides option to override file and API to parse and get endpoints is private. I can submit PR to make that public. I think that works @varunnvs92 @debora-ito

**Comment by dagnir** [comment]
@smanikim Unfortunately we do not want to expose that as a public method because we cannot guarantee that the interfaces (e.g. the `Partition` class) are stable. Methods could get remove/renamed in the future which would break clients.

**Comment by debora-ito** [comment]
Closing issue, feel free to reopen if you have more questions.
