### ISSUE TITLE
Support @DynamoDBTypeConverted for Older Data

### ISSUE THREAD

**Issue by bhagujava** [aws/aws-sdk-java#1754]
Does @DynamoDBTypeConverted support to convert older data with new data type ? 
We have data which contain some string value but value contains numeric data. we have change String to Integer now. but we are getting exception "Expecting S"  while pulling the older data.

I tried to implement DynamoDBTypeConverted  here but don't understand how to convert previously stored String to Integer .

My Entity class is

    @DynamoDBDocument
    class Player{

    private String playerName;
    private String email;
     @DynamoDBTypeConverted(converter=PlayerTypeConverter.class)
      private Integer playerScore;
    // getter
    //setter
    }

My Convert Looks like....

    public class PlayerTypeConverter<T,V> implements DynamoDBTypeConverter<T,V> {

    @Override
    public T convert(V value) {
        log.info("Type converter value is ..", value);
        return (Double)value;
    }
    @Override
    public V unconvert(T s){
        if(s instanceof String) {
            return (V)Double.valueOf(s.toString());
        }
        if(s instanceof  Double){
            return (V)s;
        }
        return (V)s;
    }
    }

What is the possible way to convert from String to Integer and also support new datatype(Integer) ?

**Comment by debora-ito** [comment]
The `unconvert` method expects a specific type of object - so in your code example, T must be `String` or `Double`, and it can't be `Object`.
So it's not possible to map two different types of the same field. It's recommended to treat the data source, changing all the records to the same type.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.

**Comment by seanzxx** [comment]
I guess this is what you need:
`class PlayerTypeConverter implements DynamoDBTypeConverter<AttributeValue, Integer> {

    @Override
    public AttributeValue convert(Integer object) {
        return new AttributeValue().withN(object.toString());
    }

    @Override
    public Integer unconvert(AttributeValue object) {
        if (object.getS() != null) {
            //string
            return Double.valueOf(object.getS()).intValue();
        } else if (object.getN() != null) {
            // number
            return Double.valueOf(object.getN()).intValue();
        } else {
            // else
            return null;
        }
    }
}`
