### ISSUE TITLE
Program type already present: com.amazonaws.auth.ChunkContentIterator

### ISSUE THREAD

**Issue by alejouribesanchez** [aws/aws-sdk-java#1755]
Hi @Karthikeyan. I was trying to use this:

    implementation 'com.amazonaws:aws-android-sdk-s3:2.6.30'
    implementation 'com.amazonaws:aws-java-sdk:1.11.404'

`val config = AWSConfiguration(applicationContext)
            val credentialsProvider = BasicAWSCredentials(AWS_ACCESS_KEY, AWS_SECRET_KEY)
            val awsStaticCredentialsProvider = AWSStaticCredentialsProvider(credentialsProvider)

            val s3Client = AmazonS3ClientBuilder.standard()
                    .withRegion(Regions.US_EAST_1)
                    .withCredentials(awsStaticCredentialsProvider)
                    .enableAccelerateMode()
                    .build()

            // Enable Transfer Acceleration for the specified bucket.
            s3Client.setBucketAccelerateConfiguration(
                    SetBucketAccelerateConfigurationRequest(BUCKET_NAME, BucketAccelerateConfiguration(BucketAccelerateStatus.Enabled)))

            // Verify that transfer acceleration is enabled for the bucket.
            val accelerateStatus = s3Client.getBucketAccelerateConfiguration(GetBucketAccelerateConfigurationRequest(BUCKET_NAME)).getStatus()
            println("Bucket accelerate status: $accelerateStatus")

            transferUtility = TransferUtility.builder()
                .awsConfiguration(config)
                .context(applicationContext)
                .s3Client(s3Client)
                .build()`

but I am getting this error from the compiler:
Program type already present: com.amazonaws.auth.ChunkContentIterator
Message{kind=ERROR, text=Program type already present: com.amazonaws.auth.ChunkContentIterator, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by varunnvs92** [comment]
Hi,
Mobile SDKs are maintained in a separate repo. Please open the issue [here](https://github.com/aws/aws-sdk-android/issues). Thank you.
