### ISSUE TITLE
AmazonS3Client is not working with temporary credentials.

### ISSUE THREAD

**Issue by adam-arold** [aws/aws-sdk-java#1759]
I'm using the `AmazonS3Client` with temporary credentials generated by `saml2aws`. My `credentials` file looks like this:

```
[default]
aws_access_key_id        = MY KEY ID
aws_secret_access_key    = MY KEY
aws_session_token        = MY SESSION TOKEN
aws_security_token       = MY TOKEN
x_principal_arn          = MY ARN
x_security_token_expires = TIME
```

When I try to use this file from the SDK:

```
AmazonS3Client(ProfileCredentialsProvider(
                ProfilesConfigFile("/Users/myuser/.aws/credentials"),
                "default"))
                .listObjects("bucket-name")
```

I get

> com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 89597EA6C057B7AE, AWS Error Code: InvalidAccessKeyId, AWS Error Message: The AWS Access Key Id you provided does not exist in our records.
, S3 Extended Request ID: whk1Mh0c7e15FaeCc/QQHbvPQeO1ktfocy6v9jRxu7suXpSpKoRVWYXjTltUf01zBYB9/G9f/VU=

I tried to do this in a lot of permutations:

```
AmazonS3Client().listObjects("bucket-name")

AmazonS3Client(ProfileCredentialsProvider("default"))
                .listObjects("bucket-name")
```

but it won't budge. If I debug into the client I can see that this resolves to this:

![image](https://user-images.githubusercontent.com/1253248/45362871-46c8e580-b5d6-11e8-80d8-19e37ff55dab.png)

and there is no mention of the session / security token.

I digged thorugh the documentation but there is no mention on how to use the SDK in this scenario when I have temporary keys in my `credentials` file.

**Note that** after using `saml2aws` the CLI works fine, I can run commands and they work, so this is an SDK issue.

I'm using `com.amazonaws:aws-java-sdk:1.7.4`. This comes from `org.apache.hadoop:hadoop-aws:2.7.1` and I can't change the version.

**Comment by dagnir** [comment]
Hi @adam-arold, Unfortunately, it looks like `1.7.4` did not have support for loading any other properties besides `aws_secret_key` and `aws_access_key_id` from the `credentials` file:

https://github.com/aws/aws-sdk-java/blob/7fd44b0504f86ad487a753cc0e11e3066622ba68/src/main/java/com/amazonaws/auth/profile/internal/ProfilesConfigFileParser.java#L110-L121

It seems this was added later in `1.7.8`: https://github.com/aws/aws-sdk-java/commit/d4b637187cb63d706ad72af99d7af3eedf7e1550#diff-7fa590917269bb46955bbe4db9e5bb92

The `1.7.4` releases [does have support for using temporary credentials](https://github.com/aws/aws-sdk-java/blob/7fd44b0504f86ad487a753cc0e11e3066622ba68/src/main/java/com/amazonaws/auth/AWSSessionCredentials.java#L20) but it looks like you will need to

**Comment by adam-arold** [comment]
Do you have documentation on how I can write such loader? I'm not familiar with the source code of the SDK.

**Comment by adam-arold** [comment]
Is it OK if I copy the new implementation from the `1.7.8` version to my local project from a licensing perspective?

**Comment by jpeddicord** [comment]
Hi @adam-arold!

The AWS SDK for Java is licensed under the Apache 2.0 license. I know this isn't _super_ helpful, but we can't provide legal advice. If you're curious about what the implications of the Apache 2.0 license are, the are various guides on the internet to peruse (such as "TLDRLegal"). If you have questions about what you can specifically do with this license, you'll want to consult an attorney.

Thanks!
Jacob

**Comment by dagnir** [comment]
Closing this based on @jpeddicord's response. Please feel free to reopen if you have further questions.

**Comment by adam-arold** [comment]
All right. Thanks for the help!
