### ISSUE TITLE
Why mergeConfig is protected?

### ISSUE THREAD

**Issue by ieiayaobb** [aws/aws-sdk-java#1761]
I'm going to hold a global state for 'DynamoDBMapperConfig'
I find we a 'config' attribute but it is private and the only method for modifying is protected.
I want to know why we design like this, thank you.

**Comment by dagnir** [comment]
Hi @ieiayaobb can you explain what you're trying to do?

**Comment by ieiayaobb** [comment]
We want to change the table_name dynamically based on the mapper.

**Comment by debora-ito** [comment]
Maybe [TableNameResolver](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.TableNameResolver.html) is what you are looking for, it allows you to determine the table name of an object at runtime.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have more questions.
