### ISSUE TITLE
Examples of using EKS cerificate data with KubenretesClient

### ISSUE THREAD

**Issue by shashank-g172** [aws/aws-sdk-java#1763]
Hi, 

 I'm working to create an EKS cluster using the eks SDK. I can create them just fine using the createClusterAsync call, and I get access the actual cluster once the future says it's done. I was wondering how I could get the Cerificate on the Cluster object to give me an access token that I can use to then work with the Java client Kubernetes Client from Fabric8 in order to manage the client programatically instead of using Kubectl:

https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java

Most of the documentation provided is about crafting the kubectl tool to talk to the cluster.

**Comment by debora-ito** [comment]
Since this is a service specific question, can you post it on EKS  Forums? https://forums.aws.amazon.com/forum.jspa?forumID=303 
You may get better support from the Amazon EKS team.
