### ISSUE TITLE
RegionUtils.getRegionsForService(“eks”) returns empty list

### ISSUE THREAD

**Issue by sameerkhan2k1** [aws/aws-sdk-java#1766]
We are trying to fetch the list of regions supporting EKS service on AWS using RegionUtils.getRegionsForService(AmazonEKS.ENDPOINT_PREFIX) API of its Java SDK. However, an empty list of Regions is returned. This API works perfectly for S3, EC2, etc. EKS is as of today supported in Northern Virginia, Oregon & Ireland. 
The SDK uses [endpoints.json](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json) to load the relevant regions and an entry to EKS service is not included here.

**Comment by spfink** [comment]
Will advise service team to update their data available to the SDK.

**Comment by krjackso** [comment]
Any progress on this? EKS has been out for a while now

**Comment by anilcs81** [comment]
its been more than a year since this issue is open. Could you please advise on it?

**Comment by debora-ito** [comment]
The EKS endpoints are now available in SDK version `1.11.780`. 

I'll go ahead and close this. Feel free to reach out if you have further questions.
