### ISSUE TITLE
Add API to know violated expected criteria in ConditionalCheckFailedException

### ISSUE THREAD

**Issue by agriardyan** [aws/aws-sdk-java#1769]
Is this a Feature Request: yes
Is this also a bug report: no
Background: conditional write to DB using DynamoDBMapper and DynamoDBSaveExpression

I stumble upon a case where I need to know the exception cause during conditional write with DynamoDBSaveExpression. 
I intend to throw an exception that specifically tell user whether to retry with same value or not, thus I need to know what expected criteria (set in DynamoDBSaveExpression) that's not fulfilled.
Unfortunately I can't find any information about the cause of failure in ConditionalCheckFailedException. So it'll be very useful if we have a field that gives client about the specific cause of failure (the expected criteria that doesn't met).

For example, I have this expectation : 
`Map<String, ExpectedAttributeValue> expected = new HashMap<>();`
`expected.put("committed", new ExpectedAttributeValue(new AttributeValue().withN("0")).withComparisonOperator(ComparisonOperator.EQ));`
`expected.put("checksum", new ExpectedAttributeValue(new AttributeValue().withS(obj.getChecksum())).withComparisonOperator(ComparisonOperator.EQ));`
`expected.put("uuid", new ExpectedAttributeValue(new AttributeValue().withS(obj.getUuid())).withComparisonOperator(ComparisonOperator.EQ));`

during writing to DynamoDB, one of the criteria (say `commited`) isn't satisfied. The exception thrown is only `ConditionalCheckFailedException` and it's not really helpful to know which criteria isn't satisfied.

**Comment by millems** [comment]
We do not currently intend to add any new features to 1.11.x of the DynamoDB mapper. You can request new features for the 2.x mapper here: https://github.com/aws/aws-sdk-java-v2/issues/35
