### ISSUE TITLE
Datamodeling annotations on fields

### ISSUE THREAD

**Issue by danilovalente** [aws/aws-sdk-java#177]
My team is working with Groovy projects for some time and at this moment we are starting a project that will persist data using DynamoDB.
For that, we are using aws-sdk-java and annotating our classes with dynamodbv2.datamodeling package annotations.
In Groovy there is no need for declaring getters and setters, like Java... We just declare the fields, and getters and setters are automatically created. The sdk´s mapping annotations like @DynamoDBHashKey and @DynamoDBAttribute require the getters and setters being declared, bringing a lot of unnecessary work.
It is possible allow to add this annotations directly to the fields?

Yours Sincerely,

Danilo Valente

**Comment by hanshuo-aws** [comment]
The change was incorporated in version 1.7.1.
