### ISSUE TITLE
potential NullPointerException ?

### ISSUE THREAD

**Issue by adriannistor** [aws/aws-sdk-java#1770]
In

`com.amazonaws.http.AmazonHttpClient.java` ([this file](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java))

the expression 

`requestConfig.getRequestClientOptions()`

is used in the method `executeHelper()` ([line 1031](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1031) and [line 1039](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1039)) without
any checks for `null` like this:

`final int readLimit = requestConfig.getRequestClientOptions().getReadLimit();`

However, in the method ([line 1452](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1452)) `setUserAgent(Request<?> request)`

the same expression

`requestConfig.getRequestClientOptions()`

is checked for `null` ([line 1452](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1452)) like this:

```
RequestClientOptions opts = requestConfig.getRequestClientOptions();
if (opts != null) {
    ...
} else {
    ...
}
```

This last usage with `null` checks ([line 1452](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1452)) suggests the expression

`requestConfig.getRequestClientOptions()`

can indeed return `null`.

These are the only 3 usages of the expression in this file.

I do not see a reason why the first two usages would be guaranteed to
not return `null` (e.g., any obvious setting of client options)---when
the third usage can actually return `null`.

However, I am new to aws-sdk-java and I may be wrong.

Can you please check if the first two usages also need `null` checks?

Thanks,

Adrian

**Comment by shorea** [comment]
RequestClientOptions will always be non-null as we initialize it on declaration. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceRequest.java#L49

Seems like the null check is just being overly defensive.

**Comment by adriannistor** [comment]
Andrew, thank you for getting back to this.

ok.

Then, is the check (and the logic on the else branch) at [line 1453](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1453)
un-necessary?

I.e., if the expression

`requestConfig.getRequestClientOptions();`

cannot be `null` at [line 1031](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1031) and [line 1039](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1039), then it should not be able
to be `null` at [line 1453 ](https://github.com/aws/aws-sdk-java/blob/e350b7e463e51424a2c3e5963e5f94ffcc8bdb4b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1453)either.

Thanks,

Adrian

**Comment by shorea** [comment]
That's correct.

**Comment by debora-ito** [comment]
Looks like @shorea answered your questions, so I'll go ahead and close this. Please feel free to reopen if you any follow up questions.
