### ISSUE TITLE
Specify privateKey with InputStream type in CloudFrontCookieSigner.getCookiesXxx

### ISSUE THREAD

**Issue by yamakz5555** [aws/aws-sdk-java#1771]
com.amazonaws.services.cloudfront.CloudFrontCookieSigner 

In getCookiesForCannedPolicy and getCookiesForCustomPolicy, I want to be able to specify privateKey with InputStream type.

An example
```
public static CookiesForCustomPolicy getCookiesForCustomPolicy(Protocol protocol,
                                                                   String distributionDomain,
                                                                   InputStream privateKeyFileStream,
                                                                   String resourcePath,
                                                                   String keyPairId,
                                                                   Date expiresOn,
                                                                   Date activeFrom,
                                                                   String ipRange)

```

Use it in a case where private key file exists in zip or jar file.

**Comment by shorea** [comment]
Would you be willing to open a PR? 

Note that when source private key from a file we detect it's type based on extension (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudfront/src/main/java/com/amazonaws/services/cloudfront/util/SignerUtils.java#L159) so when using an InputStream we'd likely have to pass in the format as a separate parameter.
