### ISSUE TITLE
SpotFleetLaunchSpecification allows for a single instance type only

### ISSUE THREAD

**Issue by jacool** [aws/aws-sdk-java#1775]
SpotFleetLaunchSpecification.setInstanceType seems to support a single instance type only, which defies the purpose of having a spot fleet.

**Comment by debora-ito** [comment]
Hi @jacool, a Spot Fleet Launch Specification can have only one instance type, but you can define more than one launch specification in the Spot Fleet request. Then, you can use Instance Weighting, launch template Overrides and Target Capacity configurations to define the rules of creation of your fleet.

Please take a look at this EC2 documentation page for more info on how the Spot Fleet request is fulfilled, and for specification examples: 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html

This blog post may also be helpful:
https://aws.amazon.com/blogs/aws/ec2-fleet-manage-thousands-of-on-demand-and-spot-instances-with-one-request/
