### ISSUE TITLE
MFA authorisation not working for the ProfileCredentialsProvider in the Java SDK

### ISSUE THREAD

**Issue by lawrence-mok** [aws/aws-sdk-java#1777]
In the java sdk (version 1.11.421), it looks like when the ProfileCredentialsProvider is trying to assume the relevant role (arn:aws:iam::226069237469:role/platform/devops-iam-role), it is not passing the "mfa_serial" from the credentials file.

This is highlighted by the following code snippet within STSAssumeRoleSessionCredentialsProvider.java:
```
    private SessionCredentialsHolder newSession() {
        AssumeRoleRequest assumeRoleRequest = new AssumeRoleRequest().withRoleArn(roleArn)
                .withDurationSeconds(roleSessionDurationSeconds)
                .withRoleSessionName(roleSessionName)
                .withPolicy(scopeDownPolicy);
        if (roleExternalId != null) {
            assumeRoleRequest = assumeRoleRequest.withExternalId(roleExternalId);
        }

        AssumeRoleResult assumeRoleResult = securityTokenService.assumeRole(assumeRoleRequest);
        return new SessionCredentialsHolder(assumeRoleResult.getCredentials());
    }
```

This will probably require a code fix to add the ".withSerialNumber" (with the value from the relevant profile in the credentials file) and ".withTokenCode" (probably prompting the user to enter the value) calls when building the assume role request.

**Comment by debora-ito** [comment]
Closing this due to duplication of #1345. 
Feel free to reopen if you think you have a different issue or have other questions.
