### ISSUE TITLE
DynamoDB validation failure misreports failing attribute's name

### ISSUE THREAD

**Issue by superbrown** [aws/aws-sdk-java#1779]
Upon validation failure, the following code within the `com.amazonaws.services.dynamodbv2.document.ItemUtils` class is incorrectly hard-coded to report "val" as the name of the invalid attribute rather than the actual attribute name.

>     public static void checkInvalidAttribute(String attrName, Object val) {
>         checkInvalidAttrName(attrName);
>         ValidationUtils.assertNotNull(val, "val");
>     }

The code should read like this:
>     public static void checkInvalidAttribute(String attrName, Object val) {
>         checkInvalidAttrName(attrName);
>         ValidationUtils.assertNotNull(val, attrName);
>     }

**Comment by debora-ito** [comment]
Thanks for reporting the bug! I'll keep you posted when a fix is released.

**Comment by millems** [comment]
Fixed in latest release
