### ISSUE TITLE
DAX client swallows cluster startup exception

### ISSUE THREAD

**Issue by dsilvasc** [aws/aws-sdk-java#1780]
The private constructor for `ClusterDaxClient` swallows exceptions on startup:

```java
        try {
            this.mCluster.startup();
        } catch (IOException var4) {
            LOG.warn("exception starting up cluster client: " + var4, var4);
        }
```

Consequently when we call `AmazonDaxClientBuilder.standard().withEndpointConfiguration(endpoint).build()` and the cluster fails to start up (for example because "Client does not have permission to invoke Endpoints"), then the application continues and every client call (for example, to `getItem`) fails with:

```
[ClusterDaxClient] Retrying request after exception: No endpoints available
[ClusterDaxClient] Retrying request after exception: No endpoints available
com.amazonaws.AmazonClientException: Unable to call cluster endpoint: No endpoints available
```

Can the ClusterDaxClient constructor and the builder propagate the exception to let the application fail at startup?

**Comment by debora-ito** [comment]
I've forwarded your request to the DAX team, because the AWS SDK team doesn't own the DAX client. Going to close this issue but will post any updates we get from the DAX team.
