### ISSUE TITLE
non-blocking DAX client

### ISSUE THREAD

**Issue by dsilvasc** [aws/aws-sdk-java#1783]
The DAX client uses blocking IO, which requires additional threads when you want to call DAX and do other work concurrently.  This becomes a problem in a server with a lot of traffic.

The clients at aws-sdk-java-v2 are all HTTP-based so that project won't be helpful to produce a non-blocking DAX client per https://github.com/aws/aws-sdk-java-v2/issues/473

Are there plans to implement a non-blocking DAX client?  If not, is there a protocol/api spec that can be used to implement one independently?

**Comment by dsilvasc** [comment]
Hi @debora-ito -- any news from the DAX team?  Is there any way to get in touch with them?

**Comment by ielkhalloufi** [comment]
> The DAX team replied saying they do plan to implement a non-blocking DAX client matching the Java SDK v2 API, but they don't have a timeline for when it will be available.
> 
> Going to close this issue but will add any updates we get from the DAX team.

Any updates on the issue? Thnx!

**Comment by DamienOReilly** [comment]
I too would be interested in an update on this, thanks.
