### ISSUE TITLE
BucketTaggingConfiguration is NULL if no tags are there for existing bucket, and clears tags when working on reference.

### ISSUE THREAD

**Issue by MartinEmrich** [aws/aws-sdk-java#1785]
While trying to set bucket tags, I ran into two issues where the tags I set do not end up on AWS S3.

First, according to the documentation, getBucketTaggingConfiguration() is supposed to return null only when the bucket does not exist. But it also returns null (instead of an empty BucketTaggingConfiguration) if the bucket exists.

Second, I found out that when calling .setTagSets(tagSet) with the same TagSets object contained in the BucketTaggingConfiguration, it just clears all tags.

Example:

```
		// Get existing tags
		GetBucketTaggingConfigurationRequest getBucketTaggingConfigurationRequest = new GetBucketTaggingConfigurationRequest(
				bucketName);

 		BucketTaggingConfiguration taggingConfiguration = s3.getBucketTaggingConfiguration(getBucketTaggingConfigurationRequest)

		if (taggingConfiguration == null) {
			// Bucket exists, but I got null instead of empty BucketTaggingConfiguration
			taggingConfiguration = new BucketTaggingConfiguration();
		}

		// Add a tag
 		List<TagSet> tagSets = taggingConfiguration.getAllTagSets();

		if (tagSets.isEmpty())
		{
			tagSets.add(new TagSet());
		}
		
		tagSets.get(0).setTag("someKey", "someValue");
		
		taggingConfiguration.setTagSets(tagSets);

		SetBucketTaggingConfigurationRequest bucketTaggingConfigurationRequest = new SetBucketTaggingConfigurationRequest(
				bucketName, taggingConfiguration);
		
		s3.setBucketTaggingConfiguration(bucketTaggingConfigurationRequest);
	
```

Expected: The tag "someKey" with value "someValue" is set.
Actual Result: an empty TagSet is sent to AWS S3.

Cause: within setTagSets(), BucketTaggingConfiguration does not check if the argument is in fact a reference to the same object as contained within the BucketTaggingConfiguration, thus clearing it before addAll() on itself.

**Comment by debora-ito** [comment]
Another solution is to substitute this:
```java
List<TagSet> tagSets = taggingConfiguration.getAllTagSets();
```
with this: 
```java
List<TagSet> tagSets = new ArrayList<>(taggingConfiguration.getAllTagSets());
```
making tagSets a copy of the internal list, and not a reference anymore.

**Comment by MartinEmrich** [comment]
@debora-ito Thanks, after reading the code I removed setTagSets and it works fine.

**Comment by debora-ito** [comment]
Cool! The documentation fix was released, so I'm going to go ahead and close this. Feel free to reopen if any further questions come up.
