### ISSUE TITLE
RestHighLevelClient signer invalid

### ISSUE THREAD

**Issue by Crab2died** [aws/aws-sdk-java#1786]
I want use es `RestHighLevelClient` ,but this signature is invalid, retrun 403,
code:
```
    public RestHighLevelClient createRestClient() {
        AWS4Signer signer = new AWS4Signer();
        signer.setServiceName(serviceName);
        signer.setRegionName(region);
        AWSStaticCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey));
        //AWSCredentialsProvider credentialsProvider = new DefaultAWSCredentialsProviderChain();
        HttpRequestInterceptor interceptor = new AWSRequestSigningApacheInterceptor(serviceName, signer, credentialsProvider);
        RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(
                        HttpHost.create(endpoint)
                ).setHttpClientConfigCallback(hacb -> hacb.addInterceptorLast(interceptor))
        );
        return client;
    }
```

**Comment by varunnvs92** [comment]
403 indicates your signature doesn't match. Our signers has lot of configuration to set and they are not optimal to use independently. I can give you some pointers to guide in right direction. We have limited bandwidth and suggest to use community forums like stackoverflow for non-sdk questions.

* Use our [v2 auth](https://github.com/aws/aws-sdk-java-v2/tree/master/core/auth) module where we refactored signers for individual use. See this [sample code](https://github.com/aws/aws-sdk-java-v2/blob/master/services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/SignersIntegrationTest.java#L121-L156). Remember v2 is in dev preview.
* If you need to use v1, then use AWSS3V4Signer class is for s3 client. Use AWS4Signer for all other services that support SigV4
* Refer to [SignerFactory](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/SignerFactory.java) and [AmazonWebServiceClient](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceClient.java) for configuring the signer.

Thank you.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.
