### ISSUE TITLE
ExpressionSpecBuilder's buildForQuery excludes type from the value map

### ISSUE THREAD

**Issue by BloodChiefStromberg** [aws/aws-sdk-java#1788]
Hi all,

I am creating a `DynamoDBQueryExpression` like this:
```
ExpressionSpecBuilder builder = new ExpressionSpecBuilder()
    .withKeyCondition(S(KEY).eq("a_key"))
    .withCondition(
        B("alive").eq(true)
        .and(...)
   );

QueryExpressionSpec exprSpec = builder.buildForQuery();
DynamoDBQueryExpression queryExpr = exprSpec
    .withKeyConditionExpression(exprSpec.getKeyConditionExpression())
    .withFilterExpression(exprSpec.getFilterExpression())
    .withExpressionAttributeValues(exprSpec.getValueMap())
    .withExpressionAttributeNames(exprSpec.getNameMap());
```
But when I try to query with it:
```
dynamoDbMapper.query(Whatever.class, queryExpr);
```
I get an error stating `Unexpected value type in payload.` I think this is because the `Value Map` of `queryExpr` doesn't include types:
```
":0" -> "a_key"
```
instead of:
```
":0" -> {"S":"a_key"}
```

Am I correct in thinking I should be able to use the API this way? Or is there a more supported way to do what I'm trying to do?

**Comment by debora-ito** [comment]
Hi @BloodChiefStromberg, based on this example =>
 https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.QueryScanExample.html, the suggested way is to use `DynamoDBQueryExpression` with a HashMap to define the attribute values. So, using your code example, it should look something like this:
```
        Map<String, AttributeValue> eav = new HashMap<>();
        eav.put(":val0", new AttributeValue().withS("a_key"));
        eav.put(":val1", new AttributeValue().withBOOL(true));

        DynamoDBQueryExpression queryExpression = new DynamoDBQueryExpression()
                .withKeyConditionExpression(KEY + " = :val0")
                .withFilterExpression("alive = :val1")
                .withExpressionAttributeValues(eav);

        dynamoDbMapper.query(Whatever.class, queryExpression);
```
As another option, you may use `QueryExpressionSpec` like in your example and then use it in this [table.query()](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/Table.html#query-java.lang.String-java.lang.Object-com.amazonaws.services.dynamodbv2.document.RangeKeyCondition-com.amazonaws.services.dynamodbv2.xspec.QueryExpressionSpec-) method. You can check more usage examples on the `ExpressionSpecBuilder` [documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/xspec/ExpressionSpecBuilder.html#ExpressionSpecBuilder--).

**Comment by BloodChiefStromberg** [comment]
Hey @debora-ito ! Thanks for getting back.

Okay, I understand what you are saying. I think a drawback, which my example doesn't make clear, is when program flow could alter the query you are constructing. The solution you suggested, which skirts `QueryExpressionSpec`, would require me to construct a query with pretty janky string building, something like:
```
int value = 0;
String searchFilter = "";
String clientFilter = "";
...

if (StringUtils.isNotBlank(searchText)) {
  String searchFilter = "#d = :d" + value++;
}

if (StringUtils.isNotBlank(clientName)) {
  String clientfilter = "#c = :c" + value++;
}
...

String query = "";
if (StringUtils.isNotBlank(searchFilter) {
  query = query + searchFilter;
}

if (StringUtils.isNotBlank(clientfilter) {
  if (StringUtils.isNotBlank(query)) {
    query = query + " AND " + clientFilter
  }
}
...
// Also have to construct the Value Map
```
Seems like it would be easier if we could just use a `QueryExpressionSpec` to build a `DynamoDBQueryExpression` (semantically seems to make sense, functionally is almost implemented). The specification for a query expression can be used to generate an actual query expression. It helps prevent errors, too, since the `ValueMap` (or `Map<String, AttributeValue>`) isn't decoupled from the rest of the `QueryExpressionSpec`. Basically, I think the API should support a way to programmatically construct `DynamoDBQueryExpressions` better than strings.

The logic to support this is almost there: it's pretty trivial to write a helper function to create the Value Map correctly using `instanceof`, and from there easy to write a helper function to extract all the bits from the `QueryExpressionSpec` and cobble them into a `DynamoDBQueryExpression`, like I do in my example above:
```
DynamoDBQueryExpression<Item> queryExpr = new DynamoDBQueryExpression<Item>()
    .withKeyConditionExpression(exprSpec.getKeyConditionExpression())
    .withFilterExpression(exprSpec.getFilterExpression())
    .withExpressionAttributeValues(helperToAddTypes(exprSpec.getValueMap()))
    .withExpressionAttributeNames(exprSpec.getNameMap());
```
So if the current best practice solution is the string building approach, I think adding support for `QueryExpressionSpec` -> `DynamoDBQueryExpression` wouldn't be too hard. It's already pretty close. But I understand you all are crazy busy! Just my two cents from the real world! Still seems like a cool product, been fun to use so far, so thanks for all the hard work.

**Comment by BloodChiefStromberg** [comment]
(No rush, but pinging again since this is still marked with `waiting for reply`)

**Comment by debora-ito** [comment]
So if you are using `QueryExpressionSpec` to build your query, is there any particular reason why you want to use `DynamoDBQueryExpression`? Because you can obtain the result with table.query(). From the [docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/xspec/ExpressionSpecBuilder.html#ExpressionSpecBuilder--):

```
Table table = dynamo.getTable(TABLE_NAME);
 
ExpressionSpecBuilder builder = new ExpressionSpecBuilder()
    .withKeyCondition(S(KEY).eq("a_key"))
    .withCondition(
        B("alive").eq(true)
        .and(...)
   );

QueryExpressionSpec exprSpec = builder.buildForQuery();
 
ItemCollection<QueryOutcome> col = table.query(HASH_KEY_NAME, "allDataTypes",
     new RangeKeyCondition("range_key_name").between(1, 10), exprSpec);
```

The [DynamoDB docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HigherLevelInterfaces.html) mention a distinction between low-level and high-level interfaces, and `DynamoDBQueryExpression` is part of the latter.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.

**Comment by Stvad** [comment]
Not sure if it's the same for the original poster, but I have a similar request - my case would be using the `ExpressionSpecBuilder` with `DynamoDBMapper`
