### ISSUE TITLE
AWS Cognito - How to exchange authorization code for tokens using the SDK ?

### ISSUE THREAD

**Issue by deepthi-shetty** [aws/aws-sdk-java#1792]
Hi,
I am not able to find any SDKs to exchange the authorization code for tokens.
I see the API **POST /oauth2/token** (https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html).
I am looking for the SDK version of this call.

**Comment by debora-ito** [comment]
Gonna go ahead and close this. Please feel free to reopen if you have further questions.
