### ISSUE TITLE
Need API to fetch EKS supported k8s versions

### ISSUE THREAD

**Issue by vinayakanzen** [aws/aws-sdk-java#1793]
As of now, there is no API to fetch EKS supported k8s version dynamically.

**Comment by debora-ito** [comment]
Hi @vinayakanzen in an effort to keep open only issues regarding the SDK, I'll go ahead and close this but will post any answer we get from the service team. We don't have any updates from them yet.

Feel free to reopen if you have any further questions.

**Comment by ArundathiGV** [comment]
@debora-ito I don't see any API to fetch version. Can you let me know if this issue is addressed? If yes how to do fetch it?

**Comment by debora-ito** [comment]
@ArundathiGV the ticket is in the EKS team backlog, there's no updates.
