### ISSUE TITLE
Record#sequenceNumber is not a sequence, may be unique number, but this is not sequence

### ISSUE THREAD

**Issue by kuzkdmy** [aws/aws-sdk-java#1798]
Doing DynamoDB Streaming via KCL 
I got the case that I can't work with Record#sequenceNumber, because it increment not +1(sure that per each event in shard)
6200000000002513011398
next should be
6200000000002513011399
but what a genious developer implement it in such a way, that this is 
6300000000002513012315
<img width="999" alt="default" src="https://user-images.githubusercontent.com/15995100/47568941-0d0c2e00-d93b-11e8-8f82-17210eb513df.png">

I snapshot commit with last processed element in chunk that comes with KCL, and that's obvious that on error or restart I can got previous chunk elements, but it can't be filtered with this magic sequence generation approach

Thanks.

**Comment by debora-ito** [comment]
Hi @kuzkdmy , from the [Kinesis documentation](https://docs.aws.amazon.com/streams/latest/dev/key-concepts.html#sequence-number) here's a description of the sequence number field:

> Sequence Number
Each data record has a sequence number that is unique within its shard. Kinesis Data Streams assigns the sequence number after you write to the stream with client.putRecords or client.putRecord. Sequence numbers for the same partition key generally increase over time. **The longer the time period between write requests, the larger the sequence numbers become**.

So sequence numbers increase over time, there's no guarantee they will increase by 1.

If you still have questions, the Amazon KCL is maintained in its own github repo, they would be able to help you more over at https://github.com/awslabs/amazon-kinesis-client/issues.

**Comment by kuzkdmy** [comment]
Thanks. 
It was clear that this can be not plus 1
Problem comes with 
6200000000002513011399
next was
6300000000002513012315
let's say that we increment and go up to this value
9900000000002513012315
and what will be the next one after this
10000000000002513012315 - not sure about limits but should be fine
1000000000002513012315 -  not fine(this is some undocumented algorythm)
Anyway thanks.
I'll revisit this and contact KCL repo.
