### ISSUE TITLE
User Attributes with AWS Pinpoint

### ISSUE THREAD

**Issue by aarnaut** [aws/aws-sdk-java#1801]
Hello,

I've been looking for ways to pass user attributes to the Pinpoint client. However, I was able to only attach endpoint attributes. This is not good for me, as I would have to add the same attributes for each endpoint user registers.  I also saw that during the ``executeCode(endpointProfile)`` method in ``TargetingClient``, only userId is added to the ``EndpointUser`` and not the attributes. Could this be a bug? See code below:

        final EndpointUser user;
        if (endpointProfile.getUser().getUserId() == null) {
            user = null;
        } else {
            user = new EndpointUser();
            user.setUserId(endpointProfile.getUser().getUserId()); // user.setUserAttributes as well?
        }

Thank you

**Comment by spfink** [comment]
Can you open a thread on this in the Amazon Pinpoint forum:

https://forums.aws.amazon.com/forum.jspa?forumID=225

This is not a bug in the SDK but rather a specific feature request for the Pinpoint team. They would be able to better respond and triage.
