### ISSUE TITLE
Support new GovCloud (US-East) region

### ISSUE THREAD

**Issue by dsw2127** [aws/aws-sdk-java#1805]
The second GovCloud region - us-gov-east-1 - is now available, so it should be supported in the SDK.

https://aws.amazon.com/blogs/aws/aws-govcloud-us-east-now-open/

**Comment by debora-ito** [comment]
Thank you for reaching out, marking this as a feature request to add the region to the Regions enum. 

In the meantime, you can set the region using a string: `.withRegion("us-gov-east-1")`

**Comment by shorea** [comment]
Apologies, thought I merged this last week but apparently not. Just pushed this, should be released today.
