### ISSUE TITLE
connectionMaxIdleMillis in ClientConfiguration does not allow a value of 0

### ISSUE THREAD

**Issue by mpontes** [aws/aws-sdk-java#1808]
ClientConfiguration's `connectionMaxIdleMillis` treats the value 0 (and negative values) as a special case; if set to 0, the SDK will [not set a `ConnectionKeepAliveStrategy`](https://github.com/aws/aws-sdk-java/blob/1.11.450/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/client/impl/ApacheHttpClientFactory.java#L102) in the underlying Apache HttpClient client (causing it to use the default `DefaultConnectionKeepAliveStrategy`). This is [not documented in ClientConfiguration's Javadoc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#getConnectionMaxIdleMillis--).

I assume it does so due to Apache HttpClient's `ConnectionKeepAliveStrategy` treating negative as a [special case](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ConnectionKeepAliveStrategy.html) meaning "no strategy", which in practice means ["indefinitely"](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java-deprecated/org/apache/http/impl/client/DefaultRequestDirector.java#L496), and it just maps `connectionMaxIdleMillis` to `maxIdleTime` in `SdkConnectionKeepAliveStrategy`.

I have a use case where I'd like to be able to run without connection reuse (when interacting with a third-party, S3 compatible object storage solution that does not handle connection reuse properly for a particular edge case), and I would like to enforce this at the AWS SDK.

Ideally, I would like to be able to set `connectionMaxIdleMillis` to 0 and have the AWS SDK disable connection reuse in the underlying Apache HttpClient client: it could do so by setting the HttpClient builder's `connectionReuseStrategy` to `NoConnectionReuseStrategy` if it's provided with a value of 0 for `connectionMaxIdleMillis`  in the above `ApacheHttpClientFactory`. This would be in line with the expected behaviour of 0 "connectionMaxIdleMillis" meaning "no idle time".

If it's not acceptable to change the current no-op behaviour of setting `connectionMaxIdleMillis` to 0 to mean no connection reuse, I would like to be able to configure this behaviour through some other property.

SDK version: 1.11.450
JRE version: 1.8.0_181

**Comment by millems** [comment]
Sorry that this issue sat for so long. We do not intend to add this feature to 1.11.x of the SDK, because we're trying to concentrate our development effort on 2.x of the SDK (based on customer feedback).
