### ISSUE TITLE
ErrorCode enum is missing for ServiceException

### ISSUE THREAD

**Issue by hrabosch** [aws/aws-sdk-java#1809]
Is it possible to introduce Enum for Error Codes which are in Service Exception response body, please?
Error codes ie for S3 are [here](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList).

If I want to handle this exception and create a different logic for specific error code, only option is compare Code from Error body with hard-coded string. Enum value would be really nice to use and easier to avoid typos.

Or is it possible to get list of error code names and descriptions somewhere, where it would be possible to read them easily (not from HTML webpage)? Then I would read it, parse it to my own enum and use it as dependency 🤔

**Comment by shorea** [comment]
The SDK generally only knows about the exceptions that are present in the service model. For those exceptions we generate subclasses of the service's base exception so you can handle different exceptions by catching different types. I would suggest this is the preferred mechanism for handling exceptions. If the service is returning errors that are not modeled I would press them to model those exceptions so they can be handled by clients.

**Comment by hrabosch** [comment]
@shorea Sorry for later response. Yes this is possible and i like that i am able to get service exception (like S3 exception), but if I would like handle different kinds of S3Service exception and create different logic if it is ie. AccessDenied or NoSuchBucket, it would be nice to have them as enum values or static variables to be sure it will works with latest sdk even if there will be any change for any reason.

**Comment by millems** [comment]
To clarify this feature request, it's to create an enum that includes an entry for every specific exception the service might return? That way you can use a switch statement instead of a catch statement to branch on them?

**Comment by hrabosch** [comment]
Yes thats correct. I think it would be nice to list them to avoid typos, hardcoding strings, etc.
