### ISSUE TITLE
DynamoDB request errors - likely connected to networking

### ISSUE THREAD

**Issue by lukaswelte** [aws/aws-sdk-java#1811]
We run our server in EC2 instances. They use AWS SDK (1.11.447) on Java 8 (1.8.0-8u162) to grab data from Dynamo tables to serve user http requests on our API.
As we need information from multiple different tables we execute the requests in parallel (on different threads), but all using the same AWS SDK client which is shared between these threads.

For very low number of requests everything works fine, but with slightly higher number of requests (around 100 RPM) we see a few issues.

Occasionally requests which usually take around 15ms and at max 60ms are suddenly throwing ClientExecutionTimeouts (configured at 2s - increasing the timeout to 10s is no difference in this issue).

We also see `java.net.UnknownHostException: dynamodb.eu-west-1.amazonaws.com` and `ConnectTimeoutException`, so the network could be the root cause of this problem.

Our client configuration is: 
```
ClientConfiguration()
    .withConnectionTimeout(200)
    .withClientExecutionTimeout(2_000)
    .withMaxErrorRetry(Integer.MAX_VALUE)
```

Especially the `UnknownHostException`s seem interesting as it seems that it can't resolve DNS name.
It is hard to reproduce this issue. It would be awesome if you could help resolve this issue.

Stacktraces:
[ClientExecutionTimeout.txt](https://github.com/aws/aws-sdk-java/files/2599086/ClientExecutionTimeout.txt)
[ConnectTimeoutException.txt](https://github.com/aws/aws-sdk-java/files/2599087/ConnectTimeoutException.txt)
[UnknownHostException.txt](https://github.com/aws/aws-sdk-java/files/2599088/UnknownHostException.txt)

**Comment by pushkar-g** [comment]
We had faced a similar issues . We had to set the TTL in our service - 

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html

**Comment by lukaswelte** [comment]
@pushkar-g thank you. We currently have this property set to 60s and it sadly didn't solve the issue.

**Comment by lukaswelte** [comment]
This was due to a networking error of the instances
