### ISSUE TITLE
S3 select result path java sdk

### ISSUE THREAD

**Issue by KD-Long** [aws/aws-sdk-java#1834]
Hi guys I'm really new to this and am struggling to setup the result path for the example code in the aws doc. If any one could point out the obvious thing i am doing wrong it would be greatly appreciated.

myBucket
    - dir/mydata.csv
    - res/

Basically i want to read the csv in dir and write the out put from my select statement to a new file in res/

private static final String BUCKET_NAME = "myBucket-123456789";
private static final String CSV_OBJECT_KEY = "dir/sea_ice.csv";
private static final String S3_SELECT_RESULTS_PATH = "res/";
private static final String QUERY = "select * from S3Object s";

It runs successfully

Received Stats, Bytes Scanned: 5052 Bytes Processed: 5052
Received End Event. Result is complete.

But no result file found in res

*note i have tried:
 S3_SELECT_RESULTS_PATH = "res";
S3_SELECT_RESULTS_PATH = "res/result.csv";

and get the error (The system cannot find the path specified)

Any help would be greatly appreciated
Thanks

**Comment by debora-ito** [comment]
Can you provide a snippet of your code?

**Comment by debora-ito** [comment]
Closing due to lack of response, please re-open if you have further questions.
