### ISSUE TITLE
Excel Upload in S3 is failling using Java code

### ISSUE THREAD

**Issue by Rashi-Mehta** [aws/aws-sdk-java#1844]
I want to upload a dynamic Excel file in S3 Bucket without storing it in local system.

I have written a code to do so but it is giving error. Please help
public static void uploadToCloud(HSSFWorkbook excelWorkBook) throws IOException
{
    AWSCredentials credentials = new BasicAWSCredentials("a-b-c", "d-e-f");
    AmazonS3 s3client = new AmazonS3Client(credentials);

    for (Bucket bucket : s3client.listBuckets()) {
        System.out.println("Bucket Name - " + bucket.getName());
        String bucketnameS3 = bucket.getName();
        System.out.println("Bucket Creation date - "+bucket.getCreationDate());       

        //creating local file just for testing. This part of code is working as expected.
        try {
            FileOutputStream fileOut = new FileOutputStream(new File("C:\\test.xls"));
            excelWorkBook.write(fileOut);
            fileOut.flush();
            fileOut.close();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        //upload to amazon s3
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        try {
            excelWorkBook.write(byteArrayOutputStream);
            byteArrayOutputStream.close();
        } catch (IOException e) {
            // LOGGER.error(e.getMessage());
        }

        ByteArrayInputStream bi= new ByteArrayInputStream(byteArrayOutputStream.toByteArray());

        bi.read(byteArrayOutputStream.toByteArray());

        Long contentLength = Long.valueOf(byteArrayOutputStream.toByteArray().length);

        ObjectMetadata objectMetaData =new ObjectMetadata();
        objectMetaData.setContentType("application/vnd.ms-excel");
        objectMetaData.setContentLength(contentLength);

        s3client.putObject(new PutObjectRequest(bucketnameS3,"test.xls",bi,objectMetaData) );

        bi.close();
    }
}

Error:[12/14/18 13:08:14:436 IST] 000000ee SystemErr     R com.amazonaws.SdkClientException: Data read has a different length than the expected: 
 dataLength=0;
 expectedLength=165376;
 includeSkipped=false;
 in.getClass()=class com.amazonaws.internal.ReleasableInputStream;
 markedSupported=true;
 marked=0;
 resetSinceLastMarked=false; 
 markCount=1; 
 resetCount=0

**Comment by shorea** [comment]
This seems like a problematic line

```java
    bi.read(byteArrayOutputStream.toByteArray());
```
Here you are reading the input stream into itself and consuming all the data in the process. 

So you want to do something like the following.

```java
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    excelWorkBook.write(baos);
    baos.close();

    ByteArrayInputStream in = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());

    Long contentLength = Long.valueOf(baos.toByteArray().length);

    ObjectMetadata objectMetaData =new ObjectMetadata();
    objectMetaData.setContentType("application/vnd.ms-excel");
    objectMetaData.setContentLength(contentLength);

    s3client.putObject(new PutObjectRequest(bucketnameS3,"test.xls",bi,objectMetaData) );

    bi.close();
```

**Comment by Rashi-Mehta** [comment]
Hi There , Thanks for your response. Yes , after removing the bi.read(byteArrayOutputStream.toByteArray()); It is uploading the excel file. I can see the excel file Uploaded in S3 bucket.Excel filesize also looks fine but when I try to Download or Open the excel file using AWS Console . I am getting excel error : "The file format and extension of .xls don't match . The file could be corrupted or unsafe" .When I click Yes to continue It is opening a blank file. Please help what is the issue and How it can be fixed.

**Comment by Rashi-Mehta** [comment]
In addition to this , I have written Java code to download the file in local.Again I am getting excel error : "The file format and extension of .xls don't match . The file could be corrupted or unsafe" .When I click Yes to continue It is opening a blank file.

**Comment by debora-ito** [comment]
Hi @Rashi-Mehta, using the code example provided by @shorea I was able to upload, download and open a xls file successfully. Since I don't know what's the content of `HSSFWorkbook excelWorkBook` file in your example, I used the following code to create the file: 
```java
FileInputStream fileInputStream = new FileInputStream("\path\test.xls");
HSSFWorkbook excelWorkBook = new HSSFWorkbook(fileInputStream);
```
I'm wondering if the error you're seeing is related to the file content, as explained here: https://support.office.com/en-us/article/a-file-is-in-a-different-format-than-its-extension-indicates-in-excel-0d2dfb3f-b5a9-4a71-9712-0084672921a7

Have you tried opening in a different reader? Also, when you create the file locally are you able to open it?

**Comment by Rashi-Mehta** [comment]
Hi @debora-ito : What my requirement is , I don't want to save my excel file in local .I write it directly to S3 bucket. I have an excelWorkBook Object and I want to transfer content of this Object to S3 then What should I do?If I am saving my file locally and then copying it to S3 It is working fine. but If I write with the help of InputStream the file size is same but no content.Attaching sample file for your reference:uploadToCloud() is the main method where I am trying dynamic writing.
[sample.zip](https://github.com/aws/aws-sdk-java/files/2740469/sample.zip)

**Comment by debora-ito** [comment]
I took a look at the `uploadToCloud()` method in your S3Util.java file, and from line 109 you have:

```java
byte[] bf=new byte[byteArrayOutputStream.toByteArray().length];
ByteArrayInputStream bi=new ByteArrayInputStream(bf);
Long ExcelLength = Long.valueOf(byteArrayOutputStream.toByteArray().length);						         
			
ObjectMetadata eobjectMetaData = new ObjectMetadata();
eobjectMetaData.setContentType("application/vnd.ms-excel");
eobjectMetaData.setContentLength(ExcelLength);
					
s3client.putObject(new PutObjectRequest(bucketnameS3,sheetname,bi,eobjectMetaData));
//s3client.putObject(
//new PutObjectRequest(bucketnameS3, fileName1, bi, eobjectMetaData).withCannedAcl(CannedAccessControlList.PublicRead));
bi.close();
```

In these lines: 
```java
byte[] bf=new byte[byteArrayOutputStream.toByteArray().length];
ByteArrayInputStream bi=new ByteArrayInputStream(bf);
```
`bf` is an empty byte array, which is used to create `bi`, so `bi` is actually empty when uploaded to S3. You should substitute the two lines with:

```java
ByteArrayInputStream bi = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());
```

as suggested in previous comments.

**Comment by Rashi-Mehta** [comment]
@debora-ito :Thanks a ton !! Yes what a silly mistake I was doing :(...Now it is working as expected. This Issue can be closed now !!

**Comment by vijusakhare** [comment]
try
		 {	 //Here Give your aws user credentials instead of xxxx
			 BasicAWSCredentials awscreds = new BasicAWSCredentials("XXXXXXXXXXXXXXXXXXXX","xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
			                                                                                
			 //Give your respected Region endpoint
			 AmazonS3 s3Client = AmazonS3ClientBuilder.standard()   
	    	    	    .withRegion("ap-south-1")
	    	    	    .withCredentials(new AWSStaticCredentialsProvider(awscreds))
	    	    	    .build();
			 
			 String bucketname = "xxxxx";
			 String foldername = "folder1";
			 
			 String filename = "test.xlsx";
			 String filenameLocalIPC = "C:\\Users\\test\\Documents\\test.xlsx";
			 
			 PutObjectRequest request = new PutObjectRequest(bucketname,foldername+"/"+filename,new File(filenameLocalIPC));
			 s3Client.putObject(request);
			 System.out.println("Uploading File Done...!!!!");
			 
			 //Get File From S3 bucket	 
			 S3Object fullObject;
			 fullObject = s3Client.getObject(new GetObjectRequest(bucketname,foldername+"/"+filename));	 
			 System.out.println("Downloading file done...!!");
			
			 S3ObjectInputStream s3ObjectInputStream = fullObject.getObjectContent();
			
			
			 XSSFWorkbook workbook = new XSSFWorkbook(s3ObjectInputStream);
			 XSSFSheet sheet = workbook.getSheetAt(0);
			 
			 
			 
			 Iterator<Row> rowIterator = sheet.iterator();
	                 while (rowIterator.hasNext()) 
	                {
	                 Row row = rowIterator.next();

	                 //For each row, iterate through all the columns
	                 Iterator<Cell> cellIterator = row.cellIterator();
	                 
	                  while (cellIterator.hasNext()) 
	                 {
	                    Cell cell = cellIterator.next();
	                    //Check the cell type and format accordingly
	                    switch (cell.getCellType()) 
	                    {
	                        case Cell.CELL_TYPE_NUMERIC:
	                            System.out.print(cell.getNumericCellValue()+"   ");
	                            break;
	                        case Cell.CELL_TYPE_STRING:
	                            System.out.print(cell.getStringCellValue()+"   ");
	                            break;
	                    }
	                }
	                System.out.println("");
	            }
			 
		
		 
		 
		 }	 catch(Exception e) {
			 e.printStackTrace();
		 }
		 

}

	

}

**Comment by navg223** [comment]
I am also facing similar kind of issue. trying to read s3 file and send as attachment via email. I am using aws ses and java for this.

public class EmailNotification {
	
	static LambdaLogger logger = null;
	private static String SENDER=null;
	private static String RECIPIENT=null;
	private static String SUBJECT=null;
	private static String BODY_TEXT=null;
	
	public void verifyEmailNotification(Context context) throws IOException, MessagingException {
        String bucketName = "bucketName";
        String key = "prefix";
        String fileName = "fileName.xlsx";
        String keyName = key + fileName;
        try {
        	logger = context.getLogger();
        	AmazonS3Client s3Client = (AmazonS3Client) AmazonS3ClientBuilder.defaultClient(); 
            S3ObjectInputStream s3ObjectInputStream = s3Client.getObject(new GetObjectRequest(bucketName, keyName)).getObjectContent();
            String result = new BufferedReader(new InputStreamReader(s3ObjectInputStream))
            .lines()
            .parallel()
            .collect(Collectors.joining(System.lineSeparator()));
            
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            
            for (int i = 0; i < result.length(); ++i)
                bos.write(result.charAt(i));
            
			logger.log("bos content = " + bos);
			ObjectMetadata md = new ObjectMetadata();
			md.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
			md.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
			md.setContentLength(bos.toByteArray().length);
			
            SENDER = "sender email";
			RECIPIENT = "receiver email";
			SUBJECT = "Subject Line";
			BODY_TEXT = "Hi";
			
			Session session = Session.getDefaultInstance(new Properties());
			MimeMessage message = new MimeMessage(session);
			message.setSubject(SUBJECT);
	        
			message.setFrom(new InternetAddress(SENDER));
			message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(RECIPIENT));
			MimeMultipart msg_body = new MimeMultipart("alternative");
			MimeBodyPart textPart = new MimeBodyPart();
			textPart.setContent(BODY_TEXT, "text/plain; charset=UTF-8");
			msg_body.addBodyPart(textPart);
			
			MimeBodyPart att = new MimeBodyPart();
			DataSource fds = new ByteArrayDataSource(bos.toByteArray(), "application/octet-stream");
			att.setDataHandler(new DataHandler(fds));
			att.setFileName(fileName);
	        message.setContent(msg_body);
	        msg_body.addBodyPart(att);
			
	        AmazonSimpleEmailServiceClientBuilder.standard().withRegion(Regions.US_EAST_1).build();
	        AmazonSimpleEmailService client = GetAWSClients.getSES();
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            
            message.writeTo(outputStream);
            logger.log("Output Stream = " + outputStream.toString());
            RawMessage rawMessage = new RawMessage(ByteBuffer.wrap(outputStream.toByteArray()));
            SendRawEmailRequest rawEmailRequest = new SendRawEmailRequest(rawMessage);
            client.sendRawEmail(rawEmailRequest);
            System.out.println("Email sent!");
			
			
        } catch (AmazonServiceException e) {
            // The call was transmitted successfully, but Amazon S3 couldn't process 
            // it, so it returned an error response.
            e.printStackTrace();
        } catch (SdkClientException e) {
            // Amazon S3 couldn't be contacted for a response, or the client
            // couldn't parse the response from Amazon S3.
            e.printStackTrace();
        } 
        
    }

}

**Comment by debora-ito** [comment]
@navg223 can you open a new issue? Make sure to fill all the fields you can in the new issue template.
