### ISSUE TITLE
Public alternative to DynamoDBMappingsRegistry

### ISSUE THREAD

**Issue by johnwalker** [aws/aws-sdk-java#1853]
Hi,

Today, we use the internal class DynamoDBMappingsRegistry in the DynamoDBMapper to get mapping information.

https://github.com/aws/aws-dynamodb-encryption-java/blob/5045e9f657a51f28ead46eacf65d753a2c385aae/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java#L132

Is there a public alternative to DynamoDBMappingsRegistry for getting data about attributes (whether an attribute is a primary key, a version field, and collecting the name of the field)? This would be useful for the dynamodb encryption client.

**Comment by shorea** [comment]
Take a look at the field method on the table mapper class. It has a lot of this information available for a specific attribute.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBTableMapper.java#L169

**Comment by johnwalker** [comment]
It looks like DynamoDBTableMapper is a wrapper around DynamoDBMapper, though. It doesn't seem right for AttributeTransformers to get this information through an internal instance of the DynamoDBTableMapper, since AttributeTransformers are provided to mappers.

Would it be possible to include this data alonside the parameter object passed to the transformer?

**Comment by jonathannaguin** [comment]
Also, DynamoDBTableMapper will only work for classes annotated with @DynamoDBTable, will not work for @DynamoDBDocument for example. However, DynamoDBMappingsRegistry or StandardBeanProperties can load the information on those.

**Comment by millems** [comment]
Unfortunately we're concentrating our development effort on 2.x of the SDK, and as such won't be adding many more features to 1.11.x. Sorry about that.
