### ISSUE TITLE
Upload video of >= 10MB gives "Request entity too large" error

### ISSUE THREAD

**Issue by usmanrana07** [aws/aws-sdk-java#1855]
I'm using following code to upload media files to server , images and small videos are uploading fine but the videos of around >= 10 MB are not uploading and giving status code 413 with error = "Request entity too large" . What is the issue?

```
Map<String, String> headers = new HashMap<>();
        headers.put("Content-Length", String.valueOf(file.length()));
        headers.put("Content-Type", mimeType);
        headers.put("Accept", "application/json");


        ApiRequest apiRequest = new ApiRequest();
        apiRequest.withPath("/s3");
        apiRequest.withHeaders(headers);
        apiRequest.withHttpMethod(HttpMethodName.PUT);
        apiRequest.withParameter("key", key);
        apiRequest.withBody(new FileInputStream(file));

client.execute(apiRequest);
```

**Comment by shorea** [comment]
This is a service side issue, see https://www.keycdn.com/support/413-request-entity-too-large for increasing your max upload size. Closing as not an SDK issue.
