### ISSUE TITLE
Some images give Internal Server Error

### ISSUE THREAD

**Issue by usmanrana07** [aws/aws-sdk-java#1857]
I'm facing a issue with some of the media files for example the image attached here. Other images are uploading fine.  But some images give status code 500 (Internal Server Error). Same image is uploading fine in iOS but not in Android. Following is the code:

```
 public Single<ApiResponse> uploadMediaApiCallAWS(String key, File file) {

        String mimeType = CommonUtils.getMimeType(file.getAbsolutePath());

        Map<String, String> headers = new HashMap<>();
        //headers.put("Content-Length", String.valueOf(file.length()));
        headers.put("Content-Length", String.valueOf(file.length()));
        headers.put("Content-Type", mimeType);
        headers.put("Accept", "application/json");


        ApiRequest apiRequest = new ApiRequest();
        apiRequest.withPath("/s3");
        apiRequest.withHeaders(headers);
        apiRequest.withHttpMethod(HttpMethodName.PUT);
        apiRequest.withParameter("key", key);
        try {
            apiRequest.withBody(new FileInputStream(file));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return Single.fromCallable(() -> client.execute(apiRequest));

    }
```

![iphone x](https://user-images.githubusercontent.com/12212502/50482347-e4221b00-0a07-11e9-9714-86cd3d4e696d.jpg)

**Comment by usmanrana07** [comment]
The issue was due to space in the name of image. Should s3 give issue in that case?

**Comment by srchase** [comment]
@usmanrana07 

You received this error due to a space in the filename? Or the key?

**Comment by usmanrana07** [comment]
In the filename

**Comment by shorea** [comment]
Are you using the AWS SDK for Java? I'm not familiar with this ApiRequest class.

**Comment by usmanrana07** [comment]
I'm using aws-api-gateway sdk for Android.

**Comment by debora-ito** [comment]
Hi @usmanrana07, the SDK for Android is maintained in a different repository, please open an issue at https://github.com/aws-amplify/aws-sdk-android/ and the Android SDK team should be able to help you out.
