### ISSUE TITLE
 {comprehendmedical, us-east-2} was not found in region metadata, 

### ISSUE THREAD

**Issue by rahulgangarde** [aws/aws-sdk-java#1861]
By using comprehendmedical sdk i am budling sample app but i ma getting below error.

 **{comprehendmedical, us-east-2} was not found in region metadata,  trying to construct an endpoint using the standard pattern for this region: 'comprehendmedical.us-east-2.amazonaws.com'**

**Comment by debora-ito** [comment]
Can you share your code snippet?

And please check these guidelines on how to work with Regions and Endpoints: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html

**Comment by rahulgangarde** [comment]
this is code snippet
public static void main(String[] args) {
AWSCredentialsProvider credentialsProvider = new AWSCredentialProvider();
		AWSComprehendMedical client = AWSComprehendMedicalClient.builder().withCredentials(credentialsProvider)
		.withRegion(Regions.US_EAST_2).build();
		DetectEntitiesRequest request = new DetectEntitiesRequest();
		request.setText("some text");
		DetectEntitiesResult result = client.detectEntities(request);
		List<Entity> entities = result.getEntities();
}



public class AWSCredentialProvider implements AWSCredentials,AWSCredentialsProvider {

    @Override
    public String getAWSAccessKeyId() {
        return "xxxxxxxx";
    }

    @Override
    public String getAWSSecretKey() {
        return "xxxxxxxxxxx";
    }

	@Override
	public AWSCredentials getCredentials() {
		String accessKey = getAWSAccessKeyId();
        String secretKey = getAWSSecretKey();
        String sessionToken = StringUtils.trim(System.getProperty(SESSION_TOKEN_SYSTEM_PROPERTY));

        if (StringUtils.isNullOrEmpty(accessKey) || StringUtils.isNullOrEmpty(secretKey)) {
            throw new SdkClientException(
                    "Unable to load AWS credentials from Java system "
                    + "properties (" + ACCESS_KEY_SYSTEM_PROPERTY + " and "
                    + SECRET_KEY_SYSTEM_PROPERTY + ")");
        }
        if (StringUtils.isNullOrEmpty(sessionToken)) {
            return new BasicAWSCredentials(accessKey, secretKey);
        } else {
            return new BasicSessionCredentials(accessKey, secretKey, sessionToken);
        }
	}

	@Override
	public void refresh() {
	}
	@Override
    public String toString() {
        return getClass().getSimpleName();
    }

}

**Comment by debora-ito** [comment]
Thank you! The Comprehend Medical service endpoint is not present in the [endpoints.json](https://github.com/aws/aws-sdk-java/blob/04e24b49b4d3cc3115633d53186940dbe9ce1454/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L660) file, I will contact the service team and ask for an update.

**Comment by debora-ito** [comment]
The Comprehend Medical endpoints are available in `1.11.514`. 

Closing, feel free to reopen if you have more questions.
