### ISSUE TITLE
DAX Request Handlers

### ISSUE THREAD

**Issue by nirajpatel** [aws/aws-sdk-java#1862]
Hi! Using the `AmazonDynamoDBClientBuilder` we have the ability to specify request handlers, but the `AmazonDaxClientBuilder` does not have that ability as the class does not extend `AwsClientBuilder`. Is being able to set up request handlers on the road map? We lose the ability to read capacity usage from DAX/DDB requests.

**Comment by debora-ito** [comment]
Hi @nirajpatel, assuming you're talking about the `AmazonDaxClientBuilder` from the [DAX Client](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.html), I'll forward your request to the DAX team, the AWS SDK team doesn't own the DAX Client. 

Going to close this issue but will post any updates we get from the DAX team.

**Comment by nirajpatel** [comment]
Yes, that client is correct. Thank you @debora-ito!

**Comment by nirajpatel** [comment]
> You can set the ReturnConsumedCapacity property on the request objects such as GetItemRequest to return the read capacity usage. I suppose their usage is not to do it at the request level, but at the client level using something like https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/monitoring/internal/ClientSideMonitoringRequestHandler.html.

Okay, we will look to see if we can hook into the usage at the response level. We are using the DynamoDBMapper so I think we might have to add a layer on top of that. Thank you for getting back to me on this issue! I will reach back out if we have any questions.
