### ISSUE TITLE
Base64 static initialization fails when jaxb-core not in classpath with jaxb-impl >= 2.2.11

### ISSUE THREAD

**Issue by akhaku** [aws/aws-sdk-java#1863]
#1428 noted that certain classes were moved from jaxb-impl to jaxb-core, which caused Base64 to fail to statically initialize. ba4a6a4ce49 updated the static initializer to attempt to not fail if jaxb was not enabled in Java 9. However, in Java8, if you have jaxb-impl on your classpath but not jaxb-core, `JAXBContext.newInstance()` fails with a `NoClassDefFoundError` (which wraps a `ClassNotFoundException`), meaning that the exception is not caught and Base64 fails to initialize.

<img width="1040" alt="screen shot 2019-01-04 at 2 56 21 pm" src="https://user-images.githubusercontent.com/463176/50716773-0b946b80-1038-11e9-941a-1c9668b2122a.png">

**Comment by varunnvs92** [comment]
Isn't `jaxb-core` required to properly initialize JAXBContext?
Can you clarify whats the expected behavior should be?

**Comment by akhaku** [comment]
As of jaxb-impl >= 2.2.11, yes. It looks like the intention of the static block in Base64 is to use jaxb if possible, but fall back to the SDK impl if it's not available. Not catching the NoClassDefFoundError makes that second bit break - the expected behaviour in that case is to bail out and use the SDK impl. With jaxb-impl < 2.2.11, we don't get the NoClassDefFoundError since only jaxb-impl is needed and not jaxb-core. You're right that we should be including the jaxb-core jar ourselves, but Base64 probably shouldn't fail to initialize without that jar.

**Comment by varunnvs92** [comment]
Got it. Catching `Throwable` instead of `Exception` should fix the issue. I will make the change.

**Comment by akhaku** [comment]
Thanks! I opened #1864 to make that change - might be simpler to hit merge on that guy?

**Comment by varunnvs92** [comment]
Fixed in v1.11.485. Thanks for reporting the issue and PR.

**Comment by brunoeufrasio** [comment]
> Corrigido em v1.11.485. Obrigado por relatar o problema e PR.

Atualizando pra essa versão resolveu pra mim tambem
