### ISSUE TITLE
 Route53 - listVPCAssociationAuthorizations  doesn't retrieve vpc's

### ISSUE THREAD

**Issue by danostro** [aws/aws-sdk-java#1865]
Hey,

I have multiple private Hosted Zones and i want to get the vpcId for each zone.
I'm trying to retrieve the data with the following call but always i got empty list:
route53Client.listVPCAssociationAuthorizations(
new ListVPCAssociationAuthorizationsRequest().withHostedZoneId("SomeHostedZoneId"))
.getVPCs

**Comment by debora-ito** [comment]
Hi @danostro, the `listVPCAssociationAuthorizations()` method is used in the case where you want to associate a VPC and a Private Hosted Zone that you created with different AWS accounts, as explained [here](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs-different-accounts.html) in the Route53 docs.

If you want to get the details about VPCs associated with your Private Hosted Zone you can use `getHostedZone()` method ([docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/route53/AmazonRoute53.html#getHostedZone-com.amazonaws.services.route53.model.GetHostedZoneRequest-)).

**Comment by danostro** [comment]
txh

**Comment by danostro** [comment]
thx

**Comment by danostro** [comment]
thx
