### ISSUE TITLE
Support deserialization into a child class.

### ISSUE THREAD

**Issue by snakeru** [aws/aws-sdk-java#1867]
Rick Houlihan showed us recently how one can reuse the same table to store different document types: https://www.youtube.com/watch?time_continue=2558&v=HaEPXoXVf2k&t=2560

This feature request is to support this programming pattern: be able to deserialize into a child class, basing on the sort key.

Example:
StorableDocument {}
Dog extends StorableDocument {id, name, age}
Toy extends StorableDocument {dogId, toyId, name, weight}

Table contents:
HK: dogId SK:"DOG" Data: {dog fields}
HK: dogId SK: "TOY_toyId1" Data: {toy1 fields}
HK: dogId SK: "TOY_toyId2" Data: {toy2 fields}

Mapper setup: specify that if search key is "DOG" then use the Dog class and if search key starts with "TOY_" then use the Toy class.

Now the mapper.query(StorableDocument.class, new DynamoDBQueryExpression<StorableDocument>().withHashKeyValues(dogId));
will return a set of StorableDocument instances, one possibly being Dog and the rest being Toys.

**Comment by debora-ito** [comment]
Marking this as a feature request. The team is actively working on V2 so I don't know if or when this will be prioritized for V1.

**Comment by millems** [comment]
Unfortunately (based on customer feedback) we're devoting our development resources toward 2.x of the SDK, and aren't planning to implement any new features in the 1.11.x mapper at this time.
