### ISSUE TITLE
putobject is slow compared to JClouds

### ISSUE THREAD

**Issue by dil022dixith** [aws/aws-sdk-java#1868]
We are using below code snap to upload the object.
Part size is 128 MB.
We are trying for 200 MB and it takes 7 seconds to upload which is slower as compared to other open source : JClouds. JClouds takes 4 seconds.

 Upload uploadObject = awsTransMgr.upload( theOp.container + suffix, mBmd.getName(), payload.openStream(), objMetadata );
UploadResult uploadResult = uploadObject.waitForUploadResult();

Need help to improve the performance here.

**Comment by dil022dixith** [comment]
<artifactId>aws-java-sdk-s3</artifactId>
   <version>1.11.358</version>

**Comment by varunnvs92** [comment]
I am not familiar with Jclouds. Are you using it to upload to S3 similar to using TransferManager?
Upload performance can vary based on the network, host configuration etc. It would be better to do multiple test runs to get avg time.

Can you provide more details on the test setup?
The part size (128MB) seems a bit high. The default of TransgerManager is 5MB. Can you lower the part sizes and see if there are improvements?

**Comment by dil022dixith** [comment]
This issue happens only with IBM Cleversafe Object Storage which is S3 compatible **and http only**. Https upload is faster as compared to JClouds. Our Minimum part size is 8MB and default is 128 MB. I will test with 8MB and see whether performance increases. 
 TransferManager awsTransMgr = TransferManagerBuilder.standard()
                .withMinimumUploadPartSize( partSize )
                .withMultipartUploadThreshold( partSize )
                .withS3Client( amazonS3Client )
                .build();

--------------------------- dstat output w/ SDK --------------------------
38 2 60 0 0 1| 0 24k| 135k 46M| 0 0 |5635 2295
39 2 58 0 0 1| 0 0 | 127k 45M| 0 0 |5278 1928
48 4 47 0 0 1| 0 4096k| 121k 42M| 0 0 |5418 2085
60 8 30 0 0 2| 0 20k| 128k 48M| 0 0 |5584 2134
38 1 60 0 0 1| 0 0 | 135k 43M| 0 0 |4798 867
34 2 63 0 0 2| 0 0 | 121k 43M| 0 0 |4503 821
32 1 66 0 0 1| 0 0 | 111k 38M| 0 0 |4122 817
41 1 57 0 0 1| 0 0 | 134k 49M| 0 0 |4964 917
32 2 66 0 0 1| 0 4132k| 98k 39M| 0 0 |3869 804
40 2 58 0 0 2| 0 0 | 133k 50M| 0 0 |4960 907
-------------------------- 

12:59:47 PM
----------------- dstat w/ jclouds -----------------
2 1 97 0 0 0| 0 0 | 49k 35M| 0 0 |1898 781
3 2 95 0 0 0| 0 0 | 70k 46M| 0 0 |2399 910
4 2 94 0 0 1| 0 4096B| 104k 68M| 0 0 |3236 1117
5 2 94 0 0 0| 0 0 | 129k 61M| 0 0 |3492 1019
4 2 94 0 0 1| 0 0 | 124k 65M| 0 0 |3830 1839
5 1 94 0 0 1| 0 0 | 120k 59M| 0 0 |3366 1105
3 2 95 0 0 0| 0 24k| 132k 69M| 0 0 |3675 1095
4 1 95 0 0 0| 0 120k| 134k 60M| 0 0 |3502 988
11 4 84 0 0 1| 0 4096k| 128k 66M| 0 0 |4098 1638
27 8 64 0 0 1| 0 16k| 111k 56M| 0 0 |4648 2979
3 2 95 0 0 0| 0 0 | 126k 62M| 0 0 |3380 870
----------------------------

With AWS SDK we get throuhput somewhere around 45-50MBps, whereas with jclouds it is around 55-60MBps  

whether any parameters tuning required to  increase the throughput with AWS SDK, so that we get similar throughtput which might resolve this issue.

**Comment by dil022dixith** [comment]
Lower the part sizes, performance is turned to be bad. 5 MB took around 11 seconds as compared to 7 seconds. I feel higher the Part size, performance will be more.

**Comment by dil022dixith** [comment]
One more query, whether Transfer manager makes use of all available threads during upload or only one thread participate in upload object.

**Comment by varunnvs92** [comment]
> whether Transfer manager makes use of all available threads during upload or only one thread participate in upload object.

If the upload happens in parts and [qualifies for parallel uploads](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadCallable.java#L184), then we use a thread pool of 10 threads (customizable) to do the part uploads.

>> This issue happens only with IBM Cleversafe Object Storage which is S3 compatible **and http only**.

we have tuned the sdk to get the maximum transfer speeds possible. It would be non-trivial for us to optimize the speeds in various object storages and in different configurations. But if you find any generic bottleneck in the current implementation, please provide the details and we can investigate further.

Fyi, we always recommend using `https` as it secure.
