### ISSUE TITLE
 using valid Sandbox credentials with your APNS SNS application

### ISSUE THREAD

**Issue by rajatt07** [aws/aws-sdk-java#1869]
My application shuts down sometime with the following error in the console:

PlatformApplicationDisabledException

I've reached out to aws service team to investigate what I was doing wrong in my program.

SO, they have replied that 👍

PlatformApplicationDisabledException is triggered when the downstream push-notification service rejects the credentials provided with the request.

In your case, the downstream provider is APNS_SANDBOX. Ensure that you are using valid Sandbox credentials with your APNS SNS application.

Apple rejected your credentials, likely due to them being expired, or for a production application.

Can someone guide me to resolve this issue.

Thankyou.

**Comment by rajatt07** [comment]
@timcharper @timcharper @stephenh @varunnvs92 @srchase

**Comment by rajatt07** [comment]
@wolpert @ivoanjo

**Comment by debora-ito** [comment]
Hi @rajatt07, I noticed this issue is an extension of #1813 so I'm going to close this in favor of the original one, as it has more context on the problem.
