### ISSUE TITLE
JsonPolicyReader does not support the NotResource element

### ISSUE THREAD

**Issue by mhuffman-r7** [aws/aws-sdk-java#1872]
`JsonPolicyReader` does not support the `NotResource` resource node in policy statements. However, as of 1.11.298 `JsonPolicyWriter` supported writing `NotResource`. Strangely enough the `withIsNotType` is unused outside of unit tests. The reader simply needs to be updated to support parsing and adding these resources to the statement object.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/policy/internal/JsonPolicyReader.java#L149

I would like this issue to be assigned to me.

**Comment by mhuffman-r7** [comment]
Is this likely to be accepted any time soon?

**Comment by debora-ito** [comment]
Feature released in `1.11.580`. Thank you.

**Comment by mhuffman-r7** [comment]
Thank you.
