### ISSUE TITLE
NoSuckBucket error when bucket definitely exists

### ISSUE THREAD

**Issue by evgeniyasti** [aws/aws-sdk-java#1874]
Hello.

I have a problem where I'm getting a `The specified bucket does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 2870868836` for a bucket called `MyBucket`.

Here is the line of code that fetches the bucket: 

    s3obj = s3Client.getObject("MyBucket", "key00");

And here are the contents of S3:

    "Buckets": [
        {
            "CreationDate": "2018-12-04T18:02:10.310Z", 
            "Name": "MyBucket"
        }, 
        {...}. ...
    ]

Now the really completely confusing part: if I create another bucket called key00, then the line ` s3obj = s3Client.getObject("MyBucket", "key00");` works and does not throw an error. That is when I subsequently run:

    log.info("======>>>>>> Key exits: [" + s3obj.getKey() + "] In bucket: [" + bucketName + "] Verified!! <<<<<<========");

I get the content back from S3.

Can someone please shed some light on this mystery? What am I doing wrong?

**Comment by debora-ito** [comment]
You shouldn't get the `NoSuchBucket` error message in the first place, are the bucket and the s3 client credentials in the same region?

**Comment by debora-ito** [comment]
Closing issue. Feel free to reopen if you need further assistance.

**Comment by imagineLife** [comment]
Hello!
I Am getting the same NoSuchBucket even thought the bucket definitely exists.
I am using minio locally.

I can create buckets, add files to buckets, && read files from buckets, all successfully.
Below are 2 snapshots, 1 of the code, 1 of the console responses. 

Any thoughts?! Thanks!
-Eric-
![Screen Shot 2019-08-15 at 9 43 56 AM](https://user-images.githubusercontent.com/24195040/63098683-62a0de00-bf41-11e9-9c99-ede37ab24e4e.png)
![Screen Shot 2019-08-15 at 9 44 16 AM](https://user-images.githubusercontent.com/24195040/63098691-67fe2880-bf41-11e9-84be-7b3a73ec8ad1.png)
