### ISSUE TITLE
Amazon Elastic Transcoder was unable to decrypt the ciphered key with MD5=******

### ISSUE THREAD

**Issue by itsinayat** [aws/aws-sdk-java#1877]
I am getting error while creating job with HLSCOntentProtection.

Amazon Elastic Transcoder was unable to decrypt the ciphered key with MD5=wJForaVS6T5wok/80E4RYg=="

>1.this is how i am creating encryptionKey ##

public static void main(String[] args) {
    AWSKMS kmsClient = AWSKMSClientBuilder.defaultClient();
    // Encrypt a data key
    //
    // Replace the following fictitious CMK ARN with a valid CMK ID 
  or ARN
    String keyId = "arn:aws:kms:us-east- 
 1:864624737976:key/*********************************";
    ByteBuffer plaintext = 
  ByteBuffer.wrap("a2V5a2V5a2V5a2V5a2V5aw==".getBytes());

    EncryptRequest req = new EncryptRequest().withKeyId(keyId).withPlaintext(plaintext);
    ByteBuffer ciphertext = kmsClient.encrypt(req).getCiphertextBlob();
    String encKey=new String(Base64.encode(ciphertext.array()));
    System.out.println(encKey);

}

>2.This is how i am generating KeyMD5

public static String GenerateKeyMD5(String encryptionKey) {
    byte[] b = Base64.decode(encryptionKey.getBytes());
    byte[] x = Md5Utils.computeMD5Hash(b);
    byte[] nj = Base64.encode(x);
    String keyMD5 = new String(nj);
    System.out.println("keyMD5 is:" + keyMD5);
    return keyMD5;
}
>3.Now I am creating HLSContentProtection as follow

String k="AQICAHiJNZmP67ofdfAWfNjDhl+TTPW7kWLUYnHXQocyT+iPgAGp2tnvx6GOF6OvQyJR/kNJAAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRDuCopOoxFBcs/YsAgEQgDOYcO2BHJbRACWo4Cgp+vAXAuxyE+UeZtWGUmOJwx5wJ4J1zYCbb9FrRaKro7njkcL7Vck=";
    //secure content
          HlsContentProtection hlsContentProtection =new HlsContentProtection()
          .withKeyStoragePolicy("NoStore")
          .withMethod(METHOD)
          .withLicenseAcquisitionUrl("https://s3.amazonaws.com/license-1452/plain.key")
          .withInitializationVector("MTIzNDU2Nzg5MDEyMzQ1Ng==")
         .withKey(k)
         .withKeyMd5(TranscoderSampleUtilities.GenerateKeyMD5(k));

Please help somebody.
Also I am not sure what should be include under plain.key file?

**Comment by debora-ito** [comment]
Hi @itsinayat, I'm following this [Encryption with Elastic Transcoder tutorial](https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/encrypted-tutorial.html), in which it looks like your code is based. 

Here are some points of attention:

- When encrypting your plaintext key with KMS, in this line:
```java
EncryptRequest req = new EncryptRequest().withKeyId(keyId).withPlaintext(plaintext);
```
 the `encryption-context` parameter is missing from the EncryptRequest, as explained in [step3](https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/encrypted-tutorial.html#step-3) of the tutorial:

> Also, make sure that you include the parameter --encryption-context "service=elastictranscoder.amazonaws.com". If you don't include it, the call to KMS succeeds, but Elastic Transcoder won't be able to decrypt your file. 

- Still about `EncryptRequest`, the `withPlaintext()` method  [documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/model/EncryptRequest.html#withPlaintext-java.nio.ByteBuffer-) mentions the SDK performs a Base64 encoding on this field before sending this request to the AWS service. Users of the SDK should not perform Base64 encoding on this field.

- As for using HLS content protection, it looks like Elastic Transcoder does not support it combined with file-level encryption, as this Job Settings [doc](https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/job-settings.html#job-settings-hls-cp) states. You can choose to encrypt the file or the data stream, but not both.

**Comment by itsinayat** [comment]
Hi, @debora-ito ,thank you for your response ,  the problem was same I didn't  "--encryption-context ".
It is resolved now.Now its working.
