### ISSUE TITLE
Mix-up between Neptune APIs to RDS APIs

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1878]
Hi
How come AmazonRDSAsyncClient.describeDBClusters returns Neptune clusters?
The same goes for Neptune DBInstance and RDS DBInstance

Is this expected? Can I use RDS api to discover all Neptune assets?

**Comment by debora-ito** [comment]
Since this is a RDS specific question, could you post it on AWS Forums https://forums.aws.amazon.com/forum.jspa?forumID=60 or StackOverflow?  You may get better support from the service team.
