### ISSUE TITLE
Listing S3 objects encounters error 403

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-java#1880]
I use the following code to initialize S3Client :
```
        if (withCredProvider) {
            AWSCredentialsProviderChain credentialsChain =
                    new AWSCredentialsProviderChain(new ProfileCredentialsProvider("dev"),
                            new EnvironmentVariableCredentialsProvider());
            bldr.withCredentials(credentialsChain);
        }
```
The code works fine when invoked from AWS lambda serving REST request.

When the code (listing objects) is invoked thru Event Rule, I got the following (https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logEventViewer:group=/aws/lambda/HorizonExecPlaneCleaner-CleanerFunction-65TNKCKHRG57;stream=2019/01/15/[$LATEST]bb36ab23004a4781afe2bf35eac4a6e2;start=2019-01-14T00:04:10Z):
```
encountered com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 88F9CA1673278356; S3 Extended Request ID: FkDmV60Ngc9wnjzyG9of/9bTVxsRQL7TtyIiPFJv2FyYIISTeM8Vz1BQIqmF3VpRB5kx03wl+mI=), S3 Extended Request ID: FkDmV60Ngc9wnjzyG9of/9bTVxsRQL7TtyIiPFJv2FyYIISTeM8Vz1BQIqmF3VpRB5kx03wl+mI=
```

**Comment by tedyu** [comment]
Here is the lambda:

https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/HorizonExecPlaneCleaner-CleanerFunction-65TNKCKHRG57?tab=graph

**Comment by debora-ito** [comment]
Hi @tedyu, the links you provided are not shareable, they are only visible with your user credentials.

The `Access Denied` message is usually related to the lack of permissions to access a resource. Permissions on CloudWatch is an extensive subject, so please take a look at this guide on managing access permissions to your CloudWatch Events Resources : https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/iam-access-control-identity-based-cwe.html

For further help, I'd suggest asking on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=138) or StackOverflow, as you may get better support from CloudWatch team.
