### ISSUE TITLE
Multipart Upload failing with TransferManager with 400 Bad Request

### ISSUE THREAD

**Issue by mourya92** [aws/aws-sdk-java#1882]
aws-sdk-java-1.11.478 seems to be adding custom metadata headers(x-amz-meta) in the Individual Parts when using TransferManager. 

S3 is returning : 

> Metadata cannot be specified in this context. (Service: Amazon S3; Status Code: 400; ........)

This seems to be fixed in the latest release. Adding the Issue here for tracking purposes and for other customers to be aware of this issue. 

I believe the error is because of this 
https://github.com/aws/aws-sdk-java/blob/f9beca2471c6fd929908b2f68508bba62a721566/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadPartRequestFactory.java#L102

SDK is simply adding the whole metadata from the PutObjectRequest.

Custom Metadata Headers are supposed to be put only in the InitiateMultipartUpload Method.

**Comment by zoewangg** [comment]
Hi, the issue has been fixed from `1.11.481`. Please upgrade to a newer version and feel free to reopen the issue if you have further questions.
