### ISSUE TITLE
LambdaInvokeFactory Marshalling SQS Event class record field into lowercase "records" 

### ISSUE THREAD

**Issue by loyaldeep** [aws/aws-sdk-java#1888]
AWS lambda expects SQS event JSON to have a field called "Records" but when LambdaInvokeFactory is invoked, `SQSEvent` class is marshalled into a JSON that has a field "records". This is a mismatch of case and the message is rejected by AWS. In order to fix this `@JsonProperty("Records")` needs to be added for setter and getter of field `records` in `SQSEvent` class but then this will affect everything else.

**Comment by debora-ito** [comment]
Hi @loyaldeep, it looks like you're referring to the `SQSEvent` class from the `aws-lambda-java-events` library, which is not maintained by the SDK Team. 

There's a separate repository for it at https://github.com/aws/aws-lambda-java-libs where you should be able to get help with your issue. 

Going to go ahead and close this. Feel free to reopen if it's not about the `aws-lambda-java-events`  or if you have other issues relating to the SDK.

**Comment by debora-ito** [comment]
And it seems like they already have an open issue related to that: https://github.com/aws/aws-lambda-java-libs/issues/45.
