### ISSUE TITLE
S3EventNotification can't handle blank dates

### ISSUE THREAD

**Issue by RyanSattler** [aws/aws-sdk-java#1889]
I'm trying to use S3EventNotification as the input parameter to a Lambda handler. Unfortunately, the incoming notification (which is generated by AWS) seems to have a value of "" (empty string) for the field `eventTime`. The constructor of S3EventNotification can't handle this (it expects missing dates to be null rather than blank - see line 383 here: https://github.com/aws/aws-sdk-java/blob/7bf0fbec42de8a7d54875510f27fb363ca2d19f5/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/event/S3EventNotification.java ), so the de-serialization fails immediately.

This means we can't use this class as intended.

Possible solution - skip parsing empty dates as well as `null` ones.

**Comment by RyanSattler** [comment]
Update: It's possible the date value wasn't actually blank, but rather that the incoming message was a different shape than expected (was tricky to debug due to the error happening before we get control), and that this was just the first error encountered.

**Comment by debora-ito** [comment]
@RyanSattler have you got more updates on your case?

**Comment by RyanSattler** [comment]
After further testing it was as described above and we were able to handle it. I guess this can be marked as not-a-bug. (Though I still think ideally the S3EventNotification being able to handle empty-string input in the eventTime field would be nice, even though that wasn't the real problem in this case).
