### ISSUE TITLE
Aws-s3 bucket location is not returned properly for the region US East (N. Virginia)

### ISSUE THREAD

**Issue by Naveen1805** [aws/aws-sdk-java#1890]
I tried to get the bucket location for a particular bucket in US East (N. Virginia) region using java sdk. Instead of returning "us-east-1" is return "US". Is there any way to handle this.

code:
 bucketRegion = s3Client.getBucketLocation(bucketName);

instead of "us-east-1" is return "US", so i can't able to access that bucket by setting US as the client region

**Comment by Naveen1805** [comment]
@dagnir  can u plz help me with this. In #1470  you explained about it.  suppose if amazon add one more region to US Standard how to handle it?

**Comment by spfink** [comment]
As @dagnir mentioned in th linked issue, we can't change this as it would break backwards compatibility.

You can safely assume that US maps to us-east-1. All future regions will correctly return the full region. Only us-east-1 will return this behavior.

**Comment by rsby** [comment]
Hey Sam, I understand that the function cannot be changed as it would break backwards compatibility, but that does not mean the product cannot be improved. Some options:

1. Update the Javadoc to inform users of the surprising behavior 
2. Deprecate the old methods and add new ones that work as expected

Some quick Googling indicates that this is not an uncommon pain-point for consumers of this product.
