### ISSUE TITLE
AWSPricingClient filters are ignored when getting list of products

### ISSUE THREAD

**Issue by marcin-sumologic** [aws/aws-sdk-java#1891]
I try to use Amazon pricing API to get list of prices for certain instances (in Scala):

```scala
val ec2Only = new Filter()
    .withField("ServiceCode")
    .withType(FilterType.TERM_MATCH)
    .withValue("AmazonEC2")

val convertibleOnly = new Filter()
    .withField("OfferingClass")
    .withType(FilterType.TERM_MATCH)
    .withValue("convertible")

val noUpfrontOnly = new Filter()
    .withField("PurchaseOption")
    .withType(FilterType.TERM_MATCH)
    .withValue("No Upfront")

val linuxOnly = new Filter()
    .withField("operatingSystem")
    .withType(FilterType.TERM_MATCH)
    .withValue("Linux")

val c4large = new Filter()
    .withField("instanceType")
    .withType(FilterType.TERM_MATCH)
    .withValue("c4.xlarge")

val client = AWSPricingClientBuilder
    .standard()
    .withRegion("us-east-1")
    .withCredentials(new AWSStaticCredentialsProvider(creds))
    .build()

val response = client.getProducts(
    new GetProductsRequest()
        .withFormatVersion("aws_v1")
        .withServiceCode("AmazonEC2")
        .withFilters(ec2Only, linuxOnly, noUpfrontOnly, convertibleOnly, c4large)
        .withMaxResults(10)
)

// Here response is not filtered...

// RESPONSE: ... "OfferingClass":"standard", ...
```
unfortunately instead of filtered list I get a list of products that looks unfiltered (e.g. there are product with `OfferingClass` `standard` although I have a filter for `OfferingClass = convertible`). 

I use Maven package:
```xml
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-pricing</artifactId>
      <version>1.11.483</version>
    </dependency>
```

I have already checked that the attributes that I use for filtering are on the lists of available attributes as described here: https://aws.amazon.com/blogs/aws/aws-price-list-api-update-new-query-and-metadata-functions/

The problem seems to be on the API side. Also I want to add that right now downloading full price' JSON file (https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json) with 500MB+ size is unacceptable for me.

**Comment by debora-ito** [comment]
Hi @marcin-sumologic, here's what I found in the Filter [documentation](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_pricing_Filter.html) : 

**Field**
The product metadata field that you want to filter on. You can filter by just the service code to see all products for a specific service, filter by just the attribute name to see a specific attribute for multiple services, or use both a service code and an attribute name to retrieve only products that match both fields.

Valid values include: ServiceCode, and all attribute names

So OfferingClass and PurchaseOptions are not actually product attributes, but terms describing ways to purchase the product. You can see the difference between product attributes and terms in the last two output examples in the [blog post](https://aws.amazon.com/blogs/aws/aws-price-list-api-update-new-query-and-metadata-functions/) you mentioned.

Regarding your feedback on the size of the JSON file, I'll forward it to the Pricing service team.

**Comment by marcin-sumologic** [comment]
@debora-ito Thank you very much for your explanation. Now I can see my mistake. Indeed `OfferingClass` and `PurchaseOptions` are part of `term`s and are not product attributes.

**Comment by debora-ito** [comment]
Glad we were able to help!

Closing this, feel free to reopen if you have further questions.
