### ISSUE TITLE
calling iotClient.describeEndpoint(DescribeEndpointRequest()) returns wrong AWS IOT Endpoint

### ISSUE THREAD

**Issue by tsypuk** [aws/aws-sdk-java#1900]
method iotClient.describeEndpoint(DescribeEndpointRequest())
returns wrong Endpoint information, devices can not connect to this endpoint. AWS changed the connection URL semantic for new devices 
```
from:
xxxxxxxxxx.iot.eu-west-1.amazonaws.com
to:
xxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com

```
But SDK code still returns all URL:
**xxxxxxxxxx.iot.eu-west-1.amazonaws.com** : this is what returns iotClient
**xxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com** : this is what expected, and in console.

As a result devices can not connect to wrong endpoint.
This method is used in autoprovissioned device creation and breaks the functionality.

**Comment by shvld** [comment]
When new iot device is created, aws console displays "-ats.iot.eu-west-1.amazonaws.com" endpoint on device/Interact page. Thus, we expect to use Amazon Trust Services Endpoints signed with recommended root certificates. In fact, when this endpoint queried via API, the API returns .iot.eu-west-1.amazonaws.com, i.e.VeriSign endpoint.

**Comment by debora-ito** [comment]
I'm not very familiar with AWS IoT, but setting endpoint type as `iot:Data-ATS` in the `DescribeEndpointRequest()` is what you're looking for?

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.
