### ISSUE TITLE
Inconsistent equality of com.amazonaws.services.ec2.model.Image

### ISSUE THREAD

**Issue by DevInsanity** [aws/aws-sdk-java#1903]
I've discovered that two Image instances representing the same AMI returned from two separate calls to describeImages (from the same EC2 client object) are not always equal.

Based on my debugging, this appears to be caused by the AMI having multiple block device mappings, and they are not always returned in a consistent order. For example, one instance will have /dev/sda1 then /dev/sdb, while other other has /dev/sdb then /dev/sda1.

The equals and hashcode method on Image should not care about the order of block device mappings, provided the same set are there, or the block device mapping list should be sorted into a consistent order.

**Comment by varunnvs92** [comment]
SDK unmarshalls the xml data sent by service (Amazon EC2) into the Java objects. If the data sent by service have device mappings in different order in different calls, SDK will create the list in the same order given in the xml response. As SDK use ArrayList and don't sort, there is no guarantee the the elements will be in the same order. It would be a non-trivial change for us to preserve the order and there might also be a performance issue if we try to sort every list.

What is your use case?
It should be trivial to have custom code in your application to do equality check for unsorted lists

**Comment by DevInsanity** [comment]
In this case, we have some tooling which is used to manage our EC2 estate. As part of this, we had a case where we were generating the intersection of two sets of EC2 instances which had been returned from different queries to the API. This worked fine for instances with only a single disk, but we spotted inconsistencies on the instances with multiple disks which we narrowed down to this.

As a workaround, we adjusted our code to perform the intersection based purely on the instance ids.

However, since no changes were made to the instances in question between the queries, two java objects representing the same EC2 instance (in the same state) should be considered equal to each other. This not being the case is somewhat surprising.

**Comment by varunnvs92** [comment]
I understand this can come as surprise as xml responses sent by service need not be in same order every time which affects elements order in lists. As mentioned earlier, it would be non-trivial to make the change as it affects all services with lists. We can consider this if there are similar requests from other customers. As you have a workaround, I will go ahead and close the issue.

Feel free to reopen if you have other questions/concerns.
