### ISSUE TITLE
Removing buckets and inner files syncing with DynamoDB

### ISSUE THREAD

**Issue by turboT4** [aws/aws-sdk-java#1906]
What I'm trying to achieve here is that, in case a bucket that wants to be written in exists, the program must remove the entire bucket and its contents so it can start again.

Regarding removing the buckets I'm just following the AWS page https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3-buckets.html#remove-objects-from-an-unversioned-bucket-before-deleting-it

But when I was removing buckets manually for quick testing I was unable to do so because an exception was thrown regarding the metadata.

`com.amazon.ws.emr.hadoop.fs.consistency.exception.ConsistencyException: Directory 'sample_dir' present in the metadata but not s3`

Does doing that removal with the API solves the syncing problem with DynamoDB or that should be done in further steps?

**Comment by debora-ito** [comment]
Hi @turboT4 I'm not sure if I understand the question. When you say:
> But when I was removing buckets manually for quick testing I was unable to do so because an exception was thrown regarding the metadata.

what do you mean by "removing manually"? Does the error show when you remove them "manually" or when you try to run your code?

Can you share a code example of what you're trying to achieve?

**Comment by turboT4** [comment]
Sorry for not being clear there. What I mean with removing them manually is just going into the AWS website and deleting them there, not via the AWS SDK Java or any other API. Don't really know if that makes a difference or not whether the metadata is erased.

There isn't much code to show I'm afraid, it's just a plain Apache Spark `.write` call which tries to write data into buckets with the same name as when they were removed, so it seems that when deleted, metadata is still there and it gets a kind of mismatch.

**Comment by debora-ito** [comment]
It depends on how you create the "folder". Quoting the S3 [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html):

> There is no hierarchy of subbuckets or subfolders; however, you can infer logical hierarchy using key name prefixes and delimiters as the Amazon S3 console does.

For S3, everything is an object. So using your example, if you uploaded the following objects to your `mainBucket`:
- example/
- example/contains/example.txt

you'll only have two objects in your bucket, and the following code will return true:
```java
s3Client.doesObjectExist("mainBucket", "example/");
s3Client.doesObjectExist("mainBucket", "example/contains/example.txt");
```
but 
 ```java
s3Client.doesObjectExist("mainBucket", "example/contains/"); //return false
```
will return false.

Also, there is no difference if you create a folder in the AWS Console or using the SDK, but you may be subject to eventual consistency.

**Comment by turboT4** [comment]
Got it! Thanks a lot for the explanation! 😄 🤙
