### ISSUE TITLE
Missing fields on ELB Listener Action

### ISSUE THREAD

**Issue by opsxcq** [aws/aws-sdk-java#1910]
The class `com.amazonaws.services.elasticloadbalancingv2.model.Action` doesn't have all attributes that represent the necessary configuration, it has only `targetGroupArn` and `type` some examples of usecases that are missing:

### Redirect http to https

Is not possible to set the redirect rule, example `HTTPS://#{host}:443/#{path}?#{query}`, neither the status code, example `HTTP_301`.

### Static response

Can't set the static response.

### Path based routing

Is not possible set via API the field (`path`, `header`, etc...) and the value to be compared with to determine a route.

**Comment by debora-ito** [comment]
Hi @opsxcq, which version of SDK are you using? 

Based on the Action [documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticloadbalancingv2/model/Action.html) of the latest version, you can set the redirect rule using [`RedirectActionConfig`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticloadbalancingv2/model/RedirectActionConfig.html) and the fixed responses with [`FixedResponseActionConfig`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticloadbalancingv2/model/FixedResponseActionConfig.html). 

The Path-based routing can be created setting [`RuleConditions`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticloadbalancingv2/model/RuleCondition.html) when you create or modify a rule.

**Comment by opsxcq** [comment]
Hello,

Bellow the dependency that I'm using in my `pom.xml` file:

```xml
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk</artifactId>
			<version>1.11.327</version>
		</dependency>
```

**Comment by debora-ito** [comment]
The configurations I mentioned were added in `1.11.374`, so upgrading the SDK version should solve the issue.

Closing this, please feel free to reopen this if the problem persists.
