### ISSUE TITLE
Sign in with sms_mfa challenge sends otp again

### ISSUE THREAD

**Issue by AnandhiRaghuraman** [aws/aws-sdk-java#1914]
I am signing in with username, default password, new password, challenge as force-change-password. It generates an otp and asks for next challenge sms_mfa. now i am signing in with username, new password, otp, using below code, again it is sending an otp, which is not required. Please fix this issue.

	
		//add the new password to the params map
	   Map<String,String> challengeParams = new HashMap<String,String>();
	   challengeParams.put(USERNAME, username);
	   challengeParams.put(PASSWORD, password);
	   challengeParams.put(SMS_MFA_CODE, mfaCode);
		
	   //populate the challenge response
	   final AdminRespondToAuthChallengeRequest challengeRequest = new AdminRespondToAuthChallengeRequest();
		         challengeRequest.withChallengeName(ChallengeNameType.SMS_MFA)
		         .withClientId(cognitoConfig.getClientId())
		           .withChallengeResponses(challengeParams)
		           .withUserPoolId(cognitoConfig.getUserPoolId())
		           .withSession(mySession);
		  
			        AdminRespondToAuthChallengeResult challengeResult = cognitoClient.adminRespondToAuthChallenge(challengeRequest);

**Comment by debora-ito** [comment]
Hi @AnandhiRaghuraman, I wasn't able to reproduce your issue. Here's what I've done, in high level:

1.  Created a new user `user01` using AWS Console, provided phone number and email. User status is FORCE_CHANGE_PASSWORD
2. Using the Java SDK, I initiated a new `AuthFlow` of type ADMIN_NO_SRP_AUTH for `user01` , which returned a challenge type NEW_PASSWORD_REQUIRED
3. In a `RespondToAuthChallengeRequest`, I provided username `user01`, a new password and challenge type NEW_PASSWORD_REQUIRED. As a result I got a new challenge SMS_MFA
4. Then I used your code snippet to provide `user01`, password (the new one) and the SMS_MFA_CODE I got from SMS, in a `AdminRespondToAuthChallengeRequest`. But after that I did not get a new code, as you did. 

Since this is a question specific to Cognito, its authentication flows and how to use them, we recommend their [AWS Service Forum](https://forums.aws.amazon.com/forum.jspa?forumID=173) as a more reliable place to ask. We also suggest asking on StackOverflow.

**Comment by Deepakms92** [comment]
Hi,

I have added the MFA for a user on Cognito console and when i do a login through my java sdk it finds a SMS_MFA challenge , so i get a OTP when i login . However i give the OTP and try to login and again i get a new OTP , i have given the code here .is it and issue from AWS side?

`public SpringSecurityUser signIn(AuthenticateRequest authenticateRequest) {
        AuthenticationResultType authenticationResult = null;
        AWSCognitoIdentityProvider cognitoClient = getAWSCognitoIdentityProvider();

        try {
            final Map<String, String> authParams = new HashMap<>();
            authParams.put(USERNAME, authenticateRequest.getUsername());
            authParams.put(PASS_WORD, authenticateRequest.getPassword());

            String sessionResult= null;
            final AdminInitiateAuthRequest authRequest = new AdminInitiateAuthRequest();
            authRequest.withAuthFlow(AuthFlowType.ADMIN_NO_SRP_AUTH)
                    .withClientId(clientId)
                    .withUserPoolId(userPoolId)
                    .withAuthParameters(authParams);

            AdminInitiateAuthResult result = cognitoClient.adminInitiateAuth(authRequest);
            if (StringUtils.isNotBlank(result.getChallengeName())) {
                if (SMS_MFA.equals(result.getChallengeName())) {
                    if (null == authenticateRequest.getPassword()) {
                        throw new CognitoException("User must provide a new password", CognitoException.USER_MUST_CHANGE_PASS_WORD_EXCEPTION_CODE, result.getChallengeName());
                    } else {

                        final Map<String, String> challengesResponse = new HashMap<>();
                        challengesResponse.put(USERNAME, authenticateRequest.getUsername());
                        challengesResponse.put(PASS_WORD, authenticateRequest.getPassword());
                        challengesResponse.put(SMS_MFA_CODE, authenticateRequest.getMfaCode());
                        final AdminRespondToAuthChallengeRequest requestChallenge = new AdminRespondToAuthChallengeRequest();
                        requestChallenge
                                .withChallengeName(ChallengeNameType.SMS_MFA)
                                .withChallengeResponses(challengesResponse)
                                .withClientId(clientId)
                                .withUserPoolId(userPoolId)
                                .withSession(result.getSession());

                        AdminRespondToAuthChallengeResult requestChallengeResponse = cognitoClient.adminRespondToAuthChallenge(requestChallenge);
                        authenticationResult = requestChallengeResponse.getAuthenticationResult();

                    }


                } else {
                    throw new CognitoException(result.getChallengeName(), CognitoException.USER_MUST_DO_ANOTHER_CHALLENGE, result.getChallengeName());
                }

            } else {

                authenticationResult = result.getAuthenticationResult();
            }`
