### ISSUE TITLE
Cognito Client adminInitiateAuth() REFRESH_TOKEN Flow using Client Secret

### ISSUE THREAD

**Issue by abrar-qureshi** [aws/aws-sdk-java#1917]
I have followed the example code at https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html#cognito-user-pools-computing-secret-hash for calculating and passing a secret hash to AWS Cognito client in Java using adminInitiateAuth() ADMIN_NO_SRP_AUTH flow for signing in a user and it works as expected for an app client with a secret. However, for the same app client when I try a similar approach for REFRESH_TOKEN_AUTH or REFRESH_TOKEN flows, I keep getting the following exception

`Unable to verify secret hash for client xxx Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException`.

For the same user pool, if I create a client without any secret it works fine. Makes me wonder if there's a bug in your SDK or a gap in your documentation?

**Comment by debora-ito** [comment]
Hi @abrar-qureshi, I wasn't able to reproduce your issue. 

I used an App Client with `Generate Client Key` option on, and my ADMIN_NO_SRP_AUTH flow also worked as expected using the calculated secret hash. 

Here's the code snippet I used for the REFRESH_TOKEN flow:

```
Map<String, String> authParam = new HashMap<>();
authParam.put("REFRESH_TOKEN", REFRESH_TOKEN);
authParam.put("SECRET_HASH", calculateSecretHash(CLIENT_ID, CLIENT_SECRET, USERNAME));

AdminInitiateAuthRequest initiateAuthRequest = new AdminInitiateAuthRequest()
        .withUserPoolId(USER_POOL_ID)
        .withClientId(CLIENT_ID)
        .withAuthFlow(AuthFlowType.REFRESH_TOKEN)
        .withAuthParameters(authParam);

AdminInitiateAuthResult initiateResult = cognitoClient.adminInitiateAuth(initiateAuthRequest);
```
and here `adminInitiateAuth()` was called with success.

I found a [StackOverflow](https://stackoverflow.com/questions/54430978/unable-to-verify-secret-hash-for-client-at-refresh-token-auth) question that says in their case the issue was a username with an `@`, but I tested the code above with a username like `user@email.com` and still didn't get an exception.

I also found a question on [AWS Cognito Forums](https://forums.aws.amazon.com/thread.jspa?messageID=829386&#829386) that says you cannot use an alias to calculate the hash, it must be the real username.

Does any of this help in your case?
If not, could you provide the code sample you're using?

**Comment by abrar-qureshi** [comment]
@debora-ito thank you for looking into it.  I have configured the User Pool to allow email or phone to be used as username. For ADMIN_NO_SRP_AUTH when I authenticate a user I am calculating the secret hash using the email of the user and it works as expected. However, when I do the same for REFRESH_TOKEN flow it doesn't work, this is why I consider it an unusual behavior.

**Comment by debora-ito** [comment]
But did the REFRESH_TOKEN flow work using the real Cognito username to calculate the secret hash?

**Comment by abrar-qureshi** [comment]
No, it didn't. I tried that as well, using the value from the "sub". Here's my code.
`			AuthFlowType flowType=AuthFlowType.ADMIN_NO_SRP_AUTH;
			Map<String, String> authParams = new HashMap<String, String>();
			if (authenitcationRequest.getAuthRequest().getCredentials() != null && authenitcationRequest.getAuthRequest().getRefreshToken() == null) {
				authParams.put("USERNAME", authenitcationRequest.getAuthRequest().getCredentials().getUsername());
				authParams.put("PASSWORD", authenitcationRequest.getAuthRequest().getCredentials().getPassword());
				authParams.put("SECRET_HASH", calculateSecretHash(CLIENTAPP_ID, CLIENTAPP_SECRET,
						authenitcationRequest.getAuthRequest().getCredentials().getUsername()));
			} else if (authenitcationRequest.getAuthRequest().getRefreshToken() != null && authenitcationRequest.getAuthRequest().getCredentials() == null && 
					authenitcationRequest.getAuthroizerJWT()!=null) {
				flowType=AuthFlowType.REFRESH_TOKEN;
				authParams.put("REFRESH_TOKEN", authenitcationRequest.getAuthRequest().getRefreshToken());
				authParams.put("SECRET_HASH", calculateSecretHash(CLIENTAPP_ID, CLIENTAPP_SECRET,username));	
			} else {
				response.setStatus(Status.INVALID_CREDENTIALS);
				authenticationResponse.setAuthResponse(response);
				return authenticationResponse;
			}

			AdminInitiateAuthRequest adminAuthRequest = new AdminInitiateAuthRequest()
					.withAuthFlow(flowType).withAuthParameters(authParams)
					.withClientId(CLIENTAPP_ID).withUserPoolId(POOL_ID);
`

**Comment by debora-ito** [comment]
Can you try using the `Username` instead of the `sub` attribute?

If you have the `sub`, one way to obtain the username is using [`AWSCognitoIdentityProviderClient .listUsers()`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cognitoidp/AWSCognitoIdentityProviderClient.html#listUsers-com.amazonaws.services.cognitoidp.model.ListUsersRequest-) and providing the `sub` as a filter and the user pool id to the ListUsersRequest.

**Comment by debora-ito** [comment]
Closing due to no response, feel free to reopen if you have more questions.

**Comment by henriquedroog** [comment]
@abrar-qureshi Did you find a solution for the issue? I am having the same issue. It works just fine for the **AuthFlowType.ADMIN_NO_SRP_AUTH**, but I get the Unable to verify secret hash for client xxxxx all the time for **AuthFlowType.REFRESH_TOKEN** or **AuthFlowType.REFRESH_TOKEN_AUTH**. I tried changing the AWS SDK Java version but the error still there. The Java SDK version I was am using is 1.11.597, I changed to 1.11.637.
My code is as fallows:
`final Map<String, String> authParameters = new HashMap<>();
			authParameters.put("REFRESH_TOKEN", refreshToken);
			authParameters.put("SECRET_HASH",
					WltCognitoAuthUtil.calculateSecretHash(wltCognitoAuthenticationRequest.getCognitoClientId(),
							wltCognitoAuthenticationRequest.getCognitoClientSecret(), wltCognitoAuthenticationRequest.getUsername()));

			AWSCognitoIdentityProvider cognitoClient = getAmazonCognitoIdentityClient();
			final AdminInitiateAuthRequest authRequest = new AdminInitiateAuthRequest();
			authRequest.withAuthFlow(AuthFlowType.REFRESH_TOKEN)
					.withClientId(wltCognitoAuthenticationRequest.getCognitoClientId())
					.withUserPoolId(wltCognitoAuthenticationRequest.getCognitoUserPoolId())
					.withAuthParameters(authParameters);

			AdminInitiateAuthResult authResult = cognitoClient.adminInitiateAuth(authRequest);`

An app client without secret is not an option for me as it seems not work for the authorization code flow and I need it to work.

**Comment by abrar-qureshi** [comment]
@henriquedroog no, I didn't find a solution yet, it is still a pending issue in our backlog. My sense is that there's a bug in the Java SDK, as I have tried one of the available mobile SDKs for Cognito and this flow works there.

**Comment by abrar-qureshi** [comment]
@henriquedroog no, I didn't find a solution yet, it is still a pending issue in our backlog. My sense is that there's a bug in the Java SDK, as I have tried one of the available mobile SDKs for Cognito and this flow works there.

**Comment by abrar-qureshi** [comment]
@debora-ito do you mind sharing the example app you built, where this flow is working? The code snippet you shared above doesn't work for me, when I plug it in my code. I am looking for an example app where I can plug in my pool Id etc and see how is it different than the one I have.

I have spent quite a bit of time on this off/on and we're reaching a point in our engineering cycle where we can't postpone this anymore.

**Comment by henriquedroog** [comment]
@abrar-qureshi I could get my refresh_token SDK flow working replacing the the username by the userUuId, to get the user UUID I am using the ```adminGetUser``` SDK method to get the user information before executing the refresh token. I am using the user UUID instead of the user email both for creating the ```SECRET_HASH``` and ```USERNAME```. That works fine for me.
My code is like the code below:
```java
Map<String, String> authParameters = new HashMap<>();
authParameters.put("USERNAME", userUuid);
authParameters.put("SECRET_HASH",
        CognitoAuthUtil.calculateSecretHash(clientId(),clientSecret(), userUuid));
authParameters.put("REFRESH_TOKEN", refreshToken);

AdminInitiateAuthRequest authRequest = new AdminInitiateAuthRequest();
authRequest.withAuthFlow(authFlowType)
	.withClientId(clientId())
	.withUserPoolId(userPoolId());
	.withAuthParameters(authParameters);
						

AdminInitiateAuthResult authResult = cognitoClient.adminInitiateAuth(authRequest);
```

**Comment by abrar-qureshi** [comment]
@henriquedroog thank you for sharing this. I did try this months ago and it didn't work for me. Do you mind sharing your maven dependency versions for Cognito? I am wondering if it has anything to do that?

**Comment by henriquedroog** [comment]
@abrar-qureshi I am currently using version AWS SDK version 1.11.637

**Comment by fourgates** [comment]
using the java `2.10.14` sdk and I'm having the same issue for `adminInitiateAuth`. I copy and pasted the code from the aws docs and still get the same exception.

https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html#cognito-user-pools-computing-secret-hash

**Comment by fourgates** [comment]
![image](https://user-images.githubusercontent.com/2994572/68800402-058ff380-0628-11ea-878c-1db2c35b9d94.png)

I created a user pool with no secret and was able to get `adminInitiateAuth` to work properly.
