### ISSUE TITLE
Provide a SDK for accessing AWS Systems Manager Parameter Store (only)

### ISSUE THREAD

**Issue by SchulteMarkus** [aws/aws-sdk-java#1918]
**Is** 
Use [com.amazonaws:aws-java-sdk-ssm](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-ssm) for accessing [AWS Systems Manager Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html)
**Feature request** 
Provide a SDK which provides as only functionality access to SSM parameter store

**Motivation**
I am developing a [Java lambda](https://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-handler-types.html), which needs access to the parameter store - nothing else from SSM is used. I am using aws-java-sdk-ssm for accessing the parameter store. For time being, aws-java-sdk-ssm-1.11.502.jar is 2.1MB "heavy". As size of a Lambda-Jar matters, I would like a more "lightweight" possibility to access SSM parameter store.

**Comment by debora-ito** [comment]
Hi @SchulteMarkus that's an interesting ask, but unfortunately cannot be done in V1. The SSM API is generated based on models provided by the service team, the SDK doesn't do any customizations after that.

Closing this, but feel free to reopen if you have further questions.

**Comment by SchulteMarkus** [comment]
Thanks for feedback.
Can you tell me where to find those models provided by the (SSM-)service team?
