### ISSUE TITLE
iterating s3 versions with 1.11.500 loops forever

### ISSUE THREAD

**Issue by andynuss** [aws/aws-sdk-java#1922]
I had a bucket with about 180 Million versions.  (but I think this bug is reproducible with much fewer).  I adapted code from this url:

https://docs.aws.amazon.com/AmazonS3/latest/dev/delete-or-empty-bucket.html

to try to delete all the versions.  Not only could I not delete them, I could not even count them.  The key difference between this code and mine was that I was using a prefix to parallelize over 64 base64 folder prefixes + the first char of a possible file name.  We ported this code to nodejs and it worked, not only correctly counting the versions, but also deleting them.

I let the counter loop run for 12 hrs, and counted 1.2 trillion versions.

Here's a code snippet:

	private class MyCountThread extends Thread {
			
		private MyCountThread ()
		{
			super(null, null, "count-thread", Configuration.catchly_minimum_thread_stack_size);
		}
		
		public void run ()
		{
			try {
				AmazonS3Client client = AmazonBlobClient.singleton().getClient(BUCKET_REGION);
				String prefix = prefixqueue.poll();
				VersionListing listing = client.listVersions(bucket_name, prefix);
				do {
					List<S3VersionSummary> summaries = listing.getVersionSummaries();
					Iterator<S3VersionSummary> iter = summaries.iterator();
					while (iter.hasNext())
						numversions.incrementAndGet();
					
					if (listing.isTruncated()) {
						listing = client.listNextBatchOfVersions(listing);
					} else {
						break;
					}
				} while (true);
				
			} catch (Throwable t) {
				t.printStackTrace();
				
			} finally {
				if (num_threads.decrementAndGet() == 0) {
					notifydone = true;
					synchronized (notify) {
						notify.notify();
					}
				}
			}
		}
	}

As in I had 64 of these threads to iterate each for the possible beginning filenames of "folder" + filename for versions corresponding to the object key.

**Comment by debora-ito** [comment]
Hi @andynuss, your `iter` iterator is not being iterated, inside the `while (iter.hasNext())` loop you must call `iter.next()` to cycle throught the List.

**Comment by andynuss** [comment]
stupid me.  You can close.

**Comment by debora-ito** [comment]
Closing! Feel free to reopen if you have further questions.
