### ISSUE TITLE
listObjectsV2 with pagination

### ISSUE THREAD

**Issue by sberequek** [aws/aws-sdk-java#1923]
Hi,

I need to create a easy view in jsf for browsing the objects in the backet with the functionality of the next page and previous page. Implementing the pagination I realized that only the next page exists. If I wanted to make the functionality of the previous page I would have to use "ListObjectsV2Request" with the "withStartAfter" method and memorize the key of the previous pages. Is there a "withStartBefore" feature or something? how can I do without having to use an external indexing engine?

**Comment by debora-ito** [comment]
Hi @sberequek, the `ListObjectsV2` API does not have something like the first key of the previous page, so unfortunately the SDK also doesn't provide it. 

You can request the feature to the service team on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).

Closing this, please feel free to reopen if you have more questions.
