### ISSUE TITLE
Add support for ProxySelector

### ISSUE THREAD

**Issue by timothy-volvo** [aws/aws-sdk-java#1927]
Would it be possible to add ProxySelector support? We have been using ProxySelector along with [proxy-vole](https://github.com/MarkusBernhardt/proxy-vole) to configure our java runtimes based on a proxypac file.

I have submitted PR #1926.

**Comment by spfink** [comment]
This sounds perfectly reasonable. Will review and run integration tests on your PR tomorrow.

**Comment by millems** [comment]
Closing in favor of tracking in the PR.
