### ISSUE TITLE
Emr Steps run in sequential manner 

### ISSUE THREAD

**Issue by georgian3590** [aws/aws-sdk-java#1928]
we are submitting the spark jobs using step api of aws sdk. But a time there is only one job is in running state and other jobs are in pending state. If someone can help us to configure our aws emr cluster, where multiple steps can run in parallel

**Comment by debora-ito** [comment]
Hi @georgian3590, I found this [question](https://forums.aws.amazon.com/thread.jspa?threadID=51919) on the AWS Developer Forums with a problem like yours, and the answer was:

> You can't run multiple steps in parallel, but one step can run multiple Hadoop jobs in parallel. (...)

Additionally, I found this AWS post saying how to run parallel Hadoop jobs on your EMR Cluster:
https://aws.amazon.com/about-aws/whats-new/2015/06/run-parallel-hadoop-jobs-on-your-amazon-emr-cluster-using-aws-data-pipeline/ 

I'm not an expert on EMR, so for further help I'd suggest asking on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=52) or on StackOverflow where someone with more knowledge on the service can help.
