### ISSUE TITLE
how to set name while sending email using ses

### ISSUE THREAD

**Issue by Pd51** [aws/aws-sdk-java#1930]
Im able to send mails from ses successfully but how do i add name `companyname <foo@mycompany.com>` .

**Comment by debora-ito** [comment]
Hi @Pd51, the email address that you send email from is the same email you verify to confirm that you own them. 

For more info, please take a look at this tutorial on how to send an email through Amazon SES using the AWS SDK for Java: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-java.html

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.
