### ISSUE TITLE
How can aws-sdk-java 1.11.51x run on android (android studio)?

### ISSUE THREAD

**Issue by kcrossen** [aws/aws-sdk-java#1932]
How can aws-sdk-java 1.11.51x run on android (android studio)? Why, well while it's true that aws-sdk-java 2.x will run on Android, 2.x doesn't support getmetricwidgetimage. The problem seems to be "NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClients" and I've tried about ten different solutions from stackexchange, etc. All failed essentially the same way.

The whole aws-sdk-java works fabulously on IntelliJ IDEA w/ JavaFX/Java 8, so the code works well enough.

**Comment by debora-ito** [comment]
Hi @kcrossen Have you checked the [AWS SDK for Android](https://github.com/aws-amplify/aws-sdk-android)? Or there is a particular reason you want to use the non-Android Java SDK on Android?

**Comment by kcrossen** [comment]
I have been using GetMetricWidgetImage (how it is in the docs), which is
available in 1.11.51x, and which I can't find in the linked sdk above
version 2.x.

Ken

**Comment by kcrossen** [comment]
I have been using GetMetricWidgetImage (how it is in the docs), which is available in 1.11.51x, and which I can't find in the linked sdk above version 2.x.

**Comment by kcrossen** [comment]
Or perhaps you either know how to get the 1.11.x version that works on android or that GetMetricWidgetImage is there and I've not found it.

**Comment by kcrossen** [comment]
In 1.11.5xx GetMetricWidgetImage is a method of a CloudWatch client:
```
        GetMetricWidgetImageRequest cw_image_request = new GetMetricWidgetImageRequest();
        // cw_image_request.setMetricWidget(cw_image_request_text);
        cw_image_request.setMetricWidget(widget_descriptor.toString());
        // Fetched image to buffer
        GetMetricWidgetImageResult cw_image = AWS_CloudWatch_Client.getMetricWidgetImage(cw_image_request);
        // ByteBuffer cw_image_bytebuffer = cw_image.getMetricWidgetImage();
```

**Comment by debora-ito** [comment]
Got it. I don't see a `getMetricWidgetImage` method in the SDK for Android indeed. I'd suggest you to open a request for them to provide the API, as we don't have the expertise to help with Android environment issues.  All I can say is `httpclient` is an [external library](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient) that seems to be missing from the classpath. If you download the `aws-java-sdk` zip from the [AWS page](https://aws.amazon.com/sdk-for-java/), all the third-party libraries jars are present in the zip.

You can also ask your question in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=70&start=0).

Closing this, but feel free to reopen if any further questions come up.

**Comment by kcrossen** [comment]
It's OK, JavaFX may not be the right solution anyway.
