### ISSUE TITLE
Cognito support for authorization code grant flow

### ISSUE THREAD

**Issue by JakubJecminek** [aws/aws-sdk-java#1935]
Hi,
I am trying to replicate functionality of cognito hosted ui sign in page(https://docs.aws.amazon.com/cognito/latest/developerguide/login-endpoint.html), but aws sdk does not provide any method that would take username,password and would return authorization code which could be used for obtaining access/id token. The initiateAuth and adminInitiateAuth only support implicit flow which returns directly access/id token. Is there plan to support this, or has anybody any workaround for this how to retrieve authorization code?

With best regards,
Jakub

**Comment by debora-ito** [comment]
Hi @JakubJecminek, it looks like it's not something the Cognito API provides in one simple method, see this [question](https://forums.aws.amazon.com/thread.jspa?threadID=274692) on AWS Forum.

You can follow the steps of the Authorization Code Grant flow described in this blog [post](https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/), interacting with https endpoints the same way the hosted UI does behind the scenes. 

For further help with Cognito specific requests, I suggest you post it on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173&start=0) as you may get specialized support from the service team.
