### ISSUE TITLE
Client side encryption with customer encryption key

### ISSUE THREAD

**Issue by WEBSHIVOM** [aws/aws-sdk-java#1936]
While in case of client side encryption :
 If bucket is lock enabled  & tried to put object which also hold object lock configuration.In  this scenerio  content-md5 of unencrypted text is attached.Please found snippets accordingly.
![AWS-codesnippet](https://user-images.githubusercontent.com/20663598/54193966-26280c80-44e1-11e9-937e-f676c2129429.JPG)
![aws-error](https://user-images.githubusercontent.com/20663598/54193967-26280c80-44e1-11e9-8fa5-6818a3640f1e.JPG)

**Comment by debora-ito** [comment]
Hi @WEBSHIVOM, currently the SDK doesn't support setting Content MD5 in S3 Encryption Client. I'm marking this as a feature request. 

You can use `putObject()` with Object Lock parameters and Content MD5 with a regular, non-encryption S3 Client.

**Comment by millems** [comment]
Unfortunately we're concentrating our development effort on 2.x of the SDK, and as such won't be adding many more features to 1.11.x. Sorry about that.
