### ISSUE TITLE
Close Connection after calling getMetadata()

### ISSUE THREAD

**Issue by anarwal** [aws/aws-sdk-java#1943]
I am getting LastModifiedDate of an object stored in S3 using getObjectMetadata(). With GetObject there is a close connection function available, however with objectMetadata there doesn't seem to be any such function. This might give connection-open error, like the following error we get for getObject if connection is not closed
`com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool`

**Comment by debora-ito** [comment]
Hi @anarwal, `S3Object` has a close() method so it can release the object stream and its connection can be reused by other request. This is not the case of `ObjectMetadata`, as it does not hold any resources, so it doesn't need to be closeable.

Are you having particular issues with `getObjectMetadata()`? Could you share your use case or a sample code?

**Comment by anarwal** [comment]
Thanks @debora-ito you did answer my confusion. `ObjectMetadata` doesnt not hold any resources so it doesn't need to be closeable.

**Comment by debora-ito** [comment]
Great! Closing this issue then.
