### ISSUE TITLE
Unable to connect to dynamodb through AWS Java sdk.

### ISSUE THREAD

**Issue by sambit-pani** [aws/aws-sdk-java#1947]
Getting hostname cannot be null while connecting to dynamoDB using Java sdk. 
Working fine through AWS CLI.

AmazonDynamoDB client2 = AmazonDynamoDBClientBuilder.standard()
			.withRegion(Regions.US_WEST_2).build();

**Comment by debora-ito** [comment]
@sambit-pani Can you share a code snippet for reproduction?

**Comment by debora-ito** [comment]
Also, what version of SDK are you using?

**Comment by debora-ito** [comment]
Closing due to lack of response, please re-open if you're still experiencing this issue.
