### ISSUE TITLE
Does ServerSideEncryption with customer supplied key support AES/GCM algorithm rather than AES-256?

### ISSUE THREAD

**Issue by WEBSHIVOM** [aws/aws-sdk-java#1949]
Hi, 
     As per current required usecase is there any support for AES/GCM for SSECustomerAlgorithm .Currently it's AES-256 SSECustomerAlgorithm which utilised by S3 while performing server side encyption .Please clarify my query .
Thanks.

**Comment by debora-ito** [comment]
Hi @WEBSHIVOM, AES/GCM is supported by the [S3 Encryption Client](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3EncryptionClient.html) when you configure it to use [CryptoMode.AuthenticatedEncryption](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/CryptoMode.html).

This blog post explain how the Client-Side Authenticated Encryption works:
https://aws.amazon.com/blogs/developer/amazon-s3-client-side-authenticated-encryption/ 

I believe the AES/GCM encryption is not supported by S3 in server-side encryption, as per their [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html).

Let us know if that helps.

**Comment by WEBSHIVOM** [comment]
Hi @debora-ito  ,
            I only have query regarding server side encryption  that Is there any possible way to support AES/GCM encryption standard ?Or it is an open feature request ? I have successfully used AES/GCM encryption standard in case of client side encryption.

**Comment by debora-ito** [comment]
I'd suggest you to post the feature request on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24), where you might get support from the S3 team.

Closing this, feel free to reopen if you have more questions.
