### ISSUE TITLE
s3 file operations SignatureDoesNotMatch on java 11 when key contains leading slash

### ISSUE THREAD

**Issue by olexandrkardash** [aws/aws-sdk-java#1950]
Hi. In our project, we had a simple file upload using aws-sdk-java.
After transferring to Java 11 we are getting 
```
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided
```
when key contains leading slash ("key" would work, "/key" wouldn't).
Same thing with reading files. Seems like the library just signs all requests with a key that contains leading slash incorrectly on 11th java.
This issue doesn't appear when running the same code on same aws sdk version on Java 8.
Version 1.11.401. Tried on current 1.11.525, same thing. 
Could you please check this?

**Comment by olexandrkardash** [comment]
I also tried using https://github.com/aws/aws-sdk-java-v2 sdk, which just truncates leading slash.
Is that some kind of new policy? 
Should we just avoid leading slashes and rename all existing objects?

**Comment by debora-ito** [comment]
Hi @olexandrkardash what version of `httpclient` are you using?

If it's `4.5.7` they introduced some changes in their URL rewriting, we are tracking the changes here: #1919. And we are still investigating the impact on the SDK.

Leading slashes are specifically mentioned here: https://issues.apache.org/jira/browse/HTTPCLIENT-1960

Could you try change the `httpclient` version to `4.5.5` and see if it fixes your issue?

**Comment by olexandrkardash** [comment]
@debora-ito, you are my savior! That actually worked! Turns out some of the new dependencies required for Java 11 were bringing httpclient 4.5.7. 
When I inforced 4.5.5, everything started working fine.
Again, thanks a lot, you saved me a lot of time:)

**Comment by debora-ito** [comment]
Glad we were able to help! Closing this, feel free to reopen if you have more questions.
