### ISSUE TITLE
Return DeletedObject(holds DeleteMarker) for AmazonS3Client.deleteObject()

### ISSUE THREAD

**Issue by roy3221** [aws/aws-sdk-java#1951]
Send a DeleteObject request to an object from versioning enabled bucket, it will create a delete marker, and this delete marker will have a version id.
If I use AWS Java SDK to make this request, I would not be able to get the Delete Maker's version id. AmazonS3Client.deleteObject() method returns nothing. While AmazonS3Client.deleteObjects() method will return a DeleteObjectsResult object will hold a list of DeletedObject. DeletedObject will have the delete marker.
Can we make changes to AmazonS3Client.deleteObject() to let it return DeletedObject as well? So we can get delete marker's version id?

**Comment by roy3221** [comment]
Send a DeleteObject request to an object from versioning enabled bucket, it will create a delete marker, and this delete marker will have a version id.
If I use AWS Java SDK to make this request, I would not be able to get the Delete Maker's version id. AmazonS3Client.deleteObject() method returns nothing. While AmazonS3Client.deleteObjects() method will return a DeleteObjectsResult object will hold a list of DeletedObject. DeletedObject will have the delete marker.
Can we make changes to AmazonS3Client.deleteObject() to let it return DeletedObject as well? So we can get delete marker's version id?

**Comment by debora-ito** [comment]
Hi @roy3221 thank you for opening this, I'm marking as a feature request.

**Comment by tan31989** [comment]
Hi @debora-ito,

Are you willing to accept a PR for this?
I was thinking of implementing and raising PR.

Regards,
Nagaraj
