### ISSUE TITLE
Incompatible with "org.apache.httpcomponents:httpclient:4.5.7"

### ISSUE THREAD

**Issue by Paramood** [aws/aws-sdk-java#1953]
Reproduced on 1.11.526
Please follow this issue for details https://github.com/aws/aws-sdk-java-v2/issues/1168

**Comment by debora-ito** [comment]
Hi @Paramood thank you for opening this issue. 

We are aware of the problem, and we are tracking in #1919, so I'll close this one. Feel free to reopen if you have more questions.
