### ISSUE TITLE
Cannot create enum from us-east-1a value

### ISSUE THREAD

**Issue by sansagara2** [aws/aws-sdk-java#1958]
So, we have this service that return the environment our codebase is running on, that uses Region.java.
It uses EC2 Metadata Java client to get the region on the machine this is running as.

We noticed that a call to `ec2metadata --availability-zone`returns `us-east-1a`. This output cannot be used to get the region from Region.java, as no enum exists for that one.

Are you planning to add support for these kind of (sub?)-regions, or should we cap the final letter from the environment? (us-east-1a -> us-east-1)

Thanks!

**Comment by sansagara** [comment]
Adding a comment here to keep me posted...

**Comment by debora-ito** [comment]
Hi @sansagara2, there are no plans to add availability zones to the Regions enum. 

Availability zones (like `us-east-1a` and `us-east-1b`) are a different concept than regions, and it would be confusing to mix them.

Closing this, please feel free to reopen if you have any more questions.
