### ISSUE TITLE
Use environment variables proxy settings 

### ISSUE THREAD

**Issue by benkropf** [aws/aws-sdk-java#1959]
Following up to #596, feel free to close this if this has already been implemented, but from what I can tell it has not.

ClientConfiguration should check common environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` if neither configured ClientConfiguration variables or Java system properties are set. Precedence would be configured values, then Java system properties, then environment variables.

I'd be happy to have this assigned to me as well if this is something we'd like implemented.

**Comment by webbhlin** [comment]
+1
I would like to see someone fixes this issue.

**Comment by debora-ito** [comment]
Hi @benkropf, this seems a reasonable ask, marking as a feature request. If you can send us a PR, we are happy to take a look.

**Comment by debora-ito** [comment]
Closed via #1967.
