### ISSUE TITLE
Add API support for "Use OpsWorks security groups" in OpsWorks CreateStackRequest

### ISSUE THREAD

**Issue by spasam** [aws/aws-sdk-java#196]
Add API support for "Use OpsWorks security groups" in OpsWorks CreateStackRequest.

http://docs.aws.amazon.com/opsworks/latest/userguide/workingstacks-creating.html

I don't see support for this in 1.7.2.

**Comment by hanshuo-aws** [comment]
Sorry for the silence here, but the API has been available in the SDK for a while.
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/opsworks/model/CreateStackRequest.html#setUseOpsworksSecurityGroups%28java.lang.Boolean%29
