### ISSUE TITLE
DynamoDb mapper cannot access get field 

### ISSUE THREAD

**Issue by PrzemyslawZajac88** [aws/aws-sdk-java#1963]
aws-sdk  version : 1.11.301

Error: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: could not invoke public java.lang.String

Note:
Class/Entity has package scope. This is mandatory for proper modularization and spaghetti code prevention. 

Can we have better reflection access. like Spring Data or hibernate (use private methods in private classes)

**Comment by PrzemyslawZajac88** [comment]
Class : https://github.com/PrzemyslawZajac88/subscription-services/blob/master/subscription-service/src/main/java/com/adidas/subscription/subscription/domain/Subscription.java

**Comment by debora-ito** [comment]
Hi @PrzemyslawZajac88 

Using reflection has some [drawbacks](https://docs.oracle.com/javase/tutorial/reflect/index.html), like performance overhead and security restrictions, and besides that, all illegal access operations will be denied in a future Java release (see http://openjdk.java.net/jeps/261#Relaxed-strong-encapsulation)

So for these reasons it’s not something we want to support.

**Comment by PrzemyslawZajac88** [comment]
Hi @debora-ito, Thank You for Your response. Well I'm stuck with the Java 8 and don't have Jigsaw which would resolve the problem of not exposing domains to the public (only dto). And with Java 8 I have hard time to do not expose Subscription entity (It is super easy with Spring Data JPA though). Is there a way to persist entity/aggregates to dynamo DB without exposing them?

**Comment by debora-ito** [comment]
You can use the DynamoDB low-level API, take a look at the "Working with DynamoDB" docs,  this one shows how to work with Items https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaDocumentAPIItemCRUD.html

Let us know if that helps.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have any other question.
