### ISSUE TITLE
Mapper ParallelScan ignores XRay Dummy Segment

### ISSUE THREAD

**Issue by paulmarkrussell** [aws/aws-sdk-java#1964]
When integration testing with junit, we setup an XRay dummy segment.

AWSXRay.beginDummySegment();

When we use the DynamoDBMapper to do a scanPage, it works.

However when we do a parallelScan it fails with the following error.

Caused by: com.amazonaws.xray.exceptions.SegmentNotFoundException: Failed to begin subsegment named 'AmazonDynamoDBv2': segment cannot be found

**Comment by debora-ito** [comment]
Hi @paulmarkrussell it looks like you are using the AWS X-Ray SDK for Java, which is maintained in another repository:  [aws/aws-xray-sdk-java](https://github.com/aws/aws-xray-sdk-java). Please open an issue over there and they will be able to help you out.

Feel free to reopen if you have further questions.
