### ISSUE TITLE
SDK support for Cost allocation tags

### ISSUE THREAD

**Issue by sumangithub123** [aws/aws-sdk-java#1970]
Hi All,

I wanted to get all active cost allocation tags.
I am using aws java sdk.
May i please know ,whether SDK support exists for the same or not ?

Thanks &Regards
Suman

**Comment by sumangithub123** [comment]
If no SDK support ,may i please know any Rest Api exposed by AWS to get the Cost Allocation tags?

**Comment by debora-ito** [comment]
Hi @sumangithub123 maybe [`AWSCostExplorerClient.getTags()`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/costexplorer/AWSCostExplorerClient.html#getTags-com.amazonaws.services.costexplorer.model.GetTagsRequest-) is what you're looking for? Check their API docs [here](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetTags.html).

**Comment by sumangithub123** [comment]
Hi @debora-ito ,
Thanks for your email..
I have checked that API.For the API 
1.We need to provide time interval as the input .And api  returns the tags ,which has usage in that period.if any active tag does not have the usage during that time interval, this api does not return that tag.

I am looking for an api which provides below info (similar to Aws console > services > billing >cost allocation tags UI)
tag key : tag value :tag status (active/inactive)

**Comment by debora-ito** [comment]
I believe there's no API for listing the cost allocation tags. The "Using Cost Allocation Tags" [documentation](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/aws-tags.html) says at some point: 

> The AWS generated tags is available only in the Billing and Cost Management console and reports, and doesn't appear anywhere else in the AWS console, including the AWS Tag Editor

So I think the tags info are pretty restricted to the console. I'd suggest requesting the feature on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=218) and get support from the service team.

Closing this for now, please feel free to reopen if you have more questions.

**Comment by wangyuhere** [comment]
SDK support for cost allocation tag is released on 2022-06-07
See https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#112235-2022-06-07
