### ISSUE TITLE
Calculate wrong object key value in TransferManager in uploadFileList method

### ISSUE THREAD

**Issue by nvzterclk** [aws/aws-sdk-java#1971]
While using uploadFileList method for upload files as a list, I have recognized object's key was changed. After reviewing the code I noticed that the error was in the following code block (line 1814).

` String key = f.getAbsolutePath()
                            .substring(startingPosition)
                            .replaceAll("\\\\", "/");`

This error caused by calculating of startingPosition. 
`int startingPosition = directory.getAbsolutePath().length();
 if (!(directory.getAbsolutePath().endsWith(File.separator)))
                startingPosition++;`

As a result of the calculation here, the key starts from the wrong place.

For example my object's name is blabla.txt , but according to above calculation result give me object key result => abla.txt.

**Comment by debora-ito** [comment]
Hi @nvzterclk could you share a sample code with the key names you're having problem with, so I can try to reproduce your issue?

**Comment by nvzterclk** [comment]
hi @debora-ito 

sorry for opening this issue. It was my fault, and when I debugged the code, I found out where I made a mistake. I used the wrong token about the file.
`
