### ISSUE TITLE
Last downloaded file resume upon Exception

### ISSUE THREAD

**Issue by studioam** [aws/aws-sdk-java#1974]
Hi there:, I'm using Java SDK 1.11.534

in my tool I declared a download named 'down' using transfermanager,

since the call:

   `down.waitForCompletion();`

is a blocking call and stops the progressbar acknowledgement by progresslistener I had to introduce a Swingworker as follows:

       ` SwingWorker worker = new SwingWorker<Void,Integer>(){
                

                @Override
                protected void process(List<Integer> chunks) {
                    int j = chunks.get(chunks.size()-1);
                    
                    if (i<=fileNum) jLabel4.setText("Scaricamento file " + i+ " di " + fileNum + "  del DCP "+ DCPname+" in corso, attendere....");
                    else jLabel4.setText("Scaricamento DCP "+ DCPname+" completato con successo.");
                
                }
                
                @Override
                protected Void doInBackground(){
                   
                    for (S3ObjectSummary file: fileList){
                          if((!isPresent(destination,file.getKey().substring(file.getKey().lastIndexOf("/") + 1),file.getSize())) && (!(file.getKey().substring(0, file.getKey().length()-1).equals(DCPname)))){
                          
                              publish(i);
                     
                     
                     
                     GetObjectRequest getObjectRequest = new GetObjectRequest(bucketName, file.getKey());
                     
                     
                     
                     down = tx.download(getObjectRequest,new File(percorso+File.separator + file.getKey().substring(file.getKey().lastIndexOf("/") + 1)));
                                         
                     down.addProgressListener(progressListener);

                    
                     try {
                         down.waitForCompletion();
                     } catch (AmazonClientException ex) {
                    
                         ex.printStackTrace();
                         tx.shutdownNow(true);
                         //jButton4.setEnabled(true);
                         jButton4.doClick();

                     } catch (InterruptedException ex) {
                         
                         ex.printStackTrace();
                         tx.shutdownNow(true);
                         //jButton4.setEnabled(true);
                         jButton4.doClick();

                     }
                        
                   
                  i++;  
                 }`

this is a portion of the code where  'doInBackground()' shows the operations to do.

It happens sometimes to have  an AmazonClientException  reporting 'not all bytes from S3inputstream were read' and this leads to have a corrupted file and a stop of the program itself upon exception.

at the beginning of my code (not reported here) before reaching the swingworker declaration, I stated that when the jButton4 is clicked the action starts checking if there's a size mismatch between files in the download folder and the ones on amazon s3 and if there's a truncated file it gets deleted and the name is added to the download list again. 

So the only solution I've found so far is to add the 

      'jButton4.doClick();'

line in the exception code, meaning when an exception is hit the prog restarts and checks for truncated files and restarts downloads adding such a file too.

My question is:  is there any way in the SDK to resume or better cancel and then download file again upon exception without restarting the program? I find the usage of:

       'jButton4.doClick();'

is not a professional way of coding.
Thanks in advance

**Comment by debora-ito** [comment]
> My question is: is there any way in the SDK to resume or better cancel and then download file again upon exception without restarting the program? 

Take a look at this AWS blog post showing how to pause and resume transfers using TransferManager: https://aws.amazon.com/blogs/developer/pausing-and-resuming-transfers-using-transfer-manager/

Let us know if that's what you're looking for.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.
