### ISSUE TITLE
ListBucket error when run hadoop terasort over s3 endpoint

### ISSUE THREAD

**Issue by wuxg** [aws/aws-sdk-java#1979]
Hi
I have deployed a hadoop cluster over ceph radosgw. After running teragen task, there are a lot of objects whose Etags are suffixed with "0x0e". These suffix cause error when running terasort benchmark, any suggestion is appreciated.

listbucketresult and terasort complaining output is following:
--------listbucketresult----------
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>hadoop</Name><Prefix>input3/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><EncodingType>url</EncodingType><Contents><Key>input3%2Fpart-m-00099</Key><LastModified>2019-04-25T06:26:23.597Z</LastModified><ETag>&quot;24e1fb422d2a3f322431ab7467461d44&#x0e;&quot;</ETag><Size>100000000</Size><StorageClass>STANDARD</StorageClass><Owner><ID>wuxg</ID><DisplayName>wuxg created for hadoop fs</DisplayName></Owner></Contents><Contents>more contents ignored</Contents></ListBucketResult>
--------terasort complaining output----------
root@bl6 hadoop]# hadoop jar /home/wuxg/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-*example*.jar terasort -Dmapred.map.tasks=100 s3a://hadoop/input3 s3a://hadoop/output
19/04/25 14:34:24 INFO terasort.TeraSort: starting
19/04/25 14:34:25 INFO Configuration.deprecation: fs.s3a.server-side-encryption-key is deprecated. Instead, use fs.s3a.server-side-encryption.key
19/04/25 14:34:25 ERROR terasort.TeraSort: listLocatedStatus on s3a://hadoop/input3: com.amazonaws.SdkClientException: Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$ListBucketHandler: Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$ListBucketHandler

**Comment by wuxg** [comment]
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>hadoop</Name><Prefix>input3/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><EncodingType>url</EncodingType><Contents><Key>input3%2Fpart-m-00099</Key><LastModified>2019-04-25T06:26:23.597Z</LastModified><ETag>&quot;24e1fb422d2a3f322431ab7467461d44&#x0e;&quot;</ETag><Size>100000000</Size><StorageClass>STANDARD</StorageClass><Owner><ID>wuxg</ID><DisplayName>wuxg created for hadoop fs</DisplayName></Owner></Contents><Contents>more contents ignored</Contents></ListBucketResult>

**Comment by wuxg** [comment]
"<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>hadoop</Name><Prefix>input3/</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><EncodingType>url</EncodingType><Contents><Key>input3%2Fpart-m-00099</Key><LastModified>2019-04-25T06:26:23.597Z</LastModified><ETag>&quot;24e1fb422d2a3f322431ab7467461d44&#x0e;&quot;</ETag><Size>100000000</Size><StorageClass>STANDARD</StorageClass><Owner><ID>wuxg</ID><DisplayName>wuxg created for hadoop fs</DisplayName></Owner></Contents><Contents>more contents ignored</Contents></ListBucketResult>"

**Comment by wuxg** [comment]
<ETag>&quot;24e1fb422d2a3f322431ab7467461d44&#x0e;&quot;</ETag>

**Comment by debora-ito** [comment]
@wuxg We don't really have the expertise to help out with Teragen or Terasort here. This repository is specifically for issues for the AWS SDK for Java. I'd suggest asking your question on StackOverflow.

**Comment by wuxg** [comment]
Got it, thank you!
