### ISSUE TITLE
Add Hong Kong region to Regions enum

### ISSUE THREAD

**Issue by daveagill** [aws/aws-sdk-java#1982]
The newly announced Asia Pacific (Hong Kong) ap-east-1 region should be added the Regions enum:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java

**Comment by kranthikumar24** [comment]
Supporting the same issue.

**Comment by debora-ito** [comment]
This is in our backlog, we'll update here when we release it.

**Comment by debora-ito** [comment]
Added in `1.11.545`. Closing.
