### ISSUE TITLE
Getting "The specified queue does not exist for this wsdl version" on AmazonSQS.getQueueName

### ISSUE THREAD

**Issue by lcfarrington92** [aws/aws-sdk-java#1985]
I get the message "The specified queue does not exist for this wsdl version." from AmaonSQS.getQueueUrl for a valid queue,credential and region The queue IS present and when I make the get-queue-url call via AWS CLI using the same credentials, region and queue name, I DO get the queue back. Using latest version of 1.11. Any recommendations on how to fix this?

**Comment by debora-ito** [comment]
Hi @lcfarrington92, this error usually means the specified queue does not exist on the specified region, it may be due to an incorrect queue name or client configuration.

Could you share a code snippet showing how you're creating the SQS client?

**Comment by lcfarrington92** [comment]
I don't believe the region is the problem as I called this with same region via CLI and I get the arn back, so maybe a config issue?  Here's a code snippet.  Not sure how much to include, let me know if you need to see more than I have here:
 AmazonSQS sqs = AmazonSQSClientBuilder.standard()
            .withRegion(region)
            .withCredentials(credentialsProvider)
            .withClientConfiguration(new ClientConfiguration()
                    .withMaxConnections(10))
            .build();

**Comment by debora-ito** [comment]
The client seems good. If you turn [wire logging](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) on, you can get additional information about the request, and you can check if the region and queue name are correct.

If you choose to provide us the logs, please make sure there is no sensitive data.

**Comment by lcfarrington92** [comment]
It looks like it is the wrong region(eu-west-2 instead of us-west-2) but unsure as to why.  Here's a snippet from the log:
05-01 09:38:27 DEBUG o.a.h.wire - http-outgoing-1 >> "POST / HTTP/1.1[\r][\n]"
05-01 09:38:27 DEBUG o.a.h.wire - http-outgoing-1 >> "Host: sqs.**eu-west-1.**amazonaws.com[\r][\n]"
However, in the debugger, if I put a breakpoint on .withRegion, I can see that it is correctly set to us-west2.
 AmazonSQS sqs = AmazonSQSClientBuilder.standard()
            .withRegion(region)
            .withCredentials(credentialsProvider)
            .withClientConfiguration(new ClientConfiguration()
                    .withMaxConnections(10))
            .build();
String queueUrl = sqs.getQueueUrl(queueName).getQueueUrl();

**Comment by debora-ito** [comment]
It seems like the `eu-west-1` region is being set somewhere in your environment. Check this AWS Selection guide, it might help you figure out where: 
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html

I'll  go ahead and close this since it doesn't look like an issue with the SDK itself. Please feel free to reopen if you have further questions.

**Comment by RenegadeMaster** [comment]
I think this issue should be re-opened. It exists across SDK's. The fact that the region needs to be specified when the region is in the URL is a failing of the SDK and in addition the error message is not helpful

**Comment by ndtreviv** [comment]
In my case I am specifying the region, and I still get this - but not all the time. I get it periodically. It rears its ugly head, and then disappears again without any changes at all occurring on my side at all. This smells of an AWS issue.

**Comment by j256** [comment]
Yeah I'm definitively specifying the correct region but I'm seeing a `receiveMessage()` command on a recently created queue fail.  This feels like all of the AWS SQS frontends haven't been updated with a new queue.  I put a wait loop in to list the queues immediately after creation and it takes a number of seconds for them to show up in the list.  Fine.  But then even after the list shows the queue, a subsequent `sqsClient.receiveMessage(...)` command fails with a:

    The specified queue does not exist for this wsdl version. (Service: Sqs, Status Code: 400, Request ID: 16dbf5aa-0322-58fc-a631-ad84576689ea, Extended Request ID: null)

**Comment by rasensio** [comment]
> Hi @lcfarrington92, this error usually means the specified queue does not exist on the specified region, it may be due to an incorrect queue name or client configuration.
> 
> Could you share a code snippet showing how you're creating the SQS client?

Exactly what happened to me. I was referencing another region.

**Comment by ndtreviv** [comment]
> In my case I am specifying the region, and I still get this - but not all the time. I get it periodically. It rears its ugly head, and then disappears again without any changes at all occurring on my side at all. This smells of an AWS issue.

After many weeks of trying to figure this out, it's not an AWS issue at all for me. Instead it was a Google AppEngine issue. My app, deployed to Google AppEngine, was getting queue config details from Datastore. It seems that when a new instance spins up due to a scale-out it doesn't have immediate access to Datastore. Resolved it with a simple catch - retry.
