### ISSUE TITLE
`ConsumedCapacity` doesn't return read and write capacity units, only the total

### ISSUE THREAD

**Issue by mbaranczak** [aws/aws-sdk-java#1986]
I implemented a `RequestMetricCollector` in order to track how many capacity units my application is using. I receive a `ConsumedCapacity` object, and calling `getCapacityUnits()` on the object gives me the expected value, but `getWriteCapacityUnits()` and `getReadCapacityUnits()` always return null. Which makes no sense - if there's a value for the total, then it must have used either read or write units.

```
private RequestMetricCollector metricCollector = new RequestMetricCollector() {
	@Override
	public boolean isEnabled() {
		return true;
	}
		
	@Override
	public void collectMetrics(Request<?> rqst, Response<?> rspns) {
		Object o = rspns.getAwsResponse();
		
		if (o instanceof PutItemResult) {
			logConsumedCapacity( "put", ((PutItemResult)o).getConsumedCapacity() );
		} else if (o instanceof DeleteItemResult) {
			logConsumedCapacity( "delete", ((DeleteItemResult)o).getConsumedCapacity() );
		} else if (o instanceof QueryResult) {
			logConsumedCapacity( "query", ((QueryResult)o).getConsumedCapacity());
		} else if (o instanceof GetItemResult) {
			logConsumedCapacity( "get", ((GetItemResult)o).getConsumedCapacity());
		} else {
			log.warn("unknown response type for metricCollector: "+o.getClass());
		}
	}
};

private void logConsumedCapacity(String operation, ConsumedCapacity cc) {
	// ...
	Double cap = cc.getCapacityUnits(); // non-null and positive
	Double capRead = cc.getReadCapacityUnits(); // always null
	Double capWrite = cc.getWriteCapacityUnits(); // always null
	// ...
}

```

library version: 1.11.512

**Comment by mbaranczak** [comment]
Sorry, I forgot to mention - this is the DynamoDB component.

**Comment by debora-ito** [comment]
Hi @mbaranczak, I'll contact the DynamoDB team internally and ask about this behavior. Will update here when they respond.

**Comment by linrongbin** [comment]
Same problem for python version.

**Comment by debora-ito** [comment]
Yes, this looks like a service-side issue, I've opened an internal ticket to the DynamoDB team.

**Comment by mbaranczak** [comment]
If the Python library is doing it too, then maybe the problem is with the server not sending the data in the first place?

**Comment by debora-ito** [comment]
@mbaranczak @linrongbin 

The DynamoDB team replied, saying getWriteCapacityUnits() and getReadCapacityUnits() will return value only for Transaction APIs (like TransactGetItems and TransactWriteItems) currently. They are working on populating the write and read capacity fields in the other APIs.

I told them there's no documentation that supports this restriction, so I asked to update the documentation in the meantime.

I'll close this for now, as it's not an issue with the SDKs, but I will update here if there are any changes.
