### ISSUE TITLE
SNS returns faulty error message when sending application platform notification

### ISSUE THREAD

**Issue by tomdevroomen** [aws/aws-sdk-java#1991]
When publishing a message to an application platform endpoint the message must contain the fields `default` AND `GCM` (or platform specific, not tried).

From the example code and code it seems only `GCM` would be enough.

Sending this message in the PublishRequest 
`{"gcm":  
    {"notification":  
        {"title":"This is the title",  
         "body":"This is the body"  
         }  
    }  
}`
would result in the following exception
`com.amazonaws.services.sns.model.InvalidParameterException: Invalid parameter: JSON must contain an entry for 'default' or 'GCM'. (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: xxx-xx-xx-xx)`

The exception clearly says `'default' or 'GCM'`, while both are required as message:
`{"gcm":{"notification":{"title":"This is the title","body":"This is the body"}},"default":"This is the body"}` works.

**Comment by debora-ito** [comment]
Could you try using `"GCM"` instead of `"gcm"`?

**Comment by tomdevroomen** [comment]
OKay, I _really_ thought I've tried that and got the same error, but you're right `"GCM"` works as expected.

**Comment by tomdevroomen** [comment]
Just tried to use `"GCM"`, but no luck.

`{"GCM":{"notification":{"title":"something","body":"Hello, this is a test push notification to check if everything is working as desired","otherParam":"Test"}}}`

That's the message I'm sending, but still got `com.amazonaws.services.sns.model.InvalidParameterException: Invalid parameter: JSON must contain an entry for 'default' or 'GCM'. (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: 10bb40ef-c23a-5d0e-9f98-15b3af413bd7)`

**Comment by debora-ito** [comment]
@tomdevroomen since you opened #1999 does it mean you got this one working?

**Comment by tomdevroomen** [comment]
Yes, I've got it working

**Comment by tomdevroomen** [comment]
> @tomdevroomen How were you able to make it work? I am getting the same error.

That was a long time ago, but I think the content of GCM needs to be escaped JSON.
So, you'll end up with JSON in JSON.

**Comment by Carlito-T101** [comment]
stringify the GCM json.

**Comment by chaau** [comment]
Whoever finds this problem: here is the correct way of sending Platform Specific messages:

```          const publishCommandInput = {
            TargetArn: createResponse.EndpointArn,
            Message: JSON.stringify({
              GCM: JSON.stringify({
                notification: {
                  title: "Hi",
                  body: "You have a new message",
                },
              }),
            }),
            MessageStructure: 'json',
          };
          const publishCommand = new PublishCommand(publishCommandInput);
          const publishResponse = await client.send(publishCommand);

```
You need to use JSON.stringify to stringify the inner notification for GCM or APNS and then you need to use JSON.stringify again to stringify the whole message. In addition to that you need to pass this parameter: MessageStructure: 'json'

I wish AWS made it simpler.

Reference: https://docs.aws.amazon.com/sns/latest/dg/sns-send-custom-platform-specific-payloads-mobile-devices.html
