### ISSUE TITLE
DynamoDBMapper: Versioned attributes not supported with transactions

### ISSUE THREAD

**Issue by mushketyk** [aws/aws-sdk-java#1992]
When a `TransactionWriteRequest` contains an operation that updates an object with a field with the`@DynamoDBVersionAttribute` annotation `DynamoDBMapper` throws the following exception:

```
com.amazonaws.SdkClientException: Versioned attributes are not supported on TransactionWrite API
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.generateTransactWriteItem(DynamoDBMapper.java:2449)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.transactionWrite(DynamoDBMapper.java:1116)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.transactionWrite(AbstractDynamoDBMapper.java:163)
```

Which is thrown because of the following check:

```java
if (field.versioned()) {
  throw new SdkClientException("Versioned attributes are not supported on TransactionWrite API");
} 
```

What is the reason behind this check?
Is this temporary and support for versioned fields will be added later or versioned fields are fundamentally incompatible with DynamoDB transactions?

**Comment by debora-ito** [comment]
Hi @mushketyk, it's the latter option, versioned fields are not supported by DynamoDBMapper transactional operations, as mentioned in the Optimistic Locking With Version Number [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html).

**Comment by kapilsingh5050** [comment]
This is not a fundamental limitation. It wasn't straight-forward to make versioning work with string condition expressions, so that work was punted for later. Options are currently being evaluated to support versioning in transactionWrite API.

**Comment by kapilsingh5050** [comment]
@mushketyk could you give a little more context on your use-case? Do you specify any conditions on the objects with a field with the `@DynamoDBVersionAttribute` annotation?

**Comment by mushketyk** [comment]
@kapilsingh5050 I am not running this in production, I am just exploring this new feature to see how it works.

> Do you specify any conditions on the objects with a field with the @DynamoDBVersionAttribute annotation?

I don't specify any conditions. It seems that the exception is thrown for any update operation that updates a table for a class with the `@DynamoDBVersionAttibute` attribute. So this seems like a significant limitation

> Options are currently being evaluated to support versioning in transactionWrite API.

Would it make sense to automatically add an update operation to increment a version field and expect a user to add a condition expression to check a version field if this is needed?
Or alternatively, would it make sense to just expect a user to add updates/checks for a version field?

**Comment by dcsena** [comment]
Any update on this?

**Comment by celluj34** [comment]
Also interested. Having both multi-document and multi-table transactions with optimistic locking is extremely important for data integrity.

**Comment by zzx88991** [comment]
> Also interested. Having both multi-document and multi-table transactions with optimistic locking is extremely important for data integrity.

+1

**Comment by vnpandey** [comment]
@DynamoDBVersionAttribute is supported in transaction API calls now. Check https://aws.amazon.com/about-aws/whats-new/2019/10/dynamodbmapper-now-supports-optimistic-locking-for-amazon-dynamodb-transactional-api-calls/

**Comment by oleksandr-bulakaiev-rft** [comment]
Hello guys. Could you please advise if this has also been implemented in .NET SDK?

**Comment by debora-ito** [comment]
@oleksandr-bulakaiev-rft the folks of the .NET SDK team should be able to answer that in the .NET SDK repo: https://github.com/aws/aws-sdk-net

**Comment by weibian-wyze** [comment]
versioned attribute now is supported in ddb transaction operations in aws.java.sdk 1.12.300 . 
it is tested in my side.
