### ISSUE TITLE
Route53 can‘t update DNS with changeResourceRecordSets

### ISSUE THREAD

**Issue by mjesse88** [aws/aws-sdk-java#1996]
I  wan to use changeResourceRecordSets to update DNS msg from A type to CNAME. but it throw
RRSet of type CNAME with DNS name xxx.xx.com. is not permitted as it conflicts with other records with the same DNS name in zone xx.com.
![image](https://user-images.githubusercontent.com/19406155/57919377-4b633d80-78cb-11e9-97c9-5dcf1a617c21.png)
![image](https://user-images.githubusercontent.com/19406155/57919419-5f0ea400-78cb-11e9-9ab3-40894b495e8b.png)

update the DNS, it must exist on xx.com, but it throw a exception.

**Comment by debora-ito** [comment]
Hi @mjesse88, 

from the Supported DNS record types [documentation](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CNAMEFormat), under CNAME type:

> CNAME Record Type
A CNAME Value element is the same format as a domain name.
> 
> **Important**
> The DNS protocol does not allow you to create a CNAME record for the top node of a DNS namespace, also known as the zone apex. For example, if you register the DNS name example.com, the zone apex is example.com. You cannot create a CNAME record for example.com, but you can create CNAME records for www.example.com, newproduct.example.com, and so on.
> 
> In addition, if you create a CNAME record for a subdomain, you cannot create any other records for that subdomain. For example, if you create a CNAME for www.example.com, you cannot create any other records for which the value of the Name field is www.example.com.
> 
> Amazon Route 53 also supports alias records, which allow you to route queries to AWS resources such as CloudFront distributions and Amazon S3 buckets. Aliases are similar in some ways to the CNAME record type; however, you can create an alias for the zone apex. For more information, see Choosing Between Alias and Non-Alias Records.

Do you think it might be the case where you have other CNAME records for the same DNS name?

**Comment by debora-ito** [comment]
Closing due to lack of response, please reopen if you're still experiencing this issue.
