### ISSUE TITLE
Documentation for sending platform application messages is unclear

### ISSUE THREAD

**Issue by tomdevroomen** [aws/aws-sdk-java#1999]
The documentation about sending messages for platform application is unclear.
https://docs.aws.amazon.com/sns/latest/dg/mobile-push-send-custommessage.html

Here the docs say you only have to escape the platform specific payload when using the console. This seems not to be the case.
After many tries with different formats the only way it works is when the payload is escaped.

Working example:
`{"GCM":"{\"data\":{\"body\":\"Hello, this is a test push notification to check if everything is working as desired\",\"definitionName\":\"Test\"}}","default":"Hello, this is a test push notification to check if everything is working as desired"}`

Not working example:
`{"GCM":"{"data":{"body":"Hello, this is a test push notification to check if everything is working as desired","definitionName":"Test"}}","default":"Hello, this is a test push notification to check if everything is working as desired"}`

**Comment by debora-ito** [comment]
Hi @tomdevroomen just to be clear, your ask is for the documentation to mention not only the SNS console but also the APIs?

**Comment by tomdevroomen** [comment]
Well, the docs give an example with plain JSON, the other 2 examples tell you for the console you need to escape part of the JSON.
This has confused me, as when using the SDK the JSON needs to be escaped too, not only for the console.

**Comment by debora-ito** [comment]
Got it, I'll ask the Documentation Team to make the docs more clear on that section.

Thank for the feedback. I'll go ahed and close this, but feel free to reach out if you have any other question.

**Comment by mig281** [comment]
Thank you, @tomdevroomen and @debora-ito. I'll implement the changes now.
