### ISSUE TITLE
Not able to find efficient way to migrate data from Azure CosmosDB (DocumentDB)

### ISSUE THREAD

**Issue by adwaitpatankar** [aws/aws-sdk-java#2000]
Not able to find efficient way to migrate data from Azure CosmosDB (DocumentDB). Can we use AWS DMS to configure Azure CosmosDB (MongoDB type) as source endpoint?

**Comment by debora-ito** [comment]
Hi @adwaitpatankar I contacted the AWS DMS team and they confirmed Azure CosmosDB is not supported currently. I opened a feature request for them to add support for CosmosDB.

If you have further questions about services like AWS DMS, I'd suggest posting it to the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=216) where you can get replies directly from the service team. This github repo is intended for specific questions about the use of AWS SDK for Java.
