### ISSUE TITLE
Add support for Elasticsearch 5-series instance types

### ISSUE THREAD

**Issue by rodrigo-fleischmann-gmail-com** [aws/aws-sdk-java#2001]
Hello,

AWS released new 5-series instance types for Elasticsearch (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html), can you support it in AWS sdk java?

With current release I am getting an "java.lang.IllegalArgumentException: Cannot create enum from m5.large.elasticsearch value! at com.amazonaws.services.elasticsearch.model.ESPartitionInstanceType.fromValue(ESPartitionInstanceType.java:96)".

If it helps to provide the patch, let me know.

Thanks,
Rodrigo Fleischmann

**Comment by debora-ito** [comment]
Hi @rodrigo-fleischmann-gmail-com, thank you for reporting this. The `ESPartitionInstanceType` enum is auto-generated from internal models so we can't accept code contributions without them being overwritten later on. 

I'll forward your request to the Elasticsearch Service team and will update here when they respond.

**Comment by rodrigo-fleischmann-gmail-com** [comment]
Hi @debora-ito , thanks for the update, hope we get an update soon from ElasticSearch Service team as we save dollars by using the 5-series instance type :-)

**Comment by millems** [comment]
@rodrigo-fleischmann-gmail-com there is a string-based setter so that you don't have to wait to get this instance type!

**Comment by debora-ito** [comment]
@rodrigo-fleischmann-gmail-com 
So I got a reply from the Elasticsearch team saying they have this task in their backlog, it's pending prioritization.

I'll go ahead and close this, since there's no issue with the SDK, but feel free to reopen if you have more questions.
