### ISSUE TITLE
Add "Clone EMR Cluster" to the API

### ISSUE THREAD

**Issue by sansagara** [aws/aws-sdk-java#2002]
There is currently no easy way to clone an existing EMR cluster configuration (Steps, Settings, Configs) using the SDK/API. 
The only way this is possible, is by creating a new jobflow and building the required parameters using settings obtained using `describeCluster()` on the source cluster.

You already provide a way to easily clone a cluster using the console:
![image](https://user-images.githubusercontent.com/1382235/58271287-5ac20b00-7d51-11e9-959f-20bc3d124bed.png)

I think it's fair to have such a helper method, where one can only pass the source cluster id, and it will create a new one using the same settings. eg: `cloneCluster(string: cluster-id)`

This will really help devops efforts when trying to recover from TERMINATED and TERMINATED_WITH_ERRORS cluster states.

**Comment by debora-ito** [comment]
Hi @sansagara I'll open an internal ticket to the EMR team requesting a clone cluster API. I suggest you also post your request on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=52), to get the EMR team support directly.

I'll close this for now, but will update when we hear back from the EMR team.

**Comment by pchychi-blox** [comment]
any updates on this? thanks
