### ISSUE TITLE
DynamoDBMapper: transactionWrite strips attributes added by the AttributeTransformer

### ISSUE THREAD

**Issue by aecollver** [aws/aws-sdk-java#2004]
This code iterates over model properties to classify them as key/non-key/null:
https://github.com/aws/aws-sdk-java/blob/439ea39371d94553d6c963075c0a4378651998f7/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.java#L2544

Attributes added by the AttributeTransformer (not present in the model) are effectively stripped.

Concrete example: The attributes added by the Client-side Encryption for Amazon DynamoDB (https://github.com/aws/aws-dynamodb-encryption-java) are stripped by transactionWrite and the stored items are unreadable (the signature check fails on read).

**Comment by debora-ito** [comment]
Fixed in version `1.11.742`. Thank you for reaching out.
