### ISSUE TITLE
Cognito adminSetUserPassword giving UserNotFoundException

### ISSUE THREAD

**Issue by krishna-sankar-capillary** [aws/aws-sdk-java#2005]
Hi,

I was trying to change the password of a user by calling adminSetUserPassword function along with username, poolId and new password. The password is getting changed but I am receiving UserNotFoundException. Am I missing some thing here or is there any bug at SDK end? Following is the log and the code snippet.

`AdminSetUserPasswordRequest request1 = new AdminSetUserPasswordRequest()
                .withUserPoolId(poolId)
                .withUsername(userName)
                .withPassword(password);
        AdminSetUserPasswordResult changePasswordResult = client.adminSetUserPassword(request1);`

`Exception in thread "main" com.amazonaws.services.cognitoidp.model.UserNotFoundException: User does not exist. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: d7bbab7a-812e-11e9-acdc-db1d671f68ff)`

I am using version 1.11.550 of aws-java-sdk-cognitoidp

**Comment by debora-ito** [comment]
Hi @krishna-sankar-capillary, here are some questions to help us identify the cause: 

1. Are you using a username or an alias in the `userName` value?
2. With a single `adminSetUserPassword` API call you are seeing the `UserNotFoundException` but the password is being changed correctly?

**Comment by krishna-sankar-capillary** [comment]
1. I am not using alias and using username directly.
2. Yes, with a single call, password is being changed but getting UserNotFoundException.

**Comment by krishna-sankar-capillary** [comment]
Pardon, I am using email in the `userName` field. And I have enabled email attribute to be used for login while creating the pool(made it an alias).

**Comment by debora-ito** [comment]
Could you try using the `username` instead of the email and see if you still get the error message? 

In any case, the behavior you are seeing in question `2` is odd, I'll contact the Cognito service team and see if it's expected.

**Comment by debora-ito** [comment]
The Cognito team responded saying they are aware of the problem, and they are working on the fix. I'll update here when the fix is up.

**Comment by debora-ito** [comment]
@krishna-sankar-capillary The fix on service side is up, can you confirm if you're still seeing the issue?

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you're still experiencing this issue.
