### ISSUE TITLE
S3Object is not closed properly

### ISSUE THREAD

**Issue by musketyr** [aws/aws-sdk-java#2007]
Not closing `S3Object`  properly may lead to worker exhaustion in the HTTP client.

Following method is not closing the `S3Object` properly:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1548-L1571

There might be similar methods which also doesn't close the instances properly in this class and sibling classes (async, encrypted)

**Comment by debora-ito** [comment]
Hi @musketyr, to release the connection resources you need to call `S3Object.close` after you processed the input stream returned by `AmazonS3Client.getObject`. 

Check this example:

```java 
    S3Object fullObject = null;
    try {
        AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                .withRegion(clientRegion)
                .withCredentials(new ProfileCredentialsProvider())
                .build();

        // Get an object.
        System.out.println("Downloading an object");
        fullObject = s3Client.getObject(new GetObjectRequest(bucketName, key));

        // Read the text input stream one line at a time and display each line.
        BufferedReader reader = new BufferedReader(new InputStreamReader(fullObject.getObjectContent()));
        String line = null;
        while ((line = reader.readLine()) != null) {
            System.out.println(line);
        }
        System.out.println();
    }
    catch(AmazonServiceException e) {
        e.printStackTrace();
    }
    catch(SdkClientException e) {
        e.printStackTrace();
    }
    finally {
        // To ensure that the network connection doesn't remain open, 
        // close any open input streams.
        if(fullObject != null) {
            fullObject.close();
        }
    }
```

For a full code example and `AmazonS3Client.getObject()` usage variations, please check the docs: https://docs.aws.amazon.com/AmazonS3/latest/dev/RetrievingObjectUsingJava.html

Closing this for now, feel free to reopen if you have any other questions.

**Comment by musketyr** [comment]
@debora-ito I'm sorry but I think there is an misunderstanding here. The code is located inside your library. The `S3Object` is only available inside the method call so there is no way how can I close the instance from within my code. Or are you suggesting to send you an PR?

**Comment by debora-ito** [comment]
Yes @musketyr it was my mistake, I didn't realize it was the `getObject()` method that returns the object metadata. Reopening this and marking as a bug.

**Comment by dagnir** [comment]
After taking a closer look, this doesn't look like a bug to me. [`retryableDownloadS3ObjectToFile`]() bubbles down to call to `ServiceUtils#downloadToFile` which closes the object in a `finally` block:

https://github.com/aws/aws-sdk-java/blob/03eed5efc7cebc1e107f807c496b8c87512bb3ba/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L283-L319

Going to go ahead and close this. Please feel free to reopen if you have further questions/concerns.
