### ISSUE TITLE
Compilation error when trying to specify S3 key for S3Location object

### ISSUE THREAD

**Issue by ks9999** [aws/aws-sdk-java#2011]
I reduced my code to the following test example where I want to specify the S3 key but I am not able to.

package com.test.example;

import com.amazonaws.services.s3.model.S3Location;

public class TestExample
{
    public static void main(String[] args) throws InterruptedException
    {

        String s3_bucket = "eb-mybucket";
        String s3_key = "nodejs.zip";
        //S3Location loc = new S3Location().withBucketName(s3_bucket).withKey(s3_key);   // Problem in withKey       
        S3Location loc2 = new S3Location().withBucketName(s3_bucket).withKey(s3_key);           
    }
}

I have tried this with aws-sdk-1.11.543 and I have tried other versions going back such as aws-sdk-1.11.502. 

The compilation error is with the method withKey(). Looking the AWS documention, I do not see a way of specifying the key. See https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/S3Location.html.

I tried using:

String loc = new S3Location(s3_bucket, s3_key) 

But the constructor now does not take any arguments.

What version of the AWS-SDK can I use to get this to work. The example in the API documentation which uses withS3Bucket() and withS3Key() also does not work and produces compile errors for these method names:

AWSElasticBeanstalk client = AWSElasticBeanstalkClientBuilder.standard().build();
CreateApplicationVersionRequest request = new CreateApplicationVersionRequest().withApplicationName("my-app").withVersionLabel("v1")
        .withDescription("my-app-v1").withSourceBundle(new S3Location().withS3Bucket("my-bucket").withS3Key("sample.war"))
        .withAutoCreateApplication(true).withProcess(true);
CreateApplicationVersionResult response = client.createApplicationVersion(request);

I am using Maven 3.6.1 on Windows 10 and my pom.xml is 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test.example</groupId>
    <artifactId>test-example</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>test-example</name>
    <url>http://aws.amazon.com/sdkforjava</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.543</version> 
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>${env.HOME}/.aws/</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>com.test.example.TestExample</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by dagnir** [comment]
Hi @ks9999, sorry it's a little confusing but multiple services actually define an `S3Location` object, and they aren't interchangeable. It looks like the one you want is the Elastic Beanstalk one, [`com.amazonaws.services.elasticbeanstalk.model.S3Location`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticbeanstalk/model/S3Location.html).

**Comment by dagnir** [comment]
Going to go ahead and close this. Please feel free to reopen if you have further concerns or questions.
