### ISSUE TITLE
SNS platform application with FCM, messages not delivered

### ISSUE THREAD

**Issue by tomdevroomen** [aws/aws-sdk-java#2012]
Hi,

I've implemented SNS with Google Firebase and aal is working pretty much fine.
Except that several customers are complaining messages aren't received.
On SNS we've turned on the delivery status feature (https://aws.amazon.com/blogs/mobile/using-the-delivery-status-feature-of-amazon-sns/) and see nearly all messages are sent outside SNS (some failure with `NOT_REGISTERED`, but these are accounted for).
So, it seems messages are delivered to FCM, but not received by the customer.

Is there a way to see if messages are really delivered to devices somehow? Or can you maybe point me in a direction to see some logging about delivery within Firebase ?

**Comment by debora-ito** [comment]
So if you are monitoring the delivery status of the SNS messages and there seems to be a successful message publication to the provider, I'd suggest you to reach out to Google Firebase support channels or search the dev community if someone is experiencing the same problems you are. 

Found this two questions on StackOverflow that may be helpful:
- https://stackoverflow.com/questions/40925195/app-connected-to-fcm-not-receiving-notification-from-aws-sns
- https://stackoverflow.com/questions/37711082/how-to-handle-notification-when-app-in-background-in-firebase

Closing this as it's not an issue with the SDK.
