### ISSUE TITLE
When and how does code generation occur?

### ISSUE THREAD

**Issue by inkblot** [aws/aws-sdk-java#2013]
The source code for many of the client interfaces and classes has an annotation indicating that they are generated using com.amazonaws:aws-java-sdk-code-generator. I can see easily enough that this library is used in a maven plugin, aws-java-sdk-codegen-maven-plugin, but I can't find where this maven plugin is used in any maven modules.

When and how is the code generator invoked to create the client source? Will changes in templates affect existing service clients?

**Comment by debora-ito** [comment]
@inkblot the code is generated by our internal deployment pipeline, based on templates that are owned and maintained by the AWS service teams. This means that changes in the templates are always made upstream, and any change made after that will be overwritten by the next update on the template.

I hope this answers your question.

**Comment by chrisbarbour** [comment]
Would it be possible to open source the templates so that others could generate code that can interact with the SDKs?
