### ISSUE TITLE
Java source version

### ISSUE THREAD

**Issue by inkblot** [aws/aws-sdk-java#2014]
The TravisCI configuration included an openjdk6 build until version 1.11.394 on 8/23/2018. However, when the openjdk6 CI build was removed, the jre.version maven property which controls the maven compiler plugin's source and target versions was left at 1.6 and it still has that value. Leaving the jre.version property at 1.6 blocks the use of Java 7 and later language features in the SDK source code. Is this discrepancy between the Travis build and the maven configuration intentional? Is Java 6 supported or not? Could jre.version be set to 1.7 without any difficulties?

**Comment by spfink** [comment]
The AWS Java SDK 1.11.x versions must still maintain backwards compatibility with JDK 6.
