### ISSUE TITLE
StateMachine.fromJson fails to parse definition when "Version" is specified

### ISSUE THREAD

**Issue by mhuffman-r7** [aws/aws-sdk-java#2015]
### Problem

According to the [Amazon States Language](https://states-language.net/spec.html#toplevelfields) specification:

> A State Machine MAY have a string field named “Version”, which gives the version of the States language used in the machine. This document describes version 1.0, and if omitted, the default value of “Version” is the string “1.0”.

The `StateMachine` class does not support the "Version" field and configures an `ObjectMapper` such that `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` has the default value of true. This results in `StateMachine` not being able to parse state machine definitions that contain a top-level field of "Version".

The result is an exception thrown:

```
Exception in thread "main" com.amazonaws.SdkClientException: Could not deserialize state machine.
...
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Version" (class com.amazonaws.services.stepfunctions.builder.StateMachine$Builder), not marked as ignorable (4 known properties: "States", "StartAt", "TimeoutSeconds", "Comment"])
```

Affected SDK Version: 1.11.568

### Steps to Reproduce

1. Define a State Machine with JSON definition that includes a top level element "Version" with the value "1.0" (as allowed by the specification).
2. Run a `describeStateMachine` request against the State Machine
3. Execute `StateMachine.fromJson` on the State Machine's definition value
4. Observe the exception be thrown

#### Sample Code

```java
import com.amazonaws.regions.Regions;
import com.amazonaws.services.stepfunctions.AWSStepFunctions;
import com.amazonaws.services.stepfunctions.AWSStepFunctionsClientBuilder;
import com.amazonaws.services.stepfunctions.builder.StateMachine;
import com.amazonaws.services.stepfunctions.model.DescribeStateMachineRequest;
import com.amazonaws.services.stepfunctions.model.DescribeStateMachineResult;

public class StepFunctionsTest {

  public static void main(String[] args) {

    AWSStepFunctions client = AWSStepFunctionsClientBuilder.standard().withRegion(Regions.US_EAST_1).build();

    DescribeStateMachineResult result = client.describeStateMachine(new DescribeStateMachineRequest().withStateMachineArn("<arn>"));

    StateMachine stateMachine = StateMachine.fromJson(result.getDefinition()).build();

    System.out.println(stateMachine);
  }
}
```

### Possible Solutions
- Enable `@JsonIgnoreProperties("Version")` on the `StateMachine` and `StateMachine.Builder` classes
- Disable `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` on the `StateMachine.MAPPER` instance
- Define and fully parse the "Version" field in the the `StateMachine` and `StateMachine.Builder` classes

**Comment by debora-ito** [comment]
Hi @mhuffman-r7, I was able to reproduce the issue. I see you already submitted a PR, it is pending review. Thank you!
