### ISSUE TITLE
BatchWrite in DynamoDb Mapper doesn't fail on duplicate entries in different batches

### ISSUE THREAD

**Issue by groverniharika25** [aws/aws-sdk-java#2017]
BatchWrite in DynamoDb Mapper doesn't fail on duplicate entries in different batches

However, when two elements with same partition key are in the same batch then BatchWrite() rejects the complete batch and throw an error, but if similar elements are in different batches it doesn't fail or throw an error.

## Expected Behavior
Should throw an error for duplicates even if in different batches.
## Current Behavior

I have request to batchWrite in DB which contains 51 values , the batchWrite() divides the request into 3 batches of 
Batch 1 has 1-25, 
Batch-2 has 26-50, 
and Batch-3 has 51 element. 
Now, 50 th, as well as 51st element, has same PrimaryKey(Partition key+Range Key). But the method() didn;t fail but it SILENTLY overrides the 50th element with 51st without throwing any errors.

## Possible Solution
DynamoDbMapper throws error : Exception: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Provided list of item keys contains duplicates (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: J4LE8H63SQUPQJMV7J76T9ACRNVV4KQNSO5AEMVJF66Q9ASUAAJG)

The similar error should be thrown even when duplicates are spanned over various batches.

## Steps to Reproduce (for bugs)
1. Insert 51 elements in dynamodb table with 50th as well as 51st element with same value.

## Context
I was trying to insert 50 elements in dynamo using batchwrite().

## Your Environment

* AWS Java SDK version used: aws-java-sdk-dynamodb-1.11.558
* JDK version used: open-jdk-11
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @groverniharika25, since you are using version `1.11.xx` of the SDK, I transferred your issue to the V1 repo.

**Comment by kittu532518** [comment]
Am using 1.12.xxx of sdk version and still having the same issue, any help is appreciated.
