### ISSUE TITLE
Error while trying to create a Create Table statement in Athena 

### ISSUE THREAD

**Issue by Yashmadane** [aws/aws-sdk-java#2020]
Code:

Connecting to Athena...
log4j:WARN No appenders could be found for logger (com.simba.athena.amazonaws.AmazonWebServiceClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.sql.SQLDataException: [Simba][JDBC](11300) A ResultSet was expected but not generated from query "CREATE EXTERNAL TABLE IF NOT EXISTS test.abc1 (name string,age int) LOCATION 's3://a1t3exbenc-2/Archive". Query not executed. 
	at com.simba.athena.exceptions.ExceptionConverter.toSQLException(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.checkCondition(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeNoParams(Unknown Source)
	at com.simba.athena.jdbc.common.SStatement.executeQuery(Unknown Source)
	at AthenaDemo.main(AthenaDemo.java:27)
Finished connectivity test.

**Comment by debora-ito** [comment]
Hi @Yashmadane, according to the Athena Create Table reference [docs](https://docs.aws.amazon.com/athena/latest/ug/create-table.html):

> [db_name.]table_name
>
> Specifies a name for the table to be created. The optional db_name parameter specifies the database where the table exists. If omitted, the current database is assumed. **If the table name includes numbers, enclose table_name in quotation marks, for example "table123"**. If table_name begins with an underscore, use backticks, for example, \`_mytable\`. Special characters (other than underscore) are not supported.

I guess your table `abc1` is missing the quotation marks. Let us know if that helps.

**Comment by debora-ito** [comment]
Closing, feel free to reopen if you have further questions.
