### ISSUE TITLE
sts client should be defaulting to regional endpoint

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-sdk-java#2023]
As STS is [recommended to use regional endpoint](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html), the STS client builder should be defaulting to use regional endpoint instead of the global one `https://sts.amazonaws.com`.

**Comment by debora-ito** [comment]
Hi @zhangzhx, using regional STS endpoints is recommended, but the **default** still is the global endpoint. Check the "Writing Code to Use AWS STS Regions" [section](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#id_credentials_temp_enable-regions_writing_code) in the docs you linked to learn more about it.

Closing this, feel free to reach out if you have further questions.

**Comment by joelthompson** [comment]
For those who find this later, as of 1.11.618, it's possible to change the default behavior using either an environment variable or a profile config option. See https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/services/securitytoken/RegionalEndpointsOptionResolver.java

**Comment by denispar** [comment]
Is there any way to set this from the code without changing environment or config files?

**Comment by joelthompson** [comment]
If you're writing the code, you can set the `EndpointConfiguration` explicitly -- see the [docs here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#region-selection-choose-endpoint).

**Comment by denispar** [comment]
@joelthompson this is not the same. With AWS_STS_REGIONAL_ENDPOINTS the client picks STS endpoint for the region. With EndpointConfiguration() I need to maintain a map of the endpoints and handle https://github.com/aws/aws-sdk-java/blob/282dd50b75e0f7e7bcb213209214022468fe7a3e/aws-java-sdk-sts/src/main/java/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.java#L92


Perhaps the way will be to subclass AWSSecurityTokenServiceClient and override mapToLegacyRegionIfNecessary() to do nothing.

**Comment by joelthompson** [comment]
No you don't. Just `"https://sts." + regionName + "amazonaws.com"`
