### ISSUE TITLE
Need API to fetch Amazon EKS-Optimized AMI based on region and version

### ISSUE THREAD

**Issue by ArundathiVardhan** [aws/aws-sdk-java#2025]
As of now we have refer this https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html documentation and get it, there is no API to fetch Amazon EKS-Optimized AMI based on region and version dynamically.

**Comment by debora-ito** [comment]
Hi @ArundathiVardhan can you tell us more about your use case, how you might use the values of the AMIs? 

Because according to the docs there's two methods for creating worker nodes, one is using `eksctl` and the other is using the AWS console.

**Comment by ArundathiVardhan** [comment]
It would be good for me to dynamically fetch the AMIs and show it in our UI for better user-experience. As of now I have a class where in the AMIs  are hard coded based on version and region. Its hard to update it every time looking at the document.

**Comment by debora-ito** [comment]
Got it, I'll send your feedback to the EKS service team.

I'd also suggest you to post your request on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=303), to get the service team's attention  and support.

Closing this, feel free to reach out if you any other question.

**Comment by Debo1404** [comment]
Hi @debora-ito , I am in search of this API to fetch the AMI types dynamically. Any update on this? Is it available now?
