### ISSUE TITLE
No way to get ports/protocols for iprange in security group

### ISSUE THREAD

**Issue by soraoka** [aws/aws-sdk-java#2026]
I'm using GovCloud, and I'm just trying to get the inbound ports/protocols for each rule in a Security Group.  For example, the AWS console for a given Security Group, on an "Inbound" tab shows a table.  The table shows Type, Protocol, Port Range, Source, and Description, where "Source" is the IP/CIDR.  For example:

Type | Protocol | Port Range | Source | Description
-------------------------------------------------------
Custom TCP Rule | TCP | 81 | 10.0.0.0/8 | My Application
HTTP | TCP | 80 | 10.1.20.16/32 |  Hello World

There doesn't seem to be a way to get anything other than the list of "Source" data.   I can get the protocol, fromPort and toPort, but they are tied to the SecurityGroup, not to each Source listed in the table.  For example:

    public void printDetailsFor(String groupID) {
        AmazonEC2Client ec2 = new AmazonEC2Client();
        Region region = Region.getRegion(Regions.GovCloud);
        ec2.setRegion(region);

        DescribeSecurityGroupsRequest request = new DescribeSecurityGroupsRequest();
        request.setGroupIds(Arrays.asList(groupID));

        DescribeSecurityGroupsResult response = ec2.describeSecurityGroups(request);

        MySecurityGroupDetails mySecurityGroupDetails = new MySecurityGroupDetails();
        for(SecurityGroup group : response.getSecurityGroups()) {
            mySecurityGroupDetails.setGroupID(group.getGroupId());
            System.out.println("Group ID .....: " + group.getGroupId());
            List<IpPermission> ipPermissions = group.getIpPermissions();
            for( IpPermission ipPermission : ipPermissions ) {
                System.out.println("     protocol: " + ipPermission.getIpProtocol());
                System.out.println("     from port: " + ipPermission.getFromPort());
                System.out.println("     to port: " + ipPermission.getToPort());

                List<String> ipRanges = ipPermission.getIpRanges();
                for(String ipRange : ipRanges ) {
                    System.out.println("     source: " + ipRange);
                }
            }
        }
    }

There should be a way to get the list of type, protocol, ports, and IP/CIDR for each record in the inbounds table of a Security Group.

**Comment by debora-ito** [comment]
@soraoka yeah, I couldn't find an API that returns the Inbound info in a table structure you want. I'll forward your request to the EC2 team, but I also would like to suggest to post your request in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) where you can get direct support from the EC2 team.

I'll go ahead an close this, feel free to reopen if you have any further questions.
