### ISSUE TITLE
AWS S3 generatePresignedUrl not working with global mode enabled

### ISSUE THREAD

**Issue by djanjic** [aws/aws-sdk-java#2033]
AWS S3 generates bad URL in case global mode is enabled and the object is located in another region. Code to reproduce this error:

```
s3Client = AmazonS3ClientBuilder
                .standard()
                .withForceGlobalBucketAccessEnabled(true)
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secret)))
                .withRegion(Regions.US_EAST_1)
                .build();
Date expiration = new Date();
        long expTimeMillis = expiration.getTime();
        expTimeMillis += 1000 * 60 * 60;
        expiration.setTime(expTimeMillis);

GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(S3_CANADA_BUCKET, key)
                                                                            .withMethod(HttpMethod.GET)
                                                                            .withExpiration(expiration);

System.out.println(s3Client.generatePresignedUrl(generatePresignedUrlRequest).toString());
```

Generated URL has the correct domain (s3.ca-central-1.amazonaws.com) but `X-Amz-Credential` value contains `us-east-1`.

If I add something like this before url generation it works:
```
s3Client.headBucket(new HeadBucketRequest(S3_CANADA_BUCKET));
System.out.println(s3Client.generatePresignedUrl(generatePresignedUrlRequest).toString());
```
Signer uses correct region if bucket location is cached but if it's not default one is choosed.

**Comment by debora-ito** [comment]
Hi @djanjic, generating presigned URLs will not work with global bucket access enabled when [SigV4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) is used, because SigV4 requires the region info.

So to be able to use `generatePresignedUrl()` properly, the bucket region must be defined in the S3 client.

**Comment by djanjic** [comment]
So, presigned url can’t really work with global mode enabled? Is there any workaround for this problem? I can leave headBucket request before generating url but if understand correctly it’s just a lucky coincidence that it’s working.

**Comment by debora-ito** [comment]
> So, presigned url can’t really work with global mode enabled?

That's correct, they will not work together. 
Do you have any particular reason to keep using global access mode? Can't you define the region in the client?

**Comment by djanjic** [comment]
We have some kind of geofencing, where data-at-rest needs to be in different region than our main. Some AWS services we use are not available in all regions 😔
Region is defined in client but we also need to access the data from other regions (global mode). Actions like put/get object are working, yet we do have a problem with presigned url. 
One ugly solution is to create client per region or to use this head hack i described above and not to update aws s3 library.

**Comment by debora-ito** [comment]
So I guess using the `headBucket()` workaround should be fine in this case.

I'll go ahead and close this, but feel free to reopen if any further questions come up.
