### ISSUE TITLE
using S3 preSigned URL to upload file throw the error "The Content-MD5 you specified was invalid.",  while generatePresignedUrlRequest with ContentMd5

### ISSUE THREAD

**Issue by dajiangqingzhou** [aws/aws-sdk-java#2034]
@millem @fulghum @kiiadi @shorea @zhangzhx 
Hello guys. I use S3 preSigned URL to upload file, but it return an error "The Content-MD5 you specified was invalid".
It happens only when I generate Presigned Url with contentMd5.However it works fine when I  annotation the line '.withContentMd5(md5)'.
My file md5 is 32c295626872e465b3d0b590eb8e88a7.

Here is my code:
```java

private static URL generatePresignUrl(HttpMethod method, String s3Key, long expiratMillis, String md5) {
        AmazonS3 s3client = getDefaultS3Client();
        Date expiration = new Date(System.currentTimeMillis() + expiratMillis);
        GeneratePresignedUrlRequest generatePresignedUrlRequest =
                new GeneratePresignedUrlRequest(bucketName, s3Key)
                        .withMethod(method)
                        .withExpiration(expiration)
                        .withContentMd5(md5)
                        .withKey(s3Key);
        return s3client.generatePresignedUrl(generatePresignedUrlRequest);
    }

    private static AmazonS3 getS3Client(String accessKey, String secretKey) {
        AWSCredentials awsCredentials = new BasicAWSCredentials(accessKey, secretKey);
        AWSStaticCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(awsCredentials);
        return AmazonS3ClientBuilder.standard()
                .withCredentials(credentialsProvider)
                .withRegion(regionName)
//                .withPathStyleAccessEnabled(true)
                .build();
    }

```

postman:
![选区_012](https://user-images.githubusercontent.com/4321439/60160341-bdfafd80-9827-11e9-8a26-03ec4c4d8faf.png)

Does S3 support checksum when using presigned url?
Could anybody give me a piece of advice to help me solve this? Thank you!

**Comment by debora-ito** [comment]
Hi @dajiangqingzhou 

According to S3 [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests), S3 expects Content-MD5 to be the base64-encoded 128-bit MD5 digest of the message (without the headers). 

Can you base64-encode your MD5 and check if you're still see the problem?

**Comment by dajiangqingzhou** [comment]
> Hi @dajiangqingzhou
> 
> According to S3 [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests), S3 expects Content-MD5 to be the base64-encoded 128-bit MD5 digest of the message (without the headers).
> 
> Can you base64-encode your MD5 and check if you're still see the problem?

Hi @debora-ito . Thank you for your reply. I had try to base64-encode my MD5, and It didn't work. It throw another message "The request signature we calculated does not match the signature you provided"

**Comment by debora-ito** [comment]
I was able to upload a file using presigned URL with content-md5, by explicitly declaring the `content-md5` header in the http PUT request.

So for example, I'm using `curl` to upload the file to S3, and here's the command I used:

```
> curl --request PUT --upload-file <my_file> <generated_presigned_url> -H "content-md5: <base64_encoded_md5>"
```

The `content-md5` value is used by S3 to calculate the signature, and you were seeing a signature mismatch error because it was missing in the request .

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have more questions.
