### ISSUE TITLE
Waiter SDK creates many unnecessary threads.

### ISSUE THREAD

**Issue by tonicsoft** [aws/aws-sdk-java#2035]
In `com.amazonaws.services.ecs.waiters.AmazonECSWaiters` (and probably other places), we create a fixed thread pool with 50 threads.

```
private final ExecutorService executorService = Executors.newFixedThreadPool(50);
```

This is probably overkill for most scenarios. I think a better (and cheap) approach would be to create a `ThreadPoolExecutor` that has a much smaller core pool size (maybe 2) but is allowed to scale up to 50.

An even better (but not as cheap) solution would be to allow the `ExecutorService` to be passed in the constructor of the clients.

**Comment by debora-ito** [comment]
@tonicsoft that's a good point, I'll mark this as feature request.

**Comment by debora-ito** [comment]
Version `1.11.589` is out with a change in our Waiters. From the changelog:

> Waiters now use a cached threadpool ExecutorService instead of a fixed threadpool. This will reduce overall resource consumption for typical use-cases, and eliminate inappropriate thread blocking behavior for heavy use.

I'll go ahead and close this one. Thank you for reaching out, and feel free to reopen if you have further questions.
