### ISSUE TITLE
Deprecated javax dependency for JDK11+

### ISSUE THREAD

**Issue by mina-asham** [aws/aws-sdk-java#2036]
Hi,

I am getting a log WARN with "JAXB is unavailable. Will fallback to SDK implementation which may be less performant".

While it's not necessarily an issue, it's bad to clutter the logs with such warns. It seems that the required module was marked for deprecation in Java 9/10 and was removed in Java 11: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

I was able to get this to disappear by adding jaxb-api to my POM file: https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api

This needs to be added to the AWS SDK since it doesn't make sense for me import a dependency needed internally in another library.

Happy to do the code change myself if there are no objections to that.

Cheers,
Mina

**Comment by debora-ito** [comment]
Hi @mina-asham, using the jaxb dependency is intended to be optional. It's a choice you can make - either add the dependency for the performance or don't add the dependency to keep your deployment lightweight. Adding the dependency in the SDK would force all into it being heavyweight for just this one piece of functionality.

**Comment by mina-asham** [comment]
@debora-ito I don't strictly disagree here, happy for it to be optional, however I have two issues with that:
1. It's not marked as an optional dependency here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/pom.xml, so we need to at least update the POM file
2. The log message doesn't explain that there is a missing optional dependency, it should suggest adding the missing dependency

I think making these two changes would make sense, what do you think?

**Comment by debora-ito** [comment]
I'm not familiar on how maven's optional dependency works exactly, but we cannot declare it as a optional dependency because the SDK V1 supports Java 6+ and the warning appears only for Java 9+, as you mentioned.

The intention of the warning is to call attention to the fact that you can add the jaxb dependency in your project if you choose performance, which was exactly what you did.

**Comment by mina-asham** [comment]
Maven optional dependency is the right thing to do here, even if the SDK V1 support Java 6+, this will work fine for all the versions. To quote the [Maven optional dependency page](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html): `The idea is that some of the dependencies are only used for certain features in the project and will not be needed if that feature isn't used.`, so it's more of a guidance basically.

So adding an optional dependency is up the consumer to bring it in or not, and if they do bring it in for Java 6-8, it will not actually cause any issues (yes the classes are going to be available twice on the classpath, but that actually doesn't cause any issues and is a user error anyway for bringing an optional dependency they don't need).

For the warning message, I just suggest making it refer to the exact Maven artifact instead of just saying "JAXB unavailable", something like "JAXB unavailable, please add javax.xml.bind:jaxb-api dependency to your project:

**Comment by debora-ito** [comment]
Also quoting the Maven page:

> If a user wants to use functionality related to an optional dependency, they have to redeclare that optional dependency in their own project.

This would be a breaking change for customers using Java 6-8. Also this:

> This is not the clearest way to handle this situation, but both optional dependencies and dependency exclusions are stop-gap solutions.

and this

> (yes the classes are going to be available twice on the classpath, but that actually doesn't cause any issues and is a user error anyway for bringing an optional dependency they don't need)

seem to illustrate some dependency confusion we'd like to avoid. 

Regarding the warning message, I agree that we can make it more clear so I'll pass your feedback to the team.

**Comment by debora-ito** [comment]
Forwarded the feedback, so I'll go ahead and close this. Feel free to reopen if you have further questions.

**Comment by mina-asham** [comment]
I am happy with just updating the log message specially that SDK 2.0 is already out anyway, will submit this as a PR.
