### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [aws/aws-sdk-java#2039]
Hi
The following lines have cryptographic API misuses. <br> File name => aws-java-sdk-glacier/src/main/java/com/amazonaws/services/glacier/internal/TreeHashInputStream.java: Line number => 37: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => aws-java-sdk-glacier/src/main/java/com/amazonaws/services/glacier/TreeHashGenerator.java: Line number => 150: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/MessageMD5ChecksumHandler.java: Line number => 224: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/MessageMD5ChecksumHandler.java: Line number => 258: API name => MessageDigest:<BR> File name => aws-java-sdk-cloudfront/src/main/java/com/amazonaws/services/cloudfront/util/SignerUtils.java: Line number => 143: API name => Signature:First parameter (with value "SHA1withRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => aws-java-sdk-cloudfront/src/main/java/com/amazonaws/services/cloudfront/util/SignerUtils.java: Line number => 146: API name => Signature:<BR> File name => aws-java-sdk-test-utils/src/main/java/com/amazonaws/test/util/InputStreamUtils.java: Line number => 39: API name => MessageDigest:<BR> File name => aws-java-sdk-test-utils/src/main/java/com/amazonaws/test/util/InputStreamUtils.java: Line number => 34: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by debora-ito** [comment]
Hi @mhp0rtal, can you give more details on what you are asking here? Is this a static code analysis report?

**Comment by debora-ito** [comment]
So most of the entries are about using MD5, which is being used by the APIs as a checksum to verify data integrity and not as a cryptographic hash function, so this is not a security issue. Also, we cannot change this without making a change in the service side.

The "unexpected call to method" entries I don't really get what's the concern; and there's a couple of entries with empty messages.

I'll go ahead and close this. Feel free to reopen if you have further questions.
