### ISSUE TITLE
Problem when querying DynamoDB table using Object Persistence Model

### ISSUE THREAD

**Issue by juniorklein** [aws/aws-sdk-java#204]
When I query or scan a table, I use DynamoDBQueryExpression or DynamoDBScanExpression respectively. 
Using the methods addFilterCondition or withRangeKeyCondition, the attribute for comparison is passed with an instance of object Condition.
Using this model, I have a problem with the attribute name passed to the method. I need call the method with the attribute name for the attribute in the DynamoDB because the SDK don't allows the name of the property in the java class.

For example:

public class UserSocialNetworkItem {

	@DynamoDBHashKey(attributeName = "ID")
	private Long id;
	
	@DynamoDBRangeKey(attributeName = "PropertyA")
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "GSI1")
	private String propertyA;
	
	@DynamoDBAttribute(attributeName = "PropertyB")
	private String propertyB;
	
	@DynamoDBAttribute(attributeName = "PropertyC")
	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "GSI2")
	private Boolean propertyC;
}

When I query this table using filters in properties "propertyA" and "propertyB", the SDK only allows the query if I pass attribute name "PropertyA" and  "PropertyB".
I believe the correct form is using the java class property name and not the Dynamo attribute name.

**Comment by david-at-aws** [comment]
`addFilterCondition` and `addRangeKeyCondition` are straight passthroughs to the underlying `AmazonDynamoDBClient`, so they use the DynamoDB attribute name. Changing this isn't really an option as it would break a lot of people, but we could look at adding an option (probably on DynamoDBMapperConfig?) to automatically translate from the POJO member name to the corresponding DynamoDB attribute name? We'd presumably need to do this translation for the new expression parameters as well? That gets a little more exciting...
