### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [aws/aws-sdk-java#2040]
Hi
The following lines have cryptographic API misuses. <br> File name => aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/util/S3UploadPolicy.java: Line number => 115: API name => SecretKeySpec:<BR> File name => aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/util/S3UploadPolicy.java: Line number => 115: API name => SecretKeySpec:<BR>

**Comment by debora-ito** [comment]
Closing as duplicate of #2039.
