### ISSUE TITLE
DynamoDB Mapper with Object properties.

### ISSUE THREAD

**Issue by dscalzi** [aws/aws-sdk-java#2045]
I am using the DynamoDB Mapper to serialize and deserialize data from dynamodb, In the POJO, I have a property that could be one of serveral types, depending on the context (`short`, `int`, `String`, etc). In order to account for this, the property needs to be declared as an `Object`, with the underlying value containing a solid instance.

I would expect the SDK to be able to handle this, since everything is stored inside of an AttributeValue. The instance of the actual value should be checked, and converted to an AttributeValue if it is one of the [supported types](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html).

This does not seem to be the case, as the mapper is unable to serialize the POJO, failing on the property declared as `Object`. What's probably happening is the mapper sees the Field is declared as an `Object` and skips it. **A fix would be to check the value of Fields declared as `Object` and then pick a marshaller based on the field value's type.**

Adding a `DynamoDBTypeConverter` to the Object property would not work, as the object needs to be converted directly to an `AttributeValue` so that the original type is persisted.

A fix, or more insight if I'm doing something incorrectly, would be greatly appreciated.

**Comment by debora-ito** [comment]
Hi @dscalzi this is an interesting request and I'm marking as such, but it would be a big change to be made on V1. As we are concentrating efforts to make an improved DynamoDB Mapper in V2, this will definitely be considered for V2.

Feel free to track this in the referenced issue above and reach out if you have further questions.
