### ISSUE TITLE
s3 sdk uploadDirectory do not support resume upload

### ISSUE THREAD

**Issue by xiaozhangshu** [aws/aws-sdk-java#2048]
Can s3 java sdk upload directory support resume upload， the succeed files do not upload again？

**Comment by debora-ito** [comment]
When using `uploadDirectory()`, you can pause and resume each subtransfer associated with the multiple file upload. Take a look at the MultipleFileUpload.getSubTransfers() [javadoc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/MultipleFileUpload.html#getSubTransfers--).

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have any other question.
