### ISSUE TITLE
DynamoDBAsyncMapper for AmazonDynamoDBAsyncClient.

### ISSUE THREAD

**Issue by adaofeliz** [aws/aws-sdk-java#205]
The asynchronous DynamoDB client extends from the synchronous client, and provides new method names for the asynchronous operations that return Futures. 

Currently the DynamoDBMapper will always use the synchronous methods of whatever AmazonDynamoDB client that you pass in. 

The feature requested is asynchronous support using the mapper.

**Comment by omar-eyeviewdigital** [comment]
Any update on this?

**Comment by shorea** [comment]
This is not something we'll likely get to soon. With Java 8 it becomes very easy to submit a method as an async task so the utility of an async version of the mapper (or clients) is not as great. That coupled with the ability to use completable feature makes it a more attractive option for async programming.

**Comment by fpoolev** [comment]
+1

**Comment by shaharck** [comment]
@shorea there's already an async support which is the Async client. isn't using java 8 to invoke the sync mapper is yet another async implementation? is the best practice now is to copy/paste the sync mapper code and run the async client? or create the additional async implementation and run the synced mapper?

**Comment by fvasco** [comment]
Is this feature available?

**Comment by n3whous3** [comment]
It is almost 2020 and we don't have any mapper yet for something which is now getting main stream, like using reactive all the way down to this DB. I think this should have more priority, the non-async version has even better 3rd party support, which is a shame.

**Comment by fvasco** [comment]
We fixed it by removing DynamoDB, it works!

**Comment by millems** [comment]
We're tracking this in V2: https://github.com/aws/aws-sdk-java-v2/issues/35

Non-blocking support is currently in scope for the V2 mapper's GA.
