### ISSUE TITLE
HttpClient dependency issue

### ISSUE THREAD

**Issue by shubh2600** [aws/aws-sdk-java#2051]
I have been using AWS SDK(<version>1.11.502)along side (<groupId>org.apache.httpcomponents <artifactId>httpclient <version>4.5.7) and the default version that AWS sdk comes with is 4.5.5.
I have started to notice some unexpected behaviour with the sdk ,though of the API calls work using SDK some ends up with SignatureDoesNotMatch error.
For example the SDK call to List tags for Lambda function,AWSResourceGroupsTaggingAPI to get tags work only when I specify filter 'ec2' but when I use filter 'ec2:instance' it gives an error.

**Comment by debora-ito** [comment]
Hi @shubh2600, thank you for reaching out. This is a known issue that we are tracking in #1919. Apache made some breaking changes in `httpclient-4.5.7` and it impacted some of our APIs.

The solution to add the ability to use the newer versions of httpclient is still being worked on, but in the meantime using `httpclient-4.5.5`  should work fine.

I'll go ahead and close this, feel free to add any comments and follow the updates in the tracking issue.
