### ISSUE TITLE
ParameterValidationError on MTurk createWorkerBlock()

### ISSUE THREAD

**Issue by westand** [aws/aws-sdk-java#2055]
I am on a very recent build. A straightforward attempt to block an MTurk worker  ("workerID") as follows:

<code>
AmazonMTurk client = mturkClient.getClient();
CreateWorkerBlockRequest WBR = new CreateWorkerBlockRequest();
WBR.setWorkerId(workerID);
WBR.setReason("Low performance")
CreateWorkerBlockResult WBResult = client.createWorkerBlock(WBR);
</code><BR><BR>

Fails with error:

<code>
com.amazonaws.services.mturk.model.AmazonMTurkException: The value "REDACTED" is not valid for the parameter WorkerId. (1563818969320 s) (Service: AmazonMTurk; Status Code: 400; Error Code: ParameterValidationError; Request ID: REDACTED)
</code><BR><BR>

The WorkerID values (Strings) being passed are valid. I am able to send a notification to the worker using the exact same value. This is happening for all workerIDs.

**Comment by debora-ito** [comment]
Hi @westand can you share the code where you create the client? Can you check if it's not using the sandbox endpoint?

**Comment by westand** [comment]
Oooof. Yep. Connecting to the sandbox. My bad. 

Just for documentation should another user find themselves here: Note that trying to send a "notify user" action to a non-existent user does not result in an Exception, but error text in the response. In contrast, "block user" throws an Exception.

**Comment by debora-ito** [comment]
Thank you for the follow-up!
