### ISSUE TITLE
How does TransferManager handle the InputStream in PutObjectRequest if the content length is less than 16MB

### ISSUE THREAD

**Issue by victor-yi** [aws/aws-sdk-java#2059]
We have a library which uses `AmazonS3.putObject()` to push files to S3 bucket. And now we are going to use `TransferManager.upload()` to replace it as TransferManager supports asynchronous uploads and downloads. But I want to know how does TransferManager handle the InputStream in the PutObjectRequest object. 
I checked the AWS SDK source code and found it uses `AmazonS3.putObject()` in the deep of `TransferManager.upload()` if the file size is less than 16MB, and it will restore the original InputStream to make the caller can release it if necessary. And it will close the InputSteam automatically if the file size is greater than 16MB.
We are using AWS SDK 1.11.270.
The file couldn't be pushed to S3 if using below way. 
```
try (InputStream is = new BufferedInputStream(new FileInputStream(file))) {
            transferManager.upload(s3Config.getBucketName(), LocalDateTime.now().toString(), is, metadata);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

I'm guessing if it will impact the OS/app as we don't close the InputStream. How do you handle this case if using `TransferManager.upload()` to upload files whose size is less than 16MB.
```
try {
            transferManager.upload(s3Config.getBucketName(), LocalDateTime.now().toString(), is, metadata);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

**Comment by zoewangg** [comment]
If you are uploading a file, you can use upload file API directly and you don't need to convert it to an inputstream.
https://github.com/aws/aws-sdk-java/blob/e89e755edcecc59ffdaf6648bc10a97ea092a3bc/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L485-L487

By default, multipartUploadThreshold is 16MB, which means If the file size is less than 16MB, it will be uploaded as a single part. You can configure the value from the builder. 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManagerBuilder.java#L265

**Comment by viktoryi** [comment]
Assuming we must use the InputStream, looks like the original InputStream in the PutObjectReuqest couldn't be closed after the file has been uploaded to S3 bucket successfully if using `TransferManager.upload()` with default settings and the content length is less than 16MB. 
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/S3DataSource.java#L52

It does the upload in an asynchronous way, we can't close the InputStream explicitly in the main thread. There will be an exception thrown if the other thread is uploading the file and we have already closed the InputStream.

There will be more and more unclosed InputStream as time elapsed according to this situation. Will it be a risk for OS/app? Please correct me if I'm wrong.

**Comment by zoewangg** [comment]
To close the provided inputStream, there are two options:

1. Adding your own `ProgresssListener` to close the stream on `TRANSFER_COMPLETED_EVENT` event. (non-blocking way)
```
upload.addProgressListener();
```

2. you can check if the upload is done and then close the inputstream (blocking way)
```
         upload.waitForCompletion();
         inputStream.close();
```

> There will be more and more unclosed InputStream as time elapsed according to this situation Will it be a risk for OS/app?  

Yes, it is recommended to close the InputStream to release the resources associated with the stream once you are finished with the stream; leaving them open could cause resource leak and other issues.

**Comment by viktoryi** [comment]
Had a try to use `ProgressListener.ExceptionReporter.wrap(new CustomProgressListener())`. But sometimes the transfer is failed and canceled, the exception won't be logged. Checked the code and found below method is only used in the tests.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/event/ProgressListener.java#L104-L111

**Comment by debora-ito** [comment]
@victor-yi apologies, it looks like this issue has escaped our attention and got stale. Marking this to auto-close soon, if you want us to take another look let us know.
