### ISSUE TITLE
RegionUtils.getRegionsForService(“cloudwatch”) returns empty list

### ISSUE THREAD

**Issue by jkoe-r7** [aws/aws-sdk-java#2063]
Similar to https://github.com/aws/aws-sdk-java/issues/1766 where an update to https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json is needed for CloudWatch. An entry for this service does not exist at the moment.

**Comment by debora-ito** [comment]
Hi @jkoe-r7,  it's not very intuitive but the actual endpoint prefix for Amazon CloudWatch is "monitoring".

According to the [RegionUtils.getRegionsForService()](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/RegionUtils.html#getRegionsForService-java.lang.String-) javadocs, you can use the client interface constant ENDPOINT_PREFIX to get the service endpoint prefix. So in the case of CloudWatch you can use:
```java
AmazonCloudWatch cw = AmazonCloudWatchClientBuilder.defaultClient();
RegionUtils.getRegionsForService(cw.ENDPOINT_PREFIX);
```

**Comment by jkoe-r7** [comment]
Ah, got it. Thanks for the clarification!
