### ISSUE TITLE
AWS: Do bad requests count in the total APIs count.

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#2065]
We've restricted the cost explorer APIs for all my IAM users except one and a root user. As the pricing model for the Cost Explorer APIs is a bit higher when compared to other services like CloudWatch APIs. 

Do the total Cost Explorer APIs count (mentioned in billing) includes the APIs that are thrown exceptions?

Let's say if one of the restricted IAM user tried to access the Cost Explorer APIs and got the exception 'AccessDeniedException' will these count in the total APIs?

**Comment by debora-ito** [comment]
Hi @gowthamsankar312 that's a good question and I asked the Cost Explorer team about it, they said that only successful requests will be charged, API calls that return exceptions will not count.

Please note that if your result set is paginated each page counts as a separate request.

**Comment by debora-ito** [comment]
Closing, feel free to reopen if any further questions come up.

**Comment by gowthamsankar312** [comment]
@debora-ito Thank you for your help.
