### ISSUE TITLE
Closing KVS input stream takes a long time

### ISSUE THREAD

**Issue by adokarasev** [aws/aws-sdk-java#2067]
Calling `close` method on `GetMediaResult` input stream takes a long time for long streams. 

```
var result = mediaClient.getMedia(new GetMediaRequest().withStreamName(streamName).withStartSelector(new StartSelector().withStartSelectorType("EARLIEST")));
r.getPayload().close();
```

Here is  [repo with tests](https://bitbucket.org/chatterbubble/amazon-kvs/src/master/) to reproduce the error.

**Comment by debora-ito** [comment]
@adokarasev What version of the SDK are you using? And when you say long time, can you give more information on that?

I'll try to run your code sample in the meantime.

**Comment by pfisher** [comment]
Hi @debora-ito — thanks for getting back to us. If you take a look at the pom.xml file, you can find the versions of each dependency we are using. So, we are using version 1.11.597 of the SDK. I've copied the relevant segment of our pom.xml file below.

In terms of the time it takes to close a KVS stream, it seems like it may be somewhat variable, based on the duration of the stream. However, we consistently ran into issues in which it took a minimum of 50 seconds for a stream to be closed, and sometimes even longer than that.

Thanks again for all your help, and please let me know if you have any additional questions.

--Paul

```
    <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-kinesisvideo</artifactId>
            <version>1.11.597</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>amazon-kinesis-video-streams-parser-library</artifactId>
            <version>1.0.13</version>
        </dependency>
```

**Comment by bkempe** [comment]
Hey @debora-ito , are there any news on this?

**Comment by pfisher** [comment]
Hey @debora-ito — I just wanted to follow up to see whether there's been any progress on this. This seems like a pretty big blocker when dealing with KVS at any level of scale.

Thanks!

**Comment by dagnir** [comment]
AFAIK we have not been able to repro this yet. I will try to look into this this week.

**Comment by bkempe** [comment]
@dagnir any news? The test provided by @adokarasev reproduces the issue for us.

**Comment by bkempe** [comment]
@debora-ito @dagnir Any updates on this?

**Comment by debora-ito** [comment]
@adokarasev I'm so sorry for losing track of this. Are you still experiencing the issue with a more recent version of the SDK?

Let me know if you still want us to investigate this.
