### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/DEPENDENCIES'

### ISSUE THREAD

**Issue by vyaskartik16** [aws/aws-sdk-java#2069]
Synch Project with gradle files is working but while rebuild project or debug/run time it fires an error
"More than one file was found with OS independent path 'META-INF/DEPENDENCIES'"

All used dependencis are as follow:
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    //region Volley + HTTPMIME + GSON
    implementation 'com.android.volley:dc-volley:1.1.0'
    implementation 'org.apache.httpcomponents:httpmime:4.5.9'
    //implementation 'com.google.code.gson:gson:2.8.5'
    //endregion
}

**Comment by debora-ito** [comment]
Hi @vyaskartik16 unfortunately we don't have the expertise to help with Android environment issues. For that I suggest asking on StackOverflow where you can get support from the Android community.
