### ISSUE TITLE
Opsworks set permission operation can't find the IAM user 

### ISSUE THREAD

**Issue by pula2000** [aws/aws-sdk-java#2077]
The user does have access to the stack as a resource but opsworks strangely throws an exception saying the user doesn't exist even though it does.

**Comment by debora-ito** [comment]
Hi @pula2000 this looks more like an issue with user permissions management than with the SDK itself. 

Have you checked OpsWorks [Managing Users Permissions](https://docs.aws.amazon.com/opsworks/latest/userguide/opsworks-security-users.html) documentation? Is the user listed in the Users page for that stack in the AWS Console?

If you think this is an issue with the SDK, please provide a sample code we can use to reproduce, the errors you're seeing and the SDK version you're using.

**Comment by pula2000** [comment]
I'm trying to do automation where I create an AWS user in IAM, give it stack access and then on opsworks side give it ssh access. After the user in IAM is created successfully and given stack access, on opsworks side "set permission" operation throws an error saying the user doesn't exist (even though it does exist in IAM). When I added a thread.sleep to give it some wait time between IAM and Opsworks the ssh access operation went through successfully but there are times that it still fails. So wanted to have ssh access operation in opsworks be successful at all times.

**Comment by debora-ito** [comment]
Can you provide a sample code?

**Comment by debora-ito** [comment]
Are you calling OpsWorks [CreateUserProfile](https://docs.aws.amazon.com/opsworks/latest/APIReference/API_CreateUserProfile.html) after creating the IAM user and before calling SetPermission?

**Comment by debora-ito** [comment]
Closing due to no response, please feel free to reopen if you're still experiencing this issue.
