### ISSUE TITLE
Missing encoding of comma in S3 Content-Disposition header

### ISSUE THREAD

**Issue by sithmein** [aws/aws-sdk-java#2079]
According to RFC, a comma in the filename field of the `Content-Disposition` header must be percent-encoded if the filename contains Unicode characters (RFC6266 and RFC5987). If this is not done, Chrome refuses to download such files (see https://bugs.chromium.org/p/chromium/issues/detail?id=454165). I didn't manage to set the correct `Content-Disposition` header with the S3 Java SDK. If I leave the comma unencoded when generating a presigned URL it will turn up unencoded in the final S3 response:

```
request.withResponseHeaders(new ResponseHeaderOverrides().withContentDisposition("attachment; filename*=UTF-8''A,B"));
=> Content-Disposition: attachment; filename*=UTF-8''A,B
```

If I encode the comma prior to generating the presigned URL, the final response will contain "%2C" instead of the comma:

```
request.withResponseHeaders(new ResponseHeaderOverrides().withContentDisposition("attachment; filename*=UTF-8''A%2CB"));
=> Content-Disposition: attachment; filename*=UTF-8''A%252CB
```

However, the header must look like
```
Content-Disposition: attachment; filename*=UTF-8''A%2CB
```

**Comment by debora-ito** [comment]
@sithmein I was able to make it work on Chrome adding double quotes around the filename:

```
request.withResponseHeaders(new ResponseHeaderOverrides().withContentDisposition("attachment; filename*=UTF-8''\"A,B\"")
```

I'm using version `1.11.613` of the SDK with Apache `httpclient-4.5.9`.
Would this work for you?

**Comment by sithmein** [comment]
That doesn't work for me. Chrome the suggest a filename such as _9a76d6f6862206c05a7e_ while Firefox suggest _\_A,B\__ (replacing the quotes by underscores). In any case this is still violating the RFC because the comma is not encoded.

**Comment by debora-ito** [comment]
Ok, so I rerun some tests and encoding the filename prior to generating the presigned url worked for me, the same way you showed here:

 ```
request.withResponseHeaders(new ResponseHeaderOverrides().withContentDisposition("attachment; filename*=UTF-8''A%2CB"));
```

My presigned url looks something like this:
```
https://<s3_url>/A%2CB?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27A%252CB&...
```
and both Chrome and Firefox suggest **A,B** as filename.

**Comment by sithmein** [comment]
This may work, because the S3 object itself is named *A,B*. Can you try it with an object that is named differently?

**Comment by debora-ito** [comment]
Tried with a new object key named `objectName` and kept the `filename*=UTF-8''A%2CB` in the content-disposition, still works.

**Comment by sithmein** [comment]
Indeed. I double-checked my code and I was actually double-encoding the comma. First I replaced comma by %2C and in a second step I encoded all unallowed characters (because of Unicode characters) which then encoded %2C again. Sorry for the false alarm.
