### ISSUE TITLE
AwsHostNameUtils.parseRegion does not support VPC endpoint host structure

### ISSUE THREAD

**Issue by mignaulo** [aws/aws-sdk-java#2082]
We make use of the KCL (Kinesis Client Library - https://github.com/awslabs/amazon-kinesis-client/) which uses the Java SDK.

When passing in a Kinesis VPC endpoint URL as a override for the endpoint, we get the following error:
```
Aug 20 22:06:28 aw-dev-xx nodejs-xxx[29373]: WARNING: Received configuration for both region name as us-west-2, and Amazon Kinesis endpoint as https://vpce-xxxx-xxxxxx-us-west-2b.kinesis.us-west-2.vpce.amazonaws.com . Amazon Kinesis endpoint will overwrite region name.
Aug 20 22:06:29 aw-dev-xx nodejs-xxx[29373]: com.amazonaws.services.kinesis.model.AmazonKinesisException: Credential should be scoped to a valid region, not 'vpce'.  (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidSignatureException; Request ID: d99564bf-a0b7-bd62-xxxx-159ab6613814) 
```
I've been trying to track down this issue, and i believe it is caused by AwsHostNameUtils.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceClient.java#L296
setEndpoint here calls `AwsHostNameUtils.parseRegion(endpoint, getEndpointPrefix());` to determine the signing region. Ultimately, that code calls AwsHostNameUtils.parseStandardRegionName, which assumes the region can be found just before `.amazonaws.com`. Unfortunately, this is not correct for the VPC or AZ-specific VPC endpoints provided by AWS, which have a format like so `*.<service>.<region>.vpce.amazonaws.com`

Would it be reasonable to modify the code here to support this?

**Comment by debora-ito** [comment]
The `setEndpoint()` method is deprecated so we will not modify it, probably. Have you tried using [`AwsClientBuilder.setEndpointConfiguration()`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/client/builder/AwsClientBuilder.html#setEndpointConfiguration-com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration-) instead?

**Comment by mignaulo** [comment]
Thanks for the information! I will look into this.
