### ISSUE TITLE
ApiGatewayManagementApi not able to give correct error messages

### ISSUE THREAD

**Issue by Starofall** [aws/aws-sdk-java#2084]
I am using "aws-java-sdk-apigatewaymanagementapi" to send a message to a connected ApiGateway-WebSocket client. If the connectionId is valid, everything works as expected and the sdk works.

But if the connectionId is no longer valid a 410 status code is expected to show me that the client is no longer connected and that I can delete the connection from my database.

But here the SDK is not able to handle this usecase, as i get the following stacktrace:

```
[ERROR] Aug 22, 2019 11:26:12 AM com.amazonaws.http.JsonErrorResponseHandler unmarshallException
[ERROR] INFORMATION: Unable to unmarshall exception content
[ERROR] java.lang.NullPointerException
[ERROR]        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2745)
[ERROR]        at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:52)
[ERROR]        at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:108)
[ERROR]        at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:96)
[ERROR]        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:63)
[ERROR]        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
[ERROR]        at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53)
[ERROR]        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41)
[ERROR]        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26)
```

The reason then is:

```
com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonApiGatewayManagementApi; Status Code: 410; Error Code: null; Request ID: e315fd2b-c4be-11e9-b94b-b1bbbfbd075a)
```

Expected Behaviour: 

The SDK should not throw an unhandleable Exception (and spam stdout) but instead let me be able to handle this 410/"user-is-gone"-case.

Steps to reproduce:

Try to call wsClient.postToConnection(...) with an valid but expired connectionId

**Comment by debora-ito** [comment]
@Starofall The service team replied and said the operation is now sending the error code in the response. I'll go ahead and close this. 

Thank you for reaching out. Feel free to reopen if you have other question.
