### ISSUE TITLE
DynamoDB annotations, nested maps are not working

### ISSUE THREAD

**Issue by LGX9** [aws/aws-sdk-java#2085]
The sdk fails to insert Map<String, Object> types whereas the Object can be another map. Right now, I have to convert a json to Map<String, String> where the nested map becomes only a string and the value is also stored as "S" in dynamoDb and cannot be be subqueried anymore.

**Comment by LGX9** [comment]
So, you can use the _AttributeValue_ type instead of Map<String, Object> it seems and use _ItemUtils.toAttributeValue(map)_ to convert the Map<String, Object> map, but this is not written in the official documentation, only basic datatypes are listed, and I only found this by accident. Is this the correct way?
``` 
@DynamoDBAttribute(attributeName = "payload") 
public AttributeValue getPayload() {
   return payload;
}

**Comment by debora-ito** [comment]
Closing. Feel free to reopen if you have any other question.
