### ISSUE TITLE
Waiter Acceptors do not have RETRY state

### ISSUE THREAD

**Issue by kyle306** [aws/aws-sdk-java#2089]
When tried to use the DMS waiter to wait for replication task stopped, but I always get failure exception no matter calling run or runAsync. I expected the waiter polls if the replication task has stopped or not for a period of time.

After investigation, I find the reason is among the acceptors of waiter created by replicationTaskStopped() in AWSDataMigrationServiceWaiters, only IsStoppedMatcher has SUCCESS state and others all have FAILURE state.  This makes the waiter goes to failure immediately if the replication task is not stopped, like running.

The other waiters have similar issue.

Is this by design or Is a bug?

**Comment by debora-ito** [comment]
Can you send us a sample code showing how you're using the waiter?

**Comment by kyle306** [comment]
I used the waiter like this:
client.waiters().replicationTaskStopped().run(new WaiterParameters<>(createDescribeReplicationTasksRequest()));

client is the AWSDatabaseMigrationService. Don't worry about the createDescribeReplicationTasksRequest(), it creates the request with the filter name and the task arn and it works fine with my own created waiter.

The waiter client.waiters().replicationTaskStopped() creates is expected to poll for a period of time until timeout. But it throws failure exception while the task is running.

**Comment by debora-ito** [comment]
The `replicationTaskStopped` will poll the task status after a Stop operation is requested. After requesting a stop the task status will change to "stopping", and you can see that "stopping" is not a failure state in that particular waiter. That's why it considers the "running" state as a failure.

Similarly, the `replicationTaskReady` will poll after the task was created, `replicationTaskDeleted`will poll after a deletion was requested.

**Comment by kyle306** [comment]
In terms of waiter, after I start a replication task, if I want poll and wait until the task stops and do something, which waiter I should use? Any example code in DMS API?

**Comment by debora-ito** [comment]
The waiter you want to use will depend on the desired state you want your resource to be. Right now the only waiter available to poll a replication task status after a Start operation is `ReplicationTaskRunning`, which will poll the task until it enters into a Running state. 

Here's an example on how to use it:

```java 
Waiter dmsWaiter = dmsClient.waiters().replicationTaskRunning();

try{
    dmsWaiter.run(new WaiterParameters(describeReplication));
}
catch(WaiterUnrecoverableException e){
    //Explicit short circuit when the resource transitions into
    //an undesired state.
}
catch(WaiterTimedOutException e){
    //Failed to transition into desired state even after polling
}
catch (AWSDatabaseMigrationServiceException e){
    //Unexpected service exception
}
```
You can also use async waiters, take a look at this [Waiters in the AWS SDK for Java blog post](https://aws.amazon.com/blogs/developer/waiters-in-the-aws-sdk-for-java/).
