### ISSUE TITLE
Stuck while loading ServiceEndpoints

### ISSUE THREAD

**Issue by libetl** [aws/aws-sdk-java#209]
The RegionUtils class (com.amazonaws.regions.RegionUtils) gathers a Web URI as Eclipse is starting up, but my company's proxy does not bear that. Instead of doing a :
- GET http://aws-vs-toolkit.s3.amazonaws.com/ServiceEndPoints.xml
I have a
- HEAD http://aws-vs-toolkit.s3.amazonaws.com/ServiceEndPoints.xml
in my wireshark network traces. The HEAD operation stucks the connection and therefore prevents eclipse from starting. I have to do a kill and then remove completely the aws eclipse plugin to get things back to order. 
Is it possible to set a timeout on the regions loading ? And in a fallback case, load the local regions.xml file ?

Thanks !Cheers.

**Comment by hanshuo-aws** [comment]
The latest SDK no longer loads the region metadata from the remote location; it's now loaded from a local copy of the region xml file bundled inside the SDK.

**Comment by libetl** [comment]
Good news. Thank you.
