### ISSUE TITLE
High native heap pressure in DownloadS3ObjectCallable

### ISSUE THREAD

**Issue by bdonlan** [aws/aws-sdk-java#2090]
In https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/DownloadS3ObjectCallable.java#L69 , we allocate a new 2MB native byte buffer for each S3 request being issued. This puts a lot of pressure on the native heap.

Native byte buffers are allocated on the C heap, with a stub object on the Java heap. They do not directly provide pressure on the system GC and so a series of large allocations could result in running out of native memory. To help avoid this, the JVM has an internal limit to the amount of native-allocated memory; when exceeded, the Java runtime will trigger a _full_ GC, and then perform an exponentially backed off sleep loop until enough finalizers run to clean up the outstanding native buffers (see https://github.com/unofficial-openjdk/openjdk/blob/jdk8u/jdk8u/jdk/src/share/classes/java/nio/Bits.java#L666-L702 ).

This excessive GC activity can be quite expensive and, due to races in the above buffer limit logic, can actually result in OOMs with high allocation rates.

In this particular case, the native buffer is not actually necessary - we read into a byte array, move to a native buffer, then write to a file channel. We could instead use `ByteBuffer.wrap` to wrap the byte array and pass it directly to the file channel. This would put pressure only on the Java heap, which can clean the buffers using young generation GCs.

**Comment by debora-ito** [comment]
Hi @bdonlan, thank you for reaching out. We have this change in our backlog already, we just don't know when it will be prioritized since the team is actively working on delivering new features in V2.

Marking as a feature request.

**Comment by SalusaSecondus** [comment]
This appears to be fixed as of [v1.11.647](8bdbdb34dc2a1b174bd40a282b4a583611024a7b).  The [current implementation](https://github.com/aws/aws-sdk-java/blob/8bdbdb34dc2a1b174bd40a282b4a583611024a7b/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/DownloadS3ObjectCallable.java#L69) now calls `ByteBuffer.wrap()` rather than `ByteBuffer.allocateDirect()`.

Can we close this issue?

**Comment by debora-ito** [comment]
@SalusaSecondus Yes, thank you for the notification. Closing.
