### ISSUE TITLE
Cloudwatch logs are not immediately available for querying through AWS SDK or AWS Management Console -> insights after lambda execution

### ISSUE THREAD

**Issue by gunaphysics** [aws/aws-sdk-java#2091]
As part of test automation, we require to query CloudWatch after a lambda finishes its execution. No logs are returned for at least 60 seconds when we try querying cloudwatch log group using startQuery() method. 

aws-java-sdk-logs version :  1.11.608

```java    
public static List<String> getLogs(String awsRequestId, long startTime, long endTime) {
           AWSLogs LOGS_CLIENT = AWSLogsClientBuilder
            .standard()
            .withCredentials(AWS_CREDENTIALS_PROVIDER_CHAIN)
            .withRegion(Regions.US_WEST_2)
            .withClientConfiguration(config)
            .build();
 String logGroup = "LOG_GROUP_NAME";
        StartQueryRequest request = new StartQueryRequest().withLogGroupName(logGroup)
                .withQueryString("fields  @message\n" +
                        "| filter @requestId='" + awsRequestId + "'\n" +
                        "| sort @timestamp desc\n" +
                        "| limit 100")
                .withStartTime(startTime)
                .withEndTime(endTime);
        String queryId = LOGS_CLIENT.startQuery(request).getQueryId();
        sleep(3);
        List<List<ResultField>> results = LOGS_CLIENT.getQueryResults(
                new GetQueryResultsRequest()
                        .withQueryId(queryId)).getResults();
        List<String> logs = new ArrayList<>();
        results.forEach(resultField -> {
            logs.add(resultField.get(0).getValue());
        });
//        LOGS_CLIENT.stopQuery(new StopQueryRequest().withQueryId(queryId));
        return logs;
    }```

**Comment by varunnvs92** [comment]
Are the logs immediately available for query by the service? If not, this is a request for the service team. 
You can enable the [wire logs](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-logging.html) and verify if the data is send over wire by the server. 
If data is sent over wire but SDK is not properly un-marshalling to response, this is a bug in SDK and we will fix it.
If no data is sent over wire, then the issue is with service.

**Comment by gunaphysics** [comment]
I think this is a service issue as the same behavior is observed in Cloudwatch insights as well.  I created a case in the support center. Closing the issue here.
