### ISSUE TITLE
ResponseMetadataCache.add shows as a major contention point

### ISSUE THREAD

**Issue by maykov** [aws/aws-sdk-java#2095]
ResponseMetadataCache.add shows as a major contention point on my workload. Could you optimize the usage?

<img width="903" alt="Screen Shot 2019-09-11 at 10 51 57" src="https://user-images.githubusercontent.com/8107629/64722989-71b57600-d484-11e9-82cc-1b2925b3ce88.png">

**Comment by debora-ito** [comment]
Closing issue, feel free to reopen if you have more questions.
