### ISSUE TITLE
Not thread safe implementation of AmazonSimpleEmailServiceAsyncClient

### ISSUE THREAD

**Issue by aparamonov** [aws/aws-sdk-java#210]
1. executorService field in this class isn't final. So, if user uses instance of this class in multiple threads, executorService field may not be visible in other threads except the thread that constructed the instance. This field can be easily marked as final. Or at least please mark implementation as not thread safe.
2. There are other fields in this class and it's subclasses that may influence on thread safety.
3. All implemented methods with 'Async' postfix consume mutable objects like SendEmailRequest in method sendEmailAsync. Then the mutable object is been passing to another thread (via executor service). This thread may see mutable object in partial state because JMM can guarantee the visibility of object fields among the threads only if object is immutable or reading/writing to object fields are properly synchronized.

**Comment by david-at-aws** [comment]
Hey Alexey,

Yep, no reason that `executorService` couldn't be final. We'll make this change in an upcoming release.

Unfortunately, we can't make the clients *totally* immutable without breaking backwards compatibility. The clients **are** safe to share between threads as long as you treat them as immutable after initialization and establish a *happens-before* relationship between the initialization of the client and any use (which you generally need to do anyways):

> Now, having said all of this, if, after a thread constructs an immutable object (that is, an object that only contains final fields), you want to ensure that it is seen correctly by all of the other thread, you still typically need to use synchronization. There is no other way to ensure, for example, that the reference to the immutable object will be seen by the second thread. The guarantees the program gets from final fields should be carefully tempered with a deep and careful understanding of how concurrency is managed in your code.

Similarly for the actual async request methods - as long as you treat the mutable request objects as immutable after initialization, the ExecutorService contract guarantees that the thread that runs the request will see a fully-constructed object, and that you will see a fully-constructed response object if you call `Future.get()`:

> Memory consistency effects: Actions in a thread prior to the submission of a Runnable or Callable task to an ExecutorService *happen-before* any actions taken by that task, which in turn *happen-before* the result is retrieved via Future.get().

Immutable clients and request/result objects would definitely be interesting to look at if and when we ever do a v2 of the SDK, as they would certainly make this stuff easier to reason about.

**Comment by breedloj** [comment]
`executorService` is now final and since this issue is nearly 2 years old I'm going to go ahead and close it.  Feel free to re-open or create a new one if you have additional concerns.
