### ISSUE TITLE
EBS volumes mount on custom location EMR cluster

### ISSUE THREAD

**Issue by sumit-prajapati** [aws/aws-sdk-java#2102]
I'm trying to launch an EMR cluster with added EBS volumes to my core instances with custom device mount point, but I could not find any option in AWS::EMR::Cluster nor the AWS::EMR::InstanceGroupConfig. Is there any option to do this while lauching the cluster along with EBS volume to custom device mount point to something like /dev/sdf..

   ```
 EbsConfiguration ebsConfiguration = new EbsConfiguration().withEbsBlockDeviceConfigs(new EbsBlockDeviceConfig()
.withVolumeSpecification(new VolumeSpecification().withVolumeType("gp2").withSizeInGB(100)));

InstanceGroupConfig instanceGroup = new InstanceGroupConfig()
                .withInstanceCount(1)
                .withInstanceRole("MASTER")
                .withInstanceType("r3.xlarge")
                .withMarket("SPOT")
                .withEbsConfiguration(ebsConfiguration);
```

The java sdk used can be found on this link to launch the cluster (https://docs.aws.amazon.com/emr/latest/ManagementGuide/calling-emr-with-java-sdk.html )

EMR Version: 5.11.0

While we are able to launch the cluster the volume device is mounted on /dev/xvdb but we need to mount the device on /dev/sdf on cluster launch.

**Comment by debora-ito** [comment]
@sumit-prajapati I didn't find a way to specify a custom mount point, but I don't really have expertise to help out with EMR. For service specific questions we recommend asking on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=52) to get support from the EMR team, or post it on Stackoverflow, which I see you already did.

Closing this, feel free to reopen if you have any other question.
