### ISSUE TITLE
Step Function Builder is missing Map State

### ISSUE THREAD

**Issue by pgoranss** [aws/aws-sdk-java#2104]
The [Map State](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-map-state.html) is missing from the Step Function Builder:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-stepfunctions/src/main/java/com/amazonaws/services/stepfunctions/builder/StepFunctionBuilder.java

**Comment by debora-ito** [comment]
Thank you for reporting this @pgoranss. 

Marking as a feature request but we don't have a date when this will be prioritized, as the team is actively working on V2 new features. PRs are welcome, and +1s help us spot the most requested features.

**Comment by pgoranss** [comment]
@debora-ito PR submitted for this: https://github.com/aws/aws-sdk-java/pull/2113. Let me know if you need anything else.

**Comment by debora-ito** [comment]
@pgoranss We added a task in our backlog to review the PR, will let you know when it's prioritized.

**Comment by Stvad** [comment]
For people wondering about alternatives in the meantime - using AWS CDK can be an option https://docs.aws.amazon.com/cdk/api/latest/docs/aws-stepfunctions-readme.html

**Comment by debora-ito** [comment]
Map State is now available from version `1.11.702`. Thank you!
