### ISSUE TITLE
Generate presigned URLs with path-style addressing when the bucket has a "." character

### ISSUE THREAD

**Issue by danielcompton** [aws/aws-sdk-java#2105]
Amazon is planning to deprecate path-style addressing for S3, and strongly encourages the use of virtual-host based addressing. In [Amazon S3 Path Deprecation Plan – The Rest of the Story](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/), Jeff Barr said (emphasis mine):

> Programmatic Access – If your application accesses S3 using one of the AWS SDKs, you don’t need to do anything, other than ensuring that your SDK is current. _The SDKs already use virtual-hosted references to S3, except if the bucket name contains one or more “.” characters._

However, when I create a presigned URL for the bucket `bucket.com`, using the guide for [Generating a presigned Object URL Using the AWS SDK for Java](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLJavaSDK.html), the SDK creates the URL:

```
https://bucket.com.s3.ap-southeast-2.amazonaws.com/test-key?X-Amz-Algorithm=AWS4-HMAC-SHA256<...>
```

This URL causes certificate errors, as S3's wildcard certificate `*.s3-ap-southeast-2.amazonaws.com` doesn't cover the extra subdomain of `bucket` in `bucket.com.s3.ap-southeast-2.amazonaws.com`.

It would be good if the SDK detected bucket names with `.` characters, and generated a path-style presigned URL.

Relates to #628

**Comment by spfink** [comment]
This is an interesting one. I know that there are customers either disabling SSL or using a custom hostname verifier for these cases. Changing to path-style could be a breaking change for them as it would change their endpoint out underneath them.

I'll have another conversation with the team on this one. We always strive not to break customers but I can understand how this is going to become only more important as S3 officially moves towards deprecation.

**Comment by ptanov** [comment]
As a workaround you could use code snipped mentioned here: <https://github.com/aws/aws-sdk-java-v2/issues/4958#issuecomment-1964402258>

**Comment by debora-ito** [comment]
@danielcompton we don't have plans to makes this auto detection change in v1.

We are closing stale v1 issues before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so if this issue still persists in v2 please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo. As @ptanov mentioned, you can use the `pathStyleAccessEnabled` as a workaround.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
