### ISSUE TITLE
Async ArchiveTransferManager 

### ISSUE THREAD

**Issue by haridarshan** [aws/aws-sdk-java#2107]
I'm trying to download archive from Glacier vault using AmazonGlacierAsyncClient but sdk doesn't have Async ArchiveTransferManager. Using ArchiveTransferManager makes the downloading process sync instead of async. 

Is there any possibility to have Async ArchiveTransferManager available in the sdk

**Comment by debora-ito** [comment]
Hi @haridarshan, as the team is focused in releasing new features in the V2 version of the SDK, your request is more likely to be considered for V2 so I opened an issue in your behalf: https://github.com/aws/aws-sdk-java-v2/issues/1442. 

Thank you for reaching out to us. Feel free to reopen if you have further questions.
