### ISSUE TITLE
aws-sdk-java 1.11.646 incomplete publish to maven central

### ISSUE THREAD

**Issue by dpfeiffer** [aws/aws-sdk-java#2114]
I just figured out that https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-sqs/1.11.646/aws-java-sdk-sqs-1.11.646.pom return a 404 when trying to resolve the dependencies.

I could also verify this behavior for:
* https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-pom/1.11.646/aws-java-sdk-pom-1.11.646.pom

**Comment by debora-ito** [comment]
@dpfeiffer There was a change in our publishing process, and some versions got an extra delay in their releases, version `1.11.646` included. Everything should be back normal now.

I'll go ahead and close this, but feel free to reopen if you continue to experience the issue.
