### ISSUE TITLE
RegionUtils.getRegionsForService(AmazonMacie.ENDPOINT_PREFIX) returns empty list

### ISSUE THREAD

**Issue by shira-bendor-exa** [aws/aws-sdk-java#2115]
SDK version: 1.11.603
I expect it to return a list of size 2: us-east-1 and us-west-2 but it returns empty.

Thanks

**Comment by debora-ito** [comment]
@shira-bendor thank you for reporting this. I'll contact the service team and ask for an update.

**Comment by shira-bendor** [comment]
Hi,
Any idea when it will be fixed?

**Comment by debora-ito** [comment]
AmazonMacie regions are now available through `RegionUtils.getRegionsForService()` in SDK version `1.11.783`.
