### ISSUE TITLE
AwsHostNameUtils.parseRegionName fails to parse ES hostname

### ISSUE THREAD

**Issue by cykl** [aws/aws-sdk-java#2116]
I use AWS4Signer to sign some HTTP requests issued to ElasticSearch. I had like to not have to invoke `signer.setRegionName()` and let the SDK extract the region from the hostname. However, `parseRegionName` fails to extract the region and return the service instead, ie. `es`.

It seems that most services follow a <service.region.amazonaws.com> convention while ES use <region.service.amazonaws.com>. Would it be possible to add a new serviceHint for ES?

This limitation seems also present in aws-sdk-java-v2.

**Comment by dagnir** [comment]
Hi @cykl can you clarify what you mean by 

> It seems that most services follow a <service.region.amazonaws.com> convention while ES use <region.service.amazonaws.com>. Would it be possible to add a new serviceHint for ES?

The ElasticSearch endpoints follow the standard `{service}.{region}.amazonaws.com` pattern: https://docs.aws.amazon.com/general/latest/gr/rande.html#elasticsearch-service-regions

**Comment by cykl** [comment]
Sure. While elasticsearch service endpoints do follow the usual convention, elasticsearch *domain* endpoints don't. They use `{domain}-{region}-es.amazonaws.com`. Signing HTTP requests issued to an ES cluster seems like a pretty common use case as it is the only way to implement an IAM based access policy. It would be nice if SDK could infer the region from domain endpoints like it does for AWS service endpoints.

Is that clearer?

**Comment by dagnir** [comment]
@cykl I see. The scope of `AwsHostNameUtils` is really just to get the region from service endpoints. For something like this, where the request is being sent to the data plane for ES, I don't think it fits there, but I think a SES-specific utility would be fine. Would you like to send a pull request?

**Comment by cykl** [comment]
What would be the best place? Likely not in aws-java-sdk-ses as it is not needed for such use case. https://github.com/awslabs/aws-request-signing-apache-interceptor would be a good fit but is not released. It could be a static function somewhere and user will be required to call something like `signer.setRegionName( getDomainRegion( url ) )` which is not a good DX. Or AWS4Signer could be subclassed / wrapped in a builder.
