### ISSUE TITLE
Drop Dependency on Jackson Databind because of multiple CVEs

### ISSUE THREAD

**Issue by marcomorain** [aws/aws-sdk-java#2120]
The `aws-sdk-java` [uses Jackson Databind](https://github.com/aws/aws-sdk-java/blob/e04c4ac666414a2843385c6d0a52fd57f9c9db52/pom.xml#L240) to serialize between JSON and Java objects.

Jackson Databind has an [unusual approach to security](https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062), with [18 CVEs in 2019 so far](https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html). Jackson Databind can operate in a mode where it will deserialize JSON into Objects from arbitrary Java classes. This allows an attacker to essentially call the constructor of any Java class on the classpath. Their approach to these is to have a list of classes that are blocked from serialization, [which is manually updated as CVEs are discovered](https://github.com/FasterXML/jackson-databind/commit/328a0f833daf6baa443ac3b37c818a0204714b0b).

Our company does not use Jackson Databind directly in any of our services, but it is pulled in as a transitive dependency by `aws-sdk-java`. Each time Jackson Databind has a CVE, we are forced to bump the dependency in all of our services that use the `aws-java-sdk`. I know that our company is not the only one in this situation.

Can you remove the dependency on Jackson Databind and replace it with a serialization library that is secure by default please?

**Comment by debora-ito** [comment]
Duplicate of #2096. 

@marcomorain Thank you for the detailed report, and we understand the pain. As explained in #2096, SDK V1 currently supports Java 6 but versions newer than jackson-databind 2.6.x require at least Java 7. We recently announced a [deprecation plan for Java 6](https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-will-no-longer-support-java-6/) and one of its motivating factors was the Jackson dependency. 

We are tracking the issue in #2096 so I'll go ahead and close this one. Please feel free to reach out if you have more issues or comments.
