### ISSUE TITLE
api-gateway client not able to unmarshall response

### ISSUE THREAD

**Issue by tomjez** [aws/aws-sdk-java#2123]
We encounter the following problem when trying to update a domain name using the api-gateway client from a Kotlin Gradle script:
```
val apiGateway = AmazonApiGatewayClientBuilder.standard()
            .withCredentials(awsCredentialsProvider)
            .withRegion(awsRegion)
            .build()
apiGateway.updateDomainName(
             UpdateDomainNameRequest()
                       .withDomainName(domainName)
                       .withPatchOperations(
                               PatchOperation()
                                       .withOp("replace")
                                       .withPath("/securityPolicy")
                                       .withValue("TLS_1_2")
                                )
```
The Patch operation is executed as expected, but we get a RuntimeException with message `Unable to unmarshall response (We expected a VALUE token but got: END_OBJECT). Response Code: 200, Response Text: OK`
We can workaround this by catching the exception because we do not need any information from the reponse, but there may be situations where this is not the case.

Package used: com.amazonaws:aws-java-sdk-api-gateway:1.11.653
Gradle version: 5.6.2

**Comment by debora-ito** [comment]
@tomjez Can you provide a [wire log](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) of the response from ApiGateway? Please make sure there is no sensitive data in the logs.

I'm looking for additional information on the response from the service. It's weird you are seeing a status 200 but the SDK is unable to unmarshall.

**Comment by debora-ito** [comment]
Closing due to lack of response, feel free to reopen if the problem persists.

**Comment by adityakakliya1** [comment]
@tomjez Did you find the solution? I am also facing the same issue.
