### ISSUE TITLE
How can I condigure the aws-java-sdk-iot to use ATS endpoints

### ISSUE THREAD

**Issue by mrczpt** [aws/aws-sdk-java#2129]
I need to configure the aws-java-sdk-iot SDK to use ATS endpoint instead of the default one that is using Symantec certificates which are untrusted, reading the doc of the SDK I cant find the specific palce this need to be changed

**Comment by spfink** [comment]
Which IoT service are you using?

You can see an example of what we had to do recently for this here:

https://github.com/aws/aws-sdk-java-v2/pull/1475

**Comment by mrczpt** [comment]
The AWSIotData using the AWSIotDataClientBuilder

**Comment by debora-ito** [comment]
@mrczpt Let us know if the example provided by @spfink helps.

**Comment by mrczpt** [comment]
I actually ended up upgrading the version of the SDK from 1.11.61 to latest then I was able to use tell the client what endpoin to use


` return AWSIotDataClientBuilder.standard()
                .withCredentials(new EnvironmentVariableCredentialsProvider())
                .withClientConfiguration(new ClientConfiguration())
                .withEndpointConfiguration(new EndpointConfiguration(<path>, "us-west-2"))
                .build();`
