### ISSUE TITLE
Does java SDK support sync?

### ISSUE THREAD

**Issue by mathanpt** [aws/aws-sdk-java#2131]
Is there any support for [sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) in java SDK?

**Comment by dagnir** [comment]
Hi @mathanpt. This is not supported in the Java SDK's TransferManager. We are working writing the next version of TransferManager in [V2](https://github.com/aws/aws-sdk-java-v2): https://github.com/aws/aws-sdk-java-v2/issues/37. I'll go ahead and close this and link this in that issue.
