### ISSUE TITLE
AP_NORTHEAST_3 not listed in Regions enum

### ISSUE THREAD

**Issue by daveagill** [aws/aws-sdk-java#2132]
The ap-northeast-3 region is not listed in the Regions enum:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java

The region does not seem to be generally available but as far as I know it does exist and is listed in various pages of AWS documentation.

**Comment by dagnir** [comment]
Hey @daveagill, The SDKs intentionally omit `ap-northeast-3` from the enum because, as you said, because the region requires getting customers to request access.

**Comment by daveagill** [comment]
Hi @dagnir,

Couldn't the same be said about (e.g.) the GovCloud regions or the China ones? They are not available to everybody but they are still listed in the enum - Is there something that makes ap-northeast-3 stand out compared to those? If not, I would still suggest it be added.

From a different angle: Why shouldn't the Regions enum contain *all* regions, regardless of availability?

It seems to hurt the utility having that enum in the SDK if there are genuine regions that it is lacking. E.g. As a type-safe way of representing a region identifier it no good because fromName will throw if "ap-northeast-3" is passed to it. Or as a way of enumerating the full set of AWS regions.

If I haven't convinced you of the value of adding ap-northeast-3 (and any other such regions) then perhaps it would make sense to document (in javadoc) that the enum is not a full list of regions so that others don't fall into (mis)using it for the use-cases I described above?

In that event I think the solution for me will be to create my own such enum and move away from the one included in the SDK, just a minor inconvenience but some Javadoc would've got me there quicker 👍

**Comment by hughesjj** [comment]
This needs to be re-opened.  Other opt-in regions are enumerated in the regions list and I believe Osaka-local is being made into a "proper" region.
