### ISSUE TITLE
Could not initialize class com.amazonaws.services.s3.AmazonS3ClientBuilder

### ISSUE THREAD

**Issue by sanabraham** [aws/aws-sdk-java#2140]
Error : com.amazonaws.util.StringUtils.trim(Ljava/lang/String;)Ljava/lang/String

I am getting this error while using 
AmazonS3 amazonS3Client() method. How can we fix this issue?

Tried the things mentioned in:  https://github.com/spring-cloud/spring-cloud-aws/issues/353
Please note, my project is a **Maven Project**.

Thanks for your help.

**Comment by KaibaLopez** [comment]
Hi @sanabraham, sorry, I'm not clear on what you're asking here....
Are you trying to do anything specific? If not, you could take a look at our [sample code documentation](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/java). And get a better idea on how to initialize s3Clients.

**Comment by sanabraham** [comment]
@KaibaLopez , Thanks for checking this.
We have solved the issue by adding following dependency:

<dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk</artifactId>
                <version>1.11.327</version>
            </dependency>

            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-s3</artifactId>
                <version>1.11.602</version>
            </dependency>

            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.11.665</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
