### ISSUE TITLE
aws-java-sdk-rdsdata does not replace parameters when using ArrayValue as SqlParameter

### ISSUE THREAD

**Issue by debae** [aws/aws-sdk-java#2141]
We are using the RDS Data API inside a Lambda Function. In our code we would like to update serveral records at once by using the IN clause.

Our code looks like this : 

```

ExecuteStatementRequest executeStatementRequest = new ExecuteStatementRequest()
                .withDatabase(LambdaEnvironment.getProductDataDatabase())
                .withResourceArn(LambdaEnvironment.getProductDataRdsReference())
                .withSecretArn(LambdaEnvironment.getRussianProductDataClusterSecret())
                .withSql("UPDATE SECURITY_CODE SET carton = :carton WHERE serialNumber IN ( :serialNumbers );")
                .withParameters(new SqlParameter[]{
                new SqlParameter().withName("carton").withValue(SqlParameterUtil.createSqlParameterField(carton.getCartonNumber())),
                new SqlParameter().withName("serialNumbers").withValue(new Field().withArrayValue(new ArrayValue().withStringValues(serialNumbers)))})
                .withTransactionId(transactionId);

```

But when executing this it looks like the parameter we want to replace with an ArrayValue SqlParameter is not getting replaced. The error is : 

`
{
    "message": "Unspecified failure : Parameter \"serialNumbers\" has value with no field set (Service: AWSRDSData; Status Code: 400; Error Code: BadRequestException; Request ID: f9592596-a8b8-425d-b0a2-48a9342e040d)"
}
`

We are using version 1.11.666 of the aws java sdk.

**Comment by debora-ito** [comment]
Hi @debae, according to RDS documentation, Array Parameters are not supported in the ExecuteStatement API:

https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_ExecuteStatement.html
