### ISSUE TITLE
RDSData Field.java class throwing NullPointerException when calling Field.isNull() or Field.getIsNull()

### ISSUE THREAD

**Issue by jzinkovich** [aws/aws-sdk-java#2142]
Before I attempt to get a value from a field I am calling Field.isNull() or Field.getIsNull() and when I call either of this methods it is throwing a NullPointerException.  

class: com.amazonaws.services.rdsdata.model.Field;

My exact call where I am finding this happen is below.

```
ExecuteStatementRequest request = executeStatementRequest(query, transactionId, buildParameters(params));
  ExecuteStatementResult result = rdsData.executeStatement(request);
 if (result != null && !result.getRecords().isEmpty()) {
         List<Field> row = result.getRecords().get(0);
         if(row.get(0).isNull()) {
           return null;
        }
}

```

The isNull variable is an object type Boolean within the Field class, since it is an object and not a primitive boolean type I suspect what is happening is the framework is never setting this value true or false therefore it is remaining null when the client users try to use this method.  

Is there another way to check that field value is returned besides calling isNull() method?  I need to be able to check a value was returned before casting it into something specific.

**Comment by debora-ito** [comment]
Hi @jzinkovich, not sure if I understand the question, is this what you're looking for?

```
if(row.get(0) == null) {
   return null;
}
```

Anyway, this is not a question regarding issues or feature requests for the AWS SDK for Java so I'll go ahead and close this. I'd suggest asking these questions on StackOverflow.
