### ISSUE TITLE
The AWS access key id you provided does not exist in our records.

### ISSUE THREAD

**Issue by sibasish0247** [aws/aws-sdk-java#2143]
Hi,
I am trying to upload a file to s3 from frontend uploader. I am sending this payload from my java backend application 
{
    "acl": "public-read",
    "bucket": "abc",
    "expires": "2019-11-07T15:31:19.989Z",
    "key": "abc/abc/abc/AGREEMENT.pdf",
    "policy": "abcd",
    "signature": "abcd",
    "region": "ap-southeast-1",
    "awsaccesskeyid": "ACCESSKEYHERE",
    "Content-Type": "application/octet-stream"
}
to my frontend application using which it uploads to s3 bucket. I am generating the access key id using InstanceProfileCredentialsProvider function in aws-sdk-java which uses the credentials of my EC2 instance metadata. The IAM role of my EC2 instance has AmazonFullS3Access. But while uploading I am getting the 'The AWS access key id does not exist in our records'. Please help here. Earlier I was using AWS access key of my IAM user which worked well. But when I tried to use IAM role credentials of my EC2 instance, this error is being thrown.

**Comment by debora-ito** [comment]
@sibasish0247 I'm so sorry that this was ignored for so long. Are you still experiencing the issue? If so reply with a comment and I'll take a look.
