### ISSUE TITLE
Lambda Execution intermittent Status Code: 403 error from ECS task

### ISSUE THREAD

**Issue by patanjalic** [aws/aws-sdk-java#2149]
we are facing intermittent issues while triggering lambda from ECS task.

ECS task is a springboot based java application, we are triggering a lambda function in the task using aws java sdk.
Task is triggered every 5 minutes, so its run 288 times in a day and we are seeing issue occurring randomly few times in a day.
IAM role is attached to the task, it has required permissions to trigger the lambda.
Stack trace

com.amazonaws.services.lambda.model.AWSLambdaException: null (Service: AWSLambda; Status Code: 403; Error Code: null; Request ID: null)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
 com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
 com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
 com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3255)
 com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3222)
com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3211)
com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1842)
 com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1813)

Java code triggering lambda.

ClientConfiguration clientConfig = new ClientConfiguration();
			clientConfig.setMaxErrorRetry(maxRetry);
			clientConfig.setSocketTimeout(socketTimeout);
			clientConfig.setConnectionTimeout(connectionTimeout);
			AWSLambda client = AWSLambdaAsyncClient.builder().withClientConfiguration(clientConfig).withRegion(region).build();

			InvokeRequest asyncRequest = new InvokeRequest().withInvocationType(InvocationType.Event).withFunctionName(lambdaFunction);
client.invoke(asyncRequest);

**Comment by debora-ito** [comment]
@patanjalic I'm so so sorry that this issue did not get any attention in such a long time. 
Are you still seeing the issue? If so please reply with a comment and I'll investigate.
