### ISSUE TITLE
How could I disable the chunk signing when putting an object?

### ISSUE THREAD

**Issue by skyler1grey** [aws/aws-sdk-java#2150]
I found my body of putobject HTTP request contains two signatures like` 0;chunk-signature=b6c6ea8a5354eaf15b3cb7646744f4275b71ea724fed81ceb9323e279d449df9`, but I don't want these two signatures to appear in my request body because our local file system which is compatible with S3 interface does not support the signature features.

Thanks a lot.

**Comment by skyler1grey** [comment]
Besides, I tried this code S3ClientOptions ```
s3ClientOptions = S3ClientOptions.builder().disableChunkedEncoding().setPayloadSigningEnabled(false).build();
Client.setS3ClientOptions(s3ClientOptions);
```
But it didn't work.

**Comment by KaibaLopez** [comment]
Hi @skyler1grey, 
can you try 
`withChunkedEncodingDisabled(true)` instead of `disableChunkedEncoding()` and let me know if that solved the issue?

**Comment by skyler1grey** [comment]
@KaibaLopez 
Thanks a lot for your kind reply. However, there is no `withChunkedEncodingDisabled(true)` option, and I found that after adding `clientConfiguration.setSignerOverride("NoOpSignerType");`, there will be no signature in the chunk.

Therefore, if anyone wants to disable the chunk signing, you could use the codes below
```
        S3ClientOptions s3ClientOptions = S3ClientOptions.builder().disableChunkedEncoding().setPayloadSigningEnabled(false).build();
        clientConfiguration.setSignerOverride("NoOpSignerType");
        S3Manager.getInstance().getClient().setS3ClientOptions(s3ClientOptions);
```
