### ISSUE TITLE
Problem with connecting to aws-java-sdk-iotjobsdataplane from device.

### ISSUE THREAD

**Issue by StanislavSerdiuk** [aws/aws-sdk-java#2152]
Hello!
I tried to update job execution status, when i submited job for device and handled it using mqqt topic:

> $aws/things/MyThing/jobs/notify-next

When i got a message into topic i executed this function:
```java
@Override
public void onMessage(AWSIotMessage message) {
	StartNextPendingJobExecutionResult result = null;
	try {
		result = awsIoTJobsDataPlane.startNextPendingJobExecution(new StartNextPendingJobExecutionRequest().withThingName(THING_NAME));
	} catch (Exception e) {
		e.printStackTrace();
	}
}
```

And as result i got exeption:
`com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain:... `

Client was initialized as:
```java
AWSIoTJobsDataPlaneClientBuilder
	.standard()
	.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(address, region))
	.build();
```

I guess that I have to put evironments, system propertry or other way to get access key id and acccess secret key.

But I have cirtificate and private key which was registered on AWS IoT. I can to publish on MQTT topics and subscribe one.

I want to initilialize `AWSIoTJobsDataPlaneClient` with that cirtificate and to execute command for describing and updating job executions. Is this possible? Or There is only way to do this using MQTT and sending to  appropriate topics messages:
```
$aws/things/thingName/jobs/jobId/get
$aws/things/thingName/jobs/jobId/update
```

**Comment by KaibaLopez** [comment]
Hi @StanislavSerdiuk, if I understand correctly what you're trying to do...
The quick answer is yes, it should be possible to initialize the `AWSIoTJobsDataPlaneClient` with a specific set of credentials. 
```
BasicAWSCredentials awsCreds = new BasicAWSCredentials("access_key_id", "secret_key_id");
AWSIoTJobsDataPlaneClientBuilder
	.standard()
        ..withCredentials(new AWSStaticCredentialsProvider(awsCreds))
	.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(address, region))
	.build();
```
let me know if this helps or if I'm missing something on your question.

**Comment by StanislavSerdiuk** [comment]
Hi @KaibaLopez. Thank you but this is not what  i need for. I can not use access_key_id and acces_secret_id by reason of security.
I have a device that  connects to AWS IoT through MQTT.
I use MQTT (over TLS 1.2) with X.509 certificate-based mutual authentication and my device can subscirbe and publish message to MQTT.

Also, my device have to execute AWS IoT Jobs. To simplify invoking StartNextPendingJobExecution, UpdateJobExecution API I try to use **aws-java-sdk-iotjobsdataplane**.

But for initializing **AWSIoTJobsDataPlane** i must provide credentials. As i mentioned earler i can not do this. 

Can i use X.509 certificate-based mutual authentication for  **AWSIoTJobsDataPlane** to do that functions:
- `aWSIoTJobsDataPlane.startNextPendingJobExecution(new StartNextPendingJobExecutionRequest())`
- `aWSIoTJobsDataPlane.updateJobExecution(new UpdateJobExecutionRequest())`

Is it possible?

**Comment by bmaizels** [comment]
Hi @StanislavSerdiuk , unfortunately the SDK does not support MQTT to the best of my knowledge. The IoT team have their own SDK (https://github.com/aws/aws-iot-device-sdk-java) that may be able to support your use-case, but you should probably raise the issue there. I can confirm that using this AWS SDK will require you to provide AWS credentials in some form or another.
