### ISSUE TITLE
Getting warning: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. While using TransferManager for downloading a file from presigned Url.

### ISSUE THREAD

**Issue by nikhilhanda** [aws/aws-sdk-java#2153]
While trying to fetch a large video file of 1.5 GB. I am continuously getting a warning:

Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.

I am using the following piece of code for downloading the file which is present in the issue:
https://github.com/aws/aws-sdk-java/issues/2088

**Comment by KaibaLopez** [comment]
Hi @nikhilhanda ,
Sorry, looking into this but will take a bit to have your answer.

**Comment by debora-ito** [comment]
@nikhilhanda I'm so sorry that this issue did not get any attention in a long time. Are you still experiencing the issue? If so please reply with a comment and I'll investigate.
