### ISSUE TITLE
What's the best way to explore regions

### ISSUE THREAD

**Issue by shira-bendor** [aws/aws-sdk-java#2154]
I'm using the java SDK version 1.11.603.
My goal is to programmatically understand what services are used in what regions.
When I iterate over all "Regions"  enum I get exceptions when I try to query regions that I'm not allowed to (like GOV), mostly "UnrecognizedClientException". 
I found the ec2 "describeRegions" function but is that supposed to work for all services?  so if I get back a list of regions from that function, can I assume I can query everything in these regions?
What is the recommended way to go?

**Comment by KaibaLopez** [comment]
I may be missing something but, here is a [table](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/?p=ugi&l=na) on what services are available on which regions.
Would that be what you're looking for?

**Comment by shira-bendor** [comment]
Well my goal is something like this: 
I want to programatically discover all trails in all regions where I have trails. (this is just example in reality I'm querying more services).
So I want to iterate over all regions and for each of them get a client and do "describeTrails".
If I iterate over all regions in the "Regions" enum I get exceptions in "forbidden" regions.
So I am looking for a way to know what are my "allowed" regions to query.
Does this make sense?

**Comment by KaibaLopez** [comment]
Ok so, if you see the file [endpoint.json](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json)
You'll find, per service, which regions the services are available on... I don't think the sdk currently provides a quick call for all of them, the way ec2 describe regions does, but you could potentially use that json file as a reference, and build your own function.

**Comment by shira-bendor** [comment]
Sorry but that still doesn't help me.
For example it says that guard duty is supported on us gov cloud.... But I'm not permitted to query that region... Does this make sense?
________________________________

**Comment by KaibaLopez** [comment]
yea it makes sense, and the describeRegions from ec2 should give you that, (regions to which you have service access to) but only for ec2... the rest of the services don't have such a function, so you'd have to make your own. 
I'd recommend taking at how ec2 does it, but other than that I'm afraid I can't really help.
