### ISSUE TITLE
Provide DynamoDBLoadExpression

### ISSUE THREAD

**Issue by joumenharzli** [aws/aws-sdk-java#2163]
In IDynamoDBMapper there is not method to pass a DynamoDBLoadExpression to specify the projection expression.

**Comment by KaibaLopez** [comment]
Hi @joumenharzli, can you be a bit more specific on what you're trying to do and what would you want this method to provide?

**Comment by avanathan** [comment]
@joumenharzli Do you mean this? https://github.com/aws/aws-sdk-java/issues/2165

**Comment by joumenharzli** [comment]
@KaibaLopez 
in the interface IDynamoDBMapper the method load wraps the operation GetItem  https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html.

Query and scan have methods where we can pass multiple parameters like projection expression using the object DynamoDBQueryExpression or DynamoDBScanExpression. 
Unfortunately it's not the case with load operation. there is not method with a signature that haves DynamoDBLoadExpression so we cannot not use some features in GetItem like Projection Expression

@avanathan 
yes kind of

**Comment by joumenharzli** [comment]
Related to https://github.com/aws/aws-sdk-java/issues/527
