### ISSUE TITLE
DynamoDBMapper "load" and "batchLoad" methods should support ProjectionExpressions

### ISSUE THREAD

**Issue by avanathan** [aws/aws-sdk-java#2165]
Support `ProjectionExpression` in `DynamoDBMapper.load` & `DynamoDBMapper.batchLoad`. [Issue #527](https://github.com/aws/aws-sdk-java/issues/527) was closed earlier saying this will be considered for v2. Please add this feature in v2. Thanks!

**Comment by debora-ito** [comment]
@avanathan we are tracking V2 DynamoDB Mapper enhancements in https://github.com/aws/aws-sdk-java-v2/issues/35 to keep all requests in one place. Issue #527 is already listed over there, so I'll go ahead and close this one.
