### ISSUE TITLE
CompleteMultipartUpload is not retried on throttling

### ISSUE THREAD

**Issue by sap1ens** [aws/aws-sdk-java#2168]
CompleteMultipartUpload doesn't use provided retry policy, instead it relies on internal `CompleteMultipartUploadRetryCondition` https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L465-L466

This condition uses a static predicate that only checks for a single error: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/CompleteMultipartUploadRetryablePredicate.java#L48-L49:
- error code: `InternalError`
- error message should contain `Please try again.`

In case of throttling, the error code is actually `SlowDown` and the error message is `Please reduce your request rate.`, which means the predicate is always false and the `CompleteMultipartUpload` is never retried on throttling. 

Documention states it's safe to retry: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html 

**Potential solutions**:
- Extend `CompleteMultipartUploadRetryablePredicate` to support more errors
- Use a configured retry policy instead of `CompleteMultipartUploadRetryCondition`

**Comment by KaibaLopez** [comment]
Hi @sap1ens , 
Sounds reasonable enough, we'll take a look at it.
And since you already seem to have a solution in mind, could I ask you to make a PR with these changes? It could make the process faster.

**Comment by sap1ens** [comment]
@KaibaLopez definitely, I can provide a PR. 

I'm thinking about simply using a configured retry policy instead of `CompleteMultipartUploadRetryCondition`, but I'm not sure what's the motivation about an adhoc retry handling for `CompleteMultipartUpload`s in the first place (git blame doesn't help much). 

Is it a safe thing to do?

**Comment by sap1ens** [comment]
Added a PR: https://github.com/aws/aws-sdk-java/pull/2174

However, I'm still not sure if it's fully safe to remove `CompleteMultipartUploadRetryCondition`.

**Comment by spfink** [comment]
@sap1ens, what leads you to believe that throttling exceptions are not getting retried. The CompleteMultipartUploadRetryCondition wraps the response from the SDK core and will retry a 200 response that has an error in the body.

However, the default retry policy, or whichever is set in ClientConfiguration, is still executed within the SDK core. I ran some quick tests where I mocked a "SlowDown" response from the service and it was getting retried in core.

**Comment by sap1ens** [comment]
@spfink `CompleteMultipartUploadRetryCondition` [uses](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/CompleteMultipartUploadRetryCondition.java#L54) `CompleteMultipartUploadRetryablePredicate` class, which only handles `InternalError` error code and `Please try again.` error message, [look here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/CompleteMultipartUploadRetryablePredicate.java#L48-L60).

[I can see](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/CompleteMultipartUploadRetryCondition.java#L45) that `CompleteMultipartUploadRetryCondition` accepts any kind of predicate for testing purposes, perhaps in your test a predicate that's passed is different from `CompleteMultipartUploadRetryablePredicate`?

Also, S3 throttling returns 503 HTTP code, not 200.

**Comment by spfink** [comment]
I can see that but I'm not aware of any case where we are overriding the RetryPolicy though. The CompleteMultipartUploadRetryCondition wraps the response of completeMultipartUpload:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3487

This is at the service client layer to handle the edge case of S3 returning an error on a 200 response.

In all cases, retrying is handled in the core. The AmazonHttpClient class will look at the configured RetryPolicy to determine if a retry should happen. This is before the response is unmarshalled. It's possible that a request could be retried 3 times in the core, end up still returning an error up the stack, which would then be evaluated against the CompleteMultipartUploadRetryCondition.

**Comment by sap1ens** [comment]
> In all cases, retrying is handled in the core (cases like this are additive at the client layer).

Is this something generic? Could you send me the link to the place in the SDK where it happens?

> I can see that but I'm not aware of any case where we are overriding the RetryPolicy though.

RetryPolicy is simply ignored inside the `shouldRetryCompleteMultipartUpload` method: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3507 there are a few checks above that line, but the actual `shouldRetry` call does not use RetryPolicy. This is what I addressed in the PR: https://github.com/aws/aws-sdk-java/pull/2174/files#diff-f61dea68f2d3579550292bbf3808624eL3507-R3503

**Comment by debora-ito** [comment]
@sap1ens I'll go ahead and close this. Feel free to reopen if you have any other question.
