### ISSUE TITLE
Missing iso regions

### ISSUE THREAD

**Issue by grnadav** [aws/aws-sdk-java#2175]
https://github.com/aws/aws-sdk-java/blob/2a4dffaad3241880fd8e2681b9babbf0a048e958/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java#L27

The output of `RegionMetadataFactory.create().getRegionsForService(someService)` for e.g. someService = 'sqs', returns regions including -iso-* regions, e.g. `us-isob-east-1`.

Using that output to create a Regions, using `Regions.fromName()` yields an Exception.
They're not aligned.

**Comment by KaibaLopez** [comment]
Hi @grnadav,
Yes you're correct, getRegionsForService includes all regions the service is available in, including isolated or restricted regions, where fromName() only includes public ones, safe to use. So this is intended to be this way, to use these other regional endpoints you'd have to configure a custom resolver.
Hope this helps.

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have any other question.
