### ISSUE TITLE
Unprintable FieldDelimiter not serialized correctly when using SelectObjectContentRequest

### ISSUE THREAD

**Issue by sflanker** [aws/aws-sdk-java#2179]
If I set the the `fieldDelimiter` for a `CSVInput` to be an unprintable character (such as `"\u0001"` for example), the XML body of the request sent for a `SelectObjectContentRequest` includes the literal byte `0x01` instead of the corresponding XML entity: `&#01;`. This causes the server to respond with an error about an invalid UTF-8 character being encountered.

**Comment by KaibaLopez** [comment]
Hi @sflanker 
thanks for pointing this out, can you tell me what version of the sdk you're using and, if possible, also provide sample code to reproduce this?

**Comment by debora-ito** [comment]
@sflanker I'll go ahead and close this due to inactivity. Please feel free to reopen when you have a reproducible test case to provide.
