### ISSUE TITLE
Unable to use KVS PutMediaClient behind proxy

### ISSUE THREAD

**Issue by luclement** [aws/aws-sdk-java#2180]
Hi,

I need to call the `PutMedia` operation for Kinesis Video Streams behind a corporate proxy. Unfortunately, since the `AmazonKinesisVideoPutMediaClientBuilder` does not extend the `AwsClientBuilder` there is no way to set the `ClientConfiguration`.

Additionally, setting Java/system environment variables doesn't seem to work either because the PutMedia client uses Netty as transport and would, based on some research, require adding a proxy handler first in the channel pipeline.

https://github.com/aws/aws-sdk-java/blob/89fd27ef2abd407ad64245215f9e90dd40276651/aws-java-sdk-kinesisvideo/src/main/java/com/amazonaws/services/kinesisvideo/internal/netty/handler/PutMediaHandlerInitializer.java#L48

Let me know if I'm seeing this correctly. 

Thanks.

**Comment by luclement** [comment]
FYI I got this to work by adding an `HttpProxyHandler` as the first step in the `ChannelPipeline`

**Comment by debora-ito** [comment]
Echoing the comments in the PR, we'll not implement this feature in v1 as the team's efforts are focused in the SDK v2.
Tracking issue for the implementation of the equivalent functionality to AmazonKinesisVideoPutMedia client in v2: https://github.com/aws/aws-sdk-java-v2/issues/1330.
