### ISSUE TITLE
Continuation token of ListObjectsV2Result doesn't not provide consistent snapshot

### ISSUE THREAD

**Issue by unoexperto** [aws/aws-sdk-java#2182]
I noticed that continuation token of `ListObjectsV2Result` doesn't not provide consistent snapshot of list of files in S3 bucket.

What I mean by that is if we have list of files with names `2`, `3`, `4`, `5` and we're paginating through it with page size 1 we'll see file with name `6` even it was added after pagination has started.

Do I understand it correctly ? If yes what official options do I have in order to get consistent snapshot of list of objects ?

**Comment by debora-ito** [comment]
I don't think there is a way to do this kind of listing of a "snapshot". S3 API will list objects that are currently in the bucket (and note that PUT requests of new objects have read-after-write consistency, with one [caveat](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel)).

I'd recommend asking the AWS Developer Forums for this feature request, where you can reach out to the S3 team: https://forums.aws.amazon.com/forum.jspa?forumID=24
