### ISSUE TITLE
How to reuse POJO class provided by AWS SDK in response of lambda?

### ISSUE THREAD

**Issue by magicalne** [aws/aws-sdk-java#2189]
I hava a node.js lambda on aws. It's about search faces by img. 
So the response is 
```json
{
    "SearchedFaceBoundingBox": {
        "Width": 0.5287697911262512,
        "Height": 0.7847409248352051,
        "Left": 0.23819763958454132,
        "Top": 0.09850229322910309
    },
    "SearchedFaceConfidence": 99.99996185302734,
    "FaceMatches": [
        {
            "Similarity": 99.99999237060547,
            "Face": {
                "FaceId": "90974b37-xxxx-4942-8d9f-2dc60481ff9b",
                "BoundingBox": {
                    "Width": 0.5287700295448303,
                    "Height": 0.7847409844398499,
                    "Left": 0.23819799721240997,
                    "Top": 0.09850230067968369
                },
                "ImageId": "xxxx,
                "ExternalImageId": "1484015000",
                "Confidence": 100
            }
        }
    ],
    "FaceModelVersion": "4.0"
}
```
Then, I need to write a method which is used to call this lambda from java application.
It looks like:
```java
public interface RekoService {
    @LambdaFunction(functionName = "searchFace")
    SearchFacesByImageResult searchFace(SearchFaceRequest request);
}
```
Here, I'm trying to just reuse **com.amazonaws.services.rekognition.model.SearchFacesByImageResult**.

But it failed to fill the response to that POJO class. I'm wondering is that possible ?

I debugged into the source code without a clue. Please help.

**Comment by debora-ito** [comment]
@magicalne perhaps what you're looking for is Lambda API `invoke()` method -
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/AWSLambda.html#invoke-com.amazonaws.services.lambda.model.InvokeRequest-

This will invoke the Lambda function you have and return the function response in the payload. 

A SearchFacesByImageResult object is used when you call the Rekognition API `searchFacesByImage()` method directly in your Java code, but in your case this is being called in your Lambda function, I assume.

**Comment by magicalne** [comment]
@debora-ito thanks for the tip. Let me try with this method later.

**Comment by magicalne** [comment]
@debora-ito That way works. Thanks again.
