### ISSUE TITLE
Please add a CHANGELOG.txt

### ISSUE THREAD

**Issue by jxtps** [aws/aws-sdk-java#219]
The release notes published on e.g. http://aws.amazon.com/releasenotes/0739020877013903 are hard to find and track. 

Please add a standard CHANGELOG.txt distributed with the actual source. Thanks!

**Comment by dagnir** [comment]
Happy to report that the SDK now includes a [`CHANGELOG.md`](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md) file!
