### ISSUE TITLE
s3 pricing api return incorrect price

### ISSUE THREAD

**Issue by liewhite** [aws/aws-sdk-java#2190]
Code here
```
val client = AWSPricingClient
      .builder()
      .withRegion("us-east-1")
      .withCredentials(
        new AWSStaticCredentialsProvider(
          new BasicAWSCredentials(ak, sk)
        )
      )
      .build()
    client
      .getProducts(
        new GetProductsRequest().withMaxResults(100)
          .withServiceCode("AmazonS3")
          .withFilters(
            new Filter()
              .withField("location")
              .withType("TERM_MATCH")
              .withValue(Regions.fromName("us-west-2").getDescription),
          )
      )
```

And then i look for item which volumeType is "Glacier Deep Archive", the price is 0.021 per GB-Month. 

```
{
  "product" : {
    "attributes" : {
      "volumeType" : "Glacier Deep Archive",
      "storageClass" : "Staging",
      "servicecode" : "AmazonS3",
      "usagetype" : "USW2-TimedStorage-GDA-Staging",
      "locationType" : "AWS Region",
      "location" : "US West (Oregon)",
      "servicename" : "Amazon Simple Storage Service",
      "operation" : ""
    },
    "sku" : "AGJFYM869JVU9PK4"
  },
  "serviceCode" : "AmazonS3",
  "terms" : {
    "OnDemand" : {
      "AGJFYM869JVU9PK4.JRTCKXETXF" : {
        "priceDimensions" : {
          "AGJFYM869JVU9PK4.JRTCKXETXF.6YS6EN2CT7" : {
            "unit" : "GB-Mo",
            "endRange" : "Inf",
            "description" : "$0.021 per GB-Month of storage used in GlacierStagingStorage",
            "appliesTo" : [
            ],
            "rateCode" : "AGJFYM869JVU9PK4.JRTCKXETXF.6YS6EN2CT7",
            "beginRange" : "0",
            "pricePerUnit" : {
              "USD" : "0.0210000000"
            }
          }
        },
        "sku" : "AGJFYM869JVU9PK4",
        "effectiveDate" : "2019-11-01T00:00:00Z",
        "offerTermCode" : "JRTCKXETXF",
        "termAttributes" : {
          
        }
      }
    }
  },
  "version" : "20191120152912",
  "publicationDate" : "2019-11-20T15:29:12Z"
}
  
```
But the price on the aws s3 price page is $0.00099 per GB.

**Comment by debora-ito** [comment]
@liewhite could you provide the link to the s3 price page?

**Comment by debora-ito** [comment]
Found it! Is this one? https://aws.amazon.com/s3/pricing/?nc=sn&loc=4

**Comment by liewhite** [comment]
@debora-ito  yes,yes. I'm confused about the price the api returns. It's totally different with the price on the aws page

**Comment by debora-ito** [comment]
I've opened an issue with Pricing API team and will update here when they respond.

**Comment by debora-ito** [comment]
@liewhite the service team responded saying that the service code for Glacier Deep Archive storage products is actually `AmazonS3GlacierDeepArchive` (and not "AmazonS3").

The product you found was if you were using the Deep Glacier Archive as a regular S3 bucket (and thus is defaults to the regular S3 price of $0.021GB/Month). This is described in the "small letters" linked by the two asterisks (**) next to the Glacier Deep Archive price in the S3 pricing page; the "small letters" says that if you use Glacier Deep Archive as a S3 bucket (delete files before 90/180 days), then the pricing will default to regular S3 prices.

Let us know if that helps.

**Comment by liewhite** [comment]
> @liewhite the service team responded saying that the service code for Glacier Deep Archive storage products is actually `AmazonS3GlacierDeepArchive` (and not "AmazonS3").
> 
> The product you found was if you were using the Deep Glacier Archive as a regular S3 bucket (and thus is defaults to the regular S3 price of $0.021GB/Month). This is described in the "small letters" linked by the two asterisks (**) next to the Glacier Deep Archive price in the S3 pricing page; the "small letters" says that if you use Glacier Deep Archive as a S3 bucket (delete files before 90/180 days), then the pricing will default to regular S3 prices.
> 
> Let us know if that helps.

Thanks! Got it. It's not easy to find the product.

**Comment by liewhite** [comment]
@debora-ito BTW do you know is there some document describes the services?

**Comment by debora-ito** [comment]
You can obtain a list of available AWS services in the Offer Index File - https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-ppslong.html#download-the-offer-index

Closing this, feel free to reopen if you have any other question.
