### ISSUE TITLE
describeDBClusters in AmazonNeptune returns RDS Clusters

### ISSUE THREAD

**Issue by anilcs81** [aws/aws-sdk-java#2192]
```
AmazonNeptune neptuneClient = AmazonNeptuneClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(temporaryCredentials)).withRegion(region.getName()).build();
List<DBCluster> dBClustersTemp = neptuneClient.describeDBClusters(new DescribeDBClustersRequest()).getDBClusters();
```
The code above returns RDS clusters not NeptuneClusters

**Comment by debora-ito** [comment]
Hi @anilcs81 

We had the same question asked in a previous issue (#1878) just the other way around - RDS client returning Neptune clusters. The documentation of RDS [describeDBClusters API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html) states that "This operation can also return information for Amazon Neptune DB instances and Amazon DocumentDB instances.", so my guess is they all have a shared infrastructure of some kind.

I'll contact the service team behind the Neptune API asking for clarification. Will let you know what we hear back.

**Comment by debora-ito** [comment]
@anilcs81 Neptune team responded saying it is the expected behavior. They will work on updating the API documentation to make it more clear.

Closing this, feel free to reopen if you have any more questions.

**Comment by anilcs81** [comment]
this is pretty weird and confusing.

**Comment by karthik-1** [comment]
@anilcs81 thanks, noted feedback . We have updated the [describeDB API](https://docs.aws.amazon.com/neptune/latest/userguide/api-clusters.html#DescribeDBClusters) doc but will also check if we can filter the list to Neptune.
