### ISSUE TITLE
describeDBClusters for DocumentDB returns RDS Clusters

### ISSUE THREAD

**Issue by anilcs81** [aws/aws-sdk-java#2193]
`
AmazonDocDBClient docDBClient = (AmazonDocDBClient) AmazonDocDBClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(temporaryCredentials)).withRegion(region.getName()).build();
					List<DBCluster> clusterList = docDBClient.describeDBClusters(new DescribeDBClustersRequest()).getDBClusters();`

Above code returns RDS clusters not DocDB clusters as expected. Same behavior is observed for Neptune as well

**Comment by debora-ito** [comment]
See https://github.com/aws/aws-sdk-java/issues/2192#issuecomment-571359359, will update when they respond.

**Comment by debora-ito** [comment]
@anilcs81 so the DocDB team also responded saying it is an expected behavior. I asked them to add a note to the DescribeDBClusters docs.

I'll go ahead and close this. Feel free to reopen if you have further questions.
