### ISSUE TITLE
Using ProfileCredentialsProvider with profile name  and file path doesn´t work.

### ISSUE THREAD

**Issue by LucianoBernal** [aws/aws-sdk-java#2194]
When I instance a ProfileCredentialsProvider with a valid file path and a profile name, it doesn't take that profile to push to a S3 bucket. 
```
String profileName = "myProfile";
ProfilesConfigFile profilesConfigFile = new ProfilesConfigFile("src/main/resources/config");
AWSCredentialsProvider credentialsProvider = new ProfileCredentialsProvider(profilesConfigFile, profileName);
return AmazonS3ClientBuilder.standard()
                .withCredentials(awsStaticCredentialsProvider)
                .withRegion(region)
                .build();
```
So, I have to use the method assumeRole with temporary credentials to create a BasicSessionCredentials(). And then it works.

Context:
I need to take a different profile from the default and the configuration is on the /.aws/config file (the role arn I need).
The code is running inside a docker container in a EC2 instance (in account A), and the S3 (in account B) bucket has a trusted relation with that instance.

**Comment by debora-ito** [comment]
@LucianoBernal do you see an error message (like "file not found"), or do the client take on another credential in the credential chain?

(Also: I'm assuming that in your code sample you meant to provide `credentialsProvider` to withCredentials(), instead of `awsStaticCredentialsProvider`)

**Comment by debora-ito** [comment]
Closing due to no response, feel free to reopen if you need further assistance.
