### ISSUE TITLE
CDK synth give error stream closed

### ISSUE THREAD

**Issue by abhinav-jain09** [aws/aws-sdk-java#2198]
Dear Friends . I just did cdk init and then doing cdk synth and get the follwoing error

```> cdk synth
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project cdk-workshop: An exception occured while executing the Java class. Unable to send request to jsii-runtime: java.io.IOException: Stream closed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project cdk-workshop: An exception occured while executing the Java class. Unable to send request to jsii-runtime: java.io.IOException: Stream closed
```
I use java 8 . Need help to fix this issue

**Comment by debora-ito** [comment]
Hey @abhinav-jain09, for issues with the CDK workshop please open an issue in their repository: https://github.com/aws-samples/aws-cdk-intro-workshop.

This is the repo for issues and feature requests relating to the [AWS SDK for Java](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html).
