### ISSUE TITLE
Cloudsearch - list/describe tags not available

### ISSUE THREAD

**Issue by anilcs81** [aws/aws-sdk-java#2209]
No sdk methods available to list the tags associated with cloud search domain

**Comment by debora-ito** [comment]
Cloudsearch API does not have a list-tags operation specifically, but you could use the [GetResources](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/resourcegroupstaggingapi/AWSResourceGroupsTaggingAPI.html#getResources-com.amazonaws.services.resourcegroupstaggingapi.model.GetResourcesRequest-) operation from the Resource Groups Tagging API. The GetResourcesResult contains a list of resource ARNs and the tags (keys and values) associated with each.

Let us know if that helps.

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have any other question.
