### ISSUE TITLE
Add ability to generate unsigned urls to objects in S3

### ISSUE THREAD

**Issue by kmejka** [aws/aws-sdk-java#221]
Currently the S3 API only allows the user to generate an unsigned URL. There should also be a possibility to generate an unsinged URL, e.g. from the PutObjectResult returned after putting the object?

**Comment by stevenferey** [comment]
Hello,

The documentation for Java specifies that it is not possible to generate an unsigned url :

http://docs.ceph.com/docs/master/radosgw/s3/java/#generate-object-download-urls-signed-and-unsigned

Maybe it needs to be changed?

Regards,
