### ISSUE TITLE
EastiCache ReplicationGroup's AuthTokenLastModifiedDate is always current time

### ISSUE THREAD

**Issue by turaleck** [aws/aws-sdk-java#2214]
The `AuthTokenLastModifiedDate` returned by `ElastiCache` service when describing a `ReplicationGroup` is always the server current time, not the time when the auth token was modified.

```
DescribeReplicationGroupsRequest request = new DescribeReplicationGroupsRequest()
                .withReplicationGroupId(replicationGroupId());

DescribeReplicationGroupsResult result =
               elastiCache.describeReplicationGroups(request);

// Get any replication group from result

log.info("Auth token modified date: {}", anyReplicationGroup.getAuthTokenLastModifiedDate()) // this is always the current time
```

```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-elasticache</artifactId>
    <version>1.11.714</version>
</dependency>
```

**Comment by turaleck** [comment]
Another way to see this behavior is to select a Redis instance (cluster mode enabled), refresh the page multiple times, and observe that every refresh returns a new date for `AUTH token last modified date`

**Comment by debora-ito** [comment]
Hi @turaleck I'm not sure if this behavior is expected or not. I'll reach out to the Elasticache service team and ask them to clarify.

**Comment by turaleck** [comment]
@debora-ito it is definitely not expected. Based on the name of the property and the sdk documentation, it is supposed to be the time the auth token was last modified, not the system current time.

**Comment by debora-ito** [comment]
@turaleck I called `elastiCache.describeReplicationGroups(request)` today and I can see the AuthTokenLastModifiedDate is not the current date anymore. 

Can you confirm you are seeing this too?
