### ISSUE TITLE
File Name and Content Type for Pre Signed URL

### ISSUE THREAD

**Issue by bhanusweet** [aws/aws-sdk-java#2215]
Hi,

The coding is being done in Java.

I have files stored in S3 with fileId.extension   The fileid is maintained internally by our application and app. While Getting the Pre-Signed URL i want to change the name of the file and also set the content type correctly. Using below code for the same

Trial 1 :
GeneratePresignedUrlRequest generatePresignedUrlRequest;
 generatePresignedUrlRequest = new GeneratePresignedUrlRequest(bucketname,keyname).withMethod(HttpMethod.GET).withExpiration(expiration);
 generatePresignedUrlRequest.addRequestParameter(Headers.S3_USER_METADATA_PREFIX,"application/pdf"); 

This above code is able to apply the correct content type but i am not able to set the filename as desired. The given URL generated is to be used by fileviewer where it is able to understand the content type is pdf format.

Trial 2 :
GeneratePresignedUrlRequest generatePresignedUrlRequest;
 generatePresignedUrlRequest = new GeneratePresignedUrlRequest(bucketname,keyname).withMethod(HttpMethod.GET).withExpiration(expiration);
generatePresignedUrlRequest.addRequestParameter(Headers.S3_USER_METADATA_PREFIX,"application/pdf");
ResponseHeaderOverrides responseHeaders = new ResponseHeaderOverrides();
responseHeaders.setContentDisposition("attachment; filename =\"" + filename + "\"");
responseHeaders.setContentType("application/pdf");
generatePresignedUrlRequest.setResponseHeaders(responseHeaders);

This set the file name correctly but content type is not correctly set as the fileviewer is not able to understand the content type is pdf type.

Please share the correct way to set the content type and file name may be first scenario as the browser is able to catch the content type of first type and preview the file but only issue is the file name to be changed.

Thanks
Regards
Bhanu

**Comment by debora-ito** [comment]
Hi @bhanusweet, can you try again the second example but setting the content-type only once? Like this:

```java
GeneratePresignedUrlRequest generatePresignedUrlRequest;
generatePresignedUrlRequest = new GeneratePresignedUrlRequest(bucketname,keyname)
    .withMethod(HttpMethod.GET)
    .withExpiration(expiration);

ResponseHeaderOverrides responseHeaders = new ResponseHeaderOverrides();
responseHeaders.setContentDisposition("attachment; filename =\"" + filename + "\"");
responseHeaders.setContentType("application/pdf");
generatePresignedUrlRequest.setResponseHeaders(responseHeaders);
```

**Comment by bhanusweet** [comment]
Hi @debora-ito Thanks for the inputs. I tried the second method with applying only content type once as mentioned by you. But the preview works in Windows Explorer but does not work in Google Chrome.
Google Chrome seems to be using content type from from some other parameter which is the one set by example one. 

Please let me know your thoughts on this.

Thanks
Regards

**Comment by debora-ito** [comment]
Does the file originally contain the content-type metadata in S3?

> But the preview works in Windows Explorer but does not work in Google Chrome.

Can you be more specific on what works and what does not?

**Comment by bhanusweet** [comment]
Hi @debora-ito 

The original file has following content type for pdf as shown in image. For other the content type is octet/stream
![Capture](https://user-images.githubusercontent.com/22333748/74078599-80fc1800-4a52-11ea-976e-f39e02d1180b.PNG)
![Capture3](https://user-images.githubusercontent.com/22333748/74078602-88232600-4a52-11ea-9576-2285210bcd6d.PNG)

The preview for the file does not work in Google Chrome and works in Windows Explorer As shown in 
image. Below is shown the preview functionality of the application. This preview viewer is of the browser.

![Capture2](https://user-images.githubusercontent.com/22333748/74078607-92ddbb00-4a52-11ea-9379-4938cb3de1e1.PNG)

Thanks
Regards

**Comment by debora-ito** [comment]
Can you try using content-disposition `inline` instead of `attachment`? `Inline` indicates it can be displayed inside a web page.

```java
responseHeaders.setContentDisposition("inline; filename =\"" + filename + "\"");
```

**Comment by bhanusweet** [comment]
Hi @debora-ito 
Thanks for sharing your inputs. This inline helped in resolving half of the issue where not browser is able to detect the file in preview option with second method also and download is happening with correct filename instead of file id.

But still one concern exist is that when i am using the url for download directly using the pre signed url generated by using direct url in browser or Phone APP still the file uuid name is being used. Can we somehow modify the FileID name with filename

Please see the below url generated.

![image](https://user-images.githubusercontent.com/22333748/74247567-458c7280-4d0c-11ea-9387-eccaf1cb79e5.png)

19.pdf should be replaced by Old-SampleInvite.pdf

Thanks for helping me out really appreciate your inputs.

Regards
Bhanu

**Comment by debora-ito** [comment]
You cannot change the 19.pdf in the url itself, it's your object url in S3 (you can see it when you open the "overview" tab of the object in S3 console).

Since all the issues have been clarified, I'll go ahead and close this. Feel free to reach out if you have any other question.
