### ISSUE TITLE
DynamoDB:  override @DynamoDBTable annotation on DTO when using DynamoDBMapper with TransactionWriteRequest & transactionWrite

### ISSUE THREAD

**Issue by qqdipps** [aws/aws-sdk-java#2216]
# DynamoDB:  override @DynamoDBTable annotation on DTO when using DynamoDBMapper with TransactionWriteRequest

## User story
**As a** developer
**I want to** transactionally insert or update the same item in 2 tables using DynamoDBMapper
**so that** I can have data consistency between both tables as I perform a phased system migration in an existing code base without modifying application layer logic.

## Simplified Example

```
@DynamoDBTable(tableName = "Table1")
public class ItemDTO  {...} 
```
itemDTO is an instance of ItemDTO and represents an item that exists in 'Table1' and 'Table2', but the itemDTO has been changed. Now I want to save those changes in both tables. I need to do a transactional update of this item in 'Table1' and 'Table2' using an instance of DynamoDBMapper, mapper.

```
TransactionWriteRequest transactionWriteRequest = new TransactionWriteRequest();
# adds update of the itemDTO in 'Table1'
transactionWriteRequest.addUpdate(itemDTO)

### override @DynamoDBTable annotation such that itemDTO maps to 'Table2' ### 

# adds update of the itemDTO in 'Table2'
transactionWriteRequest.addUpdate(itemDTO)
# commits transaction or rolls back if fails
mapper.transactionWrite(transactionWriteRequest)
```
**### override @DynamoDBTable annotation such that itemDTO maps to 'Table2' ###**  
I'm still figuring this part out without modifying application layer. It's best if we can make the change at the level of the Data Access Object library in our codebase.

If I did not require a transactional write I could: 

```
# update of the itemDTO in 'Table1'
mapper.save(itemDTO)
# create TableNameOverride config for 'Table2'
TableNameOverride table2Override = new DynamoDBMapperConfig.TableNameOverride('Table2')
# update of the itemDTO in 'Table2' by passing new DynamoDBMapperConfig w/ table2Override
mapper.save(itemDTO, new DynamoDBMapperConfig(table2Override))
```

## DynamoDB Java SDK for DynamoDBMapper

- I also require passing DynamoDBTransactionWriteExpression which is supported

### Closest method signature to what I need:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/TransactionWriteRequest.html

TransactionWriteRequest | addUpdate(Object object,          DynamoDBTransactionWriteExpression transactionWriteExpression)
-- | -- 

### What I need: 

TransactionWriteRequest | addUpdate(Object object,          DynamoDBTransactionWriteExpression transactionWriteExpression, DynamoDBMapperConfig config) 
-- | -- 

### Similar to: 

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/AbstractDynamoDBMapper.html

save(T object, DynamoDBSaveExpression saveExpression, DynamoDBMapperConfig config)
-- |

## Glossary
DTO: Data Transfer Object https://en.wikipedia.org/wiki/Data_transfer_object

**Comment by qqdipps** [comment]
**related question**
dynamodbmapper annotations onetomany  mapping https://stackoverflow.com/questions/29069224/dynamodbmapper-annotations-onetomany-mapping

**Comment by debora-ito** [comment]
Hi @qqdipps this is an interesting case, marking as a feature request. 

This request is better suited for SDK for Java 2.x though, where the team is concentrating its work. But since DynamoDBMapper is not available yet in 2.x, let's use this to track the issue.
