### ISSUE TITLE
MultipartUpload fails with Net::ReadTimeout error - s3 interface

### ISSUE THREAD

**Issue by muralivenkataraman** [aws/aws-sdk-java#2217]
We are using logstash version 7.3.2 (it comes with aws-sdk* version 2.11.330) and the upload is failing with a ReadTimeout error (small file of 10MB).   Is 2.11.330 supported ?  

TCPDUMP shows 400-Bad request initiated from the CEPH object storage host before the connection is closed.

Here is the complete trace from the log file. 
 
`Uploading failed, retrying. {:exception=>Aws::S3::MultipartUploadError, :message=>"multipart upload failed: Net::ReadTimeout; Net::ReadTimeout; Net::ReadTimeout; Net::ReadTimeout", :path=>"/u/elasticStack/logstash-working-dir/ls-szng1/tmp/482ec854-eb7b-4bd2-ba8c-92ca83f08f5e/ls.s3.59a7b8a1-3906-4331-9e16-ee7afe4bc2bc.2020-02-05T20.42.part18.txt.gz", :backtrace=>["/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:81:in abort_upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:70:in upload_parts'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:44:in upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/file_uploader.rb:32:in upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.330/lib/aws-sdk-resources/services/s3/object.rb:252:in upload_file'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.1.9/lib/logstash/outputs/s3/uploader.rb:38:in upload'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/logstash-output-s3-4.1.9/lib/logstash/outputs/s3/uploader.rb:29:in block in upload_async'", "/u/elasticStack/ls_szng1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/java_executor_service.rb:85:in run'"]}`

**Comment by muralivenkataraman** [comment]
No upload issues with aws-sdk* version 2.11.177

**Comment by debora-ito** [comment]
The Logstash team would be able to help you over at https://github.com/elastic/logstash.

There's nothing related to the AWS SDK for Java in the stacktrace.
