### ISSUE TITLE
Core still uses log4j 1.x for tests

### ISSUE THREAD

**Issue by rtveitch** [aws/aws-sdk-java#2219]
The following test classes use log4j 1.x.
- https://github.com/aws/aws-sdk-java/blob/aaa0a6f506314d314a77774ddadd303cf6e4c354/aws-java-sdk-core/src/test/java/com/amazonaws/util/LogCaptor.java
- https://github.com/aws/aws-sdk-java/blob/aaa0a6f506314d314a77774ddadd303cf6e4c354/aws-java-sdk-core/src/test/java/com/amazonaws/http/DefaultErrorResponseHandlerIntegrationTest.java
- https://github.com/aws/aws-sdk-java/blob/7b1e5b87b0bf03456df9e77716b14731adf9a7a7/aws-java-sdk-core/src/test/java/com/amazonaws/http/RetryCountInUserAgentTest.java

Now that log4j 2.x has been available for several years, it would be nice to refactor these tests to use it, and to avoid any warnings from dependency vulnerability scanner tools that may pick up on the 1.x dependency despite it being used only in `test` scope.

**Comment by debora-ito** [comment]
Hi @rtveitch, we understand how annoying it is to have this kind of warning, but currently we don't have the intention to upgrade to log4j 2.x in V1. The team is actively working in new features of the SDK V2, so refactoring the tests would have very very low priority.

Thank you for reaching out. Feel free to reopen if you have any other question or concern.
