### ISSUE TITLE
S3 bucket client not setting location constraint for ap-east-1

### ISSUE THREAD

**Issue by jkoe-r7** [aws/aws-sdk-java#2220]
SDK version: 1.11.604

Client appears to not be setting location constraint for ap-east-1 region/appears to have issue setting location constraint. Requests made by client succeed in other non-us-east-1 regions, ap-east-1 is the only region with issue atm.

**Client setup:**
AmazonS3ClientBuilder.standard()
        .withRegion(AwsCoreFactory.newRegions("ap-east-1"))
        .withClientConfiguration(new ClientConfiguration(clientConfiguration))
        .withCredentials(getCredentials(id, region))
        .withPathStyleAccessEnabled(true)
        .build();

**CLI region:**
aws s3api get-bucket-location --bucket bucket-name
{
    "LocationConstraint": "ap-east-1"
}

**Exception from requests made by client:**
java.lang.RuntimeException: com.amazonaws.services.s3.model.AmazonS3Exception: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to. (Service: Amazon S3; Status Code: 400; Error Code: IllegalLocationConstraintException; Request ID: C10658DDD10B665D; S3 Extended Request ID: pyAtwxoR/QPUgtfgkQF5bse1cS1JhUaKGL778veNZYEE79VAsu4urCpXNBvuBni1L+aVnvf3bIU=) 

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to. (Service: Amazon S3; Status Code: 400; Error Code: IllegalLocationConstraintException; Request ID: C10658DDD10B665D; S3 Extended Request ID: pyAtwxoR/QPUgtfgkQF5bse1cS1JhUaKGL778veNZYEE79VAsu4urCpXNBvuBni1L+aVnvf3bIU=)

**Comment by debora-ito** [comment]
Hi @jkoe-r7 I was not able to reproduce the issue, I could successfully call ListObjects() with both client and bucket regions set in AP_EAST_1.

The IllegalLocationConstraintException usually means that the region set in the client is different from the bucket region. In my tests, if I change the client region to any other one and call ListObjects() specifying a bucket in AP_EAST_1, I get the same exception you're seeing.

You can check the real region the client is sending the requests if you turn the wire logs on.
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose

**Comment by jkoe-r7** [comment]
Thanks!
