### ISSUE TITLE
DynamoDB: Receiving generic AmazonDynamoDBException when throttled during on-demand table scaling

### ISSUE THREAD

**Issue by pederpansen** [aws/aws-sdk-java#2222]
Hi. When using an on-demand DynamoDB table under heavy write throughput, I am getting exceptions like this one:

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html (Service: dynamodb; Status Code: 400; Error Code: ThrottlingException;
[remainder of message cut for brevity]
```
I was surprised to see a generic `AmazonDynamoDBException`exception, as this makes error handling (retry/backoff) quite inconvenient. For example, for provisioned throuhput tables, there is the [ProvisionedThroughputExceededException](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ProvisionedThroughputExceededException.html), which allows for easy exception catching/matching. (See https://github.com/scanamo/scanamo/issues/589 for a use case in Scala using Scanamo.)

The error code in the exception message hints at an exception named `ThrottlingException` - however, such a class does not exist and the only places I can find them is in some seemingly outdated javadocs.

Would there be a possibility to create a separate exception class for these kind of errors? I would be willing to contribute a PR if pointed in the right direction.

**Comment by debora-ito** [comment]
Hi @pederpansen, the SDK generates the clients from models provided by the service teams, and the models also define which exceptions you get for each operation. `ThrottlingException` is not a 
modeled error code, so the SDK returns the generic `AmazonDynamoDBException` exception.

Because of that, the change must be made upstream, so this would be a feature request to the DynamoDB team. Let us know if you want me to pass this request to the DynamoDB team.

**Comment by pederpansen** [comment]
Hi @debora-ito, yes, it would be great if you could pass on the request. Will you be able to report back here once the issue is accepted by the DynamoDB team?

**Comment by debora-ito** [comment]
Yes, I'll report back.

**Comment by debora-ito** [comment]
You can also reach out to the DynamoDB team directly posting the request in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131) or contacting Customer Support.

**Comment by debora-ito** [comment]
Hey @pederpansen, actually I realized that this would be a breaking change in the DynamoDB APIs. Other customers can be relying in this exception and error code as it is now to handle throttling exceptions, so the DynamoDB team can't make this change.

That said, I'll go ahead and close this, but feel free to reopen if you have any other question.

**Comment by WtrLmmrs** [comment]
Sorry to hijack this. The documentation for ThrottlingException here https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html shows how to workaround not having a dedicated Exception type for this.

However I also found the method isThrottlingException here: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/retry/RetryUtils.html which seems to fit the bill even better.

This class is marked as @SdkProtectedApi (doesn't show in JavaDoc?), could it be upgraded to public api?
