### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amazonaws/client/builder/AdvancedConfig

### ISSUE THREAD

**Issue by jennings1716** [aws/aws-sdk-java#2227]
I receive the error when I try to instantiate AWSSNSClient

        ```
AmazonSNSClient snsClient = new AmazonSNSClient(credentials);
snsClient.setRegion(Region.getRegion(Regions.--));
ObjectMapper Obj = new ObjectMapper();
PublishRequest publishRequest = new PublishRequest();
publishRequest.setTargetArn("arn:aws:sns:-----");
publishRequest.setMessage(transactionId);
PublishResult publishResponse = snsClient.publish(publishRequest);
```

My pox.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.4.RELEASE</version>
		<relativePath /> 
	</parent>
	<groupId>com.cmds</groupId>
	<artifactId></artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name></name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.amazonaws</groupId>
				<artifactId>aws-java-sdk-bom</artifactId>
				<version>1.11.721</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-kubernetes-config</artifactId>
			<version>1.1.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-flow</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jms</artifactId>
			<version>5.2.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>amazon-sqs-java-messaging-lib</artifactId>
			<version>1.0.8</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-sns</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>

	</build>

</project>

Error:

java.lang.NoClassDefFoundError: com/amazonaws/client/builder/AdvancedConfig
	at com.amazonaws.services.sns.AmazonSNSClient.<init>(AmazonSNSClient.java:174) ~[aws-java-sdk-sns-1.11.721.jar:na]
	at com.amazonaws.services.sns.AmazonSNSClient.<init>(AmazonSNSClient.java:151) ~[aws-java-sdk-sns-1.11.721.jar:na]
	at com.cmds.booking.infrastructure.SNSService.publishMessage(SNSService.java:18) ~[classes/:na]

Is there any dependency issue ?

**Comment by debora-ito** [comment]
Hi @jennings1716, NoClassDefFound Errors usually indicate conflicting versions of the same dependency in your environment. Can you run `mvn dependency:tree` and post the relevant output?

**Comment by debora-ito** [comment]
Closing due to no response. Feel free to reopen if you are still experiencing this.

**Comment by shehan-jay** [comment]
I updated the same version for aws-java-sdk-core and aws-java-sdk-secretsmanager. things got resolved.

```
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-core</artifactId>
      <version>1.12.715</version>
    </dependency>
```
   
```
 
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-secretsmanager</artifactId>
      <version>1.12.715</version>
    </dependency>
```
