### ISSUE TITLE
Multipart Upload fails - 400 Bad request

### ISSUE THREAD

**Issue by kvmuralidhar** [aws/aws-sdk-java#2228]
Hi there,

I was reviewing the aws-sdk documentation as well as the tcpdump for multipart upload and wanted to see if I can get help to troubleshoot this further.    The documentation says "Whenever you upload a part, Amazon S3 returns an ETag header in its response. For each part upload, you must record the part number and the ETag value."  I do not see ETag in the response.  

Is there a temporary location the individual part files are uploaded on the target server ?  We are not using s3 storage provided by aws but are using CEPH storage.

I am also attaching herewith an excel spreadsheet that shows the request/response.  Any help would be very much appreciated.
[tcpdump-request.xlsx](https://github.com/aws/aws-sdk-java/files/4204815/tcpdump-request.xlsx)

Thanks
Murali

**Comment by debora-ito** [comment]
Hi @kvmuralidhar, looking at the request logs it shows you're using the AWS SDK for Ruby. If that's the case, please reach out to the Ruby SDK team in https://github.com/aws/aws-sdk-ruby/issues

**Comment by kvmuralidhar** [comment]
hah - I will submit my request to that team, thank you :)
