### ISSUE TITLE
DynamoDBMapper.privateMarshallIntoObject should get model class after untransform call

### ISSUE THREAD

**Issue by ghost** [aws/aws-sdk-java#2232]
## Description 
Current `DynamoDBMapper.privateMarshallIntoObject` method gets the model class from the `parameters` input variable, but that happens before the call `untransformAttributes` done over the `parameters` attributes. Custom transformers are then not allowed to change the model class, in particular when the model class is dynamically defined by attribute values. This is specially required to correctly handle model hierarchies, so as models can be retrieved by the use of their parent model classes. More details on this use case may be provided if needed.
## Use case
Take a simple hierarchy of models with an abstract model class `AbstractModel` and two concrete models `ModelA` and `ModelB` derived from `AbstractModel`. The `typeName` attribute must drive the model class to be instantiated when retrieving it from DynamoDB when the `load` operation is called using the abstract `AbstractModel` as the input model class.
```
@DynamoDBTable(tableName = "Model")
public abstract class AbstractModel {
  private String id;
  private String typeName;
  // imagine here other N common attributes to all models like creation data, modified date, 
  // version, flag to signal if model is deprecated, etc. etc. which we don't want to have replicated 
  // in ModelA and ModelB

  @DynamoDBHashKey
  public String getId() {
    return this.id;
  } 

  public void setId(final String id) {
    this.id= id;
  }

  @DynamoDBAttribute
  public String getTypeName() {
    return this.typeName;
  } 

  public void setTypeName(final String typeName) {
    this.typeName= typeName;
  }
}

public final class ModelA extends AbstractModel {
  private String specificToA;
    
  @DynamoDBAttribute
  public String getSpecificToA() {
    return this.specificToA;
  } 

  public void setSpecificToA(final String specificToA) {
    this.specificToA = specificToA;
  }
}

public final class ModelB extends AbstractModel {
  private String specificToB;
  
  @DynamoDBAttribute
  public String getSpecificToB() {
    return this.specificToB;
  } 

  public void setSpecificToB(final String specificToB) {
    this.specificToB = specificToB;
  }
} 
```

**Comment by cnorthfleet** [comment]
## Proposed changes
[0001-Move-call-to-get-model-class-to-after-parameters-unt.patch.txt](https://github.com/aws/aws-sdk-java/files/4221234/0001-Move-call-to-get-model-class-to-after-parameters-unt.patch.txt)

**Comment by spfink** [comment]
After discussing with the team, I believe that this is a change we can make. Working on some test cases for it and hopefully be able to get it out with a release either tomorrow or early next week.

**Comment by cnorthfleet** [comment]
Thanks @spfink. Please note the proposed changes above are kind of hacky. 
By the use of a custom `AttributeTransformer` passed to `DynamoDBMapper` it will allow the `transform` and `untransform` methods to reassign the input parameter `Parameters<?>`. That is currently possible anyways since those input parameters are not `final` but, they allow for everything to change except for the model class as the call to `getModelClass` happens before the `untransform` call.
I particularly do not like the approach of changing objects passed as reference, but I see something similar is done with the configuration on calls like `config = mergeConfig(config)`. Please feel free to come up with different approaches!

**Comment by cnorthfleet** [comment]
Hi @debora-ito @spfink , any news on this topic?
Cheers
