### ISSUE TITLE
AWS sdk IoT createThing request is not throwing ResourceAlreadyExistsException

### ISSUE THREAD

**Issue by aloysiustany** [aws/aws-sdk-java#2234]
Hi,

I am using following code to create an Iot Thing. 

```
try {
   AWSIotAsync client = AWSIotAsyncClientBuilder.defaultClient();
   CreateThingResult res = client.createThing(createThingRequest);
   // TODO: This does not throw ResourceAlreadyExistsException even if Thing already exists. Always returns success.
   logger.info("Successfully created IoT Thing (or IoT Thing already exists) | Thing name: " + thingName + " | Thing Arn: " + res.getThingArn() + " | Thing Id: " + res.getThingId());
} catch (ResourceAlreadyExistsException ex) {
   // NEVER reaches here
   logger.info("IoT Thing already exists | Thing name: " + thingName + " | Thing Arn: " + ex.getResourceArn());
}
```

I was expecting the createThing() call to throw ResourceAlreadyExistsException if the Thing already exists. But that is not the behavior.

**Comment by debora-ito** [comment]
Hi @aloysiustany according to the CreateThing [API reference](https://docs.aws.amazon.com/iot/latest/apireference/API_CreateThing.html):

> Creates a thing record in the registry. If this call is made multiple times using the same thing name and configuration, the call will succeed. If this call is made with the same thing name but different configuration a ResourceAlreadyExistsException is thrown.

Let us know if this is not what you are experiencing.

**Comment by aloysiustany** [comment]
I totally skipped to read that line. My bad.

That's perfect. Thanks for pointing it to me.
