### ISSUE TITLE
Unable to fetch the cost and usage data

### ISSUE THREAD

**Issue by Subrata1920** [aws/aws-sdk-java#2235]
Hi, I am trying to fetch the cost and usage data according to the tags.
Here is my code.

try {
    AWSCredentials credentialsProvider = new BasicAWSCredentials(Constants.ACCESS_KEY, Constants.SECRET_KEY);
    Expression dimensions = new Expression().withDimensions(new DimensionValues()
            .withKey(Dimension.SERVICE)
            .withValues("Amazon Simple Storage Service"));

    Expression tags = new Expression().withTags(new TagValues()
            .withKey("tag-key")
            .withValues("tag-value"));

    Expression expr = new Expression().withAnd(dimensions, tags);

    List < GroupDefinition > sd = new ArrayList <  > ();

    GroupDefinition gd = new GroupDefinition();
    gd.setKey("SERVICE");
    gd.setType("DIMENSION");
    sd.add(gd);

    GetCostAndUsageRequest awsCERequest = new GetCostAndUsageRequest()
        .withTimePeriod(new DateInterval().withStart("2020-02-01").withEnd("2020-03-01"))
        .withGranularity(Granularity.MONTHLY)
        .withMetrics("BlendedCost", "UnblendedCost", "UsageQuantity")
        .withFilter(expr)
        .withGroupBy(sd);

    AWSCostExplorer ce = AWSCostExplorerClientBuilder
        .standard()
        .withCredentials(new AWSStaticCredentialsProvider(credentialsProvider))
        .withRegion(Regions.US_EAST_1)
        .build();

    System.out.println(ce.getCostAndUsage(awsCERequest));
} catch (final Exception e) {
    e.printStackTrace();
}

1) I am trying to get the cost and usage data related to my tag i.e. tag-key. Is it possible to query the cost and usage related to a particular tag.

I am getting below output. but BlendedCost, UsageQuantity and UnblendedCost showing 0.

{
    GroupDefinitions: [{
            Type: DIMENSION,
            Key: SERVICE
        }
    ],
    ResultsByTime: [{
            TimePeriod: {
                Start: 2020 - 02 - 01,
                End: 2020 - 03 - 01
            },
            Total: {
                BlendedCost = {
                    Amount: 0,
                    Unit: USD
                },
                UsageQuantity = {
                    Amount: 0,
                    Unit: N / A
                },
                UnblendedCost = {
                    Amount: 0,
                    Unit: USD
                }
            },
            Groups: [],
            Estimated: true
        }
    ]
}

Please help me out.

**Comment by debora-ito** [comment]
Hi @Subrata1920 the expression with the tag and dimension seems correct, so my guess is the cost explorer is not finding any resources in S3 or with the tag you specified.

If you sent the GetCostAndUsageRequest with only `tags` in the filter:
```
GetCostAndUsageRequest awsCERequest = new GetCostAndUsageRequest()
    .withTimePeriod(new DateInterval().withStart("2020-02-01").withEnd("2020-03-01"))
    .withGranularity(Granularity.MONTHLY)
    .withMetrics("BlendedCost", "UnblendedCost", "UsageQuantity")
    .withFilter(tags)
    .withGroupBy(sd);
```
do you get the expected values for tagged resources?
And if you specify only `dimensions`?

**Comment by Subrata1920** [comment]
Hi Debora,
Thanks for your quick reply,
I am not getting any the expected values for tagged resources and I want to get the cost and usage related to a tag not the dimensions.

Is it the correct way for creating tag and uploading files related to that tag in AWS. 
Here is my code for creating tag and uploading files related to the tag.


		try {
			Regions clientRegion = Regions.US_EAST_1;
			String bucketName = Constants.BUCKET_NAME;
			String keyName = "public/JAMES BOND 007_ NO TIME TO DIE Super Bowl Trailer (2020).mp4";// "*** Object key***";
			String filePath = "/home/subrata/Desktop/JAMES BOND 007_ NO TIME TO DIE Super Bowl Trailer (2020).mp4";// "***File path***";

			AWSCredentials credentialsProvider = new BasicAWSCredentials(Constants.ACCESS_KEY, Constants.SECRET_KEY);

			AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
					.withCredentials(new AWSStaticCredentialsProvider(credentialsProvider)).withRegion(clientRegion)
					.build();

			PutObjectRequest putRequest = new PutObjectRequest(bucketName, keyName, new File(filePath));
			List<Tag> tags = new ArrayList<Tag>();
			tags.add(new Tag("Tag_test", "This is tag 1"));
			putRequest.setTagging(new ObjectTagging(tags));
			PutObjectResult putResult = s3Client.putObject(putRequest);
			System.out.println(putResult.getETag());

			GetObjectTaggingRequest getTaggingRequest = new GetObjectTaggingRequest(bucketName, keyName);
			GetObjectTaggingResult getTagsResult = s3Client.getObjectTagging(getTaggingRequest);
			System.out.println(getTagsResult.getTagSet());
		} catch (AmazonServiceException e) {
			e.printStackTrace();
		} catch (SdkClientException e) {
			e.printStackTrace();
		}

**Comment by debora-ito** [comment]
You need to activate the tags in the Billing and Cost Management console before start using them in the reports. 

For more info see: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html

Please note that it can take up to 24 hours for tags to activate.

**Comment by Subrata1920** [comment]
Thanks for your suggestion. I will try that.
My last question, Is it the correct way for creating tag and uploading files related to the tag(which I already mentioned in my previous comment.)

**Comment by debora-ito** [comment]
Yes, in your code example you are associating the new object "keyName" to the tag {key: "Tag_test", value: "This is tag 1"}

If you want to read more about commonly used strategies for tagging AWS resources, see: https://aws.amazon.com/answers/account-management/aws-tagging-strategies/

I'll go ahead and close this, feel free to reopen if you have further questions.
