### ISSUE TITLE
DynamoDB list tables does not work when did assume role with profile credentials

### ISSUE THREAD

**Issue by Kalpa2019** [aws/aws-sdk-java#2238]
HI all,
     when I call DynamoDbClient.listTables using assume role with given permission of * (wildcard) resource * actions,
it works fo EC2 and VPC listing, However, does not work for Dynamodb list tables.  it always return 0 tables. however, when I tried the directly without assume credentials. it works.
 
thanks,
Kalpa

**Comment by debora-ito** [comment]
Hi @Kalpa2019 can you share the permissions policy of that role?
And also a code sample I can use to reproduce the issue?

**Comment by debora-ito** [comment]
Closing due to no response. Feel free to reopen if you have further questions.
