### ISSUE TITLE
InstanceCredentialsProvider does not eagerlyFetch

### ISSUE THREAD

**Issue by rhoons** [aws/aws-sdk-java#2239]
I've been debugging an issue where we observe increased latency during our first DynamoDB request. We are using the `InstanceCredentialsProvider` from the 1.11 AWS SDK and instantiating it with `true` for the first parameter.

In reviewing the source code it seems that this calls a private constructor that takes two boolean parameters, the second being `eagerlyRefreshCredentialsAsync`. Unfortunately this parameter is ignored and `shouldRefresh` is set to `false`, therefore the credentials are not actually fetched until they are used.

If the credentials were to be eagerly fetched (as it seems was intended), then our application would not suffer this latency hit on the first customer request. As it is we will need to work around this by eagerly calling `getCredentials` ourself.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceProfileCredentialsProvider.java#L100

**Comment by debora-ito** [comment]
Hi @rhoons do you think the latency you've been observing is the same reported in 
- https://github.com/aws/aws-sdk-java/issues/2171 and 
- https://github.com/aws/aws-sdk-java-v2/issues/1667?

**Comment by debora-ito** [comment]
Closing due to no response. Feel free to reopen if you have further questions.
