### ISSUE TITLE
XmlResponsesSaxParser uses outdated XMLReaderFactory

### ISSUE THREAD

**Issue by AHeise** [aws/aws-sdk-java#2242]
In Flink, we had to resort patching XmlResponsesSaxParser to address an [issue](https://issues.apache.org/jira/browse/FLINK-16014) that was caused by a JDK 8 [bug](https://bugs.openjdk.java.net/browse/JDK-8015099).

We simply replaced XMLReaderFactory with SAXParserFactory as described in the bug ticket.

It would be awesome if you would accept a patch in this project, such that we can avoid the hacky patch on our end.

**Comment by debora-ito** [comment]
Hi @AHeise marking as a feature request, will discuss it with the team.

**Comment by debora-ito** [comment]
@AHeise we are wary of the possible repercussions of this change for SDK customers, backwards compatibility wise. And as the team is focused in delivering feature requests for Java SDK v2, this change would have low priority in comparison, so we decided to not implement it.

I'll go ahead and close this. Please feel free to reach out if you have further comments.

**Comment by AHeise** [comment]
I should have probably make clear that this is a more of a bug report and less of a feature request (but it's somewhat in the middle).
Currently, the Java SDK is not working correctly with different ClassLoaders on Java 8.

However, we solved it on our end for the time being and will hopefully upgrade soonish to v2. Are the devs positive that the same thing does not happen in v2 as well?

**Comment by debora-ito** [comment]
It seems like SDK v2 does not use XMLReaderFactory, but it's not really easy to tell because it's not easy to test it in our side. If you see the same problem using v2 please open an issue with a repro code and we will take a look.
