### ISSUE TITLE
EC2MetadataUtils.getInstanceAction() returns cached value

### ISSUE THREAD

**Issue by EdHowe** [aws/aws-sdk-java#2243]
I believe getInstanceAction() should be using the version of fetchData that takes a boolean "force" parameter (with a value of "true").  Otherwise, it appears it will cache the value the first time you call it, and you'll never be able to determine when your spot instance is going to be taken away.

**Comment by debora-ito** [comment]
@EdHowe this seems reasonable. Marking as a feature request.
