### ISSUE TITLE
SaveBehavior.APPEND_SET support for batch operations

### ISSUE THREAD

**Issue by kairsas** [aws/aws-sdk-java#2245]
`SaveBehavior.APPEND_SET` is working fine when using `DynamoDBMapper.save(T object, DynamoDBMapperConfig config)`.

However it is not possible to use this behavior in batch operations.

There is no `DynamoDBMapper.batchSave` method which accepts DynamoDBMapperConfig for passing in the `SaveBehavior.APPEND_SET`.

There is a method `DynamoDBMapper.batchWrite(objectsToWrite, objectsToDelete, DynamoDBMapperConfig)` which I thought should work with `SaveBehavior.APPEND_SET`, but it just ignores this behavior and overwrites the set.

**Comment by debora-ito** [comment]
That's expected actually, `batchWrite` always acts as if SaveBehavior.CLOBBER was specified regardless of the value of the config parameter, it does not support the other SaveBehavior options.

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html#batchWrite-java.lang.Iterable-java.lang.Iterable-com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig-

**Comment by kairsas** [comment]
Just interesting, are there any plans for batch save to handle SaveBehavior.APPEND_SET?

**Comment by debora-ito** [comment]
Not currently, no. I'll mark this as a feature request and discuss it with the team.

**Comment by debora-ito** [comment]
@kairsas So there are no plans to add support for this in V1. The team is focussing efforts in V2 features - the DynamoDB Enhanced Client is getting a lot of work right now, you can track it here: https://github.com/aws/aws-sdk-java-v2/issues/35.

I'll go ahead and close this, feel free to reach out if you have further questions.
