### ISSUE TITLE
Java 11 supported?

### ISSUE THREAD

**Issue by fiducioso-dan** [aws/aws-sdk-java#2247]
I have seen contradictory information on whether Java 11 (LTS) is supported by the v1 SDK. The [README](https://github.com/aws/aws-sdk-java/blob/master/README.md) and [developer guide](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-install.html#java-dg-java-env) say that Java 6+ are supported and there is no upper limit.

PR #1527 seems to imply that Java 9+ should be compatible after being merged in. 

Issue #1725 seems to directly ask this question but the response from @varunnvs92 answered, but was oddly specific and possibly answering a different question about modules:
> We don't have JDK 9 modular support in 1.11. Assuming thats your question, I would say No. But customers can use automatic modules to make it work.

In practice it looks like tests are [only run on Java 7 and 8](https://github.com/aws/aws-sdk-java/blob/master/.travis.yml), even thought at least Java 6 is also supported.

In light of all this can we have an answer to whether Java 11 is supported?

**Comment by millems** [comment]
Java 11 is supported.

We do not currently ship any module-info.java information.

We have a separate internal testing process with each release, outside of Travis.

**Comment by fiducioso-dan** [comment]
Thanks!
