### ISSUE TITLE
Check connectivity and authentication without a full service API call

### ISSUE THREAD

**Issue by chriskilding** [aws/aws-sdk-java#2251]
I'm looking for a service-independent way to test that the SDK can reach AWS and authenticate, without performing any particular service API call. Is there a feature in the SDK as it stands which would let me do this?

**Comment by debora-ito** [comment]
@chriskilding I don't believe there is. Can you tell us more about your use case, what's the issue you are trying to solve?

**Comment by chriskilding** [comment]
I maintain a Jenkins plugin which has a section in its config to specify an Endpoint Configuration. There's a button on that page to let the Jenkins admin test that an Endpoint Configuration will work, before they save the change.

If this was only used by one plugin, obviously the test could be a full API call. But the Endpoint Configuration will soon be shared among multiple AWS Jenkins plugins, at which point it will not appropriate to use any particular service call. Instead I only want to test what is generally applicable - connectivity to the endpoint, including auth.

**Comment by bmaizels** [comment]
@chriskilding I'm not aware of any 'ping' type service in AWS that is dedicated for this purpose. Until you actually try and speak to a service it's impossible to determine if your configuration is correct, but then theoretically any operation in any service can be legitimately denied to a specific user, also it can't be asserted that any given service will be available in any given region. 

Therefore the only option I can immediately think of is to only assert that the configuration is sane, that the endpoint url is a correctly formed url and any other constraints you would like to check, such as there being valid looking credentials. You could also give the admin a way to choose a particular service and call to attempt, but that sounds like a great deal more work unless it's chosen by the plugin itself based on what it's trying to do.

**Comment by debora-ito** [comment]
I'll go ahead and close this. Feel free to reopen if you have any other question.
