### ISSUE TITLE
Not Working : As workaround you can use the AWS SDK for Java Bundle as Automatic Java 9 module. The bundle is an Ueber-Jar that contains the whole AWS SDK including it's dependencies (re-packaged); with the bundle I managed to use the aws sdk as automatic Java 9 module.

### ISSUE THREAD

**Issue by panih2o** [aws/aws-sdk-java#2252]
> As workaround you can use the AWS SDK for Java Bundle as Automatic Java 9 module. The bundle is an Ueber-Jar that contains the whole AWS SDK including it's dependencies (re-packaged); with the bundle I managed to use the aws sdk as automatic Java 9 module.
> @see https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bundle

_Originally posted by @orielmaute in https://github.com/aws/aws-sdk-java/issues/1658#issuecomment-430932125_

This isn't working out for me and I get `module not found: aws.java.sdk.bundle` when I try to compile with the bundle specified in my module-info.java. I wasn't able to find any post online for a solution hence opening this issue.

The same error comes in Intellij as well as CLI.

I am using Apache Maven 3.6.2 and aws-java-sdk-bundle-1.11.737.jar and specifying the dependency through the pom.

I would be happy to provide any more details as needed.

**Comment by panih2o** [comment]
Also if is useful  or not.

```
 jar --file ~/.m2/repository/com/amazonaws/aws-java-sdk-bundle/1.11.737/aws-java-sdk-bundle-1.11.737.jar --describe-module
Unable to derive module descriptor for: ~/.m2/repository/com/amazonaws/aws-java-sdk-bundle/1.11.737/aws-java-sdk-bundle-1.11.737.jar
Provider class com.fasterxml.jackson.core.JsonFactory not in module

```

**Comment by debora-ito** [comment]
@panih2o please add your comments in the original post, this way we keep everything in context and avoid duplicate issues.

Feel free to reach out if you have further questions.

**Comment by panih2o** [comment]
@debora-ito This isn't the same issue in my mind. Providing correct package splitting will achieve modularity so will providing the `aws-java-sdk-bundle` as a proper module.

**Comment by VarshaY** [comment]
Hi were you able to solve this
