### ISSUE TITLE
Cognito refresh token - Invalid Token response

### ISSUE THREAD

**Issue by sheshpipra** [aws/aws-sdk-java#2253]
Hello I tried with same thing in java-sdk with version <1.11.360>  with java version 8 
but got the below error

com.amazonaws.services.cognitoidp.model.NotAuthorizedException: Invalid Refresh Token. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: be8a58b5-5a20-4cb6-be21-cb06e5e38159)

here is my code ::

final Map<String, String> authParams = new HashMap<>();
			authParams.put(USERNAME, authenticationRequest.getUsername());
			authParams.put(PASS_WORD, authenticationRequest.getPassword());

			final AdminInitiateAuthRequest authRequest = new AdminInitiateAuthRequest();
			authRequest.withAuthFlow(AuthFlowType.ADMIN_NO_SRP_AUTH)
			.withClientId(cognitoConfig.getClientId())
			.withUserPoolId(cognitoConfig.getPoolId())
			.withAuthParameters(authParams);

			AdminInitiateAuthResult result = cognitoClient.adminInitiateAuth(authRequest);
		
		
		//test the refresh token
		try {

		final Map<String, String> authParams1 = new HashMap<>();
		authParams1.put("REFRESH_TOKEN", result.getAuthenticationResult().getRefreshToken());

		final AdminInitiateAuthRequest authRequest1 = new AdminInitiateAuthRequest();
		authRequest1.withAuthFlow(AuthFlowType.REFRESH_TOKEN).withClientId(cognitoConfig.getClientId())
				.withUserPoolId(cognitoConfig.getPoolId()).withAuthParameters(authParams1);
		AdminInitiateAuthResult result1 = cognitoClient.adminInitiateAuth(authRequest1);
		System.out.println("result " + result1);
		} catch (Exception e) {
			System.out.println(e);
		}
for me I make device tracking is **Always**
please suggest me If I am missing something..

**Comment by debora-ito** [comment]
@sheshpipra have you tried to specify the DEVICE_KEY in the parameters, like is mentioned in the original post you commented?

**Comment by sheshpipra** [comment]
In the first response AdminInitiateAuthResult result. I am not getting DEVICE_KEY parameter so that's why not able to check with it.

**Comment by debora-ito** [comment]
maybe `adminInitiateAuth()` is returning a challenge?

**Comment by sheshpipra** [comment]
It returning below result from AdminInitiateAuthResult
{
  ChallengeParameters: {},
  AuthenticationResult: {
    AccessToken: xxxx,
    ExpiresIn: 3600,
    TokenType: Bearer,
    RefreshToken: xxxx,
    IdToken: xxxx,  
  }
}

**Comment by debora-ito** [comment]
@sheshpipra apologies for the super long silence here. Are you still experiencing this issue?
If so please reply with a comment and I'll investigate.

**Comment by sheshpipra** [comment]
Hi @debora-ito 
From My side, I verified the issue, In AWS document It saying that,

Because it's designed for backend admin implementations, admin authentication flow doesn't support device tracking. When device tracking is enabled, admin authentication succeeds, but any call to refresh the access token will fail.
But in our case, we need the device tracking. 

check below link for more info 
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-server-side-authentication-flow

**Comment by debora-ito** [comment]
Thank you for the follow-up. So device tracking is something Cognito does not support in the admin authentication flow.

I'll go ahead and close this, as there's nothing pending on this issue. Feel free to reach out if you have any other question.
