### ISSUE TITLE
IP address & port w/o scheme in endpoint ⇒ URISyntaxException/IllegalArgumentException from EndpointToRegion.guessRegionOrRegionNameForEndpoint

### ISSUE THREAD

**Issue by jglick** [aws/aws-sdk-java#2255]
## Describe the bug

If you pass a custom endpoint in the format `127.0.0.1:1234` to the SDK, the client builder will fail.

## Expected Behavior

Should behave similarly to if a hostname such as `localhost` is used, or if an IP address is used without an explicit port, or if a full URL with scheme is passed.

## Current Behavior

You get an error such as

```
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:38835
	at java.base/java.net.URI.create(URI.java:883)
	at com.amazonaws.regions.EndpointToRegion.guessRegionOrRegionNameForEndpoint(EndpointToRegion.java:71)
	at com.amazonaws.regions.EndpointToRegion.guessRegionNameForEndpoint(EndpointToRegion.java:41)
	at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:323)
	at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(AmazonS3Client.java:725)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:453)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at …
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:38835
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.checkChar(URI.java:3094)
	at java.base/java.net.URI$Parser.parse(URI.java:3109)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 23 more
```

## Steps to Reproduce

Reproduced in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/112.

## Possible Solution

PR forthcoming.

## Context

Broke integration testing of the Jenkins plugin to store artifacts in S3 against a MinIO mock server running in a local Docker container.
The test passed against 1.11.700 and failed against 1.11.723, with the introduction of `EndpointToRegion`.

## Your Environment

* AWS Java SDK version used: 1.11.700 vs. 1.11.723
* JDK version used: 8 or 11
* Operating System and version: various Linux

**Comment by debora-ito** [comment]
@jglick can you share a code snippet where your `getAmazonS3ClientBuilder()` gets called? Or a self-contained code sample? 

I was not able to reproduce by your bug description, the client builder in my tests does not fail.

**Comment by jglick** [comment]
@debora-ito I think #2256 should cover it. If you want something in a much bigger but more realistic context, I could work up instructions on running the test in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/112/commits/46898c5a2cb9e7b8de3ed2c54fa50c4cc9386a33 or you can just look at a [failure on CI](https://ci.jenkins.io/job/Plugins/job/artifact-manager-s3-plugin/job/PR-112/1/testReport/junit/io.jenkins.plugins.artifact_manager_jclouds.s3/S3BlobStoreConfigTest/linux_11___Build__linux_11____createS3Bucket/) (already quoted above).

**Comment by debora-ito** [comment]
> I could work up instructions on running the test in jenkinsci/artifact-manager-s3-plugin@46898c5

Yes please, I'm hoping to reproduce the problem. A minimal working example would also be good.

**Comment by jglick** [comment]
> A minimal working example

Again, that is best seen in #2256 which reproduces the error as well as offering the fix. To see the bug as it was discovered in the Jenkins plugin, save this to a `Dockerfile` in the current directory and `docker build .`:

```Dockerfile
FROM maven:3.6.3-jdk-8
RUN git clone https://github.com/jenkinsci/artifact-manager-s3-plugin /src
WORKDIR /src

# 1.11.700:
RUN git checkout c46511b15788a5965fd084c4c2295d853aec5e1c^^
RUN mvn -ntp test -Dtest=S3BlobStoreConfigTest\#createS3Bucket
# 1.11.723 with workaround:
RUN git checkout c46511b15788a5965fd084c4c2295d853aec5e1c
RUN mvn -ntp test -Dtest=S3BlobStoreConfigTest\#createS3Bucket
# 1.11.723 without workaround:
RUN git checkout c46511b15788a5965fd084c4c2295d853aec5e1c^
RUN mvn -ntp test -Dtest=S3BlobStoreConfigTest\#createS3Bucket
```

which demonstrates a test passing before the update, breaking after the update, and passing again when a full URL with scheme is used (not in that order).
