### ISSUE TITLE
How to measure request for minute 

### ISSUE THREAD

**Issue by SyCode7** [aws/aws-sdk-java#2261]
I want to gain some insights into the performance of my application that connects to several services in AWS e.g. `IAM `and `S3`. One metric interesting to me is `requests-per-minute,` I have checked around for possible approaches, [AWS Metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-SDK-Metrics.html) is limited to enterprise customers. Another approach is generating Java SDK metrics, via CloudWatch. I have enabled this by adding the command below to the system property

`-Dcom.amazonaws.sdk.enableDefaultMetrics=credentialFile=/path/aws.properties`

I see some metrics in the CloudWatch dashboard, however, there is no request-per-second. I'd like to find out if someone has experience with this or maybe I am missing something.

**Comment by debora-ito** [comment]
@SyCode7 You can use CloudWatch for this. For S3, you need to enable Request Metrics for the bucket you want to monitor (note that request metrics are billed at the standard CloudWatch rate): https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html

For IAM you will probably need to use a combo of CloudTrail and CloudWatch Logs. This doc explains how IAM and STS are integrated with CloudTrail - https://docs.aws.amazon.com/IAM/latest/UserGuide/cloudtrail-integration.html

This blog post shows a concrete example of how to configure alerts of change in IAM configuration, you can use it as a start -
https://aws.amazon.com/blogs/security/how-to-receive-alerts-when-your-iam-configuration-changes/
Again, depending on the CloudTrail set up it may incur additional costs.

Let us know if that helps.

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have further questions or comments.
