### ISSUE TITLE
DynamoDBTypeConverted does not work in DynamoDBDocument fields with List

### ISSUE THREAD

**Issue by sanudatta11** [aws/aws-sdk-java#2262]
I faced a bug when I used a List of custom POJO  for type conversion: DynamoDBTypeConverted using MarshallintoObject

Issue is Similar to #817 but its comprised of a List

`@DynamoDBTypeConverted(converter = ObjectConverter.class)`
    `private List<TransactionPojo> transactions;`

`@Override`
    `public List<TransactionPojo> unconvert(String objectsString) {`
       ` try {`
            `List<TransactionPojo> objects =  objectMapper.readValue(objectsString, new TypeReference<List<TransactionPojo>>(){});`
            `return objects;`
        `} catch (JsonParseException | JsonMappingException e) {`
            `//do something`
            `System.out.println("Json parse exception with object: " + objectsString);`
            `System.out.println(e);`
        `} catch (IOException e) {`
            `//do something`
            `System.out.println("IO exception with object: " + objectsString);`
            `System.out.println(e);`
       ` }`
        `return null;`
    `}`

Error-
`TransactionMain[transactions]; could not unconvert attribute
`
It is reproduced with the latest version of aws-java-sdk

**Comment by debora-ito** [comment]
Can you share the code for `objectMapper.readValue()`?

**Comment by debora-ito** [comment]
Closing due to no response. Feel free to reopen if you have further questions.
