### ISSUE TITLE
Add support for region to ProfilesConfigFile

### ISSUE THREAD

**Issue by nikolay** [aws/aws-sdk-java#227]
The AWS CLI tool supports region in its .ini file. As this file is shared between it and my other tools, I constantly get a warning that the region is skipped as it's not recognized. Instead, you should recognize region, and expose it via a property.

**Comment by nikolay** [comment]
@manikandanrs Any update?

**Comment by shorea** [comment]
We've got an initiative internally to support more of the configuration options that CLI supports. Closing this issue.
