### ISSUE TITLE
How to collect custom tags of AWS ES?

### ISSUE THREAD

**Issue by gangadharaswamy** [aws/aws-sdk-java#2272]
Hello,
I am working on AWS ElasticSearch and able to collect AWS Elasticsearch metrics and dimensions through Cloudwatch SDK `com.amazonaws.services.cloudwatch.model.Metric`, `com.amazonaws.services.cloudwatch.model.Dimension`. I am not able to collect the custom tags configured in the Elasticsearch domain. Is there any option to collect the custom tags via CloudWatch?

**Comment by debora-ito** [comment]
Hi @gangadharaswamy I'm not sure what you mean by collecting custom tags, but if you were hoping to filter metrics by Elasticsearch resource tags I don't think there is a way. The documentation for Amazon Elasticsearch Service Metrics on CloudWatch doesn't list any Dimension - https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-cloudwatchmetrics

As an alternative you could publish your own custom metrics to CloudWatch, for more details: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html

For further questions regarding CloudWatch usage, I suggest you post it in communities like [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=138) or StackOverflow. 

If you have any issues with the AWS SDK for Java, please feel free to reach out.
