### ISSUE TITLE
SES method "listVerifiedEmailAddresses" returns 0 for too many identities

### ISSUE THREAD

**Issue by gelhan** [aws/aws-sdk-java#2273]
AWS SDK Java version: 1.11.710
JRE version: 1.8

For testing purposes, we generated 10,000 SES identities and only two of them were verified. The method "listVerifiedEmailAddresses" returns 0 when called with so many identities in SES. Only with significantly less identities, we get the correct amount of verified identities.

**Comment by debora-ito** [comment]
@gelhan according to its [docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.html#listVerifiedEmailAddresses-com.amazonaws.services.simpleemail.model.ListVerifiedEmailAddressesRequest-) the listVerifiedEmailAddresses method is marked as `Deprecated`, meaning it's obsolete and it should be avoided.

You can use [GetIdentityVerificationAttributes](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.html#getIdentityVerificationAttributes-com.amazonaws.services.simpleemail.model.GetIdentityVerificationAttributesRequest-) instead. In addition, check the methods in [SES V2 client](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemailv2/AmazonSimpleEmailServiceV2Client.html), the listEmailIdentities may be helpful too.

I'll go ahead and closing this. Feel free to reopen if you have further questions.
