### ISSUE TITLE
Get requests are failing with SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by Amarendraar23** [aws/aws-sdk-java#2279]
In one of our setup we are trying to upload and download files to aws s3. PUT operations on this bucket is working fine , but get on the file uploaded is throwing SignatureDoesNotMatch error.

Code used to get file is as below:

```
AmazonS3ClientBuilder s3Client;
s3ClientBuilder = AmazonS3ClientBuilder.standard()
					.withClientConfiguration(proxyConfig)
					.withCredentials(new AWSStaticCredentialsProvider(credentials));  
		
s3ClientBuilder.withRegion("us-east-1");
AmazonS3 s3Client = s3ClientBuilder .build();
TransferManager xfer_mgr = TransferManagerBuilder.standard()
				.withS3Client(s3Client).build();
GetObjectRequest getObjectRequest = new GetObjectRequest(bucketName, key);
xfer_mgr.download(getObjectRequest, f).waitForCompletion();
		
```

Tcpdump trace is attached 
[awss3-signaturedoesntmatch.txt](https://github.com/aws/aws-sdk-java/files/4391284/awss3-signaturedoesntmatch.txt)

I tried regenerating access keys and secret keys which didnt help.
Library used:
```
awssdk/1.11.643/aws-java-sdk-1.11.643.jar
awssdk/1.11.643/httpclient-4.5.9.jar
awssdk/1.11.643/httpcore-4.4.11.jar
awssdk/1.11.643/jackson-annotations-2.6.0.jar
awssdk/1.11.643/jackson-databind-2.6.7.2.jar
```

**Comment by debora-ito** [comment]
@Amarendraar23 Signature mismatch can have several different causes, seeing the message of the error would help in investigating it further.

I see you are using the TransferManager behind a proxy, proxies sometimes change request headers content, which can cause a signature mismatch error.

If the error is with the calculated canonical string, there is a way to troubleshoot it, the wire logs show what would be the expected canonical string by the service. For more details check: https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-canonical-errors

If you choose to provide us your wire logs, please make sure there's no sensitive information.

**Comment by debora-ito** [comment]
Closing this due to no response. Feel free to reopen if you still are experiencing this issue.
