### ISSUE TITLE
amazonS3Encryption.copyObject is not performing Client side encryption 

### ISSUE THREAD

**Issue by thedhrubo** [aws/aws-sdk-java#2289]
I am having a weird problem.
I am using client side encryption to put and copy object to S3 bucket.
Builder is :

```
    @Bean
    public AmazonS3Encryption amazonS3Encryption() {
        return AmazonS3EncryptionClientBuilder
                .standard()
                .withRegion(s3Region)
                .withCredentials(awsS3CredentialProvider())
                .withEncryptionMaterials(odinEncryptionMaterialPairProvider())
                .build();
    }

```
When I use `amazonS3Encryption` for `putObject` then the encryption works : 

```
amazonS3Encryption.putObject(bucketName, path, file);
```

But when I use amazonS3Encryption for copyObject then the client side encryption is not working:

```
amazonS3Encryption.copyObject(missingBucketName, filename, bucketName, path);
```

I checked the s3 bucket, the pdf file copied without any encryption. What am I missing here?

`AmazonS3EncryptionClientBuilder` returns an `AmazonS3EncryptionClient` which does not implement `copyObject`. So I suspect it falls back to the default implementation in AmazonS3Client. 

Is my guess correct?

**Comment by debora-ito** [comment]
> AmazonS3EncryptionClientBuilder returns an AmazonS3EncryptionClient which does not implement copyObject. So I suspect it falls back to the default implementation in AmazonS3Client.

That's correct. As you already noticed the operations implemented by AmazonS3EncryptionClient are listed here: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3EncryptionClient.html

**Comment by debora-ito** [comment]
I'll go ahead and close this, feel free to reopen if you have any more questions.
