### ISSUE TITLE
Java SDK DescribeSnapshots API could not filter based on owner-alias = self

### ISSUE THREAD

**Issue by vincent-van-chen** [aws/aws-sdk-java#2293]
Hi team!

We are using Java SDK to get snapshot list, by using DescribeSnapshots API.
Based on the official documentation:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html
It mentioned that:
For filters, there is one parameter called "owner-alias" - Value from an Amazon-maintained list (amazon | self | all | aws-marketplace | microsoft) of snapshot owners. 
However, when we use owner-alias = self, it is returning an empty list, although we do have snapshots within our account.
Moreover, if we use owner-alias = amazon, it is returning snapshots owned by AWS.
Looks like there is a mis-match between API behavior and API description.

## Steps to Reproduce
public class DescribeSnapshotTest {
    public static void main(String[] args) {
        AmazonEC2 ec2 = AmazonEC2ClientBuilder.defaultClient();
        DescribeSnapshotsRequest request = new DescribeSnapshotsRequest();
        List<Filter> filters = new ArrayList<Filter>();
        Filter ownerFilter = new Filter("owner-alias", Arrays.asList("amazon"));
        filters.add(ownerFilter);
        request.setFilters(filters);
        DescribeSnapshotsResult result = ec2.describeSnapshots(request);
        for(Snapshot snapshot : result.getSnapshots()) {
            System.out.println(snapshot.getSnapshotId());
        }
    }
}

## Your Environment
* AWS Java SDK version used: Currently I am using 1.11.336, but this issue seems working for previous version as well.
* Operating System and version: Windows 2016 Server

**Comment by debora-ito** [comment]
Hi @vincent-van-chen do you get a result if you specify the same ownerID in DescribeSnapshotsRequest#withOwnerIds()  instead of using the owner-alias=self filter?
If you do, can you check what value for owner-alias is being returned in DescribeSnapshotsResult?

**Comment by debora-ito** [comment]
Closing due to no response. Feel free to reopen if you need further assistance.

**Comment by hatchman1976** [comment]
Noticed the same behaviour today. Specifying the owner id works but owner-alias=self just returns an empty list. This is not the same behaviour as the CLI
