### ISSUE TITLE
how to use aws-java-sdk-amplify to login ?

### ISSUE THREAD

**Issue by andreimarius91** [aws/aws-sdk-java#2295]
Hello, we are trying to do a simple login using amplify library but we couldn't find an example/or documentation.
 

## Describe the issue

We want to retrieve the token id generated by AWS when a user is authenticated by Cognito service.
With this token we are building API calls for Rest Services stored in AWS Lambda in order to test the APIs.
We already have the AWS accounts configured and active, UserPool, client id and region and all necessary data.

The issue is that we don't know how to use the Amplify library to authenticate with user,password, clientID.

## Your Environment

* AWS Java SDK version used: 1.11.762
* JDK version used: 1.8
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
Hi @andreimarius91, so Amplify evolved to a separate project, you can find the documentation here: https://aws-amplify.github.io/docs/

If you need further help, you can contact the team in the AWS Amplify github repositories, there's one for each supported language: https://github.com/aws-amplify

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have any further question.
