### ISSUE TITLE
https connection to AWS services could not be establised with openjdk:8-u252

### ISSUE THREAD

**Issue by rlcomte** [aws/aws-sdk-java#2296]
In our Scala/Java service, which accesses Kinesis, SSM and other AWS services, we ran into a SSL connection problem when we used openjdk:8 with the latest u252 change (April 14, 2020). 

## Describe the bug
SSL connection fails with a detailed exception in the Java SSL Client code. 

## Expected Behavior
We expect to create https connections to the abovementioned AWS services.

## Current Behavior
The behavior with openjdk:8 - u242: establishes ssl connections with AWS services
The behavior with openjdk8: - u252: fails to establish ssl connections

After tracking the changes in several places, we suspect that a change with regards to root certificate handling may be the problem.

https://github.com/docker-library/openjdk/commit/e24f1c142d0a2fa1852b5ea899b691483fc72a02
https://wiki.openjdk.java.net/display/jdk8u/Main
http://hg.openjdk.java.net/jdk8u/jdk8u-dev/rev/a013ce3462fc

**Comment by debora-ito** [comment]
@rlcomte can you provide a stacktrace with the error? And a sample code where the error occurs?

**Comment by debora-ito** [comment]
Closing this due to no response. To investigate this further we need to take a look at the logs. Feel free to reopen if you can provide them.
