### ISSUE TITLE
In Lambda custom runtimes propagate the tracing header (Lambda-Runtime-Trace-Id) to env. _X_AMZN_TRACE_ID

### ISSUE THREAD

**Issue by evgenvelgus** [aws/aws-sdk-java#2298]
One of the steps described in Custom AWS Lambda Runtimes:

> Propagate the tracing header – Get the X-Ray tracing header from the Lambda-Runtime-Trace-Id header in the API response. Set the _X_AMZN_TRACE_ID environment variable with the same value for the X-Ray SDK to use.

## Describe the bug
According documentation should be way to set environment variable. But setting environment variables in Java is not supported. 

## Expected Behavior
_X_AMZN_TRACE_ID  should be propagated to env or should be API for setting it. 

## Current Behavior
_X_AMZN_TRACE_ID  = null in custom runtime and no ways to set it

**Comment by evgenvelgus** [comment]
Without _X_AMZN_TRACE_ID  value it is not possible to use X-Ray with custom runtime

**Comment by debora-ito** [comment]
Hi @evgenvelgus you need to set the _X_AMZN_TRACE_ID environment variable in your application environment, this is not something that the SDK for Java can do via API. Wikipedia's article on [Environment Variable](https://en.wikipedia.org/wiki/Environment_variable) has some basic examples showing how to set an environment variable depending on your OS. 

Closing this, but feel free to reopen if you have further questions.
