### ISSUE TITLE
Support Range header in the getObjectRequest like it was in the REST API

### ISSUE THREAD

**Issue by jishah** [aws/aws-sdk-java#230]
Earlier when using the REST API we could pass in Range headers like : 
1. "Range : bytes=0-900"
2. "Range : bytes=0-" 
3. "Range : bytes=-900" 
which were all interpreted correctly by Amazon. When using the SDK we have to specify the start and end of the range explicitly in the GetObjectRequest. In the current state of the API, for cases 2 and 3 , this would require an extra call to get the file size first and then calculate the missing start/end range value. This seems unnecessary given that the REST API already knows how to handle this and that inside the AmazonS3Client class the start and end values are simply used to re-create the HTTP range header. ( https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1099 )

Why is the API not allowing adding in request headers in the GetObjectRequest ? (I can see it supports setting response headers)
Alternatively, the API could allow something like a -1 for the missing start/end range value and interpret that as a blank value when re-creating the HTTP range header. The REST API already knows how to handle the different range header types, why force the user to make an extra call to S3 just to get the file size then ? 

Is there something I am missing here ? Please let me know, thank you !!

**Comment by zhangzhx** [comment]
Now the second case is as a standard API in Java SDK.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/GetObjectRequest.java#L426

**Comment by varunnvs92** [comment]
I see that APIs for cases 1 and 2 are available. I don't see the uniqueness in case 3 as the default beginning will always be 0. So we can use case 1 API. I am resolving this issue. Please feel free to reopen it if you find a strong need for case 3. Thank you.
