### ISSUE TITLE
Having issue accessing us-west-2 bucket from East cluster.

### ISSUE THREAD

**Issue by jsumit5** [aws/aws-sdk-java#2300]
I have a code which is running in east cluster and from there i am trying to access data bucket data of eu-west-1 region.

i have setup the endpoint configuration as below.

def s3 = AmazonS3ClientBuilder.standard()
  .withEndpointConfiguration(new EndpointConfiguration("https://s3.eu-west-1.amazonaws.com","eu-west-1"))
  .withCredentials(new AWSStaticCredentialsProvider(basicSessionCredentials))
  .withPathStyleAccessEnabled(true)
  .build()

s3.getObject(bucket, key).getObjectContent

but i am getting below error.

Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to s3.eu-west-1.amazonaws.com:443 [s3.eu-west-1.amazonaws.com/52.218.41.75] failed: connect timed out

What's wrong i a doing?

**Comment by debora-ito** [comment]
@jsumit5 can you try setting the region instead of the endpoint configuration?

```
s3 = AmazonS3ClientBuilder.standard()
        .withRegion(Regions.EU_WEST_1)
        .withCredentials(new AWSStaticCredentialsProvider(basicSessionCredentials))
        .withPathStyleAccessEnabled(true)
        .build()
```
