### ISSUE TITLE
TooManyRequestsException Cognito

### ISSUE THREAD

**Issue by asyba** [aws/aws-sdk-java#2301]
How I can make the RetryPolicy with BackoffStrategy.
I did this but I'm getting the same error.

``
ClientConfiguration clientConfig = new ClientConfiguration();
clientConfig.setMaxErrorRetry(5);
PredefinedBackoffStrategies.ExponentialBackoffStrategy backoffStrategy = new PredefinedBackoffStrategies.ExponentialBackoffStrategy(3, 27);
clientConfig.
                setRetryPolicy(new RetryPolicy(PredefinedRetryPolicies.DEFAULT_RETRY_CONDITION, backoffStrategy,
                        2, true));
``

``
2020-04-24 18:28:19 xxxxxx WARN  SaveSchoolPartialInfoHandler.handleRequestBody():278 - Too many requests (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: TooManyRequestsException; Request ID: xxxxx)
com.amazonaws.services.cognitoidp.model.TooManyRequestsException: Too many requests (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: TooManyRequestsException; Request ID: xxxxxxxx)
``

**Comment by debora-ito** [comment]
@asyba the arguments for `PredefinedBackoffStrategies.ExponentialBackoffStrategy(3, 27)` are in milliseconds. Cognito API limits are measured in requests per second: https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html

**Comment by asyba** [comment]
> @asyba the arguments for `PredefinedBackoffStrategies.ExponentialBackoffStrategy(3, 27)` are in milliseconds. Cognito API limits are measured in requests per second: https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html

okay, so I need to add bigger values here "(3, 27)" right ?

Is there a way to activate a logger when the backoff Strategy is trigger or something to verfy that is "working" ?
Sorry for asking, but I could not find documentation or example to do this.

**Comment by debora-ito** [comment]
> okay, so I need to add bigger values here "(3, 27)" right ?

Yes. Since the API throttling limit is per second, try to use multiples of 1000 milliseconds.

> Is there a way to activate a logger when the backoff Strategy is trigger or something to verfy that is "working" ?

DEBUG logs will show messages regarding the retries, but I don't think it will explicitly mention it's a backoff strategy.

Let us know if you have any other question.
