### ISSUE TITLE
Payload not sending to Nodejs lambda while invoking from Java based Lambda

### ISSUE THREAD

**Issue by rampatina** [aws/aws-sdk-java#2306]
## Describe the issue
Hi, I was trying to invoke Nodejs based lambda from Java-Based lambda. It is invoking the lambda but the payload is not being sent to Nodejs based lambda.

## Steps to Reproduce
Here is the code for both lambdas:
Nodejs based lambda:
```
module.exports.handler = async (event, context, callback) => {
    console.log('event ', event) // Payload not coming here either event or context
    console.log('context', context)
    const body = JSON.parse(event);
   //Processing and return response
}
```
Java-based lambda:

```
AWSLambda client = AWSLambdaClient.builder().withRegion(region).build();
InvokeRequest().withFunctionName("nodejslambda").withPayload(payload);
InvokeResult result = client.invoke(req);
```
Your help would be greatly appreciated.

## Current Behavior
The payload is not being sent to Nodejs based lambda

## Your Environment
* AWS Java SDK version used: 1.11.569
* JDK version used: 8
* Operating System and version: Mac OS

**Comment by debora-ito** [comment]
@rampatina I could not reproduce the issue, I can see the payload being logged in my tests.

Do you see any error message? How are you checking that the payload is not being sent?

**Comment by rampatina** [comment]
@debora-ito Thanks for looking into the issue.
I have verified in CloudWatch logs for the below statements in nodejs based lambda:
console.log('event ', event) // Returning empty object
console.log('context', context) // Either not being displyed in context

Could you please provide me the example which is working for you. It would be useful for me to find what I was missing.

**Comment by debora-ito** [comment]
I used the same code you provided, with payload
```
String payload = "{\n" +
        " \"name \": \"Foo\",\n" +
        " \"message\": \"Hello from the SDK\"\n" +
        "}";
```

Then I checked the Cloudwatch Logs via AWS Console:
```
START RequestId: xxx Version: $LATEST
2020-05-01T17:10:55.734Z   xxx   INFO	event  { 'name ': 'Foo', message: 'Hello from the SDK' }
2020-05-01T17:10:55.734Z   xxx   INFO	context {
  <context here>
}
END RequestId: xxx
```

Check if you're looking at the same aws region of your lambda function.

**Comment by rampatina** [comment]
Those lambdas are in same region.
I tried with the same payload still getting the same issue. Can you confirm that you are trying to invoke node based lambda from java lambda (be sending payload). If yes could you please share me the repo if possible, it would be helpful to me. Thanks.

**Comment by debora-ito** [comment]
Double check if the CloudWatch client or console is using the same region of the lambda function, and if you are looking at the correct log group.

> Can you confirm that you are trying to invoke node based lambda from java lambda (be sending payload)

Yes, I used your sample code to reproduce. Here's my node.js lambda function:
```
exports.handler = async (event, context, callback) => {
    console.log('event ', event)
    console.log('context', context)

   //Processing and return response
    const response = {
        statusCode: 200,
        body: JSON.stringify(event), //sending back the event in the response
    };
    return response;
};

```

Here's my Java code:
```java
String payload = "{\n" +
        " \"name \": \"Foo\",\n" +
        " \"message\": \"Hello from the SDK\"\n" +
        "}";

AWSLambda client = AWSLambdaClient.builder()
         .withRegion(region)
         .build();

InvokeRequest invokeRequest = new InvokeRequest()
        .withFunctionName(functionName).withPayload(payload);

InvokeResult result = client.invoke(invokeRequest);
```

Since I'm sending back the event in the Lambda function response, I can confirm that the payload is being sent in the first place. I can also confirm I'm seeing the log in CloudWatch like I showed in my previous comment.
