### ISSUE TITLE
1.7.13 - s3 put object response content md5 null

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java#231]
PutObjectResult.getContentMd5 is now null, where before (1.7.12) it returned the content md5. This is without using the new SSE-C feature.
This is a breaking change.

**Comment by l15k4** [comment]
Hi, how come `s3#get` and s3#getObject` returns `s3Object.metadata.getContentMD5` null ? Is `metadata.getContentMD5` only set for `s3.put` ?
