### ISSUE TITLE
How to decrypt with asymmetric keys

### ISSUE THREAD

**Issue by rampatina** [aws/aws-sdk-java#2310]
## Describe the issue
I was trying to decrypt the ciphertext in java based lambda which is encrypted in nodejs based lambda with asymmetric keys and the algorithm used is 'RSAES_OAEP_SHA_256'.
I am getting com.amazonaws.services.kms.model.InvalidCiphertextException and below is the code.
## Steps to Reproduce
```
String ciphertext = "xxxxxxx";
        // Decrypt the data
        System.out.println("Start decryption");
        AWSKMS kmsClient = AWSKMSClientBuilder.standard().withRegion("us-east-1").build();
        ByteBuffer buffer = getByteBuffer(ciphertext);
        DecryptRequest decryptRequest = new DecryptRequest().withCiphertextBlob(buffer);
        DecryptResult decryptResult = kmsClient.decrypt(decryptRequest);
        String plaintext = getString(decryptResult.getPlaintext());
```

```
 private String getString(ByteBuffer byteBuffer) {
        byte[] bytes = new byte[byteBuffer.remaining()];
        byteBuffer.get(bytes);
        return new String(bytes);
    }
```

```
private ByteBuffer getByteBuffer(String string) {
        byte[] bytes = java.util.Base64.getDecoder().decode(string);
        ByteBuffer byteBuffer = ByteBuffer.allocate(bytes.length);
        byteBuffer.put(bytes);
        byteBuffer.flip();

        return byteBuffer;
    }
```

## Current Behavior
Getting com.amazonaws.services.kms.model.InvalidCiphertextException

## Your Environment
* AWS Java SDK version used: 1.11.569
* JDK version used: 8
* Operating System and version: Mac OS

And also please let me know how to set an algorithm to the KMS client. Your help would be greatly appricated.

**Comment by debora-ito** [comment]
@rampatina the algorithm must be specified in the DecryptRequest, see the [Java Doc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/model/DecryptRequest.html#withEncryptionAlgorithm-java.lang.String-) or the [API Reference](https://docs.aws.amazon.com/kms/latest/APIReference/API_Decrypt.html#API_Decrypt_RequestParameters) for more details - the API Reference also has a description for each exception returned by the operation.

Check the AWS KMS [Developer Guide](https://docs.aws.amazon.com/kms/latest/developerguide/overview.html) for more info about KMS, and if you have further questions about the service I suggest you post in the [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=182) to get support from the KMS API team directly.
