### ISSUE TITLE
Need to specify per-object credentials with AmazonS3Client

### ISSUE THREAD

**Issue by tiddman** [aws/aws-sdk-java#2312]
We need to read files from S3 via `AmazonS3Client` but need to provide different credentials for each location i.e. S3 URL because of some cross-account security configurations, so provide credentials for each request rather than the entire client.

## Describe the issue
`AmazonS3Client` can be extended with a `AWSCredentialsProvider`, but that interface only provides this:

    public AWSCredentials getCredentials();

Which provides credentials to the client for all of its requests, not each individual request. Essentially what I need is:

    public AWSCredentials getCredentials(String url);

Where `url` is the S3 URL for the request.

## Current Behavior

Internally in the `AmazonS3Client` I see that the credentials are obtained from the provider in just a few places, really to generate a pre-signed URL and in the private `invoke` method.  These are unfortunately protected and private and so difficult to override or change via configurations or in a subclass. We actually don't need pre-signed URL's for this requirement and just need to read objects from S3.

This is the key line:

[https://github.com/aws/aws-sdk-java/blob/d7476faf01b591d9a557c8c531f763a05f9b1c77/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L5059](url)

Essentially I need a hook to provide my own credentials here for each request.

One option is to essentially fork this code and make the changes but I'd really like to avoid that.

I also saw that `invoke()` calls `AmazonHttpClient` with an `ExecutionContext` that contains he credentials, if there were a way to provide a different HTTP client here that would be another hook. But the execution is buried in the private `AmazonHttpClient .RequestExecutionBuilderImpl` class.

Thanks in advance for any tips or ideas.

As an aside, I am not sure why so many classes are protected and private in these classes, with the source code widely available this just requires that developers who wish to extend the classes in unexpected ways have to fork the code rather than subclass.

## Your Environment
- AWS Java SDK version used: 1.11.199
- JDK version used: 11.0.3
- Operating System and version: Mac Catalina

**Comment by debora-ito** [comment]
Hi @tiddman apologies for the long silence. Have you checked STS [Assume Role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_permissions-to-switch.html)? You could define roles in each account that has S3 buckets and grant one user permission to assume those roles.
