### ISSUE TITLE
doesBucketExistV2 does not validate bucket names with periods

### ISSUE THREAD

**Issue by wamsiv** [aws/aws-sdk-java#2314]
Bucket names which have periods (eg: `foo.build.com`) as delimiters are not identified by `doesBucketExistV2` API.

## Expected Behavior
Should be able to validate if the bucket exists or not.

## Current Behavior
Throws an error:
```
com.amazonaws.services.s3.model.AmazonS3Exception:  code:unavailable  message:failed  to  send  http  proxy  request:  x509:  certificate  is  valid  for  *.s3.amazonaws.com,  s3.amazonaws.com,  not  foo.build.com.s3.amazonaws.com  (Service:  Amazon  S3;  Status  Code:  503;  Error  Code:  ServiceUnavailable;  Request  ID:  d29adc56-fc98-472e-a26a-6ce87a17010d;  S3  Extended  Request  ID:  null)
```

## Steps to Reproduce
- Create a bucket named `foo.build.com`
- Initialize `AmazonS3Client client` and call `client.doesBucketExistV2("foo.build.com")`

## Your Environment

* AWS Java SDK version used: `1.11.257`
* JDK version used: `1.8.0_242`
* Operating System and version:

**Comment by debora-ito** [comment]
@wamsiv bucket names with dots are not recommended by S3. There is a limitation according to [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html):
> Virtual hosted URLs are supported for non-SSL (HTTP) requests only. When using virtual hosted–style buckets with SSL, the SSL wild-card certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic.

**Comment by wamsiv** [comment]
Thank you for the clarification @debora-ito
