### ISSUE TITLE
Publishing messages to a SNS topic randomly fails with "SdkClientException: Unable to execute HTTP request: connect timed out"

### ISSUE THREAD

**Issue by ramnasidharta** [aws/aws-sdk-java#2318]
I'm using the `AmazonSNS` class to publish messages to SNS topics with `AmazonSNS.publish()`. This runs in a lambda function which executes periodically (by 30 minutes). After some attempts it stops working, which "connect timed out" every time.

Error output:
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to sns.us-west-2.amazonaws.com:443 [sns.us-west-2.amazonaws.com/52.119.170.155] failed: connect timed out
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.sns.AmazonSNSClient.doInvoke(AmazonSNSClient.java:2800)
at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2767)
at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2756)
at com.amazonaws.services.sns.AmazonSNSClient.executeListTopics(AmazonSNSClient.java:1792)
```
These are the messages received by a SQS subscribed in the SNS topics in question. Note the four successful publishments starting between 23:00 and 23:30, and ending before 1:00 (other peaks are manual tests).
![image](https://user-images.githubusercontent.com/29432227/81325944-78c27180-906f-11ea-8e5c-15cb17328b45.png)

## Steps to Reproduce
I couldn't reproduce the error. Triggering the lambda manually on the web console, sometimes it works and sometimes not. The issue was identified when performing the publishing with default parameters, but I tried different connectionTimeout, socketTimeout and retries, without success.
```java
AmazonSNSClientBuilder snsBuilder = AmazonSNSClientBuilder.standard()
            .withRegion(Regions.fromName(awsRegion));

ClientConfiguration snsConfiguration = new ClientConfiguration();
snsConfiguration.setConnectionTimeout(TIMEOUT);
snsConfiguration.setSocketTimeout(TIMEOUT);

AmazonSNS sns = snsBuilder.withClientConfiguration(snsConfiguration).build();
sns.publish(topic, message, subject);
```

## Details
I also tried to write the same lambda function in Python, using boto3, and got the same weird behavior.

Locally I never got the error when running the publish locally.

The lambda in within a VPC, because it accesses a database.

AWS Java SDK version used: 1.11.576

## References
It seems that similar problems happen while accessing other AWS resources like S3 buckets or dynamo table.

- https://github.com/boto/boto3/issues/2045
- https://stackoverflow.com/questions/60272233/why-does-boto-3-occasionally-timeout-connecting-to-sns
- https://github.com/aws/aws-sdk-java/issues/1405
- https://github.com/aws/aws-sdk-java/issues/269
* JDK version used: 11

**Comment by GianaAlmeida** [comment]
[2]

**Comment by GianaAlmeida** [comment]
[2] Same error

**Comment by debora-ito** [comment]
@ramnasidharta apologies for the long silence here. `Connect timed out` errors are likely due to network connectivity issues or service high latency, seeing you are not able to reproduce and you've had similar problems with a lambda function in python seems to confirm that.

The best thing would be to [enable wire logs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) to gather more information about the requests and responses, and try to increase the connection timeout in the ClientConfiguration like you showed in the steps to reproduce.

**Comment by ramnasidharta** [comment]
@debora-ito thanks for the answer. I solved by setting up a PrivateLink, for connecting the lambda to an SNS. So the question that remains is why it worked sometimes? The lambda has four subnets, two private and two public. I imagined that maybe in the times the time out happened, the lambda was instantiated within a private subnet, and in the other times the problem didn't happen because the lambda was instantiated in a public subnet. Is that a possibility?

**Comment by debora-ito** [comment]
Hi @ramnasidharta I'm glad you've solved the issue. It's hard to pinpoint exactly the cause for the timeout exceptions without knowing the specifics of the environment. If you start seeing the errors again feel free to reach out and we'll investigate.
