### ISSUE TITLE
Milan region is not included in Regions.java

### ISSUE THREAD

**Issue by subodhiitr** [aws/aws-sdk-java#2322]
## Describe the bug
Milan region is not included in below file
aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java

## Expected Behavior
Milan region should be included in enumerator defined in Regions.java

## Your Environment

*  AWS Java SDK version used:1.11.780

**Comment by debora-ito** [comment]
Thank you for reaching out @subodhiitr. We add the new region.

**Comment by debora-ito** [comment]
Milan (eu-south-1) is now available in Regions.java, in SDK version `1.11.783`.
