### ISSUE TITLE
DynamoDBMapper.marshallIntoObject leads to false boolean value

### ISSUE THREAD

**Issue by adamcodes** [aws/aws-sdk-java#2323]
When using `marshallIntoObject` where the target class contains a boolean variable prefixed with `is` the mapped value always gets set to false.

## Describe the bug
Model class contains the following:
`  @DynamoDBAttribute(attributeName = "IA")
    private boolean isActive;
`
DynamoDB stream record contains:
`IA -> "{BOOL: true}`

Results:
isActive = false 

If model class is changed to:
`  @DynamoDBAttribute(attributeName = "IA")
    private boolean active;
`
With same stream record values then results is:
active = true

## Expected Behavior
Expect isActive should be true when attribute is IA -> "{BOOL: true}"

## Current Behavior
isActive is set to false

## Steps to Reproduce
Create model with class variable prefixed with "is" using camelCase.

## Possible Solution
Work-around is to remove "is" from variable name

## Context
Attempting to map DynamoDB stream record to model
`
DynamoDBMapper mapper = new DynamoDBMapper(getConfig().getAmazonDynamoDb());
Map<String, AttributeValue> newImageMap = record.getDynamodb().getNewImage();
Message message = mapper.marshallIntoObject(message.class, newImageMap);
`

## Your Environment
* AWS Java SDK version used: 1.11.756
* JDK version used: 11
* Operating System and version: macOS 10.15.4

**Comment by debora-ito** [comment]
Hi @adamcodes I was not able to reproduce the issue. Here's the content of one of the records in my tests:
```
(...)
        "dynamodb": {
                "ApproximateCreationDateTime": xxx,
                "Keys": {
                    "id": {
                        "N": "2"
                    }
                },
                "NewImage": {
                    "director": {
                        "S": "Edgar Wright"
                    },
                    "id": {
                        "N": "2"
                    },
                    "IA": {
                        "BOOL": true
                    },
                    "title": {
                        "S": "Scott Pilgrim vs. the World"
                    },
                    "year": {
                        "N": "2010"
                    }
                }
(...)
```

My DDBMapper class:
```java
@DynamoDBTable(tableName = "my-movies")
    public static class MyMovie {
        @DynamoDBHashKey(attributeName = "id")
        private Long id;
        private String title;
        private String director;
        private Long year;

        @DynamoDBAttribute(attributeName = "IA")
        private Boolean isActive;
(...)
```

and here's my test code :
```java
GetRecordsResult getRecordsResult = streamsClient.getRecords(new GetRecordsRequest()
                .withShardIterator(currentShardIter));
List<Record> records = getRecordsResult.getRecords();
for (Record record : records) {
        Map<String, AttributeValue> newImageMap = record.getDynamodb().getNewImage();
        MyMovie movie = mapper.marshallIntoObject(MyMovie.class, newImageMap);
        System.out.println("====> " + movie.getIsActive());
}
```
The test code prints `====> true`.

Can you provide a full, reproducible sample code, including the DynamoDB item values?
