### ISSUE TITLE
ClientConfiguration should ignore lack of proxy user & password

### ISSUE THREAD

**Issue by radeklesniewski** [aws/aws-sdk-java#2326]
Hello, I'm using java sdk version 1.11.767 and I have a problem with using ClientConfiguration without password authentication for proxy. My application is running on server with configured HTTP_PROXY & HTTPS_PROXY envs in format "host:port" and my ClientConfiguration looks like this:

`ClientConfiguration config = new ClientConfiguration().withProtocol(Protocol.HTTPS)
.withProxyHost(proxyHost)
.withProxyPort(proxyPort);
`

When ClientConfiguration is initialized and proxyUsername & proxyPassword vars are null, ClientConfiguration tries to retrieve username/password from HTTP_PROXY env variable which is in format "host:port" and it causes MalformedUrlException to be thrown. Is there any way to configure ClientConfiguration to not load proxy credentials from environment variables?

Expected Behavior:
ClientConfiguration should ignore lack of proxy username & password.

Current Behavior:
ClientConfiguration loads username/password from environment variables and exception is thrown.

Stacktrace:
```
16:07:35 2020-05-05 14:07:35 WARN [main][1] ClientConfiguration - Unable to parse HTTPS_PROXY environment variable value 'proxyhost:port' as URL. It is malformed.
16:07:35 java.net.MalformedUrlException: unknown protocol: proxyhost
16:07:35 at java.net.URL.<init>(URL.java:600) ~[?:1.8.0_162]
16:07:35 at java.net.URL.<init>(URL.java:490) ~[?:1.8.0_162]
16:07:35 at java.net.URL.<init>(URL.java:439) ~[?:1.8.0_162]
16:07:35 at com.amazonaws.ClientConfiguration.getUrlEnvVar(ClientConfiguration.java:2488) ~[aws-java-sdk-core-1.11.767.jar:?]
16:07:35 at com.amazonaws.ClientConfiguration.getHttpProxyEnvironmentVariable(ClientConfiguration.java:2479) ~[aws-java-sdk-core-1.11.767.jar:?]
16:07:35 at com.amazonaws.ClientConfiguration.getProxyPasswordEnvironment(ClientConfiguration.java:966) ~[aws-java-sdk-core-1.11.767.jar:?]
16:07:35 at com.amazonaws.ClientConfiguration.getProxyPassword(ClientConfiguration.java:998) ~[aws-java-sdk-core-1.11.767.jar:?]
16:07:35 at com.amazonaws.ClientConfiguration.<init>(ClientConfiguration.java:389) ~[aws-java-sdk-core-1.11.767.jar:?]
```

**Comment by SamBumgardner** [comment]
Based on this line of your stacktrace
```
16:07:35 java.net.MalformedUrlException: unknown protocol: proxyhost
```
I think that the actual problem is that ClientConfiguration expects the HTTP_PROXY variable to include the protocol in addition to the host and port. I expect that something formatted like this should work: `http://proxyhost:port`

**Comment by debora-ito** [comment]
Hi @radeklesniewski, does @SamBumgardner's suggestion work in your case?
