### ISSUE TITLE
How to call API Gateway (Post) from Java without using Java-sdk

### ISSUE THREAD

**Issue by sau0201** [aws/aws-sdk-java#2329]
## Describe the issue

I generated the SDK for my API. But I don't want to use it. The reason is, if I change my API (mapping template or model), I feel like I have to generate SDK again and use it. 

Can I not call API using HTTP client like how you call normal rest API. I understand that I need to provide credentials in a different way. 

Can you help

**Comment by debora-ito** [comment]
@sau0201 There are several ways to invoke your API, please refer to the API Gateway documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-call-api.html

For service specific questions like this we recommend you post it in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=199&start=0) or in communities like StackOverflow.

If you have any questions or issues regarding the AWS SDK for Java, feel free to reopen.
