### ISSUE TITLE
JsonDocumentFields does not support NotAction when parsing organization-level service control policies

### ISSUE THREAD

**Issue by jkoe-r7** [aws/aws-sdk-java#2330]
## Describe the bug

When parsing an org-level SCP using Policy.fromJson(), the policy id, effect, resource, and condition fields are parsed correctly but the NotAction field is not picked up because it is not in the list of JsonDocumentFields constants.

## Expected Behavior
{"Version":"2012-10-17","Statement":[{"Sid":"LimitActions","Effect":"Deny","NotAction":["ec2:*","organizations:*","sts:*"],"Resource":"*","Condition":{"StringNotEquals":{"aws:RequestedRegion":"us-east-1"}}}]} 

after being parsed into a Policy object then parsed back into JSON should contain the same NotAction values instead of omitting like so:

{"Version":"2012-10-17","Statement":[{"Sid":"RequireInEuWest1","Effect":"Deny","Resource":["*"],"Condition":{"StringNotEquals":{"aws:RequestedRegion":["us-east-1"]}}}]}

## Current Behavior
{"Version":"2012-10-17","Statement":[{"Sid":"LimitActions","Effect":"Deny","NotAction":["ec2:*","organizations:*","sts:*"],"Resource":"*","Condition":{"StringNotEquals":{"aws:RequestedRegion":"us-east-1"}}}]}  

is transformed into ->  

{"Version":"2012-10-17","Statement":[{"Sid":"RequireInEuWest1","Effect":"Deny","Resource":["*"],"Condition":{"StringNotEquals":{"aws:RequestedRegion":["us-east-1"]}}}]}

## Steps to Reproduce
Create an org-level service control policy with a Deny statement that contains the NotAction field. Call Policy.fromJson() on a String containing the policy text, then call Policy.toJson() to see what the output is and if it is identical.

## Possible Solution
Either include parsing NotAction field in the fromJson parser/JsonDocumentFields constants or provide separate parser specifically for parsing org-level policies which can have the NotAction field.

## Context
I'm trying to see how much access service control policies will allow a specific IAM role before using the role to perform actions.

## Your Environment

* AWS Java SDK version used: 1.11.774
* JDK version used: 1.8
* Operating System and version:

**Comment by debora-ito** [comment]
@jkoe-r7 thank you for reporting this, I was able to reproduce. It's funny that `NotResource` is implemented, but `NotAction` and `NotPrincipal` elements are not.

**Comment by karanb192** [comment]
I'm also facing this and it's quite misleading.

**Comment by ShutUpChips15** [comment]
I'm facing this problem as well, any idea on timeline to fix bug or a work around?

**Comment by debora-ito** [comment]
Hi @jkoe-r7 @karanb192 @ShutUpChips15  

We apologize but this won't get fixed in v1.  If this is still an issue on [IAM Policy Builder v2](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/policybuilder/iam/IamPolicy.html), please let us know and put the repro case details in a new [aws/aws-sdk-java-v2 issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose).

#### Reference:
- [Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
