### ISSUE TITLE
ECS to ECS protection

### ISSUE THREAD

**Issue by gituserjava** [aws/aws-sdk-java#2331]
Are there any mechanisms to grant access to ECS service only from another specific ECS without the use of Security Groups?

Can we achieve this with AWS IAM roles?

**Comment by debora-ito** [comment]
@gituserjava we don't have the expertise to answer service specific questions. I recommend you ask in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187) or communities like StackOverflow to get more specialized support.

If you have any questions related to the AWS SDK for Java, feel free to reopen.
