### ISSUE TITLE
Recover from "IllegalStateException: Connection pool shut down"

### ISSUE THREAD

**Issue by martinth** [aws/aws-sdk-java#2337]
I think I'm currently running into the same (or at least related) issue to #1282. 

We use the same AmazonS3 instance for a long time (essentially the full runtime of the service which measures in days to weeks) by providing it as a Bean in our Spring Boot application. Since the client is documented as thread safe and no documentation states we assumed that is safe.

The application processes images and pdfs and can sometimes run into an OOM situation. This is generally dealt with and the application does recover from it. However, it seems that this triggers a non-recoverable condition in the S3 client. #1282 pointed me to [apache/httpcomponents-client@ca98ad6](https://github.com/apache/httpcomponents-client/commit/ca98ad69adad79de57d8b944ba524f7267a795cb) and I think this is the root cause: Our application itself might recover but the connection pool is shut down. Now, I can't really argue with the behaviour of `httpclient` since their argument is solid for doing what they do but I still need a way out of this.

What would be the "proper" way to handle this from the standpoint of `aws-sdk-java`? I have some ideas but none seem really good:

- Don't reuse the `AmazonS3` instance but re-create it for each request. I have seen code like this floating aroung but I'm not sure on the costs of re-creating a client for each request. And I'm not even sure that this would fix it since it *looks* like the underlying connection pool is still shared.
- Call `AmazonS3.shutdown` when I run into the `IllegalStateException`. After looking at the code that *seems*  to propagate down to the connection pool and that it will close it. But then what? Will a new pool be automatically created? And I would need to do that on every call site which would make the code rather ugly.
- Limit the lifetime of the `AmazonS3` instance in my application and periodically create a new one, manually calling `shutdown` on the old on. But that would them effect also ongoing connections. And it wouldn't really solve the problem for the time after the pool is shutdown and a new one is created but at least the application will recover eventually.
- Just give up, not handle the OOM condition and lets kubernetes restart my pod.

**Comment by debora-ito** [comment]
Hi @martinth, thank you for bringing this to our attention. 

Creating one client per request is strongly recommended against. The best option would be letting kubernetes restart the whole application, as there's not a really safe way to recover from the connection pool shutting down. But we agree this is not a great user experience.

Option n.3 is a good one too, and you can add auto-scalling features and application-level QoS filters to avoid ever encountering OOM conditions.

**Comment by meshuga** [comment]
@martinth Surpassing any Java `Error` is not a recommended practice as it makes your application nondeterministic. All errors are non-recoverable problems.

**Comment by demetrio812** [comment]
Hello, I'm having the same issue and frankly having to restart the pod just for this reason seems a very bad solution, limiting the instance lifespan and calling shutdown if frankly another bad solution as it will stop ongoing connection.

Is it really something that cannot be avoided? In my case I'm not seeing any OOM error in my logs

Can we please reopen this issue?

**Comment by IHarperCircle** [comment]
I am in a similar boat to @demetrio812 where we are encountering this error but no OOM errors. For us we have an ECS service that runs scheduled queries on Athena. We think the issue occurs when many queries try to execute at once, and we get "rate limited" by this error, in a sense. We are still investigating but any insight would be helpful

**Comment by adadelta** [comment]
Is there room for more on this boat @IHarperCircle & @demetrio812? Having the same issue.

**Comment by ragnar-lothbrok** [comment]
@adadelta I am also facing the same issue with SQS which internally using AmazonHttpClient.

**Comment by IHarperCircle** [comment]
We think we have resolved this issue in our case by increasing the memory allocated to our ECS cluster.

We think the root cause was lack of JVM heap space which was causing failures during garbage collection, even though we did not see any OOM errors in our logs. We have increased the memory and CPU on our ECS cluster and have not seen any issues since.

**Comment by meshuga** [comment]
If you use Java 11 or recent 8, I recommend using -XX:MaxRAMPercentage parameter with value 70 if having around 1 GB assigned to a service. It'll ensure your app can reserve up to 700 MB for heap and leave 300 MB for other parts of memory (should be enough for basically all cases).

**Comment by spathoori** [comment]
@ragnar-lothbrok ,Did you solve connection pool issue with SQS client by any chance . We also facing same issue when using with JMSListener

**Comment by ragnar-lothbrok** [comment]
@spathoori  No I am still getting the same issue after increasing heap size to 65% and I can see heap space is available.

**Comment by stefanrybacki** [comment]
What is it with this auto closing issue even if they are not resolved?

**Comment by peterwoodworth** [comment]
Reopening since issue seems unresolved

**Comment by muhammadsr** [comment]
Same issue. Getting this error with `AmazonDynamoDBClient`. Did anyone figure this out?

**Comment by rlconst** [comment]
began receiving this error after customizing retry strategy, not sure if related

**Comment by nsvijay04b1** [comment]
Any working code sample how to use credentials or refresh so that it still works after 1 hr , please ?

I see similar issues are closed without a working solution suggested but answering this is expected behavior.

Error:- java.lang.IllegalStateException: Connection pool shut down

Code:-

try(CloudWatchClient cw = CloudWatchClient.builder().region(region).credentialsProvider(DefaultCredentialsProvider.create()).build()){

// code
