### ISSUE TITLE
Remove JodaTime dependency

### ISSUE THREAD

**Issue by jonfreedman** [aws/aws-sdk-java#2338]
## Describe the Feature
The parent pom declares jre.version = 1.6 and aws-java-sdk-core has a dependency on joda-time 2.8.1.
Java 6 was EOL in 2013 and the java.util.time classes in Java8 have superceeded joda-time.

**Comment by debora-ito** [comment]
Hi @jonfreedman, although we understand the issue, we cannot drop support for Java 6 and remove the dependency due to backward compatibility. 

As a comparison, the SDK for Java v2 removed the JodaTime dependency from the beginning.

**Comment by jonfreedman** [comment]
I see, could I please make a suggestion that the first line on the readme for v1 mentions the fact there is a v2?

**Comment by debora-ito** [comment]
Sure, we will add a note to the v1 README.

**Comment by debora-ito** [comment]
A section about AWS SDK for Java 2.x was added to the README: https://github.com/aws/aws-sdk-java/blob/master/README.md#aws-sdk-for-java-2x

Closing this. Feel free to reach out if you have any other comments.
