### ISSUE TITLE
java.net.UnknownHostException: kinesis.ap-southeast-1.amazonaws.com

### ISSUE THREAD

**Issue by hanzalaAmway** [aws/aws-sdk-java#2339]
java.net.UnknownHostException: kinesis.ap-southeast-1.amazonaws.com
Unable to execute HTTP request: kinesis.ap-southeast-1.amazonaws.com 
## Describe the issue
when we doing rest post call we are getting below error :
java.net.UnknownHostException: kinesis.ap-southeast-1.amazonaws.com
## Steps to Reproduce
we are getting intermediate issue 
when we doing rest post call we are getting below error :
java.net.UnknownHostException: kinesis.ap-southeast-1.amazonaws.com

We have set this property networkaddress.cache.ttl=60 .But still we are seeing intermediate issues.Can you please let us know ,if we need to use any particular JVM version

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode) .
uname:Linux
 uname -r  :2.6.32-754.24.3.el6.x86_64

**Comment by debora-ito** [comment]
Hi @hanzalaAmway can you provide a code snippet where you create the kinesis client and call the API? And please also provide the full stacktrace with the error.

**Comment by hanzalaAmway** [comment]
Hi Debora,

We are connecting to the URL through Webmethods Tools (EAItool).We are connecting through http/https call .this error very intermediate in last 15 days we did see this error .

**Comment by debora-ito** [comment]
In this case I recommend you contact the WebMethods Tools team for help, as there's not much I can do without knowing how they use the SDK in their underlying implementation.

If you can reproduce the error accessing the Kinesis API directly using the Java SDK and can provide a reproducible code, feel free to reopen.
