### ISSUE TITLE
Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.

### ISSUE THREAD

**Issue by perlics** [aws/aws-sdk-java#2341]
## Description
I'm trying to upload an image to S3 from an Android client. I get the exception from the title. I want to mention that images are fully uploaded but the response I get is 'FAILED'

I manually calculated two md5 sums (uploaded image and selected image for upload) and sums match.

I want to add that images over 5MB return COMPLETED. This is only happening with images under 5MB in size.

I want to remind you that 5MB is the lowest treshold for issuing a multipart request. So when I debugged the TransferUtility class, I concluded that the library issues a multipart request whenever it can.

This implementation has worked for months and suddenly has stopped. I am actively working on finding out if the issue was induced by a side effect.

## Expected Behavior
Image should be uploaded and the response should be COMPLETED.

## Current Behavior
Image is uploaded (can be found on S3 and downloaded from it) but the response I get from S3 is 'FAILED'

* AWS Java SDK version used: 2.13.1
* Operating System and version: Wide span of Android versions and devices

**Comment by debora-ito** [comment]
@perlics are you using the AWS SDK for Android? If so, you should open an issue in their repository: https://github.com/aws-amplify/aws-sdk-android
