### ISSUE TITLE
When ec2 metadata service is not available the exception is logged

### ISSUE THREAD

**Issue by giova333** [aws/aws-sdk-java#2345]
There are situations where developers need to identify whether their application is running on AWS environment or not. `EC2MetadataUtils` is a perfect class for identifying that. However, when trying to access ec2 metadata service through this class outside the ec2 instance, the exception is logged in `InstanceMetadataServiceResourceFetcher.handleException`.
The developers should be able to manage such cases themselves, handling the thrown exception,
without having the original exception logged.

**Comment by debora-ito** [comment]
@giova333 I am not fully clear on what is the ask, can you give some examples?
