### ISSUE TITLE
DefaultAWSCredentialsProviderChain documentation does not match code

### ISSUE THREAD

**Issue by rymndhng** [aws/aws-sdk-java#2346]
The javadoc of `DefaultAWSCredentialsProviderChain ` does not match the priority defined in the code.

## Describe the issue
The `WebIdentityTokenCredentialsProvider` should be documented higher up the priority list to match the code.

Note, there are already three PRs created for this.
- https://github.com/aws/aws-sdk-java/pull/2327
- https://github.com/aws/aws-sdk-java/pull/2297
- https://github.com/aws/aws-sdk-java/pull/2139

## Links

See https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by debora-ito** [comment]
Noted, will work on fixing the docs this week.

**Comment by debora-ito** [comment]
Javadoc updated in `1.11.798`. Thank you!
