### ISSUE TITLE
Fix Topics util overwriting sqs policy

### ISSUE THREAD

**Issue by monish-cashify** [aws/aws-sdk-java#2347]
If we pass extendPolicy true then same policy is added multiple times.

I got to know when it reached limit exception of 20.

So there should be one mechanism is extended truw then it should not add again is it is already added.

**Comment by debora-ito** [comment]
Hi @monish-cashify Not sure if I understand the issue. Can you clarify, showing a code sample of what you are trying to achieve?

**Comment by monish-cashify** [comment]
CreateQueueResult queueUrlResult = amazonSQSAsync.createQueue(env + "_" + serviceName);
    String queueUrl = queueUrlResult.getQueueUrl();

    String subscriptionArn = Topics
        .subscribeQueue(amazonSNSAsync, amazonSQSAsync, getTopicName(service), queueUrl, true);

    try {
      if (filter != null) {
        SetSubscriptionAttributesRequest attributesRequest = new SetSubscriptionAttributesRequest(
            subscriptionArn, "FilterPolicy", mapper.writeValueAsString(filter));
        amazonSNSAsync.setSubscriptionAttributes(attributesRequest);
      }
    } catch (JsonProcessingException e) {
      logger.error("Error in adding filter in service {}", serviceName);
    }

**Comment by monish-cashify** [comment]
@debora-ito Can you please help me out, getting this fixed.

**Comment by debora-ito** [comment]
@monish-cashify thank you for the code sample, I can see how you would expect the policy not to be added again if it was added before. I'm marking it as a feature request to add a verification.

**Comment by monish-cashify** [comment]
@debora-ito Can you please help me out to fix this asap.

Is their any way to fix this from my side.
