### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset

### ISSUE THREAD

**Issue by srikanth550** [aws/aws-sdk-java#2349]
I am trying to use spring cloud config server with s3 as backend. And I am using proxy connection and ProfileCredentialProvider for S3Client which uses default credentials which is stored in .aws/credentials file.

Got this exception when connecting to s3 bucket 

com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset

There is not stack trace for this issue  and I got this message when I debug spring cloud config server API.

Please help me with this issue. Thank you.

**Comment by debora-ito** [comment]
Without a stacktrace is hard to further investigate the case. We cannot see what threw the exception, or if there was any extra information in the error.

Connection resets are likely caused by networking issues, see this comment from a previous issue reported: https://github.com/aws/aws-sdk-java/issues/1838#issuecomment-447046405

**Comment by srikanth550** [comment]
Here is the stack trace 

```
stackTrace = {StackTraceElement[25]@5621} 
 0 = {StackTraceElement@5624} "com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1136)"
 1 = {StackTraceElement@5625} "com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1082)"
 2 = {StackTraceElement@5626} "com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)"
 3 = {StackTraceElement@5627} "com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)"
 4 = {StackTraceElement@5628} "com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)"
 5 = {StackTraceElement@5629} "com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)"
 6 = {StackTraceElement@5630} "com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)"
 7 = {StackTraceElement@5631} "com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)"
 8 = {StackTraceElement@5632} "com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443)"
 9 = {StackTraceElement@5633} "com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390)"
 10 = {StackTraceElement@5634} "com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1427)"
 11 = {StackTraceElement@5635} "org.springframework.cloud.config.server.environment.AwsS3EnvironmentRepository.getS3ConfigFile(AwsS3EnvironmentRepository.java:139)"
 12 = {StackTraceElement@5636} "org.springframework.cloud.config.server.environment.AwsS3EnvironmentRepository.getS3ConfigFile(AwsS3EnvironmentRepository.java:120)"
 13 = {StackTraceElement@5637} "org.springframework.cloud.config.server.environment.AwsS3EnvironmentRepository.findOne(AwsS3EnvironmentRepository.java:87)"
 14 = {StackTraceElement@5638} "org.springframework.cloud.config.server.environment.EnvironmentRepository.findOne(EnvironmentRepository.java:31)"
 15 = {StackTraceElement@5639} "org.springframework.cloud.config.server.environment.EnvironmentRepositoryPropertySourceLocator.locate(EnvironmentRepositoryPropertySourceLocator.java:55)"
 16 = {StackTraceElement@5640} "org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)"
 17 = {StackTraceElement@5641} "org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)"
 18 = {StackTraceElement@5642} "org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98)"
 19 = {StackTraceElement@5643} "org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)"
 20 = {StackTraceElement@5644} "org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)"
 21 = {StackTraceElement@5645} "org.springframework.boot.SpringApplication.run(SpringApplication.java:314)"
 22 = {StackTraceElement@5646} "org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)"
 23 = {StackTraceElement@5647} "org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)"
 24 = {StackTraceElement@5648} "com.example.demo.DemoClientApplication.main(DemoClientApplication.java:11)"
```

**Comment by srikanth550** [comment]
@debora-ito Have you got a chance to look at this issue. Let me know How I can set amazon profile. It is using default profile always when connecting to s3.

**Comment by debora-ito** [comment]
@srikanth550 I'm sorry for the long pause, have you got it working?
Are you able to call any other S3 operation behind the proxy?
As I said before, connection resets are likely caused by network connectivity issues, like proxy or firewall configurations.

If you are still seeing this issue, if you enable [wire logs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) you may get additional info about the requests. If you provide us the wire logs, make sure there's no sensitive data like your access key id.

**Comment by romelabed** [comment]
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import java.io.File;
import java.io.IOException;

public class UploadObject {

    public static void main(String[] args) throws IOException {
        Regions clientRegion = Regions.US_EAST_1;

        String fileObjKeyName = "N.pdf";
        String fileName = "C:\\home\\aws\\N.pdf";
        String accessKeyId = "YVWD3IEQWI";
        String secretAccessKey = "RwYefIavQ3gFvZUdUn";
        String bucketName = "fioprod-s3-addon-us-east-1/s3-bucket";
        try {
            final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(accessKeyId, secretAccessKey);
            AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                    .withRegion(clientRegion)
                    .withCredentials(new AWSStaticCredentialsProvider(basicAWSCredentials))
                    .build();
            PutObjectRequest request = new PutObjectRequest(bucketName, fileObjKeyName, new File(fileName));
            ObjectMetadata metadata = new ObjectMetadata();
            metadata.setContentType("plain/text");
            metadata.addUserMetadata("title", "someTitle");
            request.setMetadata(metadata);
            s3Client.putObject(request);
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
}

The above code is working as expected to load the file into the S3 bucket - I think this is path style; But as per https://docs.amazonaws.cn/en_us/AmazonS3/latest/dev/VirtualHosting.html#virtual-hosted-style-access , path style access will be depreciated by amazon; How do I convert the above code to load the file into S3 in virtual hosted style?

Thank you.
