### ISSUE TITLE
Use S3 Select against a versioned bucket

### ISSUE THREAD

**Issue by kevin-looft** [aws/aws-sdk-java#2357]
When using S3 select you cannot specify a version ID on the request, which means you cannot run the select query against any version but the latest. We would like to be able to select against historical versions.

## Describe the Feature

Be able to specify a version ID when using the `SelectObjectContentRequest`

## Is your Feature Request related to a problem?

Unable to use versioning in my case since I prefer to use S3 Select

## Proposed Solution

Support version ID on `SelectObjectContentRequest`

## Describe alternatives you've considered

Not available in the console either

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @kevin-looft this is a feature request for the service team, I will forward it to the S3 Select team. Will post here when they reply.

**Comment by debora-ito** [comment]
@kevin-looft the S3 Select responded, and there is a way to specify the versionId if you add it as a custom query param to the request:

```
SelectObjectContentRequest selectRequest = new SelectObjectContentRequest()
    .withBucketName(BUCKET)
    .withKey(KEY)
    .withExpression("SELECT count(*) from S3Object s")
    .withExpressionType(ExpressionType.SQL)
    .withInputSerialization(...)
    .withOutputSerialization(...);

selectRequest.putCustomQueryParameter("versionId", "xxx");
```

I asked them to add this info in the S3 Select documentation.
