### ISSUE TITLE
To change all agent status through a lamda function

### ISSUE THREAD

**Issue by arunthinagaran** [aws/aws-sdk-java#2358]
Hi 
Is there an class or API though which I can change the status of All agents using an Lamda funtion?

As far i know the connect stream api is used to change the status of currently logged in user.

I dont find any option on console to change all agent status at once. But there are options to change individual agent status. The requirement is to change all agent status to offline end of day

**Comment by debora-ito** [comment]
Hi @arunthinagaran I don't see a batch operation available in [AWS Connect API Reference](https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations.html) to change all the agents status programatically. This issue in the Connect Streams repo mentions that it's only possible to set an agent status for the currently authenticated user: https://github.com/amazon-connect/amazon-connect-streams/issues/150

Supervisors can manually change an agent status in the Real-Time Metrics page, according to the docs: https://docs.aws.amazon.com/connect/latest/adminguide/rtm-change-agent-activity-state.html

For further service specific questions I suggest you post in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=249&start=0) to get support from the service team.
