### ISSUE TITLE
Error 403 on getDASHStreamingSessionURL

### ISSUE THREAD

**Issue by pabloedm** [aws/aws-sdk-java#2359]
Hey guys, 

Im trying to retrieve the streaming url from a stream. 
credentials and config are configure as follow:
`[default]
region = us-east-1`
`[default]
aws_access_key_id = XXXXXXXX
aws_secret_access_key = XXXXXXXXXX`

then I configured my bean:
`    @Bean
    public AmazonKinesisVideoArchivedMediaClient buildAmazonKinesis() {
        return (AmazonKinesisVideoArchivedMediaClient) AmazonKinesisVideoArchivedMediaClientBuilder.defaultClient();
    }`

and Im trying to get the stream using this:
`GetDASHStreamingSessionURLResult result = kinesis.getDASHStreamingSessionURL(new GetDASHStreamingSessionURLRequest().withStreamName(streamName));`

so Im getting the following error:
`com.amazonaws.services.kinesisvideo.model.AmazonKinesisVideoException: null (Service: AmazonKinesisVideoArchivedMedia; Status Code: 403; Error Code: null; Request ID: 7972d98a-a43e-44e8-bb18-0028ddf8d705; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)`

Im running Ubuntu 20.04 LTS and Java 13 and using Spring Boot.
The aws-java-sdk version is 1.11.801

Am I doing something wrong here? All permissions have been granted on aws.

**Comment by debora-ito** [comment]
Can you provide the code where you construct the `kinesis` client?

I found this comment in the Amazon Kinesis Video Streams Parser Library with the same error you're seeing: https://github.com/aws/amazon-kinesis-video-streams-parser-library/issues/41#issuecomment-457750142

The reply was:
> That 403 status code means you don't have permission for the operation, either you didn't provide AccessKey/SecretKey to your video media client or your IAM role linked to the AccessKey/Secretkey doesn't have permission for ListFragments API.

ListFragments is of course the API used in that issue, in this case would be `GetDASHStreamingSessionURL`.

**Comment by pabloedm** [comment]
Hey @debora-ito, thanks for your response.

> Can you provide the code where you construct the `kinesis` client?

As I stated in the original post, this is the way Im constructing the Bean Im using, which is `AmazonKinesisVideoArchivedMediaClient`.

> credentials and config are configured as follow:
> [default] 
> region = us-east-1
>
> [default] 
> aws_access_key_id = XXXXXXXX 
> aws_secret_access_key = XXXXXXXXXX
> 
> then I configured my bean:
> @Bean 
> public AmazonKinesisVideoArchivedMediaClient buildAmazonKinesis() { 
> return (AmazonKinesisVideoArchivedMediaClient) amazonKinesisVideoArchivedMediaClientBuilder.defaultClient(); 
>}

So far, this is the only asset that is returning 403. I've tried a few other options like list streams, create streams and delete streams and all of them are working correctly.
The problems appears to have a correlation with the bean `AmazonKinesisVideoArchivedMediaClient`.

**Comment by debora-ito** [comment]
@pabloedm can you enable [wire logs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and provide us the logs? Please make sure to redact any sensitive information. They might have additional info about the requests.

**Comment by jasminezm1970** [comment]
I also encountered the same problem, is there any solution? getHLSStreamingSessionURL return "software.amazon.awssdk.services.kinesisvideoarchivedmedia.model.KinesisVideoArchivedMediaException: null (Service: KinesisVideoArchivedMedia, Status Code: 403, Request ID: d60cfb2e-2994-468a-95b0-cfcc639a3d1e, Extended Request ID: null)"

**Comment by jasminezm1970** [comment]
my code:
AwsCredentials credentials = AwsBasicCredentials.create(id,key);
AwsCredentialsProvider acp = StaticCredentialsProvider.create(credentials);
KinesisVideoArchivedMediaClient kvsArchivedMediaClient = KinesisVideoArchivedMediaClient.builder()
				.credentialsProvider(acp)
				.region(Region.US_WEST_2)
				.build();
GetHlsStreamingSessionUrlRequest reqest = GetHlsStreamingSessionUrlRequest
				.builder().expires(1000).streamName("1234-75676")
				.hlsFragmentSelector(HLSFragmentSelector.builder()
						.fragmentSelectorType(HLSFragmentSelectorType.SERVER_TIMESTAMP)
						.timestampRange(HLSTimestampRange.builder()
								.startTimestamp(Instant.ofEpochMilli(1611307125000L))
								.endTimestamp(Instant.ofEpochMilli(1611314325000L))
								.build()).build())
				.containerFormat(ContainerFormat.MPEG_TS)
				.discontinuityMode(HLSDiscontinuityMode.ALWAYS)
				.displayFragmentTimestamp(HLSDisplayFragmentTimestamp.NEVER)
				.maxMediaPlaylistFragmentResults(500L)
				.playbackMode(HLSPlaybackMode.LIVE_REPLAY)
				.build();
		GetHlsStreamingSessionUrlResponse resp = kvsArchivedMediaClient.getHLSStreamingSessionURL(reqest);

**Comment by JS-E** [comment]
I know this is closed but i am still having this issue, wondered if anyone can tell me a fix or whether this is still pending? Thanks in advance

**Comment by ap-northeast-0** [comment]
I am having the same issue here. getHLSStreamingSessionURL always returns null..
Below is my code.
```
public class KVSService {
    public KinesisVideoArchivedMediaClient getClient() {
        return KinesisVideoArchivedMediaClient.create();
    }
    
    public String test() {
    	KinesisVideoArchivedMediaClient kvs = getClient();
    	String url = null;
    	
    	try {
    		GetHlsStreamingSessionUrlRequest request = GetHlsStreamingSessionUrlRequest.builder()
        			.streamName(streamName)
                    .expires(1000)
        			.playbackMode(HLSPlaybackMode.LIVE)
        			.containerFormat(ContainerFormat.FRAGMENTED_MP4)
        			.discontinuityMode(HLSDiscontinuityMode.ALWAYS)
        			.displayFragmentTimestamp(HLSDisplayFragmentTimestamp.NEVER)
        			.build();
    		GetHlsStreamingSessionUrlResponse response = kvs.getHLSStreamingSessionURL(request);

        	System.out.println(response.sdkHttpResponse().statusCode()); // this always returns 200 even if streamname is not blank
        	System.out.println(response.hlsStreamingSessionURL()); // this is returning null

        	url = response.hlsStreamingSessionURL();
    	} catch (KinesisVideoArchivedMediaException e) {
    		e.printStackTrace();
    	}
    	
    	return url;
    }
}
```

On the side note, I know I have set my AWS systems credentials correctly because when I tried the code below, I was able to get the data end point. 
```
KinesisVideoClient kvsClient = KinesisVideoClient.create();
GetDataEndpointRequest requestEndPoint = GetDataEndpointRequest.builder().streamName(streamName).build();
GetDataEndpointResponse responseEndPoint = kvsClient.getDataEndpoint(requestEndPoint);
System.out.println(responseEndPoint.dataEndpoint()); // I can retrieve thsi one
```
