### ISSUE TITLE
Authenticate user after signup using CognitoIdentityProviderClient

### ISSUE THREAD

**Issue by jtleaming** [aws/aws-sdk-java#2366]
We want to be able to authenticate a user once they have created their account so they are automatically signed in on account generation.
## Describe the issue

Currently our workflow for registration is we direct a user to a registration page controlled by our application, they make a create user request, and our server uses the CognitoIdentityProviderClient to create their user. We would then like our server to also log the user in, so when we redirect them back to our application they already have an active session. We used the AdminIniateAuth functionality to authenticate the user, and this does create a bearer token for us, however we are unable to then use that token to create the proper session in our database. Our application makes use of Cognito and Spring Security JDBC Sessions. 
We opened a ticket with AWS and they suggested we open a ticket here.

## Steps to Reproduce

    fun calculateSecretHash(userPoolClientId: String, userPoolClientSecret: String, userName: String): String? {
        val HMAC_SHA256_ALGORITHM = "HmacSHA256"
        val signingKey = SecretKeySpec(
            userPoolClientSecret.toByteArray(StandardCharsets.UTF_8),
            HMAC_SHA256_ALGORITHM)
        return try {
            val mac: Mac = Mac.getInstance(HMAC_SHA256_ALGORITHM)
            mac.init(signingKey)
            mac.update(userName.toByteArray(StandardCharsets.UTF_8))
            val rawHmac: ByteArray = mac.doFinal(userPoolClientId.toByteArray(StandardCharsets.UTF_8))
            Base64.getEncoder().encodeToString(rawHmac)
        } catch (e: Exception) {
            throw RuntimeException("Error while calculating ")
        }
    }

    fun loginUser (email: String, password: String) {

        val secretHash = calculateSecretHash(config.getCognitoClientId(), "", email)
        val authparams = mapOf(
            "USERNAME" to email,
            "PASSWORD" to password,
            "SECRET_HASH" to secretHash
        )
        val a = AdminInitiateAuthRequest
            .builder()
            .authFlow(AuthFlowType.USER_PASSWORD_AUTH)
            .userPoolId(config.getCognitoUserPool())
            .clientId(config.getCognitoClientId())
            .authParameters(authparams)
            .build()

        val result = cognitoClient.adminInitiateAuth(a)

        val session = result.session()

        val accessToken = result.authenticationResult().accessToken()

        print(result)
    }

## Your Environment

* AWS Java SDK version used: 2.12.2 (cognitoidentityprovider)
* JDK version used: Java 8
* Operating System and version: MacOS

**Comment by debora-ito** [comment]
Hey @jtleaming apologies for the long silence. I sent your question to the Cognito team and here's their answer:

"Customers can generate that behavior, but it’s not built in. What I mean is that there is currently no way to get tokens after signing up without also signing in. However, in some cases developers can sign in users automatically just by submitting the same username/password used for sign up. If the user needs to be confirmed (e.g., get and enter code sent to email) it works best from the client side where a web/mobile app can hold onto the username/password through the confirmation step, and then automatically initiate sign in."

Let us know if that helps.
