### ISSUE TITLE
S3 Bucket copy issue

### ISSUE THREAD

**Issue by FabioPerrone** [aws/aws-sdk-java#2367]
## Describe the issue
 
We have 2 buckets, one in account A and one in in account B.
 
The bucket A is encrypted with a customer managed key, while the bucket B is encrypted with default aes-256. The objects are stored in the bucket A in deep archive. An application on premise requires the restoration of some objects if needed.
 
Once an object is restored, a message on a SQS queue is sent. Another application (on-premise) is consumer of that queue, and for every object restored, it proceed copying it from bucket A to bucket B (it uses an iam user created in account B to avoid any issue related with object ownership).
 
Only some files fails to be copied with a 403 error. These files have all a size around 200 MB.
 
We used (Java SDK 1.11.714) the amazonS3.copyObject() or the TransferManager.copy() having the same issue. We tested the permissions of the user and tried to copy the same files by using the aws cli getting no errors. The error
 
## Steps to Reproduce
 
TransferManager tm = TransferManagerBuilder.standard()
                                  .withExecutorFactory(new SrdExecutorFactory())
                                  .withS3Client(getAmazonS3(key, secret, region))
                                  .withMinimumUploadPartSize(minimumUploadPartSize)
                                  .withMultipartCopyPartSize(minimumUploadPartSize)
                                  .build();
 
Copy copy = transferManager.copy(getSource().getPath(), getSource().getFile(),
getDestination().getPath(),getDestination().getFile())
 
where
 
getAmazonS3(String key, String secret, String region) {
   
   BasicAWSCredentials awsCreds = new BasicAWSCredentials(key, secret);
   
   log.debug("Creating Amazon S3 client...");
   return AmazonS3ClientBuilder
            .standard()
            .withCredentials(new AWSStaticCredentialsProvider(awsCreds))
            .withRegion(region)
            .withClientConfiguration(clientConfiguration)
            .build();
 
private static class SrdExecutorFactory implements ExecutorFactory {

   /**
    *
    * @return
    */
   @Override
   public ExecutorService newExecutor() {
      return Executors.newCachedThreadPool();
   }
}
 
minimumUploadPartSize = 5000000000
 
 
## Current Behavior
 
The copy fails with the following error:
 
Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: E636EE74BC5F7E91; S3 Extended Request ID: tLBsVyByJAx5cI2Bf6hHIdnPkXZEx9xaxzaWRncLNmkz55dIOHBthhbQjrhsVMAHviHhfIxwYtc=)
 
What is strange is that other files are copied successfully, using the same code and same parameters.
 
 
## Your Environment
 
* AWS Java SDK version used: Java SDK 1.11.714
* JDK version used: OpenJDK Runtime Environment Corretto-8.252.09.2
* Operating System and version: Windows 10 Pro 1909

**Comment by debora-ito** [comment]
@FabioPerrone Does the error occur always with the same file, or are they random?
Are you running in a EC2 instance, using instance credentials?
Can you enable [wire logging](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and provide the logs? Make sure there is no sensitive data.

**Comment by andrea-avogadro** [comment]
Hi Debora,
the code is running on premis.
the error occurs always on the same files.

I'm adding the logging of a single call
[srd-service.log](https://github.com/aws/aws-sdk-java/files/4830838/srd-service.log)

**Comment by debora-ito** [comment]
@andrea-avogadro I removed the log from your previous comment because it showed your access id. The log is still in the comment history so please rotate your credentials as soon as possible.

I don't see any obvious problem in the logs. I see `Content-Length: 0` in the copy request but I'm not sure if this would be the reason for an AccessDenied error. Have you compared with the wirelog of a successful copy?

I'll try to reproduce in the meantime.

@FabioPerrone

**Comment by andrea-avogadro** [comment]
@debora-ito  Many thanks! A newbie error :(
I haven't yet compared the logs of a successfull call. 
About the `Content-Lenght` I'm using the TransferManager class: I'll check in a successfull call.

**Comment by andrea-avogadro** [comment]
Hi @debora-ito I've done a test comparing results from my JAVA code and the AWS CLI.

The file is available on S3.

If I run my code I get the error above, but if I run the CLI I get:

```
aws s3 cp s3://xxxxxxxxx.mxf s3://yyyyyyyy.mxf --profile geobackup-test

copy failed: s3://xxxxxxxx.mxf to s3://yyyyyy.mxf An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```
I've found this link: : https://github.com/aws/aws-cli/issues/1674#issuecomment-397207116

**Comment by andrea-avogadro** [comment]
Please also note that the error seems to appear only on **small** files: maybe is related to permissions when copying a file **NOT** using the **multipart** copy?

**Comment by debora-ito** [comment]
That aws-cli issue is caused by a bucket policy in the destination bucket: it does not allow uploads without --acl bucket-owner-full-control.

Does your destination bucket has a policy?

**Comment by FabioPerrone** [comment]
Hi,
the issue was solved, we are closing the ticket
many thanks

**Comment by kiranbakale1talentica** [comment]
Hi @FabioPerrone can you please let me know what was the fix
