### ISSUE TITLE
AWSIotDataClient#init contains broken URL

### ISSUE THREAD

**Issue by sergey-derugo** [aws/aws-sdk-java#2370]
com.amazonaws.services.iotdata.AWSIotDataClient#init contains a link to https://data.iot.us-east-1.amazonaws.com which has invalid certificate. See https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-iot/src/main/java/com/amazonaws/services/iotdata/AWSIotDataClient.java#L319. Could you please either fix the certificate or remove this URL

**Comment by debora-ito** [comment]
Hi @sergey-derugo, the endpoint has not changed for backwards compatibility reasons. You can see more details in this blog post: https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/

The blog post shows how to set up an Amazon Trust Services endpoint, which presents trusted certificates by default in most popular browsers and operating systems.
First create an ATS endpoint by calling the describe-endpoint API. For example, using the AWS CLI:
```
aws iot describe-endpoint --endpoint-type iot:Data-ATS
```
Then use the endpoint in the IotData Client:
```
AWSIotData iotDataClient = AWSIotDataClient.builder()
        .withEndpointConfiguration(new AwsClientBuilder
                .EndpointConfiguration("<prefix>-ats.iot.us-west-2.amazonaws.com", "us-west-2"))
        .build();
```

**Comment by sergey-derugo** [comment]
Hi @debora-ito

Thank you for your response, it resolves my issue. Also I wonder can you add a special method withAtsEndpoint() and let the SDK automatically obtain the right URL?

**Comment by debora-ito** [comment]
@sergey-derugo sorry for the long pause here. In general we avoid doing such implementations, because the client builders are auto-generated. 

I'll go ahead and close this, feel free to reopen if you have further questions.

**Comment by sergey-derugo** [comment]
it's sad that the default instance AWSIotDataClient is broken and nobody attempts to improve the SDK
