### ISSUE TITLE
Not able to connect to stepfunction using AWS SDK 1.11.327

### ISSUE THREAD

**Issue by dileep1986** [aws/aws-sdk-java#2374]
## Describe the issue

I am using JDK 1.7 and running my application in Jboss 5.1.2. I am trying to connect step function from my application. But after sending POST request it's not giving any response or exception.

## Steps to Reproduce

I am using AWSStepFunctionsClientBuilder to create AWSStepFunctions object. 

When I am trying to list the activities in step functions using the below code.
ListActivitiesResult list = client.listActivities(new ListActivitiesRequest());

After executing this line I am not getting any exceptions or response. I can see in the logs that it's sending one Https post request. But not getting any response or exception. Any help would be appreciated.

## Your Environment

* AWS Java SDK version used:1.11.327
* JDK version used:1.7
* Operating System and version:Linux

**Comment by debora-ito** [comment]
@dileep1986 can you provide the full stacktrace with the error?
Can you also share a code snippet showing how you create the client?

**Comment by dileep1986** [comment]
> @dileep1986 can you provide the full stacktrace with the error?
> Can you also share a code snippet showing how you create the client?

Hi,

Actually there is no exception in the log and I am creating the client using the below code.
AwsActivityListenerBuilder.standard().withActivityArn().withDefaultWorkTimeOutSec().withWaitIntervalBetweenPolls().withThreadPool().withDefaultClient().build();
I just removed the arguments before pasting the code here. I think the issue is because of httpclient jar conflict. But still wonder why it's not giving any exceptions.

**Comment by dileep1986** [comment]
> > @dileep1986 can you provide the full stacktrace with the error?
> > Can you also share a code snippet showing how you create the client?
> 
> Hi,
> 
> Actually there is no exception in the log and I am creating the client using the below code.
> AwsActivityListenerBuilder.standard().withActivityArn().withDefaultWorkTimeOutSec().withWaitIntervalBetweenPolls().withThreadPool().withDefaultClient().build();
> I just removed the arguments before pasting the code here. I think the issue is because of httpclient jar conflict. But still wonder why it's not giving any exceptions.

Copied the wrong code, here it is:
AWSStepFunctionsClientBuilder.standard(). withRegion().with credentials(new DefaultAWSCredentialsProviderChain()).withClientConfiguration(clientConfiguration).build();

**Comment by debora-ito** [comment]
> But not getting any response or exception.

What does this mean, specifically? Is your code execution blocked?
