### ISSUE TITLE
Pause and resume for Perssitable Download

### ISSUE THREAD

**Issue by sidkhangit** [aws/aws-sdk-java#2375]
Is resume not supported for failed download? I have scenario where I disconnect network while downloading and connect back. But It start again downloading from starting instead of resuming. I get TRANSFER_FAILED_EVENT after disconnect and retrying to resume again after connecting back

I have implemented code accordingly as mentioned here
https://aws.amazon.com/blogs/developer/pausing-and-resuming-transfers-using-transfer-manager/

But in recent code I see hard coded false is passed here for "resumeOnRetry" parameter
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L1020

Please let me know if this is S3 limitation

**Comment by sidkhangit** [comment]
Please anyone respond to this

**Comment by debora-ito** [comment]
@sidkhangit can you provide the a sample code you are using and the full stracktrace with the error?
You said you're using the code in the linked blog post, are you pausing the download before disconnecting the network?

**Comment by sidkhangit** [comment]
No for my scenario I am not pausing download. Download going on and I am dropping network intentionally for 15-20sec. Connecting again after 20 sec and I see that when network comes UP, it starts downloading from start instead of resuming.

**Comment by debora-ito** [comment]
The pause() method returns the information that can be used to resume the download at a later time in the form of a `PersistableDownload`, so if you're not pausing before the network is disconnected then the TransferManager will not know where to start downloading again (to be fair, connectivity issues are unpredictable in the real world, so there's no way to know when to call pause).
