### ISSUE TITLE
Way to generate presignedurl request without predefined key

### ISSUE THREAD

**Issue by manjunathkadrolli** [aws/aws-sdk-java#2381]
I am working on a REST API through API gateway and lambda with a requirement of uploading a file max size of 100 MB

## Describe the Feature
The solution should allow to create a presignedurl against a bucket not against specfici object/key

## Is your Feature Request related to a problem?
I am stuck wether to with Lambda or fall back to Ec2 instance since my project is in Spring boot 

## Proposed Solution
The solution should allow to create a presignedurl against a bucket not against specfici object/key

## Describe alternatives you've considered
switch to EC2 instance instead of Lambda

## Additional Context
I am working on a REST API through API gateway and lambda with a requirement of uploading a file max size of 100 MB

## Your Environment

*aws-java-sdk-s3 - 1.11.817
* 1.8
* MAC - 10.15.5

**Comment by debora-ito** [comment]
@manjunathkadrolli the object key is part of the URL that needs to be signed, I don't think this feasible.
Can you tell us more about the problem you are trying to solve, give a little more context?

**Comment by manjunathkadrolli** [comment]
@debora-ito I am looking for a way where i can just upload a file without having key known in advance like adding a new file. Else now in the current flow i have to put an object into S3 and then use the key to generate the signed url.

**Comment by debora-ito** [comment]
Yeah as I said in the previous comment the key is part of the object URL, so you have to specify it.

Closing this, feel free to reach out if you have other questions.
