### ISSUE TITLE
How to get objects in S3 bucket with Assume Role?

### ISSUE THREAD

**Issue by NajwanHino** [aws/aws-sdk-java#2382]
We would like to access a bucket of our client using AssumeRole, we are getting a 403 error Access Denied. After looking at the example code at - https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenJava.html
and talking to AWS rep which suggests adding a policy, we came up with the following code which still produces the error.

## snippet of code
AWSSecurityTokenService client = AWSSecurityTokenServiceClientBuilder.standard()
						.withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
						.withRegion(Regions.US_EAST_1)
						.build();

				AssumeRoleRequest assumeRoleRequest = new AssumeRoleRequest()
						.withRoleArn(aws_roleARN)
						.withPolicy("{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":[\"s3:List*\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:s3:::<BUCKET-NAME>\"}]}")
						.withRoleSessionName("session-name")
						.withDurationSeconds(3600)
						.withExternalId(aws_externalId);

				AssumeRoleResult roleResponse = client.assumeRole(assumeRoleRequest);
				Credentials sessionCredentials = roleResponse.getCredentials();

				BasicSessionCredentials awsSessionCredentials = new BasicSessionCredentials(
						sessionCredentials.getAccessKeyId(),
						sessionCredentials.getSecretAccessKey(),
						sessionCredentials.getSessionToken());

				AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
						.withCredentials(new AWSStaticCredentialsProvider(awsSessionCredentials))
						.withRegion(Regions.US_EAST_1)
						.build();

				List<Bucket> buckets = s3Client.listBuckets(); //Fails on 403
				ObjectListing l = s3Client.listObjects(<BUCKET_NAME>); //Fails on 403

## Current Behavior
Getting 403 Access Denied.

If we assume that both IAM Role and Bucket have permissions, What causes this error and how can we prevent it?

**Comment by debora-ito** [comment]
In this case `ListBuckets` is getting Access Denied as expected, because the policy is allowing a single bucket as resource.
On the other hand, I'm not sure why `ListObjects` is getting Access Denied. Does the aws_roleARN role includes the correct trusted entities? They can be specified in the AssumeRolePolicyDocument in the IAM API or in the Trust Relationships tab in the IAM Console.

The [IAM Policy Simulator](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_testing-policies.html) is a helpful tool for troubleshooting permission issues. Let us know if that helps.

**Comment by NajwanHino** [comment]
Hi Debora,

Our client says that he is able to access the data via Python script using the same assume role, from his side there is no permission issue, however, when we want to implement this python script in Java using the above code, we are getting  Access Denied.
How can he access the data in the bucket using Python and not getting 403 Access Denied, while when we do this in Java, we get the Access Denied?

**Comment by debora-ito** [comment]
One possibility is the user credentials being used in the STS Client to call assumeRole in the Java SDK is different from the one used in Python. You can check it by calling STS [GetCallerIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html) after the STS client is created, from both SDKs and compare if they are the same.

**Comment by NajwanHino** [comment]
Hi,
I called in both Java and Python the GetCallerIdentity method and got the same UserId, Account, and Arn.
It could be something with role policy, how can I retrieve the policy of the Role ARN programmatically? as heading to the client`s AWS console is not an option.
or maybe we are still missing something?

**Comment by NajwanHino** [comment]
Any update on this? We are still dealing with this issue.

**Comment by debora-ito** [comment]
To retrieve the role policy you can call AmazonIdentityManagementClient.getRolePolicy(). Take a look in the other operations of [AmazonIdentityManagementClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/identitymanagement/AmazonIdentityManagementClient.html), they may be helpful to troubleshoot the AccessDenied issue.

If the credentials being used to call assumeRole are the same in Java and Python and you are assuming the exact same role, my guess is there's some difference in the session values being provided, like the inline session policy or the external Id. It's not easy to investigate access permission issues, and to be honest I don't have any other pointers besides those, not without role policies examples at least.
