### ISSUE TITLE
Trigger campaign with custom event sends to all endpoints in segment

### ISSUE THREAD

**Issue by fotherda71** [aws/aws-sdk-java#2383]
## Describe the bug

I set up a campaign to trigger off a custom event which my app sends. However when the event is sent by one of my endpoints it causes the campaign to send to everyone of the endpoints in the segment in the campaign. 

## Expected Behavior

It should only send to the one endpoint in the custom event.

## Current Behavior

see above

## Steps to Reproduce

Send the event using this code:

EventsBatch eventsBatch = new EventsBatch()
                .withEndpoint(publicEndpoint)
                .addEventsEntry(eventKey, event);

PutEventsResult result = Pinpoint.client.putEvents(new PutEventsRequest()
                .withApplicationId(Pinpoint.applicationId)
                .withEventsRequest(new EventsRequest()
                        .addBatchItemEntry(endpointId, eventsBatch)));

event is correctly sent but the campaign sends emails to every endpoint in its segment.

## Context

Can't send an email on a user registration event.

## Your Environment

* AWS Java SDK version used: aws-sdk-java/1.11.784 Linux/4.14.165-102.205.amzn2.x86_64 OpenJDK_64-Bit_Server_VM/25.201-b09 java/1.8.0_201 vendor/Oracle_Corporation
* JDK version used: 8
* Operating System and version:

**Comment by debora-ito** [comment]
The segment is defined in the WriteCampaignRequest when you [create the campaign](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/pinpoint/model/CreateCampaignRequest.html), along with the Event filter. 

Have you specified the intended Segment when you created the campaign? You can check it by calling GetCampaign.

**Comment by fotherda71** [comment]
@debora-ito Yes We have specified the segment. However the use case we (and many other people) have is:
 a specific user ABC takes an action -> send email to that specific user ABC

At present it works like this: 
a specific user ABC takes an action -> send emails to all endpoints in the segment

**Comment by debora-ito** [comment]
So if I'm understanding this correctly, the CreateCampaign is working as intended but it does not meet your use case. You want to send a notification to the endpoint associated to the event, not to a whole segment.

This would be a feature request to the Pinpoint service, I will pass it on to the Pinpoint service team.
