### ISSUE TITLE
Include DeliveryDelay in the SES EventType enum

### ISSUE THREAD

**Issue by alexburlton-sonocent** [aws/aws-sdk-java#2384]
## Describe the issue
The new event type `DeliveryDelay` was [recently added to SES](https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-ses-can-now-send-notifications-when-the-delivery-of-an-email-is-delayed/), however the SDK has not been updated to include it in the `EventType` enum. It would be useful to update this as I imagine anyone who is doing any processing of these events will likely be making use of it in parsing/handling logic.

## Your Environment

* AWS Java SDK version used: 1.11.630

**Comment by debora-ito** [comment]
Hi @alexburlton-sonocent thank you for reaching out. 

According to [SES docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/monitor-using-event-publishing.html#event-publishing-terminology), the DELIVERY_DELAY type is only available via SES API v2 `UpdateConfigurationSetEventDestination` operation, which uses the SES API v2 [EventType](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemailv2/model/EventType.html) and already has the DELIVERY_DELAY included.
