### ISSUE TITLE
Provide the ability to pass tags in STSAssumeRoleSessionCredentialsProvider when assuming a role

### ISSUE THREAD

**Issue by cpatelhealthfidelity** [aws/aws-sdk-java#2388]
## Describe the Feature
Provide a mechanism to pass tags when we use STSAssumeRoleSessionCredentialsProvider and the STSAssumeRoleSessionCredentialsProvider.Builder. 
Also provide a mechanism to pass transitiveTagKeys to STSAssumeRoleSessionCredentialsProvider via STSAssumeRoleSessionCredentialsProvider.Builder. 

For more information about passing tags  can be found here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html

## Is your Feature Request related to a problem?
Without this feature, the only option we have is to implement auto-renewal of STS token ourselves.

## Proposed Solution
Provide withTags(Collection<Tag> tags) method on  STSAssumeRoleSessionCredentialsProvider.Builder and pass tags in SessionCredentialsHolder.newSession() method when creating the AssumeRoleRequest

Provide withTransitiveTagsKeys(Collection<Tag> tags) method on  STSAssumeRoleSessionCredentialsProvider.Builder and pass tags in SessionCredentialsHolder.newSession() method when creating the AssumeRoleRequest

## Describe alternatives you've considered
Alternatives are to wrap implement our own AWSCredentialsProvider, perform AssumeRoleRequest with appropriate tags and renew tokens periodically. This will need a lost of testing with AWS sdk.

## Additional Context
Without this feature, the only option we have is to implement auto-renewal of STS token ourselves.

## Your Environment

* AWS Java SDK version used: 1.11.785
* JDK version used: Amazon Corretto 11
* Operating System and version: Debian 10

**Comment by debora-ito** [comment]
Seems reasonable, marking as a feature request.

**Comment by debora-ito** [comment]
This is now available in `1.11.849`.
