### ISSUE TITLE
Please make KeyManager agnostic of JRE provider.

### ISSUE THREAD

**Issue by gilsharon321** [aws/aws-sdk-java#2390]
AWS core has "SunX509" as a hard-coded Key Manager option.
https://github.com/aws/aws-sdk-java/blob/9dd9b354da6957e6e00e857765fd7a64e8ee4b7f/aws-java-sdk-core/src/main/java/com/amazonaws/http/AbstractFileTlsKeyManagersProvider.java#L43

## Describe the bug
Using the API on IBM JRE where:
ssl.KeyManagerFactory.algorithm=IbmX509
will fail to create Key Manager.

## Expected Behavior
choosing the default key manger would let users use other options, for example ibmX509.

## Current Behavior
Using the API on IBM JRE where:
ssl.KeyManagerFactory.algorithm=IbmX509
will fail to create Key Manager.

## Possible Solution
KeyManagerFactory KMF = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
should fix this.

## Context
I am trying to use the AWS API, running on IBM JRE. getting errors when SunX509 is not found.

## Your Environment

* AWS Java SDK version used: 1.11.825
* JDK version used: java version "1.8.0_241", IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200124_438197 (JIT enabled, AOT enabled)
* Operating System and version: Red Hat Enterprise Linux Server release 7.6

**Comment by debora-ito** [comment]
Hi @gilsharon321 thank you for reaching out. We are marking this as a feature request to add a way to customize the key manager.

**Comment by JogoShugh** [comment]
I agree with @gilsharon321. This would be a great change. We (SAP Concur: https://github.com/concur) are facing this same issue with trying to implement some FIPS compliance changes.
