### ISSUE TITLE
Clearly specify DynamoDBMapper's batchSave/batchDelete retry/chunking behavior

### ISSUE THREAD

**Issue by hoffa** [aws/aws-sdk-java#2394]
The documentation for DynamoDBMapper's [`batchSave`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.html#batchSave-java.lang.Iterable-) and [`batchDelete`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.html#batchDelete-java.lang.Iterable-) should clearly specify their chunking and retry behavior.

## Describe the issue
The documentation for DynamoDBMapper's [`batchSave`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.html#batchSave-java.lang.Iterable-) and [`batchDelete`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.html#batchDelete-java.lang.Iterable-) does not clearly specify that they retry and automatically chunk the input.

I've seen quite a lot of unnecessary retry and chunking logic, probably partly because the description isn't explicit enough.

## Links
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.html#batchSave-java.lang.Iterable-
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.html#batchDelete-java.lang.Iterable-

**Comment by debora-ito** [comment]
Thank you for the feedback @hoffa. What do you mean by chunking specifically?

(Pinging @Carey-AWS)

**Comment by hoffa** [comment]
`batchSave` and `batchDelete` automatically split the input into the "chunks" (of 25 items AFAIK) used for batch writes.
