### ISSUE TITLE
AWS EC2 - describeSpotFleetRequests returning too little max results

### ISSUE THREAD

**Issue by niekvanderkooy** [aws/aws-sdk-java#2397]
The DescribeSpotFleetRequests command (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSpotFleetRequests.html) is not returning as many results as the documentation says it should.

## Describe the bug
I am using the following code:
```
        DescribeSpotFleetRequestsRequest request = new DescribeSpotFleetRequestsRequest();
        // Code with no effect: request.setMaxResults(1000);

        DescribeSpotFleetRequestsResult result = ec2.describeSpotFleetRequests(request);
        List<SpotFleetRequestConfig> spotFleetRequestConfigs = result.getSpotFleetRequestConfigs();
```

In both cases above (with `request.setMaxResults(1000);` and without) I am expecting to be returned 1000 results (Or in my case a little over 340, since that is how many Spot Requests I currently have open). However, I only get returned 55. Using the nextToken (`result.getNextToken`) I am eventually able to get all my results, but this takes a lot longer than I would want since I have to repeat my request more often than expected.

Note that setting `setMaxResults` to something less than 55 (for example: `request.setMaxResults(20);`) does work as expected.

## Expected Behavior
I expect to be able to request up to 1000 Spot Fleet Requests in a single `DescribeSpotFleetRequestsRequest`

## Current Behavior
I am only able to return 55 at a time.

## Steps to Reproduce
See above code

## Context
I need to perform an action on a subset of my SpotFleetRequests. Note that it would be helpful to be able to pass a filter to DescribeSpotFleetRequests - for example, to request only currently active SpotFleetRequests. Since this currently does not seem to be possible I am stuck requesting all SpotFleetRequests and filtering them on my side.

## Your Environment
* AWS Java SDK version used: 1.11.835
* JDK version used: 8
* Operating System and version: Both windows 10 and ubuntu linux systems

**Comment by debora-ito** [comment]
Hi @niekvanderkooy sorry for the delay in replying here.

The response will not bring the exact number of `maxResults`, the number of results will not be more than `maxResults`, so yes, it can be less. 

There are factors that influence the number of results in a page, like size (there is a max limit size for a http request body, and if the output has a list like `DescribeSpotFleetRequests` has a list of `NetworkInterfaces`, imagine if this list is long). So looking for the presence of `nextToken` like you are doing is the right way to retrieve the results.

Let us know if you have any other question or concern.

**Comment by niekvanderkooy** [comment]
@debora-ito That makes sense! Although the difference between 55 and 1000 does seem rather large...

If this is the intended behaviour, then I have a follow up question: Are there any plans to be able to filter a DescribeSpotFleetRequests request on a specific value, tag, or property? (Since I don't think this is currently possible).

In my use case for example, I am only trying to request the 20-30 active spot fleet requests, while I might have 300-400 cancelled requests which I then have to also request and immediately discard. Being able to request just active requests would also solve my problem, and prevent me from having to make needless requests.

**Comment by debora-ito** [comment]
That would be a feature request to the EC2 service. I can pass it on to the EC2 service team if you'd like to.

**Comment by niekvanderkooy** [comment]
That would be great, thanks!

**Comment by debora-ito** [comment]
Will do. Will update when we hear back.

I'll close this for now as there's no issue with the SDK. Feel free to reopen if you have any other question.

**Comment by debora-ito** [comment]
@niekvanderkooy the EC2 team responded, they acknowledged the feature request.

**Comment by niekvanderkooy** [comment]
@debora-ito Thanks for the feedback. Is this also an indication that the feature will be implemented, or is that something we'll have to wait and see?

**Comment by debora-ito** [comment]
@niekvanderkooy it's a indication that they acknowledged the feature request :) I don't have any further info.
