### ISSUE TITLE
High memory usage when using aws-sdk-java to upload a multipart file to Amazon S3 via streaming

### ISSUE THREAD

**Issue by gejunqiang** [aws/aws-sdk-java#2398]
## Describe the issue
The method below in my Java SpringBoot application directly streams and uploads a `InputStream` to an Amazon S3 bucket using the `TransferManager`,  and the `InputStream` is derived by the `MultipartFile`. I found that the code costs so many memory and I don't know why. Can someone give me some suggestions.

```java
public void upload(String key, MultipartFile file) throws AmazonClientException, InterruptedException, IOException {
        TransferManager tm = null;
        try {
            ObjectMetadata objectMetadata = new ObjectMetadata();
            objectMetadata.setContentLength(file.getSize());
            tm = TransferManagerBuilder.standard().withS3Client(s3).withMinimumUploadPartSize(5 * 1024 * 1024L).withMultipartUploadThreshold(5 * 1024 * 1024L).build();
            Upload upload = tm.upload(s3Config.getBucket(), key, file.getInputStream(), objectMetadata);
            upload.waitForCompletion();
        } finally {
            input.close();
            if (tm != null) {
                tm.shutdownNow();
            }
        }
    }
```

## Your Environment

* AWS Java SDK version used: 1.11.791
* JDK version used: openjdk 8
* Operating System and version: debian 4.9.110-1

**Comment by debora-ito** [comment]
Hi @gejunqiang how are you observing the spike in memory usage?
How big is the input file?

**Comment by kulkarni-abhishek** [comment]
Hi @gejunqiang
I am facing the same issue. Have you got any resolution for this?
