### ISSUE TITLE
Extend TransferManager to support copying virtual directories within S3

### ISSUE THREAD

**Issue by patrick-boc** [aws/aws-sdk-java#2399]
Copy all files from one virtual directory in S3 to another.

TranferManager has methods uploadDirectory() and downloadDirectory(). This request is for a similar feature but for copying dirctories within S3.

**Comment by debora-ito** [comment]
@patrick-boc Transferring this issue to SDK v1 repo.

Marking as a feature request. Please note that as the team's efforts are concentrated in SDK v2 new features, this will have low priority.

**Comment by freshmanken** [comment]
Hi is this feature being tracked somehow? It's been 2 years and didn't see any updates, thanks!

**Comment by debora-ito** [comment]
@patrick-boc @freshmanken 

We don't have plans to support this in v1 before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so I'm closing this. 

And I don't think we will add this to v2 TransferManager either, this makes more sense being a S3 modeled API. As a workaround you can check the aws cli s3 `cp` and `sync` commands - https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html


#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
