### ISSUE TITLE
DynamoDBMapper to scan super classes/interfaces for annotations

### ISSUE THREAD

**Issue by SimY4** [aws/aws-sdk-java#2402]
Currently, DynamoDBMapper only looks for annotation on the direct class instance. It doesn't check for any superclasses or interfaces

My DynamoDB entities share similar structure which I was hoping to extract into a separate interface so I won't forget to add them in. But current implementation of DbMapper never takes into account implemented interfaces and annotations presented there. Which leads to a lot of annotation code duplication and potential errors. 

```
/**
 * These interface annotations are not visible for DynamoDBMapper
 */
interface IDocument {
  @DynamoDBHashKey
  String getHash();
  @DynamoDBAutoGeneratedKey
  @DynamoDBRangeKey
  String getId();
  @DynamoDBVersionAttribute
  Long getVersion();
}

@Data
class DbDocument implements IDocument {
  private String hash;
  private String id;
  private Long version;
}
```

Many libraries in the Java ecosystem take into account the parent class/interface annotations. It would be great if DynamoDBMapper followed the same practice and scanned for annotations on overridden methods.

**Comment by debora-ito** [comment]
Hi @SimY4 I apologize for taking so long to reply. As the team is directing its efforts in the SDK v2, this feature will probably not be considered for v1 DynamoDB Mapper. I don't think this is supported in SDK v2 [DynamoDB Enhanced Client](https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/) yet, but I suggest you try it out and open a ticket in v2 repository if needed.

Let me know if you have any questions.
