### ISSUE TITLE
Support for Java 9's module system

### ISSUE THREAD

**Issue by metacodez** [aws/aws-sdk-java#2404]
For a while now I am trying to get my projects' modues straigt as of Java9's module system. As of now just two dependencies left in my projects (https://bitbucket.org/refcodes/) without stable module name, one of them  comes from AWS.

An idea to  help other Java 9 modules and their `module-info.java` declaration would be to put an entry into AWS' JAR Manifest-File, such as: `Automatic-Module-Name: aws.java.sdk.core` to get stable module references. In Maven, this can be achieved by tweaking the maven-jar-plugin similar to:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			...
			<manifestEntries>
				<Automatic-Module-Name>aws.java.sdk.core</Automatic-Module-Name>
			</manifestEntries>
		</archive>
	</configuration>
	...
</plugin>
```
I would be very greatful when you generate such a Manifest entry as AWS provides great cloud services!

**Comment by debora-ito** [comment]
Hi @metacodez thank you for reaching out!

This would be such a big change to be made in SDK v1 that will probably not be considered. I recommend to take a look and eventually migrate to SDK v2, where `Automatic-Module-Name` is already supported - https://github.com/aws/aws-sdk-java-v2/

**Comment by metacodez** [comment]
Hello @debora-ito thank you for your fast reply. Indeed v2 looks very promising, though I cannot find `SimpleDB` with an automatic module name, I just found some `preview` versions which seem to be missing the automatic module names and which did not change their `preview` status since Jul, 2018:

```
<!-- https://mvnrepository.com/artifact/software.amazon.awssdk/simpledb -->
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>simpledb</artifactId>
    <version>2.0.0-preview-11</version>
</dependency>
```

Are there any chances this artifact gets automatic module names and gets out of preview status or is it contained in some other artifact I was missing?

Thansk beforehand & best regards!

**Comment by debora-ito** [comment]
@metacodez I will ask the team behind `SimpleDB` API as I don't know for sure. Will let you know when they reply back.

**Comment by metacodez** [comment]
Hello @debora-ito thank you & looking forward for their reply!

**Comment by metacodez** [comment]
Hello @debora-ito, I plan to prepare a next release of REFCODES.ORG artefacts, do you have nay news on this `preview` issue regarding `SimpleDb`?

```
<!-- https://mvnrepository.com/artifact/software.amazon.awssdk/simpledb -->
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>simpledb</artifactId>
    <version>2.0.0-preview-11</version>
</dependency>
```

Thanks beforehand & best regards -

**Comment by debora-ito** [comment]
Good timing! I just got a reply from the Simple DB team, saying they have no plans to make the APIs available in the Java SDK v2, unfortunately.

**Comment by debora-ito** [comment]
Marking this issue to auto close soon. Feel free to reopen or add a comment if you have further questions.

**Comment by metacodez** [comment]
Thanks for your investigation! 

For me to get it right: When I stay with `2.0.0-preview-11` for `SimpleDB` I will have Java 9's module support, but no updates or bugfixes, as it will never make it out of `preview`. When I go back to `1.11.865` I will get updates but I will miss Java 9's module support  as it will never come for the `1.xx.yyy` versions? 

Now I got to decide as I already use `S3` with `2.x.y` version APIs and have to stay with `1.11.865` for `SimpleDB` (feels somehow as if I was mixing two version lines of `AWS` libraries).

Are there any reasons for the `SImpleDB` API team not to follow up on a final release succeeding version `2.0.0-preview-11`? E.g. will `SimpleDB` be deprecated (or is it already deprecated) and not be supported by AWS at all any more in the near future? Then maybe I should skip support for `SimpleDB` at all and look for an alternative? Which NoSQL DB in the AWS cloud would be an alternative for `SimpleDB`?
