### ISSUE TITLE
IdleConnectionReaper prints a misleading exception when the logging level is set to debug

### ISSUE THREAD

**Issue by carlspring** [aws/aws-sdk-java#2405]
I'm assuming that based on the fact that the class' name is `com.amazonaws.http.IdleConnectionReaper` and the package is `software.amazon.awssdk.http.apache.internal.conn`, that you guys have this class in multiple libraries. However, the code appears to be the same (and I didn't manage to find your other project on Github, so I'm assuming it's Amazon-internal only and, hence, reporting it here).

In `software.amazon.awssdk.http.apache.internal.conn.IdleConnectionReaper`, the following [code block](https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/IdleConnectionReaper.java#L146-164):

```java
        @Override
        public void run() {
            while (!stopping) {
                try {
                    Thread.sleep(sleepPeriod);

                    for (Map.Entry<HttpClientConnectionManager, Long> entry : connectionManagers.entrySet()) {
                        try {
                            entry.getKey().closeIdleConnections(entry.getValue(), TimeUnit.MILLISECONDS);
                        } catch (Exception t) {
                            log.warn("Unable to close idle connections", t);
                        }
                    }
                } catch (Throwable t) {
                    log.debug("Reaper thread: ", t);
                }
            }
            log.debug("Shutting down reaper thread.");
        }
```

Causes:

```
22:57:44.967 09-08-2020 | DEBUG | tp-connection-reaper | com.amazonaws.http.IdleConnectionReaper            | Reaper thread: 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
```

So... the issue here is that due to the fact that I have `tearDown()` method in my test which invokes:

```java
    com.amazonaws.http.IdleConnectionReaper.shutdown();
```

... the exception above is thrown. It's actually not really an error, _**but**_ when you have the logging level set to `DEBUG` it prints out the exception. To me, this makes little sense the way that it currently is. If you would like to debug things, either use `trace`, or fine tune it by adding whatever checks you need. Also, the exception states that the `Reaper thread` is `XYZ` whereas this is actually a `Throwable`.

Could you please make this only throw/print an exception, if this is really required?

This issue is identical to https://github.com/aws/aws-sdk-java-v2/issues/1982 .

## Expected Behavior

No exception should be printed in `DEBUG`. if you really care about the exception, please throw/re-throw it

## Your Environment

* AWS Java SDK version used:
`com.amazonaws:aws-java-sdk-core:1.11.837`
* JDK version used:
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```
* Operating System and version:
```
# uname -a 
Linux carlspring 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by debora-ito** [comment]
Let's track this issue in the v2 repo and avoid duplication: https://github.com/aws/aws-sdk-java-v2/issues/1982
It will be analyzed for both v1 and v2.

**Comment by carlspring** [comment]
Okay, sounds reasonable!
