### ISSUE TITLE
How to convert job.json to a JobSettings (AWSMediaConvert)

### ISSUE THREAD

**Issue by NeXT405** [aws/aws-sdk-java#2407]
Hi 

I'm not sure if this is the right place to ask. Actually, this is not an issue, it is a question how to use the sdk. 

I followed the instructions here: 
https://docs.aws.amazon.com/mediaconvert/latest/apireference/java.html

I struggled here: 

`After you specify your job in JSON format, translate it according to the SDK for Java documentation to create your jobSettings object.`

Do I really have to create the **jobSettings** object **by hand** or is there a way around it? 

I cannot  find a way to marshall / unmarshall the json file. 

Thanks in advance.

**Comment by pawanraocse** [comment]
I am also looking for the same -- to try out media convert from java

**Comment by debora-ito** [comment]
@NeXT405 @pawanraocse

There is no operation to convert the JSON to a JobSettings object unfortunately, you would have to create the [JobSettings](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/mediaconvert/model/JobSettings.html) object and specify every field.

**Comment by NeXT405** [comment]
@debora-ito 

Thank you for your clarification I thought so.

**Comment by MariemSoussiDev** [comment]
Hello
 Please, can you tell me how did you translate job.json to a jobsettings?
