### ISSUE TITLE
Pagination with search operation in dynamodb using java?

### ISSUE THREAD

**Issue by khanaaqib** [aws/aws-sdk-java#2410]
## Describe the issue

Hi i am working on the search operation where perform a query in Dynamodb and fetch the required result ,the result is coming fine but now i am wanted the search result in pagination format which is record of 10 data items per each page.If any one help me it would be great appreciation.

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
To paginate the result you can provide a `limit` to the [QueryRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/QueryRequest.html) and watch if a `LastEvaluatedKey` value is present in the QueryResult. If it is then you'll have to provide this value in the `ExclusiveStartKey` field in a subsequent query request. Take a look at the Query API documentation: 
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html

Another option is to call the `query` method of the [Table](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/Table.html) class, which returns a collection you can iterate and let the SDK do the pagination automatically for you. See some code examples here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryingJavaDocumentAPI.html

Please refer to the DynamoDB developer guide for more examples.

**Comment by khanaaqib** [comment]
Hi  @debora-ito  I  have tried the second one but here search thing happened on page by page but I want to first search in the whole database and  fetch the whole search result then divided the search result in pagination format and this thing also happened in filter operation.

> To paginate the result you can provide a `limit` to the [QueryRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/QueryRequest.html) and watch if a `LastEvaluatedKey` value is present in the QueryResult. If it is then you'll have to provide this value in the `ExclusiveStartKey` field in a subsequent query request. Take a look at the Query API documentation:
> https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html
> https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html
> 
> Another option is to call the `query` method of the [Table](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/Table.html) class, which returns a collection you can iterate and let the SDK do the pagination automatically for you. See some code examples here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryingJavaDocumentAPI.html
> 
> Please refer to the DynamoDB developer guide for more examples.

**Comment by debora-ito** [comment]
@khanaaqib I am not fully clear on the issue. What do you mean by "search thing happened on page by page"?
