### ISSUE TITLE
ECS IAM Role get Too Many Requests error for SQS

### ISSUE THREAD

**Issue by todzheng** [aws/aws-sdk-java#2411]
Use ECS IAM Role, occasionally got error complaining about Too Many Requests, results in not able to load AWS credentials in the chain
## Describe the bug

com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), com.amazonaws.auth.profile.ProfileCredentialsProvider@72cc5f01: Unable to load credentials into profile [default]: AWS Access Key ID is not specified., com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@4385f967: Too Many Requests (Service: null; Status Code: 429; Error Code: null; Request ID: null)]\n\tat com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)\n\tat 
## Expected Behavior

how to avoid Too Many Requests error?
## Your Environment

* AWS Java SDK version used: aws-java-sdk-1.11.415
* JDK version used: OpenJDK11
* Operating System and version: CentOs6.6

**Comment by debora-ito** [comment]
429 `Too Many Requests` indicates that you've reached the API rate limits.

 [`EC2ContainerCredentialsProviderWrapper`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.html) is probably trying to load the credentials from EC2 Instance Metadata Service and hitting the API call rate limits. See the [Throttling](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#instancedata-throttling) section of EC2 documentation for more info.

You can try to reduce the number of calls to IMDS or write a custom retry logic for the credentials fetching.
