### ISSUE TITLE
[AWS][ECS]Similarities for Utilization, Utilized and Reservation and reserved metrics for ECS cluster in cloudwatch and insights.

### ISSUE THREAD

**Issue by susindran1308** [aws/aws-sdk-java#2416]
Hi,
I am currently working on monitoring ECS Clusters in AWS. The value for CPU and memory Utilization from cloudwatch when calculated from container insights (Utilized/Reserved) are not equal.

When calculated for service, utilized/reserved was equal to utilization (For both CPU and Memory). Same goes for Instance specific metrics too.

I want to know, What does CPU Or Memory Utilization Or reservation mean from cloudwatch and what does CPU Or memory utilized Or reserved mean from insights (for ClusterName dimension)?

aws-java-sdk-1.11.499.jar SDK is used.

**Comment by debora-ito** [comment]
Hi @susindran1308 this is a very service specific question, I don't have the expertise to answer but I can point to some ECS documentation pages:
- On how ECS Service utilization is measured: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#service_utilization
- On Container Insight Metrics descriptions: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-ECS.html

For further questions about the service behavior I'd suggest asking in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=138&start=0). We try to keep this repository as a channel for issues and feature requests for the AWS SDK for Java.
