### ISSUE TITLE
Conflicting Libraries in 1.1.869

### ISSUE THREAD

**Issue by djchapm** [aws/aws-sdk-java#2418]
When using aws.java.sdk:1.11.869, there are conflicting versions of transient dependency aws-java-sdk-simpleworkflow.

## Describe the issue

With large projects, managing transient dependencies and dependency-convergence is critical for getting expected results.  We use maven enforcer plugin described below to double check our libraries are in sync - normally aws does not popup as having an issue within itself.  Would love for you to make the enforcer a required part of your aws-java-sdk build.
Here it shows you have a transient dependency via aws-java-sdk-swf-libraries that conflicts with the version in aws-java-sdk-simpleworkflow.  It may not be an issue since mvn would auto upgrade to 1.11.869, but it also means you have un-managed dependency in aws-java-sdk-swf-libraries that could lead to unexpected results.  

    +-com.amazonaws:aws-java-sdk:1.11.869
      +-com.amazonaws:aws-java-sdk-simpleworkflow:1.11.869
And
    +-com.amazonaws:aws-java-sdk:1.11.869
      +-com.amazonaws:aws-java-sdk-swf-libraries:**1.11.22**
        +-com.amazonaws:aws-java-sdk-simpleworkflow:**1.11.22**

## Steps to Reproduce

basic pom file with dependency:
```
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk</artifactId>
                <version>${aws.version}</version>
            </dependency>
```
Run with enforcer build plugin:
```
                <plugin> <!-- run mvn validate -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>validate</phase>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <dependencyConvergence/>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
```

## Current Behavior

Compile succeeds

[WARNING] 
Dependency convergence error for com.amazonaws:aws-java-sdk-simpleworkflow:1.11.869 paths to dependency are:
    +-com.amazonaws:aws-java-sdk:1.11.869
      +-com.amazonaws:aws-java-sdk-simpleworkflow:1.11.869
and
    +-com.amazonaws:aws-java-sdk:1.11.869
      +-com.amazonaws:aws-java-sdk-swf-libraries:1.11.22
        +-com.amazonaws:aws-java-sdk-simpleworkflow:1.11.22

## Your Environment

* AWS Java SDK version used:  1.11.869
* JDK version used: 11, maven 3.6
* Operating System and version: macOS

**Comment by debora-ito** [comment]
Hi @djchapm, thank you for reaching out. I'm trying to pinpoint which sdk module has a dependency on `aws-java-sdk-swf-libraries` but having a hard time - I tried to run the enforcer plugin but it runs successfully for me. I'll investigate more and report back.

**Comment by debora-ito** [comment]
@djchapm Found it, it's in `aws-java-sdk-osgi`. It's not simple to replace `aws-java-sdk-swf-libraries` because 1.11.22 is the last released version. And with the team's efforts focused in the Java SDK v2, this issue would have really low priority.
