### ISSUE TITLE
ClusterCache.getConfigurationEndpoint() is not returned for Redis Cluster

### ISSUE THREAD

**Issue by eddumelendez** [aws/aws-sdk-java#2419]
Currently, when a redis cluster is created in elasticache `ClusterCache.getConfigurationEndpoint()` is not returned neither via cli nor java sdk. Docs said that this is for memcache but I would be great to have the same for redis.

**Comment by debora-ito** [comment]
@eddumelendez this is a feature request to the ElastiCache service. I'll send this over to the ElastiCache service team and will update here when they respond.

**Comment by debora-ito** [comment]
@eddumelendez here's the service team response:

The configuration endpoint is a property of the ReplicationGroup for Redis, not the CacheCluster. A CacheCluster for Redis is only a single node, so the property exists in the parent object: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ReplicationGroup.html

As the documentation mentions, the ReplicationGroup contains all of the attributes of a specific Redis replication group.

I'll go ahead and close this. Feel free to reach out if you have further questions.
