### ISSUE TITLE
SQS - JAVA SDK v1.11.171 - 502 Bad Gateway error thrown while discovering SQS queues

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#2420]
Hi

We are facing the same issue when invoking AWS SQS APIs via AWS java SDK version v1.11.171

https://stackoverflow.com/questions/55637977/502-when-running-sqs-test-using-localstack

Upon analyzing we found that the issue has been addressed by referring below link:
https://github.com/localstack/localstack/issues/966

We would like to know in which version of AWS java SDK, this issue has been handled. Please help us with resolving this.

Thanks in advance.

**Comment by debora-ito** [comment]
@gowthamsankar312 are you using LocalStack? If so, you'll need to use the version of LocalStack that fixed localstack/localstack#966, the fix was made on the LocalStack side.
