### ISSUE TITLE
How to get and print number of open/used connection and number of max connection allowed in S3 client connection pool

### ISSUE THREAD

**Issue by harisingh-highq** [aws/aws-sdk-java#2422]
Hi
Below is my code snippet. I have not set any client configuration while creating AmazonS3 object build 
so it should take default client configuration but to confirm same, I want to get number of open/used connections, free connections and number of max connection allowed in connection pool while application is running.
Can you please guide me how can I print those value here? 
Also should I increase those property value to support my application load in production environment OR if i go with default configuration, is this OK in lots of upload/download operations

            EndpointConfiguration endpointConfiguration = new EndpointConfiguration(endpoint,regions.getName());
		AmazonS3 amazonS3Client = null;
		try {
			
			AWSCredentials credentials = new BasicAWSCredentials(accessKey, secretKey);
			amazonS3Client = AmazonS3ClientBuilder.standard()
					.withEndpointConfiguration(endpointConfiguration)
	       			.withCredentials(new AWSStaticCredentialsProvider(credentials))
	       			.withPathStyleAccessEnabled(true)
	       			.build();
                      }

**Comment by harisingh-highq** [comment]
Hi @debora-ito 
I tried below one but not getting details because of I've not set any customized configuration at the the time of builder.
`AmazonS3ClientBuilder.standard().getClientConfiguration();`

could you please have a glance on this?

**Comment by harisingh-highq** [comment]
Hi @debora-ito 
Can you help me to sort out this?

**Comment by debora-ito** [comment]
@harisingh-highq may I suggest an easier way to visualize this info other than printing them? You can generate metrics about your application performance and visualize them in CloudWatch by simply enabling the SDK Metrics: https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/

The RequestMetrics category includes `HttpClientPoolAvailableCount`, `HttpClientPoolLeasedCount` and `HttpClientPoolPendingCount` metrics you're looking for. Check the [package summary](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/package-summary.html) for the metrics description, and see this blog post for code examples and metrics explanation: https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/

**Comment by harisingh-highq** [comment]
@debora-ito 
Thanks a lot for your response. 
You mean to say that we can monitor connection pool available, max & free counts only using SDK metrics.
There is no any implementation in SDK java to print those values in application, right?

**Comment by Nirmal-zymr** [comment]
@harisingh-highq enable logger for org.apache.http.impl.conn at DEBUG level 
i.e 
        <AsyncLogger name="org.apache.http.impl.conn" level="DEBUG" additivity="true" includeLocation="true"/>

**Comment by debora-ito** [comment]
Marking this to close soon, let us know if there are any more questions.

**Comment by srgplv** [comment]
And the article on SDK Java 1.x
https://medium.com/@srgplv/amazon-web-services-metrics-6c27d9c5f6f2
