### ISSUE TITLE
【Bugs In the Sample Code】Kinesis Consumer App Sample

### ISSUE THREAD

**Issue by Merikanto** [aws/aws-sdk-java#2423]
## Describe the bug

The file that has the bug:
https://github.com/aws/aws-sdk-java/blob/master/src/samples/AmazonKinesis/AmazonKinesisApplicationSampleRecordProcessor.java

**Line 81**, method  ``` processRecordsWithRetries```

## Expected Behavior

Retry 10 times when failure occurs

## Current Behavior

Will skip the retry no matter the failure occurs or not, and x will **ALWAYS** be true.

## Possible Solution

The problem occurs because the boolean ```processedSuccessfully```  is set to ```true``` directly after ```processSingleRecord(record);```, then break the loop, thus effectively skipping the retry & backoff.

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @Merikanto, the idea of the `processRecordsWithRetries` method is, once you are in the inner for loop and `processSingleRecord` is called, any exception thrown by `processSingleRecord` will be handled by the `catch (Throwable t)` statement, skipping `processedSuccessfully = true; break;` and triggering the backoff sleep time.

That's the basic idea of the example, and it invites you to add your own logic to the record processing.

Let us know if this helps.

**Comment by Merikanto** [comment]
But the boolean value does not do anything, it will always be evaluated as true. I have experimented with test cases.

**Comment by debora-ito** [comment]
What exceptions are your test cases throwing specifically?
