### ISSUE TITLE
DescribeInstancesRequest with tag filters does not returns stopped instances

### ISSUE THREAD

**Issue by deporcali** [aws/aws-sdk-java#2427]
When trying to get the instances tagged with a certain tag key/value pair, only the instances that are running are returned.

## Describe the bug
When manually searching in the AWS EC2 console with `tag:Owner : 'xyz'` the return instances are correct (all instances with that tag) which includes both running and stopped instances. But when doing the same thing through Java, only the running instances are returned.  

## Expected Behavior
The Java SDK should return both running and stopped instances

## Current Behavior
The Java SDK only returns running instances

## Steps to Reproduce
1. Have in AWS a set of instances with same tag (i.e. `Owner=xyz`)
2. Manually in EC2 console search `tag:Owner : 'xyz'` and it should return both running and stopped instances matching that tag
3. Execute the same request in Java and only the running instances are returned
```java
// List for all the instances
List<Instance> instances = new ArrayList<>();

// Make request with filter
Filter filter = new Filter().withName("tag:Owner").withValues("xyz");
DescribeInstancesRequest request = new DescribeInstancesRequest().withFilters(filter);
DescribeInstancesResult result = ec2Client.describeInstances(request );

// Add all instances found to list
List<Reservation> reservations = result.getReservations();
for (Reservation reservation : reservations) {
    instances.addAll(reservation.getInstances());
}
```

## Possible Solution
Java SDK should describe instances the same way as the AWS Web Console

## Context
Trying to automate cleanup process by fetching instances with a certain tag

## Your Environment
* AWS Java SDK version used: `compile group: 'com.amazonaws', name: 'aws-java-sdk', version: '1.11.875'`
* JDK version used: Java 8
* Operating System and version: Mac Mojave

**Comment by debora-ito** [comment]
@deporcali maybe the results are being paginated, have you checked if `nextToken` is present in the response?

**Comment by deporcali** [comment]
@debora-ito Yes `nextToken` is not present, and also the section in the code to reproduce where it says `Add all instances found to list` is where it loops through all the reservations.

Also I verified by changing `new DescribeInstancesRequest().withFilters(filter);` to `new DescribeInstancesRequest();` and it does returns all the instances available (both running and stopped). So there must be something that the filter is doing besides looking for the specified tag.

You can reproduce it by running the sample code.

**Comment by deporcali** [comment]
Found issue with instances
