### ISSUE TITLE
Support for AWS SSO credentials

### ISSUE THREAD

**Issue by andyndang** [aws/aws-sdk-java#2434]
I'd like to use AWS SSO as the credentials for my program:
```
aws sso login
```
I can use SSO credentials in boto3

## Describe the Feature
AWS SSO credentials to replace static AWS credentials 

## Is your Feature Request related to a problem?
I'm frustrated because I keep having to manually copy the credentials from SSO portal to my disk

## Proposed Solution
Replicate the boto3 implementation?

## Describe alternatives you've considered
N/A

## Additional Context
N/A

## Your Environment
* AWS Java SDK version used: 1.11.880
* JDK version used: 1.8
* Operating System and version: MacOS X

**Comment by debora-ito** [comment]
@andyndang thank you for reaching out, feature request noted.

**Comment by josephwofford** [comment]
See https://github.com/aws/aws-cli/issues/4982 and https://github.com/aws/aws-sdk-java-v2/issues/1970.

I'm currently using https://github.com/victorskl/yawsso to work around the problem, but there are easily a half dozen other workarounds.

AWS Single Sign-On (SSO) is a really cool feature, but it's unfortunate that so few tools currently support it.

**Comment by internetstaff** [comment]
This is a big pain point for us. Migrating to v2 is non-trivial, so we're stuck with nasty work-arounds to use SSO.

**Comment by debora-ito** [comment]
@internetstaff thank you for reaching out, I understand that the task to migrate to v2 is not a trivial one. We'd like to add native support for SSO in v1 but currently the team efforts are focused in releasing features for SDK v2 and in closing the feature parity gap.

I'd like to point out that you can use v2 SSO Credential Provider with some modifications, even if your project uses mostly SDK v1. You can add the v2 `sso` dependency (showing here in a pom.xml file):
```
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>sso</artifactId>
    <version>2.16.40</version>
</dependency>
```

and write an adapter to [`SsoCredentialsProvider`](https://github.com/aws/aws-sdk-java-v2/blob/master/services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/SsoCredentialsProvider.java) for it to work in a v1 style credential provider. The adapter would look like the example shown here for a ProfileCredentialsProvider: https://github.com/aws/aws-sdk-java/issues/803#issuecomment-593530484

**Comment by internetstaff** [comment]
@debora-ito Thank you, that actually worked pretty well, even with Spring Cloud AWS. :)

**Comment by andreacavagna01** [comment]
At least you can use Leapp to generate temporary credentials from aws SSO and then use this inside the sdk

https://github.com/Noovolari/leapp

**Comment by francis-a** [comment]
Is anyone able to provide an update on this? I'm just asking since the issue has been open for quite some time without much feedback. It would help us a lot of there was any kind of update so we could think about either upgrading to the v2 SDK or using the collection of workarounds in v1.

**Comment by wojtekk** [comment]
Hi, any update on this topic?

**Comment by flex-finch** [comment]
Are there any code examples for using SSO in a Java application? I can log in via the CLI, but I don't know how to use this in my app.

**Comment by thallium205** [comment]
Hi - any updates on this topic?

**Comment by debora-ito** [comment]
We don't have plans to support this in v1 before going into Maintenance Mode.

Java SDK v2 has native support for SSO credentials, so the recommendation here is to migrate to v2. As workaround in v1, you can add the v2 `sso` module to the classpath and write an adapter to work in the v1 credential style - more details in my comment here: https://github.com/aws/aws-sdk-java/issues/2434#issuecomment-819985174.


#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
