### ISSUE TITLE
MaxItems parameter in ListFunctionsRequest in aws-sdk-java-lambda has no effect on amount of returned function configurations

### ISSUE THREAD

**Issue by KottiCheese** [aws/aws-sdk-java#2435]
## Describe the issue

ListFunctionsResult always returns 50 or less configurations even if the maxItems parameter of ListFunctionsRequest is set to what we are lead to believe in the documentation is the maximum number(10000). Either the documentation is lying or you have a bug. Please clarify which case is this and fix if this is a bug or correct if it's a lie.

## Links

https://docs.aws.amazon.com/lambda/latest/dg/API_ListFunctions.html
After a quick google I found out this discrepancy was brought up few years ago in js sdk https://github.com/aws/aws-sdk-js/issues/1118 I assume that under the hood it is the one and the same bug/issue

**Comment by debora-ito** [comment]
@KottiCheese I agree that the documentation is confusing. `MaxItems` can be the total number of items that will be retrieved, with 50 results per page, but I'm not sure. I will send your feedback to the Lambda documentation team asking to make it more clear.

On a side note, every AWS documentation page has a Feedback button on the top right, you can use it to send the feedback directly to the service team associated to that page.

**Comment by debora-ito** [comment]
The service team has updated the documentation:

> [MaxItems](https://docs.aws.amazon.com/lambda/latest/dg/API_ListFunctions.html#API_ListFunctions_RequestSyntax)
The maximum number of functions to return in the response. Note that ListFunctions returns a maximum of 50 items in each response, even if you set the number higher.
