### ISSUE TITLE
Using S3 API ListObjectsV2 appears SignatureDoesNotMatch

### ISSUE THREAD

**Issue by SJTUChenJi** [aws/aws-sdk-java#2447]
Because of blobs' number over 1000, there are two requests sent to S3 server when using S3 API Reference ListObjectsV2. But SignatureDoesNotMatch will appear in second request. With help of postman, I found the uriencoded result of continuation-token value leads to the error. Because continuation-token includes character “/” and "&". According to S3 API Reference Authenticating Requests (AWS Signature Version 4), queryparameter should be encoded. "/" is encoded into "%2B" and "&" which is between two queryparameters  should not be encoded. But in the result of postman, I found "/" is encoded to "%20" and "&" which is between two queryparameters  is encoded to "& amp;"(please ignore the space. I hava to add a space for displaying normally).

## Expected Behavior

The CanonicalRequest **in postman** is "GET
/dataide/
continuation-token=1vxf53eO7XeLKVcev6kbIuo4WeMCSa%2FWNN%2FE%20pfvw1mb0DxeaNlp3ZxpQ1ap7B1sE91KObcAK%2004%3D& amp;list-type=2(please ignore the space after "&" again)
host:s3.cn-north-1.amazonaws.com.cn
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20201105T063905Z

host;x-amz-content-sha256;x-amz-date
UNSIGNED-PAYLOAD".

But the CanonicalRequest **in my codes** is "GET
/dataide/
continuation-token=1vxf53eO7XeLKVcev6kbIuo4WeMCSa%2FWNN%2FE%2Bpfvw1mb0DxeaNlp3ZxpQ1ap7B1sE91KObcAK%2B04%3D&list-type=2
host:s3.cn-north-1.amazonaws.com.cn
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20201105T063905Z

host;x-amz-content-sha256;x-amz-date
UNSIGNED-PAYLOAD".

## Context

The related code of uriEncode function as follow:
private String uriEncode(CharSequence input, boolean encodeSlash) {
		StringBuilder result = new StringBuilder();
		for (int i = 0; i < input.length(); i++) {
			char ch = input.charAt(i);
			if ((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '_' || ch == '-' || ch == '~' || ch == '.') {
				result.append(ch);
			} else if (ch == '/') {
				result.append(encodeSlash ? "%2F" : ch);
			} else {
				result.append(byteToHexUTF8(ch));
			}
		}
		return result.toString();
	}

private String byteToHexUTF8(char c) {
		Charset charset = Charset.forName("utf-8");
		CharBuffer charBuffer = CharBuffer.allocate(1);
		charBuffer.put(c);
		charBuffer.flip();
		ByteBuffer byteBuffer = charset.encode(charBuffer);
		byte[] bytes = byteBuffer.array();
		StringBuffer stringBuffer = new StringBuffer();
		for (int i = 0; i < bytes.length; i++) {
			stringBuffer.append("%").append(Integer.toHexString(bytes[i] & 0xFF).toUpperCase());
		}
		return stringBuffer.toString();
	}

## Your Environment

* AWS Java SDK version used:  azure-storage-blob:12.6.0
* JDK version used: jdk 1.8.0_241
* Operating System and version: mac os 

Thank you and look forward to your reply!

**Comment by debora-ito** [comment]
@SJTUChenJi can you provide a sample code I can use to reproduce the issue?

**Comment by SJTUChenJi** [comment]
Ok. There are two files:

`import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;

public class GetBucketSizeTest {

	class BucketProperties {
		private String name;
		private long size;
		private long objCount;

		public long getSize() {
			return size;
		}
		public void setSize(Long size) {
			this.size = size;
		}
		public long getObjCount() {
			return objCount;
		}
		public void setObjCount(long objCount) {
			this.objCount = objCount;
		}
		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
	}


	private String rgwProtocol = "https";
	private String service = "s3";
	private String rgwRegion = "cn-north-1";
	private String rgwEndpointSuffix = "amazonaws.com.cn";
	private String accessKey = "xxxxxxxxxxxxxx";
	private String secretKey = "xxxxxxxxxxxxxx";

	public static void main(String[] args) throws Exception {
		GetBucketSizeTest getBucketSizeTest = new GetBucketSizeTest();
		BucketProperties bucketProperties = getBucketSizeTest.getBucketSize("dataide");
		System.out.println(bucketProperties.getName());
		System.out.println(bucketProperties.getObjCount());
		System.out.println(bucketProperties.getSize());
	}

	public BucketProperties getBucketSize(String bucket) throws Exception{
		BucketProperties bucketProperties = new BucketProperties();
		bucketProperties.setName(bucket);
		long count = 0;
		long size = 0;
		HashMap<String, Long> hashMap = getRemainingProjects(bucket, null, count, size);
		bucketProperties.setObjCount(hashMap.get("Count"));
		bucketProperties.setSize(hashMap.get("Size"));
		return bucketProperties;
	}

	private HashMap<String, Long> getRemainingProjects(String bucket, String nextMarker, long count, long size) throws Exception {
		HashMap<String, Long> res = new HashMap<>();
		if(nextMarker == "false"){
			res.put("Count", count);
			res.put("Size", size);
			return res;
		}
		InputStream is = null;
		String urlStr;
		String bucketAndKey;
		TreeMap<String, String> params = new TreeMap<String, String>();
		if(nextMarker == null){
			urlStr = rgwProtocol + "://" + service + "." + rgwRegion + "." + rgwEndpointSuffix + "/" + bucket + "/?" + "list-type=2";
			bucketAndKey = "/" + bucket + "/";
			params.put("list-type", "2");
		}else{
			urlStr = rgwProtocol + "://" + service + "." + rgwRegion + "." + rgwEndpointSuffix + "/" + bucket + "/?" + "continuation-token=" + nextMarker + "&list-type=2";
			bucketAndKey = "/" + bucket + "/";
			params.put("continuation-token", nextMarker);
			params.put("list-type", "2");
		}
		String host = service + "." + rgwRegion + "." + rgwEndpointSuffix;
		TreeMap<String, String> awsHeaders = new TreeMap<String, String>();
		awsHeaders.put("host", host);
		awsHeaders.put("x-amz-content-sha256", "UNSIGNED-PAYLOAD");
		try {
			Map<String, String> header = new AWSV4Auth.Builder(accessKey, secretKey)
					.regionName(rgwRegion)
					.serviceName(service)
					.httpMethodName("GET")
					.canonicalURI(bucketAndKey)
					.queryParametes(params)
					.awsHeaders(awsHeaders)
					.payload(null)
					.build()
					.getHeaders();
			String date = header.get("x-amz-date");
			String authorization = header.get("Authorization");
			HttpURLConnection conn = getConnection(urlStr, "GET", date, null, null, authorization, null);
			conn.connect();
			is = conn.getInputStream();

			//parse response xml
			DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
			DocumentBuilder db = dbf.newDocumentBuilder();
			Document document = db.parse(is);
			NodeList contentLengthList = document.getElementsByTagName("Key");
			String keyVal = null;
			for(int i = 0; i < contentLengthList.getLength(); i++){
				Element key = (Element) contentLengthList.item(i);
				Node keyNode = key.getFirstChild();
				keyVal = keyNode.getNodeValue();
				if(!keyVal.endsWith("/")){
					count++;
					Node lastModifiedNode = key.getNextSibling();
					Node eTagNode = lastModifiedNode.getNextSibling();
					Node sizeNode = eTagNode.getNextSibling();
					Node sizeValTmp = sizeNode.getFirstChild();
					String sizeVal = sizeValTmp.getNodeValue();
					size += Long.parseLong(sizeVal);
				}
			}
			NodeList isTruncatedFlag = document.getElementsByTagName("IsTruncated");
			Element isTruncatedNode = (Element) isTruncatedFlag.item(0);
			Node isTruncatedTmp = isTruncatedNode.getFirstChild();
			String isTruncated = isTruncatedTmp.getNodeValue();
			String nextMarkerFlag = null;
			if(isTruncated.equals("true")){
				NodeList continueNode = document.getElementsByTagName("NextContinuationToken");
				Element continueNodetmp = (Element) continueNode.item(0);
				Node contain = continueNodetmp.getFirstChild();
				nextMarkerFlag = contain.getNodeValue();
			}else{
				nextMarkerFlag = "false";
			}
			HashMap<String, Long> resTmp = getRemainingProjects(bucket, nextMarkerFlag, count, size);
			count = resTmp.get("Count");
			size = resTmp.get("Size");
			res.put("Count", count);
			res.put("Size", size);
			return res;
		}catch (Exception e){
			throw new Exception(e);
		}
	}
	private HttpURLConnection getConnection(String urlStr, String method, String date,
	                                        String contentLength, String range, String authorization,
	                                        String contentType) throws Exception {
		String host = service + "." + rgwRegion + "." + rgwEndpointSuffix;
		try{
			URL url = new URL(urlStr);
			HttpURLConnection conn = (HttpURLConnection) url.openConnection();
			conn.setRequestMethod(method);
			conn.addRequestProperty("X-Amz-Date", date);
			conn.addRequestProperty("Host", host);
			conn.addRequestProperty("X-Amz-Content-Sha256","UNSIGNED-PAYLOAD");
			conn.addRequestProperty("Authorization", authorization);
			if(contentLength != null) {
				conn.addRequestProperty("Content-Length", contentLength);
			}
			if(range != null){
				conn.addRequestProperty("Range", range);
			}
			if(contentType != null){
				conn.addRequestProperty("Content-Type", contentType);
			}
			return conn;
		}catch (Exception e){
			throw new Exception(e);
		}
	}
}
`
`public class AWSV4Auth {

	private AWSV4Auth() {
	}

	public static class Builder {

		private String accessKeyID;
		private String secretAccessKey;
		private String regionName;
		private String serviceName;
		private String httpMethodName;
		private String canonicalURI;
		private String xAmzDate = getTimeStamp();
		private String currentDate = getDate();
		private TreeMap<String, String> queryParametes;
		private TreeMap<String, String> awsHeaders;
		private String payload;
		private boolean debug = false;

		public Builder(String accessKeyID, String secretAccessKey) {
			this.accessKeyID = accessKeyID;
			this.secretAccessKey = secretAccessKey;
		}

		public String getxAmzDate(){
			return xAmzDate;
		}

		public String getCurrentDate(){
			return currentDate;
		}

		public Builder regionName(String regionName) {
			this.regionName = regionName;
			return this;
		}

		public Builder serviceName(String serviceName) {
			this.serviceName = serviceName;
			return this;
		}

		public Builder httpMethodName(String httpMethodName) {
			this.httpMethodName = httpMethodName;
			return this;
		}

		public Builder canonicalURI(String canonicalURI) {
			this.canonicalURI = canonicalURI;
			return this;
		}

		public Builder queryParametes(TreeMap<String, String> queryParametes) {
			this.queryParametes = queryParametes;
			return this;
		}

		public Builder awsHeaders(TreeMap<String, String> awsHeaders) {
			this.awsHeaders = awsHeaders;
			return this;
		}

		public Builder payload(String payload) {
			this.payload = payload;
			return this;
		}

		public Builder debug() {
			this.debug = true;
			return this;
		}

		public AWSV4Auth build() {
			return new AWSV4Auth(this);
		}
	}

	private String accessKeyID;
	private String secretAccessKey;
	private String regionName;
	private String serviceName;
	private String httpMethodName;
	private String canonicalURI;
	private TreeMap<String, String> queryParametes;
	private TreeMap<String, String> awsHeaders;
	private String payload;
	private boolean debug = false;

	/* Other variables */
	private final String HMACAlgorithm = "AWS4-HMAC-SHA256";
	private final String aws4Request = "aws4_request";
	private String strSignedHeader;
	private String xAmzDate;
	private String currentDate;

	private AWSV4Auth(Builder builder) {
		accessKeyID = builder.accessKeyID;
		secretAccessKey = builder.secretAccessKey;
		regionName = builder.regionName;
		serviceName = builder.serviceName;
		httpMethodName = builder.httpMethodName;
		canonicalURI = builder.canonicalURI;
		queryParametes = builder.queryParametes;
		awsHeaders = builder.awsHeaders;
		payload = builder.payload;
		debug = builder.debug;

		/* Get current timestamp value.(UTC) */
		xAmzDate = builder.xAmzDate;
		currentDate = builder.currentDate;
//		currentDate = getDate();
	}

	/**
	 * 
	 *
	 * @return
	 */
	private String prepareCanonicalRequest() {
		StringBuilder canonicalURL = new StringBuilder("");

		canonicalURL.append(httpMethodName).append("\n");

		canonicalURI = canonicalURI == null || canonicalURI.trim().isEmpty() ? "/" : canonicalURI;
		canonicalURL.append(uriEncode(canonicalURI, false)).append("\n");

		StringBuilder queryString = new StringBuilder("");
		if (queryParametes != null && !queryParametes.isEmpty()) {
			for (Map.Entry<String, String> entrySet : queryParametes.entrySet()) {
				String key = entrySet.getKey();
				String value = entrySet.getValue();
				queryString.append(key).append("=").append(uriEncode(value, true)).append("&");
			}

			queryString.deleteCharAt(queryString.lastIndexOf("&"));

			queryString.append("\n");
		} else {
			queryString.append("\n");
		}
		canonicalURL.append(queryString);

		StringBuilder signedHeaders = new StringBuilder("");
		if (awsHeaders != null && !awsHeaders.isEmpty()) {
			for (Map.Entry<String, String> entrySet : awsHeaders.entrySet()) {
				String key = entrySet.getKey();
				String value = entrySet.getValue();
				signedHeaders.append(key).append(";");
				canonicalURL.append(key).append(":").append(value.trim()).append("\n");
			}
			canonicalURL.append("\n");
		} else {
			canonicalURL.append("\n");
		}

		 strSignedHeader = signedHeaders.substring(0, signedHeaders.length() - 1); 
		canonicalURL.append(strSignedHeader).append("\n");

		canonicalURL.append("UNSIGNED-PAYLOAD");

		if (debug) {
			System.out.println("##Canonical Request:\n" + canonicalURL.toString());
		}

		return canonicalURL.toString();
	}

	
	private String prepareStringToSign(String canonicalURL) {
		String stringToSign = "";

		stringToSign = HMACAlgorithm + "\n";

		stringToSign += xAmzDate + "\n";

		stringToSign += currentDate + "/" + regionName + "/" + serviceName + "/" + aws4Request + "\n";

		stringToSign += generateHex(canonicalURL);

		if (debug) {
			System.out.println("##String to sign:\n" + stringToSign);
		}

		return stringToSign;
	}


	private String calculateSignature(String stringToSign) {
		try {
			byte[] signatureKey = getSignatureKey(secretAccessKey, currentDate, regionName, serviceName);

			byte[] signature = HmacSHA256(signatureKey, stringToSign);

			String strHexSignature = bytesToHex(signature);
			return strHexSignature;
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return null;
	}


	public Map<String, String> getHeaders() {
		awsHeaders.put("x-amz-date", xAmzDate);
		String signature = getSignature();
		if (signature != null) {
			Map<String, String> header = new HashMap<String, String>(0);
			header.put("x-amz-date", xAmzDate);
			header.put("Authorization", buildAuthorizationString(signature));

			if (debug) {
				System.out.println("##Signature:\n" + signature);
				System.out.println("##Header:");
				for (Map.Entry<String, String> entrySet : header.entrySet()) {
					System.out.println(entrySet.getKey() + " = " + entrySet.getValue());
				}
				System.out.println("================================");
			}
			return header;
		} else {
			if (debug) {
				System.out.println("##Signature:\n" + signature);
			}
			return null;
		}
	}

	 public String getSignature(){
		String canonicalURL = prepareCanonicalRequest();

		String stringToSign = prepareStringToSign(canonicalURL);

		String signature = calculateSignature(stringToSign);

		return signature;
	}

		private String buildAuthorizationString(String strSignature) {
		return HMACAlgorithm + " "
				+ "Credential=" + accessKeyID + "/" + getDate() + "/" + regionName + "/" + serviceName + "/" + aws4Request + ", "
				+ "SignedHeaders=" + strSignedHeader + ", "
				+ "Signature=" + strSignature;
	}


	private String generateHex(String data) {
		MessageDigest messageDigest;
		try {
			messageDigest = MessageDigest.getInstance("SHA-256");
			messageDigest.update(data.getBytes("UTF-8"));
			byte[] digest = messageDigest.digest();
			return String.format("%064x", new BigInteger(1, digest));
		} catch (NoSuchAlgorithmException | UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		return null;
	}

	private byte[] HmacSHA256(byte[] key, String data) throws Exception {
		String algorithm = "HmacSHA256";
		Mac mac = Mac.getInstance(algorithm);
		mac.init(new SecretKeySpec(key, algorithm));
		return mac.doFinal(data.getBytes("UTF8"));
	}

	
	private byte[] getSignatureKey(String key, String date, String regionName, String serviceName) throws Exception {
		byte[] kSecret = ("AWS4" + key).getBytes("UTF8");
		byte[] kDate = HmacSHA256(kSecret, date);
		byte[] kRegion = HmacSHA256(kDate, regionName);
		byte[] kService = HmacSHA256(kRegion, serviceName);
		byte[] kSigning = HmacSHA256(kService, aws4Request);
		return kSigning;
	}

	final protected static char[] hexArray = "0123456789ABCDEF".toCharArray();

		private String bytesToHex(byte[] bytes) {
		char[] hexChars = new char[bytes.length * 2];
		for (int j = 0; j < bytes.length; j++) {
			int v = bytes[j] & 0xFF;
			hexChars[j * 2] = hexArray[v >>> 4];
			hexChars[j * 2 + 1] = hexArray[v & 0x0F];
		}
		return new String(hexChars).toLowerCase();
	}

		private static String getTimeStamp() {

		DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'");
		dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));//server timezone
		return dateFormat.format(new Date());
	}

		private static String getDate() {

		DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
		dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));//server timezone
		return dateFormat.format(new Date());
	}


	private String uriEncode(CharSequence input, boolean encodeSlash) {
		StringBuilder result = new StringBuilder();
		for (int i = 0; i < input.length(); i++) {
			char ch = input.charAt(i);
			if ((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '_' || ch == '-' || ch == '~' || ch == '.') {
				result.append(ch);
			} else if (ch == '/') {
				result.append(encodeSlash ? "%2F" : ch);
			} else {
				result.append(byteToHexUTF8(ch));
			}
		}
		return result.toString();
	}

	private String byteToHexUTF8(char c) {
		Charset charset = Charset.forName("utf-8");
		CharBuffer charBuffer = CharBuffer.allocate(1);
		charBuffer.put(c);
		charBuffer.flip();//字符编码为字节数组
		ByteBuffer byteBuffer = charset.encode(charBuffer);
		byte[] bytes = byteBuffer.array();
		StringBuffer stringBuffer = new StringBuffer();
		for (int i = 0; i < bytes.length; i++) {
			stringBuffer.append("%").append(Integer.toHexString(bytes[i] & 0xFF).toUpperCase());
		}
		return stringBuffer.toString();
	}
}`

**Comment by debora-ito** [comment]
@SJTUChenJi I see you wrote your own request signer. One of the features of using the SDK is that it calculates the signature for any AWS API operation so you don't have to. Is there a particular reason why you need to write your own signer?

**Comment by SJTUChenJi** [comment]
@debora-ito Yes. We cannot use the SDK.

**Comment by debora-ito** [comment]
In this case I suggest you reach out to the AWS Support Center or post you question in communities like StackOverflow. In this repository the issues are focused on problems with the SDK itself.

**Comment by praks1704** [comment]
Hi @HSJiChen , Were you able to resolve this error using manually API methods. If so, please do let me know how you have handled it. Thanks!
