### ISSUE TITLE
Getting revoked token after a globalSignOut

### ISSUE THREAD

**Issue by atoledo** [aws/aws-sdk-java#2449]
## Description
 Access/Refresh Tokens from a new login are being revoked by a previous globalSignOut

## Expected Behavior
After performing a globalSignOut or adminUserGlobalSignout, if a user logs in again the tokens should be valid.

## Current Behavior
After performing a globalSignOut or adminUserGlobalSignout, if a user logs in again the tokens quite often gets rejected with the following error:
`User Not Authorized exception occurred: Access Token has been revoked (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 7968c3dc-61a5-4837-b824-947bdab233ef; Proxy: null)`

## Steps to Reproduce
The issue was caught in an end-to-end test scenario, but then further scoped to simulate the issue in a single request.

A Cognito User Pool was setup with basically default configurations, and in addition an email address alias was created. There is also a lambda trigger to auto validate email address. An App client was configured with a secret, allowing USER_PASSWORD_AUTH and REFRESH_TOKEN_AUTH flows.

Steps:
1. SignUp a new user providing username (UUID), email and password
2. Login with email + password through cognitoClient.initiateAuth() providing username, password and secret hash
3. Perform an cognitoClient.adminUserGlobalSignOut() (Same results with cognitoClient.globalSignOut())
4. Login again with the same user and capture the new Access Token (Compared with Access Token from  step2 to ensure it's a new one)
5. Try to update email address for this user with cognitoClient.updateUserAttributes() providing the Access Token from step 4 and the email attribute 

NOTE: The same test works everytime if using the AWS CLI with the attached script, but through java SDK sometimes it works and sometimes the token is revoked.
[token_invalidation_snippet_test.sh.txt](https://github.com/aws/aws-sdk-java/files/5497534/token_invalidation_snippet_test.sh.txt)

## Context
Our users may be authenticated in multiple devices and we want to invalidate the session when he/she changes email and/or password, but keeping the main session still active (By generating a new token after signout).

Potential documentation bug: The documentation clearly states that the globalSignOut doesn't invalidate issued Access Tokens, but through example above if you try to use Access Token from  step 2 it will always fail with Access Token Revoked error message. 

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GlobalSignOut.html
"The user's current access and Id tokens remain valid until their expiry. Access and Id tokens expire one hour after they are issued."

## Your Environment
aws-cli/2.0.0 Python/3.7.3 Linux/5.4.0-52-generic botocore/2.0.0dev4
aws-java-sdk-cognitoidp version: 1.11.894
Ubuntu 18.04
openjdk 11.0.9 2020-10-20

**Comment by debora-ito** [comment]
@atoledo it's weird that you get the exception when using the Java SDK but not when using the aws-cli, there's no customization on the SDK side, the SDK simply call the API operations, so the problem may be on the service side.

I'll work in a repro case and report back.

**Comment by atoledo** [comment]
Only difference I've seen while debugging is that the Java SDK opens a socket connection to send the requests, while the CLI should be sending requests in different contexts. Maybe this extra overhead is enough to not reproduce the issue over CLI.

**Comment by debora-ito** [comment]
I confirm I observe the same behavior using the Java SDK, and it does not occur every time.

Are you calling `updateUserAttributes` immediately after the second `initiateAuthRequest`? I wonder if the problem is that the there was not enough time for the new access token to propagate through the cognito system.

**Comment by debora-ito** [comment]
I've added a sleep time of 2 seconds after `adminUserGlobalSignOut` and my local tests are not failing anymore. Can you try adding a sleep after `adminUserGlobalSignOut` or maybe after the second `initiateAuth` and check if you still see the exceptions?

**Comment by atoledo** [comment]
Yep, I also have it working with the sleep, which is not an ideal solution.
For now, I have a retry/loop (with maximum retry limit) validating if the token is valid before returning it, but also not ideal. Should this be opened as a Service issue?

**Comment by debora-ito** [comment]
> Should this be opened as a Service issue?

Yes, I can reach out to the Cognito team internally, they can clarify if this behavior is expected or not. Can you provide stacktraces and request-ids of the exceptions you get from `updateUserAttributes` in case they ask?

You can also open a support case via [AWS Support](https://aws.amazon.com/premiumsupport/) if you want to track the issue closely.

**Comment by atoledo** [comment]
AWS Support has been engageged for investigation on their end.
