### ISSUE TITLE
Add support for the C5n Bare Metal instance type

### ISSUE THREAD

**Issue by viktorkholod** [aws/aws-sdk-java#2452]
The C5n Bare Metal instances have been available since Aug 9, 2019 ([announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/introducing-amazon-ec2-i3en-and-c5n-bare-metal-instances/)). Unfortunately, AWS SDK for Java does not support them.

Could you please fix this?

**Comment by debora-ito** [comment]
@viktorkholod I see the C5n Bare Metal is not listed in the [InstanceType](https://github.com/aws/aws-sdk-java/blob/cca2afb7bb6f89bae01516e7c1474fb1bff80c4c/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/InstanceType.java) enum. The list is maintained by the EC2 service team, I will forward your request to them. 

In the meantime you can use the String alternative method.

**Comment by debora-ito** [comment]
Added in SDK version `1.11.919`. Thank you for reaching out.
