### ISSUE TITLE
Getting PKIX path build failure for aws com.amazonaws.SdkClientException

### ISSUE THREAD

**Issue by uddeshyapratik** [aws/aws-sdk-java#2457]
## Your Environment
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

While I am trying to upload an object to the S3 bucket from java using Eclipse. I am getting below exception

com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

![image](https://user-images.githubusercontent.com/12900819/98800386-50f50180-2436-11eb-94ce-9b2214a06772.png)

Any help on this will be appriciated

**Comment by debora-ito** [comment]
@uddeshyapratik Searching for "PKIX path building failed" in this repository you can find old issues about the same error.

Check this comment for more info: https://github.com/aws/aws-sdk-java/issues/2087#issuecomment-525847044
