### ISSUE TITLE
aws-lambda-java-core: error: package com.amazonaws.services.s3 does not exist

### ISSUE THREAD

**Issue by jianwu10** [aws/aws-sdk-java#2459]
## Describe the bug

Added aws-lambda-java-core package in dependencies. But when building the lambda package, had "error: package com.amazonaws.services.s3 does not exist"

## Current Behavior

error: package com.amazonaws.services.s3.model does not exist

## Your Environment

* AWS Java SDK version used: 1.11.x
* JDK version used: 1.8.0_242
* Operating System and version:

**Comment by debora-ito** [comment]
You need to add `aws-java-sdk-s3` as a dependency as well if you want to use the S3 API operations.

Check the Java SDK Developer guide for ways to add SDK modules to your project: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-install.html
