### ISSUE TITLE
AWS4Signer invalid signature for requests using DELETE method with a payload

### ISSUE THREAD

**Issue by nruspantini** [aws/aws-sdk-java#2462]
## Describe the issue

When using the AWS4Signer to sign a request that is using the DELETE method, whenever content is provided in the request, an error occurs upon sending request to API Gateway.

## Steps to Reproduce

Using code like below will result in the following error:
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.

```
final Map<String, String> headers = new HashMap<>();
headers.put(CONTENT_TYPE, APPLICATION_JSON);
headers.put("Host", HOST);
headers.put("Content-Length", Integer.toString(body.toString().getBytes(StandardCharsets.UTF_8).length));

Request<Void> request = new DefaultRequest<>("execute-api");
request.setHttpMethod(HttpMethodName.DELETE);
request.setEndpoint(new URI(API_ENDPOINT));
request.setResourcePath(resourcePath);
request.setHeaders(headers);
request.setContent(new StringInputStream(body.toString()));
signRequest(request, credentials);

Response<String> response = new AmazonHttpClient(new ClientConfiguration())
            .requestExecutionBuilder()
            .executionContext(new ExecutionContext(true))
            .request(request)
            .errorResponseHandler(new ErrorHandler())
            .execute(new ResponseHandler());
```

After debugging, I can see that the only difference in the canonical string AWS4Signer used and the expected canonical string is the contentShua256. The expected canonical sting has a contentShua256 that represent empty content but content is included in the request, so it does not match.

If content is provided to the request, then the signing works as expected and is sent successfully to API gateway.

Credentials are obtained from AWSSessionCredentialsProvider and a valid ARN Role.

All other methods are working fine with the same code snippet above. The signature issue is only with DELETE method that has a payload.

Please let me know if any other information is needed.

## Your Environment

* AWS Java SDK version used: 1.11
* JDK version used: 1.8

**Comment by debora-ito** [comment]
@nruspantini I'm not completely clear on the issue. Are you sending the request to an API you created on API Gateway?

You wrote:
> If content is provided to the request, then the signing works as expected and is sent successfully to API gateway.

but before that you wrote that if content is included in the request the signature does not match.

**Comment by nruspantini** [comment]
I have figured out the issue. This issue was not due to AWS4Signer. AWS4Signer was working as expected. What happened was the signature was not matching because the request body was being dropped when making the DELETE request. So the AWS4Signer generated the signature from content, but once API Gateway got the request with an empty body, it expected a signature for an empty body, resulting in a signature mismatch. Closing this issue.

**Comment by rubenmch** [comment]
> I have figured out the issue. This issue was not due to AWS4Signer. AWS4Signer was working as expected. What happened was the signature was not matching because the request body was being dropped when making the DELETE request. So the AWS4Signer generated the signature from content, but once API Gateway got the request with an empty body, it expected a signature for an empty body, resulting in a signature mismatch. Closing this issue.

I'm experiencing the same issue. Was the body being dropped by AmazonHttpClient ?

**Comment by AmitP30** [comment]
I'm experiencing the same issue. Was the body being dropped by AmazonHttpClient ?

**Comment by markyky** [comment]
Same issue here.

**Comment by hleadmin** [comment]
> 

How did you resolve the issue?

**Comment by hleadmin** [comment]
> I have figured out the issue. This issue was not due to AWS4Signer. AWS4Signer was working as expected. What happened was the signature was not matching because the request body was being dropped when making the DELETE request. So the AWS4Signer generated the signature from content, but once API Gateway got the request with an empty body, it expected a signature for an empty body, resulting in a signature mismatch. Closing this issue.

How did you resolve the issue then?
