### ISSUE TITLE
Route53 generates requests with invalid signature when secret key contains slash

### ISSUE THREAD

**Issue by vojtapol** [aws/aws-sdk-java#2464]
## Describe the bug
When executing the snippet below, I got an error:
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided
```

After I generated a new access key with a secret that does not contain `/` it started to work. This may or may not be related to the characters in the secret key. I tried regenerating the key because of this comment: https://github.com/aws/aws-sdk-js/issues/86#issuecomment-517231941

```java
public static void main(String[] args) {
    var credentials = new BasicAWSCredentials("ACCESSKEY", "seCret/keyContainsSlash");
    var credentialProvider = new AWSStaticCredentialsProvider(credentials);
    var route53 = AmazonRoute53ClientBuilder.standard()
        .withCredentials(credentialProvider)
        .withRegion(US_EAST_1)
        .build();
    
    route53.getHostedZone(new GetHostedZoneRequest("SOMEZONEID"));
}
```

## Expected Behavior
Request signatures should work no matter what special characters are in the the access secret.

* AWS Java SDK version used: `1.11.327`
* JDK version used: `corretto-11.0.9.1`
* Operating System and version: macOS 10.15.7

**Comment by debora-ito** [comment]
I'm not able to repro locally, using an access key with `/` and other special characters.

Where are you running the code, are you using a virtual environment?

**Comment by vojtapol** [comment]
> I'm not able to repro locally, using an access key with `/` and other special characters.
> 
> Where are you running the code, are you using a virtual environment?

No. I am running the code locally on my machine.

**Comment by debora-ito** [comment]
Can you try with the latest version of the SDK?

**Comment by vojtapol** [comment]
The issue was caused by using SMTP credentials instead of regular IAM credentials which have a different format.
