### ISSUE TITLE
CSVInput.java validates an empty string cannot be used as a fieldDelimiter although it is a valid use case

### ISSUE THREAD

**Issue by muttbag** [aws/aws-sdk-java#2469]
CSVInput.java will throw an IllegalArgumentException if the fieldDelimiter is an empty String, although the XML generated would be valid and the client would be consistent with AWS CLI and calling S3 Select API directly.

## Describe the issue
We are storing a CSV file in S3 with the fields delimited by null to reduce the size of the file, S3 Select is then used to query the data and return a subset. The query was tested on the AWS CLI and via creating an XML request to the S3 Select endpoint directly via Postman. The field delimiter is set as an empty string "" via the AWS CLI and an empty element for the XML request, S3 Select API interprets this as null and the field delimiter is set correctly for this use case. 
When attempting to implement the same request in S3 Java client we're unable to due to the CSVInput.java:450, although the XML generated from this state would be valid.

```
<SelectObjectContentRequest>
   <Expression>select s._1,from S3Object s</Expression>
   <ExpressionType>SQL</ExpressionType>
   <InputSerialization>
      <CSV>
         <FileHeaderInfo>IGNORE</FileHeaderInfo>
         <FieldDelimiter></FieldDelimiter>
         <AllowQuotedRecordDelimiter>true</AllowQuotedRecordDelimiter>
      </CSV>
   </InputSerialization>
</SelectObjectContentRequest>
```

A comment at CSVInput.java:452 suggests an empty String would not be valid because the field will be converted to a Character for recordDelimiter but this isn't the case for fieldDelimiter. Perhaps this validation could be done on when conversion takes place recordDelimiter as this does not happen before the XML is created for fieldDelimiter.

## Steps to Reproduce
```
        SelectObjectContentRequest request = new SelectObjectContentRequest();
        request.setBucketName("bucket");
        request.setKey("key");
        request.setExpression("query");
        request.setExpressionType(ExpressionType.SQL);

        CSVInput csvInput = new CSVInput();
        csvInput.setFieldDelimiter("");
        csvInput.setAllowQuotedRecordDelimiter(true);
        csvInput.setFileHeaderInfo(FileHeaderInfo.IGNORE);

        InputSerialization inputSerialization = new InputSerialization();
        inputSerialization.setCsv(csvInput);
        inputSerialization.setCompressionType(CompressionType.GZIP);
        request.setInputSerialization(inputSerialization);
        OutputSerialization outputSerialization = new OutputSerialization();
        JSONOutput jsonOutput = new JSONOutput();
        jsonOutput.setRecordDelimiter(",");
        outputSerialization.setJson(jsonOutput);
        request.setOutputSerialization(outputSerialization);

        final AtomicBoolean isResultComplete = new AtomicBoolean(false);
        SelectObjectContentResult result = this.s3Client.selectObjectContent(request);

```
## Current Behavior
An IllegalArgumentException is thrown.

```
        Caused by: java.lang.IllegalArgumentException: fieldDelimiter must not be empty-string.
	at com.amazonaws.services.s3.model.CSVInput.validateNotEmpty(CSVInput.java:454)
	at com.amazonaws.services.s3.model.CSVInput.setFieldDelimiter(CSVInput.java:322)
```
	

## Your Environment

* AWS Java SDK version used: 1.11.913
* JDK version used: jdk-13.0.2
* Operating System and version: macOS Catalina

**Comment by debora-ito** [comment]
Hi @muttbag thank you for reaching out. I'll mark this as a bug since it works when you call the S3 Select API directly.

**Comment by debora-ito** [comment]
@muttbag We apologize but this will not get fixed in v1.

I ran a quick test and the validation is not present in v2, v2 supports an empty fieldDelimiter in CSVInput. So the recommendation here is to migrate to Java SDK v2.
