### ISSUE TITLE
md5 of download file is not true

### ISSUE THREAD

**Issue by xiongxinxin** [aws/aws-sdk-java#2476]
### Today i test a program,upload is not problem,but md5 of download file is not true.

**Before** uploading file,i calculate md5 of source file and get value '5993ca0127e568565c5eb79a38010dc4';

**Then** i download the object that i upload just now from ceph, and then calculate md5 of this object，get 'c515ef64817e540b6f1a87f5d83611da'.

**That is my code:**
`
@Service
public class FileOperationServiceImpl implements FileOperationService {
    @Autowired
    private AmazonS3 amazonS3;

    private static final String OBJECT_KEY = "nginxtest.tar";

    private static final String SOURCE_FILE = "/root/source/" + OBJECT_KEY;
    private static final String TARGET_FILE = "C:\\Users\\HP\\Desktop\\" + OBJECT_KEY;

    /**
     * 上传文件
     */
    @Override
    public void uploadFile() {
        TransferManager manager = TransferManagerBuilder.standard().withS3Client(amazonS3).build();
        Upload upload = manager.upload(Constant.BUCKET_NAME, OBJECT_KEY, new File(SOURCE_FILE));

        try {
            upload.waitForUploadResult();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    /**
     * 下载文件
     */
    @Override
    public void downloadFile() {
        TransferManager manager = TransferManagerBuilder.standard().withS3Client(amazonS3).build();
        Download download = manager.download(Constant.BUCKET_NAME, OBJECT_KEY, new File(TARGET_FILE));
        try {
            download.waitForCompletion();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
`

**my dependency is:**
`        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.457</version>
        </dependency>
`

**The result is the same whether operation system is windows or linux.**

Hope response!

**Comment by xiongxinxin** [comment]
I think this is a bug,although the length of the object is same downloaded from ceph,but md5 is not same.

**Comment by debora-ito** [comment]
@xiongxinxin Depending on the file type, this can be caused by downloading the file in a different operational system from the one you uploaded it - for example, '\n' writes a newline in UNIX while for Windows is '\r\n'. 

It could also be possible that Ceph changes something in the file in their upload/download process, specially if the file is large.

I tested locally your sample code transferring the file directly to S3 (not using Ceph) and the md5 matches after the download. Can you try uploading directly to S3?

**Comment by xiongxinxin** [comment]
@debora-ito thanks for your reply.

**I correct the storage  i used  is minio,not ceph.**
I upload the file by my code method 'uploadFile()',then download directionly from minio by links,not by my code method 'downloadFile()',finally i get the file that i get md5 of the file is '5993ca0127e568565c5eb79a38010dc4'. In other words,upload method 'uploadFile()' is fine,md5 value not change.

But downloading file by code method 'downloadFile()',the md5 of the file is 'c515ef64817e540b6f1a87f5d83611da'.
So i think the question is method 'downloadFile()'.

I don`t know how you download this file,directly download by links or code method 'downloadFile()'?

**Comment by debora-ito** [comment]
You can use the SDK S3 client like you're already using but without overriding the EndpointConfiguration in the s3Client (I assume to use minio you have to set a different endpoint). Or you can access it via [AWS Console](https://aws.amazon.com/console/).

But if the md5 matches after the upload, the difference is probably caused by the different Operational Systems.

**Comment by xiongxinxin** [comment]
If i use minio,i must override the EndpointConfiguration,otherwise i cann`t connect to minio. Furthermore,minio is not related to the AWS console.

Today i create TransferManager with method '**withDisableParallelDownloads(true)'** ,downloading file by single file to download.
I get the right md5,so I don`t think  the reason is the different Operational Systems.

**Comment by debora-ito** [comment]
@xiongxinxin hi, I'm sorry for the long delay in response here. 

If you get the MD5 you expected when the file is downloaded in one single part, then I guess it depends on how you are calculating the MD5. S3 uses the [eTag header](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) to verify content change, no metadata, and for multipart uploads the eTag is calculated differently, it is not a simple MD5 hash. The SDK TransferManager uses the eTag to check the integrity of the downloaded file, if they don't match it throws an exception.
