### ISSUE TITLE
Kinesis PutRecords response should tell which requests have failed

### ISSUE THREAD

**Issue by leosurwiki** [aws/aws-sdk-java#2480]
According to:
https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html
This API tells user how many requests have failed, but not which record have failed, so we still have to retry for a full batch. 

To ensure the order guarantee, I keep every record in the batch to have a unique partition key, so I would appreciate if the response tells me records with which partition key have failed so I can retry partially. 

Another thing, the documentation says this API may still throw `ProvisionedThroughputExceededException`, is that still true? Because the failed PutRecordsResultEntry also contains the exception type which can also be `ProvisionedThroughputExceededException`.

**Comment by debora-ito** [comment]
@leosurwiki take a look at Kinesis Data Streams Dev Guide - [Adding Multiple Records with PutRecords](https://docs.aws.amazon.com/streams/latest/dev/developing-producers-with-sdk.html#kinesis-using-sdk-java-putrecords). According to the docs:

> The PutRecords response includes an array of response Records. Each record in the response array directly correlates with a record in the request array using natural ordering, from the top to the bottom of the request and response. The response Records array always includes the same number of records as the request array.

So you can use the position of the failed record in the response array to retry only the failed records, there's a code example showing how to do this in the Dev Guide page.

As for the PutRecords API possibly throwing ProvisionedThroughputExceededException, the API does not have a rate limit but has a payload limit, look for PutRecords in the [Kinesis Data Streams Quotas and Limits doc](https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html) to know more.
