### ISSUE TITLE
JSONOutput for SelectObjectContentRequest OutputSerialization returns invalid JSON

### ISSUE THREAD

**Issue by muttbag** [aws/aws-sdk-java#2481]
When selecting the OutputSerialization as JSON for results from S3 Select, the returned JSON is not valid.

## Describe the bug
When the contents of the SelectRecordsInputStream is converted to a String, the JSON within is malformed and not parseable as JSON.

The response is a comma separated list of JSON objects rather than valid JSON:

```
{
	"_1": "result1",
	"_3": "result3"
}, {
	"_1": "result1",
	"_3": "result3"
},

```
## Expected Behavior
The response should be valid JSON and should be parseable as JSON without converting to String and editing. 

## Current Behavior
Response is invalid JSON and as such has to be converted to a String and edited into a JSON array before being parsed as JSON.

## Steps to Reproduce

```
final SelectObjectContentRequest selectObjectContentRequest = new SelectObjectContentRequest();

        final CSVInput csvInput = new CSVInput();
        csvInput.setFieldDelimiter(",");
        csvInput.setAllowQuotedRecordDelimiter(true);
        csvInput.setFileHeaderInfo(FileHeaderInfo.IGNORE);

        final InputSerialization inputSerialization = new InputSerialization();
        inputSerialization.setCsv(csvInput);
        inputSerialization.setCompressionType(CompressionType.GZIP);
        selectObjectContentRequest.setInputSerialization(inputSerialization);

        final OutputSerialization outputSerialization = new OutputSerialization();
        final JSONOutput jsonOutput = new JSONOutput();
        jsonOutput.setRecordDelimiter(",");
        outputSerialization.setJson(jsonOutput);
        selectObjectContentRequest.setOutputSerialization(outputSerialization);

        s3Client.selectObjectContent(selectObjectContentRequest);

        final SelectObjectContentResult result = s3Client.selectObjectContent(query);

        try (InputStream resultInputStream = result.getPayload().getRecordsInputStream(customSelectObjectContentEventVisitor)) {

            //Jackson
            final ObjectMapper objectMapper = new ObjectMapper();
            objectMapper.configure(JsonParser.Feature.AUTO_CLOSE_SOURCE, true);

            //JsonDomainObject to map the S3 Select response to
            List<JsonDomainObject> resultList = objectMapper.readValue(resultInputStream, new TypeReference<>() {});

        } catch (IOException e) {
            //Error as JSON is invalid
        }

```

## Possible Solution
Perhaps as a JSON object containing the response as nested JSON objects or array of JSON objects:

```
[{
	"_1": "result1",
	"_3": "result3"
}, {
	"_1": "result1",
	"_3": "result3"
}]

```
## Context
We're having to do extra processing on the response and manually wrapping with brackets to convert to a JSON array - adding risks for errors rather than agreeing to a standard.

## Your Environment
AWS Java SDK version used: 1.11.913
JDK version used: jdk-13.0.2
Operating System and version: macOS Catalina

**Comment by debora-ito** [comment]
Hi @muttbag I'm sorry it took so long to get a reply.

The output serialization describes the format of individual records. It doesn't mean that having `,` as  a record delimiter will make the full response a valid JSON array. 

As a comparison, this would be a JSON output with the default record delimiter (newline):

```json
{"_1":"Jaws","_2":" Steven Spielberg","_3":" 1975"}
{"_1":"Back to the Future","_2":" Robert Zemeckis","_3":" 1985"}
{"_1":"The Hurt Locker","_2":" Kathryn Bigelow","_3":" 2008"}
```

and this would be the equivalent in CSV output:
```
Jaws, Steven Spielberg, 1975
Back to the Future, Robert Zemeckis, 1985
The Hurt Locker, Kathryn Bigelow, 2008
```

You need to keep parsing the JSON output using the provided record delimiter.

**Comment by muttbag** [comment]
Ahh I see, my mistake. Thanks for the reply @debora-ito and I'll close this off :)
