### ISSUE TITLE
DynamoDB StandardConverters don't Support Enums with toString Method

### ISSUE THREAD

**Issue by bountin** [aws/aws-sdk-java#2484]
## Describe the bug

The `StandardTypeConverters` fail to convert enums with custom `toString` methods.

## Expected Behavior

Enum serialization should exclusively use the enum's name.

## Current Behavior

Enum serialization falls through to `toString` serialization.

## Steps to Reproduce

```java
package com.amazonaws.services.dynamodbv2.datamodeling;

public class Test {

    public static void main(String[] args) {
        final DynamoDBTypeConverter<String, TestEnum> serializer = StandardTypeConverters.factory()
                .getConverter(String.class, TestEnum.class);
        final String result = serializer.convert(TestEnum.ONE);

        System.out.println("EXPECTED: " + TestEnum.ONE.name());
        System.out.println("ACTUAL:   " + result);

        final DynamoDBTypeConverter<TestEnum, String> deserializer = StandardTypeConverters.factory()
                .getConverter(TestEnum.class, String.class);
        // fails but shouldn't
        deserializer.convert(result);
    }

    enum TestEnum {
        ONE;

        @Override
        public String toString() {
            return "toString";
        }
    }
}
```
## Possible Solution

Internally the converters use the `Scalar` class which returns `Scalar.DEFAULT` for target enums in https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardTypeConverters.java#L65 

`target.<T>type()` is then `Object` instead of `Enum` which leads to the mentioned `toString` converter.

## Your Environment

From at least AWS SDK version 1.11.30 up to 1.11.934.

## Workaround
Either remove the custom `toString` method (if possible), or implement custom converters/marshallers for each enum.

**Comment by debora-ito** [comment]
Hi @bountin, I would agree to discuss this change if the class was not annotated with [@SdkInternalApi](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/annotation/SdkInternalApi.java), meaning it's for internal use only, it should not be used outside the core module.

Feel free to reach out if you have further questions.
