### ISSUE TITLE
AmazonS3ClientParams abstract class is missing public keyword

### ISSUE THREAD

**Issue by ionapatterson** [aws/aws-sdk-java#2485]
AmazonS3ClientParams, AmazonS3EncryptionClientParams and AmazonS3EncryptionClientV2Params are missing the public keyword forcing any subclasses of their respective client classes to use the finaled ParamsWrapper classes which results in Client subclasses being unable to include any additional context in their constructor.

Solution: add public keyword to AmazonS3ClientParams, AmazonS3EncryptionClientParams and AmazonS3EncryptionClientV2Params.

**Comment by debora-ito** [comment]
Hi @ionapatterson 

[`AmazonS3EncryptionClientParams`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3EncryptionClientParams.java) is deprecated and will not get any more updates.
[`AmazonS3ClientParams`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3ClientParams.java) and [`AmazonS3EncryptionClientV2Params`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3EncryptionClientV2ParamsWrapper.java) are meant for SDK internal use only (see the @SdkInternalApi annotation). SDK internal use means that breaking changes can occur, so external tools should not depend on these classes.
