### ISSUE TITLE
Synchronization in AmazonS3Client::fetchRegionFromCache method

### ISSUE THREAD

**Issue by rbalamohan** [aws/aws-sdk-java#2488]
## Describe the bug
There are cases when lots of threads are trying to execute invoke() method. E.g: big data use case, where multiple threads  query S3 for listing operation.

In such cases, "fetchRegionFromCache" gets executed multiple times causing additional HEAD requests and delays.

It would be good to mark "AmazonS3Client::fetchRegionFromCache" as synchornized to avoid unwanted HEAD requests. 

This would help in improving performance of listing with multiple threads in client side. 

## Your Environment
aws-java-sdk-bundle-1.11.563.jar
OpenJDK 1.8.0_262

**Comment by debora-ito** [comment]
And also, since it's an improvement, I'm changing this to a feature request.
