### ISSUE TITLE
Redshift - JAVA SDK v1.11.171 - Getting empty response for describeClusters()

### ISSUE THREAD

**Issue by susindran1308** [aws/aws-sdk-java#2490]
Hi,
I am trying to list all the redshift clusters via 'describeClusters' API via AWS java SDK version v1.11.171.

```
 DescribeClustersRequest describeClustersRequest = new DescribeClustersRequest();
 DescribeClustersResult describeClustersResult = redshiftClient.describeClusters();
```
I am getting an **empty response every time** but I am having clusters in my account.
When tried with AWS command line, I can get the list of clusters.

Please help me with resolving this.

Thanks in advance.

**Comment by debora-ito** [comment]
Check if `redshiftClient` is configured using the correct region and credentials.

**Comment by susindran1308** [comment]
Yes I am using correct region and credentials. I am not getting any exceptions. 
`describeClustersResult.getClusters()` is an empty list.

**Comment by susindran1308** [comment]
Hi, I am getting response from the API with the same code now. Thank you.
