### ISSUE TITLE
Kinesis - JAVA SDK v1.11.171 - Impact of disabling CBOR 'com.amazonaws.sdk.disableCbor' in AWS SDK?

### ISSUE THREAD

**Issue by susindran1308** [aws/aws-sdk-java#2493]
Hi,

**Use case**: To list all the kinesis data streams using [listStreams](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_ListStreams.html) API but we received the below exception:
```
Error in fetching data from Kinesis client. Message: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
You have two possible resolutions:
1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance) 
```
Reference Post - [Link](https://stackoverflow.com/questions/60152964/getting-service-amazonkinesis-status-code-502-with-apache-flink-and-localstac)
Referring [this](https://stackoverflow.com/a/60542671/9362607) comment, We set the system property **com.amazonaws.sdk.disableCbor** to true.
After setting the property, we can get the list of streams. 

Questions:
1. Want to know the impact of disabling it overall?
2. Will other service APIs(SQS,ECS,etc,.) be affected by disabling this or only Kinesis?

**Comment by debora-ito** [comment]
Hi @susindran1308 if CBOR protocol is disabled the SDK will use Jackson's JSON, which will have slower performance.
Right now it will only affect Kinesis.
