### ISSUE TITLE
com.amazonaws.services.apigatewayv2.model.DomainNameConfiguration.withApiGatewayDomainName() - What does it do?

### ISSUE THREAD

**Issue by niekvanderkooy** [aws/aws-sdk-java#2495]
When creating a new domain in the AWS API Gateway, I first tried using:

```
DomainNameConfiguration domainNameConfiguration = new DomainNameConfiguration()
                .withEndpointType(EndpointType.REGIONAL)
                .withSecurityPolicy(SecurityPolicy.TLS_1_2)
                .withCertificateArn("MY_ARN")
                .withApiGatewayDomainName("MY_DOMAIN");
CreateDomainNameRequest createDomainNameRequest = new CreateDomainNameRequest()
                    .withDomainNameConfigurations(domainNameConfiguration)
AmazonApiGatewayV2.createDomainName(createDomainNameRequest);
```
This request creates an Internal Server Error (Without extra information, which might be a bug of itself).
Turns out, I need to provide my domain to the `CreateDomainNameRequest `, like 
`CreateDomainNameRequest createDomainNameRequest = new CreateDomainNameRequest().withDomainNameConfigurations(domainNameConfiguration).withDomainName("MY_DOMAIN")`

This create an API Gateway domain, with the domain name as passed to CreateDomainNameRequest.withDomainName().
This creates several questions:

1. Why does .withApiGatewayDomainName() exist on DomainNameConfiguration? Does it have any effect? If I change it to something random, everything still seems to work.
2. This seems to indicate that a `CreateDomainNameRequest` only creates a single domain name (Which is fair enough, since else I would expect it to be called `CreateDomainNamesRequest` - plural. But then, why does the class accept _multiple_ `DomainNameConfiguration`s?

## Your Environment
* AWS Java SDK version used: 1.11.942

**Comment by debora-ito** [comment]
Hi @niekvanderkooy I'm no expert in API Gateway APIs so I'll send your questions to the service team, I will reply when I hear back.

**Comment by debora-ito** [comment]
Here's the response from the API Gateway team:

> 1 - Why does .withApiGatewayDomainName() exist on DomainNameConfiguration? Does it have any effect? If I change it to something random, everything still seems to work.

The ApiGatewayDomainName is the APIGateway-issued domain name you create an Alias/CNAME to from your actual domain name. 
For Regional domains, this is the record that begins with "d-", and for EDGE domains, this is the backing CloudFront distribution's DNS. 
You can provide a value, but it's not used; we overwrite it with the issued ApiGatewayDomainName above.

>  2 - This seems to indicate that a CreateDomainNameRequest only creates a single domain name (Which is fair enough, since else I would expect it to be called CreateDomainNamesRequest - plural. But then, why does the class accept multiple DomainNameConfigurations?

Each domain name configuration represents a different endpoint type. For instance, you can have both an EDGE and REGIONAL domain name configuration at the same time on a single domain name. The primary use case for this is migrating from one endpoint type to another. 

Let us know if you have more questions.

**Comment by niekvanderkooy** [comment]
Thanks, that clears it up! Although a point of improvement might still be to make sure that calling `AmazonApiGatewayV2.createDomainName(createDomainNameRequest);` without a `.withDomainName("X")` value in the `CreateDomainNameRequest` returns a sensible error message, instead of a generic 500.
