### ISSUE TITLE
update_skip_null_attributes not working with DynamoDBDocument

### ISSUE THREAD

**Issue by imjuoy** [aws/aws-sdk-java#2496]
The dynamoDBMapper configuration save.update_skip_null_attributes does not seem to work with @DynamoDBDocument annotated nested json object

## Steps to Reproduce
public class Test
{
   @DynamoDBHashKey private String testPk;
  @DynamoDBRangeKey private String testSk;
  @DynamoDBAttribute private String name;
  **@DynamoDBAttribute private MyClass myClass;**
}

@DynamoDBDocument
public class MyClass{
@DynamoDBAttribute private String myName;
@DynamoDBAttribute private String mySubject;
}

Above is an example of my test mapper class which contains a nested json represented by DynamoDBDocument.
My update mapper config is below:

`
DynamoDBMapperConfig updateMapperConfig =
        DynamoDBMapperConfig.builder()
            .withSaveBehavior(DynamoDBMapperConfig.SaveBehavior.UPDATE_SKIP_NULL_ATTRIBUTES)
            .withConsistentReads(DynamoDBMapperConfig.ConsistentReads.EVENTUAL)
            .build();
`

## Current Behavior
What I am seeing is the **update skip null attributes** do work for the parent class (Test.java) but does not work for the nested Json class(MyClass.java). Hence when I set, the attributes of Test.java to null, updates are skipped, but when I set the attributes of MyClass.java to null, they are set to null. Is this expected? If I am supposed to have update_skip_null_attributes for the nested Json class, am I supposed to declare a separate mapper for it?

## Your Environment
* AWS Java SDK version used: 1.11.757
* JDK version used: 11

**Comment by imjuoy** [comment]
I think this has been addressed in 
https://forums.aws.amazon.com/thread.jspa?messageID=726446

**Comment by chxiaowu** [comment]
> I think this has been addressed in https://forums.aws.amazon.com/thread.jspa?messageID=726446

@imjuoy This url seems be archived....

**Comment by chxiaowu** [comment]
@imjuoy would you please share, was it able to update some filed of custom class annotation by DynamoDBDocument?
