### ISSUE TITLE
RegionUtils.getRegionsForService(AWSNetworkFirewall.ENDPOINT_PREFIX) returns empty list

### ISSUE THREAD

**Issue by moeshue** [aws/aws-sdk-java#2498]
I think the feature was released around NOV. 2020....but I still can get the supported regions by sdk

**Comment by debora-ito** [comment]
Thank you for calling our attention to this, @moeshue. 

We parse this information from the [endpoints.json](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json) file, and the service teams are responsible for adding their endpoints information to it. AWS Network Firewall is not present in the file, I'll contact the service team and ask for a fix.

**Comment by debora-ito** [comment]
`RegionUtils.getRegionsForService(AWSNetworkFirewall.ENDPOINT_PREFIX)` is now returning the relevant AWS Network Firewall endpoints, starting SDK version `1.12.66`.

Closing this. Feel free to reach out if you have any other question or concern.
