### ISSUE TITLE
Prefix of "/" is required for the bucket name when calling `AmazonS3.listObjects(String bucketName)`, when using the s3 SDK for local development with localstack

### ISSUE THREAD

**Issue by xiandalong** [aws/aws-sdk-java#2499]
## Describe the bug
I was using localstack 0.10.4 as the simulator for local s3. I created a bucket and put a file under the bucket, but I when using `AmazonS3.listObjects(String bucketName)` in the s3 sdk, it gives me an empty list. I spent quite some time on this, and found out that a prefix of `"/"` is needed for the bucketName, even though the bucket names you get from `AmazonS3.listBuckets()` doesn't have the prefix.

## Expected Behavior
I should be able to just use bucket name as input without the prefix. (This applies to not only `AmazonS3.listObjects(String bucketName)` , but also `AmazonS3.doesObjectExist(String bucketName, String objectName)`, not sure if there're other methods suffering from the same issue.)

## Current Behavior
I need to include a prefix of `"/"` for the bucket name when calling `AmazonS3.listObjects(String bucketName)`, when working with localstack s3 simulator.

## Steps to Reproduce
* Run localstack 0.10.4 in docker (actually tried to use latest 0.12.6 and seeing the same issue)
* Use AWS s3 java SDK in a java application
* With AWS CLI tool, Create bucket and put a file under the bucket
* In the java application, create an instance of `AmazonS3` connected to localstack, and print the result of `AmazonS3.listObjects(String bucketName)`
* The result is an empty list.

## Possible Solution
I shouldn't need the prefix for a bucket name.

## Context
I was using localstack as a s3 simulator for local development, and I wanted to be able to develop without connecting to a real s3 bucket on the cloud.

## Your Environment
* AWS Java SDK version used: 1.11.940
* JDK version used: 8
* Operating System and version: MacOS Catalina 10.15.7

**Comment by debora-ito** [comment]
Hi @xiandalong this seems to be a limitation on localstack side. I wasn't able to reproduce calling S3 APIs directly:

```java
AmazonS3 s3Client = AmazonS3ClientBuilder.standard().build();
ObjectListing l = s3Client.listObjects(BUCKET);
```

I get all objects in the response.

I suggest you open an issue in the localstack repo: https://github.com/localstack/localstack

**Comment by xiandalong** [comment]
Thanks @debora-ito . Created issue in `localstack` here: https://github.com/localstack/localstack/issues/3573, closing this one.
