### ISSUE TITLE
Protection against CRLF email injection when using SendEmailRequest

### ISSUE THREAD

**Issue by chtpl** [aws/aws-sdk-java#2500]
I want to use the AWS SDK to send an email via Amazon SES and want to make sure no one can inject email header fields.
So my question is whether I need to validate the user input myself or does SES / AWS SDK do that for me?

For example, I'm a bit worried about the `recipientEmail` and `from` fields in the below code

## Steps to Reproduce
```
AmazonSimpleEmailServiceClientBuilder.standard()
                        .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretAccessKey)))
                        .withRegion(Regions.EU_CENTRAL_1)
                        .build();
        SendEmailRequest request =
                new SendEmailRequest()
                        .withDestination(new Destination().withToAddresses(recipientEmail))
                        .withMessage(
                                new Message()
                                        .withBody(
                                                new Body()
                                                        .withHtml(new Content().withCharset("UTF-8").withData(htmlBody))
                                                        .withText(new Content().withCharset("UTF-8").withData(plaintTextBody)))
                                        .withSubject(new Content().withCharset("UTF-8").withData(subject)))
                        .withSource(from);
        client.sendEmail(request);
```

## Your Environment

* AWS Java SDK version used: 1.11.722
* JDK version used: openJDK 1.8.0_275
* Operating System and version: Ubuntu 20.04

**Comment by debora-ito** [comment]
@chtpl thank you for reaching out. It depends on what you mean by "validate the user input".

- The values you set in `SendEmailRequest` are the values that will be sent to the SES service. Destination, source and message values will be sent in the form of key-value pairs in the body of a POST request, url-encoded; they will not be HTTP headers.
- The source email address needs to be individually verified with Amazon SES. You can read more about verifying identities and other options like verifying a domain address or adding email labels  in the [Amazon SES Developer Guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html).

From what I read about CRLF email injection, it's more likely to occur in web application input forms. Do you have any specific concerns? In which step of the request call?

**Comment by chtpl** [comment]
> @chtpl thank you for reaching out. It depends on what you mean by "validate the user input".
> 
>     * The values you set in `SendEmailRequest` are the values that will be sent to the SES service. Destination, source and message values will be sent in the form of key-value pairs in the body of a POST request, url-encoded; they will not be HTTP headers.
> 
>     * The source email address needs to be individually verified with Amazon SES. You can read more about verifying identities and other options like verifying a domain address or adding email labels  in the [Amazon SES Developer Guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html).
> 
> 
> From what I read about CRLF email injection, it's more likely to occur in web application input forms. Do you have any specific concerns? In which step of the request call?

The recipient email we get from a web form. The question was just more general. Does AWS do input validation against SMTP injection or do we have to do it ourself?

The source email address will be configured in the environment variable of the Java application sending the message with AWS SDK

**Comment by debora-ito** [comment]
No validation is made on the client side.
I don't know if there's any validation made on the AWS SES side, I will forward your question to the service team and comment here when I get a reply.

**Comment by chtpl** [comment]
OK :) is there any news so far?

**Comment by debora-ito** [comment]
Here's the SES Team reply: 

SES performs server-side validation of customer input on the SendEmail API. The source field, in addition to being well-formatted, must also be a verified identity. SES recommends customers thoroughly test the API to ensure it fulfills all their requirements. We do recommend customers apply best-practices and sanitize any external input themselves before passing it to any downstream system (SES included).

**Comment by debora-ito** [comment]
Let us know if you have any further questions.
