### ISSUE TITLE
Vulnerability found in netty version

### ISSUE THREAD

**Issue by deporcali** [aws/aws-sdk-java#2501]
The following netty version needs to be updated to 4.1.59.Final due to vulnerability found regarding Information Disclosure

https://github.com/aws/aws-sdk-java/blob/2155b4d8181f97149591318a4f382dffe63c2f9e/pom.xml#L336 

See https://app.snyk.io/vuln/SNYK-JAVA-IONETTY-1070799 for more info on the issue

**Comment by debora-ito** [comment]
Thank you for reporting this @deporcali, we will work to upgrade it.

**Comment by debora-ito** [comment]
Upgraded netty to `4.1.59.Final` in SDK version `1.11.953`.
