### ISSUE TITLE
InstanceRefresh does not respect the instance warmup if provided

### ISSUE THREAD

**Issue by alexbarnes** [aws/aws-sdk-java#2504]
In our testing when we provide a value for `RefreshPreferences.instanceWarmup` which differs from the ASG's default health check grace period is not respected.

## Expected Behavior

We would expect that we can provide a specific value for the instance refresh when triggered via the API which differs from the ASG's default health check grace period and this would be used for the instance refresh.

## Current Behavior

It appears (although it's hard to be sure due to lack of UI/SDK information) that the ASG's default health check grace period is always used as the value for `instanceWarmup`.

## Context

Our application requires a longer health check grace period when initially deployed because it can create its own schema containing hundreds of tables and can also import a previous database position. All of this combined can push the warmup over 5 minutes.

However, when we are releasing a patch we know that we are able to startup much quicker and would like to reduce the instance refresh time by reducing the warmup in this specific case. Ideally this would be provided to `startInstanceRefresh` via the SDK.

## Your Environment

* AWS Java SDK version used: 1.11.842
* JDK version used: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
* Operating System and version: Mac OS 10.14.6

**Comment by debora-ito** [comment]
@alexbarnes can you provide a code sample showing how you're setting the `RefreshPreferences.instanceWarmup`?

**Comment by alexbarnes** [comment]
Of course.

`autoScaling.startInstanceRefresh(new StartInstanceRefreshRequest().withAutoScalingGroupName(autoScalingGroup).withPreferences(new RefreshPreferences().withInstanceWarmup(120)));`

**Comment by debora-ito** [comment]
Sorry for the delay in response. I ran some tests and I see what you mean. I created an auto scaling group with the default health check period of 300 seconds, and then called startInstanceRefresh with 0 instance warmup, and it stays in status `Waiting for a health check interval to pass before continuing` for some time.

I'll forward the question to the Auto Scaling Group team, will comment here when I hear back.

**Comment by alexbarnes** [comment]
Thank you @debora-ito . Much appreciated.

**Comment by debora-ito** [comment]
@alexbarnes the Auto Scaling Group Team clarified some things, and this behavior is expected. Here's the reply:

This behavior is expected. The health check grace period signifies the amount of time we wait for a newly launched instance before we run a health check on it. During an instance refresh, before we move onto replacing the next instance, we wait for the instance warmup time to complete and for the instance to pass a health check.

So if the health check grace period is longer than the instance warm up time - we wait for the instance to warm up, and then we wait for the health check to pass (after the grace period ends) before moving on to replacing the next instance. This way we make sure the instance has enough time to become healthy before moving on to replacing the next instance.

You can find more details here: https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html

---

The documentation referred describes how the rolling updates work:

> During an instance refresh, Amazon EC2 Auto Scaling takes a set of instances out of service, terminates them, and then launches a set of instances with the new configuration. After that, instances are replaced on a rolling basis. In a rolling update, when a new instance launches, Amazon EC2 Auto Scaling waits until the instance passes a health check and completes warm-up, before moving on to replace another instance. This process repeats until all instances are replaced.

Let us know if you have more questions.
