### ISSUE TITLE
Closeable objects to not declare Exception in close() method signature

### ISSUE THREAD

**Issue by tkowalcz** [aws/aws-sdk-java#2505]
This is a proposal to improve the API. Given that Amazon SDK embraces unchecked exception which make for a better
API UX when coding you could go step further and clean up the API of close method of `Closeable` objects like `S3Object` or `S3ObjectInputStream`.

## Describe the Feature

I propose to modify SDK classes that implement the `Closeable` or `AutoCloseable` interface and - where it makes sense - change signatures of those methods from:

```diff
 @Override
- public void close() throws IOException {
+ public void close()       
}
```

Releasing resources (esp. after other exception) will rarely throw the exception, it is even more rare for it to be useful. Of course there are exceptions to this rule :)

At the same time having close throw exception complicates the control flow of try-with-resources with unnecessary catch:

```java
  try (S3Object s3Object = amazonS3Client.getObject(...)) {
            
        } catch (IOException exception) {
        }
```

That catch is not necessary if there is no throws clause on `close` method. It may be needed for other reasons but sometimes we will only need to catch something like `AmazonServiceException`.

## Is your Feature Request related to a problem?

"I'm always frustrated when" I need to declare catch clause that is only needed to "handle" exceptions from close when such exception are not logically possible or there is no sensible logic that can handle them.

## Proposed Solution
- Remove throws clause from `close` method(s). Sometimes this is enough.
- Decide what to do when such removal causes code to not compile (e.g. do we need to wrap something in try-catch block and rethrow runtime exception or leave close with throws?).
- Find closeable classes that do not override close at (some superclass have sensible implementation) and override with no throws declaration. 

## Describe alternatives you've considered
Catching the exception in separate catch block but this complicates exception handling.

## Additional Context
This is a source incompatible change - existing tyr-with-resources might need to be recompiled.

## Your Environment
* AWS Java SDK version used: 1.11.538
* JDK version used: openjdk14
* Operating System and version: Various

**Comment by debora-ito** [comment]
Hi @tkowalcz thank you for the detailed request. We understand the pain point but this modification would be backwards incompatible, as you mentioned, so unfortunately it would not be done in v1. 

In comparison, this change was made in the SDK v2, the implementation of [SdkAutoCloseable](https://github.com/aws/aws-sdk-java-v2/blob/master/utils/src/main/java/software/amazon/awssdk/utils/SdkAutoCloseable.java) explicitly states that it does not throw any checked exceptions in its close() methods.

Let us know if you have any more questions.

**Comment by tkowalcz** [comment]
Thanks for the explanation. Looks like we just need to move to 2.x.
