### ISSUE TITLE
Update HTTPS Certificate Amazon Simple Storage Service (S3)

### ISSUE THREAD

**Issue by eduardoaw** [aws/aws-sdk-java#2506]
We recently received the HTTPS certificate update message from Amazon Simple Storage Service (S3)

_Hello,

This is a reminder that Amazon Simple Storage Service (S3) and Amazon CloudFront are both migrating their services’ certificates from DigiCert to Amazon Trust Services starting March 23, 2021. If you do not send HTTPS traffic directly to your S3 bucket, or only use custom domains like www.example.com with your CloudFront distribution, then there is no impact and you can disregard this message. If you do send HTTPS traffic directly to your S3 bucket, or use CloudFront domains covered by *.cloudfront.net, please continue reading and review the FAQ below on which certificates are migrating.

The Amazon Trust Services Certificate Authority originates from AWS’ purchase of the Starfield Services Certificate Authority which has been valid since 2005. This means you shouldn’t have to take any action to use the certificates issued by Amazon Trust Services as it is already included in common trust stores across most web browsers, operating systems, and applications. However, if you build custom certificate trust stores or use certificate pinning, you may need to alter your configurations. As a best practice, we recommend verifying Amazon Trust Services is in your trust store with one of the following tests.

[1] Visit our blog at https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/ and use the test URLs there.

[2] Fetch the object from https://s3-ats-migration-test.s3.eu-west-3.amazonaws.com/test.jpg and verify a 200 response or that you see the green check mark in the test image.

[3] Create an S3 bucket in any of the following AWS regions and confirm you can fetch a test object over HTTPS: EU-WEST-3, EU-NORTH-1, ME-SOUTH-1, AP-NORTHEAST-3, AP-EAST-1, and US-GOV-EAST-1.

If Amazon Trust Services is not in the trust store, browsers will display an error message like https://untrusted-root.badssl.com/ and applications will show an application-specific error. If any of the tests fail, you must do one or more of the following actions: [A] Upgrade your operating system or browser that you are using, [B] Update your application to use CloudFront with a custom domain name and your own certificate, or [C] if you are using custom certificate trust stores or certificate pinning, include Amazon Trust Services’ Certificate Authorities, see https://www.amazontrust.com/repository/.

I use version 1.11.700 of the sdk, more precisely aws-java-sdk-s3.

Would you be able to tell me if I should update the sdk in order not to have the integration services interrupted?

*I don't use Amazon CloudFront

* AWS Java SDK version used: 1.11.700
* JDK version used: 1.8.0_212

**Comment by debora-ito** [comment]
Hi @eduardoaw thank you for reaching out.

The Java SDK uses the underlying certificate trust store configured in the application environment, so this is something you should check independently of the SDK version used.

You can test right now if your environment is ready by doing the tests described in the email using the SDK:

> [2] Fetch the object from https://s3-ats-migration-test.s3.eu-west-3.amazonaws.com/test.jpg and verify a 200 response or that you see the green check mark in the test image.

You can use a `BufferedInputStream` to get the image, for example.

> [3] Create an S3 bucket in any of the following AWS regions and confirm you can fetch a test object over HTTPS: EU-WEST-3, EU-NORTH-1, ME-SOUTH-1, AP-NORTHEAST-3, AP-EAST-1, and US-GOV-EAST-1.

These are simple tests that can be done by creating S3 clients in those regions, and calling `s3Client.getObject()` after creating the bucket and adding the object.

If any of the tests fails with messages like `Unable to find valid certification path to requested target`, it means that Amazon Trust Services is not in your trust store. To fix it, follow the instructions in the [blog post](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/) referenced.


You can also run the following command that lists the certificates installed in your trust store

```
keytool -list -v /path/to/keystore
```

and make sure the Amazon Trust Services certificates listed in the [blog post](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/) are present.

**Comment by debora-ito** [comment]
Let us know if you have any questions.

**Comment by debora-ito** [comment]
The migration date has passed, so I'm marking this to auto close soon. Please reach out if you have any further questions.
