### ISSUE TITLE
HandlerContextKey contains no CLIENT_ENDPOINT and ENDPOINT_OVERRIDDEN

### ISSUE THREAD

**Issue by dmitry-weirdo** [aws/aws-sdk-java#2509]
## Describe the bug
I am trying to get the STS token via Java SDK, according to this tutorial
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/prog-services-sts.html

## Expected Behavior
Everything works without throwing the exception.

## Current Behavior
This line
```
        GetSessionTokenResult session_token_result = sts_client.getSessionToken(session_token_request);
```
fails with 
```
Caused by: java.lang.NoSuchFieldError: CLIENT_ENDPOINT
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeGetSessionToken(AWSSecurityTokenServiceClient.java:1548) ~[aws-java-sdk-sts-1.11.954.jar:?]
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.getSessionToken(AWSSecurityTokenServiceClient.java:1530) ~[aws-java-sdk-sts-1.11.954.jar:?]
	at com.mycompany.myproject.adapter.cli.configuration.SqsConfiguration.credentialsProvider(SqsConfiguration.java:77) ~[classes/:?]
```

It obviously fails since `com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient#executeGetSessionToken` is using `HandlerContextKey.CLIENT_ENDPOINT` and `HandlerContextKey.ENDPOINT_OVERRIDDEN`, but they're not present in the `com.amazonaws.handlers.HandlerContextKey`:

```
                request.addHandlerContext(HandlerContextKey.CLIENT_ENDPOINT, endpoint);
                request.addHandlerContext(HandlerContextKey.ENDPOINT_OVERRIDDEN, isEndpointOverridden());
```

## Steps to Reproduce
Follow the aforementioned tutorial.

Code will look like this:
```
        final AwsClientBuilder.EndpointConfiguration endpointConfiguration = new AwsClientBuilder.EndpointConfiguration("sts-endpoint.amazonaws.com", "signing-region");

        AWSSecurityTokenService sts_client = AWSSecurityTokenServiceClientBuilder.standard()
            .withEndpointConfiguration(endpointConfiguration)
            .build();

        GetSessionTokenRequest session_token_request = new GetSessionTokenRequest();
        session_token_request.setDurationSeconds(7200);

        GetSessionTokenResult session_token_result = sts_client.getSessionToken(session_token_request);

        Credentials session_credentials = session_token_result.getCredentials();

        BasicSessionCredentials sessionCredentials = new BasicSessionCredentials(
            session_credentials.getAccessKeyId(),
            session_credentials.getSecretAccessKey(),
            session_credentials.getSessionToken()
        );

        AmazonSQSAsyncClientBuilder.standard()
            .withCredentials(new AWSStaticCredentialsProvider(sessionCredentials))
            .withEndpointConfiguration(endpointConfiguration)
            .build();
```

## Possible Solution
Return these constants back. The maven dependency of this artifact is now inconsistent!

```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
            <version>1.11.954</version>
        </dependency>
```

Just to check that `aws-java-sdk-core` dependency is not overridden somewhere in my Maven, this is an excerpt from `mvn dependency:tree`:

```
+- com.amazonaws:aws-java-sdk-sts:jar:1.11.954:compile
|  +- com.amazonaws:aws-java-sdk-core:jar:1.11.792:compile
|  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
|  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.11.2:compile
|  |  \- joda-time:joda-time:jar:2.8.1:compile
|  \- com.amazonaws:jmespath-java:jar:1.11.792:compile
```

## Context
I was trying to get the STS token to use an SQS Queue which belongs to other AWS account than EKS where my application is running on.

## Your Environment
* AWS Java SDK version used: aws-java-sdk-sts 1.11.954 + aws-java-sdk-core 1.11.792
* JDK version used: Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
* Operating System and version: Microsoft Windows [Version 10.0.17134.1902]

**Comment by debora-ito** [comment]
Hi @dmitry-weirdo thank you for reaching out.

`NoSuchFieldError` errors are usually caused by version mismatch between SDK modules. Ideally `core` and `sts` modules should be in the same version.

You can avoid this type of error if you use the `aws-sdk-java-bom` module: https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/

**Comment by DannyDevlin19671** [comment]
Hi, 
I am receiving the same error when sending a message to a dead letter queue. I've tried to reduce my build.gradle files as much as possible. I'm new to Gradle so apologies if I have missed something obvious:
buildscript {
	ext {
		SPRING_BOOT = '2.2.12.RELEASE'
		SPRING_CLOUD_AWS = '2.2.4.RELEASE'
		SPRING_CLOUD = 'Hoxton.SR8'
		AWS_SDK = "1.11.611"
		SPRING_BOOT_GRADLE_PLUGIN='2.4.0'
	}
	repositories {
		maven {
			url = uri('https://repo.maven.apache.org/maven2/')
		}
	}
	dependencies {
		classpath "org.springframework.boot:spring-boot-gradle-plugin:${SPRING_BOOT}"
		classpath "gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:2.0.0"
		classpath "org.owasp:dependency-check-gradle:6.1.0"
		classpath 'com.github.ben-manes:gradle-versions-plugin:0.27.0'
	}
}

plugins {
	id 'net.ltgt.apt' version '0.21'
	id 'net.ltgt.apt-idea' version '0.21'
	id "com.gorylenko.gradle-git-properties" version "2.0.0"
}

configurations {
	antJUnit
}
dependencies {
	antJUnit 'org.apache.ant:ant-junit:1.10.8'
}


apply plugin: 'io.spring.dependency-management'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'groovy'

group = "com.theverygroup.${rootProject.name}"
archivesBaseName = "${rootProject.name}"

sourceCompatibility = 1.8
//mainClassName = 'com.tvg.notifications.handler.ScheduledEventHandlerImplementation'
dependencyManagement {
	dependencies {
		dependency "org.springframework.boot:spring-boot-starter:${SPRING_BOOT}"
		dependency "org.springframework.boot:spring-boot-starter-web:${SPRING_BOOT}"
		//dependency "org.springframework.boot:spring-boot-starter-activemq:${SPRING_BOOT}"
		
		dependency 'xalan:xalan:2.7.1'
		dependency 'commons-lang:commons-lang:2.3'
		dependency 'net.logstash.logback:logstash-logback-encoder:6.1'
		dependency 'org.apache.commons:commons-lang3:3.11'
		dependency 'javax.xml.bind:jaxb-api:2.3.1'
		dependency 'xerces:xercesImpl:2.8.1'
		dependency 'org.mvel:mvel2:2.4.11.Final'
	}
	imports {
		mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${SPRING_CLOUD}"
		mavenBom "org.springframework.cloud:spring-cloud-aws-dependencies:${SPRING_CLOUD_AWS}"
	}
	testCompile {
		dependencies {
			//dependency "org.spockframework:spock-core:1.3-groovy-2.5"
		}
	}
}


allprojects {
	apply plugin: 'java'
	apply plugin: 'jacoco'
	repositories {
		maven {
			url = uri('https://repo.maven.apache.org/maven2/')
		}
	}
}

//apply from: 'gradle/code-quality.gradle'
apply from: 'gradle/dependency-check.gradle'
//apply from: 'gradle/utils.gradle'
apply from: 'gradle/dependency-updates.gradle'

apply plugin: 'application'
apply plugin: 'org.springframework.boot'

dependencies {
	compile "org.springframework.boot:spring-boot-starter-actuator"
	compile "org.springframework.boot:spring-boot-starter-web"
	//compile 'org.springframework.boot:spring-boot-starter-activemq:2.4.1'
	compile 'org.springframework.cloud:spring-cloud-starter-aws-secrets-manager-config'
	compile "org.springframework.cloud:spring-cloud-function-adapter-aws"
	compile 'com.amazonaws:amazon-sqs-java-messaging-lib:1.0.4'
	//compile group: 'com.amazonaws', name: 'aws-java-sdk-dynamodb', version: '1.11.792' TODO Commented out
	implementation group: 'com.amazonaws', name: 'aws-lambda-java-events', version: '3.6.0'//'2.2.2'
	//implementation 'com.amazonaws:aws-lambda-java-core:1.2.1' TODO Commented out
	//testImplementation 'junit:junit:4.13.1' TODO Commented out
	//implementation group: 'com.amazonaws', name: 'aws-java-sdk-sqs', version: '1.11.993' TODO Commented out

	//implementation 'org.slf4j:slf4j-api:1.7.30' TODO Commented out
	
	// https://mvnrepository.com/artifact/org.w3c/dom
	implementation group: 'org.w3c', name: 'dom', version: '2.3.0'//-jaxb-1.0.6
	
	// https://mvnrepository.com/artifact/org.json/json
	implementation group: 'org.json', name: 'json', version: '20090211'
	
	// https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-sqs
	//implementation group: 'com.amazonaws', name: 'aws-java-sdk-sqs', version: '1.11.988'
	
	//implementation group: 'org.springframework.ws', name: 'spring-ws-core', version: '3.0.10.RELEASE' TODO Commented out
	
	// https://mvnrepository.com/artifact/com.sun.xml.messaging.saaj/saaj-impl
	implementation group: 'com.sun.xml.messaging.saaj', name: 'saaj-impl', version: '1.3'
	
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test
	//testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test' TODO Commented out
	
	runtimeOnly 'org.jlib:jlib-awslambda-logback:1.0.0'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'//Added to run tests in IDE

	compile "com.fasterxml.jackson.core:jackson-databind"
	compile 'xalan:xalan'
	compile 'commons-lang:commons-lang'
	compile 'net.logstash.logback:logstash-logback-encoder'
	compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'

	//compile 'org.apache.commons:commons-lang3:3.11' TODO Commented out
	compile 'javax.xml.bind:jaxb-api:2.3.1'
	compile 'xerces:xercesImpl:2.8.1'
	compile 'org.mvel:mvel2:2.4.11.Final'
	
	//compile 'javax.xml.bind:jaxb-api:2.3.0' TODO Commented out
	compile 'javax.activation:activation:1.1'
	//compile 'org.glassfish.jaxb:jaxb-runtime:2.3.0' TODO Commented out
	//compile "org.springframework.boot:spring-boot-starter-actuator" TODO Commented out
	//compile "org.springframework.boot:spring-boot-starter-web" TODO Commented out

	 testImplementation(platform("org.junit:junit-bom:5.7.0"))
		testImplementation('org.junit.jupiter:junit-jupiter-api')
		testCompile('org.junit.jupiter:junit-jupiter-params')
		testRuntime('org.junit.jupiter:junit-jupiter-engine')
		testCompile group: 'org.mockito', name: 'mockito-inline', version: '3.2.0'
		test.useJUnitPlatform() // fix "test events not received" bug in IDEA
		testCompile 'com.willowtreeapps.assertk:assertk-jvm:0.23'
}

jar {
	manifest {
		attributes "Main-Class": "com.tvg.cam.orch.handler.CamOrchFunction"
	}

	from {
		configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
	}
	from('src/main/resources') {
		include '*'
	 }
}

task buildZip(type: Zip) {
	from compileJava
	from processResources
	into('lib') {
		from configurations.runtimeClasspath
	}
	doLast{
		FileTree tree = fileTree('build/distributions')
		tree.each {
			println it.name
		}
	}
}

test {

	useJUnitPlatform {
		includeEngines 'junit-jupiter', 'junit-vintage'
	}
	reports.html.enabled = false
	reports.junitXml.enabled = true
}


task testReport {
	ant.taskdef(name: 'junitreport', classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator', classpath: configurations.antJUnit.asPath)
	dependsOn subprojects*.test
	doFirst {
		mkdir "$buildDir/test-results"
		ant.junitreport(todir: "$buildDir/test-results") {
			subprojects.each {
				if (it.testResultsDir.exists()) {
					fileset(dir: it.testResultsDir)
				}
			}
		}
	}
}
This is the exception:
[2021-05-20 14:51:26.298] DEBUG o.s.w.s.DispatcherServlet - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: CLIENT_ENDPOINT
[2021-05-20 14:51:26.304] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: CLIENT_ENDPOINT] with root cause
java.lang.NoSuchFieldError: CLIENT_ENDPOINT

**Comment by DannyDevlin19671** [comment]
Hi, 
I am receiving the same error when sending a message to a dead letter queue. I've tried to reduce my build.gradle files as much as possible. I'm new to Gradle so apologies if I have missed something obvious:
```
buildscript {
	ext {
		SPRING_BOOT = '2.2.12.RELEASE'
		SPRING_CLOUD_AWS = '2.2.4.RELEASE'
		SPRING_CLOUD = 'Hoxton.SR8'
		AWS_SDK = "1.11.611"
		SPRING_BOOT_GRADLE_PLUGIN='2.4.0'
	}
	repositories {
		maven {
			url = uri('https://repo.maven.apache.org/maven2/')
		}
	}
	dependencies {
		classpath "org.springframework.boot:spring-boot-gradle-plugin:${SPRING_BOOT}"
		classpath "gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:2.0.0"
		classpath "org.owasp:dependency-check-gradle:6.1.0"
		classpath 'com.github.ben-manes:gradle-versions-plugin:0.27.0'
	}
}

plugins {
	id 'net.ltgt.apt' version '0.21'
	id 'net.ltgt.apt-idea' version '0.21'
	id "com.gorylenko.gradle-git-properties" version "2.0.0"
}

configurations {
	antJUnit
}
dependencies {
	antJUnit 'org.apache.ant:ant-junit:1.10.8'
}


apply plugin: 'io.spring.dependency-management'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'groovy'

group = "com.theverygroup.${rootProject.name}"
archivesBaseName = "${rootProject.name}"

sourceCompatibility = 1.8
//mainClassName = 'com.tvg.notifications.handler.ScheduledEventHandlerImplementation'
dependencyManagement {
	dependencies {
		dependency "org.springframework.boot:spring-boot-starter:${SPRING_BOOT}"
		dependency "org.springframework.boot:spring-boot-starter-web:${SPRING_BOOT}"
		//dependency "org.springframework.boot:spring-boot-starter-activemq:${SPRING_BOOT}"
		
		dependency 'xalan:xalan:2.7.1'
		dependency 'commons-lang:commons-lang:2.3'
		dependency 'net.logstash.logback:logstash-logback-encoder:6.1'
		dependency 'org.apache.commons:commons-lang3:3.11'
		dependency 'javax.xml.bind:jaxb-api:2.3.1'
		dependency 'xerces:xercesImpl:2.8.1'
		dependency 'org.mvel:mvel2:2.4.11.Final'
	}
	imports {
		mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${SPRING_CLOUD}"
		mavenBom "org.springframework.cloud:spring-cloud-aws-dependencies:${SPRING_CLOUD_AWS}"
	}
	testCompile {
		dependencies {
			//dependency "org.spockframework:spock-core:1.3-groovy-2.5"
		}
	}
}


allprojects {
	apply plugin: 'java'
	apply plugin: 'jacoco'
	repositories {
		maven {
			url = uri('https://repo.maven.apache.org/maven2/')
		}
	}
}

//apply from: 'gradle/code-quality.gradle'
apply from: 'gradle/dependency-check.gradle'
//apply from: 'gradle/utils.gradle'
apply from: 'gradle/dependency-updates.gradle'

apply plugin: 'application'
apply plugin: 'org.springframework.boot'

dependencies {
	compile "org.springframework.boot:spring-boot-starter-actuator"
	compile "org.springframework.boot:spring-boot-starter-web"
	//compile 'org.springframework.boot:spring-boot-starter-activemq:2.4.1'
	compile 'org.springframework.cloud:spring-cloud-starter-aws-secrets-manager-config'
	compile "org.springframework.cloud:spring-cloud-function-adapter-aws"
	compile 'com.amazonaws:amazon-sqs-java-messaging-lib:1.0.4'
	//compile group: 'com.amazonaws', name: 'aws-java-sdk-dynamodb', version: '1.11.792' TODO Commented out
	implementation group: 'com.amazonaws', name: 'aws-lambda-java-events', version: '3.6.0'//'2.2.2'
	//implementation 'com.amazonaws:aws-lambda-java-core:1.2.1' TODO Commented out
	//testImplementation 'junit:junit:4.13.1' TODO Commented out
	//implementation group: 'com.amazonaws', name: 'aws-java-sdk-sqs', version: '1.11.993' TODO Commented out

	//implementation 'org.slf4j:slf4j-api:1.7.30' TODO Commented out
	
	// https://mvnrepository.com/artifact/org.w3c/dom
	implementation group: 'org.w3c', name: 'dom', version: '2.3.0'//-jaxb-1.0.6
	
	// https://mvnrepository.com/artifact/org.json/json
	implementation group: 'org.json', name: 'json', version: '20090211'
	
	// https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-sqs
	//implementation group: 'com.amazonaws', name: 'aws-java-sdk-sqs', version: '1.11.988'
	
	//implementation group: 'org.springframework.ws', name: 'spring-ws-core', version: '3.0.10.RELEASE' TODO Commented out
	
	// https://mvnrepository.com/artifact/com.sun.xml.messaging.saaj/saaj-impl
	implementation group: 'com.sun.xml.messaging.saaj', name: 'saaj-impl', version: '1.3'
	
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test
	//testImplementation group: 'org.springframework.boot', name: 'spring-boot-starter-test' TODO Commented out
	
	runtimeOnly 'org.jlib:jlib-awslambda-logback:1.0.0'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'//Added to run tests in IDE

	compile "com.fasterxml.jackson.core:jackson-databind"
	compile 'xalan:xalan'
	compile 'commons-lang:commons-lang'
	compile 'net.logstash.logback:logstash-logback-encoder'
	compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.30'

	//compile 'org.apache.commons:commons-lang3:3.11' TODO Commented out
	compile 'javax.xml.bind:jaxb-api:2.3.1'
	compile 'xerces:xercesImpl:2.8.1'
	compile 'org.mvel:mvel2:2.4.11.Final'
	
	//compile 'javax.xml.bind:jaxb-api:2.3.0' TODO Commented out
	compile 'javax.activation:activation:1.1'
	//compile 'org.glassfish.jaxb:jaxb-runtime:2.3.0' TODO Commented out
	//compile "org.springframework.boot:spring-boot-starter-actuator" TODO Commented out
	//compile "org.springframework.boot:spring-boot-starter-web" TODO Commented out

	 testImplementation(platform("org.junit:junit-bom:5.7.0"))
		testImplementation('org.junit.jupiter:junit-jupiter-api')
		testCompile('org.junit.jupiter:junit-jupiter-params')
		testRuntime('org.junit.jupiter:junit-jupiter-engine')
		testCompile group: 'org.mockito', name: 'mockito-inline', version: '3.2.0'
		test.useJUnitPlatform() // fix "test events not received" bug in IDEA
		testCompile 'com.willowtreeapps.assertk:assertk-jvm:0.23'
}

jar {
	manifest {
		attributes "Main-Class": "com.tvg.cam.orch.handler.CamOrchFunction"
	}

	from {
		configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
	}
	from('src/main/resources') {
		include '*'
	 }
}

task buildZip(type: Zip) {
	from compileJava
	from processResources
	into('lib') {
		from configurations.runtimeClasspath
	}
	doLast{
		FileTree tree = fileTree('build/distributions')
		tree.each {
			println it.name
		}
	}
}

test {

	useJUnitPlatform {
		includeEngines 'junit-jupiter', 'junit-vintage'
	}
	reports.html.enabled = false
	reports.junitXml.enabled = true
}


task testReport {
	ant.taskdef(name: 'junitreport', classname: 'org.apache.tools.ant.taskdefs.optional.junit.XMLResultAggregator', classpath: configurations.antJUnit.asPath)
	dependsOn subprojects*.test
	doFirst {
		mkdir "$buildDir/test-results"
		ant.junitreport(todir: "$buildDir/test-results") {
			subprojects.each {
				if (it.testResultsDir.exists()) {
					fileset(dir: it.testResultsDir)
				}
			}
		}
	}
}
```
This is the exception:
[2021-05-20 14:51:26.298] DEBUG o.s.w.s.DispatcherServlet - Failed to complete request: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: CLIENT_ENDPOINT
[2021-05-20 14:51:26.304] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: CLIENT_ENDPOINT] with root cause
java.lang.NoSuchFieldError: CLIENT_ENDPOINT

**Comment by DannyDevlin19671** [comment]
Hi @debora-ito  that resolved the issue. I could see that two of the dependencies had different sdk versions. Once I changed those the message has gone to the dlq without issue. Thanks for your help.

**Comment by akuzni2** [comment]
Is there another reason why this error could occur? I've verified that every dependency of `aws-java-sdk-*` in my dependency tree has the same version - yet I still get this error.

**Comment by AnilGupta-Zee5** [comment]
i got same error. I fixed by adding following dependency:
<dependencyManagement>
 
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.12.221</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
</dependencyManagement>

**Comment by fvargasj** [comment]
> Is there another reason why this error could occur? I've verified that every dependency of `aws-java-sdk-*` in my dependency tree has the same version - yet I still get this error.

Any update here? Did you find any fix for this issue?

Thanks!

**Comment by tiansu-yu-idealo** [comment]
Please notice that SQS java lib is not included in POM:
(This is what i get after following the link https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/):
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.amazonaws:amazon-sqs-java-messaging-lib:jar is missing. @ line 165, column 21
```
And in general the SQS lib itself does not following the general SEMVER like the rest of the AWS SDK (Dynamodb, log, etc.). Don't know what is happening with this repo https://github.com/awslabs/amazon-sqs-java-messaging-lib but the release versioning looks quite different from other AWS Java sdks.
