### ISSUE TITLE
Content-disposition not getting set in the Object Metadata using Java SDK

### ISSUE THREAD

**Issue by debabratapatra** [aws/aws-sdk-java#2515]
I am trying to force download files in Firefox. I want to set content-disposition to "attachment" in the meta-data of the object. I have tried several things. But Metadata is not getting added. I have tried setting content-disposition like below.

        GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(bucketName,
					s3key);

         ResponseHeaderOverrides responseHeaderOverrides = new ResponseHeaderOverrides();
			responseHeaderOverrides.setContentDisposition("attachment; filename =\"" + filename + "\"");
			
			generatePresignedUrlRequest.setResponseHeaders(responseHeaderOverrides);
			
But in the console I still don't see the content-disposition getting added.

![image](https://user-images.githubusercontent.com/5602062/109167025-571fab80-77a3-11eb-919d-f78813a4a07e.png)

Please let me know if I missed something.

Thank You!

**Comment by debora-ito** [comment]
@debabratapatra `content-disposition` is a response header, it won't show in the object's metadata in the S3 console after you uploaded the object.

If you are using the header with get presigned urls, your sample code should work fine if you just add the missing request method:

```java
GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(bucketName, s3key)
                .withMethod(HttpMethod.GET);

ResponseHeaderOverrides responseHeaderOverrides = new ResponseHeaderOverrides();
responseHeaderOverrides.setContentDisposition("attachment; filename =\"" + filename + "\"");
generatePresignedUrlRequest.setResponseHeaders(responseHeaderOverrides);
```

**Comment by debabratapatra** [comment]
@debora-ito Thanks for your response. I want to add `content-disposition` to the metadata of the Object. Firefox doesn't automatically download `.mov` files unless `content-disposition=attachment` set in the metadata. Is there a way to add? Please let me know.

Thank you!

**Comment by debora-ito** [comment]
The sample code in my previous comment generates a presigned URL that seems to work on Firefox:

<img width="425" alt="Screen Shot 2021-03-03 at 2 06 40 PM_ALT" src="https://user-images.githubusercontent.com/476307/109879715-d3464300-7c2a-11eb-9ef8-1a5b00e16ba0.png">

Can you specify what is not working in your case?

**Comment by debabratapatra** [comment]
@debora-ito Thanks again for your response again. It is working now.

**Comment by MezliniSelim29** [comment]
@debora-ito  Thank you for the help. I want to ask if it's possible to pass content-disposition in parameters ? if it's the case i would like to know if i did it correctly.
public URL streamPresignedUrl( Disposition disposition)
{
ResponseHeaderOverrides responseHeaderOverrides = new ResponseHeaderOverrides();
responseHeaderOverrides.setContentDisposition( disposition.toString());
GeneratePresignedUrlRequest streamGeneratePresignedUrlRequest = new GeneratePresignedUrlRequest( getBucketName(), file)
			.withMethod( HttpMethod.GET).withExpiration( expInstant);
}
