### ISSUE TITLE
Unable to execute HTTP request: The target server failed to respond

### ISSUE THREAD

**Issue by hamzakhawaja27** [aws/aws-sdk-java#2517]
We are Trying to copy large volume of file from one bucket to another. But some files are copied twice. This breaks our architecture as we are invoking another lambda function based on the number of files being created in the destination bucket.

Description of issue: I have replicated the issue. I can observe this issue happening in a lambda function, my local machine and an ec2 instance. 

We have have successfully reproduced it. How we reproduced it :
	
1. We uploaded a file to source bucket.
2. Enabled s3 object versioning on destination bucket.
3. Wrote a small java program (deployed as a lambda) to copy file to this destination bucket by looping 1000 times and each copy happens in a separate thread. We kept the thread pool size as 50. So 50 copies were happening at the same time. Totally 1000 copy calls were made. So totally 1000 objects must be present in the destination bucket, but more than 1000 are present.
4. As we have enabled s3 object versioning, it will be easy for us detect if we have multiple versions of same object.
5. We then reduced the looping to 100 and thread pool size to 1, which means copies were happening one after the other in serial fashion, here also we noticed the issue. The destination s3 path should contain totally 100 objects but 101 objects are present.

We repeated step 3 few times and below are the no. of objects in each try :
try 1. 1005 objects
try 2. 1004 objects
try 3. 1006 objects
try 4. 1006 objects
try 5. 1004 objects

We repeated step 5 also few times and below are the no. of objects in each try :
try 1. 101 objects
try 2. 100 objects
try 3. 100 objects
try 4. 101 objects
try 5. 100 objects
try 6. 100 objects
try 7. 101 objects
try 8. 100 objects
try 9. 100 objects
try 10. 101 objects

The file size used for testing are 498MB and 629MB. We have enabled logs for printing request and response details from the aws sdk (Request/Response Summary Logging https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html). When looked at the logs, we saw sdk is retrying few requests without printing what happened
to first request. Please the find the attachment which contains the logs where sdk retried a request without printing what happened to first request.

aws s3 sdk version in use :
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
    <version>1.11.800</version>
</dependency>

Complete Error logs: 

when ever a file is copied twice we can see the following error:

"com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond"

**Comment by hamzakhawaja27** [comment]
Here is the code we are using:

=================

package com.amazonaws.lambda.demo;

import com.amazonaws.SdkClientException;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.CopyObjectRequest;
import com.amazonaws.lambda.demo.S3Client;
//import com.amazonaws.services.lambda.runtime.LambdaLogger;

//import org.apache.log4j.Level;
import org.apache.log4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

//import org.apache.log4j.PropertyConfigurator;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;

public class LambdaFunctionHandler implements RequestHandler<Map<String,String>, String>{
	
	
	
	static String MAX_RETRIES_FOR_S3_INTERNAL_ERRORS = "2";
	static String AWS_REGION = "ap-southeast-2";

	private static final Logger logger = Logger.getLogger(LambdaFunctionHandler.class);

    private static String SourceS3Bucket = System.getenv("source");
    private static String destinationS3Bucket = System.getenv("destination") ;
    private static AmazonS3 amazonS3 = S3Client.getInstance("ap-southeast-2","2");
    private static int nTimesCopy = 1000;
    
    @Override
    public String handleRequest(Map<String, String> input,Context context) {
		org.apache.log4j.BasicConfigurator.configure();
		//String log4jConfPath = "S3CopyReplication/src/main/resources/log4j.properties";
		//PropertyConfigurator.configure(log4jConfPath);
        String sourceS3Key = "Archive.zip";
        String destinationS3Key = "Archive.zip";

        ExecutorService executorService = Executors.newFixedThreadPool(50);
        List<Future> futures = new ArrayList<>();
        for (int i = 0; i < nTimesCopy; i++) {
            futures.add(executorService.submit(getCopyThread(sourceS3Key, destinationS3Key + i)));
        }
        executorService.shutdown();
        while (!executorService.isTerminated());
        for (Future future : futures) {
            try {
				future.get();
			} catch (InterruptedException | ExecutionException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
		return destinationS3Key;
    }

    private Thread getCopyThread(String sourceS3Key, String destinationS3Key) {

        return new Thread(new Runnable() {
            @Override
            public void run() {
                CopyObjectRequest copyObjectRequest = new CopyObjectRequest(SourceS3Bucket,sourceS3Key,destinationS3Bucket,destinationS3Key);
                try {
					copyObjectWithBasicApi(copyObjectRequest);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    private static void copyObjectWithBasicApi(CopyObjectRequest copyObjectRequest) throws Exception {
        logger.info("copyObjectWithBasicApi");

        try {
            logger.info("copy started with copy source bucket = " + copyObjectRequest.getSourceBucketName() + " and copy source key = " + copyObjectRequest.getSourceKey() + " to copy destination bucket = " + copyObjectRequest.getDestinationBucketName() + " and copy destination key = " + copyObjectRequest.getDestinationKey());
            logger.debug(amazonS3.copyObject(copyObjectRequest));
            logger.info("copy successful with copy source bucket = " + copyObjectRequest.getSourceBucketName() + " and copy source key = " + copyObjectRequest.getSourceKey() + " to copy destination bucket = " + copyObjectRequest.getDestinationBucketName() + " and copy destination key = " + copyObjectRequest.getDestinationKey());
        } catch (SdkClientException var3) {
        	throw new Exception("error while copying file = " + copyObjectRequest.getSourceKey() + " from bucket = " + copyObjectRequest.getSourceBucketName() + " to file = " + copyObjectRequest.getDestinationKey() + " to bucket = " + copyObjectRequest.getDestinationBucketName(), var3);
        }
    }
    


}


================
S3 client class
===================

package com.amazonaws.lambda.demo;

import com.amazonaws.ClientConfiguration;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

public class S3Client {

    private static AmazonS3 amazonS3;
    //public static int connectionTimeout = 100000; 
    //public static int socketTimeout = 1000000;
    public static long ConnectionMaxIdleMillis = 5000;
    //public static int clientExecutionTimeout = 1000000; // 1 s
    //public static int requestTimeout = 1000000; // 500 ms
    //public static int maxSdkRetries = 2;

    private static void initialize(String region, String maxSdkRetries) {
        ClientConfiguration clientConfiguration = new ClientConfiguration()
        		.withValidateAfterInactivityMillis(1000);
      //  		.withConnectionMaxIdleMillis(ConnectionMaxIdleMillis);
     //   		.withConnectionTimeout(connectionTimeout)
     //   		.withSocketTimeout(socketTimeout);
       // 		.withClientExecutionTimeout(clientExecutionTimeout)
       //         .withRequestTimeout(requestTimeout)
       //         .withSocketTimeout(socketTimeout)
       // 		.withMaxErrorRetry(Integer.parseInt(maxSdkRetries));
        
      //  if (maxSdkRetries != null) {
      //      clientConfiguration = new ClientConfiguration()
      //              .withMaxErrorRetry(Integer.parseInt(maxSdkRetries));
      //  }
        amazonS3 = AmazonS3ClientBuilder.standard()
                .withRegion(region)
                .withClientConfiguration(clientConfiguration)
                .build();
    }

    public static synchronized AmazonS3 getInstance(String region, String maxSdkRetries) {
        if (amazonS3 == null) {
            initialize(region, maxSdkRetries);
        }
        return amazonS3;
    }
}

===============

**Comment by debora-ito** [comment]
Hi @hamzakhawaja27 I think the issue is how you are using the `ExecutorService.submit()` method, it should receive a `Runnable` as an argument ([see javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#submit-java.lang.Runnable-)), and in your sample code it is passing a new `Thread`. Since you are creating a new Thread at that point, I don't how it will behave in addition to submitting the thread to the executors pool.

Can you change `getCopyThread()` to return a `Runnable` and run your tests again?

**Comment by hamzakhawaja27** [comment]
CX will comment on this issue soon.

**Comment by hamzakhawaja27** [comment]
Can we please reopen this issue?

**Comment by debora-ito** [comment]
Reopened. Waiting for new updates.
