### ISSUE TITLE
Availability of ap-northeast-3

### ISSUE THREAD

**Issue by dladia** [aws/aws-sdk-java#2519]
When will the ap-northeast-3 region be available in the SDK?

https://github.com/aws/aws-sdk-java/blob/141c3628102d37718fdb3346b56b368b5330f8ba/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java#L44

**Comment by debora-ito** [comment]
Very soon! We are working on it.

**Comment by debora-ito** [comment]
Added in SDK version `1.11.968`.

https://github.com/aws/aws-sdk-java/blob/9ec1c10588d536a500221cc8d1b71e671dc913e3/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java#L45

@dladia thank you for reaching out.
