### ISSUE TITLE
DescribeNetworkInterfaceAttributeRequest and ResetNetworkInterfaceAttributeRequest incorrect

### ISSUE THREAD

**Issue by sjones4** [aws/aws-sdk-java#252]
The DescribeNetworkInterfaceAttributeRequest and ResetNetworkInterfaceAttributeRequest requests should have an "attribute" property to specify what is being described/reset:

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-DescribeNetworkInterfaceAttribute.html

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-ResetNetworkInterfaceAttribute.html

Currently these requests have string properties relating to each supported attribute (which should presumably be removed?). If there is some way to use the current messages to describe / reset network interface attributes it would be good to add that to the documentation. 

It is possible to work around this by getting attribute values via describing the network interface and using modify attribute instead of reset.

I would be happy to submit a pull request for this if that is helpful.

**Comment by manikandanrs** [comment]
Both these APIs now match the API docs. Feel free to re open if you still see the issue.
