### ISSUE TITLE
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by rmskmr33** [aws/aws-sdk-java#2525]
I wants to connect aws s3 bucket in the existing java project. We already have truststore.jks configured in the existing. 

While connecting aws-s3 using aws-java-sdk getting following error:

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

kindly help which cert we need to import to fix this issue.

Java Version : 1.8

Thanks,
Ramesh

**Comment by debora-ito** [comment]
Hi @rmskmr33 if you search for that error message in this repo you'll find some issues about how to solve it.

You need to have the Amazon Trust Services certificates in your trust store. See more info here: https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/

You can check what certificates are installed in your trust store with the following command:
```
keytool -list -v /path/to/keystore
```

And just ensure the certificates from that link are present.

**Comment by rmskmr33** [comment]
@debora-ito thank you so much for the reply. Following are the steps i tried but still getting the same error.

**Step 1:** Downloaded the rds-ca-2019-root.pem file from following site:
https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem

**Step 2:** Converted the root certificate to der format by using following command
>openssl x509 -in rds-ca-2019-root.pem -inform pem -out rds-ca-2019-root.der -outform der

**Step 3:** Imported the root certificate file[rds-ca-2019-root.der] to my truststore.jks which already available in my project
>keytool.exe -keystore my_truststore.jks -storepass changeit file rds-ca-2019-root.der

**Step 4:** Trying to list the cert using following command and able to see the cert.
>keytool.exe -list -v -keystore   my_truststore.jks

I have tried with latest .jks but still getting the same error. Kindly confirm above steps are correct or  i missed anything.

Thanks,
Ramesh

**Comment by debora-ito** [comment]
Check if your application is actually using the trust store located in my_truststore.jks, it may be configured to use a trust store in another path.

**Comment by rmskmr33** [comment]
@debora-ito, thanks for the reply. I need to enable the public SSL in the aws account as well right?

**Comment by debora-ito** [comment]
I'm not fully clear on the question, what do you mean by "enable the public SSL in the aws account"?
