### ISSUE TITLE
Support jakarta.* namespaces

### ISSUE THREAD

**Issue by MasatoshiTada** [aws/aws-sdk-java#2527]
## Describe the Feature

When I call `AmazonS3#putObject()` , I can see a WARN log below:

`JAXB is unavailable. Will fallback to SDK implementation which may be less performant`

So I added dependencies of `3.0.0` (this version is the latest) of `jakarta.xml.bind:jakarta.xml.bind-api` and `com.sun.xml.bind:jaxb-api` . But unfortunately, I still see the WARN log above.

I changed versions from `3.0.0` to `2.3.3` , and the WARN log was disappered.

It seems that aws-sdk-java doesn't support `jakarta.*` namespaces.

## Is your Feature Request related to a problem?

At this time, this is not a very big problem. But it becomes bigger with the lapse of time.

## Describe alternatives you've considered

As I mentioned above, use `2.3.3` . And if you use JDK 8, this problem doesn't occur.

## Your Environment

* AWS Java SDK version used: 1.11.327
* JDK version used: 11
* Operating System and version: macOS Big Sur 11.2.3 (M1)

**Comment by MasatoshiTada** [comment]
@debora-ito Thank you for your comment!

> Please note that as the team's focus is in SDK v2 work, we don't have a timeline for when this will be prioritized.

Do you have any plan to support jakarta.* namespaces in SDK v2?👀

**Comment by antechrestos** [comment]
Still no news on this issue?

**Comment by debora-ito** [comment]
@MasatoshiTada 

I believe we don't use any package in SDK v2 that requires migrating to jakarta namespaces. If you are seeing otherwise, please share your dependency tree.

**Comment by antechrestos** [comment]
Indeed, migration to sdk v2 works like a charm

**Comment by debora-ito** [comment]
We don't have plans to support this in v1, so I'll go ahead and close this issue.

This issue is not present in v2, please migrate to v2 for the improved performance and continued support from aws.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
