### ISSUE TITLE
Java OSGi V2?

### ISSUE THREAD

**Issue by alexseguin** [aws/aws-sdk-java#2528]
Is there any plan for the release of the V2 API to the OSGi format?

**Comment by debora-ito** [comment]
It's a feature request, we are tracking it here: https://github.com/aws/aws-sdk-java-v2/issues/59

**Comment by kastork** [comment]
@debora-ito   It is a 5 year old feature request -- I think that makes this a legitimate question.  Are there any plans to do this or not?

**Comment by kastork** [comment]
@alexseguin Service Mix has done it.  Sadly their bundle does not include the enhanced dynamodb client.
https://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.aws-java-sdk2

**Comment by joannehoadobe** [comment]
> @debora-ito It is a 5 year old feature request -- I think that makes this a legitimate question. Are there any plans to do this or not?

Is there an answer to this question? I think it's still a legitimate question.
We're also interested in an OSGi-compatible version of the AWS SDK V2 jar.
Or is the answer to use the Service Mix wrapper even though it doesn't include the enhanced dynamodb client? Thanks
