### ISSUE TITLE
Caused by: java.net.UnknownHostException: kinesisvideo.eu-west-2.amazonaws.com

### ISSUE THREAD

**Issue by darwinanirudh** [aws/aws-sdk-java#2529]
## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Please fill the issue template, I'm not able to help if all the information I have is one line of exception.

**Comment by darwinanirudh** [comment]
Hey I am sorry . I accidently created the issue while I still trouble shooting.  We can close this for now and open a new issue if needed. Apologies for the inconvenience.
