### ISSUE TITLE
S3 Client generating presigned URL mistakenly containing "%2F"

### ISSUE THREAD

**Issue by madelynnelson** [aws/aws-sdk-java#2533]
For some valid S3 keys, the AWS Java SDK consistently generates invalid presigned URLs.

## Describe the bug
For some valid S3 keys, the AWS Java SDK consistently generates invalid presigned URLs. These invalid presigned URLs are in the format `https://<bucket_name>.s3.amazonaws.com/%2F<path>...`. Note the presence of the "**%2F**", which is an encoded forward slash. When you navigate to that URL, you get a `NoSuchKey` error.

This presumably is related to the forward-slash replacement logic [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L204). The replacement of consecutive "/" with "%2F" is reasonable, but in this case, the S3 key and path do not contain consecutive forward slashes, so this addition/replacement should not have happened.

This is definitely not an issue with the S3 bucket permissions or key itself, because the AWS S3 CLI successfully generates presigned URLs for the identical S3 key using the same credentials and timing.

## Expected Behavior
For all valid S3 keys, the AWS Java SDK should consistently generate valid presigned URLs. In this case, the generated presigned URL should not contain "%2F".

## Current Behavior
For some valid S3 keys, the AWS Java SDK consistently generates invalid presigned URLs that incorrectly contain "%2F".

## Possible Solution
This presumably is related to the forward-slash replacement logic [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L204). The replacement of consecutive "/" with "%2F" is reasonable, but in this case, the S3 key and path do not contain consecutive forward slashes, so this addition/replacement should not have happened.

## Your Environment

* AWS Java SDK version used:  the latest version `1.11.982`
* JDK version used: JDK 8
* Operating System and version: Mac OS Catalina `10.15.7`
* Apache `httpclient-4.5.13`

**Comment by debora-ito** [comment]
Hi @madelynnelson can you provide a repro code? 

And this information too:

- AWS Java SDK version used:
- JDK version used:
- Operating System and version:

Also, which version of Apache `httpclient` are you using? We recommend using `httpclient-4.5.9` or newer, versions before `4.5.9` made some changes in their url encoding.

**Comment by madelynnelson** [comment]
Hi @debora-ito!

Thanks for the quick response. I've updated the issue to include that information.

**Comment by debora-ito** [comment]
Can you share a minimal repro code?

**Comment by madelynnelson** [comment]
Hi all,

I'm going to close this issue because it looks like this may be expected behavior after all. Presigned URLs are correctly generated as long as the provided S3 resource path does NOT contain a leading forward slash. I'm going to note this expectation and adjust accordingly on my end.

Thank you!
