### ISSUE TITLE
Vulnerability found in dependency jackson-dataformat-cbor

### ISSUE THREAD

**Issue by deporcali** [aws/aws-sdk-java#2534]
This library is using a version of jackson-dataformat-cbor that is prone to DoS attack.

https://github.com/aws/aws-sdk-java/blob/bafd25631d9f7db249db42a21207a9934faa833d/aws-java-sdk-core/pom.xml#L39

https://github.com/aws/aws-sdk-java/blob/bafd25631d9f7db249db42a21207a9934faa833d/pom.xml#L308

This needs to be upgraded to version 2.12.1 or higher

See https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONDATAFORMAT-1047329 for more information

**Comment by debora-ito** [comment]
Hi @deporcali thank you for reaching out. 

We cannot upgrade `jackson-dataformat-cbor` to a version higher than 2.6.x due to backwards compatibility with Java 7, which the SDK still supports. It's not a simple version upgrade, but we'll work on it. In the meantime, you can upgrade the `jackson-dataformat-cbor` version in your project.

**Comment by deporcali** [comment]
@debora-ito I see, sounds good I can do that at my project level. Thanks for checking up on this.

**Comment by bollmann** [comment]
@debora-ito:

> In the meantime, you can upgrade the `jackson-dataformat-cbor` version in your project.

Are you saying that we can safely override the `jackson-dataformat-cbor` dependency from version 2.6.7 to version 2.12.1 (or 2.11.4) in our project that uses your aws-sdk-java library if we don't have to run on Java 7? I just want to confirm that in the case of not having to support Java 7, upgrading the jackson-dataformat-cbor dependency also inside your aws-sdk-java library doesn't break anything within it.

**Comment by debora-ito** [comment]
@bollmann the SDK is compatible with newer versions of `jackson-dataformat-cbor`. If your application uses any feature of `jackson-dataformat-cbor` outside of the SDK, we recommend you test it with newer versions to make sure nothing breaks, as jackson libraries made some backward-incompatible changes in newer versions.

In https://github.com/aws/aws-sdk-java/issues/2096 we are tracking the work to bump the SDK version number to 1.12.x and upgrade the version of jackson, we'll make sure that `jackson-dataformat-cbor` is included in that version bump. Please upvote that tracking issue, we'd like to know if you are impacted by this and help us with prioritization.
