### ISSUE TITLE
Step function does not return the last lambda function return json object, only getting executionArn and startDate

### ISSUE THREAD

**Issue by sainath-thakare** [aws/aws-sdk-java#2535]
## Describe the issue
 I am using serverless framework with aws, creating a step function using serverless.yml
 in serverless.yml :
stepFunctions:
  stateMachines:
    hellostepfunc1:
      events:
        - http:
            path: startStepFunctionymltest
            method: post
      definition:
        Comment: "A sample application of step function"
        StartAt: createUserStepFunction
        States:
          createUser:
            Type: Task
            Resource: arn:aws:lambda:ap-south-1:00000:function:user-api-module-dev-createUser
            Next: addNewUserTwo
          addChild:
            Type: Task
            Resource: arn:aws:lambda:ap-south-1:00000:function:user-api-module-dev-addChild
            End: true

plugins:
  - serverless-step-functions
 
## Current Behavior
on sls deploy getting the step function endpoint, when i hit the same from postman getting only this
{
    "executionArn": "arn:aws:states:ap-south-1:00000:execution:Hellostepfunc1StepFunctionsStateMachine-85WV8FDEuBbv:a7c2d0a2-18b5-4d0f-20c9-39722f5fe12e",
    "startDate": 1.616746994142E9
}

but i need the result return by my last lambda "addChild" .. how to get it, is there any way... 
## Your Environment

* AWS Java SDK version used: 1.8
* JDK version used: 1.8
* Operating System and version: windows 10

**Comment by debora-ito** [comment]
Hi @sainath-thakare it looks like you are using the Serverless Framework plugin for AWS Step Functions, please open an issue in their repository - https://github.com/serverless-operations/serverless-step-functions
