### ISSUE TITLE
[SQS] - only return 1 or 3 messages 

### ISSUE THREAD

**Issue by juanjavito** [aws/aws-sdk-java#2536]
Hi, 

i've more than 10 messages in a queue and sdk only return 1 or 3. 

My code :

```
ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest("URL");
receiveMessageRequest.setMaxNumberOfMessages(10); 
receiveMessageRequest.setWaitTimeSeconds(20); 

sqs.receiveMessage(receiveMessageRequest).getMessages(); 
```

if i use 
`receiveMessageRequest.setVisibilityTimeout(0);`
 return 10 messages but this doesn't serve me, i need the messages later

**Comment by debora-ito** [comment]
@juanjavito Can you provide a reproducible code showing how you created the queue and how you're sending the messages?

Please also provide:
* AWS Java SDK version used:
* JDK version used:
* Operating System and version:
