### ISSUE TITLE
Feature Request: Spring integration for AWS

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java#2541]
There are numerous overlaps between the features that Spring exposes and AWS provides. For example, we could integrate any number of the various AWS databases with spring-data.

[spring-cloud-aws](https://github.com/awspring/spring-cloud-aws) currently provides some functionality but it only supports the AWS SDK for Java 1.11.x, and there are a lot more integrations that could be made.

**Please thumbs-up this feature if you're interested in better Spring integration for AWS. Comments on which specific integrations you are interested it would also be useful.**

Some initial research found the following opportunities:

Spring Feature | Use Case | AWS Services
-- | -- | --
Spring Cloud Gateway | Microservices | API Gateway, Lambda
Spring Cloud Functions | Microservices | Lambda
Spring Data | Data Access | RDS, DynamoDB, MongoDB, ElastiCache, ...
Spring Integration | Service Integration | SQS, SNS, EventBridge, Kinesis, ...
Spring Cloud Stream and Spring Cloud Bus | Microservices | EventBridge, Kinesis
Spring Cloud Config and Spring Cloud Vault | Service Configuration | SSM
Spring Cloud Kubernetes | Microservices | EKS
Spring Cloud Security | AuthN / AuthZ | SSO, Cognito
Spring Cloud Sleuth | Traceability | X-Ray, CloudWatch
Spring Cloud Task | Short-Lived Microservices | CodeBuild, EKS, Beanstalk, ...
Spring Statemachine | Microservices | StepFunctions

Related issue in 2.x: https://github.com/aws/aws-sdk-java-v2/issues/2369

**Comment by debora-ito** [comment]
Closing this, we don't have plans to release new big integration features in Java SDK 1.x.

Please track the corresponding issue in Java SDK 2.x: https://github.com/aws/aws-sdk-java-v2/issues/2369
