### ISSUE TITLE
Generation of S3 presign URL does not work with lambda function

### ISSUE THREAD

**Issue by avri-sela** [aws/aws-sdk-java#2551]
We use the following code to generate an S3 presign URL:
		BasicAWSCredentials credentials = new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY);
		AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withRegion(CLIENT_REGION)
				.withCredentials(new AWSStaticCredentialsProvider(credentials)).build();
		GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(BUCKET_NAME,
				objectKey).withMethod(HttpMethod.GET).withExpiration(expiration);
		URL url = s3Client.generatePresignedUrl(generatePresignedUrlRequest);

When running this code on a laptop (running in UTC+3 time zone), the generated URL works without problem.
However, when the same code runs as a part of Lambda Function (us-east-1), the generated URL results in the following error:
<Error>
	<Code>SignatureDoesNotMatch</Code>
	<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
	<AWSAccessKeyId>XXX</AWSAccessKeyId>
	<StringToSign>AWS4-HMAC-SHA256 20210411T130238Z 20210411/us-east-1/s3/aws4_request 08d78f8dccdb4f29424a1d06ef3a246d856eb5dd36e3014620afc5f135398614</StringToSign>
	<SignatureProvided>517fddb56e5037207f30ad576b4d2b7b67d2a76adee1392b105973c2ab61f519END RequestId: 9960a89f-3963-4f61-bf2e-02120f8688de</SignatureProvided>
	<StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 31 30 34 31 31 54 31 33 30 32 33 38 5a 0a 32 30 32 31 30 34 31 31 2f 75 73 2d 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 30 38 64 37 38 66 38 64 63 63 64 62 34 66 32 39 34 32 34 61 31 64 30 36 65 66 33 61 32 34 36 64 38 35 36 65 62 35 64 64 33 36 65 33 30 31 34 36 32 30 61 66 63 35 66 31 33 35 33 39 38 36 31 34</StringToSignBytes>
	<CanonicalRequest>GET /WaveFixpack_2_0_0_1.tar X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXX%2F20210411%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210411T130238Z&X-Amz-Expires=604799&X-Amz-SignedHeaders=host host:wave-log-on-downloads.s3.amazonaws.com host UNSIGNED-PAYLOAD</CanonicalRequest>
	<CanonicalRequestBytes>47 45 54 0a 2f 57 61 76 65 46 69 78 70 61 63 6b 5f 32 5f 30 5f 30 5f 31 2e 74 61 72 0a 58 2d 41 6d 7a 2d 41 6c 67 6f 72 69 74 68 6d 3d 41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 26 58 2d 41 6d 7a 2d 43 72 65 64 65 6e 74 69 61 6c 3d 41 4b 49 41 55 4e 4b 4e 51 59 36 58 44 53 50 53 36 52 50 47 25 32 46 32 30 32 31 30 34 31 31 25 32 46 75 73 2d 65 61 73 74 2d 31 25 32 46 73 33 25 32 46 61 77 73 34 5f 72 65 71 75 65 73 74 26 58 2d 41 6d 7a 2d 44 61 74 65 3d 32 30 32 31 30 34 31 31 54 31 33 30 32 33 38 5a 26 58 2d 41 6d 7a 2d 45 78 70 69 72 65 73 3d 36 30 34 37 39 39 26 58 2d 41 6d 7a 2d 53 69 67 6e 65 64 48 65 61 64 65 72 73 3d 68 6f 73 74 0a 68 6f 73 74 3a 77 61 76 65 2d 6c 6f 67 2d 6f 6e 2d 64 6f 77 6e 6c 6f 61 64 73 2e 73 33 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 0a 68 6f 73 74 0a 55 4e 53 49 47 4e 45 44 2d 50 41 59 4c 4f 41 44</CanonicalRequestBytes>
	<RequestId>2KX00NNZPP93QZF4</RequestId>
	<HostId>mJ+g5dOn76iYwkAroWac2Dur2sOC9/sfihCxAHLK8akGthuEmoZXRv68DYnVuo0Zs57dxUfdH7M=</HostId>
</Error>
## Your Environment
* AWS Java SDK version used: 1.11.256
* JDK version used:
 java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
* Operating System and version:  Microsoft Windows 10 Pro 10.0.19041 N/A Build 19041

**Comment by debora-ito** [comment]
@avri-sela check if the credentials used in lambda to generate the presigned URL have access to the object. 
If credentials are ok, compare the fields on the presigned URL that works with the one generated in lambda and see what's different. 

By the way, I edited your description to remove your access key, but now that it was exposed I recommend you rotate it as soon as possible.
