### ISSUE TITLE
No programmatic way to configure legacy STS endpoint behavior

### ISSUE THREAD

**Issue by ztravis** [aws/aws-sdk-java#2553]
## Describe the Feature
The STS client classes don't provide a programmatic way to configure/toggle the legacy endpoint behavior.
AFAICT the only ways to configure this behavior (in class `com.amazonaws.services.securitytoken.RegionalEndpointsOptionResolver`) are via environment variables and properties files.

## Is your Feature Request related to a problem?
Yes, it would be nice to be able to programmatically configure an `AWSSecurityTokenService` instance to use/not use the legacy endpoint behavior as needed.

## Proposed Solution
I'm not very familiar with the client configuration options, so I can't really say the best way to proceed  - this seems too specific to get its own method in `ClientConfiguration`, but maybe there is some other mechanism available? I would be happy with simply being able to provide my own option resolver implementation or override `AWSSecurityTokenServiceClient.legacyRegionModeEnabled()`. If someone has a suggestion for how to proceed, I'm happy to open a PR.

## Describe alternatives you've considered
Using an environment variable or profile means that this service-specific configuration now has to be part of our deployed infrastructure rather than handled all in java.
I believe we can also set the endpoint ourselves explicitly, but that doesn't seem ideal - I don't want to have to know what the STS endpoint looks like/how to build it, I just want the client to do it based on the configured region.

## Additional Context
For some motivation around why we want to configure this, we'd like to use a VPC service endpoint for STS, which I believe requires using the region-specific endpoints rather than the global endpoint.

**Comment by debora-ito** [comment]
Hi @ztravis thank you for reaching out.

Just to be clear, by "programmatically" you mean a way to set the `AWS_STS_REGIONAL_ENDPOINTS` configuration in the SDK client level?
Overriding the endpoint configuration would not work for your use case?

```
AWSSecurityTokenService stsClient = AWSSecurityTokenServiceClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("https://sts.eu-west-1.amazonaws.com","eu-west-1"))
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .build();
```

I believe to be able to use VPC endpoints you need to override the endpoint.

**Comment by ztravis** [comment]
Thanks for the response!

By "programmatically" I mean some way to, entirely within java code, configure the STS client to use the region I'm providing (letting the SDK determine the correct endpoint), not replace it under the hood with the global region.

As mentioned under alternatives I've considered, I can set the endpoint myself explicitly (and that's what I'm doing for the time being). However, I think that's a less than ideal approach, since it requires me to know how to build the correct STS endpoint given a region if we want our application to work anywhere. It seems like it's the case that the endpoint is always "sts.{region_name}.amazonaws.com", but that's an extra bit of external knowledge I'd rather not have to embed in our code given that it's already embedded in the AWS SDK, which presumably will remain up to date even if something unexpected happens down the line that violates this inferred endpoint pattern rule.

Not a critical fix by any means, but would be nice IMO.

Thanks again!

**Comment by ztravis** [comment]
FWIW this is unresolved.
