### ISSUE TITLE
com.amazonaws.services.dynamodbv2.xspec.condition equals() returns false for equivalent objects

### ISSUE THREAD

**Issue by M3Tr01T** [aws/aws-sdk-java#2554]
com.amazonaws.services.dynamodbv2.xspec.condition equals() does not work as would be expected.

## Describe the bug
ExpressionSpecBuilder.S("MyKey").eq("MyValue").equals(ExpressionSpecBuilder.S("MyKey").eq("MyValue")) returns false.

## Expected Behavior
ExpressionSpecBuilder.S("MyKey").eq("MyValue").equals(ExpressionSpecBuilder.S("MyKey").eq("MyValue")) should return true. In my opinion, it does not makes sense for this class to be compared on instance level. Object.equals() should be overwritten.
Analogously, ExpressionSpecBuilder.S("MyKey").eq("MyValue").hashCode() == ExpressionSpecBuilder.S("MyKey").eq("MyValue").hashCode() should return true as well.

## Current Behavior
ExpressionSpecBuilder.S("MyKey").eq("MyValue").equals(ExpressionSpecBuilder.S("MyKey").eq("MyValue")) returns false.

Same issue happens with hashCode(): ExpressionSpecBuilder.S("MyKey").eq("MyValue").hashCode() == ExpressionSpecBuilder.S("MyKey").eq("MyValue").hashCode() returns false.

## Steps to Reproduce
assertTrue(ExpressionSpecBuilder.S("MyKey").eq("MyValue").equals(ExpressionSpecBuilder.S("MyKey").eq("MyValue")))

assertEquals(ExpressionSpecBuilder.S("MyKey").eq("MyValue").hashCode(), ExpressionSpecBuilder.S("MyKey").eq("MyValue").hashCode());

## Possible Solution
Overwrite Object.equals() to compare logically Condition classes.

## Context
We use custom QueryRequest objects on our code.This custom objects contain several attributes which are of type Condition. When mocking those objects for tests using mockito, the reponse is always null. It is because internally it uses equals() method.

## Environment
* AWS Java SDK version used: 1.11.961
* JDK version used: correto-11 (11.0.7)

**Comment by M3Tr01T** [comment]
Same issue happens with hashCode().

**Comment by debora-ito** [comment]
Hi @M3Tr01T, I see you got a response in the support case you've opened, I'm posting here for completeness. 

ExpressionSpecBuilder currently uses reference equality, so this would be a feature request to change it to value-type equality. Since the team efforts are concentrated in the Java SDK 2.x, this change would have low priority.

I'll go ahead and close this. If anyone else would like to see this supported, please upvote the description or add a comment.
