### ISSUE TITLE
No way to attach listener right on TransferManger::uploadResume

### ISSUE THREAD

**Issue by Saoqq** [aws/aws-sdk-java#2555]
## Describe the issue

There is no way to attach listener right during upload resume initiation.
So it means possible loss of events until listener will be attached via `upload::addProgressListener`

## Current Behavior
```java
...
Upload result = transferMgr.resumeUpload(uploadToContinue);
result.addProgressListener(progressListener); // possible loss of events until listener will be attached
```
## Excpected Behavior
```java
...
Upload result = transferMgr.resumeUpload(uploadToContinue, listenerImpl);
```

## Your Environment
* AWS Java SDK version used: aws-java-sdk-s3:1.11.970
* JDK version used: - 
* Operating System and version:  -

**Comment by debora-ito** [comment]
@Saoqq I see what you mean, you want the same config option of TransferManager Upload like `transferMgr.upload(putObjectRequest, progressListener)`.

I guess it is possible to loose some events in theory, but I don't expect them to be significant. You can always obtain the upload's current TransferProgress by calling `result.getProgress()`. Are you experiencing any critical event losses?

**Comment by Saoqq** [comment]
@debora-ito 
We are using `PROGRESS_EVENTS` to resume our threads and other activities, so this events are quite critical for us.
We prevent this possible loss using reflection. 

Overload for `transferManager::resumeUpload`  with second param as `progressListener` looks quite natural to me

**Comment by debora-ito** [comment]
Marking this as a feature request. Note that the team's focus is in Java SDK v2 work, so there's no timeline for when this will be prioritized.
