### ISSUE TITLE
DeleteItemOutcome#getItem() is documented as not-null, but is null if the primary key did not exist

### ISSUE THREAD

**Issue by eager** [aws/aws-sdk-java#2559]
## Describe the bug

`DeleteItemOutcome#getItem()` is [documented as non-null](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/DeleteItemOutcome.html#getItem--), but it is null if the primary key in the `DeleteItemSpec` did not exist.

## Expected Behavior

`getItem()` should return a non-null `Item`, and that item should have an empty attribute map.

## Steps to Reproduce
```java
private DynamoDB dynamoDB = // initialization is not relevant;

// JUnit 5 test case
@Test
void testDelete() {

 // create table
 Table table = dynamoDB.createTable("test",
     List.of(new KeySchemaElement("h", KeyType.HASH), new KeySchemaElement("r", KeyType.RANGE)),
     List.of(new AttributeDefinition("h", ScalarAttributeType.S),
         new AttributeDefinition("r", ScalarAttributeType.S)),
     new ProvisionedThroughput(10L, 10L));

 // primary key used throughout the test
 final PrimaryKey primaryKey = new PrimaryKey("h", "1", "r", "2");

 // create the item
 final PutItemSpec putItemSpec = new PutItemSpec().withItem(new Item().withPrimaryKey(primaryKey));
 table.putItem(putItemSpec);

 // confirm the put succeeded
 Item item = table.getItem(primaryKey);
 assertEquals("1", item.getString("h"));

 // delete item
 DeleteItemSpec deleteItemSpec = new DeleteItemSpec().withPrimaryKey(primaryKey)
     .withReturnValues(ReturnValue.ALL_OLD);

 // first delete
 DeleteItemOutcome deleteItemOutcome = table.deleteItem(deleteItemSpec);

 // confirm deleteItem returns the deleted item details
 assertNotNull(deleteItemOutcome.getItem());
 assertEquals("1", deleteItemOutcome.getItem().getString("h"));

 // second delete
 deleteItemOutcome = table.deleteItem(deleteItemSpec);

 // item should be not null, as documented
 assertNotNull(deleteItemOutcome.getItem());
 // item shouldn’t have attributes
 assertFalse(deleteItemOutcome.getItem().hasAttribute("h"));
}
```

## Your Environment

* AWS Java SDK version used: 1.11.939
* JDK version used: 11

**Comment by debora-ito** [comment]
Hi @eager, you're correct, the documentation should mention that it only returns `Item` if the item existed before calling `deleteItem`. Marking this as a documentation issue.

**Comment by AnshulYADAV007** [comment]
Hi @debora-ito, I would like to contribute to fixing the documentation.

**Comment by debora-ito** [comment]
@AnshulYADAV007 thank you for volunteering. In the Java SDK v1, we have to add the changes to our internal packages for them to be published, so it will be easier if we do this ourselves since it's a small change. I'll work on it this week.

**Comment by debora-ito** [comment]
DeleteItemOutcome javadoc updated, closing this.
Feel free to reach out if you have any other question.
