### ISSUE TITLE
Sending Bytes on Kinesis Receiving JSON

### ISSUE THREAD

**Issue by hanymorcos** [aws/aws-sdk-java#2560]
I have a program that based on Java Generic. 

```
Kinesis<MyRecord> myrecord = new Kinesis<>(); 
```

MyRecord is a Java class that implements Serializable. 

I'm sending Data as Bytes, I would like to receive the data as bytes. 
But I get the data as JSON in data buffer. 

I see the data I'm sending has the correct stream header "ACED00057". 

But the data received is JSON.
 
**Can I tell Kinesis not send data as JSON at all and just use Bytes?** 

https://stackoverflow.com/questions/67220570/kinesis-invalid-stream-header

* AWS Java SDK version used: 1.11.631
* JDK version used: Java 8 
* Operating System and version: Openshift Pod.

**Comment by debora-ito** [comment]
@hanymorcos I'm not fully clear on the question. Can you provide a self-contained repro code?

Note that this is a service usage question, which we sometimes don't have the expertise to answer.
