### ISSUE TITLE
How to access HttpClientGetConnectionTime metric for each request?

### ISSUE THREAD

**Issue by swaranga** [aws/aws-sdk-java#2563]
I am looking at the docs for SDK metrics: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/metrics/package-summary.html and I wanted to know how to get access to the `HttpClientGetConnectionTime`

I am using my own custom `RequestMetricsCollector` both at the SDK level and at each individual request level - the SDK uses the SDK level collector if no request level collector is defined. How do I get access to the `HttpClientGetConnectionTime` metric - from the doc it seems like it is only made available to a _Service metrics collector_ but from the code I do not see that metric field.

* https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/metrics/ServiceMetricCollector.java
* https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/metrics/ServiceLatencyProvider.java
* https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/metrics/ServiceMetricType.java

Here is how I configure my SDK (example for DynamoDB client):

```
AmazonDynamoDB ddbClient = AmazonDynamoDBClientBuilder.standard()
                .withMetricsCollector(new MyCustomSdkLevelRequestCollector(...))
                .withRegion(...)
                .build();
```

And when I am using this to make a call, I also attach a request level metric collector

```
ddbClient.getItem(
  new GetItemRequest()
    .withMetricsCollector(new MyCustomRequestLevelMetricsCollector(...)
);
```

In both the cases, my collectors are extending the `RequestMetricCollector` abstract class as seen here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/metrics/RequestMetricCollector.java

I don't see how I can get access to the `HttpClientGetConnectionTime` metric. Please assist.

**Comment by swaranga** [comment]
Ping.

**Comment by swaranga** [comment]
Ping. Any updates?

**Comment by swaranga** [comment]
Ping. Any updates on this?

**Comment by aaoswal** [comment]
Hi @swaranga,
I apologize for the delay but are you currently still facing the issue?

**Comment by swaranga** [comment]
Yes. I am still facing this issue. I forgot to set the next monthly reminder to ping here.

**Comment by aaoswal** [comment]
Hi @swaranga,
Upon further investigation and assistance from the team, I can confirm that unfortunately accessing `HttpClientGetConnectionTime` with a custom `RequestMetricsCollector` is not supported.

Sorry again for the delay.

**Comment by kchobantonov-runbuggy** [comment]
```HttpClientGetConnectionTime``` is available when ```com.amazonaws.metrics.ServiceMetricCollector.collectLatency``` method is invoked
