### ISSUE TITLE
Does the ClientExecuteTime metric include retries?

### ISSUE THREAD

**Issue by swaranga** [aws/aws-sdk-java#2564]
I am looking at the docs for SDK metrics: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/metrics/package-summary.html and I have a question about the `ClientExecuteTime` metric.

Under the _AWS Request Metrics_ section, does the metric `ClientExecuteTime` represent one single physical Http request (as defined in the nomenclature section above; no retries) or does it represent a logical request (including retries made by the SDK, if any).

**Comment by debora-ito** [comment]
@swaranga apologies for the delay in response. 

Yes, `ClientExecuteTime` will include retries. 
A single http request metric would be `HttpRequestTime`.
