### ISSUE TITLE
End of support date SDK version 1

### ISSUE THREAD

**Issue by blitz555** [aws/aws-sdk-java#2565]
My organization currently use SDK v1. In our attempt to migrate to SDK v2 we currently see many classes that have no equivalent in v2 and confirmed this with developers of SDK v2 on their Github page. Therefore, we have reservations about migrating to SDK v2 at the moment.

Is there any information about when SDK v1 will reach end of support for the foreseeable future (months, years)? 

## Describe the issue

For example, .NET SDK, 
https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-the-aws-sdk-for-net-version-2/

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by blitz555** [comment]
https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html

**Comment by millems** [comment]
Ending support for 1.x is not something we take lightly. While we have nothing to announce at this time, our maintenance policy (https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html) guarantees that we’ll give you at least 18 months notice before we end support for 1.x. I’ll also say that while 18 months of notice is the minimum, we want to do more than the minimum here.

In the meantime, we are still filling feature gaps that impact people in 2.x. You mention that there are features missing that you want to see in 2.x before you can even consider migrating from 1.x. I know that there are issues open in 2.x and that you have probably upvoted or commented on those issues, but can you list them out for us explicitly?

**Comment by blitz555** [comment]
@millems Thank you for your prompt reply. We use many AWS services. The ones I didn't find matching class for in v2, as noted in https://github.com/aws/aws-sdk-java-v2/issues/2459, could be just a small sample. We currently use these imported classes: 
[importedclasses.txt](https://github.com/aws/aws-sdk-java/files/6455132/importedclasses.txt)
. I could not afford the time to search for all classes that are not migrated to v2. I'm hoping the migration guide could list which classes were added, removed, renamed, etc.

**Comment by millems** [comment]
Thanks for the import list, that helps a lot! It would be nice to have a class mapping from old public classes to (generally) which new classes to use. A more comprehensive migration guide in general would likely be welcome.

**Comment by blitz555** [comment]
I look forward to the updated migration guide. I understand the list of classes is very long so I will close this issue for now.
