### ISSUE TITLE
AWSSecurityTokenServiceClient.setRegion deprecated

### ISSUE THREAD

**Issue by blitz555** [aws/aws-sdk-java#2568]
According to documentation, setRegion is deprecated for this Client, 
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html#setRegion-com.amazonaws.regions.Region-

What can I replace this method with that isn't deprecated?

## Describe the issue

As described in summary.

## Links

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html#setRegion-com.amazonaws.regions.Region-

**Comment by debora-ito** [comment]
`AmazonWebServiceClient.setRegion(String)` was deprecated in favor of `AwsClientBuilder.setRegion(String)`. The AWSSecurityTokenServiceClient  documentation says

> Deprecated. 
Description copied from class: [AmazonWebServiceClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonWebServiceClient.html#setRegion-com.amazonaws.regions.Region-)

and clicking at the AmazonWebServiceClient link leads to the documentation that indicates what to use instead.
To set a region to the client, use the client builder:

```
AmazonEC2 ec2 = AmazonEC2ClientBuilder.standard()
                    .withRegion("us-west-2")
                    .build();
```

You can also use the Regions enum:
```
AmazonEC2 ec2 = AmazonEC2ClientBuilder.standard()
                    .withRegion(Regions.US_WEST_2)
                    .build();
```

For this and more information on AWS Region selection, please check the AWS SDK for Java Developer Guide: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html

**Comment by debora-ito** [comment]
Forgot to mention that specifically for AWS SecurityTokenService (STS), by default the Java SDK v1 will use the legacy endpoint `sts.amazonaws.com` even if you define a region in the client builder. To use the STS regional endpoints you need to set a flag in the config file or as an environment variable:
```
sts_regional_endpoints = regional
```

For a list of regions impacted by this flag, check our Reference Guide: https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-sts_regional_endpoints.html

**Comment by blitz555** [comment]
Thank you!
