### ISSUE TITLE
AmazonWebServiceClient.setEndpoint is deprecated

### ISSUE THREAD

**Issue by blitz555** [aws/aws-sdk-java#2569]
When I invoke 
`public void setEndpoint(String endpoint)`
It is flagged as deprecated. In docs for this method: 
`Deprecated. use AwsClientBuilder.setEndpointConfiguration(AwsClientBuilder.EndpointConfiguration) for example: builder.setEndpointConfiguration(new EndpointConfiguration(endpoint, signingRegion));`

How could I create EndpointConfiguration to match the behaviour of setEndpoint with only one parameter?

## Describe the issue

As described in summary. 

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonWebServiceClient.html#setEndpoint-java.lang.String-

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/client/builder/AwsClientBuilder.EndpointConfiguration.html

**Comment by debora-ito** [comment]
Hi @blitz555, the EndpointConfiguration takes two parameters: the endpoint and the signing region, which is the region to use in the [Sigv4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) request signature.

```
AmazonS3 s3 = AmazonS3ClientBuilder.standard()
     .withEndpointConfiguration(new EndpointConfiguration("https://endpoint-override.com", "eu-west-1"))
     .build();
```

Note that you only need to provide an endpoint configuration if you need to override the default service endpoint used by the SDK. 

Check the Java SDK Reference Guide for more information on client configuration: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#region-selection-choose-endpoint

**Comment by blitz555** [comment]
Will 
`AmazonS3 s3 = AmazonS3ClientBuilder.standard()
     .withEndpointConfiguration(new EndpointConfiguration("https://endpoint-override.com", null))
     .build();`
have the same behaviour as 
`s3.setEndpoint("https://endpoint-override.com")`?

**Comment by debora-ito** [comment]
Hi @blitz555,

> Will 
AmazonS3 s3 = AmazonS3ClientBuilder.standard() .withEndpointConfiguration(new EndpointConfiguration("https://endpoint-override.com", null)) .build();
have the same behaviour as
s3.setEndpoint("https://endpoint-override.com")?

It will have the same behavior, but you'll probably see errors related to request signature or other request issues further in the process. 

As you can see in the code snippet, `setEndpoint()` would make a guess on the signing region based on the endpoint string provided. The guess would try to match the endpoint with any of the standard aws endpoints for the client service and the extract region from it. This method works for an endpoint like `dynamodb.ap-east-1.amazonaws.com` but it does not work well for an endpoint like `endpoint-override.com`. Providing the signing region in EndpointConfiguration removes the guess work and allows you to know exactly which region is being used to sign the requests:
`new EndpointConfiguration("https://endpoint-override.com", "ap-east-1")`

> 1. How do I call new EndpointConfiguration() knowing only endpoint (and not signingRegion)?

To be clear, if you are using one of the default standard service endpoints you don't have to provide EndpointConfiguration, the SDK will use the standard endpoint automatically. If you need to override the default service endpoint (to use a third-party application for example) use the region that will contain your resources - if your s3 bucket is in `us-east-2` then use `us-east-2`.

> 2. How does withEndpointConfiguration match the behaviour of setEndpoint in lines 320-323? Or how it doesn't?
These are the questions I cannot answer after reading the documentation.

See the first answer.
