### ISSUE TITLE
Encrypting files with Java 7 at local using AWS KMS Data Keys

### ISSUE THREAD

**Issue by EthosData** [aws/aws-sdk-java#2571]
Hello! I am trying to encrypt/decrypt files in local with AWS KMS DataKey but I don't know what to use to do it.

I have already generate the DataKey from AWS KMS (receiving the Plaintext Key and the Encrypted Key). Now it's suppose I have to use Plaintext key to encrypt the file, store the Encrypted key with Final Encrypted file and delete Plaintext key.

`//AWS KMS requesting data key`
`GenerateDataKeyRequest dataKeyRequest = new GenerateDataKeyRequest()`
`dataKeyRequest.setKeyId(keyId)`
`dataKeyRequest.setKeySpec("AES_256")`

`GenerateDataKeyResult dataKeyResult = awskmsClient.generateDataKey(dataKeyRequest)`
`ByteBuffer plaintextKey = dataKeyResult.getPlaintext()`
`ByteBuffer encryptedKey = dataKeyResult.getCiphertextBlob()`

How do I encrypt a file in Java 7 using that Plaintext Key? I mean, there are several ways to do it but which is the most effective and secure with AES_256 cipher I request to AWS KMS to get the keys?

I cannot use AWS Encryption to do that (even it would be easier) because o Java 7 version

**Comment by debora-ito** [comment]
Hi @EthosData, Java SDK v1 is compatible with Java 7, you should not have issues using the Encryption Client. Are you seeing differently?

**Comment by EthosData** [comment]
Finally we managed to encrypt files in Java 7 using the data key from the AWS KMS. And using Java SDK v1.

Using the crypto library from Java (javax.crypto.Cipher) and AES 256 algorithm.
