### ISSUE TITLE
uploadFileList without directory in TransferManager

### ISSUE THREAD

**Issue by jereztech** [aws/aws-sdk-java#2572]
Rarely does a backend create files on the server, so using a directory as a source for uploads causes unnecessary memory and performance problems. Ideally, the backend sends the MultipartFile received from the frontend without having to save it internally on the server and then upload it, this is frustrating and unnecessary.

## Describe the Feature
Upload files directly without saving them to internal server directories.
In TransferManager, create a new method using InputStream instead of File:
`MultipleFileUpload uploadFileList(String bucketName, List<InputStream> streams)`

## Is your Feature Request related to a problem?
I'm always frustrated when I'm forced to implement unnecessary code that negatively impacts the end user, for example response time.

## Proposed Solution
In TransferManager, create a new method using InputStream instead of File:
`MultipleFileUpload uploadFileList(String bucketName, List<InputStream> streams)`
Is very important to use InputStream because many times we manipulate the files sent by users, for example reducing images.

## Describe alternatives you've considered
uploadFileList without directory is the best option!

## Additional Context
Cloud computing is expensive, therefore creating unnecessary directories is not reasonably acceptable. Processing delays negatively impact our companies, affect our image and can easily cause abandonment of our end users.

## Your Environment
* AWS Java SDK version used: 1.11.970
* JDK version used: 1.8.0.291
* Operating System and version: macOS Big Sur 11.3.1

**Comment by debora-ito** [comment]
Hi @jereztech this is a restriction on the S3 side. To be able to send putObject or uploadPart requests, S3 requires to know the `content-length` beforehand, so the SDK tries to buffer the stream into memory or writes the file in disk to calculate its size. 

This is an old ask that we get (see https://github.com/aws/aws-sdk-java/issues/474), and it has more chance to be addressed in the TransferManager Java SDK v2 equivalent that we are tracking here: https://github.com/aws/aws-sdk-java-v2/issues/37. Feel free to upvote and add your use case to the v2 tracking issue.
