### ISSUE TITLE
DeleteObjectsRequest not working with String keys

### ISSUE THREAD

**Issue by jereztech** [aws/aws-sdk-java#2574]
## Describe the bug
DeleteObjectsRequest not working with String keys

## Expected Behavior
DeleteObjectsRequest should work with String keys

## Current Behavior
no object is deleted in S3

## Steps to Reproduce
       ` private final AmazonS3 s3Client;

         public void deleteFiles(String bucketName, String... keys) {
		s3Client.deleteObjects(new DeleteObjectsRequest(bucketName).withKeys(keys));
	     }
      `

## Context
This works: `Arrays.stream(keys).forEach(key -> s3Client.deleteObject(bucketName, key))`
This don't work: `s3Client.deleteObjects(new DeleteObjectsRequest(bucketName).withKeys(keys))`

## Your Environment
* AWS Java SDK version used: 1.11.970
* JDK version used: 1.8.0.291
* Operating System and version: macOS 11.3.1

**Comment by debora-ito** [comment]
> This don't work: s3Client.deleteObjects(new DeleteObjectsRequest(bucketName).withKeys(keys))

Why it's not working? Does it throw an exception?

**Comment by jereztech** [comment]
no exception and no object is deleted in S3

**Comment by debora-ito** [comment]
@jereztech I'm not able to reproduce, the code works fine for me locally.

Are you checking the right bucket, in the right region?
Can you turn on the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and provide them? Make sure to redact any sensitive information.

**Comment by jereztech** [comment]
S3 doesn't require region selection; but yes, my AmazonS3Client is singleton and has same configuration for all requests. I updated the sdk version to aws-java-sdk-bom@1.11.1019 and the problem continues with no exceptions and no deletions in S3.

Logs:
"amz-sdk-invocation-id: 01b384f1-97b5-6b87-ab88-9a04ba291d15[\r][\n]"
"User-Agent: aws-sdk-java/1.11.1019 Mac_OS_X/10.16 Java_HotSpot(TM)_64-Bit_Server_VM/25.251-b08 java/1.8.0_251 groovy/2.5.7 vendor/Oracle_Corporation cfg/retry-mode/legacy[\r][\n]"
"x-amz-request-id: K2Q7BF1KTGABPKSP[\r][\n]"
"<DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Deleted><Key>65503397208d47f5ad2de9d318e74188Wq2CW0p1CqCn/1d6aff5afed147f9afc5eba155cf0bb77RboMJ1s4A2p.jpg</Key></Deleted></DeleteResult>[\r][\n]"

DeleteResult is fake because deletions are not executed on S3.

This works: Arrays.stream(keys).forEach(key -> s3Client.deleteObject(bucketName, key))
This don't work: s3Client.deleteObjects(new DeleteObjectsRequest(bucketName).withKeys(keys))

**Comment by debora-ito** [comment]
@jereztech please note that those are not wire logs. Wire logs will hopefully show additional information that is being sent over the wire.

**Comment by jereztech** [comment]
this is still a problem

**Comment by debora-ito** [comment]
@jereztech Are you able to provide the full wirelogs? Wirelogs are different from the logs you showed in your last comment, they look like the logs in this comment: https://github.com/aws/aws-sdk-java/issues/1733#issuecomment-415249733.
