### ISSUE TITLE
Non US-ASCII characters in metadata throws AmazonS3Exception

### ISSUE THREAD

**Issue by leogerber** [aws/aws-sdk-java#2577]
I have read the documentation I think non-ascii characters metadata should be automatically encoded to ascii characters using UTF-8 encoding and this then gets encoded to ascii characters.
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

There is the exact same bug in aws-sdk-net that already got fixed some time ago. 
If there are some things unclear about my bug, you can also look for certain information here:
https://github.com/aws/aws-sdk-net/issues/1587

## Expected Behavior

According to the documentation, S3 should handle non-ascii characters automatically by itself.

## Current Behavior

When I upload an image with metadata that contains non-ascii characters an AmazonS3Exception gets thrown.
`com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

## Steps to Reproduce

```
AmazonS3Client s3C = new AmazonS3Client();

PutObjectRequest objectRequest = new PutObjectRequest("/test", "file-key-test", new File("/Users/test/test.txt"));
ObjectMetadata metadata1 = new ObjectMetadata();
metadata1.addUserMetadata("value", "£");
objectRequest.setMetadata(metadata1);

s3C.putObject(objectRequest);
```

## Context

I would like to be able to upload files with metadata that contains non-ascii characters like äöü or -_

## Your Environment

* AWS Java SDK version used: 1.11.1019
* JDK version used: 1.11.0
* Operating System and version: Windows 10 Version 1909

**Comment by debora-ito** [comment]
Hi @leogerber thank you for reaching out. Even though I'm able to reproduce the issue, I'll look for S3 guidelines for metadata values. As showed in the .NET SDK github issue, we cannot simply change to start enconding the values because it can break existing metadata. And running a test using the AWS Console shows I'm not able to add "£" as a user-define metadata too, I see the same signature error.

Will do some research and get back shortly.

**Comment by mumar-FA** [comment]
Guys, any update on this please?

**Comment by debora-ito** [comment]
Hey everyone, sorry for losing track of this.

We can't add automatic encoding to the SDK, it would be a breaking change for customers who already added encoding to their code (as it has occurred in the Dotnet SDK change https://github.com/aws/aws-sdk-net/issues/1587).
We don't have plans to add a feature like `EnableUnicodeEncodingForObjectMetadata` soon in v1.

The recommendation is to add special character handling in your application.
