### ISSUE TITLE
STSAssumeRoleSessionCredentialsProvider not using regional endpoint

### ISSUE THREAD

**Issue by ShrushtiPatel** [aws/aws-sdk-java#2579]
STSAssumeRoleSessionCredentialsProvider is not able to honor AWS_STS_REGIONAL_ENDPOINTS: "regional" and AWS_REGION: "us-east-1" env variables and trying to connect to global endpoint sts.amazonaws.com:443

## Current Behavior
I have following code which tries to connect to global sts endpoint inspite of env variables
provider = new STSAssumeRoleSessionCredentialsProvider(provider, awsRole, "secor");        

## Expected Behavior
It should access regional(us-east-1) sts endpoint       

## Your Environment

AWS SDK
 <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
            <version>1.11.704</version>
        </dependency>
JAVA 8

**Comment by debora-ito** [comment]
That's expected. The underlying STS client was written before the STS regional endpoints were released. But there is another option.

The constructor 
```
STSAssumeRoleSessionCredentialsProvider(AWSCredentialsProvider, String, String)
```

was deprecated in favor of a Builder pattern, and the Builder has an option to provide your own STS Client. I believe if you pre-configure the "us-east-1" region in this STS Client it will use the regional endpoint.

Check the STSAssumeRoleSessionCredentialsProvider.Builder documentation: 
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.Builder.html#withStsClient-com.amazonaws.services.securitytoken.AWSSecurityTokenService-

Let us know if that helps.
