### ISSUE TITLE
getCurrentRegion for ECS Service

### ISSUE THREAD

**Issue by ozaditya** [aws/aws-sdk-java#2581]
Currently getCurrentRegion call made from java sdk only fetchs regions if application is running on EC2 based instance only and does not support other services like ECS and EKS or any other containerised platform deployed on top of EC2

## Describe the Feature

Currently getCurrentRegion call made from java SDK only and  fetches regions if application is running on EC2 based instance and otherwise written null. Currently, I don't see any SDK option which can help fetch current region when application run from ECS or EKS or other service where application is not directly deployed on top of an instance but encapsulated into a namespace which don't have access to EC2 metadata. 

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/regions/Regions.html#getCurrentRegion()

## Is your Feature Request related to a problem?

As everyone is now migrating to container-ed world to deploy and run application across regions absence of any such function for ECS which returns current regions push us toward only thinkable resolution of adding environment variable "AWS_REGION" in task definition which can be consumed by application and passed to client to make connect.

This adds a unnecessary trouble of maintaining one more configuration parameter.

## Proposed Solution

ECS task metadata API can help here. It return Availability zone which can be spitted to return AWS Region.

Curl ${ECS_CONTAINER_METADATA_URI_V4}/task return below json
------
...
 "PullStartedAt": "2020-10-02T00:43:06.202617438Z",
    "PullStoppedAt": "2020-10-02T00:43:06.31288465Z",
    "AvailabilityZone": "us-west-2d",
    "LaunchType": "EC2",
    "Containers": [
        {
...
------
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-metadata-endpoint-v4.html

## Describe alternatives you've considered

Currently possible alternate is by setting environment variable or reading region information from pre-configured property file

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @ozaditya thank you for reaching out.

To be able to make a call like getCurrentRegion in a container, the information must be made available by the ECS team in the container metadata, like you exemplified. I'll send this feature request to the ECS team, and will comment here when they reply.

**Comment by debora-ito** [comment]
Hi @ozaditya the ECS team has a public roadmap, and this request is already there: https://github.com/aws/containers-roadmap/issues/337.

Please upvote the request there and feel free to add your use case, the more votes the issue get, the more likely they are to gain traction.
