### ISSUE TITLE
AWS Appsync Signature BadRequestError: The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by FraserYu** [aws/aws-sdk-java#2583]
## Describe the bug
Get BadRequestException when send HTTP request to AWS Appsync using [AWS4Signer.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java) `sign(SignableRequest<?> request, AWSCredentials credentials)` method for signature 

## Expected Behavior
Get 200 HTTP status code with correct credentials

## Current Behavior
Get 400 HTTP status code and BadRequestException with correct credentials

## Steps to Reproduce
```java
DefaultRequest defaultrequest = new DefaultRequest<Void>("appsync");
defaultrequest.setHttpMethod(HttpMethodName.POST);
defaultrequest.setEndpoint(URI.create("https:xxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql"));
defaultrequest.setContent(new StringInputStream("my json string"));

AWS4Signer signer = new AWS4Signer();
signer.setRegionName("us-east-1");
signer.setServiceName("appsync");
signer.sign(defaultrequest, credentials);
```

## Possible Solution
Above Appsync URL **without ending slash "/"**  is generated in AWS Console Appsync Settings 
but when generate canonical request string though the SDK method `appendUri(final String baseUri, String path, final boolean escapeDoubleSlash)` in [SdkHttpUtils.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/SdkHttpUtils.java) , it will add an ending slash "/" automaticly

to avoid this issue,  we need to manually add the ending slash "/" to above endpoint  as below: 
```java
defaultrequest.setEndpoint(URI.create("https:xxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql/"));
```

This is where the two inconsistent.

**Suggestion**: remove automaticlly add ending slash "/" code logic in SDK, cause Postman works fine when send request to Appsync without ending slash "/"  by adding AWS Signature, Nodejs and Python works well without ending slash "/"

## My Environment

* AWS Java SDK version used: 1.11.870
* JDK version used: 11
* Operating System and version: MACOS

**Comment by FraserYu** [comment]
hi @debora-ito 

Thanks for your quick response.

I'm sorry, for complying with company policy, I'm not allowed to post full stacktrace with the error.

it's easy to reproduce, Just use any HttpClient(eg. OkHttpClient) to send http request and you will get the BadRequestException. as described above, when you debug to ` appendUri(final String baseUri, String path, final boolean escapeDoubleSlash)` , it will add an ending slash to the URL. that's the point

**Comment by debora-ito** [comment]
Ok, so I'm able to reproduce the BadRequestException - "Signature does not match"  error. But adding a slash in the end does not work for me, I still get the same signature error.

I need to investigate what could be the root cause. In the meantime, using your workaround is the best bet.

**Comment by FraserYu** [comment]
hi @debora-ito 

please make sure add http request header("Content-Type", application/json)

**Comment by debora-ito** [comment]
Still not able to repro the success path after adding content-type. 

Are you using a proxy?
I know your company policy does not allow to provide stacktraces, but what about wire logs, can you provide them?
