### ISSUE TITLE
S3 SDK copy between buckets is much slower than aws cli

### ISSUE THREAD

**Issue by gs618** [aws/aws-sdk-java#2584]
S3 SDK copy between buckets is much slower than aws cli

## Describe the issue
I'd like to use the sdk to copy file between buckets in Lambda. For a 2.2GB file, it takes 50+ secs. It is a kind fo slow. 
But when I use a command line to copy the same file, the duration is less than 20 secs.

I'd like to know if there is any optimization I could do in code.

## Steps to Reproduce
1. copy file by sdk, the sdk objects I used are CopyObjectRequest, AmazonS3 | TransferManager
2. copy file by aws cli, the command I usesd is aws s3 cp

## Your Environment

* AWS Java SDK version used: 1.11.1002
* JDK version used: 11
* Operating System and version: MacOS 11.2.3

**Comment by debora-ito** [comment]
@gs618 apologies for the long delay in response.

It depends on how the TransferManager is configured, if it's using single-part or multi-part copy for example. But it's hard give suggestions without looking at how you are making the copy.

Lambda cold-start is also a known issue in Java SDK 1.x, this github thread explains the problem - https://github.com/aws/aws-sdk-java/issues/1774. 

If you are able to use Java SDK 2.x, it contains several optimizations target for Lambda use, like the option to use a more lightweight client and a maven archetype designed to reduce startup time. You can read more details in this blog post - https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time.

Let us know if this helps.
