### ISSUE TITLE
Elasticsearch - Apply package update for domain

### ISSUE THREAD

**Issue by byronvoorbach** [aws/aws-sdk-java#2585]
Hiii

I just started using this java SDK for managing my Elasticsearch instance in AES. 
While building support for updating synonyms through an external application, I was trying to get packages updated for my specific domain. After associating a package and updating the files in S3 through the SDK, I need to use the console to apply the package update for my domain. 

The documentation states the following:

[> When the package status changes to Available, select it. Then choose one or more associated domains, Apply update, and confirm. Wait for the association status to change to Active.](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/custom-packages.html#custom-packages-updating)

I couldn't find an API in the Elasticsearch SDK to apply the package update, but was wondering if this would be a good new feature.

**Comment by debora-ito** [comment]
Hi @byronvoorbach thank you for reaching out!

I believe we have an [ElasticsearchClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/elasticsearch/ElasticsearchClient.html) API, it's UpdatePackage -
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/elasticsearch/ElasticsearchClient.html#updatePackage-software.amazon.awssdk.services.elasticsearch.model.UpdatePackageRequest-

Let me know if this helps.

**Comment by byronvoorbach** [comment]
Hi @debora-ito 

Thank you for your reply! 

I was under the impression that `UpdatePackage` only updates a package, which then still needs to be applied for a specific domain. After using `UpdatePackage`, I can see in Console that my package is updated, but not that it's applied:

![Screenshot 2021-05-27 at 12 16 19](https://user-images.githubusercontent.com/4427161/119809403-5e12a300-bee5-11eb-97fb-9d4387116bdc.png)

In this image you can see that V5 is available, but V1 is the current package version.

**Comment by debora-ito** [comment]
@byronvoorbach I see! In this case, would the UpgradeElasticsearchDomain API do that last step?

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-upgrade-domain

**Comment by byronvoorbach** [comment]
Hi @debora-ito!

Thank you for your reply.
Doesn't that just upgrade the version of OpenDistor running in my domain??? The update I showed is specifically for a package, and I would maybe expect an API that allows me to upgrade a certain package for a specific domain like in the UI.

My use-case is that third-party users want to update their own synonyms, but in order to do that at the moment means that I have to log-in into the console of the third party and click the update button :( 

I know console allows me to apply the package, is there a chance that you'd be able to expose that same api? I wouldn't mind contributing to this if this either if that's possible :)

**Comment by byronvoorbach** [comment]
Hi @debora-ito 

Do you have any update regarding this?? :)

**Comment by byronvoorbach** [comment]
Sorry for pushing on this thread, but I'm sort of stuck at the moment as there seems to be no way to upgrade a package for a domain through the SDK.

In the following reference:

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html

There is no reference to upgrading a package neither, only the following piece of text under `GetPackageVersionHistory`:

> Returns a map of Elasticsearch versions and the versions you can upgrade them to.

But there is no other reference to upgrading. Is this an issue that's bigger than just this SDK project? If so, do you have any recommendations for me to proceed with this?

**Comment by byronvoorbach** [comment]
I found it! Running a new `AssociatePackage` request with the results from my `UpdatePackageResult` actually upgrades the package for my domain. Maybe good to have this added to the documentation??

**Comment by debora-ito** [comment]
@byronvoorbach Apologies for the long silence, I'm glad you're not blocked anymore. 

I'll reach out to the Elasticsearch doc team and ask to list the APIs in the Developer Guide, since it mentions that the SDK can be used.
