### ISSUE TITLE
Reg : Amazon Connect -  Historical metrics SDK v 2.0 response 

### ISSUE THREAD

**Issue by kmuthuraja** [aws/aws-sdk-java#2589]
Hi,

1) I used the java SDK v2.0 issue to retrieve the historical metrics from the amazon connect. But the metrics sdk not returning any response.

Request -

GetMetricDataRequest(InstanceId=086e420c-dec5-45da-94d6-564c71807f20, StartTime=2021-05-30T01:00:00Z, EndTime=2021-05-30T10:10:00Z, Filters=Filters(Queues=[22f575d7-3327-4465-aefe-8126c2fa2860, 0e65bafd-6f5c-48e6-bcb0-2163fd58d15d, 7068941c-bed7-4ee2-a5eb-ccfb9cd4ba27, 0dee8dff-a26e-41d8-8e42-362bf43a968f, 72c019e4-e06a-4f73-93d3-f6eb95b3e7c3, ef2660d0-8228-4c39-b826-cf3deaba0a78, 1cc03003-7606-4713-870e-8e4def96c5ca], Channels=[VOICE]), Groupings=[CHANNEL, QUEUE], HistoricalMetrics=[HistoricalMetric(Name=CONTACTS_HANDLED, Statistic=SUM, Unit=COUNT), HistoricalMetric(Name=CONTACTS_QUEUED, Statistic=SUM, Unit=COUNT), HistoricalMetric(Name=CONTACTS_ABANDONED, Statistic=SUM, Unit=COUNT), HistoricalMetric(Name=SERVICE_LEVEL, Threshold=Threshold(Comparison=LT, ThresholdValue=30.0), Statistic=AVG, Unit=PERCENT)])

Response -

GetMetricDataResponse(MetricResults=[])

And also, please let me know, how to pass the multiple threshold in a single hit?

2) I tried to pass the threshold using the "Threshold" class, but its not accepting in the input request.

Threshold metric30Threshold = Threshold.builder().comparison("LT").thresholdValue(30.0).comparison("LT").build();
			
			Threshold metric20Threshold = Threshold.builder().comparison("LT").thresholdValue(20.0).comparison("LT").build();
			
			Threshold metric15Threshold = Threshold.builder().comparison("LT").thresholdValue(15.0).comparison("LT").build();
			
			List<Threshold> listThreshold = new ArrayList<Threshold>();
			listThreshold.add(metric30Threshold);
			listThreshold.add(metric20Threshold);
			listThreshold.add(metric15Threshold);

But the list or collection not accepting in the input request.

3) Historical Metrics SDK accepting the time range only within 24 hours. If i want to get the metrics for a month, how to retrieve it?

**Comment by debora-ito** [comment]
@kmuthuraja I responded the questions in https://github.com/aws/aws-sdk-java/issues/2575 so I'll close this as a duplicate. You can keep asking questions in the other thread.
