### ISSUE TITLE
S3 initiateMultipartUpload returns error code 'NoSuchKey' when I pass invalid bucket name

### ISSUE THREAD

**Issue by karkin-ai** [aws/aws-sdk-java#2590]
I'm trying to upload object using example from Amazon S3 documentation with low-level API (https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html):

```java
InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest("invalidBucketName", "<some object key>");  
InitiateMultipartUploadResult initResponse = s3Client.initiateMultipartUpload(initRequest);
```

When I call AmazonS3#initiateMultipartUpload(..) with invalid bucket name I got AmazonS3Exception with errorCode: NoSuchKey. Is it correct behaviour? According to documentation (https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) there is NoScuhBucket error, which returned when specified bucket doesn't exists. Why this error code doesn't take a place in this case?

When I pass valid bucket name and key it works as expected.

**Comment by debora-ito** [comment]
@karkin-ai can you provide the full stacktrace?
