### ISSUE TITLE
ECR repository additional protection against delete request

### ISSUE THREAD

**Issue by cw-vikas** [aws/aws-sdk-java#2592]
Feature request to improve ECR developer experience when working with IaaC

## Describe the Feature

ECR repository additional protection against delete request, when using the IaaC tools like terraform, the resource is being removed in order to maintain the state, to avoid sudden loss of ECR data (images) in repository. Its appropriate to add additional safety similar to the "termination protection" in EC2 instance. For example, If the ECR repo is flagged with the "delete protection" the resource will require manual intervention to do so.

## Is your Feature Request related to a problem?

It's not a problem, but it can solve a problem where you want additional protection for the resources when provisioning / making unexpected changes to the resource state with IaaC toolings.

## Proposed Solution

When creating / making changes to the ECR repository the additional optional parameter should be available to the SDK's and Terraform modules .

```
ECR delete protection: Disabled / Enabled
```
Note: This lifecycle parameter should be only for the repository not for the images

## Describe alternatives you've considered

The terraform aws module has a option for lifecycle but it halts the process with exception, when set to `prevent_destroy = true`

```
resource "aws_ecr_repository" "ecr-test-repo" {
  name = "test-repo"

  lifecycle {
    prevent_destroy = true
  }
}
```

## Your Environment

* AWS Java SDK version used: Not applicable to the feature as it will be a update to all SDK's
* JDK version used: Not applicable
* Operating System and version: Mac
* Terraform: 0.14.9

**Comment by debora-ito** [comment]
@cw-vikas actually I just remembered that ECR has a public roadmap in https://github.com/aws/containers-roadmap.
It looks like this request is already there: https://github.com/aws/containers-roadmap/issues/215. Feel free to upvote that issue and add your use case in the comments.

Let me know if you have any other question or concern.

**Comment by cw-vikas** [comment]
@debora-ito 
Thanks for reviewing the feature request and navigating me to the roadmap.  I have upvoted the existing request.
https://github.com/aws/containers-roadmap/issues/215
I will close this issue
