### ISSUE TITLE
Cold-start improvements with a lightweight client

### ISSUE THREAD

**Issue by davidmoten** [aws/aws-sdk-java#2597]
I wanted to improve my lambda cold-start times (and still use java) so I knocked up a lightweight client at https://github.com/davidmoten/aws-lightweight-client-java. The client has a friendly API, performs required AWS Signature Version4 request signing, and includes an inbuild xml-parser. The artifact is 56K at the moment which of course has a dramatic effect on the class loading delays incurred in the cold start of a lambda function.

I thought the aws java sdk dev team might be interested to see the perf benefits of the lightweight client but also users should know they have an alternative to really get java lambda cold-start times down (if they can do without the auto-complete goodness of the aws sdk).  

Review welcome at https://github.com/davidmoten/aws-lightweight-client-java.

<img width="500" src="https://github.com/davidmoten/aws-lightweight-client-java/raw/master/src/docs/graph.jpeg"/>

Update: I've noticed differences in cold start with the Lightweight client just making the client variables static fields. I'll do the same with sdk v1 and v2 and get some more stats.

**Comment by davidmoten** [comment]
I moved the instantiation of client objects to static fields and reran my analysis. There is still a big cold-start advantage for using the lightweight client. I've documented it [here](https://github.com/davidmoten/aws-lightweight-client-java/blob/master/README.md#instantiating-client-objects-as-static-fields) (and included exact source code used so you can check my patterns).

Here's an extract that is the request time in seconds (from my home) against an API Gateway + 2GB Lambda integration and you can see that the lightweight client takes about 40% off cold start times on average compared to the v2 SDK.

| | Average | Stdev | Min | Max | n |
|-------|-------|-------|------|-------|------|
| **AWS SDK v1** | 3.987 | 0.320 | 3.583 | 5.280 | 28 |
| **AWS SDK v2** | 3.153 | 0.267 | 2.918 | 4.060 | 28 |
| **lightweight** | 1.938 | 0.149 | 1.739 | 2.376 | 28 |

If you are interested in contributing further to this discussion a good place is on the AWS SDK v2 [issue](https://github.com/aws/aws-sdk-java-v2/issues/2527) (I posted there as well given that I did the comparisons against both AWS SDK v1 and v2). Having said that if you post something here, I'll answer here.

**Comment by debora-ito** [comment]
Hi @davidmoten to keep all the discussion in one place let's close this one here and track this on the Java v2 repo - https://github.com/aws/aws-sdk-java-v2/issues/2527.
