### ISSUE TITLE
Support for SNS message attributes

### ISSUE THREAD

**Issue by gregtszabo** [aws/aws-sdk-java#2599]
Make SNS message attributes accessible when handling HTTP(S) subscriptions with SnsMessageManager

## Describe the Feature
In the [SNS library](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-sns), the [SnsMessageUnmarshaller](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/message/SnsMessageUnmarshaller.java) does not capture the message attributes that SNS sends as part of the HTTP(S) subscription. Please add support for message attributes. 

## Is your Feature Request related to a problem?
The message attributes contain important metadata that we are unable to access using this library. 

## Your Environment

* AWS Java SDK version used: 1.11.1028
* JDK version used: 11.0.10
* Operating System and version: macOS 11.2.3

**Comment by debora-ito** [comment]
Hi @gregtszabo which attributes were you expecting to see, specifically?

**Comment by gregtszabo** [comment]
Hey @debora-ito , I'm looking for [these](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html). These are populated in the request that comes from SNS under `MessageAttributes`. Ideally, you would add an additional field in the SnsMessageUnmarshaller [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/message/SnsMessageUnmarshaller.java#L25). The conversion will have some complexity as the MessageAttributes contains one of these four types: 1) String 2) String.Array 3) Number 4) Binary. These are documented in this [link](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html) I referenced earlier.

**Comment by debora-ito** [comment]
Got it! This has more chance to be prioritized in Java SDK v2, it's where the team is concentrating its efforts. SnsMessageManager is not currently supported in v2 but we are tracking in https://github.com/aws/aws-sdk-java-v2/issues/1302. I've added a comment referencing your request, feel free to upvote 👍  the issue description and tell us more about your use case.

Setting this to auto-close soon, do reach out if you have any more questions.

**Comment by gregtszabo** [comment]
Thanks @debora-ito , do you have an ETA for when v2 will come out?

**Comment by debora-ito** [comment]
Java SDK v2 is generally available already, but some v1 features are not supported yet (like SnsMessageManager). 

We usually don't comment on timelines, whenever we have new information we comment on the tracking issue.
