### ISSUE TITLE
OSGi information missing in Maven Central JAR

### ISSUE THREAD

**Issue by alblue** [aws/aws-sdk-java#260]
Despite the data in META-INF/MANIFEST.MF specifying the content for the OSGi metadata, the generated JAR that lives in Maven Central does not include that file and instead replaces it with a generic one.

http://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.8.6/aws-java-sdk-1.8.6.jar
META-INF/MANIFEST.MF contains:

Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: drtoolci
Build-Jdk: 1.7.0_51

**Comment by manikandanrs** [comment]
@sopel We have an <a href="https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-osgi">aws-java-sdk-osgi</a> module being generated specifically for OSGi. Let us know if this works for you.

Feel free to reopen this ticket if there is any issue.
