### ISSUE TITLE
TransferManagerBuilder indicates "During parallel downloads, each part is downloaded to a temporary file" - is this correct?

### ISSUE THREAD

**Issue by david-sitsky** [aws/aws-sdk-java#2600]
I noticed TransferManagerBuilder has javadoc which states:

> During parallel downloads, each part is downloaded to a temporary file, gets merged
> into the final destination file and will be deleted. These temporary files uses disk space temporarily.
> Disable parallel downloads if your system do not have enough space to store these files during download.

However when I looked at the code for TransferManager and DownloadS3ObjectCallable - it seems each thread is creating its own RandomAccessFile and seeking to the appropriate position in the destination file for dumping the S3 part's contents to directly without temporary files (at least for version 1.11.595).

Have I missed where the temporary files are created or is the documentation out of date?

**Comment by debora-ito** [comment]
Hi @david-sitsky thank you for the call out. You are correct, TransferManager does not use temporary files anymore, the documentation is outdated. We'll work to change the docs.

**Comment by debora-ito** [comment]
Documentation was updated, that excerpt was removed - https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManagerBuilder.html#isDisableParallelDownloads--

Thank you again!
