### ISSUE TITLE
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'

### ISSUE THREAD

**Issue by zhazi0101** [aws/aws-sdk-java#2601]
## Describe the issue
We have code to write to AWS S3 bucket. As the client's bucket can be located into different regions, so I am trying to getBucketLocation based on the bucket name. However, when I try to do that, I got error below

`The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: PB6A03KGA44SVJJ4).
`
Below is the code

`ClientConfiguration clientConfiguration = new ClientConfiguration();
clientConfiguration.setSignerOverride("AWSS3V4SignerType");
  AmazonS3 s3Client = new AmazonS3Client(clientConfiguration);
  String region = s3Client.getBucketLocation(bucketName);`

Note that our application can be deployed to EMRs at diff regions. I googled around some people said that use default region ("us-east-1") without set endpoint can do that. But as you can see, this is exactly what happened here. Also, some suggested setForceGlobalBucketAccess(true) will do the trick. However, due to the library conflicts, our AWS jdk version is super old (compile 'com.amazonaws:aws-java-sdk:1.7.4'), so we don't have option for AmazonS3ClientBuilder, which is the way all online materials are using to do the global bucket access.

Any body can help? Thanks in advance.

## Your Environment

* AWS Java SDK version used: 1.7.4
* JDK version used: jdk 1.8
* Operating System and version: AWS EMR

**Comment by debora-ito** [comment]
@zhazi0101 yes the `forceGlobalBucketAccess` flag is the solution for this, unfortunately I don't see another way to work around it besides upgrading the SDK version.

**Comment by crberus** [comment]
Given our conversation and your documented findings in the ticket (https://idtdna.atlassian.net/browse/CLDOPS-304), I think this is a reasonable workaround and approach for the short- to mid-term.
