### ISSUE TITLE
version 1.11 and version 1.9 are incompatible. 

### ISSUE THREAD

**Issue by kunwuliu** [aws/aws-sdk-java#2605]
## Describe the bug
version 1.11 and version 1.9 are incompatible.  Cannot find com.amazonaws.util.json.JSONObject and com.amazonaws.util.json.JSONException in version 1.11.

My program is dependent on version 1.9. and 1.11, but these two versions are incompatible.

## Expected Behavior
Please add the missing classes in version 1.11. Make these two versions be compatible.

## Your Environment

* AWS Java SDK version used: 1.11
* JDK version used: 1.8
* Operating System and version: windows 10

**Comment by debora-ito** [comment]
Hi @kunwuliu, different versions of the same library are not suppose to be compatible, that's the purpose of the version numbers. 

In general, you should not need to use two different versions at the same time in your application. Is there a particular reason why your app is dependent on 1.9 and 1.11?
