### ISSUE TITLE
Refresh token with WebIdentityTokenCredentialsProvider

### ISSUE THREAD

**Issue by bpuertolas** [aws/aws-sdk-java#2606]
## Describe the Feature

Actually there is no way to refresh the AWS credentials when using the WebIdentityTokenCredentialsProvider. (Or maybe I didn't find it?)

## Is your Feature Request related to a problem?

I use WebIdentityTokenCredentialsProvider to get IAM credential when working with EKS.
Actually, I see in the tracing tool we use, that `AWSSecurityTokenService.AssumeRoleWithWebIdentity` calls took more than 500ms in average and we would like to reduce this with a background task which refresh the token manually. 

## Proposed Solution

I don't know if it can solve the problem but actually the refresh method in the WebIdentityTokenCredentialsProvider.class doesn't do nothing. Maybe it can call `this.credentialsProvider.refresh()` instead ?

**Comment by debora-ito** [comment]
Hi @bpuertolas 

The Web Identity Token is provided by EKS in the file present in the path configured in AWS_WEB_IDENTITY_TOKEN_FILE env variable, the SDK just uses the token to make the AssumeRole call. Any token refresh request must be made from the container side. 

Let us know if this makes sense (or maybe I misunderstood the ask).

**Comment by bpuertolas** [comment]
Hi @debora-ito

Thanks for your response but I think you misunderstood the ask. I will try to be more precise.
We have an application running on EKS which communicate with DynamoDB. Sometimes, we have long calls to STS to refresh the token in a endpoint which needs to answer fast to the client. It's happening in 1% of the traces. You can find here a screenshot of the problem:
![Capture d’écran du 2021-07-21 16-47-34](https://user-images.githubusercontent.com/40265525/126510375-3739741c-b1bb-4e3a-845a-a7c36089629b.png)
We are looking for a solution to automatically refresh the token on the container side in a such way that it will never happen in a client request. First, I was thinking of calling the `refresh()` method of the CredentialProvider (the one used by dynamodb) periodically in a background task on my application. Unfortunately, It seems that the `refresh` method of the `WebIdentityTokenCredentialsProvider` class returns without doing nothing:

`    public void refresh() {}`

**Comment by debora-ito** [comment]
We are closing stale v1 issues before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so if this issue is still relevant in v2 please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
