### ISSUE TITLE
'services.s3.transfer.Upload' should extend 'AbortableTransfer'

### ISSUE THREAD

**Issue by fetherolfjd** [aws/aws-sdk-java#2611]
## Describe the Feature

The interface `com.amazonaws.services.s3.transfer.Upload` extends `com.amazonaws.services.s3.transfer.Transfer`, yet also provides an `abort` method. This should work the same as the interface `com.amazonaws.services.s3.transfer.Download` which extends `com.amazonaws.services.s3.transfer.AbortableTransfer`.

## Is your Feature Request related to a problem?

I'd like to be able to deal with both `Upload` and `Download` objects using the same code, by treating them as `AbortableTransfer`s.

## Proposed Solution

Have `Upload` extend `AbortableTransfer`.

## Describe alternatives you've considered

That you have a good reason for not extending `AbortableTransfer` that is unknown to an outsider.

## Additional Context

I am attempting to abort `Upload`s and `Download`s if there is an exception, but need to have separate code to do so since they both don't extend `AbortableTransfer`.

## Your Environment

* AWS Java SDK version used: 1.12.22
* JDK version used: 1.8.x
* Operating System and version: Win 10 and WSL 2

**Comment by fetherolfjd** [comment]
If there isn't a specific reason to not have `Upload` extend `AbortableTransfer`, I could probably get a PR up without too much trouble.

**Comment by debora-ito** [comment]
Hi @fetherolfjd,

> I'd like to be able to deal with both Upload and Download objects using the same code, by treating them as AbortableTransfers.

Can you elaborate on what exactly are the advantages of this change? 

We are focusing our work in Java SDK v2 features and, on top of that, changing the `Upload` class is a breaking change at this point, so this is a change we probably won't be making.

**Comment by fetherolfjd** [comment]
Hi @debora-ito. In my opinion, the advantage of the change would be to maintain parity between the `Upload` and `Download` interfaces.

It's perfectly understandable to not want to make further, unnecessary changes to a "legacy" library. Take care!
