### ISSUE TITLE
RDS-DB IAM AUTH Token doesn't work properly for me

### ISSUE THREAD

**Issue by Kristin0** [aws/aws-sdk-java#2617]
Hi, i just use https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html#UsingWithRDS.IAMDBAuth.Connecting.Java.AuthToken2 
this code with changed expireMinutes = "10000", then i build it with maven and use java -jar, but when i use it, a token still expires after 15 minutes, sometimes it throws an error 
```
psql: error: FATAL:  PAM authentication failed for user "test_rds"
FATAL:  pg_hba.conf rejects connection for host "10.0.4.116", user "test_rds", database "initialdb", SSL off

```
with 900 seconds it works properly, but i want it never to expire

**Comment by Kristin0** [comment]
i did some tests and noticed that it works in two variants : when i pass expireMinutes <= 900 secs it give me 15 minutes, and when i pass value > 900 it gives me error which i noticed above

**Comment by Kristin0** [comment]
when i pass 0 it expires about 6-10 minutes

**Comment by debora-ito** [comment]
@Kristin0 I don't think it will work to set the expiryMinutes for more than 900, the documentation explicitly says that the token is valid for 15 minutes and then it expires. It's a service requirement, not something you can change on the client side.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html
