### ISSUE TITLE
Getting UnsupportedOperationException while trying to insert Map <String, List<Object>>

### ISSUE THREAD

**Issue by NeeleshJaiswal** [aws/aws-sdk-java#2618]
While following the document performing CRUD operation for personal project, facing some issues while inserting data to DynamoDB

## Describe the issue
    I am new to use dynamoDB while performing the CRUD operation where I am just trying to insert Map object to DB

Slot.java

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public class  Slot {

      @DynamoDBHashKey(attributeName = "slotId")
      @DynamoDBAutoGeneratedKey
      private String slotId;
      @DynamoDBAttribute
      private String slotTime;
      @DynamoDBAttribute
      private boolean booked;

    }

DAOImpl.java

        AmazonDynamoDB client = dynamoDBConfig.amazonDynamoDBConfig();
        DynamoDB dynamoDB = new DynamoDB(client);

        Map<String, List<Slot>> map = new HashMap<>();
        // have some data in map
        Table table = dynamoDB.getTable("slotDetails");

        Item item = new Item()
                .withPrimaryKey("slotId", "123")
                .withMap("slotDetails", slotMap);

        PutItemOutcome outcome = table.putItem(item);

## Steps to Reproduce

Above code snippet is causing issues

## Current Behavior

Giving UnsupportedOperationException

        java.lang.UnsupportedOperationException: value type: class com.entity.Slot
	   at com.amazonaws.services.dynamodbv2.document.internal.ItemValueConformer.transform(ItemValueConformer.java:100) 			   
	   ~[aws-java-sdk-dynamodb-1.12.1.jar:na]
	  at com.amazonaws.services.dynamodbv2.document.internal.ItemValueConformer.transform(ItemValueConformer.java:87) 
	   ~[aws-java-sdk-dynamodb-1.12.1.jar:na]
	   at com.amazonaws.services.dynamodbv2.document.internal.ItemValueConformer.transform(ItemValueConformer.java:96) 
	   ~[aws-java-sdk-dynamodb-1.12.1.jar:na]
	   at com.amazonaws.services.dynamodbv2.document.Item.withMap(Item.java:900) ~[aws-java-sdk-dynamodb-1.12.1.jar:na]
	   at com.repository.SlotRepository.addSlot(SlotRepository.java:49) ~[classes/:na]

## Your Environment

* AWS Java SDK version used: 1.12.1
* JDK version used: 1.8
* Operating System and version: windows 10

**Comment by debora-ito** [comment]
Hi @NeeleshJaiswal thank you for reaching out. 

In the Slot class I see you're using annotations like `@DynamoDBHashKey` and `@DynamoDBAttribute`, this indicates that you want to use DynamoDBMapper, which is a library with a high level of abstraction. But in the DAOImpl code snippet you are using the low-level AmazonDynamoDB client, they have different interfaces. To use DynamoDBMapper you need to use the DynamoDBMapper client, it would look something like this:

```
AmazonDynamoDB client = AmazonDynamoDBClientBuilder.standard().build();
DynamoDBMapper mapper = new DynamoDBMapper(client);

Slot slot = new Slot();
slot.setSlotId("id1");
slot.setSlotTime("11:59");
mapper.save(slot);
```
The example adds a single slot, but you can change the code to make it add a Map.

Please read the documentation in the DynamoDB Developer Guide, it explains the DynamoDBMapper concept and it has lots of code examples - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html
