### ISSUE TITLE
Presigned URL for other services than S3

### ISSUE THREAD

**Issue by vietthang** [aws/aws-sdk-java#2619]
First, sorry if this is wrong place to ask this question.

I'm working on a problem that need to pass secret to lambda function at runtime. 

Currently I'm using SSM parameter store for secret storage and want to pass the secret to lambda runtime, but I don't want to include AWS SDK in lambda function.

I wonder if there is presigned URL mechanism for other services than S3 (in my case is SSM parameter store), it would be perfect for my use case. I tried to research but found nothing.

Thanks a lot

**Comment by debora-ito** [comment]
Besides S3 we have Polly - https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/polly/presign/AmazonPollyPresigners.html

Did a quick search and I don't see presigners for SSM. If you want to try and write your own to get unblocked, you can take a look at the implementation of [AmazonS3Client](https://github.com/aws/aws-sdk-java/blob/1c94d1504753629995764231a311f787d42a9c8c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3458) and [AmazonPollyPresigner](https://github.com/aws/aws-sdk-java/blob/1c94d1504753629995764231a311f787d42a9c8c/aws-java-sdk-polly/src/main/java/com/amazonaws/services/polly/presign/AmazonPollyPresigners.java) as example.
