### ISSUE TITLE
AmazonKinesisFirehoseClientBuilder sometimes take too long to process

### ISSUE THREAD

**Issue by t-tien** [aws/aws-sdk-java#2621]
## Describe the bug

I'm using aws-sdk-java version 1.12.22 in Kotlin and it's `AmazonKinesisFirehoseClientBuilder` to put my log to AWS Firehose in ap-northeast-1 region. Sometimes my logs are succeed straightaway putted in approximately 100 milliseconds, but other times they take several seconds or even minutes to complete.

## Expected Behavior

Log put shouldn't take too long to process, it effected to my system peformance.

## Current Behavior

Almost of my requests is completed in about 100 milliseconds, but sometimes they take too long to complete. And it happened randomly.

## Steps to Reproduce

- My `build.gradle`:
  ```
  // kinesis
  // https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-kinesis
  implementation "com.amazonaws:aws-java-sdk-kinesis:1.12.22"   
  ```
- My `FirehoseClient.kt`
```
package clients.kinesisFirehose

import com.amazonaws.ClientConfiguration
import com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClientBuilder
import com.amazonaws.services.kinesisfirehose.model.PutRecordRequest
import com.amazonaws.services.kinesisfirehose.model.Record
import util.logger
import java.nio.ByteBuffer

class FirehoseClient {
    private val logger by logger()

    private val client = AmazonKinesisFirehoseClientBuilder
        .standard()
        .withClientConfiguration(ClientConfiguration().withMaxErrorRetry(10))
        .build()

    fun putRecord(data: ByteArray, deliveryStreamName: String) {
        val record = Record().withData(ByteBuffer.wrap(data))
        val request = PutRecordRequest().withDeliveryStreamName(deliveryStreamName).withRecord(record)
        val putRecordBegin = System.nanoTime()
        this.client.putRecord(request)
        val putRecordTime = (System.nanoTime() - putRecordBegin).toDouble()/1000000
        logger.info("Time of put record by AmazonKinesisFirehoseClientBuilder: $putRecordTime ms")
    }
}
```

- And then I call `putRecord` method to put my log to Firehose.

## Possible Solution

I've read [this answer](https://stackoverflow.com/a/59100405/11123483) and change `AmazonKinesisFirehoseClientBuilder` to `AmazonKinesisFirehoseAsyncClientBuilder ` but it still happen to me. 

## Your Environment

* AWS Java SDK version used: 1.12.22
* JDK version used: jdk8
* Kotlin version used: 1.5.0
* Ktor version used: 1.6.1

**Comment by debora-ito** [comment]
@t-tien response latency can have several causes, and some causes like networking and service side latency we don't really have much control over. It can also be related to the input size, but all these are mostly guesses.

Are you able to identify which step of the request/response process it is taking longer? You can use the client-side metrics to have more insights on the application, you can check these pages for more info:
- Dev guide: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/generating-sdk-metrics.html
- Blog post: https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/

**Comment by t-tien** [comment]
@debora-ito
Thanks for your response.
I've enabled  client-side metrics to see what makes my requests take too long time, and this is my metrics
![Screen Shot 2021-08-12 at 11 35 09](https://user-images.githubusercontent.com/30063599/129129936-29ce99c4-f963-4610-9910-4b6bcc873061.png)

As you can see, ClientExecuteTime, HttpRequestTime and HttpClientReceiveResponseTime of KinesisFirehose takes too long time to process (about 11 seconds). In the normal case, them take about 100 milliseconds to complete, but sometimes it's become to long.

If you have any idea about what happened, please tell me.
Thank you!

**Comment by t-tien** [comment]
@debora-ito 
I'm watched for an another request, and it same to above. ClientExecuteTime, HttpRequestTime and HttpClientReceiveResponseTime of KinesisFirehose takes too long time to process. 

Are you have any idea about what happened? 

![Screen Shot 2021-08-16 at 11 41 59](https://user-images.githubusercontent.com/30063599/129504570-4ffb035a-7807-4932-95ac-e2c067176a55.png)

**Comment by debora-ito** [comment]
@t-tien do you have the `HttpClientGetConnectionTime` values for those calls? Even better if you can provide all the other metrics for the problematic calls.

You said that those delays happen randomly, what's the volume of operations in your application? How often do you see those latency issues?

**Comment by debora-ito** [comment]
@t-tien I'm sorry but I lost track of this after a long time. Are you still experiencing the high latency? 5 out of 70000 requests seems a small amount, it may be attributed to network connectivity.
