### ISSUE TITLE
In case of connection time out in AWS s3 java sdk, should retry upto configured num of time (default 3 times). for me after one time failure next time it will retry then it will stop, actually I configured with  ClientConfiguration class also, still retry is not working..

### ISSUE THREAD

**Issue by satishyc** [aws/aws-sdk-java#2625]
## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
@satishyc please provide the fields we ask in the issue template, specially a reproducible code snippet and your environment info.
