### ISSUE TITLE
Remove profile prefix warning log message

### ISSUE THREAD

**Issue by Slooz** [aws/aws-sdk-java#2631]
The SDK spams this log message at the warn level on application start up:
> 2021-08-24 13:27:54.322  WARN 74651 --- [           main] c.a.a.p.i.BasicProfileConfigLoader       : Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.

A warning should indicate that an application has encountered some kind of unexpected or undesired state, and that the user should take some kind of action. AWS tooling [documents](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) and expects the `profile` prefix, so the SDK shouldn't log a warning.

The SDK shouldn't log this at the info level either, because most people don't care because they don't use the SDK with profiles.

## Proposed Solution
The SDK shouldn't log this message, or the SDK should only log it at the debug or trace level. AWS should document this issue elsewhere.

## Additional Context
This useless log annoys many people:
https://github.com/aws/aws-sdk-java/issues/1707

## Your Environment

* AWS Java SDK version used: 1.11.1034
* JDK version used: 11
* Operating System and version: macOS Catalina 10.15.7

**Comment by millems** [comment]
Today's release should hopefully resolve this issue. The SDK will now fall back to "profile X" if there is no "X" profile defined and the SDK is configured to look for profile X.
