### ISSUE TITLE
PutObjectRequest fails for the bucket with Object Lock and default retention enabled 

### ISSUE THREAD

**Issue by amangoel49** [aws/aws-sdk-java#2634]
Content-MD5 header is not getting set for `putObject` operations.

## Describe the bug
According to the [documentation](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/ObjectMetadata.java#L575) S3 client should populate the value of this field automatically but it is not working as expected. I get below exception -

`com.amazonaws.services.s3.model.AmazonS3Exception: Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters`

I am using [putObject](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1747) method to upload files to an S3 Bucket with Locking enabled by default.

```
 /**
     * <p>
     * Sets the base64 encoded 128-bit MD5 digest of the associated object
     * (content - not including headers) according to RFC 1864. This data is
     * used as a message integrity check to verify that the data received by
     * Amazon S3 is the same data that the caller sent. If set to null,then the
     * MD5 digest is removed from the metadata.
     * </p>
     * <p>
     * This field represents the base64 encoded 128-bit MD5 digest digest of an
     * object's content as calculated on the caller's side. The ETag metadata
     * field sometimes (but not always) represents the hex encoded 128-bit MD5 digest as computed by Amazon
     * S3. See the documentation at {@link #getETag()} for more information on what the ETag field represents.
     * </p>
     * <p>
     * The Amazon Web Services S3 Java client will attempt to calculate this field automatically
     * when uploading files to Amazon S3.
     * </p>
     *
     * @param md5Base64
     *            The base64 encoded MD5 hash of the content for the object
     *            associated with this metadata.
     *
     * @see ObjectMetadata#getContentMD5()
     */
    public void setContentMD5(String md5Base64) {
        if(md5Base64 == null){
            metadata.remove(Headers.CONTENT_MD5);
        }else{
            metadata.put(Headers.CONTENT_MD5, md5Base64);
        }

    }
```

[AmazonS3Client](https://github.com/aws/aws-sdk-java/blob/c0d6216f44190ea8721a235b836b81bcae01c07c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1827) does not set Content-MD5 header for putObject request. 

There is a [similar issue logged ](https://github.com/aws/aws-sdk-java/issues/2052)but that refers to S3 Encryption Client. 

## Expected Behavior
Content-MD5 header should have been populated.

## Steps to Reproduce
- Create a S3 Bucket with locks enabled by default.
- Enable default retention.
- Upload an object using `AmazonS3Client.putObject(bucketName, key, in, objectMetadata)`

## Your Environment

* AWS Java SDK version used: 1.11.1034
* JDK version used: 11
* Operating System and version: ubuntu 18

**Comment by debora-ito** [comment]
Hi @amangoel49 thank you for reaching out.

The SDK does calculate the Content-MD5 in `putObject` but not when an InputStream is used.

As a workaround you can use the constructor that takes a File as attribute and the client will calculate the Content-MD5; or 
you can calculate the MD5 and provide it in the metadata.

As mentioned in https://github.com/aws/aws-sdk-java/issues/1936 that is referenced in the issue with the Encryption Client, the team is concentrating the development efforts in the Java SDK v2, so this has low chance to be changed here in V1. Note that we have a similar ask in v2 though: https://github.com/aws/aws-sdk-java-v2/issues/2155

**Comment by amangoel49** [comment]
Constructor with File as an attribute limits from providing additional metadata. I'll go ahead with computing MD5 on my end only.
Can you point me to the code where using a File attributed constructor generates MD5 hash. I couldn't find any such operation happening in SDK.

**Comment by amangoel49** [comment]
SDK exposes ways to generate MD5 hash, `Md5Utils.md5AsBase64(file)` worked for me.

**Comment by debora-ito** [comment]
Glad that worked out for you. Going ahead and closing this.
