### ISSUE TITLE
Step Function Builder is missing intrinsic functions

### ISSUE THREAD

**Issue by andresvia** [aws/aws-sdk-java#2637]
It looks like there is no fluent way of writing `States.Format` and other intrinsic functions.

Example: 

```
{
  "Greeting.$" : "States.Format('Hello, {} {}', $.firstName, $.lastName)"
}
```

## Describe the Feature

To build expressions with intrinsic functions I need to manually concatenate strings. I ended up writing something like this:

```
    private static Entry<String, String> statesFormatIntoVariable(String variable, String formatString, String ... args) {
        String formatArgs = String.join(", ", args);
        return entry(variable.concat(".$"), String.format("States.Format('%s', %s)", formatString, formatArgs));
    }
```

using:

```
statesFormatIntoVariable("Greetings", "Hello, {} {}", "$.firstName", "$.lastName")
```

Which is very deficient and (very) far from perfect, first `'` should be escaped as `\'` for `formatString`, sending `,` to `args` will trip the whole thing. If those validations are put into the Step Function Builder, I wouldn't need to wait to actually use the rendered state machine to check it's validity, like invalid paths like `$.my-path`, etc.

## Is your Feature Request related to a problem?

No.

## Additional Context

I've written States.Format with bad syntax, forgot to add `.$` to the "variables", used invalid paths which are discovered to be bad very late, etc.

## Your Environment

* AWS Java SDK version used:

`compile group: 'com.amazonaws', name: 'aws-java-sdk-stepfunctions', version: '1.+'`

* JDK version used:

11

* Operating System and version:

Mac OS X Big Sur

**Comment by debora-ito** [comment]
@andresvia to be able to help you out I need more context on the problem. Can you please elaborate on what you're trying to do and what you've done so far? Please provide your environment config too.

We ask all those info in the form of a template:

```
<!--- Provide a general summary of the issue in the Title above -->

## Describe the Feature
<!--- A clear and concise description of the feature you are proposing -->

## Is your Feature Request related to a problem?
<!--- A description of the issue, e.g. I'm always frustrated when... -->

## Proposed Solution
<!--- Not required, but suggest how to implement the addition or change -->

## Describe alternatives you've considered
<!--- Any alternative solutions or features you've considered -->

## Additional Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details as possible about your environment -->
* AWS Java SDK version used:
* JDK version used:
* Operating System and version:
```

**Comment by debora-ito** [comment]
Hi @andresvia I'm sorry for taking so long to send a reply.

An expression builder for Intrinsic Functions would be a nice utility to have indeed. We don't have it right now because most of the SDK code is auto-generated based on service client models, and since intrinsic functions are not modeled it would require to be a handwritten library/utility tool.

The team focus is in working in new features for the Java SDK v2, so this has low chance of being implemented in SDK v1. Let me know if you'd like to see this supported in the SDK v2, if so I can add this request to the v2 repo.
