### ISSUE TITLE
InstanceProfileCredentialsProvider Not working, throwing 401 Unauthorized

### ISSUE THREAD

**Issue by waqarMohammed** [aws/aws-sdk-java#2640]
## Describe the issue
I am trying to get credentials to connect my AEM Application to EC2 Instance through InstanceProfileCredentialsProvider but when i try to build Amazon s3 client, I am getting a 401 Unauthorized exception

## Steps to Reproduce
The code I am using to Connect and build Amazons3client

    ```
public static AmazonS3 getAmazonS3Client(final Regions region) {


        return AmazonS3ClientBuilder.standard().withCredentials(new InstanceProfileCredentialsProvider(false))
                .withRegion(region).enableForceGlobalBucketAccess().withPathStyleAccessEnabled(true)
                .build();

    }
```

EXCEPTION FROM ERROR LOGS :
```
*ERROR* [pool-55-thread-1] com.amazonaws.auth.InstanceProfileCredentialsProvider Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null)
com.amazonaws.AmazonServiceException: Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null)
	at com.amazonaws.internal.EC2CredentialsUtils.handleErrorResponse(EC2CredentialsUtils.java:154)
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:119)
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:77)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider$InstanceMetadataCredentialsEndpointProvider.getCredentialsEndpoint(InstanceProfileCredentialsProvider.java:156)
	at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:121)
	at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider$1.run(InstanceProfileCredentialsProvider.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Your Environment

* AWS Java SDK version used: 1.11.155
* JDK version used: 1.8
* Operating System and version: Red Hat BYOL Linux

**Comment by prasad-sonawane** [comment]
Hi Team,

@waqarMohammed and me work together and have been facing this issue at present.
For above issue we already worked with AWS support but per them they are not able to provide code assistance and directed us to open a thread here (Github) for current issue. We were told that this is official AWS SDK group and we can seek inputs here.

Can someone help with this? Let us know if more information is needed.

Thanks!

**Comment by debora-ito** [comment]
Hi @waqarMohammed,  @prasad-sonawane sorry for the delay in reply.

The error indicates that the SDK tried to connect to the Instance Metadata endpoint but got an `Unauthorized` error in return.

The SDK version you are using `1.11.155` is more than 4 years old. Is is possible for you to try a more recent version of the SDK and check if you still see the issue? 

The EC2 credential process was rewritten at some point (the EC2CredentialsFetcher class doesn't exist in the latest versions, for example). If you see the same issue in recent versions, we can try to reproduce it.

**Comment by prasad-sonawane** [comment]
Hi @debora-ito Thank you for your response!
We did upgrade AWS dependencies to version as suggested : **1.12.66**
This started working fine for us with minor changes in API client. We are now able to successfully get our application upload files to s3. We are still unit testing for end to end scenarios.

Based on the recommendation from AWS docs, we have tried to reuse / use singleton instance of InstanceProfileCredentialsProvider in our code as earlier we were getting error for one of the file out of 4 files. 
Sample code below:

`    
   private static InstanceProfileCredentialsProvider provider;

    /**
     * Helper function to get InstanceProfileCredentialsProvider instance.
     * Maintains singleton instance to leverage reuse across multiple calls.
     * 
     * @return InstanceProfileCredentialsProvider
     */
    public static InstanceProfileCredentialsProvider getInstanceProfileCredentialsProvider() {
    	if(provider == null) {
    		provider = new InstanceProfileCredentialsProvider(false);
    	}
    	return provider;
    }

    /**
     * Helper function to get Amazon S3 client.
     *
     * @param region for AWS region
     * @return instance of Amazon S3 client
     */
    public static AmazonS3 getAmazonS3Client(final Regions region) {
        LOGGER.info("Entering getAmazonS3Client method of CommonUtils");

        return AmazonS3ClientBuilder.standard()
        		.withCredentials(getInstanceProfileCredentialsProvider())
                .withRegion(region).enableForceGlobalBucketAccess().withPathStyleAccessEnabled(true)
                .build();
    }

    /**
     * Helper function to get Amazon CloudFront client.
     * 
     * @return instance of AmazonCloudFront
     */
    public static AmazonCloudFront getAmazonCloudFrontClient() {
        LOGGER.info("Entering getAmazonCloudFrontClient method of CommonUtils");

        return AmazonCloudFrontClientBuilder.standard()
        		.withCredentials(getInstanceProfileCredentialsProvider())
        		.build();
    }`'

Can you suggest if this implementation approach is fine?

Thanks a lot for your inputs!

**Comment by debora-ito** [comment]
The code should be fine, just note that setting false in `InstanceProfileCredentialsProvider(false)` means that the credentials won't be automatically refreshed in the background. Instance profile credentials are temporary, so you'll need to manually call refresh after they expire in this case.

I'll go ahead and close this, feel free to reach out if you have any more questions.
