### ISSUE TITLE
AmazonS3Client getObjectMetadata always returns null value for contentMD5

### ISSUE THREAD

**Issue by vpawar-tibco** [aws/aws-sdk-java#2645]
I am calling `com.amazonaws.services.s3.AmazonS3Client.GetObjectMetadata()` to get the ObjectMetadata. But its `getContentMD5()` method always returns null. 
While uploading the object to S3 bucket, the content MD5 is set in ObjectMetadata `metadata.setContentMD5(contentMD5);` also it is added separately in user metadata with key `x-amz-meta-md5checksum`. The one in user metadata is available in `GetObjectMetadata()` output but `getContentMD5()` still returns null.

* AWS Java SDK version used: 1.11.967
* JDK version used: JDK8
* Operating System and version: Windows 10

**Comment by ashishdhingra** [comment]
Hi @vpawar-tibco,

Good afternoon.

Thanks for posting guidance question. The [AmazonS3Client.getObjectMetadata()](https://github.com/aws/aws-sdk-java/blob/ebe12dbe6c9a3450b1199f958da115d65047609b/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1359) invokes the [HeadObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html) service operation. If you examine the `HeadObject` API reference page, it does not return ContentMD5 in the response. Hence, it is not populated in `ObjectMetadata`. Hope this helps.

Thanks,
Ashish

**Comment by vpawar-tibco** [comment]
@ashishdhingra Thanks for your response. It is bit misleading and creates confusion. You expect the `HeadObject` to return `ContentMD5` when same is set while uploading the object.
Is this something which will be fixed in future?

**Comment by ashishdhingra** [comment]
Closing this in favor of https://github.com/aws/aws-sdk/issues/89.
