### ISSUE TITLE
Support Uploading to S3 using an OutputStream

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-sdk-java#2647]
## Describe the Feature

Provide the ability for the S3 client to expose an OutputStream that can be written to in order to write to a S3 object.

It appears that it's a fairly normal idiom for a class to expose a save/write method that takes an OutputStream parameter in order to allow the class to serialize something to a stream.

Note this was previously discussed a few years ago via https://github.com/aws/aws-sdk-java/issues/1139, however the discussion never really went anywhere, and no one really tried to justify this as a feature. I've created this as a new Issue as the last issue was treated as a request for guidance rather than a feature request.

## Is your Feature Request related to a problem?

I've found in two Java Lambdas I've recently been working on, I have a component that wants to write its output to an OutputStream. I'm having to hack around the fact S3 only will accept an InputStream by using the workaround shown at https://stackoverflow.com/a/36961688/792238.

One is writing an image to S3 using [ImageIO#write](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/imageio/ImageIO.html#write(java.awt.image.RenderedImage,java.lang.String,java.io.OutputStream)).

The other is writing a PDF document using [PDDocument#save](https://pdfbox.apache.org/docs/2.0.13/javadocs/org/apache/pdfbox/pdmodel/PDDocument.html#save-java.io.OutputStream-).

Currently the hack looks something like:

```
    public static class CopyStream extends ByteArrayOutputStream {
        public CopyStream() { super(); }

        public InputStream toInputStream() {
            return new ByteArrayInputStream(this.buf, 0, this.count);
        }

        public int size() {
            return this.count;
        }
    }

[...]

        PDFDocument outputDocument = generateDocument();
        CopyStream outputStream = new CopyStream();
        outputDocument.save(outputStream);
        outputDocument.close();
        InputStream inputStream = outputStream.toInputStream();
        long size = outputStream.size();
        // Do S3 upload using inputStream and size
```

## Proposed Solution

I'm not super familiar with Java streams and the correct idioms to use, but I'm guessing that we'd want usage to be something like this:

```
        PDFDocument outputDocument = generateDocument();
        PutObjectRequest putRequest = buildS3PutRequest();

        try (OutputStream outputStream = S3_CLIENT.putObjectOutputStream(putRequest)) {
            outputDocument.save(outputStream);
            outputDocument.close();
        }
```

## Describe alternatives you've considered

The only other alternative I can see is the kind of hack I'm currently having to use.

## Your Environment

* AWS Java SDK version used: 2.17.44
* JDK version used: 11
* Operating System and version: AWS Lambda

**Comment by debora-ito** [comment]
Hi @SamStephens apologies for taking so long to get a reply.

The Java SDK team is focusing efforts in Java v2 feature work, so even though this is an interesting feature it has very low chance to get implemented in v1. If you'd like to request it for the Java SDK v2 TransferManager I can transfer this feature request to the v2 repo.

**Comment by SamStephens** [comment]
> Hi @SamStephens apologies for taking so long to get a reply.
> 
> The Java SDK team is focusing efforts in Java v2 feature work, so even though this is an interesting feature it has very low chance to get implemented in v1. If you'd like to request it for the Java SDK v2 TransferManager I can transfer this feature request to the v2 repo.

@debora-ito apologies for taking so long to reply. I meant to create this against the V2 repository, it relates to the V2 SDK.

I've duplicated this issue in that repository as https://github.com/aws/aws-sdk-java-v2/issues/3131, and will close this issue.
