### ISSUE TITLE
No way to add custom ProgressListener to `TransferManager::uploadFileList`

### ISSUE THREAD

**Issue by Khakov** [aws/aws-sdk-java#2650]
After reading the documentation and checking the source code I cannot find the way to put custom `ProgressListener`
## Describe the Feature
It would be great to add possibility to put custom progress listeners to `TransferManager::uploadFileList` method
## Proposed Solution
There is a part of code with creating, but there is no way to provide custom listeners. Maybe is it possible to add some parameters (Collection to provide listeners to TransferManager) or provide PutRequest builder?

```
public MultipleFileUpload uploadFileList(...) {
 /* This is the hook for adding additional progress listeners */
        ProgressListenerChain additionalListeners = new ProgressListenerChain();
        TransferProgress progress = new TransferProgress();
        /*
         * Bind additional progress listeners to this
         * MultipleFileTransferProgressUpdatingListener to receive
         * ByteTransferred events from each single-file upload implementation.
         */
        ProgressListener listener = new MultipleFileTransferProgressUpdatingListener(
                progress, additionalListeners);
               
}
```

## Your Environment
* AWS Java SDK version used: aws-java-sdk-s3:1.11.987
* JDK version used: 1.8
* Operating System and version: CentOS 7

**Comment by debora-ito** [comment]
Super late reply in here @Khakov, I'm sorry for that.

You can add ProgressListeners to the MultipleFileUpload that is returned from that method, is that what you're looking for?

```java
TransferManager tm = TransferManagerBuilder.defaultTransferManager();
        
MultipleFileUpload myUpload = tm.uploadFileList(bucketName, keyPrefix, directory, fileList);
myUpload.addProgressListener(myProgressListener);
```
