### ISSUE TITLE
AmazonCloudwatch APIs failed for certain Regions using the SDK

### ISSUE THREAD

**Issue by kabathla** [aws/aws-sdk-java#2655]
## Exception for US_ISO type Regions added in new AWS SDK 
It has been found that there are new Regions added in the new AWS SDK which were not present in the previous versions.
for example:
In version 1.11.611 version: http://45.136.31.39/artifacts/com.amazonaws/aws-java-sdk-core/1.11.611/source-code/com/amazonaws/regions/Regions.java there are no regions of US_ISO type. 

however, in 1.12.15 version: http://45.136.31.39/artifacts/com.amazonaws/aws-java-sdk-core/1.12.15/source-code/com/amazonaws/regions/Regions.java, we have few new regions added.
The regions which are causing issues are:
```
US_ISO_EAST_1
US_ISOB_EAST_1
US_ISO_WEST_1
```
The exception caused by these regions is:
`com.amazonaws.SdkClientException: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
and Sometimes, I am getting:
`com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to monitoring.us-iso-west-1.c2s.ic.gov:443 [monitoring.us-iso-west-1.c2s.ic.gov/198.81.130.253] failed: Connect timed out error message Unable to execute HTTP request: Connect to monitoring.us-iso-west-1.c2s.ic.gov:443 [monitoring.us-iso-west-1.c2s.ic.gov/198.81.130.253] failed: Connect timed out cause org.apache.http.conn.ConnectTimeoutException: Connect to monitoring.us-iso-west-1.c2s.ic.gov:443 [monitoring.us-iso-west-1.c2s.ic.gov/198.81.130.253] failed: Connect timed out
`
## Expected Behavior
The API functionality should work for all regions without exceptions

## Current Behavior
I am getting exceptions (one of them) as 

1. `com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to monitoring.us-iso-west-1.c2s.ic.gov:443 [monitoring.us-iso-west-1.c2s.ic.gov/198.81.130.253] failed: Connect timed out error message Unable to execute HTTP request: Connect to monitoring.us-iso-west-1.c2s.ic.gov:443 [monitoring.us-iso-west-1.c2s.ic.gov/198.81.130.253] failed: Connect timed out cause org.apache.http.conn.ConnectTimeoutException: Connect to monitoring.us-iso-west-1.c2s.ic.gov:443 [monitoring.us-iso-west-1.c2s.ic.gov/198.81.130.253] failed: Connect timed out`

2. `com.amazonaws.SdkClientException: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
`WARN  [2021-10-06 11:44:14,154] ec2: cannot connect to rds in region: US_ISO_EAST_1 for: master using credentials: ***
! sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
! at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
! at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
! at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:433)
! ... 68 common frames omitted
! Causing: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:438)
! at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:305)
! at java.base/sun.security.validator.Validator.validate(Validator.java:264)
! at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
! at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
! at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
! ... 63 common frames omitted
! Causing: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
! at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
! at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
! at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
! at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
! at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
! at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
! at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
! at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
! at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
! at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
! at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
! at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
! at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
! at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
! at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
! at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
! at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
! at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
! at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:567)
! at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
! at com.amazonaws.http.conn.$Proxy155.connect(Unknown Source)
! at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
! at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
! at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
! at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1331)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
! ... 34 common frames omitted
! Causing: com.amazonaws.SdkClientException: Unable to execute HTTP request: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
! at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1728)
! at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1695)
! at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1684)
! at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRole(AWSSecurityTokenServiceClient.java:488)
! at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRole(AWSSecurityTokenServiceClient.java:457)`

## Steps to Reproduce
[RDSData.zip](https://github.com/aws/aws-sdk-java/files/7310869/RDSData.zip)
The gradle project is attached as zip which is used to fetch metrics for RDS and in my AWS configurations on MAC, I have set up the region as us-iso-east-1.

## Context

The product uses the AWS SDK to fetch relevant metrics per region

## Your Environment

* AWS Java SDK version used: 1.12.15
* JDK version used: openjdk 13.0.2 2020-01-14
* Operating System and version: MacOS Big Sur, 11.6 version

**Comment by debora-ito** [comment]
Hi @kabathla thank you for reaching out.

Those regions are part of the U.S. Government program and Intelligence Community infrastructure. Unlike the other regions like us-west-1, to be able to use them you need to onboard the program. You can read a little more about it in the Government solutions page - https://aws.amazon.com/federal/us-intelligence-community/
