### ISSUE TITLE
AWS SQS sendMessageAsync future sometimes never completes 

### ISSUE THREAD

**Issue by deepalii** [aws/aws-sdk-java#2661]
### Describe the bug

While calling `sendMessageAsync` function of aws sdk we get a Future Object. If we try to get the result from future by calling get function like this `future.get(15, TimeUnit.SECONDS);` sometimes there is a time out giving the exception `java.util.concurrent.TimeoutException at java.util.concurrent.FutureTask.get(FutureTask.java:205)`. 

### Expected behavior

Sending messages with `sendMessageAsync` should return a Future that eventually completes.

### Current behavior

Sending several thousands of messages to sqs via sendMessageAsync can lead to a few calls to fail and eventually failing to publish.

### Steps to Reproduce

AmazonSQSAsyncClient createAmazonSQSAsyncClient() {
    return new AmazonSQSAsyncClient(new DefaultAWSCredentialsProviderChain(), new ClientConfiguration(), Executors.newCachedThreadPool(THREAD_FACTORY));
 }

public Future<SendMessageResult> postMessage(final String shardId, final String message) {
sqs = createAmazonSQSAsyncClient();
String url = getQueueURL(id);
SendMessageRequest smr = new SendMessageRequest(url, message);
return sqs.sendMessageAsync(smr);

 }

### AWS Java SDK version used

1.11.543

### JDK version used

8u172

### Operating System and version

Linux in AWS

**Comment by deepalii** [comment]
Hello @aaoswal . Thanks for the suggestion. The thing I want to point out here is that we use the SDK in one of our worker services where most of the sendMessageAsync finishes in a few ms there are a few calls that do not complete even in 15 seconds and neither gives any other exception in those 15 seconds. Since we do not get the details on the reason for such a delay we are unable to judge what to do in such scenarios and have doubts if extending timeout or retry on the same thread would work. There was a similar bug https://github.com/aws/aws-sdk-java-v2/issues/1207 in aws sdk 2 but it was for Netty based http client. I was wondering if there are some edge cases here that we might be missing.

**Comment by aaoswal** [comment]
Hi @deepalii,
The response received may be taking longer than the 15 seconds for reasons outside the scope of the SDK. Some common reasons might be service processing time and network connectivity issues. How often are you seeing the `timeout exception` in such cases?

If you want to investigate it further, you can try removing the 15 second timeout and check if the response is received at all, in the first place.

You can also enable client-side metrics for [obtaining more insights on your application performance](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/generating-sdk-metrics.html).

Hope this helps!

Thanks,
Anish.
