### ISSUE TITLE
Exception occurred while processing the job Unable to complete transfer: Task java.util.concurrent.FutureTask@1f446d02 rejected from java.util.concurrent.ThreadPoolExecutor@114e3f2

### ISSUE THREAD

**Issue by SouvikDasgupta** [aws/aws-sdk-java#2666]
### Describe the issue

I am facing this issue while trying to upload a file to s3 using transfer manager.

"Exception occurred while processing the job Unable to complete transfer: Task java.util.concurrent.FutureTask@1f446d02 rejected from java.util.concurrent.ThreadPoolExecutor@114e3f2[Shutting down, pool size = 5, active threads = 5, queued tasks = 0, completed tasks = 0]"

Upload upload = transferManager.upload(new PutObjectRequest(s3Uri.getBucket(), s3Uri.getKey(), new FileInputStream(sourceFile), objectMetadata));
                upload.addProgressListener(uploadFileRequest.getProgressListener());
                UploadResult uploadResult = upload.waitForUploadResult();
                AmazonS3 s3Client = getS3Client(credentialsForJob);
                s3Client.setObjectAcl(s3Uri.getBucket(), s3Uri.getKey(), CannedAccessControlList.BucketOwnerFullControl);
            } catch (InterruptedException | FileNotFoundException e) {
                throw new RuntimeException(String.format("Exception occurred while uploading the file from %s to %s - %s", sourceFile.getAbsolutePath(), targetObjectPath, e.getMessage()), e);
            } finally {
                transferManager.shutdownNow(true);
            }

### Steps to Reproduce

Na

### Current behavior

NA

### AWS Java SDK version used

<version>1.11.766</version>

### JDK version used

15

### Operating System and version

amazon linux

**Comment by debora-ito** [comment]
Hi @SouvikDasgupta, 
note that the `finally` clause is always executed, even in non-exceptional scenarios, meaning you are always shutting down the TransferManager after the upload. 
So the error is probably due to the `transferManager` instance being reused by other parts of the code.
