### ISSUE TITLE
AmazonDynamoDB / DynamoDBMapper retries are considered as new requests

### ISSUE THREAD

**Issue by weierstrass** [aws/aws-sdk-java#2667]
### Describe the issue

Hi,

we have a problem when write requests through the DynamoDBMapper times out on the client side. We have set up the Dynamo client to retry in these cases. The problem is that even though the first request timed out, the Dynamo server still processed the request and when the retry comes, it fails with a `ConditionalCheckFailedException` since we have some conditional write checks like: no entry should already exist on creation and we also have optimistic locking enabled for updates.

How are these cases supposed to be handled? Is there a way to configure the client to include e.g. an idempotency token so the server can detect that it is a retry of a previous request? With the [transactional API](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html) retries seems to work better when the ClientRequestToken is present.

### Steps to Reproduce

```
ClientConfiguration clientConfiguration = new ClientConfiguration()
            .withConnectionTimeout(CONNECTION_TIMEOUT)
            .withRequestTimeout(REQUEST_TIMEOUT)
            .withRetryPolicy(PredefinedRetryPolicies.getDynamoDBDefaultRetryPolicyWithCustomMaxRetries(MAX_ERROR_RETRIES));
         
AmazonDynamoDB awsClient = AmazonDynamoDBClientBuilder.standard()
            .setClientConfiguration(clientConfiguration);
            
DynamoDBMapper mapper = new DynamoDBMapper(awsClient, ...);
```

```
ExpectedAttributeValue nonExistingId = new ExpectedAttributeValue(false);
DynamoDBSaveExpression expression = new DynamoDBSaveExpression().withExpectedEntry(PRIMARY_KEY, nonExistingId);
mapper.save(obj, expression); <-- conditional expression will fail on retry if first try times out on the client.
```

### Current behavior

1st try: Request did not complete before the request timeout configuration.

2nd try: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException

I have no easy way on the client side to tell if the write actually went through.

### AWS Java SDK version used

1.12.102

### JDK version used

openjdk version "11.0.11" 2021-04-20

### Operating System and version

OS X 11.6.1

**Comment by debora-ito** [comment]
Hi @weierstrass so sorry for taking this long to get a response. I was going through the list of guidance issues and found yours.

I can't think of an easy way to handle this case. Idempotency tokens are defined by the service when the APIs are designed, so the client will only make them available if it's in the API definition - see `ClientRequestToken` parameter in [TransactWriteItems](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html) API.

If it's an error you see frequently you can try increasing the timeout - which in the DynamoDB Mapper can be made at the client level, request-level configuration is not available - or catching the `ConditionalCheckFailedException`.
