### ISSUE TITLE
S3 bucket location api not getting locatoin name for us-east-1

### ISSUE THREAD

**Issue by nanda-kumar-office1** [aws/aws-sdk-java#2671]
### Describe the bug

When API call is made to get the bucket location, it gets an incorrect name as "US" instead of "us-east-1" for those buckets whose region happens to be "US East (N. Virginia) us-east-1"
I tested for buckets in all other regions, it gets correct names but not for the above Virginia region. This issue exists only for buckets in the Virginia region.

Here is a code

AmazonS3 s3Client = getS3ClientConnection(Regions.DEFAULT_REGION.getName());
// my-bucketname1 is a bucket present in Virginia region
String loc = s3Client.getBucketLocation("my-bucketname1");

### Expected behavior

String loc = s3Client.getBucketLocation("my-bucketname1");

Above api should return location name as "us-east-1" for those buckets whose region is in "US East (N. Virginia) us-east-1"

### Current behavior

String loc = s3Client.getBucketLocation("my-bucketname1");

Above api is returning location name as "US"  instead of "us-east-1" for those buckets whose region is in "US East (N. Virginia) us-east-1"

### Steps to Reproduce

Create a bucket in the Virginia region and try the below code.

AmazonS3 s3Client = getS3ClientConnection(Regions.DEFAULT_REGION.getName());
// my-bucketname1 is a bucket present in Virginia region
String loc = s3Client.getBucketLocation("my-bucketname1");

### AWS Java SDK version used

latest

### JDK version used

1.8

### Operating System and version

Linux

**Comment by debora-ito** [comment]
Duplicate of https://github.com/aws/aws-sdk-java/issues/1890 and https://github.com/aws/aws-sdk-java/issues/1470#issuecomment-367039990.

This is for legacy reasons. S3's GetBucketLocation API returns an empty string for the bucket location when it's located in `us-east-1`, and on the SDK's end, it replaces the empty string with "US". We cannot change this behavior now as it would break backwards compatibility.

For more info on S3 legacy endpoints, see [Virtual hosting of buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#VirtualHostingBackwardsCompatibility) in the S3 Dev Guide

**Comment by nanda-kumar-office1** [comment]
Thank you Debora.

**Comment by lekkimworld** [comment]
For the record it seems EU is also shorthand for eu-west-1
