### ISSUE TITLE
Getting "java.lang.OutOfMemoryError" when uploading a large directory to S3

### ISSUE THREAD

**Issue by kyungSong** [aws/aws-sdk-java#2676]
### Describe the issue

Hi, I'm getting the below issue and seeking some guidance in resolving it:

I'm using TransferManager to upload a large directory (300G+ give or take) to S3 bucket and getting a "java.lang.OutOfMemoryError: GC overhead limit exceeded" error. Looking at the trace stack it seems "TransferManager.doUpload" is causing the problem.

Trace Stack:

```
[AWS CodeBuild Plugin] java.lang.OutOfMemoryError: GC overhead limit exceeded
[AWS CodeBuild Plugin] 	at com.amazonaws.services.s3.transfer.TransferManager.doUpload(TransferManager.java:665) ~[aws-java-sdk-s3-1.11.1000.jar!/:na]
[AWS CodeBuild Plugin] 	at com.amazonaws.services.s3.transfer.TransferManager.uploadFileList(TransferManager.java:1921) ~[aws-java-sdk-s3-1.11.1000.jar!/:na]
[AWS CodeBuild Plugin] 	at com.amazonaws.services.s3.transfer.TransferManager.uploadDirectory(TransferManager.java:1679) ~[aws-java-sdk-s3-1.11.1000.jar!/:na]
[AWS CodeBuild Plugin] 	at com.amazonaws.services.s3.transfer.TransferManager.uploadDirectory(TransferManager.java:1627) ~[aws-java-sdk-s3-1.11.1000.jar!/:na]
[AWS CodeBuild Plugin] 	at com.amazonaws.services.s3.transfer.TransferManager.uploadDirectory(TransferManager.java:1587) ~[aws-java-sdk-s3-1.11.1000.jar!/:na]
[AWS CodeBuild Plugin] 	at com.amazonaws.services.s3.transfer.TransferManager.uploadDirectory(TransferManager.java:1551) ~[aws-java-sdk-s3-1.11.1000.jar!/:na]
---- and more lines ---
```
I checked a similar issue here ([#1271](https://github.com/aws/aws-sdk-java/issues/1271)) but it seems like the reporter had error on "listFiles" while mine is caused by "doUpload".

I also did some counting and there are about 1,000,000 files, all of them are image files that I need to upload, apart from two files (one is a single csv file for meta data on the image files and a zip file that zips the csv and images for ease of download).

I wouldn't be uploading directories as large as this regularly, but as I'm creating images and meta data per user request and a million image files are very probable requests expected from users, although may be rare.

Questions:
1. can transferManager handle large directories (~250G, sometimes a bit more)?
2. If it can't, what should I implement to handle such case? 
3. Current heap size (-xmx setting) is 2G, is this just too low for handling cases like this? or maybe the multiPartUploadThreshold is too low (currently at 1024L*1024)?
4. Any other guidance is much appreciated.

### Steps to Reproduce

upload a large (250G+) directory using TransferManger.uploadDirectory (MultiPartUpload threshold set to 1024L*1024 on TransferManager)

### Current behavior

Gets "java.lang.OutOfMemoryError: GC overhead limit exceeded" error

### AWS Java SDK version used

1.11.1000

### JDK version used

1.8.0_303

### Operating System and version

amazon linux version 2

**Comment by aaoswal** [comment]
Hi @kyungSong,
As mention in #1271, it seems like this seems to be a problem related to having the files in your directory loaded in the memory at once which is causing a huge memory overhead. It is not directly related to the function but the memory used for the operations performed on your local machine.

TransferManager should generally be able to handle large directories hence, this seems to be a memory leak problem in the code.

Could you please provide some additional information on this:
- While running the code snippet, what is your CPU and memory utilization? Is it close to 100%?
- Is this a one-off upload or something you'll be building into a service? If so, CLI might be able to handle this better.
- If this is something that you are building into a service, could you please provide a small sample code to reproduce the issue? This would help me analyze the solution for any memory leaks and see if we could solve the issue.

**Comment by kyungSong** [comment]
@aaoswal Hello, sorry for the late response. Holiday season and all.

I increased JVM heap size to 4G and it could handle this case. (Haven't tried anything more than a million files as one million image files act as the upper limit per service policy).

As for your question:
1. It was a while ago, but as far as I remember both cpu and memory utilization was around 80% ish
2. Something built into the service
3. I'll edit the code into the comment when I can

**Comment by aaoswal** [comment]
Hi @kyungSong,
Apologies for the delay but I am unable to reproduce the issue on my end. 

I would like to request you to please provide a simple java project replicating the error with necessary code for replication on my end. This would help me assist you better and provide you with an appropriate solution at a much faster pace.

Thank you so much for your patience.

Regards,
Anish.
