### ISSUE TITLE
Malformed policy (400)

### ISSUE THREAD

**Issue by makushatnik** [aws/aws-sdk-java#2678]
### Describe the bug

When I try to apply a bucket policy, created by the **Policy** class from that exact SDK, I get this:
```
' (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: 16BC4B7D916A0218; S3 Extended Request ID: 313b1a14-13cb-4e33-b6f1-4878bb5202ff; Proxy: null)
com.amazonaws.services.s3.model.AmazonS3Exception: ' (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: 16BC4B7D916A0218; S3 Extended Request ID: 313b1a14-13cb-4e33-b6f1-4878bb5202ff; Proxy: null), S3 Extended Request ID: 313b1a14-13cb-4e33-b6f1-4878bb5202ff
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
...
```
I didn't write the **Policy** class and I didn't guess it, it's a class from that official SDK. Why it doesn't work?
I know for sure that this exact policy is appropriate, I've checked it in my AWS management console. Why it does work in AWS console?
```
{
  "Version": "2012-10-17",
  "Id": "AllS3ActionsPolicy",
  "Statement": [
    {
      "Sid": "Stmt1638260692266",
      "Effect": "Allow",
      "Principal": "*",
      "Action": ["s3:*"],
      "Resource": [
        "arn:aws:s3:::first-bucket",
	"arn:aws:s3:::first-bucket/*"
      ]
    }
  ]
}
```

### Expected behavior

Bucket policy applied successfully.

### Current behavior

When I try to apply my bucket policy I get:
' (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: 16BC4B7D916A0218; S3 Extended Request ID: 313b1a14-13cb-4e33-b6f1-4878bb5202ff; Proxy: null)
com.amazonaws.services.s3.model.AmazonS3Exception: ' (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: 16BC4B7D916A0218; S3 Extended Request ID: 313b1a14-13cb-4e33-b6f1-4878bb5202ff; Proxy: null), S3 Extended Request ID: 313b1a14-13cb-4e33-b6f1-4878bb5202ff
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
...

### Steps to Reproduce

1. Start a container for tests:
```
@Container
private static final GenericContainer<?> container = new GenericContainer<>(
        "minio/minio:RELEASE.2020-07-27T18-37-02Z")
        .withCreateContainerCmdModifier((e) -> e.withName("minio-test"))
        .withExposedPorts(s3InnerPort)
        .withEnv(getEnvMap())
        .withCommand("server /data");
```
2. Setup env for tests like this:
```
@BeforeEach
public void setUp() {
        if (container == null || storageController == null) {
            log.error("Container or storageController isnt initialized");
            throw new RuntimeException("Container or storageController isnt initialized");
        }

        if (!s3.doesBucketExistV2(BUCKET_NAME)) {
            try {
                storageController.createBucket(BUCKET_NAME);
                s3.setBucketPolicy(BUCKET_NAME, getPublicPolicy());
            } catch (IOException e) {
                log.error("Creating bucket error %s", e.getMessage());
                throw new RuntimeException("Creating bucket error " + e.getMessage());
            }
        }
}
```
where s3 is **AmazonS3** class instance from that SDK:
```
@Autowired
private AmazonS3 s3;
```
3. Configure AmazonS3 bean like that:
```
@TestConfiguration
public class S3Config {

    @Value("${s3.url}")
    private String s3Url;
    @Value("${s3.port}")
    private String s3port;
    @Value("${s3.accessKey}")
    private String accessKey;
    @Value("${s3.secretKey}")
    private String secretKey;

    @Bean
    public AmazonS3 s3Client() {
        final AWSCredentials credentials = new BasicAWSCredentials(accessKey, secretKey);
        final ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");

        return AmazonS3ClientBuilder
            .standard()
            .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(s3Url + ":" + s3port,
                Regions.US_EAST_1.name()))
            .withPathStyleAccessEnabled(true)
            .withClientConfiguration(clientConfiguration)
            .withCredentials(new AWSStaticCredentialsProvider(credentials))
            .build();
    }
}
```
Actually, I don't have any Regions in my http://localhost:9009 Minio container's AWS S3 implementation.
4. Enable configuration on our test class:
```
@Slf4j
@Testcontainers
@SpringBootTest(classes = S3Config.class)
@ContextConfiguration(initializers = StorageControllerTest.Initializer.class)
public class StorageControllerTest {
...
```
5. Write a getPublicPolicy() function like this:
```
private static String getPublicPolicy() {
        Statement allowAllS3Stmt = new Statement(Statement.Effect.Allow)
            .withPrincipals(Principal.All)
            .withActions(S3Actions.AllS3Actions)
            .withResources(
                new Resource("arn:aws:s3:us-east-1::" + BUCKET_NAME),
                new Resource("arn:aws:s3:us-east-1::" + BUCKET_NAME + "/*")
            );
        allowAllS3Stmt.setId("Stmt1638260692266");
        Policy allS3ActionsPolicy = new Policy()
            .withId("AllS3ActionsPolicy")
            .withStatements(allowAllS3Stmt);
        String policyJson = allS3ActionsPolicy.toJson();
        //AWS SDK checks here that this exact policy is appropriate
        //No exceptions falling here
        try {
            Policy.fromJson(policyJson);
        } catch (IllegalArgumentException e) {
            System.out.println("Invalid policy text");
            System.out.println(e.getMessage());
        }
        return policyJson;
}
```
6. Libraries used:
```
implementation "com.amazonaws:aws-java-sdk:1.12.115"   (1.12.119 doesn't work, too)
testImplementation "org.springframework.boot:spring-boot-starter-test"
testImplementation "org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion"
testImplementation "org.junit.jupiter:junit-jupiter-params:$junitJupiterVersion"
testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion"
testImplementation "org.testcontainers:testcontainers:1.16.2"
testImplementation "org.testcontainers:junit-jupiter:1.16.2"
```
7. That's it. On the s3.setBucketPolicy(..) string falling the exception.

### Possible Solution

Check and make needed changes in the **Policy** class.

### Context

I'm trying to apply a policy to a new bucket I've created in my Docker container.
I use official Minio Docker container, which is compatible with all the AWS SDK methods.

### AWS Java SDK version used

com.amazonaws:aws-java-sdk:1.12.119

### JDK version used

17

### Operating System and version

Windows 7, Ubuntu 20.04

**Comment by debora-ito** [comment]
Hi @makushatnik Apologies for the delay in response. Thank you for the detailed report.

On a quick look I don't see anything standing out. I see your resource ARNs contain the region, but in the AWS Console the bucket ARNs have no region info (like `arn:aws:s3:::bucket_name` instad of `arn:aws:s3:us-east-1::bucket_name`), have you tried that?

Have you tried enabling the verbose wirelogs and checking how the policy is sent in the wire? You can check this page for instructions on how to enable the wirelogs: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose. If you choose to share the wirelogs here make sure to redact any sensitive information.
