### ISSUE TITLE
How to use S3 even in aws-sdk-java-v2

### ISSUE THREAD

**Issue by elixluo** [aws/aws-sdk-java#2680]
### Describe the issue

I am working on a project using aws-sdk-java-v2, I need to get notified whenever new objects are added to a S3 bucket, how can this be implemented? I saw S3 event in aws-sdk-java-v1 but I did not see it in v2. Or is there any other ways that I can implement this: when new objects are added to a S3 bucket, my program gets informed and then starts to analyze the files. Thank you.

### Steps to Reproduce

n/a

### Current behavior

n/a

### AWS Java SDK version used

V2

### JDK version used

openjdk version "11.0.12" 

### Operating System and version

CentOS 7

**Comment by debora-ito** [comment]
@elixluo which operation did you see in v1, was it PutBucketNotificationConfiguration?
If so, here's the equivalent in v2: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#putBucketNotificationConfiguration-java.util.function.Consumer-

You can read more about S3 Event notification in their Developer Guide - https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html
