### ISSUE TITLE
S3 400 error using af-south-1

### ISSUE THREAD

**Issue by simonsteiner1984** [aws/aws-sdk-java#2684]
### Describe the bug

When I use aws-sdk-java 1.12 with a bucket in region af-south-1, I am getting a http 400 error. When I use a bucket in eu-west-1 region it works ok.

### Expected behavior

No error

### Current behavior

400 error

### Steps to Reproduce

Example code we use:
String sessionName = "sc-input-retriever-session-" + UUID.randomUUID().toString();
RoleInfo role = new RoleInfo()
.withRoleArn("xxx")
.withExternalId("xxx")
.withRoleSessionName(sessionName);
STSProfileCredentialsServiceProvider serviceProvider = new STSProfileCredentialsServiceProvider(role);
String region = "af-south-1";
AmazonS3 client = AmazonS3ClientBuilder.standard()
.withCredentials(serviceProvider)
.withRegion(region)
.build();
TransferManager transferManager = TransferManagerBuilder.standard().withS3Client(client).build();
transferManager.download("xxx", "x", new File("tmp"));

### AWS Java SDK version used

1.12

### JDK version used

11.0.5

### Operating System and version

Ubuntu

**Comment by kozub** [comment]
Hey @simonsteiner1984!
I've checked the issue that you have rised using lates version of SDK (`1.12.131`) and it was also failing for some regions including `af-south-1`.
I found that it might be related to the fact that some new regions are disabled by default on AWS accounts. When enabled - listing s3 buckets works for me. 
Could you please confirm that `af-south-1` is enabled on you account?

**Comment by simonsteiner1984** [comment]
works once we enabled v2 tokens on our account

**Comment by debora-ito** [comment]
@simonsteiner1984  Glad you figured this out.
Thank you for looking into this @kozub.

Closing.
