### ISSUE TITLE
withForceGlobalBucketAccessEnabled and enableForceGlobalBucketAccess not working as expected

### ISSUE THREAD

**Issue by sunilke** [aws/aws-sdk-java#2692]
### Describe the bug

I am using java aws sdk and currently creating the s3 client using following manner:

AmazonS3 s3Client= AmazonS3ClientBuilder.standard().withRegion(Regions.AP_SOUTH_1).withCredentials(new AWSStaticCredentialsProvider(myCredentials)).enableForceGlobalBucketAccess().build();

OR 

AmazonS3 s3Client= AmazonS3ClientBuilder.standard().withRegion(Regions.AP_SOUTH_1).withCredentials(new AWSStaticCredentialsProvider(myCredentials)).withForceGlobalBucketAccessEnabled(true).build();

I want to access buckets that can be in region other than mentioned default region so hence I am using enableForceGlobalBucketAccess or withForceGlobalBucketAccessEnabled and this works fine when I do get/put api call for buckets in different region 
but for GeneratePresignedUrl api its behaving strange:
-It works fine when I first do put/get api call for certain object on bucket in different region and then do generatePresignedUrl(with GET http method) api call for any object of any bucket . 
-When I directly do generatePresignedUrl(with GET http method) api call for some already existing object on bucket of different region then I error "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint"

Also isForceGlobalBucketAccessEnabled() for this created AmazonS3ClientBuilder is giving true.

So why I am getting this error even though I have used  enableForceGlobalBucketAccess or withForceGlobalBucketAccessEnabled while creating s3client. Please help me on this

Java version: 8
Maven dependency used for aws sdk:
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.11.873</version>
    </dependency>

### Expected behavior

I should get the object using generatePresignedUrl(with GET http method) api

### Current behavior

<Error>
<Code>PermanentRedirect</Code>
<Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
<Endpoint>...</Endpoint>
<Bucket>...</Bucket>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>

### Steps to Reproduce

AmazonS3 s3Client= AmazonS3ClientBuilder.standard().withRegion(Regions.AP_SOUTH_1).withCredentials(new AWSStaticCredentialsProvider(awsCredentials2)).withForceGlobalBucketAccessEnabled(true).build();

//Use bucket that's in different region than default region provided to create seClient
GeneratePresignedUrlRequest presignedUrlRequest=new GeneratePresignedUrlRequest("Bucket-Name","Bucket-Key");
        URL url=s3Client.generatePresignedUrl(presignedUrlRequest);
        //Now try opening this URL we got in response.

### AWS Java SDK version used

1.11.873

### JDK version used

1.8

### Operating System and version

Macos cataline version 10.15.7

**Comment by debora-ito** [comment]
@sunilke `forceGlobalBucketAccess` won't work for URL presigners.

What the forceGlobalBucketAccess flag does is: when you call an S3 API and the region defined in the client is different from the bucket you are trying to access, the SDK will get the response with the exception and, using some complicated logic, will retry the operation with the correct region.

This is not possible for presigned urls, because they need to be generated with the correct region since the region is part of the object endpoint.

**Comment by rchache** [comment]
Is there a recommended workaround for this use-case?
