### ISSUE TITLE
Dynamodb between query fails to correctly return full items on queries ending in 000

### ISSUE THREAD

**Issue by BenMillsPerkins** [aws/aws-sdk-java#2693]
### Describe the bug

When querying DynamoDB using the Java SDK, the between clause fails to correctly identify items within the period specified if the request ends in 000. The field in question in DynamoDB is formatted as an ISO datetime (yyyy-mm-dd'T'HH:mm:ss.SSS'Z') and, whenever a query is made with the between field starting at a second on the dot, 000 milliseconds, the first second's results are completely ignored. 

Query is being done from a lambda running on Java SE 11, on a Global Secondary index, with the between clause applied to the sort key, and values created from Instant.toString() functionality

### Expected behavior

When making a query of x field between "2021-12-15T15:21:44.000Z" and "2021-12-15T15:31:43.999Z", an item with the value "2021-12-15T15:21:44.543Z" should be returned as part of the results

### Current behavior

When making a query of x field between "2021-12-15T15:21:44.000Z" and "2021-12-15T15:31:43.999Z", all items with a value of between "2021-12-15T15:21:44.000Z" and "2021-12-15T15:21:44.999Z" are ignored, but all items between "2021-12-15T15:21:45.000Z" and "2021-12-15T15:31:43.999Z" are returned correctly as expected

### Steps to Reproduce

Create a DynamoDB table with a Global secondary index with an arbitrary partition key (pkey here) and a sort key on a string field (skey here).
Insert data with the sort key field being "2021-12-15T15:21:44.543Z" and the partition key being "string"
Make a request as below via the Java SDK:
`		
                Map<String, AttributeValue> expressionAttributeValues = new HashMap<>();
		expressionAttributeValues.put(":pkey", new AttributeValue().withS("string"));
		expressionAttributeValues.put(":fromDateUtc", new AttributeValue().withS("2021-12-15T15:21:44.000Z"));
		expressionAttributeValues.put(":toDateUtc", new AttributeValue().withS("2021-12-15T15:31:43.999Z"));
`
`
		DynamoDBQueryExpression<TableClass> queryExpression = new DynamoDBQueryExpression<TableClass>()
				.withIndexName(GSI_INDEX)
				.withConsistentRead(false)
				.withKeyConditionExpression("pkey = :pkey AND skey BETWEEN :fromDateUtc AND :toDateUtc")
				.withLimit(queryLimit)
		        .withScanIndexForward(true)
				.withExpressionAttributeValues(expressionAttributeValues);
`

The results will not contain the item inserted, despite being within the time range in question

### Context

This being used to evaluate which items in a table need actioning, which is failing as the items are not returned correctly and therefore do not get actioned.

### AWS Java SDK version used

1.12.135

### JDK version used

Java 11 (Corretto)

### Operating System and version

Lambda x86_64

**Comment by aaoswal** [comment]
Hi @BenMillsPerkins,
I was unable to reproduce the bug. Following the reproduction steps listed, the query did result in including the item inserted as it should.

<details>
<summary>Table Class</summary>

```
// Partition key
    @DynamoDBHashKey(attributeName = "partitionkey")
    public String getPartitionkey() {
        return partitionkey;
    }

    public void setPartitionkey(String partitionkey) {
        this.partitionkey = partitionkey;
    }

    // Sort key
    @DynamoDBRangeKey(attributeName = "sortkey")
    public String getSortkey() {
        return sortkey;
    }

    public void setSortkey(String sortkey) {
        this.sortkey = sortkey;
    }

```
</details>

<details>
<summary>Code</summary>

```
        AmazonDynamoDB client = AmazonDynamoDBClientBuilder.standard().build();
        DynamoDBMapper mapper = new DynamoDBMapper(client);
        Map<String, AttributeValue> expressionAttributeValues = new HashMap<>();
        expressionAttributeValues.put(":partitionkey", new AttributeValue().withS("string"));
        expressionAttributeValues.put(":fromDateUtc", new AttributeValue().withS("2021-12-15T15:21:44.000Z"));
        expressionAttributeValues.put(":toDateUtc", new AttributeValue().withS("2021-12-15T15:31:43.999Z"));
        DynamoDBQueryExpression<TableClass> queryExpression = new DynamoDBQueryExpression<TableClass>()
                .withIndexName(GSI_INDEX)
                .withConsistentRead(false)
                .withKeyConditionExpression("partitionkey = :partitionkey AND sortkey BETWEEN :fromDateUtc AND :toDateUtc")
                .withLimit(limit)
                .withScanIndexForward(true)
                .withExpressionAttributeValues(expressionAttributeValues);
        List<TableClass> result = mapper.query(TableClass.class, queryExpression);
        for (TableClass res : result) {
            System.out.format("pkey=%s, sortkey=%s", res.getPartitionkey(),
                    res.getSortkey());
        }
```
</details>

Output:
```
pkey=string, sortkey=2021-12-15T15:21:44.543Z
```

Could you please share a simple sample code that reproduces the bug or provide any additional information which would help to reproduce the bug on my end?

**Comment by BenMillsPerkins** [comment]
Hi there,

I have double checked and this issue is still very much the case, but I can't see any differences in approach between the implementation on my side and yours. The global secondary index we have doesn't project all attributes, only two alongside the partition and sort key, but I struggle to see how that would make any difference. The only other difference is that we use a .toString on an Instant instead of passing the string directly, but it reproduces the same result regardless of whether I do that or not.

What versions etc are you using?

**Comment by aaoswal** [comment]
Hi @BenMillsPerkins,
I am using the same versions as mentioned above.
- `Java SDK 1.12.135`
- `Java JDK 11 Corretto`

Are you using any other additional customizations on your end?
Could you also please share a sample code for reproduction on my end?

Thank you for your patience.
