### ISSUE TITLE
I corrected the log typo at the debug level

### ISSUE THREAD

**Issue by seheonCho** [aws/aws-sdk-java#2697]
### Describe the bug

I corrected the log typo at the debug level

### Expected behavior

aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferProgress.java

The correct log needs to be printed out, logger.debug()

log.debug("Number of bytes transferred is more than the actual total bytes to transfer. Total number of bytes to Transfer : "
                        + totalBytesToTransfer
                        + ". Bytes Transferred : "
                        + (bytesTransferred + bytes));

### Current behavior

```
log.debug("Number of bytes transfered is more than the actual total bytes to transfer. Total number of bytes to Transfer : "
                        + totalBytesToTransfer
                        + ". Bytes Transferred : "
                        + (bytesTransferred + bytes));
```

### Steps to Reproduce

It's a simple example.
```
TransferProgress transferProgress = new TransferProgress();
transferProgress.setTotalBytesToTransfer(1L);
transferProgress.updateProgress(2L);
```
and if, logging level for project is DEBUG,

We can receive logs with typos output from the following methods.

### Possible Solution

```
log.debug("Number of bytes transferred is more than the actual total bytes to transfer. Total number of bytes to Transfer : "
                        + totalBytesToTransfer
                        + ". Bytes Transferred : "
                        + (bytesTransferred + bytes));
```

[This is my Pull Request](https://github.com/aws/aws-sdk-java/pull/2690)

Logs must be stamped with correct words.

Please understand that it is insufficient because it is the first issue preparation and full request. :)

### Context

It doesn't affect the operation of the program, but I want the log to be printed correctly.

### AWS Java SDK version used

AWS SDK for Java 1.12.92

### JDK version used

openJdk 11.0.10

### Operating System and version

Window10 , Mac OS Big Sur 11.5.2

**Comment by debora-ito** [comment]
Hi @seheonCho thank you for your contribution. I'll change this to a documentation issue.

For the Java SDK v1 we need to incorporate the changes in our internal repository, so that after the release process they are reflected here in the Github. We'll add your change internally when we have a chance.

**Comment by debora-ito** [comment]
The fix was released. Closing.
