### ISSUE TITLE
How to get Virtually Hosted style URL for an pre-signed S3 resource

### ISSUE THREAD

**Issue by hadiyarajesh** [aws/aws-sdk-java#2698]
### Describe the issue

I want to get virtually hosted style url for pre-signed s3 object. AWS docs mention that s3 by default return virtually hosted style url, but i'm getting path style url in response.

### Steps to Reproduce

```
val s3Client = AmazonS3ClientBuilder.standard()
    .withCredentials(AWSStaticCredentialsProvider(BasicAWSCredentials(accessKey, secretKey)))
    .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration(endpoint, region))
    .build()


val preSignedUrlRequest = GeneratePresignedUrlRequest(
    "mybucket",
    "/folder1/myobject",
    HttpMethod.GET
).withExpiration(expireAt)

// This returns path style url, but i wants virtually hosted style url
val url = s3Client.generatePresignedUrl(preSignedUrlRequest).toString()
```

### Current behavior

S3 returns  path style url instead of virtually hosted style url

### AWS Java SDK version used

1.12.138

### JDK version used

11

### Operating System and version

Windows 11 Pro 22526.1000.0

**Comment by debora-ito** [comment]
@hadiyarajesh I can't reproduce the issue on my side, I get a virtual host style URL.

`
https://my-bucket-test.s3.us-west-2.amazonaws.com/folder1/tree.txt?X-Amz-Security-Token=XXX&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220112T223608Z&X-Amz-SignedHeaders=host&X-Amz-Expires=285&X-Amz-Credential=ABC123%2F20220112%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=XXX
`

Does your bucket name contain dot or other special characters?
Are you using the system configuration that sets the `addressing_style` to path? https://docs.aws.amazon.com/sdkref/latest/guide/setting-s3-addressing_style.html
