### ISSUE TITLE
Reactive Elasticsearch client from springframework.data cannot connect to AWS Opensearch

### ISSUE THREAD

**Issue by Cvmaggio** [aws/aws-sdk-java#2704]
### Describe the issue

We are trying to establish a reactive async connection from a springboot app running in ec2 to an opensearch instance. We have successfully used a synchronus httpclient to do much the same connection so we know that the url we are attempting to reach is correct. 

We have been building a reactiveclient like is described at the below documentation 
docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#reference 
using different permutations of the Example 55. Client Configurationcode, but always with .connectedTo and .usingSsl

Can you offer any guidance?

We prefer the spring because we like the stream (flux) functionality. Is there a way to get this functionality from the AWS equivalent libraries

### Steps to Reproduce

```
public class ReactiveRestClientConfig extends AbstractReactiveElasticsearchConfiguration {

    @Override
    @Bean
    public ReactiveElasticsearchClient reactiveElasticsearchClient() {
        final ClientConfiguration clientConfiguration = ClientConfiguration.builder() 
            .connectedTo("localhost:9200") //
            .build();
        return ReactiveRestClients.create(clientConfiguration);

    }
}


ClientConfiguration clientConfiguration = ClientConfiguration.builder()
  .connectedTo("localhost:9200", "localhost:9291")                      
  .usingSsl()                                                           
  .withHeaders(() -> {                                                  

  })
  .withClientConfigurer(                                                
    ReactiveRestClients.WebClientConfigurationCallback.from(webClient -> {

      return webClient;
  	}))
```

### Current behavior

We expect a connection to be established and for the aws elasticsearch instance to be queryable. Instead the reactive client returns that the instance is "`org.springframework.data.elasticsearch.client.NoReachableHostException: ..... not reachable. Cluster state is offline`"

### AWS Java SDK version used

1.11.951

### JDK version used

11.0.13 2021-10-19 LTS

### Operating System and version

Windows 7

**Comment by aaoswal** [comment]
Hi @Cvmaggio,
Based on the error that you mentioned above `org.springframework.data.elasticsearch.client.NoReachableHostException: ..... not reachable. Cluster state is offline`, it hints towards the error being related to the spring framework and not particularly related to the Java SDK used or the EC2 instance.

There seem to be multiple issues opened in [spring-projects/spring-boot](https://github.com/spring-projects/spring-boot/issues) mentioning this error.

If you still think that this is a problem with the SDK, I would be happy to investigate further. 
Hence, I would like to request you to please share your sample code with the reproduction steps along with the full stack-trace of the error you are facing?
