### ISSUE TITLE
Cloudfront - Sample Java Example for Cross account Cache invalidation 

### ISSUE THREAD

**Issue by uchakula132** [aws/aws-sdk-java#2708]
### Describe the issue

Hi,
We are trying to invalidate cache on different account (Account B) by passing accountId . We noticed that we are not able to pass accountId in the createInvalidateRequest object. I did some analysis and came across the post where cross account invalidation can be done using lamba function and role assumption. This is the link https://subhaspatil-c.medium.com/cloudfront-invalidation-from-cross-account-codepipeline-8614a8b858b1 

Could you please advise below - 
1. Is there a way to pass accountId in the CreateInvalidationRequest object and form arn:aws:cloudfront::<accountB-ID>:distribution/<distibutionId>
2. If point 1 is not possible, could you please share sample Java code for the lamba function and role assumption logic that's mentioned in the above blog OR
3. Any other possible approach to perform cross account invalidation. 

### Steps to Reproduce

Currently we are simply creating createInvalidationRequest object using distributionId and InvalidationBatch 

CreateInvalidationRequest invalidation = new CreateInvalidationRequest(
                        distributionId, invalidationBatch);
                final AmazonCloudFront client = CommonUtils.getAmazonCloudFrontClient();

### Current behavior

Currently the system is trying to invalidate cache on the same account where distributionId is provided. We would like to perform cross account invalidation.

### AWS Java SDK version used

1.12.66

### JDK version used

1.8

### Operating System and version

windows 10

**Comment by debora-ito** [comment]
Hi @uchakula132 

  > 1. Is there a way to pass accountId in the CreateInvalidationRequest object and form arn:aws:cloudfront:::distribution/

Not currently, according to the API reference: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateInvalidation.html

> 2. If point 1 is not possible, could you please share sample Java code for the lamba function and role assumption logic that's mentioned in the above blog OR

I won't write the whole lambda handler example in Java - this is not really the right channel for this.
But I can point you in the direction of the Java documentation that can help:
- The AssumeRole operation is in the STS client - [AWSSecurityTokenServiceClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html)
- The CreateInvalidation is using the CloudFront client - [AmazonCloudFrontClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/AmazonCloudFrontClient.html)
- The PutJobSuccessResult and PutJobFailureResult are in the CodePipeline client - [AWSCodePipelineClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codepipeline/AWSCodePipelineClient.html)

The request fields are the same across the SDKs, it should be simple to "translate" the api calls in the Python example to Java. If you've recently started using the Java SDK take a look at the Developer Guide - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/basics.html

> 3. Any other possible approach to perform cross account invalidation.

We don't really have the expertise on CloudFront things. This is a good question to ask in the AWS re:Post forums - https://repost.aws/

**Comment by uchakula132** [comment]
Thank you for clarification Debora.

**Comment by debora-ito** [comment]
Feel free to reach out if you have any other question.
