### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to store object contents to disk: Read timed out

### ISSUE THREAD

**Issue by shenhongwei33** [aws/aws-sdk-java#2712]
### Describe the issue

[https://github.com/aws/aws-sdk-java/issues/2700](url)
This question was mentioned before, but it was closed unexpectedly, please check the problem in detail

### Steps to Reproduce

I think this exception will continue to retry the migration, but if it continues, it will cause some objects to fail to migrate

### Current behavior

#2700

### AWS Java SDK version used

aws-java-sdk-bom 1.12.138

### JDK version used

java version "1.8.0_172" Java(TM) SE Runtime Environment (build 1.8.0_172-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

### Operating System and version

centos 7.6

**Comment by debora-ito** [comment]
@shenhongwei33 #2700 is pretty extensive, is your question about why reusing one single s3 client seems to impact the download speed?

If so, you're setting `config.setMaxConnections(4)`, which means you'll only have 4 concurrent connections open at max. If you increase this number you'll probably see improvement - the default value is 50.
