### ISSUE TITLE
DynamoDB Create Table from JSON

### ISSUE THREAD

**Issue by wise-coders** [aws/aws-sdk-java#2714]
### Describe the issue

I found that tables can be created in Java like [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.Java.01.html).
Is it possible to create them from Java also directly from JSON?
The JSON can be as object or String.

### Links

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.Java.01.html

**Comment by debora-ito** [comment]
Not to create a table, no.

There are some options to insert items:
- using the low-level DynamoDB API: [Step 2 - Load Sample Data](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.Java.02.html)
- if you use the high-level library [DynamoDB Mapper](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.html), you can use the [@DynamoDBTypeConvertedJson](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBTypeConvertedJson.html) annotation.

Let us know if this helps.

**Comment by wise-coders** [comment]
None of this does help me.
I need this to be able to export and import the schema as JSON from Java.
What is usually done using this
```
Table table = dynamoDB.createTable(tableName,
                Arrays.asList(new KeySchemaElement("year", KeyType.HASH), // Partition
                                                                          // key
                    new KeySchemaElement("title", KeyType.RANGE)), // Sort key
                Arrays.asList(new AttributeDefinition("year", ScalarAttributeType.N),
                    new AttributeDefinition("title", ScalarAttributeType.S)),
                new ProvisionedThroughput(10L, 10L));
```
to be done by exporting and importing a JSON. Should I create a feature request for this?
It would be nice to add also comment properties to fields, so we can document the tables, partition keys, etc.

**Comment by debora-ito** [comment]
@wise-coders that would be a feature request, but since we are not working in big features for Java SDK v1 it probably won't be implemented.

Regarding keeping the schema documented, take a look at the Java SDK 2.x DynamoDB Enhanced client - https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/

It does not support the JSON-based table creation that you're looking for,  but it may help on the other asks.

You can find some basic examples in the Overview - https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced

**Comment by baldram** [comment]
Maybe it will be helpful to someone. 👇 

The last hint from @debora-ito helps. 

I wish there were a way to use the JSON fixture. However, it's excellent that, e.g. I don't need to implement a boilerplate in tests utilising the builder by hand.
(I mean the `CreateTableRequest.builder()`... `AttributeDefinition.builder()`... `KeySchemaElement.builder()`... `ProvisionedThroughput.builder()`... and so on).

What I do instead is just a as Debora mentioned I use the [dynamodb-enhanced](https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced#initialization).

The key hint here is the 

```java
static final TableSchema<Customer> CUSTOMER_TABLE_SCHEMA = TableSchema.fromClass(Customer.class);
```

Below is a complete tested code snipped to create a table out of the DynamoDb bean (a class annotated with `@DynamoDbBean`). 

_Sorry for the Scala code, I use this JVM-based variant)._
```scala
    TableSchema.fromClass(classOf[Customer]).pipe { tableSchema =>
      dynamoDbClient
        .table(TABLE_NAME, tableSchema)
        .createTable()
```
