### ISSUE TITLE
AsyncCloudwatch log client not returning reponse when run from inside of the VPU

### ISSUE THREAD

**Issue by umesh2611** [aws/aws-sdk-java#2715]
### Describe the bug

We are logging the application traces and metrics in cloud watch.
We are using the Cloudwatch Async client to do the actions ( for example putLogEvents ).

When The application is run outside the VPC , the client works perfectly fine. 
But when we run the Application inside the VPC ( from an Openshift microservice ) , the application hangs waiting for the response from the client. 

NOTE : the same use case works fine when we run with JDK 8. But when we run with JDK 15 things stop working inside of VPC.

following are the observtions : 

1. JDK 15 / outside of vpc ==> client returns back normally
2. JDK 8 / outside of VPC ==> client return normally
3. JDK 8 / inside of VPC ==> client returns normally
4. JDK 15 / Inside of VPC ==> client does not retrun and blocks the connections 

### Expected behavior

The completable Future should return the result and give back the connection to the cache ( in built )

### Current behavior

the Client never returns back and so the connection pool exhausts the connections 

### Steps to Reproduce

1.run a simple java program using cloudwatch async client
2. add logs to the log streams. 
3. you should notice that the client return back successfully
4. run the same tests inside of an VPC the client is not returning back. 

NOTE : the same use case works fine when we run with JDK 8. But when we run with JDK 15 things stop working inside of VPC.

following are the observtions : 

1. JDK 15 / outside of vpc ==> client returns back normally
2. JDK 8 / outside of VPC ==> client return normally
3. JDK 8 / inside of VPC ==> client returns normally
4. JDK 15 / Inside of VPC ==> client does not retrun and blocks the connections 

### AWS Java SDK version used

2.17.118

### JDK version used

15

### Operating System and version

Linux

**Comment by debora-ito** [comment]
@umesh2611 since it works fine in some cases but not when using a VPC, this is probably a network configuration problem. Is the service endpoint reachable?

Can you share the logs with the errors?

**Comment by debora-ito** [comment]
It looks like you get at least one successful response from PutMetricData so maybe it's not a network config problem. 

There's no error in the logs after this? Have you identified which line of code is hanging?

**Comment by umesh2611** [comment]
Hi,

We have disabled the observability for now due to the criticality of the
functional aspect..we plan to start lookin at this next week. I will update
on the findings.

Thank you
Umesh Paliwal
