### ISSUE TITLE
Provide a way to access Message Attributes in SnsMessage/SnsNotification

### ISSUE THREAD

**Issue by GouthamiKondakindi** [aws/aws-sdk-java#2716]
### Describe the feature

Setup: A queue in SQS is subscribed to a topic in SNS with RawMessageDelivery=false

Usecase: When a message is published to the above topic and this message has some message attributes, when this message is forwarded to a queue, the message body that SQS receives will be in JSON format and this JSON contains "MessageAttributes". 
Sample message that SQS receives in this case:
{
  "Type": "Notification",
  "MessageId": "dc1e94d9-56c5-5e96-808d-cc7f68faa162",
  "TopicArn": "arn:aws:sns:us-east-2:111122223333:ExampleTopic1",
  "Subject": "TestSubject",
  "Message": "This is a test message.",
  "MessageAttributes": {
    "<Attribute 1>": {
      "Type": "String",
      "Value": "<Attribute 1 Value>"
    },
    "<Attribute 2>": {
      "Type": "String"
      "Value": "<Attribute 2 Value>"
    }
  }
  "Timestamp": "2021-02-16T21:41:19.978Z",
  "SignatureVersion": "1",
  "Signature": "abc==",
  "SigningCertURL": "<cert.pem>",
  "UnsubscribeURL": "<url>"
}

But I don't see this "MessageAttributes" in [SnsNotification.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/message/SnsNotification.java) or [SnsMessage.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/message/SnsMessage.java). So, I don't have a way to map the message body that SQS receives to a Java object in the aws sdk.

### Is your Feature Request related to a problem?

AWS sdk provides no way to parse the message that SQS received from SNS and extract "MessageAttributes" from it.

### Proposed Solution

Add "MessageAttributes" to SnsNotification.java or SnsMessage.java

### Describe alternatives you've considered

Alternative would be to create my own custom object to map the JSON and extract "MessageAttributes" from it.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

1.12.167

### JDK version used

1.8.0_172

### Operating System and version

macos

**Comment by debora-ito** [comment]
I think it's the same ask we had in the past here: https://github.com/aws/aws-sdk-java/issues/2599.

If so, this has greater chance to be supported in the Java SDK v2. 
Let us know if you have further questions.

**Comment by GouthamiKondakindi** [comment]
Hi @debora-ito, we current use v1 and we don't plan to upgrade to v2 yet because it's going to be a huge upgrade for us. If this isn't going to be supported in v1, my only option is to create my own custom object that extends SnsNotification.java and includes "MessageAttributes"? Is there no way to add this support in v1 sdk?

**Comment by debora-ito** [comment]
We understand that upgrading is not an easy task, but v1 features have very low chances to be prioritized in favor of Java SDK v2 feature work.

The SNS Message Manager is not available yet in v2, you can track the progress and give a 👍  in the specific ask about Message Attributes here: https://github.com/aws/aws-sdk-java-v2/issues/1302#issuecomment-866241404

**Comment by GouthamiKondakindi** [comment]
Thanks @debora-ito . Closing this issue.
