### ISSUE TITLE
Will S3 Client support SHA256/SHA512  for checking the integrity of an object uploaded to Amazon S3?

### ISSUE THREAD

**Issue by VikkeyJiang** [aws/aws-sdk-java#2718]
### Describe the feature

same with subject

### Is your Feature Request related to a problem?

no

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

lastest

### JDK version used

1.8

### Operating System and version

Linux Centos 7

**Comment by debora-ito** [comment]
Hi @VikkeyJiang  S3 perform some checks on the service side using the content-MD5: https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/

Can you give more context on the question? Are you using S3Client or TransferManager, single or multipart? Are you trying to solve a problem?
