### ISSUE TITLE
No scalar value for BooleanAttribute means we can no longer have Boolean value keys

### ISSUE THREAD

**Issue by cttillman** [aws/aws-sdk-java#2720]
### Describe the feature

Recently upgraded to version 2 and noticed that we can no longer have a boolean as part of a composite key in the code, and then have it saved as a numeric value in the table. 

```
        @Override
        public Consumer<StaticTableMetadata.Builder> modifyMetadata(String attributeName,
                                                                    AttributeValueType attributeValueType) {
            return metadata -> {
                if (attributeValueType.scalarAttributeType() == null) {
                    throw new IllegalArgumentException(
                        String.format("Attribute '%s' of type %s is not a suitable type to be used as a key.",
                                      attributeName, attributeValueType.name()));
                }

                tableMetadataKeySetter.accept(metadata, new AttributeAndType(attributeName, attributeValueType));
            };
        }
```

### Is your Feature Request related to a problem?

See above.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2

### JDK version used

1.8

### Operating System and version

macOS Monterey

**Comment by debora-ito** [comment]
@cttillman I'm not clear on the ask here. DynamoDB Enhanced client has a built-in [BooleanAttributeConverter](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/BooleanAttributeConverter.html).

Can you give us more context on what your code in v1 did exactly? Maybe show some code examples?

**Comment by cttillman** [comment]
In my v1 code, I was able to use Boolean types for keys, and it would convert them to numeric 1/0 before trying to persist to DynamoDB. At least that's what I thought. On second look, it may have been the case that my project was using a third party library to make that possible.

**Comment by debora-ito** [comment]
In any case, the DynamoDB Enhanced client should support this, it was implemented specifically to support the use case of applications that migrated from v1 to v2 and had 0s and 1s in the database - https://github.com/aws/aws-sdk-java-v2/issues/1912.

Le us know if you find out more or if you have any questions.

**Comment by cttillman** [comment]
Oh, thank you. I will try that. I did try writing a custom converter before, but not at that level of detail. At a glance, it looks like it should solve the scalar attribute checking problem when using the @SortKey annotations.

**Comment by debora-ito** [comment]
Yes, give it a try and let us know how it goes.
