### ISSUE TITLE
About session after adminInitiateAuth with ADMIN_NO_SRP_AUTH

### ISSUE THREAD

**Issue by s-kim-biz** [aws/aws-sdk-java#2724]
### Describe the issue

I have one question about the session returned after the request of adminInitiateAuth with ADMIN_NO_SRP_AUTH.

Is it possible to be session as null ?

temporary user register password by using  adminInitiateAuth with ADMIN_NO_SRP_AUTH and AdminRespondToAuthChallengeRequest with NEW_PASSWORD_REQUIRED challenge.

It works well but sometimes I met the issue "Missing Required Parameter : session".

from some experiment, This problem occurred when I set null in `new AdminRespondToAuthChallengeRequest().withSession` .

so , I guess that some case makes the session parameter in response after the request of adminInitiateAuth with ADMIN_NO_SRP_AUTH to be null.
 

### Steps to Reproduce

1. create AdminInitiateAuthRequest with auth flow, userPoolId, clientId, and auth parameters (USERNAME, PASSWORD)
2. send api and get response from 1
3. create AdminRespondToAuthChallengeRequest with userPoolId, clientId, NEW_PASSWORD_REQUIRED challenge, session from 2, challenge response (USERNAME, NEW_PASSWORD)

### Current behavior

It will works almost well. but some times the issue "Missing Required Parameter: session " occurred  

### AWS Java SDK version used

aws-java-sdk-cognitoidp 1.11.969

### JDK version used

1.8.0_292

### Operating System and version

Linux 1.4.0

**Comment by debora-ito** [comment]
Hi @s-kim-biz this is more a service question than a SDK question, I don't have the expertise in Cognito to answer. May I suggest you ask in [AWS re:Post](https://repost.aws/)?

**Comment by s-kim-biz** [comment]
Hi @debora-ito thank you for your reply. That would be helpful for me.

**Comment by debora-ito** [comment]
I'll go ahead and close this. Please reach out if you have any other question about the AWS SDK for Java.
