### ISSUE TITLE
Add support for c6a instance type family

### ISSUE THREAD

**Issue by zacblazic** [aws/aws-sdk-java#2731]
### Describe the feature

The [`com.amazonaws.services.ec2.model.InstanceType`](https://github.com/aws/aws-sdk-java/blob/47fc372c0deb1e46509d346554c119067fd99159/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/InstanceType.java) enum does not currently specify instance types for the [`c6a` family](https://aws.amazon.com/ec2/instance-types/c6a/).

### Use Case

I'd like to be able to add support for the [`c6a` family](https://aws.amazon.com/ec2/instance-types/c6a/) to the [Jenkins EC2 plugin](https://github.com/jenkinsci/ec2-plugin) which makes use of the SDK to specify instance types.

### Proposed Solution

I'm not familiar with how to go about adding the new instance family as the code appears to be [generated](https://github.com/aws/aws-sdk-java/blob/47fc372c0deb1e46509d346554c119067fd99159/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/InstanceType.java#L20). If someone could point me at documentation regarding how to implement the change I'd be happy to.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.12.193

### JDK version used

11.0.14.1

### Operating System and version

Ubuntu 20.04

**Comment by debora-ito** [comment]
@zacblazic thank you for reaching out. We are tracking this in https://github.com/aws/aws-sdk/issues/198, so I'll close this one.
