### ISSUE TITLE
DynamoDbLocal support for all recently released apis

### ISSUE THREAD

**Issue by anton-tkachenko** [aws/aws-sdk-java#2744]
### Describe the feature

I understand that it's not quite related to java sdk, but it's been some time since dynamodblocal 1.18 was released, and since then where were few updates in DynamoDb api (for instance, https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-dynamodb-limit-request-partiql-operations/)

Latest java sdk supports limit in api, but lates DynamoDbLocal (1.18) doesn't :(

### Use Case

I want to be able to use all recent features of DynamoDb in tests & pipeline without using actual hosted service

### Proposed Solution

Please release new version :)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

com.amazonaws:aws-java-sdk-dynamodb:1.12.196

### JDK version used

11

### Operating System and version

Linux

**Comment by debora-ito** [comment]
Thank you for reaching out @anton-tkachenko. I will pass your feedback to the DynamoDB Local team.

**Comment by debora-ito** [comment]
The DynamoDB Local team acknowledged the request, and said it's on the backlog.

Closing this, as there's nothing pending from the Java SDK team.
