### ISSUE TITLE
Allow full SDK client initialization for newly created clients based on environment variable

### ISSUE THREAD

**Issue by aal80** [aws/aws-sdk-java#2745]
### Describe the feature

When creating a new Client object, the client is not fully initialized until the first request is made. It looks like internal components/dependencies are loaded lazily on first client usage. While this might be the desired behavior in some scenarios, this is not always the case. This feature request is for a way to force full client initialization when creating new client objects, preferably using an environment variable.

### Use Case

When runing a sequence of SDK requests from a Lambda function configured with default settings, it was observed that the first request always takes significantly longer, up to x100 longer in some cases (~9000ms vs ~80ms). This was tested with DynamoDbClient and SsmClient. The result is a degraded UX for the first function invocation, which is very noticable when developing Lambdas.
![image](https://user-images.githubusercontent.com/3949873/164287932-20e9d160-fccd-4183-8750-229cebfce144.png)
![image](https://user-images.githubusercontent.com/3949873/164287906-cbb089b2-80c1-42aa-b006-bff549cdc255.png)

### Proposed Solution

Introduce environment variable that will force full client initialization when present.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

Latest on v3 branch

### JDK version used

Corretto 11 in Lambda's Java runtime

### Operating System and version

AL2, Lambda's Java runtime

**Comment by debora-ito** [comment]
@aal80 I see you've posted the same feature request in the AWS SDK for Java v2 [here](https://github.com/aws/aws-sdk-java-v2/issues/3167). The team focus is mostly in Java SDK v2 work, so I'll go ahead and close this in v1.
