### ISSUE TITLE
Use S3 SDK with Cloudfront

### ISSUE THREAD

**Issue by bamthomas** [aws/aws-sdk-java#2748]
### Describe the feature

We have developed [a service](https://github.com/ICIJ/datashare-api/blob/master/src/main/java/org/icij/datashare/io/RemoteFiles.java) based on NLP models stored in an S3 bucket.

It worked fine. Op team wanted to add a CloudFront instance in between. Then we've seen instabilities when downloading models : 
* crash during downloads
* corrupted files
* and sometimes it is working

For more details you can see [this issue](https://github.com/ICIJ/datashare/issues/626).

Did we miss something on the S3Client configuration/initialization ?

We created a ticket on AWS support, they told us to use S3 transfer acceleration. We did that, and it worked. The only drawback is that we couldn't use the FQDN on our bucket as the SSL endpoint was different.

As we've seen that S3 SDK was doing HTTP requests, why couldn't we use it with cloudfront ?
Or is there any specific settings to add either on the cloudfront instance or in the S3 client/server ?

### Use Case

Use S3 with cloudfront and S3 SDK

### Proposed Solution

As workaround : 

- S3 with cloudfront and classic HTTP client (like Apache HttpClient) was doing the job but we had to code recovering network errors, chunks downloads...

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.11.327

### JDK version used

11.0.10

### Operating System and version

Ubuntu 20.04

**Comment by debora-ito** [comment]
Is the main error you're seeing with the SDK `Caused by: javax.net.ssl.SSLException: Connection reset`?
How often do you see the error? It looks like it happens at random, which can indicate a network or environmental problems.
