### ISSUE TITLE
The SDK attempting to unmarshall an error into an exception is failing on Java 17

### ISSUE THREAD

**Issue by JasonMathison** [aws/aws-sdk-java#2754]
### Describe the bug

An error condition that was returning a useful exception with Java 11 is now returning a much less useful error with Java 17.  The SDK's attempt to use reflection to unmarshall the error is no longer allowed with Java 17.

### Expected Behavior

We would get the same exception back for this error on Java 17 as we did on Java 11.

### Current Behavior

This issue came up while moving a service from java 11 to java 17.  A couple of 'error path' integration tests started failing because we were not getting the same exception back from the AWS SDK.

Here is the redacted message coming over the wire:
{"Message":"User: arn:aws:sts::<some-account-id>:assumed-role/<some-role-name>/<name> is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:<account-id>:function:<function-name> because no identity-based policy allows the lambda:InvokeFunction action"}

On Java 11 we get
com.amazonaws.services.lambda.model.AWSLambdaException: User: arn:aws:sts::<account>:assumed-role/<role>/<name> is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:<account>:function:<function-name> because no identity-based policy allows the lambda:InvokeFunction action (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: ccca3dbc-fcd7-4fa5-ba5f-a7c359b39892; Proxy: null)

On Java 17 we get 
com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: e4fc5b4d-c264-42d5-bc20-0173a3102651; Proxy: null)

The reason is that the com.amazonaws.transform.JsonErrorUnmarshaller unmarshall method fails on Java 17 due to making an illegal reflective access.

Specifically, line 72 works with a warning in previous versions of java
return MAPPER.treeToValue(jsonContent, exceptionClass);
but it is now throwing an exception in java 17.

### Reproduction Steps

If this is required I will put this together, but there isn't much to this.  Trying to reflect in and out of Exceptions isn't allowed in Java 17.

### Possible Solution

At least in this case it would be as simple as creating an AmazonServiceException and using the message included in the jsonContext to populate the message.  I don't know if there are times where a more complex jsonContext has to be handled.

### AWS Java SDK version used

1.12.213

### JDK version used

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Operating System and version

Seen on windows 10 and linux

**Comment by debora-ito** [comment]
@JasonMathison can you provide a sample code I can use to reproduce?

**Comment by JasonMathison** [comment]
This can be reproduced with the https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/java/example_code/lambda/src/main/java/com/example/lambda/LambdaInvokeFunction.java example application.  If your credentials are expired, or if you modify your .aws/credentials file to make your aws_session_token invalid you will get a meaningful error if you run the example in Java 11 and the unmarshalling error with java 17.

**Comment by dennisameling** [comment]
Seeing the same issue with `com.amazonaws:aws-java-sdk-cognitoidp:1.12.218` and Java 17:

```
Unable to unmarshall exception response with the unmarshallers provided (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: AccessDeniedException; Request ID: 774de090-ce56-4675-9828-d21745246cfd)
```

Can't provide more details as this is a private repo, sorry. Switching back to Java 14 fixed the issue in our case.

**Comment by ckbrewer33** [comment]
I'm getting asimilar issue with `com.amazonaws:aws-java-sdk-core:1.12.130. Java 11 gives a warning about Illegal reflective access, pressumably from [here](https://github.com/aws/aws-sdk-java/blob/fd409dee8ae23fb8953e0bb4dbde65536a7e0514/aws-java-sdk-core/src/main/java/com/amazonaws/util/XpathUtils.java#L112) from what I can tell.

`Illegal reflective access by com.amazonaws.util.XpathUtils (file:/Users/cbrewer/.m2/repository/com/amazonaws/aws-java-sdk-core/1.12.130/aws-java-sdk-core-1.12.130.jar) to method com.sun.org.apache.xpath.internal.XPathContext.getDTMManager()`.

**Comment by debora-ito** [comment]
The recommendation here is to use AWS SDK for Java 2.x. Thanks to @dennisameling for confirming it works in 2.x.

AWS SDK for Java 1.x relies on some JDK APIs that are deprecated or will be deprecated on newer versions of Java and removing them may introduce breaking changes for those who are on older versions of JDK, so we can't change it unfortunately.

**Comment by JasonMathison** [comment]
The issue I was seeing can be worked around in Java 17 by adding the following to the VM args:
--add-opens java.base/java.lang=ALL-UNNAME
It would not be surprising if this work around is removed by the time that the next LTS java version is released.

Since this SDK is primarily for older code and versions of Java, can the documentation be updated to note that there is limited support for newer versions of Java?  Currently it simply says that it supports Java 8+. 

Also, the release notes have a broken link around installing a supported version of Java:
https://github.com/aws/aws-sdk-java#release-notes  
 "[Installing a Java Development Environment](http://docs.aws.amazon.com/java-sdk/v1/developer-guide/setup-install.html#installing-a-java-development-environment)"

**Comment by debora-ito** [comment]
Good callout @JasonMathison, I'll see to update the docs.
