### ISSUE TITLE
DynamoDBLocal 1.15.0+ has Kotlin embedded resulting in NoClassDefFoundError

### ISSUE THREAD

**Issue by ghaiszaher** [aws/aws-sdk-java#2755]
### Describe the bug

It is not possible to use DynamoDBLocal v1.15.0 or later with Kotlin in Gradle projects, a workaround is possible for Maven projects.

### Expected Behavior

Running integration tests with Spring & DynamoDBLocal should work. 

### Current Behavior

Using DynamoDBLocal as a test dependency on Kotlin projects results in the following error after running integration tests:

```
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    kotlin.reflect.jvm.internal.impl.descriptors.Visibilities.<clinit>(Visibilities.kt:56)

The following method did not exist:

    'java.util.Map kotlin.collections.MapsKt.createMapBuilder()'

The calling method's class, kotlin.reflect.jvm.internal.impl.descriptors.Visibilities, was loaded from the following location:

    jar:file:~/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.6.21/kotlin-reflect-1.6.21.jar!/kotlin/reflect/jvm/internal/impl/descriptors/Visibilities.class

The called method's class, kotlin.collections.MapsKt, is available from the following locations:

    jar:file:~/.m2/repository/com/amazonaws/DynamoDBLocal/1.15.0/DynamoDBLocal-1.15.0.jar!/kotlin/collections/MapsKt.class
    jar:file:~/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.6.21/kotlin-stdlib-1.6.21.jar!/kotlin/collections/MapsKt.class

The called method's class hierarchy was loaded from the following locations:

    kotlin.collections.MapsKt: file:~/.m2/repository/com/amazonaws/DynamoDBLocal/1.15.0/DynamoDBLocal-1.15.0.jar
    kotlin.collections.MapsKt___MapsKt: file:~/.m2/repository/com/amazonaws/DynamoDBLocal/1.15.0/DynamoDBLocal-1.15.0.jar
    kotlin.collections.MapsKt__MapsKt: file:~/.m2/repository/com/amazonaws/DynamoDBLocal/1.15.0/DynamoDBLocal-1.15.0.jar
    kotlin.collections.MapsKt__MapsJVMKt: file:~/.m2/repository/com/amazonaws/DynamoDBLocal/1.15.0/DynamoDBLocal-1.15.0.jar
    kotlin.collections.MapsKt__MapWithDefaultKt: file:~/.m2/repository/com/amazonaws/DynamoDBLocal/1.15.0/DynamoDBLocal-1.15.0.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes kotlin.reflect.jvm.internal.impl.descriptors.Visibilities and kotlin.collections.MapsKt
```

For Maven projects, a workaround exists by adding kotlin-reflect dependency:
```xml
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>
```

However, this doesn't solve it for Gradle projects.

### Reproduction Steps

1. Use dependency
```kotlin
dependencies {
    testImplementation("com.amazonaws:DynamoDBLocal:1.18.0")
}
```

2. Start a Spring Context in integration test

### Possible Solution

Remove kotlin in next version:
![image](https://user-images.githubusercontent.com/20379416/167134314-f1604f9e-4ecb-431e-9cfc-5bdcc8520b04.png)

### Additional Information/Context

Versions 1.13.6 and before work fine
![image](https://user-images.githubusercontent.com/20379416/167135445-e8d1f48a-3fd5-4405-a980-e2aa05f59658.png)

### AWS Java SDK version used
(irrelevant)

### JDK version used

11

### Operating System and version

Ubuntu-20.04.4-LTS

**Comment by debora-ito** [comment]
Hi @ghaiszaher, we are tracking this issue in https://github.com/aws/aws-sdk-java-v2/issues/2487.

The DynamoDB team is the maintainer of DynamoDBLocal, I'll ping them again in the internal ticket and ask for an update. Please use the other issue to check updates on the case.
