### ISSUE TITLE
Please do not swallow InterruptedException

### ISSUE THREAD

**Issue by shuwada** [aws/aws-sdk-java#276]
`com.amazonaws.util.Throwables#failure` completely swallows `InterruptedExeption`. This is a bad practice since the caller cannot tell whether a blocking call was interrupted.

If you cannot re-throw InterruptedException, please call `Thread.currentThread().interrupt()` like:

``` java
public static RuntimeException failure(Throwable t) {
  if (t instanceof InterruptedException)
    Thread.currentThread().interrupt()

  if (t instanceof RuntimeException)
    return (RuntimeException)t;
  if (t instanceof Error)
    throw (Error)t;
  return new AmazonClientException(t);
}
```

**Comment by cristianocca** [comment]
Not sure if this same logic is used in the SDK v2, but an interrupt makes all existing client instances to reject all new requests even if the underlying thread is not interrupted. This makes it hard to run for example additional calls while handling an interrupt, and any new SDK call must happen in a new thread
