### ISSUE TITLE
AmazonDynamoDBClientBuilder is taking too long to create dynamoDB instance

### ISSUE THREAD

**Issue by mak2211** [aws/aws-sdk-java#2764]
### Describe the bug

Hi Team,

Here we are using Kotlin (JAVA) and trying to establish a connection with AWS DynamoDB and so creating an instance for the same, but during that connection to build its taking more ~800ms  due to which the overall API response time is impacted. 

### Expected Behavior

The Connection time or instance creation time should be minimal to reduce the overall API response time

### Current Behavior

Output loggers:

2022-05-16 16:47:57.054 [main] INFO  GetOrganizationsHandler - Start Handler INIT 
2022-05-16 16:47:57.871 [main] INFO  GetOrganizationsHandler - HANDLER INIT AFTER DYNAMODB INSTANCE 

### Reproduction Steps

class GetOrganizationsHandler : RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
    private val logger: Logger = LoggerFactory.getLogger(this::class.simpleName)
    init {
        logger.info("Start Handler INIT")
        val dynamoDB = DynamoDB(AmazonDynamoDBClientBuilder.standard().withRegion(System.getenv("AWS_REGION") ?: "us-east-1").withCredentials(
            EnvironmentVariableCredentialsProvider()
        ).build())
        logger.info("HANDLER INIT AFTER DYNAMODB INSTANCE")
}

### Additional Information/Context

We are using below Configuration

Java version : 11
aws-java-sdk-dynamodb: 1.11.853
aws-lambda-java-core: 1.2.0
aws-lambda-java-events: 3.2.0

### AWS Java SDK version used

1.12.201 (internal)

### JDK version used

11.0.13

### Operating System and version

Mac OS Big Sur version 11.4

**Comment by debora-ito** [comment]
Hi @mak2211, 800ms sounds like a long time.

If you're able to migrate to Java SDK v2, using the built-in UrlConnectionHttpClient with Lambda will improve the startup time, the client being more lightweight and having lower instantiation time. 

We have other suggestions too with Java SDK v2: https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time/

Let us know if this helps.
