### ISSUE TITLE
Add Graviton3 instance types

### ISSUE THREAD

**Issue by twbraam** [aws/aws-sdk-java#2769]
### Describe the feature

The new c7g instance types are missing from https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/InstanceType.java:

c7g.medium
c7g.large
c7g.xlarge
c7g.2xlarge
c7g.4xlarge
c7g.8xlarge
c7g.12xlarge
c7g.16xlarge

### Use Case

Currently we cannot launch Graviton3 instances using the Java SDK.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

latest

### JDK version used

1.8

### Operating System and version

Any

**Comment by debora-ito** [comment]
They were added in SDK version `1.12.229`.
