### ISSUE TITLE
While using aws-java-sdk-s3 unable to establish connection with S3

### ISSUE THREAD

**Issue by Anchal2989** [aws/aws-sdk-java#2772]
### Describe the bug

AmazonS3ClientBuilder.standard().withClientConfiguration(clientConfig)
                .withCredentials(new AWSStaticCredentialsProvider(creds))
                .withRegion("us-east-1")
                .build();

### Expected Behavior

AmazonS3 object should be returned successfully.

### Current Behavior

java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:88)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:315)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:299)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:172)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:638)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	
------------------------------------------------------------------------------------------------------------------------------------
	
using - autogenerated by sdk - httpclient-4.5.13.jar
	
maven dependency tree -
	
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.6.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.6.4:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.6.4:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.4:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.6.4:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.29:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.6.4:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.6.4:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.8.3:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- com.github.ulisesbocchio:jasypt-spring-boot-starter:jar:3.0.3:compile
[INFO] |  \- com.github.ulisesbocchio:jasypt-spring-boot:jar:3.0.3:compile
[INFO] |     \- org.jasypt:jasypt:jar:1.9.3:compile
[INFO] +- org.springframework.boot:spring-boot-starter-hateoas:jar:2.6.4:compile
[INFO] |  \- org.springframework.hateoas:spring-hateoas:jar:1.4.1:compile
[INFO] |     +- org.springframework:spring-beans:jar:5.3.16:compile
[INFO] |     +- org.springframework:spring-context:jar:5.3.16:compile
[INFO] |     \- org.springframework.plugin:spring-plugin-core:jar:2.0.0.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-security:jar:2.6.4:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.16:compile
[INFO] |  +- org.springframework.security:spring-security-config:jar:5.6.2:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.6.2:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.16:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.6.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.6.4:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.1:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.16:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.16:compile
[INFO] +- org.mybatis.spring.boot:mybatis-spring-boot-starter:jar:2.1.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.6.4:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.16:compile
[INFO] |  |     \- org.springframework:spring-tx:jar:5.3.16:compile
[INFO] |  +- org.mybatis.spring.boot:mybatis-spring-boot-autoconfigure:jar:2.1.1:compile
[INFO] |  +- org.mybatis:mybatis:jar:3.5.3:compile
[INFO] |  \- org.mybatis:mybatis-spring:jar:2.0.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:provided
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:provided
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.13.1:provided
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.1:provided
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.1:provided
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:provided
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-hppc:jar:2.13.1:provided
[INFO] |  \- com.carrotsearch:hppc:jar:0.8.1:provided
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.13.1:provided
[INFO] |  \- org.json:json:jar:20190722:provided
[INFO] +- com.oracle.database.jdbc:ojdbc8:jar:19.3.0.0:compile
[INFO] |  +- com.oracle.database.jdbc:ucp:jar:21.3.0.0:compile
[INFO] |  +- com.oracle.database.security:oraclepki:jar:21.3.0.0:compile
[INFO] |  +- com.oracle.database.security:osdt_cert:jar:21.3.0.0:compile
[INFO] |  +- com.oracle.database.security:osdt_core:jar:21.3.0.0:compile
[INFO] |  +- com.oracle.database.ha:simplefan:jar:21.3.0.0:compile
[INFO] |  \- com.oracle.database.ha:ons:jar:21.3.0.0:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.10:compile
[INFO] +- org.apache.commons:commons-csv:jar:1.8:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.245:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.11.245:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.245:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.245:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.22:compile (optional)
[INFO] +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.6.4:provided
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.58:provided
[INFO] |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.58:provided
[INFO] |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.58:provided
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.6.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.6.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.6.4:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile
[INFO] |  |  +- net.minidev:json-smart:jar:2.4.8:compile
[INFO] |  |  |  \- net.minidev:accessors-smart:jar:2.4.8:compile
[INFO] |  |  |     \- org.ow2.asm:asm:jar:9.1:compile
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.21.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.0.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.11.22:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.11.22:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.0.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.16:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.16:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.16:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.8.4:test
[INFO] +- org.springframework.restdocs:spring-restdocs-mockmvc:jar:2.0.6.RELEASE:test
[INFO] |  +- org.springframework.restdocs:spring-restdocs-core:jar:2.0.6.RELEASE:test
[INFO] |  \- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] +- org.springframework.security:spring-security-test:jar:5.6.2:test
[INFO] |  \- org.springframework.security:spring-security-core:jar:5.6.2:compile
[INFO] |     \- org.springframework.security:spring-security-crypto:jar:5.6.2:compile
[INFO] \- org.apache.avro:avro-tools:jar:1.9.1:compile
[INFO]    +- org.apache.avro:avro:jar:1.9.1:compile
[INFO]    |  \- org.apache.commons:commons-compress:jar:1.19:compile
[INFO]    +- org.apache.avro:avro-compiler:jar:1.9.1:compile
[INFO]    |  \- org.apache.velocity:velocity-engine-core:jar:2.0:compile
[INFO]    +- org.apache.avro:avro-ipc:jar:1.9.1:compile
[INFO]    |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO]    +- org.apache.avro:avro-mapred:jar:1.9.1:compile
[INFO]    |  \- org.apache.avro:avro-ipc-jetty:jar:1.9.1:compile
[INFO]    |     +- org.eclipse.jetty:jetty-server:jar:9.4.45.v20220203:compile
[INFO]    |     |  +- org.eclipse.jetty:jetty-http:jar:9.4.45.v20220203:compile
[INFO]    |     |  \- org.eclipse.jetty:jetty-io:jar:9.4.45.v20220203:compile
[INFO]    |     +- org.eclipse.jetty:jetty-servlet:jar:9.4.45.v20220203:compile
[INFO]    |     |  +- org.eclipse.jetty:jetty-security:jar:9.4.45.v20220203:compile
[INFO]    |     |  \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.45.v20220203:compile
[INFO]    |     \- org.eclipse.jetty:jetty-util:jar:9.4.45.v20220203:compile
[INFO]    +- org.xerial.snappy:snappy-java:jar:1.1.7.3:compile
[INFO]    +- org.tukaani:xz:jar:1.8:compile
[INFO]    +- commons-cli:commons-cli:jar:1.4:compile
[INFO]    \- net.sf.jopt-simple:jopt-simple:jar:5.0.4:compile
	
	

### Reproduction Steps

<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.245</version>
</dependency>

<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.6.4</version>
  <relativePath/> 
</parent>

### AWS Java SDK version used

1.11.245

### JDK version used

11

### Operating System and version

windows/linux - tomcat 9

**Comment by Anchal2989** [comment]
Tried below-
org.apache.http.conn.ssl.SSLConnectionSocketFactory.class.getProtectionDomain().getCodeSource().getLocation().getPath()

library used it still - httpclient-4.5.13.jar

**Comment by ashishdhingra** [comment]
@Anchal2989 Good afternoon. Could you please share the sample project and Maven POM file to reproduce the issue?

Thanks,
Ashish

**Comment by Anchal2989** [comment]
Above solution doesn't work when deployed with whole application on tomcat.
But works when I run it it a class with main method.

import org.springframework.context.annotation.Bean;

import com.amazonaws.ClientConfiguration;
import com.amazonaws.Protocol;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

public class TestS3 {	
	
	public static void main(String[] args) {
		ClientConfiguration clientConfig = null;
		try {
			clientConfig = getClientConfig();
		} catch (Exception e) {
			e.printStackTrace();
		}

		BasicAWSCredentials creds = null;
		try {
			creds = getCredentials();
		} catch (Exception e) {
			e.printStackTrace();
		}

		AmazonS3 s3Obj = AmazonS3ClientBuilder.standard().withClientConfiguration(clientConfig)
				.withCredentials(new AWSStaticCredentialsProvider(creds)).withRegion("us-east-1").build();
	}

	@Bean
	public static BasicAWSCredentials getCredentials() {
		return new BasicAWSCredentials("", "");
	}

	@Bean
	public static ClientConfiguration getClientConfig() {
		ClientConfiguration proxyConfig = new ClientConfiguration();

		proxyConfig.setProtocol(Protocol.HTTPS);
		proxyConfig.setProxyUsername("");
		proxyConfig.setProxyPassword("");
		proxyConfig.setProxyHost("");
		proxyConfig.setProxyPort();
		proxyConfig.withGzip(true);
		proxyConfig.withSocketTimeout(750);
		proxyConfig.withConnectionTimeout(750);

		return proxyConfig;
	}

}

**Comment by roshnee99** [comment]
Hi! I can confirm that I am seeing the same issue too. 

I am using the following dependency 
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.12.221</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
        </dependency>
```
And then in my code I'm calling
```
AmazonS3ClientBuilder.standard().withRegion(Regions.US_EAST_1).build();
```
It works in a main method, however, when I launch it as a `jetty` server, I get the following exception
```
java.lang.NoSuchMethodError: 'void org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(javax.net.ssl.SSLContext, javax.net.ssl.HostnameVerifier)'
    at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init> (SdkTLSSocketFactory.java:58)
    at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory (ApacheConnectionManagerFactory.java:93)
    at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create (ApacheConnectionManagerFactory.java:66)
    at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create (ApacheConnectionManagerFactory.java:59)
    at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create (ApacheHttpClientFactory.java:50)
    at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create (ApacheHttpClientFactory.java:38)
    at com.amazonaws.http.AmazonHttpClient.<init> (AmazonHttpClient.java:347)
    at com.amazonaws.http.AmazonHttpClient.<init> (AmazonHttpClient.java:331)
    at com.amazonaws.AmazonWebServiceClient.<init> (AmazonWebServiceClient.java:239)
    at com.amazonaws.AmazonWebServiceClient.<init> (AmazonWebServiceClient.java:225)
    at com.amazonaws.services.s3.AmazonS3Client.<init> (AmazonS3Client.java:723)
    at com.amazonaws.services.s3.AmazonS3Builder$1.apply (AmazonS3Builder.java:35)
    at com.amazonaws.services.s3.AmazonS3Builder$1.apply (AmazonS3Builder.java:32)
    at com.amazonaws.services.s3.AmazonS3ClientBuilder.build (AmazonS3ClientBuilder.java:64)
    at com.amazonaws.services.s3.AmazonS3ClientBuilder.build (AmazonS3ClientBuilder.java:28)
    at com.amazonaws.client.builder.AwsSyncClientBuilder.build (AwsSyncClientBuilder.java:46)
    at org.arfna.database.s3.S3Util.<clinit> (S3Util.java:21)
```

Any help with this will be greatly appreciated!

**Comment by Anchal2989** [comment]
hi @debora-ito,
I have tried below:

- .m2 directory clean up
- build application from scratch to see at what stage with what version issue is there (for all aws library versions I am seeing the same issues)
- tried skipping core and client versions conflict, that doesn't work too.

**Comment by roshnee99** [comment]
+1 It is just very strange because it only happens in the jetty/tomcat environment and not in a main method

**Comment by debora-ito** [comment]
If it works in one environment and not in other is an indication of an environment configuration problem, not an issue with the SDK code. I won't be able to recreate it locally because of this.

Generally speaking, [`NoSuchMethodError`](https://docs.oracle.com/javase/8/docs/api/java/lang/NoSuchMethodError.html) is 

> thrown if an application tries to call a specified method of a class and that class no longer has a definition of that method.
Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

I'm not familiar with Jetty server so I cannot help with troubleshooting in it, but it looks like the dependencies on Jetty classpath are different from the dependencies used to compile the code.
