### ISSUE TITLE
ProcessCredentialsProvider does not indicate why the process failed

### ISSUE THREAD

**Issue by Avinm** [aws/aws-sdk-java#2774]
### Describe the feature

ProcessCredentialsProvider fails on non-zero exit code without providing any useful debugging info.
The provider could capture the stderr into the exception message/description

Could raise a PR to help out if this is not by design.

### Use Case

To load credentials from an external process using the `credential_process` attribute in aws config file.

### Proposed Solution

Capture the stderr into the exception message/description thrown from ProcessCredentialsProvider

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.x

### JDK version used

8

### Operating System and version

Mac OS 12.3.1

**Comment by debora-ito** [comment]
Hi @Avinm thank you for reaching out.

That's a reasonable feature request, but we are not prioritizing feature work for Java SDK v1. This has a better chance to get implemented in Java SDK v2, if it wasn't already. Let us know if having this in v is something you'd be interested in.

**Comment by Avinm** [comment]
@debora-ito : Sorry for the delayed response but yes, this is also an issue in sdv2 which is what I was using.
