### ISSUE TITLE
ExpiredTokens not refreshed for S3ClientCache / S3Link

### ISSUE THREAD

**Issue by jdamick** [aws/aws-sdk-java#278]
In using an InstanceProfile with DynamoDBMapper and an S3Link after a few hours I'm seeing:

! com.amazonaws.services.s3.model.AmazonS3Exception: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken; Request ID: BE70A766F0ED13AE)

It appears that this is due to the S3ClientCache which upon initialization it calls s3CredentialsProvider.getCredentials() from the InstanceProfileCredentialsProvider, so after a few hours these credentials become expired.  It seems that the S3ClientCache should be using the provider and calling getCredentials when it absolutely needs to so that the InstanceProfileCredentialsProvider will refresh the expired tokens..  Or perhaps I'm misunderstanding or doing something wrong?

See:

https://github.com/aws/aws-sdk-java/blob/8d1cf00d8ca141880995f02c8f74997fe8289f7e/aws-java-sdk/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.java#L335

**Comment by pcssi** [comment]
:+1:

**Comment by manikandanrs** [comment]
This has been fixed. 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.java#L391

Feel free to reopen if you still face issues.
