### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by ade90036** [aws/aws-sdk-java#2784]
### Describe the bug

I'm exploring the use of transfer manager to perform multipart upload and download of large files. 

Apart from the obvious, seen a huge performance benefits of parallelizing uploads via concurrent connection and also the ability to resume the upload, I'm experiencing some issues with the multipart download.

I have a number of legacy files which have been uploaded before multi-part upload was put in place and some multi-part uploaded files which have been newly created. 

Multipart download works fantastically on multipart uploaded files, however on `legacy` files is not working.

For the moment i'm qualifying `legagy` files as files which were uploaded using a single `PUT` request and not using multipart upload

### Expected Behavior

What i believe it should happen if I provided the `setMinimumUploadPartSize` and `setMultipartUploadThreshold` that the transfer should dynamically calculate a new `partCount` and use this to multipart download the file in parallel connection using a number of concurrent GET requests with Range.

This also bring in the question why we would want the multipart download to re-use the same `multiPartSize` and `partCount` used during the upload if, for example, we are downloading from EC2 instance where we may want jumbo multipart size to allow to utilize the full bandwidth of the multi gigabit connection?

### Current Behavior

What I'm experiencing is when the `legacy` files which were upload using a single PUT request  are download with the transfer manager and multipart enable, a single request is processed, which is a GET request with range 0:(filesize).

### Reproduction Steps

will provide some later.. 

### Possible Solution

From what i can see the `TransferManager` established if the download can happen in parallel by calling the 

```
GetObjectMetadataRequest getObjectMetadataRequest = requestCopyUtils.createGetObjectMetadataRequestFrom(getObjectRequest)
                .withPartNumber(1);

return s3.getObjectMetadata(getObjectMetadataRequest).getPartCount();
    
```

When i'm downloading a `legagy` file this returns null for me which then trigger the `TransferManager` to set

```
final boolean isDownloadParallel = !configuration.isDisableParallelDownloads()
                && TransferManagerUtils.isDownloadParallelizable(s3, getObjectRequest, ServiceUtils.getPartCount(getObjectRequest, s3));

//isDownloadParallel == false

```

### AWS Java SDK version used

1.12.240

### JDK version used

openjdk version "17.0.3" 2022-04-19

### Operating System and version

ubuntu 22.04

**Comment by debora-ito** [comment]
Hi @ade90036 thank you for reaching out.

> Multipart download works fantastically on multipart uploaded files, however on legacy files is not working.

Yes, that's a limitation of the TransferManager v1. 
Have you tried running the Java SDK v2 TransferManager? The download is not restricted anymore by the way the upload was made. Note that TransferManager v2 is still in Developer Preview but we are actively working towards GA. More info in our Blog - https://aws.amazon.com/blogs/developer/introducing-amazon-s3-transfer-manager-in-the-aws-sdk-for-java-2-x.
