### ISSUE TITLE
Cloudwatch Dimensions don't implement withName().withValue(), they alias them to setName() and setValue()

### ISSUE THREAD

**Issue by ebrandsberg** [aws/aws-sdk-java#2785]
### Describe the bug

Cloudwatch dimensions appear to only accept the last dimension.  Given the following dimension, you would expect both dimensions to be available:

        Dimension dimension = new Dimension().
        		withName("VDB").withValue(vdb).
        		withName("InstanceId").withValue(CloudUtils.getInstanceID());

However, in this code, only the second dimension "InstanceId" is actually honored.

Looking at the code for Dimension "withName", which should add to a list of names, it is instead calling "setName" which sets a single name:

    public Dimension withName(String name) {
        setName(name);
        return this;
    }

As such, it appears that withName is actually just an alias of setName, and the Java SDK doesn't support sending more than one dimension at once despite documentation of this capability.

### Expected Behavior

Both dimensions should have the data logged against it.

### Current Behavior

Only the last dimension chained using "withName" and "withValue" show up in the statistics

### Reproduction Steps

Dimension dimension = new Dimension().
        		withName("VDB").withValue(vdb).
        		withName("InstanceId").withValue(CloudUtils.getInstanceID());
PutMetricDataRequest request = new PutMetricDataRequest().withNamespace(NAMESPACE).withMetricdata(new MetricDatum().withMetricName("metric").withUnit(StandardUnit.Percent).withValue(value).withDimensions(dimension));

PutMetricDataResult response = cw.putMetric(request);

### AWS Java SDK version used

1.12.240

### JDK version used

Irrelevent, the SDK code is clearly not coded to support this feature

### Operating System and version

Irrelevent, the SDK code is clearly not coded to support this feature

**Comment by debora-ito** [comment]
Hi @ebrandsberg the Dimension type only takes one dimension. If you want to provide more than one Dimension, the MetricDatum takes a collection of Dimension:

```java
PutMetricDataRequest request = new PutMetricDataRequest()
        .withNamespace(NAMESPACE)
        .withMetricData(
                new MetricDatum()
                        .withMetricName("metric")
                        .withUnit(StandardUnit.Percent)
                        .withValue(value)
                        .withDimensions(dimension1, dimension2));
```

For reference: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatch/model/MetricDatum.html

**Comment by ebrandsberg** [comment]
> ```java
> withDimensions(dimension1, dimension2));
> ```

If this is so, the help for withName should indicate this limitation and provide guidance on how to specify multiple dimensions.
