### ISSUE TITLE
All requests fail after DynamoDB connection pool errors

### ISSUE THREAD

**Issue by turbotrb** [aws/aws-sdk-java#2788]
### Describe the bug

After a few days of working fine, our server will fail to respond to any requests.  The solution so far has been to restart the app, and it will then run for a few days again.

In the logs, we are getting "connection pool shut down" error messages.  Exceptions get thrown when we try to make a call into DynamoDB.  I've attached examples of one of the function calls we get this exception from as well as the exception error message

[ErrorMessage.txt](https://github.com/aws/aws-sdk-java/files/8937934/ErrorMessage.txt)
[GetGamesFunction.txt](https://github.com/aws/aws-sdk-java/files/8937936/GetGamesFunction.txt)
.

This problem began when we upgraded to Java SDK 2.  We've been running fine with Java SDK 1 for at least 4 years and never had a problem.

We've tried a few things to try fixing the problem like changing the instance size from t2.medium to t3.large, changing the heap size, and opening and closing the DynamoDB connection after each request.  We were getting some out of memory errors at one point that seemed to be fixed with the heap size change.  Also going to the large instance seemed to improve the connection pool problem.  Instead of taking 4 days or so for the server to start failing completely, the large instance can go maybe 2 weeks or a little more.  But the exceptions will eventually return so it isn't a real solution.

In the example I gave above, we are doing a batch get.  In our batch get, we will retrieve no more than 30 objects in a single request.  Also those objects should be no more than 2000 bytes, usually much less.  So I believe we are well within the restrictions for the number of objects and number of bytes queried in a single request.

### Expected Behavior

Server requests can operate indefinitely without getting connection pool shut down errors.  The server doesn't need to be restarted every few days because it fails to respond to any requests.

### Current Behavior

I've included an example of the error message above.  Here is a more complete set of logs. 
 
These are older logs before I added printing out of the full call stack when an exception occurs.  Unfortunately, I recently restarted the server and don't have a more up to date set of logs with these errors.  But I can probably send you some in the next couple days.

### Reproduction Steps

The code included above should be able to reproduce it given enough time for it to run.  You'll just need to pass in the IDs for about 20 objects for it to retrieve from the database table.  This function is called from a Java HttpServlet-derived class.

### AWS Java SDK version used

2.17.144

### JDK version used

1.8

### Operating System and version

Tomcat 8.5 with Corretto 8 running on 64bit Amazon Linux 2/4.2.15

**Comment by debora-ito** [comment]
`java.lang.IllegalStateException: Connection pool shut down` can happen if the client is closed by some part of the system by calling close() (which closes the underlying connection pool), but some other part of the system continues to try and use that client to make requests.

Check if the client isn't being closed either directly or indirectly. Are you using Spring? For example, Spring `@Bean` will automatically close objects if the have a close() or shutdown() method: https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html#destroyMethod--

**Comment by turbotrb** [comment]
I'm not using Spring.  The application is just a Java app with a bunch of HttpServlets running on Tomcat.

I don't know what could be causing the client to shut down.  The configuration is the same as it was with my Linux 1 / Java SDK 1 environment that never had this problem.  Is there anything you can think of that would be doing that for a non-Spring application?

Thanks.

**Comment by debora-ito** [comment]
The SDK will not shut down connection pools that are in use, so I can't think of anything else other than something closing the client indirectly. Have you tried looking for clues in the client-side metrics?

**Comment by turbotrb** [comment]
What kind of client side metrics would you suggest looking at?

I've attached some more recent logs in case that might help.  It has a few of the connection pool shut down exceptions.  But so far it hasn't resulted in the server failing completely to respond to other requests.  So I'm not sure if the connect pool error is the culprit causing the server to die.  But it is the only exception that I've seen.

I also thought the DynamoDB batch get calls were the problem, but there are a few of the exceptions in this log where it was doing a simple getItem call.

One change I made in trying to diagnose this was to close the DynamoDbClient after completing each HttpServlet request.  Originally, I had left the DynamoDbClient open and tried to reuse it for each request.  I think each HttpServlet had its own DynamoDbClient instance in the original case though so there were maybe 10 instances for the entire application.  What is the best way to reuse DynamoDbClient?  Should I close it after every request like it is doing now?  Could this be contributing to the connection pool error?

Is there any other information I could provide you that might help?

Thank you.

**Comment by turbotrb** [comment]
Here are the logs.

[BundleLogs-1655873805460.zip](https://github.com/aws/aws-sdk-java/files/8954541/BundleLogs-1655873805460.zip)

**Comment by debora-ito** [comment]
I was talking about the SDK client-side metrics - https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/

> Should I close it after every request like it is doing now?

The recommended way is to reuse the client whenever possible. Each client will manage it's own connection pool.

> Could this be contributing to the connection pool error?

Did you see any changes after closing the client after each request?

**Comment by turbotrb** [comment]
I've added the enable default metrics parameter to the JVM options.  I'll see if it returns any useful data.  Thanks for the suggestion.  Are there any particular metrics that you suggest looking at?  What exactly are the other metrics this option enables?  What kinds of things do you see when you have experienced problems like the one I'm having?  I don't really have much experience with CloudWatch or these particular JVM metrics so I could use some suggestions.

I didn't see any changes after closing the client after each request.  The server seemed to fail completely after about the same amount of time.  I was thinking about trying to share one client object among all requests and leaving it open.  It seems like at best it would just be delaying the inevitable failure, but I don't have much else to try.

**Comment by debora-ito** [comment]
I'm sorry, I see now that you're having problems using Java SDK v2, the link for v2 client-side metrics instructions is this - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics.html.

The list of available metrics can be found [here](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics-list.html).

To be honest, I don't know exactly what to look for. I would enable the metrics and look for any patterns in LeasedConcurrency and PendingConcurrencyAcquires or in ApiCallDuration for example, but I understand that it can take a week for the exception to appear.

**Comment by turbotrb** [comment]
Thanks for the SDK v2 instructions for getting client-side metrics.  I've turned them on for all DynamoDB calls.  I'll let you know what kind of information I get when the problem occurs again.

I also have a case open about this issue in the AWS Support Center.  They recommended that I focus the discussion here since this is a direct line to the SDK team.  So I'll give a little more info about what was discussed there.

Someone in the support center case was thinking maybe the problem was an out of memory condition not being handled correctly.  I have seen an out of memory error before, and that would seem to match how I see the server fail more frequently when using an instance type with less memory.

They asked if I was doing any handling of the out of memory error.  I don't have any code that handles that specific error.  So it seems like the default handler in the virtual machine will get called.  They pointed out the line of code in Apache where it would shut down the connection pool in this case.
https://github.com/apache/httpcomponents-client/blob/6a741b4f8f23e6c5c7cc42c36c2acabfac19c3d6/httpclient/src/main/java/org/apache/http/impl/execchain/MainClientExec.java#L368

So is it recommended to handle this error to prevent this or does letting Apache handle it allow it to recover from the error better?

Thanks.

**Comment by turbotrb** [comment]
Also do you have any ideas why the application would be using more memory running on a Linux2 instance using AWS Java SDK 2 versus a Linux 1 instance using AWS Java SDK 1?  Our server ran fine for 4 or 5 years without failing or noticeable OOM errors, but starting having problems moving to Linux2.  The application code is identical except for the changes needed to upgrade to AWS Java SDK 2.  Thanks.

**Comment by debora-ito** [comment]
I see your Support ticket :) Github issues and Support Cases regarding the Java SDK are responded by the same team in the end. To avoid duplicate efforts I'll mark this to close soon, please send your questions through the Support case.

I don't have the answer for your question about Linux2 memory. I believe we do have some benchmarks, but don't have details comparing Java SDK v1 vs. v2 in different Linux distros.

**Comment by turbotrb** [comment]
Hi Debora,

Thanks for following up and for the new information in the support center.  I tried the OOM suggestion and made a change to how the DDB client is created to see if that helps with the problems.  I added details to the support case if you want more information.

Thanks.

**Comment by desperateBob** [comment]
Hi.
I am experiencing the same issue.
@turbotrb Did you solve the issue?
Can you please share a link to a support case you've opened (if it's public)?

Thanks

**Comment by turbotrb** [comment]
Yes and no, in regards to solving the issue. It still happens for me if I wait long enough. But the problem is much better. 

The main thing I did is reduce the number of connections to AWS services I have open. I now just have 1 for DynamoDB and 1 for push notifications. These two connections are shared with every HttpServlet who needs to access them. 

This seemed to increase the time before failing to several weeks when it used to be several days. So the problem is vastly improved. But there still seems to be some instability in the AWS services eventually shutting down the connection pool and trashing all further requests. Sometimes I saw out of memory errors and sometimes I didn’t. I never saw any spikes in memory usage when failures happened. Plus my requests are so simple and low memory that I just don’t see what can be happening other than the AWS services doing something weird. 

But definitely sharing AWS services as much as possible helped. Hopefully this helps your solve your problems.

**Comment by muhammadsr** [comment]
I am having the same issue here. I started to experience this just today. Here is the stack trace:

```
Connection pool shut down\n\tat org.apache.http.util.Asserts.check(Asserts.java:34)\n\tat org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)\n\tat sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)\n\tat com.amazonaws.http.conn.$Proxy46.requestConnection(Unknown Source)\n\tat org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)\n\tat org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)\n\tat org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)\n\tat org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n\tat org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)\n\tat com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1343)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)\n\tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)\n\tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)\n\tat com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6243)\n\tat com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6210)\n\tat com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeGetItem(AmazonDynamoDBClient.java:3199)\n\tat com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:3163)\n\tat com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:432)\n\tat com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:449)\n\tat com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.load(AbstractDynamoDBMapper.java:80)\n\ta
```

Any advice is appreciated!

**Comment by saratbhaswanth** [comment]
I know this is a old issue, But is there any fix that is release yet? We are also facing the same issue..

**Comment by kkinvincible007** [comment]
same here. I am also facing this. @muhammadsr @turbotrb Any resolution for this issue? Anything would be really helpful. Thanks!

**Comment by turbotrb** [comment]
I think AWS must have fixed something.  When I responded above with some of the things above that helped, I was still having to restart the server after it stopped responding after a couple months.  But then magically about a year ago, I no longer needed to do that.  So I think AWS had a bug and then fixed it.  I never got any communication they fixed anything.  The server just continued to work without me having to restart it.  So probably not the answer you were hoping for.  Good luck.
