### ISSUE TITLE
chime messaging "Sensitive Data Redacted"

### ISSUE THREAD

**Issue by infra-betamonks** [aws/aws-sdk-java#2791]
### Describe the issue

We have created the chime messaging instance and channel arn successfully and we are able to send messages to the channel using send messages api..
when we try to list the messages in the channel using list messages api 
we are content the content as "**Sensitive Data Redacted**"

is it possible to get the original content of the each messages ? 

below is the sample content we have received from the list messages api 

{MessageId: 13c1a39e42eda2d4e6625b8f45c158fd629094cac127aae8303ecb3457453692,Content: ***Sensitive Data Redacted***,Type: STANDARD,CreatedTimestamp: Mon Apr 25 14:59:44 IST 2022,LastUpdatedTimestamp: Mon Apr 25 14:59:44 IST 2022,Sender: {Arn: arn:aws:chime:us-east-1:104579719335:app-instance/61b9ee9b-74e3-4620-93dc-8b6e8e8c88a4/user/aws-psq-backend-worker,Name: ***Sensitive Data Redacted***},Redacted: false}

### Links

https://docs.aws.amazon.com/chime-sdk/latest/dg/send-messages.html
https://docs.aws.amazon.com/chime/latest/APIReference/API_ListChannelMessages.html

**Comment by debora-ito** [comment]
I couldn't find anything in the Chime SDK docs that indicate what could redact the message content and the sender name. The `Redacted` field being false means that [RedactChannelMessage](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_RedactChannelMessage.html) was not called.

Maybe the content is being changed by a Channel Flow? https://docs.aws.amazon.com/chime-sdk/latest/dg/using-channel-flows.html
