### ISSUE TITLE
{geo, us-east-2} was not found in region metadata

### ISSUE THREAD

**Issue by egypttoc** [aws/aws-sdk-java#2805]
### Describe the bug

Warning in logs

 c.a.i.DefaultServiceEndpointBuilder      : {geo, us-east-2} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'geo.us-east-2.amazonaws.com'.

### Expected Behavior

no warning and correct geo region is selected

### Current Behavior

 this warning in the logs

 c.a.i.DefaultServiceEndpointBuilder      : {geo, us-east-2} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'geo.us-east-2.amazonaws.com'.

### Reproduction Steps

sample code to reproduce

AmazonS3ClientBuilder
                .standard()
                .withRegion(Regions.US_EAST_2)
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .build();

### AWS Java SDK version used

1.11.931

### JDK version used

11

### Operating System and version

centos 7

**Comment by egypttoc** [comment]
> @egypttoc where's the `geo` coming from? Is it for the [Amazon Location service](https://docs.aws.amazon.com/location/latest/developerguide/location-regions.html)?

Yes it’s the Amazon Location Service using the sample code provided above

**Comment by debora-ito** [comment]
To access the Location endpoints you need to use the `AmazonLocation` client, not the S3 client. `geo` is part of the hostname, not the region.

```
AmazonLocation client = AmazonLocationClient.builder()
                .build();

client.listMaps(new ListMapsRequest());
```
