### ISSUE TITLE
(Short term workaround): Temporarily omit TLS 1.3 from SDK enabled protocols.

### ISSUE THREAD

**Issue by neerajgupta23745** [aws/aws-sdk-java#2810]
### Describe the issue

TLS 1.3 Incompatibility with AWS SDK for Java versions 1.9.5 to 1.10.31
As we are trying to increase version for aws-java-sdk but certain Jar file and war file for toccatas. From below Link we got the workaround to bypass TLS1.3  but still we did not get any workaround for war file.Will you please provide some workaround for war file.

https://aws.amazon.com/blogs/developer/tls-1-3-incompatibility-with-aws-sdk-for-java-versions-1-9-5-to-1-10-31/#:~:text=The%20SDK%20version%20and%20JDK%20version%20are%20also%20included%20the%20User%2DAgent%20header%20of%20the%20HTTP%20requests%20made%20by%20the%20SDK%20so%20you%20can%20also%20query%20your%20CloudTrail%20logs%20to%20see%20if%20you%20are%20making%20API%20calls%20with%20the%20affected%20SDK%20version

java -Djdk.tls.client.protocols="TLSv1.2" -jar my-app.jar

### Links

https://aws.amazon.com/blogs/developer/tls-1-3-incompatibility-with-aws-sdk-for-java-versions-1-9-5-to-1-10-31/#:~:text=The%20SDK%20version%20and%20JDK%20version%20are%20also%20included%20the%20User%2DAgent%20header%20of%20the%20HTTP%20requests%20made%20by%20the%20SDK%20so%20you%20can%20also%20query%20your%20CloudTrail%20logs%20to%20see%20if%20you%20are%20making%20API%20calls%20with%20the%20affected%20SDK%20version

**Comment by debora-ito** [comment]
For `war` files you need to consult the documentation of the web server you are using.

**Comment by shiranyosef1** [comment]
Hello @debora-ito,

I wanted to ask if the `Djdk.tls.client.protocols="TLSv1.2"` setting is being strictly enforced. I noticed in the [code snippet](https://github.com/aws/aws-sdk-java/blob/e80cdf3acf15ae9595220de8f653f36132bc26a5/aws-java-sdk-core/src/main/java/com/amazonaws/http/conn/ssl/SdkTLSSocketFactory.java#L95) that the supported protocols are concatenated with the enabled ones. If I want to ensure that TLSv1.1 and TLSv1 are not used, how can I achieve this? Thank you for your assistance.
