### ISSUE TITLE
S3: unclear what storage class to use for "Glacier Flexible Retrieval"

### ISSUE THREAD

**Issue by emilburzo** [aws/aws-sdk-java#2811]
### Describe the issue

Hi,

I'm trying to upload files to S3 with the `Glacier Flexible Retrieval (formerly Glacier)` storage class (as named in the web UI)

However, looking through the [StorageClass enum](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/StorageClass.java#L33-L97), it's not clear if I should be using `GLACIER` (as hinted by the "formerly" in the web UI) or if there should be a new enum?

Thank you.

### Links

- https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/StorageClass.java#L33-L97
- https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/StorageClass.html

**Comment by debora-ito** [comment]
I'd say that you should use `GLACIER`, since the other two Glacier flavors are in the enum (`GlacierInstantRetrieval` and `DeepArchive`).

I'll reach out to the documentation team and ask to update the enum description with the same wording used in the documentation and UI.

**Comment by debora-ito** [comment]
Closing this, there's no pending actions from the SDK team.
