### ISSUE TITLE
AWS SDK v2 EC2MetadataUtils.IamSecurityCredentials class missing in v2.17.233

### ISSUE THREAD

**Issue by damienborowski** [aws/aws-sdk-java#2817]
### Describe the issue

Any idea what it's replacement class is, or how in this version are we meant to get the tokens, access keys etc ? I see it's 'back' in 2.9.9 but we can't use this unfortunately.

Docs for V.1: [docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/util/EC2MetadataUtils.html)
Docs for V2.0.0: [docs](https://sdk.amazonaws.com/java/api/2.0.0/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.html#getIamSecurityCredentials)

Index for V2.17.233 : [index](https://javadoc.io/doc/software.amazon.awssdk/regions/2.17.233/index-all.html#I:I)
you can try to find the IamSecurityCredentials but it's no longer there

We can see that in V.1 that the IamSecurityCredentials class is there but in V.2 versions ( > 2.9.9 ) it is no longer there. I might of been moved but i cannot find any docs regarding this.

### Links

N/a

**Comment by yasminetalby** [comment]
Hello @damienborowski ,

We are not supporting the [EC2MetadataUtils.IamSecurityCredential](https://javadoc.io/static/software.amazon.awssdk/regions/2.16.104/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.IamSecurityCredential.html) class anymore. 

There's a feature request to create a public-facing EC2 Metadata Client, we are tracking here: https://github.com/aws/aws-sdk-java-v2/issues/61. Make sure you add a 👍 in the original description if you want to support it.

Is there a specific reason why you would need to use EC2MetadataUtils.IamSecurityCredentials?
If you are using IAM Security Credential in the AWS Java SDK V2 you can follow the developer guide documentation : https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/ec2-iam-roles.html

Best,

Yasmine
