### ISSUE TITLE
SWF  PeriodicWorkflowTest not passing

### ISSUE THREAD

**Issue by gdogaru** [aws/aws-sdk-java#282]
could not run the example,
What I got was com.amazonaws.services.simpleworkflow.flow.examples.periodicworkflow.PeriodicWorkflowImpl#callPeriodicActivity being called in a loop

**Comment by breedloj** [comment]
Closing this due to the age of the issue and the fact that this library has seen considerable changes in the interim.  Please feel free to re-open or create a new issue if you continue to have problems.
