### ISSUE TITLE
Using AWS-Java-SDK-S3, return to Inform Error 501 Not Implemented when uploading files

### ISSUE THREAD

**Issue by fantastic2085** [aws/aws-sdk-java#2820]
### Describe the bug

Upload files to the CEPH object store using AWS-java-SDK-S3, Using AWS-Java-SDK-S3, return to Inform Error 501 Not Implemented when uploading files

### Expected Behavior

I hope I can upload the file successfully

### Current Behavior

An error is as follows:
![image](https://user-images.githubusercontent.com/4116773/182996175-05388783-151e-4418-bda7-e740bd8b45e9.png)

### Reproduction Steps

s3 client The following code:
![image](https://user-images.githubusercontent.com/4116773/182996017-dd2e2459-2054-4899-8e82-72b9874a8146.png)

AWS-Java-SDK-S3 version:
![image](https://user-images.githubusercontent.com/4116773/182996107-2f2c118d-766a-4ffd-b4d4-32b2e60f6a08.png)

The code to upload the file is as follows:
![image](https://user-images.githubusercontent.com/4116773/182996158-78cce6a3-0d58-48c6-911d-398379aef75f.png)

### AWS Java SDK version used

1.11.1030

### JDK version used

1.8.0_341

### Operating System and version

4.19.90-25.16

**Comment by yasminetalby** [comment]
Hello @fantastic2085 ,

Thank you very much for your message.
An error 501 means that a header that you provided implies functionality that is not implemented.
Unfortunately, we do not offer support/troubleshooting for error which arise due to the use of third party.
If the SDK flags an exception caused by your use of CEPH we do not cover third party compatibility issues.

It seems that CEPH offers [documentation on example syntax for S3 with Java SDK ](https://docs.ceph.com/en/latest/radosgw/s3/java/). It might be useful to compare your approach if it matches your use case. 

Best,
Yasmine

**Comment by fantastic2085** [comment]
[documentation on example syntax for S3 with Java SDK ](https://docs.ceph.com/en/latest/radosgw/s3/java/), This CEPH website has been seen, you also see the implementation code, basically and CEPH website is the same. It is possible to use s3cmd and Python, but not Java @yasminetalby

**Comment by yasminetalby** [comment]
Hello @fantastic2085 ,

Thank you very much for your answer.
The issue you are encountering is not SDK or service related as the type of request you are attempting successfully complete with AWS endpoints.
CEPH being a third-party service, we recommend you to [reach out](https://tracker.ceph.com/projects/ceph) to the CEPH support team for any guidance or troubleshooting. 


Best,

Yasmine

**Comment by fantastic2085** [comment]
If CEPH is the problem, why is s3cmd OK?

this s3cmd http header:
![image](https://user-images.githubusercontent.com/4116773/184269908-21851f72-7c3d-4184-a8e1-2bbfbe24f3f7.png)

this java s3 http header:
![image](https://user-images.githubusercontent.com/4116773/184269949-d4a466ba-99bb-4a39-a653-6fc29f01eb6e.png)

**Comment by fantastic2085** [comment]
I provide enough information, your answer makes me very helpless @yasminetalby

**Comment by debora-ito** [comment]
Hi @fantastic2085 I'm sorry you're feeling frustrated with this, but both `s3cmd` and `CEPH` are tools that are not maintained by AWS teams. We guarantee that the AWS SDK for Java clients will work when communicating directly with AWS endpoints, but we cannot guarantee it will work when the communication goes throw a third-party service. 
The best thing you can do is to reach out to CEPH support team.
