### ISSUE TITLE
aws-java-sdk-apigatewaymanagementapi 1.12.277 POM file is missing in maven central

### ISSUE THREAD

**Issue by rpalcolea** [aws/aws-sdk-java#2821]
### Describe the bug

https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-apigatewaymanagementapi/1.12.277/aws-java-sdk-apigatewaymanagementapi-1.12.277.pom returns 404

### Expected Behavior

https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-apigatewaymanagementapi/1.12.277/aws-java-sdk-apigatewaymanagementapi-1.12.277.pom should return the proper POM file

### Current Behavior

https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-apigatewaymanagementapi/1.12.277/aws-java-sdk-apigatewaymanagementapi-1.12.277.pom

is returning 404s

```
< HTTP/2 404
< last-modified: Wed, 10 Aug 2016 15:08:35 GMT
< etag: "1fb066da6a67c7c02962f59b4b8cd1ee"
< x-amz-error-code: NoSuchKey
< x-amz-error-message: The specified key does not exist.
< x-amz-error-detail-key: maven2/com/amazonaws/aws-java-sdk-apigatewaymanagementapi/1.12.277/aws-java-sdk-apigatewaymanagementapi-1.12.277.pom
< content-type: text/html
< via: 1.1 varnish, 1.1 varnish
< accept-ranges: bytes
< date: Tue, 09 Aug 2022 20:03:00 GMT
< age: 74559
< x-served-by: cache-iad-kcgs7200149-IAD, cache-lax10645-LGB
< x-cache: HIT, HIT
< x-cache-hits: 1, 1
< x-timer: S1660075381.980103,VS0,VE1
< content-length: 554
```

Wondering if there is/was an issue while publishing the new version or something on Sonatype's side

### Reproduction Steps

```
curl -v https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-apigatewaymanagementapi/1.12.277/aws-java-sdk-apigatewaymanagementapi-1.12.277.po
```

### AWS Java SDK version used

1.12.277

### JDK version used

doesn't apply

### Operating System and version

doesn't apply

**Comment by yasminetalby** [comment]
Hello @rpalcolea ,

Thank you very much for your submission.
We are currently investigating this issue. I will update you here.

Best,

Yasmine

**Comment by rpalcolea** [comment]
Hi @yasminetalby , yeah absolutely. We went ahead and did that :) just wanted to bring this up. It might be ok if you mark this as won't solve but at least folks can understand that something was/is wrong 👍 

Thanks for looking into this

**Comment by yasminetalby** [comment]
Thank you very much for bringing this up @rpalcolea !
This is very valuable to the team.

Best regards,

Yasmine

**Comment by yasminetalby** [comment]
Update: For anyone who encountered this issue please use version 1.12.278 or later versions.
The team will investigate the source of this discrepancy in the release to prevent it from happening in the future.

Best,

Yasmine.
