### ISSUE TITLE
Service: AmazonPinpoint; Status Code: 400 when scheduling campaign with timezone

### ISSUE THREAD

**Issue by p611159** [aws/aws-sdk-java#2836]
### Describe the bug

When launching a campaign, the time zone set in the Schedule is ignored and 400 error is thrown. I set the timezone to UTC-4 and have confirmed that the correctly scheduled campaign is created with the correct timezone, but if the request is being scheduled within 4 hours of the current time, then the exception below is thrown.

com.amazonaws.services.pinpoint.model.BadRequestException: StartTime must be at least current time. (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException;

It looks like date is still being compared to UTC instead of UTC-4

### Expected Behavior

schedule.withTimezone("UTC-4") should allow campaigns to be scheduled for any time in the future using the time zone supplied, not UTC.

### Current Behavior

schedule.withTimezone("UTC-4")

Attempt to schedule a campaign an hour or two in the future. 

com.amazonaws.services.pinpoint.model.BadRequestException: StartTime must be at least current time. (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException;

### Reproduction Steps

schedule.withTimezone("UTC-4")

Attempt to schedule a campaign an hour or two in the future. 

com.amazonaws.services.pinpoint.model.BadRequestException: StartTime must be at least current time. (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException;

### AWS Java SDK version used

1.12.230

### JDK version used

11

### Operating System and version

LAMBDA

**Comment by debora-ito** [comment]
@p611159 can you provide a full sample code I can use to reproduce?

It's weird that the operation returned an error but still scheduled the campaign.

**Comment by p611159** [comment]
It seems to only schedule the campaign if it is outside the window of time where the bad comparison is occurring. For my example I am using UTC-4. If I schedule for more than 4 hours past the current time in UTC, then it works. In this example say EDT scheduled time is 4PM and current time is 2PM EDT which is 6PM UTC, it will fail with **StartTime must be at least current time.**  
It should be allowing the scheduling but it appears to be comparing dates only in UTC.

**Comment by p611159** [comment]
Here is code

      ` String DEFAULT_TIME_ZONE = "UTC-04"
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM-dd-yyyy-HH-mm-ss");
        LocalDateTime launchDateTime = LocalDateTime.parse(launchDateStr, formatter);
        launchDateTime.atZone(ZoneId.of(DEFAULT_TIME_ZONE));
        LocalDateTime now = LocalDateTime.now(ZoneId.of(DEFAULT_TIME_ZONE));

        if (launchDateTime.isBefore(now))
        {
            campaignScheduleStartTime = PinpointConstants.PINPOINT_LAUNCH_IMMEDIATE;
        }
        else
        {         
            campaignScheduleStartTime = launchDateTime.toString();    
        }

        //Set the schedule
        Schedule schedule = new Schedule()
                .withStartTime(campaignScheduleStartTime);
            schedule.withFrequency(Frequency.ONCE);
            schedule.withTimezone(PinpointConstants.DEFAULT_TIME_ZONE);`

**Comment by debora-ito** [comment]
Thank you for the repro code. A couple of notes:

1- `launchDateTime.atZone()` does not modify the original object, you need to work with the returned value:
```Java
ZonedDateTime launchDateTime = LocalDateTime.parse(launchDateStr, formatter)
        .atZone(ZoneId.of(DEFAULT_TIME_ZONE));
```
2- When it's time to use the launchDateTime in the Schedule, you can format to include the timezone in the timestamp:
```Java
Schedule schedule = new Schedule()
        .withStartTime(launchDateTime.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME))
        .withFrequency(Frequency.ONCE)
        .withTimezone(DEFAULT_TIME_ZONE);
```

This way Pinpoint will validate the start time correctly.

I see how this is confusing (for example, why the validation does not use the Timezone setting?) and the[ Pinpoint API reference](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-campaigns-campaign-id.html#apps-application-id-campaigns-campaign-id-properties) does not mention specifically the format of the StartTime, I'll contact the Pinpoint Documentation team and ask to make the reference more clear.

**Comment by p611159** [comment]
Ah I see. Validation is only using the date string which does not contain the time zone. yes, it was confusing because it scheduled in EDT through all our tests until we scheduled close to the current time. Thanks for the info!
