### ISSUE TITLE
Multiple conditions on a single attribute DynamoDBSaveExpression

### ISSUE THREAD

**Issue by anujbansal16** [aws/aws-sdk-java#2844]
### Describe the feature

Since we have `Map<String, ExpectedAttributeValue>` as an argument of the expectation of the `DynamoDBSaveExpression` means that we cannot implement multiple conditions on a single attribute.
Please implement this. 
Or please suggest a way to do it. I have described the usecase below.

### Use Case

With DynamoDBMapper i want to create a condition expression before updating a item such that for `Attribute A`
```
If (A does not exist || (A <less_than> newA ))
    save(item, saveExpression)
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

aws-java-sdk-dynamodb-1.12.131

### JDK version used

1.8.0_282

### Operating System and version

Mac OS Big Sur 11.3.1

**Comment by debora-ito** [comment]
Hey @anujbansal16 thank you for reaching out.

DynamoDB Mapper probably won't get new features after the release of the DynamoDB Enhanced Client in the SDK 2.x. I believe this use case is supported in the Enhanced Client with the use of [Expressions](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/Expression.html). So if you're able to migrate to 2.x, please try it out and let us know if you have any feedback.
