### ISSUE TITLE
Incorrect documentation for com.amazonaws.services.cloudfront.model.InvalidationBatch

### ISSUE THREAD

**Issue by 4th-line** [aws/aws-sdk-java#285]
For the parameter "callerReference", the documentation says : 
"If the CallerReference is new (no matter the content of the Path object), a new distribution is created.

Not a distribution, an invalidation.
See http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/InvalidationBatchDatatype.html

**Comment by manikandanrs** [comment]
Thanks for pointing this out. The documentation is fixed in the latest SDK.
