### ISSUE TITLE
AmazonS3Client: Unable to execute HTTP request: The target server failed to respond

### ISSUE THREAD

**Issue by riteshmaurya** [aws/aws-sdk-java#2870]
### Describe the bug

Hi there,
 We're having intermittent issue when uploading files to S3. We're using Java SDK v1 on top of Springboot app.
We're suspecting that the issue could be triggered by having an HTTP(S) proxy, so we want to exclude the S3 in the proxy but
somehow the logs shows it's still using the HTTP(S) proxy.
We are using retry-mode standard, so it is catching the exceptions, but still some time its is failing ultimately.

### Expected Behavior

Put object call should succeed if there is no network issue.

### Current Behavior

Here's out setup:
- EKS cluster private setup
- S3 using Gateway endpoints - ( .ap-southeast-2.amazonaws.com )
- Application Pod (Springboot with Java SDK v1)
Below is the ENV variables for proxy(see the (no|NO)_(p|P)roxy) :
HTTPS_PROXY=http://proxy.elb.ap-southeast-2.amazonaws.com:3128
no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com,10.0.0.0/8,172.20.0.0/16,.bucket.s3.ap-southeast-2.amazonaws.com,.ap-southeast-2.amazonaws.com,10.174.0.0/21,10.169.0.0/21,10.161.0.0/21,.com.amazonaws.ap-southeast-2.s3
NO_PROXY=localhost,127.0.0.1,localaddress,.localdomain.com,10.0.0.0/8,172.20.0.0/16,.bucket.s3.ap-southeast-2.amazonaws.com,.ap-southeast-2.amazonaws.com,10.174.0.0/21,10.169.0.0/21,10.161.0.0/21,.com.amazonaws.ap-southeast-2.s3
https_proxy=http://proxy.elb.ap-southeast-2.amazonaws.com:3128
http_proxy=http://proxy.elb.ap-southeast-2.amazonaws.com:3128
HTTP_PROXY=http://proxy.elb.ap-southeast-2.amazonaws.com:3128
Below is the Java code with override:
  public AmazonS3 amazonS3Client() {
    return AmazonS3ClientBuilder
        .standard()
        .withClientConfiguration(
            new ClientConfiguration()
                .withRetryPolicy(PredefinedRetryPolicies
                    .getDefaultRetryPolicy())
                .withRequestTimeout(requestTimeout)
                .withNonProxyHosts(nonProxyHosts)
                .withRetryMode(RetryMode.STANDARD))
        .build();
  }

Put file to S3 logs:
Exception Caught:
{ "@timestamp": "2022-10-18T12:34:38.499+13:00", "@version": "1", "message": "Unable to execute HTTP request: The target server failed to respond Request will be retried.", "logger_name": "com.amazonaws.http.AmazonHttpClient", "thread_name": "http-nio-8080-exec-5", "level": "DEBUG", "level_value": 10000, "app": "file-storage-service", "traceId": "233859c044d9b22e", "spanId": "233859c044d9b22e", "x-journey-id": "fab924fb-d47d-421d-9755-b8a3dce71441" }
Retry Triggered:
{ "@timestamp": "2022-10-18T12:34:38.499+13:00", "@version": "1", "message": "Retrying Request: PUT https://bucket.s3.ap-southeast-2.amazonaws.com /HEALTHNZ-DDFR-6a896034-a704-415b-a348-617a8c9abe40-221018.pdf Headers: (amz-sdk-invocation-id: 2829c9d4-b6d6-d316-b157-56e7f384b65e, Content-Length: 3222, Content-MD5: nzIWQWZ+yMRKeHxy3LUEqQ==, Content-Type: application/pdf, User-Agent: aws-sdk-java/1.12.267 Linux/5.4.190-107.353.amzn2.x86_64 OpenJDK_64-Bit_Server_VM/11.0.16.1+9-LTS java/11.0.16.1 vendor/Amazon.com_Inc. cfg/retry-mode/standard, ) ", "logger_name": "com.amazonaws.request", "thread_name": "http-nio-8080-exec-5", "level": "DEBUG", "level_value": 10000, "app": "file-storage-service", "traceId": "233859c044d9b22e", "spanId": "233859c044d9b22e", "x-journey-id": "fab924fb-d47d-421d-9755-b8a3dce71441" }
Successful:
{ "@timestamp": "2022-10-18T12:34:38.68+13:00", "@version": "1", "level": "INFO", "app": "file-storage-service", "x-journey-id": "fab924fb-d47d-421d-9755-b8a3dce71441", "traceId": "233859c044d9b22e", "spanId": "233859c044d9b22e", "logger_name": "application.payment.files.services.FileStorageS3Service", "thread_name": "http-nio-8080-exec-5", "message": "The putObject call completed , resourceUrl https://bucket.s3.ap-southeast-2.amazonaws.com/HEALTHNZ-DDFR-6a896034-a704-415b-a348-617a8c9abe40-221018.pdf" }

### Reproduction Steps

Can be reproduced using below client bean, with aws-sdk-java

public AmazonS3 amazonS3Client() {
    return AmazonS3ClientBuilder
        .standard()
        .withClientConfiguration(
            new ClientConfiguration()
                .withRetryPolicy(PredefinedRetryPolicies
                    .getDefaultRetryPolicy())
                .withRequestTimeout(requestTimeout)
                .withNonProxyHosts(nonProxyHosts)
                .withRetryMode(RetryMode.STANDARD))
        .build();
  }

### AWS Java SDK version used

aws-sdk-java/1.12.267

### JDK version used

OpenJDK_64-Bit_Server_VM/11.0.16.1+9-LTS java/11.0.16.1

### Operating System and version

Linux/5.4.190-107.353.amzn2.x86_64

**Comment by debora-ito** [comment]
@riteshmaurya Apologies for the delay in response. I'm wondering if this is something to do with the leading dot `.` in the hostnames listed in the no_proxy property:

```
no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com,10.0.0.0/8,172.20.0.0/16,.bucket.s3.ap-southeast-2.amazonaws.com,.ap-southeast-2.amazonaws.com,10.174.0.0/21,10.169.0.0/21,10.161.0.0/21,.com.amazonaws.ap-southeast-2.s3
```

Have you tried removing the leading dot?
