### ISSUE TITLE
AmazonApiGateway client returns null for items in GetRestApisResult object when calling getRestApis()

### ISSUE THREAD

**Issue by ssipcic** [aws/aws-sdk-java#2871]
### Describe the bug

When using `getRestApis()` method with the `AmazonApiGateway` client to return a list of available `REST` APIs in API Gateway, the returning `GetRestApisResult` object is empty. There's no error or exception, but the `items` property in the object is `null`.

The region, policy, and credentials have been set properly on the client; we get a 200 http status code and the `sdkHttpMetadata` reflects that. So the response is OK but there's no data in the response.

From EC2, when running the cli command `aws apigateway get-rest-apis --region eu-west-1` the `items` are returned properly.

When using `getApis()` method with the `AmazonApiGatewayV2` client all `HTTP` and `WEBSOCKET` APIs are returned in the `GetApisResult` object (inside it's `items` field).

Maybe I'm missing something here, but it's not obvious to me what.
The REST APIs are created and deployed, they can be pinged, and the CLI returns them properly.
The V2 Gateway client works as expected.

What am I missing here?

### Expected Behavior

Calling `getRestApis()` with `AmazonApiGateway` client should return `GetRestApisResult` with a populated list of all `REST` APIs found.

### Current Behavior

No errors occurred, the logs indicate that the GET request was successful and a 200 response is returned.

> Sending Request: GET https://apigateway.eu-west-1.amazonaws.com /restapis Parameters: ({"limit":["10"]}Headers: (amz-sdk-invocation-id: 132bbfe0-d5a0-896e-6506-e531a2aee1ba, User-Agent: aws-sdk-java/1.12.296 Linux/5.10.144-127.601.amzn2.x86_64 OpenJDK_64-Bit_Server_VM/25.342-b07 java/1.8.0_342 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy, ) 
> AWS4 Canonical Request: '"GET
> /restapis
> limit=10

### Reproduction Steps

Make sure you have deployed REST APIs in API Gateway, using Mock Integration endpoints.

Create a `AmazonApiGateway` client with default `ClientConfiguration`:

> AmazonApiGateway client = AmazonApiGatewayClientBuilder.standard()
>         .withClientConfiguration(clientConfiguration)
>         .withRegion("eu-west-1")
>         .build();

    
Call `getRestApis()` and observe the returning result object:

> GetRestApisResult result = client.getRestApis(new GetRestApisRequest())

Was also tried with setting `position` and `limit` but made no difference:

> GetRestApisResult result = client.getRestApis(new GetRestApisRequest().withLimit(10).withPosition(position))

### AWS Java SDK version used

aws-java-sdk-api-gateway/1.12.331

### JDK version used

openjdk version "1.8.0_345"

### Operating System and version

Amazon Linux - Amazon Linux 2 Kernel 5.10 AMI 2.0.20221004.0 x86_64 HVM gp2

**Comment by debora-ito** [comment]
Can you enable the [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and share the logs?
Can you also share the debug logs of the cli call? Just add `--debug` option to the command.

**Comment by ssipcic** [comment]
Just wanted to leave a comment since I was able to fix this, maybe it helps someone out in the future.

The problem was that the `http request` was missing the header `Accept: application/json` and then the `response` would come back with `Content-Type: application/hal+json`. The SDK doesn't handle this and the response does 
not get parsed - resulting in `items` field being null. 

We use a bunch of AWS SDK clients in our codebase and only ApiGateway has this issue. For some reason, the header doesn't get set properly or it gets dropped somewhere.

The fix, in our case, was to simply set a custom header on the request object:

> GetRestApisRequest request = new GetRestApisRequest();
> request.putCustomRequestHeader("Accept", "application/json");
> GetRestApisResult result = client.getRestApis(request);

After adding the header the response comes back as expected and the `items` list is populated.

@debora-ito
