### ISSUE TITLE
Incorrect signature calculation when instantiating  AmazonS3 object differently 

### ISSUE THREAD

**Issue by EI22** [aws/aws-sdk-java#2874]
### Describe the bug

I get SignatureDoesNotMatch response from S3 when constructing the client differently. 

In my first program I constructed the client as follows:

` AWSCredentials awsCredentials = new BasicAWSCredentials("awsAccessKey","awsSecretKey")
ClientConfiguration clientConfiguration = new ClientConfiguration();
AmazonS3Client s3Client = new AmazonS3Client(awsCredentials,clientConfiguration);
s3Client.setEndpoint("s3.eu-west-1.amazonaws.com ")`

I managed to create object and retrieve object from my bucket.

After some time I needed to change the client to be constructed as follows (with the same credentials as above):

` AWSCredentials awsCredentials = new BasicAWSCredentials("awsAccessKey","awsSecretKey")
ClientConfiguration clientConfiguration = new ClientConfiguration();
AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder.standard().withClientConfiguration(clientConfiguration)
					                               .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
					                             .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("s3.euwest-1.amazonaws.com","eu-west-1"));
AmazonS3 client = s3ClientBuilder.build()`

But I get a response back from S3 (and cannot connect to the bucket) : 
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch;

Construct the client differently causes incorrect signature 

### Expected Behavior

I would expect that regardless of the creation of client (via sdk) with the same credential result in sucsesfull connection to bucket 

### Current Behavior

get com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; when building the client like the second step

### Reproduction Steps

1) create client like that :
 AWSCredentials awsCredentials = new BasicAWSCredentials("awsAccessKey","awsSecretKey")
ClientConfiguration clientConfiguration = new ClientConfiguration();
AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder.standard().withClientConfiguration(clientConfiguration)
					                               .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
					                             .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("s3.euwest-1.amazonaws.com","eu-west-1"));
AmazonS3 client = s3ClientBuilder.enableForceGlobalBucketAccess().build()

connect to bucket and upload files

2) stop application

3) change the client creation to 
AWSCredentials awsCredentials = new BasicAWSCredentials("awsAccessKey","awsSecretKey")
ClientConfiguration clientConfiguration = new ClientConfiguration();
AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder.standard().withClientConfiguration(clientConfiguration)
					                               .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
					                             .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("s3.euwest-1.amazonaws.com","eu-west-1"));
AmazonS3 client = s3ClientBuilder.enableForceGlobalBucketAccess().build()

4)start application again

### AWS Java SDK version used

1.11.654

### JDK version used

11

### Operating System and version

Windows and Linux

**Comment by debora-ito** [comment]
```
.withEndpointConfiguration(
    AwsClientBuilder.EndpointConfiguration("s3.euwest-1.amazonaws.com","eu-west-1"));
```

Maybe it's the typo in "s3.euwest-1.amazonaws.com"?

Just a note, the s3 client will resolve to the regional endpoint automatically based on the aws region set, so you don't have to provide an EndpointConfiguration in most of the cases.

**Comment by EI22** [comment]
thanx for answering

yes its a typo ...sorry 

The thing is why I get different signatures?

**Comment by debora-ito** [comment]
Different requests will have different signatures. The signature is calculated based on request headers, endpoint and request date are two examples. If you want to know more about how the signature is calculated you can check [here](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html).

**Comment by EI22** [comment]
I see...Thank you.
So if I already started using the sdk in to create AmazonS3 instance (constructor - deprecated)
and after a while changed the creation using builder should I expect signature problem like the one I experiencing now? 
Do I need to manually calculate the signature?

**Comment by debora-ito** [comment]
No, moving from the client constructor to builder should not lead to signature issues, and you don't need to manually calculate the signature, the SDK will do it automatically.

I thought the typo was the cause of the error, it wasn't?

**Comment by EI22** [comment]
Thank u for answering me.
I only made type when writing the question..in real world I enter the correct url. 
So I don't understand how I get SignatureDoesNotMatch error just moving from deprecated client constructor to client builder

**Comment by debora-ito** [comment]
Can you try to set the region and remove the endpoint override?

```
AmazonS3ClientBuilder s3ClientBuilder = AmazonS3ClientBuilder.standard()
                .withClientConfiguration(clientConfiguration)
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .withRegion(Regions.EU_WEST_1);
```

If that doesn't work, can you enable the verbose wirelogs? 
Usually in the case of signature errors, S3 will send in the response what was the canonical string they expected and we can compare with the string that was sent instead. For more info see:
https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-canonical-errors

If you choose to share the wirelogs here, please make sure to redact any sensitive information like access keys. For instructions on how to enable the verbose wirelogs check the Dev Guide: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose

**Comment by EI22** [comment]
I found the problem at last.
My mistake I had a bug in different code.
I'm sorry.
