### ISSUE TITLE
Using `BufferedInputStream` causes an upload error

### ISSUE THREAD

**Issue by JavaLionLi** [aws/aws-sdk-java#2876]
### Describe the bug

Upload files to receive using `MultipartFile`
`MultipartFile.getInputStream` return `BufferedInputStream`
Using `BufferedInputStream` causes an upload error

### Expected Behavior

use bytes upload success

### Current Behavior

![image](https://user-images.githubusercontent.com/31852897/201526470-3bd42311-1528-48b8-92fe-d77b0e5f312e.png)
![image](https://user-images.githubusercontent.com/31852897/201526525-a9ad7b4f-995b-4d9a-8dbe-c998eda77d93.png)

### Reproduction Steps

![image](https://user-images.githubusercontent.com/31852897/201526768-0521e654-1c2c-4b21-bb9c-a20f08d7dc84.png)

![image](https://user-images.githubusercontent.com/31852897/201526687-d4bc0e58-ca02-473c-b35c-6275aa61b73b.png)

### AWS Java SDK version used

1.12.341

### JDK version used

1.8.0_202

### Operating System and version

centos7.6

**Comment by debora-ito** [comment]
Hi @JavaLionLi can you share a repro code in text format, not screenshot?
We ask for repro code for two main reasons: to better understand what the application is trying to do, and to be able to simply copy+paste the code and run it in our side to reproduce the error.

**Comment by JavaLionLi** [comment]
> Hi @JavaLionLi can you share a repro code in text format, not screenshot? We ask for repro code for two main reasons: to better understand what the application is trying to do, and to be able to simply copy+paste the code and run it in our side to reproduce the error.

Simply put, PutObjectRequest use BufferedInputStream error

**Comment by JavaLionLi** [comment]
> Hi @JavaLionLi can you share a repro code in text format, not screenshot? We ask for repro code for two main reasons: to better understand what the application is trying to do, and to be able to simply copy+paste the code and run it in our side to reproduce the error.

```
        try {
            // 文件必须大于200kb
            BufferedInputStream inputStream = new BufferedInputStream(new FileInputStream("D:\test.txt"));
            PutObjectRequest putObjectRequest = new PutObjectRequest("test", path, inputStream, new ObjectMetadata());
            client.putObject(putObjectRequest);
        } catch (Exception e) {
            e.printStackTrace();
        }
```

**Comment by debora-ito** [comment]
Can you share a code sample of how the s3 client is being created?

**Comment by JavaLionLi** [comment]
> Can you share a code sample of how the s3 client is being created?

```
        AwsClientBuilder.EndpointConfiguration endpointConfig =
            new AwsClientBuilder.EndpointConfiguration("http://127.0.0.1:9000", "");
        AWSCredentials credentials = new BasicAWSCredentials("admin", "123456");
        AWSCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(credentials);
        ClientConfiguration clientConfig = new ClientConfiguration();
        AmazonS3ClientBuilder build = AmazonS3Client.builder()
            .withEndpointConfiguration(endpointConfig)
            .withClientConfiguration(clientConfig)
            .withCredentials(credentialsProvider)
            .disableChunkedEncoding();
        this.client = build.build();
```
use minio

**Comment by debora-ito** [comment]
I can't reproduce the issue. I used the s3 endpoint though, not minio. Maybe it's a minio issue, do you see the same error when using the s3 endpoint directly?

You mentioned Multipart in the description, but the repro code calls a regular non-multipart PutObject, can you share a repro code for Multipart Upload? And if possible, please enable the DEBUG logs and share here when the error occurs. For instructions on how to enable DEBUG logs check Request/Response Summary Logging here: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-request-response

**Comment by JavaLionLi** [comment]
> I can't reproduce the issue. I used the s3 endpoint though, not minio. Maybe it's a minio issue, do you see the same error when using the s3 endpoint directly?
> 
> You mentioned Multipart in the description, but the repro code calls a regular non-multipart PutObject, can you share a repro code for Multipart Upload? And if possible, please enable the DEBUG logs and share here when the error occurs. For instructions on how to enable DEBUG logs check Request/Response Summary Logging here: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-request-response

Nothing to do with minio, Using a BufferedInputStream file larger than 500kb will result in an error,

**Comment by JavaLionLi** [comment]
No one to deal with it?

**Comment by hqbhoho** [comment]
I had the same problem in sdk 2.x , So I try use java reflection to get BufferedInputSteam filed in (FileInputStream)  and put it .  @JavaLionLi 
code like:
```java
InputStream inputStream = file.getInputStream();
Field in = FilterInputStream.class.getDeclaredField("in");
in.setAccessible(true);
InputStream inNew = (InputStream)in.get(inputStream);
PutObjectResponse putObjectResponse = s3Client.putObject(putObjectRequest, RequestBody.fromInputStream(inNew, size));
```
