### ISSUE TITLE
Bucket name itself displays as Object in the Listing Object summary using v2 api

### ISSUE THREAD

**Issue by samrajcse** [aws/aws-sdk-java#2882]
### Describe the bug

Hi Team, 
We are using AWS java sdk v2 api for listing the folder documents inside the buckets. This issue is data specific. When we listdown the specific folder, we are getting that folder itself in the getObjectSummary response. This issue is reproduceable in the S3 CLI as well.
We could see those ETag value is common across all the object as d41d8cd98f00b204e9800998ecf8427e. 

In the below screenshot, when I am listing ingest folder, it displays ingest as new object with Etag value as d41d8cd98f00b204e9800998ecf8427e and size as Zero.

![image](https://user-images.githubusercontent.com/696988/204811178-34ef2962-4036-4f9a-b488-a61c1028b372.png)

### Expected Behavior

When we are listing the object summaries only files in the folder should be displayed. Here the base folder ( prefix added in the criteria) itself listed as a file.

### Current Behavior

Now the prefix folder is displayed as file in the response. 

### Reproduction Steps

This is data specific and we cannot reproduce with regular dataset. 

### Possible Solution

Need to ignore the prefix path in object summary listing.

### AWS Java SDK version used

1.12.286

### JDK version used

1.8.0_312

### Operating System and version

Windows 10 and Centos 8

**Comment by debora-ito** [comment]
Hi @samrajcse, 

S3 does not have the concept of folders. Everything is an object.

When you create a "ingest" folder, S3 creates an object of 0 bytes. The console UI makes it look like a folder.
Check this page for more details: https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html
