### ISSUE TITLE
Spring cloud sqs listener stops polling from SQS after sometime

### ISSUE THREAD

**Issue by mohan22** [aws/aws-sdk-java#2885]
### Describe the bug

We are using spring cloud sqs listener (Spring annotation : @SqsListener) to poll for messages from SQS queue.

Our consumer microservice runs in AWS EKS (eks.11)

Consumer does following activities in sequence for each message it consumed:
1.Our consumer consumes single message at a time and executes a long running query (2-5 minutes execution time)
2.Copy the query result file from S3 to SFTP server.

After working for about a week, the consumer stops consuming messages from the queue. I could see messages in the queue.

My issue is same as this - https://github.com/awspring/spring-cloud-aws/issues/551

### Expected Behavior

Consumer should not stop after working for sometime.

### Current Behavior

Consumer intermittently getting stopped after consuming messages for sometime. 

### Reproduction Steps

Refer this post for sample code - https://github.com/awspring/spring-cloud-aws/issues/551

### AWS Java SDK version used

AWS SDK : 1.12.150, spring-cloud-starter-aws: 2.4.0,  spring-cloud-starter-aws-messaging:2.4.0

### JDK version used

1.8.0_191

### Operating System and version

Amazon Linux 2

**Comment by tomazfernandes** [comment]
Hi, we've been working on the `3.0.0` version which is a complete rewrite of the `SQS` integration and should not have this problem. A `GA` is expected this year or early next.

Please try it out and let us know if there are any issues!

Thanks.
