### ISSUE TITLE
Add logging for STS service calls

### ISSUE THREAD

**Issue by riteshvaryani** [aws/aws-sdk-java#2886]
### Describe the feature

We do get throttled a lot of times when the AWS SDK is making calls to STS service to get credentials. These files do not have any debug logs and enabling them would really help us understand how many calls are happening to fetch credentials in spite of setting long expiry times for the token

### Use Case

To debug calls to AWS throttling. AWS STS service does not provide clear limits for number of calls that can be made and adding debug logging will help us understand how many times the calls are actually going to AWS STS vs returning the unexpired tokens

### Proposed Solution

Add debug logging when calls are being made to https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSSessionCredentials.java#L148
and https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSSessionCredentials.java#L167

### Other Information

I can help by creating a PR to commit this- let me know

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.12.85

### JDK version used

11

### Operating System and version

Fedora CoreOS

**Comment by debora-ito** [comment]
Hi @riteshvaryani thank you for reaching out.

The STSSessionCredentials class is deprecated, so we don't intend to make changes to it, even if you submit a PR, sorry.

That said, the Request & Response logging should show what you're looking for, it does not?
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-request-response

**Comment by riteshvaryani** [comment]
What is the class STSAssumeRoleSessionCredentialsProvider and STSSessionCredentials deprecated in favor of? Is there a new auth flow to get credentials?

**Comment by debora-ito** [comment]
STSSessionCredentials was deprecated in favor of [STSSessionCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSSessionCredentialsProvider.html).

You can check the deprecation info in the class Javadoc -
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSSessionCredentials.html
