### ISSUE TITLE
AmazonSQSClient getting permanent "Timeout waiting for connection from pool" errors

### ISSUE THREAD

**Issue by rjgithub2** [aws/aws-sdk-java#2887]
### Describe the bug

Sporadically, and usually after running for a minimum of several days, some of our server instances begin getting "Timeout waiting for connection from pool" errors when trying to call AmazonSQSClient.sendMessage().  From that point on, all subsequent sendMessage() calls fail with the same error, until the server instance is restarted.  Some notes:

1. We see this with a default AmazonSQSClient, and a couple of times we've also seen the error once with DynamoDBClient.  I know that a lot of reports of this error involve S3 where user code doesn't release streams, that is not the scenario here.
2. We're not experiencing high load or high usage of the services at the time the error starts happening.  
3. No matter how long we wait, the problem does not go away once it has started, so somehow connections from the pool are being permanently lost/held.  I don't see how anything that user code does could cause that to happen for SQSClient.

### Expected Behavior

Not to receive a ConnectionPoolTimeoutException when calling sendRequest() under normal load conditions.   And if such an error is received legitimately due to high load conditions, sendRequest() should begin working correctly again once a return to normal load conditions occurs.

### Current Behavior

We sometimes receive a ConnectionPoolTimeoutException when calling sendRequest() under normal load conditions, but usually not until a server instance has been running for several days.   Once we receive such an error, sendRequest() never works again on that instance until the instance is restarted.

Here's a partial stack trace:

```
! org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:316)
! at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
! at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
! at com.amazonaws.http.conn.$Proxy38.get(Unknown Source)
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
! at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
! at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
! at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
! ... 79 common frames omitted
! Causing: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
! at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2329)
! at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2296)
! at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2285)
! at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1875)
```

### Reproduction Steps

The problem is unfortunately difficult to reproduce as we don't understand how anything that our code could do could possibly permanently exhaust the SQSClient connection pool.  We're just making normal calls to send and receive messages using a default AmazonSQSClient.   We do use several other AWS services within the same app, but my understanding is that each AWS client has its own connection pool, such that SQS wouldn't be affected even if there were connection release issues with other AWS clients or with Apache HTTP connections unrelated to AWS clients.

### Possible Solution

Examine AWSSQSClient connection pool related code and determine how connections could possibly be permanently "leaked", and whether Apache connection usage in other AWS clients or in code unrelated to AWS could possibly have any effect on the SQS connection pool.

As a workaround, we tried the steps below, which seem to be helping for the moment, but we are hesitant to declare the problem fixed because we still don't understand how the problem could occur in the first place:

1. Use separate AWS client instances with separate connection pools in our various service runnables instead of a shared AWS client instance and connection pool, hopefully lessening the chances of connection pool exhaustion.
2. Addressed a few instances of explicitly created Apache connection resources (unrelated to AWS) potentially not being cleaned up fully. In theory not related to this issues as AWS services use their own private connection pools, but can’t hurt.
3. Turned on AWS SDK metric collection, which may provide some additional insight into connection pool usage if/when the problem occurs again.

### Additional Information/Context

Our server instances had been deployed since May 2022 with no new deployments since then and no major changes in server load or network environment.   But strangely, the problem was not seen until September 2022, at which point it began happening to an instance every week or two, and even to instances that had been rebooted a few days prior.  Is it possible that something in the AWS service or network setup changed such that occasionally client connections to the service were held open indefinitely by the server, causing the connection to never be released on the client side?  

### AWS Java SDK version used

1.12.328

### JDK version used

1.8.0_45

### Operating System and version

Ubuntu 20.04.4 LTS

**Comment by debora-ito** [comment]
@rjgithub2 thank you for the detailed report. 

> Our server instances had been deployed since May 2022 with no new deployments since then and no major changes in server load or network environment. But strangely, the problem was not seen until September 2022 (...)

Given that there was no code or SDK version change, this indicates that it's not an issue with the SDK itself but with the environment around it - like network configs, timeouts, connectivity, etc. 

About the workarounds:
> 1. Use separate AWS client instances with separate connection pools in our various service runnables instead of a shared AWS client instance and connection pool, hopefully lessening the chances of connection pool exhaustion.

We don't recommend creating multiple clients if possible. This leads to resource and connection leaks more often than using just one client, based on our experience. You also have the risk of reaching the maximum number of file descriptors available in your OS, and at that point it can be harder to troubleshoot connectivity issues.

> 3. Turned on AWS SDK metric collection, which may provide some additional insight into connection pool usage if/when the problem occurs again.

This is the recommended path forward: analyze the client-side metrics and identify any strange patterns of HttpClientPool AvailableCount and PendingCount, ClientExecuteTime and other metrics, and tweak the timeouts accordingly.

Maybe you've seen this already but there's a couple of blog posts that show how to interpret the client-side metrics:
- Tuning the AWS SDK for Java to Improve Resiliency ([link](https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/))
- Tuning AWS Java SDK HTTP request settings for latency-aware Amazon DynamoDB applications ([link](https://aws.amazon.com/blogs/database/tuning-aws-java-sdk-http-request-settings-for-latency-aware-amazon-dynamodb-applications/))

Let me know if this helps. If you need further help, please share the client-side metrics you generated at the time ConnectionPoolTimeoutException occurs.

**Comment by rjgithub2** [comment]
Thanks for the response, we will continue to monitor things and see if the metrics are helpful should the problem reoccur.  Can you please help confirm the following, though?

- Are the connection pools for AmazonSQSClient instances completely separate from those of other AWS client instances and from the default Apache connection pools?  Such that connection alllocations in those other areas should have absolutely no effect on the SQS connection pool?
- Do you have any ideas what could explain the seemingly permanent depletion of the SQS connection pool?  Given the API methods exposed by AmazonSQSClient, it doesn't seem like there's anything there that could cause a connection to never be returned to the pool, but that's the effect that we're seeing.

**Comment by debora-ito** [comment]
> Are the connection pools for AmazonSQSClient instances completely separate from those of other AWS client instances and from the default Apache connection pools? Such that connection alllocations in those other areas should have absolutely no effect on the SQS connection pool?

Yes, each instance of an SDK client has its own connection pool.

> Do you have any ideas what could explain the seemingly permanent depletion of the SQS connection pool? Given the API methods exposed by AmazonSQSClient, it doesn't seem like there's anything there that could cause a connection to never be returned to the pool, but that's the effect that we're seeing.

Not really, besides high request rate. The client-side metrics will give more insights on this.
