### ISSUE TITLE
`doesBucketExistV2` breaks interoperability with other S3 compatible APIS

### ISSUE THREAD

**Issue by pwharned** [aws/aws-sdk-java#2889]
### Describe the bug

The AWS S3 APIS are more or less interoperable with other S3 compatible apis. However the implementation of some methods breaks the interoperability of client apps that use the SDK to interoperate with S3 compatible apis( for example Hive S3 integrations). (and are besides smelly)  The `doesBucketExistV2` method seems to make a call to the AWS ACL apis? Which can be seen in the implementation.

```

    @Override
    public boolean doesBucketExistV2(String bucketName) throws SdkClientException {
        try {
            ValidationUtils.assertStringNotEmpty(bucketName, "bucketName");
            getBucketAcl(bucketName);
            return true;
        } catch (AmazonServiceException ase) {
            // A redirect error or an AccessDenied exception means the bucket exists but it's not in this region
            // or we don't have permissions to it.
            if ((ase.getStatusCode() == Constants.BUCKET_REDIRECT_STATUS_CODE) || "AccessDenied".equals(ase.getErrorCode())) {
                return true;
            }
            if (ase.getStatusCode() == Constants.NO_SUCH_BUCKET_STATUS_CODE) {
                return false;
            }
            throw ase;
        }
    }
```

In this trivial example replacing the AWS endpoint with a GCS endpoint I can easily list buckets in my GCS account.

```
import com.amazonaws.auth.AWSStaticCredentialsProvider
import com.amazonaws.client.builder.AwsClientBuilder
import com.amazonaws.regions.Regions
import com.amazonaws.services.s3.model.ObjectListing
import com.amazonaws.services.s3.{AmazonS3, AmazonS3Client, AmazonS3ClientBuilder, AmazonS3URI}
import com.amazonaws.services.s3.model.ObjectListing

object Main extends App{

  import com.amazonaws.auth.AWSCredentials
  import com.amazonaws.auth.BasicAWSCredentials

  val endpointConfig = new AwsClientBuilder.EndpointConfiguration("https://storage.googleapis.com", "us-east1")

  val credentials = new BasicAWSCredentials("", "")
  val s3client: AmazonS3ClientBuilder  = AmazonS3ClientBuilder
    .standard()
  s3client.setEndpointConfiguration(endpointConfig);
  val finalClient = s3client.withCredentials(new AWSStaticCredentialsProvider(credentials))
    .build();

  import com.amazonaws.services.s3.model.Bucket

  val buckets = finalClient.listBuckets.get(0).getName

  println(buckets)

  finalClient.doesBucketExistV2("walmart12")




}
```
<img width="1878" alt="Screen Shot 2022-12-14 at 1 16 54 PM" src="https://user-images.githubusercontent.com/52669420/207692483-d2820c7a-c4f9-49da-8175-30e8687ec88d.png">

This function call doesnt make sense for the following reasons:

1. I have already provided HMAC credentials and am authenticated. The server should be responsible for determining whether I have access to the bucket with the provided credentials, the client shouldn't be making extra calls to determine this, plus the extra call introduces an additional  synchronous call which slows down the SDK
2. The function name and implementation are only orthogonally related - I guess checking the ACL theoretically answers the question of whether the bucket exists, but a more straightforward implementation is just listing the buckets and checking whether the user provided bucket is in the list. 

### Expected Behavior

I would expect the implementation of the method would be a straightforward call to the S3 apis

### Current Behavior

Currently the S3 SDK calls the ACL apis to check whether a bucket exists, which doesnt make sense from an implementation standpoint and also breaks interoperability with other libraries.

### Reproduction Steps

Use the client SDK built in methods to determine whether a bucket exists with any S3 compatible API.

### Possible Solution

```

import com.amazonaws.AmazonServiceException;
import com.amazonaws.SdkClientException;

import com.amazonaws.services.s3.internal.Constants;
import com.amazonaws.services.s3.AmazonS3Client;

import com.amazonaws.util.ValidationUtils;
import com.amazonaws.services.s3.model.Bucket;

import java.util.List;

class AmazonS3ClientT extends AmazonS3Client {



    @Override
    public boolean doesBucketExistV2(String bucketName) throws SdkClientException {
        try {
            ValidationUtils.assertStringNotEmpty(bucketName, "bucketName");
            List<Bucket> buckets = this.listBuckets();

            for(int i=0; i<buckets.size(); i++){
                if (buckets.get(i).getName()==bucketName){
                    return true;
                }
            }
            return false;
        } catch (AmazonServiceException ase) {
            // A redirect error or an AccessDenied exception means the bucket exists but it's not in this region,
            // or we don't have permissions to it.
            if ((ase.getStatusCode() == Constants.BUCKET_REDIRECT_STATUS_CODE) || "AccessDenied".equals(ase.getErrorCode())) {
                return true;
            }
            if (ase.getStatusCode() == Constants.NO_SUCH_BUCKET_STATUS_CODE) {
                return false;
            }
            throw ase;
        }
    }


}

```

### AWS Java SDK version used

3.3.4

### JDK version used

▶ java -version openjdk version "1.8.0_345" OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01) OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)

### Operating System and version

Tested on RHEL 8 and Mac OSX Monterey

**Comment by debora-ito** [comment]
Hi @pwharned,

as the [doesBucketExistV2](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#doesBucketExistV2-java.lang.String-) states:

> Checks if the specified bucket exists. Amazon S3 buckets are named in a global namespace; use this method to determine if a specified bucket name already exists, and therefore can't be used to create a new bucket.

Bucket names are unique across all S3, not just in your account. That's why we check bucketACL. Using listBuckets() will not work here.

Another point is while we understand customers use the SDK with third-party solutions, the scope of the AWS SDK for Java is to work with AWS APIs.

We appreciate the PR you submitted but we won't be able to accept it.
