### ISSUE TITLE
DynamoDBMapper support for polymorphism

### ISSUE THREAD

**Issue by jamiethermo** [aws/aws-sdk-java#289]
As suggested in the comment for the @Deprecated marshallIntoObject call, I'm adding an issue requesting a hook to solve our problem: We have a dynamodb table with multiple model classes. So, we have a Shape table, but the table contains Square and Circle items. All we require is a way to specify the class to be used as the target for deserialization based on one of the item's values, so that we get a List<Shape> that actually contains instances of Square and Circle. 

```java
public interface ClassSelector<T> {
    Class<? extends T> selectClass(Map<String, AttributeValue> itemAttributes);
}
```
Or something like that.

**Comment by JuanCarlosGonzalez** [comment]
This would be a nice feature. Currently I'm struggling with this.

KR,

**Comment by zhangzhx** [comment]
This is a duplicated issue to this one https://github.com/aws/aws-sdk-java/issues/832. Please follow that thread to trace this feature.
