### ISSUE TITLE
Implement PaginatedScanList toString Method

### ISSUE THREAD

**Issue by belugabehr** [aws/aws-sdk-java#2893]
### Describe the feature

Add a `toString()` method to `PaginatedScanList`.

### Use Case

I'm always frustrated when I'm using the `DynamoDBEmbedded` in my unit tests and I can't easily examine the outputs.

I always have to do:

```java
this.dynamoDBWrapper.scan(MyClass.class, new DynamoDBScanExpression()).foreach(System.out::println).
```

Which logs each record per line.  Instead of getting all the results in one concatenated log line, like:

```java
log.debug("Results: {}", this.dynamoDBWrapper.scan(MyClass.class, new DynamoDBScanExpression()));
```

### Proposed Solution

Add a `toString()` method to `PaginatedScanList` class

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1

### JDK version used

11

### Operating System and version

Amazon Linux 2

**Comment by yasminetalby** [comment]
Hello @belugabehr,

Thank you very much for your submission.

Currently the team is focusing its effort on features for the AWS Java SDK V2, it is highly recommended to migrate to the v2 version.

Have you tried using the V2 Java SDK?https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/DynamoDbClient.html#scan(software.amazon.awssdk.services.dynamodb.model.ScanRequest


Best,

Yasmine
