### ISSUE TITLE
Add Support for Java Time API in DynamoDB

### ISSUE THREAD

**Issue by belugabehr** [aws/aws-sdk-java#2895]
### Describe the feature

Add support for storing Java Time API objects, in particular: `Instant` and `ZonedDateTime`

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBTypeConvertedTimestamp.java

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardTypeConverters.java

### Use Case

When dealing with `Date`, which is not immutable, my code looks something like:

```
public Date getDeletedDate() { return (null == deletedDate) ? null : new Date(deletedDate.getTime()); }

public void setDeletedDate(Date deletedDate) {
  this.deletedDate = (null == deletedDate) ? null : new Date(deletedDate.getTime());
}
```

### Proposed Solution

Add support Java Time API which includes immutable objects and is over-all a better solution in Java.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1

### JDK version used

11

### Operating System and version

Amazon Linux 2

**Comment by debora-ito** [comment]
Hi @belugabehr you might have noticed this already, but Instant and ZonedDateTime are already supported in the SDK V2 DynamoDB Enhanced Client. 

The team is focused in working in V2 features right now, so this request would have very low priority. Because of this, and because it's already supported in V2, I'll go ahead and close this.

**Comment by belugabehr** [comment]
@debora-ito Thanks.  I've moved my focus to SDK V2 based on your advice.
