### ISSUE TITLE
Why no presignPostObject for software.amazon.awssdk.services.s3.presigner.S3Presigner?

### ISSUE THREAD

**Issue by Lelouch-Lamperouge-Code-Geass** [aws/aws-sdk-java#2896]
### Describe the feature

I'm using 'software.amazon.awssdk:s3:2.18.35', and I find that there is no method `presignPostObject` for class `software.amazon.awssdk.services.s3.presigner.S3Presigne`. It only has `presignPutObject` and `presignGetObject` methods.

This force me to use HTTP PUT when I want to use HTTP POST at frontend. 

```
axios({
      method: "put",
      url: presignedUrl,
      data: formData,
      cancelToken: source.token,
      onUploadProgress: (e) => {
        // updating progress indicator
        progress(e.lengthComputable, e.loaded, e.total);
      },
    })
```

If I use HTTP Post in above code, it will return error:

```
Request Method: POST
Status Code: 403 Forbidden
```

My question, why not support HTTP POST for presigned URL? Isn't POST generally used for object creation and HTTP PUT for updating object? 

### Code

```java
    public String getS3PreSignedUrl(@NonNull final String storeIdentifier,
                                    @NonNull final String productIdentifier,
                                    final int pictureOrder) {
        log.info("storeIdentifier: {}, productIdentifier: {}", storeIdentifier, productIdentifier);
        String objectKey = storeIdentifier + pictureOrder;
        PutObjectRequest putObjectRequest = PutObjectRequest.builder()
                .bucket(environment.getProperty("PRODUCT_IMAGE_BUCKET"))
                .key(objectKey)
                .build();

        PutObjectPresignRequest putObjectPresignRequest = PutObjectPresignRequest.builder()
                .signatureDuration(Duration.ofMinutes(30))
                .putObjectRequest(putObjectRequest)
                .build();
        PresignedPutObjectRequest presignedPutObjectRequest = s3Presigner.presignPutObject(putObjectPresignRequest);
        return presignedPutObjectRequest.url().toString();
    }
```

### Use Case

I want to get S3 presigned URL for HTTP Post request to create object in the specified object. 

Use case similar to here: https://stackoverflow.com/questions/70490650/403-when-upload-file-to-s3-bucket-using-axios/70753194#70753194

### Proposed Solution

presignPostObject is supported for software.amazon.awssdk.services.s3.presigner.S3Presigner

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

software.amazon.awssdk:s3:2.18.35

### JDK version used

11

### Operating System and version

macos monterey

**Comment by yasminetalby** [comment]
Hello @Lelouch-Lamperouge-Code-Geass ,

Thank you very much for your submission.

You are right, this feature doesn't exist yet in the AWS Java SDK V2. However this is already in the team backlog as a feature-request for the AWS Java SDK V2!
This feature is tracked here : https://github.com/aws/aws-sdk-java-v2/issues/1493. You can showcase your interest for this feature by upvoting the feature-request, this helps the team to prioritize the most requested feature form the community.
Once this feature will be implemented, we will close this submission as completed.

If that is ok with you, I will close this submission in favor of the original feature-request to prevent duplicate items and better track the community interest regarding this feature and provide update on release.

As a side note, this repository is for the AWS Java SDK V1. If you would like to submit feature-request for the AWS Java SDK V2 you can do so in the [issue section of the AWS Java SDK V2 repository](https://github.com/aws/aws-sdk-java-v2/issues).

Thank you very much again for your submission! This is extremely helpful for our team.

Sincerely,

Yasmine
