### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by neetikasinghal** [aws/aws-sdk-java#2899]
### Describe the feature

Support mark with CryptoInputStream

### Use Case

When uploading objects to Amazon S3 using streams (either through [S3 client](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html)or [Transfer manager ](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html)), it is possible to run into network connectivity or timeout issues. The AWS Java SDK by default attempts to retry these failed transfers. The input stream is marked before the start of transfer and reset before retrying. The SDK recommends customers to use resettable streams (streams that support mark and reset operations). If the stream does not support mark and reset, then the SDK throws ResetException when there are any transient failures and retries are enabled.

CryptoInputStream for encryption doesn't support mark. When Amazon S3 client tries to reset the mark on failures such as throttling as it expects the stream to have mark supported, there is an exception thrown as the mark is not supported by the CryptoInputStream. Ref: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1284

### Proposed Solution

Proving mark support with the CryptoInputStream would highly be useful for our application and provide out-of the box support to support S3 retries

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.11.750

### JDK version used

11

### Operating System and version

Mac OS

**Comment by debora-ito** [comment]
Hi @neetikasinghal I think you're talking about [aws-encryption-sdk-java](https://github.com/aws/aws-encryption-sdk-java) CryptoInputStream, and if so the Crypto Team is the maintainer of that class. 

I see you've submitted a feature request in their repo https://github.com/aws/aws-encryption-sdk-java/issues/1279. I'll go ahead and close this issue, the work needs to be done in the aws-encryption-sdk-java library.
