### ISSUE TITLE
AmazonS3Client for Android Studio Not Uploading File Completely

### ISSUE THREAD

**Issue by maq796113** [aws/aws-sdk-java#2902]
### Describe the bug

It looks like there is an issue with the file upload to Amazon S3. The log messages indicate that the server returned a "Moved Permanently" error with a status code of 301.     
                                                                                                                                               
```
[okhttp]:check permission begin!    
[okhttp]:not MMS!     
[okhttp]:not Email!     
Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: Moved Permanently (Service: null; Status Code: 301; Error Code: 301 Moved Permanently; Request ID: E3JNKG6YV5BDW7NH), S3 Extended Request ID: UZlAGcIBZ68msl7YNJh2Qv56Pe0RLgB8kF8sLvrOVxTHlQtGQL85oVL871mAXBnHu1XCzLY9spA=                            Key: surahIkhlas-1.wav; Request: PUT https://audiofileswav.s3.ap-northeast-1.amazonaws.com /surahIkhlas-1.wav Headers: (x-amz-website-redirect-location: /storage/emulated/0/Android/data/com.example.qurantutor/files/Music/maq@maq.com/audio9ec60389-479d-4f2c-a06c-3b50e4f2ba59.wav, Content-Length: 0, Content-Type: application/octet-stream, )       
[okhttp]:check permission begin!      
[okhttp]:not MMS!       
[okhttp]:not Email!       
[socket]:check permission begin!      
[OkHttp] sendRequest<<       
Server is ignored.     
x-amz-request-id is ignored.     
x-amz-id-2 is ignored.           
Date is ignored.  

```

### Expected Behavior

I was expecting to get all the file content on my s3 bucket. 

### Current Behavior

I get a file uploaded on s3 Bucket with size` 0 B`.

### Reproduction Steps

To reproduce this I will be sharing the source code found below:
[https://gist.github.com/maq796113/a1757542fb5891def3d4285cdb044a6c](url)

### AWS Java SDK version used

2.60.0

### JDK version used

19.0.1

### Operating System and version

Android 11

**Comment by debora-ito** [comment]
@maq796113 apologies for the delay in response.

`301  Moved Permanently` usually indicates the request was sent to a regional s3 endpoint but the bucket is actually in a different region.

You can see this and other error codes in the S3 API Reference - https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList.
