### ISSUE TITLE
Not All Supported data types for DynamoDB Mapper for Java are Documented

### ISSUE THREAD

**Issue by belugabehr** [aws/aws-sdk-java#2904]
### Describe the issue

As I understand it, the _Supported data types for DynamoDB Mapper for Java_ documentation does not include several implemented converters.

https://github.com/aws/aws-sdk-java/blob/39d5072fc13b491075f2798352b5348babcb677f/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardTypeConverters.java#L254-L274

### Links

- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html

**Comment by debora-ito** [comment]
Will reach out to the documentation team again, since the docs were not updated. Closing this for now.
