### ISSUE TITLE
dynamodb document api query count

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java#291]
It would be nice to have a query count on the dynamodb document api.
Something like Table.count(QuerySpec).
Currently you need to touch low level results for that.

**Comment by namrasaheba** [comment]
How can I pull the lastEvaluatedKey for the Document API Query and Scan operations?

**Comment by kiiadi** [comment]
Not sure if I fully understand the question - but the QueryResult & ScanResult both have getters for the lastEvaluatedKey - is that what you're looking for?

* [QueryResult#getLastEvaluatedKey](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/QueryResult.html#getLastEvaluatedKey--)
* [ScanResult#getLastEvaluatedKey](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ScanResult.html#getLastEvaluatedKey--)
