### ISSUE TITLE
Missing method name in AmazonS3Client ctor javadoc

### ISSUE THREAD

**Issue by tedyu** [aws/aws-sdk-java#2912]
### Describe the bug

There is no method name following the second occurrence of `anonymous clients can call` in AmazonS3Client ctor javadoc.

### Expected Behavior

The method name should be specified which anonymous clients can call.

### Current Behavior

Method name is missing.

### Reproduction Steps

See aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java source code around line 523

### AWS Java SDK version used

master branch of source code

### JDK version used

N/A

### Operating System and version

N/A

**Comment by debora-ito** [comment]
Hi @tedyu I'm not clear on what is the issue. Can you elaborate on the problem?

Can you provide a code sample showing what you trying to do?
