### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.apache.http.client.methods.HttpRequestBase com.amazonaws.http.HttpResponse.getHttpRequest()

### ISSUE THREAD

**Issue by sbathwal1999** [aws/aws-sdk-java#2915]
### Describe the bug

getHttpRequest() is being imported from org.apache.http.client.methods.HttpRequestBase in com.amazonaws.http.HttpResponse.
But no such method is defined in HttpRequestBase file.

### Expected Behavior

Original html request should be received on calling the method

### Current Behavior

There shouldn't be any call to a method which isn't available.

### Reproduction Steps

While reading the files from minio is spark the above issue can be observed.

### AWS Java SDK version used

1.12.322

### JDK version used

11.0.15

### Operating System and version

Debian GNU/Linux version 11

**Comment by debora-ito** [comment]
Hi @sbathwal1999 `NoSuchMethodError` usually indicates a version mismatch between SDK modules.

Ideally, all the SDK modules in your project must be in the same version. To achieve this we recommend you use the BOM module - 
https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/
