### ISSUE TITLE
Questions about the behavior of STSAssumeRoleSessionCredentialsProvider

### ISSUE THREAD

**Issue by isaac33zhang** [aws/aws-sdk-java#2918]
### Describe the issue

I am opening this issue according to suggestion from AWS Support. I am trying to use STSAssumeRoleSessionCredentialsProvider with AWS KMS client. As is known, STSAssumeRoleSessionCredentialsProvider spins up a background thread to refresh the credentials. We have a couple of questions about it that don't seem to be addressed in any document:

1. When does the background thread exit?
For example, for a single request, if the workflow is just we create a credential provider, create a kms client with it, and do a decrypt operation, does the background thread get closed after the workflow is completed?
2. If we put the instantiated credential provider object in a cache, will the backgroud thread of it keep running?
3. If the answer to question 2 is yes, will the background thread exit if the object gets evicted from the cache?
Thanks

### Links

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.html

**Comment by debora-ito** [comment]
> 1. When does the background thread exit?

The background thread only terminates when the STSAssumeRoleSessionCredentialsProvider  method `close()` is called.
If the credential provider is not needed anymore and `close()` is called at the end of the workflow described, then the thread is shut down.


> 2. If we put the instantiated credential provider object in a cache, will the backgroud thread of it keep running?

Yes.

> 3. If the answer to question 2 is yes, will the background thread exit if the object gets evicted from the cache?

No, see answer to question 1.

Check the STSAssumeRoleSessionCredentialsProvider javadoc for more info - https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.html

**Comment by isaac33zhang** [comment]
@debora-ito Thanks for the reply. If I understand correctly, close() must be called explicitly to terminate the thread?

**Comment by debora-ito** [comment]
Yes. Note that close() will also terminate the credential provider, so it must be called when the provider is no longer needed.
