### ISSUE TITLE
SSM Client PutParameter() not throwing access denied exceptions when having insufficient permissions with new data type `aws:ec2:image`

### ISSUE THREAD

**Issue by Jpk518** [aws/aws-sdk-java#2919]
### Describe the bug

The new ssm parameter data type `aws:ec2:image` requires an additional IAM permission ec2:DescribeImages for validating the new ami data in PutParameter calls, but does not throw an AccessDenied Exception when this permission is not incuded in the requesters IAM scope, rather returning a success response w/o performing the expected functionality of updating the parameter. 

``` 
PutParameterRequest putParameterRequest = PutParameterRequest.builder()
        .name("<SSM_PARAMETER_NAME>")
        .value("<AMI_ID>")
        .dataType("aws:ec2:image")
        .overwrite(true)
        .build();
PutParameterResponse response = ssmClient.putParameter(putParameterRequest);
```

### Expected Behavior

Exception Thrown showing AccessDenied

### Current Behavior

SDK call returns success w/o performing it's intended purpose.

### Reproduction Steps

Run the below code block against an existing SSM Parameter with data type `aws:ec2:image` 

``` 
PutParameterRequest putParameterRequest = PutParameterRequest.builder()
        .name("<SSM_PARAMETER_NAME>")
        .value("<AMI_ID>")
        .dataType("aws:ec2:image")
        .overwrite(true)
        .build();
PutParameterResponse response = ssmClient.putParameter(putParameterRequest);
```

with IAM permissions to perform the PutParameter() call, excluding the new IAM permissions the call requires to validate the ami
``` 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [ "ssm:PutParameter" ],
            "Resource": "<PARAMETER_ARN>",
        }
    ]
}
```

### AWS Java SDK version used

2.19.26

### JDK version used

Java 8

### Operating System and version

 Amazon Linux 2

**Comment by debora-ito** [comment]
@Jpk518 I think this is expected, according to the PutParameter API Reference the validation is made asynchronously, check the Note under DataType -
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PutParameter.html

**Comment by Jpk518** [comment]
> @Jpk518 I think this is expected, according to the PutParameter API Reference the validation is made asynchronously, check the Note under DataType -
> https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PutParameter.html

Interesting, the functionality and complex workaround seems counterintuitive from a user perspective, can’t imagine aws keeping this as the final solution here. Thanks for reply.

> @Jpk518 I think this is expected, according to the PutParameter API Reference the validation is made asynchronously, check the Note under DataType -
> https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PutParameter.html

Interesting, the functionality and complex workaround seems counterintuitive from a user perspective, can’t imagine aws keeping this as the final solution here. Thanks for reply.
