### ISSUE TITLE
dynamodb document api dynamic query

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java#293]
It would be nice to be able to make queries in the dynamodb document api where the comparison operators are dynamic for filters and key conditions.
Also a utility method to convert ComparisonOperator into KeyConditions would help.

For example
```
new QueryFilter("strAttr").withComparisonOperator(ComparisonOperator.EQ).withValues("attrValue");
new RangeKeyCondition("strAttr").withKeyCondition(KeyConditions.EQ).withValues("attrValue");
new RangeKeyCondition("strAttr").withKeyCondition(InternalUtils.toKeyConditions(ComparisonOperator.EQ)).withValues("attrValue");
```

**Comment by manikandanrs** [comment]
AWS Java SDK released xspec API some time ago. Please take a look at this.

https://java.awsblog.com/post/TxBG87QOQZRZJF/DynamoDB-XSpec-API
