### ISSUE TITLE
Support S3 checksum algorithm

### ISSUE THREAD

**Issue by bentsherman** [aws/aws-sdk-java#2931]
### Describe the feature

The checksum algorithm option should be supported for `PutObjectRequest` and `InitiateMultipartUploadRequest`.

### Use Case

I am trying to use the checksum algorithm option that was announced in [this blog post](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/). I assumed I could specify it for `PutObjectRequest` and `InitiateMultipartUploadRequest`, but in the API docs I see it is only supported for `S3CopyObjectOperation`. In the blog post there is a Python example, so I assumed it should be possible to support in the Java SDK as well.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.12.351

### JDK version used

Temurin 17.0.6

### Operating System and version

Ubuntu 20.04

**Comment by debora-ito** [comment]
Hi @bentsherman apologies for the delay in replying in here.

Checksum algorithms are supported only in Java SDK 2.x - for example, check the 2.x PutObjectRequest docs: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/PutObjectRequest.Builder.html

Changes in the Java SDK 1.x S3 client require handwritten effort, while in 2.x the change was done upstream in the service model. In this case, the team decided not to make the change in 1.x.

**Comment by bentsherman** [comment]
Thanks Deborah!
