### ISSUE TITLE
Older sdk version default authentication changed?

### ISSUE THREAD

**Issue by dhivyak83** [aws/aws-sdk-java#2936]
### Describe the bug

We are using aws sdk - 1.11.505 (and below) and was using ec2 role based authentication which was by default to connect from EKS pods to AWS services s3/sqs with below sample code. 
AmazonS3 s3 = AmazonS3ClientBuilder.defaultClient();

But we recent noticed[from 3rd feb], this was failing to connect with ec2 role, instead it was trying to connect with aws keys using aws profile in local pod. We when upgraded to latest sdk[1.12.403] , it could connect back again with ec2 node role. When we raised issue with AWS team, they confirmed that nothing changed on their side and was asked to reachout to this forum. Kindly share your thoughts on this if something was changed in older version sdk.

### Expected Behavior

Default to ec2 instance role

### Current Behavior

Defaults to keys in local aws profile

### Reproduction Steps

try connecting to aws sdk older version with below code:
AmazonS3 s3 = AmazonS3ClientBuilder.defaultClient();

### AWS Java SDK version used

1.11.505 and below

### JDK version used

openjdk version "1.8.0_151"

### Operating System and version

NAME="Alpine Linux" ID=alpine VERSION_ID=3.7.0

**Comment by debora-ito** [comment]
Yes, EC2 IMDSv2 was introduced in version 1.11.678 -
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

I don't know what changed in February 3rd, but the logs should show an insight.

**Comment by dhivyak83** [comment]
Thanks. This was helpful. Our new AMI had this IMDSv2 change and that older sdk couldn't pick ec2 instance role
