### ISSUE TITLE
forceGlobalBucketAccessEnabled interferes with endpoint configuration

### ISSUE THREAD

**Issue by fuetgeo** [aws/aws-sdk-java#2937]
### Describe the bug

`AwsClientBuilder.withForceGlobalBucketAccessEnabled(true)` seems to interfere with the endpoint configured via `withEndpointConfiguration`. While this might make some sense for AWS-only users, the behavior is not documented & problematic when accessing non-AWS buckets.

### Expected Behavior

minimum: consistent behavior & clearer documentation of ForceGlobalBucketAccess
ideal: do not allow enabling ForceGlobalBucketAccess (or ignore it?) in combination with a non-AWS endpoint configuration

### Current Behavior

When building clients with the attached code, we observe sporadic permission errors when the requested bucket on the 3rd party provider has the same name as an existing AWS S3 bucket. It seems that in these cases, the client is accessing AWS instead of the configured endpoint. Further proof: When using credentials which are valid for the AWS bucket (which in this case was luckily our own), the request is sporadically successful.

Conclusion: For an estimated 20% of attempts, AWS is being accessed. In 80% of attempts, the endpoint configured via `withEndpointConfiguration`

### Reproduction Steps

    var endpointConfiguration = new EndpointConfiguration("https://storage.googleapis.com", "auto");
    var client = AmazonS3Client.builder()
        .withEndpointConfiguration(endpointConfiguration)
        .withForceGlobalBucketAccessEnabled(true)
        .withCredentials(...)
        .build();
    client.getBucketLocation("name-matching-an-AWS-bucket");

### AWS Java SDK version used

aws-java-sdk-s3 1.12.410

### JDK version used

OpenJDK 17.0.1

### Operating System and version

Ubuntu

**Comment by debora-ito** [comment]
Hi @fuetgeo non-aws endpoints are not in scope of this SDK. We cannot add logic supporting third-party solutions, once we add one, we'll start to get requests to support others.

We'll acknowledge bug reports when aws endpoints are used directly. With non-aws solutions, we can't guarantee that the SDK will work.
