### ISSUE TITLE
putCustomQueryParameter does not work with QuickSight GetDashboardEmbedUrlRequest

### ISSUE THREAD

**Issue by bluemonki** [aws/aws-sdk-java#2942]
### Describe the bug

Whilst following this blog post [https://docs.aws.amazon.com/quicksight/latest/user/iam-policy-examples.html#security_iam_id-based-policy-examples-dashboard](https://docs.aws.amazon.com/quicksight/latest/user/iam-policy-examples.html#security_iam_id-based-policy-examples-dashboards) I think I've found a bug in the QuickSight GetDashboardEmbedUrlRequest.

In the blog post parameters are passed by the JS code to the URL, but this looks like it should also be available to do when generating the embedding URL via the GetDashboardEmbedUrlRequest class via the inherited [putCustomQueryParameter](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonWebServiceRequest.html#putCustomQueryParameter-java.lang.String-java.lang.String-)

But setting parameters here do nothing to the final URL.

### Expected Behavior

Parameters set in `putCustomQueryParameter` should be included in the URL as it would prevent people from being able to grab the 'generic' embed URL and supply their own parameters to it.

### Current Behavior

Parameters set via `putCustomQueryParameter` are set but ignored

![Screenshot 2023-03-09 102132](https://user-images.githubusercontent.com/15387658/224278271-2ddda750-09c3-4525-b25c-981a2088cde7.png)

![Screenshot 2023-03-09 102225](https://user-images.githubusercontent.com/15387658/224277881-dd0aa155-7ebd-4c1b-8cf0-c88c8ffafc58.png)

### Reproduction Steps

It's quick complex to set up all the bits for QuickSight, so this is just the important bit
```
GetDashboardEmbedUrlRequest getDashboardEmbedUrlRequest = new GetDashboardEmbedUrlRequest();
getDashboardEmbedUrlRequest.setAwsAccountId(awsAccountId);
getDashboardEmbedUrlRequest.setDashboardId(dashboardId);
getDashboardEmbedUrlRequest.setUserArn(userARN);
getDashboardEmbedUrlRequest.setIdentityType(IdentityType.QUICKSIGHT.name());
getDashboardEmbedUrlRequest.setSessionLifetimeInMinutes(600L);
getDashboardEmbedUrlRequest.setStatePersistenceEnabled(false);

// this does nothing to the embed URL
getDashboardEmbedUrlRequest.putCustomQueryParameter("subject", subjectId);

GetDashboardEmbedUrlResult getDashboardEmbedUrlResult = quickSight.getDashboardEmbedUrl(getDashboardEmbedUrlRequest);
String embedURL = getDashboardEmbedUrlResult.getEmbedUrl();
```

### AWS Java SDK version used

1.12.422

### JDK version used

11

### Operating System and version

Windows 11

**Comment by debora-ito** [comment]
Hi @bluemonki apologies for the delay in response.

The URL obtained from the `getDashboardEmbedUrl` API is generated by the service, so my guess is it only takes into consideration the attributes present in the request. Any other attribute will be ignored.
