### ISSUE TITLE
RequestIds not getting captured using amazonS3.getCachedResponseMetadata(req)

### ISSUE THREAD

**Issue by Naman-555** [aws/aws-sdk-java#2945]
### Describe the bug

I am trying to check if bucket exists in s3 using GetBucketAclRequest
before this, I was directly using doesBucketExistsInV2(), but I was not getting requestIds incase of AmazonServiceExceptions with error code 500.
So as suggested by AWS support , used high level method         amazonS3.getBucketAcl(req) and tried capturing requestIds/hostIds using S3ResponseMetadata as suggested here as [well](https://docs.aws.amazon.com/AmazonS3/latest/userguide/get-request-ids.html#sdk-request-ids).
However, In case of success response (when bucket exists) , we get hostIds/requestIds captured  in metaData,
whereas in case of exception 404( bucket doesnt exists), hostId/requestId is null

### Expected Behavior

ideally, for all the request requestIds/hostIds should be captured using S3ResponseMetadata.

### Current Behavior

RequestId .hostId is null incase of 404 error 
  Status Code  404 with **Host ID: null  RequestID:  null**  stacktrace com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: QHDPDD0HA1N068BF; S3 Extended Request ID: IpXSW1MTQknaCI7WNTAE5+n5Me9MwI8PG84Dx+wUQ9COx9bSBMknZS9cma1vQzyay3u9bZ3d7DQ=; Proxy: null), S3 Extended Request ID: IpXSW1MTQknaCI7WNTAE5+n5Me9MwI8PG84Dx+wUQ9COx9bSBMknZS9cma1vQzyay3u9bZ3d7DQ=

** note
Stacktrace does prints requestIds.

### Reproduction Steps

private fun doesBucketExistsInS3(bucketName: String, amazonS3: AmazonS3): Boolean {
    val req = GetBucketAclRequest(bucketName)

    try {
        println("Fetching bucket $bucketName")
        amazonS3.getBucketAcl(req)
        return true
    } catch (e: AmazonServiceException) {
        val md = amazonS3.getCachedResponseMetadata(req)
        println(
            " AmazonServiceException while fetching bucket  $bucketName  from s3 with Status Code  ${e.statusCode} with Host ID: " +
                    "${md?.hostId}  RequestID:  ${md?.requestId}  stacktrace $e"
        )
        return when {
            e.statusCode != 301 && "AccessDenied" != e.errorCode -> {
                /* println(
                     " AmazonServiceException while fetching bucket  $bucketName  from s3 with Status Code  ${e.statusCode} with Host ID: " +
                             "${md?.hostId}  RequestID:  ${md?.requestId}  stacktrace $e"
                 )*/
                when (e.statusCode) {
                    404 -> false
                    else -> throw e
                }
            }
            else -> true
        }
    } catch (e: Exception) {
        val md = amazonS3.getCachedResponseMetadata(req)
        println(
            " Exception while fetching bucket  $bucketName with Host ID:  ${md?.hostId}  RequestID:  ${md?.requestId} stacktrace $e "
        )
        throw e
    }
}

Check the output when bucket doesnt exists. (404 error) , may be for any exception , this doesn't logs requestIds

### AWS Java SDK version used

1.11.828 but checked with 1.12.425 as well

### JDK version used

11.0.15.1

### Operating System and version

mac os Monterey (12.4)

**Comment by s-aws** [comment]
The S3 service assigns the request to the account that owns the bucket. If the bucket doesn't exist, where will the service assign the request?

**Comment by debora-ito** [comment]
I'm not sure why `getCachedResponseMetadata()` is not returning the requestID in this case, even when the request logs show a requestID was returned.

I'm replying to your questions in this Github Discussion - https://github.com/aws/aws-sdk-java/discussions/2941
I'll go ahead and close this, let's keep all discussion in one place.
