### ISSUE TITLE
Add OSGi metadata to AWS SDK Java libraries

### ISSUE THREAD

**Issue by fipro78** [aws/aws-sdk-java#2957]
### Describe the feature

Add OSGi metadata to the aws-sdk-java artefacts, so it can be deployed and consumed in OSGi applications.

### Use Case

I want to create services that use the AWS SDK to be able to orchestrate applications in the cloud. I want to use OSGi, so the services can also be integrated in an Eclipse based application. This is currently not possible by using the artefacts published at Maven Central, as all artefacts doesn't contain the necessary OSGi metadata. The only way would maybe to use the aws-java-sdk-osgi artefact. But that one has about 300MB and is therefore not really usable for small services. In my use case I only need aws-java-sdk-ec2 and its dependencies, and not the whole 300MB.

The only way I could verify that it is generally working, was to create wrapped bundles that consume the artefacts and add the OSGi metadata. But this is more a workaround for verification than a reliable solution.

### Proposed Solution

Add the [bnd-maven-plugin](https://github.com/bndtools/bnd/tree/master/maven-plugins/bnd-maven-plugin) or [Grade Plugins](https://github.com/bndtools/bnd/tree/master/gradle-plugins) to the build process of the AWS CDK Java libraries (dependent on whether Maven or Gradle is used), to get the OSGi metadata automatically generated at build time.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.12.448

### JDK version used

11

### Operating System and version

Windows 10, Eclipse, Java 11

**Comment by debora-ito** [comment]
Hi @fipro78 thank you for reaching out.

OSGi support is an [old ask](https://github.com/aws/aws-sdk-java/issues/314#issuecomment-526392242) for Java SDK v1 but we decided to close the feature request in a past backlog cleaning, we don't have plans to support in v1. 

We are tracking a related request in Java SDK v2 here - https://github.com/aws/aws-sdk-java-v2/issues/59.
