### ISSUE TITLE
Wrong AWS IAM role being called

### ISSUE THREAD

**Issue by lifeofmoo** [aws/aws-sdk-java#2967]
### Describe the bug

Hello,

We have a Java container that has a service account attached to it be able to perform SNS actions.

arn:aws:iam::xxxxxxxxxx:role/eksctl-eksdev-addon-role

The problem, is that node instance (NodeInstanceRole) which the pod runs on is trying to perform the SNS actions instead of the Pod

We then see this error.

```
com.amazonaws.services.sns.model.AuthorizationErrorException: User: arn:aws:sts::xxxxxxx:assumed-role/eksctl-eksdev-nodegroup-managed-s-NodeInstanceRole-xxxxxxx/i-xxxxxxx is not authorized to perform: SNS:SetSMSAttributes on resource: arn:aws:sns:eu-west-1:xxxxxxxxx:* because no identity-based policy allows the SNS:SetSMSAttributes action (Service: AmazonSNS; Status Code: 403; Error Code: AuthorizationError; Request ID: 36f3f26f-6cdf-5965-94b2-aed479a536bc; Proxy: null)
```

This is the current java code for SNS:

```
package com.bmj.identity.configuration;

import com.amazonaws.services.sns.AmazonSNSClient;
import com.amazonaws.services.sns.AmazonSNSClientBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SnsConfiguration
{

    @Bean
    public AmazonSNSClient amazonSNSClient()
    {
        return (AmazonSNSClient) AmazonSNSClientBuilder.defaultClient();
    }
}
```

What’s the correct way to Assume role with a WebIdentity request in Java to be able to perform **SNS** actions?

### Expected Behavior

As above

### Current Behavior

As above

### Reproduction Steps

As above

### AWS Java SDK version used

1.12.405

### JDK version used

1.12.405

### Operating System and version

EKS

**Comment by debora-ito** [comment]
The SNS client will use the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default), so in this case you need to check if the credential being picked up is indeed the WebIdentityTokenCredentialsProvider.

The DEBUG logs should provide a little more information about what is happening in the credential provider chain - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-request-response
