### ISSUE TITLE
AWS4Signer should provide option to set custom host header

### ISSUE THREAD

**Issue by voiddrum** [aws/aws-sdk-java#2974]
### Describe the feature

As of now, AWS4Signer [extracts host name from end point url](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L237) and uses it to set the `Host` header and compute hash to sign the request.

Ideally, if a host name is provided in the request's `Host` header, AWS4Signer should use that instead.

### Use Case

In cases where the target host is behind a load balancer/gateway, the final host name will be that of the host which hosts the API (Eg: AWS Neptune `/sparql` API).

Clients should be able to set the target host name in header in order for the target host to verify the request.

### Proposed Solution

If a host name is provided in the request's `Host` header, AWS4Signer should use that instead of extracting from endpoint url.

### Other Information

`awscurl` command line tool is able to honour the host header.
eg:
The below invocation works
```
awscurl \
-H'Host: target_host.aws.com'  \
--access_key $AWS_ACCESS_KEY_ID \
--secret_key $AWS_SECRET_ACCESS_KEY \
--session_token $AWS_SESSION_TOKEN \
--service neptune-db \
--region us-west-2  \
-X POST -H 'Content-Type: application/sparql-query'  \
-H 'Accept: text/csv' "https://alb-host.aws.com/sparql" -d ...
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.11.1009

### JDK version used

11.0.16.1

### Operating System and version

MacOS Ventura 13.3.1 (22E261)

**Comment by voiddrum** [comment]
Looks similar to https://github.com/aws/aws-sdk-ruby/issues/2339

**Comment by debora-ito** [comment]
So the feature request is to not overwrite the `Host` header if the request already has one.

It's unusual that this is needed at the AWS4Signer level. You can override the endpoint at the client level with a custom `EndpointConfiguration` but I guess you can't use this.

As a workaround, you can use a `RequestHandler2` to change the endpoint to the hostname you want. 
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/handlers/RequestHandler2.html

Just a heads up, the team is focused in working in features for the Java SDK v2, so this has a low chance to be implemented.

**Comment by subuhi-nigar** [comment]
This is weird of AWS4Signer to set  host as  endpoint  .  
StringBuilder hostHeaderBuilder = new StringBuilder(endpoint.getHost());
Due to this unable to access AWS service that are running behind NLB .

**Comment by debora-ito** [comment]
We don't have plans to support this in v1 before going into Maintenance Mode, so I'll go ahead and close this issue.

The recommendation is to migrate to Java SDK v2. If this issue is still relevant in v2, please open [new Github issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo and provide all the details.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
