### ISSUE TITLE
Bucket Owner displayName null even though it isn't

### ISSUE THREAD

**Issue by anas-ben-ouaghrem** [aws/aws-sdk-java#2978]
### Describe the bug

Hello, 
I was retrieving the owner display names for all of my s3 buckets a week ago then today and with the same code the display name became null. I checked in the cli and I retrieve the expected display name, meaning that it shouldn't be null

### Expected Behavior

The actual display name gets retrieved

### Current Behavior

The display name is always null

### Reproduction Steps

List<Bucket> buckets = s3Client.listBuckets();
for ( Bucket bucket : buckets) {
    System.out.println(bucket.getOwner().getDisplayName());
}

### AWS Java SDK version used

1.12.470

### JDK version used

17

### Operating System and version

windows 11 and ubuntu 23.04

**Comment by bhoradc** [comment]
Hello @Anas-Ben-Oughrem,

Can you please check and confirm the AWS region it's pulling via AWS SDK for Java? 

DisplayName is supported only in certain AWS regions, as specified [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Owner.html).

If you still have further questions, can you kindly enable verbose wire logging and provide us the logs? Kindly redact any sensitive information the log may contain.  

Instructions to enable wire logging can be found [here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose).

Regards, 
Chaitanya

**Comment by Anas-Ben-Oughrem** [comment]
Here is the full list of regions that I use: 

 ```
private static final Regions[] awsRegions = {
            Regions.AP_SOUTH_1,
            Regions.EU_NORTH_1,
            Regions.EU_WEST_3,
            Regions.EU_WEST_2,
            Regions.EU_WEST_1,
            Regions.AP_NORTHEAST_3,
            Regions.AP_NORTHEAST_2,
            Regions.AP_NORTHEAST_1,
            Regions.CA_CENTRAL_1,
            Regions.SA_EAST_1,
            Regions.AP_SOUTHEAST_1,
            Regions.AP_SOUTHEAST_2,
            Regions.EU_CENTRAL_1,
            Regions.US_EAST_1,
            Regions.US_EAST_2,
            Regions.US_WEST_1,
            Regions.US_WEST_2,

    };
```

**Comment by debora-ito** [comment]
@anas-ben-ouaghrem is this still an issue? If it is, it can be easily checked with the verbose wirelogging. 

Here's an example of the verbose wirelogs that shows the ListBuckets XML response with the DisplayName information:

```
2024-06-18 17:04:39,111 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8"?>[\n]"
2024-06-18 17:04:39,111 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>xxx</ID><DisplayName>debora</DisplayName></Owner><Buckets><Bucket><Name>debora-bucket</Name><CreationDate>2021-07-02T22:01:01.000Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>[\r][\n]"
2024-06-18 17:04:39,113 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "[\r][\n]"
```
