### ISSUE TITLE
How to bind a custom domain name to a bucket? No relevant configuration method has been found.

### ISSUE THREAD

**Issue by JavaLionLi** [aws/aws-sdk-java#2979]
### Describe the bug

How to bind a custom domain name to a bucket? No relevant configuration method has been found.

generatePresignedUrl whether you can use custom domain name generation

### Expected Behavior

1

### Current Behavior

1

### Reproduction Steps

1

### AWS Java SDK version used

1.12.400

### JDK version used

1.8

### Operating System and version

centos7.6

**Comment by debora-ito** [comment]
@JavaLionLi what do you mean by custom domain? Can you give an example?

**Comment by JavaLionLi** [comment]
> @JavaLionLi what do you mean by custom domain? Can you give an example?

OSS vendors have the function of binding a domain name to a bucket.
You can access the bucket directly through the domain name.
The secret key generated by the signature cannot be accessed by using the bound domain name, and the signature does not match.

**Comment by debora-ito** [comment]
Can you give a code example?
