### ISSUE TITLE
SQS consume request erroring out with "The connection was closed during the request."

### ISSUE THREAD

**Issue by varunu28** [aws/aws-sdk-java#2980]
### Describe the bug

I have multiple workers which are consuming from a SQS queue. For two instances on different worker nodes, I have seen the following error while consuming from SQS. This was eventually retried and the message was consumed

Error Log:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause.
```

### Expected Behavior

The expected behavior is either consuming a message successfully or erroring out after a timeout. Note that these were just 2 instances out of close to 1M+ invocations. This was spread in span of 10 seconds so it can be a network jitter but I want to understand how to better leverage AWS SDK configuration to avoid such issues in future.

### Current Behavior

Working as expected aside from these 2 instances of erroring out

### Reproduction Steps

Non-reproducible as it happened on 2 instances of consuming from SQS

### AWS Java SDK version used

2.x

### JDK version used

11.0.16

### Operating System and version

ec2

**Comment by debora-ito** [comment]
We do have some documentation about tuning the SDK clients, they may be the references you're looking for:
- [Tuning the AWS SDK for Java to Improve Resiliency](https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/)
- [Tuning AWS Java SDK HTTP request settings for latency-aware Amazon DynamoDB applications](https://aws.amazon.com/blogs/database/tuning-aws-java-sdk-http-request-settings-for-latency-aware-amazon-dynamodb-applications/)

The blog posts show how to generate SDK client-side metrics and how to interpret them to customize your client to be more fault-tolerant.

**Comment by debora-ito** [comment]
I'm changing this to a documentation issue, as it's more a guidance question. Let us know if you have follow-up questions.
