### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by dzmitryv111111** [aws/aws-sdk-java#2982]
### Describe the feature

Java AWS Pinpoint client don't allow to add EmailTags which are needed to trace send emails in cloudwatch.

  
This API has EmailTags field. 
[EmailTags](https://docs.aws.amazon.com/pinpoint-email/latest/APIReference/API_SendEmail.html#pinpoint-SendEmail-request-EmailTags)

client not allow to add email tags. 

return new SendMessagesRequest()
                .withApplicationId(pinpoitApiProperties.getAppId())
                .withMessageRequest(new MessageRequest()
                        .withAddresses(addressMap)
                        .withTemplateConfiguration(new TemplateConfiguration().withEmailTemplate(new Template()
                                .withName(emailTemplate.getTemplateName())))
                        .withMessageConfiguration(new DirectMessageConfiguration()
                                .withEmailMessage(new EmailMessage().withBody(
                                        .withSubstitutions(subs).withFromAddress(from)
                                )
                        ));

### Use Case

We need to pass email tags to trace event in cloud watch. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1.12.476

### JDK version used

17

### Operating System and version

linux

**Comment by debora-ito** [comment]
Hi @dzmitryv111111 thank you for reaching out.

The API you are looking for is SendEmail, not SendMessages.
Here's the SendEmailRequest javadoc, you can see it has the `withEmailTags` method:

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/pinpointemail/model/SendEmailRequest.html
