### ISSUE TITLE
Spelling error in exception message in XpathUtils

### ISSUE THREAD

**Issue by jmax01** [aws/aws-sdk-java#2987]
### Describe the bug

Spelling error in exception message.the static initialization block 

### Expected Behavior

Exception message to be spelled correctly

### Current Behavior

    ```
static {
        try {
            speedUpDcoumentBuilderFactory();
        } catch(Throwable t) {
            log.debug("Ingore failure in speeding up DocumentBuilderFactory", t);
        }
        try {
            speedUpDTMManager();
        } catch(Throwable t) {
            log.debug("Ingore failure in speeding up DTMManager", t);
        }
    }
```

### Reproduction Steps

Turn on delogging

### Possible Solution

fix spelling 

### AWS Java SDK version used

1.12.482

### JDK version used

17

### Operating System and version

MacOS

**Comment by debora-ito** [comment]
@jmax01 thank you for reaching out.

Java SDK v1's source mainline is in our internal repository, what means we need to incorporate the changes internally first to be released here in github later. 

The Java SDK team is focused in doing SDK v2 work, so we'll make this change when we have a minute.

**Comment by mynkdsi1011** [comment]
@debora-ito I would like to contribute and work on the issue if no one else working on it. Please let know If I can work on it?

**Comment by debora-ito** [comment]
@mynkdsi1011 there's a PR for this already, check the issue timeline.

**Comment by debora-ito** [comment]
Fix was released. Closing.
