### ISSUE TITLE
java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder

### ISSUE THREAD

**Issue by Cherry111** [aws/aws-sdk-java#2991]
### Describe the bug

We are facing below issue when creating the AWS SQS builder on EMR:

java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder.withRegion(Lcom/amazonaws/regions/Regions;)Lcom/amazonaws/client/builder/AwsClientBuilder;

We can run it locally but not on EMR.
1.12.487 is the sdk version we are using.

### Expected Behavior

We are facing below issue when creating the AWS SQS builder on EMR:

java.lang.NoSuchMethodError: com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder.withRegion(Lcom/amazonaws/regions/Regions;)Lcom/amazonaws/client/builder/AwsClientBuilder;

We can run it locally but not on EMR.
1.12.487 is the sdk version we are using.

### Current Behavior

Able to create the SQS builder without any issue.

### Reproduction Steps

deploying our jar on EMR

### AWS Java SDK version used

1.12.487

### JDK version used

1.8

### Operating System and version

EMR

**Comment by debora-ito** [comment]
`NoSuchMethodError` indicates a version mismatch of the `core` and `sqs` modules. Ideally all SDK modules should be in the same version. 

Using the BOM artifact helps to achieve this, for more info check our blog post - https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/.
