### ISSUE TITLE
Add support for new Step Functions MapState ASL Syntax including Distributed Map state to the fluent State Machine builder

### ISSUE THREAD

**Issue by gerrardcowburn** [aws/aws-sdk-java#2993]
### Describe the feature

As part of the Step Functions launch of Distributed Map, the Amazon States Language was updated to deprecate the 'Iterator' syntax and replace it with an '[ItemProcessor](https://states-language.net/spec.html#map-state)' syntax within the MapState. The fluent State Machine builder has not yet been updated to align with this and as such it's not possible to create Distributed Maps.  There's also some danger that as the deprecation of the Iterator syntax progresses, the state machine definitions generated by this builder will cease to function correctly.

Requesting the integration of the ItemProcessor generation capability into the MapState builder

### Use Case

To keep pace with the evolution of the Amazon States Language and new capabilities launched by Step Functions

### Proposed Solution

Add an itemProcessor method to the [MapState.Builder](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/stepfunctions/builder/states/MapState.Builder.html#iterator-com.amazonaws.services.stepfunctions.builder.states.Iterator.Builder-) class with a relevant ItemProcessor.Builder to generate the ASL components required as part of the ItemProcessor object.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1

### JDK version used

N/A

### Operating System and version

N/A

**Comment by debora-ito** [comment]
@gerrardcowburn the team is focused in working in Java SDK v2 features, so this has better chances to be implemented in v2.

The fluent Step Functions API builder is not yet implemented in v2, we are tracking the feature here: https://github.com/aws/aws-sdk-java-v2/issues/40

**Comment by debora-ito** [comment]
We don't have plans to support this in v1 before going into Maintenance Mode, so I'll close this issue.

Please track the progress of Step Functions builder in the v2 repo: https://github.com/aws/aws-sdk-java-v2/issues/40

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
