### ISSUE TITLE
Connection Pool Error after when exceeding the Throughput

### ISSUE THREAD

**Issue by jakelowie** [aws/aws-sdk-java#3002]
### Describe the bug

Whenever my Springboot Application exceeds the RCU/WCU of my DynamoDB, I get a Connection Pool Error, which is why that certain API call fails. 
I already added a Retry annotation from Spring and also a Backoff but it seems that does not solve the problem.
My API receives 150-250 calls per hour on average.

### Expected Behavior

The expected behavior is for the API call to Backoff and then return to its previous behaviour which processes my read and writes in DynamoDB

### Current Behavior

I get connection pool errors and my API fails.

### Reproduction Steps

Exceed the throughput of a certain DynamoDB table and indexes.

### AWS Java SDK version used

1.11.506

### JDK version used

15

### Operating System and version

Linux

**Comment by debora-ito** [comment]
@jakelowie please provide:
- a self-contained sample code we can use to reproduce the error. See http://sscce.org/
- the full stacktrace with the error

"Connection Pool Error" is a message too broad, I can't give meaningful pointers with just that description.
