### ISSUE TITLE
AWS DefaultCredentialsProviderChain connection with Regional STS Endpoint through Private VPC

### ISSUE THREAD

**Issue by shashankpisal30** [aws/aws-sdk-java#3009]
### Describe the bug

Hi Team,

We are evaluating one case where we have setup a Virtual Private cloud (VPC) and are trying to execute an application of S3 activities using the DefaultCredentialsProviderChain type of authentication using the Credential Profiles file and also having the assume role in place at the default location (~/.aws/credentials). However, as we execute the application, the credentials are not picked up from the default credentials profile file. Instead, it's taking it from the Amazon EC2 container credentials.

We have also gone through the order of picking up the credentials for the DefaultCredentialsProviderChain authentication. We observed that it was not able to reach the global STS endpoint, which was present on the public internet. Instead, It was picking up the credentials from the EC2 Container Credentials Provider, which should not be the case as we are able to execute the same cases with the AWS Credentials authentication type using the regional STS endpoint within the Private VPC.

Hence, we would like to know how we can reach out to the STS regional endpoint from DefaultCredentialsProviderChain, as it is the only endpoint reachable in the Private VPC.

### Expected Behavior

Ideally, for the DefaultCredentialsProviderChain we should be able to reach out to the STS regional endpoint on the Private VPC.

### Current Behavior

Currently, the credentials are picked up from the EC2 Container Credentials Provider excluding the DefaultCredentialsProviderChain.

### Reproduction Steps

credentialsProvider = new DefaultAWSCredentialsProviderChain();
AmazonS3Client s3client =AmazonS3ClientBuilder.standard()
.withCredentials(credentialsProvider).build();
Configure the Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI.
Provide role_arn in config file.

### AWS Java SDK version used

1.12.411

### JDK version used

1.8

### Operating System and version

Windows 10

**Comment by debora-ito** [comment]
If you set `AWS_STS_REGIONAL_ENDPOINTS` to `regional`, the internal STS client created for the DefaultCredentialsProviderChain should start using the regional endpoint. The configuration is also available for the `config` file and as a system property.

More info on the `AWS_STS_REGIONAL_ENDPOINTS` configuration:
https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html

**Comment by shashankpisal30** [comment]
Hi @debora-ito,
Thank you for your response!

As per your comment, we have already tried all the configurations mentioned by you and also gone through the reference link that you have given us. However, the behavior is still the same. 
Also, can you please confirm that `AWS_STS_REGIONAL_ENDPOINTS`, this specific property is only applicable for Environment variables or we can use it in the config file too.

For. eg. In the config file like this.
```
[default]
aws_sts_regional_endpoints = regional
```

Thanks!

**Comment by debora-ito** [comment]
Yes, it works with config file properties too, the property name is `sts_regional_endpoints` (no "aws_"prefix).

**Comment by shashankpisal30** [comment]
Hi @debora-ito,

We already tried all the possible combinations of the configurations mentioned by you and also from the AWS Documentation. Also, we had a call with the support team of the AWS where we connected with their Engineering Associate as well and demonstrated various use cases. However, they verified the Cloud Trail logs and confirmed that, it eventually reached out to the global endpoint rather than retrieving the credentials from the regional endpoint. PFA, file for the cloud trail logs provided by the AWS support team.
To conclude, the engineer acknowledged that there is an issue.

Please let me know if you need any more information on the same.
Thanks!

[Cloud Trail LOgs.txt](https://github.com/aws/aws-sdk-java/files/12272352/Cloud.Trail.LOgs.txt)

**Comment by debora-ito** [comment]
I see. I apologize, I assumed the internal STS client would pick the regional configuration up without really testing.

If the internal STS client does not pick up the regional configuration, I don't think there's a workaround for the DefaultCredentialsProviderChain.

If you can change to use STSAssumeRoleSessionCredentialsProvider, you're able to provide a custom STS client to the builder.

I'd also recommend to migrate to Java SDK v2 if possible. STS regional endpoints are supported by default in v2.
