### ISSUE TITLE
Content-MD5 header required when using `createBucket()` method

### ISSUE THREAD

**Issue by me-ydv-5** [aws/aws-sdk-java#3015]
### Describe the bug

when trying to use `s3Client.createBucket(bucketName)`, I get 

`
com.amazonaws.services.s3.model.AmazonS3Exception: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters
`

I'm not sure if I can add that header while sending the request (one way to do that is to add it via `ClientConfiguration` object), if yes, how do I calculate MD5 for a bucket that I want to create, there's no body as such, just a bucket name.

### Expected Behavior

The request should succeed without throwing the error.

### Current Behavior

Throwing the attached error

```
com.amazonaws.services.s3.model.AmazonS3Exception: Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters
```

### Reproduction Steps

something like 

```java

var s3Client = AmazonS3ClientBuilder
        .standard()
        .withEndpointConfiguration(
            new AwsClientBuilder.EndpointConfiguration("us-east-1-endpoint", "us-east-1"))
        .withPathStyleAccessEnabled(true)
        .withClientConfiguration(new ClientConfiguration())
        .withCredentials(new AWSStaticCredentialsProvider(credentials)).build();

s3Client.createBucket("mybucket");

```

### AWS Java SDK version used

1.12.276

### JDK version used

openjdk version "17.0.1" 2021-10-19

### Operating System and version

MacOS 13.3.1 (a)

**Comment by debora-ito** [comment]
The error message makes sense for `PutObject`, but not for `CreateBucket`.

Can you provide a functioning repro code and the full stacktrace of the error?

**Comment by me-ydv-5** [comment]
```
      var bucketRequest = new CreateBucketRequest(bucketName);

      bucketRequest.putCustomRequestHeader("Content-MD5",
          Arrays.toString(Md5Utils.computeMD5Hash(new ByteArrayInputStream(bucketRequest.toString().getBytes(
              StandardCharsets.UTF_8)))));
      s3Client.createBucket(bucketRequest);
```

I tried this snippet and added the content md5 hash but I get `com.amazonaws.services.s3.model.AmazonS3Exception: The Content-MD5 you specified was invalid.`
