### ISSUE TITLE
Public API to validate bucket names

### ISSUE THREAD

**Issue by frankoid** [aws/aws-sdk-java#304]
It would be nice to be able to validate bucket names when users enter them into our application.

`com.amazonaws.services.s3.internal.BucketNameUtils#isValidV2BucketName(java.lang.String)` looks like it does what I'm looking for, but it is in the internal package so presumably shouldn't be used except by code inside the `aws-sdk-java` library.

**Comment by shorea** [comment]
Sorry for the long silence. I wouldn't be opposed to exposing BucketNameUtils in a public package. Is this still a requirement for your application?

**Comment by manikandanrs** [comment]
Closing this as we have not heard back. Feel free to re open this in case of an issue.

**Comment by ff-jkrispel** [comment]
This would absolutely be useful  :+1:

**Comment by juliankrispel** [comment]
@shorea it'd be pretty great if this could be exposed :+1:
