### ISSUE TITLE
Deadlock on Kinesis Client connection pool when making parallel requests

### ISSUE THREAD

**Issue by pranavanand** [aws/aws-sdk-java#3041]
### Describe the bug

We use the Kinesis Client at Databricks as part of one of the Structured Streaming sources. We noticed an issue when executing multiple parallel getRecords calls on a single Amazon Kinesis client, a deadlock occurs if one of the calls fails while holding a lock on the connection pool. This leads to other calls waiting indefinitely on that lock. For more context we create a threadpool per core that each performs a fetch and if there is an error in one of the threads we shutdown the threadpool. Is this an issue you have seen before?

cc @anishshri-db

### Expected Behavior

Each getRecords call should either complete successfully or release the connection pool lock in case of failure, allowing other calls to proceed.

### Current Behavior

One of the getRecords calls fails and exits while holding the connection pool lock, causing a deadlock. Other getRecords calls wait indefinitely for that lock to be released.

### Reproduction Steps

Create an Amazon Kinesis client.
Execute multiple parallel getRecords calls using the same client.
Simulate a failure in one of the getRecords calls after it has acquired a connection pool lock.

### Possible Solution

Free the locks before the connection pool is shutdown possibly.

### AWS Java SDK version used

1.12

### JDK version used

8

### Operating System and version

Linux

**Comment by debora-ito** [comment]
@pranavanand Deadlocks are definitely not expected. How often do you see them?

Can you provide a repro code? Without a repro code it will be hard to troubleshoot and test a potential fix.

Please also provide:
- The version of the Java SDK used
- Full logs and stacktraces of the error
- When you say "we create a threadpool per core that each performs a fetch and if there is an error in one of the threads we shutdown the threadpool", how exactly are you creating the pool, and how do you make the SDK client use it?
