### ISSUE TITLE
Please do not use underscores as Java identifiers in source code

### ISSUE THREAD

**Issue by vemv** [aws/aws-sdk-java#3045]
### Describe the bug

The java source code of these libraries, as distributed in e.g. `aws-java-sdk-core-1.12.576-sources.jar(/com/amazonaws/internal/ResettableInputStream.java):143` can occasionally use underscores as identifiers.

That's no longer valid after Java 9 and hinders any modern tooling that would want to parse your source code (e.g. for extracting useful info from its doc comments).

### Expected Behavior

The Java source code is valid for JDK9+.

### Current Behavior

It uses underscores as identifiers, and official tooling (e.g. `javax.tools.DocumentationTool`) will complain:

    error: as of release 9, '_' is a keyword, and may not be used as an identifier

### Reproduction Steps

Try running `javac` and/or other official JDK tools over your source code using a target version >= 9

### Possible Solution

Update `_` identifiers to e.g. `_ignored`

### AWS Java SDK version used

1.12.576

### JDK version used

openjdk version "16.0.1" 2021-04-20

### Operating System and version

macOS

**Comment by debora-ito** [comment]
@vemv I understand the issue, I'll see if we can make the change in `ResettableInputStream#mark`.

That said, you don't need to compile the Java SDK code to be able to use it. The recommended way to consume the SDK is to add the modules as dependencies, as showed in the Developer Guide - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html#configuring-maven

```
<dependencies>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
  </dependency>
<dependency>
```

The SDK is compiled against JDK7, so you won't be blocked by this error when consuming as dependencies.

**Comment by vemv** [comment]
Thanks! Yes, I understand.

My issue is not created from the perspective of a SDK consumer but rather, from the perspective of a tooling maker.

My tooling parses source jars such as `aws-java-sdk-core-1.12.576-sources.jar` for IDE insights - so the source ideally would be valid.

**Comment by debora-ito** [comment]
@vemv We removed the underscore, the change is available in the latest release:

https://github.com/aws/aws-sdk-java/blob/9acdd7a744fef85a56ca298a955890dce6111688/aws-java-sdk-core/src/main/java/com/amazonaws/internal/ResettableInputStream.java#L143

**Comment by vemv** [comment]
Thanks - appreciated!
