### ISSUE TITLE
Changes merged with Pull Request #255 is missing from latest release

### ISSUE THREAD

**Issue by Raniz-at-Sony** [aws/aws-sdk-java#305]
The changes made in #255 are no longer present after the code was split into sub-projects.

**Comment by hanshuo-aws** [comment]
The TableNameResolver was accidentally dropped due to a bad merge of the code changes relating to DynamoDB JSON document support.
We have added it back n the latest 1.9.14 version of the SDK.
Sorry for the trouble and thanks for letting us know of the issue.
