### ISSUE TITLE
Can't set SourceSecurityGroupId on an AuthorizeSecurityGroupIngressRequest

### ISSUE THREAD

**Issue by henrydavidge** [aws/aws-sdk-java#307]
The absence of this parameter denies the the user the ability to programmatically create ingress rules from other security groups within a vpc. As far as I can see there's no reason it should not be included.

**Comment by breedloj** [comment]
This is not an SDK side limitation as that parameter is not present in the EC2 API itself: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html

That said, unless I'm mistaken providing the SourceSecurityGroupName should allow you to explicitly define the source security group.

Due to the age of this issue I'm going to resolve, but feel free to re-open if you have additional questions or concerns.

**Comment by abarrafo** [comment]
I know this is old, but, in case anyone else is looking. The correct way to add/revoke an ingress rule with a source SG ID in a different VPC (same account yet not the default) is to use IPPermission with UserGroupId Collection. 

```        
        final UserIdGroupPair userIdGroupPair = new 
        UserIdGroupPair().withGroupId(sourceSgId).withDescription
                ("Enabling ES Access").withUserId(accountId);

        final IpPermission ipPermission = new IpPermission();
        ipPermission.setFromPort(fromPort);
        ipPermission.setToPort(toPort);
        ipPermission.setIpProtocol("TCP");
        ipPermission.setUserIdGroupPairs(Collections.singleton(userIdGroupPair));

        final AuthorizeSecurityGroupIngressRequest ingressReq = new AuthorizeSecurityGroupIngressRequest()
                .withGroupId(sgId)
                .withIpPermissions(ipPermission);

        final AmazonEC2 ec2 = awsClient.createEc2Client(region, lmAccount);
        return ec2.authorizeSecurityGroupIngress(ingressReq);
```

**Comment by balkrishan333** [comment]
> I know this is old, but, in case anyone else is looking. The correct way to add/revoke an ingress rule with a source SG ID in a different VPC (same account yet not the default) is to use IPPermission with UserGroupId Collection.
> 
> ```
>         final UserIdGroupPair userIdGroupPair = new 
>         UserIdGroupPair().withGroupId(sourceSgId).withDescription
>                 ("Enabling ES Access").withUserId(accountId);
> 
>         final IpPermission ipPermission = new IpPermission();
>         ipPermission.setFromPort(fromPort);
>         ipPermission.setToPort(toPort);
>         ipPermission.setIpProtocol("TCP");
>         ipPermission.setUserIdGroupPairs(Collections.singleton(userIdGroupPair));
> 
>         final AuthorizeSecurityGroupIngressRequest ingressReq = new AuthorizeSecurityGroupIngressRequest()
>                 .withGroupId(sgId)
>                 .withIpPermissions(ipPermission);
> 
>         final AmazonEC2 ec2 = awsClient.createEc2Client(region, lmAccount);
>         return ec2.authorizeSecurityGroupIngress(ingressReq);
> ```

Thanks a lot. It worked for me.
