### ISSUE TITLE
AWS SDK1 Java does not provide ability to authenticate to AWS STS via proxy that requires Kerberos Authentication

### ISSUE THREAD

**Issue by PankajSAgarwal** [aws/aws-sdk-java#3074]
### Describe the feature

Need to connect from on-prem to AWS STS API via proxy which requires Kerberos authentication .

### Use Case

Need to connect from on-prem to AWS STS API via proxy which requires Kerberos authentication .

Same use case as [Issue#4767](https://github.com/aws/aws-sdk-java-v2/issues/4767) raised for AWS SDK Java 2 

### Proposed Solution

If AWS can provide a provision to set `authSchemeProvider`  on instance of HttpClientBuilder  .

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/client/impl/ApacheHttpClientFactory.java#L86

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

1

### JDK version used

17

### Operating System and version

Windows Server 2016 Standard/ Linux

**Comment by debora-ito** [comment]
Hi @PankajSAgarwal, Java SDK v1 is not getting new features currently, it's unlikely we are going to add this. 

Please keep tracking the request in Java SDK v2.

**Comment by debora-ito** [comment]
Marking this to auto close soon. If you have any questions, feel free to post them here.
