### ISSUE TITLE
Avoid logging stack trace at INFO level

### ISSUE THREAD

**Issue by aztecrex** [aws/aws-sdk-java#308]
In  the class, _com.amazonaws.http.AmazonHttpClient_, around line 460 is this:

```java
            } catch (IOException ioe) {
                if (log.isInfoEnabled()) {
                    log.info("Unable to execute HTTP request: " + ioe.getMessage(), ioe);
                }
```

This exception often results in a retry, particularly for long-polling operations when the socket is reset. What happens, then, is that the log files are littered with INFO-level stack trace dumps that do not correspond to any interesting events. This increases the difficulty diagnosing real problems especially in long-lived process such as those polling for SWF work.

I propose that, in this case at least, the level be changed to DEBUG and that the code emit a single-line descriptive log entry saying the operation may be retried and names the exception. If it is important to get the stack trace for some purpose here, I suggest that it be dumped only when logging is at TRACE level.

**Comment by dagnir** [comment]
Hi @aztecrex Thanks again for reporting this and I apologize for the long delay. I have added a fix for this and it should be available in the next release of the SDK.
