### ISSUE TITLE
GetBlobStoreContext failing after updating the aws-sdk

### ISSUE THREAD

**Issue by melwinlobo21** [aws/aws-sdk-java#3082]
### Describe the bug

We have updated aws-sdk-java from **1.12.464** to **1.12.641**

After updating `AmazonWebServiceConfiguration.getBlobStoreContext` is failing with following error:
```sh
1) [Guice/ErrorInCustomProvider]: NoSuchMethodError: 'void ConstructorConstructor.<init>(Map)'
  at GsonModule.provideGson(GsonModule.java:99)
      \_ installed by: AWSS3HttpApiModule -> GsonModule
  at GsonWrapper.<init>(GsonWrapper.java:38)
      \_ for 1st parameter
  at GsonWrapper.class(GsonWrapper.java:32)
  while locating GsonWrapper
  while locating Json
```

The complete trace is quite long. I have included it in this file:
[error_logs.txt](https://github.com/aws/aws-sdk-java/files/14022416/error_logs.txt)

### Expected Behavior

```java
ContextBuilder.newBuilder(ObjectStoreServiceProviders.PROVIDER_AWS.toString())
				.credentials(this.getAccessKeyId(), this.getSecretAccessKey())
				.buildView(BlobStoreContext.class)
```

To return the BlobStoreContext

### Current Behavior

Described above.

### Reproduction Steps

Upgrade to 1.12.641

### Additional Information/Context

Dependencies Used:

```xml
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-bom</artifactId>
	<version>1.12.641</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>


<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-core</artifactId>
</dependency>
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-s3</artifactId>
<dependency>
```

### AWS Java SDK version used

1.12.641

### JDK version used

17

### Operating System and version

MacOS

**Comment by debora-ito** [comment]
@melwinlobo21  What's `AmazonWebServiceConfiguration.getBlobStoreContext`, is it your code? 

Also, I see you're using Guice/Gson, which are Google libraries. If the error is being thrown by those libs you'll need to reach out to their maintainers.

**Comment by melwinlobo21** [comment]
Hey @debora-ito ,

Thanks for the response. The issue was due to the JClouds library not being compatible with Gson 2.9 (https://issues.apache.org/jira/browse/JCLOUDS-1620)

This is not related to AWS SDK. Sorry for the trouble.

Regards,
Melwin Lobo
