### ISSUE TITLE
KMS: when EncryptionContext map is empty the service fails

### ISSUE THREAD

**Issue by kubek2k** [aws/aws-sdk-java#309]
I suspect its because of marshaller marshalling empty map more or less like:
```json
"EncryptionContext": {}
```

The idea would be to change that if to check if the map is empty
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-kms/src/main/java/com/amazonaws/services/kms/model/transform/EncryptRequestMarshaller.java#L70

or change
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-kms/src/main/java/com/amazonaws/services/kms/model/EncryptRequest.java#L168
to not to initialize field

I would go for the 1st option because it wouldn't break compability (because probably this lazy initialization in EncryptRequest was put there for some reason).

**Comment by manikandanrs** [comment]
This seems to be fixed. Closing now. 

Feel free to re-open if the issue still exists.
