### ISSUE TITLE
Update dependency: httpcomponents

### ISSUE THREAD

**Issue by asurovenko-zeta** [aws/aws-sdk-java#3090]
### Dependency update request

Since [org.apache.httpcomponents:httpcore](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore) has moved to [org.apache.httpcomponents.core5:httpcore5](https://mvnrepository.com/artifact/org.apache.httpcomponents.core5/httpcore5) need to replace deprecated dependency
The same with [org.apache.httpcomponents.httpclient](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient) has moved to [org.apache.httpcomponents.client5.httpclient5](https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5)

#####
Please update it in all your products, incude com.amazonaws:aws-java-sdk-ses

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.23.14

### JDK version used

21

### Operating System and version

CentOS 9

**Comment by asurovenko-zeta** [comment]
Please update it in all your products, incude **com.amazonaws:aws-java-sdk-ses**

**Comment by debora-ito** [comment]
@asurovenko-zeta we are tracking this in the Java SDK V2 repository here: https://github.com/aws/aws-sdk-java-v2/issues/2831.

Will close this as a duplicate, please use the issue in V2 to check updates on the progress.
