### ISSUE TITLE
[Auth] the pod falling back to instance role instead of IRSA

### ISSUE THREAD

**Issue by bseenu** [aws/aws-sdk-java#3096]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

I am aware of the default credential provider chain, where the next credential provider is called in the chain, ref: https://github.com/aws/aws-sdk-java-v2/issues/3896

My app is calling the dynamo db api, and all i am seeing is 

`2024-02-15 14:33:03.236 Error querying table user with request {TableName: user,IndexName: userId-index,Limit: 100,ConsistentRead: false,KeyConditionExpression: userId = :userId,ExpressionAttributeValues: {:userId={S: XXXX,}}} : com.amazonaws.http.timers.client.ClientExecutionTimeoutException: Client execution did not complete before the specified timeout configuration.`

Following the timeouts i am seeing the accessdenied exceptions, And just before that i am seeing a call being made to IMDS -`/latest/meta-data/iam/security-credentials`

I am using the aws-java-sdk-dymanodb:1.12.267

Are the assume role calls retried, i do not see in the log that the web identity credentials has failed and it is moving with other providers in the chain, whenever this happens all the subsequent calls are using the instance role credentials failing the dynamo api call's

Are there any other better solutions here 

### Expected Behavior

i want the IRSA role to be used with the app

### Current Behavior

it does not use IRSA role when there are timeouts

### Reproduction Steps

NA

### AWS Java SDK version used

1.12.267

### JDK version used

17

### Operating System and version

linux

**Comment by debora-ito** [comment]
@bseenu apologies for the silence.

Can you provide the full stacktrace of the errors?

My guess is that the ClientExecutionTimeoutException is not necessarily related to the IAM imds credential fetching.
