### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by alayne-xumo** [aws/aws-sdk-java#3106]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

This bug stems from the fact that s3 "urls" dont conform to the url spec, because they allow things like spaces which for urls have to be encoded. While "s3://mybucket/my key+something" is a valid s3 url it is not a valid url/uri.

So   final S3Uri s3Uri = s3.utilities().parseUri(URI.create(s3Url)); results in a parse exception. parseUri should probably accept a string instead of a Uri.
        
             
             

### Expected Behavior

I should be able to parse any s3 "url" that will resolve to an object in s3.

### Current Behavior

Illegal character in path at index 16: s3://mybucket/my key+something

### Reproduction Steps

        try (final S3Client s3 = S3Client.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(credentialsProvider)
                .build()) {
            final S3Uri s3Uri = s3.utilities().parseUri(URI.create("s3://mybucket/my key+something"));

### Possible Solution

parseUri should accept a string.

### AWS Java SDK version used

2.20.45

### JDK version used

8

### Operating System and version

Sonoma

**Comment by debora-ito** [comment]
@alayne-xumo sorry for the long silence.

The use of special characters are addressed in the `S3Utilities::parseUri` [javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Utilities.html#parseUri(java.net.URI)):

> If you work with object keys and/or query parameters with special characters, they must be URL-encoded, e.g., replace " " with "%20"

Example: 
```Java
        S3Utilities s3Utilities = s3Client.utilities();
        String uriString = "s3://mybucket/my%20key+something";
        S3Uri s3Uri = s3Utilities.parseUri(URI.create(uriString));

        String bucket = s3Uri.bucket().orElse(null); // "mybucket"
        String key = s3Uri.key().orElse(null); // "my key+something"
```
