### ISSUE TITLE
Resourcegroupstaggingapi error when running on FIPS

### ISSUE THREAD

**Issue by penglerts** [aws/aws-sdk-java#3128]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

When we set `-Daws.useFipsEndpoint=true` then we have exception `Caused by: java.net.UnknownHostException: tagging-fips.eu-west-2.amazonaws.com` (calling e.g. `software.amazon.awssdk.services.resourcegroupstaggingapi.ResourceGroupsTaggingApiAsyncClient#getResources` ).

Is this endpoint coreect? it is set automatically by SDK.

### Expected Behavior

FIPS endpoint works

### Current Behavior

UnknownHostException

### Reproduction Steps

set `-Daws.useFipsEndpoint=true` and call `software.amazon.awssdk.services.resourcegroupstaggingapi.ResourceGroupsTaggingApiAsyncClient#getResources`

### AWS Java SDK version used

software.amazon.awssdk.resourcegroupstaggingapi:2.26.12

### JDK version used

openjdk version "21.0.1" 2023-10-17 LTS

### Operating System and version

ubuntu

**Comment by debora-ito** [comment]
The Resource Groups Tagging service doesn't have a FIPS endpoint, according to the service Endpoints and Quota page:
https://docs.aws.amazon.com/general/latest/gr/arg.html

The SDK will construct the FIPS endpoint based on the normal endpoint for that service, and use it in the client, but it doesn't know if the FIPS endpoint exists or not.

Another reference is the list of available FIPS endpoints by service - 
https://aws.amazon.com/compliance/fips/#FIPS_Endpoints_by_Service

**Comment by penglerts** [comment]
thanks for a reply. what about Service `AWS Resource Groups` is it not the same as `Resource Groups Tagging`?
