### ISSUE TITLE
Unable to build the 'ALL' sdk jar from source

### ISSUE THREAD

**Issue by brucej72** [aws/aws-sdk-java#313]
Trying to build the SDK 1.9.8 from source (have done this many times before pre-modularization). Per the instructions:
- checkout from github
- mvn clean install -Dgpg.skip=true

I find the individual module jars are correctly created, but the top level jar (presumably located in aws-java-sdk/target/aws-java-sdk-1.9.8.jar) is only 2360 bytes in size.

How do you now build the complete jar containing everything per the binary download?

**Comment by david-at-aws** [comment]
As discussed on #314, the aws-java-sdk-osgi module now builds a single uberjar containing the whole SDK for users who prefer to consume it that way.

```sh
mvn clean install
jar -tf aws-java-sdk-osgi/target/aws-java-sdk-osgi-{version}.jar
```
