### ISSUE TITLE
Issues with AWS SDK after migrating from CentOS to Amazon AMI

### ISSUE THREAD

**Issue by OliverKaunds** [aws/aws-sdk-java#3133]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

We recently migrated our web servers from CentOS to Amazon Linux (Amazon AMI). After this migration all connections that our Web Server was making to AWS Cloud started failing. These are old solutions that are live on production for at least a couple of years. We have not changed any code when we did the migration, the same code base is deployed.

The SDK on the Amazon AMI the following three pieces of information:
1) Region
2) Client Secret
3) Access Key

Our Infra team has checked the configurations on both old and new servers and they seem to be identical. 
After referring to https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html we suspect that the above three pieces of information is coming from environment variables. For some reason on the old server the application is able to find this information whereas on the new one it is not able to find. 

This is a serious blocker for us. Request you to kindly help sharing sanitized stack trace for reference

### Expected Behavior

When we migrate from the OS from CentOS to Amazon AMI we shouldn't have to make any code changes to our code.
The same AWS SDK should work seamlessly. 

### Current Behavior

The SDK is not connecting to AWS services from our Web Server.
[AWS Exception.txt](https://github.com/user-attachments/files/16379526/AWS.Exception.txt)

### Reproduction Steps

No changes to Code.

### Possible Solution

Refactor all code to use Client Secret, Access Key and Region explicitly. But this is hard to do in more than 200+ places.

### Additional Information/Context

Happens consistently on all our Amazon AMI instances.

### AWS Java SDK version used

1.11.xx

### JDK version used

8

### Operating System and version

Amazon AMI

**Comment by debora-ito** [comment]
@OliverKaunds I've updated the internal case created for this, posting here for posterity:

If there was no code or SDK version change, this indicates the issue is not in the SDK, the SDK does not change behavior if the code is the same. This is most likely a misconfiguration in the application environment.

**Comment by OliverKaunds** [comment]
The issue was because our EC2 instance had IMDSv2 enforced. When we changed it to IMDSv2 optional it allows IMDSv1 and v2 both.
After this change our AWS SDK code deployed on this EC2 was able to hit the IMDSv1 urls and the AWS SDK was able to make connection with AWS resources. 

In short we need to enable IMDSv1 to resolve the issue.
