### ISSUE TITLE
Binary SDK build does not contain OSGi metadata in Manifest

### ISSUE THREAD

**Issue by brucej72** [aws/aws-sdk-java#314]
Additionally to #313 the reason I'm trying to build the sdk from source is that the binary build does not contain any OSGi metadata in the manifest, although this should have been fixed per the pull request on 1.9.7 of the SDK.

**Comment by sopel** [comment]
Hi @breedloj, could you please briefly comment on why this has been closed? The split package issue that is blocking proper OSGi support for individual modules seems to be in place still - does this mean you are not going to address it ever, not even for an eventual 2.0 release (given it might require a backwards incompatible package refactoring)? Thanks much!

**Comment by breedloj** [comment]
Hi Steffen,

We do still have this on our radar and are tracking it internally.  We've recently been trying to clean up some of our older outstanding issues.  This was my bad for simply closing the issue without giving a status update.  Given your continued interest in OSGi improvements I am fine with re-opening the issue.

**Comment by muellerc** [comment]
I'm working on it...

**Comment by muellerc** [comment]
There are many modules which are using the package "com.amazonaws.auth.policy.actions" which will violate the OSGI constraints. These packages only include one enum which implements com.amazonaws.auth.policy.Action. I will annotate these enums with @deprecated and provide an alternative in the package "com.amazonaws.services.<<service name>>.auth.policy.actions".
Any thoughts?

**Comment by debora-ito** [comment]
@brucej72 @sopel @muellerc 

The SDK team has reviewed the feature request list for V1 and decided to not implement this since they're concentrating efforts on V2 new features. This was already addressed in V2.

Feel free to reach out if you have any questions or comments.
