### ISSUE TITLE
Infinite loop: com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:118)

### ISSUE THREAD

**Issue by aballa-perforce** [aws/aws-sdk-java#3140]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

We are integrating connecting to RDS using IAM service accounts using `assumedRoles` across AWS accounts.

Attached complete log.

`com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials` is going in an infini
[aws.log](https://github.com/user-attachments/files/16707352/aws.log)
te loop.

`at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:118)` is getting called repeatedly from at `com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1269)`

Below is the code from `com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext` and `credentialsProvider` is getting set to `AWSCredentialsProviderChain` and that is the reason it is going into infinite loop.

![image](https://github.com/user-attachments/assets/7439daf4-1c38-4862-adbb-4d8a45a7a145)

 

### Expected Behavior

It should be able to get credentials.

### Current Behavior

Inifite loop.

### Reproduction Steps

See description.

### AWS Java SDK version used

1.12.682

### JDK version used

1.8

### Operating System and version

Linux

**Comment by debora-ito** [comment]
@aballa-perforce can you share a [SSCEE](https://sscce.org) code example that we can use to repro?
