### ISSUE TITLE
Source jar should also be published to the Maven repository

### ISSUE THREAD

**Issue by mslinn** [aws/aws-sdk-java#315]
It's great that the binary jar is available via Maven, but it would be much more convenient if the src jar was also published. For example, here is a `build.sbt` entry that attempts to download both the binary and src jars:

    "com.amazonaws" % "aws-java-sdk" % "1.9.8" withSources()

Here is what SBT shows:

````
[info] downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.9.8/aws-java-sdk-1.9.8.jar ...
[info] 	[SUCCESSFUL ] com.amazonaws#aws-java-sdk;1.9.8!aws-java-sdk.jar (271ms)
[warn] 	[NOT FOUND  ] com.amazonaws#aws-java-sdk;1.9.8!aws-java-sdk.jar(src) (109ms)
````

**Comment by manikandanrs** [comment]
The source jar is published to maven in aws-java-sdk-osgi module. This module is a consolidated module contains the whole AWS Java SDK code.

https://oss.sonatype.org/#nexus-search;quick~aws-java-sdk-osgi

Let us know if this works for you. Feel free to re open if there is still issues.

**Comment by mslinn** [comment]
I used this SBT dependency:

    "com.amazonaws"          %  "aws-java-sdk"        % "1.9.31" withSources()

And I got this result after all the binary jars downloaded:

    [error] (*:update) sbt.ResolveException: download failed: com.amazonaws#aws-java-sdk;1.9.31!aws-java-sdk.jar(src)

**Comment by hansonchar** [comment]
Hi @mslinn,

Have you tried the consolidated jar <b>aws-java-sdk-osgi</b> (which has all the code of AWS Java SDK included) ?

For example,

> "com.amazonaws"          %  "aws-java-sdk-osgi"        % "1.9.31" withSources()

**Comment by mslinn** [comment]
That did the job! :+1:

**Comment by manikandanrs** [comment]
@mslinn Glad to hear that it aws-java-sdk-osgi module worke for you.
