### ISSUE TITLE
method not found: AnonymousAWSCredentials

### ISSUE THREAD

**Issue by huycse31501** [aws/aws-sdk-java#3153]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

This file forgets to import AnonymousAWSCredentials as the beginning of the file, causing the error to popup

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No bugs

### Current Behavior

Bugs (method not found)

### Reproduction Steps

Just use the sdk on the file path and its gonna show

### Possible Solution

Import the method at the beginning of the file

### AWS Java SDK version used

AWS SDK for Java 1.12.771

### JDK version used

17

### Operating System and version

MAC OS

**Comment by debora-ito** [comment]
Hi @huycse31501 `STSAssumeRoleWithWebIdentitySessionCredentialsProvider` and `AnonymousAWSCredentials` are in the same package `com.amazonaws.auth`, so the import statement is not needed.

What's the actual issue you are running into? Can you provide the full stacktrace of the error and a repro code?

**Comment by debora-ito** [comment]
Is is NotSuchMethodError?

[How do I fix a NoClassDefFoundError, NoSuchMethodError or NoSuchFieldError?](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/troubleshooting.html#faq-classpath-errors)

**Comment by huycse31501** [comment]
Hi, its not there
![image](https://github.com/user-attachments/assets/a833dc11-c611-4d22-a7d5-8ea95febb0f8)

**Comment by huycse31501** [comment]
Ah yes we are also trying to standardize the aws-java-sdk-bundle version in our codebase, leaving no strictly version dependencies of other in it. But I just want to raise it so we could have a check here

**Comment by debora-ito** [comment]
They are in the same package, just not in the same SDK module. Java SDK v1 has split packages.

STSAssumeRoleWithWebIdentitySessionCredentialsProvider is in `com.amazonaws:aws-java-sdk-sts`, AnonymousAWSCredentials is in `com.amazonaws:aws-java-sdk-core`.

What's the actual issue you are running into? Can you provide the full stacktrace of the error and a repro code?
