### ISSUE TITLE
MPU failed to upload part of files

### ISSUE THREAD

**Issue by zhaohehuhu** [aws/aws-sdk-java#3158]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

I adopt AWS MPU to upload tons of files in parallel, and all MPU upload request is done after calling completeMultipartUpload. But I checked the AWS s3 and found some files failed to be uploaded on AWS. 

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

all MPU upload request is done and all files are on AWS.

### Current Behavior

 some files failed to be uploaded on AWS and there is no any error message shown.

### Reproduction Steps

1. Initialize AWS S3 Client
2. Simulate 3000 Upload Requests:
3. Complete the upload through calling completeMultipartUpload function

### AWS Java SDK version used

1.12.532

### JDK version used

JDK 8

### Operating System and version

Centos

**Comment by debora-ito** [comment]
@zhaohehuhu please provide:
-  a self-contained code sample we can use to reproduce
- the full error stacktrace


Consider using the Java SDK 2.x [S3TransferManager](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html), it will manage multipart uploads automatically. The Java SDK 1.x is under Maintenance Mode and will only receive security updates and critical bugfixes.

**Comment by zhaohehuhu** [comment]
> @zhaohehuhu please provide:
> 
> * a self-contained code sample we can use to reproduce
> * the full error stacktrace
> 
> Consider using the Java SDK 2.x [S3TransferManager](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html), it will manage multipart uploads automatically. The Java SDK 1.x is under Maintenance Mode and will only receive security updates and critical bugfixes.

Thanks. I'll take a shot.
