### ISSUE TITLE
DescribeInstancesRequest.java doc comment '<code>network-interface.network-interface.id</code>' incorrect

### ISSUE THREAD

**Issue by jhorriga** [aws/aws-sdk-java#317]
DescribeInstancesRequest.java doc comment '<code>network-interface.network-interface.id</code>' incorrect. It should read: <code>network-interface.network-interface-id</code>. Note the subtle difference between .id and -id

**Comment by manikandanrs** [comment]
I believe this fixed in the latest code. Feel free to re open if you still see this incorrect java doc.
