### ISSUE TITLE
Check size of values list to Filter

### ISSUE THREAD

**Issue by llarsson** [aws/aws-sdk-java#320]
Since there seems to be a limit at how many values one can successfully specify as `com.amazonaws.services.ec2.model.Filter` values (I just got an error trying to go above 200), I think it would be prudent to check this precondition as an invariant in the `setValues(java.util.Collection<String> values)` method and throw an `java.lang.IllegalArgumentException` if the size exceeds the limit.

**Comment by zhangzhx** [comment]
I'm closing this issue. To keep track of this, go to the related pull request #324 .
