### ISSUE TITLE
Java retry delay goes from 0 to 2*scale factor

### ISSUE THREAD

**Issue by cbroglie** [aws/aws-sdk-java#323]
If the scale factor is 25ms, the first delay will be 0ms, and the next will be 50ms, then 100ms, and so on. A delay of 25ms will be skipped.

Consider this code: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L242

`retries` will always be >= 1 there (b/c of the early return when it is <= 0), so you will end up with a minimum delay of `2*SCALE_FACTOR`. Depending on the desired behavior, the fix would be to change to early return to < 0, or change the shift to `1 << (retries-1)`.

**Comment by hanshuo-aws** [comment]
The fix has been released in the latest 1.9.14 version.
