### ISSUE TITLE
Avoid overloading region property in AmazonWebServiceClient

### ISSUE THREAD

**Issue by aemruli** [aws/aws-sdk-java#325]
The commit https://github.com/aws/aws-sdk-java/commit/d7ab60c7ae1153a15ff05b33d01f52a135b5005a introduces a new setRegion(Regions) method that overloads the existing setRegion(Region) method. This causes problems if the client is configured in the Spring Framework or any other framework that uses the java.beans.Introspector to gather the accessor (write/read) methods. 
Please add a getter for the Region/Regions to make the class again "compatible" to the java.beans.Introspector which marks the particular setter (those type is returned by the getter) as the primary set method. 

Otherwise it is hard to to use the SDK in any DI context (e.g. https://github.com/spring-cloud/spring-cloud-aws)

**Comment by madama** [comment]
+1 for this issue. I've problem to set it properly with Spring

**Comment by hansonchar** [comment]
Unfortunately there already exists a `getRegion` method in AmazonS3Client, but with a different return type:

```java
public Region getRegion();
```
This makes it impossible to add a `getRegion` method that returns `Regions` in `AmazonWebServiceClient` without breaking backward compatibility.

**Comment by madama** [comment]
Actually I resolved in `Spring` using the `MethodInvokingFactoryBean` to save the `Region` and then use it
```
aws.region=eu-west-1
```
```xml
<bean id="awsRegion" class="org.springframework.beans.factory.config.MethodInvokingFactoryBean">
    <property name="targetClass" value="com.amazonaws.regions.RegionUtils"/>
    <property name="targetMethod" value="getRegion"/>
    <property name="arguments">
        <list>
            <value>${aws.region}</value>
        </list>
    </property>
</bean>

<bean id="simpleDB" class="com.amazonaws.services.simpledb.AmazonSimpleDBClient">
    <constructor-arg ref="awsSimpleDBCredentialsProvider"/>
    <property name="region" ref="awsRegion"/>
</bean>
```
