### ISSUE TITLE
SDK can't list bucket nor delete S3 object with characters in range [0x00 - 0x1F]

### ISSUE THREAD

**Issue by SoMCUSDev** [aws/aws-sdk-java#333]
According to the S3 objects naming scheme, [0x00 - 0x1F] are valid characters for the S3 object. However, it's not possible to list bucket with such objects using the SDK (XML parser chokes on them) and also, they can't be deleted thru multi objects delete (also XML failure). What is interesting, download works just fine.

This is what I'm getting for delete operation, for example (the similar one for list objects operation as well):
com.amazonaws.services.s3.model.AmazonS3Exception: The XML you provided was not well-formed or did not validate against our published schema (Service: Amazon S3; Status Code: 400; Error Code: MalformedXML; Request ID: **), S3 Extended Request ID: **

**Comment by shorea** [comment]
URL encoding is now the default in the SDK. Closing issue.

**Comment by mcandre** [comment]
> URL encoding is now the default in the SDK. Closing issue.

Which release version implements this?

**Comment by leo237** [comment]
Hi! I'm using AWS SDK for Java 1.11.x and am facing the same issue. Can you tell me if the fix was made available? My issue is with the DeleteObjectsRequest API.
