### ISSUE TITLE
1.9.11 DynamoDBTableSchemaParser.parseTablePOJOToCreateTableRequest ignore none-key attribute

### ISSUE THREAD

**Issue by flashflexpro** [aws/aws-sdk-java#335]
Inside this method, it is only processing primary keys and index keys, but in the document:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBAttribute.html

all the attributes should processed as attribute except marked "@SynamoDBIgnore"

this leads the generated createTableRequest only have table key attributes!

**Comment by david-at-aws** [comment]
This is intentional and correct. CreateTableRequest's [AttributeDefinitions](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-AttributeDefinitions) member should only contain definitions for primary keys and index keys of the table. If you add definitions for other attributes, you'll actually get an error back from the service when you send the request:

```
Exception in thread "main" com.amazonaws.AmazonServiceException: One or more
parameter values were invalid: Some AttributeDefinitions are not used. AttributeDefinitions:
[index, hash, extra], keys used: [index, hash] (Service: AmazonDynamoDBv2; Status Code: 400;
Error Code: ValidationException)
```

When calling any of the DynamoDBMapper methods that store data into DynamoDB or load data back out, all of the members of the POJO that are not annotated ```@DynamoDBIgnore``` are considered.

**Comment by flashflexpro** [comment]
Thank you David, and please excuse me for asking rookie questions, but I was creating a global index on a attribute( not a key ) with the createTableRequest generated by mapper:


            CreateTableRequest createTableRequest = mapper.generateCreateTableRequest( TheMessage.class );
            createTableRequest.setProvisionedThroughput( new ProvisionedThroughput( 2L, 5L ) );

            createTableRequest.setGlobalSecondaryIndexes( PersistMessage.createGlobal2ndIndexes() );



com.amazonaws.AmazonServiceException: One or more parameter values were invalid: Some index key attributes are not defined in AttributeDefinitions. Keys: [csActType, lastIndexTime], AttributeDefinitions: [csSessionId, recTimeStamp, lastIndexTime] (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID ...


that is why I thought the request should contain all attributes, could you give me a tip how to make this work please?

**Comment by david-at-aws** [comment]
No worries, happy to help. The mapper will automatically create the index definition and relevant attribute definition(s) for you if you add the ```@DynamoDBIndexHashKey``` annotation to the relevant member of your TheMessage class.

```java
public class TheMessage {
    ...
    @DynamoDBIndexHashKey(globalSecondaryIndexName="YourIndexNameHere")
    private String recTimeStamp;
    ...
}
```

You'll need to fill in the provisioned throughput for the index, as you do for the table as a whole, and you may want to twiddle the projection (which defaults to KEYS_ONLY).

**Comment by flashflexpro** [comment]
It works, thank you very much for the help!
