### ISSUE TITLE
Implement com.amazonaws.services.s3.model.S3ObjectSummary.toString()

### ISSUE THREAD

**Issue by ceefour** [aws/aws-sdk-java#338]
To make it easier & more convenient for debugging.

**Comment by hanshuo-aws** [comment]
@ceefour It's definitely a reasonable request. Do you want to contribute a pull-request for this?:smiley:

**Comment by breedloj** [comment]
This has (finally) been staged and will be going out with our next release.  Thanks for the patience on this one.
