### ISSUE TITLE
[Feature request] Avoid extra S3 request if size of object is known 

### ISSUE THREAD

**Issue by SoMCUSDev** [aws/aws-sdk-java#340]
I'd like to propose a feature request.

In https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L741 there is a s3.getObjectMetadata() request the whole purpose of it is to find the size of the object which is going to be downloaded.

What if I already know the size? In this case - those getObjectMetadata() requests just a waste and only introduce more costs and slows the code execution. Please, introduce additional methods as https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L689 & https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L729, etc but with additional parameter - objectLength and if it's called, avoid doing getObjectMetadata().

**Comment by sopel** [comment]
@manikandanrs - This seems to have been addressed by #363, which has been published as of [AWS SDK for Java 1.9.25](https://aws.amazon.com/releasenotes/Java/1588204245623789):
> Merged GitHub pull request #363 and #379.

**Comment by aletheia** [comment]
Ecco due esempi







—
Luca Bianchi PhD
bianchi.luca@gmail.com

**Comment by aletheia** [comment]
Sorry, I sent mail to the wrong address…




I am terribly sorry


—
Luca Bianchi PhD
bianchi.luca@gmail.com
