### ISSUE TITLE
HadoopJarStepConfig withArgs(Collection) overwrites other args, but withArgs(String...) does not

### ISSUE THREAD

**Issue by jonchase** [aws/aws-sdk-java#341]
I believe the (String...) variant behaves correctly, as this produces the expected result (script, arg1, arg2):

```
new StepFactory().newScriptRunnerStep("script").withArgs("arg1", "arg2")
```

whereas this does not (it produces arg1, arg2):

```
new StepFactory().newScriptRunnerStep("script").withArgs(Lists.newArrayList("arg1", "arg2"))
```

Test case:

```
import static org.junit.Assert.assertEquals;

import com.amazonaws.services.elasticmapreduce.model.HadoopJarStepConfig;
import com.google.common.collect.Lists;
import org.junit.Test;

import java.util.List;

public class HadoopJarStepConfigTest {

    @Test
    public void testWithArgsBehaviorVaries() {
        // given:
        List<String> expected = Lists.newArrayList("arg1", "arg2", "arg3");
        String[] asArray = new String[]{"arg2", "arg3"};
        List<String> asCollection = Lists.newArrayList("arg2", "arg3");

        // when:
        HadoopJarStepConfig ok = new HadoopJarStepConfig().withArgs("arg1").withArgs(asArray);
        HadoopJarStepConfig bad = new HadoopJarStepConfig().withArgs("arg1").withArgs(asCollection);

        // then:
        assertEquals("args should also contain 'script'", expected, ok.getArgs());
        assertEquals("args should also contain 'script'", expected, bad.getArgs()); // fails
    }
}
```

The (Collection) call overwrites the existing args, whereas the (String...) call appends.

**Comment by hanshuo-aws** [comment]
> The (Collection) call overwrites the existing args, whereas the (String...) call appends.
@jonchase Your observation is absolutely correct. Admittedly this is kinda a confusing user experience -- we can't change this behavior and break existing customers who actually rely on it though. But I will see how we can improve our javadoc (they are code-generated) to clearly document the behavior and make it less surprising.

**Comment by jonchase** [comment]
Thanks, clarification in the docs would be helpful.

**Comment by hanshuo-aws** [comment]
The documentation has been updated in 1.9.31 version.
