### ISSUE TITLE
TableNameOverride with suffix

### ISSUE THREAD

**Issue by chook** [aws/aws-sdk-java#343]
Hi, besides withTableNamePrefix I want to add withTableNameSuffix to TableNameOverride.
I want TableNameOverride to provide both prefix and suffix if needed.

I don't mind implement it - would you consider pulling it or was it already discussed and decided not to be included in the SDK?

**Comment by hanshuo-aws** [comment]
Hi,

A recent addition to the dynamodb-mapper library introduces [TableNameResolver](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.java#L444), which allows you to fully control the target table name for a specific Pojo object or class.
The SDK's default implementation can be found [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.java#L487), and it should be fairly straightforward to implement your own strategy and pass it to the mapper via DynamoDBMapperConfig.

I will close the issue for now, and please let us know if you have any further question.

**Comment by chook** [comment]
thanks, does that mean TableNameOverride will eventually get deprecated? If I understand you correctly, it currently doesn't do anything the TableNameResolver can't

**Comment by hanshuo-aws** [comment]
Currently we don't have plan to deprecate TableNameOverride. Existing customers relying on it should still keep using it if they only need a simple mechanism to override the table-name. The new TableNameResolver is aimed for more advanced use cases - although it does cover all the functionality of TableNameOverride, I still see the value in keeping both of them in the API.
