### ISSUE TITLE
[SWF] Implement DecisionTaskPoller.awaitTermination.

### ISSUE THREAD

**Issue by zstd** [aws/aws-sdk-java#346]
Right now method DecisionTaskPoller.awaitTermination not implemented (there is only TODO item) and WorkflowWorker stops without waiting for currently active polling task to complete.

This may lead to sporadical errors in situation when we stop workflow and start it immediately: in that case stopped workflow may 'steal' decision task from starting workflow without ability to process it - that will cause decision task timeout.

**Comment by christophercurrie** [comment]
:+1: for this. Implementing graceful shutdown is very difficult (read: impossible) without a proper lifecycle implementation.

**Comment by zstd** [comment]
Ок. I have seen the code and understand that if this feature was trivial it was already implemented. 
Nevertheless, I'd be glad to hear if this improvement was at least planned for 'not-so-near' future.

**Comment by manikandanrs** [comment]
This issue was moved to aws/aws-swf-flow-library#6
