### ISSUE TITLE
Flow Framework: Release build tools jar to Maven Central

### ISSUE THREAD

**Issue by christophercurrie** [aws/aws-sdk-java#347]
The flow build tools jar is only available by downloading the SDK from the AWS website, which makes it awkward to integrate into Maven-driven AspectJ compilation. Please consider releasing this JAR to Maven central so that end users don't need to install it locally. See [stackoverflow](aws-java-sdk-flow-build-tools-1.9.16) for more details of this scenario.

**Comment by mirceal** [comment]
+1

**Comment by flozano** [comment]
+1 here

**Comment by DuvallK** [comment]
Now that Amazon has separated the SDK in Maven into multiple modules, this seems like a logical next step.

**Comment by ericdcobb** [comment]
:+1:

**Comment by vvondra** [comment]
+1

**Comment by kanderson450** [comment]
@fulghum Any update on this issue & #349 ?

**Comment by kristianperkins** [comment]
+1

**Comment by srmds** [comment]
+1

**Comment by ajkerr** [comment]
+100. We asked about this literally years ago on the support forums, and never received a response as to why this jar is not published. I'm guessing there is a licensing issue at play here, but if so, why not just tell us that?

**Comment by srmds** [comment]
@ajkerr Amen to you!

**Comment by ajkerr** [comment]
To make matters worse, recent versions of the full SDK have misnamed versions of this jar file, e.g. aws-java-sdk-flow-build-tools.jar-1.10.65.jar (note the extra '.jar' before the version number).

**Comment by fulghum** [comment]
Hey guys, sincere apologies for the lack of response from us on this issue.  The Flow library is maintained by another team, separate from the AWS SDK for Java team, and unfortunately this issue fell through the cracks.  I'm happy to let you know that we are now actively working on getting the Flow build tools published to Maven.  The Flow team is working on this, and if they hit any snags, we're going to jump in and help them out.  

@ajkerr – As to the jar naming issue, @manikandanrs just fixed this issue in our build logic and we'll get the fix published in the next SDK release going out next week.  

Apologies again that it's taken us longer than we'd like to help out with this problem.  As always, thank you for all the feedback; please keep it coming!  We'll have an update on this for you by the end of next week.

**Comment by varunnvs92** [comment]
Hey guys, apologies for not getting back sooner. The AWS SDK for Java team has now released the SWF build tools jar to Maven. You can add this as a dependency by:
```
    <dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>aws-swf-build-tools</artifactId>
       <version>1.0</version>
    </dependency>
```
I hope this solves the issue that you were facing. Try it out and give us your feedback.

**Comment by umcodemonkey** [comment]
@varunnvs92 Thanks, this will help immensely. However, I notice that the POM declares the SCM location to be https://github.com/aws/aws-swf-build-tools.git, which does not appear to be publicly available, despite the declaration of Apache 2.0 licensing.

This issue is tracked separately as #349, I'll follow up there as well.

**Comment by manikandanrs** [comment]
@umcodemonkey we are working on getting it to a separate Github repository. Stay tuned.

**Comment by mirceal** [comment]
awesome. thanks @fulghum and @varunnvs92 !

**Comment by egglestonbd** [comment]
@varunnvs92, 
The sdk download page references v. 1.10.71 (http://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip) which includes the build flow tools.  And your reference above references 1.0.  How do they line up?

**Comment by varunnvs92** [comment]
@egglestonbd Thanks for bringing it up. **Both jars are exactly the same**. The build tools jar is owned by a different team, so the maven artifactId is named accordingly. We will be renaming the build flow tools jar in aws-java-sdk.zip to match maven within the next few releases. We are investigating the effect of this and will act accordingly. Please let me know if you have more questions. Thank you.

**Comment by ajkerr** [comment]
Great news! Happy this is finally done.

**Comment by manikandanrs** [comment]
Closing this issue as the jar is published to maven.
