### ISSUE TITLE
[AmazonS3Client] fails first request when Signer V4 is required in us-east-1

### ISSUE THREAD

**Issue by mapoulin** [aws/aws-sdk-java#348]
I am using S3 encryption with a AWS KMS managed key and I get the following warning in my logs when I try to upload a file : 

>  WARN  c.a.services.s3.AmazonS3Client - Attempting to re-send the request to bucketname.s3-external-1.amazonaws.com with AWS V4 authentication. To avoid this warning in the future, please use region-specific endpoint to access buckets located in regions that require V4 signing.

Even if I specified the region on my `AmazonS3Client` exactly as described in the `AmazonS3Client#setEndpoint` method :

> If you want to use Signature Version 4 to access a bucket in the
> US Classic region (which does not have a region-specific endpoint),
> you'll need to call setRegion(Region.getRegion(Regions.US_EAST_1))
> to explicitly tell us which region to include in the signature.

I also enabled Signature V4 using the system property.

```java
System.setProperty(SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY, "true");
```

Since the first request is made to `s3.amazonaws.com` (comes from the default us-east-1 endpoint defined in `com/amazonaws/regions.xml` from what I understand) and then retried to `s3-external-1.amazonaws.com`, would it be possible to detect the right endpoint when specifying us-east-1 before having to retry?

Test Case : 
```java
    @Test
    public void s3UsEastSignerV4()
    {
        System.setProperty(SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY, "true");

        AmazonS3Client s3Client = new AmazonS3Client();
        s3Client.setRegion(Region.getRegion(Regions.US_EAST_1));

        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentLength(0);

        PutObjectRequest request = new PutObjectRequest("bucket", "key", new ByteArrayInputStream(new byte[0]), metadata);
        request.setSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams("KMSKey"));

        s3Client.putObject(request);
    }
```

**Comment by manikandanrs** [comment]
@mapoulin 
All KMS requests require SigV4 signing. There isn't a specific endpoint for US_EAST_1 region. It uses the classic end point "s3.amazonaws.com"

The system property that you have mentioned is ignored when the endpoint is a classic endpoint. 

To avoid this warning if accessing an object through classic endpoint, set the other system property SDKGlobalConfiguration.ENFORCE_S3_SIGV4_SYSTEM_PROPERTY in addition to setting the region as US_EAST_1.

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#ENFORCE_S3_SIGV4_SYSTEM_PROPERTY

**Comment by mapoulin** [comment]
@manikandanrs 
I would rather not have to enforce a specific version of the signature. I feel like this could be abstracted from the user, especially when the request requires a specific version such as SSE-KMS. Could the library detect from my request which version of Signature it should use without having to retry ?

**Comment by manikandanrs** [comment]
@mapoulin 

The library does detect which version of signature is required based on service and region. This information is available in the <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/awssdk_config_default.json">config</a>. Using the classic endpoint, users can access buckets in other regions as well. If enabling Sigv4 for KMS requests, then the SDK cannot by default sign the request using "us-east-1" because the bucket might be in different region. 

Alternatively, you could use the endpoint s3-external-1.amazonaws.com, but you still need to set the SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY system property.

We are also looking into the option of automatically upgrading the requests to SigV4 for PUT requests with KMS. But it might take sometime.

**Comment by mapoulin** [comment]
>  If enabling Sigv4 for KMS requests, then the SDK cannot by default sign the request using "us-east-1" because the bucket might be in different region.

I don't mind having to specify the region. Although, I'm using `Regions.getCurrentRegion()`. I'm assuming the `s3.amazonaws.com` DNS resolves to the same region as the one given in the EC2 Metadata. I might be wrong on this one.

> Alternatively, you could use the endpoint s3-external-1.amazonaws.com, but you still need to set the SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY system property.

Indeed, this is what i did.

>We are also looking into the option of automatically upgrading the requests to SigV4 for PUT requests with KMS. But it might take sometime.

Perfect, that is what I was hoping for.

Thanks @manikandanrs

**Comment by manikandanrs** [comment]
This is fixed as part of <a href="https://aws.amazon.com/releasenotes/Java/8255923333358616">1.9.18</a> release.
