### ISSUE TITLE
[SWF] Publish Flow Build tools sources

### ISSUE THREAD

**Issue by christophercurrie** [aws/aws-sdk-java#349]
The Flow Build Tools are provided with the AWS SDK for Java, but sources aren't in this repository. Please publish the build tools sources so that enhancements and pull requests can be made against them.

**Comment by mirceal** [comment]
+1

**Comment by ajkerr** [comment]
Please also add the jar file (aws-java-sdk-flow-build-tools-x.y.z.jar) to the Maven Central repository. Currently this jar has to be handled separately from the rest of the SDK.

**Comment by christophercurrie** [comment]
@ajkerr FWIW I filed that separately as #347.

**Comment by vvondra** [comment]
:+1:

**Comment by vvondra** [comment]
+1

**Comment by fzakaria** [comment]
+1

**Comment by srmds** [comment]
+1

**Comment by fzakaria** [comment]
Here is my solution at the moment (it works decently well) in Maven.
This will basically create a local repo in your project. The benefit of doing this vs. installing it to your local m2 repository, is that there's no further setup required for other people who use your project.

Download the Java AWS SDK and copy out the `aws-java-sdk-flow-build-tools` jar and place it in the root of your project.

```bash 
AWS_SDK_VERSION=1.10.60
mkdir -p repo/com/amazonaws/aws-java-sdk-flow-build-tools/$AWS_SDK_VERSION
mv aws-java-sdk-flow-build-tools.jar repo/com/amazonaws/aws-java-sdk-flow-build-tools/$AWS_SDK_VERSION/aws-java-sdk-flow-build-tools-$AWS_SDK_VERSION.jar
cat >  repo/com/amazonaws/aws-java-sdk-flow-build-tools/$AWS_SDK_VERSION/aws-java-sdk-flow-build-tools-$AWS_SDK_VERSION.pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-flow-build-tools</artifactId>
    <version>1.7.3</version>
    <packaging>jar</packaging>

    <properties>
        <freemarker.version>2.3.9</freemarker.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>${freemarker.version}</version>
        </dependency>
    </dependencies>
</project>
```

Add the following to your `pom.xml`

```xml
  <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-flow-build-tools</artifactId>
            <version>${aws.version}</version>
        </dependency>
 </dependencies>
    <repositories>
        <!-- Super annoying that we have to do this, however
             aws-java-sdk-flow-build-tools is not published!
             https://github.com/aws/aws-sdk-java/issues/349 -->
        <repository>
            <id>repo</id>
            <releases>
                <enabled>true</enabled>
                <checksumPolicy>ignore</checksumPolicy>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <url>file://${project.basedir}/repo</url>
        </repository>
    </repositories>
```

**Comment by umcodemonkey** [comment]
In #347, @varunnvs92 announced out that the jar has finally been to Maven. However, the POM declares the SCM location to be https://github.com/aws/aws-swf-build-tools.git, which does not appear to be publicly available, despite the declaration of Apache 2.0 licensing.

**Comment by varunnvs92** [comment]
@umcodemonkey Hey, the sources are submitted for open source approval and will be released soon. This is mentioned in the Readme file in the jar. We didn't want the customers who requested the jar in maven to wait until the approval. Thank you.

**Comment by manikandanrs** [comment]
The sources are now available in https://github.com/aws/aws-swf-build-tools.git repository
