### ISSUE TITLE
[SWF] Flow Build Tools: Support Java 8 sources

### ISSUE THREAD

**Issue by christophercurrie** [aws/aws-sdk-java#350]
`AsynchronyDeciderAnnotationProcessor` is annotated with `@SupportedSourceVersion(SourceVersion.RELEASE_6)`, indicating it only supports code compiled for java 1.6 or earlier. This is awkward to support in Java 7+ projects because of the need for a `bootclasspath` argument pointing to a Java 6 environment.

**Comment by manikandanrs** [comment]
Is this still an issue ? If so, I would recommend opening up an issue in the below repository. This project is currently maintained separately from the AWS Java SDK.

https://github.com/aws/aws-swf-build-tools.git
