### ISSUE TITLE
Maven?

### ISSUE THREAD

**Issue by bmcustodio** [aws/aws-sdk-java#354]
Is there any good reason for the samples under `src/samples` to still be Ant-based? Would you accept a PR "Mavenizing" them?

**Comment by fulghum** [comment]
Hey Bruno, that's a great suggestion.  We'd be happy to look at a PR to switch them over to a Maven build.

**Comment by hanshuo-aws** [comment]
@bmcustodio Let us know when you are ready for a pull-request for this. Will close the issue for now.
