### ISSUE TITLE
SignerOverride is not honored for GetObject requests

### ISSUE THREAD

**Issue by yurykats** [aws/aws-sdk-java#357]
The SDK allows for signer override via ClientConiguration. See a good example in this issue: https://github.com/aws/aws-sdk-java/issues/277#issuecomment-58129144

This mechanism is however no longer honored for GetObject requests, in that AmazonS3Client#createSigner hardcodes V4 signer for all endpoints except for s3.amazonaws.com:

        // For all GetObject requests, we default to SigV4 if the endpoint is a
        // non-standard endpoint. This is because, we know the region name to be
        // used for SigV4 signing.
        final boolean sigv4ForGetRequests = ((originalRequest instanceof GetObjectRequest) && !isStandardEnpoint);

        if (
                !(signer instanceof AWSS3V4Signer) &&
                (upgradeToSigV4() || sigv4ForGetRequests)
           ) {

            AWSS3V4Signer v4Signer = new AWSS3V4Signer();

This is a violation of the ClientConfiguration contract and completely breaks support for all s3-compatible services that do not implement v4. The workaround suggested in https://github.com/aws/aws-sdk-java/issues/277 no longer works.

If SignerOverride has been provided in ClientConfiguration, AmazonS3Client#createSigner should honor it for all requests.

**Comment by hansonchar** [comment]
Hi @yurykats,

Thanks for catching this.  Will have this fixed in the next release.

Regards,
Hanson

**Comment by manikandanrs** [comment]
Fixed as part of 1.9.18 release.
