### ISSUE TITLE
SSLSocketFactory set by user being overriden with default one while connecting to S3

### ISSUE THREAD

**Issue by nikhildhankani** [aws/aws-sdk-java#362]
When creating a S3 client we specify the SSLSocketFactory using config.getApacheHttpClientConfig().setSslSocketFactory(sf). But this sf gets overridden in https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#disableStrictHostnameVerification. 

The changes done in commit https://github.com/aws/aws-sdk-java/commit/c19606a6a5bfcc0e8cc7d33dde5e4f20425ca33e#diff-f91b7dd5b56ee19883f751e608dc43a8 in file aws-java-sdk-core/src/main/java/com/amazonaws/http/HttpClientFactory.java should be done here too(common code would be better).

**Comment by hansonchar** [comment]
Hi @nikhildhankani,

Thanks for the catch.  Will have the change applied in our next release.

**Comment by hansonchar** [comment]
Available now in the latest release:

  http://aws.amazon.com/releasenotes/9983269688843537

**Comment by nikhildhankani** [comment]
Thanks @hansonchar , that was really quick.
