### ISSUE TITLE
AwsSdkMetrics and conflicting mbean names

### ISSUE THREAD

**Issue by soldierkam** [aws/aws-sdk-java#366]
We have 2 applications running on single server. In our case AwsSdkMetrics is trying to register two MBeans using the same name (each one for every application because jars are loaded by separated class loaders). As a result only first application wins. I think that AWS SDK should have option to disable/enable bean registration and customize bean name (for example: append application name to easy distinguish each mbean instance)

**Comment by hansonchar** [comment]
Hi @soldierkam, Interesting, and thanks for reporting this.

**Comment by hansonchar** [comment]
Changes merged into master and will be available in the next release.
