### ISSUE TITLE
S3 TransferManager not calling ProgressListener when adding metadata to an object

### ISSUE THREAD

**Issue by soldiermoth** [aws/aws-sdk-java#371]
I'm using the TransferManager to perform a CopyRequest to add metadata to an s3 object and I'm using a com.amazonaws.event.ProgressListener to monitor when this finishes.

The progress listener isn't called w/ any events. If I explicitly poll the Copy transfer I see that is being completed but no events are being published to the listener

**Comment by hansonchar** [comment]
Hi @soldiermoth,

Apparently the progress listener that is specified in the CopyObjectRequest gets discarded in the case when TransferManager decided to split it into multiple copy part requests when the size exceeded a certain threshold.  Taking a look at how this can be fixed.

**Comment by hansonchar** [comment]
On the other hand, have you tried providing a `TransferStateChangeListener` that you can specify in the `copy` method of `TransferManager`?

```java
    public Copy copy(final CopyObjectRequest copyObjectRequest,
            final TransferStateChangeListener stateChangeListener)
```
This listener is meant to receive event at the TransferManager (ie higher) level, as opposed to the request's progress listener which is meant to receive the per request (ie low level) events.

**Comment by hansonchar** [comment]
The fix will be available in the upcoming release.
