### ISSUE TITLE
s3 object website url

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java#374]
a method to get the website url of an object

```
    public URL getWebsiteUrl(String bucketName, String key) {
```

**Comment by hanshuo-aws** [comment]
@brackxm 
The bucket website URL includes the AWS region where your bucket is located, and such region information might not be available to the client. It should be pretty straightforward  to write some code and construct the URL on your own (with the knowledge of where your bucket's location).
For more information, see the S3 documentation:
http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
