### ISSUE TITLE
s3 BucketLifecycleConfiguration malformed xml

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java#376]
the s3 client generates malformed xml when not setting the status of a lifecycle rule

example
```
        final BucketLifecycleConfiguration.Rule rule = new BucketLifecycleConfiguration.Rule()
                .withId("id")
                .withPrefix("prefix")
                .withExpirationInDays(1);
        final BucketLifecycleConfiguration lifecycleConfiguration = new BucketLifecycleConfiguration()
                .withRules(Collections.singletonList(rule));
        client.setBucketLifecycleConfiguration(getBucket(), lifecycleConfiguration);
```

**Comment by hansonchar** [comment]
The XML looks well formed:

```
<LifecycleConfiguration><Rule><ID>id</ID><Prefix>prefix</Prefix><Status></Status><Expiration><Days>1</Days></Expiration></Rule></LifecycleConfiguration>
```
However, the server side would return an error message:

> The XML you provided was not well-formed or did not validate against our published schema

So it seems the status is a required element.  For more information, see [Lifecycle Configuration Elements](http://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html#intro-lifecycle-rule-id).  Hope this helps.
