### ISSUE TITLE
Is there a spec that describes KMS-Secured envelope process/metadata?

### ISSUE THREAD

**Issue by paxan** [aws/aws-sdk-java#378]
It looks like Java SDK contains the de-facto standard logic for managing envelope metadata when client-side encrypting/decrypting objects (e.g. S3 objects).

This logic is spread over a smattering of classes such as:

 - `com.amazonaws.services.s3.model.KMSEncryptionMaterialsProvider`
 - `com.amazonaws.services.s3.internal.crypto.ContentCryptoMaterial`
 - `com.amazonaws.services.s3.internal.crypto.KMSSecuredCEK`
 - and so on and so forth...

I have no doubt that efforts are ongoing to port this logic to Ruby SDK, Boto &c.
But I wonder, is there a spec or RFC that describes it concisely?

**Comment by hansonchar** [comment]
Hi @paxan,

Such spec or RFC has yet to be written.  Is there a specific aspect/information about the storage format that you are interested in?  Or can you provide more information on why you need such spec/RFC?

**Comment by paxan** [comment]
We have two systems that archive and access some sensitive data to S3. One system is written in Ruby, another one in Python. We'd like to use KMS to make this data safe. But seems like only Java SDK has it fully implemented. We also have systems written in Go and Clojure. So if we want to start using KMS consistently and more widely we need a spec :smile: 

I can just wing it and create my own `x-amz-foo` convention for storing ciphertext of CEK in S3 objects' metadata. But I dislike that idea. Judging by simply looking at the metadata headers, I have a feeling that minds better than me had put a lot of thought into designing this.

I'd feel much better if I had full understanding of what each of the following headers mean, rules for producing their values and so on:

![screen shot 2015-03-11 at 14 07 31](https://cloud.githubusercontent.com/assets/20566/6606895/26f33654-c7f8-11e4-98d9-dc5cfa8f7951.png)

... then the code I write will be interoperable with Java SDK.

**Comment by hansonchar** [comment]
I see.  Sounds like you should have access to my internal wiki page :)  Let me find dig out more info shortly.

**Comment by paxan** [comment]
:+1:

**Comment by hansonchar** [comment]
Hi @paxan, please take a look at the pull request to see if the information of the Appendix helps.

**Comment by paxan** [comment]
Very very helpful, @hansonchar 

Would be nice to have a link or brief desc of `AES/CBC/PKCS5Padding` and other cipher variants that are supported. But even w/o that it's great because I can figure out the cipher stuff just by looking at code.

**Comment by hansonchar** [comment]
Glad to hear.  In the latest pull request, I've added a paragraph and a link in the introduction section:

> For all references to the Cipher Algorithm Names, Modes, and Padding, such as "AES/CBC/PKCS5Padding", please refer to Oracle's [Java™ Cryptography Architecture Standard Algorithm Name Documentation](http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html) for more details.

**Comment by hansonchar** [comment]
Will be available in the next release.

**Comment by hansonchar** [comment]
Available now at:

  http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/package-summary.html

**Comment by paxan** [comment]
:smiley_cat:
