### ISSUE TITLE
Unmarshalling of S3 EventNotification fails if s3 object size is more than 2147483647 bytes

### ISSUE THREAD

**Issue by ishwarpandeya** [aws/aws-sdk-java#382]
The field "size" in com.amazonaws.services.s3.event.S3ObjectEntity (which is inside S3EventNotification.java) is of type Integer and unmarshalling fails for any value larger than Integer.MAX_VALUE. In my opinion, this field ("size") sould be of type Long like one in com.amazonaws.services.s3.model.S3ObjectSummary

**Comment by hanshuo-aws** [comment]
Yep, it's definitely a bug. We will get this fixed in our next release.
Thanks for reporting this.

**Comment by hanshuo-aws** [comment]
Fixed in 1.9.31 version.
