### ISSUE TITLE
Presigned URL in Frankfurt

### ISSUE THREAD

**Issue by mywptechblog** [aws/aws-sdk-java#383]
I am trying to upload on object to S3 in Frankfurt using the sample code (http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObjectDotNetSDK.html), modified adding the property System.setProperty(SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY, "true").

I still get the same error "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256"

**Comment by david-at-aws** [comment]
From the [javadoc](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#ENABLE_S3_SIGV4_SYSTEM_PROPERTY) for that system property:

> Setting this property to anything other than null will cause the client to upgrade to Signature Version 4 whenever it has been configured with an explicit region (which is a required parameter for Signature Version 4). The client will continue to use the older signature protocol when not configured with a region to avoid breaking existing applications.

Have you configured the client you're using to generate the presigned URL for the eu-central-1 region?
