### ISSUE TITLE
New 1.9 packaging results in dependency/NoSuchMethod errors

### ISSUE THREAD

**Issue by stephenh** [aws/aws-sdk-java#384]
Just as an FYI/FWIW, this 1.9 migration has caused several broken dependencies issues for us.

The problem is:

* Existing library A pulls in aws-java-sdk 1.8
* New library B pulls in aws-java-sdk-s3 1.9 + aws-java-sdk-core 1.9
* Application pulls in both library A + library B
* We now have aws-java-sdk.jar (1.8 + old common code) + aws-java-sdk-core.jar 1.9 on the classpath
* The old aws-java-sdk sorts first, so loads first in terms of classpath order, so any aws-java-sdk-s3 code that attempts to call new methods, say setAuthErrorRetryStrategy on ExecutionContext, breaks with:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.http.ExecutionContext.setAuthErrorRetryStrategy(Lcom/amazonaws/retry/internal/AuthErrorRetryStrategy;)V
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3665)
```

We've also seen:

```
    [java] Exception in thread "main" java.lang.NoSuchFieldError: currentToken
     [java] 	at com.amazonaws.services.elasticmapreduce.model.transform.RunJobFlowResultJsonUnmarshaller.unmarshall(RunJobFlowResultJsonUnmarshaller.java:40)
     [java] 	at com.amazonaws.services.elasticmapreduce.model.transform.RunJobFlowResultJsonUnmarshaller.unmarshall(RunJobFlowResultJsonUnmarshaller.java:31)
     [java] 	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:106)
     [java] 	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:42)
```

I have not thought about whether you can really fix this or not. Basically it's already too late.

Note that I'm also anticipating we'll have problems in the future with:

* library A pulls in aws-java-sdk-s3 2.0 + aws-java-sdk-core 2.0
* library B pulls in aws-java-sdk-emr 2.5 + aws-java-sdk-core 2.5
* application pulls in both library A and library B
* we now have aws-java-sdk-s3-2.0 talking to an aws-java-sdk-core 2.5

So, as long as you've made no breaking changes, ever, to aws-java-sdk-core, this will be fine. But, from my experience with other projects that follow this "core + children" pattern, e.g. Apache httpclient v4, eventually a breaking change slips in somewhere, and then things blow up.

**Comment by david-at-aws** [comment]
Hey Stephen,

Sorry to hear that the move to a modularized SDK is causing problems for you. This move was important for [a number of users](https://github.com/aws/aws-sdk-java/issues/224) and will only become more so as the SDK continues to grow, but it does make dependency management trickier. :(

I suspect you've already sorted this out, but for anyone else with the same issue: the short-term fix is to ensure you're picking up consistent versions of the SDK modules. If you're using Maven (and the code in library A wasn't using the `@Deprecated` dynamodb 2011-12-05 client that was dropped 1.9) this should simply be a matter of adding a dependency on aws-java-sdk 1.9.x to the application, where 'x' matches library B's dependency on aws-java-sdk-s3:

```xml
<dependency>
  <groupId>com.example</groupId>
  <artifactId>library-a</artifactId>
</dependency>
<dependency>
  <groupId>com.example</groupId>
  <artifactId>library-b</artifactId>
</dependency>
<dependency>
  <groupId>com.amazonaws</groupId>
  <artifactId>aws-java-sdk</artifactId>
  <version>1.9.x</version>
</dependency>
```

We're looking into ways we can make this easier to reason about in the longer term. At a minimum we need some better documentation about how to resolve version conflicts if and when they pop up. And I'd certainly love suggestions for other ways we can make this brave new modularized world easier to deal with if you or anyone else has them.

**Comment by stephenh** [comment]
Hi David; thanks for the response. I agree per-service jars are great in the long run.

AFAICT this is just a weakness in Maven/Ivy dependency management, of not being able to specific in the metadata that "the latest child needs to pull in the latest parent/common", without saying "the latest parent/common needs to pull in (all) the latest children", which of course defeats the point of splitting up the parent/child.

We've had the same issue with slf4j (slf4j-api/backends), Scala (scala-library, scala-reflect, scala-compiler), and httpclient (httpcore, etc.).

If anything, I filed the issue to provide other users Google-able hints. :-)
