### ISSUE TITLE
Several services not listed in com.amazonaws.regions.ServiceAbbreviations

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#385]
I have not checked for all services, but at least the somewhat new ```ecs```, ```lambda``` and ```kms``` services are not listed in ```com.amazonaws.regions.ServiceAbbreviations```.

Might be a simple oversight, or is there a reason for these omissions?

**Comment by david-at-aws** [comment]
Yikes, looks like we've been forgetting to keep that up to date; we'll do an audit and get it updated for our next release. Thanks for letting us know!

**Comment by manikandanrs** [comment]
This has been fixed in release <a href= "https://aws.amazon.com/releasenotes/6189010795683301" >1.9.26</a>
