### ISSUE TITLE
References to undocumented JRE classes

### ISSUE THREAD

**Issue by sigpwned** [aws/aws-sdk-java#386]
The class `com.amazonaws.util.XpathUtils` in the `aws-java-sdk-core` module refers to several undocumented classes in the JRE:

    import com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl;
    import com.sun.org.apache.xml.internal.dtm.DTMManager;
    import com.sun.org.apache.xml.internal.dtm.ref.DTMManagerDefault;
    import com.sun.org.apache.xpath.internal.XPathContext;

I checked the Java8 javadocs, and these classes are not a documented part of the JRE. I then checked all of the (transitive) dependences that the `aws-java-sdk-core` module has, and confirmed that none of those dependencies provide those classes, either. Since the library works -- wonderfully, by the way! -- one must infer that these classes are being loaded from `rt.jar`. A quick check confirms:

    $ unzip -l rt.jar | grep -iE '(com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl|com.sun.org.apache.xml.internal.dtm.DTMManager|com.sun.org.apache.xml.internal.dtm.ref.DTMManagerDefault|com.sun.org.apache.xpath.internal.XPathContext).class'
         5015  03-04-14 03:13   com/sun/org/apache/xerces/internal/jaxp/DocumentBuilderFactoryImpl.class
         3582  03-04-14 03:13   com/sun/org/apache/xml/internal/dtm/DTMManager.class
        14176  03-04-14 03:13   com/sun/org/apache/xml/internal/dtm/ref/DTMManagerDefault.class
        19048  03-04-14 03:13   com/sun/org/apache/xpath/internal/XPathContext.class

Having referred to undocumented JRE classes in the past and been bitten by an untested code path on upgrade, I know first-hand that this is a risky practice.

Moreover, this creates a dependency from `aws-java-sdk` to `com.sun.*` packages, which wreaks merry hell on OSGi bundles. This dependency forces people to make a bit of a devil's choice between:
* Exporting these proprietary packages -- again, a red flag
* Conscientiously tracking these classes down in other places, which -- at least in my case -- involves traipsing through poorly-documented, 5-year-old maven artifacts, and creates a brittle fix at best

Would it be possible to either:
* Remove references to these classes altogether
* Replace references to these classes with classes imported from a proper maven dependency

Thank you! And please let me know if I can help in any way, particularly with OSGi testing.

**Comment by hansonchar** [comment]
Hi @sigpwned, the dependency on these specific sun classes are "soft" dependency, in the sense that they would only be loaded if available, but would not cause any runtime failure otherwise.  Why do we need to make use of these classes?  The answer can be traced from the inline comments in the [source code](https://github.com/aws/aws-sdk-java/blob/cf21041bc0129512cd30431fc4a960f9e73e6cbc/aws-java-sdk-core/src/main/java/com/amazonaws/util/XpathUtils.java).  Or see [github issue 238](https://github.com/aws/aws-sdk-java/issues/238).  As far as we know, there is currently no better solution/optimization than this. However, if there was one, we'd love to hear about it. Is this solution/optimization currently causing any actual OSGi failure?

**Comment by sigpwned** [comment]
Having reivewed the code more closely now, I see what you mean. I have not tested what happens when I don't import those packages -- I'll do that on our next deploy!

Assuming that works as expected -- and having browsed the code, I expect it will -- it would be nice if this were documented more clearly for OSGi consumers. Is it documented somewhere and I just missed it? We're using `aws-java-sdk-s3` directly, as opposed to the whole `aws-java-sdk` package. I'd be happy to provide that as an example after we've tested excluding that package, if that would be useful!

**Comment by hanshuo-aws** [comment]
@sigpwned Have you got a chance to test it out? We are always curious about how the SDK works (or does not work) within the OSGi framework. So feel free to provide more information about your use case If you find anything that doesn't work as expected. I will keep the issue open for now.

**Comment by seanbright** [comment]
FYI - as of 1.10.35, these imports are now optional which should ease deployment in an OSGi environment.

**Comment by manikandanrs** [comment]
Closing this as we have merged the pull request

https://github.com/aws/aws-sdk-java/pull/558

Feel free to reopen if you see issues in OSGi environment
