### ISSUE TITLE
Built-in retry policies integer overflow with large number of retries

### ISSUE THREAD

**Issue by amrasarfeiniel** [aws/aws-sdk-java#387]
Should be obvious from reading the code.  I'd like to submit a PR but am not sure what the workflow is.  Do I need some kind of permission?

**Comment by david-at-aws** [comment]
We'd be happy to look at a pull request for this. You shouldn't need any special permissions - just fork the repo, clone it locally, make the change, push to your fork, then open a pull request through the GitHub UI. We'll review it and merge it in if everything looks good. Thanks!

**Comment by amrasarfeiniel** [comment]
heh, sorry github newb here.  What is "my fork"?  I'm used to the feature branch model.

**Comment by amrasarfeiniel** [comment]
ok i think i figured it out.  https://github.com/aws/aws-sdk-java/pull/388

**Comment by hanshuo-aws** [comment]
@amrasarfeiniel We have merged in your fix. Thanks for the contribution!
