### ISSUE TITLE
Document on providing AWS credentials may be incorrect

### ISSUE THREAD

**Issue by adamv** [aws/aws-sdk-java#390]
From: http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html

```
When you create an AWS credentials file using the aws configure command, it creates a file with the following format...
```

If I run `aws configure` with aws-cli 1.7.12 I get two files.

My `config` file is:
```
[default]
region = us-east-1
```

My `credentials` file is:
```
[default]
region = us-east-1
aws_access_key_id = (key)
aws_secret_access_key = (key)
```

Trying to load credentials using the default providers from aws-sdk 1.9.25 then fails.
It will succeed if I copy the keys from `credentials` to `config`.

Either the credential loader should be updated to work with the configuration generated by `aws configure`, or the documentation should be updated to be clear that only reading from `config` works by default.

**Comment by adamv** [comment]
(Further, if I delete `config` entirely, which is referenced in code as a "legacy location", the default credentials provider also fails.)

**Comment by adamv** [comment]
In addition, the aws-cli configuration lets you set a default region: http://docs.aws.amazon.com/cli/latest/reference/configure/index.html

The Java SDK then outputs this:
```
INFO: Unsupported configuration setting: region = us-east-1
```

I would expect either that this setting be silently ignored by the Java SDK, or the documentation for the Java SDK updated to mention this.

**Comment by fulghum** [comment]
Hey Adam, thanks for taking the time to report these problems.  We'll investigate the problems loading credentials from the config and credentials file and get you an answer.

We chose to be explicit about ignoring the us-east-1 region setting to make sure developers were aware that we weren't using it, instead of silently ignoring it and having people assume it was being honored.  We'll make sure we get the documentation updated to be clear about that behavior.

Would you want the region param to be honored?  We chose not to use it because we thought it would make region selection more difficult in the SDK since there are several ways to do set regions.

**Comment by david-at-aws** [comment]
Hey Adam, I'm not able to reproduce this with SDK version 1.9.25. Is there any chance you're picking up an older version of the SDK that only looks in `config` and not `credentials`?

**Comment by adamv** [comment]
I don't think I'm picking up an older version; my minimal project is here: https://github.com/adamv/aws-creds

The output I get with a credentials file but without a config file is:
```
$ java -jar target/aws-creds-1.0-SNAPSHOT.jar 
Exception in thread "main" java.lang.IllegalArgumentException: AWS profiles config file not found in the given path: /home/adamv/.aws/config
	at com.amazonaws.auth.profile.internal.ProfilesConfigFileParser.loadProfiles(ProfilesConfigFileParser.java:55)
	at com.amazonaws.auth.profile.ProfilesConfigFile.loadProfiles(ProfilesConfigFile.java:129)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:97)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:77)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.<init>(ProfileCredentialsProvider.java:45)
	at adamv.Credentials.configureS3(Credentials.java:17)
	at adamv.Credentials.main(Credentials.java:13)
```

**Comment by david-at-aws** [comment]
I cloned your repo and it seems like it's working for me:

```
$ ls ~/.aws
credentials
$ cat ~/.aws/credentials 
[default]
aws_access_key_id = not_my_access_key
aws_secret_access_key = not_my_secret_access_key
$ java -jar target/aws-creds-1.0-SNAPSHOT.jar
$ // No output
```

[Line 45 of ProfileCredentialsProvider](https://github.com/aws/aws-sdk-java/blob/1.9.25/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/ProfileCredentialsProvider.java#L45) as of 1.9.25 doesn't seem to match your stack trace either. :/

Very strange. Maybe something funky in your local maven repository? Can you try again after a `mvn dependency:purge-local-repository`?

**Comment by adamv** [comment]
David, thanks for the pointer. I see the stack trace mismatch now that you point it out. There may be other system level configuration on this workstation that is interfering with my classpath. I'll investigate and report back.

**Comment by adamv** [comment]
I finally thought to print out `VersionInfoUtils.getVersion()`; on one of my workstations this is reporting a much older SDK, which is almost certainly the source of the problem here. On an alternate workstation the SDK version reports correctly.

I'll close this ticket; thank you for your time.
