### ISSUE TITLE
Seeking for help regarding cloud search server

### ISSUE THREAD

**Issue by aswinich** [aws/aws-sdk-java#393]
Hello,

Can you please help me in settting up the aws cloud search in e-commerce site using JAVA.

Thanks,
Regards,
Aswini.

**Comment by fulghum** [comment]
Hey Aswini, this issue queue is for issues related to using the AWS SDK for Java.  If you're looking for help using Amazon CloudSearch, here are a few resources for you...

The Amazon CloudSearch Forum is a great place to post questions about using Amazon CloudSearch:
https://forums.aws.amazon.com/forum.jspa?forumID=137

The Amazon CloudSearch Developer Guide has some great walk throughs and explanations of how to setup and use CloudSearch:
http://docs.aws.amazon.com/cloudsearch/latest/developerguide/getting-started.html

Hope that helps!
