### ISSUE TITLE
TransferManager - Parallel Part Uploads for streams

### ISSUE THREAD

**Issue by joech4n** [aws/aws-sdk-java#394]
Today, it appears TransferManager will perform the UploadPart API calls in a serial fashion. Can this be changed to make the UploadPart API calls in parallel?

**Comment by hanshuo-aws** [comment]
Hi @joech4n

InputStream inherently doesn't support random access, therefore it's impossible to read and upload different parts of the stream in parallel.
TransferManager does support parallel upload if you supply a file as input, and the strategy for chunking the file can be configured using [TransferManagerConfiguration](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManagerConfiguration.html)

If you need to upload a large stream data, you should consider stashing the content to the file system first and then multipart-upload the file using TransferManager -- it's probably more performant than doing the whole upload in serial.
