### ISSUE TITLE
DynamoDBMapper marshaller tries to convert values from static getter methods

### ISSUE THREAD

**Issue by tuscland** [aws/aws-sdk-java#396]
Hello,

I have defined a static getter "getAll()" method on a model class mapped to DynamoDB using the DynamoDBMapper (version 1.9.27 of the AWS SDK for Java).

I have this problem where I can't save an object because the marshaller tries to save the result of my static getter to the database.  May this be considered as a bug or a feature?

Thank you for your help!
Camille

**Comment by hansonchar** [comment]
Hi @tuscland, 

This sounds like a bug to me.  As a work around, have you tried annotating the static method with @DynamoDBIgnore ?

**Comment by tuscland** [comment]
Hello @hansonchar,
Yes `@DynamoDBIgnore` does the trick.

**Comment by hansonchar** [comment]
Will include the fix in the next release.

**Comment by hansonchar** [comment]
Actually we cannot put in the fix (of excluding static getter methods) without breaking backward compatibility.  I think I'll opt to keep it simple and leverage on @DynamoDBIgnore for now.

**Comment by tuscland** [comment]
No problem, and thank you for your promptness.
