### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by nykolaslima** [aws/aws-sdk-java#399]
I'm getting this error intermittently when trying to access S3.

I didn't got this error before but I got a lot of this those days. Is this a "normal situation"?

**Comment by fulghum** [comment]
Hey Nykolas, that doesn't sound like a normal situation.  This doesn't sound like an SDK specific issue, so I'd head over to the Amazon S3 forum and see if you can find any answers there:
https://forums.aws.amazon.com/forum.jspa?forumID=24
