### ISSUE TITLE
Expose instance request time, not just launch time

### ISSUE THREAD

**Issue by llarsson** [aws/aws-sdk-java#401]
Spot requests support obtaining when the request was made. So, if it takes too long to get an instance associated to it, we can cancel the request. This is great, and just as I expect it to be.

Instance requests, however, can only expose when the instance(s) was launched, **not** when they were initially requested. In practice, instances are often launched almost immediately after the request has been made, but that is not a guarantee. I have actual use cases when I would like to be able to determine that a given provisioning operation takes too long, e.g., while starting a large number of on-demand instances, and I can provision the instances from another availability zone, region, or even cloud provider. Keeping records of these operations myself is insufficient, since an instance can be started in many ways that I do not control (Auto Scaling, web console, ...).

A [Reservation](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Reservation.html) is made when we make a [RunInstances](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html) request (which is associated to a number of instances, if one makes a single RunInstances that requests several instances). Whether we keep that Reservation around, or query for it using a [DescribeInstances](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) call, it is at least available to us.

If Reservation would just include a timestamp that states when it was created, the API would offer a bit more information that might be relevant to some (I don't know if OpenStack is a curse word around these parts, but "creation time" and "launch time" exist there as separate concepts -- someone must have figured they need it), not to mention support my use cases. :)

Bonus question: what is returned by DescribeInstances if invoked after RunInstances, where the Reservation has been created (i.e. we are not being subjected to eventual consistency) but before any instance has been started? Ideally, I would like it to return a listing that includes the reservation I got as a return value from RunInstances, of course. Is that the case?

**Comment by manikandanrs** [comment]
This is a feature request to EC2 service. I will pass this on the EC2 service team. I would also suggest raising this in the EC2 forum

https://forums.aws.amazon.com/forum.jspa?forumID=30&start=0
