### ISSUE TITLE
New Amazon ECS region availabilities not reflected in regions.xml

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#403]
The 1.9.30 update added support for the new ECS Service related actions, but did not update [```aws-java-sdk-core/src/main/resources/com/amazonaws/regions/regions.xml```](https://github.com/aws/aws-sdk-java/blob/1.9.30/aws-java-sdk-core/src/main/resources/com/amazonaws/regions/regions.xml) regarding the new regions added with the GA announcement, i.e. still listing only US East (N. Virginia) and not US West (Oregon), EU (Ireland), and Asia Pacific (Tokyo).

**Comment by manikandanrs** [comment]
Thanks for the find @hopel. We have fixed this. This should be available in our next release.

**Comment by manikandanrs** [comment]
New regions are available in 1.9.31
