### ISSUE TITLE
com.amazonaws.services.s3.model.Region.fromValue should accept us-east-1

### ISSUE THREAD

**Issue by eswenson1** [aws/aws-sdk-java#405]
If you call Region.fromValue("us-east-1") you get an IllegalArgumentException "Cannot create enum from us-east-1 value!".  This causes the AWScala (AWS SDK for Scala, https://github.com/seratch/AWScala) to fail when you specify Region.US_EAST_1 for an S3 region from that library.

**Comment by manikandanrs** [comment]
S3 doesn't have a us-east-1 region. It just has a region US Standard which places the data in either that east coast/west coast data centers. 

S3's Standard endpoint ("s3.amazonaws.com") routes the requests to either the east/west coast data centers which is closest to you. SigV4 requires you to mention the region while signing the request and for the S3's standard endpoint the value to be used is "us-east-1". 

So, when you create an S3 client with Region as Region.US_EAST_1, the endpoint is  set as  "s3.amazonaws.com" and the region to be used for signing is "us-east-1". 

Hence you don't see a enum for us-east-1 in the <a href="http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/Region.html">Region</a> class.

**Comment by eswenson1** [comment]
Thanks for the explanation. I've submitted a PR for the AWS SDK for Scala to include a workaround that maps the "us-east-1" region to "US" for the purposes of configuring S3. However, it does seem a bit asymmetric that the AWS S3 SDK for Java defines a us-west-1 region and not a us-east-1 region, if, in fact, the "US Standard" region maps to both of these US regions. Also, while you are able to list the bucket name using the us-west-1 region, even if the buckets were created in us-east-1 region, you are not able to to list the bucket keys and attributes using the us-west-1 region. If there is really just one US Standard region, why the asymmetry?

**Comment by manikandanrs** [comment]
S3's regions are different from AWS regions. S3 has a us-west-1 endpoint (s3.us-west-1.amazonaws.com) which is different from the west coast data center that I mentioned in the previous comment. 

S3's US Standard is either "s3.amazonaws.com" or "s3-external-1.amazonaws.com" and in both these cases the signing region is "us-east-1". Its just the "s3.amazonaws.com" has a special capability of placing your data close to you. <a href="http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region">Here</a> is the list of regions supported by S3.

**Comment by david-at-aws** [comment]
Also relevant is that S3's bucket namespace is global. *Any* S3 endpoint will respond to you with a list of all of your buckets, regardless of which region they're in. Listing the contents of a bucket, however, requires using a correct endpoint (either `s3-{region}.amazonaws.com` or `{bucket}.s3.amazonaws.com` once DNS updates to point to the correct region).

**Comment by eswenson1** [comment]
Thanks much for all the explanations. I guess it makes sense to me.

The real issue is that I want to use the AWS SDK for Scala, and this SDK
sets the default region for S3 requests to be us-west-1. Since all my
content is actually stored in Northern Virginia, all requests to retrieve
keys or attributes fail. Doing the "obvious", which is configuring the AWS
SDK for Scala's S3 object to use the "right" region is not possible. This
SDK defines the regions in the same way that the AWS Core SDK for Java
does, including "us-east-1" as a name of a region. When you try to
configure the S3 object to use a region other than "us-west-1", it tries to
invoke the com.amazonaws.services.s3.model.Region.fromValue method on the
name of a AWS SDK for Scala Region object. Since there is no "US" or "US
Standard" core (global) region, this method fails. Of course, it works for
the other regions. There are no values you can provide to that SDK to get
it to work.
