### ISSUE TITLE
SDK ver 1.9.30 SQS

### ISSUE THREAD

**Issue by ambientmemory** [aws/aws-sdk-java#407]
List<Message> msgs = sqs.receiveMessage(receiveMessageRequest).getMessages();
is returning an empty list... 

problem started after upgrading SDK to 1.9.30 did not use it on 1.9.29 but was working perfectly on 1.9.28.1

The command is a part of doPost handler of a worker, invoked every time a message is received.

**Comment by manikandanrs** [comment]
Both <a href="https://aws.amazon.com/releasenotes/Java/0358434906243843">1.9.29</a> and <a href="https://aws.amazon.com/releasenotes/Java/1139575884634364">1.9.30</a> doesn't have any updates to SQS client. 

Could you give more context on the issue that you are facing? Can you share any standalone test code that can simulate the issue ?

**Comment by ambientmemory** [comment]
Dear Sir,

Thanks you for your email. I am a student in Columbia University and
after exhausting all other options
felt like asking you for help.

I am writing a worker environment servlet we b server that works in
the backend, and send a HTTP Post request
to another web server (also written by me and called
"debug-senti-server"). The code is attached.
After a smooth start, I keep getting the following in the log :
-------------------------------------
/var/log/httpd/elasticbeanstalk-error_log
-------------------------------------
[Mon Apr 20 10:26:37 2015] [error] (111)Connection refused: proxy:
HTTP: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Mon Apr 20 10:26:37 2015] [error] ap_proxy_connect_backend disabling
worker for (localhost)
[Mon Apr 20 10:26:37 2015] [error] (111)Connection refused: proxy:
HTTP: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Mon Apr 20 10:26:37 2015] [error] ap_proxy_connect_backend disabling
worker for (localhost)
[Mon Apr 20 10:26:37 2015] [error] (111)Connection refused: proxy:
HTTP: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Mon Apr 20 10:26:37 2015] [error] ap_proxy_connect_backend disabling
worker for (localhost)

and the program stops working. I have given an inbound access to HTTP,
all TCP, and HTTPS permissions to this worker.

The code I have used is also attached below.

Please help.
Thanks in advance,
Piyali



On Tue, Apr 14, 2015 at 3:36 PM, Manikandan Subramanian <
notifications@github.com> wrote:

> Both 1.9.29 <https://aws.amazon.com/releasenotes/Java/0358434906243843>
> and 1.9.30 <https://aws.amazon.com/releasenotes/Java/1139575884634364>
> doesn't have any updates to SQS client.
>
> Could you give more context on the issue that you are facing? Can you
> share any standalone test code that can simulate the issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-java/issues/407#issuecomment-93032853>.
>

package senti_worker;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.sns.AmazonSNSClient;
import com.amazonaws.services.sns.model.AuthorizationErrorException;
import com.amazonaws.services.sns.model.EndpointDisabledException;
import com.amazonaws.services.sns.model.InternalErrorException;
import com.amazonaws.services.sns.model.NotFoundException;
import com.amazonaws.services.sns.model.PlatformApplicationDisabledException;
import com.amazonaws.services.sns.model.PublishRequest;
import com.amazonaws.services.sns.model.PublishResult;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClient;
import com.amazonaws.services.sqs.model.DeleteMessageRequest;
import com.amazonaws.services.sqs.model.InvalidMessageContentsException;
import com.amazonaws.services.sqs.model.Message;
import com.amazonaws.services.sqs.model.ReceiveMessageRequest;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.TimerTask;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.http.Consts;
import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.message.BasicNameValuePair;

/**
 *
 * @author Piyali Mukherjee pm2678@columbia.edu This program is written as a Java servlet. It works in conjunction with the senti_analyzer web hosted program.
 * This program is run as a Worker environment in AWS EBS. It starts by establishing due credentials, and read the tweet_server queue asynchronously. On
 * receiving a tweet, it reaches out to a third party sentiment analyzer by raising an internal http request, and waits for the response. On receiving the
 * response, the program does a SNS to the senti_analyzer program, and updates the sentiment value.
 *
 */
public class senti_web_worker extends HttpServlet {
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		LocalTime now = LocalTime.now(ZoneId.of("America/New_York"));
		String msg_id = null;
		String msg_body = null;
		ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(tweet_queue_url);
		List<Message> msgs = sqs.receiveMessage(receiveMessageRequest).getMessages();
		int debug_int;
		if (msgs.isEmpty()) {	//Problematic situation
			return;
		} else {
			debug_int = 1;
			Message a_msg = msgs.get(0);
			String[] body_parts = a_msg.getBody().split("\n");
			msg_id = body_parts[0];
			msg_body = body_parts[1];
			for (msg_rec a_msg_rec : store) {
				if (a_msg_rec.msg_id.equals(msg_id)) {
					sqs.sendMessage(new SendMessageRequest(debug_queue_url, "Duplicate msg : \n" + msg_id + " : msg already present in queue \n" + msg_body));
					System.err.println("ERROR : Duplicate Message received with msg id : "+msg_id);
					return;
				}
			}
			String messageRecieptHandle = a_msg.getReceiptHandle();
			sqs.deleteMessage(new DeleteMessageRequest(tweet_queue_url, messageRecieptHandle));
			sqs.sendMessage(new SendMessageRequest(debug_queue_url, "Debug_int : 1 for msg : \n" + msg_id + " : msg properly deleted\n" + msg_body));
		}
		msg_rec new_msg = new msg_rec(msg_id, now);
		store.add(new_msg);
		//Next we form the necessary header to send the message to sentiment analysis external url
		String url = "http://debug-senti-server.elasticbeanstalk.com/debug_senti_server";
		CloseableHttpClient client = HttpClients.createDefault();
		HttpPost post = new HttpPost(url);
		post.setHeader("User-agent", "Mozilla/5.0");
		List<NameValuePair> params = new ArrayList<>();
		params.add(new BasicNameValuePair("apikey", "6e3a504462d2a0f80dc4cfabe1e4e77b2e41931a"));
		params.add(new BasicNameValuePair("outputMode", "xml"));
		params.add(new BasicNameValuePair("showSourceText", "1"));
		params.add(new BasicNameValuePair("text", msg_body));
		post.setEntity(new UrlEncodedFormEntity(params, Consts.UTF_8));
		CloseableHttpResponse reply = null;
		StringBuilder senti_result = new StringBuilder();
		try {
			reply = client.execute(post);
			int ret_status = reply.getStatusLine().getStatusCode();
			HttpEntity reply_entity = reply.getEntity();
			InputStream in_stream = null;
			if (reply_entity != null) {
				try {
					in_stream = reply_entity.getContent();
					InputStreamReader in_stream_reader = new InputStreamReader(in_stream);
					BufferedReader reader = new BufferedReader(in_stream_reader);
					String a_line = "";
					while ((a_line = reader.readLine()) != null) {
						senti_result.append(a_line);
					}
				} finally {
					in_stream.close();
				}
			}
		} finally {
			reply.close();
		}

		//Now we do the ral processing of the web returned value
		String extract_sentiment = "";
		int loc_of_status = senti_result.indexOf("<status>");
		String actual_status = senti_result.substring(loc_of_status + 8, loc_of_status + 10);
		//sqs.sendMessage(new SendMessageRequest(debug_queue_url, "Got preliminary data :  \n" + actual_status));
		if (actual_status.equalsIgnoreCase("OK")) {
			int loc_of_score = senti_result.indexOf("<score>");
			extract_sentiment = senti_result.substring(loc_of_score + 7, senti_result.indexOf("</score>"));
			String count = senti_result.substring(senti_result.indexOf("<count>") + 7, senti_result.indexOf("</count>"));
			try {
				sqs.sendMessage(new SendMessageRequest(debug_queue_url, "Got a OK :\n" + msg_id + " " + count + " " + now.toString() + "\n" + extract_sentiment));
			} catch (InvalidMessageContentsException inv) {
				System.err.println("Error writing to debug_queue_url : Invalid Message Contents in msg_id " + msg_id + " actual error : " + inv.getErrorMessage());
				return;
			} catch (AmazonServiceException ase) {
				System.err.println("Error writing to debug_queue_url :Amazon Service Exception with msg_id " + msg_id + " actual error : " + ase.getErrorMessage());
				return;
			} catch (AmazonClientException ace) {
				System.err.println("Error writing to debug_queue_url :Amazon Client Exception with msg_id " + msg_id + " actual error : " + ace.getMessage());
				return;
			}
			PublishRequest pub = new PublishRequest(topic_arn, "Got a OK :\n" + msg_id + " " + count + " " + now.toString() + "\n" + extract_sentiment);
			try {
			PublishResult pub_result = sns.publish(pub);
			}  catch (NotFoundException nfe) {
				System.err.println("Error publishing : Not Found Exception with msg_id " + msg_id + " actual error : " + nfe.getMessage());
				return;
			} catch (PlatformApplicationDisabledException pad) {
				System.err.println("Error publishing : Platform Application Disabled with msg id : " + msg_id + " actual error : " + pad.getMessage());
				return;				
			} catch (EndpointDisabledException ede) {
				System.err.println("Error publishing : Endpoint Disabled Exception with msg id : " + msg_id + " actual error : " + ede.getMessage());
				return;								
			} catch (AuthorizationErrorException auer) {
				System.err.println("Error publishing : Authorization Error Exception with msg id : " + msg_id + " actual error : " + auer.getMessage());
				return;								
			} catch (InternalErrorException inter) {
				System.err.println("Error publishing : Internal Error Exception with msg id : " + msg_id + " actual error : " + inter.getMessage());
				return;												
			}  catch (AmazonServiceException ase) {
				System.err.println("Error publishing : Amazon Service Exception with msg_id " + msg_id + " actual error : " + ase.getErrorMessage());
				return;
			} catch (AmazonClientException ace) {
				System.err.println("Error publishing : Amazon Client Exception with msg_id " + msg_id + " actual error : " + ace.getMessage());
				return;
			}
			System.err.println("Got a OK :\n" + msg_id + " " + count + " " + now.toString() + "\n" + extract_sentiment);
		} else {
			int loc_of_err_info = senti_result.indexOf("<statusInfo>");
			if (loc_of_err_info > 0) {
				String error_status = senti_result.substring(loc_of_err_info + 12, senti_result.indexOf("</statusInfo>"));
				sqs.sendMessage(new SendMessageRequest(debug_queue_url, "Got an ERROR :\n" + msg_id + "\n" + error_status));
				//System.out.println("Got an ERROR :\n" + error_status);
			}
		}
	} //end of doPost
}

	private class msg_rec {

		LocalTime msg_time;
		String msg_id;

		msg_rec(String id, LocalTime time) {
			msg_time = time;
			msg_id = id;
		}
	}

} //end of class

**Comment by neil-rubens** [comment]
The reason for this could be due to the following `default` behavior of `receiveMessage`:

> Short poll is the default behavior where a weighted random set of machines is sampled on a ReceiveMessage call. This means only the messages on the sampled machines are returned. If the number of messages in the queue is small (less than 1000), it is likely you will get fewer messages than you requested per ReceiveMessage call. If the number of messages in the queue is extremely small, you might not receive any messages in a particular ReceiveMessage response; in which case you should repeat the request.

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClient.html

**Comment by zhangzhx** [comment]
Are you still facing this problem? Otherwise, I will close this issue.
