### ISSUE TITLE
userData limitation to 21847 length

### ISSUE THREAD

**Issue by gbougeard** [aws/aws-sdk-java#408]
Hi,

I'd like to know why this limitation is and if it is possible to get rid of it.

We have big `userData` blocks because we define configuration files in it but maybe you have best practices discouraging this?

**Comment by manikandanrs** [comment]
Hi @gbougeard 

Can you provide some context on the API that you are referring here ?

**Comment by gbougeard** [comment]
I realized that maybe it is related to aws-cli but as it's also specified in aws-sdk javadoc...

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/autoscaling/model/LaunchConfiguration.html

**Comment by david-at-aws** [comment]
This is a restriction imposed by EC2, which [limits](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) user data to 16 KB (or 21847 bytes when base64 encoded). If you need more configuration data than that, maybe store it on S3, pass a URL in user data, and have your instances download it from there on startup?

**Comment by gbougeard** [comment]
Does it mean when you do a  ```aws  create-launch-configuration --user-data file://cloud-config.yaml```  the size of my local ```cloud-config.yaml``` is limited but if I use ```--user-data url://s3/cloud-config.yaml ``` the ```cloud-config.yaml``` on s3 is not size limited?
