### ISSUE TITLE
AmazonSQSAsyncClient does not have constructor taking a RequestMetricCollector

### ISSUE THREAD

**Issue by robertclancy** [aws/aws-sdk-java#409]
AmazonSQSAsyncClient does expose the constructors of its superclass that [take a RequestMetricCollector](https://github.com/aws/aws-sdk-java/blob/0adb8ab9a4e73350622ff4938820b8dd2c26dc07/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/AmazonSQSClient.java#L245). This means any metric collection must be configured at the global level with [AwsSdkMetrics::setMetricCollector](https://github.com/aws/aws-sdk-java/blob/0adb8ab9a4e73350622ff4938820b8dd2c26dc07/aws-java-sdk-core/src/main/java/com/amazonaws/metrics/AwsSdkMetrics.java#L455).

Is this due to concerns about the thread safety of implementations of RequestMetricCollector?

**Comment by muellerc** [comment]
https://github.com/aws/aws-sdk-java/pull/957 should resolve the feature request.

**Comment by shorea** [comment]
Client builders support this. Closing this issue. 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/AmazonSQSAsyncClientBuilder.java
