### ISSUE TITLE
Update Jackson dependency versions

### ISSUE THREAD

**Issue by iwhitfield** [aws/aws-sdk-java#411]
The version in the pom.xml is currently `2.3.2`. This is about a year old now (Feb 2014), and there are certain Jackson modules which are clashing when in use alongside the aws-sdk.

A major example of this is the JDK 8 module for Jackson, which was developed against version 2.4.x of Jackson initially, and as such it's not really safe to use it against 2.3.x. Other modules, such as the Joda module, are also clashing because of this old dependency.

In my use case, a service running on ec2 is using this SDK for the ec2 utilities, and is loading Jackson `2.3.2`. Then when my code executes something based on a newer Jackson version (2.4.5), it cannot find the reference as the version bundled in this dependency is taking priority. 

Is it possible we can maybe get the latest Jackson version into this SDK? Right now the latest is `2.5.2`.

**Comment by jgangemi** [comment]
have you tried just defining jackson as a top level dependency in your pom above the aws toolkit so it takes precedence (you could also just add an excluded entry).

**Comment by iwhitfield** [comment]
@jgangemi yeah, that would be my first choice - unfortunately we're getting it transitively via another library using the AWS SDK. Our code is running on their app layer which has already loaded the SDK by the time our lib is loaded, so Maven can't help us.

**Comment by jgangemi** [comment]
ah - yeah - that's annoying. i have a similar situation at the day job dealing w/ apache spark where i'm being forced into certain dependency versions. hopefully you'll get some traction on this.

**Comment by iwhitfield** [comment]
@jgangemi hopefully it shouldn't be too much of an issue to update the dependency; I believe Jackson is backwards compatible most of the time.

**Comment by david-at-aws** [comment]
Upgrading to a new version of a dependency is not a backwards-compatible change. As long as the dependency stays backwards-compatible (as Jackson tends to), anyone deploying the SDK in an environment that provides a version of the dependency that's *at least* as new as what the SDK is built against is fine. Very few libraries are strictly *forwards* compatible though, so building against a newer version of the dependency will likely break anyone still deploying an older version of the dependency (as you've found, more or less :)).

We'll take a look at whether it makes sense to require a newer version of Jackson when we bump to 1.10.x and have a bit more freedom to make backwards-incompatible changes like this. In the meantime, if you want a newer version of Jackson but can't control which version is getting pulled in by your application container, one reasonable option is to use the [shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/) (or something similar) to in-line a newer version of Jackson in your application and relocate it (and your references to it) to a different Java package where it won't conflict with the older version pulled in by the container.

**Comment by iwhitfield** [comment]
@david-at-aws I'm not sure I understand... Shouldn't a backwards compatible library mean you can bump the version of it safely, without breaking code based on older versions? Essentially having 2.3.2 inside this SDK is tying people (safely) to <= 2.3.2, unless I'm mistaken?

If I have Jackson code working on 2.3.x and I upgrade the Jackson version to 2.5.x, the existing code should function correctly (in most cases). The issue I'm facing is that I need to flip my code to match the *lowest* version of Jackson in play, which is the version in this SDK. If I use a new method from 2.5.x, and this SDK is loaded first (which is beyond my control), then my 2.5.x method is unusable... right?

Sorry if I'm misunderstanding - I appreciate your response, and the consideration of bumping the version. I just want to make sure I explained my issue correctly.

**Comment by david-at-aws** [comment]
We're in essentially the same position as you are - if we build against 2.5.x but get deployed in an application that's pulling in 2.3.x at runtime (which works today), we'll have problems.

In most cases it's the end-user who controls which versions of our dependencies get deployed, so we want to compile against the oldest version of those dependencies we can. Our dependency is a *lower* bound: users can safely deploy a *newer* version of Jackson if they want, but not an older one.

The problem for you is that your container is forcing its version of *both* Jackson and the SDK on you. Ideally, it'd be running you in a separate classloader so you could safely pull in whatever version of Jackson and the SDK you wanted.

If you controlled the container, you could fix this in the short term by having the container pull in a newer version of Jackson along side its current version of the SDK; *its* dependencies are effectively upper bounds for you. If we were to "fix" this in the SDK by compiling against a newer version of Jackson, you'd need to get the container to deploy the new version of the SDK AND the new version of Jackson.

Does that make sense?

**Comment by iwhitfield** [comment]
@david-at-aws oh, duh. I never even considered that. 

I gotcha, I never even thought about this SDK being affected by the same problem. Makes sense, thank you for taking the time to clarify :)

**Comment by qrtt1** [comment]
Maybe we need another aws-sdk using the jackson before the version 2.5 for working with the spark core library.

Spark using jackson 2.3.x, but it compliants with jackson 2.4.x. 

https://issues.apache.org/jira/browse/SPARK-3955


Now I use new aws sdk and spark with the work around:

```groovy
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'eclipse'

repositories {
    mavenCentral()
}


dependencies {
    compile ('com.amazonaws:aws-java-sdk-s3:1.+') {
        exclude group: 'com.fasterxml.jackson.core', module:'jackson-databind'
    }
    compile 'org.apache.spark:spark-core_2.10:1.5.0'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.4'
}
```
