### ISSUE TITLE
Read me is in wrong format

### ISSUE THREAD

**Issue by medyagh** [aws/aws-sdk-java#413]
The ReadMe on this github is on a wrong format, you can't view it correctly on github on a browser.
https://github.com/aws/aws-sdk-java/tree/master/src/samples/AmazonSimpleQueueService

**Comment by manikandanrs** [comment]
@medyagh Thanks for finding this. We will get this fixed.

**Comment by manikandanrs** [comment]
This is fixed as part of the pull request <a href="https://github.com/aws/aws-sdk-java/pull/428">428</a>
