### ISSUE TITLE
AmazonS3.setEndpoint() throws a null pointer exception when endpoint contains '_'

### ISSUE THREAD

**Issue by mikegfink** [aws/aws-sdk-java#414]
AmazonS3 conn = new AmazonS3Client();
String endpoint = s3_us-west-1.amazonaws.com;
conn.setEndpoint(endpoint);

This code throws a null pointer exception with AWS SDK 1.9.30.

**Comment by david-at-aws** [comment]
Yep, we should definitely be kicking back a better exception if you pass an invalid endpoint. The URI class is parsing this as a relative URI with no host component, and we're just assuming URI.getHost() will be non-null.

**Comment by manikandanrs** [comment]
Thanks for reporting this. This is fixed in the latest release.
