### ISSUE TITLE
Cant get MD5 checksum for a multipart upload using Transfer manager

### ISSUE THREAD

**Issue by yagyesha** [aws/aws-sdk-java#416]
I have configured TransferManager as below:

```java
TransferManager tx = new TransferManager(s3, thPool, true);

TransferManagerConfiguration txConf = new TransferManagerConfiguration();
txConf.setMinimumUploadPartSize(6*1024*1024); //6MB
txConf.setMultipartUploadThreshold(10*1024*1024);  //10MB

tx.setConfiguration(txConf);
```

Request object & its metadata is set as below:

```java

ObjectMetadata metaData = new ObjectMetadata();
metaData.setContentMD5(streamMD5);

PutObjectRequest request = new PutObjectRequest(
						bucketName, fileToUpload.getName(), fileToUpload)
				.withMetadata(metaData)
				.withGeneralProgressListener(progressListener);
```

And finally, i start uploading using

```java

Upload upload = tx.upload(request);
```

After upload is completed when i try to get the result and print MD5, it returns null. I only get proper value for ETag (i.e. f45566596bfdfc89264b4bd09a99c4bb-9). But i cannot use it since it is not MD5 checksum.
```java

UploadResult result = upload.waitForUploadResult();
System.out.println(result.getETag());			
S3Object uploadObject = s3.getObject(bucketName, fileToUpload.getName());
ObjectMetadata objectMetaData = uploadObject.getObjectMetadata();
System.out.println(objectMetaData.getETag());
System.out.println(objectMetaData.getContentMD5());
```

Ability to verify the integrity of the uploaded objects is critical for my project as the objects are in GB's & will be downloaded by end customers. 

I'm using aws-java-sdk-s3-1.9.0.
Edit: Also tried with v1.9.6 and the issue is same.

Please let me know if i'm doing anything wrong here or is this an issue with SDK.

**Comment by manikandanrs** [comment]
@yagyesha 

As per the API documentation for <a href="http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html">upload part</a>, Content-MD5 header is in the request and not response. So, this would be null in the response.

This header is used by S3 for the integrity of the upload. For putObject requests, Java SDK computes the MD5 of object being uploaded if not explicitly specified by the user and sets this header. For upload part requests, the SDK is not setting this header if the user is not explicitly setting it in the metadata (cases like TransferManager are affected by this). 

We will fix this issue in the SDK. We would love to accept a pull request if you wish to submit.

**Comment by yagyesha** [comment]
Thanks for the reply.

I understand that content md5 is part of the request and that is how i'm setting it in ObjectMetadata. As per the documentation, after the upload is done, AWS will compute the md5 of the uploaded object and if the computed md5 doesnt match the md5 passed as metadata, it will report an error. This is not happening for me in case of multipart upload. So is this behavior not applicable for multipart uploads?

**Comment by manikandanrs** [comment]
TransferManager internally uses the AmazonS3 client to perform the upload and download operations.

The uploadPart in AmazonS3Client doesn't set this header if its not available in the UploadPartRequest. <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L2764">Here</a> is the piece of code which does this. 

When you use TransferManager to upload objects, it creates new upload part requests for every part and uses the underlying AmazonS3Client. This is <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadPartRequestFactory.java#L64">where</a> it creates new UploadPartRequests and as you can see the MD5 is not set.

Hence when you use TransferManager to upload big objects, you don't see this header being set in the request.

However, <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L2817">AmazonS3Client#doUploadPart</a> calculates the MD5 of the individual part as it streams the contents and compares it with the value returned in Etag in the response. The piece of code which does the integrity check is <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L2828">here</a>

We will need to fix the uploadPart method in AmazonS3Client to set this header if the source is a file. If the source is a stream (for cases like TransferManager), the check is done at the client side by the Java SDK and not at the server side by S3.

**Comment by yagyesha** [comment]
Simply put...
If i have precalculated md5 hash of the object(in the range of 5GB & above) that i'm trying to upload to s3 using multipart upload, is there a way i can verify the integrity of uploaded object?

**Comment by manikandanrs** [comment]
The Java SDK does that for you. It throws a AmazonClientException when it is not able to verify the integrity of the upload.

**Comment by yagyesha** [comment]
Exactly, that's what i'm saying..This behavior is not seen with multipart upload. Though i get AmazonClientException when i upload the same file in a one part if the md5 hash doesn't match.

**Comment by manikandanrs** [comment]
I believe, you are using the TransferManager for the uploading. When using TransferManager, the object is uploaded in multiple parts. The MD5 check is done for the individual parts and not for the complete object. 

S3 doesn't return the MD5 of the whole object in case of multi part uploads.

**Comment by manikandanrs** [comment]
And the MD5 computations is done for you by the SDK.

**Comment by manikandanrs** [comment]
Closing this issue since there is no response. Feel free to reopen.

**Comment by sgarg-symphy** [comment]
@manikandanrs I am trying to perform  a multi part upload by following the documentation [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/mpListPartsJavaAPI.html). Once the upload succeeds I try to download the object
`s3Object = s3Client.getObject(bucketName, key); 
String md5=s3Object.getObjectMetadata().getContentMD5();
` 

However md5 is null...I looked at the objectMetadata but it does not have the Content-Md5 set in it.How can I get the Md5 ?

**Comment by tagus24** [comment]
I think we should be able from client side verify integrity of a multi part upload using one method to get the md5 of the whole object...
