### ISSUE TITLE
aws-java-sdk-s3: java.lang.NoClassDefFoundError: com/amazonaws/SignableRequest

### ISSUE THREAD

**Issue by GuiSim** [aws/aws-sdk-java#420]
Looks like aws-java-sdk-s3 requires com.amazonaws.SignableRequest.
This class is defined in aws-java-sdk-core and from what I've seen aws-java-sdk-s3 doesn't have it in its dependencies.
I've tried with 1.9.32 and 1.9.33.

A workaround is simply to depend on both aws-java-sdk-s3 and aws-java-sdk-core as such:
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.9.33</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.9.33</version>
        </dependency>
```

If the current behavior is expected and end users are expected to include aws-java-sdk-core, the documentation at http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-setup.html should be updated.

Let me know if this is something that I can fix, I'm not familiar with the dependency sections of this project's modules. 
From what I've seen most sub-modules include in their pom.xml:
```
  <!-- The dependencies section in pom.xml is auto generated. No manual changes are allowed -->
  <dependencies>
    <dependency>
        <artifactId>aws-java-sdk-core</artifactId>
        <groupId>com.amazonaws</groupId>
        <optional>false</optional>
        <version>1.9.33</version>
    </dependency>
```

I'm not sure where this autogeneration is coming from. Perhaps this config is missing aws-java-sdk-s3?

**Comment by GuiSim** [comment]
Hmm. Looking at https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/pom.xml it seems to be pulling on https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-kms/pom.xml which in turns includes aws-java-sdk-core.

I'm not sure why I get the NoClassDef above and why the proposed workaround works.

**Comment by david-at-aws** [comment]
Do you perhaps have some other dependency that's pulling in an older version of aws-java-sdk-core before SignableRequest was added? [Maven's dependency plugin](https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html) can help sort these kinds of things out. Maven uses a 'nearest-wins' conflict resolution strategy by default rather than a 'newest-wins', which could explain why adding a direct dependency on core-1.9.33 fixes things.

**Comment by GuiSim** [comment]
@david-at-aws 

That is indeed the problem. I had a dependency on a library that is pulling on aws-java-sdk 1.9.15.

Since Maven uses a nearest-wins conflict resolution strategy and aws-java-sdk-s3 requires aws-java-sdk-core, perhaps aws-java-sdk-s3 should pull directly from aws-java-sdk-core instead of going through aws-java-sdk-kms? Maybe that's not worth it considering the rarity of the situation I'm facing and the ease of the workaround.

Thank you for your time!

**Comment by david-at-aws** [comment]
Glad to hear you got it sorted out! It does seem like it'd be safer to pull in an explicit dependency on the appropriate version of `aws-java-sdk-core` from `aws-java-sdk-s3` - I'll see if we can get this added in a future release.

**Comment by Sravan-Gogineni** [comment]
: java.lang.NoClassDefFoundError: com/amazonaws/services/s3/AmazonS3EncryptionClientV2Builder will this dependency resolve by adding aws-java-sdk-core.jar to spark environment ?
