### ISSUE TITLE
generatePresignedUrl returns a URL which doesn't always play well with https cert

### ISSUE THREAD

**Issue by MichaelBlume** [aws/aws-sdk-java#421]
If I have a bucket, foo.bar, and I call generatePresignedUrl to get a URL for a resource in the bucket, I get something like

`https://foo.bar.s3.amazonaws.com/some-resource`

If I try to open this link in the browser, I get an error saying the provided cert doesn't cover this address. The amazon s3 cert covers `*.s3.amazonaws.com`. Unfortunately, that `*` doesn't cover substrings with dots in them. There's a simple workaround for this, which is to reorder the url so that the bucket name is in the path:

`https://s3.amazonaws.com/foo.bar/some-resource`

Right now we're doing this rewriting in our service, but it seems like there's no reason the SDK couldn't return URLs this way by default.

**Comment by hansonchar** [comment]
Hi @MichaelBlume, for the AmazonS3Client instance that you used to generate the pre-signed URL, have you tried specifying the option of using path style access, like so:

```java
  AmazonS3Client s3 = ...;
  s3.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
  ...
  s3.generatePresignedUrl("foo.bar", ...);
```
?

That should produce the pre-signed URL with the desired format.

**Comment by MichaelBlume** [comment]
Missed that, thanks =)
