### ISSUE TITLE
Removal of JSON.org library code

### ISSUE THREAD

**Issue by puntogil** [aws/aws-sdk-java#423]
Hi
Most of the code in aws-java-sdk is licensed under Apache License Version 2, but a few utility classes used for JSON support [1] are non-free [2] . These classes contain a clause that contains usage restrictions ("The Software shall be used for Good, not Evil.").
Such usage restriction makes the license incompatible with The Open Source Definition and The Free Software Definition. Because aws-java-sdk binary distribution includes this software, it effectively becomes proprietary software itself.

Please try to replace it with one of the many free alternatives.

[1]
aws-java-sdk-core/src/main/java/com/amazonaws/util/json/JSONArray.java
aws-java-sdk-core/src/main/java/com/amazonaws/util/json/JSONException.java
aws-java-sdk-core/src/main/java/com/amazonaws/util/json/JSONObject.java
aws-java-sdk-core/src/main/java/com/amazonaws/util/json/JSONTokener.java
aws-java-sdk-core/src/main/java/com/amazonaws/util/json/JSONWriter.java
[2]
http://www.sonatype.com/people/2012/03/use-json-well-youd-better-not-be-evil/
http://tanguy.ortolo.eu/blog/article46/json-license

**Comment by shorea** [comment]
JSON.org has been removed in 1.11.0

**Comment by indivisible-irl** [comment]
So for reference the last version WITH the /util/json/JSONThings is 1.10.77
