### ISSUE TITLE
changeMessageVisibility on AmazonSQSClient javadocs are ambiguous

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-sdk-java#424]
The javadocs for the [changeMessageVisibility] (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClient.html#changeMessageVisibility(java.lang.String,%20java.lang.String,%20java.lang.Integer)) method.

Contain:
> Changes the visibility timeout of a specified message in a queue to a new value. The maximum allowed timeout value you can set the value to is 12 hours. This means you can't extend the timeout of a message in an existing queue to more than a total visibility timeout of 12 hours. (For more information visibility timeout, see Visibility Timeout in the Amazon SQS Developer Guide .)

> For example, let's say you have a message and its default message visibility timeout is 30 minutes. You could call ChangeMessageVisiblity with a value of two hours and the effective timeout would be two hours and 30 minutes. When that time comes near you could again extend the time out by calling ChangeMessageVisiblity, but this time the maximum allowed timeout would be 9 hours and 30 minutes.

This is a little ambiguous because it is not clear whether changing the timeout extends the timeout - i.e. adds to the current timeout or simply resets the timeout.

From the [API docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html) it is clear that changing the timeout resets the time out - i.e the value provided becomes the timeout from now:

> Changes the visibility timeout of a specified message in a queue to a new value. The maximum allowed timeout value you can set the value to is 12 hours. This means you can't extend the timeout of a message in an existing queue to more than a total visibility timeout of 12 hours. (For more information visibility timeout, see Visibility Timeout in the Amazon SQS Developer Guide.)

> For example, let's say you have a message and its default message visibility timeout is 5 minutes. After 3 minutes, you call ChangeMessageVisiblity with a timeout of 10 minutes. At that time, the timeout for the message would be extended by 10 minutes beyond the time of the ChangeMessageVisibility call. This results in a total visibility timeout of 13 minutes. You can continue to call ChangeMessageVisibility to extend the visibility timeout to a maximum of 12 hours. If you try to extend beyond 12 hours, the request will be rejected.

Please could the javadocs be updated to better reflect the API behaviour...

**Comment by manikandanrs** [comment]
The javadocs are in sync with the API docs now. Closing this.
