### ISSUE TITLE
AmazonHttpClient.logRequestId logs request IDs at INFO level.

### ISSUE THREAD

**Issue by seanparsons** [aws/aws-sdk-java#426]
As of the current time, this line here:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L789
Causes logs to go out at INFO level for every single HTTP request that is made. Which is quite an aggressive log level for something that happens on every request and in our case means we're having to reconfigure our logging to prevent it from appearing.

**Comment by hansonchar** [comment]
Apparently some customers want to have this request id always logged but some don't.  We need to think more about where the line can best be drawn.

**Comment by seanparsons** [comment]
@hansonchar Surely for those that want it they can switch DEBUG on for that class and it logs at DEBUG? This seems to be a reverse application of the 80:20 rule where most people will have to disable it rather than the minority needing to enable it.

**Comment by hansonchar** [comment]
I guess the tricky bit is that for those who want to have the request id only want the request id and nothing else.  Turning on DEBUG unfortunately will log more than they wish.

**Comment by seanparsons** [comment]
Surely the better solution then is to create a separate logger just for the request IDs?

**Comment by hansonchar** [comment]
Agree.  We will have this fixed in our next release.  Thanks for reporting this and the suggested fixes.
