### ISSUE TITLE
Create a "BOM pom" to ease maven dependencyManagement

### ISSUE THREAD

**Issue by zacthompson** [aws/aws-sdk-java#429]
A bill-of-materials (BOM) maven module would allow users to easily keep the versions of aws-java-sdk modules in sync across their project by adding a single dependencyManagement item (type=pom, scope=import). As suggested by a comment on the post announcing the module split
(https://java.awsblog.com/post/TxBSZ02ZOG3VPZ/AWS-SDK-for-Java-Maven-Modules#postCommentsTxBSZ02ZOG3VPZ):

> With a BOM module, a project could declare a single versioned dependency (the BOM) into its dependency management section ... This would be a really big help for complex multi-module build configurations that use a significant number of AWS services in various combinations.

See Spring framework for an example of a project with many modules that delivers a BOM module for this purpose (note that they generate theirs programmatically with gradle, so a source code link would not be v helpful): https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/4.1.6.RELEASE/spring-framework-bom-4.1.6.RELEASE.pom

**Comment by manikandanrs** [comment]
@zacthompson 

Thanks for the suggestion. We will look into this and get back to you.

**Comment by doom777** [comment]
This is also important because the spring-cloud-aws pulls in old versions of aws jars, causing version mismatch

**Comment by NathanChristie** [comment]
I 5th this request! It's painful to see so many duplicated version numbers in my POMs.

**Comment by manikandanrs** [comment]
Thanks for the suggestion everyone. We will get this fixed.

**Comment by manikandanrs** [comment]
Good news everyone. We have released a new Maven BOM "aws-java-sdk-bom" as part of the last release

https://aws.amazon.com/releasenotes/Java/8273574374315535
