### ISSUE TITLE
Effective Java 8 Streams in Dynamo API

### ISSUE THREAD

**Issue by adammaass** [aws/aws-sdk-java#431]
Copying the text of a question I asked at the AWS forums (https://forums.aws.amazon.com/thread.jspa?threadID=180415&tstart=0)

[QUOTE]

I haven't found a positive answer, so I thought I'd ask directly.

In the Java API to dynamodb, the response to Table.query is an ItemCollection<QueryOutcome>. (Funky that it implements Iterator<Item>, but so be it).

That's good as far as it goes: it appears that the paging behavior is hidden behind the Iterator. (I'll be confirming that with some tests in the next little bit).

What I really want, though, is not an Iterator<Item> but a Stream<Item> -- so that I can start taking advantage of a number of pipelining operations. (Ultimately, DynamoDB Item instances are represented across the wire in a customized JSON format -- I'd like to make use of Java 8 streams to pipeline the transformation.)

I can transform the ItemCollection<QueryOutcome> into a Stream<Item> using ItemCollection.spliterator() and passing the result through StreamSupport.stream() -- but this (as of 1.9.34) appears to rely on the default implementation of spliterator() in Iteratable. Can I expect better (more customized, appropriate) support for Java 8 streams from the Java API anytime soon? 

[/QUOTE]

The primary use-case for my immediate needs is:

I want a Stream<Item> that:

1) Implicitly handles the paging behavior of the query and scan apis behind the scenes,
1A) That does not hold references to Item instances already returned,
2) So that I can call a .map operation on the stream to produce a Stream<MyCustomDTO> 
3) Which can then have a .map operation on it to produce a Stream<MyCustomView>
4) Which can then be .forEach'ed so that I can produce a streaming response to my client -- which implicitly is actually fed from paging responses all the way in the DynamoDB API. 

The primary reason for this is to handle very large data sets in a way that does not require a lot of memory in my app server. IE, at no time should any layer of the application, from the DynamoDB API up through my code, hold any more than a small [or barring "small", at least finite] number of the records that need to be returned in memory.

-------

Additional use-cases (more specialized) might be:

1) Easily enable the app-server to parallelize processing on the Stream<Item> that is coming back from DynamoDB. (This necessarily comes with limitations: IE, if encounter order the stream is no longer guaranteed, then parallelization is easier to produce.)

--------

It makes sense that the DynamoDB API would return Stream<Item> in this way -- perhaps implementations of the Streams would work seamlessly with behavior on the server-side to produce nifty features like extreme parallelization.

**Comment by adammaass** [comment]
In particular, a customized Spliterator would report appropriate characteristics. (Maybe ORDERED | DISTINCT | NONNULL | CONCURRENT). It would also report an accurate guesstimate for estimateSize(), and maybe would produce a Spliterator per page in response to trySplit().

The query and scan APIs might be extended so that the callers could indicate that order is not important, and the Spliterators returned from those calls might report DISTINCT | NONNULL | CONCURRENT characteristics.

**Comment by shorea** [comment]
We've recently fixed a bug in the paginated scan lists when using Java 8 streams. Unfortunately since we still support Java 6 and 7 we can't take full advantage of Java8 streams and ideally (for now at least) we should only return iterators and trying to make a paginated result set a collection has given us many problems in the past.
