### ISSUE TITLE
socket leak in IdleConnectionReaper?

### ISSUE THREAD

**Issue by kelnos** [aws/aws-sdk-java#433]
I have an app that uses the DynamoDB client.  I've noticed that over time memory usage grows, until after a few days, I'm running out of heap.  I used plumbr (https://plumbr.eu) to watch for memory leaks, and it claims that instances of `com.amazonaws.internal.SdkSSLSocket` are piling up.  Here's the incident output:
```
At the time the leak was detected, 626 objects existed of class

com.amazonaws.internal.SdkSSLSocket

These objects had been created at

com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(java.net.Socket, java.net.InetSocketAddress, java.net.InetSocketAddress, org.apache.http.params.HttpParams):121

and were being held

in socket of org.apache.http.impl.conn.DefaultClientConnection
  in conn of org.apache.http.impl.conn.HttpPoolEntry
    in item of java.util.LinkedList$Node
      in next of java.util.LinkedList$Node
        in first of java.util.LinkedList
          in available of org.apache.http.impl.conn.HttpConnPool
            in pool of org.apache.http.impl.conn.PoolingClientConnectionManager
              in elementData of java.util.ArrayList
                in connectionManagers of com.amazonaws.http.IdleConnectionReaper
                  in com.amazonaws.http.IdleConnectionReaper
```
Note that it says 626 socket objects are being held, which is odd since I have max connections set to 100 for the client.  Also possibly of note is that I've set a connection timeout of 4 seconds and a connection TTL of 15 minutes.  I've also disabled the client's retry behavior and I'm handling it myself.  I'm using version 1.9.33 of the SDK.

**Comment by hanshuo-aws** [comment]
Hi @kelnos IdleConnectionReaper holds reference to all the httpclient instances spawned in the JVM process (and the reference will be released after the client is gced or explicitly shutdown). In your application code, did you instantiate any other service clients (or multiple dynamodb clients) but forget to release them?

Also, can you enable debug logging for apache-httpclient's connection-manager?
https://hc.apache.org/httpcomponents-client-ga/logging.html

**Comment by kelnos** [comment]
No, I have just one DynamoDB client instance that gets used for the lifetime of the app, and I'm not using any other service through the AWS SDK.  I'll try to set up debug logging and post results when I have them.

**Comment by kelnos** [comment]
So I disabled connection TTLs (set to -1), and after 24 hours memory usage is much more stable and hasn't been growing, from what I can tell.

I enabled debug logging for the httpclient connection manager and let it run overnight, and now I have a 16GB log file.  Is there any particular message you're looking for, or should I just cut out a section of it to post somewhere?

**Comment by kelnos** [comment]
@hanshuo-aws sorry i lost track of this one.  unfortunately lost the instance with the logs on it.  about 3 weeks ago i downgraded to the previous version of the aws sdk we were using (1.9.10), and the leak has gone away.

**Comment by manikandanrs** [comment]
Do you mean you don't see the issue prior to 1.9.10 ?

**Comment by kelnos** [comment]
hey, sorry i hadn't followed up on this more.  after some more investigating, it looks like it was a GC issue (G1 GC not able to keep up with garbage generated by a scala app).  moving back to the CMS collector has fixed the problem.  not sure why the leak detection tools were consistently pointing at the AWS SDK as the culprit, but it's certainly not at fault here.

**Comment by manikandanrs** [comment]
Glad you are able to resolve this problem.

**Comment by jsrayalu** [comment]
Hello Manikandan,

Can you pls help in understanding this.
I have some data stored in AWS and am retrieving the data using S3 client. But when I am trying to get the S3Client instance created, it is taking lot of time(4-6 seconds) sometimes. When I checked the logs, I see that SdkTLSSocketFactory is the class which is trying to create the SdkSSLSocket class instance , which itself is taking around 3 seconds.

Could you please help me in understanding this issue and to my knowledge it is a configuration issue. 

Please help me in understand and resolve this. Expecting your response asap.

**Comment by manikandanrs** [comment]
Can you provide a repro test case for this ?

**Comment by manikandanrs** [comment]
Also, can you please open a new issue in the repo.
