### ISSUE TITLE
Missing data in the Grantee

### ISSUE THREAD

**Issue by amedeiros** [aws/aws-sdk-java#434]
We are currently switching from the Ruby SDK into the Java SDK as we are switching to Java. When getting a buckets ACL in the Ruby SDK and looking at the grantee there is a URI that we check. Here are the docs http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#get_bucket_acl-instance_method. Under response structure and then grants -> grantee there is a URI that gets returned.
```
:uri => String
URI of the grantee group.
```

This field is not present in the Java SDK equivalent.

**Comment by hansonchar** [comment]
There exists a ```groupUri"``` when the returned list of ```"Grant"```'s involve ```"GroupGrantee"```. It seems you can check the type of the returned ```Grant``` instances and for ```GroupGrantee``` you can do a downcast and get the group URI via the ```GroupGrantee#getIdentifier()``` method.

Hope this helps.

**Comment by amedeiros** [comment]
@hansonchar Do you mind elaborating on that more. Right now I just see CanonicalGrantee coming across in the debugger. How do you suggest I pivot based on CanonicalGrantee and GroupGrantee with in the Grants list? Or does the list not return a mixture of grantees.

**Comment by hansonchar** [comment]
Hi  @amedeiros,

Actually there is no need to downcast.   You can do something like:

```java
AccessControlList res = ...;
List<Grant> grants = res.getGrantsAsList();
for (Grant grant: grants) {
  Grantee grantee = grant.getGrantee();
  if ("uri".equals(grantee.getTypeIdentifier()) {
      System.out.println("uri: " + grantee.getIdentifier());
  }
}
```

**Comment by amedeiros** [comment]
@hansonchar Thank you that looks like what I'm looking for.
