### ISSUE TITLE
development s3 server

### ISSUE THREAD

**Issue by jackphel** [aws/aws-sdk-java#438]
Does aws have a local development s3 server?

Google cloud seems to have https://cloud.google.com/datastore/docs/tools/devserver to test using the analogous service without having to connect to a production, and azure seems to have https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/

Suppose I'm running my server in a container and I start up containers all the time for dev/testing on CI machines and on different teams of devs. I'll have all sorts of false positives and false negatives in manual and automated tests if they share buckets, and they all have to be able to connect to the internet anyway in order to access buckets (not to mention incur $ costs!). I can stub out, hard coding special stuff for s3 so that I just write/read local files, in my server code, but then I'm not sure whether everything is going to actually work in production, and then if I have two services that expect to read/write the same bucket in an integration scenario, they both have to be stubbed to share the same files, and then I have potential issues with concurrent access.

I've been using https://github.com/jubos/fake-s3 but it's not really actively maintained, though it seems to be popular.

**Comment by andrewgaul** [comment]
@jackphel Consider using https://github.com/andrewgaul/s3proxy which is actively maintained.  You can configure it to use either a memory or filesystem backend for development.

**Comment by shorea** [comment]
Closing this issue as there are a couple alternatives out there. We don't have immediate plans to provide a local version of S3.
