### ISSUE TITLE
SDK not working on upcoming Java 1.8u60

### ISSUE THREAD

**Issue by tkowalcz** [aws/aws-sdk-java#444]
Joda Time has problems with formatting time zones starting with Java 1.8u60. AWS client requests will incorrectly format Date header causing server to reject the request. We tested this with S3 client but probably all services will be affected. I have described the issue in more detail here: https://github.com/JodaOrg/joda-time/issues/288

**Comment by david-at-aws** [comment]
Yikes, thanks for bringing this to our attention!

**Comment by tkowalcz** [comment]
I have created pull request for this: https://github.com/JodaOrg/joda-time/pull/291. @jodastephen have patched and released version 2.8.1.

**Comment by manikandanrs** [comment]
This has been fixed. Thanks for the pull request
http://aws.amazon.com/releasenotes/8143039639694253

**Comment by tkowalcz** [comment]
Hi, Is it possible at all to mention this issue in release notes? Right now there is no way someone notices the need to upgrade just from release notes.

**Comment by kaaloo** [comment]
I'm seeing this just now on aws-sdk-java 1.10.12 and oracle jdk 1.8u60 on ubuntu vivid:

    java version "1.8.0_60"
    Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by dadoonet** [comment]
@kaaloo Same here. We have users reporting the same behavior [here](https://github.com/elastic/elasticsearch-cloud-aws/pull/234#issuecomment-134934708).

**Comment by shorea** [comment]
Can you confirm you are pulling in joda-time-2.8.1+ at runtime? See https://github.com/aws/aws-sdk-java/issues/484 for suggestions on how to identify which version of joda time you are using.

**Comment by kaaloo** [comment]
I clearly saw the joda-time 2.8.1 jar in my war file.  I even tried with 2.8.2 with no effect.  I will try again printing out new DateTime().getClass().getProtectionDomain().getCodeSource() and get back to you.

**Comment by kaaloo** [comment]
Whoa, you're right!  Something weird is going on with the dependencies in my project:

Joda Time Version: (file:/home/luis/.m2/repository/org/jruby/jruby-complete/1.7.11/jruby-complete-1.7.11.jar <no signer certificates>)

It's picking up an embedded version of joda-time and I have to see why jruby is being brought in in the first place.  Thanks for your help @shorea !

**Comment by shorea** [comment]
Yeah no problem, glad I could help.

**Comment by dadoonet** [comment]
w00t! I know what happened on my end. Indeed, I updated to latest AWS version my project but my project is still also using JODA 2.7! :( Will fix and report.  Thanks!

**Comment by dadoonet** [comment]
Confirmed. Works fine with JODA 2.8.2. Sorry for the noise.

**Comment by JoelJ** [comment]
The latest version still doesn't work for me. I have this in my pom.xml:

```xml
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk</artifactId>
			<version>1.10.15</version>
		</dependency>
```

And I did a mvn dependency:tree and have the following:

```
[INFO]    \- com.amazonaws:aws-java-sdk-core:jar:1.10.15:compile
[INFO]       +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO]       +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO]       |  +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
[INFO]       |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO]       \- joda-time:joda-time:jar:2.5:compile
```

I had to do the following to work around the issue:

```xml
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk</artifactId>
			<version>1.10.15</version>
			<exclusions>
				<exclusion>
					<groupId>joda-time</groupId>
					<artifactId>joda-time</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.8.2</version>
        </dependency>
```

That changes the dependency:tree to look like this:

```
[INFO] |  \- com.amazonaws:aws-java-sdk-core:jar:1.10.15:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |     \- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] |        +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
[INFO] |        \- commons-codec:commons-codec:jar:1.6:compile
[INFO] \- joda-time:joda-time:jar:2.8.2:compile
```

**Comment by shorea** [comment]
Can you try printing out new DateTime().getClass().getProtectionDomain().getCodeSource() to show where joda time is being loaded from when you run your app?

**Comment by mortenbruhn** [comment]
Just a quick comment if others are suffering from this same issue on what solved it for me. I use 
- java version "1.8.0_60" 
- Apache Maven 3.3.3

Here are the steps that I ended up following:

1. Update pom.xml to depend on version 2.8.2 of `joda-time` and 1.10.15 of `aws-java-sdk` as @JoelJ describes in his post above
2. Use the method suggested by @shorea to see what version of `joda-time` is actually being linked:

```System.out.println(new DateTime().getClass().getProtectionDomain().getCodeSource());``` 

3. Purge the old version of joda-time (2.3) that was apparently being linked 

```rm -rf ~/.m2/repository/joda-time/```

4. Build and run again
5. Repeat step 2 to verify that the correct version of `joda-time` is now being linked.

That did the trick for me. Hope it will help others

**Comment by chexov** [comment]
Here is my "quickfix fork" which works with JVM1.8
https://github.com/chexov/s3s3mirror/tree/jvm1.8

I did removed slf4j, joda, lambo because they.. well... no needed for such simple tools:)

**Comment by sathishkumar55** [comment]
Updated the Joda time library to 2.8.2 or 2.9.4 and it is working fine for 1.10.72.
But when i update the aws-sdk-core library to 1.11.23 version ,i am still facing thie issue

**Comment by varunnvs92** [comment]
@sathishkumar55 
Can you try printing the version of joda-time using this:
System.out.println(new DateTime().getClass().getProtectionDomain().getCodeSource());
