### ISSUE TITLE
Aws not working with non-google devices

### ISSUE THREAD

**Issue by moonandroid** [aws/aws-sdk-java#447]
My app have some google functionality like GCM,Google +,Google map with clustering.
Before implementing aws my app working well in all devices.
But after implementing aws my app stop working in non-google devices means app only work in Nexus device.
I tried lots but not found any solution.
But We have checked more and founded that there are some issue with aws-android-sdk-core-2.2.1 because this file contain some google classes so it may be conflict with other google classes.

Any one have idea why this issue comes ?

**Comment by manikandanrs** [comment]
Hi,

Thanks for question. Here is the git repo for android sdk. I suggest raising a question here.

https://github.com/aws/aws-sdk-android

**Comment by moonandroid** [comment]
ok i will post there
