### ISSUE TITLE
ProfileCredentialsProvider Should Support AWS_DEFAULT__PROFILE

### ISSUE THREAD

**Issue by jrduncans** [aws/aws-sdk-java#451]
I'm not sure of the history here, I see that the environment variable AWS_PROFILE was added in #249, but all of the documentation and the AWS CLI supports AWS_DEFAULT_PROFILE, not AWS_PROFILE.

**Comment by manikandanrs** [comment]
As part of our recent efforts to standardize the credentials usage across SDK's , CLI and tool kits we agreed on to use AWS_PROFILE as the environment variable name. The CLI supports AWS_DEFAULT_PROFILE for backwards compatibility reasons. 

I will get the CLI's documentation updated to reflect the AWS_PROFILE. Thanks for bringing this to our documentation.
