### ISSUE TITLE
Feature request: allow to interrupt long-poll message receiving in SQS (withWaitTimeSeconds)

### ISSUE THREAD

**Issue by flozano** [aws/aws-sdk-java#454]
There's no way right now to cleanly interrupt the long-poll request that is performed when receiving messages from SQS with the option:
```java
    public ReceiveMessageRequest withWaitTimeSeconds(Integer waitTimeSeconds) {
        this.waitTimeSeconds = waitTimeSeconds;
        return this;
    }
```

**Comment by shorea** [comment]
This is tricky as the apache client (and any IO bound activity in general) is not responsive to interrupts. We'd essentially need to abort the connection which obviously needs to be done on another thread. What's your use case? If you are trying to shutdown cleanly perhaps the client shutdown will give you what you want.

**Comment by flozano** [comment]
I missed the comment. I'm trying to do a proper shutdown without having to wait for each of the ongoing long-SQS-polls to finish.

**Comment by shorea** [comment]
See https://github.com/aws/aws-sdk-java/issues/655. Shutting down the client is the recommended way to cancel any pending long poll operations.
