### ISSUE TITLE
NPE from string builder in AWS4Signer

### ISSUE THREAD

**Issue by amedeiros** [aws/aws-sdk-java#456]
We are seeing a NPE that looks like it is originating from the AWS4Signer. We are currently running version 1.9.36.

```
java.lang.NullPointerException
        at java.lang.StringBuilder.<init>(StringBuilder.java:112)
        at com.amazonaws.auth.AWS4Signer.computeSigningCacheKeyName(AWS4Signer.java:370)
        at com.amazonaws.auth.AWS4Signer.deriveSigningKey(AWS4Signer.java:338)
        at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:204)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:687)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:6925)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.listRoles(AmazonIdentityManagementClient.java:6195)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.listRoles(AmazonIdentityManagementClient.java:6856)
```

**Comment by david-at-aws** [comment]
Thanks for the report! [Looks like](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L370) your secret key is null for some reason. How are you passing credentials to the SDK? We should definitely be kicking back a nicer exception than just an NPE in this case, but it's definitely going to have to fail somehow if it doesn't actually have credentials available.

**Comment by amedeiros** [comment]
Thats interesting because we just start our EC2 instance under a specific role with the policy we need it to have. Its not something thats happening all the time either. 

I double checked and the instances running the code are all running the same IAM role. Its very strange that its not constant. 

We use bugsnag I just set it to open again if it happens 10 more times. Will monitor and see if it occurs again. Thank you for your response.

**Comment by david-at-aws** [comment]
Hm, I agree, very strange. We should be throwing an exception [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceProfileCredentialsProvider.java#L194) if there's no secret key in the response from the instance metadata service...

**Comment by amedeiros** [comment]
With some further digging I found where we were indeed exporting keys. Early on in the development of our storm cluster we had the storm configuration export keys when it deploys to the cluster. I removed this from the configuration and started up new supervisors and it seems like nothing is happening at all now as in we stopped assuming role all together. Which leads me to believe that we are having an issue with our role setup.

With the NPE this could be a weird distributed problem with our cluster where the keys might not of been getting exported across all the machines on the cluster from the configuration. Not 100% on that just speculating.

Going to keep digging to make sure its a role issue on our end, but so far it looks like it might point to that.

**Comment by amedeiros** [comment]
We are still experiencing this issue. The only thing I can think of on our end is that the keys are not getting exported correctly by the storm cluster, but I think if that was the case it would be constant and not a once and awhile issue.

**Comment by david-at-aws** [comment]
What AWSCredentialsProvider are you ending up using to pick up the exported credentials? Could you cut out the middleman and switch to using the InstanceProfileCredentialsProvider directly?

**Comment by amedeiros** [comment]
The reason we are using the exported keys is because its in our staging environment which is a different AWS account from our production environment. But the ARN's that we are assuming role with come from our production environment and are setup for assume role under that account. So they are setup with the production account which causes us to have to export the keys from production on the EC2 instances in our staging environment unfortunately.
