### ISSUE TITLE
Docs are not correct for this Class

### ISSUE THREAD

**Issue by nmaves** [aws/aws-sdk-java#458]
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/CloudFrontUrlSigner.html

The examples reference methods that do not exist.

**Comment by david-at-aws** [comment]
Whoop, we'll get those updated. Thanks for the report!

**Comment by david-at-aws** [comment]
Fixed now!
