### ISSUE TITLE
Why does PageBasedCollection return a package protected iterator?

### ISSUE THREAD

**Issue by Dimes** [aws/aws-sdk-java#465]
[PageBasedCollection::iterator](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/internal/PageBasedCollection.java#L31) specifies its return type as [IteratorSupport](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/internal/IteratorSupport.java). The issue is that IteratorSupport is not a public class.

This is a problem because ItemCollection (returned by DynamoDB) extends PageBasedCollection, which means it cannot be mocked. IteratorSupport is listed explicitly as the return type, which means the returned mock must be of type IteratorSupport, which is impossible to create because it is package protected.

**Comment by manikandanrs** [comment]
We have fixed this as part of 1.10.9 release. Thanks for reporting it.

http://aws.amazon.com/releasenotes/6063296319752912
