### ISSUE TITLE
Kinesis isn't recognised as a valid service in us-west-1

### ISSUE THREAD

**Issue by samcday** [aws/aws-sdk-java#466]
[`regions.xml`](https://github.com/aws/aws-sdk-java/blob/55dafdd96ebbb1c22433190df366a25f383d740e/aws-java-sdk-core/src/main/resources/com/amazonaws/regions/regions.xml#L2702) seems fairly out of date - Kinesis is not a supported service in us-west-1, when it should be.

**Comment by manikandanrs** [comment]
Thanks. We have fixed this and should be part of our next release.

**Comment by manikandanrs** [comment]
This is fixed as part of our last release.

https://aws.amazon.com/releasenotes/Java/8273574374315535
