### ISSUE TITLE
Attempting to create an ELB identical to an existing ELB responds silently

### ISSUE THREAD

**Issue by danieljamesscott** [aws/aws-sdk-java#469]
Steps to reproduce:

1. Create an ELB
2. Create an identical ELB with exactly the same configuration.
3. The response from: elbClient.createLoadBalancer(createLoadBalancerRequest); is an empty object containing null values.

Shouldn't this throw DuplicateLoadBalancerNameException?

**Comment by shorea** [comment]
This seems to be the expected behavior from the service although it doesn't appear to be documented. I'll follow up with the service team to ensure that's the case.

You state that you get a response with all null values on subsequent requests. I'm seeing different results, all requests to createLoadbalancer return a valid CreateLoadBalancerResult with the DNSName fields populated. Are you experiencing different behavior? If so which version of the SDK are you using.

**Comment by danieljamesscott** [comment]
From memory, I got createLoadBalancerResult.getDNSName()) == null, version 1.10.2. This then blew up when I attempted to create a DNS record pointing at the ELB.

I can double check this tomorrow and confirm.

**Comment by danieljamesscott** [comment]
OK, I've double checked this, and found the following:

I'm creating ELBs in a VPC.

Creating an **Internet-facing** ELB works correctly, createLoadBalancerResult.getDNSName()) contains the public DNS name of the ELB.

Creating an **Internal** ELB (createLoadBalancerRequest.setScheme("internal")) exhibits the behaviour above. i.e. createLoadBalancerResult.getDNSName()) == null

So, it seems that there may be an issue with internal ELB creation.

**Comment by shorea** [comment]
Interesting, I'm seeing the same behavior with internal LBs. The first call to create will return the DNS name but subsequent calls will not error out and return null for the DNS name. This behavior seems inconsistent. I'll follow up with the service owners to see if there is reasoning behind this.

**Comment by shorea** [comment]
Talked with the service team and there does appear to be a few bugs regarding load balancer creation. There is also an issue with the exception documentation that is in the process of being addressed. I'll update this issue when I get more details from the service team. Thanks for bringing this to our attention!

**Comment by danieljamesscott** [comment]
Is this now fixed?
