### ISSUE TITLE
Should EC2MetadataUtils.getIAMSecurityCredentials return IAMSecurityCredential

### ISSUE THREAD

**Issue by markberryman** [aws/aws-sdk-java#476]
I'm unclear as to why this method returns a Map when an EC2 instance can only be assigned a single role. The comments on the method also mentions the possibility of roles, but is this really possible? Or maybe there's some other way to get multiple sets of credentials associated with an EC2 instance?

**Comment by david-at-aws** [comment]
Hey Mark,

There's no way *currently* to get multiple roles associated with an instance. Under the covers, you associate the instance with an [instance profile](http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-usingrole-instanceprofile.html). In theory an instance profile may be associated with multiple roles, although for the moment at least IAM only actually lets you associate a single one.

The instance metadata service models role credentials as a map from role name to credentials, presumably so they won't need a breaking change if IAM ever allows you to associate multiple roles with a single instance profile in the future. This API is directly modeled on the instance metadata service's API, so it also exposes a map (which for now will only ever contain a single entry).

**Comment by markberryman** [comment]
Got it. Thanks for the details David.
