### ISSUE TITLE
Is s3.internal.RestUtils.makeS3CanonicalString inconsistent with the document?

### ISSUE THREAD

**Issue by akiradeveloper** [aws/aws-sdk-java#480]
Hi, I am new to AWS SDK. I don't know if this is the correct place to ask this question but

I am wondering if the makeS3CanonicalString function in RestUtils

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/RestUtils.java

doesn't implement what's described in this document

http://docs.aws.amazon.com/ja_jp/AmazonS3/latest/API/sig-v4-header-based-auth.html

because the ordering of URI, Query String and the Canonical Headers are different. Also, Signed Headers and Hashed Payload aren't appended by the function.

Am I right? If so, please tell me why code is way off the document?

**Comment by akiradeveloper** [comment]
It's likely the makeS3CanonicalString (the name is quite misleading though) is for signature v2. I will close this issue.

**Comment by david-at-aws** [comment]
Yep, that code's for the old v2 signature. We can't get rid of it yet since v4 requires knowing what region you're going to be talking to before you send the request, while the AmazonS3Client historically has not required an explicit region to be configured.
