### ISSUE TITLE
S3 buckets tagging configuration updated, not overwritten, please.

### ISSUE THREAD

**Issue by wdurhamh** [aws/aws-sdk-java#486]
This is a request for a way to update a bucket's tagging configuration without overwriting the existing configuration.

I need to add a tag to S3 buckets while keeping the existing configuration. I tried getting the current configuration, adding the new tag, and then setting the BucketTaggingConfiguration with this updated configuration. However, some of these buckets are created by CloudFormation, and they have 'aws' prefixed tags, which a user is prohibited from writing to any resource. Because of this, I cannot reset the entire configuration as it was plus the extra tag.

The java sdk needs a way to add tags without rewriting the entire configuration, as is [available in EC2](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2Client.html#createTags(com.amazonaws.services.ec2.model.CreateTagsRequest)).

There seems to be a way to do this [through http](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTtagging.html), so it seems like it should be straightforward, and quite useful.

**Comment by shorea** [comment]
This seems to be a limitation of the S3 API and not specifically the Java SDK. We call the same Action in the API reference you linked. I can make a feature request to S3 if this is a must have feature. Is it possible for you to specify and create the tags through your CloudFormation template?

**Comment by nterry** [comment]
We do need this feature. Can you submit an enhancement request? It seems odd that we are the first people to hit this limitation....

**Comment by wdurhamh** [comment]
Please make the feature request. Achieving our goal through cloudformation would be very roundabout and ugly.

**Comment by hanshuo-aws** [comment]
Hi, @wdurhamh This does look like a reasonable request. We have passed this to the service team and let them look into the possibility of adding this feature. Will update the issue once we get a response.

**Comment by wdurhamh** [comment]
Thank you

**Comment by manikandanrs** [comment]
We have passed this to the S3 team and they have included it in their feature requests planned for S3.

Closing this for now. Feel free to re open.
