### ISSUE TITLE
EMR stopped in middle of job with error.

### ISSUE THREAD

**Issue by darkwish121** [aws/aws-sdk-java#488]
EMR:
There is an error occurred in middle of job and it cancelled all remaining tasks.

Task summary: 108705 total tasks - 62757 completed, 85 running, 0 failed, 45863 pending, 0 cancelled.

I think issue comes after Update of Amazon services. 

S3:
Last time when I run cluster its output parts to S3 as soon as completed a task. But now it make temporary directory in output directory and it ll output parts at the end of all tasks completion. But if job cancelled in middle as shown in following pictures s3 output's temporary directory didn't output parts.

Here is cluster view.

![emr_error](https://cloud.githubusercontent.com/assets/1590250/9217117/23902a04-40dd-11e5-9dfb-cb5e249da268.png)

Here is stderr

![stderr](https://cloud.githubusercontent.com/assets/1590250/9217118/23992136-40dd-11e5-90c0-4b8b6b869b82.png)

Here is syslog
![syslog](https://cloud.githubusercontent.com/assets/1590250/9217120/23ac9ab8-40dd-11e5-950b-3aafd41e6f0d.png)

**Comment by shorea** [comment]
Are you using the SDK to start the EMR job or using the SDK in the job itself? Also could you please give the version that it was working on and the version that it stopped working on.

**Comment by darkwish121** [comment]
I am running it from AWS UI. I re-run server now it completed all steps with no errors but it didn't stop cluster after completion all tasks. It takes almost 12 hours to move files from "/output/temporary/" directory  /output directory. Before AWS updates it creates files in output directory as soon as task completed. But now it takes 12 extra hours. 15 c3.2xlarge machines X 12 hours :-1: 

Here are screenshots of cluster start, end time and task completed time. Then in second screen shot of s3 in which first output file time and _sucess file time.

If it is not right place for this issue then please guide me where can I tell this to Amazon.

Nightmares started after AWS updates which done on 30th Jul

![cluster-comletion-time](https://cloud.githubusercontent.com/assets/1590250/9242840/7f0157cc-41a1-11e5-809f-f8ae5ec23913.png)
    

S3

![files-moving-end-time](https://cloud.githubusercontent.com/assets/1590250/9242850/96ff10a8-41a1-11e5-80d8-3e1c849ab393.png)

**Comment by shorea** [comment]
I'll engage the EMR team and let you know if they prefer you communicate through a different channel like the AWS Forums or by opening a support case.

**Comment by shorea** [comment]
"Nightmares started after AWS updates which done on 30th Jul"

Do you mean an updated version of the SDK? If you roll back to the previous version does the problem persist?

**Comment by darkwish121** [comment]
Some times it works and some times it don't. Now I have completed work some how so closing this issue.
