### ISSUE TITLE
AmazonServiceException: 400 response

### ISSUE THREAD

**Issue by danieljamesscott** [aws/aws-sdk-java#491]
Recently, I've been receiving an increasing number of AmazonServiceExceptions when creating ELBs. The problem is inconsistent, but more and more frequent, so I'm having trouble isolating the cause.

The problem occurs when creating ELBs using:

AmazonElasticLoadBalancing.createLoadBalancer(CreateLoadBalancerRequest)

and I receive the following response:

com.amazonaws.AmazonServiceException: The connection was closed by the server at some point between the client sending the request and the client receiving the entire response (Service: AmazonElasticLoadBalancing; Status Code: 400; Error Code: HttpFailureException; Request ID: 19a8b65f-47e8-11e5-acfc-efe08b93b60a)

I can't see anything consistent about the ELB configuration of those which fail. We create the ELB with its name, listeners, subnets and tags, and then modify it to enable connection draining, access logging and cross-zone balancing. The error occurs during the initial create.

We create several hundred ELBs per day, when launching our test/dev environments, and I'm seeing the error at least once per day, so it's a relatively infrequent, but annoying, problem.

Anyone have any idea what is causing this?

**Comment by danieljamesscott** [comment]
Another one of these today. Anyone else seeing this?

**Comment by david-at-aws** [comment]
Hey Daniel, that does look suspicious. I've passed this on to the ELB team to investigate what's going on.

**Comment by danieljamesscott** [comment]
I'm still getting these requests occasionally. Yesterday, I received the same error when trying to delete a load balancer - the first time I've seen one when deleting, rather than creating.

**Comment by manikandanrs** [comment]
This has been fixed on the service side. Feel free to re open the issue if you still see issues.

**Comment by danieljamesscott** [comment]
Thanks, we've not seen for quite a while now.
