### ISSUE TITLE
Flow Framework @SkipTypeRegistration on a Method

### ISSUE THREAD

**Issue by soldiermoth** [aws/aws-sdk-java#493]
It appears that the `@SkipTypeRegistration` annotation only works on an interface level even though it is allowed on methods in the [definition](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/annotations/SkipTypeRegistration.java#L37).

This appears to be caused by a typo on line [POJOActivityImplementationFactory.java#L214](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/pojo/POJOActivityImplementationFactory.java#L214)
where `interfaze` should be changed to `method`.

**Comment by manikandanrs** [comment]
This issue was moved to aws/aws-swf-flow-library#4
