### ISSUE TITLE
Correct access/secret key env variable names in EnvironmentVariableCredentialsProvider?

### ISSUE THREAD

**Issue by srowen** [aws/aws-sdk-java#50]
In com.amazonaws.auth.EnvironmentVariableCredentialsProvider, the environment variables "AWS_ACCESS_KEY_ID" and "AWS_SECRET_KEY" are used for access and secret keys. 

However in documentation like at http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SettingUp_CommandLine.html#set-aws-credentials_ the names are "AWS_ACCESS_KEY" and "AWS_SECRET_KEY".

Elsewhere, like at http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html , the values seem to be "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY".

This is maybe more of a question. But I had understood the second version to be correct.

**Comment by manoharreddyporeddy** [comment]
List of all environment variables: http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
