### ISSUE TITLE
Non-AWS connections being cleaned by ConnectionReaper

### ISSUE THREAD

**Issue by sangupta** [aws/aws-sdk-java#500]
In one of our applications we are using both the AWS SDK and Apache HttpClient 4.3.5. Apache HttpClient is used to make other webservice calls both inside and outside of AWS. We are seeing an issue where the background ConnectionReaper thread is closing down the connections created using PoolingClientManager created somewhere else.

This closes connections to our webservice calls before the call could be made successfully.

Anyone else experiencing this issue, or know why this might be happening?

**Comment by manikandanrs** [comment]
Can you share us a standalone test case for this ?

IdleConnectionReaper closes the idle connections only on the connection managers registered to it

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/IdleConnectionReaper.java#L120

By any chance does your application register the pooling client manager with the idle connection reaper?

**Comment by manikandanrs** [comment]
Closing this issue as we haven't heard back. Feel free to reopen.

**Comment by sangupta** [comment]
I haven't been able to reproduce the issue in a stand-alone application. I have checked that our pooling client manager is not registered with the idle connection reaper explicitly.

Am still trying to reproduce a standalone app - will post code if I get successful.

**Comment by manikandanrs** [comment]
Thanks for the update. Feel free to re open the issue when you are able to reproduce an issue.
