### ISSUE TITLE
Get empty hadoop configuration by using AmazonElasticMapReduceClient.describeCluster 

### ISSUE THREAD

**Issue by bchen-talend** [aws/aws-sdk-java#501]
Hi

I tried to use the java sdk to get hadoop configuration properties of EMR cluster, the API I used is:
[AmazonElasticMapReduceClient.describeCluster](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-emr/src/main/java/com/amazonaws/services/elasticmapreduce/AmazonElasticMapReduceClient.java#L1227)
But the result I get is 
```
{
    Cluster: {
        Id: j-12DWOAIMTHZK9,
        Name: emr400wizard,
        Status: {
            State: WAITING,
            StateChangeReason: {
                Message: Waiting after step completed
            },
            Timeline: {
                ...
            }
        },
        Ec2InstanceAttributes: {
            Ec2KeyName: emr400wizard,
            ...
        },
        LogUri: s3n://aws-logs-242907804123-ap-northeast-1/elasticmapreduce/,
        ReleaseLabel: emr-4.0.0,
        AutoTerminate: false,
        TerminationProtected: false,
        VisibleToAllUsers: true,
        Applications: [
            {
                Name: Hadoop,Version: 2.6.0,
                Args: [],
                AdditionalInfo: {}
            }, 
            ...
        ],
        Tags: [],
        ServiceRole: EMR_DefaultRole,
        NormalizedInstanceHours: 24,
        MasterPublicDnsName: ec2-176-32-83-123.ap-northeast-1.compute.amazonaws.com,
        Configurations: []
    }
}
```
The Confgurations is empty, is it a bug?

Thanks!

**Comment by shorea** [comment]
Which version of the Java SDK are you using? Can you try with the CLI to see if anything is coming back there?

**Comment by bchen-talend** [comment]
1.10.15,  will try CLI later, a question is no matter the status of cluster is, the Configurations should always exists?

**Comment by bchen-talend** [comment]
aws-cli/1.8.1, the result is same as the SDK, no configurations

**Comment by shorea** [comment]
Inspected the raw response and it's empty there as well. I'll forward this question to the service team as it doesn't appear to be an issue with the SDK.

**Comment by bchen-talend** [comment]
Thank you

**Comment by shorea** [comment]
Quick question. Are you passing custom config to the cluster or are you expecting the default hadoop configuration to be returned in the response?

**Comment by bchen-talend** [comment]
Want the hadoop configuration of the current cluster used.

**Comment by bchen-talend** [comment]
Hello @shorea ,
Is that mean the problem has been fixed?

**Comment by shorea** [comment]
Hey sorry we were closing old issues on Friday and I guess I got a bit too eager with this one. Is the API still returning empty configurations?

**Comment by bchen-talend** [comment]
I tested it again with the 1.10.72 version, I found it can return the configuration which I set when create cluster.
such as I use my configuration file to create the cluster.
`[
    {
      "Classification": "mapred-site",
      "Properties": {
        "mapred.job.reuse.jvm.num.tasks": "-1"
      }
    }
  ]
`
I can get the same by using describeCluster, is that the expect behavior?
if so, there is a question about how to get the default configuration? I want to get the all the real configuration the cluster used.

**Comment by shorea** [comment]
Sorry for the long delay in response here. I engaged the service team and they confirmed this is expected behavior.

> The behavior is expected. The customer wants to know what configuration EMR is calculating on their behalf when it provisions the cluster. For example, the host address of the master node, etc. 

They recommended making a feature request for EMR, the AWS Forums is a good place to engage the service team directly and get more timely answers and updates.
