### ISSUE TITLE
Unable to create a DevicePool using Device Farm SDK

### ISSUE THREAD

**Issue by bruno-abreu-sofist** [aws/aws-sdk-java#502]
When I try to create a DevicePool for a project, I'm getting an error from the SDK. I checked and I'm doing everything in the requested way. See the code snipet below:

 if(project.getName().equals("Blabla")) {
                    Rule r = new Rule().withAttribute(DeviceAttribute.ARN).withOperator(RuleOperator.EQUALS).withValue("arn:aws:devicefarm:us-west-2::device:986EF2BC62B04362BCA3D5A94344ADB2");
                    ArrayList<Rule> collection = new ArrayList<Rule>();
                    collection.add(r);

```
                client.createDevicePool(new CreateDevicePoolRequest().withName("WIC-Android2").withProjectArn(project.getArn()).withRules(collection));
```

}

The error message is: 
Error message: null (Service: AWSDeviceFarm; Status Code: 500; Error Code: InternalFailure; Request ID: c803a50e-51c4-11e5-ab89-8bc6a642ae6b)

**Comment by manikandanrs** [comment]
Thanks for reporting this. I am getting the same error and reported it to the service team. Will respond back as soon as I hear back from the service team.

**Comment by usultis** [comment]
I just stumbled upon the same issue. 
For me the server always returns status code 500 when attribute '**device**' is used with '**equals**' operation i.e.
new `
Rule()
.withAttribute(DeviceAttribute.ARN)
.withOperator(RuleOperator.EQUALS)
.withValue(device.getArn())) 
`

this always returns a HTTP 500 status code, 
but semantically same

`
new Rule()
.withAttribute(DeviceAttribute.ARN)
.withOperator(RuleOperator.IN)
.withValue("[\""+device.getArn()+"\"]"))
`

works without problems. 

I believe it has something to do with the way that the AWS web console works. There when creating a device pool with just one device a request is sent with operation 'IN' and a single-element array.

**Comment by manikandanrs** [comment]
You are right @usultis . We are working with the service team to get this issue fixed.
