### ISSUE TITLE
Unable to create a DevicePool using Device Farm SDK

### ISSUE THREAD

**Issue by bruno-abreu-sofist** [aws/aws-sdk-java#503]
When I try to create a DevicePool for a project, I'm getting an error from the SDK. I checked and I'm doing everything in the requested way. See the code snipet below:

 if(project.getName().equals("Blabla")) {
                    Rule r = new Rule().withAttribute(DeviceAttribute.ARN).withOperator(RuleOperator.EQUALS).withValue("arn:aws:devicefarm:us-west-2::device:986EF2BC62B04362BCA3D5A94344ADB2");
                    ArrayList<Rule> collection = new ArrayList<Rule>();
                    collection.add(r);

                    client.createDevicePool(new CreateDevicePoolRequest().withName("WIC-Android2").withProjectArn(project.getArn()).withRules(collection));
}

The error message is: 
Error message: null (Service: AWSDeviceFarm; Status Code: 500; Error Code: InternalFailure; Request ID: c803a50e-51c4-11e5-ab89-8bc6a642ae6b)

**Comment by manikandanrs** [comment]
Duplicate issue #502 . Closing this.
