### ISSUE TITLE
Cant get MD5 Checksum with AWSS3TransferUtility

### ISSUE THREAD

**Issue by samma89** [aws/aws-sdk-java#504]
I have used amazon v2 iOS latest api to upload videos to s3 BUCKET , i use there latest class called 
AWSS3TransferUtility

https://mobile.awsblog.com/post/Tx283AGGIL76PKP/Amazon-S3-Transfer-Utility-for-iOS

i managed upload videos successfully , but now i cant get the checksum of the uploaded file 

                     AWSS3 *s3 = [AWSS3 S3ForKey:@"uploadingS3"];
                    
                    AWSS3HeadObjectRequest *headObjectRequest = [AWSS3HeadObjectRequest new];
                    headObjectRequest.bucket = [Utill getBucketName];
                    headObjectRequest.key =footage.videoFileName;
                    
                    AWSTask *awsTask = [s3 headObject:headObjectRequest];
                    AWSS3HeadObjectOutput *headObjectOutput = awsTask.result;
                    
                    NSLog(@"headObjectOutput.ETag %@",headObjectOutput.ETag);

in here etag returns as null 

any particular reason that this doesnt work

**Comment by manikandanrs** [comment]
Since this is iOS SDK related, you will need to submit a issue to the below Github repo

https://github.com/aws/aws-sdk-ios

Closing this. Feel free to open if you face any issues with AWS SDK for Java
