### ISSUE TITLE
Make AmazonS3Client.headBucket public

### ISSUE THREAD

**Issue by wujek-srujek** [aws/aws-sdk-java#511]
I would like to validate if the bucket id and its credentials are correct when the application starts. Sadly, the AmazonS3Client.headBucket method is protected, but it seems perfect for my needs, tested it.
Reasoning: I have a Spring application on Cloud Foundry, and use PostgreSQL and S3. When the application is booted up, if the database doesn't work, I get a fail-fast error. For S3, the error only manifests itself upon a request, which might happen well after the application starts.
Another option would be to provide a different, explicit method for this.
Of course, I can just subclass the AmazonS3Client class and call the method somewhere in the constructor etc. but it is still calling non-public APIs, and dirty.
What do you think?

**Comment by shorea** [comment]
@wujek-srujek I don't see any issue with exposing this method publicly. It's part of the S3 API and thus should be exposed in the client. I will make this change.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html

**Comment by shorea** [comment]
Sorry for the delay. This has been staged for our next release, tentatively scheduled for next Thursday.

**Comment by wujek-srujek** [comment]
Hi. I've just integrated the 1.10.27 release and the method is there and seems to be working fine. Thank you, also for the fast feedback. As far as I'm concerned, this could be closed.

**Comment by shorea** [comment]
My pleasure!
