### ISSUE TITLE
Wrong pattern for RFC 822 date (com.amazonaws.util.DateUtils)

### ISSUE THREAD

**Issue by jenshadlich** [aws/aws-sdk-java#514]
The current pattern `EEE, dd MMM yyyy HH:mm:ss z` (rfc822DateFormat) can produce outputs like `Mon, 21 Sep 2015 20:13:49 +00:00` but the **colon is not valid** with RFC 822.

As the time zone seems to be fixed to GMT anyway, it would be better to change the pattern to statically produce the GMT string like this:

```
DateTimeFormatter rfc822DateFormat =
        DateTimeFormat.forPattern("EEE, dd MMM yyyy HH:mm:ss 'GMT'") // instead of z
                .withLocale(Locale.US)
                .withZone(new FixedDateTimeZone("GMT", "GMT", 0, 0));
```

**Comment by jenshadlich** [comment]
See https://github.com/jenshadlich/aws-sdk-java/commit/d300a0a89988c86686d4c28ff3b63aacc25a2124 for the fix.

**Comment by ramonmaruko** [comment]
I was also having this problem and found out that I was using joda 2.7 in my sbt build file.

Here are the differences between the outputs of their formatter using the same pattern:

2.7:
```scala
scala> val rfc822DateFormat: DateTimeFormatter = DateTimeFormat.forPattern("EEE, dd MMM yyyy HH:mm:ss z").withLocale(Locale.US).withZone(GMT)
scala> rfc822DateFormat.print(new Instant)
res0: String = Wed, 23 Sep 2015 04:24:27 +00:00
```

2.8:
```scala
scala> val rfc822DateFormat: DateTimeFormatter = DateTimeFormat.forPattern("EEE, dd MMM yyyy HH:mm:ss z").withLocale(Locale.US).withZone(GMT)
scala> rfc822DateFormat.print(new Instant)
res6: String = Wed, 23 Sep 2015 04:20:22 GMT
```

**Comment by jenshadlich** [comment]
I also had joda-time:joda-time:jar:2.7 which I got through maven managing my project dependencies. Even though one could argue to use 2.8, it's annoying and error-prone for users of the sdk. So I still opt for using the fixed string "GMT".

**Comment by shorea** [comment]
Hey @jenshadlich, thanks for the recommendation. This patch looks very interesting to us, our customers have continued to experience problems with this and it would be nice to fix this with code rather then through updating our dependencies. I've reached out to the maintainers of JodaTime to see if they have any advice on the patch. I'll update this issue when I hear back from them.

https://github.com/JodaOrg/joda-time/issues/288

**Comment by jodastephen** [comment]
This approach should work fine, subject to your usual testing.

**Comment by shorea** [comment]
Thanks @jodastephen!

@jenshadlich we greatly appreciate this patch, this will be super helpful for our customers. If you'd like to submit it as a pull request and confirm you are contributing under the Apache 2.0 license we can get you proper credit for this contribution!

**Comment by jenshadlich** [comment]
@shorea very good :) thanks for accepting my contribution. I already created a pull request:
https://github.com/aws/aws-sdk-java/pull/515 and I'm willing to contribute under Apache 2.0 licence
Anything else I need to do?

**Comment by shorea** [comment]
Awesome, that's all we need. Thanks again for the contribution! We've got a release planned for today so I'll merge this to master after that and get it staged for the next release.

**Comment by jenshadlich** [comment]
My pleasure :smile:

**Comment by shorea** [comment]
This has been merged. Thanks again for the contribution!
