### ISSUE TITLE
Normalize tags

### ISSUE THREAD

**Issue by amedeiros** [aws/aws-sdk-java#516]
We noticed that there is a difference between the tag objects we get back from EC2 versus S3. It looks like in EC2 your returning `List<Tag>` which is what we are looking for when it comes to all tags, and what we are use to coming from the ruby sdk.

 However, S3 looks like its returning `List<Map<String, String>>` for its tagSet. It would be easier to normalize any tags to just one type because right now we are actually forced to manually take `List<Map<String, String>>` and convert it into `List<Tag>`

Is there a particular reason to why tags don't use the same type across all clients?

**Comment by shorea** [comment]
I'm not 100% sure about the history here but I suspect S3 and EC2 have legacy tagging solutions before tagging resources was standardized across AWS. We have a handwritten S3 client and for some reason choose to represent the TagSet as a map tag key->tag value rather then a list of Tag objects having a key and value. For backwards compatibility reasons we can't change this in the near future.

As for using the same type across clients, that's something we've discussed and yes I agree it would be useful. We are still in the process of refining our roadmap for next year so I don't know if this feature will make the cut.
