### ISSUE TITLE
AWS EC2 clock skew error detection problem

### ISSUE THREAD

**Issue by devain** [aws/aws-sdk-java#519]
I changed my system time then call AWS EC2 API and it returns "AuthFailure" instead of "RequestTimeTooSkewed" (or something similar) 
-> Cannot detect Clock Skew error (RetryUtils.isClockSkewError) -> Fail to retry

Note: It works ok when my system time is correct.

**Comment by shorea** [comment]
Reached out to the EC2 team to see if they can return a more specific exception that gives us an indication that a clock skew error occurred.

**Comment by devain** [comment]
Could you at least update RetryUtils.isClockSkewError to use the same error codes as aws-sdk-net?

private static HashSet<string> clockSkewErrorCodes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "RequestTimeTooSkewed",
            "RequestExpired",
            "InvalidSignatureException",
            "SignatureDoesNotMatch",
            "AuthFailure",
            "RequestExpired",
            "RequestInTheFuture",
        };

https://github.com/aws/aws-sdk-net/blob/84afada7f15263600155fe314cad09f2802338bc/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryPolicy.cs

**Comment by shorea** [comment]
That's most likely what we will end up doing. We wanted to check with the service team if it would be possible to return a more specific exception as AuthFailure can be many things and retrying with an adjusted clock may not help.

**Comment by devain** [comment]
Yes, I think so. "RequestTimeTooSkewed" error code would be better. Anyway, hope to see the fix soon.
Thanks

**Comment by devain** [comment]
Hi shorea, 
Any updates for this issue? We really need it.

**Comment by shorea** [comment]
Sorry for the delay. Service team isn't likely to get around to this by the end of the year so for now we are going with including AuthFailure as a retryable clock skew error and adding an extra check to make sure the clock skew exceeds a certain threshold before retrying (to avoid retrying for other types of AuthFailure). This change is in code review now and looking to get pushed out in the next release.

**Comment by devain** [comment]
Ok. Thanks

**Comment by shorea** [comment]
This has been staged for our next release tentatively scheduled for tomorrow.

**Comment by devain** [comment]
Fixed in build 1.10.28
