### ISSUE TITLE
How to push `Map` type attribute to dynamodb table with map schema?

### ISSUE THREAD

**Issue by dieend** [aws/aws-sdk-java#520]
This might be related to #331, but I can't find way for my own case.

Suppose I have this POJO class:
```java
@DynamoDBTable
class Item {
    @DynamoDBHashKey
    private String id;
    @DynamoDBAttribute(attributeName="attr")
    private Map<String, String> attributes;
}
```
How to save it correctly using `DynamoDBMapper`?
I've tried to explicitly config dynamo db using `ConversionSchemas.V2` to no avail.
```java
DynamoDBMapper mapper = new DynamoDBMapper(dynamodb, new DynamoDBMapperConfig(ConversionSchemas.V2));
```

I'm using `aws-java-sdk-dynamodb` with `aws-java-sdk-bom` version 1.10.18.

**Comment by fernomac** [comment]
Hm, that should work just fine with either `ConversionSchemas.V2` or the default `ConversionSchemas.V2_COMPATIBLE`. What problem are you seeing?

**Comment by dieend** [comment]
When I did `mapper.save(model)`, I expect in dynamodb have `attr` column. But I'm not seeing it. Ah, is it possible because of I am using dynamodb local? Let me test it in aws dynamodb first.

**Comment by manikandanrs** [comment]
Any updates on this ?

**Comment by dieend** [comment]
Yes, there is no problem, it's my side error where I set up the test
wrongly. You can close this issue. Thanks.

--
Adinata

Typed in mobile, expect typi and auto corrected error.

**Comment by manikandanrs** [comment]
Thanks for the update.

**Comment by mac10046** [comment]
I got the same problem and was stuck for hours - the mistake I had made was ... one of the test code was putting a blank string in the map - due to which it was breaking while reading the same map variable.
