### ISSUE TITLE
Region.isServiceSupported and Directory Service

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#521]
the Region.isServiceSupported is not working for Directory Service
for the supporting Regions it gives info log such as 

INFO: {ds, us-west-2} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'ds.us-west-2.amazonaws.com'.

and for the unsupported it gives timeout exception

SDK Version 1.10.17

**Comment by manikandanrs** [comment]
We depend on regions.xml to provide this information. Directory service was added to regions.xml as part of 1.10.21 release. Please upgrade to an SDK version greater than 1.10.21 or later
