### ISSUE TITLE
Image.getPlatform

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#522]
the Image.getPlatform return "window" value while the PlatformValues is "Window"
(small letter vs capital later)

SDK Version 1.10.17

**Comment by manikandanrs** [comment]
Thanks for reporting this. I have opened up an issue with the service team. Will update once I hear back from them.

**Comment by manikandanrs** [comment]
We have got the reply from the service team. The service team has fixed this in their model. 

The SDKs will be updated in the upcoming releases. I will update this issue when the SDKs are updated.
