### ISSUE TITLE
Instance.getPlatform

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#523]
the Instance.getPlatform return "window" value while the PlatformValues is "Window"
(small letter vs capital later)

SDK Version 1.10.17

**Comment by manikandanrs** [comment]
Thanks for reporting this. I have opened up an issue with the service team. Will update once I hear back from them.

**Comment by manikandanrs** [comment]
We have got the reply from the service team. The service team has fixed this in their model. 

The SDKs will be updated in the upcoming releases. I will update this issue when the SDKs are updated.

**Comment by bmagic39** [comment]
I just checked at the latest release. this issue still not resolved

**Comment by zhangzhx** [comment]
Same problem with https://github.com/aws/aws-sdk-java/issues/522. Looks like the value changed to "windows" although it's still starting with a smaller case 'w'. This is not a SDK issue. If you still need the letter to be capital, you can go to [EC2's forum](https://forums.aws.amazon.com/forum.jspa?forumID=30) and ask them directly.
