### ISSUE TITLE
SDK not honoring https.proxyHost and https.proxyPort from Java

### ISSUE THREAD

**Issue by jfisbein** [aws/aws-sdk-java#524]
Even when launching applications that use aws-sdk with 
`-Dhttps.proxyHost=1.2.3.4 -Dhttps.proxyPort=3128` [command line options](http://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html), all https calls are not using the proxy as they should.

**Comment by manikandanrs** [comment]
Currently SDK supports configuring proxy settings via [ClientConfiguration#setProxyPort] (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setProxyPort(int)) and [ClientConfiguration#setProxyHost] (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setProxyHost(java.lang.String)).

We will discuss this internally and let you know if this can be considered as a feature request.

**Comment by manikandanrs** [comment]
An update here. The team agreed that it is nice to have feature on the Java SDK. I am turning this issue into feature request. 

The SDK will always take into consideration the proxy settings in ClientConfiguration and will only check the https.proxyHost and https.proxyPort only if the proxy settings are not set in ClientConfiguration. 

Note: We accepts pull requests from our customers. If you wish to contribute one for this feature, feel free to do so and we would be happy to take a look at it and merge.

**Comment by bobby** [comment]
@manikandanrs I've added a PR which addresses this issue, and I'd love your thoughts on how to incorporated it into a future release.

**Comment by manikandanrs** [comment]
@bobby 

Thanks for the contribution. I will take a look at your PR.

**Comment by manikandanrs** [comment]
This is fixed as part of #596

**Comment by SushmitaGoswami** [comment]
Is there any alternatives to ClientConfiguration#setProxyPort and ClientConfiguration#setProxyHost in aws java sdk 2.x? I was able to do this in aws sdk 1.x, but found no way to do this in aws java sdk 2.x

**Comment by debora-ito** [comment]
@SushmitaGoswami In SDK 2.x, proxy settings are defined using the [ProxyConfiguration](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/apache/ProxyConfiguration.html) in the `HttpClient` configuration, so it would be something like:

```java
SdkHttpClient httpClient = ApacheHttpClient.builder()
        .proxyConfiguration(
                ProxyConfiguration.builder()
                        .endpoint(URI.create("http://myproxy.com:1234"))
                        .username(username)
                        .password(password)
                        .build())
        .build();

SnsClient client = SnsClient.builder()
        .httpClient(httpClient)
        .region(region)
        .build();
```

Note that you specify the proxy host and port in the endpoint.
