### ISSUE TITLE
S3UploadPolicy error in code or in docs

### ISSUE THREAD

**Issue by joantune** [aws/aws-sdk-java#529]
Hi fellas!

Your latest documentation for the S3Upload with a POST, that can be found here: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html , talks about signing the upload policy with "AWS4-HMAC-SHA256" however, in the code ```com.amazonaws.services.ec2.util.S3UploadPolicy``` you clearly use ```private static final String HMAC_SHA1_ALGORITHM = "HmacSHA1";```

Either the docs or the code is wrong. I haven't tested your SDK's signature at the same time that I report a "AWS4-HMAC-SHA256" but meanwhile I should do it. I'll let you guys know of the results here.

Another thing is:
Your constructor, by default, does not allow Exact match on the key, only the starts with.

I might, based on your class, implement something, if I do that, I'll post it or PR it.

**Comment by zhangzhx** [comment]
The signing algorithm could be any implementation of Hmac. The two cases you provided are using AWS4-HMAC-SHA256 and HmacSHA1, respectively. Both cases are corrected but AWS4-HMAC-SHA256 is preferred.

Feel free to send us a PR for your implementation. We would love to take a look.

**Comment by varunnvs92** [comment]
Closing old issues. Feel free to reopen if you still have the issue. Thanks!!
