### ISSUE TITLE
Inconsistency: Role class from identitymanagement package with correlation with other packages

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#531]
at com.amazonaws.services.ec2.model.IamInstanceProfile you can get Id or Arn for the role/instance-profile 
but if you want to load the Role independently using com.amazonaws.services.identitymanagement.AmazonIdentityManagement.getRole, using the GetRoleResult. you don't have the option to filter the role by Id
the GetRoleResult has only Role Name option

Thus, Role can't be loaded by Id or Arn even other classes uses Id or Arn

**Comment by manikandanrs** [comment]
This seems to be a feature request to IAM. Can you please open this request at the below IAM forum

https://forums.aws.amazon.com/forum.jspa?forumID=76
