### ISSUE TITLE
DynamoDBMarshaller cannot custom marshal sets because of hardcoded marshal string.

### ISSUE THREAD

**Issue by sretsnom** [aws/aws-sdk-java#532]
DyanmoDBMarshaller has a hardcoded string marshall(T). There should be a DynamoDBSetMarshaller to handle cases where SS is required.

**Comment by shorea** [comment]
This is now possible with DynamoDBTypeConverted and DynamoDBTypeConverter

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBTypeConverted.html

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBTypeConverter.html
