### ISSUE TITLE
Allow support to enable/disable HTTP/1.1 handshake for PUT operations

### ISSUE THREAD

**Issue by amatety10** [aws/aws-sdk-java#535]
Currently the AWS S3 SDK does not allow any way to disable handshake operation for the "Expect: 100-Continue" operation when it might make sense from a client perspective. In our use case, we uploads 100-300kb files and don't want to incur the roundtrip for a handshake but go straight for the upload and deal with the response. Looks like the PUT operation via the SDK always enforces the handshake assuming uploads size to always be large which is not true in our case. 

Can we enhance "ClientConfiguration" to allow us to set this value in the HTTPParams instead of forcing a one size fits all at the HttpMethod level?

Code in contention:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/HttpRequestFactory.java#L111

**Comment by zhangzhx** [comment]
Thanks for the request. It sounds like an interesting feature. I've added this to our backlog. I will update this issue once there's activity to report.

**Comment by amatety10** [comment]
Thanks for the update. I have provided a pull request to the same effect: https://github.com/aws/aws-sdk-java/pull/539

I have the code compiling and passing locally. For some reason, the CI build is failing. Please let me know if you can provide insights.

**Comment by zhangzhx** [comment]
The change looks fine to merge. I will run the internal test for the change. If they all passed, I will merge the change for you.
