### ISSUE TITLE
Workspaces at ServiceAbbreviations

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#540]
Worspakces service is missing from ServiceAbbreviations
so Region.isServiceSupported can't be used to check if Workspaces is enabled or not

**Comment by manikandanrs** [comment]
Which version of the SDK are you using ? I could see this information available in regions.xml in the latest version. Please upgrade to the latest version of SDK and let us know if the issue still persists.

**Comment by bmagic39** [comment]
the problem is not at regions.xml but at ServiceAbbreviations which is missing the enum

**Comment by manikandanrs** [comment]
I see now. We have fixed this and will be available as part of next release.
