### ISSUE TITLE
Elastic Based Storage List

### ISSUE THREAD

**Issue by waynetaylor** [aws/aws-sdk-java#541]
In Spring Tool Suite, when i got to EBS Storage. It returns a long list and IDE takes some time to resolve. The list returns all snapshots of the EBS, including those created much earlier than the EBS Volume ID.

Example volume, vol-ea260cad created on May 2nd 2015 has snapshots going back to 2008, snapshot ID: snap-d010f6b9

**Comment by shorea** [comment]
Can you provide more details on the issue you're experiencing. A code sample would be ideal if you're able to provide it.

**Comment by waynetaylor** [comment]
Hi Shorea, this is actually in the AWS Toolkit Plugin for Eclipse vs actual code I have.

If i go to Eclipse -> AWS Toolkit -> Show View -> EC2 Elastic Based Storage

![image](https://cloud.githubusercontent.com/assets/2912112/10561001/0e10b8b8-74e2-11e5-92c6-cc0e636f771b.png)

**Comment by shorea** [comment]
Oh I see. Can you create an issue at https://github.com/aws/aws-toolkit-eclipse with some details on how you would like it to behave.

**Comment by waynetaylor** [comment]
Rasied as https://github.com/aws/aws-toolkit-eclipse/issues/28
