### ISSUE TITLE
AWSKMS.listKeys

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#542]
Can't load KMS key using key Id at AWSMKS.listKeys(request), since ListKeysRequest don't have withKeyId() method

**Comment by manikandanrs** [comment]
As per the API documentation [here](http://docs.aws.amazon.com/kms/latest/APIReference/API_ListKeys.html), ListKeys currently doesn't support accepting KeyId parameter.

This is a feature request to the AWS KMS service team. Can you forward the request to AWS KMS forum 

https://forums.aws.amazon.com/forum.jspa?forumID=182&start=0
