### ISSUE TITLE
Enum support for Java SDK

### ISSUE THREAD

**Issue by sivasubr** [aws/aws-sdk-java#544]
Support for enum data types in the java sdk. Recently it was supported for the .NET sdk (https://blogs.aws.amazon.com/net/post/Tx1CJYBVAKM1L75/DynamoDB-DataModel-Enum-Support)
It would be great to have this for the java sdk as opposed to having a custom marshaller for enum and annotating individual class fields with it

**Comment by shorea** [comment]
.NET is more flexible when dealing with enum values (which are integral types in .NET) that are unknown. In Java there is not clear way to deal with an unknown enum type during unmarshalling.

**Comment by sivasubr** [comment]
when we unmarshall, the valueOf() can be used to retrieve the correct value. In case that enum value is unknown/bad, a null can be returned or an exception can be thrown. Is there some other problem while unmarshalling?

**Comment by shorea** [comment]
I don't think we can make the correct decision that will work for everyone. Setting to null could cause data loss if you are roundtripping the record (read/modify/write scenario), throwing an exception could become an availability concern if a new enum is added and deployed incrementally across a fleet.

**Comment by sivasubr** [comment]
okay in that case, is the only way to do this is by using custom marshaller classes and annotating them on the class fields or is there any other way to define and use a custom marshaller over the entire model class which handles marshalling/unmarshalling of supported data types the standard way plus the support for enums?

**Comment by sivasubr** [comment]
or in other words, add a custom marshaller that handles enums to the standard set of marshallers used and have the mapper use this?

**Comment by shorea** [comment]
Sorry for the delay in response. You should be able to do this with a custom conversion schema. Assuming you are using the default conversion schema V2_COMPATIBLE (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/ConversionSchemas.java#L139) then you can extend the V2CompatibleMarshallerSet and StandardUnmarshallerSet to include your custom enum marshaller/unmarshaller.

**Comment by sivasubr** [comment]
Thanks for the response. All these classes are package-private (StandardConversionSchema, V2CompatibleMarshallerSet StandardUnmarshallerSet) and not publicly exposed. Is there any way to extend them without re-defining these classes?
