### ISSUE TITLE
S3ObjectInputStream taking more than 8 sec

### ISSUE THREAD

**Issue by jain-aanchal** [aws/aws-sdk-java#550]
Hi, 
I am using 
aws-java-sdk 1.10.30, jersey 1.17.1 and jetty version 9.1.4.v20140401.
This is how i am creating client.
                AmazonS3Client client = new AmazonS3EncryptionClient(credsProvider,
                        encryptionProvider, clientConfiguration, cryptoConfiguration);
                client.setEndpoint(region);
This is how I am getting the data.
S3Object object = client.getObject(dataBucketName, userKey);
S3ObjectInputStream inputstream = object.getObjectContent();

 and then I am sending the input stream to the client directly. 
This implementation used to work with 1.6.8, but now it is taking more than *8 sec* between when I get the input stream and when client gets it. I am not sure what going wrong. I could have gone back to 1.6.8 but I don't want to as it is a very old version. 

Help is appreciated. 

-Aanchal

**Comment by manikandanrs** [comment]
Do you mean it takes 8 seconds between the below lines ?

S3Object object = client.getObject(dataBucketName, userKey);
S3ObjectInputStream inputstream = object.getObjectContent(); 

We need to check how much time it takes to execute the request. You can enable client side metrics look at cloud watch to see where most of the time is spent while executing the request. 

Information from the metrics would be helpful in tracking the issue.

https://java.awsblog.com/post/Tx3C0RV4NRRBKTG/Enabling-Metrics-with-the-AWS-SDK-for-Java

**Comment by jain-aanchal** [comment]
sorry I was not clear

S3Object object = client.getObject(dataBucketName, userKey);
S3ObjectInputStream inputstream = object.getObjectContent();
byte[] data = IOUtils.toByteArray(inputStream);

So the step where I am getting data from inputstream 
byte[] data = IOUtils.toByteArray(inputStream);
is taking 7.5 min.

**Comment by manikandanrs** [comment]
What is the size of the object that you are trying to download ?

Did you get a chance to enable client side metrics ? The blog post in my previous comment tells you how to use cloud watch to view the metrics. Can you let us know what is the download throughput that you see in cloud watch. The blog post has an example for this use case.

**Comment by manikandanrs** [comment]
Any updates on this ?

**Comment by manikandanrs** [comment]
Closing this issue as we have not heard back. Feel free to open.
