### ISSUE TITLE
cn-north-1 could not use beanstalk

### ISSUE THREAD

**Issue by elbertwang** [aws/aws-sdk-java#553]
![screen shot 2015-11-13 at 8 52 17 am](https://cloud.githubusercontent.com/assets/557793/11135826/dd485ae4-89e3-11e5-87a7-c2b5444c434f.png)

Now we have Elasticbeanstalk service in cn-north-1, but the console could not connect.

I guess we have wrong elasticbeanstalk endpoint for cn-north-1

**Comment by manikandanrs** [comment]
Thanks for reporting this. Looking into it.

**Comment by manikandanrs** [comment]
We have updated the region metadata for eclipse tool kit. This should be fixed now.

Feel free to re open if you still see any issues.
