### ISSUE TITLE
com.amazonaws.services.s3.model.Bucket is not implementing Serializable 

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#554]
S3 Bucket class is not implementing Serializable as all other AWS classes
actually, the whole s3.model package classes are not implementing this interface

**Comment by zhangzhx** [comment]
Do you have any specific reason for implementing Serializable for S3 Bucket class and all other classes in s3.model package?

**Comment by bmagic39** [comment]
In my application, there is a use case where I need to save state of (including the services data) my cloud (account). Currently this is implemented by serializing AWS objects into files. Later we load those objects from the files and compare it to the current state.
It work for all AWS objects, but once we included S3Buckets in our application we faced this issue

**Comment by zhangzhx** [comment]
I see. So it's for persistence use. I've added this issue into our backlog and will update this issue once releasing this fix.

**Comment by zhangzhx** [comment]
We have released the fix, so close this issue now. Feel free to reopen it if you have other questions.
