### ISSUE TITLE
Remove SSL Security issue: sun.security.ssl.allowLegacyHelloMessages

### ISSUE THREAD

**Issue by mslinn** [aws/aws-sdk-java#556]
S3 requires` sun.security.ssl.allowLegacyHelloMessages` to be set `true`. To see this in action, try running any program that accesses S3 using aws-sdk-java with the following Java system property: 

    -Dsun.security.ssl.allowLegacyHelloMessages=false

See [this](http://www.oracle.com/technetwork/java/javase/overview/tlsreadme2-176330.html) and [this](https://bugs.openjdk.java.net/browse/JDK-8139586).
Any plans to fix this security problem?

**Comment by shorea** [comment]
Can you provide some more details on your environment? This shouldn't be needed for the S3 client to function.

SDK Version
Java Version
OS
APIs used
Exception seen if this property is not enabled

**Comment by mslinn** [comment]
I think I may not have made myself understood. The Oracle recommended value (`false`) is not the Java default value (`true`). However, `aws-sdk-java` throws a fatal error if this property is set `false`.

**Comment by shorea** [comment]
Can you provide the exception it's throwing? I'm not able to reproduce.

**Comment by mslinn** [comment]
Sorry, should have mentioned that the exception happens when a CloudFront distribution (backed by an S3 bucket, in my case) is configured with wildcard SSL certificate in order to support a CNAME alias. Here is the exception:

    [info] c.a.h.AmazonHttpClient - Unable to execute HTTP request: Failed to negotiate the use of secure renegotiation
    javax.net.ssl.SSLHandshakeException: Failed to negotiate the use of secure renegotiation
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_66]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[na:1.8.0_66]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_66]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:292) ~[na:1.8.0_66]
	at sun.security.ssl.ClientHandshaker.serverHello(ClientHandshaker.java:504) ~[na:1.8.0_66]

Here are the SSL-related Java system properties I used:

````
-Djdk.tls.rejectClientInitiatedRenegotiation=true \
-Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" \
-Dsun.security.ssl.allowUnsafeRenegotiation=false \
-Djdk.tls.ephemeralDHKeySize=2048 \
-Dsun.security.ssl.allowLegacyHelloMessages=false \
-Djdk.tls.rejectClientInitializedRenego=true \
-Dcom.amazonaws.sdk.disableCertChecking=false
````

**Comment by shorea** [comment]
The com.amazonaws.sdk.disableCertChecking property doesn't respect the value false. Any value set for this property will disable certificate checking. This is enabled by default so if you don't specify you'll get the desired behavior. This doesn't seem related to the problem you are having but could you try running your app with this property removed. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/HttpClientFactory.java#L146

After that do you mind enabling -Djavax.net.debug=all and providing the client and server hello's for the initial handshake and the renogtation?

**Comment by mslinn** [comment]
The property under discussion is `sun.security.ssl.allowLegacyHelloMessages`, not `com.amazonaws.sdk.disableCertChecking`. I'll follow up with the output you asked for tomorrow.

**Comment by shorea** [comment]
Just pointing out that com.amazonaws.sdk.disableCertChecking=false isn't doing what you are intending.

**Comment by mslinn** [comment]
You identified the actual issue. Thanks!

Are the docs clear on this, I wonder? I don't recall reading about the behavior you (accurately) described.

**Comment by shorea** [comment]
It does seem counter intuitive now that you mention it. It seems to be intended to use as a flag -Dcom.amazonaww.sdk.disableCertChecking rather then as a typical property with a value. I'll make the documentation more clear and I think it's safe to explicitly check for false as this can be a dangerous property to misinterpret. Thanks for reporting!

**Comment by shorea** [comment]
FYI the documentation has been improved and we are no treating false as enabling cert checking. These changes will go out in our next release.

**Comment by mslinn** [comment]
(y)
