### ISSUE TITLE
Documentation: redrivepolicy missing from CreateQueueRequest

### ISSUE THREAD

**Issue by mdaley** [aws/aws-sdk-java#557]
Hello, on this page of the docs:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/model/CreateQueueRequest.html

it lists, in setAttributes and a few other places, the attributes that can be set when creating a queue.  However, there is no mention of RedrivePolicy.

When I set the attribute RedrivePolicy with a value that is valid json, like this: `{"maxReceiveCount":5,"deadLetterTargetArn":"a queue arn"}, then it does work.

Does the documentation need to be updated to reflect this?

**Comment by shorea** [comment]
It's mentioned in https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/model/QueueAttributeName.java. Is that what your looking for?

**Comment by mdaley** [comment]
Yes, that is very useful confirmation but it doesn't cover that fact that the methods setAttributes, withAttributes for CreateQueueRequest only mention some of the attributes that are allowed.  Perhaps the CreateQueueRequest documentation should refer to the documentation for QueueAttribute Name?

**Comment by shorea** [comment]
Oh gotcha. I'll follow up with the service team to update the documentation. Linking to the enum sounds interesting, we'd have to make a customization in our code generator to do this but sounds like it would be valuable.

**Comment by mdaley** [comment]
Glad I said something useful.  Cheers :-)

**Comment by shorea** [comment]
Had to reopen an issue with the service team as the documentation for CreateQueue still doesn't look quite right. Will update this ticket when I hear back.

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html

**Comment by shorea** [comment]
This has been resolved server side. We'll pull in the updated documentation in our next release.

**Comment by mdaley** [comment]
Just looked at the docs and it looks nice to me.  Thanks for sorting this out!
