### ISSUE TITLE
Failed batches are lost when `DynamodbMapper.batchWrite` is interrupted. 

### ISSUE THREAD

**Issue by conleym** [aws/aws-sdk-java#562]
Looking at [batchWrite](https://github.com/aws/aws-sdk-java/blob/b703aac75330b31d42c1b3b93cd49c60a71292fa/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.java#L1638-L1646), I see that it can throw an `AmazonClientException` if the thread is interrupted while sleeping. There are several issues here:

1. This is not documented (the mapper lacks documentation about thrown exceptions in general).
2. If this exception is thrown, the list of failed batches is lost forever.

There should be a way to get the failed batches even if an exception is thrown here (or perhaps an exception should _not_ be thrown), and the exceptions thrown by the various mapper methods should be documented.

**Comment by zhangzhx** [comment]
Thanks for the feedback, we will add this to our backlog.

**Comment by shorea** [comment]
A fix for this will be included in our next release tentatively scheduled for tomorrow.
