### ISSUE TITLE
AWS_DEFAULT_REGION environment variable not handled

### ISSUE THREAD

**Issue by mfischer-zd** [aws/aws-sdk-java#563]
The `AWS_DEFAULT_REGION` environment variable is not read from as with the CLI if the user doesn't specify the client endpoint.

**Comment by manikandanrs** [comment]
Thanks for the feature request. We will get this added to our backlog.

**Comment by twothirdscyft** [comment]
+1

Would make consistent with other tools and allow configuration based on EC2 instance instead of having to setup additional configuration to set this in our code.

**Comment by shorea** [comment]
This is now possible via the new client builders. Note that we use AWS_REGION not AWS_DEFAULT_REGION.

https://java.awsblog.com/post/Tx3QE4T4596T5G4/Fluent-Client-Builders
