### ISSUE TITLE
Feature request - Use Iterable<T> instead of List<T> on DynamoDBMapper.batch*() methods

### ISSUE THREAD

**Issue by tfeak** [aws/aws-sdk-java#566]
This may apply for other classes, but it came up most recently for me when working with the DynamoDBMapper.

I'm working with a List<FooDao> and want to filter them to determine which ones need to be deleted via DynamoDBMapper.batchDelete(). I could leverage Java's inherent Collections2.filter() method, which works with Collections instead of Lists. Or I can use Guava's Iterables.filter(), which works with Iterables instead of Lists. In both cases, I end up having to create temporary/wrapper List after filtering in order to make a call to DynamoDBMapper.batchDelete().

Digging into the current implementation of batchDelete(), the usage of the Lists themselves boils down to simply iterating through them with a for each loop.

Changing the public API here to take implementations of Iterable would seem to make it more flexible without requiring any major code surgery. I'm pretty sure it would be backwards compatible too, as List implements Iterable.

Please consider modifying the public API on this class.

**Comment by shorea** [comment]
While it does appear to be source backwards compatible it looks like it's not binary compatible. We are planning a major version bump in the near future (within a couple of months) and this looks like a good candidate to include in it. 

If you'd like to submit a pull request for this change we will consider it for our next major version. I'll add it to the proposed features for 1.11.

**Comment by fernomac** [comment]
Widening the parameter type does indeed break binary compatibility. You can, however, safely add *new* overloads that take Iterables, and wait to drop the existing overloads that take lists until you're ready to break binary compatibility.

**Comment by shorea** [comment]
+1 David. Great idea!

**Comment by shorea** [comment]
This is been implemented and is tentatively scheduled for release later today.

**Comment by shorea** [comment]
This has been released.
