### ISSUE TITLE
How to contribute to aws-sdk-java project? 

### ISSUE THREAD

**Issue by mfarid** [aws/aws-sdk-java#569]
Hi there

I take this opportunity to introduce myself as a Software Architect from Open Source Unit tests development Team of DevFactory. Our team is working on writing unit tests for different open source projects. 

As I could not find any resource that could help me in knowing how to contribute to aws-sdk-java.  I am using this issue tracker to put my query. 

Secondly, I would like to confirm if our changes for unit tests would be  considered.

A quick response will be highly appreciated.

Thank you
Farid

**Comment by manikandanrs** [comment]
Hi @mfarid 

Thanks for reaching out to us. Glad to hear you want to contribute to this library.

Contributions are accepted via pull requests to this github repository. We accept requests if you are fine with it submitting under Apache 2.0 license.

A point to note : Client code for all AWS services are code generated from the service API model. We are working on open sourcing our code generators. Our core model aws-java-sdk-core and high level libraries like S3's transfer manager, dynamo db document api, dynamo db mapper, sqs async buffer client are handwritten. We do have some fair amount of unit tests for our core library and integration tests for services. Our unit tests are already open sourced while we are working on exposing our integration tests.

Let us know if you have any further questions and we will be happy to clarify it for you.

**Comment by kennethjor** [comment]
@manikandanrs Do you have any timeline for open sourcing the code generators used for this library?

**Comment by manikandanrs** [comment]
@kennethjor  

Most of the client side code is migrated to new code generators. Only a few more left. We are actively working on moving the rest of the services to use the new code generator. I don't have a timeline yet for this. But you should see the code generators open sourced early next year.

**Comment by mfarid** [comment]
@manikandanrs Thanks a lot for your quick reply. 

I went through many modules but all of them seem to be generated just as you mentioned. I would appreciate if you can point me to 3-4 modules which I can start with to increase unit tests. 

Thanks and regards

**Comment by shorea** [comment]
The core module is handwritten and would make sense to unit test. Are you looking to add a specific feature to the SDK?

**Comment by mfarid** [comment]
I am looking forward to increase the unit test coverage by writing unit tests for missing branches/line. Thanks for sharing that core module can be a candidate in this regards.

**Comment by manikandanrs** [comment]
Resolving this ticket. Feel free to open issues if you need help.
