### ISSUE TITLE
Using StorageClass.StandardInfrequentAccess causes s3.putObject() to hang

### ISSUE THREAD

**Issue by kriswest** [aws/aws-sdk-java#571]
The following code will hang and never return from s3.putObject() in 1.10.39:

```java
PutObjectRequest por = new PutObjectRequest(bucket, key, datafile);
if (forceAttachment){
    ObjectMetadata meta = new ObjectMetadata();
    meta.setContentDisposition("attachment");
    meta.setContentType("application/octet-stream");
    por.setMetadata(meta);
}
por.setStorageClass(StorageClass.StandardInfrequentAccess);
por.setCannedAcl(CannedAccessControlList.Private);
PutObjectResult result = s3.putObject(por);
```

Commenting out the line:
```java
por.setStorageClass(StorageClass.StandardInfrequentAccess);
```
stops it doing so but obviously disables use of the StandardInfrequentAccess storage class without a separate request to change the storage class. 

StorageClass.StandardInfrequentAccess was introduced in 1.10.19 I think - I'm currently building some past releases of the AWS java SDK to see if all revisions since then were affected.

**Comment by shorea** [comment]
I'm not able to reproduce this. Are you seeing this issue consistently? With all files or just certain types of files? Would it be possible to do a thread dump when it hangs?

**Comment by kriswest** [comment]
We've found a flaw in our build system that was packaging the build with an older copy of the AWS libs that didn't support StorageClass.StandardInfrequentAccess. This is almost certainly the cause of the problem so I'll close this issue while we retest and reopen it in (the (unlikely) event of a recurrence.
