### ISSUE TITLE
TransferManager.copy() doesn't fire TRANSFER_COMPLETED_EVENT for multipart copy requests

### ISSUE THREAD

**Issue by mkleint** [aws/aws-sdk-java#573]
We have a queue with upper bound of 1000 of Transfer instances and we attach ProgressListener to the copy request. In the listener we remove the item from blocking queue on TRANSFER_COMPLETED_EVENT, TRANSFER_CANCELED_EVENT or TRANSFER_FAILED_EVENT.

If we have more than 1000 copy requests for artifacts bigger than 5G, the queue gets blocked indefinitely because the TRANSFER_COMPLETED_EVENT event never arrives.

using version 1.10.14

**Comment by zhangzhx** [comment]
Hi @mkleint ,

Does this happen if you specify less than 1000 copy requests or the file size smaller than 5G? Could you give me more context when this unexpected behavior happen?

**Comment by mkleint** [comment]
I've reproduced the problem with 2 copy requests of size BIGGER than <whatever_the_multi_copy_size_limit> I believe, that's the crucial point. The ProgressListener events do come for single part copy, but not for multipart copy.

**Comment by kiiadi** [comment]
@mkleint apologies for the extended delay in responding. Are you still seeing this issue? I'm trying to reproduce it and can't seem to, I'm using TransferManager do to the copy - the following code-snippet gives me back the TRANSFER_COMLETED_EVENT

```java
AmazonS3 s3 = new AmazonS3Client();
TransferManager tm = TransferManagerBuilder.standard().withS3Client(s3).withMultipartCopyThreshold(50L * MB).withMultipartCopyPartSize(50L * MB).build();

Copy copy = tm.copy(SOURCE_BUCKET_NAME, LARGE_FILE, DESTINATION_BUCKET_NAME, LARGE_FILE);
copy.addProgressListener((ProgressListener)progressEvent -> System.out.println(String.format("Event: %s", progressEvent)));
copy.waitForCompletion();
```

Could you provide a snippet that demonstrates the problem so I can help investigate further?

**Comment by mkleint** [comment]
most likely not using the code anymore, let's close it. thanks.
