### ISSUE TITLE
Add List constructor to AWSCredentialsProviderChain

### ISSUE THREAD

**Issue by electrum** [aws/aws-sdk-java#574]
Having a constructor for `AWSCredentialsProviderChain` that takes a `List` would be helpful when the chain is computed dynamically. (sure, the caller can convert a list into an array, but that's messy)

**Comment by shorea** [comment]
Sounds good to me. Would you like to submit a pull request for this?

**Comment by shorea** [comment]
This has been staged internally and will be included in the next release.
