### ISSUE TITLE
AmazonKinesisApplicationSample on Android

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-sdk-java#577]
Will the example AmazonKinesisApplicationSample.java run on Android?
I need an alternative to use the AWS Android SDK, since it has too many dependencies (as described here  - http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/setup.html), so I'm finding a way to use the java sdk instead.

**Comment by manikandanrs** [comment]
Are you saying, you want to use the Android SDK and use this sample ?

**Comment by loretoparisi** [comment]
@manikandanrs yes exactly, there are too much dependencies in the Android SDK. Considering all of them you have to put it 6000+ methods, and you know Dalvik limit is 65K, and that's very a lot of methods, for a events producer feature. Of course, considering only the producer it's like 800 methods, but all dependencies are too much.

**Comment by manikandanrs** [comment]
From what I see in the android kinesis SDK the [AmazonKinesisClient] (https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-kinesis/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient.java) interface in java and android look same to me. So, you should be able to execute this sample using the android sdk.

**Comment by manikandanrs** [comment]
No response on this. Closing this for now. Feel free to re open if you still see issues.
