### ISSUE TITLE
S3 connector does not work with underscores in bucket names (IllegalArgumentException: Invalid S3 URI: no hostname)

### ISSUE THREAD

**Issue by fabianmeier** [aws/aws-sdk-java#579]
The getHost() in AmazonS3URI.java returns no hostname (null) for bucket names that contain underscores which leads to the following error message:

`java.lang.IllegalArgumentException: Invalid S3 URI: no hostname: s3://my_bucket/prefix123`

I used the following snippet to confirm my theory:

```java
class TestGetURI{
 	public static void main(String[] args) throws Exception {
 		java.net.URI uri = new java.net.URI("s3://mybucket");
		String host = uri.getHost();
		System.out.println("Host = [" + host + "].");

		uri = new java.net.URI("s3://my_bucket/");
		host = uri.getHost();
		System.out.println("Host = [" + host + "].");
	}
}
```

It returns:
> java TestGetHost
> Host = [mybucket].
> Host = [null].

Which confirms that the getHost() does not work for extracting the bucket name from a S3 URI if ith contains underscores.

**Comment by shorea** [comment]
Can you use http/https scheme with path style addressing rather then the s3 scheme. Non DENS-compatible buckets can no longer be created and are supported for backwards compatibility only.

**Comment by shorea** [comment]
@fabianmeier will the suggestion work for your use case?

**Comment by fabianmeier** [comment]
Indeed. Thank you @shorea !

Our current implementation was already using the http/s:// "path style" for the connection establishment but was fetching objects using the old fashioned s3:// manner.

Btw. underscores in the path segment of a URL are allowed as per several RFCs. Just not in the host name segment.
