### ISSUE TITLE
Is there a way to not use chunked uploading for java-sdk for signature V4? 

### ISSUE THREAD

**Issue by harshavardhana** [aws/aws-sdk-java#580]
```PUT /testbbucket/caddy HTTP/1.1 1 1 map[X-Amz-Content-Sha256:[STREAMING-AWS4-HMAC-SHA256-PAYLOAD] User-Agent:[aws-sdk-java/1.10.41 Mac_OS_X/10.11.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.25-b02/1.8.0_25] Content-Type:[application/octet-stream] Content-Length:[12241473] Connection:[Keep-Alive] X-Amz-Date:[20151218T164446Z] X-Amz-Decoded-Content-Length:[12232928] Content-Md5:[4uUkMUjnvb+ymFcDSeexUA==] Authorization:[AWS4-HMAC-SHA256 Credential=WLGDGYAQYIGI833EV05A/20151218/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=6575c62db878f4151357f54b4e7a5c19555afb1a9efc0573dce615850caaf646]] 0xc82017a140 12241473 [] false localhost:9000 map[] map[] <nil> map[] 127.0.0.1:50544 /testbbucket/caddy <nil> <nil>```

Following code makes it default - i couldn't find a way to override this, is there any? 

```java
/**
     * Determine whether to use aws-chunked for signing
     */
    private static boolean useChunkEncoding(SignableRequest<?> request) {
        // Whether to use chunked encoding for signing the request
        boolean chunkedEncodingEnabled = false;
        if (request.getOriginalRequestObject() instanceof PutObjectRequest
                || request.getOriginalRequestObject() instanceof UploadPartRequest) {
            chunkedEncodingEnabled = true;
        }
        return chunkedEncodingEnabled;
    }
```

The behavior is entirely different than how aws-sdk-go behaves which does calculate the sha256 during multipart and regular put operation.

**Comment by shorea** [comment]
The sample code in the referenced issue worked for me hitting S3. I see your setting the endpoint to localhost. Are you going through some kind of proxy?

**Comment by harshavardhana** [comment]
> The sample code in the referenced issue worked for me hitting S3. I see your setting the endpoint to localhost. Are you going through some kind of proxy?

S3 it will work since this is a supported style ``X-Amz-Content-Sha256:[STREAMING-AWS4-HMAC-SHA256-PAYLOAD]``  - this is generally to avoid calculating sha256 on the payload but the server i am using doesn't implement that. 

My question was is there a way to force payload calculation for putObject and uploadPart? i for one couldn't see a way to do it. 'aws-sdk-go' does payload calculation by default. 

Here is the sample code.

```java
public static void main(String[] args) throws IOException {
    AWSCredentials credentials = new BasicAWSCredentials("WLGDGYAQYIGI833EV05A",
                                                         "BYvgJM101sHngl2uzjXS/OBF/aMxAN06JrJ3qJlF");
    ClientConfiguration clientConfiguration = new ClientConfiguration();
    clientConfiguration.setSignerOverride("AWSS3V4SignerType");
    AmazonS3 s3Client = new AmazonS3Client(credentials, clientConfiguration);
    Region usEast1 = Region.getRegion(Regions.US_EAST_1);
    s3Client.setRegion(usEast1);
    s3Client.setEndpoint("http://localhost:9000");
    s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
    File file = new File("/Users/harsha/caddy");
    s3Client.putObject(new PutObjectRequest("testbbucket", file.getName(), file));
  }
```

It is not a proxy it is - https://github.com/minio/minio object storage which supports S3 signature version '4' implementation.

**Comment by shorea** [comment]
Ok gotcha. We don't have a mechanism today to do this. We could introduce a system property to turn off chunked encoding for all requests. If you'd like to submit a PR for that I can evaluate it. Otherwise I should have some time next week to look at this.

**Comment by harshavardhana** [comment]
> Ok gotcha. We don't have a mechanism today to do this. We could introduce a system property to turn off chunked encoding for all requests. If you'd like to submit a PR for that I can evaluate it. Otherwise I should have some time next week to look at this.

Oh nice! let me see - if i can get that done.  I would think `S3ClientOptions()` can have this option?

    s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));

**Comment by harshavardhana** [comment]
`` s3Client.setS3ClientOptions(new S3ClientOptions().disableChunkedUpload(true));``

**Comment by shorea** [comment]
+1 I like that more than a system property.
