### ISSUE TITLE
Issue in ReflectionUtils::resolveClass (line 151)

### ISSUE THREAD

**Issue by txu0393** [aws/aws-sdk-java#583]
I'm getting an exception with the message:
`Cannot resolve class for type T`
where T is a type parameter.

I am trying to call:
`DynamoDBMapper.scan(ProblemClass.class, new DynamoDBScanExpression())`
where
`public class ProblemClass extends AbstractClass<ASimpleDynamoDBDocumentClass>`
and AbstractClass is declared as following
`public abstract class AbstractClass<T extends ASimpleDynamoDBDocumentClass>`

Seems to me that the problem occurs when attempting to unmarshall the object from DynamoDB

**Comment by txu0393** [comment]
After poking around, i figured out the issue. I think the root of the problem comes from the issue explained in #582, but this is how to reproduce the problem and how to temporarily fix it.
If we have:
```
class AbstractClass<T> {
    protected List<T> genericList;

    public void setGenericList(List<T> genericList) {
        this.genericList = genericList;
    }
}
```
and
```
class NotAbstractClassA extends AbstractClass<SomeDynamoDBDocumentClass> {
}
```
The setter method WILL be detected because it sets a List, which is a supported DynamoDBMapper object type. However, an exception will be thrown because DynamoDBMapper will try to unmarshall the type "T" rather than "SomeDynamoDBDocumentClass". I was able to get around this by overriding the setter from the parent class, even though this shouldn't be necessary.
```
class NotAbstractClassA extends AbstractClass<SomeDynamoDBDocumentClass> {
    @Override
    public void setGenericList(List<SomeDynamoDBDocumentClass> genericList) {
        this.genericList = genericList;
    }
}
```

**Comment by zhangzhx** [comment]
It's a similar issue as https://github.com/aws/aws-sdk-java/issues/582. DynamoDB Mapper doesn't support generic type for now due to the limitation of Java reflection. As far as I know, even in runtime, Java reflection couldn't return the correct generic type. In this case, we never know the returned type for method getGenericList() is
```
java.util.List<SomeDynamoDBDocumentClass>
```
instead, it will return
```
java.util.List
```

**Comment by zhangzhx** [comment]
Do you have any more questions for this from us? Otherwise, I will close this issue.

**Comment by txu0393** [comment]
Nope, go ahead
