### ISSUE TITLE
Custom marshaller to marshall Objects into AttributeValue instead of String

### ISSUE THREAD

**Issue by txu0393** [aws/aws-sdk-java#585]
Right now the interface DynamoDBMarshaller<T> declares 2 methods:
`String marshall(T getterReturnResult);`
`T unmarshall(Class<T> clazz, String obj);`
that transform an object into a string and vice-versa.

Is it possible to have an interface like DynamoDBMarshallerV2<T> where these 2 methods are declared:
`AttributeValue marshall(T getterReturnResult);`
`T unmarshall(Class<T> clazz, AttributeValue obj);`
That way, we can maintain the correct structure of an item when marshalling it instead of having to convert it into a String.

On that note, can we support the type `AttributeValue` without explicitly having to define a custom marshaller for it?
For example:
```
@DynamoDBTable(...) 
class WhateverClass {
...
    @DynamoDBAttribute
    public AttributeValue getDynamicField() {
        ....
    }
...
}
```

This would add a lot of flexibility to the Java ORM.
Thanks!

**Comment by shorea** [comment]
Take a look at the new @DynamoDBTypeConverted annotation. I believe it may meet your needs.
