### ISSUE TITLE
DynamoDB xspec, S PathOperand does not have lt, le, gt or ge methods.

### ISSUE THREAD

**Issue by StefCeyssens** [aws/aws-sdk-java#592]
Class com.amazonaws.services.dynamodbv2.xspec.S does not have lt, le, gt or ge methods. Making it impossible to put that kind of conditions on a query or scan using xspec. 

However class com.amazonaws.services.dynamodbv2.model.Condition tells us that it is possible to do put this kind of conditions on a String field in DynamoDB:

<code>LT</code> : Less than.
<i>AttributeValueList</i> can contain only one
<i>AttributeValue</i> of <b>type String, Number, or Binary</b>

Is there a reason why this functionality is not included in com.amazonaws.services.dynamodbv2.xspec.S?

**Comment by manikandanrs** [comment]
Addressed in pull request #610
