### ISSUE TITLE
G2 8X Large is not supported in the enumerated instance types.

### ISSUE THREAD

**Issue by sono-bfio** [aws/aws-sdk-java#593]
Can this be added to: 
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/InstanceType.java

We are using some plugins that are leveraging the SDK and we are noticing it is not a supported option.

**Comment by shorea** [comment]
We will get this fixed next week. As a temporary workaround all EC2 APIs take a raw string for instance type so you can explicitly set it.

**Comment by shorea** [comment]
This will be added in the next release of the SDK.
