### ISSUE TITLE
AmazonS3Client.listObjects() in version 1.10.45 does not URL decode common prefixes

### ISSUE THREAD

**Issue by mdietz198** [aws/aws-sdk-java#600]
In version 1.10.45, the AmazonS3Client does not decode the common prefixes for a listObjects request.

Example:
```
// existing s3 objects:
// s3://my-bucket/reports/year=2015/report.tsv
// s3://my-bucket/reports/year=2016/report.tsv

final AmazonS3 s3 = new AmazonS3Client();
final ListObjectsRequest request = new ListObjectsRequest("my-bucket", "reports/", null, "/", null);
final ObjectListing r = s3.listObjects(request);
for (final String prefix : r.getCommonPrefixes()) {
  System.out.println(r.getCommonPrefixes());
}

// output in version 1.10.44:
// reports/year=2015
// reports/year=2016

// output in version 1.10.45:
// reports/year%3D2015
// reports/year%3D2016
```

**Comment by manikandanrs** [comment]
Yes. This is a bug. We will get this fixed.

**Comment by mdietz198** [comment]
Thank you for the quick response!

**Comment by manikandanrs** [comment]
I have fixed this and staged it for next release which is tentatively next week.

**Comment by bli88** [comment]
Is this fix deployed to the AWS S3 servers? We're using AWS SDK 3.1.3.9 for trying to list objects and then get objects by re-directing with prefix. But it seems the server is not re-directing to the destination bucket and subfolders.
