### ISSUE TITLE
Calling AmazonS3Client.doesBucketExist slows down call to listObjects

### ISSUE THREAD

**Issue by motocross510** [aws/aws-sdk-java#601]
Call to listObjects takes a long time if preceded by a call to doesBucketExist()

```
def s3 = new AmazonS3Client(new DefaultAWSCredentialsProviderChain());
if (s3.doesBucketExist(bucketName)) System.err.println("Bucket exists");
        
ListObjectsRequest req = new ListObjectsRequest();
req.setBucketName(bucketName);
req.setPrefix(prefix);
        
System.err.println("LISTING OBJECTS");
ObjectListing list = s3.listObjects(req);
System.err.println("DONE LISTING OBJECTS"); 
```

**Comment by manikandanrs** [comment]
I am not able to simulate the issue with the given code. When you say long time, can you give us more information about that. 

1. IS the server taking longer time to respond ?
2. Can you enable the wirelog and SDK metrics and see send us the output ?
3. From the code, I see that you are calling the US Standard endpoint ("s3.amazonaws.com"). Is this correct ?

Take a look at this blog post on how to enable metrics provide us the metrics data

**Comment by manikandanrs** [comment]
Closing the issue as there is no reply on this. Feel free to re open when you have more data.
