### ISSUE TITLE
LambdaInvokerFactory and @LambdaFunction do not support multiple environments

### ISSUE THREAD

**Issue by codan84** [aws/aws-sdk-java#602]
If I create an interface:
```
interface MyLambdas {
    @LambdaFunction(functionName = "my-aws-lambda-name")
    public String helloWorld(String name);
}
```

And then build an implementation:
```
AWSLambdaClient lambda = new AWSLambdaClient(); lambda.configureRegion(Regions.EU_WEST_1);
MyLambdas lambdas = LambdaInvokerFactory.build(MyLambdas.class, lambda);
```

This is all fine. However, it doesn't support different deployment environments (say int/test/live), where a lambda can have different name (say created via CloudFormation). 

To address this, I would propose to overload `LambdaInvokerFactory.build` to take an additional map of key->lambdaName. Key would store the value passed to `@LambdaFunction`, whilst value for this key would be the actual function name in AWS. This would allow to use different function names for different environments. An example of use:
```
interface MyLambdas {
    @LambdaFunction(functionName = "hello-world-lambda-key")
    public String helloWorld(String name);
}

Map<String, String> myLambdaNames = new HashMap<String, String>();
myLambdaNames.put("hello-world-lambda-key", "my-aws-lambda-name");

AWSLambdaClient lambda = new AWSLambdaClient();
lambda.configureRegion(Regions.EU_WEST_1);
MyLambdas lambdas = LambdaInvokerFactory.build(MyLambdas.class, lambda, myLambdaNames);
```

As you can see this let's us to pull the names at runtime, from places like config etc. I think this would be a beneficial addition to the API.  
I have implemented this functionality in [this fork](https://github.com/codan84/aws-sdk-java)

**Comment by shorea** [comment]
Made some comments in the PR.

**Comment by gigi888** [comment]
so cool! it solves our problem too! Many thanks
