### ISSUE TITLE
Workflow re-run stops working after some time

### ISSUE THREAD

**Issue by jharajeev** [aws/aws-sdk-java#607]
I just started working on aws swf and have developed a simple workflow using AWS flow framework for JAVA. After I register the workflow, when I try to re-run it, it works fine for some time no matter how many times I try that. But after some time, say few hours, re-run stops working. I checked the history and can see that execution is stuck at DecisionTaskScheduled event and so eventually times out. It seems that activity and workflow workers have stopped running as I can see "No Activities found for the given execution" message in Activities tab of the execution history. It starts working again if I run the workflow and activity host manually.

Am I doing something wrong? For my use case, I need workflow and activity workers to run continuously so that I can trigger the workflow whenever I need from my web application.

![4](https://cloud.githubusercontent.com/assets/15798596/12385259/07807122-bde0-11e5-9c57-427c9eedbd32.PNG)

![1](https://cloud.githubusercontent.com/assets/15798596/12385236/bdb8bc48-bddf-11e5-849f-02e7f88d5690.PNG)
![2](https://cloud.githubusercontent.com/assets/15798596/12385239/c548cc5a-bddf-11e5-8901-e7996ab51ee5.PNG)
![3](https://cloud.githubusercontent.com/assets/15798596/12385242/cbe0110e-bddf-11e5-883c-ce1d5be929a0.PNG)

**Comment by manikandanrs** [comment]
Are you creating the workflows through console ?

**Comment by jharajeev** [comment]
No, I am using java flow framework to create the workflow. To re-run it, I am using console.

For your reference, I am trying with this sample workflow (http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/getting-started-example-helloworldworkflow.html). I run both GreeterWorker and GreeterMain to start the workers and the workflow. It works fine but as I mentioned, worker service gets stopped after some time due to some reason and so re-run also stops working. If I execute GreeterWorker again, re-run again starts working.

**Comment by manikandanrs** [comment]
This issue was moved to aws/aws-swf-flow-library#3

**Comment by SaiNageswarS** [comment]
I'm having the same issue. Create an swf domain and ran workflow against the domain. Got exception com.amazonaws.services.simpleworkflow.model.UnknownResourceException.

On creating a new workflow type, the above error is resolved, however, I get "No Activities found for the given execution." in aws console. 

Please let me know what am I missing here.
