### ISSUE TITLE
DynamoDBMapper: filter out empty byte[] arrays

### ISSUE THREAD

**Issue by lesliel** [aws/aws-sdk-java#608]
DynamoDBMapper should also filter out empty `byte[]` arrays, not just the `null` values. Currently the following code:
``` java
@DynamoDBAttribute(attributeName = "bin")
public byte[] getBinary() {
    return new byte[0];
}
```
throws `com.amazonaws.AmazonServiceException: One or more parameter values were invalid: An AttributeValue may not contain a null or empty binary type. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ...)`

On the other hand:
``` java
@DynamoDBAttribute(attributeName = "bin")
public byte[] getBinary() {
    return null;
}
```
will simply skip the given attribute.

**Comment by shorea** [comment]
We don't really skip it if it's null, null values are treated as deletions of the attribute. For strings we actually treat empty kind of like null but that's considered legacy behavior per the comment here, https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/marshallers/StringToStringMarshaller.java#L39. 

I'm a little hesitant to add this until I fully understand the use case. Could you explain why skipping empty byte arrays is preferable in your application?

**Comment by lesliel** [comment]
It is your error message that is misleading as it is inconsistent with the current behaviour: you do allow null binary values in mapped objects.

**Comment by shorea** [comment]
I definitely agree there. Unfortunately this is a service exception so we don't really have control over it. I could make a feature request to the Dynamo DB team to break this validation message out a little better (i.e. have one message for null, one message for empty) if you're interested.

**Comment by shorea** [comment]
Closing issue, feel free to reopen if you have further problems.
