### ISSUE TITLE
Path with JSON key does not work in UpdateExpression name map. 

### ISSUE THREAD

**Issue by Dimes** [aws/aws-sdk-java#615]
Consider an item that looks like this:

    {
      "id": "theId",
      "document": {}
    }

The following update expressions should produce the name result. They don't however. The first one updates the `document` map, while the second adds a new top-level property called `document.propertyName`. 

    Table myTable = ...;
    myTable.updateItem("id", "theId", "ADD document.propertyName :val", null, 
            new ValueMap().withStringSet(":val", "theStringToAdd"));

The above example produces the expected result.

    Table myTable = ...;
    myTable.updateItem("id", "theId", "ADD #name :val", 
            new NameMap().with("#name", "document.propertyName"), 
            new ValueMap().withStringSet(":val", "theStringToAdd"));

The above produces the wrong result. After executing the last statement, the item looks like this:

    {
      "id": "theId",
      "document": {},
      "document.propertyName": ["theStringToAdd"]
    }

**Comment by manikandanrs** [comment]
looking into it.

**Comment by manikandanrs** [comment]
This is the expected behavior of the service. The "dot" in the name is treated as part of the attribute as it is a valid character allowed for an attribute name.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ExpressionPlaceholders.html

To solve this, you will need to say #name.#propertyname in the expression and specify the actual names in the name map.

**Comment by Dimes** [comment]
I see, thanks.

**Comment by Dimes** [comment]
I think there are some consistency issues across the different APIs. For instance, using AttributeUpdate("a.b.c") does not treat "." as a path separator.

**Comment by manikandanrs** [comment]
I believe you are referring to #617. I am going to comment there. 

Closing this issue.
