### ISSUE TITLE
Feature request: support DELETE on List type or support empty StringSet and JSON StringSets.

### ISSUE THREAD

**Issue by Dimes** [aws/aws-sdk-java#616]
The current JSON support feels a little weird when used with StringSets. StringSets are currently the only operation to support the `DELETE` operation. This operation is very useful for certain type of operations. Using them with JSON, however, feels very clunky. For instance, there is no way that a list inside of a JSON object should be treated as a StringSet instead of a List. Another issue is that empty StringSets are not currently supported, which makes serialization / deserialization a little weird, since empty lists must be treated as null. 

An alternative would be the support the `DELETE` operation on lists. So, instead of using `REMOVE` with an index, `DELETE` and a value can remove elements from the list instead. I don't know what would happen if there were duplicates in the list.

**Comment by zhangzhx** [comment]
Could you give me a concrete example, such as a piece of anticipated sample code. I don't quite understand what you mean in the description.

**Comment by zhangzhx** [comment]
Closing this for lack of response. Feel free to open a new one if you still have further questions. Thank you.
