### ISSUE TITLE
AttributeUpdate does not work with JSON keys.

### ISSUE THREAD

**Issue by Dimes** [aws/aws-sdk-java#617]
[Possibly related to #615]

Given a document that looks like this:

    {
      "myMap": {
        "innerMap": {}
      },
      "hashKeyName": "hashKeyValue"
    }

The following code produces an unexpected result:

    Table myTable = ...;
    myTable.updateItem("hashKeyName", "hashKeyValue", 
            new AttributeUpdate("myMap.innerMap.myKey").addNumeric(100));

The resulting document looks like this (notice the inner map has not been modified):

    {
      "myMap": {
        "innerMap": {}
      },
      "myMap.innerMap.myKey": 100,
      "hashKeyName": "hashKeyValue"
    }

**Comment by manikandanrs** [comment]
The AttributeUpdate corresponds the older way of updating an attribute using AttributeUpdates Map which doesn't support JSON keys.

For your use case, you will need to call updateItem(primarykey, updateexpression, nameMap, valueMap)

**Comment by manikandanrs** [comment]
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/Table.java#L201

**Comment by manikandanrs** [comment]
Closing this. Feel free to re open if you still face any issues.
