### ISSUE TITLE
S3: PutObject with more than 5MB fails (Entity Too Large)

### ISSUE THREAD

**Issue by akiradeveloper** [aws/aws-sdk-java#618]
AmazonS3Client#putObject fails when I try to upload a file larger than 5MB. Please explain why?

About the number 5, all I know is:
1. S3 server can process 5GB upload per one request.
2. In multipart upload, part size should be larger than 5MB.

But I don't have a clue why putObject is restricted to 5MB.

```
Request Entity Too Large (Service: Amazon S3; Status Code: 413; Error Code: 413 Request Entity Too Large; Request ID: null)
com.amazonaws.services.s3.model.AmazonS3Exception: Request Entity Too Large (Service: Amazon S3; Status Code: 413; Error Code: 413 Request Entity Too Large; Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
```

**Comment by shorea** [comment]
I'm not able to reproduce with the latest version of the SDK (1.10.49). Which version are you using and if possible could you provide a code snippet that can reproduce this issue?

**Comment by akiradeveloper** [comment]
@shorea I am using 1.0.49 too. I was using 1.0.12 and it was reproducible and I am now using 1.0.49 to see if it reproducible in the latest.

Actually, the server isn't the Amazon's S3 but my own S3-compatible storage. It's using finagle-http as the backend. (https://github.com/akiradeveloper/akashic-storage)

I ask this issue here because the error seems to be occurring on client-side, before reaching the server.

The code snippet is here. It's simple. Creating a S3Client and call putObject with large file. Note that it says 8MB but the boundary I found is 5MB. 5MB is ok but 5MB+1000B is not ok.

Do you think aws-sdk first (on creating client or before each request) asks the server how large the data it accepts at once? 

```scala
  override protected def withFixture(test: OneArgTest) = {
    val conf = new ClientConfiguration
    conf.setSignerOverride("S3SignerType") // force to use v2 signature. not supported in 1.9.7

    val cli = new AmazonS3Client(new BasicAWSCredentials(TestUsers.hoge.accessKey, TestUsers.hoge.secretKey), conf)
    cli.setEndpoint(s"http://${server.address}")
    cli.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true))

    test(FixtureParam(cli))
  }

  test("put 8mb file") { p =>
    import p._
    client.createBucket("myb")
    val path = FILE_PATH_8MB
    createLargeFile(path, 8)
    val f = path.toFile
    client.putObject("myb", "myobj", f)
    val obj = client.getObject("myb", "myobj")
    checkFileContent(obj, f)
  }
```

**Comment by akiradeveloper** [comment]
@shorea Sorry, it was my mistake. I should have configure finagle-http. Once I've done it. putObject became successful
