### ISSUE TITLE
New Amazon ECS regions ap-southeast-1 and eu-central-1 are not supported yet

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#621]
Amazon ECS added support for [ap-southeast-1](https://aws.amazon.com/about-aws/whats-new/2015/12/amazon-ec2-container-service-available-in-asia-pacific-singapore/) and [eu-central-1](https://aws.amazon.com/about-aws/whats-new/2015/12/amazon-ec2-container-service-available-in-eu-frankfurt/) several weeks and SDK versions ago (including a notable ECS related update in [release 1.10.43](https://aws.amazon.com/releasenotes/Java/6574088230565898)), but the SDK is still missing these regions in ['aws-java-sdk-core/src/main/resources/com/amazonaws/regions/regions.xml'](https://github.com/aws/aws-sdk-java/blob/1.10.49/aws-java-sdk-core/src/main/resources/com/amazonaws/regions/regions.xml) as of  the current release 1.10.49 .

* Please note that this seems similar to the oversight in #403.

**Comment by manikandanrs** [comment]
Thanks for the heads up. I will stage this for next release.

**Comment by manikandanrs** [comment]
This is staged for next release tentatively next week.
