### ISSUE TITLE
AWS EC2 clock skew error - getSigningDate problem (Integer overflow) -> Incorrect signing date

### ISSUE THREAD

**Issue by devain** [aws/aws-sdk-java#622]
I'm having a problem with clock skew error, the root cause is from this method:
com.amazonaws.auth.internal.AWS4SignerRequestParams 
   /**
     * Returns the signing date from the request.
     */
    private final long getSigningDate(SignableRequest<?> request) {
        return System.currentTimeMillis() - request.getTimeOffset() * 1000;
    }

request.getTimeOffset() -> return integer
request.getTimeOffset() * 1000 -> return integer -> overflow when request.getTimeOffset() > 2147483

-> Solutions:
1.  request.getTimeOffset() * 1000 ->  request.getTimeOffset() * 1000L
2. Change to use miliseconds instead of seconds (request.getTimeOffset return "long").

Please fix it ASAP,
Thanks!

**Comment by manikandanrs** [comment]
Thanks for reporting this. We will get this fixed as part of next release.

**Comment by manikandanrs** [comment]
This is fixed and staged for next release.
