### ISSUE TITLE
About validation in S3 getObject

### ISSUE THREAD

**Issue by akiradeveloper** [aws/aws-sdk-java#625]
The following code roughly says:

1, MD5 validation is skipped if property is set or etag doesn't exist in the response or the etag is of Multipart Upload form that contains "-"
2. If validation is skipped (Go to else clause), take the Content-Length as the expected length and examine if the actual bytes read is equal to the expected.

I guess this code corrupts if the server responds in chunked transfer encoding what was uploaded in Multipart Upload.

When it's chunked transfer encoding, there is no Content-Length in the HTTP header so the expected length becomes 0. Apparently, the length-check validation fails.

This code is irrational because if-else clauses are completely different meaning. I don't see any reason to check by length in case MD5 validation is skipped.

My idea is, we should purge the else clause completely. (MD5 skipping is OK)

```java
            // The Etag header contains a server-side MD5 of the object. If
            // we're downloading the whole object, by default we wrap the
            // stream in a validator that calculates an MD5 of the downloaded
            // bytes and complains if what we received doesn't match the Etag.
            if (!skipMd5CheckStrategy.skipClientSideValidation(getObjectRequest, s3Object.getObjectMetadata())) {
                byte[] serverSideHash = BinaryUtils.fromHex(s3Object.getObjectMetadata().getETag());
                try {
                    // No content length check is performed when the
                    // MD5 check is enabled, since a correct MD5 check would
                    // imply a correct content length.
                    MessageDigest digest = MessageDigest.getInstance("MD5");
                    is = new DigestValidationInputStream(is, digest, serverSideHash);
                } catch (NoSuchAlgorithmException e) {
                    log.warn("No MD5 digest algorithm available.  Unable to calculate "
                            + "checksum and verify data integrity.", e);
                }
            } else {
                // Ensures the data received from S3 has the same length as the
                // expected content-length
                is = new LengthCheckInputStream(is,
                    s3Object.getObjectMetadata().getContentLength(), // expected length
                    INCLUDE_SKIPPED_BYTES); // bytes received from S3 are all included even if skipped
            }
```

**Comment by shorea** [comment]
Can you provide some sample code that demonstrates the case where GetObject does not return a Content-Length?

**Comment by shorea** [comment]
Closing this issue. Feel free to reopen if problem persists.

**Comment by uddhav** [comment]
I think that I just bumped into this one just now. I don't have any sample code yet but just confirmed that this is happening with TransferManager & AmazonS3 with or without the SkipMD5 property.
<img width="681" alt="nocontentlengthawss3sdk1 11 12" src="https://cloud.githubusercontent.com/assets/431917/18222209/c7c99338-715d-11e6-9e66-6232cbc36d1d.png">

**Comment by uddhav** [comment]
Removing the gzip = true setter from new ClientConfigurationFactory().getConfig() fixed this. The content was already gzipped at rest in S3.
