### ISSUE TITLE
Support for multiple shadows per thing

### ISSUE THREAD

**Issue by ramki982** [aws/aws-sdk-java#626]
Hi all,

In troubleshooting section in documentation (http://docs.aws.amazon.com/iot/latest/developerguide/iot_troubleshooting.html) - it is clearly mentioned "A device can have an unlimited number of thing shadows. The only requirement is that the thing name is unique in your account",

In the AWS IOT SDK for Javascript - https://github.com/aws/aws-iot-device-sdk-js - it is mentioned "The 'thingShadow' class supports multiple Thing Shadows per mqtt connection". 
In the example - there is mention about "register" (eg: **thingShadows.register( 'RGBLedLamp' );**) for creating a additional shadow document & update call will take the <shadow document name> to specifically update a specific shadow document.**thingShadows.update('RGBLedLamp', rgbLedLampState);**

But the getThingShadow and updateThingShadow SDKs in java don't let me use this ability to write to a specific document. 

Could you help fix this? Kindly let me know if I'm missing something here

thanks
Ram

**Comment by ramki982** [comment]
TO be on same page - I did some more tests and found updateThingShadow to be a upsert. But I'm surprised that I'm able to create shadow documents with any arbitrary thingName even if such a thing doesnt exists. 

`UpdateThingShadowRequest shadowUpdateRequest = new UpdateThingShadowRequest();
    shadowUpdateRequest.setThingName("rama"); // NOT Attached to any THING in AWS IOT Registry - but is working
    ByteBuffer payload = getMyPayload();
    shadowUpdateRequest.setPayload(payload);
    UpdateThingShadowResult result = dataClient.updateThingShadow(shadowUpdateRequest);
    ByteBuffer asReadOnlyBufferForUpdate = result.getPayload().asReadOnlyBuffer();
    JsonObject updateShadowResult = JsonUtils.toJson(asReadOnlyBufferForUpdate);
    LOGGER.debug("UpdateThingShadowResult: {}", updateShadowResult);`

Once I create such a free floating document - I'm also able to send a GetThingShadowRequest to read it.

So want to understand how the system is allowing arbitrary shadows not attached to IOT things

**Comment by shorea** [comment]
@ramki982 I'm engaging the service team. Stay tuned for a response :)

**Comment by ramki982** [comment]
Thanks a lot shorea

**Comment by ramki982** [comment]
As a gentle reminder - wanted to check if the service team had any inputs regarding my query.

Thanks so much in advance for all your awesome work!!

**Comment by amirthar** [comment]
@ramki982 thanks for reaching out. Per our current design, there isn't a strong association between a Thing in the Registry and shadows. We did not want to enforce such an association before understanding different scenarios it would enable/constrain. Based on customer feedback, we are considering supporting such a relationship (no ETA yet). 

So, yes you can create shadows independent of things in Registry today and that is the expected behavior. Having said that, we recommend creating a Thing in the Registry with unique Thing Name and use it to reference to the shadows.

**Comment by ramki982** [comment]
@amirthar  main problems are the API calls this variable thingName so it is difficult to understand that it is any string that will be used as shadow document name & also only 1 shadow is visible in IOT dashboard that is misleading

**Comment by reachprateek** [comment]
Hi,

I'm using iot-java-sdk for a project and observed that Once i create a thing in the registry with a unique Thing Name and try to update/retrieve document for that thing in the registry using the SDK the changes (update, delete etc) are not reflected to the shadow document of thing in the registry.  i've made sure i'm using the exact same name.

Based on the above  conversation I understand that there isn't a strong association between the registry and shadows you create using the SDK but then you seem to suggest you "recommend creating a Thing in the Registry with unique Thing Name and use it to reference to the shadows"
I'm using the recommend path here but the association doesn't seem to be happening. Can you please advice ??

My project is to Control some home devices using an Alexa skill. So both my Lambda function and the software directing the device need to update or view the latest state of the shadow. 

Best,
Prateek

**Comment by BorjaHazas** [comment]
Hello All,

Any update? Same matter as **reachprateek** is happening to me (using java).

I'm trying to update like: device.update(jsonState); without success:

_nov 10, 2017 7:46:42 AM com.amazonaws.services.iot.client.shadow.AwsIotDeviceCommand put
INFORMACIÓN: Request is pending: UPDATE/44a420b9-fec9-4387-92ae-ee5971684bf3_

Any idea?

Also I've tryinig to update the topic, publishing to "**aws/things/testTermostato/shadow/update**" and I'm not showing the thing shadow updated.

Your help/comments are to much appreciated.

Thanks in advance.

Kind regards,
