### ISSUE TITLE
Different handling of null content-type in putObject() and TransferManager::upload()

### ISSUE THREAD

**Issue by BluelivSecurity** [aws/aws-sdk-java#627]
Using the method ``putObject`` of ``AmazonS3Client`` without providing it with a content-type in the ``ObjectMetadata`` doesn't crash because at some point it sets it accordingly.
However, when using the method ``TransferManager::upload()`` using the exact same ``AmazonS3Client`` and the exact same ``ObjectMetadata``, it seems to throw a ``NullPointerException`` coming from [this point](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L3189) in ``AmazonS3Client``, because in this case it doesn't set it, contrary to the previous case.
It feels like it's either a bug or odd undocumented behavior, which makes it confusing.

**Comment by shorea** [comment]
@BluelivSecurity I am having trouble reproducing. Can you provide some sample code?

**Comment by BluelivSecurity** [comment]
Hi @shorea,

Yes, of course. We forgot to mention that the NPE happens when you try to execute the ``waitForCompletion()`` method. We created a [gist](https://gist.github.com/BluelivSecurity/08e67552050fc57b5616) with what our code looks like.

Best regards,
Blueliv Engineering Team

**Comment by shorea** [comment]
If you remove metadata.setContentType(null) does the code work?

**Comment by BluelivSecurity** [comment]
Hi @shorea, 

Sorry for the late answer. Basically, we tested it out with a small file (~1MB) and a big one (~70MB). We had no problems uploading the small file with or without the ``metadata.setContentType(null)``. The same was not true for the bigger one, since it threw an ``AmazonClientException`` whose cause is a NPE, if setting the content type as ``null``.

Best regards,
Blueliv Engineering Team

**Comment by shorea** [comment]
Sorry for the long pause. If you don't explicitly set the content type we will attempt to guess it for you. Will that meet your needs?

**Comment by BluelivSecurity** [comment]
Hi @shorea,

Yes, that is right. I guess that is the same behavior implemented in ``putObject()`` as well.

Best,
Blueliv Engineering Team

**Comment by shorea** [comment]
Closing this issue.
