### ISSUE TITLE
Presigned URLs : bucket names containing "." chars + HTTPS

### ISSUE THREAD

**Issue by dili91** [aws/aws-sdk-java#628]
Hi, 
i'm using java SDK (aws-java-sdk-s3 1.10.50) to generate presigned URLs for files hosted on my bucket. I noticed that if my bucket name contains dots in it (eg: "my.bucket"), I can generate presigned public URLs but when I try to access the resource through the generated link my browser says that cannot verify the identity of the bucket, similar to the one shown whenever someone uses https with a self-signed certificate 

judging from [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) it seems to my that my bucket name is valid. 
Therefore is this an expected behavior? 

Thanks,
Andrea

<img width="1440" alt="schermata 2016-02-08 alle 14 38 26" src="https://cloud.githubusercontent.com/assets/10221348/12887042/0f7b12d6-ce72-11e5-9a2a-ea4fbf8b7449.png">

**Comment by dili91** [comment]
"When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic."

**Comment by ptanov** [comment]
As a workaround you could use code snipped mentioned here: <https://github.com/aws/aws-sdk-java-v2/issues/4958#issuecomment-1964402258>
