### ISSUE TITLE
Feature request: Support JSON as a value type in a ValueMap.

### ISSUE THREAD

**Issue by dimes** [aws/aws-sdk-java#629]
Currently `com.amazonaws.services.dynamodbv2.document.utils.ValueMap` supports a lot data types such as number, string, string set, or map. It does not, however, support JSON. It would be very nice to construct a value map like so:

```
new ValueMap().withJson(":val", "{\"theKey\": 5}");
```

Currently, the JSON must be converted to a `Map<String,?>` and then set using `withMap`.

**Comment by breedloj** [comment]
Hey, thanks for reaching out to us.  While ValueMap does not currently support JSON values, you can create an Item with a JSON value for a particular attribute: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/Item.html#withJSON(java.lang.String, java.lang.String).  Would this work for you or do you effectively need to be able to nest JSON values within the map?

**Comment by Dimes** [comment]
I am using a ValueMap with an update a JSON field inside a Dynamo item. The primary API I'm using is `com.amazonaws.services.dynamodbv2.document.Table`, which does not currently support updates using `Item`. 

To give you a quick example, my Dynamo Item looks like this:

    {
        "id": 123,
        "stringKey": "value",
        "intKey": 5,
        "mapKey": {
            "someKey": 10,
            "someOtherKey": 20
        }
    }

To create this `Item`, I do `new Item().withPrimaryKey("id", 123).withJSON("mapKey", "{...}").with(...);` In my update expression, I would like to update only `mapKey`. I think the only way to do this is with an update expression. Given my basic knowledge, it seems that an update should look like this:

    table.updateItem("id", 123, "SET mapKey :val", null /* name map */, new ValueMap().withJSON(":val", "{...}");

It's not that big of a deal to convert the JSON to `Map<String, Object>`, but it would be nice if you could update with JSON directly.

**Comment by zhangzhx** [comment]
Thanks for the explanation. I will add this to our feature request back log.

We love accepting pull requests from our customers. If you wish to submit a PR for this, I would be happy to take a look at it.

**Comment by yairzaslavsky** [comment]
@Dimes 

IMHO, your suggestion is a potential to contract breakage and some strange behavior.

The source code at UpdateItemImpl.java shows that  that the request is set with attribute names, which is provided from the NameMap on the spec object.
What happens if your updateExpression contains for example two values to be updated? one is a map and one is an integer?

**Comment by yairzaslavsky** [comment]
@Dimes  is this feature still interesting you? I am looking for something similar.
What I did not understand is why in your example for suggested behavior you did not provide a names map?

@zhangzhx when looking at AWS dynamodb samples (java) I did not see update queries without using a name  -

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaDocumentAPIItemCRUD.html#JavaDocumentAPIItemUpdate

Can you elaborate on that?


Cheers,
Yair

**Comment by yairzaslavsky** [comment]
I see a JS example 

http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.JsShell.07.html

With a similar syntax to the requested syntax by @Dimes  -  i.e: no usage of names map.

**Comment by yairzaslavsky** [comment]
@zhangzhx  @Dimes 
Here is a suggestion for implementation of this feature request.
I tested it with our code that required it besides the unit test that I added.


https://github.com/aws/aws-sdk-java/pull/910

**Comment by millems** [comment]
This seems to be supported now. Please let me know if this is still an issue for you.
