### ISSUE TITLE
Consider documenting thread safety

### ISSUE THREAD

**Issue by jfaerman** [aws/aws-sdk-java#632]
Questions about thread safety and connection management are frequent:

http://stackoverflow.com/questions/26381289/is-it-safe-to-declare-an-aws-java-sdk-client-object-as-static-for-concurrent-use/26381559
http://stackoverflow.com/questions/23407515/amazons3-connection-management/23457392

Consider making thread safety and connection management information more clear in the docs.

**Comment by manikandanrs** [comment]
Thanks for the reporting this. We will add thread safety annotations to the client class.

**Comment by manikandanrs** [comment]
I have staged a fix for this. We will get this released as part of next release that is tentatively scheduled for tomorrow.

**Comment by jfaerman** [comment]
wow, that was fast :) thanks!
