### ISSUE TITLE
SQS Attribute MD5 mismatch for the Binary type.

### ISSUE THREAD

**Issue by vburenin** [aws/aws-sdk-java#633]
Hi folks,

I am experiencing this issue when I am trying to calculate MD5 hash for the binary typed attribute.
Issue is reproducible even for one attribute.

'MessageAttribute.1.Name': 'testname'
'MessageAttribute.1.Value.DataType': 'Binary'
'MessageAttribute.1.Value.BinaryValue': '123'

The MD5 I get from SQS is 7aad2f4b0331285b6ce9683fe98ae563

When I try to calculate the same hash on my end, I get 4969dd151b0a6c8b619ebb802f76e035

Another issue that could point to the problem is that if binary value is just one byte I get this error back from SQS:
```

<?xml version="1.0"?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>The message attribute \'testname\' must contain non-empty message attribute value for message attribute type \'Binary\'.</Message>
    <Detail/>
  </Error>
  <RequestId>1ecd79c5-5ff9-51ce-9d99-36fe3ddbaf5b</RequestId>
</ErrorResponse>
```

For types String and Number MD5 checksum matches as expected.

Thoughts?

**Comment by vburenin** [comment]
Found the problem. Problem is in boto2 library. It builds a little malformed SQS request that is not well parsed by SQS service, so it ends up with the wrong MD5. Switching to boto3 resolved the problem.

**Comment by manikandanrs** [comment]
Are you seeing this issue with Java SDK ?

**Comment by vburenin** [comment]
Nope. However, I thought it might be related.
