### ISSUE TITLE
RunJobFlowRequest from JSON

### ISSUE THREAD

**Issue by iglezouton** [aws/aws-sdk-java#636]
Is there any direct method that return RunJobFlowRequest object from JSON as input??

**Comment by manikandanrs** [comment]
Do you mean to create a RunJobFlowRequest from a JSON ? Can you give us more context on this JSON and from where it is being received ? Can you use Jackson object mapper to create an instance of RunJobFlowRequest ?

**Comment by iglezouton** [comment]
Yes, I means create it from JSON. Actually I'm using Jackson to create the Object and all works fine but I was looking for a method to load the JSON directly on AWS SDK and I didn't found it.

The JSON looks like the following:
```
{
  "requestMetricCollector": null,
  "customRequestHeaders": null,
  "customQueryParameters": null,
  "cloneSource": null,
  "sdkRequestTimeout": null,
  "sdkClientExecutionTimeout": null,
  "name": "test".............}
```

My code does the next:
```
ObjectMapper mapper = new ObjectMapper();
mapper.addMixIn(InstanceGroupConfig.class, IgnoreSetValues.class);
request = mapper.readValue(new File(pathToJson), RunJobFlowRequest.class);
```

I've made a MixIn class for overloaded methods (mapper fails in this case).

My question is if it's any direct option with Marshalling or something like that in the JDK.

Regards.

**Comment by manikandanrs** [comment]
The AWS Java SDK currently doesn't support loading the creating a request object from a JSON directly.

**Comment by shorea** [comment]
If you are using Jackson you should be able to roundtrip the request object although please take caution in doing this as request objects may optionally contain credentials.
