### ISSUE TITLE
Error while trying to list the bucket using an AWS S3 client

### ISSUE THREAD

**Issue by jeetendranarayan** [aws/aws-sdk-java#640]
om.amazonaws.AmazonClientException: Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader)
	com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:620)
	com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:331)
	com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:202)
	com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3001)
	com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2972)
	com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:529)
	com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:537)

**Comment by shorea** [comment]
Sounds like something is up with your JVM configuration and the S3 client is not able to find a SAX implementation to use. Is there more to the exception message?

**Comment by jeetendranarayan** [comment]
Hi Shorea,

I have multiple applications installed in single tomcat server. With that i started facing issue as explained in https://blogs.oracle.com/mei/entry/java_lang_classnotfoundexception_org_apache. Basically i added System.clearProperty("org.xml.sax.driver") before calling s3Client.listBuckets(). 

It worked for sometime, but today it started failing with the error i mentioned.

**Comment by shorea** [comment]
What's the value of that property before you clear it?

**Comment by jeetendranarayan** [comment]
I am not checking that. not sure about that.

**Comment by shorea** [comment]
Is another part of your application setting this property? It looks like that property is being set to an invalid implementation.

**Comment by jeetendranarayan** [comment]
Yes. but when i clear the property before calling listBuckets(), then it should work fine . Somehow it worked for more than a week and started throwing the exception after that.

**Comment by shorea** [comment]
Is there a possibility of a race condition. I.E. you clear the property before it get's set and then it's set to the invalid implementation. Would it be possible just to stop the code from setting this property at all?

**Comment by shorea** [comment]
Is this still a problem for you @jeetendranarayan

**Comment by shorea** [comment]
Closing this issue. Feel free to reopen if you continue to have an issue.

**Comment by anishpr9** [comment]
How do you fix this issue? Im getting the same exception
