### ISSUE TITLE
Gradle test run : aws-sdk-java log level control

### ISSUE THREAD

**Issue by sandakith** [aws/aws-sdk-java#644]
I know its up to gradle env to set the log level, however i tried to do that and could not get the aws log level updated while running test-cases (which uses the aws-sdk, especially using com.amazonaws.AmazonWebServiceClient ) ... Seems like it always defaulted to debug mode ... 

*.*.*.environments.impl.*UtilsTest > test* STANDARD_OUT
    13:30:29.429 [Test worker] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging succesfully configured to commons logger: true
    13:30:29.507 [Test worker] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics

Any Input on this is really appreciated .. Thanks in advance.

**Comment by zhangzhx** [comment]
I'm not sure what logging system you are using, but we do recommend you to use log4j. You can refer to the following link for how to set up the log4j. Hope this could help you solve your problem.

http://docs.amazonaws.cn/en_us/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-logging.html

**Comment by sandakith** [comment]
Actually the issue was Gradle is using http://logback.qos.ch/ and we did not include a logback.xml in our test resources classpath ! 

Was able to redirect debug level messages to a file using the logback.xml

	<root level="debug">
		<appender-ref ref="FILE" />
	</root>
