### ISSUE TITLE
Release notes missing for versions 1.10.53 and 1.10.52

### ISSUE THREAD

**Issue by danieljamesscott** [aws/aws-sdk-java#648]
The release notes are missing for versions 1.10.53 and 1.10.52.

https://aws.amazon.com/releasenotes/Java?browse=1

Is it possible to get this fixed?

**Comment by breedloj** [comment]
Hey Daniel, thanks for reaching out to us.  I actually do see 1.10.52 there (https://aws.amazon.com/releasenotes/Java/0632862539448375) but not .53 or .54.  Regardless I'll look into backfilling the missing ones.

**Comment by danieljamesscott** [comment]
Hi,

I did mean .54 - forgot to edit after my copy paste, sorry!

Thanks for looking into it,

Dan

**Comment by breedloj** [comment]
The missing release notes have been backfilled.  Sorry for the inconvenience.  Feel free to reach out to us if you have any other questions or concerns.
