### ISSUE TITLE
Creating SdkSSLSocket  from SdkTLSSocketFactory  is taking lot of time....

### ISSUE THREAD

**Issue by jsrayalu** [aws/aws-sdk-java#651]
Hello Manikandan,

Can you pls help in understanding this.
I have some data stored in AWS and am retrieving the data using S3 client. But when I am trying to get the S3Client instance created, it is taking lot of time(4-6 seconds) sometimes. When I checked the logs, I see that SdkTLSSocketFactory is the class which is trying to create the SdkSSLSocket class instance , which itself is taking around 3 seconds.

Could you please help me in understanding this issue and to my knowledge it is a configuration issue.

I am attaching the logs also here

29 Feb 2016 19:24:14 [http-localhost/127.0.0.1:8080-1] DEBUG SdkTLSSocketFactory  - Connecting to server:port
29 Feb 2016 19:24:16 [http-localhost/127.0.0.1:8080-1] DEBUG SdkSSLSocket  - created: server/IP address:port

Please help me in understand and resolve this. Expecting your response asap.

**Comment by manikandanrs** [comment]
These logs are not printed during S3 client creation. These logs are printed when you execute an API. 

Take a look at the below blog post 

http://java.awsblog.com/post/TxO7X6GJCW1VUB/Tuning-the-AWS-SDK-for-Java-to-Improve-Resiliency

It gives information about how you can enable and start capturing metrics from the AWS Java SDK.

**Comment by manikandanrs** [comment]
Going to close this as there is no response. Feel free to re open when you have more information for us.
