### ISSUE TITLE
AWS IoT Samples

### ISSUE THREAD

**Issue by Mindbowser** [aws/aws-sdk-java#652]
Can you put some samples for IoT SDK describing consuming data from Thing and Publishing data to Thing?

**Comment by Mindbowser** [comment]
Any update here?

**Comment by o-can** [comment]
Feel free to view [https://github.com/o-can/aws-java-iot-example](https://github.com/o-can/aws-java-iot-example) . It might be able to get you started.

**Comment by shorea** [comment]
Sorry for the lack of response. Thanks @o-can for providing the samples.
