### ISSUE TITLE
No unit tests?

### ISSUE THREAD

**Issue by dcmdeivid** [aws/aws-sdk-java#66]
Where is the tests?

**Comment by bsideup** [comment]
Yup, lack of tests makes it almost impossible to contribute since there is no way to test that your changes will not break anything.

**Comment by flozano** [comment]
This issue has almost two years now and no news at all... the Ruby SDK has a test suite, so it must not be that difficult.

**Comment by fulghum** [comment]
Hey Francisco, you guys are right.  We have a big suite of integration tests internally that we strongly rely on, and we need to get those out externally for you guys to be able to run, too.  I'll talk to the team and see if we can prioritize getting the internal test code released.

**Comment by manikandanrs** [comment]
We just released unit tests for [aws-java-sdk-core module](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-core/src/test) as part of the [last release](https://aws.amazon.com/releasenotes/0061646886197506).

**Comment by hanshuo-aws** [comment]
We are actively working on publishing our internal test suites, and at this point we have released the unit test suits for the core and dynamodb modules. I am gonna close the issue for now, but feel free to reopen if you want to request the test code for a specific module and we will try to prioritize the work.
