### ISSUE TITLE
AmazonCloudSearchDomainClient does not expose a way to set "search" requests to use HTTP POST

### ISSUE THREAD

**Issue by humanzz** [aws/aws-sdk-java#660]
As per the documentation at http://docs.aws.amazon.com/cloudsearch/latest/developerguide/submitting-search-requests.html, HTTP GET requests have a size limit of 8190 bytes. To get around that, one might want to submit search requests via an HTTP POST. However, the AmazonCloudSearchDomainClient class does not expose any way to change the default HTTP GET to become a POST.

Ideally, setting the HTTP method for the search HTTP request should be exposed.

**Comment by zhangzhx** [comment]
We've had discussed this issue in our team meeting. Unfortunately, we are not planing to support both POST and GET in the SDK. We are relying on the service model to generate our SDK code. It's not a easy work to support both http methods simply for this operation. A workaround is perhaps try to shrink the size.

**Comment by dagnir** [comment]
Hi @humanzz, in case you were still interested in this feature, this is now fixed as of [1.11.32](https://aws.amazon.com/releasenotes/Java/0627162592215831) and all search requests now use `POST`. Thank for reporting this!
