### ISSUE TITLE
My EC2 always be attacked, who can help me?

### ISSUE THREAD

**Issue by liujiayi771** [aws/aws-sdk-java#662]
Our lab has a EC2 server. On the end of Last year, I found a strange process transfer data from my EC2 and I pay lots of money for these flows. I had no idea to deal with it, so I reset the EC2. Today, I found a strange process appear again, I really don't know how to do. I have a  pem to login my EC2, and I have limited the login IP, how can other people login my EC2, please help me.

**Comment by varunnvs92** [comment]
Hi liujiayi771,
This looks like it is not a SDK issue. I recommend you to go to support center which is at the top right corner of your AWS console and contact the support team.
Thank you!
