### ISSUE TITLE
AmazonCognitoSync InvalidSignatureException due to URL encoding

### ISSUE THREAD

**Issue by ruhkopf** [aws/aws-sdk-java#668]
There seems to be an issue with the cognito sync client caused by URL encoding.

The URL that's being invoked and that is expected in the signature: `GET /identitypools/us-east-1%3Af3bf****/identities/us-east-1%3Aad35*****/datasets/***/records`

The URL from the AWS log (and I assume this one is used for the signature): `Sending Request: GET https://cognito-sync.us-east-1.amazonaws.com/ /identitypools/us-east-1:f3bf*****/identities/us-east-1:ad35****/datasets/***/records`

Notice that the `:` gets encoded to `%3A`

The error I'm seeing: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

**Comment by ruhkopf** [comment]
Actually it was a configuration issue. Signing works as expected, I was just jumping to conclusions based on the logging output and error message. Sorry for opening this issue.

**Comment by manikandanrs** [comment]
Glad to know it worked. Feel free to open if you have more issues.
