### ISSUE TITLE
HeadBucketRequest doesn't properly fill AmazonS3Exception.errorCode

### ISSUE THREAD

**Issue by wujek-srujek** [aws/aws-sdk-java#672]
I'm using HeadBucketRequest for initial check and later for periodic health checks. Generally, it works fine with the one issue that the getErrorCode() method doesn't return the codes as defined here: http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList. For instance, when I use an invalid bucket id, I get '404 Not Found', instead of the expected 'NoSuchBucket'. Similarly, when the key id or secret are wrong, I get '403 Forbidden' instead of 'AccessDenied' or similar.

Is this as expected? For example, when I fetch an object for a key which doesn't exist, I get 'NoSuchKey', as defined in the linked error code table.

**Comment by manikandanrs** [comment]
The code in question is this

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/S3ErrorResponseHandler.java#L179-L180

For an HEAD request, we construct the exception from the headers and the status line in the HTTP response. Apparently S3 returns Not Found in the status line. Here is a sample wire log. 

org.apache.http.headers - << HTTP/1.1 403 Forbidden
org.apache.http.headers - << x-amz-bucket-region: us-east-1
org.apache.http.headers - << x-amz-request-id: A0EFE6F16EACE947
org.apache.http.headers - << x-amz-id-2: 1TdiswdjHsXZqHjrHD/kDaIJLqYspAEM7fPPKOnscUVNgFCdBnfThzQe4KGt4P0F
org.apache.http.headers - << Content-Type: application/xml
org.apache.http.headers - << Transfer-Encoding: chunked
org.apache.http.headers - << Date: Tue, 29 Mar 2016 19:15:34 GMT
org.apache.http.headers - << Server: AmazonS3

I will talk to the service team if they can improve the documentation on this.

**Comment by manikandanrs** [comment]
I just looked at this again. Since it is a head request we don't receive a payload from S3. The exception object is created from the headers and the SDK populates the HTTP Status code in the error code.

http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList

The status code for AccessDenied is 403 Forbidden as per the API doc. This is the expected behavior.

**Comment by wujek-srujek** [comment]
I think you are confusing status codes and error codes. Yes, the status code is '403 Forbidden', the problem is that the **error code** is also '403 Forbidden', not 'AccessDenied', as the table of error codes would suggest. Please take a look at the first column in the table, it actually never uses the HTTP status codes there. I really think the error code is wrong.

I also don't fully understand the comment about creating the exception from the headers and status line - when you get 404 in HeadBucket, it is clear that the issue is the bucket is wrong, and you can just 'translate' the 404 status code into 'NoSuchBucket', as for other requests (there must be such 'translation' logic somewhere). Note: I didn't come up with 'NoSuchBucket' by myself, it is defined in the error codes table linked to above. It actually seems like a trivial thing to fix.

Of course, I don't know the code so I might be completely wrong, but please take a second look.

**Comment by wujek-srujek** [comment]
Fair enough.
Two things, though: the HeadBucketRequest has been publicly available for a few months (I would know since I created a request to make the headBucket method public last year ;d), but still it could potentially break existing code, you are right - the way I see it, though, such code would be relying on a bug. Secondly, I think it is an issue of the HeadBucketRequest, since it should provide the payload allowing it to create a really useful exception, with error codes and all. Let's wait for future improvements.

Should I close the ticket or is it possible to change it into an improvement proposal?

**Comment by manikandanrs** [comment]
I have already created an issue in our backlog (tracked internally) on how we can improve the behavior here. I can leave the issue open or feel free to close it.

**Comment by wujek-srujek** [comment]
I will close it, no need to track it any more. Thanks for your answers.
