### ISSUE TITLE
DynamoDbMapper: support additional/dynamic attributes on declared models

### ISSUE THREAD

**Issue by estebistec** [aws/aws-sdk-java#674]
Jackson has a feature whereby with @AnyGetter [1] and @AnySetter annotations a serializable bean can handle JSON properties that aren't accounted for in the modeled properties (while keeping the benefits of the defined model).

Currently, with DynamoDbMapper this is only supported with a fully custom marshaller. However, this means that you've lost the benefit of modeling the known attributes and their constraints. This is true for both _table_ models and for _embedded document_ models. Is it reasonable for DynamoDb to perhaps have a feature like Jackson's, to support documents that could have unknown data attributes (especially helpful for embedded JSON "blobs").

I'm not against working on a pull request when I can make the time, but I wanted to get the suggestion logged now.

Thanks!

[1] http://wiki.fasterxml.com/JacksonFeatureAnyGetter

**Comment by fernomac** [comment]
:+1:

**Comment by zhangzhx** [comment]
Thanks for reaching out to us and this is really a nice feature for DynamoDB Mapper. You are welcome to send us a PR and we'll be glad to take a look.

**Comment by yairzaslavsky** [comment]
@estebistec  -
Won't @DynamoDBTypeConvertedJson annotation over a field that is map in your entity bean help in what you want to achieve?

**Comment by estebistec** [comment]
@yairzaslavsky that looks like it'd only work if you were okay with storing the entire object as a blob. The hope was to have the mapper still use dynamodb record attributes, but both for modeled and dynamic fields.

**Comment by yairzaslavsky** [comment]
@estebistec  
I think I understand - if I use json terminology - if  we use the annotation you suggested you end up with an internal map which will be serialized to run record.
What you want on the other hand is have the entries of the map (let's say 5 entries) being "serialized" as  5 separate records, similar to the Embeddable concept of Hibernate. Am I correct here?

**Comment by estebistec** [comment]
Err, no, not five records. One object is still one record (or embedded object in a containing record). I just want them to be discrete attributes (or fields) instead of one big JSON string.

**Comment by yairzaslavsky** [comment]
@estebistec  

Yes! This is what I meant - 5 attributes ! Sorry for my confusion :)  
A record is a row, I obviously meant 5 fields  (5 columns ).

Thanks for explaining

**Comment by estebistec** [comment]
No problem! As you can tell, this hasn't risen to the top of my To-Do list yet :/

**Comment by yairzaslavsky** [comment]
I don't mind assisting with implementing a pull request for this.

**Comment by yairzaslavsky** [comment]
@estebistec 

May I suggest that for the map field you will have for example something like this?

```
@DynamoDbEmbeddable
Map<String,Object> properties;
```

or use the "Annotation on getter" convention?
And have only one annotation and not two annotation as in the 
case of the Jackson example you gave?

**Comment by yairzaslavsky** [comment]
This is just the beginning of my work on this issue.

DynamoDBFlattened looks similar to your request.

**Comment by satz03** [comment]
do we have a solution for this in DynamoDBMapper yet? I want a particular item to have one attribute that comes from an inner class which uses @DynamoDBDocument ,so it's saved as a json object, but the class needs to be pre-defined with attributes , I want that class to take any JsonObject actually,any suggestion?

**Comment by suryavas** [comment]
hi,  any solutions to above @satz03 problem?
Map<String,Object> properties;

**Comment by debora-ito** [comment]
Hey @estebistec @yairzaslavsky @satz03 @suryavas, 

the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
