### ISSUE TITLE
ObjectMetadata doesn't have methods to set and get Content-Language metadata

### ISSUE THREAD

**Issue by tomlee** [aws/aws-sdk-java#676]
The raw S3 API allows the user to set and get the **Content-Language** header. But the `ObjectMetadata` class doesn't have the setter and getter for this metadata. I'd like to request adding `setContentLanguage()` and `getContentLanguage()` to `ObjectdMetadata`.

See AWS CLI documentation:
- [`set-object`](http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html)
- [`get-object`](http://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html)

Thanks.

**Comment by manikandanrs** [comment]
Sure. We can add the support

**Comment by manikandanrs** [comment]
I have staged this for next release that is scheduled tentatively tomorrow

**Comment by tomlee** [comment]
I have tested it and it works. Thank you very much for your prompt action.
