### ISSUE TITLE
New Amazon ECR region eu-west-1 is not supported yet

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#677]
Amazon ECR added support for [eu-west-1](http://aws.amazon.com/about-aws/whats-new/2016/03/amazon-ec2-container-registry-available-in-eu-ireland/) last week, but the SDK is still missing this region in ['/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json'](https://github.com/aws/aws-sdk-java/blob/1.10.67/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L347) as of  the current [release 1.10.67](https://aws.amazon.com/releasenotes/Java/5906392270528558), despite some other features announced just yesterday being included already.

* Please note that this seems similar to the oversight in #621.

* :question:While at this topic: The [AWS SDK for Java 1.10.51](https://aws.amazon.com/releasenotes/Java/3488066182595967) features notable refactorings to the region handling, presumably because it _introduces a new dynamic endpoint system that can compute endpoints for services in new regions_ . At a glance I had difficulties understanding how this is supposed to work back then, and the issue at hand seems to suggest it might not be complete or enabled yet - could you elaborate on this eventually? Thanks much!

**Comment by manikandanrs** [comment]
Thanks for bringing this in to our attention. We will update the endpoints.json file as part of our next release.

As part of 1.10.51, we revamped our endpoints system. The previous system was relying on static XML file that contains the endpoint mappings for regions and services. The new "endpoints.json" contains metadata about a different AWS partitions, regions inside a partition and how to compute endpoint for a region inside the partition. This information gives the SDK the capability to to guess an endpoints for services in existing or future AWS region even if the "endpoints.json" doesn't maintain the information.

If you have the latest SDK, I would suggest you to try the below code

System.out.println(Region.getRegion(Regions.EU_WEST_1).getServiceEndpoint("ecr"));

Although SDK doesn't have endpoint configured for ECR in eu-west-1, SDK will still be able to resolve the endpoint.

**Comment by manikandanrs** [comment]
I have staged the update for endpoints.json. It should be available as part of our next release tentatively scheduled for tomorrow.
