### ISSUE TITLE
Release notes missing for version 66

### ISSUE THREAD

**Issue by danieljamesscott** [aws/aws-sdk-java#678]
The release notes for version 1.10.66 are missing from:

https://aws.amazon.com/releasenotes/Java

Please can you add them?

**Comment by breedloj** [comment]
Hey Daniel,

Thanks for bringing this to our attention.  This release didn't contain any customer facing features which is why it was likely overlooked.  I've gone back and added the release notes: http://aws.amazon.com/releasenotes/0788564766757806
