### ISSUE TITLE
Check max error retry is working in case of 5XX error and how to cause 5XX error

### ISSUE THREAD

**Issue by alok1ranjan** [aws/aws-sdk-java#681]
Hi,

I am new in AWS application. I have created S3 client and configured it with default DEFAULT MAX_ERROR_RETRY setting. Now I want to check whether retry logic is working in case of 4XX or 5XX error.

Other thing is that, I want to replicate 5XX error but not succeeded. Can anyone please, help me out.

Regards,
Alok

**Comment by manikandanrs** [comment]
Default Retries of the SDK kicks in only on certain conditions. Please take a look at the below code to understand the conditions on which the retries happen

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L150-L190

One of the metrics that is captured by the metrics system in the SDK is the retry count. You can enable SDK metrics and catpure the retry count.

https://java.awsblog.com/post/Tx3C0RV4NRRBKTG/Enabling-Metrics-with-the-AWS-SDK-for-Java

Have you tried using wire mock to simulate 5xx errors ? 

http://wiremock.org/index.html

**Comment by manikandanrs** [comment]
Closing this as we have not heard back. Feel free to open if you have any issues.
