### ISSUE TITLE
Lambda updateFunctionConfiguration does not allow to update runtime

### ISSUE THREAD

**Issue by SamVerschueren** [aws/aws-sdk-java#684]
It's not possible to update the runtime when updating th configuration. http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html

**Comment by manikandanrs** [comment]
The javadocs seems to be not up to date. The code has been released.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-lambda/src/main/java/com/amazonaws/services/lambda/model/UpdateFunctionConfigurationRequest.java#L123

I will get the docs updated.

**Comment by SamVerschueren** [comment]
It appears to be resolved in the docs.
