### ISSUE TITLE
importRestApi NPE

### ISSUE THREAD

**Issue by stevensurgnier** [aws/aws-sdk-java#687]
[This](https://github.com/aws/aws-sdk-java/blob/a2c231a9a0e3b3141c53db09f8d653380ce34764/aws-java-sdk-api-gateway/src/main/java/com/amazonaws/services/apigateway/model/transform/ImportRestApiRequestMarshaller.java#L79) is throwing an NPE when `parameters` is null. Which happens to be the default value of `parameters`.

**Comment by breedloj** [comment]
Thanks for reporting this bug.  A fix has been pushed and will be released as part of the next version of the SDK.
