### ISSUE TITLE
Can I gracefully stop a docker instance from the Java sdk?

### ISSUE THREAD

**Issue by Sohaib12** [aws/aws-sdk-java#690]
I have a java code that I want to run inside a Docker Instance that will run in a container on the Amazon AWS. To terminate the container, I am thinking about sending a sigterm from Java to the main Bash script that starts the Java program in the first place. But this seems a bit complicated.

Now I have come across this AWS api for Java, I was just wondering if this api has the capability to close/stop a docker container gracefully on AWS server?

**Comment by zhangzhx** [comment]
The AWS API for Java is auto-generated from the service model. I will ask the service team to see if they provided a programmatic way to stop a Docker.

**Comment by zhangzhx** [comment]
I'm not sure, but I think the following API is what you want:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-ecs/src/main/java/com/amazonaws/services/ecs/AmazonECSClient.java#L1826

**Comment by Sohaib12** [comment]
I think this is very very close to what I want. It could even be exactly what I want but I need to try it first. I am relatively new at coding so I have to import the Java AWS api into my existing code and then call this method at the end of the code.

**Comment by zhangzhx** [comment]
Just let me know if it works for you.

**Comment by Sohaib12** [comment]
Will do (Y).

**Comment by zhangzhx** [comment]
Hi does this resolve your problem ? The service team said this is the right way to do this. I'm closing this issue for now, and feel free to open a new issue if you have further questions.

**Comment by Sohaib12** [comment]
Yes this resolves the problem. Thank you :).
