### ISSUE TITLE
Issue with PutRecordsRequest from Lambda to Kinesis

### ISSUE THREAD

**Issue by CiliaFred** [aws/aws-sdk-java#691]
Hi,

With version 1.10.70 & 1.10.71 we've got the following error : 
> com.amazonaws.AmazonClientException: Unable to marshall request to JSON: com/amazonaws/util/json/SdkJsonProtocolFactory

We are using PutRecordsRequest in a lambda function to insert data into Kinesis Stream.
Work perfectly with version 1.10.69.

Please correct it and fix version in your pom. We are using "aws-lambda-java-events" artifact in version 1.1.0 and the version 1.10.70 of sdk is coming automaticly....

**Comment by shorea** [comment]
Can you provide the full exception?

**Comment by CiliaFred** [comment]
Sure
The exception : 
> java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to marshall request to JSON: com/amazonaws/util/json/SdkJsonProtocolFactory
Caused by: com.amazonaws.AmazonClientException: Unable to marshall request to JSON: com/amazonaws/util/json/SdkJsonProtocolFactory 

Sorry i haven't the full trace in logstream.

The code :
`AmazonKinesisClient amazonKinesisClient = new AmazonKinesisClient(provider, kinesisConfig);
amazonKinesisClient.setRegion(Region.getRegion(Regions.EU_WEST_1));`
...
`PutRecordsRequestEntry putRecordsRequestEntry = new PutRecordsRequestEntry();
putRecordsRequestEntry.setData(ByteBuffer.wrap(os.toByteArray()));
putRecordsRequestEntry.setPartitionKey(String.format("partition-%d", i % 10));
putRecordsRequestEntryList.add(putRecordsRequestEntry);`
...
`putRecordsRequest.setRecords(putRecordsRequestEntryList);
amazonKinesisClient.putRecords(putRecordsRequest);`

Code is really basic....

**Comment by shorea** [comment]
Just tried with 1.10.71 and did not get an error. I suspect you have a dependency mismatch (i.e. you got version 1.10.71 of the Kinesis client but are somehow pulling in an older version of the core). Can you share your pom.xml?

**Comment by CiliaFred** [comment]
[pom.zip](https://github.com/aws/aws-sdk-java/files/230772/pom.zip)

**Comment by shorea** [comment]
Hmm so it looks like the lambda events is using version ranges. Not sure if this could be causing a problem, I'd expect maven to resolve the latest versions of each which would mean they'd be consistent.

Can you try declaring an explicit dependency on core?

```xml
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-java-sdk-core</artifactId>
	<version>1.10.71</version>
</dependency>
```

**Comment by shorea** [comment]
@CiliaFred did you get a chance to try out adding a explicit dependency?

**Comment by CiliaFred** [comment]
Sorry for the delay.
I just try again with version 1.10.76, works again.

I close this issue.
