### ISSUE TITLE
Allow configuration of ContentType in AmazonSNSClient, AmazonHttpClient, HttpRequestFactory chain

### ISSUE THREAD

**Issue by coryfklein** [aws/aws-sdk-java#692]
Concerning calls routed through this chain:

```java
AmazonSNSClient.invoke()
    |
    V
AmazonHttpClient.execute()
    |
    V
AmazonHttpClient.executeHelper()
    |
    V
AmazonHttpClient.executeOneRequest()
    |
    V
AmazonHttpClient.newApacheRequest()
    |
    V
HttpRequestFactory.createHttpRequest()
    |
    V
HttpRequestFactory.newStringEntity()
    |
    V
HttpRequestFactory.createHttpRequest()
    |
    V
org.apache.http.entity.StringEntity()
```

The entire pipeline above does not support calls to Amazon's SNS service with message bodies containing unicode. Ultimately, `HttpRequestFactory` creates an Apache `StringEntity` using this constructor:

```java
    /**
     * Creates a StringEntity with the specified content. The content type defaults to
     * {@link ContentType#TEXT_PLAIN}.
     *
     * @param string content to be used. Not {@code null}.
     *
     * @throws IllegalArgumentException if the string parameter is null
     * @throws UnsupportedEncodingException if the default HTTP charset is not supported.
     */
    public StringEntity(final String string)
            throws UnsupportedEncodingException {
        this(string, ContentType.DEFAULT_TEXT);
    }
```

This means that all messages are given a content type of `text/plain` which results in these headers being set on the request:

```
Content-Type: text/plain
charset=ISO-8859-1
```

With `ISO-8859-1` set as the charset, the following line in `StringEntity`'s constructor replaces unicode characters such as 吗 with an ascii question mark character: '?'

```java
            this.content = string.getBytes(charset.name());
```

The Amazon SNS service *does support* such unicode characters:

> Q: How much and what kind of data can go in a message?
> Amazon SNS messages can contain up to 256 KB of text data, including XML, JSON and unformatted text. The following Unicode characters are accepted:
> #x9 | #xA | #xD | x20 to #xD7FF | xE000 to #xFFFD | x10000 to #x10FFFF
> (according to http://www.w3.org/TR/REC-xml/#charsets).

(Note: The unicode value of 吗 is U+5417, which falls in the class `x20 to #xD7FF`.)

https://aws.amazon.com/sns/faqs/

> Amazon SNS supports the following logical data types:
> String – Strings are Unicode with UTF-8 binary encoding.

(Note: 吗 is representable with UTF-8 binary encoding)

http://docs.aws.amazon.com/sns/latest/dg/SNSMessageAttributes.html

The AWS Java SDK can be brought in line with the above documentation by updating the forementioned method chain to allow the specification of a ContentType or charset to be passed down to the construction of the `StringEntity`.

**Comment by varunnvs92** [comment]
Looking into this.

**Comment by zhangzhx** [comment]
Hi @coryfklein,

Sorry for the late reply. We had a major version bump to 1.11.x around May, but the related code in this case didn't change too much. I've tested both using 1.10.70 and 1.11.24, and I didn't see any problem delivering Unicode messages with Amazon SNS.

I dug into the code a bit and would explain why we don't need to deliver the ContentType or charset to the constructor of the `StringEntity`.

First, the http header Content-Type will not be set as what you mentioned: `Content-Type: text/plain; charset=ISO-8859-1`. (See the <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/request/impl/ApacheHttpRequestFactory.java#L194-L202">link</a> for the code). SNS is using query protocol which would not set the `Content-Type` header in `Request` in which case the actually `Content-Type` header would be 
`Content-Type: application/x-www-form-urlencoded; charset=utf-8`

As for the query parameter string passed to the `StringEntity`, it is url-encoded (see <a href="https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/request/impl/ApacheHttpRequestFactory.java#L68">here</a>) and will never have Unicode in the String which makes sense to use the default charset.

Do you see any encoding problem using SNS Java Client, such as the Unicode messages were not correctly delivered? If so, what SDK version are you using? If you can provide us some test data, we'd like to fix the problem. Thanks.

**Comment by coryfklein** [comment]
Sorry, my work has since moved me past this issue and I will likely not be coming back to it soon (if ever). I can't verify whether this issue still exists in our use of the Java client or provide any further information on the issue I was experiencing when I first created this issue.

Feel free to close the issue, if you so desire.

**Comment by zhangzhx** [comment]
Thanks for letting us know. I'm closing this issue for now, but feel free to open a new issue referencing this one if you still have problems.
