### ISSUE TITLE
[aws-java-sdk-kinesis] DescribeStreamRequest.setLimit Does Not Work

### ISSUE THREAD

**Issue by az3** [aws/aws-sdk-java#695]
Hello,

When a stream with more than 100 shards is queried, only first 100 is returned although setLimit/withLimit is set to a higher number. 

        com.amazonaws.services.kinesis.model.DescribeStreamRequest describeStreamRequest = new DescribeStreamRequest();
        describeStreamRequest.setStreamName("big-stream-with-500-shards");
        if (!isEmpty(startShardId)) {
            describeStreamRequest.setExclusiveStartShardId(startShardId);
        }
        describeStreamRequest.setLimit(9999); // TODO This might be broken
        DescribeStreamResult describeStreamResult = client.describeStream(describeStreamRequest);
        System.err.println(describeStreamResult.getStreamDescription().getShards().size()); // prints "100".

The documentation says limits less than 10000 is valid.

Thanks.

**Comment by varunnvs92** [comment]
I have verified that we are correctly passing the limit to service. I contacted the service team for further investigation. Will update you as soon as I receive a reply.

**Comment by varunnvs92** [comment]
Hi, This is the response I received from the service team.

**"The Limit parameter purely exists to control the "maximum". It is not a directive to return exactly "n" number of shards, nor does it represent a "minimum". We might return only 100 at a time currently, but this could change in the future. Customers should not make any assumptions on how many shards are returned in a call and should rely on the hasMoreShards flag to determine completeness of the response."**

As per their response, you can't rely on the limit to increase the number of shards returned. I know the docs do not mention this, so I suggested the service team to update the docs. 

I am closing the issue. Please feel free to re-open it if you have more questions. Thank you.

**Comment by az3** [comment]
Thanks. We will continue using the iteration approach with "ExclusiveStartShardId" as you suggested.
