### ISSUE TITLE
Creating a signed cookie using aws sdk

### ISSUE THREAD

**Issue by developer-codecraft** [aws/aws-sdk-java#698]
As of now, in AWS sdk we have a method CloudFrontUrlSigner.getSignedURLWithCannedPolicy() to generate signed url. But I have not come across any method or way to generate the signed cookies in java. Can anyone help me out or add the method to AWS SDK if it is not added yet?

**Comment by manikandanrs** [comment]
Are you looking for this

**Comment by manikandanrs** [comment]
Closing this as we have not received any response. Feel free to reopen.
