### ISSUE TITLE
Rationale for explicit maven dependency on httpcore?

### ISSUE THREAD

**Issue by jhovell** [aws/aws-sdk-java#702]
Is there a reason this project depends on both Apache httpclient and httpcore explicitly? httpcore is already a transitive dependency of httpclient and one would presume management of the versions between these dependencies is best left to httpclient and not explicitly overridden in the POM. For version 1.10.74, there is no difference in the version of httpcore being explicitly overridden and what httpclient specifies itself.

```xml
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>${httpcomponents.httpclient.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
      <version>${httpcomponents.httpcore.version}</version>
    </dependency>
```

This ends up causing Maven to make bad decisions about resolving conflicts when other libraries include a newer but compatible version of httpclient, leading to user confusion and the need to manually exclude httpcore from the aws-sdk-java-core dependency in their pom.

For example:
![screen shot 2016-05-03 at 11 10 21 am](https://cloud.githubusercontent.com/assets/1376570/14993913/f930e800-1121-11e6-961b-f228de0b0280.png)

Example downstream problem:
https://github.com/SunRun/cfn-response-java/issues/5

Just curious to get a rationale on this, or if there's a reason httpcore explicit dependency can't be removed from the POM.

CC @timmattison

**Comment by shorea** [comment]
Chatted with Tim and the team. We will make this change.

**Comment by shorea** [comment]
This has been staged internally and will be included in our next release.
