### ISSUE TITLE
S3: Suspected URL encode/decode problem when listing files

### ISSUE THREAD

**Issue by Rosch** [aws/aws-sdk-java#703]
We have a file in a S3 bucket called '**folder/Test+ file.xml**'.
We query '**folder**' for its content. In the returned list we find 
"**Test  file.xml**" (with 2 spaces) instead of '**Test+ file.xml**'.

We use SDK 1.10.72 and 1.10.69. Last version we can verify that it works is 1.10.2. We are now going back to 1.10.2 but are hoping that this gets fixed fast as we would like to upgrade to a recent version.

This is quite annoying...

**Comment by manikandanrs** [comment]
I just tested this in 1.10.72 and 1.10.69 and I am not able to reproduce this issue. Below is the code that I tried

`
final String bucketName = "";
final String fileName = "";
AmazonS3Client client = new AmazonS3Client();
client.putObject(bucketName, "Test+ file.xml", new File(fileName));
ObjectListing listing = client.listObjects(bucketName);
listing.getObjectSummaries().stream().forEach(s3ObjectSummary -> System.out.println
                (s3ObjectSummary.getKey()));
`
And I get Test+ file.xml

**Comment by manikandanrs** [comment]
Can you share a test code that simulates this issue ?

**Comment by manikandanrs** [comment]
Closing this as we have not heard back. Feel free to re open if you still face issues.
