### ISSUE TITLE
S3 User Meta Data uses case sensitive comparision

### ISSUE THREAD

**Issue by nathanabercrombie** [aws/aws-sdk-java#704]
See https://github.com/aws/aws-sdk-java/blob/18d2d604b0edb925f42eb1ef7492b87197ba9a58/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/AbstractS3ResponseHandler.java#L112

`if (key.startsWith(Headers.S3_USER_METADATA_PREFIX)) {`

This fails if the header is not cased the same as "x-amz-meta-", such as "X-Amz-Meta-".  RFC says that headers are case insensitive.  The rest of that method seems to respect RFC, but this part doesn't.

I would suggest using String.regionMatches http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#regionMatches%28boolean,%20int,%20java.lang.String,%20int,%20int%29 instead of toLower or toUpper

Discovered while trying to get https://github.com/jubos/fake-s3/ to work in a test environment.

**Comment by manikandanrs** [comment]
Yes. You are right. We need to fix this. Would you like to send us a PR ?

**Comment by nathanabercrombie** [comment]
https://github.com/aws/aws-sdk-java/pull/706

**Comment by manikandanrs** [comment]
PR merged.
