### ISSUE TITLE
SDK not honoring http.nonProxyHosts from Java

### ISSUE THREAD

**Issue by sebastiankirsch** [aws/aws-sdk-java#708]
Although in theory I like the new feature introduced with #596, this prevents us from updating to the latest SDK versions. This is because we are running integration tests against [Wiremock](wiremock.org) which is set up on localhost; so the SDK tries to access localhost via proxy (which doesn't work).
There is no way to bypass the proxy using `com.amazonaws.ClientConfiguration`, we also can't turn it off; there's no workaround coming to mind that would allow us to upgrade.

From what I can tell, `com.amazonaws.http.impl.client.SdkHttpClient` could define it's own `org.apache.http.conn.routing.HttpRoutePlanner` to bypass/select the proxy.

**Comment by zhangzhx** [comment]
Hi, thanks for reaching out to us. We'll consider to add this feature to our next releases. I'll let you know once it is published.

**Comment by zhangzhx** [comment]
Hi, we have released the support for nonProxyHosts. You can now either set the system property or explicitly set the ClientConfiguration to enable this. See the following link:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L753

**Comment by sebastiankirsch** [comment]
Awesome, it works! Thank you!
