### ISSUE TITLE
AWS.CognitoIdentityServiceProvider doesn't have authenticate API for User Pools

### ISSUE THREAD

**Issue by srkprasadam** [aws/aws-sdk-java#709]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html

AWS.CognitoIdentityServiceProvider doesn't have authentication API. I see that there are apis to signup, getting attributes for a user etc. It is surprising that there aren't APIs to authenticate, with the given username and password.

**Comment by manikandanrs** [comment]
You have to use Amazon Cognito Identity for authentication

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

**Comment by srkprasadam** [comment]
i am aware of that https://github.com/aws/amazon-cognito-identity-js/ which does the client side authentication. I compared the APIs available in both https://github.com/aws/amazon-cognito-identity-js/ and AWS.CognitoIdentityServiceProvider. They almost seem to have the same APIs, except for the authentication. What is the reason for not including in AWS.CognitoIdentityServiceProvider ? I want to avoid client side authentication and do everything on server side
