### ISSUE TITLE
Could you upgrade to a newer version of FasterXML/Jackson, 2.5 causes problems with scala

### ISSUE THREAD

**Issue by fabianmenges** [aws/aws-sdk-java#711]
https://github.com/aws/aws-sdk-java/blob/master/pom.xml

You are currently using version 2.5.3 of jackson. Because of different behavior concerning generics in Java and Scala, Jackson 2.5 contained breaking api changes only for scala projects. Newer versions of Jackson ( => 2.6) reverted back to pre 2.5 behavior. It would be great if you could upgrade to a more recent version.

See for https://github.com/FasterXML/jackson-module-scala/issues/201 for details.

Thanks

**Comment by breedloj** [comment]
Hey, thanks for reaching out to us and bringing this issue to our attention.  The latest version of the Java SDK (https://aws.amazon.com/releasenotes/Java/0023045637790667) is now using Jackson 2.6.6.  Please let us know if you continue to have any issues.
