### ISSUE TITLE
Bugs in ProfileCredentialsProvider class with a custom configuration file (version 1.11.0)

### ISSUE THREAD

**Issue by dscoppelletti** [aws/aws-sdk-java#713]
I run this code:

```
AWSCredentialsProvider provider = new ProfileCredentialsProvider(
    "/Users/dario/etc/aws/aws.ini", "dario");
```

If my `aws.ini` file is:

```
[default]
region=eu-west-1
output=json

[profile dario]
aws_access_key_id=...
aws_secret_access_key=...
region=eu-west-1
output=json
```

The code fails with the exception:

```
com.amazonaws.AmazonClientException: Unable to load credentials into profile [default]: AWS Access Key ID is not specified. at com.amazonaws.auth.profile.internal.ProfilesConfigFileLoader.fromStaticCredentials(ProfilesConfigFileLoader.java:109) at com.amazonaws.auth.profile.internal.ProfilesConfigFileLoader.loadProfiles(ProfilesConfigFileLoader.java:96) at com.amazonaws.auth.profile.internal.ProfilesConfigFileLoader.loadProfiles(ProfilesConfigFileLoader.java:58) at com.amazonaws.auth.profile.ProfilesConfigFile.loadProfiles(ProfilesConfigFile.java:214)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:139)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:128)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:104)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.<init>(ProfileCredentialsProvider.java:115)
```

I don't like to put credentials in default profile, and why the `ProfileCredentialsProvider` constructor looks for the default profile?

However, if my `aws.ini` file is:

```
[default]
aws_access_key_id=...
aws_secret_access_key=...
region=eu-west-1
output=json

[profile dario]
aws_access_key_id=...
aws_secret_access_key=...
region=eu-west-1
output=json
```

The `ProfileCredentialsProvider` constructor runs properly, but if I try to use these credentials (for example, with S3 client), the following exception is thrown:

```
java.lang.IllegalArgumentException: No AWS profile named 'dario'
     at com.amazonaws.auth.profile.ProfilesConfigFile.getCredentials(ProfilesConfigFile.java:148)
     at com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:185)
```

In order to use my credentials, I have to remove the `profile` prefix from `aws.ini` file:

```
[default]
aws_access_key_id=...
aws_secret_access_key=...
region=eu-west-1
output=json

[dario]
aws_access_key_id=...
aws_secret_access_key=...
region=eu-west-1
output=json
```

I have not inspected if the other settings (i.e. `region` and `output`) are recognized without `profile` prefix.
However, with my original `aws.ini` file (no credentials in default profile and `profile` prefix in other profiles), the AWS CLI runs properly.

**Comment by manikandanrs** [comment]
Though CLI supports different configurations in the file, most SDKs supports only credentials from the file. Hence the SDKs fails to load when it sees a profile without a credentials information configured.

The file that you are using is CLI specific and may contain configurations specific to CLI. Our recommendation is to store credentials separately and CLI specific configuration separately.

http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files

To answer your second question, as per the format of the credentials file, profile keyword should not be present. CLI is supporting this for backwards compatibility

https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs
