### ISSUE TITLE
AmazonS3URI: Support Version and ETag in URI

### ISSUE THREAD

**Issue by kohidave** [aws/aws-sdk-java#714]
Often, the S3 URI contains the version and etag as url parameters. It'd be awesome if AmazonS3URI supported parsing those out (if present), as well as the bucket and key.

**Comment by breedloj** [comment]
Thanks for the feature request.  This has been added in PR #715 (https://github.com/aws/aws-sdk-java/pull/715) and will be included with our next SDK release.
