### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [aws/aws-sdk-java#719]
Hi

The following source files are without license headers:

./aws-java-sdk-api-gateway/src/main/java/com/amazonaws/services/apigateway/internal/AcceptJsonRequestHandler.java

./aws-java-sdk-cloudfront/src/main/java/com/amazonaws/services/cloudfront/util/SignerUtils.java

./aws-java-sdk-codegen-maven-plugin/src/main/java/com/amazonaws/codegen/maven/plugin/ClassPathUtils.java

./aws-java-sdk-core/src/main/java/com/amazonaws/http/conn/ssl/ShouldClearSslSessionPredicate.java
./aws-java-sdk-core/src/main/java/com/amazonaws/http/timers/package-info.java
./aws-java-sdk-core/src/main/java/com/amazonaws/log/InternalLogFactory.java
./aws-java-sdk-core/src/main/java/com/amazonaws/protocol/json/SdkStructuredJsonFactory.java
./aws-java-sdk-core/src/main/java/com/amazonaws/handlers/IRequestHandler2.java
./aws-java-sdk-core/src/main/java/com/amazonaws/internal/DateTimeJsonSerializer.java
./aws-java-sdk-core/src/main/java/com/amazonaws/util/FakeIOException.java
./aws-java-sdk-core/src/test/java/com/amazonaws/AmazonWebServiceRequestTest.java
./aws-java-sdk-core/src/test/java/com/amazonaws/SDKGlobalConfigurationTest.java
./aws-java-sdk-core/src/test/java/com/amazonaws/TestPreConditions.java
./aws-java-sdk-core/src/test/java/com/amazonaws/auth/AbstractAWSSignerTest.java
./aws-java-sdk-core/src/test/java/com/amazonaws/http/conn/ssl/ShouldClearSslSessionsPredicateTest.java
./aws-java-sdk-core/src/test/java/com/amazonaws/http/timers/TimeoutTestConstants.java
./aws-java-sdk-core/src/test/java/com/amazonaws/internal/config/InternalConfigTest.java
./aws-java-sdk-core/src/test/java/com/amazonaws/util/CollectionUtilsTest.java

./aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/marshallers/package-info.java
./aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/unmarshallers/package-info.java
./aws-java-sdk-dynamodb/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/GenerateDeleteTableRequestTest.java

./aws-java-sdk-emr/src/main/java/com/amazonaws/services/elasticmapreduce/spi/EMRFSAnnotationProvider.java

./aws-java-sdk-lambda/src/main/java/com/amazonaws/services/lambda/invoke/package-info.java
./aws-java-sdk-lambda/src/main/java/com/amazonaws/services/lambda/invoke/LambdaInvokerFactoryConfig.java

./aws-java-sdk-logs/src/main/java/com/amazonaws/services/logs/internal/AcceptJsonRequestHandler.java

./aws-java-sdk-osgi/src/main/javadoc/com/amazonaws/JavaDoc.css
./aws-java-sdk-osgi/src/main/javadoc/resources/styles/aws-docs.css

./aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java
./aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/WebsiteConfiguration.java

./aws-java-sdk-simpleworkflow/src/main/java/com/amazonaws/services/simpleworkflow/model/PredefinedDuration.java

./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/DynamicActivitiesClientImpl.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/core/AsyncTaskInfo.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/generic/TerminateWorkflowExecutionParameters.java

./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/interceptors/AsyncExecutor.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/interceptors/AsyncRetryingExecutor.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/interceptors/AsyncRunnable.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/interceptors/AsyncScheduledExecutor.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/interceptors/FixedIntervalInvocationSchedule.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/interceptors/InvocationSchedule.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/junit/FlowBlockJUnit4ClassRunner.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/junit/WorkflowTestStatement.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/junit/spring/FlowSpringJUnit4ClassRunner.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/spring/CronDecorator.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/spring/CronInvocationSchedule.java
./aws-java-sdk-swf-libraries/src/main/java/com/amazonaws/services/simpleworkflow/flow/spring/POJOWorkflowStubImplementationFactory.java

./aws-java-sdk-test-utils/src/main/java/com/amazonaws/test/util/InputStreamUtils.java
./aws-java-sdk-test-utils/src/main/java/com/amazonaws/test/util/SdkAsserts.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by manikandanrs** [comment]
All the source files are shipped under Apache 2.0 license. We will get the license headers added to these files.

**Comment by manikandanrs** [comment]
The repository has a license.txt file that you can refer for more information.

https://github.com/aws/aws-sdk-java/blob/master/LICENSE.txt

**Comment by puntogil** [comment]
To avoid confusion should be remove this line from NOTICE.txt file
"- JSON parsing and utility functions from JSON.org - Copyright 2002 JSON.org."
(https://github.com/aws/aws-sdk-java/issues/423 is fixed)

**Comment by shorea** [comment]
Good catch. This will be removed in the next release.

**Comment by varunnvs92** [comment]
@puntogil 
Added license headers for the files in this repo. The only files without headers are files from aws-java-sdk-swf-libraries module. We recently moved this module to a [new git repo](https://github.com/aws/aws-swf-flow-library). I opened a new issue in that repo: https://github.com/aws/aws-swf-flow-library/issues/7

Closing this issue. Feel free to reopen if you have more questions. Thank you.
