### ISSUE TITLE
Disable/Enable IdleConnectionReaper through ClientConfiguration options

### ISSUE THREAD

**Issue by lc-nyovchev** [aws/aws-sdk-java#72]
In restricted environments it is very rare that a codebase has the modifyThread and modifyThread group permission. In order to accomodate for that, it would be nice if the IdleThreadReaper constructor took the ClientConfiguration options and avoided modifying the thread to a daemon thread.

**Comment by zhaoxi2000** [comment]
> Hi, this has been implemented in version 1.6.5

Hi, How to do it for disabling?
