### ISSUE TITLE
CloudFormation: Missing functionality to remove all tags on updateStack() request

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#721]
According to the docs of [UpdateStackRequest#setTags(Collection\<Tag\> tags)](https://github.com/aws/aws-sdk-java/blob/9243e0716bc2a649085480d3a4fb7606b6541da3/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/model/UpdateStackRequest.java#L1656), I should be able to remove all tags during an update by passing an empty value:

> If you don't specify this parameter, AWS CloudFormation doesn't modify the stack's tags. If you specify an empty value, AWS CloudFormation removes all associated tags.

However, passing an empty `Collection<Tag>` (or `null`) does not result in the expected removal of all tags, but seems to be simply ignored (changing tags by passing a non empty collection works as expected).

Looking at the tag request parameter assembly code in [UpdateStackRequestMarshaller#marshall() (line 173ff.)](https://github.com/aws/aws-sdk-java/blob/a51792ec9d34263c12de5231131b42bd7dc544d9/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/model/transform/UpdateStackRequestMarshaller.java#L173), I can not find any indication of the required distinction between the parameter not being specified at all ('keep existing tags') vs. setting it to an empty value ('remove all tags') - it looks like both cases are treated as 'not specified at all', i.e. no parameter is being set, resulting in the existing tags being kept.

Am I missing something here or could this be a bug/oversight in the Java SDK?

(As a cross check, calling [update-stack](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack.html) with an empty `--Tags` parameter from the AWS CLI works as advertised, i.e. I can remove all tags during an update successfully.)

**Comment by varunnvs92** [comment]
@hopel 
I was able to reproduce the issue. After discussion with my team, it seems like this is a known issue as it is difficult to differentiate between explicit null(customer setting null value) and implicit null(Java defaults to null value for objects). 

AmazonCloudFormationClient is auto-generated from the service model. We don't handwrite this code. We have to see if its possible to just change this behavior without affecting other auto-generated clients. We decided to have more discussion on this issue next week. I will get back to you once we come up with an answer. 

Thanks for bringing this up. Feel free to share your thoughts.

**Comment by hopel** [comment]
@varunnvs92 - thanks for the update. Regarding the 'explicit vs. implicit null' value problem, I think this could/should be sidestepped by relying on an empty `Collection<Tag>` to signal the removal intent. IMHO, that would match the doc part of "specifying an empty value", and would also fit semantically, i.e. one would basically just overwrite the existing Tag collection with an empty one.

As for the code generation topic, I see the problem and can not really add much to the discussion without knowing the details of that generation process. (Though I would have assumed that this is not the first 'special case' issue in the API that requires some kind of tweaking option for the generation logic?)

**Comment by shorea** [comment]
Thanks for reporting this. We will have this fixed in our next release, tentatively scheduled for next Tuesday.

**Comment by shorea** [comment]
This is will be fixed in today's release. Preemptively closing issue.
