### ISSUE TITLE
s3 how to create folder by java sdk

### ISSUE THREAD

**Issue by wzhonggo** [aws/aws-sdk-java#724]
Hi

I am newer for aws s3, i can upload file to s3 bucket, but can not find s3 java  api to create folder.
I hava search google, but can not find solution.  It is file not folder by use this  java code.
Anyone can help me.

```java
        String dirName = "demo";
        String existingBucketName = "bucket1";
        ClientConfiguration configuration = new ClientConfiguration();
        AmazonS3 amazonS3 = new AmazonS3Client(new    BasicAWSCredentials("accessKey", "secretKey"), configuration);
        configuration.setConnectionTimeout(120 * 1000);
        configuration.setSocketTimeout(120 * 1000);

        PutObjectRequest por2 = new PutObjectRequest(existingBucketName,
                dirName, new ByteArrayInputStream(new byte[0]), null);
        por2.setCannedAcl(CannedAccessControlList.PublicRead);
        PutObjectResult r2 = amazonS3.putObject(por2);
```

**Comment by varunnvs92** [comment]
Hi @wzhonggo 
You can use [TransferManager](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#uploadDirectory(java.lang.String,%20java.lang.String,%20java.io.File,%20boolean)) to upload a directory(folder) to an Amazon S3 bucket.

Here is a sample code that uploads a folder with name "sampleFolder" to a bucket "bucket-name" in S3. 
```
TransferManager tm = new TransferManager();
MultipleFileUpload upload = tm.uploadDirectory(
                                   "bucket-name",
                                   "sampleFolder",
                                    new File("/Users/myusername/Documents/sampleFolder"),
                                    true);
upload.waitForCompletion();
tm.shutdownNow();
```
I hope this answers your question. Feel free to contact us if you have more questions.

**Comment by wzhonggo** [comment]
Thank you very much , this code is can upload folder
