### ISSUE TITLE
ReleaseLabel support in RunJobFlowRequest

### ISSUE THREAD

**Issue by arindamnayak** [aws/aws-sdk-java#729]
I have used "com.amazonaws:aws-java-sdk-bom:1.11.6" , but I am not able to define ReleaseLabel in "RunJobFlowRequest" object. I am only able to set "AMIVersion". Even though I have used latest version of aws sdk, I am not able to do so. Please advise.

**Comment by manikandanrs** [comment]
I see them in the late source code [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-emr/src/main/java/com/amazonaws/services/elasticmapreduce/model/RunJobFlowRequest.java#L547-L604). 

Are you pulling in the correct version of the SDK ?

**Comment by arindamnayak** [comment]
Yes, I can see there in github source code. Here is my gradle config.

```
buildscript {
	ext {
		springBootVersion = '1.3.5.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("io.spring.gradle:dependency-management-plugin:0.5.4.RELEASE")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'spring-boot'
apply plugin: "io.spring.dependency-management"

dependencyManagement {
    imports {
        mavenBom 'com.amazonaws:aws-java-sdk-bom:1.11.6'
    }
}

jar {
	baseName = 'cm-cockpit'
	version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.7
targetCompatibility = 1.7

repositories {
	mavenCentral()
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
	compile('org.springframework.boot:spring-boot-starter-web')
    compile('com.amazonaws:aws-java-sdk-s3')
	compile('com.amazonaws:aws-java-sdk-ec2')
    compile('com.amazonaws:aws-java-sdk-emr')
	runtime('mysql:mysql-connector-java:5.1.10')
//	compile group: 'org.projectlombok', name: 'lombok', version: '1.16.8'
	runtime('org.postgresql:postgresql')
	testCompile('org.springframework.boot:spring-boot-starter-test')
	testCompile('com.fasterxml.jackson.module:jackson-module-jsonSchema:2.5.2')
//    runtime('org.apache.tomcat.embed:tomcat-embed-jasper')
	compile group: 'commons-lang', name: 'commons-lang', version: '2.6'
}
```

In gradle dependency jars, I can see that emr has got 1.9.0 version - "com.amazonaws:aws-java-sdk-emr:1.9.0" . Not sure, why it is not pulling latest version 1.11.6.

**Comment by manikandanrs** [comment]
I just tried with this config. I am able to see 1.11.6 jar in my dependency tree

![screen shot 2016-06-07 at 8 57 27 am](https://cloud.githubusercontent.com/assets/2710935/15865015/06dbfb20-2c8e-11e6-8400-7be20aef4b49.png)

Can you clean and re build again ?

**Comment by arindamnayak** [comment]
Thanks. It worked. Invalidated cache and restarted IntelliJ , then it worked .

**Comment by manikandanrs** [comment]
Glad to hear.
