### ISSUE TITLE
iam GetPolicyRole returns encoded policy document

### ISSUE THREAD

**Issue by nickwhiggins** [aws/aws-sdk-java#730]
When requesting an existing role policy using the iam client
```
iamClient.getRolePolicy(new GetRolePolicyRequest()
.withPolicyName('foo')
.withRoleName('bar')
).getPolicyDocument()
```
 the returned policy document is encoded and resembles the following: 

> %7B%22Version%22%3A%222012-10-17%22%2C%22Statement%22%3A%5B%7B%22Sid%22%3A%22Stmt1465345522686%22%2C%22Effect%22%3A%22Allow%22%2C%22Action%22%3A%5B%22dynamodb%3ABatchGetItem%22%2C%22dynamodb%3ABatchWriteItem%22%2C%22dynamodb%3ADeleteItem%22%2C%22dynamodb%3ADescribeTable%22%2C%22dynamodb%3AGetItem%22%2C%22dynamodb%3AListTables%22%2C%22dynamodb%3APutItem%22%2C%22dynamodb%3AQuery%22%2C%22dynamodb%3AScan%22%2C%22dynamodb%3AUpdateItem%22%2C%22dynamodb%3AUpdateTable%22%5D%2C%22Resource%22%3A%5B%22arn%3Aaws%3Adynamodb%3Aap-southeast-2%3A%3Atable%2Fnwh-test-2-1465345522686%22%2C%22arn%3Aaws%3Adynamodb%3Aap-southeast-2%3A%3Atable%2Fnwh-test-2-1465345522686%2F%2A%22%2C%22arn%3Aaws%3Adynamodb%3Aus-west-2%3A%3Atable%2Fnwh-test-2-1465345522686_replica%22%2C%22arn%3Aaws%3Adynamodb%3Aus-west-2%3A%3Atable%2Fnwh-test-2-1465345522686_replica%2F%2A%22%5D%7D%5D%7D

as opposed to the json string I was expecting.

I am using version 1.11.7 of the sdk but it was also in 1.10.71 & 1.11.0.

**Comment by shorea** [comment]
It appears to be URL encoded on the wire was well and we don't do any special decoding client side. Engaging service team to see if this is a regression or behavior change. 

As a short term workaround you can use URLDecoder.decode(policy, StandardCharsets.UTF_8.name())

**Comment by shorea** [comment]
Service team confirmed the URL encoded document is expected behavior.
