### ISSUE TITLE
Implement Closeable or AutoCloseable by clients

### ISSUE THREAD

**Issue by flozano** [aws/aws-sdk-java#733]
`AmazonWebServiceClient` and its children declare a "shutdown" method; however, this method doesn't belong to any interface and it's difficult to automate detection of closeable resources that need clean-up.

It would be great if this class implemented `Closeable`/`AutoCloseable` (and even better if the client interfaces did it themselves too - `AmazonSQS`, `AmazonDynamoDB`), with a method like:

``` java
    public void close() {
        this.shutdown();
    }
```

This way, containers such as Spring would automatically detect that these components need to be closed, and handle shutdown in a cleaner way. (edit: in this example, Spring should already detect that the "public void shutdown" method should be called, but it's pretty obscure and it'd be better to make it explicit by implementing the right interface).

**Comment by shorea** [comment]
We do support Java6 still, not sure if we can actually do this as it means we can't compile against Java6 anymore (although it might still work at runtime if we compile into Java6 compatible bytecode)

**Comment by flozano** [comment]
Thanks for considering it. `java.io.Closeable` is available since Java 5, so I guess it should be fine: https://docs.oracle.com/javase/1.5.0/docs/api/java/io/Closeable.html

**Comment by shorea** [comment]
Good call, I was looking at AutoCloseable. We should be able to accommodate this then.

**Comment by shorea** [comment]
I was thinking more about this and I'm not super enthusiastic about how coupled Closeable seems to input streams. AutoCloseable seems like the right abstraction to use and has the benefit of try with resources support. I'm leaning towards deferring supporting this until we drop Java6 support and can just use AutoCloseable.

**Comment by flozano** [comment]
AutoCloseable is the right abstraction, but it's not available in Java 6. I think Closeable is a good compromise, which also supports try( ) { } in Java 7+, because Closeable extends AutoCloseable from Java 7 onwards.
https://docs.oracle.com/javase/7/docs/api/java/io/Closeable.html

so, you get the benefits of try-with-resources in Java 7, but you're still compatible with Java 6. 

It's just an interface, so I don't see the problem with the supposed coupling to java.io... also many other non-Input/Output-stream classes implement it from the java SE standard library:
 - Sockets
 - NIO channels 
 - Formatters

and, from the classpath of my project, there are many diverse classes implementing it:
 - Redis client (jedis)
 - Guava tools to cleanup resources
 - SQL data-sources (hikari)
 - JSON parsers (jackson, gson)
 - MongoDB client

I think Closeable original intention maybe was related to I/O, but it's not anymore. Other artifacts had the same fate in Java - for example, TimeUnit - which is in java.util.concurrent but that doesn't preclude everyone from using it whenever it's needed.

**Comment by shorea** [comment]
@flozano I don't think we will be taking this on in V1 due to the friction it will cause (may implement these client interfaces). We are ramping up on a V2 of the Java SDK and this definitely will be included.
