### ISSUE TITLE
withLimit on DynamoDBQueryExpression does not work using DynamoDBMapper

### ISSUE THREAD

**Issue by markathomas** [aws/aws-sdk-java#736]
Setting a limit value on DynamoDBQueryExpression using withLimit(100) returns more than 100 results

**Comment by markathomas** [comment]
using version 1.10.52

**Comment by markathomas** [comment]
note: this is with using query(); using queryPage() works fine with limit

**Comment by zhangzhx** [comment]
Hey @markathomas,

The **limit** parameter in DynamoDBQueryExpression is used in the pagination purpose. As per the [query doc](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html#query(java.lang.Class,%20com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBQueryExpression,%20com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig)), it returns a **PaginatedQueryList** which is loaded on demand. However, for each load, it will fetch **limit** number of items.

Here is the doc for **PaginatedQueryList**:

_Implementation of the List interface that represents the results from a query in AWS DynamoDB. Paginated results are loaded on demand when the user executes an operation that requires them. Some operations, such as size(), must fetch the entire list, but results are lazily fetched page by page when possible._
