### ISSUE TITLE
AmazonCloudWatchEventsClient#putTargets doesn't add the event as a source for lambda

### ISSUE THREAD

**Issue by frapontillo** [aws/aws-sdk-java#737]
I am using the AWS Java SDK to successfully create a CloudWatch Schedule Rule and apply an already existing lambda ARN as the only Rule Target.
If I go to the AWS Web UI, I can also see that the Rule exists and that my lambda is correctly set as a target.

The issue is that **the lambda never gets called!** In fact, if I go to my lambda's event sources, **there is no Rule** there... If I try to add the same Rule that I added with the Java SDK, I get the error: "There was an error creating the event source mapping: This function is already attached to the schedule job-banana1465836106". See a screenshot here:

<img width="858" alt="screenshot 2016-06-13 17 43 28" src="https://cloud.githubusercontent.com/assets/1140238/16040355/ee6d74bc-3226-11e6-91bf-228bd71f9202.png">

This is definitely a bug, but I can't say if it's related to the Java SDK (doubtfully) or to the Web services being called.

Can someone please look into this?

**Comment by zhangzhx** [comment]
Thanks for reaching out to us. I've tested with AWS CLI and it has the same problem. I can successfully create AWS Events Rule and target but the corresponding target Lambda function doesn't have the event source on AWS Console. I suspect it be a problem of AWS Console. I will reach out to them and also the service team.

**Comment by zhangzhx** [comment]
Hi, here is what the service team replied:

_It seems like customer doesn't add permission to their lambda function to allow CloudWatch Events(events.amazonaws.com) to invoke this function when the rule triggers._

_I believe that Lambda console is looking at the policy statement for determine what even sources are attached and since the policy doesn't have "events.amazonaws.com" and the rule name, the lambda console doesn't render event source properly. 
This is likely a bug in the Lambda console._

_Regarding setting up the permissions correctly: 
Please reply customer that they can add permission by following instructions here:_
http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html 
_And here is some further explanation about managing permissions for allowing CloudWatch Events to send events:_
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/EventsResourceBasedPermissions.html

I will let you know when the Lambda console team replies this problem.

**Comment by frapontillo** [comment]
So, just to get this straight:

1. I have enabled scheduled events on my lambda as described [here](http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html)
2. The lambda function is now triggering with my programmatically created Rule
3. The Rule still doesn't show up in the Lambda Event Sources Web console, which is an issue as you mentioned

One question: why are the Rules created from the Rule Web console working correctly and do show up in the Lambda Event Sources page? Did I understand correctly that the Web UI also attaches a custom policy to the lambda specifying the exact name of the created Rule instead of the generic `events.amazonaws.com` source?

For future reference, I have now attached the following policy to my lambda:
```
aws lambda add-permission \
    --statement-id 'Allow-scheduled-events' \
    --action 'lambda:InvokeFunction' \
    --principal 'events.amazonaws.com' \
    --function-name function:my-target-lambda
```
This policy **does not** include a specific Rule name, so it should allow all created Rules to trigger it, correct?

To complete the issue description, if I now try to attach a Rule (for which the lambda is already a target) as an event source for the Lambda itself, it returns a new error message: "There was an error creating the event source mapping: Could not create scheduled-event event source" (see screenshot):

![image](https://cloud.githubusercontent.com/assets/1140238/16111783/0288f2ec-33ac-11e6-8e6f-064e20deb425.png)

**Comment by jgangemi** [comment]
i spent a bunch of time trying to do this using `terraform` yesterday. the aws docs on all of this are very confusing but you need a topic, topic subscription, and the lambda permission for this to work.

if you want your lambda to write logs properly, you also need to make sure whatever role you've assigned to the lambda function also has this role `AWSLambdaBasicExecutionRole` or something equivalent.

**Comment by zhangzhx** [comment]
Hi frapontillo,

The following is the answer to your question from the AWS Console team:

_Yes. When a customer creates a CloudWatch Events trigger from the Lambda console, we will add a resource policy statement that specifies the exact ARN of the rule. When adding a permission manually, not specifying the rule ARN means the Lambda console will not be able to discover the "source" of the event (only that it comes from CloudWatch Events). This is likely to result in undefined UI behavior._

So you have to specify `--source-arn` parameter to `add-permission` command to attach the rule to the Lambda function as the Event Sources. I've tested this and the rule will show up in the Event Sources tab of the Lambda console.

Here is related doc they updated to clarify this behavior.
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/RunLambdaSchedule.html

**Comment by frapontillo** [comment]
@zhangzhx thank you for helping me debug this!

**Comment by zhangzhx** [comment]
No problem. If you don't have further questions, I will close this issue.

**Comment by frapontillo** [comment]
Closing it, thanks! :+1:
