### ISSUE TITLE
No API for getting HealthCheck name

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#738]
com.amazonaws.services.route53.model.HealthCheck don't have any way to get the object name

**Comment by shorea** [comment]
From their service documentation I don't see that HealthCheck has a name. Is Id what you are looking for?

http://docs.aws.amazon.com/Route53/latest/APIReference/API_GetHealthCheck.html

**Comment by bmagic39** [comment]
this is what I'm sying. it is missing from API
in AWS Console you can provide a name (e.g. when creating such HealtCheck)

**Comment by shorea** [comment]
I've forwarded the request to the service team, I'll let you know what I hear.

**Comment by shorea** [comment]
Response from service team.
```
Health check names are not part of health check configuration. They are tags that can be Create/Update/Delete/List by Route53 tag API:

Whenever you assign a name to health check, say "yourHealthCheckName", we create a tag on the health check with key="name" and value="yourHealthCheckName"
The tag has resource type TagResourceType.HealthCheck and its ID is your health check ID.

To list health check's tags:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services...

To create/update/delete health check's tag:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services...
```

**Comment by shorea** [comment]
Those health check name, they are not part of health check configuration. They are tags that can be Create/Update/Delete/List by Route53 tag API:

Whenever you assign a name to health check, say "yourHealthCheckName", we create a tag on the health check with key="name" and value="yourHealthCheckName"
The tag has resource type TagResourceType.HealthCheck and its ID is your health check ID.

To list health check's tags:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services...

To create/update/delete health check's tag:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services...

**Comment by bmagic39** [comment]
thank you. got it
