### ISSUE TITLE
Region.createClient should support RequestMetricCollector param

### ISSUE THREAD

**Issue by kohidave** [aws/aws-sdk-java#739]
In [Region.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Region.java#L128
), you can create a AmazonWebServiceClient, which a credential provider and configuration. While the service classes also have a third parameter available, [RequestMetricCollector](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/RequestMetricCollector.html) - we can not provide that through the Region static constructor.

**Comment by shorea** [comment]
We are thinking of deprecating this approach soon in favor of a new style of client creation in the works. You can customize this via the three arg constructor on the client class itself though.
