### ISSUE TITLE
Provide replacement for SDKGlobalConfiguration.ENABLE_S3_SIGV4_SYSTEM_PROPERTY

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-sdk-java#740]
This is now deprecated as of 1.11.0, yet I can't seem to find the equivalent functionality nor is an alternative documented. We have an S3 mock and need a way to disable this when talking to it. That property was working great up to and including 1.10.77.

**Comment by breedloj** [comment]
Hey Axel, thanks for reaching out to us.  This property was deprecated as in 1.11.x we moved to use SigV4 by default in S3.  If you need to explicitly set the signer used for your mock you can also achieve this through a ClientConfiguration option (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L1379-L1401).  The options for S3 are defined in the client impl (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L185-L186).  Keep in mind that SigV2 is effectively a deprecated signing method and support for it will eventually be removed altogether in a future major version bump.

**Comment by axelfontaine** [comment]
Hi Jonathan,

Thanks! Using `new AmazonS3Client(new ClientConfiguration().withSignerOverride("NoOpSignerType"))` worked great.

Just so you know, you have a bug in https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L185 as it should be **AWS**S3SignerType according to the constants in SignerFactory. You may want to extract this into an enum to avoid such issues in the future.

Cheers
Axel

**Comment by fernomac** [comment]
[AWS3SignerType](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/SignerFactory.java#L27) (only one 'S') is the signer for AWS signature version 3, which never really went anywhere. `S3SignerType` is the similarly-named (sorry) signer for S3's nonstandard flavor of signature version 2, and is what you would want in this case. :+1: for an enum though.
