### ISSUE TITLE
Many log messages "Count must be at least one"

### ISSUE THREAD

**Issue by cch1** [aws/aws-sdk-java#741]
We are seeing a high frequency of these messages being logged from 

`com.amazonaws.metrics.internal.cloudwatch.PredefinedMetricTransformer`

Is this normal?  I can find no documentation for this error.  Might it be caused by enabling system metrics when not running on an EC2 instance?  If so, should there not be more strident warnings?  If not, then why not tone this message down.

**Comment by shorea** [comment]
I'll lower this down to debug.

**Comment by shorea** [comment]
This will be included in our next SDK release.
