### ISSUE TITLE
com.amazonaws.regions.ServiceAbbreviations deprecation

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#743]
Hi
In version 1.11.x, the com.amazonaws.regions.ServiceAbbreviations was deprecated, and pointing to use  AmazonWebServiceClient.getEndpointPrefix() instead. Nice and very good
But I think the getEndpointPrefix() should be added to the relevant Interfaces (e.g. AmazonEC2 interface)

The following code will not work (as used to the at the previous versions):
		AmazonEC2 awsClient = new AmazonEC2Client(credentials);
		awsClient.getEndpointPrefix();

it should be changed to:
		AmazonEC2Client awsClient = new AmazonEC2Client(credentials);
		awsClient.getEndpointPrefix();

I think this is bad programming practice to work with the class not the interface

**Comment by zhangzhx** [comment]
It is a breaking change to introduce a new method to the interface. Although we don't recommend customers to implement the interface directly, it is still risky. We'll talk about this on our next team meeting and get back to you.

**Comment by shorea** [comment]
@bmagic39 what's your use case for using endpoint prefix? Just want to understand how you are using it so we know how best to expose it.

**Comment by bmagic39** [comment]
Let's say that I'm scanning all regions to load all Directories in those regions
so in order not to get exceptions during load, I need to validate if Region supports this service

 AmazonEC2 awsClient = new AmazonEC2Client(credentials);
Region region = .....
if (region.isServiceSupported(awsClient.getEndpointPrefix()) == false)
     return null;
awsClient.describeDirectoriesAsync....
... load ...

this was done with ServiceAbbreviations at the previous versions

**Comment by zhangzhx** [comment]
Hey @bmagic39,

We have exposed the constant ENDPOINT_PREFIX to each of the client interface. Take EC2 as example, you can use AmazonEC2.ENDPOINT_PREFIX for the service abbreviation. See

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/AmazonEC2.java#L43

**Comment by bmagic39** [comment]
Then please fix the deprecation comment to point to this option instead isServiceSupported

**Comment by zhangzhx** [comment]
Thanks for pointing out that. Will fix the comment in our next release.

**Comment by zhangzhx** [comment]
This has been fixed and will be in the next release.
