### ISSUE TITLE
getName for SQS

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#744]
Hi 
Could not find a way to get the SQS name
The listQueues return url
The getQueueAttributes returns map of attributes, but none include the name as attribute, is it part of the Arn
If you look at the AWS Console, you see the name is different attribute that Arn
Please provide a way to get the Queue name (e.g. listQueues to return Queue object with getName method)

**Comment by zhangzhx** [comment]
This is a similar issue to <a href="https://github.com/aws/aws-sdk-java/issues/745">#745</a>. I can reach out to the service team to see if they have plan to add this.

For my best knowledge, you can fetch the name from the last part of the URL which doesn't seem to be a big deal.

**Comment by zhangzhx** [comment]
You can parse the URL to fetch the name for now. The service team had added this to their backlog.
