### ISSUE TITLE
getName for SNS Topic

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#745]
Hi
Could not find a way to get the SNS name
The com.amazonaws.services.sns.model.Topic returned from listTopics method, include only Arn but not name
If you look at the AWS Console, you see the name is different attribute that Arn
Please add getName to Topic class

**Comment by zhangzhx** [comment]
The client code is auto-generated from the service model. See the model here https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/resources/models/sns-2010-03-31-model.json.

The service team is maintaining this model and I can reach out to them to see if they have plan to add this field to Topic class.

**Comment by bmagic39** [comment]
you please, do that

**Comment by zhangzhx** [comment]
They have added this to their backlog. For now, you could parse the topic name out of the ARN that is returned. This could change in the future, but it unlikely to any time soon.

I'm closing this issue for now as it relates to the service team.
