### ISSUE TITLE
Trying to update too many Load Balancers/Target Groups at once. The limit is 10

### ISSUE THREAD

**Issue by danieljamesscott** [aws/aws-sdk-java#746]
Hi,

We've suddenly started encountering this:

com.amazonaws.AmazonServiceException: Trying to update too many Load Balancers/Target Groups at once. The limit is 10

The request object looks like this:

DetachLoadBalancersRequest:{AutoScalingGroupName: devvpn-qa9-other-services-asg,LoadBalancerNames: [3d007fc1442747a2a7b099be01
fc465b]}

Admittedly, we're running threads in parallel, so there are several individual requests to detach ELBs from the same ASG, but that doesn't seem to be what the error is saying. As you can see from the request, it's only modifying one ELB.

I see that there's a 'detach' limit of 10:

http://docs.aws.amazon.com/autoscaling/latest/userguide/as-account-limits.html

But that would be 'per-request', right, as the limit per ASG defaults to 50.

Can anyone help?

EDIT: I have created a script, running a loop which creates a new request to attach an ELB to an ASG, I receive the AmazonServiceException exception after 10 requests - please can someone confirm if this is expected behaviour? How long must I wait before my requests would not be considered simultaneous?

Thanks,

Dan

**Comment by shorea** [comment]
@danieljamesscott I've forwarded your question to the service team. I'll let you know when I hear back.

**Comment by shorea** [comment]
Reply from the service team.

> When load balancers are attached or detached from an Auto Scaling group, a background process works on registering or deregistering all EC2 instances from these load balancers. Until this process is complete for a newly attached or detached load balancer, it is considered as a load balancer that is being updated and is counted towards your limit of 10.

**Comment by danieljamesscott** [comment]
Thanks for this - is there a published 'wait time' after which I can expect requests to start succeeding again? Or do I have to catch the exception in my code and loop?
