### ISSUE TITLE
 Getting access to Workspaces dates through API 

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#747]
Hi
Can you please expose the Workspace & WorkspaceBundle creation date and updated date through the Java API??
e.g. looking at com.amazonaws.services.workspaces.model.WorkspaceBundle I could not find a way getting this information

**Comment by shorea** [comment]
I'm not seeing those parameters in Workspace's API reference. Is this a feature request to surface this parameters in the API?

**Comment by bmagic39** [comment]
yes. please add those to the API if possible

**Comment by shorea** [comment]
I've opened an issue with the service team to triage.

**Comment by shorea** [comment]
Service team has added this to their backlog. Closing this ticket for now and will comment when I hear that it's been implemented.
