### ISSUE TITLE
Presigning non-S3 requests

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-sdk-java#748]
Specifically I would like clients to be able to issue a CloudWatchLogs.GetLogEvents() call without needing to transfer the data via the server nor sending AWS credentials to the client. Is this possible? If so, how?

**Comment by shorea** [comment]
I don't see why not. Have you tried using a similar approach to our S3 presigned URL code? I'd suggest starting there, if you need help I'd be happy to take a look at your code and provide suggestions. 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L2474-L2554
