### ISSUE TITLE
SQS Load by URL

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#750]
Hi
the only way to load SQS is to work with its URL. e.g. AmazonSQSAsyncClient.getQueueAttributes
and also ListQueuesResult support getQueueUrls
Can you please support loading SQS by another means, such as SQS Arn
it is more convenient and similar to another AWS loading methods (such as SNS)

**Comment by breedloj** [comment]
Hey Majed, thanks for reaching out to us!  I see what you mean about SNS and SQS working a little differently in that SNS has you interact with Topic ARNs while SQS works off Queue URLs.  That said, this is a concept baked in to the SQS service API (for example: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html) which is what the Java SDK adheres to meaning we don't have a great way to change it.  However I'll definitely forward this feedback on to them so they're aware of your concerns.  I'm sure you're probably already aware of this but the GetQueueUrl does allow you to snag a queue's underlying URL from its name, the result of which can then be passed into other operations requiring the URL.

**Comment by bmagic39** [comment]
Thank you very much
indeed I'm aware of GetQueueUrl. this is good for the case I ave single SQS that I want to query
but for batch load (listQueues) the name still missing. for now I'm parsing it from the URL as a workaround
waiting for your update about the progress to remove my workaround

**Comment by breedloj** [comment]
Closing this for now since there is no SDK change incoming for this.  Will update the thread if I hear back from the service team about this.
