### ISSUE TITLE
AmazonEC2Client.describeVpcClassicLink 

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#754]
Why AmazonEC2Client.describeVpcClassicLink throws unsupported exception for region EU-CENTRAL-1 (Frankfort) and works on all others?
At the same interface all other methods related to VPC are working fine for EU-CENTRAL-1

if this is by intention, how I can check, beforehand, if this supported on region or not?

**Comment by zhangzhx** [comment]
Can you provide the detailed message returned from the Exception? It seems to be a question to the service team. I will reach out to them and let you know once get back from them.

**Comment by bmagic39** [comment]
Sorry for the long delay. the error message I get: 

com.amazonaws.AmazonServiceException: The functionality you requested is not available in this region. (Service: AmazonEC2; Status Code: 400; Error Code: UnsupportedOperation; Request ID: 4fc96eed-5a7e-4a01-88d1-2f51c25bb904)

**Comment by shorea** [comment]
I believe newer accounts only support EC2-VPC http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/vpc-migrate.html

**Comment by bmagic39** [comment]
I'm sorry
but it is not clear to me how this relate to the original issue I reported!
querying the classicklinks works fine for all VPC in all regions except EU_CENTRAL_1
no instances were migrated and no linux instances involved

**Comment by zhangzhx** [comment]
Sorry for the slow reply. Here is what I got from the service team:

```EU-CENTRAL-1 is a VPC only region and doesn't support EC2-Classic, so the VpcClassicLink APIs are disabled. This is the same for all new regions.```
