### ISSUE TITLE
Region.getServiceEndpoint(String) returns the wrong url for service CodeCommit

### ISSUE THREAD

**Issue by mway-dmueller** [aws/aws-sdk-java#755]
When called with value "codecommit" for parameter serviceName, getServiceEndpoint(String) returns codecommit.us-east-1.amazonaws.com whereas git-codecommit.us-east-1.amazonaws.com would be the correct endpoint.

Short example:

public static void main(final String[] args) {
	final List<Region> regions = RegionUtils.getRegionsForService("codecommit");
	for (final Region region : regions) {
		System.out.println(region.getServiceEndpoint("codecommit"));
	}
}

**Comment by manikandanrs** [comment]
As per this service documentation, codecommit.us-east-1.amazonaws.com is the correct endpoint.

http://docs.aws.amazon.com/general/latest/gr/rande.html#codecommit_region
