### ISSUE TITLE
CodeDeploy - DeploymentLimitExceededException include the deployment ID as a field

### ISSUE THREAD

**Issue by kohidave** [aws/aws-sdk-java#757]
Howdy,

It'd be really awesome if the DeploymentLimitExceededException included the deployment ID as a modeled field. Currently, when you create a deployment when another is already in progress, the exception includes a description string with the currently executing deployment ID. It'd be cool if those data were exposed as a field. 

DeploymentLimitExceededException e = ...;
e.getInProgressDeploymentId();

**Comment by zhangzhx** [comment]
Hi, thanks for reaching out to us. The client code is auto-generated from the service model which is defined by the service team.  See https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-codedeploy/src/main/resources/models/codedeploy-2014-10-06-model.json for CodeDeploy's model.

I will talk about this customization of the Exception in our team and reach out to the service team to see if  they have the plan to add this field.

**Comment by kohidave** [comment]
I'd really appreciate it if you forwarded this on to Code Deploy, thanks Zhaoxi!

**Comment by zhangzhx** [comment]
Sorry for the late reply, they've added this feature request to their backlog.

**Comment by kohidave** [comment]
Hey! I just wanted to reach out and say I see better error messaging now. Thanks a ton for the handwork, and pass my thanks on to the team!

**Comment by zhangzhx** [comment]
I am glad to hear you are satisfied with our work. I will forward your thanks to the team. :)
