### ISSUE TITLE
Release notes missing from 1.11.9-1.11.11

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#759]
Hi Team,

Could you please publish the usual [AWS SDK for Java Release Notes](https://aws.amazon.com/releasenotes/Java) for the last three versions 1.11.9-11?

Inspecting the SDK diffs has always been difficult due to the sheer size of that (usual) single commit per release, and things have gotten more noisy even due to the increasing use of code generation. The release notes provide very important guidance accordingly and ease focusing on those areas of an SDK update that might impact the dependent product in question.

Thanks much!

**Comment by zhangzhx** [comment]
Thanks for letting us know. We'll backfill these missing release notes shortly.

**Comment by zhangzhx** [comment]
The missing release notes 1.11.9-1.11.12 were added.

http://aws.amazon.com/releasenotes/8376697023030563
http://aws.amazon.com/releasenotes/8206921538694435
http://aws.amazon.com/releasenotes/5151335307213209
http://aws.amazon.com/releasenotes/2878241577606051
