### ISSUE TITLE
Cognito Userpools serverside API

### ISSUE THREAD

**Issue by shasti421** [aws/aws-sdk-java#762]
We are trying to use Cognito userpools feature. We like the feature, but noticed, java sdk lacks API  to use on serverside(lambda) to manage users. All the API published is targeted for use in mobile app. To provide serverside user management, we feel it would be great, if you can provide below API.
  1) Find a user in userpool by username
  2) Find a user in user pool by alias
  3) Lambda trigger whenever user attribute is changed

**Comment by zhangzhx** [comment]
This looks like a feature request for the service team. The SDK provided APIs are actually defined and exposed by the service team. I will reach out to the service team to see if they have the plans exposing the APIs you mentioned.

**Comment by zhangzhx** [comment]
You can reach out to the service team directly on their forum: https://forums.aws.amazon.com/forum.jspa?forumID=173

I cut a ticket about this feature request to them anyway, I will let you know once they get back to me.

**Comment by zhangzhx** [comment]
Service team added this feature request to their backlog. Closing this issue.
