### ISSUE TITLE
aws-java-sdk-core will not run without ReflectPermission "suppressAccessChecks"

### ISSUE THREAD

**Issue by tlrx** [aws/aws-sdk-java#766]
We encounter an issue similar to #528 using AWS SDK in version 1.10.69.

The `AmazonS3Client.resolveServiceEndpoint()` method calls the `RegionUtils.getRegion()` method to load AWS partitions from a JSON file.

This loading is done by the  `PartitionsLoader` class using a default Jackson `ObjectMapper` that will call `AccessibleObject.setAccessible(true)` on the public constructor of `Partitions`. This issue might be resolved by using a more recent version of Jackson. 

Also, the `ObjectMapper` used by the  `PartitionsLoader` should be configured to disable the following Jackson's features:
- MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS
- MapperFeature.OVERRIDE_PUBLIC_ACCESS_MODIFIERS
- MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS

For now, we added the ReflectPermission "suppressAccessChecks" but we'd love to get rid of it.

Thanks

**Comment by zhangzhx** [comment]
The `ObjectMapper` used by `PartitionsLoader` is a public `ObjectMapper` provided by the helper class `com.amazonaws.util.json.Jackson`. See the following the link:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/json/Jackson.java#L32-L36

We have potential risks to disable these features to the shared mapper, but we can definitely change the `PartitionsLoader`'s `ObjectMapper` to be a private one, and disable these features to that `ObjectMapper` the same way to `InternalConfig` (see the link). Does that meet your need ?

https://github.com/aws/aws-sdk-java/blob/1.10.69/aws-java-sdk-core/src/main/java/com/amazonaws/internal/config/InternalConfig.java#L43-L46

**Comment by tlrx** [comment]
> The ObjectMapper used by PartitionsLoader is a public ObjectMapper provided by the helper class com.amazonaws.util.json.Jackson. See the following the link:
> 
> https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/json/Jackson.java#L32-L36

Yes. With the default configuration on Jackson 2.5.3 (used by aws sdk) the following features are enabled: 
- CAN_OVERRIDE_ACCESS_MODIFIERS
- ALLOW_FINAL_FIELDS_AS_MUTATORS

which will require special permissions.

> We have potential risks to disable these features to the shared mapper, but we can definitely change the PartitionsLoader's ObjectMapper to be a private one, and disable these features to that ObjectMapper the same way to InternalConfig (see the link). Does that meet your need ?

That would be great, yes. I do think that you would benefit to use a more recent version of Jackson but I can definitely test with this change.

**Comment by zhangzhx** [comment]
This update will be published in our next release on 7/7. Please try our newest version to see if you still have the problem.
