### ISSUE TITLE
AWS Lambda: Support for region ap-southeast-2 not reflected in SDK

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#767]
The [recently added availability of AWS Lambda in Asia Pacific (Sydney)](http://aws.amazon.com/about-aws/whats-new/2016/06/aws-lambda-available-in-asia-pacific-sydney/) is not [reflected in the SDK yet](https://github.com/aws/aws-sdk-java/blob/75f77d3b7a9ae9559f2b967c5979b943777ae9bf/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L646).
This affects UX in terms of e.g. the added region not being returned by `RegionUtils.getRegionsForService()` (actual usage of the region by setting it explicitly to the result of `RegionUtils.getRegion("ap-southeast-2")` does work as expected)

**Comment by manikandanrs** [comment]
Thanks for bringing this to our attention. I have pushed a change for this. This will be fixed as part of our next release.
