### ISSUE TITLE
Upload Restart Not Working

### ISSUE THREAD

**Issue by spoticus** [aws/aws-sdk-java#769]
Upload restart not working. Tried several mechanisms found on Internet and finally used the mechanism described here, which seems simplest:

https://java.awsblog.com/post/Tx2Y9J2CUDVJ5LZ/Pausing-and-Resuming-transfers-using-Transfer-Manager

Attached are two apps; one for the upload and one for the restart. I traced both using Charles proxy so am sure that the restart is not working. BTW, neither shutdown the TransferManager or S3 client properly, so app never finishes.
[awsdbg.zip](https://github.com/aws/aws-sdk-java/files/346854/awsdbg.zip)

**Comment by varunnvs92** [comment]
@spoticus 
I have tested with the code you provided with minor modification and the pause/resume functionality seems to work fine. I have tested with both 1.10.x and 1.11.x major versions. What version of the SDK are you using? What is the size of the file you are trying to upload?

I have attached the test code I used. I did my testing with 200 MB file and paused the resume at 100MB. When the upload is resumed, the code prints the percent transferred every 2 seconds. You can see the resume starts from 45%(approx). 

[S3Tests.java.zip](https://github.com/aws/aws-sdk-java/files/348927/S3Tests.java.zip)

**Comment by varunnvs92** [comment]
Did you have chance to look at the test code I attached? Are you still seeing the issue?

**Comment by spoticus** [comment]
I just got home from business trip and will test tonight. Thank you for uploading a working sample.

**Comment by spoticus** [comment]
I ran the test. I’ve discovered that you need to run tryPause(…) to make it work. So, the example you sent works, because the upload is paused before the application terminates.

However, if the application crashes it does not. For example, hit “ctrl+c”, while the application is uploading.

I tried adding a shutdown hook, Runtime.getRuntime().addShutdownhook(…), and run the tryPause(…) from there. When I hit “ctrl+c” it does run the shutdown hook, and the tryPause(…) returns true, but it doesn’t save the current progress. When I restart the app again it restarts back at the beginning.

The shutdown hook is run after public static void main(…) returns, so maybe the AWS library isn’t able to inform the server properly of the pause. I don’t know. But that’s the problem. If the application crashes then it seems impossible to restart the upload from the place where the application crashed.

Clay

**Comment by varunnvs92** [comment]
If the upload is not paused before the crash, the test code won't be able to save the PersistableUpload information needed to resume the upload. 

To handle crashes, look at the last section in this [blog](https://java.awsblog.com/post/Tx2Y9J2CUDVJ5LZ/Pausing-and-Resuming-transfers-using-Transfer-Manager).  You can pass an instance of S3SyncProgressListener to TransferManager#upload and serialize the data to a file.

**Comment by spoticus** [comment]
If the application controls the shutdown, I understand now that the a normal shutdown call to aws will set a marker allow a restart. However, if the operating system kills the process then the application is unable to perform any shutdown logic.

**Comment by varunnvs92** [comment]
If process is killed, the application can't save the information to resume the upload. So as I mentioned in my last comment, you can have a S3SyncProgressListener and serialize the data to a file regularly. So when a crash occurs, you can use the last serialized file to resume the upload. Please refer the last code snippet of the blog mentioned in my previous comment.

**Comment by kiiadi** [comment]
Closing aged issue with no response, please feel free to reopen if this is still a problem.
