### ISSUE TITLE
Add AWS SDK method to pull single certificate

### ISSUE THREAD

**Issue by license2e** [aws/aws-sdk-java#770]
Right now there is only a method to pull all server certificates: 

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/identitymanagement/AmazonIdentityManagement.html#listServerCertificates--

And then you have to iterate over each one comparing the certificateId.. 

It would be nice to have an api call that just retrieves a single certificate.

**Comment by varunnvs92** [comment]
@license2e 
There is another [API](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/identitymanagement/AmazonIdentityManagement.html#listServerCertificates-com.amazonaws.services.identitymanagement.model.ListServerCertificatesRequest-) that lists the server certificates based on path prefix. The docs related to this feature http://docs.aws.amazon.com/IAM/latest/APIReference/API_ListServerCertificates.html

I am not sure if this is what you are looking for. If not, I suggest you opening a new post in[ AWS Identity and Access Management (IAM) forums](https://forums.aws.amazon.com/forum.jspa?forumID=76). The AWS SDK for Java team don't own the AWS IAM service and so we cannot add new features to the service. Reaching out to the service team is more suitable. Thank you for contacting us. Please let us know if you have more questions.
