### ISSUE TITLE
Tweaking Hadoop Configuration after running certain jobs in EMR.

### ISSUE THREAD

**Issue by Beyek** [aws/aws-sdk-java#772]
I have numbers of batch job that run on a emr cluster.
I want to update certain properties of hadoop configuration depending upon my batch job using java sdk.

I have found 2 possible ways to configure hadoop.
1) Setting configuration during cluster start . 
2) Using add-step to run custom script that will modify the require property in master and copy it across the core and task instances.

Is there anything more I can do to modify configuration in existing cluster without needing to use scripts ? Like, passing a json configuration to the running cluster for its next batch job.

**Comment by varunnvs92** [comment]
@Beyek 
Thanks for contacting us. I don't have much context about setting hadoop configuration. I have found some docs on setting configuration.
http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-hadoop-config.html
http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/Config_JSON.html

I also raised a ticket to the Amazon Elastic MapReduce team to look at this issue and respond here.

**Comment by varunnvs92** [comment]
Amazon EMR team responded that they don't support reconfiguration on running clusters yet. The AWS SDK for Java team mirrors the functionality of the EMR team. So looks like there is no way to do what you are looking for.

Thank you. Feel free to reopen the ticket if you have more questions.

**Comment by Beyek** [comment]
I am looking forward for the support for reconfiguration.
Thanks for the reply.
