### ISSUE TITLE
CloudWatchActions enum grants 'monitoring:' actions instead of 'cloudwatch:' actions

### ISSUE THREAD

**Issue by gidsg** [aws/aws-sdk-java#774]
Steps to reproduce
==============
See https://github.com/aws/aws-sdk-java/blob/786bc588b48f39f2dd9cb9cd370388ca79dcd7d1/aws-java-sdk-cloudwatch/src/main/java/com/amazonaws/auth/policy/actions/CloudWatchActions.java#L25-51

Actual Results
===========
Actions are deprecated `monitoring:` actions

Expected Results
==============
Actions are `cloudwatch:` actions as per: https://awspolicygen.s3.amazonaws.com/policygen.html

**Comment by manikandanrs** [comment]
This is fixed and will be released as part of our next release.
