### ISSUE TITLE
Missing constant ENDPOINT_PREFIX in AmazonS3 interface

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#777]
The [deprecation note for the ServiceAbbreviations class](https://github.com/aws/aws-sdk-java/blob/1eecff84c96b89111f2e2f111ae3633533a245dd/aws-java-sdk-core/src/main/java/com/amazonaws/regions/ServiceAbbreviations.java#L22) says:

```
 * @deprecated use the constant ENDPOINT_PREFIX from the specific service client
 *             interface instead for retrieving the specific service abbreviation,
 *             e.g. AmazonEC2.ENDPOINT_PREFIX.
```

However, different to the other service interfaces, the [AmazonS3 interface](https://github.com/aws/aws-sdk-java/blob/1d3471d831d07078739b06f5f1006c990323ab4a/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3.java) does not declare an `ENDPOINT_PREFIX`. The closest contender would be the [AmazonS3Client.S3_SERVICE_NAME constant](https://github.com/aws/aws-sdk-java/blob/786bc588b48f39f2dd9cb9cd370388ca79dcd7d1/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L292) (slightly matching the client classes being an 'intermediate' location for the moved endpoint definitions in context of #743 )

:grey_question: Is this an oversight or intentional, and if the latter, is it safe to use `AmazonS3Client.S3_SERVICE_NAME` instead?

**Comment by manikandanrs** [comment]
Thanks for reporting this. This is a bug. I have pushed a fix which will be available in the next release.
