### ISSUE TITLE
S3 upload not reflecting. 

### ISSUE THREAD

**Issue by samyuktr** [aws/aws-sdk-java#778]
Hi, 

I'm using aws-java-sdk for S3 upload. My code compiles and runs like a charm. But I can't see my uploaded file on the console. Nothing is reflected.

**Comment by manikandanrs** [comment]
Do you have multiple accounts  ? If so are you looking at the correct account.

**Comment by samyuktr** [comment]
I have only one account. Does the file have to be created on aws already? 
test-bucket/test/myfile is my keyName and myfile is the name of my file I uploaded.

**Comment by manikandanrs** [comment]
No. Can you share the code that is trying to upload the file

**Comment by samyuktr** [comment]
String bucketName     = "Sample";
					 String keyName        = "test-bucket/test/myfile";
					 String uploadFileName = "C:/Users/..../myfile";

					AmazonS3 s3client = new AmazonS3Client(new ProfileCredentialsProvider());
	        		try 
	        		{
	        			
	        			System.out.println("Uploading a new object to S3 from a file\n");
	            		File file = new File(uploadFileName);
	            		
	            		s3client.putObject(new PutObjectRequest(bucketName, keyName, file));
	            		Out.prln("Successfully uploaded!");

	         		}

**Comment by manikandanrs** [comment]
You don't need to create a file; but the bucket should be created prior to this putObject.

Did you create a s3 bucket name with name "Sample" ?

**Comment by samyuktr** [comment]
Yes. Sample/test-bucket/test/ is already created.

**Comment by manikandanrs** [comment]
So, here is the thing. You have created a bucket name with "Sample/test-bucket/test/" which is different from the bucket "Sample"

**Comment by manikandanrs** [comment]
I would suggest reading this to understand the s3 terminologies like "Bucket", "Key" etc.,

http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#CoreConcepts

**Comment by samyuktr** [comment]
No. I mean, I have a bucket Sample and folders inside sample. 
Folder inside the bucket "Sample" is "test-bucket" which has a sub folder "test".

**Comment by manikandanrs** [comment]
I just tested this code

```
public class s3 {
    
    public static void main(String[] s) throws Exception {
        final String bucketName = "test-sample";
        final String key = "test-bucket/test/myfile";
        final String keyContents = "Hello World";
        AmazonS3Client client = new AmazonS3Client(new ProfileCredentialsProvider("default"));
        // Create Bucket.
        client.createBucket(bucketName);

        // Upload Contents to a key.
        client.putObject(bucketName, key, keyContents);

        // Download s3 object.
        S3Object s3Object = client.getObject(bucketName, key);
        System.out.println("Compare Contents : " + keyContents.equals(IOUtils.toString(s3Object.getObjectContent())));
        
    }
}
```

I am able to see the file on my console.
