### ISSUE TITLE
CannedAccessControlList.PublicReadWrite applicable to S3Object?

### ISSUE THREAD

**Issue by tomlee** [aws/aws-sdk-java#780]
Hello,

I have set the S3 object ACL with the `CannedAccessControlList.PublicReadWrite` permission to an existing S3 object with the `AmazonS3Client.setObjectAcl` method and the `SetObjectAclRequest` object. Then, I did an anonymous HTTP post to replace the object. However, I got an access denied response. Is the public-read-write permission applicable to an S3 object? BTW, the same HTTP post request can replace the object when I have given the `CannedAccessControlList.PublicReadWrite` permission to the object's bucket.

However, the documentation at http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html says the `CannedAccessControlList.PublicReadWrite` permission is applicable to an S3 object. What does it mean?

Thanks for your advice.

Thomas

My HTTP post request:

```
POST / HTTP/1.1
Host: somebucket.s3.amazonaws.com
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu1fW

----WebKitFormBoundary7MA4YWxkTrZu1fW
Content-Disposition: form-data; name="key"

hello.txt
----WebKitFormBoundary7MA4YWxkTrZu1fW
Content-Disposition: form-data; name="file"

hello world!
----WebKitFormBoundary7MA4YWxkTrZu1fW
```

The HTTP response I got:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>B29BB5D91A11F24C</RequestId>
    <HostId>+3qHADxaz7GUGajmEKxXooonkj7v3vLmNgN1u3DcveiVz+w/aBGRy9h53rFgZcbP/DCrHtobgUA=</HostId>
</Error>
```

**Comment by shorea** [comment]
Not able to reproduce, could you provide sample code and double check in the console that the object permissions are correct.

Here's what I tried (note that I'm using the SDK to make the anonymous request rather then a raw HTTP post so my example doesn't quite match up with your use case)

```java
    public static void main(String[] args) throws IOException {
        AmazonS3Client client = new AmazonS3Client(new ProfileCredentialsProvider("personal"));
        client.setObjectAcl(BUCKET_NAME, KEY, CannedAccessControlList.PublicReadWrite);
        AmazonS3Client anonClient = new AmazonS3Client(new AnonymousCredentialsProvider());
        final String content = IOUtils
                .toString(anonClient.getObject(BUCKET_NAME, KEY).getObjectContent());
        System.out.println(content);
    }

    public static class AnonymousCredentialsProvider implements AWSCredentialsProvider {

        public AWSCredentials getCredentials() {
            return null;
        }

        public void refresh() {
        }
    }

```

**Comment by tomlee** [comment]
I have no problem when I `getObject`  which is assigned with `PublicReadWrite`. But I'll get an "Access Denied" exception when I `putObject`. Since the [documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html) says `PublicReadWrite` can be applied to an object so I presume I can overwrite an existing object with an anonymous `putObject` request.

Please see my test program:

```
public static void main(String[] args) throws IOException {
        AWSCredentials credentials = new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY);
        AmazonS3Client client = new AmazonS3Client(credentials);
        client.setObjectAcl(BUCKET_NAME, KEY, CannedAccessControlList.PublicReadWrite);
        AmazonS3Client anonClient = new AmazonS3Client(new AnonymousCredentialsProvider());
        final String content = IOUtils
                .toString(anonClient.getObject(BUCKET_NAME, KEY).getObjectContent());
        System.out.println(content);
        anonClient.putObject(BUCKET_NAME, KEY, "hello world!");
    }

    public static class AnonymousCredentialsProvider implements AWSCredentialsProvider {

        public AWSCredentials getCredentials() {
            return null;
        }

        public void refresh() {
        }
    }
```

I got the following `AmazonS3Exception` when I ran the above program:

`Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9DB4DC98969DB685), S3 Extended Request ID: Ciu2KoDbMEqPS2QYVhbuubUMV2qzQSQny0Ib9Tb34L4LyFAIzk3OyFHkahciEc/tZBiqG7Yo9Wk=`

If an existing object isn't rewritable when the `PublicReadWrite` ACL is set, please kindly specify this in the documentation.

Thank you.

**Comment by shorea** [comment]
Sorry I misread your issue. I'll take a look at the putObject case now. I suspect the PublicReadWrite needs to be set on the bucket but need to confirm.

**Comment by tomlee** [comment]
Thanks alot. I have checked that it's okay to `putObject` when I set the bucket to `PublicReadWrite`. However, in that case, I can upload whatever objects into that bucket.

Is it possible to make a particular object `PublicReadWrite` without making the whole bucket `PublicReadWrite`?

**Comment by shorea** [comment]
Okay so it looks like the preferred way to do this is with bucket policies. ACL's are legacy access control mechanisms according to http://blogs.aws.amazon.com/security/post/TxPOJBY6FE360K/IAM-policies-and-Bucket-Policies-and-ACLs-Oh-My-Controlling-Access-to-S3-Resourc

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "PublicReadWrite",
			"Effect": "Allow",
			"Principal": "*",
			"Action": [
				"s3:GetObject",
				"s3:PutObject"
			],
			"Resource": "arn:aws:s3:::BUCKET_NAME/KEY_NAME"
		}
	]
}
```

**Comment by shorea** [comment]
BTW if you need to programmatically create these bucket policies I believe the PolicyWriter utility would meet your needs.

Construct a policy object and call to JSON to get the bucket policy string.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/policy/Policy.java
