### ISSUE TITLE
Invalid AccessControlList: missing an S3Owner

### ISSUE THREAD

**Issue by tomlee** [aws/aws-sdk-java#781]
Hello,

I tried to use `AmazonS3Client::setObjectAcl()` to set the ACL of an S3 object by supplying an `SetObjectAclRequest` object. I granted a `Permission.Read` to an `EmailAddressGrantee`. I got the exception "Invalid AccessControlList: missing an S3Owner" when I called `AccessControlList::setOwner()`.

According to the [API documentation](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html), `AccessControlList::setOwner()` is for internal use only and the owner can't be changed. I suppose it needn't be called.

However, in the examples of [this tutorial](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-using-java-sdk.html), `AccessControlList::setOwner()` is called.

Do I need to call `AccessControlList::setOwner()` before calling `AmazonS3Client::setObjectAcl()`? Where should I get the `Owner` of an S3 object? From the `AwsS3Client` or `S3ObjectSummary`?

Thank you for your advice.

Thomas

**Comment by shorea** [comment]
You can get owner id and display name from the getS3AccountOwner API. You can also get it from a preexisting resource if you're modifying an ACL (i.e. call getBucketAcl or getObjectAcl and directly modify the access control list it returns and then pass that to a setBucketAcl or setObjectAcl API call). In the get/modify/put flow you would not change owner but just the grants in the ACL. 

Here's a simple example of the get/modify/put flow.
```java
AmazonS3Client client = new AmazonS3Client(new ProfileCredentialsProvider("personal"));
final AccessControlList acl = client.getObjectAcl(BUCKET_NAME, KEY);
acl.revokeAllPermissions(GroupGrantee.AllUsers);
client.setObjectAcl(BUCKET_NAME, KEY, acl);
```

Here's a couple of examples of retrieving owner information for various resources (service, bucket, object)
```java
final Owner owner1 = client.getS3AccountOwner();
final Owner owner2 = client.getBucketAcl(BUCKET_NAME).getOwner();
final Owner owner3 = client.getObjectAcl(BUCKET_NAME, KEY).getOwner();
```

**Comment by tomlee** [comment]
Do you mean when I do `setObjectAcl` with an `AccessControlList` instance created from scratch (not updating the `AccessControlList` instance retrieved from S3 for the object), I need to set the owner with `setOwner`? Is it safe to use the `setOwner` method while the API documentation says `AccessControlList::setOwner()` is for internal use only? 

You may want to remove the "for internal use" statement from the API documentation on `AccessControlList::setOwner()`.

Alternatively, can `AmazonS3Client` automatically `setOwner` with either one of the method you suggested when the owner is detected to be null because the owner of the object can't be changed anyway? Is it possible to add this feature in a future version? Then, you needn't modify the API documentation on AccessControlList::setOwner()`.

Thanks for your advice.

**Comment by shorea** [comment]
See correspondence in #780. Bucket policies are a more robust way to grant permissions. I'll update the docs to remove the blurb about internal usage as it is acceptable to call this method.
