### ISSUE TITLE
Where is HelloWorldWorkflowClientExternalFactoryImpl?

### ISSUE THREAD

**Issue by kennyk65** [aws/aws-sdk-java#786]
This class seems to be missing from the SWF samples.  See https://github.com/aws/aws-sdk-java/blob/master/src/samples/AwsFlowFramework/src/com/amazonaws/services/simpleworkflow/flow/examples/helloworld/WorkflowExecutionStarter.java, line 28.

Are there any SWF samples available that compile / work?

**Comment by varunnvs92** [comment]
@kennyk65  
Sorry for the delayed response. The classes are generated when you build the client and flow library. All the samples should be working. 

SWF team owns the following repo: https://github.com/aws/aws-swf-flow-library
You can open an issue if you need help running them. Thank you.
