### ISSUE TITLE
Where is BookingWorkflowClientExternalFactoryImpl?

### ISSUE THREAD

**Issue by kennyk65** [aws/aws-sdk-java#787]
Where is BookingWorkflowClientExternalFactoryImpl.java?  See https://github.com/aws/aws-sdk-java/blob/master/src/samples/AwsFlowFramework/src/com/amazonaws/services/simpleworkflow/flow/examples/booking/WorkflowExecutionStarter.java

Do any of these samples actually compile?

**Comment by varunnvs92** [comment]
@kennyk65  
Sorry for the delayed response. The class BookingWorkflowClientExternalFactoryImpl is generated when you build the client and flow library.

SWF team owns the following repo: https://github.com/aws/aws-swf-flow-library
You can open an issue if you need help running them. Thank you.
