### ISSUE TITLE
STSAssumeRoleSessionCredentialsProvider - Take in Scope Down Policy

### ISSUE THREAD

**Issue by kohidave** [aws/aws-sdk-java#789]
It'd be really cool if the credentials provider could take a scope down policy as one of its arguments (just as it takes an external ID, session name, etc now).

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sts/src/main/java/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.java#L298

**Comment by shorea** [comment]
Sounds like a great addition! I'll look into implementing this.

**Comment by shorea** [comment]
This has been implemented and will be included in the next (1.11.23) release of the SDK.
