### ISSUE TITLE
S3ObjectInputStream skip is inefficient

### ISSUE THREAD

**Issue by yagyesha** [aws/aws-sdk-java#797]
I working on implementing S3 download framework with resume support. When using S3ObjectInputStream while downloading an object, I had to skip bytes in order to support resume of previously broken downloads. Calling skip() on S3ObjectInputStream takes forever (if the file is big) & it seems it is simply using the default skip() implementation. Here is what documentation says about default implementation:

> The skip method of this class creates a byte array and then repeatedly reads into it until n bytes have been read or the end of the stream has been reached. Subclasses are encouraged to provide a more efficient implementation of this method. For instance, the implementation may depend on the ability to seek.

Is there a way i can efficiently seek to a specific position when using S3ObjectInputStream? Or is there any other alternative?

**Comment by fernomac** [comment]
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GetObjectRequest.html#setRange-long-long-

**Comment by manikandanrs** [comment]
You can also take a look at 

http://java.awsblog.com/post/Tx3Z7NO7C2TVLB/Parallelizing-Large-Downloads-for-Optimal-Speed

**Comment by yagyesha** [comment]
Thanks for quick response. GetObjectRequest setRange was exactly what i was looking for.
