### ISSUE TITLE
[feature-request] KinesisFirehose-ElasticSearch - Save to ES with Id

### ISSUE THREAD

**Issue by yashrajrs** [aws/aws-sdk-java#800]
Currently Kinesis Firhose doesnt support a way to configure the elastic search document id for saving the document id to ES.
Would be better if this feature is added

**Comment by zhangzhx** [comment]
Looks like this is a feature request for the service team. Will reach out to them to see if they have the plan to support this.

**Comment by zhangzhx** [comment]
Sorry for the slow reply. The service team have this added in their roadmap. You can report issues on their forum if you have service-specific questions https://forums.aws.amazon.com/forum.jspa?forumID=169

**Comment by oneryalcin** [comment]
It us now August 2021 and this 'pretty easy to implement' feature still pending after 4 years? That's not really good.
