### ISSUE TITLE
Scala build warning with 1.11.16+

### ISSUE THREAD

**Issue by dmatth** [aws/aws-sdk-java#806]
My build.sbt contains this:
    libraryDependencies ++= Seq(
      "com.amazonaws" % "amazon-kinesis-client" % "1.6.5",
      "com.amazonaws" % "aws-java-sdk-dynamodb" % "1.11.15",
...
    )

and it has worked fine up to and including 1.11.15
but when I change that to 1.11.16 or later (still an issue with 1.11.24), my sbt package output includes this unsettling warning:
`[warn] Class com.amazonaws.client.AwsSyncClientParams not found - continuing with a stub.`

**Comment by shorea** [comment]
Looks like it's preferring kinesis's dependency on core which is prior to when this class was introduced. Adding an explicit dependency on a later version of core should fix this issue.

**Comment by dmatth** [comment]
Yes, adding the explicit core dependency worked. Thanks.
