### ISSUE TITLE
Status/Future of embedded JMESPath for Java library?

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#808]
Hi Team,

I've just looked into the new resource state "Waiters" added in [release 1.11.25](https://aws.amazon.com/releasenotes/Java/7149077418971982), and as anticipated, those will considerably ease many implementation scenarios and effectively replace lots of existing custom code, thanks much for adding this notable feature!

Too my delight, you have also based this on a long missed [JMESPath](http://jmespath.org/libraries.html) Java implementation. However, I'm surprised you opted to make it [part of the SDK](https://github.com/aws/aws-sdk-java/tree/master/jmespath-java) rather than at least a standalone library (like the just recently extracted [aws-swf-flow-library](https://github.com/aws/aws-swf-flow-library)), or even part of the [JMESPath](https://github.com/jmespath) GitHub organization to ease discovery and foster the JMESPath community and brand identity?

Any insight into the resp. status and future of this de facto 'jmespath.java' library would be much appreciated accordingly! /cc @jamesls

* Background: We are in need of a (user facing) JSON query layer and would have much preferred to use JMESPath for consistency within the AWS universe, but had to base our current implementation on [JSONPath](https://github.com/jayway/JsonPath) due to timing constraints - given your most welcome initiative, it might not be too late to reverse this decision :)

Cheers,
Steffen

**Comment by shorea** [comment]
Thanks for the interest. You're absolutely right, we eventually want this as a standalone library in the jmespath organization with the other implementations. We are working with our open source team to make this happen. The current implementation is a subset of the full JMESPath language, we'll be adding more support in the future to be fully compliant with the spec (we are also cheating a bit and use Python's parser to generate the AST rather then implement our own lexer/parser, this is done at build time of the SDK for the waiters).

**Comment by sopel** [comment]
Thanks for the quick clarification @shorea, much appreciated - I'm looking forward to a fully spec compliant release down the road (we'll evaluate whether the current subset might already cover our limited use case regardless /cc @hopel).
