### ISSUE TITLE
[flow framework] Need more type info in DataConverter interface

### ISSUE THREAD

**Issue by ogrodnek** [aws/aws-sdk-java#81]
I'm finding it difficult to write a [DataConverter](https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/services/simpleworkflow/flow/DataConverter.java) -- it seems like there's not really any type information passed to it for deserialization.

fromData takes a Class<T> valueType parameter, but it seems like the flow framework calls this method with "Object[].class" -- effectively giving no type information at all (e.g. see [POJOWorkflowDefinition](https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/services/simpleworkflow/flow/pojo/POJOWorkflowDefinition.java) lines 74, 111.

Since the framework expects Arrays, maybe it would make more sense to have fromData take an array of Type information to better match and give the implementer more information to make deserialization decisions on?

thanks.

**Comment by dieend** [comment]
+1 for this feature. Or at least enable overriding `DataConverter` using `@Activity` instead of only possible to define the `DataConverter` in `@Activities`.
