### ISSUE TITLE
DynamoDB latency logger should populate request type metric

### ISSUE THREAD

**Issue by chook** [aws/aws-sdk-java#810]
After looking at http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/package-summary.html and turning on AwsSdkMetrics I concluded that I must search for RequestType.
However, there is no RequestType defined under Field for AWSRequestMetrics.

The latency logger properties show the following:
`{ServiceName=[AmazonDynamoDBv2], StatusCode=[200], ServiceEndpoint=[https://dynamodb.us-east-1.amazonaws.com], AWSRequestID=[DN8MQ...G]}`

I expected the `properties` to have RequestType.
The only place I could locate a RequestType is in the `MetricUploaderThread.java` but it looked like it is a bit "mistakenly" there:

```
// Either a non request type specific datum is created per
// sub-measurement, or a request type specific one is
// created but not both
if (includesRequestType) {
    dims.add(new Dimension()
            .withName(Dimensions.RequestType.name())
            .withValue(requestType(req)));
}
```
 (ref: PredefinedMetricTransformer.java#214)

=====

Please copy the RequestType logic from the Cloudwatch metrics into the Latency logger so we can see the request being made in "real time" (as opposed to the async nature of the metric upload thread).

**Comment by breedloj** [comment]
Thanks for the feature request.  This seems reasonable to me and I've made a change to add a RequestType field which is emitted to the latency logger.
