### ISSUE TITLE
ProfilesConfigFile returns NPE if ~/.aws/credentials doesn't exist

### ISSUE THREAD

**Issue by ttenhor** [aws/aws-sdk-java#812]
The following code will produce a NPE if ~/.aws/credentials does not exist

`
try {
	AWSCredentials credentials = new ProfileCredentialsProvider("test").getCredentials();
}
catch (Exception e) {
	e.printStackTrace();
}
`

Resulting in this stacktrace:

`java.lang.NullPointerException
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:143)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:132)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:99)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:135)
	at ProfilesConfigBug.main(ProfilesConfigBug.java:16)
`

This is due to the ctor not checking _file_ argument for null before calling .lastModified()

**Comment by manikandanrs** [comment]
What is the version of the SDK that you are using ? We have fixed this. Give it a try with the latest version of the SDK and let us know if you still face issues.

**Comment by ttenhor** [comment]
With 1.11.26 it still fails.  1.11.27 doesn't seem to be available from [https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip]

**Comment by manikandanrs** [comment]
Are you sure it is 1.11.26 in the class path ? I just tested this in the 1.11.26 and I get only IllegalArgumentException.

```
try {
                       System.out.println(ProfileCredentialsProvider.class.getProtectionDomain().getCodeSource()); 
AWSCredentials credentials = new ProfileCredentialsProvider("test").getCredentials();
} catch (Exception e) { e.printStackTrace(); }
```

Check if the class being loaded is from 1.11.26

**Comment by ttenhor** [comment]
I tested this and gave the JVM the -verbose:class VM argument and it printed 

'
[Loaded com.amazonaws.auth.AWSCredentialsProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.auth.profile.ProfileCredentialsProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.auth.profile.ProfilesConfigFile from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.auth.profile.internal.securitytoken.ProfileCredentialsService from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.AwsProfileFileLocationProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.AwsProfileFileLocationProviderChain from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.cred.CredentialsEnvVarOverrideLocationProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.AwsDirectoryBasePathProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.cred.CredentialsDefaultLocationProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.AmazonClientException from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.cred.CredentialsLegacyConfigLocationProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.config.ConfigEnvVarOverrideLocationProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.profile.path.config.SharedConfigDefaultLocationProvider from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]
[Loaded com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceLoader from file:/C:/aws-java-sdk/1.11.26/lib/aws-java-sdk-1.11.26.jar]

java.lang.NullPointerException
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:143)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:132)
	at com.amazonaws.auth.profile.ProfilesConfigFile.<init>(ProfilesConfigFile.java:99)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:135)
	at ProfilesConfigBug.main(ProfilesConfigBug.java:16)
'

**Comment by manikandanrs** [comment]
This is now fixed and will be released as part of our next release scheduled for tomorrow.
