### ISSUE TITLE
DynamoDBTypeConverted does not work in DynamoDBDocument fields

### ISSUE THREAD

**Issue by zeldigas** [aws/aws-sdk-java#817]
I faced with a bug using new annotations for type conversion: DynamoDBTypeConverted.

DynamoDb mapper (and underlying DynamoDBMapperTableModel) does not handle custom converter for fields in subentities annotated with DynamoDBDocument.

I created a simple test that shows the problem: https://github.com/zeldigas/aws-sdk-dynamodb-conversion-bug

The failing test: https://github.com/zeldigas/aws-sdk-dynamodb-conversion-bug/blob/master/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/ConversionToAttributeValuesTest.java#L51

It seems that problem is in AnnotationAwareUnmarshallerSet and AnnotationAwareMarshallerSet that are used when during conversion of embedded document fields.

It is reproduced with the latest version of aws-java-sdk (1.11.27).

**Comment by dagnir** [comment]
Hi @zeldigas I will look into this. Thank you for reporting the issue and providing sample code!

**Comment by dagnir** [comment]
This particular case is now fixed as of the current release; with small modifications (you'll need to add a hash key to the tables), the tests provided now pass. There is still an issue if the type-converted object is within a collection such as List or Map that will be fixed in a future release.

**Comment by zeldigas** [comment]
Awesome thank you!

**Comment by rkrier85233** [comment]
Any ETA when it will be fixed when its in a collection? I had to resort to deprecated @DynamoDBMarshalling with a marshaller class.

**Comment by selectedpixel** [comment]
You mentioned that you need to add a hash key to the tables? I'm assuming that the attribute that is being converted cannot be the HashKey?
