### ISSUE TITLE
Amazon ECR returning invalid authentication token?

### ISSUE THREAD

**Issue by ByteFlinger** [aws/aws-sdk-java#818]
I am using the ECR SDK to request a authentication token for login and I get back a token with an expiration date which has not yet expired yet when I try to access the Registry I get a message saying that my token as expired and I should do aws ecr get-login.

Relevant code can be found below

```java
URI proxy = new URI("http://myproxy.com:3344");
AWSCredentials awsCredentials = new BasicAWSCredentials("someKeyId", "someKeySecret");
ClientConfiguration clientConfiguration = new ClientConfiguration();
if (proxy != null) {
    clientConfiguration.setProxyHost(proxy.getHost());
    clientConfiguration.setProxyPort(proxy.getPort());
}
AmazonECR amazonECR = AmazonECRClientBuilder.standard().withClientConfiguration(clientConfiguration).withRegion("eu-west-1").withCredentials(
                new StaticCredentialsProvider(awsCredentials)).build();

GetAuthorizationTokenResult authorizationToken = amazonECR.getAuthorizationToken(new GetAuthorizationTokenRequest());
List<AuthorizationData> authorizationData = authorizationToken.getAuthorizationData();

String password = authorizationData.get(0).getAuthorizationToken();
```

The code above will yield a authorization token and checking it's `getExpiresAt()` method reveals that it has not yet expired but as mentioned above when trying to authenticate to the ECR endpoint I get a message saying the token is no longer valid.

I tried using a token gotten from the `aws ecr get-login` command and that one works.

I also noticed that the cli will return a new token everytime while the sdk keeps returning the same token. Could the sdk not be triggering the generation of a new token at all?

Seems to be the same issue reported here as well
https://issues.jenkins-ci.org/browse/JENKINS-34958

**Comment by spfink** [comment]
To confirm, you are generating a token with the AmazonECR client in eu-west-1, are you also attempting to use it to login in that region only?

**Comment by ByteFlinger** [comment]
Yes. I am only trying to login into that region. I haven't tried another
one (More correctly said I tried calling the Api for us-east-1 but got a
404 which is expected as I don't have an ecr instance there).

**Comment by spfink** [comment]
Can you provide the command you are using the authorization token with? (without any usernames or passwords of course)

**Comment by ByteFlinger** [comment]
Sure.

I am using it both in an apache httpclient and curl.

The curl command I am query the api is the following

curl -v -H "Accept: application/json" -H "Content-Type: application/json" -u "<USERNAME>:<GIANT_TOKEN>" -X GET -k https://somevalue.ecr.eu-west-1.amazonaws.com/v2/aaaaa/bbbbbb/manifests/latest

Replacing the token with one i get from the aws sdk (which contains a valid expiration) gives me the message that it is no longer valid but the one from aws cli works

**Comment by spfink** [comment]
Also, didn't catch this earlier, are you directly using the output of the password string above as your password?

The authorizationToken is base64 encoded and includes both the username and password. You need to decode it and then grab out the password. The username and password are split by ":" after you base64 decode.

**Comment by ByteFlinger** [comment]
Well dont I just feel silly now. I was not aware of that. Must have missed in the documentation.

It worked just fine upon fixing that issue in the code. Thank you.

**Comment by spfink** [comment]
Glad we could help! 

I have also sent a request to the service team to see if they can provide a more clear error message in this case.
