### ISSUE TITLE
SDK version should be 2.x

### ISSUE THREAD

**Issue by umcodemonkey** [aws/aws-sdk-java#819]
According to [semantic versioning](http://semver.org/), the SDK version should be at least 2.0; version 1.11.x has introduced at least one backwards incompatible change; the `AWSLog.createLogGroup` method was changed from returning void to returning a value; while this is a *compile-time* compatible change, it is a *binary-incompatible* change; libraries linked against 1.10.x will fail to run when attempting to invoke this method.

The SDK version should be updated to 2.0 on next release to reflect this incompatibile change.

**Comment by varunnvs92** [comment]
The versioning of AWS SDK for Java currently does not exactly match semantic versioning. Moving from 1.10.x to 1.11.x is consider a major version and we do this when we introduce breaking changes. Release notes for 1.11.0 mentions the breaking changes introduced in this major version.
https://aws.amazon.com/releasenotes/Java/9979983567247718

But in future we will be following semantic versioning when making breaking changes.
