### ISSUE TITLE
Unified exceptions

### ISSUE THREAD

**Issue by lesliel** [aws/aws-sdk-java#826]
DynamoDB has its own `ConditionalCheckFailedException` and `ProvisionedThroughputExceededException` classes, however similar errors (not provisioned but simple throughput exceptions) can arise in **SimpleDB** too, but they are presented only as a general `AmazonServiceException` with specific status code (int) and error code (String) (e.g. '_ConditionalCheckFailed_'). You should throw more specific exceptions for SimpleDB too.

Also several aws subprojects already have **similar exceptions** (e.g. `AlreadyExistsException` in both kms and simpleemail, etc.) that should be unified, or use a common, but still less general base (e.g. `com.amazonaws.services.common.model.AlreadyExistsException` as the parent for the current AlreadyExistsExceptions in kms and simpleemail) to preserve backward compatibility (and mark the current exception classes as deprecated).

Right now the different error flows as well as the duplicated exceptions (along with the different naming conventions) in the subprojects might suggest you have no architect for the whole sdk.

**Comment by shorea** [comment]
Shared types is something we've considered for some time but haven't made any progress on implementing it. It is challenging for SDKs that are modularized (i.e. each service in it's own module) as it becomes less clear where these shared shapes should live. It also has the side effect of coupling different services together which limits service teams ability to evolve their API. 

So while I do see value in having shared exceptions (and shared model types), I don't see it becoming a reality in the near future.

**Comment by lesliel** [comment]
Having shared types is not against modularization: it just defines a common path for your modules, thus decreasing code duplication, reducing excess work (design, coding and testing), and increasing overall quality of the whole SDK.

As of common exceptions: why don't you add them to the root/common module where `AmazonServiceException` is stored? Even if you prefer to have specific exceptions for each of your modules, they should have a common base "above" AmazonServiceException for each of the exception types; e.g. **conditional check failed** and **throughput exceeded** exceptions are pretty common for (almost) all of the SDK modules.
