### ISSUE TITLE
DynamoDB exceptions

### ISSUE THREAD

**Issue by ogmios-voice** [aws/aws-sdk-java#830]
DynamoDB should have dedicated **exception types** for all errors (listed under [Error handling](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html) and [Common errors](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/CommonErrors.html)) that should require special handling in the client. (e.g. there is a `LimitExceededException`, `ProvisionedThroughputExceededException`, etc. but there is **no** `ThrottlingException`, `UnrecognizedClientException`, etc.).

See also #826.

**Comment by shorea** [comment]
+1. I'll engage the service team to see if it's feasible to add modeled exceptions for more of these common errors.

**Comment by debora-ito** [comment]
Hi @ogmios-voice, we've passed your feature request to the DynamoDB team, so I'll go ahead and close this. Will update here when we hear back.

Feel free to reach out if you have further questions.
