### ISSUE TITLE
Some Jars contains large JSON files in models folder

### ISSUE THREAD

**Issue by shanielh** [aws/aws-sdk-java#831]
Hi, Some of the the JARs you publish contains large JSON files in models folder, For example : Dynamo DB - https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-dynamodb/1.11.29

Contains the following files : 

* `models/dynamodb-2012-08-10-intermediate.json` (5.2 MB)
* `models/streams.dynamodb-2012-08-10-intermediate.json` (546.4 kB)
* `models/dynamodb-2012-08-10-model.json` (263.6 kB)
* `models/streams.dynamodb-2012-08-10-model.json` (29.9 kB)

Are these files needed for run time?

Thanks

**Comment by shorea** [comment]
We may be able to omit the intermediate model. The other model at a minimum is needed for various tooling we have that reflects on the client. Is this a performance issue for you?

**Comment by shanielh** [comment]
Well, I will be happy if you'll omit the intermediate model, it costs in terms of space :smile: (And I guess that it isn't a problem in your side).

I'm aware that I can do it myself in my project definition; I just wanted to know if the client uses them ...

**Comment by shorea** [comment]
Yes it is safe to omit them for now. I'll create a task in our backlog to migrate off the intermediate model for our tooling and omit it from the client.

**Comment by shanielh** [comment]
Thanks :+1:

**Comment by shorea** [comment]
@shanielh this has been corrected. Models are now in a separate module thanks to @dagnir

**Comment by dagnir** [comment]
Hey @shanielh, we have added a new module named [aws-sdk-java-models](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-models) that just contains the model files. For now we have left in the individual client JARs, but eventually they will be removed from there.
