### ISSUE TITLE
Unable to execute HTTP request

### ISSUE THREAD

**Issue by nikolaitn** [aws/aws-sdk-java#833]
Hi,
I am using the latest java AWS SDK 1.11.30.

When I try to execute a request, for example whether a specified bucket exists,
I receive the following exception which happens from time to time and
for certain regions:
com.amazonaws.AmazonClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:724)
at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1234)
at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1191)

Regions that I do not observe this issue are US located. Issue occurs with EU and Asia regions.
Regards

**Comment by shorea** [comment]
What version of Java are you using? Sounds like you have outdated certs installed that can't validate newer regions.

Are you seeing the issue consistently for those regions or just periodically?

**Comment by nikolaitn** [comment]
Hi,
I am using java 1.8.0_92. I thought it might be certs related. This happens randomly for the problematic regions. I am executing the code on VM with suse linux.

When run the same code on my Win machine with same Java version I do not observe the issue.
Do you think it will be a good idea to switch to Rest calls using java or any other suggestions.

One other question, is there any example in java that I can use trying to tunnel all aws calls through Socks and HTTP Proxies?

Thanks

**Comment by nikolaitn** [comment]
Hi,
This happens randomly, for mentioned regions EU and Asia, no matter what is the Java version. It happens on Win and Linux, but only to VM lab machines. On my computer is ok. I am not sure, is some routing, TTL etc. not sure. I have copied cacerts file from my comp to the java versions on the VMs, even imported manually the certificate der file, from the console site, same result.

Please let me know if you have some info about those proxies.

Thanks

**Comment by duddns** [comment]
Hi @nikolaitn 
I had a similar problem, resolved to note the link below.
http://stackoverflow.com/a/30699960

**Comment by yzhong52** [comment]
FYI, I ran into this issue when I have Charles proxy enabled...

**Comment by yzhong52** [comment]
@AllysonYuShiong You probably have a different problem I had this issue when I have Charles proxy enabled. It works after I close it.

**Comment by AllysonYuShiong** [comment]
@yzhong52 thanks for reply. I need to restart my machine in order for it to work. I need to use charles proxy to capture the traffic so I must have charles proxy turned on. I tried cacerts and use us-west-2 region still it doesn't work with charles proxy.

**Comment by adtoniq** [comment]
> FYI, I ran into this issue when I have Charles proxy enabled...

I had the exact same issue with the Fiddler proxy enabled.
