### ISSUE TITLE
DynamoDB - Updating column used for GSI hash value

### ISSUE THREAD

**Issue by mvincellette** [aws/aws-sdk-java#837]
I'm using com.amazonaws:aws-java-sdk:1.11.29

I have a GSI hashkey on the "UserId" column in a particular table (no range key). On a selected row, I'd like to remove the "UserId" attribute, but I can't seem to do it. I can change the attribute, but I can't remove it. The primary hashkey on the table is "Id".

// lookup customer by primary hashkey
CustomerRow customerRow = dynamoDBMapper.load(CustomerRow.class, "Test");

// at this point, customerRow.getUserId() == "Freedom"

// update userId
customerRow.setUserId("");

dynamoDBMapper.save(customerRow, new DynamoDBMapperConfig(DynamoDBMapperConfig.SaveBehavior.UPDATE_SKIP_NULL_ATTRIBUTES);

// update succeeds, but on next read, customerRow.getUserId() still equals "Freedom"

**Comment by zhangzhx** [comment]
Does it happen only in GSI column? Did you turn on [consistent read](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.java#L387-L399) in the `DynamoDBMapperConfig`?

**Comment by mvincellette** [comment]
Hi, yes it only happens on the GSI column. If I set any other column to "" (empty string), it is removed from the row. I didn't try consistent reads (I'll give that a try), but I looked at the row through the AWS DynamoDB application several minutes later, and the column wasn't changed.

If I attempt to update the GSI column to any other value, it works fine. It's only when I attempt to set it to "" (empty string) that the issue occurs.

**Comment by mvincellette** [comment]
Sorry, clicked the wrong button. Didn't mean to close this...

**Comment by mvincellette** [comment]
Sorry, clicked the wrong button. Didn't mean to close this...

**Comment by mvincellette** [comment]
Hi, yes it happens only on the GSI column. I can change the value to any other string with no issues, but when I set it to "" (empty string), the value doesn't change, and the column remains in the table.

Setting any other column to "" (empty string), removes the column as expected.

**Comment by zhangzhx** [comment]
Hi, I couldn't reproduce the issue you described. With MapperConfig set as `SaveBehavior.UPDATE_SKIP_NULL_ATTRIBUTES`, all the empty/null attributes will not be updated no matter it's GSI or not.

If you use the default `SaveBehavior.UPDATE` setting, both the GSI and non-GSI columns will be updated, ie removed from the table.

**Comment by mvincellette** [comment]
Ok, I'll switch over to UPDATE mode. I was using some partial writes, so UPDATE_SKIP_NULL_ATTRIBUTES was more convenient, but this will still work. If I can extract a small sample program to illustrate the behavior, I'll re-post. Thanks for the quick response.
