### ISSUE TITLE
AwsFlowFramework disappeared at commit 2574564... "AWS SDK for Java 1.11.23"

### ISSUE THREAD

**Issue by billmccarthy** [aws/aws-sdk-java#838]
...not sure if that was intentional or not. If it was intentional, then the documentation here https://aws.amazon.com/swf/details/flow/ and here https://aws.amazon.com/code/3015904745387737 now has broken links.

**Comment by zhangzhx** [comment]
It is intentional. We moved the flow framework to [here](https://github.com/aws/aws-swf-flow-library) as a separate repo.

We'll update the broken links in the documentations. Thanks for pointing out.

**Comment by zhangzhx** [comment]
I noticed the links in the documentation are pointing to https://aws.amazon.com/sdk-for-java/. Although the source code of Flow Framework is out of this repo, the AWS SDK for Java distributed artifact still has dependency on it. So technically, the links are still valid.

**Comment by billmccarthy** [comment]
Thanks for pointing to the new repo.

**Comment by billmccarthy** [comment]
Not all the links are still valid. Go here: https://aws.amazon.com/swf/details/flow/, then click on "Download the samples", then, on the resulting page (which is https://aws.amazon.com/code/3015904745387737), click on the big "Download" button at the top.

Note the 404.

**Comment by zhangzhx** [comment]
Ah, I see. That's really a big breaking change. I will notice the service team to update the broken link for the Download. Thanks for bringing this up.
