### ISSUE TITLE
Uploading to S3 type storage chunked without knowing content length

### ISSUE THREAD

**Issue by yakovm3** [aws/aws-sdk-java#839]
I need to stream file to S3 type storage.

I know that V2 authorization do support chunked streaming using PUT without knowing the content length but Its not clear what the exact API and how exactly I implement such upload
I have found how to force V2 signer but not anything beyond that.
Note:I don't want to use multi-part upload.

Thanks

**Comment by zhangzhx** [comment]
Hi, the uploading (PutObject) currently doesn't support chunked encoding using SigV2. It is only feasible in SigV4 and you must enable [body signing](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/S3ClientOptions.java#L126). However, SDK is not exactly respecting the [Chunked Encoding specification](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) that it still calculates the Content-Length header before sending the body to the wire.

What is the use case for your request? Do you just need to send chunked content without knowing the length or do you have to use SigV2? Can you use SigV4 for sending the chunked content?

**Comment by yakovm3** [comment]
Hеre the user [says](https://forums.aws.amazon.com/thread.jspa?threadID=157894) 

> I had been using native Java to implement the REST api with V2 signature for a while until I realize the "streaming" that seems to work blows up when my data size gets large. The reason is because Java will buffer ALL the data in order to compute its length. When my data exceeds the heap size, my app will die. The way to work around it is to use "Transfer-coding = chunked"
Did this functionality existed?
In the end I want to stream my data without knowing the size beforehand.

**Comment by zhangzhx** [comment]
Hi @yakovm3,

I don't think this functionality exists at the moment. S3 has the [specification](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests) that the **Content-Length** header must be provided.

I can go ahead ask the S3 service team whether they have a plan to fully support chunked encoding scheme where the **Content-Length** header could be eliminated.

By the way, the chunked encoding feature is only supported when you are using SigV4 and enabling body signing.

**Comment by debora-ito** [comment]
S3 upload for objects with unknown content-length is now available in v2 TransferManager, using the CRT-based S3 client.

Check the Java SDK v2 [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html) for more information and some code examples using v2 TransferManager. If you experience any issue or have any feedback, let us know in the [v2 repo](https://github.com/aws/aws-sdk-java-v2/issues/new/choose).

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)

**Comment by narengogi** [comment]
8 years later and this functionality still doesn't exist
