### ISSUE TITLE
DynamoDBMarshalling

### ISSUE THREAD

**Issue by caio-northfleet** [aws/aws-sdk-java#840]
Hi,

We recently upgraded the SDK to version 1.11.31 and found that @DynamoDBMarshalling used extensively throughout our entities to handle complex types got deprecated.

Trying to follow the recomendation to use @DynamoDBTypeConverted we ended up on an issue. We had to created classes to all our lists and maps as to keep their generic types when marshalling them into JSON. So, for example, a List<MyComplexType> was wrapped into a MyComplexTypeList class that externds List<MyComplexType>. 

Using @DynamoDBMarshalling with a simple JSON marshaller/unmarshaller is working good, but as the annotation got deprecated we want to move to the new approach. 

Issue happens on the ConversionSchemas class on the getUnmarshaller method... the unmarshaller resolution gets a ListUnmarshaller which then tries to get the generic type of the list, which is not available for MyComplexTypeList (there is no generics in there). Same happens with maps, as it resolves to a MapUnmarshaller and there are not generics as key and value, as the MyComplexTypeMap is not a generic type since it extends HashMap<Integer, MyComplexType> (for example).

Maybe the question is: is there a way to reproduce the same bahaviour we had with @DynamoDBMarshalling with the new @DynamoDBTypeConvered, i.e., just handling convert/unconvert to a custom marshaller class?

Thanks,
Caio

**Comment by shorea** [comment]
Can you share some sample code? I was able to use the type converted annotation with a non-generic list here https://gist.github.com/shorea/caf706c8534d0d388e0db2896f26caf7.

**Comment by caio-northfleet** [comment]
Hi, thanks for sharing the sample code. Seeing that it works and doing some further investigations we realized the issue was actually on a customization we did on the DynamoDBMapper which we didn't push to the latest version.
