### ISSUE TITLE
Aws SDK for S3 Service Proxy Support

### ISSUE THREAD

**Issue by nikolaitn** [aws/aws-sdk-java#841]
Hi,
I am using the latest AWS SDK for java 1.11.32, does it have SOCKS4(5) proxy support.
HTTP proxy is working fine, but SOCKS seems not being supported?

Regards

**Comment by varunnvs92** [comment]
AWS SDK for Java internally uses Apache http client. So if apache http client supports SOCKS proxy without any customizations, the SDK should support it. As per my knowledge, apache client requires using raw sockets to support SOCKS, so you may be right that SDK doesn't support it.

Feel free to reopen if you have more questions. Thank you.
