### ISSUE TITLE
The underlying input stream must be initialized

### ISSUE THREAD

**Issue by antonleliuk** [aws/aws-sdk-java#843]
After I turned on metrics AwsSdkMetrics.enableHttpSocketReadMetric() I got an exception  
`Caused by: java.lang.IllegalStateException: The underlying input stream must be initialized!
	at com.amazonaws.internal.SdkSSLMetricsSocket.setMetrics(SdkSSLMetricsSocket.java:38)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:58)
`
when trying to call s3Client.listBuckets.
I'm using aws-java-sdk-s3 version 1.11.33

**Comment by varunnvs92** [comment]
Thanks for bringing up this issue. I was able to reproduce the behavior. Looking into why this is happening and will update once it is fixed.

**Comment by zhangzhx** [comment]
Hi, this is fixed from yesterday's release 1.11.35. Thanks for reporting this bug.
