### ISSUE TITLE
Exception on Condition Write with DynamoDBMapper

### ISSUE THREAD

**Issue by luyao226** [aws/aws-sdk-java#844]
Dear AWS developers:

I have a question regarding Condition Write with DynamoDBMapper. Basically it throws ConditionalCheckFailedException exception, but I could not figure out why.

I have an item in DynamoDB like this:

{
  "Items": [
    {
      "scheduledTaskStatus": {
        "laskInstancePingedTime": "Wed Sep 14 11:40:51 PDT 2016",
        "runningInstance": "USF45C89940C01",
        "lastTaskCompleteTime": "Wed Sep 14 11:40:51 PDT 2016"
      },
      "scheduledTaskName": "UploadMessageEventToS3"
    }
  ],
  "Count": 1,
  "ScannedCount": 1
}

I’m trying to do a condition write with DynamoDBMapper.save(item, condition), where my condition is the hostname matches the "runningInstance" in db. This is how I build the condition:

            final String condition2_key = "scheduledTaskStatus.runningInstance";
            
            final AttributeValue v2 = new AttributeValue();
            v2.setS(hostname); //host name is the same as value in DB here
            final ExpectedAttributeValue condition2_value = new ExpectedAttributeValue();
            condition2_value.setValue(v2);

            final Map<String, ExpectedAttributeValue> expected = Maps.newHashMap();            
            expected.put(condition2_key, condition2_value);
            
            final DynamoDBSaveExpression condition = new DynamoDBSaveExpression();
            condition.setExpected(expected);

but I got ConditionalCheckFailedException, but no details in the exception. I don't understand why it doesn't match. 

P.S. it worked for the top level, is this because I'm trying to access the nested field of the Map?

Any hint is greatly appreciated!

Jenny

**Comment by manikandanrs** [comment]
Oops. I may be wrong.

**Comment by luyao226** [comment]
Still thank manikandanrs for replying. The only reason I thought it supports is because I saw this in the documentation: 
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html

**Comment by fernomac** [comment]
As far as I understand you need to use a [condition expression](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html) to set a condition on a nested field. Your code using Expected is checking for an item that looks like `{"scheduledTaskStatus.runningInstance": "USF45C89940C01", ...}`. :(

**Comment by luyao226** [comment]
Hi Fernomac,

Could you please give me an example of how to using condition expression? I don't know where and how I can define something. I understand dynamodb is expecting to see the key like "#topLevel.#nextLevel", but where do I define  #topLevel = "scheduledTaskStatus" and #nextLevel = "runningInstance"?

Jenny

**Comment by fernomac** [comment]
Sorry @luyao226, I had a hard time figuring out how to use the expression stuff back when I was working with DynamoDB, and that was a while ago now. Good luck.

**Comment by varunnvs92** [comment]
@luyao226 
Can you give me sample program you are using. I can try creating an object similar to yours and try different combinations/condition expressions and see if something works.

**Comment by luyao226** [comment]
Hi, @varunnvs92 

This is the CLI I used to create the DynamoDB locally:
//*******************************
1. aws configure --profile local
2. aws dynamodb create-table --table-name nodes_coordinator --attribute-definitions AttributeName=scheduledTaskName,AttributeType=S --key-schema AttributeName=scheduledTaskName,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --profile local --endpoint-url http://localhost:8000
//*******************************

Here I attach the java source code. The main function in the Test.java is the code to run. 

[ConditionWrite.zip](https://github.com/aws/aws-sdk-java/files/473909/ConditionWrite.zip)

Thank you very much in advance!! Any idea is much appreciated.
Jenny

**Comment by manikandanrs** [comment]
@luyao226 

The values for #toplevel and #nextLevel goes in [ExpressionAttributeNames](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ExpressionAttributeNames) in the underlying Update Item API.

Here is a [blog post](https://java.awsblog.com/post/TxBG87QOQZRZJF/DynamoDB-XSpec-API) that talks about a feature in Java SDK called **xpec** that helps you work create expressions and use it with [DynamoDB Document API](https://java.awsblog.com/post/Tx1DDAWQGXWITSG/Introducing-DynamoDB-Document-API-Part-1) Although one point to note is that currently the xpec API is not supported in the mapper.

**Comment by luyao226** [comment]
Thank you everyone here! Made it work using PutItem's API with parameter nampMap and valueMap. Good to know this is not supported with mapper. Really appreciated your quick response!
