### ISSUE TITLE
DynamoDBMapper read problem with complex hash type

### ISSUE THREAD

**Issue by brucej72** [aws/aws-sdk-java#845]
There appears to be a problem with DynamoDB reads using the DynamoDBMapper class in the AWS Java SDK when using a hash key type that is complex.

The following bean class PlaylistBeanImpl has a complex type for its hash key and defines a marshaller class.
An instance of the bean can be constructed and saved to dynamo using DynamoDBMapper.save() and this works fine.

@DynamoDBTable(tableName="playlist")
public class PlaylistBeanImpl extends Playlist{

public PlaylistBeanImpl() {}
@DynamoDBMarshalling(marshallerClass=EntityIdentifierMarshaller.class)
@DynamoDBHashKey(attributeName="id")
public EntityIdentifier getEntityId() {return super.getEntityId();}

@Override
public void setEntityId(EntityIdentifier identifier) {super.setEntityId(identifier);}
}

However, when attempting to read the data back using DynamoDBMapper.load() we get the stack trace as below.
Logging was added to our marshaller class and we can see from the logging it was consulted on the write, but on calling DynamoDBMapper.load there is no logging from the method DynamoDBMarshaller.unmarshall(). We had similar results when we switched the marshaller class from and instance of DynamoDBTypeConverter to an instance of DynamoDBTypeConverter.

! Caused by: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: PlaylistBeanImpl[id]: could not set
! at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.set(DynamoDBMapperFieldModel.java:127) ~[aws-java-sdk-1.11.33.jar:na]
! at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperTableModel.asKey(DynamoDBMapperTableModel.java:271) ~[aws-java-sdk-1.11.33.jar:na]
! at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:461) ~[aws-java-sdk-1.11.33.jar:na]
! at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:412) ~[aws-java-sdk-1.11.33.jar:na]
! at org.codesaurus.aws.services.ddb.AbstractSingleEntryPerKeyPersistenceService.get(AbstractSingleEntryPerKeyPersistenceService.java:21) ~[org.codesaurus.aws.services.jar:na]
! at com.myriadgroup.radio.playlist.PlaylistDelegatingService.getPlaylistById(PlaylistDelegatingService.java:47) ~[com.myriadgroup.radio.playlist.jar:na]
! at com.myriadgroup.radio.ws.PlaylistWebservice.getPlaylist(PlaylistWebservice.java:62) ~[com.myriadgroup.radio.ws.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
! at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.22.1.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) ~[jersey-container-servlet-core-2.22.1.jar:na]
! ... 35 common frames omitted
! Caused by: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: could not invoke public void org.codesaurus.data.impl.Identifiable.setEntityId(org.codesaurus.data.EntityIdentifier) on class com.myriadgroup.radio.playlist.ddb.PlaylistBeanImpl
! at com.amazonaws.services.dynamodbv2.datamodeling.StandardMethodReflects$MethodReflect.set(StandardMethodReflects.java:82) ~[aws-java-sdk-1.11.33.jar:na]
! at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.set(DynamoDBMapperFieldModel.java:125) ~[aws-java-sdk-1.11.33.jar:na]
! ... 63 common frames omitted
! Caused by: java.lang.IllegalArgumentException: argument type mismatch
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
! at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
! at com.amazonaws.services.dynamodbv2.datamodeling.StandardMethodReflects$MethodReflect.set(StandardMethodReflects.java:80) ~[aws-java-sdk-1.11.33.jar:na]

**Comment by varunnvs92** [comment]
Can you please provide me working test code to repo the issue. Thanks.

**Comment by varunnvs92** [comment]
The log shows "java.lang.IllegalArgumentException: argument type mismatch". Can you make sure that the item in dynamoDB has same structure as the class passed to load method. 

Javadoc for DynamoDBMapper has a basic example for reference.
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html

**Comment by shorea** [comment]
Was not able to reproduce this either. Looks like you've got some inheritance in your model, do you mind sharing a complete code snippet?

**Comment by brucej72** [comment]
Yes, here you are. This is a full example that can run standalone and shows the same exception on the load. If I replace the key with a string type it all works fine. I added an arbitrary attribute  (creatorId ) that uses the same type (TestEntityIdentifier) that demonstrates the marshaller class works fine. It is only when the TestEntityIdentifier is used as the hash key that it fails

[dynamo_bug_source_java.zip](https://github.com/aws/aws-sdk-java/files/486722/dynamo_bug_source_java.zip)

**Comment by shorea** [comment]
Thanks for the code. 

I changed
```java
        TestPlaylistBeanImpl entity = mapper().load(TestPlaylistBeanImpl.class, id.toIdString());
```
to
```java
        TestPlaylistBeanImpl entity = mapper().load(TestPlaylistBeanImpl.class, id);
```
in TestPlayListService L45 and it worked. The mapper is expecting your hash key in raw, unconverted form and it will handle converting that to the actual attribute value.

Alternatively you can pass in just a TestPlayListBeanImpl object with the hash key set and call load.
