### ISSUE TITLE
S3 TransferManager do not handle S3 object version while copying objects

### ISSUE THREAD

**Issue by kamoor** [aws/aws-sdk-java#848]
com.amazonaws.services.s3.transfer.TransferManager ends up with error if you try to copy an object with a version. This is because MetaData object do not consider the version while setting prior copy. See line 1776 in TranferManager. 

**line 1776**
GetObjectMetadataRequest getObjectMetadataRequest = new GetObjectMetadataRequest(
                copyObjectRequest.getSourceBucketName(), copyObjectRequest.getSourceKey())
                .withSSECustomerKey(copyObjectRequest.getSourceSSECustomerKey());

**Comment by varunnvs92** [comment]
Which version of the SDK are you using? Can you provide a test case to repo the issue and error log?

**Comment by kiiadi** [comment]
Are these large objects being copied? The TransferManager automatically uses a multi-part copy if the object is over a certain size (default is 5GB - see here [TransferManagerConfiguration.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManagerConfiguration.java#L42))

Unfortunately S3 doesn't handle meta-data copy on a multi-part copy - see related issue #367 

You can explicitly set the metadata when you initiate the copy request and in this case it will get persisted - 

```java
copyObjectRequest.withNewObjectMetadata(metadata);
```

**Comment by kamoor** [comment]
@kiiadi I think copy method in TransferManager will always create a new GetObjectMetadataRequest regardless  of the fact copyObjectRequest has metadata set. See line 1776 in TransferManager

**Comment by kiiadi** [comment]
What version of the SDK are you using? The TransferManager creates a CopyCallable object with the details of the CopyObjectRequest - when a multi-part copy is initiated; if newObjectMetadata exists on the CopyObjectRequest it will get used otherwise a new ObjectMetadata object is created.

See https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/CopyCallable.java#L239

**Comment by kiiadi** [comment]
Closing aged issue, please feel free to reopen if this is still a problem.
