### ISSUE TITLE
Broken Link for AWS Flow Framework

### ISSUE THREAD

**Issue by devang-kredx** [aws/aws-sdk-java#852]
This page links to a github link which is not present- https://aws.amazon.com/code/Amazon-SWF/3015904745387737

Where can I find the latest code for SWF and AWS Flow Frameworks?

**Comment by kiiadi** [comment]
The SWF library has been moved into its own repository here are the samples: https://github.com/aws/aws-swf-flow-library/tree/master/src/samples/AwsFlowFramework 

Thanks for letting us know about the broken link we'll have the documentation updated.

**Comment by devang-kredx** [comment]
Thanks. Closing this issue.

**Comment by kiiadi** [comment]
Links on the documentation page have been updated - thanks again for letting us know.
