### ISSUE TITLE
Add in missing support for x-amz-server-side-encryption-context

### ISSUE THREAD

**Issue by mjgp2** [aws/aws-sdk-java#857]
Go client has it:

https://github.com/aws/aws-sdk-go/pull/674/files

**Comment by dagnir** [comment]
Hi thank you for bringing this to our attention. It doesn't look like Go actually has support for that yet; they've closed the linked PR and opened https://github.com/aws/aws-sdk-go/issues/750 to track its progress.

**Comment by tolidano** [comment]
Hi, pinging on this a year later. Any progress on this?

I've already implemented a tool in Python with boto3 (which *does* support x-amz-server-side-encryption-context) and I'd like to port it to Java (and then Go, so I see I have an uphill climb).

This is a pretty important part of integrity and adds to the security in some small way as the key alone won't decrypt, so an attacker will need to know our logic as well.

Do you accept PRs for this?

**Comment by tolidano** [comment]
Here is how I'm doing it in Boto3:

I've got a KMS handler module like this:
```
    def get_data_key(self, secret_name):
        context = self.get_encryption_context(secret_name)
        try:
            data_key_req = self._kms.generate_data_key(KeyId=self.key_id, KeySpec='AES_256',
                                                       EncryptionContext=context)
            data_key = data_key_req['Plaintext']
            data_key_ciphered = data_key_req['CiphertextBlob']
            response = {'plaintext': data_key, 'ciphered': data_key_ciphered}
        except ClientError as err:
            error_message = err.response['Error']['Message']
            print(error_message)
        return response

    def get_encryption_context(self, secret_name):
        return {'secret_name': secret_name, 'kms_key': self.key_id}

    def decrypt(self, ciphered, secret_name):
        context = self.get_encryption_context(secret_name)
        try:
            output = self._kms.decrypt(CiphertextBlob=ciphered, EncryptionContext=context)
        except ClientError as err:
            error_message = err.response['Error']['Message']
            print(error_message)
        return output
```

And an S3 handler module like this:

```
    def put(self, secret_name, secret_value):
        try:
            encryption_keys = self._cse_kms.get_data_key(secret_name)
            plaintext = encryption_keys['plaintext']
            ciphered = encryption_keys['ciphered']
            s3e = S3EncryptionClient(encryption_key=plaintext, client=self._s3)
            ciphered_key = self._cse_kms.get_ciphered_key_name(secret_name)
            s3e.client.put_object(Body=ciphered, Bucket=self.bucket_name, Key=ciphered_key,
                                  ServerSideEncryption='aws:kms',
                                  SSEKMSKeyId=self._sse_kms.key_id)
            s3e.put_object(Body=secret_value, Bucket=self.bucket_name, Key=secret_name,
                           ServerSideEncryption='aws:kms',
                           SSEKMSKeyId=self._sse_kms.key_id)
        except ClientError as err:
            error_message = err.response['Error']['Message']
            print(error_message)

    def get(self, secret_name):
        try:
            ciphered_s3_key = self._cse_kms.get_ciphered_key_name(secret_name)
            ciphered = self._s3.get_object(Bucket=self.bucket_name, Key=ciphered_s3_key)
            kms_response = self._cse_kms.decrypt(ciphered['Body'].read(), secret_name)
            plaintext = kms_response['Plaintext']
            s3e = S3EncryptionClient(encryption_key=plaintext, client=self._s3)
            value = s3e.get_object(Bucket=self.bucket_name, Key=secret_name)
        except ClientError as err:
            error_message = err.response['Error']['Message']
            print(error_message)

        return value
```

It relies on this Python library: https://github.com/boldfield/s3-encryption which allows Python to replicate the Ruby SDK client-side encryption logic (and that works great).

But as you can see, I'm attempting to use KMS DEKs instead of locally managed keys, so I want to supply the context.

**Comment by tolidano** [comment]
If you can explain how to replicate this functionality in Java with the current SDK, I'm interested. I imagine I could *not* use the AmazonS3EncryptionClient and just roll my own, but I'm really trying hard not to do that.

**Comment by PoeppingT** [comment]
For any others that come across this, it is actually supported with the current Java SDK:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/AbstractPutObjectRequest.java#L953-L963

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/SSEAwsKeyManagementParams.java#L26-L30

**Comment by debora-ito** [comment]
Thank you for the follow-up @PoeppingT.

Closing this, feel free to reach out if any other question come up.
