### ISSUE TITLE
Amazon ECR: Support for regions ap-southeast-1, ap-southeast-2, ap-northeast-1, eu-central-1 and us-west-1 not reflected in SDK

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#863]
The recently announced [Amazon EC2 Container Registry Region Expansion](https://aws.amazon.com/de/about-aws/whats-new/2016/08/amazon-ec2-container-registry-region-expansion/) to US West (N. California), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), and EU (Frankfurt) is not [reflected in the SDK yet](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json#L411).

This affects UX in terms of e.g. the added regions not being returned by `RegionUtils.getRegionsForService("ecr")`.

**Comment by manikandanrs** [comment]
Thanks for bringing this to our attention. I will stage a fix for our next week release.

**Comment by manikandanrs** [comment]
This will be added as part of next release.
