### ISSUE TITLE
aws s3 java-sdk is not working for versioned bucket

### ISSUE THREAD

**Issue by mkaja** [aws/aws-sdk-java#864]
http://docs.aws.amazon.com/AmazonS3/latest/UG/deleting-object-versioned-bucket.html ==> this java program is not working for buckets which is having version enabled.

**Comment by varunnvs92** [comment]
I don't see a java program in the provided link. Can you explain more and provide us a code sample to reproduce the issue you are seeing. If possible provide us the error log too. Thank you.

**Comment by mkaja** [comment]
link : http://docs.aws.amazon.com/AmazonS3/latest/dev/delete-or-empty-bucket.html#delete-bucket-awssdks 

Deleting S3 bucket: prd-datadriventypes
Caught an AmazonServiceException, which means your request made it to Amazon S3, but was rejected with an error response for some reason.
Error Message:    The bucket you tried to delete is not empty. You must delete all versions in the bucket. (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: 351B821D9B766190)
HTTP Status Code: 409
AWS Error Code:   BucketNotEmpty
Error Type:       Client
Request ID:       351B821D9B766190

**Comment by mkaja** [comment]
we were trying to migrate our buckets from one non-prod account to prod account and we were not able to delete the buckets which had version enabled on it. we used the java program to delete the versioned bucket but still we got error.
in order to keep the same naming convention for buckets( application requirement) we copied all prd-* to temp* on same account.

**Comment by varunnvs92** [comment]
I see the bug in the sample code. The listVersions operation is a paginated operation like listObjects operation but the existing sample does not consider that. I will fix the sample soon.

For now to unblock you, replace the code 1 in sample with code 2.

**Code to replace:**
```
for ( Iterator<?> iterator = list.getVersionSummaries().iterator(); iterator.hasNext(); ) {
    S3VersionSummary s = (S3VersionSummary)iterator.next();
    s3client.deleteVersion(bucketName, s.getKey(), s.getVersionId());
}
```

**Replacement:**
```
while (true) {
    for ( Iterator<?> iterator = list.getVersionSummaries().iterator(); iterator.hasNext(); ) {
        S3VersionSummary s = (S3VersionSummary)iterator.next();
        s3client.deleteVersion(bucketName, s.getKey(), s.getVersionId());
    }

    if (list.isTruncated()) {
        list = s3client.listNextBatchOfVersions(list);
    } else {
        break;
    }
}  
```

**Comment by varunnvs92** [comment]
Please try the above mentioned fix and let me know if it works for you.

**Comment by varunnvs92** [comment]
The documentation is updated. 
https://docs.aws.amazon.com/AmazonS3/latest/dev/delete-or-empty-bucket.html#delete-bucket-awssdks
