### ISSUE TITLE
getObjectMetadata throws an exception on a folder that has more than 1000 files

### ISSUE THREAD

**Issue by paraita** [aws/aws-sdk-java#870]
In my `s3://foo-bar` bucket I have two folders:

* FOLDER1 (has 10 files)
* FOLDER2 (has 1250 files)

In my code I have the following:
```
getService().getObjectMetadata(getBucket().getName(), "FOLDER2/")
```

But I get a AmazonS3Exception:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: <REQUEST_ID>), S3 Extended Request ID: <EXTENDED_ID>
```

I also tried running the same code without the leading separator character without any success.

Running the following code works:
```
getService().getObjectMetadata(getBucket().getName(), "FOLDER1/")
```

Am I doing something wrong ?

I am using version 1.11.222.

**Comment by kiiadi** [comment]
@paraita the concept of a "folder" is S3 is actually synthetic. S3 operates on objects in buckets (whose keys may have "/" to denote hierarchy).

You can see the difference clearly with the following:

```java
s3.putObject(bucketName, "foo/bar", someFile);
s3.putObject(bucketName, "folder/", "");
s3.putObject(bucketName, "folder/file", someFile);

s3.listObjects(bucketName).getObjectSummaries().forEach(o -> System.out.println(o.getKey()));
```
This should print out :
folder
folder/file
foo/bar

Notice that there's no "foo" key - as it was not explicitly created. Similarly we can do :

```java
s3.getObjectMetadata(bucketName, "folder/");
s3.getObjectMetadata(bucketName, "folder/file");
s3.getObjectMetadata(bucketName, "foo/bar");
```

But this will fail:
```java
s3.getObjectMetadata(bucketName, "foo/");
```

Hopefully that makes sense, let me know if you have any more questions.

**Comment by paraita** [comment]
Thank you @kiiadi for the answer, it makes sense now :)
