### ISSUE TITLE
Race condition during parent directory creation in S3 download

### ISSUE THREAD

**Issue by pbruski** [aws/aws-sdk-java#871]
When ServiceUtils.createParentDirectoryIfNecessary is called concurrently by several threads. File.mkdirs() call may fail because the directory already exists, although it hasn't existed before the mkdirs() call.
This no longer causes problems in the latest versions of SDK, because we create the parent dir upfront, but needs fixing nevertheless.

**Comment by kiiadi** [comment]
Fixed by fix to [ServiceUtils.createParentDirectory](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L343) closed PR #872
