### ISSUE TITLE
ExpressionSpecBuilder missing 'size' function

### ISSUE THREAD

**Issue by joprice** [aws/aws-sdk-java#873]
The documentation here http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html lists a function 'size' that may be used in conditional expressions. I'd like to use this in a conditional write defining my query with the `ExpressionSpecBuilder`.

**Comment by debora-ito** [comment]
Hi @joprice,

the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It will be considered for V2.

Please feel free to reach out if you have further questions or comments.
