### ISSUE TITLE
Overflow problem in ExponentialBackoffStrategy

### ISSUE THREAD

**Issue by yairzaslavsky** [aws/aws-sdk-java#874]
return (originalRequest, exception, retriesAttempted) -> (retriesAttempted > maxRetries) ? maxBackoffTime :
                Math.min(((1 << retriesAttempted) \* baseDelay), maxBackoffTime);

This might cause an overflow (negative integer value due to the overflow) and to return a negative delay value.

**Comment by dagnir** [comment]
This is fixed in version [`1.11.49`](https://aws.amazon.com/releasenotes/2981276408528428). Thanks again for your help in finding and fixing the issue!
