### ISSUE TITLE
How to implement your signed cookies ? 

### ISSUE THREAD

**Issue by jcyh** [aws/aws-sdk-java#876]
This is where i stuck from, i got three header for response header, but i do not know how to proceed with the instructions you have provided in the below like your instruction on http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html#private-content-how-signed-cookies-work. Kindly please give me some sample code of it, can you? [stackoverflow, nobody answer my question], there are lack of source on web too.

Instructions (Do not know how to proceed):
The user requests an object.

The user's browser or other viewer gets the name-value pairs from step 4 and adds them to the request in a Cookie header. This is the signed cookie.

CloudFront uses the public key to validate the signature in the signed cookie and to confirm that the cookie hasn't been tampered with. If the signature is invalid, the request is rejected.

If the signature in the cookie is valid, CloudFront looks at the policy statement in the cookie (or constructs one if you're using a canned policy) to confirm that the request is still valid. For example, if you specified a beginning and ending date and time for the cookie, CloudFront confirms that the user is trying to access your content during the time period that you want to allow access.

If the request meets the requirements in the policy statement, CloudFront serves your content as it does for content that isn't restricted: it determines whether the object is already in the edge cache, forwards the request to the origin if necessary, and returns the object to the user.

**Comment by dagnir** [comment]
Hi @jcyh, it's not clear from your question exactly what you need help with. Are you already able to generate the cookies?

**Comment by jcyh** [comment]
![capture](https://cloud.githubusercontent.com/assets/13764077/19225171/eef73766-8ec8-11e6-94a0-c2246335a7b6.PNG)

I set-cookie into response header, but i still do not able to stream video in private content distribution uisn signed cookies. Can anyone kindly please help me out on this ? Your help is greatly appreciated from me

**Comment by jcyh** [comment]
i understand request header is the one sent from browser to server, but how to set-cookie in request header? Is it have to put in request header? and how to sent cookie from browser to server ?

**Comment by jcyh** [comment]
Yes, i do got the response header with cookie, but i do not know how to
proceed with it...

if(mServerID == 4){

            SignedUrl signedMobileUrl = new SignedUrl("
dmrdmkpdtjgcn.cloudfront.net/ios", Constants._M3U8_VIDEO_PATH_PREFIX,
vidDetObj.getM3u8VideoURL(), vidDao.getVideoDuration(videoId));
            cookies = signedMobileUrl.getHTTPSignatureUrlCookie();

            //CloudFront Policy
            Cookie signedCookiePolicy = new
Cookie(cookies.getExpires().getKey(), cookies.getExpires().getValue());
            signedCookiePolicy.setDomain("dmrdmkpdtjgcn.cloudfront.net/ios/
");
            signedCookiePolicy.setPath("/");
            signedCookiePolicy.setMaxAge(365 * 24 * 60 * 60);
            response.addCookie(signedCookiePolicy);

            //CloudFront Signature
            Cookie signedCookieSignature = new
Cookie(cookies.getSignature().getKey(), cookies.getSignature().getValue());
            signedCookieSignature.setDomain("
dmrdmkpdtjgcn.cloudfront.net/ios/");
            signedCookieSignature.setPath("/");
            signedCookieSignature.setMaxAge(365 * 24 * 60 * 60);
            response.addCookie(signedCookieSignature);

            //CloudFront Key Pair ID
            Cookie signedCookieKeyPairID = new
Cookie(cookies.getKeyPairId().getKey(), cookies.getKeyPairId().getValue());
            signedCookieKeyPairID.setDomain("
dmrdmkpdtjgcn.cloudfront.net/ios/");
            signedCookieKeyPairID.setPath("/");
            signedCookieKeyPairID.setMaxAge(365 * 24 * 60 * 60);
            response.addCookie(signedCookieKeyPairID);
}
ObjectNode json = new ObjectNode(JsonNodeFactory.instance);

        json.put("id", videoId);
        json.put("title", vidPkg.getName() + " : " + thisLesson.getTitle()
+ " - " + vidDetObj.getTitle());
        json.put("pathFlash", vQuality.getPath() +
vidDetObj.getMp4VideoURL() + rtmpSignatureurl);
        json.put("pathM3U8", Constants._M3U8_VIDEO_PATH_PREFIX +
vidDetObj.getM3u8VideoURL());
        json.put("streamFlash", "rtmp://s147i5fdp1g822.cloudfront.net/cfx/st
");
        json.put("streamM3U8", "http://dmrdmkpdtjgcn.cloudfront.net/ios/");
        json.put("streamMp4", "http://dmrdmkpdtjgcn.cloudfront.net/ios/");

        json.put("allowVidQualityUpdate", vidPkg.allowLowBitRate()); //Will
use same value for determine 16:9 Aspect Ratio video. In future, pls use
another var for indication.
        json.put("allowLowBitRate", vidPkg.allowLowBitRate()); //For old
video player and player_mobile usage.
        json.put("vidAspectRatio", vidAR.getId());
        json.put("vidQuality", vQuality.getId());
        json.put("hasIndexData", hasIndexData);

        json.put("enableTrace", enableTrace); //Updated 14 Oct 2014: Always
enabled trace.
        json.put("cueList", new ObjectMapper().valueToTree(cueList));
        json.put("flowplayerLicKey", Constants._FLOWPLAYER_LICENSE_KEY);

        //For next part
        json.put("nextVidId", nextVidId);
        json.put("prevVidId", prevVidId);
        json.put("nextVidTitle", nextVidTitle);
        json.put("prevVidTitle", prevVidTitle);

        return json;
    }




public CookiesForCannedPolicy getHTTPSignatureUrlCookie(){
        DateTime utcCurrentTime = new DateTime(DateTimeZone.UTC);
        DateTime addedHour = utcCurrentTime.plusMinutes(10);
        String
currentTimeaddedHour=addedHour.toString("yyyy-MM-dd'T'HH:mm:ss'Z'");
        Date dateTimeLessThan =
DateUtils.parseISO8601Date(currentTimeaddedHour);

        Protocol protocol = Protocol.http;
        File privateKeyFile = new File("C:\\pk-APKAJLGHNOWIRMZ7Y2TA.pem");
        String s3ObjectKey = videoPath + videoURL;
        String keyPairId = "APKAJLGHNOWIRMZ7Y2TA";

        CloudFrontCookieSigner.CookiesForCannedPolicy cookies = null;
        try{
            cookies =
CloudFrontCookieSigner.getCookiesForCannedPolicy(protocol,
distributionDomain, privateKeyFile, s3ObjectKey, keyPairId,
dateTimeLessThan);
        }catch(Exception e){
            _log.error("Signature URL unable to generate");
        }
        return cookies;
    }

**Comment by dagnir** [comment]
Hey @jcyh, unfortunately this is not something we provide assistance with as it's not an issue with the SDK. With that said, it does look like the browser/client is sending the request with XHR so it could be an issue with Cross Origin Resource Sharing (CORS); try and see what you need to do so that your XHR requests set the `Cookie` header.

The [Amazon CloudFront Forum](https://forums.aws.amazon.com/forum.jspa?forumID=46&start=0) would also be a good resource to check out.

**Comment by jcyh** [comment]
Hey @Dongie Agnir, Will it be a problem if i use my desktop as localhost
server for testing this cloudfront signed cookies ? i have no problem using
cloufront signed url, but always encounter problem that video can't load if
use cloudfront signed cookies.
