### ISSUE TITLE
QUESTION: Is it a good practice to create a new client for each call we make to an AWS service e.g. SWF, S3 etc?

### ISSUE THREAD

**Issue by tankchintan** [aws/aws-sdk-java#877]
We are using AWS SDK for Java (version **1.11.6**). We use it for communicating with various AWS services like SWF, S3, SQS etc.

Currently for each activity we want to do with AWS service we create a brand new client & use it to perform the operations. E.g.
```  
public AmazonS3 createS3Client() {
    AWSCredentials s3AWSCredentials = new BasicAWSCredentials(settings.getAccessId(), settings.getSecretKey());
    AmazonS3 client = new AmazonS3Client(s3AWSCredentials);
    return client;
}
```
My question is, is this recommended? Should we be instead caching this object, by form of singleton & use that every time? Or we should create our own pool of such objects and use that?

Are there any best practices regarding this which I can read through?

**Comment by kiiadi** [comment]
It somewhat depends on your use-case but we would usually recommend re-using the client rather than newing up every time. This way multiple operations can share the same connection pool.
