### ISSUE TITLE
AmazonS3Exception with Elasticsearch

### ISSUE THREAD

**Issue by AntoineLemaire** [aws/aws-sdk-java#878]
I'm trying to create snapshots directly on a S3 bucket, but it throw a AmazonS3Exception:

    {"error":"SnapshotCreationException[[mysnapshotname:20161007-152322] failed to create snapshot]; nested: IOException[Unable to upload object preprodelasticsearch/snapshot-20161007-152322 due to AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 5B10DA56C7832AD2)]; ","status":500}

cleaned error:

    AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header

I saw lot of [topics][1] indicate I need to upgrade my Java & AWS, here my versions : 

    $ java -version
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

    $ aws --version
    aws-cli/1.11.2 Python/2.7.6 Linux/3.13.0-48-generic botocore/1.4.60

Problem should be solved on 1.10.1 version of AWS, but still get it in 1.11.2

  [1]: http://stackoverflow.com/questions/32058431/aws-java-sdk-aws-authentication-requires-a-valid-date-or-x-amz-date-header

**Comment by manikandanrs** [comment]
Can you check if you have a version of JodaTime greater than 2.8.1 is your class path ?

**Comment by kiiadi** [comment]
Also the [aws-cli](https://github.com/aws/aws-cli) and the [aws-sdk-java](https://github.com/aws/aws-sdk-java) are versioned separately. What version of the Java AWS SDK are you using?

**Comment by AntoineLemaire** [comment]
I didn't installed the java jdk myself, maybe Elastisearch did it for me? How could I get the version of the SDK/JodaTime?

**Comment by KumareshBabuNS** [comment]
The problem is creating snapshots on a S3 bucket but facing permission problem with response error code 403. Kindly check ACCESS_KEY and SECRET_KEY in path or set aws access key in aws cli command.

**Comment by AntoineLemaire** [comment]
@KumareshBabuNS Thanks. I checked, and both are well presents in elasticsearch.yml and I also tried to force them

![capture du 2016-10-10 18-58-01](https://cloud.githubusercontent.com/assets/2025537/19244288/edf84e38-8f1b-11e6-8310-ac31b6ba2820.png)

**Comment by kiiadi** [comment]
Are you using the Java SDK to S3 or are you using the CLI?

**Comment by KumareshBabuNS** [comment]
I think you are using OpenJDK. If it is true, uninstall OpenJDK. Install Oracle Java 1.8 and then try it.

**Comment by AntoineLemaire** [comment]
No, it's Oracle Java. I posted the `java -version` in the first post.

With OpenJDK it's look liked
```
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

```

**Comment by kiiadi** [comment]
@AntoineLemaire are you using the AWS Java SDK to talk to S3 or the cli (ie `aws...` at the command line)

Can you share a java-code snippet?

**Comment by KumareshBabuNS** [comment]
Does IAM user has permissions to access S3?

On Tuesday, 11 October 2016, Kyle Thomson <notifications@github.com> wrote:
> @AntoineLemaire are you using the AWS Java SDK to talk to S3 or the cli
(ie aws... at the command line)
>
> Can you share a java-code snippet?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/t5esQ22VLaSYELZyL2KZvHDLiuozMdxlhx80OeUWcMtW0iEB8bWQJGKhZcwUDE5C_kIaGGTpxwiN0HJiKCLP4bU_UuSINxCTycxJaJu5WncNwVZa8VzqU8OKR-7RWOxrp-9clvcNsz-zY_gTaNffd5HxN7w3jA=s0-d-e1-ft#https://github.com/notifications/beacon/APN4qg9AlqHg4K6XYVjjIqx8t-tNWcHAks5qypDVgaJpZM4KSZHU.gif>

**Comment by AntoineLemaire** [comment]
I don't know because it's a Elasticsearch feature. I'll check the documentation tomorow

https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws-repository.html

**Comment by KumareshBabuNS** [comment]
Kindly check IAM user has required permissions to perform your task.
Because the problem is about permission with error code 403.

On Tuesday, 11 October 2016, Antoine Lemaire <notifications@github.com>
wrote:
> I don't know because it's a Elasticsearch feature. I'll check the
documentation tomorow
>
>
https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws-repository.html
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/f8nYBEErqUWy5RXXsfIYJvul88xTY4ETSau-nbW229eLgL1gIsWrXjmusiuD8SkyePNhsQx4ytydu56hAJOl-KwFaezXCv2Qp8dChxMx-8dgqCTDReoipOD89rbM5D_I6lRNbCYSvffjx-4SAFaJmE8LMgX5FA=s0-d-e1-ft#https://github.com/notifications/beacon/APN4qtL58nK8QLhP_yRzqt1Gz3uJ_U7Mks5qypHQgaJpZM4KSZHU.gif>

**Comment by AntoineLemaire** [comment]
Ok, the version of https://github.com/elastic/elasticsearch-cloud-aws I used was 2.7.0, that is using Java SDK 1.9.34.
Just needed to migrate to elasticsearch-cloud-aws 2.7.1 which is using Java SDK 1.10.12, and it's sufficient to fix the problem!
