### ISSUE TITLE
InstanceProfileCredentialsProvider refresh is by default off

### ISSUE THREAD

**Issue by JeffAtDeere** [aws/aws-sdk-java#884]
Both [DefaultAWSCredentialsProviderChain](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java#L48) and the static instance of [InstanceProfileCredentialsProvider](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceProfileCredentialsProvider.java#L52) use the no arg constructor which does not periodically refresh the credentials on an EC2. I can't think of a time when I would want my EC2 credentials to expire. Could the default be made to refresh or provide a way to set/update this?

On an EC2, under heavy load, after about an hour I am getting:

```
com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
at our.code:0)
```

**Comment by kiiadi** [comment]
Are you getting any other exceptions logged out to debug? We should be logging if an attempt to get credentials from a provider fails [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSCredentialsProviderChain.java#L126).

Which CredentialsProviders are you actually using? If you expect to load credentials from EC2 it may make more sense to use the [InstanceProfileCredentialsProvider](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceProfileCredentialsProvider.java) directly rather than the chain. The concern with defaulting to the async refresh behaviour is that we're spinning up a new thread - that's probably something we want customers to opt-into.

**Comment by JeffAtDeere** [comment]
logging - do I not see those messages but I don't have logging turned up high enough to see errors logged at debug level.

provider - I run/test my application locally as well as deployed (EC2) so I use DefaultAWSCredentialsProviderChain.

changing defaults - Threads are cheap. The InstanceProfileCredentialsProvider thread that wakes once a minute and does one quick thing is super cheap especially given that we know this will only happen on EC2s so I disagree that the default should be off. Should the default stay off, I need to be able to enable to turn on the refreshing behavior on the static instance of InstanceProfileCredentialsProvider.

**Comment by kiiadi** [comment]
Actually if you turn on refreshCredentialsAsync by default it will attempt to fetch EC2 credentials regardless of whether you're on an EC2 instance or not - the async thread is created in the constructor.

This will fail, raising an exception on a non-EC2 instance. To test you can create the chain yourself:

```java
AWSCredentialsProvider provider = new AWSCredentialsProviderChain(
        new EnvironmentVariableCredentialsProvider(),
        new SystemPropertiesCredentialsProvider(),
        new ProfileCredentialsProvider(),
        new InstanceProfileCredentialsProvider(true));
Thread.sleep(5000);
```

**Comment by JeffAtDeere** [comment]
True so changing the default is right out.

Best case is if `InstanceProfileCredentialsProvider` could turn on refresh when it's the provider being used. (e.g. lazily in getCredentials()).

Next best is a way to turn refresh on after construction, particularly on the (singleton `InstanceProfileCredentialsProvider`)[https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/InstanceProfileCredentialsProvider.java#L51] (because it's made before I can do anything about it). Bonus points if I could tell the provider chain to auto refresh or not instead of trying to figure out if I'm on an EC2.

**Comment by kiiadi** [comment]
`AWSCredentialsProviderChain` implements `AWSCredentialsProvider` - it does expose a `refresh()` method which in-turn refreshes all of the underlying `AWSCredentialProvider` instances.

I like the idea that the `InstanceProfileCredentialsProvider` could (optionally) lazily load the credentials the first time getCredential is called and from that point on asynchronously refresh.

**Comment by JeffAtDeere** [comment]
Would you like a quick PR on that? Or what's next?

**Comment by kiiadi** [comment]
@JeffAtDeere  I took a stab at it, take a look at #889

**Comment by JeffAtDeere** [comment]
I still can't control if the singleton `InstanceProfileCredentialsProvider` refreshes or not plus I can't use the `DefaultAWSCredentialsProviderChain`.

I was thinking something more like [this commit](https://github.com/JeffAtDeere/aws-sdk-java/commit/b2ee6a8d62bab29aa93053bc6589728f3860cbb6). By saving the async refresh off and lazily starting the backgroud thread:
- the background thread only fires up if the `InstanceProfileCredentialsProvider` is the provider used to get credentials.
- it is safe to make the default as true even when not on an EC2
- I can use the `DefaultAWSCredentialsProviderChain` as well as the singleton of `InstanceProfileCredentialsProvider`. This could even let you remove both constructors on `InstanceProfileCredentialsProvider` (which is where it looks like AWS is going).

What do you think?

**Comment by kiiadi** [comment]
I made some comments on your commit; I like the way we only create the thread when we're going to refresh asynchronously (rather than having it running a no-op all the time in my implementation). I have some concerns around backwards compatibility and mutability though.

**Comment by JeffAtDeere** [comment]
To achieve 'at construction time' configuration for a singleton, I need something that comes before a singleton such as an environment variable  (there is [precedence](https://github.com/JeffAtDeere/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.java#L40])). Thoughts on that?

**Comment by kiiadi** [comment]
The `DefaultAWSCredentialsProviderChain` is provided as a convenience to serve *most* customers. As you can probably tell from my hesitation, I'm concerned about the impact of any changes in behaviour to this chain that may affect a large number of customers.

Could you not create your own `AWSCredentialsProviderChain` with the CredentialProviders that you need (configured the way you need them) ? Something along the lines of :

```java
new AWSCredentialsProviderChain(
   new SystemPropertiesCredentialsProvider(),
   new InstanceProfileCredentialsProvider(true, false)
)
```

**Comment by JeffAtDeere** [comment]
I added a comment to PR #889 which I would like to see updated and merged so I can safely use `new InstanceProfileCredentialsProvider(true)` locally (non-EC2) as deployed (EC2). Apart from that, I'm out of options given the restrictions of no breaking changes, no environment variables, and no mutable state (isn't `getCredentialsCalled` mutable state?). Thank you for your time and patience.

**Comment by kiiadi** [comment]
PR merged
