### ISSUE TITLE
SNS region selection does not follow SDK documentation

### ISSUE THREAD

**Issue by rocketraman** [aws/aws-sdk-java#887]
`AmazonSNSClient` does not respect the region selection documented in [Determining Region from Environment](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#determining-region-from-environment), if no explicit region is set as per point 1.

**Comment by shorea** [comment]
Are you using the client builders?

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/AmazonSNSClientBuilder.java

**Comment by rocketraman** [comment]
Oops, I missed that reference to "client builders" in the docs. Thanks for the feedback. Let me try that and close if it works.

**Comment by shorea** [comment]
Yeah it's a little ambiguous in the docs, especially with the constructor usage in the section above it. I'll clean up the docs and add a code example.
