### ISSUE TITLE
Filtered PaginatedQueryList result fails as Iterator can't be iterated

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-sdk-java#888]
(Copied from forum: https://forums.aws.amazon.com/thread.jspa?threadID=241057)

I execute a mapper query that contains a FilterExpression while going against a GSI. I expect to get no items returned in many executions of the query. No issues when items are returned. However, when the query returns no items, it seems to go off into doing a table scan since I get a ProvisionedThroughputExceededException.

Relevant code sections:

(Class A)

``` java
PaginatedQueryList<ClientListing> *queryResult* = mapper.query(ClientListing.class, queryExpression);
```

(Class B)

```
List<ClientListing> clList = [*queryResult* from other class]
    for (Iterator<ClientListing> iterator = clList.iterator(); iterator.hasNext();) {
            ClientListing cl = (ClientListing) iterator.next();
```

Creating the iterator is fine, but the `iterator.hasNext()` is the problem. The values in the PaginatedQueryList queryResult field are empty and count = 0. It should say there is "no Next" to get, but it goes off and tries to get the items from DDB. The PaginatedQueryList allResults object has 10 null values in the elementData array.

Same thing happens if I do a `clList.size()`. 

As I mentioned at first, there is a FilterExpression on the query. It's almost as if it's instantiating the PaginatedQueryList with a collection of null objects, then not recognizing there is nothing to get in the hasNext() method, but still trying.

Any thoughts? What does a developer do if he does get no values returned from the query that has a FilterExpression?

**Comment by kiiadi** [comment]
I'm trying to reproduce this and when I run the following I get "false" printed:

```java
PaginatedList<Item> result = mapper.query(Item.class, queryExpressionThatReturnsZeroResults);
System.out.println(result.iterator().hasNext());
```

Are you doing anything with the result list in between when you execute the query and you access the iterator?

**Comment by viper2846** [comment]
Hi Kiiadi,
I get a false as well. 

I don't quite understand what is happening behind the scenes.  In my query I have this:
DynamoDBQueryExpression<ClientListing> queryExpression = new DynamoDBQueryExpression<ClientListing>()
	.withKeyConditionExpression("franchiseArea = :val1")
	.withExpressionAttributeNames(ean)
	.withExpressionAttributeValues(eav)
	.withConsistentRead(false)
	.withIndexName("CLIndex")
	.withFilterExpression("resSearchData.#d = :val2");

The query itself seems to return quickly, but when it tries to do the hasNext() after creating the Iterator, it takes a long time (even though the returned list from the query has a count of 0).  I also see a spike  way beyond the Read Capacity of the index.  I bumped up the Read capacity on the index, but I still see spiking beyond the defined Read Capacity, which is why it seems like it is scanning the DDB table to find nothing is in the PaginatedQueryList (it seems like it is executing the query again).

**Comment by kiiadi** [comment]
Do you have a different pagination strategy in your `DynamoDBMapper` configuration? By default queries should be loaded lazily (ie: only the first result-set is loaded); of-course certain operations (including `.size()`) on the PaginatedList force loading the whole data-set; so that explains why you see the delay during iteration. It's definitely odd that it appears to be re-loading the data-set after you've already called `size()` (assume that's how you determined that the result was 0)

**Comment by varunnvs92** [comment]
Any updates?

**Comment by kiiadi** [comment]
Been a while since we've heard back on this one so going to close for now, feel free to re-open if this is still a problem.
