### ISSUE TITLE
AmazonS3.createBucket(bucketName) should use region set with setRegion()

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-sdk-java#89]
This makes the interface a lot more natural. Set on region and then expect all subsequent calls to target on that region by default. The current behavior is confusing.

**Comment by hanshuo-aws** [comment]
I believe this has been fixed at the client level:
https://github.com/aws/aws-sdk-java/blob/3baab096839f6848eed40940fb7b6f519a8e0580/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L771-L786
