### ISSUE TITLE
S3 presigned URL file upload failing with secured/https URL

### ISSUE THREAD

**Issue by sanjaypatel2525** [aws/aws-sdk-java#891]
I have two buckets, one private and one public. Private will have file with CannedAccessControlList.Private and public will have file with CannedAccessControlList.PublicRead. Apart from these they are all same.

`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>_</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>_</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

AmazonS3 s3client = new AmazonS3Client(new BasicAWSCredentials(AWS_ACCESS_KEY,AWS_SECRET_KEY));
            generatePresignedUrlRequest = new GeneratePresignedUrlRequest(AWS_BUCKET_PRIVATE_NAME, path,HttpMethod.PUT);
            generatePresignedUrlRequest.setExpiration(expiration); 
            generatePresignedUrlRequest.putCustomRequestHeader("x-amz-acl", CannedAccessControlList.Private.toString());
            generatePresignedUrlRequest.putCustomRequestHeader("content-type", fileType);
            url = s3client.generatePresignedUrl(generatePresignedUrlRequest);`

I able to upload file to s3 in below scenarios. All generated URL are by default https. 1. private bucket with https 2. public bucket failed over https, replaced https to http it worked.

Problem why public bucket upload is failing with https. I can't work with http on production system as it have ssl installed.

**Comment by kiiadi** [comment]
When you say it's failing - is the call to generatePresignedUrl failing or is the URL that's generated not working?

**Comment by sanjaypatel2525** [comment]
Its not failing while URL generation. Failing while upload in only one case when acl set to public-read. Url generated is https.
1. If i replace https url to http by string replace and use upload it with perfectly fine .
2. If i use same https url without replace it fails while upload.

**Comment by kiiadi** [comment]
@sanjaypatel2525 sorry about the radio silence on this one - I'm looking at trying to recreate this scenario locally. Can you give me a simple concrete example that reproduces this? The following works for me - what am I missing?

```java
AmazonS3 s3 = AmazonS3ClientBuilder.standard().withRegion("us-west-1").build();

s3.createBucket(new CreateBucketRequest(bucketName).withCannedAcl(CannedAccessControlList.PublicRead));

GeneratePresignedUrlRequest request = new GeneratePresignedUrlRequest(bucketName, key, HttpMethod.PUT);
URLConnection conn = s3.generatePresignedUrl(request).openConnection();

conn.setDoOutput(true);
((HttpURLConnection)conn).setRequestMethod("PUT");
conn.getOutputStream().write("Hello world!".getBytes());

conn.getInputStream();
```

**Comment by kiiadi** [comment]
Closing due to no response, please feel free to re-open if this is still an issue!

**Comment by jdkealy** [comment]
I'm having an issue with this too. When I create a presigned URL it uses the format  but HTTPS doesn't work for the above. I then need to regex and change http for https. I'd like to generate the presigned URL for s3.amazonaws.com/{bucket-name}/my-key... does that make sense ?

**Comment by juanmbellini** [comment]
Same here

**Comment by ahmedeldeeb25** [comment]
@jdkealy did you find a solution for your issue as I've the same one ?
