### ISSUE TITLE
Beanstalk Tags

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#894]
Please help...
I'm not finding a way to get tags for Beanstalk Environment... is it missing?

**Comment by woodstock3368** [comment]
Good question.  

I've go code that does locate the tags.  However, it does so via a round-about way.  You can describe the resources associated with the ElasticBeanstalk environment.  Then using the autoscaling group that is associated, you can see the tags.

Hopefully that helps until someone comes along with a better answer.

**Comment by bmagic39** [comment]
Sorry but I'm still not finding it
from Environment Resources I can get a list of AutoScalingGroup... but those don't have a way to get any tags, nor for the Environment neither for AutoScaleGrroup

**Comment by zhangzhx** [comment]
Seems like a feature request for the beanstalk service. I couldn't see the tags as well. I've reached out to the service team to see if they can answer your question.

**Comment by zhangzhx** [comment]
Service team said they will have this feature out soon. Please follow our [release notes](https://aws.amazon.com/releasenotes/Java?browse=1) announcement for this feature support in SDK.
