### ISSUE TITLE
Product Advertising API

### ISSUE THREAD

**Issue by ISchwarz23** [aws/aws-sdk-java#898]
I was not able to find anything regarding the product advertising API inside the Java SDK. Is there already, or is it planned to include the PAAPI to this SDK?

Best regards,
Ingo

**Comment by zhangzhx** [comment]
It's not part of the SDK for now, but it's on our backlog for supporting this.

**Comment by ISchwarz23** [comment]
As I have used the Product Advertising API in one of my products, I have created a small library to be able to create the request URLs in a very simple manner. You could find it here: https://github.com/ISchwarz23/Amazon-Product-Advertising-API-URL-Builder
Would it be helpful to integrate this in your SDK or to mention it in your docs, so other devs don't have the same thing I already did?

**Comment by zhangzhx** [comment]
I see the pattern to use your API is very diverged from our standard SDK APIs, we might not consider integrating our SDK. But we'll definitely consider mentioning this in our docs for other devs using it. I'll bring this up to the team, thank your for the contribution to AWS.

**Comment by ISchwarz23** [comment]
You are welcome. I'm glad, that my library is sophisticated enough to be referenced in your docs :)  
Could you post the link here as soon as the docs have been extended?

**Comment by zhangzhx** [comment]
I’ve consulted our internal docs experts and the policy is not to provide links to third-party implementations from within our documentation (with the exception of mature, well-known public libraries eg Maven, Gradle, Eclipse). Having said that the URL builder for PA-API does seem like a useful library and it would be nice for customers to be able to find it and decide whether or not it suits their use-case. What might be a good option is to open a pull-request against the AWS Open Guide (https://github.com/open-guides/og-aws), it’s maintained by a third-party and provides a place for several similar resources that customers find useful when working with AWS.

**Comment by zhangzhx** [comment]
Not seeing reply for over 3 months., closing this issue for now. Feel free to reopen it or cut a new one if needed.
