### ISSUE TITLE
User Pools authentication

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-java#900]
I see there is api to sign up but how do we sign in using Java SDK. I am aware we can do this with Javascript but I want to sign in using java SDK.

**Comment by zhangzhx** [comment]
Not sure if I follow, but can't you use AWS credentials (i.e access key and secret access key) to access AWS resources using Java SDK?

**Comment by hashitha** [comment]
This is for a Java client-side code. We also have a .net client app that would like for users to sign in but no method in sdk.

**Comment by debora-ito** [comment]
Hi @hashitha are you still experiencing this issue? 
If so, can you give us a more detailed use case? Where do you want to sign in?

**Comment by debora-ito** [comment]
I'm closing this for now, please reopen with more info on your use case, or if you have more questions.
