### ISSUE TITLE
Orphaned log message “[Fatal Error] :1:1: Premature end of file.”

### ISSUE THREAD

**Issue by ssurabhi** [aws/aws-sdk-java#902]
We are occasionally seeing the above message in stdout log file. There are 2 issues with the message
1. There is no context in the message, neither stack trace nor the name of the xml file that it failed to parse. 
2. That message is logged to std out file rather a  file configured thru application logger. 

After debugging, we found that it is caused due to parsing an empty xml type response from one  (SNS) of the aws services. Upon digging into logs we found that application is receiving an empty error response when http status is 503. But the code is still going ahead and parsing the empty error response resulting in error “premature end of file”. This is triggered from com.amazonaws.util.XpathUtils.documentFrom(InputSource). When an empty response is run with this code, you would see the output is going to std out, which is written from com.sun.org.apache.xerces.internal.util.DefaultErrorHandler.printError().

Here is the code snippet that we can use to reproduce this.   

`System.setProperty("javax.xml.parsers.DocumentBuilderFactory", "com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl"); XpathUtils.documentFrom("");`

Proposed Change: We want the message output to application log file with some context around what xml file it has failed to parse with stack trace. 

For example pass custom ErrorHandler that logs message with context using logger. 

```
DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance(); 
DocumentBuilder documentBuilder = factory.newDocumentBuilder(); 
String xml = "test.xml"; 
documentBuilder.setErrorHandler(new ErrorHandler() {     
@Override     
public void warning(SAXParseException exception) throws SAXException {        
 logger.warn(" Error parsing {}", xml, exception);     
}      
@Override     
public void error(SAXParseException exception) throws SAXException {         
logger.error(“ Error parsing {}", xml, exception);     
}      
@Override     
public void fatalError(SAXParseException exception) throws SAXException {         
logger.fatal(“ Error parsing {}", xml, exception);    
 }
 });
```

**Comment by kiiadi** [comment]
Can you post the full log message? Looking at the code when we attempt to parse the response XML we print "Unable to parse HTTP response content" along with the error message [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/DefaultErrorResponseHandler.java#L104).

I want to make sure we're in the right place, but this is probably where we want to add the log message - since we're logging anyway.

**Comment by ssurabhi** [comment]
Here is the full debug log. I think the code is rightly logging error highlighted bold below, but there is a downstream jdk class **DefaultErrorHandler.printError()**, that outputs "Premature end of file"  using system.out. That message is the problem as it is not giving the context, we are unsure which request or xml parsing has a problem.  

016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] o.a.h.i.conn.DefaultClientConnection - Receiving response: HTTP/1.1 503 Service Unavailable
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] org.apache.http.headers - << HTTP/1.1 503 Service Unavailable
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] org.apache.http.headers - << Date: Wed, 19 Oct 16 19:53:16 GMT
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] org.apache.http.headers - << Connection: close
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] org.apache.http.headers - << x-amz-id-2: QWZ1JxCkAsUDRl2poin2O9WLOJayOmZffB40tAnTLUF0rzzSj4qpo25yTrG1dqL3slEO/4S21N2DqpTyCD8JBFyD560k+27hwRk3dfB6j6fPz4Lf5tebHw==
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] org.apache.http.headers - << x-amz-request-id: B4D0093C035E1054
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] org.apache.http.headers - << Content-Length: 0
2016-10-19 19:53:16.736 +0000 [pool-8-thread-1] [DEBUG] com.amazonaws.requestId - x-amzn-RequestId: not available
2016-10-19 19:53:16.737 +0000 [pool-8-thread-1] [DEBUG] o.a.h.i.conn.DefaultClientConnection - Connection 0.0.0.0:53614<-><SCRUBBED>:8080 closed
2016-10-19 19:53:16.737 +0000 [pool-8-thread-1] [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection released: [id: 532][route:
{tls}
->http://us-west-2-proxy.lendingcloud.us:8080->https://sns.us-west-2.amazonaws.com][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2016-10-19 19:53:16.738 +0000 [pool-8-thread-1] [DEBUG] com.amazonaws.request - Received error response: com.amazonaws.AmazonServiceException: **Unable to unmarshall error response** () (Service: null; Status Code: 503; Error Code: 503 Service Unavailable; Request ID: null)

**Comment by kiiadi** [comment]
What version of the SDK are you using?

Don't think we're going to be able to get the requestId if the body is empty - as request ID typically resides in the error response body. But we should at least be able to log the body of the xml that we're trying to parse.

**Comment by ssurabhi** [comment]
hi, we are using SDK (aws-java-sdk-s3) 1.10.76. BTW, I think we are getting empty body of the xml when the service is unavailable. You can see that it happens when http status code is 503 and below is the service url that we are hitting in this case.

https://sns.us-west-2.amazonaws.com

**Comment by kiiadi** [comment]
Would something like this #909 give you the visibility you need?

**Comment by ssurabhi** [comment]
Hi Kyle, thank you for the changes, looks promising and gives visibility what we need.

**Comment by kiiadi** [comment]
This is queued up to go into the next release, I'm going to close the PR. If this resolves your issue please close the issue also.

**Comment by ssurabhi** [comment]
@kiiadi thank you for the fix. Do you know when is the next release?

**Comment by kiiadi** [comment]
I believe we have a release tomorrow, otherwise - Thursday.
