### ISSUE TITLE
S3 doesObjectExits redirection

### ISSUE THREAD

**Issue by kevinsdooapp** [aws/aws-sdk-java#908]
Hi everybody,
 
I'm trying to configure the modeshape storage of binary to S3 but I get this error:
 
Caused by: org.modeshape.jcr.value.binary.BinaryStoreException: `com.amazonaws.services.s3.model.AmazonS3Exception: Moved Permanently (Service: Amazon S3; Status Code: 301; Error Code: 301 Moved Permanently; Request ID: ****************), S3 Extended Request ID: ***************************
        at org.modeshape.jcr.value.binary.S3BinaryStore.storeValue(S3BinaryStore.java:213) ~[modeshape-jcr-5.2.0.Final.jar:5.2.0.Final]
        at org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:230)`
 
I'm using the last version of amazon aws java SDK (com.amazonaws:aws-java-sdk-osgi:1.11.48).
 
It look like when request doesObjectExits is performed, a Moved Permanently status is get by sdk.

Do you know how to fix this behaviour?

Thank you in advance!
 
Kevin

**Comment by dagnir** [comment]
Hi @kevinsdooapp, S3 will respond with a `301 Moved Permanently` if the user attempts to access a bucket from outside the region that it resides in.

In the 1.11.x version of the SDK, if no explicit region on the S3 client, it will send a preemptive `HEAD` Object request to S3 to determine the correct region to route the request to, so a user would not see this 301 but they would incur the extra latency of performing the `HEAD` request; the region for the given bucket will be cached for later operations so only one extra `HEAD` request will be sent for each unique bucket the S3 client encounters. If an explicit region *is* set though, the S3 client will always send requests to that region.

Please ensure that you are setting the correct region on your S3 client. Alternatively, you may also *not* specify an explicit region if you are okay with the client doing the extra `HEAD` request to find the right region for you.

  [This page](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) has a good summary of the errors S3 can respond with.

**Comment by kevinsdooapp** [comment]
>
S3 will respond with a 301 Moved Permanently if the user attempts to access a bucket from outside the region that it resides in.
> 
The request is performed from an ec2 instance in eu-west-1 to a bucket in eu-west-1. So 301 Moved Permanently should not be triggered no?
Anyway, I'll try by specifying the region to the S3 Client and keep you in touch.

**Comment by dagnir** [comment]
You're welcome! Glad I could help.
