### ISSUE TITLE
SQS MessageAttributes not being requested correctly

### ISSUE THREAD

**Issue by bacota-github** [aws/aws-sdk-java#912]
I'm unable to receive message attributes with AmazonSQSClient, though I can see the attributes using the command line utilities.  The difference seems to be that the command line utility is using a key "AttributeName.x" for each attribute name, whereas AmazonSQSClient.java is using "MessageAttributeName.x".  e.g.

2016-11-03 16:31:00,470 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7f44376508d0> (verify_ssl=True) with params: {'body': {'Action': u'ReceiveMessage', u'QueueUrl': u'https://sqs.us-east-1.amazonaws.com/181246307823/test', 'Version': u'2012-11-05', u'AttributeName.1': u'ApproximateFirstReceiveTimestamp'}, 'url': u'https://queue.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.10.16 Python/2.7.12 Linux/4.4.0-45-generic botocore/1.4.7'}, 'query_string': '', 'url_path': '/', 'method': u'POST'}

vs 

POST https://sqs.us-east-1.amazonaws.com /181246307823/test Parameters: ({"Action":["ReceiveMessage"],"Version":["2012-11-05"],"MessageAttributeName.1":["ApproximateFirstReceiveTimestamp"],"MessageAttributeName.2":["ApproximateReceiveCount"],"MaxNumberOfMessages":["10"],"WaitTimeSeconds":["20"]}Headers: (User-Agent: aws-sdk-java/1.11.49 Linux/4.4.0-45-generic Java_HotSpot(TM)_64-Bit_Server_VM/25.45-b02/1.8.0_45, amz-sdk-invocation-id: 01456ced-5ab0-2f54-77ca-d5aaff13aed0, ) 

I'm attaching a patchthat resolves the issue for me
[patch.txt](https://github.com/aws/aws-sdk-java/files/571800/patch.txt)

**Comment by shorea** [comment]
This seems to be working for me. Are you sure your calling the getMessageAttributes accessor and not the getAttributes accessor? Message attributes can be user defined, Attributes are a fixed set defined by the service. See http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

```java
        AmazonSQS sqs = AmazonSQSAsyncClientBuilder.defaultClient();
        final ReceiveMessageResult result = sqs.receiveMessage(new ReceiveMessageRequest("blog-queue")
                                                                       .withMessageAttributeNames("Foo", "Bar")
                                                                       .withAttributeNames("All")
                                                                       .withVisibilityTimeout(10)
                                                                       .withWaitTimeSeconds(20));

        for (Message message : result.getMessages()) {
            System.out.println(message.getMessageId());
            System.out.println(message.getAttributes());
            System.out.println(message.getMessageAttributes());
        }
```

**Comment by bacota-github** [comment]
You're right, that was it, I didn't catch the difference between Attribute and MessageAttribute.
