### ISSUE TITLE
1.11.53 Cloudformation invalid documentation link

### ISSUE THREAD

**Issue by drainx** [aws/aws-sdk-java#919]
I'm not sure how it is generated; however https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/AmazonCloudFormation.java#L43 and others in the cloudformation stack.

**Comment by dagnir** [comment]
Thank you for point this out! I will get in touch with the documentation team about it.

**Comment by dagnir** [comment]
I've contacted the documentation team. This will be fixed once they've fixed it on their end.

**Comment by dagnir** [comment]
A fix for this has been made internally by the docs team, and should be available in a future release, depending on when they give us the updated docs. Thanks again for reporting this!
