### ISSUE TITLE
ClientConfiuration.connectionMaxIdleMillis not honored by the IdleConnectionReaper

### ISSUE THREAD

**Issue by swehner** [aws/aws-sdk-java#921]
Hi,

The value set for connectionMaxIdleMillis in ClientConfiguration [1] is only used when setting up the HTTPClient, but the IdleConnectionReaper [2] totally ignores this values requests that all connections idle for more than 60 seconds to be closed.
This makes setting any timeout higher than 60 seconds impossible, as connections will be closed after a minute anyways.
Maybe the IdleConnectionReaper should read this timeout from the configuration instead of hardcoding it?

[1] https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L1682
[2] https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/IdleConnectionReaper.java#L172

**Comment by shorea** [comment]
+1, looking into this.

**Comment by shorea** [comment]
Pushed a change to address this, it will be included in the next release. Thanks for the suggestion!

**Comment by swehner** [comment]
Great! Thanks a lot!
