### ISSUE TITLE
Rest Client for AWS Hosted Elasticsearch

### ISSUE THREAD

**Issue by nikhil-sahu** [aws/aws-sdk-java#927]
Can you please include the REST Client to interact with the data present in elasticsearch.

The current aws-sdk-elasticsearch only provides means to configure the service and not the data.

For ESv < 5.x, there are third party libraries like [jest](https://github.com/searchbox-io/Jest) that provide a REST client and ES has to be open on port 80 to be accessible.

For ES >= 5.x, elastic itself provides a java [REST client](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/index.html) which can be wrapped around AWS security features to provide sdk . You would have to include ES 5.x in your hosted ES solution as well(Currently being supported are : 2.3 & 1.5)

**Comment by zhangzhx** [comment]
Thanks for the request. The SDK is auto generated from the service model. You can go to the AWS [Elasticsearch forum](https://forums.aws.amazon.com/forum.jspa?forumID=200) and ask the service team directly whether they have plan to support data plan operations. We'll provide client support once they have the model for these APIs.
