### ISSUE TITLE
Dynamodb FilterExpression for Java Mapper

### ISSUE THREAD

**Issue by tinnytian** [aws/aws-sdk-java#928]
Hello 
I am trying to use the dynamodb mapper on java side to run a query with know hash key.
How can I use a filter expression to do a OR selection? I keep getting error saying: Condition parameter type does not match schema type.

expressionAttributes.put(":val", new AttributeValue("LOL"));
        DynamoDBQueryExpression queryExpr = new DynamoDBQueryExpression()
                .withIndexName("t-freq-index")
                .withLimit(pageSize)
                .withConsistentRead(false)
                .withHashKeyValues(report)
                .withFilterExpression(":val = rname")
                .withExpressionAttributeValues(expressionAttributes);

Thanks

**Comment by zhangzhx** [comment]
The FilterExpression you typed is in a wrong format.

See [ConditionExpressionReference](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html#ConditionExpressionReference) for the detailed description for the schema. 

Note
The syntax for FilterExpression is identical to that of ConditionExpression. In addition, FilterExpression uses the same comparators, functions, and logical operators as ConditionExpression. However, FilterExpression does not allow key attributes. You cannot define a filter expression based on a partition key or a sort key.
