### ISSUE TITLE
Problem saving DynamoDBDocument annotated property in collection with DynamoDBMapper

### ISSUE THREAD

**Issue by tstroband** [aws/aws-sdk-java#932]
There seems to be a problem saving a collection (List) property of a class that is annotated with DynamoDBDocument.
The error message is:
`com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: not supported; requires @DynamoDBTyped or @DynamoDBTypeConverted`

A DynamoDBDocument-annotated property that is not in a collection will be saved correctly. 

The problem occurs in version 1.11.60

The following sample code will illustrate the problem:
`  @DynamoDBTable(tableName="MyObject")
public class MyObject {

    @DynamoDBHashKey(attributeName = "uid")
    public String getUid() {
        ...
    }

    @DynamoDBAttribute(attributeName = "myData")
    public MyData getMyData() {
        ...
    }

    @DynamoDBAttribute(attributeName = "myOtherData")
    public List<MyData> getMyOtherData() {
        ...
    }

    @DynamoDBDocument
    public static class MyData {
        @DynamoDBAttribute(attributeName = "someProperty")
        public String getSomeProperty() {
        }
    }
}`

The problem occurs with the myOtherData property that returns a list. The myData property works fine.

Possibly related to issue #817. The last comment mentions that a problem remains whe the property involves a collection.

**Comment by zhangzhx** [comment]
Can't repro this exception with your sample code. Tried both save and load and it worked for me. Can you provide more context for your issue, like some sample code and the error trace?

**Comment by zhangzhx** [comment]
Closing this issue now as I don't hear back for 10 days. Feel free to reopen this if you still have this issue.

**Comment by BigChief45** [comment]
I am experiencing the same issue with JDK version `1.11.179`. @tstroband Did you found a solution for this?
