### ISSUE TITLE
Downloading of object in client side (browser) fails when using same SSE-C key which has been used for PutObjectRequest 

### ISSUE THREAD

**Issue by ChiranjibKarn** [aws/aws-sdk-java#933]
I have a Grails application that uses aws-sdk-s3:2.0.5 plugin, which in-turn uses aws-java-sdk-s3-1.11.49.jar.
I can successfully encrypt an object using SSE-C key, and put it in S3 bucket.  

```
SecretKey secretKey = null
  try {
            KeyGenerator generator = KeyGenerator.getInstance("AES")
            generator.init(256, new SecureRandom())
            secretKey = generator.generateKey()
        } catch (Exception e) {
            e.printStackTrace()
        }
        SSECustomerKey sseKey = new SSECustomerKey(secretKey)
	/* ssKey.md5 is empty here */
        PutObjectRequest putObjectRequest = new PutObjectRequest("bucket_name", "s3-file-key", new File(fullFilePath)).withSSECustomerKey(sseKey)
        amazonS3Service.getClient().putObject(putObjectRequest)
```
My requirement is to access the object using REST in front-end (angularJs web application), how do I get required header values ("x-amz-server-side​-encryption​-customer-algorithm", "x-amz-server-side​-encryption​-customer-key", "x-amz-server-side​-encryption​-customer-key-MD5" and signature) ?

I have tried following:
```
GeneratePresignedUrlRequest presignedUrlRequest = new GeneratePresignedUrlRequest("bucket_name", "s3-file-key").withSSECustomerKey(sseKey)
presignedUrlRequest.setMethod(HttpMethod.GET)
presignedUrlRequest.setExpiration(new Date()+1)
String amzUrl = s3Client.generatePresignedUrl(presignedUrlRequest).toString()
```
But the amzUrl does not contain the required header.

I know I can get the S3 object from GetObjectRequest but it again will be in my back-end (grails server side) availability of the object, I need it to be accessed directly from front-end (client side browser) application with required headers/url parameters set.

I have refer following Docs:
[http://docs.aws.amazon.com/AmazonS3/latest/dev/sse-c-using-java-sdk.html](url) and 
[http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html#sse-c-how-to-programmatically-intro](url)

**Comment by shorea** [comment]
Take a look at https://aws.amazon.com/blogs/developer/generating-amazon-s3-pre-signed-urls-with-sse-c-part-4/. Note that when using SSE-C you need to send the appropriate headers in the request made with the presigned URL.
