### ISSUE TITLE
Thread leak on glassfish application shutdown using AmazonCloudWatchClient

### ISSUE THREAD

**Issue by bobbotron** [aws/aws-sdk-java#934]
Hi there,

I'm using the AmazonCloudWatchClient in an EJB to log some custom metrics to cloudwatch.  On app server startup the client is created, and on app shutdown the client is shutdown using:

`amazonCli.shutdown();`

When the application is undeployed, we're seeing the following error messages:

```
[2016-12-06T12:07:12.369-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=113 _ThreadName=admin-listener(6)] [timeMillis: 1481044032369] [levelValue: 1000] [[
  The web application [/XYZ] created a ThreadLocal with key of type [com.amazonaws.auth.AbstractAWSSigner$1] (value [com.amazonaws.auth.AbstractAWSSigner$1@39054dd0]) and a value of type [java.security.MessageDigest.Delegate] (value [SHA-256 Message Digest from SUN, <initialized>
]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]

[2016-12-06T12:07:12.371-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.web.util] [tid: _ThreadID=113 _ThreadName=admin-listener(6)] [timeMillis: 1481044032371] [levelValue: 1000] [[
  The web application [/XYZ] created a ThreadLocal with key of type [com.amazonaws.auth.SigningAlgorithm$1] (value [com.amazonaws.auth.SigningAlgorithm$1@396e15e3]) and a value of type [javax.crypto.Mac] (value [javax.crypto.Mac@411308ff]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]
```
My best guess is that a ThreadLocal should be destroyed/cleaned up when shutdown is called.  Is there a method to do this already, or is this a bug?

Thanks!

**Comment by varunnvs92** [comment]
what version of the SDK are you using?

**Comment by shorea** [comment]
Possible duplicate of https://github.com/aws/aws-sdk-java/issues/918? Are you seeing an actual memory leak or just the log messages? It's possible this is a red herring.

**Comment by bobbotron** [comment]
Hi @varunnvs92, good q, I didn't think to check that!  Just updated to 1.11.63, still seeing the same behaviour.

**Comment by varunnvs92** [comment]
Did you look into the issue linked by shorea@. Was it helpful?

**Comment by bobbotron** [comment]
I did.  Seems definitely possible; I haven't had the time to confirm with a debugger whether the leak is occurring or not and if this is a warning that we can ignore.

**Comment by bobbotron** [comment]
I downloaded the AWS java SDK source, it looks like the two culprits are in AbstractAWSSigner and SigningAlgorithm, where static final ThreadLocal variables are created.  From what I understand there's no good way to clean up static final variables in java so the issue would require rework of these two classes (at least) to have these cleaned up when unloaded by a classloader?  I think this would be ideal library behaviour.

```
aws-sdk-java: fgrep -R "ThreadLocal" *
aws-java-sdk-core/src/main/java/com/amazonaws/auth/AbstractAWSSigner.java:    private static final ThreadLocal<MessageDigest> SHA256_MESSAGE_DIGEST;
aws-java-sdk-core/src/main/java/com/amazonaws/auth/AbstractAWSSigner.java:        SHA256_MESSAGE_DIGEST = new ThreadLocal<MessageDigest>() {
aws-java-sdk-core/src/main/java/com/amazonaws/auth/SigningAlgorithm.java:    private final ThreadLocal<Mac> macReference;
aws-java-sdk-core/src/main/java/com/amazonaws/auth/SigningAlgorithm.java:        macReference = new ThreadLocal<Mac>() {
```

**Comment by dagnir** [comment]
Hi @bobbotron were you able to check if you're actually seeing a leak? Since the classes stored in the `ThreadLocal` are not application classes, they should be able to be GC'd.

**Comment by bobbotron** [comment]
I don't have the time to track this down currently.  I'll let you know if I ever do get to the bottom of it.  :^|

**Comment by davidmoten** [comment]
I'd like to see this issue reopened. I see exactly the same behaviour in that Glassfish writes SEVERE log lines on container shutdown or application redeploy. We monitor for the existence of SEVERE log lines and raise on-call alerts when seen.

I'm not concerned about this as a GC leak as @dagnir mentioned however after benchmarking I don't see any significant benefit to holding ThreadLocal caches of SHA-256 MessageDigest instances (in AbstractAWSSigner.java) and Mac SHA-1,SHA-256 instances (in SigningAlgorithm.java). If we remove ThreadLocal usage from these classes then Glassfish will no longer log SEVEREs making my life easier. This may also be problematic in Tomcat and perhaps other containers.

For the AbstractAWSSigner case I ran JMH benchmarks that created and applied a MessageDigest instance to an 8 byte array in these variants:
* create a new MessageDigest instance and apply it to bytes
* clone an existing MessageDigest instance an apply it to bytes
* get a ThreadLocal MessageDigest, reset it and apply it to bytes

Here are the results:
```
Benchmark                                     Mode  Cnt        Score       Error  Units
DigestBenchmarks.createNewDigestAndUse       thrpt   10  1368554.701 ± 17528.805  ops/s
DigestBenchmarks.cloneMessageDigestAndUse    thrpt   10  1529761.626 ±  3525.232  ops/s
DigestBenchmarks.getThreadLocalDigestAndUse  thrpt   10  1648388.630 ±  9248.017  ops/s
```

For starters, creating a new MessageDigest every time is still very fast (1.4 million a second) and is 83% as fast as using the ThreadLocal version. Note that I was using a very small byte array as input and the margin between the methods would very likely reduce as the array size increases.

I included the clone case out of interest but I shy away from that one as implementing clone is not mandatory and different JVMs may differ.

**Would the team be open to a PR from me where we create a new MessageDigest instance every time?**

Here's the benchmarking code:
```java
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import org.openjdk.jmh.annotations.Benchmark;

public class DigestBenchmarks {

    private static final byte[] input = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 };
    private static final ThreadLocal<MessageDigest> messageDigestThreadLocal = new ThreadLocal<MessageDigest>() {
        @Override
        public MessageDigest initialValue() {
            return createMessageDigest();
        }
    };
    private static final MessageDigest messageDigest = createMessageDigest();
 
    @Benchmark
    public byte[] createNewDigestAndUse() throws NoSuchAlgorithmException {
        MessageDigest d = MessageDigest.getInstance("SHA-256");
        return d.digest(input);
    }

    @Benchmark
    public byte[] getThreadLocalDigestAndUse() throws NoSuchAlgorithmException {
        MessageDigest d = messageDigestThreadLocal.get();
        d.reset();
        return d.digest(input);
    }
    
    @Benchmark
    public byte[] cloneMessageDigestAndUse() throws NoSuchAlgorithmException {
        MessageDigest d;
        try {
            d = (MessageDigest) messageDigest.clone();
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
        return d.digest(input);
    }

    private static MessageDigest createMessageDigest() {
        try {
            return MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by davidmoten** [comment]
Happy to transfer this to a fresh issue if desired (I see the title talks about leaks).

**Comment by davidmoten** [comment]
Moved discussion of removing ThreadLocal use to new issue #1704
