### ISSUE TITLE
QueueBufferConfig copy constructor excludes flushWithShutdown

### ISSUE THREAD

**Issue by dasousa** [aws/aws-sdk-java#940]
The com.amazonaws.services.sqs.buffered.QueueBufferConfig copy constructor does not copy the flushWithShutdown attribute.  The effect is to disable the buffer flush that can occur with the buffered asynchronous client during shutdown.

```java
public QueueBufferConfig(QueueBufferConfig other) {
    longPoll = other.longPoll;
    longPollWaitTimeoutSeconds = other.longPollWaitTimeoutSeconds;
    maxBatchOpenMs = other.maxBatchOpenMs;
    maxBatchSize = other.maxBatchSize;
    maxBatchSizeBytes = other.maxBatchSizeBytes;
    maxDoneReceiveBatches = other.maxDoneReceiveBatches;
    maxInflightOutboundBatches = other.maxInflightOutboundBatches;
    maxInflightReceiveBatches = other.maxInflightReceiveBatches;
    visibilityTimeoutSeconds = other.visibilityTimeoutSeconds;
}
```

When a new QueueBuffer is added to the buffers map in AmazonSQSBufferedAsyncClient, a copy of the QueueBufferConfig is made at line 375.  The flushWithShutdown attribute of the new copy will always be false.

```java
private synchronized QueueBuffer getQBuffer(String qUrl) {
    QueueBuffer toReturn = buffers.get(qUrl);
    if (null == toReturn) {
        QueueBufferConfig config = new QueueBufferConfig(bufferConfigExemplar);
        toReturn = new QueueBuffer(config, qUrl, realSQS);
        buffers.put(qUrl, toReturn);
    }
    return toReturn;
 }
```

AmazonSQSBufferedAsyncClient.shutdown iterates over the buffers map, and calls shutdown on each buffer.  QueueBuffer.shutdown checks its QueueBufferConfig, and will only flush if flushOnShutdown is true.
```java
public void shutdown() {
    if (config.isFlushOnShutdown()) {
        flush();
    }
    receiveBuffer.shutdown();
}
```

**Comment by kiiadi** [comment]
That's definitely odd - I'll take a look.

**Comment by kiiadi** [comment]
Fixed : https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/buffered/QueueBufferConfig.java#L153
