### ISSUE TITLE
http clients are being blocked on network IO when parsing the responses 

### ISSUE THREAD

**Issue by pepribas** [aws/aws-sdk-java#943]
Creating the event reader seems to try to read some bytes from the
passed input stream by the looks of it, in order to determine the
encoding. A read on the http input stream causes network access
and suddenly all threads are blocked on that first synchronized block.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/StaxResponseHandler.java#L90

See #942

**Comment by debora-ito** [comment]
Just a quick update letting you know that the SDK team has reviewed the feature request list for V1 and this looks like a great candidate for a community PR, which we’ll help merge in and support. 

See #942 for context and suggestions for the change.
