### ISSUE TITLE
NetworkAclEntry.icmpTypeCode is always null.

### ISSUE THREAD

**Issue by bagovino** [aws/aws-sdk-java#947]
The NetworkAclEntry.icmpTypeCode field is always null regardless of if there should be a value set for it. This is using 1.11.66.

Steps to reproduce:

1) Create or modify a network ACL and add a new network ACL entry that uses any type code. In my case the entry was configured to use SSH (22).
2) The following code fragment should query us-east-1 network ACLs and output if any entries have a non-null IcmpTypeCode. It seems to always be null no matter what:
```java 
AmazonEC2 ec2 = AmazonEC2ClientBuilder.standard().withRegion(Regions.US_EAST_1).withCredentials(new InstanceProfileCredentialsProvider(false)).build();
List<NetworkAcl> nacls = ec2.describeNetworkAcls().getNetworkAcls();
for (NetworkAcl nacl : nacls) {
    System.out.println(String.format("%s has an entry with a non-null IcmpTypeCode: %s", nacl.getNetworkAclId(), nacl.getEntries().stream().anyMatch(entry -> entry.getIcmpTypeCode() != null)));
}
ec2.shutdown();
```

**Comment by fulghum** [comment]
Hey bagovino, could you turn on verbose wire logging for us?  That'll show us exactly what EC2 is returning in the response and tell us if the SDK is not parsing the response correctly, or if it's the EC2 service that's not sending the data.

The Java SDK Developer Guide has a topic explaining how to turn on verbose wire logging:
http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

**Comment by bagovino** [comment]
Sure, I attached it to this comment. Let me know if you need anything else.

[verbose-log.txt](https://github.com/aws/aws-sdk-java/files/655293/verbose-log.txt)

**Comment by varunnvs92** [comment]
Thanks for providing the wirelog. If you look at the log, none of the NetworkAclEntry items have the icmpTypeCode (Look for items in <entrySet>).  So the SDK returns null. 

I don't know a lot about the EC2 specific stuff but I suggest you to double check whether your network Acls are configured with the ICMP code or not. You can also reach out to service team through https://forums.aws.amazon.com/forum.jspa?forumID=30
