### ISSUE TITLE
Release notes missing for versions 1.11.66 and 1.11.67

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#949]
Hi Team,

Could you please publish the usual [AWS SDK for Java Release Notes](https://aws.amazon.com/releasenotes/Java) for the last two versions 1.11.66-67?

As outlined on #759, _Inspecting the SDK diffs has always been difficult due to the sheer size of that (usually) single commit per release [...]. The release notes provide very important guidance accordingly and ease focusing on those areas of an SDK update that might impact the dependent product in question_.

Also, the [AWS Release Notes](https://aws.amazon.com/releasenotes) feature RSS feeds that ease unified monitoring and filtering of the ever increasing volume of new features that you are making available across the entire AWS portfolio :)

Many thanks!

**Comment by kiiadi** [comment]
I'll get these out by end of day.

**Comment by hopel** [comment]
@kiiadi - the ones for 1.11.53 seem to be missing as well.

**Comment by hopel** [comment]
@kiiadi - argh, sorry for the piecemeal reporting, but 1.11.60 looks missing as well.

**Comment by kiiadi** [comment]
These have been published now, sorry about the delay.
