### ISSUE TITLE
removing the property awsjavasdk.version in pom.xml in favor for project.version

### ISSUE THREAD

**Issue by muellerc** [aws/aws-sdk-java#950]
As I'm discovering the source, I'm wondering why we are using the property awsjavasdk.version which points to the latest release version. In my eyes, this prevents real continuous integration because it doesn't integrate the latest binaries. Did I miss something?
I updated the source in my fork so that awsjavasdk.version points to ${project.version} and the build went well. I would like to provide a patch where we could totally get rid of this property, but the dependencies section has a comment it's auto generated and no changes are allowed. Where can I find some more information how it's generated and how to "adjust" the generator?

Thanks in advance for your time,
Christian

**Comment by kiiadi** [comment]
@muellerc not sure how having the property prevents continuous integration - can you elaborate a bit? This is just a property we refer to that it's defined in the parent pom (https://github.com/aws/aws-sdk-java/blob/master/pom.xml#L132). It points to the latest released version of the SDK (which is not necessarily the same as project.version which may include a SNAPSHOT version instead)

**Comment by muellerc** [comment]
Hi Kyle,
thanks for taking the time looking into it.
The goal of continuous integration is to to integrate (compile, package, test) the entire code which will be released in the next release. This is not the case at present. For example: Assuming the trunk version is 1.11.69-SNAPSHOT, the version of aws-java-sdk-s3 is the same, but it integrates with aws-java-sdk-core version 1.11.68.
If we introduce an incompatible change in aws-java-sdk-core 1.11.69-SNAPSHOT, it will not be discovered during the CI run because all other modules using version 1.11.68.
Do you know what is the reason, not to use the same version for all modules which are build and shipped during the development? Or do I miss something?

Thanks,
Christian

**Comment by kiiadi** [comment]
That makes sense to me, not sure why we're not testing our modules against the SNAPSHOT versions of each other.

I'll make the change to our pom generation.

Good catch thanks!

**Comment by muellerc** [comment]
Hi Kyle,

thanks.
Do you have any point for me where the pom generation is described? I'm wondering how it works because it means, we have checked in generated code - which is a bed smell in my eyes... ;-) I'm just curious...

Thanks,
Christian

**Comment by kiiadi** [comment]
@muellerc main reason for checking in both the generated and actual source is so that we can easily see the whole project in a single place (github is really easy to search !). I agree it's something that is a bit frustrating for people wanting to contribute it and we're looking for alternatives for our next version of the SDK. Any ideas would be great!

**Comment by muellerc** [comment]
@kiiadi that's unfortunately true for contributors. Also, at least it looks so for me, all merges are done on the AWS side and only pushed to GitHub, when a new release went out. That's also not optimal for contributing but your speed for publishing new releases is impressive.
I will join AWS in 6 weeks and hopefully get a better inside how the generation process works, why it's necessary and all the other things. May we can create ideas how to improve it...
For now, if all modules are using the same version, it's a good improvement from my point of view.
And thanks again for your time.

**Comment by muellerc** [comment]
Closing the issue after the pull request was merged into the master branch (and already released).
