### ISSUE TITLE
calls to aws rest api may have side-effect of writing to System.err

### ISSUE THREAD

**Issue by davidmoten** [aws/aws-sdk-java#952]
When attempting to read messages from a queue using aws-sdk any message returned is parsed for xml content. When we experience an internet outage we can get any old crap back from our corporate internet gateway saying that an outbound connection (the call to the aws rest api) timed out. Xml parsing is attempted and an error is thrown which we trap and then retry. All good so far.  

The trouble is that this particular scenario can bring about messages written to `System.err` before the error is thrown. This is because the sun xerces parser (when running on say Oracle JDK) that is used by the sdk has a fatal error in parsing and writes the error to `System.err`. Our application containers map `System.err` to log lines of level ERROR/SEVERE and our monitoring goes off. I don't know what other JDKs do.

Overriding xerces logging behaviour seems tricky so I thought I'd see if I can make this a problem to be solved by the team here seeing as calls to the aws rest api using the aws sdk can have annoying side effects (in terms of output on `System.err`).

Below is a little test that shows the log line appearing. It occurs because `loose.dtd` is malformed (!).

```java
import java.io.IOException;
import javax.xml.parsers.ParserConfigurationException;
import org.junit.Test;
import org.xml.sax.SAXException;
import com.amazonaws.util.XpathUtils;
import au.gov.amsa.util.net.AmsaConstants;

public class ErrorTest {

    @Test
    public void testXPathUtilsErrorLogging()
            throws SAXException, IOException, ParserConfigurationException {
        XpathUtils.documentFrom("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n"
                + "\"http://www.w3.org/TR/html4/loose.dtd\">\n" + "<html>\n");
    }

}
```
System.err looks like:
```
[Fatal Error] loose.dtd:31:3: The declaration for the entity "HTML.Version" must end with '>'.
```

**Comment by muellerc** [comment]
Did you already had a look at https://xerces.apache.org/xerces2-j/faq-dom.html#faq-10?
There is a possibility to register its own ErrorHandler which could ignore this errors.
But to be able to use it, we have to extend XpathUtils first. Not sure whether this is a good idea for a corner case in my eyes...

**Comment by davidmoten** [comment]
Excuse the delay, missed your response due to holidays. Yep register an ErrorHandler but don't expose it as an option in the API, just ensure that nothing gets written to stderr by the current `XpathUtils.documentFrom` method. Does this seem reasonable?

**Comment by davidmoten** [comment]
I modified `XPathUtils.documentFrom` like below and all works as I would like. I stepped through in debug to see what the default error handler does and to see what this one does. In particular I was curious if the `error()` method should throw but the default handler does not so that is reflected below.

If you like I can submit a PR with unit tests.

```java
    /**
     * This method closes the given input stream upon completion.
     */
    public static Document documentFrom(InputStream is)
            throws SAXException, IOException, ParserConfigurationException {
        is = new NamespaceRemovingInputStream(is);
        // DocumentBuilderFactory is not thread safe
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        builder.setErrorHandler(new ErrorHandler() {
            
            @Override
            public void warning(SAXParseException e) throws SAXException {
               //do nothing
            }
            
            @Override
            public void fatalError(SAXParseException e) throws SAXException {
                throw e;
            }
            
            @Override
            public void error(SAXParseException e) throws SAXException {
                // do nothing
            }
        });
        Document doc = builder.parse(is);
        return doc;
    }
```

**Comment by zhangzhx** [comment]
Hi @davidmoten, 

Thanks for bringing up this issue. Personally, I think we should log these warnings and errors by the ErrorHandler for debug use and throw the underlying exception if needed. I will drive this issue to our team and let you know what we think. Please submit a pull request and we are glad to take a look.

**Comment by zhangzhx** [comment]
Sorry missed to see you've already submitted the PR #985 . :)

**Comment by dagnir** [comment]
I'm in favoring of logging the exceptions in the `ErrorHandler` as well

**Comment by zhangzhx** [comment]
This has been fixed and released.
