### ISSUE TITLE
Please consider adding a Client Context for Region

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#956]
Please consider deprecating `setRegion`/`setEndpoint` and adding a default method for either (a) creating a ClientContext based on a region or (b) adding a `setRegion` to the default `AmazonWebServiceRequest`. Both will allow regions to be used with clients in a thread-safe way. 

Option (a) might look like:
```
  AmazonEC2RegionContext ctx = client.newRegionContext(region);
  ctx.describeInstances();
```
You could make a new AmazonRegionalEC2 that is just like AmazonEC2 but without the setRegion method (or setEnpoint for that matter). AmazonEC2 could extend the AmazonFixedRegionEC2 interface.  The result is that the context would be immutable and thread-safe. The client would become more of a factory even though it would retain client requests methods for backwards compatibility.  `setRegion` or `setEndpoint` would just create an _internal_ context instance that is delegated to (but really those methods should just be deprecated). 

Option (b) would be simple, but harder to reason about your connection pools. But I suppose you could have a map of pools by endpoint.  If the user wants to work with multiple region then they just put the region in the request the same way they do now for different Credentials Providers.

**Comment by dagnir** [comment]
Sorry for the late reply on this one! `ClientContext` is a nice idea! But I think changing the way customers interact with the SDK (for v1) at this point would not be good, and would also require lots of work in the code generator. We did recently [deprecate `setRegion` on clients](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#aws-sdk-for-java) in favor of using the builders which is a step in the right direction. I'm not sure on option (b) as that would be another way to set region which would just compound the issue I think, especially if `setRegion` is still on the clients (deprecated or not). We'll have a focus on stronger immutability in the next iteration of the SDK and we'll keep this suggestion in mind.

**Comment by dagnir** [comment]
Going to go ahead and close this as we won't be implementing this feature in v1. As I said, we're working on v2 so this will be something we consider going forward.
