### ISSUE TITLE
Add API to give indication where the caller has permission to perform the action

### ISSUE THREAD

**Issue by yairzaslavsky** [aws/aws-sdk-java#958]
We would like to write a health check to our system to check our various AWS resources, and one of the things we would like to check is whether the credentials the app is running with can perform certain actions.

Example for such usage may be:

`AmazonS3Client client = ..... ///get your s3 client somehow
if (client.canPerformPutObject()) {
   client.putObject(..... );
}`

**Comment by yairzaslavsky** [comment]
I saw there is a Policy class, but not sure if this is the correct thing to use?

[http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/policy/Policy.html](url)


and if so, a helper class around that can help developers (Something that will get the current principal, compare it to the principal and compare it to the proper principal object that is associated with an object?)

**Comment by shorea** [comment]
The policy class is an API to build policy JSON documents, not evaluating policies to check permissions. As far as I know there is no such client side API. I'm not even sure if there is a way to go from credentials to the policy that will be used. 

Would it work for your use case to try the action and handle the access denied exception?

**Comment by yairzaslavsky** [comment]
@shorea  thanks for your quick response.
I am aware of the AccessDeniedException.
I think it would be nice if we can check permissions without relying on exceptions.

**Comment by shorea** [comment]
IAM policies can be quite complex so that would be a big undertaking and always runs the risk of not matching the service side evaluation of policies. I think for now making the service call and handling the access denied exception is your best bet.

**Comment by yairzaslavsky** [comment]
Thanks for explaining,
@shorea .

I understand the limitations.
