### ISSUE TITLE
Getting Exception while running Rekognition sample

### ISSUE THREAD

**Issue by rakeshkeerthi** [aws/aws-sdk-java#969]
Hi,

 I'm not sure if this is a bug or problem from my end.

Below is my code.

```
import com.amazonaws.services.rekognition.AmazonRekognitionClient;
import com.amazonaws.AmazonClientException;
import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.services.rekognition.model.AmazonRekognitionException;
import com.amazonaws.services.rekognition.model.DetectLabelsRequest;
import com.amazonaws.services.rekognition.model.DetectLabelsResult;
import com.amazonaws.services.rekognition.model.Image;
import com.amazonaws.services.rekognition.model.S3Object;
import com.fasterxml.jackson.databind.ObjectMapper;

public class DetectLabelsExample {
	public static void main(String[] args) throws Exception {

		AWSCredentials credentials;
		try {
			credentials = new ProfileCredentialsProvider("adminuser").getCredentials();
		} catch (Exception e) {
			throw new AmazonClientException("Cannot load the credentials from the credential profiles file. "
					+ "Please make sure that your credentials file is at the correct "
					+ "location (C:\\Users\\rakesh.keerthi\\.aws\\credentials), and is in a valid format.", e);
		}

		DetectLabelsRequest request = new DetectLabelsRequest()
				.withImage(new Image().withS3Object(
						new S3Object().withName("fe9f77d1b489d66b9ee9cc60e1af6205").withBucket("imagesbucketsample")))
				.withMaxLabels(10).withMinConfidence(77F);

		AmazonRekognitionClient rekognitionClient = new AmazonRekognitionClient(credentials)
				.withEndpoint("sts.amazonaws.com");
		rekognitionClient.setSignerRegionOverride("Global");
		try {
			DetectLabelsResult result = rekognitionClient.detectLabels(request);
			ObjectMapper objectMapper = new ObjectMapper();
			System.out.println("Result = " + objectMapper.writeValueAsString(result));
		} catch (AmazonRekognitionException e) {
			e.printStackTrace();
		}

	}
}
```

Here when I try to run this code, I get the below Exception.

> Jan 03, 2017 11:54:55 PM com.amazonaws.protocol.json.JsonContent parseJsonContent
> INFO: Unable to parse HTTP response content
> com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
>  at [Source: [B@5524cca1; line: 1, column: 1]
> 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
> 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2294)
> 	at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72)
> 	at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64)
> 	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54)
> 	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
> 	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
> 	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
> 	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
> 	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1568)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
> 	at com.amazonaws.services.rekognition.AmazonRekognitionClient.doInvoke(AmazonRekognitionClient.java:1131)
> 	at com.amazonaws.services.rekognition.AmazonRekognitionClient.invoke(AmazonRekognitionClient.java:1107)
> 	at com.amazonaws.services.rekognition.AmazonRekognitionClient.detectLabels(AmazonRekognitionClient.java:708)
> 	at DetectLabelsExample.main(DetectLabelsExample.java:33)
> 
> com.amazonaws.services.rekognition.model.AmazonRekognitionException: null (Service: AmazonRekognition; Status Code: 302; Error Code: null; Request ID: ecb6846a-d1e1-11e6-a2c1-b78364be2bef)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
> 	at com.amazonaws.services.rekognition.AmazonRekognitionClient.doInvoke(AmazonRekognitionClient.java:1131)
> 	at com.amazonaws.services.rekognition.AmazonRekognitionClient.invoke(AmazonRekognitionClient.java:1107)
> 	at com.amazonaws.services.rekognition.AmazonRekognitionClient.detectLabels(AmazonRekognitionClient.java:708)
> 	at DetectLabelsExample.main(DetectLabelsExample.java:33)
> 

In my S3 Console I've a bucket named `imagesbucketsample`, and inside this bucket, I've a file named `	fe9f77d1b489d66b9ee9cc60e1af6205.jpg`, and I'm trying to get what is in that image, but instead of giving me the result back, it gives me an Exception. The Image that I used is [here](https://www.google.co.in/imgres?imgurl=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2F736x%2Ffe%2F9f%2F77%2Ffe9f77d1b489d66b9ee9cc60e1af6205.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fexplore%2Fexotic-flowers%2F&docid=OBqfjyqGjNUAxM&tbnid=-q27K0Fg4ODhBM%3A&vet=1&w=554&h=739&bih=591&biw=1280&q=flowers&ved=0ahUKEwjb2JDQzqbRAhUDT48KHcdfBNUQMwhRKBYwFg&iact=mrc&uact=8). Please let me know where am I going wrong and how can I fix this.

Thanks

**Comment by kiiadi** [comment]
Is there a reason you're setting the endpoint on the Rekognition client to an sts endpoint? That's probably the source of the problem, the client is expecting a Rekognition service at the end of the end point, rather than STS.

**Comment by rakeshkeerthi** [comment]
Thanks for the quick response @kiiadi, Can you please help me on how can I set up this Rekognition end point? I'm completely new to this. :-(

**Comment by kiiadi** [comment]
do you need to explicitly set the endpoint? You can just do `setRegion(RegionUtils.getRegion("us-east-1"));`
