### ISSUE TITLE
Unable to get the md5 of an S3Object after performing a multi part upload

### ISSUE THREAD

**Issue by sgarg-symphy** [aws/aws-sdk-java#970]
I am trying to perform a multi part upload by following the documentation here. Once the upload succeeds I try to download the object
s3Object = s3Client.getObject(bucketName, key); String md5=s3Object.getObjectMetadata().getContentMD5();

However md5 is null...I looked at the objectMetadata but it does not have the Content-Md5 set in it.How can I get the Md5 ?

**Comment by muellerc** [comment]
Can you share your complete code so that's easier to reproduce the issue?

**Comment by sgarg-symphy** [comment]
@muellerc :
the multipart upload happens exactly as documented [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/llJavaUploadFile.html). When constructing the UploadPartRequest I also added the objectMetaData using the withObjectMetadata clause:

`
ObjectMetaData objectMetadata=new ObjectMetaData();
objectMetadata.setContentMd5(<128 bit Base 64 encoded Md5>);
 UploadPartRequest uploadRequest = new UploadPartRequest()
            .withBucketName(existingBucketName).withKey(keyName)
            .withUploadId(initResponse.getUploadId()).withPartNumber(i)
            .withFileOffset(filePosition)
            .withFile(file)
            .withPartSize(partSize).withObjectMetaData(objectMetadata);
`
Once the object is uploaded, I retrieve it using 
`  s3Object = s3Client.getObject(bucketName, key); 
`
and try to get the md5 using
`
String md5=s3Object.getObjectMetadata().getContentMD5();
`
the md5 is null.. When I checked the objectMetaData returned as part of the s3Object it does not have the Content-MD5 key set .

**Comment by sgarg-symphy** [comment]
i uploaded the entire file as a single part...

**Comment by manikandanrs** [comment]
@sgarg-symphy The MD5 being passed in UploadPartRquest is for the part of the object being uploaded. S3 does not combine your parts on the service side. It stores your object as a collection of parts. So, MD5 is not computed for the entire object.

The getObject that are you calling is on the entire object and not on the individual part.

**Comment by sgarg-symphy** [comment]
@manikandanrs ok that makes sense...however the question remains..when I do a getObject from S3 how do I get the MD5 then?

**Comment by manikandanrs** [comment]
@sgarg-symphy ETag is the header that you are looking for. However please note, they are not available in all cases; especially when an object is uploaded via Multi part upload. This [link](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) should give you information about cases this header has a value.

**Comment by sgarg-symphy** [comment]
@manikandanrs I did look at that page but it says: "
If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption."

**Comment by manikandanrs** [comment]
I believe in case of multipart upload it is "-"

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L269-L271

**Comment by sgarg-symphy** [comment]
@manikandanrs so are u saying the code and the documentation are out of sync? and the eTag is actually the Md5 digest?

**Comment by manikandanrs** [comment]
@sgarg-symphy Sorry for not being clear. 

What I meant was, there is no MD5 of the entire object when the object is uploaded using Multiparts. Hence the reason the service sends a "-" in the ETag header. I believe the API documentation clearly says that ETAG is **not** an MD5 digest.

**Comment by sgarg-symphy** [comment]
so once I opt for multi part upload there is no way I can get the MD5 digest from S3?

**Comment by manikandanrs** [comment]
If you are requesting for an entire object then yes. But If you download the parts, then you should get the MD5 of the part in the ETag header. I just tested this with the sample code

        final AmazonS3Client client = new AmazonS3Client();
        final TransferManager tm = TransferManagerBuilder.standard()
                .withS3Client(client)
                .withMultipartUploadThreshold(5L *Constants.MB).build();

        final String bucketName = ...;
        final String key = "largerThan5MB";
        Upload upload = tm.upload(new PutObjectRequest(bucketName, key, new File
                (...)));

        upload.waitForCompletion();

        S3Object s3Object = client.getObject(new GetObjectRequest(bucketName, key).withPartNumber(1));
        System.out.println("ETAG for first part >> " + s3Object.getObjectMetadata().getETag());
        System.out.println("part length >> " + `s3Object.getObjectMetadata().getContentLength());`

**Comment by sgarg-symphy** [comment]
@manikandanrs if my entire object is uploaded as 1 part and subsequently I am trying to download the entire object ( which essentially is 1 part ) then etag becomes the MD5 digest?

**Comment by manikandanrs** [comment]
Yes. But why would you want to use part requests in that case ? You can directly use PutObject and GetObject. 

Also what is the use case behind MD5 ? If its basic MD5 validation, the the SDK does the MD5 validation for you when you use TransferManager to upload and download.

**Comment by sgarg-symphy** [comment]
so I am not using the TransferManager for the Upload.. I am using the multi part upload low level java api's as documented [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/llJavaUploadFile.html) . The scenario behind MD5 is .. once I have downloaded the object I want to check if the Md5 is the same as the time when I uploaded it to S3 using the multi part approach.

**Comment by manikandanrs** [comment]
You can use PutObject and GetObject from the low level S3 client. It should take care of the MD5 validation for you.

**Comment by manikandanrs** [comment]
SDK performs MD5 validation for you on the first case as per the [link](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html)

**Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.**
