### ISSUE TITLE
DynamoDB: BatchWriterItemOutcome#getUnprocessedItems Should never be null

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#972]
It seems like there are some cases where calling `getUnprocessedItems` can return `null` instead of an empty `Map`.  This is some kind of rare issue, after months of continuous running I have only seen a `NullPointerException` once when trying to call `size` on the result of `getUnprocessedItems`. 
```
           BatchWriteItemOutcome result = db.batchWriteItem(batchRequest);
            while (result.getUnprocessedItems().size() > 0) {
                result = db.batchWriteItemUnprocessed(result.getUnprocessedItems());
            }
 ```
A quick look at the code didn't reveal where the bug might be occurring.  I'm thinking some error condition may be preventing line 53 in `BatchWriteItemResultJsonUnmarshaller.java` from being evaluated correctly but without propagating the original exception.

**Comment by rdifalco** [comment]
Also, I think it's impossible to know if I should retry the operation or know that the operation succeeded if `#getUnprocessedItems` returns null.

**Comment by shorea** [comment]
@rdifalco sorry for the lack of response. This sounds like it may be a service issue. Are you still running into this from time to time? If so would it be possible to capture request ids of affected responses?

**Comment by rdifalco** [comment]
@shorea I've coded around it for now so I'm not sure if it's recurring. It's not a huge issue for me, just feel that it should never be null regardless of what state the service is in. I just added a null check.
```
            while (result.getUnprocessedItems() != null && result.getUnprocessedItems().size() > 0) {
```
But I would prefer if that field (and really all collection fields in any result) would default to Collections.emptyMap() or some such.

**Comment by shorea** [comment]
Closing this issue for now. If it comes up again could you capture request ids so we can send it to the service team for investigation. Looking at the code the only time this would be null is if the service sends back null.
