### ISSUE TITLE
Remove usage of org.apache.http.annotation.NotThreadSafe

### ISSUE THREAD

**Issue by GuiForget** [aws/aws-sdk-java#973]
There is a handful of classes which uses this class which has been removed abruptly from httpcore-4.4.5. 

https://github.com/aws/aws-sdk-java/search?utf8=%E2%9C%93&q=org.apache.http.annotation.NotThreadSafe

**Comment by varunnvs92** [comment]
Is there any release notes/docs says why both ThreadSafe and NotThreadSage are removed.

If not, an issue should be opened to add them back.

**Comment by fernomac** [comment]
https://issues.apache.org/jira/browse/HTTPCLIENT-1743

**Comment by shorea** [comment]
All references to the Apache versions have been removed from our code base.
