### ISSUE TITLE
ListPrincipalPolicies model JSON incorrectly specifies all arguments are optional

### ISSUE THREAD

**Issue by lvh** [aws/aws-sdk-java#976]
Ostensibly, this API call always takes a principal. It also has a "marker" which is a string; perhaps it's possible to call it with just a marker (because the markers are somehow unique identifiers).

**Comment by zhangzhx** [comment]
The **principal** parameter is still needed. AFAIK, the marker is specific to the API call with the specific parameters. It is generated from the parameter list. Therefore, you must specify the same parameter list for the next API call.

**Comment by lvh** [comment]
Gotcha. I was hedging against the call not mentioning the required `principal` parameter because the way you express required parameters doesn't let you say "you need a principal XOR a parameter".

**Comment by lvh** [comment]
Has this issue been resolved? The model JSON is still broken in master, it appears.

**Comment by zhangzhx** [comment]
This parameter is marked as **required** though in the model. See

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-iot/src/main/resources/models/iot-2015-05-28-model.json#L10194

And I have the same question to #977 as the **TableName** is marked **required** as well. That's why I closed this issue. But if this is not the answer you are seeking, feel free to reopen it.

**Comment by lvh** [comment]
You're right! I figured out what was wrong. I was using the class to find its parent JAR, and then find the JSON files wtihin that JAR. I assumed there'd be exactly one (since there's no obvious canonical mapping from class name to). But that's not true! dynamodb (#977) and iot (this ticket) are special in that they contain not one but two JSONs/clients per JAR (`data.iot` and `iot`, `streams.dynamodb` and `dynamodb`). Because of the order these files occur in the JAR, these models were getting picked up first. So my code was, uh "correctly" reporting that there are no required arguments for anything called `ListPrincipalPoliciesRequest` because there is no such thing as s `ListPrincipalPoliciesRequest` in `data.iot`.

This is entirely my bad. Sorry!
