### ISSUE TITLE
dynamodbv2's DescribeTable model JSON incorrectly specifies all arguments are optional

### ISSUE THREAD

**Issue by lvh** [aws/aws-sdk-java#977]
Any attempt to call it without a table name fails.

> com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The parameter 'TableName' is required but was not present in the request (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ~REDACTED~)

**Comment by zhangzhx** [comment]
Hi Ivh,

It is an intended behavior. The Java SDK doesn't do client side validation. The table name is a required parameter. You can

**Comment by lvh** [comment]
@zhangzhx It appears half your comment went missing.

**Comment by lvh** [comment]
Oops; it's there now. I understand that the client does not do validation; I am saying the _model JSON_ that ships with the client incorrectly does not specify it as required.

**Comment by zhangzhx** [comment]
Not sure if I follow, but do you mean _model JSON_ what is actually sent to the wire? Or are you saying it's a documentation issue?

**Comment by lvh** [comment]
No, the JSON describing the API: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-models/src/main/resources/models/dynamodb-2012-08-10-model.json

**Comment by shorea** [comment]
@zhangzhx see https://github.com/aws/aws-sdk-java/issues/965. This would require the service team to update their service model with the required trait.

**Comment by zhangzhx** [comment]
@lvh I see your point. But for **DescribeTable**, the **TableName** parameter is marked as required though. See

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-models/src/main/resources/models/dynamodb-2012-08-10-model.json#L2671

**Comment by lvh** [comment]
Turns out this is a false positive. Explanation: https://github.com/aws/aws-sdk-java/issues/976#issuecomment-272044727

Sorry!
