### ISSUE TITLE
Considering switching to Apache HttpAsyncClient?

### ISSUE THREAD

**Issue by HaloFour** [aws/aws-sdk-java#989]
Sorry if this is a dupe, I poked through the existing issues and didn't see other real mentions of "async" or "NIO".

Currently all of the AWS clients based on AmazonWebService using Apache HttpClient which is synchronous and blocking.  The asynchronous versions of the clients rely on an `ExecutorService` to spin up separate threads which block for the duration of the request.  Given that Apache also has HttpAsyncClient which is NIO-based and very similar in design to HttpClient has any consideration been given to porting to it?  That way asynchronous calls would be truly asynchronous.

I understand that this would be an undertaking.  The configuration of HttpAsyncClient is quite different from that of HttpClient, which would likely cause breaking changes (or awkward adapters).  But I think that most of the details of the requests and handling the responses asynchronously could be abstracted away from current consumers of the client interfaces.

**Comment by varunnvs92** [comment]
I will add it to our backlog. As you said it may cause breaking changes, we can't introduce this feature in our current major version (1.11.x).

**Comment by varunnvs92** [comment]
Actually, we have it in our priority backlog for this year. We don't have the timeline yet. I will update the issue if there are any changes.

**Comment by HaloFour** [comment]
That's awesome news.  I'd love to contribute if I can.

**Comment by shorea** [comment]
Will leave this issue open until we have a repo to share for the V2 SDK.

**Comment by shorea** [comment]
We just launched a Developer Preview of AWS SDK for Java 2.0 that adds support for this feature request. Try it out and let us know what you think!

https://github.com/aws/aws-sdk-java-v2
http://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html
https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/

PS we are using a Netty based implementation as our default non-blocking HTTP client but we do support pluggable HTTP as well.
