### ISSUE TITLE
DynamoDBMapper batchDelete does not respect optimistic locking.

### ISSUE THREAD

**Issue by newports123** [aws/aws-sdk-java#990]
I have noticed that I am able to get around optimistic locking when using the batchDelete method.  Version number is respected in the batchSave method and the delete method but not in the batchDelete method.  Is this intentional?

**Comment by varunnvs92** [comment]
What is the version of the SDK used? Can you give me a test case to reproduce the issue?

**Comment by newports123** [comment]
Here is a sloppy example I threw together.  This is using the latest version of the SDK.
[BugExample.txt](https://github.com/aws/aws-sdk-java/files/720257/BugExample.txt)

**Comment by newports123** [comment]
Any update on this?  Is there anything else I can provide to help?

**Comment by varunnvs92** [comment]
This is the current behavior of the Mapper and not a bug. It is explicitly mentioned in the mapper javadoc.
[BatchSave](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.java#L243-L250 )
[BatchDelete](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/IDynamoDBMapper.java#L226-L227)

Reason:
In you look at [PutItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#API_PutItem_RequestSyntax), the request parameters include ConditionExpressions which is sent by the Mapper. Whereas in [BatchWrite](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html#API_BatchWriteItem_RequestSyntax), we can send only the items but not additional condition expressions. This is why batch operations don't respect optimistic locking
