### ISSUE TITLE
Workspaces creation date

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#993]
Hi 
is there is any way to get the creation data for certain workspace (and WorkspaceBundle too)?

**Comment by varunnvs92** [comment]
I don't see an API for it. The CreateWorkspaces result don't have a creationDate field. 

I have raised an internal ticket to the service team about this issue. I will get back to you as soon as they respond. Thanks.

**Comment by varunnvs92** [comment]
Service team replied that creation date info is not available using APIs or console. They don't have any plans for adding that feature yet. 

You can check the "What's New from Amazon WorkSpaces" in this [link](https://aws.amazon.com/workspaces/) for latest workspaces announcements. Thank you.

**Comment by youssemn** [comment]
Any update for this topic ?
