### ISSUE TITLE
UploadPartRequest partSize is a required field, but not listed in comments or properly validated

### ISSUE THREAD

**Issue by landon9720** [aws/aws-sdk-java#995]
The comment at the top of `UploadPartRequest.java` does not list `partSize` as a required field.

If `partSize` is not set, `AmazonS3Client#uploadPart` should fail. The current implementation is incorrect because it checks that `partSize` is not null, however `partSize` is a primitive long and therefore is never null.

**Comment by kiiadi** [comment]
@landon9720 I've switched the underlying datatypes to their boxed equivalents and updated the validation to use those. I've also updated the comment at the top. Should be out in our next release.

**Comment by kiiadi** [comment]
@landon9720 thinking more about this, I'm not sure that we can do this validation without it being backwards incompatible. Currently, if you do not supply partSize on the UploadPart the request will succeed - the part that's uploaded will be zero bytes long. Whilst this might be undesired there may be customers relying on this behaviour. I think we have to leave it as it is for now; I agree we might as well remove the validation.

**Comment by kayvonr** [comment]
Would it be possible to have them boxed but still accept 0 as a value? That was forces people to explicitly set to 0 if they want, otherwise errors out if someone omits it. Does not matter for me anymore, I know now that I need it, just thinking of people using in the future.

**Comment by shorea** [comment]
@kayvonr I believe that might also be considered a breaking change if customers are implicitly relying on zero being the default.
