### ISSUE TITLE
TransferManagerBuilder lacks ability to configure 'setDisableParallelDownloads'

### ISSUE THREAD

**Issue by NikolayAtSony** [aws/aws-sdk-java#996]
TransferManagerConfiguration tmConfig = new TransferManagerConfiguration();
        // Disable parallel downloads for TransferManager
        tmConfig.setDisableParallelDownloads(true);
        transferManager = TransferManagerBuilder.standard().build();
        transferManager.setConfiguration(tmConfig);

Warning now: The method setConfiguration(TransferManagerConfiguration) from the type TransferManager is deprecated.

How to pass this setting to TransferManagerBuilder now? It looks like it's not possible now as there is no support for it in TransferManagerBuilder. Please consider adding it or there is no way to stop using now deprecated setConfiguration method.

**Comment by kiiadi** [comment]
@NikolayAtSony oops! That was a miss when applied the deprecation, I've added to the `TransferManagerBuilder` and it should be out in our next release (most likely tomorrow 1/26).

**Comment by kiiadi** [comment]
This has now been added to the transfer manager builder: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManagerBuilder.java#L400
