### ISSUE TITLE
No builder for AmazonS3Encryption similar to all other available builders

### ISSUE THREAD

**Issue by NikolayAtSony** [aws/aws-sdk-java#997]
There is no builder for AmazonS3Encryption similar to AmazonS3ClientBuilder or AmazonCloudWatchClientBuilder,  etc.

At the same time, syntax like new AmazonS3EncryptionClient(credentialsProvider.getCredentials(), encryptionMaterials, config, crypto).withRegion(region); gives a warning:

The method withRegion(Region) from the type AmazonWebServiceClient is deprecated. Which implies  use {@link AwsClientBuilder#withRegion(Region)} for example:
     * {@code AmazonSNSClientBuilder.standard().withRegion(region).build();}

But, there is no such builder for S3 Encrypted client exists. Please advice what is the plan here.

**Comment by kiiadi** [comment]
@NikolayAtSony I'll look to add a builder for the encrypted S3 client.

**Comment by kiiadi** [comment]
Builder added in 1.11.86 https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3EncryptionClientBuilder.java
