### ISSUE TITLE
Allow cloudsearch POST requests

### ISSUE THREAD

**Issue by daskruegge** [aws/aws-sdk-java#998]
CloudSearch has the ability to handle POST requests for cases when the GET calls would result in a too long URI. Unfortunately, when using the AmazonCloudSearchDomainClient, the HTTP method is set to GET here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudsearch/src/main/java/com/amazonaws/services/cloudsearchdomain/model/transform/SearchRequestMarshaller.java#L50 

Would it be possible to allow setting the HTTP method with a parameter on the search request?

That would be great. 

Thanks
Nils

**Comment by shorea** [comment]
We should be using POST now. Are you using the latest version of the SDK?

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudsearch/src/main/java/com/amazonaws/services/cloudsearchdomain/SwitchToPostHandler.java

**Comment by daskruegge** [comment]
You are right. It is a POST now. Since it is kind of "hidden" by overwriting GET to POST under the hood I did not notice the update. Closing this.

Thanks

**Comment by phuonglviet** [comment]
Please tell me how to use with SwitchToPostHandler to Httpmethod POST with AmazonCloudSearchDomainClientBuilder

Thanks!
