### ISSUE TITLE
AWS Kinesis: Jackson error when processing PutRecord request

### ISSUE THREAD

**Issue by joeyvmason** [aws/aws-sdk-java#999]
When I attempt to make a PutRecord request to AWS Kinesis, I am getting this error: `com.amazonaws.SdkClientException: Unable to marshall request to JSON`. It happens not matter what data I send (I've also tried sending an empty byte array). I thought that it might have to do with which version of Jackson I am using locally, but not sure Jackson 2.5.0, but have since updated to 2.8.6 and am still getting the error.

Sample code:

```
ObjectMapper JSON = new ObjectMapper();
JSON.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

PutRecordRequest putRecord = new PutRecordRequest();
putRecord.setData(ByteBuffer.wrap(JSON.writeValueAsBytes("FizzBuzz)));
putRecord.setStreamName("example");
putRecord.setPartitionKey("foo");

amazonKinesisClient.putRecord(putRecord);
```

Stack trace:

```
com.amazonaws.SdkClientException: Unable to marshall request to JSON: com.fasterxml.jackson.dataformat.cbor.CBORGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;

	at com.amazonaws.services.kinesis.model.transform.PutRecordRequestMarshaller.marshall(PutRecordRequestMarshaller.java:81)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecord(AmazonKinesisClient.java:1387)
        at com.joeyvmason.test.KinesisTest.test1(KinesisTest.java:93)
```

**Comment by shorea** [comment]
Looks like you are using an older version of CBOR with a new version of jackson core. There was a breaking change in Jackson Core regarding the getOutputContext method. Using a consistent version of the CBOR module along with Jackson Core should fix the issue.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/pom.xml#L38-L44
